dev-packages/browser-integration-tests/suites/replay/canvas/manualSnapshot/test.ts
dev-packages/browser-integration-tests/suites/replay/canvas/records/test.ts
packages/replay-canvas/package.json
packages/replay-canvas/src/canvas.ts
packages/replay-canvas/test/canvas.test.ts
packages/replay-internal/package.json
yarn.lock

We do not want to allow users to capture super large canvases, enforce a max size limit
Requires https://github.com/getsentry/rrweb/pull/174
Closes https://github.com/getsentry/sentry-javascript/issues/10498

feat(replay): Add "maxCanvasSize" option for replay canvases

---

packages/google-cloud-serverless/src/gcpfunction/cloud_events.ts
packages/google-cloud-serverless/test/gcpfunction/cloud_event.test.ts

Closes #9044
Adds relevant tests for testing handlers that return promises.

fix(serverless): Check if cloud event callback is a function (#9044)

---

dev-packages/browser-integration-tests/suites/integrations/lazyLoad/validIntegrationNpm/init.js
dev-packages/browser-integration-tests/suites/integrations/lazyLoad/validIntegrationNpm/subject.js
dev-packages/browser-integration-tests/suites/integrations/lazyLoad/validIntegrationNpm/test.ts
packages/browser/src/utils/lazyLoadIntegration.ts
packages/browser/test/unit/utils/lazyLoadIntegration.test.ts

As noticed by @ryan953 here: https://github.com/getsentry/sentry-javascript/pull/11621#issuecomment-2063028064, this was not actually working properly in NPM-mode. I added a proper test for this and fixed this, so hopefully should be all good now.

fix(browser): Ensure `lazyLoadIntegration` works in NPM mode

---

packages/serverless/src/gcpfunction/cloud_events.ts
packages/serverless/test/gcpfunction.test.ts

Backport of https://github.com/getsentry/sentry-javascript/pull/11701 to v7

fix(serverless): [v7] Check if cloud event callback is a function

---

CHANGELOG.md

Closes https://github.com/getsentry/sentry-javascript/issues/11729

meta(changelog): Update changelog for v7.112.0

---

packages/nextjs/package.json
packages/node/package.json
yarn.lock

Bumping the package to `0.50.0` in https://github.com/getsentry/sentry-javascript/pull/11725 seems to have broken the Next.js 13 E2E tests.
This PR reverts the bump until we have figured out what caused the failures.

deps: Downgrade `@opentelemetry/instrumentation-http` to `0.48.0`

---

MIGRATION.md

"...which is a dependency of the SvelteKit SDK" could also be understood as "you need this as additional dependency"

docs(sveltekit): Vite plugin rewording

---

packages/ember/addon/instance-initializers/sentry-performance.ts

Backport of https://github.com/getsentry/sentry-javascript/pull/11749

fix(ember/v7): Do not create rendering spans without transaction

---

.github/workflows/build.yml

ci: Run e2e tests for dependabot PRs

---

dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/navigation/test.ts
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/pageload-meta/test.ts
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/pageload/test.ts
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/tracing-without-performance/test.ts
packages/core/src/server-runtime-client.ts
packages/core/src/tracing/sentrySpan.ts
packages/core/src/utils/applyScopeDataToEvent.ts
packages/core/src/utils/spanUtils.ts
packages/core/test/lib/tracing/sentrySpan.test.ts

Today, we have different behavior for the `trace` context in core/browser & node:
In Node, we made the change so that `contexts.trace` only contains `span_id`, `trace_id` and `parent_span_id` for non-transaction events. 
In contrast, in core/browser we are always adding the full span trace context, if there is an active span (including e.g. data, status, etc.) 
This PR aligns this to use the node behavior everywhere.
Transaction events are unchanged by this PR.

feat(core): Ensure trace context only includes relevant data

---

packages/ember/addon/instance-initializers/sentry-performance.ts

This was brought up in discord - we forgot to add `onlyIfParent` to the ui spans we emit for ember, so it's possible to capture a bunch of them as transactions, accidentally.

fix(ember): Do not create rendering spans without transaction

---

packages/browser/src/tracing/browserTracingIntegration.ts

The primary change is to make `finalStartSpanOptions.name !== finalStartSpanOptions.name` -> `startSpanOptions.name !== finalStartSpanOptions.name` in `packages/browser/src/tracing/browserTracingIntegration.ts`.
While I was here though I cleaned up some other code to improve bundle size. Let me know if you want me to extract the cleanup changes, I figured it's all easier to review here with the same context.

fix(browser): Set custom sentry source correctly

---

packages/core/src/transports/base.ts

Nowadays, the SDK simply sends more data and we are seeing overflows in our E2E tests which do not produce an unreasonable amount of events.
Dropped events can lead to broken traces and confusing data inside Sentry, which is why I think bumping this is reasonable.
We make this under the assumption that an event in the transport holds at max something like 5MB of memory, which would bump the memory consumption from 150MB to 320MB.

feat(core): Increase default transport buffer size from 30 to 64

---

dev-packages/e2e-tests/test-applications/nextjs-14/sentry.client.config.ts
packages/nextjs/src/client/browserTracingIntegration.ts
packages/nextjs/test/clientSdk.test.ts
packages/sveltekit/src/client/browserTracingIntegration.ts
packages/sveltekit/test/client/sdk.test.ts

Turns out the logic to get the options was not correct, because we used the `options` that the integration exposes, but this has `instrumentPageload: false` & `instrumentNavigation: false` because we did not "fix" the `options` we expose on the integration. This was not caught by the tests, because it only happens if passing the `browserTracingIntegration` from `@sentry/nextjs` or `@sentry/sveltekit`, not when passing the "original" one (which we had tests for). 
Really fixes https://github.com/getsentry/sentry-javascript/issues/11627

fix(nextjs|sveltekit/v7): Ensure we can pass `browserTracingIntegration`

---

packages/opentelemetry/src/utils/parseSpanDescription.ts
packages/opentelemetry/test/utils/parseSpanDescription.test.ts

Fixes https://github.com/getsentry/sentry-javascript/issues/11755
OpenTelemetry restructured their http semantic conventions and declared them stable: https://opentelemetry.io/blog/2023/http-conventions-declared-stable/
This has unfortunately not been reflected in OpenTelemetry JS yet, blocked on them making everything backwards compat: https://github.com/open-telemetry/opentelemetry-js/issues/4572
For now we can directly reference `http.request.method`, the replacement to `http.method`. When the OTEL SDK is finally updated to use proper conventions, we can avoid hard coding the string.

feat(opentelemetry): Support new http method attribute

---

packages/angular/src/errorhandler.ts
packages/angular/src/zone.ts

This commit calls `showReportDialog` outside of the Angular context to prevent
unnecessary view updates when asynchronous tasks are set up within the `showReportDialog` function.

fix(angular): call `showReportDialog` in root context

---

packages/remix/src/utils/instrumentServer.ts
packages/remix/src/utils/serverAdapters/express.ts
packages/remix/test/integration/test/server/action.test.ts
packages/remix/test/integration/test/server/loader.test.ts
packages/remix/test/integration/test/server/ssr.test.ts

Ref: https://github.com/getsentry/sentry-javascript/issues/10846
Sets a transaction name on the isolation scope for remix serverside features.

feat(remix): Update scope `transactionName` for Remix server features

---

dev-packages/e2e-tests/test-applications/nextjs-14/tests/generation-functions.test.ts
dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/edge-route.test.ts
dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/edge.test.ts
dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/middleware.test.ts
dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/route-handlers.test.ts
dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/server-components.test.ts
packages/nextjs/src/common/utils/edgeWrapperUtils.ts
packages/nextjs/src/common/utils/wrapperUtils.ts
packages/nextjs/src/common/withServerActionInstrumentation.ts
packages/nextjs/src/common/wrapApiHandlerWithSentry.ts
packages/nextjs/src/common/wrapGenerationFunctionWithSentry.ts
packages/nextjs/src/common/wrapRouteHandlerWithSentry.ts
packages/nextjs/src/common/wrapServerComponentWithSentry.ts
packages/nextjs/test/integration/test/server/errorServerSideProps.test.ts

Ref: https://github.com/getsentry/sentry-javascript/issues/10846
Adds relevant transaction names to isolation scopes in Next.js.

feat(nextjs): Add `transactionName` to isolation scope for Next.js server side features

---

dev-packages/browser-integration-tests/suites/public-api/startSpan/standalone-mixed-transaction/test.ts
dev-packages/browser-integration-tests/suites/public-api/startSpan/standalone/test.ts
packages/core/src/envelope.ts
packages/core/test/lib/envelope.test.ts

based on #11696 
This PR adds a `trace` envelope header to our standalone span envelope creation function.
ref #11562

feat(core): Add `trace` envelope header to span envelope

---

packages/core/src/baseclient.ts
packages/types/src/client.ts

`client.captureException/captureMessage/captureEvent` do not include current scope in events by default. This is in contrast to `captureException/captureMessage/captureEvent` exported from every SDK which include the current scope by default.
This PR changes the parameter names (`scope` > `currentScope`) and adds jsdocs to make this more clear. It also changes the parameters to use the scope interface instead of the scope class.

feat(core): Set default scope for BaseClient methods

---

dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals-inp/test.ts
packages/browser-utils/src/metrics/inp.ts
packages/types/src/envelope.ts

builds on top of #11696 #11699 
This PR refactors how we create INP spans. Previously we'd directly initialize a `SentrySpan` instance with the necessary properties and manually sample the span. Ironically, we heavily discourage directly initializing a `Span` class. 
With this refactor PR, we leverage the `standalone: true` flag introduced in #11696. This way, we can also use the built-in sampling functionality and ensure that we only have one logic for creating standalone span envelopes. Also bundle size should decrease slightly 🤞 
Adjusted the integration tests to more thoroughly test the INP span envelopes

ref(browser): Create standalone INP spans via `startInactiveSpan`

---

packages/core/src/integrations/captureconsole.ts
packages/core/test/lib/integrations/captureconsole.test.ts

I'm seeing a lot of breadcrumbs for `console.assert`s even though they are passing. This issue was previously fixed in #2239 but I guess there was a regression at some point. There was already an existing test case for this, but it was missing an assertion.

fix(core): Capture only failed console.assert calls

---

packages/browser/src/feedback.ts
packages/browser/src/feedbackAsync.ts
packages/feedback/src/core/getFeedback.test.ts
packages/feedback/src/core/getFeedback.ts
packages/feedback/src/core/integration.ts
packages/types/src/integration.ts

Noticed this while bumping sentry itself - the types are wrong today, because we return it as `IntegrationFn` which is just a generic integration with no custom methods.

fix(feedback): Fix feedback type

---

packages/svelte/src/performance.ts

Small refactor; The previous guard also worked but using `onlyIfParent` instead of checking for `getActiveSpan` saves us a couple of bytes

ref(svelte): Use `onlyIfParent` for recording component update spans

---

packages/core/src/exports.ts

Multiple cron jobs can run at the same time and they may run on a server where other work is being performed.
Wrapping the  `withMonitor` callback in `withIsolationScope` ensures that scope and breadcrumbs for the cron tasks remain isolated.

feat(core): Wrap cron `withMonitor` callback in `withIsolationScope`

---

packages/remix/src/utils/instrumentServer.ts

Closes: https://github.com/getsentry/sentry-javascript/issues/11615

fix(remix): Rethrow `loader`, `action` and `documentRequest` errors

---

dev-packages/e2e-tests/test-applications/nextjs-app-dir/assert-build.ts
packages/nextjs/src/config/types.ts
packages/nextjs/src/config/webpack.ts

Currently, Next.js (Webpack) prints an annoying warning about an import statement that cannot be statically analyzed inside `@opentelemetry/instrumentation`. This is annoying (but harmless) and spams the logs **a lot** so we should probably ignore the warning.
More info on the issue in OTEL: https://github.com/open-telemetry/opentelemetry-js/issues/4173
Hopefully this will be fixed in https://github.com/open-telemetry/opentelemetry-js/pull/4660 soon.

feat(nextjs): Mute webpack warnings about critical dependencies inside `@opentelemetry/instrumentation`

---

CHANGELOG.md

quick PR to sync changelogs so I don't have to keep going back and forth.

chore: Update changelog to include latest v7 release

---

MIGRATION.md
dev-packages/e2e-tests/test-applications/create-react-app/src/App.tsx
packages/react/src/errorboundary.tsx
packages/react/test/errorboundary.test.tsx

Fixes https://github.com/getsentry/sentry-javascript/issues/11728
As reporting in the above issue, it is not typesafe to type the error thrown by react components as `Error`, it can actually be any JS object/primitive that was thrown. This means we have to type everything as `unknown`.
This change only will happen for `8.x` because it's a breaking change.
Related: 
- https://react.dev/reference/react/Component#componentdidcatch
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69434

feat(react): type error as unknown in ErrorBoundary

---

CHANGELOG.md
packages/types/src/user.ts

Adds types for `geo` in the user object
https://develop.sentry.dev/sdk/event-payloads/user/

ref: Add geo location types

---

.github/workflows/build.yml

They fail because a secret is missing, we can skip them for dependabot.
See: https://github.com/orgs/community/discussions/26253

ci: Skip cloudflare-astro E2E tests for dependabot

---

packages/feedback/src/constants.ts
packages/feedback/src/widget/Actor.css.ts

Backport of https://github.com/getsentry/sentry-javascript/pull/11641 to v7

feat(feedback): [v7] New feedback button design

---

packages/feedback/src/core/integration.ts

Defaults to having screenshots.

feat(feedback): Have screenshot by default

---

packages/feedback/src/core/integration.ts

This fixes the conditions for loading and rendering the screenshot integration.... also improves the conditions for not rendering it if we're on a mobile device.
- We should check the local`options.showScreenshot` instead of the closed-over `showScreenshot` because the options might have changed for this instance of the widget
- We should combine `options.showScreenshot` (the desire) with `isScreenshotSupported()` (the possibility) to set the right expectation

fix(feedback): Be consistent about whether screenshot should and can render

---

.github/workflows/build.yml
dev-packages/e2e-tests/test-applications/react-router-5/.gitignore
dev-packages/e2e-tests/test-applications/react-router-5/.npmrc
dev-packages/e2e-tests/test-applications/react-router-5/package.json
dev-packages/e2e-tests/test-applications/react-router-5/playwright.config.ts
dev-packages/e2e-tests/test-applications/react-router-5/public/index.html
dev-packages/e2e-tests/test-applications/react-router-5/src/globals.d.ts
dev-packages/e2e-tests/test-applications/react-router-5/src/index.tsx
dev-packages/e2e-tests/test-applications/react-router-5/src/pages/Index.tsx
dev-packages/e2e-tests/test-applications/react-router-5/src/pages/User.tsx
dev-packages/e2e-tests/test-applications/react-router-5/src/react-app-env.d.ts
dev-packages/e2e-tests/test-applications/react-router-5/start-event-proxy.ts
dev-packages/e2e-tests/test-applications/react-router-5/tests/errors.test.ts
dev-packages/e2e-tests/test-applications/react-router-5/tests/transactions.test.ts
dev-packages/e2e-tests/test-applications/react-router-5/tsconfig.json
packages/react/src/reactrouter.tsx

Turns out we were not correctly setting parametrized route names for react router v4/v5 😬 We had no proper test covering this.
So I added a new E2E test `react-router-5` that actually checks that parametrization etc. works as expected.
Fixes https://github.com/getsentry/sentry-javascript/issues/11815

fix(react): Fix react router v4/v5 instrumentation

---

CHANGELOG.md

meta(changelog): Update changelog for 7.113.0

---

packages/core/src/baseclient.ts
packages/core/src/transports/multiplexed.ts
packages/core/test/lib/transports/multiplexed.test.ts
packages/types/src/transport.ts

feat(v7): Add `tunnel` support to multiplexed transport

---

dev-packages/e2e-tests/test-applications/node-nestjs-app/src/main.ts
dev-packages/e2e-tests/test-applications/node-nestjs-app/tests/errors.test.ts
dev-packages/node-integration-tests/suites/tracing/nestjs-errors-no-express/scenario.ts
dev-packages/node-integration-tests/suites/tracing/nestjs-errors/scenario.ts
dev-packages/node-integration-tests/suites/tracing/nestjs-no-express/scenario.ts
packages/node/src/integrations/tracing/nest.ts

This was brought up here https://github.com/getsentry/sentry-javascript/discussions/5578#discussioncomment-9284317,
our error handler implementation was too naive, and our tests not ideal - the tests only checked that stuff is sent to sentry (which it was!) but not that the page otherwise worked.
Now, I updated the test to ensure this works as expected.
With this PR, the signature for `Sentry.setupNestErrorHandler()` changes ( breaking change, but sadly required at this point). You have to pass in an exception filter, which we'll extend to _also_ send exceptions to Sentry:
```js
import { BaseExceptionFilter, HttpAdapterHost } from '@nestjs/core';
const { httpAdapter } = app1.get(HttpAdapterHost);
Sentry.setupNestErrorHandler(app1, new BaseExceptionFilter(httpAdapter));
```
This is a bit …

fix(node): Fix nest.js error handler

---

.github/workflows/build.yml
packages/profiling-node/README.md
packages/profiling-node/binding.gyp
packages/profiling-node/bindings/cpu_profiler.cc
packages/profiling-node/package.json
packages/profiling-node/src/cpu_profiler.ts
yarn.lock

Port from v7: https://github.com/getsentry/sentry-javascript/pull/11754

feat(node): Support Node 22

---

.craft.yml

We want to stop publishing lambda layers for v7, since lambda layer versioning is linear (a number is incremented), and communitcating which layer version corresponds to which SDK version would be impossible.
Also this lets us use very simple logic in Sentry to determine whether we should include `@sentry/serverless` or `@sentry/aws-lambda` within the layer.

build(aws-lambda/v7): Turn off lambda layer publishing

---

MIGRATION.md

https://github.com/getsentry/sentry-javascript/issues/11823 rightfully mentioned that the way we recommend people to init the SDK may crash if there are nodejs specific packages being imported in `instrumentation.ts`.
We could solve this by either changing the way we recommend users to add configuration like so:
```ts
import * as Sentry from '@sentry/nextjs';
export async function register() {
if (process.env.NEXT_RUNTIME === 'nodejs') {
await import('./sentry.server.config.ts');
}
if (process.env.NEXT_RUNTIME === 'edge') {
await import('./sentry.edge.config.ts');
}
}
```
But for now I'd rather keep the base-case simple and add additional explanation for the more complicated case. Maybe we need to switch this up in the future.

docs: Clarify Node.js specific imports in Next.js register hook migration guide

---

packages/angular/src/tracing.ts

This commit updates all tracing functionality to run outside the Angular zone. Before this change, it hindered server-side rendering and hydration, causing instability in the app. The app achieves stability when there are no micro/macro tasks running. As a result, the HTML can now be serialized and sent to the client.

fix(angular): run tracing stuff outside Angular

---

packages/nextjs/src/config/webpack.ts

In theory it is possible that people still have files like `sentry.server.config.ts` and reference them from `instrumentation.ts`. In that case we do not want to show the warning about the old way.

feat(nextjs): Be smarter in warning about old ways of init configuration

---

dev-packages/browser-integration-tests/utils/helpers.ts

For now, to unblock the release - we need to fix this, but today we cannot run them because we try to fetch the modal/screenshot integrations from the CDN for the version that is not yet deployed to the CDN.
In a follow up I'll try to make these tests actually work.

test: Skip feedback tests on CDN

---

packages/nextjs/package.json
packages/node/package.json
yarn.lock

Should resolve some dep-resolving warnings when installing the SDK.

deps(node): Bump `@opentelemetry/instrumentation-http` to version `0.51.0`

---

dev-packages/browser-integration-tests/suites/feedback/captureFeedback/test.ts
dev-packages/browser-integration-tests/suites/feedback/captureFeedbackAndReplay/hasSampling/test.ts
dev-packages/browser-integration-tests/suites/replay/slowClick/windowOpen/test.ts
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/navigation/test.ts
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/pageload-meta/test.ts
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/pageload/test.ts
dev-packages/browser-integration-tests/utils/fixtures.ts
dev-packages/browser-integration-tests/utils/generatePlugin.ts
dev-packages/browser-integration-tests/utils/helpers.ts

This reverts https://github.com/getsentry/sentry-javascript/pull/11888, and ensures the feedback tests actually work on CDN.
For this, we now ensure to serve this locally, so this will work also on release branches. It means you have to use `getLocalTestUrl` instead of `getLocalTestPath` to work. (side note: We can/should probably just remove `getLocalTestPath` overall 🤔 URL based is much more realistic and IMHO better. I'll do that in a follow up, maybe.

test(feedback): Re-add feedback CDN tests

---

packages/react/src/reactrouterv6.tsx

Not a big issue but noticed it when the IDE showed the docs for the function

docs: fix typo in doc for `reactRouterV6BrowserTracingIntegration`

---

packages/node/package.json
packages/opentelemetry/package.json
yarn.lock

As some instrumentation may need higher versions, which we don't want to block there. This shuld be treated more like core etc.
Note that deduping this does not really work nicely, sadly, because this is still experimental (`0.x`) so `^0.50.0` will not match `0.51.0` 😞

build: Bump `@opentelemetry/instrumentation` and relax to `^`

---

dev-packages/node-integration-tests/suites/esm/warn-esm/server.js
dev-packages/node-integration-tests/suites/esm/warn-esm/server.mjs
dev-packages/node-integration-tests/suites/esm/warn-esm/test.ts
dev-packages/node-integration-tests/utils/runner.ts
packages/node/src/sdk/init.ts

This prints a console.warn out if we detect that we are running in ESM mode.

feat(node): Warn if ESM mode is detected

---

package.json
packages/angular/package.json
packages/astro/test/integration/snippets.test.ts
packages/sveltekit/.empty.js
packages/sveltekit/vite.config.ts
yarn.lock

Remove angular dep of 1.4.0 -- I'd like to move replay's tests over to vitest.

dev: Upgrade to use `vitest@1.6.0`

---

packages/node/src/integrations/tracing/koa.ts

This prints a warning if we detect that the koa app passed to setupKoaErrorHandler is not instrumented.
This happens if you import koa before calling Sentry.init.

feat(koa): Warn if koa is not instrumented

---

packages/opentelemetry-node/src/utils/parseOtelSpanDescription.ts
packages/opentelemetry-node/test/spanprocessor.test.ts

fix(opentelemetry-node): support `HTTP_REQUEST_METHOD` attribute

---

packages/node/src/integrations/tracing/hapi/index.ts

feat(hapi): Warn if hapi is not instrumented

---

packages/browser-utils/src/metrics/instrument.ts

Through debugging I found that we were only recording the CLS web vital when we were hiding the tab (so either when switching tabs or when unloading the page).
This is problematic because it result in us not sending CLS values for pageloads at all (or at least with really low probability). We fix this by setting `reportAllChanges: true` which will continuously update the CLS metric before we send it.

fix(browser): Continuously record CLS web vital

---

packages/node/src/integrations/tracing/fastify.ts

When using `setupFastifyErrorHandler(app)` we can check if the app was correctly instrumented.
Not sure how to best test this - I tested this manually in a test app and could verify that the log was printed when requiring fastify before calling init!

feat(fastify): Warn if fastify is not instrumented

---

packages/opentelemetry-node/test/spanprocessor.test.ts
packages/tracing-internal/src/browser/instrument.ts
packages/tracing-internal/src/browser/web-vitals/getCLS.ts

Backports https://github.com/getsentry/sentry-javascript/pull/11934

fix(browser/v7): Continuously record CLS

---

packages/react/src/reactrouter.tsx

Turns out we were not correctly setting parametrized route names for react router v4/v5 😬
Backport of https://github.com/getsentry/sentry-javascript/pull/11855
Fixes https://github.com/getsentry/sentry-javascript/issues/11938

fix(react/v7): Fix react router v4/v5 span names

---

packages/node/package.json
packages/opentelemetry/package.json
yarn.lock

deps(node): Bump `@opentelemetry/core` to `1.24.1` and `@opentelemetry/instrumentation` to `0.51.1`

---

packages/feedback/src/core/integration.ts
packages/types/src/feedback/config.ts

ref(feedback): Rename showScreenshot config to enableScreenshot

---

packages/feedback/src/constants/index.ts
packages/feedback/src/core/components/Actor.ts
packages/feedback/src/core/integration.ts
packages/feedback/src/modal/components/Form.tsx
packages/feedback/src/modal/integration.tsx
packages/feedback/src/screenshot/components/ScreenshotEditor.tsx
packages/feedback/src/screenshot/integration.ts
packages/types/src/feedback/config.ts
packages/types/src/feedback/index.ts

Adding some missing labels that users will need access to if they want to do translations. Also took the chance to rename a few to better align with the other labels, and with their use.

ref(feedback): Rename and add missing Label constants to feedback

---

packages/feedback/src/modal/components/Form.tsx

The `type="email"` textbox enables some basic browser settings like validating that the input looks like an email address, and will change the keyboard to make it easier for phone users to type their info into the box.

feat(feedback): Use type=email for the email input textbox

---

packages/feedback/src/core/createMainStyles.ts
packages/feedback/src/core/integration.ts
packages/feedback/src/modal/components/Dialog.css.ts
packages/feedback/src/modal/components/Dialog.tsx
packages/feedback/src/modal/components/DialogHeader.tsx
packages/feedback/src/modal/components/Form.tsx
packages/feedback/src/modal/integration.tsx

We can simplify the function params and only pass options around most of the time.
I also moved some dialog specific css variables into dialog.css.ts so they can be async loaded, which depends on the options config.

ref(feedback): Simplify feedback function params

---

packages/feedback/src/constants/theme.ts
packages/feedback/src/core/components/Actor.css.ts
packages/feedback/src/core/createMainStyles.ts
packages/feedback/src/modal/components/Dialog.css.ts
packages/feedback/src/modal/components/Dialog.tsx
packages/feedback/src/modal/components/SentryLogo.ts
packages/feedback/src/modal/components/SuccessIcon.ts
packages/feedback/src/modal/integration.tsx
packages/types/src/feedback/theme.ts

This updates the CSS theme, variable names and also how the css works.
The widget is better able to handle cases like:
- short desktop window (scrolls form)
- phone in portrait (full width if the screen is 600px or less)
- phone in landscape (scrolls form)
- when screenshots are in use, stick to screen edges
I also made it, I think, easier to position the button (aka trigger, aka actor) around the screen. You can override in css `--page-margin: 16px` to dictate the distance from the edge, and override `--inset: auto 0 0 auto;` to position the button in the different corners of the screen. For example, you can put the trigger button on the edge of the screen with something like: 
```css
#sentry-feedback {
--actor-inset: auto 0 calc(50% - var(--header-height)) auto;
}
```
Docs are updated …

fix(feedback): Improve CSS theme variable names and layout

---

packages/bun/src/sdk.ts

Add support for global onUnhandled Error/Promise for Bun.
```javascript
import * as Sentry from "@sentry/bun";
Sentry.init({
dsn: "DSN",
});
console.log("Hello via Bun!");
throw new Error('Unhandled Bun Sentry Error!');
```
ref: https://github.com/oven-sh/bun/issues/5091

[v7] Bun Global Unhandled Handlers

---

packages/bun/src/sdk.ts

Add support for global onUnhandled Error/Promise for Bun.
```javascript
import * as Sentry from "@sentry/bun";
Sentry.init({
dsn: "DSN",
});
console.log("Hello via Bun!");
throw new Error('Unhandled Bun Sentry Error!');
```
ref: https://github.com/oven-sh/bun/issues/5091

[v8] Bun Global Unhandled Handlers

---

packages/node/src/sdk/client.ts

Starting Sentry via `--require` and `--import` can cause the SDK to be initialised in every worker thread and forked process which can be confusing to users. With `debug: true` you can see the SDK being initialised multiple times but it's not immediately obvious why this is happening.
This PR adds logging to the `NodeClient` constructor that logs `Initializing Sentry` along with with the `process.pid` and `threadId` to make it a little more clear what's happening:

feat(node): Log process and thread info on initialisation

---

packages/browser-utils/src/instrument/xhr.ts
packages/browser/src/tracing/request.ts
packages/core/src/fetch.ts

We introduced sending standalone `http.client` spans in https://github.com/getsentry/sentry-javascript/pull/11783. Subsequently, we had to revert this change due to internal timeline problems (😢). However, in the revert PR (#11879) we missed that originally, we checked for an active parent span and only then created an `http.client` span. The result were `http.client` _transactions_ which we also don't want. This PR fixes that by re-introducing the `hasParent` check as it was pre-#11783.

fix(browser): Only start `http.client` spans if there is an active parent span

---

packages/aws-serverless/package.json

This PR fixes the `files` property in our AWS Serverless SDK `package.json` to include ESM artifacts now that we support ESM in AWS Serverless. 
(supersedes #11968)
closes #11965

fix(aws-serverless): Include ESM artifacts in package

---

packages/feedback/src/modal/integration.tsx

When getting the user from the scope, the user can also be an empty object, which doesn't work with null coalescing. This checks to see if the user exists and that it's not empty in all scopes
Fixes https://github.com/getsentry/sentry/issues/70347

fix(feedback): Check  for empty user

---

MIGRATION.md
packages/nextjs/src/config/types.ts
packages/nextjs/src/config/webpack.ts

I dropped the ball on this a bit to deprecate but removing it now should still be fine.

feat(nextjs): Remove `transpileClientSDK`

---

dev-packages/e2e-tests/test-applications/node-exports-test-app/scripts/consistentExports.ts
packages/aws-serverless/src/awslambda-auto.ts
packages/aws-serverless/src/sdk.ts
packages/google-cloud-serverless/src/sdk.ts
packages/node/src/index.ts
packages/node/src/sdk/init.ts

In order to keep bundle size compact, performance integrations (except for http & fetch) have to be manually added for serverless packages.
This means that users will have to do e.g. this if they want to have mysql instrumented:
```js
import * as Sentry from '@sentry/aws-serverless';
Sentry.init({
integrations: [Sentry.mysqlIntegration()]
});
```
Closes https://github.com/getsentry/sentry-javascript/issues/11991

feat(serverless): Do not include performance integrations by default

---

packages/replay-canvas/src/canvas.ts
packages/replay-canvas/test/canvas.test.ts

`snapshot` is a public API.
I think the other methods we do not need to expose (?).
With this, usage will be:
```ts
const canvas = getClient()?.getIntegrationByName<ReturnType<typeof replayCanvasIntegration>>('ReplayCanvas');
await canvas.snapshot();
```
Closes https://github.com/getsentry/sentry-javascript/issues/11971

fix(replay): Fix type for `replayCanvasIntegration`

---

packages/replay-internal/src/replay.ts
packages/replay-internal/test/integration/start.test.ts

Replays will fail to start recording when using `start()` specifically when manually recording and after the user has been idle for a long period of time. We need to reset the user activity state when we call `start()`, otherwise the session will be [incorrectly] considered to be idle and unable to send any replay events.
Closes #11983

fix(replay): Fix user activity not being updated in `start()`

---

dev-packages/node-integration-tests/suites/express/without-tracing/server.ts
dev-packages/node-integration-tests/suites/express/without-tracing/test.ts

Just to ensure we do not regress here.
Request isolation should work even without tracing (which means, even without the express integration added - that is only added when tracing is enabled, today!). 
Really, the only thing missing should be `transactionName`.

test(node): Add test for express without tracing

---

dev-packages/node-integration-tests/suites/express/multiple-init/server.ts
dev-packages/node-integration-tests/suites/express/multiple-init/test.ts

Just a test showing how stuff behaves if:
1. `init` is called without DSN
2. `httpIntegration` is manually added
3. `init` is called again, later, with DSN

test(node): Add test to show how re-init works

---

packages/react/src/reactrouterv6.tsx

Hoping that this may address https://github.com/getsentry/sentry-javascript/issues/12018
We should set these dependency-injections as early as possible.

fix(react): Set dependency-injected functions as early as possible

---

packages/aws-serverless/package.json

In v7, the exports were not explicitly defined. In v8, the `awslambda-auto` export has to be added to the list of exports (done in this PR). Also added a variant without the `dist`, so it can be added to the `NODE_OPTIONS ` as `-r @sentry/aws-serverless/awslambda-auto`
fixes https://github.com/getsentry/sentry-javascript/issues/12012

fix(aws-serverless): Add `awslambda-auto` to `package.json` exports

---

packages/core/src/utils/parseSampleRate.ts

Just noticed that there's not really a reason to have the two separate warnings. Let's save some bytes. 
(we have tests covering this change)

ref(core): Steamline `parseSampleRate` utility function

---

packages/browser-utils/src/metrics/inp.ts
packages/browser/src/tracing/browserTracingIntegration.ts
packages/browser/test/unit/tracing/browserTracingIntegration.test.ts

This PR forward-ports the `interactionsSampleRate` option for `browserTracingIntegration` introduced in 7.110.0 to v8. Looks like we missed this when forward-porting the INP implementation as reported in #12006, probably because these two things happened in parallel.
Generally, this PR orients itself on https://github.com/getsentry/sentry-javascript/pull/11382 but I made a couple of changes (that are not API-breaking):
- In v7 we used to sample the span completely manually. In v8 we no longer do this after migrating to using `startInactiveSpan` with `standalone: true`. This function internally samples the span based on `tracesSampleRate` and the usual sampling controlling SDK options. In an effort to keep things simple, I opted to simply sample twice - once on `interactionsSampleRate` and …

feat(browser): Add `interactionsSampleRate` to `browserTracingIntegration` options

---

packages/replay/src/replay.ts
packages/replay/test/integration/beforeAddRecordingEvent.test.ts
packages/replay/test/integration/start.test.ts
packages/replay/test/integration/stop.test.ts

Replays will fail to start recording when using `start()` specifically
when manually recording and after the user has been idle for a long
period of time. We need to reset the user activity state when we call
`start()`, otherwise the session will be [incorrectly] considered to be
idle and unable to send any replay events.

fix(replay/v7): Fix user activity not being updated in `start()`

---

MIGRATION.md

We had this as TBD. I checked with @ryan953 and put the version that we want in, plus a disclaimer.

docs: Put min. self hosted version in migration docs

---

packages/react/src/reactrouterv6.tsx

Ref https://github.com/getsentry/sentry-javascript/issues/12018

fix(react): Warn and fall back gracefully if dependency injected functions are not available

---

.size-limit.js
dev-packages/e2e-tests/test-applications/node-exports-test-app/scripts/consistentExports.ts
packages/aws-serverless/src/sdk.ts
packages/aws-serverless/test/sdk.test.ts
packages/node/rollup.npm.config.mjs
packages/node/src/index.ts
packages/node/src/sdk/init.ts

The prior fix was incomplete, because we were still using `getDefaultIntegrations()` inside of node's `init`, so the deps where pulled in anyhow.
Furthermore, it seems that `preserveModules: false` for `@sentry/node` also prevented this from working as expected.
So this PR does two things:
1. Set `preserveModules: true` so that tree-shaking can work as expected (😿 )
2. Expose a new `initWithoutDefaultIntegrations` method from `@sentry/node` which AWS uses, which avoids including any integrations by default. You have to pass your own `defaultIntegrations` to it.
This is not the prettiest solution, but I couldn't think of anything much better 😬 I also added a size-limit entry to keep track of this.

feat(aws-serverless): Fix tree-shaking for aws-serverless package

---

MIGRATION.md
packages/astro/src/index.server.ts
packages/aws-serverless/src/index.ts
packages/browser/src/exports.ts
packages/bun/src/index.ts
packages/core/src/baseclient.ts
packages/core/src/exports.ts
packages/core/src/index.ts
packages/core/src/scope.ts
packages/core/test/lib/base.test.ts
packages/deno/src/index.ts
packages/google-cloud-serverless/src/index.ts
packages/node/src/index.ts
packages/remix/src/index.server.ts
packages/remix/src/index.types.ts
packages/sveltekit/src/index.types.ts
packages/sveltekit/src/server/index.ts
packages/types/src/scope.ts
packages/vercel-edge/src/index.ts

As discussed, we'll keep it simple and set the event id regardless of the event getting dropped.
A follow-up PR will update `ReportDialogOptions` to make `eventId` optional again as well as use the isolation scope directly in React ErrorBoundaries.

feat(scope): Bring back `lastEventId` on isolation scope (#11951)

---

MIGRATION.md
packages/astro/src/index.server.ts
packages/astro/src/index.types.ts
packages/browser/src/exports.ts
packages/browser/src/sdk.ts
packages/bun/src/index.ts
packages/core/src/exports.ts
packages/core/src/index.ts
packages/deno/src/index.ts
packages/node-experimental/src/index.ts
packages/node-experimental/src/sdk/api.ts
packages/node-experimental/src/sdk/types.ts
packages/node/src/index.ts
packages/remix/src/index.server.ts
packages/remix/src/index.types.ts
packages/serverless/src/index.ts
packages/sveltekit/src/index.types.ts
packages/sveltekit/src/server/index.ts
packages/vercel-edge/src/index.ts

The `lastEventId` api will be brought back in v8 in the near future.

ref(api): Remove `lastEventId` deprecation warnings (#11951)

---

packages/core/src/exports.ts
packages/core/src/index.ts
packages/node/src/integrations/tracing/connect.ts
packages/node/src/integrations/tracing/express.ts
packages/node/src/integrations/tracing/fastify.ts
packages/node/src/integrations/tracing/hapi/index.ts
packages/node/src/integrations/tracing/koa.ts

Closes https://github.com/getsentry/sentry-javascript/issues/12040

fix(node): Do not warn for missing instrumentation if SDK is disabled

---

docs/publishing-a-release.md

Also fixes the broken link for release-approvers.

fix(docs): Reorder how to determine version numbers for releases

---

packages/browser-utils/src/metrics/inp.ts
packages/browser/src/tracing/browserTracingIntegration.ts
packages/browser/test/unit/tracing/browserTracingIntegration.test.ts

This reverts commit c2ae9bde01fdfc221a7898a00f0be018643ea132 (PR #12023).
The reason is that we're concerned about 1. the usefulness and 2. the name of this option and would like to revisit this without blocking the 8.1.0 release. This is not semver-breaking because in 8.0.0, this API did not exist.
We still realized that the back and forth here, including us missing this in the migration guide is not optional. Apologies for anyone who's relying on this option at the moment.

revert: "feat(browser): Add `interactionsSampleRate` to `browserTracingIntegration` options (#12023)"

---

.github/workflows/build.yml
dev-packages/e2e-tests/test-applications/node-express-esm-without-loader/.npmrc
dev-packages/e2e-tests/test-applications/node-express-esm-without-loader/package.json
dev-packages/e2e-tests/test-applications/node-express-esm-without-loader/playwright.config.ts
dev-packages/e2e-tests/test-applications/node-express-esm-without-loader/src/app.mjs
dev-packages/e2e-tests/test-applications/node-express-esm-without-loader/src/instrument.mjs
dev-packages/e2e-tests/test-applications/node-express-esm-without-loader/start-event-proxy.mjs
dev-packages/e2e-tests/test-applications/node-express-esm-without-loader/tests/server.test.ts

This tests a node app that uses ESM, but no `--import` flag.
Somehow this works for `http` (but not other packages...) but this is fine for errors-only mode, for now.
Missing: We do show the warning for missing express instrumentation there, still 😬 we may need to tweak this...

test(node): Add test for errors-only ESM app

---

packages/core/src/tracing/idleSpan.ts
packages/core/test/lib/tracing/idleSpan.test.ts

Closes https://github.com/getsentry/sentry-javascript/issues/12051
This PR does two things:
1. Ensures we add helpful attributes to idle spans more consistently. We now add the `sentry.idle_span_finish_reason` attribute always for idle spans, not only when op == `ui.action.click`. This should also make it easier to debug stuff etc, and I see no reason to not always set this. Additionally, we also keep the number of spans we discarded (if any) for easier debugging too (as `sentry.idle_span_discarded_spans`).
2. We ensure that idle spans cannot exceed the configured `finalTimeout`. Previously, due to the order of things, it was possible that we ended a span very late, if it had a child span with a very late end timestamp (as we took the last child span timestamp). Possibly this could lead …

feat(browser): Improve idle span handling

---

packages/node/src/sdk/init.ts

ref https://github.com/getsentry/sentry-javascript/issues/12034
cc @AbhiPrasad when you're back, let's look again at `hasTracingEnabled()` and see if we want to adjust this maybe.

fix(node): Fix check for performance integrations

---

packages/browser-utils/src/instrument/xhr.ts
packages/browser/src/profiling/utils.ts
packages/core/src/integrations/sessiontiming.ts
packages/utils/src/instrument/fetch.ts

In some places we used `Date.now()`, instead of `timestampInSeconds()` which used performance.now().
There are still other places where we use `Date.now()`, esp. in replay and node, but I focused on regular browser stuff for now (because this is most likely to be affected by this).

fix(browser): Use consistent timestamps

---

packages/core/src/utils/hasTracingEnabled.ts

This is a bit weird in that we access the current scope & client etc., even if options are passed. Since we also use this method in `init()` before we have setup stuff, it seems safer to avoid calling this at all if possible.
This is related to https://github.com/getsentry/sentry-javascript/issues/12054, but not really the cause of it.

fix(core): Avoid looking up client for `hasTracingEnabled()` if possible

---

scripts/get-commit-list.ts

Actually we should check for the changelog commit, which we look for by checking `-meta` and `changelog` in the commit message. (Not perfect, but good enough hopefully...)
I noticed it was not correctly picking up all commits while a release was in progress before.

meta: Fix changelog script

---

dev-packages/e2e-tests/test-applications/node-express-esm-without-loader/tests/server.test.ts
dev-packages/node-integration-tests/suites/express/without-tracing/server.ts
dev-packages/node-integration-tests/suites/express/without-tracing/test.ts
packages/node/src/integrations/http.ts

We noticed that in http integration, we were only setting `transactionName` when we had a sampled span. We can actually set this based on the request object we get either way, making this more robust for error-only mode.

fix(node): Set transactionName for unsampled spans in httpIntegration

---

packages/sveltekit/src/vite/sentryVitePlugins.ts
packages/sveltekit/src/vite/sourceMaps.ts

Adresses https://github.com/getsentry/sentry-javascript/issues/8260#issuecomment-2113620033. Now we can at least recommend to use `filesToDeleteAfterUpload` since we bumped to vite plugin 2.x with 8.0.0
realistically, this also
closes https://github.com/getsentry/sentry-javascript/issues/8260

ref(sveltekit): Emit warning to delete source maps if Sentry plugin enabled source maps generation

---

packages/aws-serverless/rollup.aws.config.mjs
packages/aws-serverless/src/awslambda-auto.ts

We previously adjusted our lambda layer auto initialization in https://github.com/getsentry/sentry-javascript/pull/12017. This unfortunately changed the build output of the `awslambda-auto` bootstrapping script which required a package that isn't included in the layer (`@sentry/node`). This PR fixes the `awslambda-auto` file; local testing showed no more imports from `@sentry/node`.
fixes https://github.com/getsentry/sentry-javascript/issues/12074

fix(aws-serverless): Fix build of lambda layer

---

packages/node/package.json
yarn.lock

This mainly bumps transitive dependencies to be better aligned.

fix(node): Update `@prisma/instrumentation` from 5.13.0 to 5.14.0

---

packages/core/src/envelope.ts
packages/core/test/lib/envelope.test.ts

This was forgotten/got lost while we migrated this from v7 to v8. Now, adding the dsn again when the tunnel is enabled.
Fixes https://github.com/getsentry/sentry-javascript/issues/12094

fix(core): Add dsn to span envelope header

---

dev-packages/node-integration-tests/suites/tracing/apollo-graphql/test.ts
packages/node/src/integrations/tracing/graphql.ts

Users can pass `ignoreResolveSpans` and `ignoreTrivalResolveSpans` to the integration now, which is passed to the instrumentation. They default to `true`. This should reduce noise and perf overhead.
Closes https://github.com/getsentry/sentry-javascript/issues/12092

feat(node): Do not create GraphQL resolver spans by default

---

MIGRATION.md

It was brought up https://github.com/getsentry/sentry-javascript/issues/12013 that importing Sentry as a default import is not working anymore in v8. While this was never officially supported (and also not "removed" on purpose, it just seemed to have worked incidentally before), I do not really consider this a "breaking change", but, as pointed out in the issue, it is still helpful to point this out in the migration docs, for users who incidentally did this before.
We should also add this to migration docs on docs.sentry.io.

docs: Add migration docs to point out that default import does not work

---

dev-packages/e2e-tests/test-applications/node-fastify/package.json
dev-packages/e2e-tests/test-applications/node-fastify/playwright.config.mjs
dev-packages/e2e-tests/test-applications/node-fastify/tests/transactions.test.ts
dev-packages/e2e-tests/test-applications/node-fastify/tsconfig.json
packages/node/src/integrations/tracing/fastify.ts

This ensures we have correct op, name & origin for all fastify middleware spans.
Sadly, we have no good hook in fastify to handle all spans it emits - only `request_handler` spans are passed to `requestHook` 😬 so I opted to add a `spanStart` hook to handle this. Since it would suck to always register this, even without fastify being used, I put this into the fastify error handler - kind of mixing concerns there but I'd say it's fine for this case (as it just enhances the data).
I had some issues running this locally, so I changed the playwright config to not be TS which is IMHO ok and simplifies the setup a bit...

feat(node): Ensure fastify spans have better data

---

packages/feedback/src/core/integration.ts

These params are optional, to the TS typedef should align with that.
**Before:**
**After:**
Related to https://github.com/getsentry/sentry-javascript/issues/12015

fix(feedback): Set optionOverrides to be optional in TS definition

---

packages/nextjs/src/common/wrapAppGetInitialPropsWithSentry.ts
packages/nextjs/src/common/wrapErrorGetInitialPropsWithSentry.ts
packages/nextjs/src/common/wrapGetInitialPropsWithSentry.ts
packages/nextjs/src/common/wrapGetServerSidePropsWithSentry.ts

Fixes https://github.com/getsentry/sentry-javascript/issues/12102
Next.js seems to employ a custom serializer that doesn't like `undefined` values. This PR will guard the undefined values.

fix(nextjs): Don't put `undefined` values in props

---

packages/nextjs/src/config/webpack.ts

Our logic to detect whether the user used the legacy way of initializing the sdk had a flaw because the heuristic to check whether the user has an instrumentation file with sentry config was matching for `sentry.server.config.ts` instead of `sentry.server.config`, which would be the way users import their config files.

fix(nextjs): Fix legacy configuration method detection for emitting warning

---

packages/node/src/sdk/init.ts

Hopefully fixes https://github.com/getsentry/sentry-javascript/issues/12114??

ref(node): Handle failing hook registration gracefully

---

packages/node/src/integrations/context.ts
packages/node/test/helpers/conditional.ts
packages/node/test/integrations/context.test.ts
packages/types/src/context.ts

Adds support for https://nodejs.org/api/process.html#processavailablememory introduced with Node 22
App Context: https://develop.sentry.dev/sdk/event-payloads/contexts/#app-context
ref https://github.com/getsentry/sentry-javascript/issues/11455

feat(node): Add app.free_memory info to events

---

MIGRATION.md

Adds https://github.com/getsentry/sentry-javascript/pull/10780 to the migration guide.

doc(migration): Add entry for runWithAsyncContext

---

packages/google-cloud-serverless/package.json
packages/google-cloud-serverless/src/sdk.ts

closes https://github.com/getsentry/sentry-javascript/issues/11776
This exposes the ESM build for `@sentry/google-cloud-serverless`, with the caveat that the performance related instrumentation does not work atm. These need to be ported to use OpenTelemetry instrumentation.

feat(google-cloud): Expose ESM build

---

packages/node/src/integrations/tracing/connect.ts
packages/node/src/integrations/tracing/express.ts
packages/node/src/integrations/tracing/fastify.ts
packages/node/src/integrations/tracing/hapi/index.ts
packages/node/src/integrations/tracing/koa.ts
packages/node/src/sdk/init.ts
packages/node/src/utils/ensureIsWrapped.ts

Also gives a better warning in ESM mode with a helpful link to the docs.

ref(node): Only show instrumentation warning when tracing is enabled

---

dev-packages/node-integration-tests/suites/tracing/requests/fetch-breadcrumbs/scenario.ts
dev-packages/node-integration-tests/suites/tracing/requests/fetch-breadcrumbs/test.ts
dev-packages/node-integration-tests/suites/tracing/requests/http-breadcrumbs/scenario.ts
dev-packages/node-integration-tests/suites/tracing/requests/http-breadcrumbs/test.ts
packages/node/src/integrations/http.ts
packages/node/src/integrations/node-fetch.ts

This PR ensures that (node) fetch and http requests generate breadcrumbs correctly, even if tracing is disabled.
It also adds tests for this, and ensures we pass the request/response to the hint correctly.
Fixes https://github.com/getsentry/sentry-javascript/issues/12132

fix(node): Ensure fetch/http breadcrumbs are created correctly

---

packages/sveltekit/README.md

Remove quotes around process.env.SENTRY_AUTH_TOKEN

docs(sveltekit): process.env.SENTRY_AUTH_TOKEN

---

.madgerc
package.json
packages/bun/package.json
packages/core/package.json
packages/core/src/asyncContext/stackStrategy.ts
packages/core/src/currentScopes.ts
packages/core/src/defaultScopes.ts
packages/core/src/envelope.ts
packages/core/src/index.ts
packages/core/src/tracing/dynamicSamplingContext.ts
packages/core/src/tracing/index.ts
packages/core/src/utils/spanUtils.ts
packages/deno/package.json
packages/node/src/integrations/anr/index.ts
packages/node/src/sdk/init.ts
packages/node/src/utils/commonjs.ts
packages/node/src/utils/ensureIsWrapped.ts
packages/types/src/event.ts
packages/types/src/index.ts
packages/types/src/options.ts
packages/types/src/samplingcontext.ts
packages/types/src/transaction.ts
packages/vercel-edge/package.json
yarn.lock

I noticed we were getting some build warnings for circular dependency issues, which indicated that madge was not correctly capturing all issues. So I went ahead and updated madge to latest, and aligned the setup, which actually surfaced problems again more correctly. 
I also fixed all the circular dep issues that were raised there. We still have a bunch of types-related circular deps but these are hard to solve, so let's ignore this for now.

ref: Fix circular dependency checks & setup

---

CHANGELOG.md

Anything missing we want to release?

meta(changelog): Update changelog for v8.3.0

---

packages/opentelemetry/src/contextManager.ts

Just noticed we still mention the hub in the `ContextManager`, removing that.

ref(otel): Remove mentions of hub from comments

---

packages/browser-utils/src/getNativeImplementation.ts
packages/utils/src/supports.ts

This makes the `isNativeFetch` check a bit more generic/naive. It no longer checks that the function name matches `fetch` explicitly, but I think thats ok.
Follow-up to https://github.com/getsentry/sentry-javascript/pull/11924

ref(browser): Refactor `isNativeFetch` -> `isNativeFunction`

---

dev-packages/browser-integration-tests/suites/metrics/init.js
dev-packages/browser-integration-tests/suites/metrics/test.ts
packages/core/src/metrics/exports.ts

Closes https://github.com/getsentry/sentry-javascript/issues/12164

fix(metrics): Ensure string values are interpreted for metrics

---

dev-packages/e2e-tests/test-applications/nextjs-14/package.json
dev-packages/e2e-tests/test-applications/nextjs-app-dir/package.json

Next.js 15 will require react 19

ci(e2e): Use react beta for Next.js canary tests

---

dev-packages/node-integration-tests/suites/tracing/redis-cache/test.ts
dev-packages/node-integration-tests/suites/tracing/redis/test.ts
packages/node/src/integrations/tracing/redis.ts

Noticed we forgot to set this.

fix(node): Add origin to redis span

---

.github/workflows/build.yml

The action sets up node 18 currently anyway, this doesn't seem to have any effect.

chore(ci): Remove unused NODE_VERSION 16 env from browser ci tests

---

dev-packages/e2e-tests/test-applications/nextjs-15/app/ppr-error/[param]/page.tsx
dev-packages/e2e-tests/test-applications/nextjs-15/next.config.js
dev-packages/e2e-tests/test-applications/nextjs-15/tests/ppr-error.test.ts
packages/nextjs/src/server/index.ts

Fixes https://github.com/getsentry/sentry-javascript/issues/12061
Fixes https://github.com/getsentry/sentry-javascript/issues/11969
React/Next.js throw errors for control flow. In this case, React throws a "postpone" error, to signify that a route cannot be pre-rendered. We obviously do not want to report these errors so we drop the events.

fix(nextjs): Don't report React postpone errors

---

packages/react/package.json

Closes https://github.com/getsentry/sentry-javascript/issues/12200
From my personal testing everything works with with React 19, so we can bump the peer dep.
For the new error APIs, there is https://github.com/getsentry/sentry-javascript/pull/12147, but that PR is draft while we get feedback from the React team.

feat(react): Add React 19 to peer deps

---

packages/nextjs/src/server/index.ts

While doing https://github.com/getsentry/sentry-javascript/pull/12194 I noticed that there were some inconsistencies with how the generic event processors were running in nextjs and I think it might be because we are attaching to an isolation scope instead of a global scope.

fix(nextjs): Use global scope for generic event filters

---

.github/workflows/canary.yml

resolves https://github.com/getsentry/sentry-javascript/issues/12176
Given the test apps are having issues, disable these tests for now.

test: Disable ember-release and embroider-optimized ember canary tests

---

packages/node/src/integrations/tracing/prisma.ts

Potentially fixes https://github.com/getsentry/sentry-javascript/issues/11216
In esm due to interop, the PrismaInstrumentation can be found under `default`.

fix(node): Change import of `@prisma/instrumentation` to use default import

---

dev-packages/e2e-tests/test-applications/node-exports-test-app/scripts/consistentExports.ts
packages/node/src/index.ts
packages/node/src/sdk/init.ts
packages/node/src/sdk/initOtel.ts

Based on the great feedback in https://github.com/getsentry/sentry-javascript/discussions/12191, this does some small adjustments to ensure that you actually can use the Node SDK properly with a custom OTEL setup:
Today, this is impossible to fix because you need a client to create the sampler, and you need the sampler to satisfy the validation, but the validation runs in `init()`. So either you call init() before doing your manual setup, which means you get the warning, or you do the manual setup first, but then you can't actually add the sampler, and still get the warning.
This change means that users that configure `skipOpenTelemetrySetup` can manually call `Sentry.validateOpenTelemetrySetup()` if they want to get the validation, else there will be no validation automtically.
This is …

feat(node): Ensure manual OTEL setup works

---

packages/core/src/feedback.ts
packages/core/test/lib/feedback.test.ts

This allows to pass a custom scope to `Sentry.captureFeedback()`, like this:
```js
Sentry.captureFeedback({message : 'test' }, {}, scope);
```
This should fix the use case from https://github.com/getsentry/sentry-javascript/issues/11072#issuecomment-2129259591

feat(core): Allow to pass custom scope to `captureFeedback()`

---

dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/startNewTrace/subject.js
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/startNewTrace/template.html
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/startNewTrace/test.ts
packages/astro/src/index.server.ts
packages/aws-serverless/src/index.ts
packages/browser/src/index.bundle.tracing.replay.feedback.ts
packages/browser/src/index.bundle.tracing.replay.ts
packages/browser/src/index.bundle.tracing.ts
packages/browser/src/index.ts
packages/browser/src/tracing/browserTracingIntegration.ts
packages/bun/src/index.ts
packages/core/src/scope.ts
packages/core/src/tracing/index.ts
packages/core/src/tracing/propagationContext.ts
packages/core/src/tracing/trace.ts
packages/core/test/lib/tracing/proagationContext.test.ts
packages/core/test/lib/tracing/trace.test.ts
packages/deno/src/index.ts
packages/google-cloud-serverless/src/index.ts
packages/node/src/index.ts
packages/remix/src/index.server.ts
packages/sveltekit/src/server/index.ts
packages/utils/src/index.ts
packages/utils/src/propagationContext.ts
packages/utils/test/proagationContext.test.ts
packages/vercel-edge/src/index.ts

This PR adds a new `Sentry.startNewTrace` function that allows users to start a trace in isolation of a potentially still active trace. When this function is called, a new trace will be started on a forked scope which remains valid throughout the callback lifetime.
Simple usage example:
```js
myButton.addEventListener('click', async () => {
Sentry.startNewTrace(() => {
Sentry.startSpan({ op: 'ui.interaction.click', name: 'fetch click' }, async () => {
await fetch('http://example.com');
});
});
});
```
Extraced the `generatePropagationContext` utility to utils because it's used in multiple packages

feat(core): Add `startNewTrace` API

---

packages/browser/rollup.bundle.config.mjs

Backporting https://github.com/getsentry/sentry-javascript/pull/12158 to v7
ref https://github.com/getsentry/sentry-javascript/issues/12156
This is also necessary (or at least helpful) if we want to make this selectable in the loader script.

feat(browser/v7): Publish browserprofling CDN bundle

---

.size-limit.js

We had no entry covering the bundle size of metrics so far.

build: Add size-limit entry for metrics

---

dev-packages/e2e-tests/test-applications/sveltekit-2-svelte-5/test/performance.test.ts
dev-packages/e2e-tests/test-applications/sveltekit-2/test/performance.test.ts

test(e2e): Unflake sveltekit test

---

dev-packages/rollup-utils/plugins/bundlePlugins.mjs

This PR fixes one of the two issues that currently cause our lambda layer to break. When we build the lambda layer bundle we apply minification via our terser plugin which mangles `_`-prefixed private variables - like `Module._resolveFilename`. 
To be clear, this PR unfortunately does not fix the lambda layer as we're still blocked on [this issue](https://github.com/getsentry/sentry-javascript/issues/12009#issuecomment-2126211967). Not sure what we can do SDK-side to fix this.
ref: https://github.com/getsentry/sentry-javascript/issues/12089

fix(aws-serverless): Avoid minifying `Module._resolveFilename` in Lambda layer bundle

---

packages/profiling-node/src/integration.ts
packages/profiling-node/src/nodeVersion.ts

resolves https://github.com/getsentry/sentry-javascript/issues/11777

ref(profiling-node): Add warning when using non-LTS node

---

dev-packages/node-integration-tests/suites/public-api/LocalVariables/deny-inspector.mjs
dev-packages/node-integration-tests/suites/public-api/LocalVariables/test.ts
packages/node/src/integrations/anr/index.ts
packages/node/src/integrations/anr/worker.ts
packages/node/src/integrations/local-variables/local-variables-async.ts
packages/node/src/integrations/local-variables/local-variables-sync.ts

Closes #12223
I've added a test that uses `import-in-the-middle` to throw if `inspector` is imported without enabling the `LocalVariables` integration so this should not regress in the future.
Note that we don't need to import asynchronously in the worker scripts since these are not evaluated if the features aren't used.

fix: Only import `inspector` asynchronously

---

dev-packages/rollup-utils/bundleHelpers.mjs
packages/aws-serverless/rollup.aws.config.mjs

So this is a fun one: 
Our lambda layer relies on one bundled Sentry SDK, which caused problems raised in #12089  and https://github.com/getsentry/sentry-javascript/issues/12009#issuecomment-2126211967. Specifically, by bundling `import-in-the-middle` code into one file, it seems like the library's way of declaring its exports conflict, causing the "ImportInTheMiddle is not a constructor" error to be thrown. While this should ideally be fixed soon in `import-in-the-middle`, for now this PR adds a small Rollup plugin to transform `new ImportInTheMiddle(...)` calls to `new ImportInTheMiddle.default(...)` to our AWS Lambda Layer bundle config.
Once the fixes land upstream and we updated our dependencies accordingly, we should remove this plugin again.
I tested this locally with a …

fix(aws): Ensure lambda layer uses default export from `ImportInTheMiddle`

---

packages/browser/src/sdk.ts
packages/browser/test/unit/sdk.test.ts

This PR makes our check for when we abort and log an error due to `Sentry.init` being used in a browser extension a bit more fine-gained. In particular, we now do not abort the SDK initialization if we detect that the SDK is running in a browser-extension dedicated window (e.g. a URL starting with `chrome-extension://`).
This was raised in https://github.com/getsentry/sentry-javascript/issues/12025. h/t @Thomas101 for providing the initial idea how to check for the dedicated pages. I expanded on the check a bit to add other browsers. This list is not complete but probably good enough for start.
Also rewrote the function a bit to hopefully save a few bytes 🤞

fix(browser): Improve browser extension error message check

---

dev-packages/browser-integration-tests/suites/tracing/maxSpans/init.js
dev-packages/browser-integration-tests/suites/tracing/maxSpans/test.ts
dev-packages/node-integration-tests/suites/tracing/maxSpans/scenario.ts
dev-packages/node-integration-tests/suites/tracing/maxSpans/test.ts
packages/core/src/tracing/sentrySpan.ts
packages/core/src/utils/spanUtils.ts
packages/opentelemetry/src/spanExporter.ts

To avoid too large payloads, we should only send up to 1000 spans.
We actually had two different problems here in browser and node:
1. In browser, we _did_ limit to 1000, but we did so in an unfortunate way, which is to reset the set after 1000 spans. So if a span had 1010 children, only the last 10 would be send.
2. In node, we just sent all spans.
I rewrote this to now consistently send the first 1000 spans of a transaction.
I decided to keep all spans (no matter the limit) on the internal parent-child map. Due to this this may grow a lot, but we can avoid inconsistent state (e.g. what happens if a span has a parent in the map, but the parent does not have the span as children, ...) 
All of these should be garbage collected together ideally, so this should be fine hopefully.

fix(tracing): Ensure sent spans are limited to 1000

---

dev-packages/e2e-tests/test-applications/create-next-app/tests/behaviour-server.test.ts
dev-packages/e2e-tests/test-applications/node-connect/tests/errors.test.ts
dev-packages/e2e-tests/test-applications/node-connect/tests/transactions.test.ts
dev-packages/e2e-tests/test-applications/node-express/tests/errors.test.ts
dev-packages/e2e-tests/test-applications/node-express/tests/transactions.test.ts
dev-packages/e2e-tests/test-applications/node-fastify/src/app.ts
dev-packages/e2e-tests/test-applications/node-fastify/tests/errors.test.ts
dev-packages/e2e-tests/test-applications/node-fastify/tests/propagation.test.ts
dev-packages/e2e-tests/test-applications/node-fastify/tests/transactions.test.ts
dev-packages/e2e-tests/test-applications/node-hapi/tests/errors.test.ts
dev-packages/e2e-tests/test-applications/node-hapi/tests/transactions.test.ts
dev-packages/e2e-tests/test-applications/node-koa/tests/errors.test.ts
dev-packages/e2e-tests/test-applications/node-koa/tests/propagation.test.ts
dev-packages/e2e-tests/test-applications/node-koa/tests/transactions.test.ts
dev-packages/e2e-tests/test-applications/node-nestjs/tests/errors.test.ts
dev-packages/e2e-tests/test-applications/node-nestjs/tests/propagation.test.ts
dev-packages/e2e-tests/test-applications/node-nestjs/tests/transactions.test.ts

This does two main things:
1. Updates node E2E tests to use `fetch` instead of axios
2. Update node E2E tests to avoid sending to Sentry.
Instead, we check everywhere via the proxy that the data sent is OK.
Part of https://github.com/getsentry/sentry-javascript/issues/11910

test: Improve E2E node tests

---

dev-packages/e2e-tests/test-applications/sveltekit-2-svelte-5/test/errors.server.test.ts
dev-packages/e2e-tests/test-applications/sveltekit-2-svelte-5/test/performance.server.test.ts
dev-packages/e2e-tests/test-applications/sveltekit/test/errors.server.test.ts
dev-packages/e2e-tests/test-applications/sveltekit/test/performance.server.test.ts
packages/sveltekit/src/server/handle.ts
packages/sveltekit/test/server/handle.test.ts

This PR adds request data to server-side Sentry events by extracting the request object in our `sentryHandle` request handler. This is in line with our other SDKs and was simply missing from the SvelteKit SDK so far.
closes #12253 
ref: https://stackoverflow.com/questions/78534091/sentry-logging-missing-http-server-side-metadata-for-sveltekit/78537808

feat(sveltekit): Add request data to server-side events

---

dev-packages/browser-integration-tests/suites/replay/captureConsoleLog/test.ts

Noticed this while looking into https://github.com/getsentry/sentry-javascript/issues/12244, console should be instrumented just fine in the CDN bundle.

test(replay): Remove outdated test constraint

---

packages/react/src/reactrouterv6.tsx

This came up in the [review for solidjs](https://github.com/getsentry/sentry-javascript/pull/12263#discussion_r1617553627) but is also applicable to react.

ref(react): Use WeakSet to keep track of navigation instrumented clients

---

dev-packages/node-integration-tests/suites/public-api/LocalVariables/deny-inspector.mjs
dev-packages/node-integration-tests/suites/public-api/LocalVariables/test.ts

Uses an alternative test method.
Should reduce failures like [this](https://github.com/getsentry/sentry-javascript/actions/runs/9281632639/job/25538103763).

test: Fix flakey `inspector` test

---

.size-limit.js
dev-packages/e2e-tests/package.json
dev-packages/e2e-tests/test-applications/node-express-cjs-preload/package.json
dev-packages/e2e-tests/test-applications/node-express-esm-loader/package.json
dev-packages/e2e-tests/test-applications/node-express-esm-preload/package.json
dev-packages/e2e-tests/test-applications/node-express-esm-without-loader/package.json
package.json

I noticed that locally the node-integration-tests that check versions fail, because in the SDK we use 18.18.0, we only check for "If node.major >= 18", and then get an incorrect test because actually in code we check the minor too.
Instead of adjust this, IMHO it's better to update this. This also never failed on CI because there we do use latest 18 for the matrix tests...

build: Bump node to 18.20.3

---

packages/nextjs/src/config/types.ts
packages/nextjs/src/config/webpack.ts

https://github.com/getsentry/sentry-javascript/issues/12219 correctly points out that we are stomping the webpack `devtool` option for when people actually want to have the `sourceMappingURL` show up via `productionBrowserSourceMaps`.
With this PR, if people set `productionBrowserSourceMaps` in Next.js, we will not hide their `sourceMappingURL` comment.
Fixes https://github.com/getsentry/sentry-javascript/issues/12219

fix(nextjs): Do not hide `sourceMappingURL` comment on client when `nextConfig.productionBrowserSourceMaps: true` is set

---

dev-packages/e2e-tests/test-applications/node-hapi/tests/errors.test.ts
packages/node/src/integrations/tracing/hapi/index.ts

Resolves: https://github.com/getsentry/sentry-javascript/issues/12260
We're currently attempting to manually update the Hapi route transaction status, followed by `.end()` call. 
Looking at `@opentelemetry/instrumentation-hapi`s code, it looks like that is [already covered by the underlying instrumentation](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/27d6503089163a3d1ed85687cd8e0bc43f525fdd/plugins/node/opentelemetry-instrumentation-hapi/src/instrumentation.ts#L395-L402).
This PR removes that, also extends tests to make sure the error events and the transactions are linked properly.

fix(node): Do not manually finish / update root Hapi spans.

---

packages/node/src/integrations/tracing/hapi/index.ts

Recreating https://github.com/getsentry/sentry-javascript/pull/11151 for v8 again, as the updates seem to be lost when moving the instrumentation inside the project structure.
The testing updates introduced in the original PR do exist in develop / master, so this PR only reintroduces changes in the instrumentation code.

fix(node): Skip capturing Hapi Boom responses v8.

---

.github/workflows/build.yml
.github/workflows/canary.yml
dev-packages/e2e-tests/.env.example
dev-packages/e2e-tests/README.md
dev-packages/e2e-tests/lib/validate.ts
dev-packages/e2e-tests/test-applications/create-next-app/tests/behaviour-client.test.ts
dev-packages/e2e-tests/test-applications/create-next-app/tests/behaviour-server.test.ts
dev-packages/e2e-tests/test-applications/create-remix-app-express-vite-dev/tests/behaviour-client.test.ts
dev-packages/e2e-tests/test-applications/create-remix-app-express/tests/behaviour-client.test.ts
dev-packages/e2e-tests/test-applications/create-remix-app-v2/tests/behaviour-client.test.ts
dev-packages/e2e-tests/test-applications/create-remix-app/tests/behaviour-client.test.ts
dev-packages/e2e-tests/test-applications/create-remix-app/upload-sourcemaps.sh
dev-packages/e2e-tests/test-applications/debug-id-sourcemaps/rollup.config.mjs
dev-packages/e2e-tests/test-applications/debug-id-sourcemaps/tests/server.test.ts
dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/exceptions.test.ts
dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/server-components.test.ts
dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/transactions.test.ts
dev-packages/e2e-tests/test-applications/node-connect/tests/transactions.test.ts
dev-packages/e2e-tests/test-applications/node-express-send-to-sentry/tests/send-to-sentry.test.ts
dev-packages/e2e-tests/test-applications/react-router-6-use-routes/tests/behaviour-test.test.ts
dev-packages/e2e-tests/test-applications/react-send-to-sentry/tests/send-to-sentry.test.ts
dev-packages/e2e-tests/test-applications/standard-frontend-react/tests/behaviour-test.spec.ts
dev-packages/e2e-tests/test-applications/webpack-4/tests/behaviour-test.spec.ts
dev-packages/e2e-tests/test-applications/webpack-5/tests/behaviour-test.spec.ts

Document the env vars necessary for e2e tests

chore: Document e2e test env vars

---

dev-packages/e2e-tests/test-applications/react-create-hash-router/tests/transactions.test.ts
packages/core/src/tracing/idleSpan.ts
packages/core/src/tracing/sentrySpan.ts
packages/core/test/lib/tracing/idleSpan.test.ts

I noticed here https://github.com/getsentry/sentry-javascript/pulls that some tests were becoming flaky. Investigating this some more, I figured out what was happening:
1. For idle spans, when the span is ended (in `on('spanEnded')`, which is triggered in `span.end()`), we call `onIdleSpanEnded`
2. In there, we call `beforeSpanEnd`
3. This is used by `browserTracingIntegration` to call `addPerformanceEntries(span)`, which adds performance spans to the idle span
4. After that, in `onIdleSpanEnded`, any spans having start/end timestamps outside of the idle span start/end timestamp will be discarded
This lead to cases where performance spans were discarded because they were out of bounds of the idle span - which is not what we want!
Now, this PR changes the timing of this a bit:
Now, we …

fix(browser): Fix idle span ending

---

packages/browser/package.json

Oops... 
Fixes https://github.com/getsentry/sentry-javascript/issues/12295

fix(browser): Fix types export path for CJS

---

packages/replay/package.json

Noticed that this package was missing the `v7` npm tag entry, causing some tests in migr8 to fail.

fix(v7/publish): Add `v7` tag to `@sentry/replay`

---

packages/replay-internal/src/util/addEvent.ts

When using `_experiments.traceInternals`, this could lead to an infinite loop, as we run this check when a breadcrumb is added, and we add this breadcrumb in the check, ...
Fixes https://github.com/getsentry/sentry-javascript/issues/12283

fix(replay): Avoid infinite loop of logs

---

.github/workflows/build.yml
dev-packages/e2e-tests/test-applications/aws-lambda-layer/.npmrc
dev-packages/e2e-tests/test-applications/aws-lambda-layer/package.json
dev-packages/e2e-tests/test-applications/aws-lambda-layer/playwright.config.ts
dev-packages/e2e-tests/test-applications/aws-lambda-layer/src/lambda-function.js
dev-packages/e2e-tests/test-applications/aws-lambda-layer/src/run-lambda.js
dev-packages/e2e-tests/test-applications/aws-lambda-layer/src/run.js
dev-packages/e2e-tests/test-applications/aws-lambda-layer/start-event-proxy.mjs
dev-packages/e2e-tests/test-applications/aws-lambda-layer/tests/basic.test.ts
dev-packages/test-utils/src/event-proxy-server.ts
packages/aws-serverless/package.json

This PR adds an e2e (or rather integration) test for our AWS lambda layer bundle. The motivation for this test is that we broke the layer during the initial v8 releases (multiple times for different reasons) without us noticing this in tests. Simply because we never tested the bundled SDK code that we create and publish for the lambda layer. 
The new e2e test tries to simulate a lambda environment by:
- copying over the lambda layer content into the test app as if a layer was added to a lambda function
- running a lambda function as a process which gets passed all environment variables that we [instruct users ](https://docs.sentry.io/platforms/javascript/guides/aws-lambda/container-image/#function-configuration)to set for a code-change-less Sentry lambda layer setup. This includes the …

test(aws-lambda): Add basic lambda layer e2e test

---

packages/feedback/src/core/integration.ts

Fixes https://github.com/getsentry/sentry-javascript/issues/12229

fix(feedback): Override TriggerLabel Option

---

packages/nextjs/src/config/withSentryConfig.ts

---
When using Next.js v15.0.0-rc.0 or v15.0.0-canary.6, `withSentryConfig` does not add `clientTraceMetadata` to `experimental`. This is because both rc and canary releases have a minor version of `0` and are always treated as `false`.

fix(nextjs): Fix version detection and option insertion logic for `clientTraceMetadata` option

---

.github/workflows/flaky-test-detector.yml
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/pageloadWithChildSpanTimeout/init.js
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/pageloadWithChildSpanTimeout/test.ts
packages/core/src/tracing/idleSpan.ts

Saw this flake here: https://github.com/getsentry/sentry-javascript/actions/runs/9316244122/job/25644256391
It seems this was sometimes minimally flakey because we used a slightly different end time in the two places - no, we ensure to use the same, which should make this more consistent.

ref(browser): Ensure idle span ending is consistent

---

dev-packages/e2e-tests/test-applications/sveltekit-2-svelte-5/tests/performance.test.ts
dev-packages/e2e-tests/test-applications/sveltekit-2/tests/performance.test.ts

Observed a flake here: https://github.com/getsentry/sentry-javascript/actions/runs/9348183996/job/25727088799?pr=12267#step:12:92

ci: Fix sveltekit flakes

---

packages/nextjs/src/common/utils/responseEnd.ts

I honestly don't know why this fixes the memory leak.
I tried using
```ts
await new Promise(resolve => setTimeout(() => { resolve() }), 50))
```
and
```ts
await new Promise(resolve => { setTimeout(() => { resolve() }) }, 50))
```
but they both also leak.
Since this was just a nice to have, the best path moving forward is just to remove the artificial delay.
Probably fixes https://github.com/getsentry/sentry-javascript/issues/12317

fix(nextjs): Fix memory leak

---

.size-limit.js

You can initialize the Node SDK like this:
```js
import * as Node from '@sentry/node';
Sentry.initWithoutDefaultIntegrations({
dsn: '...',
integrations: [...Sentry.getDefaultIntegrationsWithoutPerformance()]
});
```
Which can be used to tree shake all the otel performance instrumentation (except for http) away.
Also adjusts the size limits to be the current values + ~15kb.

ci(node): Add size limit entry for node without performance

---

.github/workflows/canary.yml
dev-packages/e2e-tests/test-applications/nextjs-15/package.json
dev-packages/e2e-tests/test-applications/nextjs-app-dir/assert-build.ts

- Increase timout for canary tests
- Use Next.js `rc` build, otherwise build crashes
- Don't assert build output for canary and rc builds

ci(canary-tests): Fix Next.js canary test issues

---

packages/hub/README.md
packages/integrations/README.md
packages/replay/README.md
packages/serverless/README.md
packages/tracing/README.md

This PR adds discontinuity notes to the Readme files of
- @sentry/tracing
- @sentry/hub
- @sentry/serverless
- @sentry/integrations
- @sentry/replay
with links to the respective sections in the migration guide.
Figured, since I started with #12344 I might as well add similar notes to the other packages 😅

doc(v7): Add package discontinuity notes to remaining discontinued packages

---

packages/profiling-node/bindings/cpu_profiler.cc

Tentative fix for https://github.com/getsentry/sentry-javascript/issues/12169
I did not generate a core dump, but by looking at the crash, it seemed like it the segfault was happening after the bindings were required and the code after the require statement had already ran, which hints at an issue with the measurement collection loop.
This is a small change, but it ensures that the reference to the timer is not maintained and can be properly collected, as well as adds a missing nullptr check.

ref(profiling): unref timer

---

.size-limit.js
packages/browser/src/stack-parsers.ts
packages/browser/test/unit/tracekit/chromium.test.ts
packages/browser/test/unit/tracekit/firefox.test.ts
packages/browser/test/unit/tracekit/safari.test.ts

We had a bug where the chrome stack trace parser incorrectly parsed stack frames when the frame was not inside a function (ie. top level in a module) and contained parentheses.
This surfaced in Next.js because Next.js has file based routing with folders that can contain parentheses and our debug ID injection snippet is injected top-level.
We fix this by first using a regex that attempts to match a simple top level module frame, and if it matches we extract the filename and line/colnumbers without attempting to use the more elaborate regex.

fix(browser): Fix parenthesis parsing logic for chromium

---

dev-packages/node-integration-tests/suites/tracing/redis-cache/scenario-ioredis.js
dev-packages/node-integration-tests/suites/tracing/redis-cache/test.ts
packages/node/src/integrations/tracing/redis.ts
packages/node/src/utils/redisCache.ts
packages/opentelemetry/src/utils/parseSpanDescription.ts

Follow-up for https://github.com/getsentry/sentry-javascript/pull/12348

feat(redis): Support `setex` command in caching functionality

---

packages/astro/package.json
packages/nextjs/package.json
packages/sveltekit/package.json
yarn.lock

Bumping so we can get some `applicationKey` sweetness: https://github.com/getsentry/sentry-javascript-bundler-plugins/pull/540

deps: Bump Sentry bundler plugins to version `2.18.0`

---

packages/replay-internal/src/replay.ts
packages/replay-internal/test/integration/earlyEvents.test.ts

This PR ensures that if a replay is manually started (=no sample rates are defined at all, and a user later calls `start()` or `startBuffering()`, we do not back-port the `initialTimestamp` of the replay based on the event buffer.
By default (for the first segment) we'll backport the `initialTimestamp` to the time of the first event in the event buffer, to ensure that e.g. the pageload browser metrics that may be emitted with an earlier timestamp all show up correctly.
However, this may be unexpected if manually calling `startBuffering()` and seeing things for stuff that happened before.
Now, we keep track of this and adjust the behavior accordingly.
Fixes https://github.com/getsentry/sentry-javascript/issues/11984

fix(replay): Ignore old events when manually starting replay

---

packages/browser-utils/src/index.ts
packages/browser-utils/src/metrics/browserMetrics.ts
packages/browser-utils/src/metrics/inp.ts
packages/browser-utils/src/metrics/instrument.ts
packages/browser/src/tracing/browserTracingIntegration.ts

This is a PR adjusting https://github.com/getsentry/sentry-javascript/pull/12372 to keep transaction name for INP even if the route has changed in the meanwhile.
Now, we keep a map of the last 10 interactionId <> route names, which we use instead (if possible).

fix(browser): Handle more edge cases with INP

---

.size-limit.js
dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals-inp-late/init.js
dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals-inp-late/subject.js
dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals-inp-late/template.html
dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals-inp-late/test.ts
dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals-inp-parametrized-late/init.js
dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals-inp-parametrized-late/subject.js
dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals-inp-parametrized-late/template.html
dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals-inp-parametrized-late/test.ts
dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals-inp-parametrized/init.js
dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals-inp-parametrized/subject.js
dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals-inp-parametrized/template.html
dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals-inp-parametrized/test.ts
packages/browser-utils/src/index.ts
packages/browser-utils/src/metrics/browserMetrics.ts
packages/browser-utils/src/metrics/inp.ts
packages/browser-utils/src/metrics/instrument.ts
packages/browser/src/tracing/browserTracingIntegration.ts

Instead of https://github.com/getsentry/sentry-javascript/pull/12358, this is a simpler change which ensures we pick the transaction from the scope instead.
I also added tests for the various different scenarios, to ensure we see how they behave:
1. INP is emitted _during_ pageload (span is active)
2. INP is emitted _after_ pageload
a. Pageload is parametrized (route)
b. Pageload is unparametrized (URL)
When the pageload is unparametrized (default browser SDK), the transaction is not added to the DSC envelope header (which is correct and also what we do in other places). it is _always_ added to the span attributes now, though. If no span is active, it will use transactionName from the last active pageload/navigation span.
There may be edge cases where this is not 100% correct (e.g. if the …

fix(browser): Fix INP span creation & transaction tagging

---

packages/aws-serverless/src/awslambda-auto.ts

The `awslambda-auto.js` file can be used to automatically init the AWS Serverless SDK by only setting [environment variables](https://docs.sentry.io/platforms/javascript/guides/aws-lambda/container-image/#function-configuration). This file is currently only exposed for CJS output. In a future PR, I'd like to also expose it in ESM so that users don't have to create their own `instrumentation.ts` file for lambda functions. 
To make this file compatible with ESM though, we can only conditionally try to auto patch the lambda function handler as our auto patching method relies on `require`ing users' lambda function handlers. So this PR guards the `tryPatcHandler` call by checking for the availability of `require` (which is undefined in ESM).

fix(aws-serverless): Only auto-patch handler in CJS when loading `awslambda-auto`

---

dev-packages/e2e-tests/test-applications/node-express-esm-preload/src/app.mjs
dev-packages/e2e-tests/test-applications/node-express-esm-preload/tests/server.test.ts

Just a quick by-product of working on the ESM lambda layer: This PR adds a test to our ESM Express e2e test app to test that http instrumentation is working correctly by ensuring a `http.client` span is captured.

test(e2e): Add ESM http instrumentation test

---

packages/nextjs/package.json

As stated [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#packagejson-exports-imports-and-self-referencing) in the typescript docs, `types` exports should always come first, so that they are resolved correctly. This also applies to the nested `types` within and `exports` condition.
This corrects an issue where `eslint-import-resolver-typescript` was not correctly resolving the full types for Sentry.

fix(nextjs): correct types conditional export ordering

---

packages/astro/package.json
packages/remix/package.json
packages/sveltekit/package.json

Ensure the `types` export is always first, as documented here: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#packagejson-exports-imports-and-self-referencing
Follow up to https://github.com/getsentry/sentry-javascript/pull/12355

fix: Fix types export order

---

dev-packages/e2e-tests/test-applications/vue-3/src/router/index.ts
dev-packages/e2e-tests/test-applications/vue-3/src/views/CategoryIdView.vue
dev-packages/e2e-tests/test-applications/vue-3/tests/performance.test.ts
packages/vue/src/router.ts
packages/vue/test/router.test.ts

Fixed an issue where the correct transactionName could not be obtained when using nested routes in VueRouter.
```typescript
const routes: Array<RouteRecordRaw> = [
{
path: '/',
component: () => import('@/components/Home.vue'),
children: [
{
path: 'categories',
component: () => import('@/components/Categories.vue'),
children: [
{
path: ':categoryId',
component: () => import('@/components/CategoryDetail.vue'),
},
],
},
],
},
];
```
TransactionName would always be "/" for nestedRoute.
The correct value (/categories/:categoryId) is set.
https://router.vuejs.org/guide/essentials/nested-routes.html

fix(vue): Correct span name assignment for matched routes in VueRouter

---

CHANGELOG.md

Discussed internally that we're gonna add external contributor shoutouts to ##Unreleased so that we don't forget them when we create the
changelog for the next release. This PR adds the contributor of #12398.

chore(changelog): Add external contributor credit message to unreleased

---

packages/nextjs/src/config/webpack.ts

Resolves https://github.com/getsentry/sentry-javascript/issues/12367

feat(nextjs): Allow for suppressing warning about missing global error handler file

---

packages/solidjs/README.md

I pretty much copied these instructions from the svelte sdk. They work, although the wizard does not detect the sdk yet.
That being said, I was thinking of recommending using the wizard over creating a bash script, wdyat?
It works:

feat(solidjs): Add sourcemap instructions to README

---

CHANGELOG.md

Small backport release, mostly publishing browser profiling to CDN.

meta(changelog): Update changelog for 7.117.0

---

packages/replay-internal/src/coreHandlers/handleBeforeSendEvent.ts

Fixes https://github.com/getsentry/sentry-javascript/issues/11759, hopefully.
One more example for why we should enable noUncheckedIndexedAccess... See https://github.com/getsentry/sentry-javascript/issues/12440

fix(replay): Fix guard for exception event

---

CHANGELOG.md

`8.9.0` failed to publish fully, this is a retry.

meta(changelog): Update Changelog for 8.9.1

---

packages/profiling-node/src/utils.ts
packages/types/src/index.ts

resolves https://github.com/getsentry/sentry-javascript/issues/12468 
profiling really needs an e2e test for these types, but lets get this merged and released asap to unblock this user.

fix(profiling): Update exports so types generate properly

---

packages/astro/test/tsconfig.json
packages/aws-serverless/test/tsconfig.json
packages/browser-utils/test/tsconfig.json
packages/browser/test/tsconfig.json
packages/bun/test/tsconfig.json
packages/core/test/tsconfig.json
packages/deno/test/tsconfig.json
packages/gatsby/test/tsconfig.json
packages/google-cloud-serverless/test/tsconfig.json
packages/node/test/tsconfig.json
packages/opentelemetry/test/tsconfig.json
packages/profiling-node/test/tsconfig.json
packages/react/test/tsconfig.json
packages/remix/test/tsconfig.json
packages/replay-canvas/test/tsconfig.json
packages/replay-internal/test/tsconfig.json
packages/replay-worker/test/tsconfig.json
packages/solid/test/tsconfig.json
packages/svelte/test/tsconfig.json
packages/sveltekit/test/tsconfig.json
packages/utils/test/tsconfig.json
packages/vercel-edge/test/tsconfig.json
packages/vue/test/tsconfig.json

VSCode does not pick up the `tsconfig.test.json` files, and thus does not apply the config properly to the test files. By adding a tsconfig.json into the test/ directory, this is picked up correctly by VSCode as well.

build: Add `tsconfig.json` to test directories to fix VSCode

---

packages/profiling-node/src/integration.ts
packages/profiling-node/src/spanProfileUtils.ts
packages/profiling-node/src/utils.ts
packages/profiling-node/test/spanProfileUtils.test.ts
packages/profiling-node/test/spanProfileUtils.worker.test.ts

Attach profile context to events while a profiler is active and assign thread id and name to the trace context.
This will be required by the profiling API so that we can figure out the links between spans and profiles. In the future (span streaming), tid and thread name will be assigned to each span

feat(profiling) add global profile context while profiler is running

---

dev-packages/e2e-tests/test-applications/node-express/tests/transactions.test.ts
packages/opentelemetry/src/utils/mapStatus.ts
packages/opentelemetry/test/utils/mapStatus.test.ts

I noticed that we were not correctly setting a status message based on http status for errored http.server span.
The problem was in our logic, where we already had the status set to `{ code: 2, message: undefined }`, and whenever the code was not 0 (unset), we'd never look at the attributes to infer the proper status message.
Now, if we have code: 2 but not message, we try to infer the message from the attributes, if possible.

fix(node): Ensure status is correct for http server span errors

---

.github/workflows/build.yml
dev-packages/external-contributor-gh-action/.eslintrc.cjs
dev-packages/external-contributor-gh-action/action.yml
dev-packages/external-contributor-gh-action/index.mjs
dev-packages/external-contributor-gh-action/package.json
package.json

This adds a new GHA job that, if a PR is created by an external contributor, it will open a PR against that branch that adds the contributor to the changelog, so we do not forget about this.
It will open a PR like this:
https://github.com/getsentry/sentry-javascript/pull/12435
which we have to manually merge/review, so nothing "bad" can happen.

ci: Add workflow to automatically add external contributors to CHANGELOG.md

---

packages/feedback/src/modal/components/Dialog.css.ts
packages/feedback/src/screenshot/components/ScreenshotEditor.tsx
packages/feedback/src/screenshot/components/ScreenshotInput.css.ts

Screenshots will no longer become larger to fit the screenshot area after being cropped, instead it would remain the same size. The image quality of the screenshot goes down if the image is cropped too much. This could help make small crops a bit more readable.
Before:
After:
Relates to https://github.com/getsentry/sentry-javascript/issues/12329

feat(feedback): Screenshots don't resize after cropping

---

.github/workflows/build.yml

Ensure we run node-integration, remix, nextjs tests for changes in opentelemetry package.
You can see how this PR: https://github.com/getsentry/sentry-javascript/pull/12477 did not trigger node-integration tests 😬

ci: Fix node dependencies for CI jobs

---

packages/browser/test/unit/eventbuilder.test.ts
packages/browser/test/unit/index.test.ts
packages/browser/test/unit/profiling/integration.test.ts
packages/browser/test/unit/tracing/browserTracingIntegration.test.ts
packages/core/test/lib/integrations/functiontostring.test.ts
packages/core/test/lib/tracing/idleSpan.test.ts
packages/core/test/lib/tracing/trace.test.ts
packages/core/test/mocks/client.ts
packages/core/test/mocks/integration.ts
packages/node/test/integration/scope.test.ts
packages/opentelemetry/test/integration/scope.test.ts
packages/opentelemetry/test/trace.test.ts
packages/react/test/reactrouterv3.test.tsx
packages/react/test/reactrouterv4.test.tsx
packages/react/test/reactrouterv5.test.tsx
packages/react/test/reactrouterv6.4.test.tsx
packages/react/test/reactrouterv6.test.tsx
packages/replay-internal/test/integration/session.test.ts
packages/replay-internal/test/unit/coreHandlers/handleNetworkBreadcrumbs.test.ts
packages/utils/test/aggregate-errors.test.ts

This updates some tests to avoid unnecessary conditions.
Extracted this out while looking at enabling eslint no-uncessary-condition, as this can be done without much reviewing.

test(ref): Avoid some unnecessary conditions in tests

---

packages/node/src/sdk/initOtel.ts
packages/node/src/types.ts
packages/node/test/integration/transactions.test.ts
packages/opentelemetry/src/spanExporter.ts
packages/opentelemetry/src/spanProcessor.ts

This adds a new config option for `@sentry/node`, `maxSpanWaitDuration`.
By configuring this, you can define how long the SDK waits for a finished spans parent span to be finished before we discard this.
Today, this defaults to 5 min, so if a span is finished and its parent span is not finished within 5 minutes, the child span will be discarded. We do this to avoid memory leaks, as parent spans may be dropped/lost and thus child spans would be kept in memory forever.
However, if you actually have very long running spans, they may be incorrectly dropped due to this. So now, you can configure your SDK to have a longer wait duration.
Fixes https://github.com/getsentry/sentry-javascript/issues/12491

feat(node): Allow to configure `maxSpanWaitDuration`

---

packages/browser/src/index.ts

We may or may not have forgotten to export this from the browser SDK.

feat(browser): Export `thirdPartyErrorFilterIntegration` from `@sentry/browser`

---

packages/feedback/src/screenshot/components/ScreenshotEditor.tsx

Improves screenshot quality after cropping for retina displays. This increases resolution after cropping by factoring in DPI.
Before:
After:
The size is the same when cropping but when viewing feedbacks, screenshots from retina displays are twice as large due to higher DPI.
Closes https://github.com/getsentry/sentry-javascript/issues/12329

feat(feedback): Improve screenshot quality for retina displays

---

packages/node/src/integrations/contextlines.ts
packages/node/test/integrations/contextlines.test.ts

We want to have some safeguards in place to avoid reading minified files or large bundled files as we could incur a large processing time cost. The output of such files is likely to be less useful anyways, so contextlines would be low value

feat(node) add max lineno and colno limits

---

packages/remix/src/index.client.tsx
packages/remix/src/index.types.ts

fix(remix): Export no-op as `captureRemixServerException` from client SDK

---

packages/remix/src/utils/web-fetch.ts
packages/remix/test/utils/normalizeRemixRequest.test.ts

Remix v2.9+ now supports `undici` native fetch. `normalizeRemixRequest()` would throw an error when processing `headers`. This PR uses the standard `Object.fromEntries()` to convert `Headers` into an object.

fix(remix): Add nativeFetch support for accessing request headers

---

packages/feedback/src/core/sendFeedback.ts
packages/feedback/src/modal/components/Dialog.css.ts
packages/feedback/src/modal/components/Form.tsx

`sendFeedback` rejects if the response isn't a valid status code. Also propagates message into form.
Fixes https://github.com/getsentry/sentry-javascript/issues/12476

fix(feedback): Send feedback rejects invalid responses 

---

packages/nextjs/package.json
yarn.lock

updated `@rollup/plugin-commonjs` to v26.0.1
the previous version has dependency on vulnerable `inflight` package
Closes https://github.com/getsentry/sentry-javascript/issues/12516

fix(nextjs): Update @rollup/plugin-commonjs

---

packages/core/src/tracing/sentrySpan.ts
packages/core/test/lib/tracing/sentrySpan.test.ts

@edwardgou-sentry pointed out that `sendSpanEnvelope` immediately sends spans without checking for `this._sampled`, which means you can't use `tracesSampler` to filter them. This changes that!
We also record client outcomes for `sample_rate` with spans.

fix(core): Ensure standalone spans respect sampled flag

---

.github/workflows/build.yml

I noticed that this was not actually working, maybe the check here was wrong 🤔  According to here: https://stackoverflow.com/questions/61886993/in-github-actions-how-to-get-the-type-of-a-trigger-event-as-a-variable this should work!

ci: Fix check for external contributors

---

README.md

We want to support v7 with critical bug fixes until EOY 2024. So we're explicitly stating this in the readme, and I also fixed/updated some other small things.

docs: Update readme to include v7 support time & some small fixes

---

packages/node/src/sdk/api.ts
packages/vercel-edge/src/sdk.ts

ref https://github.com/getsentry/sentry-javascript/issues/12513
This PR upgrades release detection for Node and Vercel Edge SDKs.
This change adds release name detection for:
- GitLab CI
- AppVeyor
- AWS Amplify
- Azure Pipelines
- Bitrise
- Buddy CI
- Cirrus CI
- Codefresh
- Codemagic
- Semaphore CI
- Travis CI
- CloudBees CodeShip
- Coolify
- Jenkins
- TeamCity
- Woodpecker CI
Based on https://github.com/getsentry/sentry-javascript-bundler-plugins/pull/549
Supercedes https://github.com/getsentry/sentry-javascript/pull/12507

feat(node): Detect release from more providers

---

packages/profiling-node/src/integration.ts

ref https://github.com/getsentry/sentry-javascript/issues/12468#issuecomment-2178865905
We need to import from `@sentry/core` instead of a relative import otherwise the types break.

fix(profiling-node): Use correct getGlobalScope import

---

packages/core/src/tracing/trace.ts
packages/core/test/lib/tracing/trace.test.ts
packages/opentelemetry/src/trace.ts
packages/opentelemetry/test/trace.test.ts
packages/types/src/startSpanOptions.ts

With this PR, you can now pass a `parentSpan` optionally to `startSpan*` APIs to create a span as a child of a specific span:
```js
const span = Sentry.startInactiveSpan({ name: 'xxx', parentSpan: parent });
Sentry.startSpan({ name: 'xxx', parentSpan: parent }, () => {});
Sentry.startSpanManual({ name: 'xxx', parentSpan: parent }, () => {});
```
With this, it should be easier to understand how you can manually work with spans in v8.
Closes https://github.com/getsentry/sentry-javascript/issues/12539
ref https://github.com/getsentry/sentry-javascript/issues/12566, which I noticed while working on this. For now I just cast the span which should be fine, but is not ideal.

feat(core): Add `parentSpan` option to `startSpan*` APIs

---

dev-packages/browser-integration-tests/loader-suites/loader/onLoad/keepSentryGlobal/init.js
dev-packages/browser-integration-tests/loader-suites/loader/onLoad/keepSentryGlobal/subject.js
dev-packages/browser-integration-tests/loader-suites/loader/onLoad/keepSentryGlobal/template.html
dev-packages/browser-integration-tests/loader-suites/loader/onLoad/keepSentryGlobal/test.ts
dev-packages/rollup-utils/bundleHelpers.mjs

This was brought up in Slack - turns out we were always overwriting `window.Sentry` when a CDN bundle was loaded. This means that if a user e.g. loaded an integration via CDN, which is put on `window.Sentry`, this was overwritten if the loader fetched the base CDN bundle later.
This _probably_ did not come up earlier because we may handle `Sentry.Integrations` specially, but not sure. This fix should ensure this works as expected!

fix(v7/bundle): Ensure CDN bundles do not overwrite `window.Sentry`

---

CHANGELOG.md

Backport release that should fix CDN bundles for the loader.

meta(changelog): Update Changelog for 7.118.0

---

dev-packages/e2e-tests/test-applications/node-express-esm-preload/tests/server.test.ts
dev-packages/e2e-tests/test-applications/node-profiling/build.mjs
dev-packages/e2e-tests/test-applications/node-profiling/index.ts
dev-packages/e2e-tests/test-applications/node-profiling/package.json
dev-packages/e2e-tests/test-applications/node-profiling/tsconfig.json
packages/profiling-node/src/integration.ts

Should catch issues like https://github.com/getsentry/sentry-javascript/pull/12564

test: Update profiling e2e test to use typescript

---

packages/feedback/src/util/isScreenshotSupported.ts

iPads on iPad OS 13+ will show up as Macintosh in the UserAgent since they show the desktop version of sites. This adds extra checks to distinguish if it's an iPad.
Fixes [JAVASCRIPT-2TNR](https://sentry.sentry.io/feedback/?feedbackSlug=javascript:5511454761&project=11276)

feat(feedback): Extra check for iPad in screenshot support

---

dev-packages/browser-integration-tests/loader-suites/loader/onLoad/keepSentryGlobal/init.js
dev-packages/browser-integration-tests/loader-suites/loader/onLoad/keepSentryGlobal/subject.js
dev-packages/browser-integration-tests/loader-suites/loader/onLoad/keepSentryGlobal/template.html
dev-packages/browser-integration-tests/loader-suites/loader/onLoad/keepSentryGlobal/test.ts
dev-packages/rollup-utils/bundleHelpers.mjs

v8 portion of https://github.com/getsentry/sentry-javascript/pull/12579 (not that relevant there because no Loader support yet, but still...)

fix(bundle): Ensure CDN bundles do not overwrite `window.Sentry`

---

docs/gitflow.md

docs: Update gitflow docs with caveat

---

packages/nuxt/package.json

We did not correctly handle this in the backmerge from the 8.11.0 release.

chore: Fix up nuxt package versions

---

packages/node/src/integrations/node-fetch.ts

While debugging, it is hard to find the reason why `NodeFetch` is not loading.
ref https://github.com/getsentry/sentry-javascript/issues/12603

ref(node): Add error message to NodeFetch log

---

dev-packages/e2e-tests/test-applications/node-koa/index.js
dev-packages/e2e-tests/test-applications/node-koa/tests/assert.test.ts
packages/node/src/integrations/tracing/koa.ts

Fixes #12517 
Note: I did not yet any filtering for error status codes in this PR.

fix(node): Re-throw errors from koa error handler

---

packages/remix/src/index.client.tsx
packages/remix/src/index.types.ts
packages/remix/src/utils/errors.ts

Marks `isRemixV2` as optional in the exposed types of `captureRemixServerException`. 
This is a follow-up on https://github.com/getsentry/sentry-javascript/pull/12497

fix(remix): Mark `isRemixV2` as optional in exposed types.

---

docs/triaging.md

This adds docs about how to triage effectively. It is rather specific to this repository/team, but parts of it may also be relevant for outside contributors.
See https://github.com/getsentry/sentry-javascript/blob/fn/docs-triaging/docs/triaging.md

docs: Add triaging docs

---

.github/workflows/build.yml

11 and 12 are soon to be [deprecated](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners) so we need to upgrade them

fix(build) upgrade deprecated runners

---

CHANGELOG.md
dev-packages/e2e-tests/test-applications/solid/src/index.tsx
packages/solid/README.md
packages/solid/package.json
packages/solid/rollup.npm.config.mjs
packages/solid/src/index.ts
packages/solid/src/solidrouter.ts
packages/solid/test/solidrouter.test.tsx
packages/solid/tsconfig.types.json
yarn.lock

⚠️ This PR introduces **breaking changes** to `@sentry/solid`⚠️
Previously, we had to pass `useBeforeLeave` and `useLocation` to `solidRouterBrowserTracingIntegration`. This has now been removed in favor of importing the router hooks directly within the sdk as needed.
Import `solidRouterBrowserTracingIntegration` from `@sentry/solid/solidrouter` and add it to `Sentry.init`:
```js
import * as Sentry from '@sentry/solid';
import { solidRouterBrowserTracingIntegration, withSentryRouterRouting } from '@sentry/solid/solidrouter';
import { Router } from '@solidjs/router';
Sentry.init({
dsn: '__PUBLIC_DSN__',
integrations: [solidRouterBrowserTracingIntegration()],
tracesSampleRate: 1.0, //  Capture 100% of the transactions
});
const SentryRouter = withSentryRouterRouting(Router);
```
As a …

feat(solid): Remove need to pass router hooks to solid integration

---

dev-packages/e2e-tests/test-applications/react-router-6/tests/transactions.test.ts
dev-packages/test-utils/src/event-proxy-server.ts

While looking into https://github.com/getsentry/sentry-javascript/issues/11646, I decided to add an E2E test for INP spans.

test: Test INP spans in E2E test

---

packages/feedback/src/core/sendFeedback.test.ts
packages/feedback/src/core/sendFeedback.ts
packages/feedback/src/modal/components/Dialog.css.ts

Fix error message colour back to red. Also updated the default error message to include information about network issues and ad blockers since ad blockers can result in a type error which has no status code.

fix(feedback): Improve feedback error message

---

docs/creating-a-new-sdk.md

This adds a doc page with infos about creating a new SDK.
See: https://github.com/getsentry/sentry-javascript/blob/fn/new-sdk-docs/docs/creating-a-new-sdk.md

docs: Add docs about creating a new SDK

---

packages/nextjs/src/config/withSentryConfig.ts

Fixes https://github.com/getsentry/sentry-javascript/issues/12654

docs(nextjs): Fix JSDoc param for `withSentryConfig`

---

packages/nextjs/package.json

The react peer dep is implicitly covered by the react SDK and we would like to allow the release candidates for next 15.

deps(nextjs): Remove react peer dep and allow rc

---

yarn.lock

Ran `npx yarn-update-dependency @opentelemetry/instrumentation` over the repo.
This fixes an issue with the aws lambda layer build where `@opentelemetry/instrumentation-aws-lambda` used an older version of `@opentelemetry/instrumentation` without named imports of import-in-the-middle.
Possibly related to: https://github.com/getsentry/sentry-javascript/issues/12465

fix: Update @opentelemetry/instrumentation dependencies

---

dev-packages/rollup-utils/plugins/npmPlugins.mjs
package.json
yarn.lock

ref: https://github.com/getsentry/sentry-javascript/pull/12644
We don't use the codecov plugin anymore, we can remove it.
Extracted from the previous PR because 1 big change was breaking CI and I couldn't figure out the root cause.

chore: Remove @codecov/rollup-plugin

---

package.json
yarn.lock

ref: https://github.com/getsentry/sentry-javascript/pull/12644
We don't use `es-check` anymore, we can remove it. It was previously used to validate our es5 builds, but we don't target that anymore.
Extracted from the previous PR because 1 big change was breaking CI and I couldn't figure out the root cause.

chore: Remove `es-check` from deps

---

packages/nextjs/src/config/types.ts
packages/nextjs/src/config/webpack.ts

Attempts to reliably fix https://github.com/getsentry/sentry-javascript/issues/12077
It seems like we are not catching _some_ instances of the warning, but I would like to try this solution.

fix(nextjs): Attempt to ignore critical dependency warnings

---

packages/node/src/sdk/index.ts
packages/node/src/types.ts

Currently the only way to disable ESM loader hook registration is to set:
```ts
globalThis._sentryEsmLoaderHookRegistered = true;
```
After this PR, you can set the new `registerEsmLoaderHooks` option to `false`:
```ts
import * as Sentry from '@sentry/node';
Sentry.init({
dsn: '__DSN__', 
registerEsmLoaderHooks: false,
});
```

feat(node): Add `registerEsmLoaderHooks` option

---

dev-packages/bundle-analyzer-scenarios/package.json
dev-packages/bundle-analyzer-scenarios/webpack.cjs
package.json
scripts/versionbump.js
yarn.lock

ref: https://github.com/getsentry/sentry-javascript/pull/12644
We can remove `replace-in-file` and `inquirer` with some built-in functions and clean up our lockfile even more.
Extracted from the previous PR because 1 big change was breaking CI and I couldn't figure out the root cause.

chore: Remove replace-in-file and inquirer

---

dev-packages/browser-integration-tests/tsconfig.json
dev-packages/browser-integration-tests/utils/generatePlugin.ts
dev-packages/browser-integration-tests/utils/helpers.ts

Not sure how this worked before, but there was a bunch of stuff that conflicted with `noUncheckedIndexedAccess` :thinking:
Noticed this locally when running browser integration tests now.

test: Fix tsconfig for browser-integration-tests

---

dev-packages/e2e-tests/test-applications/nestjs/src/app.controller.ts
dev-packages/e2e-tests/test-applications/nestjs/src/app.service.ts
dev-packages/e2e-tests/test-applications/nestjs/tests/errors.test.ts
packages/node/src/integrations/tracing/nest.ts

Small change filtering expected errors from being reported to sentry in the nestjs sdk.
Tested manually on my sample app.
Fixes https://github.com/getsentry/sentry-javascript/issues/12523

feat(nestjs): Filter 4xx errors

---

.github/workflows/build.yml
.github/workflows/external-contributors.yml

This should fix the old behavior...
previously, we made a PR against a PR branch when we detected that it was opened by an external contributor. This is problematic, turns out, because external contributors will usually have a fork of the repo and thus the action will fail.
Now, instead, we will make a PR against develop when a contributor PR is _merged_.
See example PR: https://github.com/getsentry/sentry-javascript/pull/12728

ci: Refactor/fix external contribution handling

---

packages/react/src/reactrouter.tsx
packages/react/src/types.ts

Using React 19 release candidate, I find that the `JSX` namespace is now private and cannot be used by dependencies. Doing so produces build errors:
```
.../Yarn/Berry/cache/@sentry-react-npm-8.13.0-bd23d3c2da-10c0.zip/node_modules/@sentry/react/build/types/reactrouter.d.ts:19:17 - error TS2503: Cannot find namespace 'JSX'.
19     component?: JSX.Element;
~~~
.../Yarn/Berry/cache/@sentry-react-npm-8.13.0-bd23d3c2da-10c0.zip/node_modules/@sentry/react/build/types/types.d.ts:51:51 - error TS2503: Cannot find namespace 'JSX'.
51 export type CreateRoutesFromChildren = (children: JSX.Element[]) => RouteObjectArrayAlias;
~~~
Found 2 errors in 2 files.
```
This PR addresses this issue by replacing `JSX.Element` with the public type `ReactElement`.

Remove private namespace `JSX`

---

dev-packages/e2e-tests/test-applications/vue-3/package.json
package.json
yarn.lock

https://github.com/mysticatea/npm-run-all is no longer maintained, so switching to npm-run-all2.
Eliminates some deps from `yarn.lock` and should be faster!

chore: Use npm-run-all2

---

dev-packages/e2e-tests/package.json
package.json

This is just used internally, but we may as well be up to date there.

build: Bump yarn to `1.22.22` and pnpm to `9.4.0`

---

packages/opentelemetry/src/index.ts
packages/opentelemetry/src/sampler.ts

When users want to use a custom sampler, they can use these new helpers to still have sentry working nicely with whatever they decide to do in there.
For e.g. trace propagation etc. to work correctly with Sentry, we need to attach some things to trace state etc. These helpers encapsulate this for the user, while still allowing them to decide however they want if the span should be sampled or not.
This was brought up here: https://github.com/getsentry/sentry-javascript/discussions/12191#discussioncomment-9892777

feat(opentelemetry): Expose sampling helper

---

packages/remix/package.json

Reverts getsentry/sentry-javascript#12663
This seems to break the e2e tests.

Revert "fix(remix): add esm export for node"

---

dev-packages/rollup-utils/npmHelpers.mjs
dev-packages/rollup-utils/plugins/make-esm-plugin.mjs

Fixes https://github.com/getsentry/sentry-javascript/issues/12608
Sucrase injects a `"react/jsx-runtime"` import, however, ESM requires this to end in `.js` because the react package doesn't have an exports field.
With this PR we rewrite the import to `"react/jsx-runtime.js"` for our ESM output.
I tried importing running `require.resolve("react/jsx-runtime.js")` with node and it crashed so we likely shouldn't do it for CJS.

fix(react): Fix React jsx runtime import for esm

---

.github/workflows/build.yml
dev-packages/e2e-tests/test-applications/react-router-6/tests/transactions.test.ts
dev-packages/test-utils/src/event-proxy-server.ts

Makes e2e tests less flakey by adding an event buffer that is used to send events to callback listeners that have not managed to connect in time for a particular events.
We do this by letting the event listeners also send along a timestamp from which point onwards they would like to receive events.
The race condition would have happened when a listener is registered and an event is triggered right after, meaning the event would escape the provided callback because the listener hasn't connected yet. Slim chance but happens.
We will consume more memory by buffering but it is hopefully managable. GH runners are free right?

test: Fix e2e test race condition by buffering events

---

packages/core/src/baseclient.ts
packages/core/test/lib/base.test.ts
packages/types/src/client.ts

This commit updates the return signature of the client's `on` function to be a void function,
which, when executed, unregisters a callback. This adjustment is necessary for managing instances
where objects are created and destroyed, ensuring that callbacks are properly unregistered to
prevent self-referencing in callback closures and facilitate proper garbage collection.
Typically, changing a type from `void` to `() => void` (or `VoidFunction`) shouldn't be considered
a breaking change because `void` signifies the absence of a return value, implying that the return
value of the `on` function should never be used by consumers.
Opting for the `on` approach, which returns a cleanup function, "seems" simpler because having another
function called `off` requires saving the callback reference …

feat(core): allow unregistering callback through `on`

---

packages/core/src/baseclient.ts

We already report a client report for dropped standalone spans. However, so far we did not report any for spans dropped for transactions.
This PR also emits a client report when `beforeSendSpan` is used to filter a span of a transaction, as well as when the whole transaction is dropped in `beforeSendTransaction`.
For now, we _do not_ emit this if users manually drop single spans in e.g. `beforeSendTransaction`, which I'd say is OK for now.
Closes https://github.com/getsentry/sentry-javascript/issues/12727

fix(tracing): Report dropped spans for transactions

---

.github/workflows/external-contributors.yml

This failed (again) here: https://github.com/getsentry/sentry-javascript/actions/runs/9791997167/job/27036907594
Hopefully this fixes it...

ci: Fix external contributor workflow

---

packages/deno/package.json
packages/deno/scripts/prepack.js

In https://github.com/getsentry/sentry-javascript/pull/12700 I adjusted the prepack script to bring back the build directory, but I forgot to adjust `npm pack X` to make sure we pack the tarball from the `build` directory. This patch fixes that.

fix(deno): Publish from build directory

---

packages/browser/src/utils/lazyLoadIntegration.ts

I was referred by support team to this repository in order to suggest a fix for an issue we encountered. In our case the referrer is not passed to the feedback script and thus results in a 403 (because we set allowed domains in our project settings). Consequently also the modal doesn't open and it's a bit disappointing for us since we would like to use the feature.

fix(core): Pass origin as referrer for `lazyLoadIntegration`

---

dev-packages/rollup-utils/npmHelpers.mjs
dev-packages/rollup-utils/plugins/make-esm-plugin.mjs
packages/react/rollup.npm.config.mjs
packages/remix/rollup.npm.config.mjs

Undoes some of the changes in https://github.com/getsentry/sentry-javascript/pull/12204 and https://github.com/getsentry/sentry-javascript/pull/12740 to fix https://github.com/getsentry/sentry-javascript/issues/12608.

fix(react): Revert back to `jsxRuntime: 'classic'` to prevent breaking react 17

---

packages/opentelemetry/src/utils/parseSpanDescription.ts
packages/opentelemetry/test/utils/parseSpanDescription.test.ts

Allows skipping the automatic span data inference by setting a `sentry.skip_span_data_inference` attribute on the span in question.
The attribute is intentionally not exported as a semantic attribute because this is intended to be intimite API.

feat(opentelemetry): Allow skipping of span data inference

---

.github/workflows/build.yml
dev-packages/e2e-tests/test-applications/react-17/.gitignore
dev-packages/e2e-tests/test-applications/react-17/.npmrc
dev-packages/e2e-tests/test-applications/react-17/package.json
dev-packages/e2e-tests/test-applications/react-17/playwright.config.mjs
dev-packages/e2e-tests/test-applications/react-17/public/index.html
dev-packages/e2e-tests/test-applications/react-17/src/globals.d.ts
dev-packages/e2e-tests/test-applications/react-17/src/index.tsx
dev-packages/e2e-tests/test-applications/react-17/src/pages/Index.tsx
dev-packages/e2e-tests/test-applications/react-17/src/pages/User.tsx
dev-packages/e2e-tests/test-applications/react-17/src/react-app-env.d.ts
dev-packages/e2e-tests/test-applications/react-17/start-event-proxy.mjs
dev-packages/e2e-tests/test-applications/react-17/tests/errors.test.ts
dev-packages/e2e-tests/test-applications/react-17/tests/transactions.test.ts
dev-packages/e2e-tests/test-applications/react-17/tsconfig.json
dev-packages/e2e-tests/test-applications/solid/src/index.tsx

Adds a react 17 test app so we can hopefully catch breaking react 17, as we did recently (https://github.com/getsentry/sentry-javascript/issues/12608) with https://github.com/getsentry/sentry-javascript/pull/12204 and https://github.com/getsentry/sentry-javascript/pull/12740.

chore(e2e): Add react-17 e2e test app

---

.github/workflows/external-contributors.yml

Another day, another try to fix this!
Now it failed like this https://github.com/getsentry/sentry-javascript/actions/runs/9804811101/job/27073251966, hopefully this change fixes this... we'll see!

ci: Fix permissions for external contributors PRs (for real?)

---

dev-packages/node-integration-tests/suites/express/tracing/test.ts
dev-packages/node-integration-tests/suites/tracing/httpIntegration/server-experimental.js
dev-packages/node-integration-tests/suites/tracing/httpIntegration/server.js
dev-packages/node-integration-tests/suites/tracing/httpIntegration/test.ts
packages/nextjs/src/server/httpIntegration.ts
packages/node/src/integrations/http.ts
packages/remix/src/utils/integrations/http.ts

Today, it is not (easily) possible to use custom config for the OTEL HttpInstrumentation. We depend on our own integration for various things, so overwriting this will lead to lots of problems.
With this PR, you can now pass some config through directly, in an "allowlisted" way, + there is an escape hatch to add arbitrary other config:
```js
Sentry.init({
Sentry.httpIntegration({ instrumentation: {
// these three are "vetted"
requestHook: (span, req) => span.setAttribute('custom', req.method),
responseHook: (span, res) => span.setAttribute('custom', res.method),
applyCustomAttributesOnSpan: (span, req, res) => span.setAttribute('custom', req.method),
// escape hatch: Can add arbitrary other config that is passed through
_experimentalConfig: {
serverName: 'xxx'
}
})
]
}); …
```

feat(node): Allow to pass instrumentation config to `httpIntegration`

---

packages/remix/test/integration/package.json

This PR fixes our broken Remix v1 @ Node 16 integration test. Over the weekend, the following transitive dependencies received minor and patch releases which removed support for EOL Node versions. 
- `glob` (https://github.com/isaacs/node-glob/issues/596)
- `lru-cache` (https://github.com/isaacs/node-lru-cache/issues/340)
- `jackspeack` (https://github.com/isaacs/jackspeak/issues/13)
IMO this, despite the dropped versions being EOL, is a breaking change and a major inconvenience for a lot of users. I added comments/opened issues with the request to revert the Node version drops and do it in a major version instead. We're by far not the only affected ones. As our tests show, at least everyone using Remix@1 on Node 16 will be broken by this.
To fix, I added dependency resolutions, mostly …

test(remix): Add dependency resolution overrides to fix breaking Node compatibility changes in dependencies

---

dev-packages/e2e-tests/test-applications/nextjs-14/app/propagation/test-outgoing-fetch-external-disallowed/route.ts
dev-packages/e2e-tests/test-applications/nextjs-14/app/propagation/test-outgoing-fetch/route.ts
dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/client-errors.test.ts
dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/transactions.test.ts

Fixes canary tests in 2 ways:
- Makes fetch requests for propagation non-static.
- Checks for the client trace metadata that was introduced in Next.js 15.
Fixes https://github.com/getsentry/sentry-javascript/issues/12489
Fixes https://github.com/getsentry/sentry-javascript/issues/12501

test(nextjs): Fix Next.js canary tests

---

.github/workflows/build.yml

This PR enables running E2E tests on PRs opened from forked repositories. Previously we excluded these because some E2E tests required secrets which are not available in the forks, causing e2e test runs to always fail. Now that we separated these tests from the e2e tests that don't require secrets (https://github.com/getsentry/sentry-javascript/pull/12259) we should be good to re-enable the required e2e tests for external PRs.
For this to work though, I had to move the "Astro Cloudflare" test to optional tests since it requires a cloudflare token for deployment. IMO this is fine because the test doesn't have any other real tests anyway and we should create a dedicated Astro e2e test app with tests instead and add it to the required test apps.
Tested this with my forked repo and it seems …

test(e2e): Run required E2E tests on PRs from forks

---

packages/feedback/src/screenshot/components/CropCorner.tsx
packages/feedback/src/screenshot/components/ScreenshotEditor.tsx

I noticed this after https://github.com/getsentry/sentry-javascript/pull/12784, but the `<CropCorner>` wasn't inside the `ScreenshotEditorFactory()` function. So of course it wasn't getting access to the `h` ref that is passed in. That variable is what the `<div>` gets transpiled into -> it becomes `h.createElement('div')`.
So what i'm doing is moving `CropCorner` into a `CropCornerFactory` so we can pass `h` in and hopefully not have the extra `import .. from 'preact';`  in the 2nd bundle.
Related to https://github.com/getsentry/sentry-javascript/pull/12535

ref(feedback): Let CropCorner inherit the existing h prop

---

packages/opentelemetry/src/contextManager.ts
packages/opentelemetry/src/propagator.ts

This is more a safety thing that we do not swallow this accidentally in the future, that I noticed while looking through stuff.

ref(otel): Ensure we never swallow args for ContextManager

---

.github/workflows/build.yml

Came up in https://github.com/getsentry/sentry-javascript/pull/12791#issuecomment-2214548933. Dependabot PRs don't seem to have access to the repo secrets, hence causing the optional e2e tests to fail. This PR disables optional e2e tests for dependabot PRs. Our regular, required e2e tests are still executed normally.

test(e2e): Don't run optional E2E tests on Dependabot PRs

---

dev-packages/browser-integration-tests/suites/integrations/moduleMetadata/appliesMetadata/init.js
dev-packages/browser-integration-tests/suites/integrations/moduleMetadata/appliesMetadata/subject.js
dev-packages/browser-integration-tests/suites/integrations/moduleMetadata/appliesMetadata/test.ts
dev-packages/browser-integration-tests/suites/integrations/moduleMetadata/appliesMetadataWithRewriteFrames/init.js
dev-packages/browser-integration-tests/suites/integrations/moduleMetadata/appliesMetadataWithRewriteFrames/subject.js
dev-packages/browser-integration-tests/suites/integrations/moduleMetadata/appliesMetadataWithRewriteFrames/test.ts
packages/core/src/baseclient.ts
packages/core/src/integrations/metadata.ts
packages/core/src/integrations/third-party-errors-filter.ts
packages/core/src/utils/prepareEvent.ts
packages/core/test/lib/integrations/third-party-errors-filter.test.ts
packages/core/test/lib/prepareEvent.test.ts
packages/node/test/sdk/scope.test.ts
packages/types/src/client.ts

Fixes https://github.com/getsentry/sentry-javascript/issues/12704
Previously we had a bug where stack frame metadata wasn't properly applied when something rewrote the stack frame file names in a way that wouldn't allow us to associate the injected metadata stack traces with the stack frames. This boils down to a timing issue where we would attempt to write the stack frame metadata onto the stack frames after the event processors have run, even though we should do that before they run.
To solve this timing issue, this PR adds a hook `applyFrameMetadata` to the client that signals the moment frame metadata should be attached. Additionally we update all of the integrations that make use of frame metadata to use this hook.

fix: Apply stack frame metadata before event processors

---

.github/workflows/external-contributors.yml
dev-packages/external-contributor-gh-action/action.yml

This does two things:
1. Pass the author association to the step - we do not use it right now, but it will be logged at least, allowing us to debug this.
2. Include a reference to the merged PR in the PR body.

ci: Small adaptions to external contributor workflow

---

.github/workflows/build.yml
dev-packages/e2e-tests/package.json
dev-packages/e2e-tests/test-applications/aws-serverless-esm/.npmrc
dev-packages/e2e-tests/test-applications/aws-serverless-esm/package.json
dev-packages/e2e-tests/test-applications/aws-serverless-esm/playwright.config.ts
dev-packages/e2e-tests/test-applications/aws-serverless-esm/src/instrument.mjs
dev-packages/e2e-tests/test-applications/aws-serverless-esm/src/lambda-function.mjs
dev-packages/e2e-tests/test-applications/aws-serverless-esm/src/package.json
dev-packages/e2e-tests/test-applications/aws-serverless-esm/src/run-lambda.mjs
dev-packages/e2e-tests/test-applications/aws-serverless-esm/src/run.mjs
dev-packages/e2e-tests/test-applications/aws-serverless-esm/start-event-proxy.mjs
dev-packages/e2e-tests/test-applications/aws-serverless-esm/tests/basic.test.ts
packages/aws-serverless/package.json
yarn.lock

This PR adds an E2E test app that simulates running an AWS lambda function in ESM mode. At the same time, this test app represents the state of how to manually use the `@sentry/aws-serverless` SDK for ESM-based lambda functions. For the moment, the plan is to document this as follows:
1. Install `@sentry/aws-serverless` with the package manager of your choice
2. Add the following environment variables to your lambda environment:
- `NODE_OPTIONS: '--import @sentry/aws-serverless/awslambda-auto`
- `SENTRY_DSN: '<your-dsn>'`
- `SENTRY_TRACES_SAMPLE_RATE: '1.0'`
3. wrap your lambda handler function with `Sentry.wrapHandler`
4. ensure that when deploying your function, the `node_modules` directory is deployed alongside your lambda code
Unfortunately, we can't get around  highest friction …

test(e2e): Add e2e test for AWS lambda in ESM mode

---

packages/nuxt/README.md
packages/nuxt/package.json

Adds the `module` folder to the build output when building packages in root-level.

fix(nuxt): Add module to build:transpile script

---

packages/browser/src/sdk.ts
packages/browser/test/unit/sdk.test.ts

Looks like our browser extension check that blocks SDK initalization via `Sentry.init` also blocked initializing 
the SDK in NW.js apps. This PR adds a check for the `window.nw` property to handle this case.
Note: If we get more reports like this, we should consider adding a flag to force-init the SDK when this
check wrongfully blocks sdk init. For now though, I wanna hold off from expanding public API.
fixes https://github.com/getsentry/sentry-javascript/issues/12668

fix(browser): Allow SDK initialization in NW.js apps

---

packages/nextjs/src/common/wrapRouteHandlerWithSentry.ts
packages/nextjs/src/index.types.ts

ref https://github.com/getsentry/sentry-javascript/issues/12865

docs(nextjs): Clarify which API wrappers are intended for which router

---

dev-packages/e2e-tests/test-applications/nestjs/src/app.module.ts
dev-packages/e2e-tests/test-applications/nestjs/src/test-module/test.controller.ts
dev-packages/e2e-tests/test-applications/nestjs/src/test-module/test.exception.ts
dev-packages/e2e-tests/test-applications/nestjs/src/test-module/test.filter.ts
dev-packages/e2e-tests/test-applications/nestjs/src/test-module/test.module.ts
dev-packages/e2e-tests/test-applications/nestjs/tests/errors.test.ts

Related to [this issue](https://github.com/getsentry/sentry-javascript/issues/12351).
Currently errors in submodules are not properly handled in nest applications if a custom exception filter extending the BaseExceptionFilter is used, leading to expected exceptions not being caught correctly and therefore being returned as 500 and sent to Sentry.
This expands the sample nest application and adds an e2e test that documents this behavior that can be used to check that future improvements to the SDK actually work. Of course the test has to be adjusted in that case.

test(e2e): Add nestjs e2e test documenting errors not being properly caught in submodules

---

packages/nextjs/src/config/loaders/wrappingLoader.ts
packages/nextjs/src/config/webpack.ts
packages/nextjs/test/config/fixtures.ts
packages/nextjs/test/config/loaders.test.ts

This PR updates the regex and logic for detecting middleware, route handler, and server component files to support [custom page extensions](https://nextjs.org/docs/pages/api-reference/next-config-js/pageExtensions), such as `middleware.custom.ts` and `route.custom.ts`.
- Modified the `isRouteHandler` function to use a regex that matches custom page extensions for route handler files.
- Modified the `isMiddlewareResource` function to use a regex that matches custom page extensions for middleware files.
- Modified the `isServerComponent` function to use a regex that matches custom page extensions for server component files.
- modified `hasGlobalErrorFile` flag to account for custom page extensions 
- Verified the updated regex matches route handlers and middleware files with standard and …

fix(nextjs): Support automatic instrumentation for app directory with custom page extensions

---

dev-packages/e2e-tests/test-applications/create-remix-app/app/entry.client.tsx
dev-packages/e2e-tests/test-applications/create-remix-app/app/routes/user.$id.tsx
dev-packages/e2e-tests/test-applications/create-remix-app/tests/client-inp.test.ts
packages/browser-utils/src/metrics/inp.ts
packages/browser/src/tracing/browserTracingIntegration.ts
packages/remix/src/client/browserTracingIntegration.ts
packages/remix/src/client/performance.tsx

Fixes https://github.com/getsentry/sentry-javascript/issues/12855
Previously, we stored the route name of the pageload in a map for INP interactions. However, in some frameworks - e.g. remix, but also others, we update the pageload span name later (since we rely on e.g. react hooks for this etc). 
Since we store the name of the pageload span at the time the first interaction is recorded, it can thus happen that these run out of sync.
This PR changes this so that instead of the routename itself, we store the pageload span in a map, and pick the last name of this when generating the INP span.
I added tests in a remix e2e tests that show the now correct behavior, these used to fail (because `transaction` on the pageload INP was `/`).

fix(inp): Ensure INP spans have correct transaction

---

dev-packages/e2e-tests/test-applications/nestjs/src/app.service.ts
packages/nestjs/src/span-decorator.ts

_Before submitting a pull request, please take a look at our
[Contributing](https://github.com/getsentry/sentry-javascript/blob/master/CONTRIBUTING.md) guidelines and verify:_
---
**The `SentryTraced()` decorator in the `@sentry/nestjs` package (introduced in #12721) stealthily turns any decorated function asynchronous.**
We experienced issues on a production Nest app due to this - it's a bit sneaky because the Typescript compiler doesn't understand (or check at all?) that the decorator changes the function signature.
There was a test written to check sync support, but since the tests are end-to-end and always go through a first layer of async functions, the returned `Promise<>` from the supposedly sync test function was just unwrapped later without any issues.
**This PR:**
- Fixes the …

fix(nestjs): do not make SentryTraced() decorated functions async

---

dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/client-app-routing-instrumentation.test.ts
dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/server-components.test.ts

https://github.com/getsentry/sentry-javascript/actions/runs/9889158043

test(nextjs): Fix canary tests

---

packages/angular/src/errorhandler.ts
packages/angular/test/errorhandler.test.ts

Small fix for a "bug" mentioned in https://github.com/getsentry/sentry-javascript/issues/12757#issuecomment-2220585593
This PR adds a guard for referencing `ErrorEvent` which is only available in browser environments but not in Node. Now, the errorHandler, as well as `@sentry/angular` in general is only expected to be run in browser environments. So this fix is technically not necessary at the moment but people nevertheless use `@sentry/angular` in Node environments so let's make their lives a bit easier.

fix(angular): Guard `ErrorEvent` check in ErrorHandler to avoid throwing in Node environments

---

dev-packages/e2e-tests/test-applications/nextjs-15/app/nested-rsc-error/[param]/page.tsx
dev-packages/e2e-tests/test-applications/nextjs-15/app/streaming-rsc-error/[param]/client-page.tsx
dev-packages/e2e-tests/test-applications/nextjs-15/app/streaming-rsc-error/[param]/page.tsx
dev-packages/e2e-tests/test-applications/nextjs-15/instrumentation.ts
dev-packages/e2e-tests/test-applications/nextjs-15/package.json
dev-packages/e2e-tests/test-applications/nextjs-15/tests/nested-rsc-error.test.ts
dev-packages/e2e-tests/test-applications/nextjs-15/tests/streaming-rsc-error.test.ts
packages/nextjs/src/common/captureRequestError.ts
packages/nextjs/src/common/index.ts
packages/nextjs/src/index.types.ts

This PR adds an experimental implementation of an error handler that can be used to capture errors for the `onRequestError` hook recently added to Next.js canary: https://github.com/vercel/next.js/pull/67539
The handler can be added to the `instrumentation.ts` file as follows:
```ts
// instrumentation.ts
import * as Sentry from '@sentry/nextjs';
export async function register() {
if (process.env.NEXT_RUNTIME === 'nodejs') {
await import('./sentry.server.config');
}
if (process.env.NEXT_RUNTIME === 'edge') {
await import('./sentry.edge.config');
}
}
export const onRequestError = Sentry.experimental_captureRequestError;
```
Currently, Next.js requires a `__NEXT_EXPERIMENTAL_INSTRUMENTATION=1` environment variable for this feature to work.

feat(nextjs): Add `experimental_captureRequestError` for `onRequestError` hook

---

.size-limit.js
dev-packages/browser-integration-tests/suites/replay/canvas/manualSnapshot/template.html
dev-packages/browser-integration-tests/suites/replay/canvas/records/template.html
packages/replay-canvas/package.json
packages/replay-internal/package.json
packages/replay-internal/src/types/rrweb.ts
yarn.lock

* Uses clean `Array.from` implementation
* Revert css parsing (player)
* Implements multitouch gestures (player)
* Many upstream fixes

feat(replay): Bump `rrweb` to 2.25.0

---

dev-packages/e2e-tests/test-applications/aws-lambda-layer-cjs/playwright.config.ts
dev-packages/e2e-tests/test-applications/aws-serverless-esm/playwright.config.ts
dev-packages/test-utils/.eslintrc.js
dev-packages/test-utils/src/playwright-config.ts

Small refactor:
Not all our e2e tests require a `startCommand` as we sometimes directly invoke an application from within tests. For example in our AWS lambda e2e tests. This PR makes the `startCommand` option optional so that we can avoid a larger override of the entire `webServer` playwright config object.

ref(e2e-tests): Make `startCommand` optional in shared playwright config

---

MIGRATION.md

resolves https://github.com/getsentry/sentry-javascript/issues/12887

docs: Add apollo integration to migration docs

---

CONTRIBUTING.md

Adding a note here too as first time users are likely to be following this doc when they see the build fail due to python version incompatibility

chore: add python version requirement to contributing doc

---

packages/profiling-node/README.md

Add better build docs on how to build profiling binaries from source #12899

docs(profiling-node): add detailed docs on how to build bindings

---

CHANGELOG.md
packages/core/src/utils/hasTracingEnabled.ts
packages/node/src/sdk/index.ts
packages/types/src/options.ts

Resolves https://github.com/getsentry/sentry-javascript/issues/12883
The `enableTracing` option has been a source of confusion in combination with the existing `tracesSampleRate` and `tracesSampler` options. We are deprecating it in favor of the other options.

ref: Deprecate `enableTracing`

---

packages/node/README.md

docs(node): Update Node `README.md`

---

packages/node/src/sdk/index.ts
packages/node/src/sdk/initOtel.ts
packages/node/src/types.ts

Closes #12878
I added this feature to `import-in-the-middle` which was released in v1.9.0:
- https://github.com/nodejs/import-in-the-middle/pull/124
This PR changes the hook from `@opentelemetry/instrumentation/hook.mjs` to `import-in-the-middle/hook.mjs` as it was only pasing though anyway and the otel hook doesn't pass the `initialize` export.

feat: Expose `exclude` and `include` options for ESM loader

---

dev-packages/e2e-tests/test-applications/solidstart/tests/performance.client.test.ts
packages/solid/src/solidrouter.ts
packages/solid/test/solidrouter.test.tsx
packages/solidstart/test/client/solidrouter.test.tsx

The `@sentry/solid/solidrouter` integration is used within the solid start sdk as well, so we need a way to update the `sentry.origin` for navigation spans to be for the correct framework.
I opted to read this out of the sdk metadata instead of exposing extra api surface and passing it through several levels.

fix(solidstart): Set proper sentry origin for solid router integration when used in solidstart sdk

---

.github/workflows/external-contributors.yml

While we specifically ignored dependabot, we did not ignore github bot. So now, just generally skipping this for any bot users.

ci: Do not run external contributor job for bots

---

packages/sveltekit/package.json

---
Hello! I am in the process of setting up the SvelteKit plugin within a monorepo that includes multiple applications with multiple versions of Vite. I've found that because `@sentry/sveltekit` does not specify a peer dependency on `vite`, `pnpm` picks up the wrong `vite` version for the package's `import type { Plugin } from 'vite'` statement, causing type errors in my Vite config.
This PR adds a simple, optional peer dependency on Vite to `@sentry/sveltekit` to ensure that it picks up whatever version of Vite is being used in the specific package it's installed in, without auto-installing `vite` or anything …

fix(sveltekit): add Vite peer dep for proper type resolution

---

packages/core/src/tracing/trace.ts
packages/core/test/lib/tracing/trace.test.ts
packages/opentelemetry/src/trace.ts
packages/opentelemetry/test/trace.test.ts
packages/types/src/startSpanOptions.ts

Noticed this while writing docs, this makes this a bit harder to understand. With this change you can say that `parentSpan` behaves the same and accepts the same as `withActiveSpan`.
See https://github.com/getsentry/sentry-docs/pull/10729

fix(tracing): Ensure you can pass `null` as `parentSpan` in `startSpan*`

---

dev-packages/node-integration-tests/src/index.ts
dev-packages/node-integration-tests/suites/tracing/httpIntegration/server-ignoreIncomingRequests.js
dev-packages/node-integration-tests/suites/tracing/httpIntegration/server-ignoreOutgoingRequests.js
dev-packages/node-integration-tests/suites/tracing/httpIntegration/test.ts
packages/node/src/integrations/http.ts

This PR fixes an oversight in our Node `httpIntegration`. It looks like we assumed that the `request` object being passed to `ignoreIncomingRequestHook` and `ignoreOutgoingRequestHook` was of the same type. However, it's not:
- `request` is of type `IncomingMessage` in `ignoreIncomingRequestHook`
- `request` is of type `RequestOptions` in `ignoreOutgoingRequestHook` 
In both cases though, we tried to obtain the url to pass into the `ignoreIncoming|outgoingRequests` callback via our `getUrl` helper function.  Since `IncomingMessage` doesn't have any of the properties required by `getUrl`, we always passed `///` to the `ignoreIncomingRequests` callback. 
This PR fixes the bug by simply taking the `request.url` property instead and adds integration tests to properly test the two options.
We …

fix(node): Ensure correct URL is passed to `ignoreIncomingRequests` callback

---

dev-packages/node-integration-tests/suites/tracing/httpIntegration/server-ignoreIncomingRequests.js
dev-packages/node-integration-tests/suites/tracing/httpIntegration/server-ignoreOutgoingRequests.js
dev-packages/node-integration-tests/suites/tracing/httpIntegration/test.ts
packages/node/src/integrations/http.ts

This PR adds a second parameter  (`request`) to the `httpIntegration`'s `ignoreIncomingRequests` and `ignoreOutgoingRequests` callbacks. This allows users to not only filter on the URL as previously but on the entire request objects.
Docs PR: https://github.com/getsentry/sentry-docs/pull/10735
ref https://github.com/getsentry/sentry-javascript/issues/12913

feat(node): Add `request` parameter to `httpIntegration` ignore callbacks

---

docs/gitflow.md

This adds docs about how to resolve gitflow merge conflicts.

docs: Add docs about resolving gitflow merge conflicts

---

CHANGELOG.md

Unfortunately, we missed adding a contributor to the changelog https://github.com/getsentry/sentry-javascript/pull/12932/files#r1679943685

meta(changelog): Add missing contributor attribution

---

packages/browser-utils/src/metrics/browserMetrics.ts

We saw instances of pageload transactions being dropped because they contained spans with negative durations (`timestamp` < `start_timestamp`).
After investigating it seems like performance entries by the browser are emitted with a negative duration. We could only observe this happening in Chrome.
The particular environment this could be (flakily) reproduced is on Chrome, for the scaffold Next.js app, with the Sentry SDK and Replay installed. The negative duration span that was recorded was for the replay worker resource.
[Other people](https://stackoverflow.com/questions/23191918/peformance-getentries-and-negative-duration-display) also seem to be running into this but so far I don't really understand why the duration is negative and how we would mitigate this properly. This PR is more …

fix(browser): Fix bug causing unintentional dropping of transactions

---

.github/workflows/build.yml

I noticed these while working on the cloudflare sdk.
- update browser path to use new replay packages
We were previously referencing `packages/replay`, which does not exist anymore. This updates us to use the correct paths.
- add vercel-edge to nextjs
The nextjs sdk depends on vercel-edge, so we should be running tests for it when that package changes.
- remove browser from deno
The deno sdk no longer relies on the browser sdk, this updates the paths accordingly
- add bun section
We can be smarter about CI time and only run bun tests when relevant package paths change.

chore: Update changed package paths

---

packages/vercel-edge/jest.config.js
packages/vercel-edge/package.json
packages/vercel-edge/test/async.test.ts
packages/vercel-edge/test/sdk.test.ts
packages/vercel-edge/test/transports/index.test.ts
packages/vercel-edge/test/wintercg-fetch.test.ts
packages/vercel-edge/tsconfig.test.json
packages/vercel-edge/vite.config.ts
yarn.lock

Before: `Time: 2.621 s`
After: `Duration 638ms (transform 343ms, setup 0ms, collect 1.61s, tests 22ms, environment 0ms, prepare 278ms)`
Also removes `edge-runtime/jest-environment` which we weren't using anyway, removes a lot of unnecessary stuff in our `yarn.lock` (-151 lines!)

test(vercel-edge): Switch to using vitest

---

packages/replay-worker/jest.config.js
packages/replay-worker/package.json
packages/replay-worker/test/unit/Compressor.test.ts
packages/replay-worker/tsconfig.test.json
packages/replay-worker/vite.config.ts

Before: `Time: 0.303 s`
After: `Duration  271ms (transform 28ms, setup 0ms, collect 26ms, tests 3ms, environment 0ms, prepare 68ms)`

test(replay): Switch to using vitest for replay worker

---

packages/replay-canvas/.eslintrc.js
packages/replay-canvas/jest.config.js
packages/replay-canvas/package.json
packages/replay-canvas/test/canvas.test.ts
packages/replay-canvas/tsconfig.test.json
packages/replay-canvas/vite.config.ts

Before: `Time:        2.026 s`
After: `Duration  960ms (transform 291ms, setup 0ms, collect 446ms, tests 5ms, environment 283ms, prepare 65ms)`
Also:
- removes unused `@babel/core` dev dep
- removes unused eslintrc logic

test(replay-canvas): Switch to using vitest

---

packages/nestjs/README.md

SentryCron was missing from the nest readme

docs(nestjs): Update README to include SentryCron

---

packages/feedback/src/core/integration.ts

Fixing a missing paranthesis to call `appendToDom` on `DOMContentLoaded` event.
Fixes #12970

fix(feedback): add a missing call of Actor.appendToDom method when DOMContentLoaded event is triggered

---

packages/angular/src/errorhandler.ts
packages/angular/test/errorhandler.test.ts

In this commit, we added cleanup logic to handle the removal of `afterSendEvent`, which is set up within the Angular error handler. This fixes memory leaks that occur when the event is still being handled after the root view is removed.

fix(angular): Remove `afterSendEvent` listener once root injector is destroyed

---

packages/vue/jest.config.js
packages/vue/package.json
packages/vue/test/errorHandler.test.ts
packages/vue/test/integration/VueIntegration.test.ts
packages/vue/test/integration/init.test.ts
packages/vue/test/router.test.ts
packages/vue/test/vendor/components.test.ts
packages/vue/tsconfig.test.json
packages/vue/vite.config.ts

Before: `Time: 3.935 s`
After: `Duration  1.55s (transform 961ms, setup 0ms, collect 3.56s, tests 127ms, environment 1.73s, prepare 367ms)`
If we remove the jsdom based tests it'll probably get even faster.
earlier attempt: https://github.com/getsentry/sentry-javascript/pull/11071
I'll try to do a couple of these a week when I'm blocked on some of my other tasks.

test(vue): Switch to using vitest

---

docs/changelog/v7.md

Sync with https://github.com/getsentry/sentry-javascript/edit/develop/docs/changelog/v7.md
Just keeping everything up to date.

chore: Add changelog entries for 7.118.0 and 7.117.0

---

packages/sveltekit/test/client/browserTracingIntegration.test.ts
packages/sveltekit/test/client/fetch.test.ts
packages/sveltekit/test/client/handleError.test.ts
packages/sveltekit/test/client/load.test.ts
packages/sveltekit/test/client/sdk.test.ts
packages/sveltekit/test/common/utils.test.ts
packages/sveltekit/test/index.test.ts
packages/sveltekit/test/server/handle.test.ts
packages/sveltekit/test/server/handleError.test.ts
packages/sveltekit/test/server/load.test.ts
packages/sveltekit/test/server/sdk.test.ts
packages/sveltekit/test/server/utils.test.ts
packages/sveltekit/test/vite/autoInstrument.test.ts
packages/sveltekit/test/vite/detectAdapter.test.ts
packages/sveltekit/test/vite/injectGlobalValues.test.ts
packages/sveltekit/test/vite/sentrySvelteKitPlugins.test.ts
packages/sveltekit/test/vite/sourceMaps.test.ts
packages/sveltekit/test/vite/svelteConfig.test.ts
packages/sveltekit/tsconfig.test.json
packages/sveltekit/vite.config.ts

I think we should follow vitest defaults here and explicitly import in the APIs that we need. This refactors our SvelteKit SDK tests to do so.
This change also removes `environment: 'jsdom'` from the sveltekit global vite config in favour of explicitly adding jsdom environment via the `@vitest-environment` pragma to the specific test file that needs it. This should means that our server tests are not polluted with jsdom globals, and that future writers have to explicitly opt-in to the behaviour.

test(sveltekit): Switch to explicit vitest imports

---

dev-packages/node-integration-tests/suites/express/tracing/tracesSampler/server.js
dev-packages/node-integration-tests/suites/express/tracing/tracesSampler/test.ts
packages/opentelemetry/src/sampler.ts
packages/opentelemetry/src/trace.ts
packages/opentelemetry/src/utils/parseSpanDescription.ts
packages/opentelemetry/test/trace.test.ts

Previously, we passed the span name directly to the `tracesSampler` as-is. However, this is not ideal because this does not match the name we actually send to sentry later, making this confusing. The reason is that we infer the name from the attributes for some types of spans, but we do that at export-time.
This PR adjust this so that we send the inferred name & attributes to the `tracesSampler`. This works reasonably enough. However, there is a big caveat: This still only has access to the initial attributes that a span has at creation time. This means that we'll never have e.g. the `http.route` correctly there, because all `http.server` spans originate from the http instrumentation where they do not have a route yet, and then more specific instrumentation (e.g. express or fastify) add …

fix(node): Pass inferred name & attributes to `tracesSampler`

---

.github/workflows/build.yml

Let's pin to Node `22.4` - there's a regression with `22.5` that affects us https://github.com/nodejs/node/issues/53902
We can revert this pin after they do a Node.js release.

build: Pin to Node 22.4

---

packages/vercel-edge/src/sdk.ts

Add the dedupe integration as a default integration to `vercel-edge`.
Saw this discrepancy while working on the cloudflare sdk.

feat(vercel-edge): Add dedupe as default integration

---

packages/astro/vite.config.ts
packages/nestjs/vite.config.ts
packages/replay-internal/vitest.config.ts
packages/solid/vite.config.ts
packages/solidstart/vite.config.ts
packages/svelte/vite.config.ts
packages/sveltekit/vite.config.ts

Something I noticed while doing my jest -> vitest conversions, we don't need this anymore.

test: Remove explict casting of baseconfig in vite configs

---

dev-packages/node-integration-tests/suites/express/setupExpressErrorHandler/server.js
dev-packages/node-integration-tests/suites/express/setupExpressErrorHandler/test.ts
packages/node/src/integrations/tracing/express.ts

Allows to pass this through to the underlying `expressErrorHandler`.
See https://github.com/getsentry/sentry-javascript/discussions/12715#discussioncomment-9965427

feat(express): Allow to pass options to `setupExpressErrorHandler`

---

.github/ISSUE_TEMPLATE/internal.yml

With the new issues UI (beta), our previous way of skipping issue templates for internally created issues doesn't work anymore. So this PR adds a new template that essentially mimics a blank issue. I decided to do this rather than setting 
```
blank_issues_enabled: true
```
in `config.yml` so that we can change the name of the template and mark it clearly as internal-only. Let's hope this works reasonably well.

chore(repo): Add internal blank issue template

---

packages/node/src/sdk/initOtel.ts

As mentioned in here: https://github.com/getsentry/sentry-javascript/issues/12912#issuecomment-2241308316 there is no way today to exclude/include esm modules when preloading today.
This PR adds the option to pass `registerEsmLoaderHooks` as option to `preloadOpenTelemetry`, which allows to exclude/include packages there as well. Users can then write their own custom `preload` script and configure this there, if wanted.
I chose to use the same option naming here than for `init`, although the semantics are a bit different - here we can't actually disable the wrapping (because that's the only reason to even call this). We can also use a different name if we want, but I thought this would maybe be easier to understand that this is the same thing 🤔

feat(node): Allow to pass `registerEsmLoaderHooks` to preload

---

dev-packages/node-integration-tests/suites/client-reports/drop-reasons/before-send/scenario.ts
dev-packages/node-integration-tests/suites/client-reports/drop-reasons/before-send/test.ts
dev-packages/node-integration-tests/suites/client-reports/drop-reasons/event-processors/scenario.ts
dev-packages/node-integration-tests/suites/client-reports/drop-reasons/event-processors/test.ts
dev-packages/node-integration-tests/suites/client-reports/periodic-send/scenario.ts
dev-packages/node-integration-tests/suites/client-reports/periodic-send/test.ts
dev-packages/node-integration-tests/utils/runner.ts
packages/browser/src/client.ts
packages/core/src/baseclient.ts
packages/node/src/sdk/client.ts
packages/node/src/sdk/index.ts
packages/node/src/types.ts
packages/node/test/helpers/mockSdkInit.ts
packages/types/src/options.ts

Resolves https://github.com/getsentry/sentry-javascript/issues/12822
This PR adds client reports to the Node.js SDK.
Client reports must be enabled via the `startClientReportTracking()` method on the `NodeClient`. This is due to the fact that client reports (or rather the `setInterval` that is required for periodically sending them) is acquiring a resource that needs cleanup. If somebody were to create clients over and over again, without calling `client.close()` they would be leaking memory.
If `startClientReportTracking()` is called, the client will flush all client reports
- every 60 seconds.
- on `process.on('beforeExit')`, which is when the event loop has run out of things to do.
Out of the box, the Node.js SDK's `Sentry.init()` will call `startClientReportTracking()`, since there we …

feat(node): Send client reports

---

dev-packages/e2e-tests/test-applications/nextjs-15/package.json

The need for the flag was removed in one of the latest canaries: https://github.com/vercel/next.js/pull/67856

test(e2e): Remove experimental intrumentation flag for Next.js `onRequestError` hook

---

packages/node/package.json
packages/node/src/types.ts
yarn.lock

`import-in-the-middle@1.10.0` supports regular expressions for `include` and `exclude`.
Is there a risk here that users might not have the latest version of `import-in-the-middle` in their dependencies?

feat: Extend ESM hooks options for iitm v1.10.0

---

packages/solid/test/errorboundary.test.tsx
packages/solid/test/sdk.test.ts
packages/solid/test/solidrouter.test.tsx
packages/solid/tsconfig.test.json
packages/solid/vite.config.ts

I think we should follow vitest defaults here and explicitly import in the APIs that we need. This refactors our Solid SDK tests to do so.
This change also removes `environment: 'jsdom'` from the vite config as it seems nothing needs this for solid. This should means that our tests are not polluted with jsdom globals, and that future writers have to explicitly opt-in to the behaviour.

test(solid): Switch to explicit vitest imports

---

packages/nuxt/README.md

Specify how Nuxt is set up on the server-side. Nuxt v3+ runs with ESM.

docs(nuxt): Add readme docs for server-side setup (ESM)

---

packages/svelte/test/config.test.ts
packages/svelte/test/performance.test.ts
packages/svelte/test/preprocessors.test.ts
packages/svelte/test/sdk.test.ts
packages/svelte/tsconfig.test.json
packages/svelte/vite.config.ts

I think we should follow vitest defaults here and explicitly import in the APIs that we need. This refactors our Svelte SDK tests to do so.
This change also removes `environment: 'jsdom'` from the vite config in favour of explicitly adding jsdom environment via the `@vitest-environment` pragma to the specific test file that needs it. This should means that our server tests are not polluted with jsdom globals, and that future writers have to explicitly opt-in to the behaviour.
I was also getting some ts errors in the tests, so addressed those as well.

test(svelte): Switch to explicit vitest imports

---

.github/workflows/build.yml

Reverts https://github.com/getsentry/sentry-javascript/pull/12980
We no longer need to pin to Node 22.4 now that Node 22.5.1 has been released.
https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V22.md#22.5.1

Revert "build: Pin to Node 22.4"

---

docs/publishing-a-release.md

Extending the "how to" with information about the new GitHub action.

docs(publish-release): Add information about external contributor GitHub Action

---

dev-packages/e2e-tests/test-applications/nuxt-3/components/ErrorButton.vue
dev-packages/e2e-tests/test-applications/nuxt-3/pages/client-error.vue
dev-packages/e2e-tests/test-applications/nuxt-3/pages/test-param/[param].vue
dev-packages/e2e-tests/test-applications/nuxt-3/tests/errors.client.test.ts
packages/nuxt/src/client/sdk.ts
packages/nuxt/src/common/types.ts
packages/nuxt/src/runtime/plugins/sentry.client.ts
packages/nuxt/test/client/sdk.test.ts

Adding the Vue BrowserTracing instrumentation to get parametrized routes.

feat(nuxt): Add vue-router instrumentation

---

dev-packages/browser-integration-tests/README.md

Figured having this written down might prove useful in the future :)

doc: Add `--ui` mode note to browser integration test Readme

---

packages/feedback/src/screenshot/components/ScreenshotEditor.tsx

This addition adds an intuitive way to resize screenshots in the user feedback widget. The draggable area is bound by the canvas box (so it won't overflow) and is only draggable when cropped (when confirm/cancel buttons present) 
https://github.com/user-attachments/assets/7ddff991-a791-4d41-a2ad-b278e1ab4950

feat (feedback) - Make cropped screenshot area draggable

---

.size-limit.js
packages/core/src/baseclient.ts
packages/core/test/lib/base.test.ts

Fixes https://github.com/getsentry/sentry-javascript/issues/12849.
This is a bit tricky because `beforeSendTransaction` can return a promise, so in order to avoid dealing with this I put the # of spans on the sdk metadata, and then compare that afterwards.

feat(core): Capture # of dropped spans through `beforeSendTransaction`

---

packages/node/src/sdk/index.ts
packages/node/test/sdk/init.test.ts

When using the SDK without tracing, the span processor is not required - we should reflect this in our validation logic.
While at it, I also improved the warning for not using the SentrySampler.

fix(node): Improve OTEL validation logic

---

.size-limit.js
dev-packages/e2e-tests/test-applications/react-router-6/package.json
dev-packages/e2e-tests/test-applications/react-router-6/server/app.js
dev-packages/e2e-tests/test-applications/react-router-6/src/index.tsx
dev-packages/e2e-tests/test-applications/react-router-6/src/pages/SSE.tsx
dev-packages/e2e-tests/test-applications/react-router-6/tests/sse.test.ts
packages/browser/src/tracing/browserTracingIntegration.ts
packages/browser/src/tracing/request.ts
packages/browser/test/unit/tracing/request.test.ts
packages/sveltekit/test/client/browserTracingIntegration.test.ts
packages/utils/src/instrument/fetch.ts
packages/utils/src/instrument/handlers.ts
packages/utils/src/instrument/index.ts

This PR makes spans for client-side fetch calls more accurate by cloning the response and adapting the span `endTimestamp` when the stream has been resolved.
fixes [#12640](https://github.com/getsentry/sentry-javascript/issues/12640)

feat(core): Adapt spans for client-side fetch to streaming responses

---

packages/cloudflare/README.md
packages/cloudflare/package.json
packages/cloudflare/src/client.ts
packages/cloudflare/src/handler.ts
packages/cloudflare/src/index.ts
packages/cloudflare/src/integrations/fetch.ts
packages/cloudflare/src/sdk.ts
packages/cloudflare/src/vendor/stacktrace.ts
packages/cloudflare/test/handler.test.ts
packages/cloudflare/test/integrations/fetch.test.ts
packages/cloudflare/test/sdk.test.ts
packages/utils/src/instrument/fetch.ts
yarn.lock

before reviewing this PR, I recommend reading through a writeup I did: https://github.com/getsentry/sentry-javascript/discussions/13007
This PR adds `withSentry`, a method that wraps your cloudflare worker handler to add Sentry instrumentation. The writeup above explains why we need to do this over just a regular `Sentry.init` call.
The implementation of `withSentry` is fairly straightforward, wrapping the fetch handler in the cloudflare worker with:
1. `withIsolationScope` to isolate it from other concurrent requests
2. helpers to update scope with relevant contexts/request
3. `continueTrace` to continue distributed tracing
4. `startSpan` to track spans
Usage looks something like so:
```ts
import * as Sentry from …
```

feat(cloudflare): Add `withSentry` method

---

CHANGELOG.md

Explicitly add a changelog entry for cloudflare so it's ready to go whenever the team decides to do a release.

chore: Add changelog entry for cloudflare

---

dev-packages/browser-integration-tests/suites/feedback/captureFeedback/init.js
dev-packages/browser-integration-tests/suites/feedback/captureFeedbackAndReplay/hasSampling/init.js
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/init.js
dev-packages/browser-integration-tests/utils/generatePlugin.ts
dev-packages/browser-integration-tests/utils/helpers.ts
packages/browser/rollup.bundle.config.mjs
packages/browser/src/integrations-bundle/index.feedback.ts
packages/feedback/rollup.bundle.config.mjs

Fixes https://github.com/getsentry/sentry-javascript/issues/13080
This was basically just wrong - we need stuff from `browser` package there, so we can't really build the final CDN bundle from the feedback-internal package.
I moved this over and also adjusted tests to actually test this with pluggable CDN integrations as well.

fix(feedback): Ensure pluggable feedback CDN bundle is correctly built

---

packages/nuxt/src/module.ts
packages/nuxt/src/runtime/plugins/sentry.server.ts
packages/nuxt/src/runtime/utils.ts
packages/nuxt/test/server/runtime/plugin.test.ts

Also changes the `findDefaultSdkInitFile` function as the backend-related file is located and named differently than the client config file (`sentry.client.config.ts` and `public/instrument.server.mjs`).
closes https://github.com/getsentry/sentry-javascript/issues/13097

feat(nuxt): Add connected tracing meta tags

---

dev-packages/e2e-tests/test-applications/solidstart/package.json
dev-packages/e2e-tests/test-applications/solidstart/src/entry-client.tsx
dev-packages/e2e-tests/test-applications/solidstart/src/instrument.server.mjs
dev-packages/e2e-tests/test-applications/solidstart/src/routes/index.tsx
dev-packages/e2e-tests/test-applications/solidstart/src/routes/server-error.tsx
dev-packages/e2e-tests/test-applications/solidstart/src/routes/users/[id].tsx
dev-packages/e2e-tests/test-applications/solidstart/tests/errors.server.test.ts
dev-packages/e2e-tests/test-applications/solidstart/tests/performance.server.test.ts
packages/solidstart/package.json
packages/solidstart/rollup.npm.config.mjs
packages/solidstart/src/index.types.ts
packages/solidstart/src/server/index.ts
packages/solidstart/src/server/utils.ts
packages/solidstart/src/server/withServerActionInstrumentation.ts
packages/solidstart/test/server/withServerActionInstrumentation.test.ts
scripts/node-unit-tests.ts

Can be used like this:
```js
const getUserData = async () => {
'use server';
return await withServerActionInstrumentation('getData', () => {
return { prefecture: 'Kanagawa' };
});
};
```
Shows up like this:
Can also be used for api routes like this:
```js
export async function GET() {
return await withServerActionInstrumentation('getUser', () => {
return json({ prefecture: 'Akita' })
})
}
```
Shows up like this for pageloads on a route that makes a fetch call to an api route

feat(solidstart): Add server action instrumentation helper

---

packages/astro/test/client/sdk.test.ts
packages/astro/test/integration/index.files.test.ts
packages/astro/test/integration/index.test.ts
packages/astro/test/integration/middleware/index.test.ts
packages/astro/test/integration/snippets.test.ts
packages/astro/tsconfig.test.json
packages/astro/vite.config.ts

I think we should follow vitest defaults here and explicitly import in the APIs that we need. This refactors our Astro SDK tests to do so.
I also went ahead and fixed up some TS errors in some tests.
This change also removes `environment: 'jsdom'` from the vite config as it seems nothing needs this for astro. This should means that our tests are not polluted with jsdom globals, and that future writers have to explicitly opt-in to the behaviour.

test(astro): Switch to explicit vitest imports

---

dev-packages/e2e-tests/test-applications/nextjs-app-dir/assert-build.ts
packages/nextjs/src/config/webpackPluginOptions.ts

Fixes https://github.com/getsentry/sentry-javascript/issues/13099
For currently unknown reasons, deleting the serverside sourcmaps will crash Vercel deployments during build. Working theory is that some manifest references the files, and Vercel tries to upload the files but they're missing when Vercel gets to actually uploading them.

fix(nextjs): Only delete clientside bundle source maps with `sourcemaps.deleteFilesAfterUpload`

---

dev-packages/browser-integration-tests/utils/fixtures.ts
dev-packages/browser-integration-tests/utils/generatePlugin.ts

This PR fixes a nasty problem in our browser integration test setup that caused our current release 8.21.0 to fail.
In #13081 we re-introduced testing against the feedback addon CDN bundles in our integration tests. This triggered a test fail on release branches but it remained undiscovered in `develop` and feature branches. Chain of events:
- The addon feedback CDN bundle now correctly exports the async feedback integration
- The async feedback integration lazy-loads the modal and screenshot integrations
- To avoid actually lazy loading these via http requests to the CDN but to test against the locally built versions, we added a couple of request interceptors in our `getLocalTestPath` fixture setup function.
- This interceptor however, would just silently fail if it didn't find the local …

fix(browser-integration-tests): Fix feedback addon CDN bundle integration test setup

---

packages/node/package.json
packages/nuxt/README.md
yarn.lock

ref https://github.com/nodejs/import-in-the-middle/releases/tag/import-in-the-middle-v1.11.0
ref https://github.com/getsentry/sentry-javascript/issues/12806
Bumping this for the bug fix, we can expose the `registerOptions` in another PR.

feat(node): Upgrade import-in-the-middle to 1.11.0

---

packages/replay-internal/src/replay.ts
packages/replay-internal/src/types/replay.ts
packages/replay-internal/src/util/addEvent.ts

We currently have no visibility when this client report happens. Lets capture the exception if our experimental flag is on.
Also refactors `_handleException()` to be a public method instead of private.

feat(replay): Capture exception when `internal_sdk_error` client report happens

---

dev-packages/e2e-tests/test-applications/nestjs-basic/src/app.controller.ts
dev-packages/e2e-tests/test-applications/nestjs-basic/src/app.service.ts
dev-packages/e2e-tests/test-applications/nestjs-basic/tests/errors.test.ts
dev-packages/e2e-tests/test-applications/node-nestjs-basic/src/app.controller.ts
dev-packages/e2e-tests/test-applications/node-nestjs-basic/src/app.service.ts
dev-packages/e2e-tests/test-applications/node-nestjs-basic/tests/errors.test.ts
packages/nestjs/src/setup.ts
packages/node/src/integrations/tracing/nest.ts

So far we are filtering exceptions on the status code and do not report 4xx errors. However, we actually only want to capture unexpected exceptions but all HttpExceptions are only ever thrown explicitly. Hence, we do not want to capture them and they should be filtered.
In `@sentry/nest` we can use the nest `HttpException` directly, since we have `@nest/common` as a dependency. In `@sentry/node` this is not the case, so we filter based on whether a property called status is defined.

feat(nestjs): Filter all HttpExceptions

---

packages/nextjs/src/config/loaders/valueInjectionLoader.ts
packages/sveltekit/src/vite/injectGlobalValues.ts
packages/sveltekit/test/vite/injectGlobalValues.test.ts

Since v8, all platforms and versions we support have support for `globalThis`. Since [this PR](https://github.com/getsentry/sentry-javascript/pull/11351) we also use `globalThis` when reading these injectected values.

fix: Use `globalThis` for code injection

---

dev-packages/e2e-tests/test-applications/nestjs-basic/src/app.controller.ts
dev-packages/e2e-tests/test-applications/nestjs-basic/src/example.guard.ts
dev-packages/e2e-tests/test-applications/nestjs-basic/tests/transactions.test.ts
dev-packages/e2e-tests/test-applications/node-nestjs-basic/src/app.controller.ts
dev-packages/e2e-tests/test-applications/node-nestjs-basic/src/example.guard.ts
dev-packages/e2e-tests/test-applications/node-nestjs-basic/tests/transactions.test.ts
packages/node/src/integrations/tracing/nest.ts

Adds automatic instrumentation to `@sentry/nestjs`. Guards in nest have a `@Injectable` decorator and implement a `canActivate` function. So we can simply extend the existing instrumentation to add a proxy for `canActivate`.
Also fixed a mistake with the middleware instrumentation (missing return).
Screenshot from sample app:

feat(nestjs): Automatic instrumentation of nestjs guards 

---

.github/workflows/build.yml
package.json
scripts/node-unit-tests.ts

This PR updates our unit test runner on CI to only run unit tests for packages that have been changed.
In addition, it also updates the list of packages to run in node/browser only unit test envs - we've been running some in both. We only actually need to run the fully-browser-only unit tests in the "Browser Unit Tests" job, the rest (including e.g. core, ...) runs in the node unit tests in all node versions.
In a follow up step, maybe we can further streamline this and simply run only unit tests and ensure that e.g. the browser ones only run in one of the node versions, not all of them. Or find another way that does not require us to keep 2 lists of packages in separate places. But for now, this should be an improvement.
I opened a test PR to show this in action, where only something in …

ci: Only run affected unit tests on PRs

---

dev-packages/e2e-tests/test-applications/nestjs-basic/src/app.controller.ts
dev-packages/e2e-tests/test-applications/nestjs-basic/tests/transactions.test.ts
dev-packages/e2e-tests/test-applications/node-nestjs-basic/src/app.controller.ts
dev-packages/e2e-tests/test-applications/node-nestjs-basic/tests/transactions.test.ts
packages/node/src/integrations/tracing/nest.ts

Adds automatic instrumentation of pipes to `@sentry/nestjs`. Pipes in nest have a `@Injectable` decorator and implement a `transform` function. So we can simply extend the existing instrumentation to add a proxy for `transform`.
Screenshot from sample app:

feat(nestjs): Automatic instrumentation of nestjs pipes

---

packages/cloudflare/README.md
packages/cloudflare/src/d1.ts
packages/cloudflare/src/index.ts
packages/cloudflare/test/d1.test.ts

resolves https://github.com/getsentry/sentry-javascript/issues/13141
This PR adds a new method to the cloudflare SDK, `instrumentD1WithSentry`. This method can be used to instrument [Cloudflare D1](https://developers.cloudflare.com/d1/), Cloudflare's serverless SQL database.
```js
// env.DB is the D1 DB binding configured in your `wrangler.toml`
const db = instrumentD1WithSentry(env.DB);
// Now you can use the database as usual
await db.prepare('SELECT * FROM table WHERE id = ?').bind(1).run();
```
The reason this has to be a standalone wrapper method instead of an integration is because the cloudflare d1 instance can be bound to any arbitrary environmental variable as per user config. This is why the snippet above shows `env.DB` being passed into `instrumentD1WithSentry`. `env.DB` can …

feat(cloudflare): Add Cloudflare D1 instrumentation

---

dev-packages/e2e-tests/test-applications/nestjs-basic/src/app.controller.ts
dev-packages/e2e-tests/test-applications/nestjs-basic/src/app.service.ts
dev-packages/e2e-tests/test-applications/nestjs-basic/src/example.interceptor.ts
dev-packages/e2e-tests/test-applications/nestjs-basic/tests/transactions.test.ts
dev-packages/e2e-tests/test-applications/node-nestjs-basic/src/app.controller.ts
dev-packages/e2e-tests/test-applications/node-nestjs-basic/src/app.service.ts
dev-packages/e2e-tests/test-applications/node-nestjs-basic/src/example.interceptor.ts
dev-packages/e2e-tests/test-applications/node-nestjs-basic/tests/transactions.test.ts
packages/nestjs/src/setup.ts
packages/node/src/integrations/tracing/nest.ts

Adds automatic instrumentation of interceptors to `@sentry/nestjs`. Interceptors in nest have a `@Injectable` decorator and implement a `intercept` function. So we can simply extend the existing instrumentation to add a proxy for `intercept`.
Current screenshot from my sample app:
Remark: Interceptors allow users to add functionality before and after a route handler is called. This PR adds tracing to whatever happens before the route is executed. I am still figuring out how to trace any instructions after the route was executed. Will do that in a separate PR.

feat(nestjs): Automatic instrumentation of nestjs interceptors before route execution

---

packages/browser/src/sdk.ts
packages/browser/test/sdk.test.ts

This PR relaxes our browser extension detection check. The idea is to avoid showing the error message and blocking `Sentry.init` if the SDK is not initialized in a `window` global scope. For instance, this will allow `Sentry.init` to be executed in (service) workers. We likely don't need to worry about multiple SDK instance collisions in non-`window` global scopes.
We discussed this a bit internally and there are some caveats to this. Using the browser SDK in workers is a bit problematic as many global APIs are not available in there. However, we currently instruct users [to do just that](https://docs.sentry.io/platforms/javascript/best-practices/web-workers/). Long-term, it'd be valuable to have a worker SDK that doesn't expect certain browser/Window APIs to be present at all. …

fix(browser): Avoid showing browser extension error message in non-`window` global scopes

---

.github/workflows/build.yml
package.json

I accidentally broke this, not properly ignoring the dev packages for the `test:ci:browser` command 😬

ci: Fix non-PR unit tests

---

packages/nextjs/README.md

Ephasis of this PR:
- Fix wrong minimum supported version.
- Get rid of outdated TypeDoc link
- Put more emphasis on going to the getting started doc
- Include wizard snippet
- Remove `setExtra` call
- Remove potentially confusing captureEventCall

docs(nextjs): Update Next.js readme

---

packages/browser-utils/src/metrics/browserMetrics.ts

ref(browser): Improve browserMetrics collection

---

.github/workflows/build.yml
packages/profiling-node/bindings/cpu_profiler.cc

Upgrade action to artifacts v4 (previous version did some convenient merging for us)

build: upgrade artifacts actions to v4

---

dev-packages/browser-integration-tests/utils/staticAssets.ts

Our playwright tests can be flakey caused by the build process when generating static assets. Even though we check if file exists before symlinking, it can at times fail because file already exists. I have not dug/thought about why this happens -- just catch/ignore and move on.
Closes https://github.com/getsentry/sentry-javascript/issues/11902

test: Fix flakey Playwright tests due to static assets

---

packages/cloudflare/README.md
packages/cloudflare/package.json
packages/cloudflare/src/handler.ts
packages/cloudflare/src/request.ts
packages/cloudflare/src/scope-utils.ts
packages/cloudflare/src/sdk.ts
packages/cloudflare/test/handler.test.ts
yarn.lock

resolves https://github.com/getsentry/sentry-javascript/issues/13112
This PR adds instrumentation for the [`scheduled` handler](https://developers.cloudflare.com/workers/runtime-apis/handlers/scheduled/) in cloudflare workers. This is used for cron triggers.
I elected to not do automatic cron instrumentation for now, this is tracked by https://github.com/getsentry/sentry-javascript/issues/13113. Instead I added manual instrumentation docs to the README, this will get copied to the sentry docs eventually.

feat(cloudflare): instrument scheduled handler

---

packages/feedback/src/core/integration.ts

Updates `_loadAndRenderDialog` to call `dialog.close()` in the `onFormClose` and `onFormSubmitted` callbacks.
Motivation: over at Codecov, we're modifying our user feedback setup so that we have two different feedback integrations, one using the default widget with `createWidget`, and one that is triggered by a button in our help dropdown with `createForm`. After adding these we noticed what seems to be a bug where the `createForm` form does not clear the `overflow: hidden` style on the body when the modal is closed, while the `createWidget` form does clear this style. We currently have added a callback on our end that manually resets the overflow style, but I'm currently revisiting this code again and I thought why not see if we can fix it upstream here 🙂
Here's a gif of the issue: …

fix(feedback): Call dialog.close() in dialog close callbacks in _loadAndRenderDialog

---

packages/cloudflare/README.md
packages/cloudflare/src/index.ts
packages/cloudflare/src/pages-plugin.ts
packages/cloudflare/test/pages-plugin.test.ts

While working on adding the cloudflare sdk to some open source projects, I noticed that setup for the cloudflare plugin was a bit of a hassle when you needed access to environmental variables.
This PR allows users to pass a function to `sentryPagesPlugin` that looks like so:
```ts
handler: (context: EventPluginContext<Env, Params, Data, PluginParams>) => CloudflareOptions
```
This means that users can access the cloudflare `context` (which only exists at the request level) to get environmental variables. 
```javascript
export const onRequest = Sentry.sentryPagesPlugin(context => ({
dsn: context.env.SENTRY_DSN,
}));
```
To make some other use cases easier, this PR also exposes the `wrapRequestHandler` API to users.

feat(cloudflare): Allow users to pass handler to sentryPagesPlugin

---

dev-packages/node-integration-tests/suites/express/without-tracing/test.ts

The node integration test runner depends on event order. We cannot assert on that.
Fixes https://github.com/getsentry/sentry-javascript/issues/13177

ci: Unflake #13177

---

dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals-lcp/test.ts

This test is quite flakey -- most of the time it correctly has the image as LCP, but sometimes it will report the button as LCP. I have tried fixing it by waiting for image to load, but it did not work. I wonder if it is a bug with our LCP reporting?

test: Soft skip flakey LCP test

---

packages/solidstart/src/server/sdk.ts
packages/solidstart/src/server/utils.ts
packages/solidstart/test/server/sdk.test.ts
packages/types/src/eventprocessor.ts

feat(solidstart): Filter out low quality transactions for build assets

---

packages/solidstart/README.md
packages/solidstart/package.json
packages/solidstart/rollup.npm.config.mjs
packages/solidstart/src/middleware.ts
packages/solidstart/test/middleware.test.ts
packages/solidstart/tsconfig.subexports-types.json
packages/solidstart/tsconfig.types.json

Works by adding the Sentry middlware to your `src/middleware.ts` file:
```typescript
import { sentryBeforeResponseMiddleware } from '@sentry/solidstart/middleware';
import { createMiddleware } from '@solidjs/start/middleware';
export default createMiddleware({
onBeforeResponse: [
sentryBeforeResponseMiddleware(),
// Add your other middleware handlers after `sentryBeforeResponseMiddleware`
],
});
```
And specifying `./src/middleware.ts` in `app.config.ts`
Closes: https://github.com/getsentry/sentry-javascript/issues/12551

feat(solidstart): Add sentry `onBeforeResponse` middleware to enable distributed tracing

---

.github/actions/install-playwright/action.yml
.github/workflows/build.yml
.github/workflows/flaky-test-detector.yml

We used to include the playwright binaries in the general dependency cache, which inflated this for no reason. Now, this is not included there anymore.
Additionally, I extracted the code to install & cache playwright into a composite action, making it easier to reuse it.

ci: Cache playwright separately

---

dev-packages/e2e-tests/test-applications/nestjs-basic/package.json
dev-packages/e2e-tests/test-applications/nestjs-basic/src/app.controller.ts
dev-packages/e2e-tests/test-applications/nestjs-basic/src/app.service.ts
dev-packages/e2e-tests/test-applications/nestjs-basic/tests/errors.test.ts
dev-packages/e2e-tests/test-applications/node-nestjs-basic/package.json
dev-packages/e2e-tests/test-applications/node-nestjs-basic/src/app.controller.ts
dev-packages/e2e-tests/test-applications/node-nestjs-basic/src/app.service.ts
dev-packages/e2e-tests/test-applications/node-nestjs-basic/tests/errors.test.ts
packages/nestjs/package.json
packages/nestjs/src/setup.ts
packages/node/src/integrations/tracing/nest/nest.ts
packages/node/src/integrations/tracing/nest/types.ts
yarn.lock

`RpcExceptions` are always explicitly thrown in nest. Therefore, they are expected for users and should not be sent to Sentry.
This PR filters these exceptions. In `@sentry/nestjs` we can simply use `instanceof RpcExceptions` to achieve this. In `@sentry/node` we do not have access to this class, so we need to check based on a property.
[ref](https://github.com/getsentry/sentry-javascript/issues/13190)

feat(nestjs): Filter RPC exceptions

---

dev-packages/browser-integration-tests/suites/integrations/lazyLoad/feedbackIntegration/init.js
dev-packages/browser-integration-tests/suites/integrations/lazyLoad/feedbackIntegration/subject.js
dev-packages/browser-integration-tests/suites/integrations/lazyLoad/feedbackIntegration/test.ts
dev-packages/rollup-utils/plugins/bundlePlugins.mjs
packages/browser/src/utils/lazyLoadIntegration.ts
packages/integration-shims/src/Feedback.ts

This was brought up in slack - if you use a CDN bundle (or the loader) without feedback included, and you try to lazy-load the feedbackIntegration, it fails as of today. The reason is that we check if `window.Sentry.feedbackIntegration` exists, which it _does_, because we register a shim integration for compatibility in the loader.
So this PR adds a property on the shim integration which we can check for during lazy loading. While at it, I also added a missing method to the feedback integration shim.

fix(feedback): Ensure feedback can be lazy loaded in CDN bundles

---

dev-packages/e2e-tests/test-applications/nestjs-basic/src/app.controller.ts
dev-packages/e2e-tests/test-applications/nestjs-basic/tests/errors.test.ts
dev-packages/e2e-tests/test-applications/nestjs-with-submodules/src/app.controller.ts
dev-packages/e2e-tests/test-applications/nestjs-with-submodules/tests/errors.test.ts
dev-packages/e2e-tests/test-applications/node-nestjs-basic/src/app.controller.ts
dev-packages/e2e-tests/test-applications/node-nestjs-basic/tests/errors.test.ts

Adding a separate flush endpoint that flushes the client in the application so that we can remove the timeout await and speed up tests.

tests(e2e): Remove await timeout in nest e2e tests

---

packages/utils/src/instrument/fetch.ts

fixes [#13220](https://github.com/getsentry/sentry-javascript/issues/13220)

fix: Guard getReader function for other fetch implementations

---

packages/core/src/utils/hasTracingEnabled.ts

A very small PR that should shave off a couple of bytes of `hasTracingEnabled`.
Inlining the function removes the function declaration from the bundle.

ref(core): Reduce `hasTracingEnabled` size

---

packages/astro/src/client/sdk.ts
packages/astro/test/client/sdk.test.ts

The bundler-plugins still refer to the option as `excludePerformanceMonitoring` ([here](https://github.com/getsentry/sentry-javascript-bundler-plugins/blob/main/packages/bundler-plugin-core/src/types.ts#L260)), but this is going to be renamed to `excludeTracing`, so I already used the new naming as discussed with @Lms24 and @mydea.
closes https://github.com/getsentry/sentry-javascript/issues/13013

feat(astro): Always add BrowserTracing

---

packages/browser/test/utils/lazyLoadIntegration.test.ts

Fixes https://github.com/getsentry/sentry-javascript/issues/13184
We can now await here because we use `vitest`, so there should be no jsdom problems :)
But really these tests should live in playwright instead.

test(browser): Fix flaky test in test/utils/lazyLoadIntegration.test.ts

---

packages/nestjs/test/sdk.test.ts
packages/nestjs/tsconfig.test.json

I think we should follow vitest defaults here and explicitly import in the APIs that we need. This refactors our Nestjs SDK tests to do so.

test(nestjs): Switch to explicit vitest imports

---

dev-packages/node-integration-tests/suites/express/multiple-init/server.ts

https://github.com/getsentry/sentry-javascript/actions/runs/10263576392/job/28396005694

test: Fix flakey integration test

---

dev-packages/node-integration-tests/.eslintrc.js
dev-packages/node-integration-tests/suites/tracing/meta-tags/test.ts

Discovered today that TS 3.8 doesn't understand `// @ts-expect-error`. Since we test on Node 22 also with TS 3.8, we shouldn't use `ts-expect-error` in test files as TS 3.8 would simply ignore the comment and throw a type error.
Instead, it's fine to use `@ts-ignore` in these test files.

chore(lint): Allow `ts-ignore` in Node integration tests

---

.github/workflows/flaky-test-detector.yml
dev-packages/browser-integration-tests/suites/replay/slowClick/mutation/test.ts

Attempts to fix https://github.com/getsentry/sentry-javascript/issues/13223

test: Unflake slow click test

---

.size-limit.js
packages/browser/src/sdk.ts
packages/browser/test/sdk.test.ts

While working on E2E tests for TwP in meta frameworks, I noticed that we have erroneous logic in the browser SDK init code: If users or our higher-level SDKs pass `defaultIntegrations: undefined` to the Browser SDK's init options, it deactivates all default integrations. As per our docs, this should only happen if you explicitly pass `defaultIntegrations: false`. 
This is caused by us spreading user-passed options over default SDK options, meaning previously set default options get overridden by users options being explicitly `undefined` instead of not set. 
This PR fixes this by removing the `defaultIntegrations` key from the user options object before merging the options together. Long-term, we need to fix this properly for all user-passed options. This is blocked on …

fix(browser): Initialize default integration if `defaultIntegrations: undefined`

---

packages/solidstart/README.md

Working sourcemap upload via our vite-plugin:

chore(solidstart): Add sourcemap instructions to README

---

packages/solidstart/src/middleware.ts
packages/solidstart/test/middleware.test.ts

ref(solidstart): Use core's getTraceMetaTags over own implementation

---

packages/aws-serverless/rollup.npm.config.mjs
packages/aws-serverless/src/integration/awslambda.ts
packages/aws-serverless/src/sdk.ts
packages/aws-serverless/src/utils.ts
packages/aws-serverless/test/utils.test.ts

Currently, the AWS otel integration (and our `wrapHandler` fallback) try to extract sentry trace data from the `event` object passed to a Lambda call. The aws-sdk integration, however, places tracing data onto `context.clientContext.Custom`.
This PR adds a custom `eventContextExtractor` that attempts extracting sentry trace data from the `context`, with a fallback to `event` to enable distributed tracing among Lambda invocations.
Traces are now connected. Here an example:
`Lambda-A` calling `Lambda-B`:
```
import { LambdaClient, InvokeCommand } from "@aws-sdk/client-lambda";
import * as Sentry from "@sentry/aws-serverless";
export const handler = Sentry.wrapHandler(async (event, context) => {
const client = new LambdaClient();
const command = new InvokeCommand({
FunctionName: `Lambda-B`, …
```

fix(aws-serverless): Extract sentry trace data from handler `context` over `event`

---

dev-packages/node-integration-tests/suites/tracing/apollo-graphql/apollo-server.js
dev-packages/node-integration-tests/suites/tracing/apollo-graphql/scenario-mutation.js
dev-packages/node-integration-tests/suites/tracing/apollo-graphql/scenario-query.js
dev-packages/node-integration-tests/suites/tracing/apollo-graphql/test.ts
dev-packages/node-integration-tests/suites/tracing/apollo-graphql/useOperationNameForRootSpan/scenario-invalid-root-span.js
dev-packages/node-integration-tests/suites/tracing/apollo-graphql/useOperationNameForRootSpan/scenario-multiple-operations-many.js
dev-packages/node-integration-tests/suites/tracing/apollo-graphql/useOperationNameForRootSpan/scenario-multiple-operations.js
dev-packages/node-integration-tests/suites/tracing/apollo-graphql/useOperationNameForRootSpan/scenario-mutation.js
dev-packages/node-integration-tests/suites/tracing/apollo-graphql/useOperationNameForRootSpan/scenario-no-operation-name.js
dev-packages/node-integration-tests/suites/tracing/apollo-graphql/useOperationNameForRootSpan/scenario-query.js
dev-packages/node-integration-tests/suites/tracing/apollo-graphql/useOperationNameForRootSpan/test.ts
packages/node/src/integrations/tracing/graphql.ts
packages/opentelemetry/src/index.ts
packages/opentelemetry/src/semanticAttributes.ts
packages/opentelemetry/src/utils/parseSpanDescription.ts
packages/opentelemetry/src/utils/spanTypes.ts
packages/opentelemetry/test/utils/spanTypes.test.ts

This introduces a new option for the `graphqlIntegration`, `useOperationNameForRootSpan`, which is by default `true` but can be disabled in integration settings like this: `Sentry.graphqlIntegration({ useOperationNameForRootSpan: true })`.
With this setting enabled, the graphql instrumentation will update the `http.server` root span it is in (if there is one)  will be appended to the span name. So instead of having all root spans be `POST /graphql`, the names will now be e.g. `POST /graphql (query MyQuery)`.
If there are multiple operations in a single http request, they will be appended like `POST /graphql (query Query1, query Query2)`, up to a limit of 5, at which point they will be appended as `+2` or similar.
Closes https://github.com/getsentry/sentry-javascript/issues/13238

feat(node): Add `useOperationNameForRootSpan` to`graphqlIntegration`

---

.github/actions/install-playwright/action.yml
.github/workflows/build.yml

This PR streamlines our browser integration tests a bit more:
1. We now only install chromium for playwright tests in most places. This may help cut down test run time a bit, as we do not need to install native dependencies for webkit and firefox everywhere.
2. I changed how we split the matrix jobs for the browser integration tests. Previously, we sharded this via playwright. Now, we only do this for esm tests, which we now only run in chromium, not all browsers. Only the full bundle tests are run in all browsers (they are considerably faster than the esm tests...), and there we now do not use sharding, but have one matrix job for chromium (default), one for webkit and one for firefox (where each can only install the native dependencies it needs).
3. I renamed the jobs a bit so that we …

ci: Streamline CI browser playwright tests

---

packages/remix/src/utils/integrations/opentelemetry.ts
packages/remix/test/integration/test/server/instrumentation-otel/loader.test.ts

Noticed here: https://github.com/getsentry/sentry-javascript/pull/13282 that we are not correctly setting origin for remix spans.

fix(remix): Ensure `origin` is correctly set for remix server spans

---

packages/astro/src/server/middleware.ts
packages/astro/test/server/middleware.test.ts

This PR fixes a bug in the Astro SDK which would emerge if users configured their app as SSR output `hybrid` or `server` but also had static routes. 
In Astro middleware, we're not allowed to access the `request.headers` object if the incoming request is for a statically generated/prerendered route. Since we accessed these headers previously, users would get a warning as reported multiple times and tracked in https://github.com/getsentry/sentry-javascript/issues/13116
fixes https://github.com/getsentry/sentry-javascript/issues/13116
Note: While working on this, I discovered another bug which I'll fix in a follow-up PR. Also, I'll finally add an e2e test app.

fix(astro): Only track access request headers in dynamic page requests

---

.github/workflows/build.yml
packages/opentelemetry/README.md

Noticed that we still called this out as alpha, even though it is not.

docs: Remove alpha message for `@sentry/opentelemetry`

---

packages/astro/src/server/middleware.ts
packages/astro/test/server/middleware.test.ts

builds on top of #13306, found while working on #13116
This PR ensures that we correctly extract the request data in our Astro middleware. Previously we didn't convert the `request.headers` object into a `Record<string, string>` but simply passed a `Headers` instance. This caused problems with the `requestDataIntegration` which doesn't handle the instance correctly.

fix(astro): Correctly extract request data

---

dev-packages/node-integration-tests/suites/tracing/meta-tags-twp/server.js
dev-packages/node-integration-tests/suites/tracing/meta-tags-twp/test.ts
packages/astro/src/server/middleware.ts
packages/core/src/asyncContext/types.ts
packages/core/src/index.ts
packages/core/src/utils/meta.ts
packages/core/src/utils/traceData.ts
packages/core/test/lib/utils/traceData.test.ts
packages/opentelemetry/src/asyncContextStrategy.ts
packages/opentelemetry/src/utils/getTraceData.ts
packages/types/src/index.ts
packages/types/src/tracing.ts

This PR adds an Otel-specific version of `getTraceData` and adds the `getTraceData` function to the `AsyncContextStrategy` interface. This allows us to dynamically choose either the default implementation (which works correctly for browser/non-POTEL SDKs) and the Otel-specific version.
Our previous, universal implementation of  `getTraceData` didn't propagate the correct trace data in POTEL SDKs in Tracing Without Performance mode. The reason is that even in TwP mode, we start a non-recording span which is available via `getActiveSpan`. The previous implementation would therefore incorrectly take trace data from this span and even more incorrectly add a negative sampling decision to the trace data instead of deferring it.
Another change in this PR is that I removed the optional parameters …

feat(core): Add OpenTelemetry-specific `getTraceData` implementation

---

packages/browser/src/sdk.ts
packages/browser/test/sdk.test.ts

Add `safari-web-extension:` to the list of allowed extension protocols. This chage should allow sentry/browser to work in safari browser extensions.

feat(browser): allow sentry in safari extension background page

---

dev-packages/external-contributor-gh-action/index.mjs

Tiny PR but just noticed that we should write "thank you for your contribution**s**" if we credit multiple contributors in a changelog entry.

chore(ci): Adjust contribution message for multiple contributors

---

packages/sveltekit/src/client/sdk.ts
packages/sveltekit/test/client/sdk.test.ts

closes https://github.com/getsentry/sentry-javascript/issues/13011
ref: https://github.com/getsentry/sentry-javascript/pull/13318

feat(sveltekit): Always add browserTracingIntegration

---

dev-packages/e2e-tests/test-applications/nuxt-3/app.vue
dev-packages/e2e-tests/test-applications/nuxt-3/nuxt.config.ts
dev-packages/e2e-tests/test-applications/nuxt-3/pages/fetch-server-error.vue
dev-packages/e2e-tests/test-applications/nuxt-3/pages/test-param/[param].vue
dev-packages/e2e-tests/test-applications/nuxt-3/server/api/param-error/[param].ts
dev-packages/e2e-tests/test-applications/nuxt-3/server/api/server-error.ts
dev-packages/e2e-tests/test-applications/nuxt-3/server/api/test-param/[param].ts
packages/nuxt/src/module.ts

Adds explicit imports in case `autoImport` is disabled (Nuxt docs [here](https://nuxt.com/docs/guide/concepts/auto-imports#disabling-auto-imports)). Disabled `autoImport` in the E2E test to verify.
fixes https://github.com/getsentry/sentry-javascript/issues/13302

fix(nuxt): Add import line for disabled `autoImport`

---

dev-packages/e2e-tests/test-applications/nextjs-15/package.json
packages/nextjs/src/common/captureRequestError.ts

https://github.com/vercel/next.js/pull/68672 changed the name of a field. This PR updates `experimental_captureRequestError` to use the new field.
Fixes https://github.com/getsentry/sentry-javascript/issues/13332

feat(nextjs): Update `experimental_captureRequestError` to reflect `RequestInfo.path` change in Next.js canary

---

.size-limit.js
packages/core/src/baseclient.ts
packages/core/test/lib/base.test.ts
packages/node-experimental/test/integration/transactions.test.ts

- backport https://github.com/getsentry/sentry-javascript/pull/12751
- https://github.com/getsentry/sentry-javascript/commit/df45d65885764be2ca75c1b5122e7746c07efd59
Some SDK can't get this from v8 in timely fashion:
- https://github.com/getsentry/sentry-capacitor/issues/693
- https://github.com/getsentry/sentry-react-native/issues/3944

backport(tracing): Report dropped spans for transactions

---

packages/nuxt/src/client/sdk.ts
packages/nuxt/src/common/types.ts
packages/nuxt/src/server/sdk.ts
packages/nuxt/test/server/sdk.test.ts

fixes https://github.com/getsentry/sentry-javascript/issues/13304

fix(nuxt): Add vue to excludeEsmLoaderHooks array

---

.github/workflows/build.yml

https://github.com/getsentry/sentry-javascript/pull/13351 still triggered the `job_build` job  because I forgot to explicitly check for `true` in the if condition.
Also made a minor simplifcation to the condition I missed in the PR review suggestion in https://github.com/getsentry/sentry-javascript/pull/13340

fix(ci): Fix incorrect `changed_any_code` check in `job_build`

---

.github/workflows/cleanup-pr-caches.yml

Taken from https://github.com/actions/cache/blob/main/tips-and-workarounds.md#force-deletion-of-caches-overriding-default-cache-eviction-policy.
Caches are per-branch, so if a PR is closed we do not need to keep any caches for that branch around anymore. This PR adds automation to do just that.

ci: Automatically clear caches for closed PRs

---

.github/workflows/build.yml

5 days after the previous v7 release github removed the macos-11 runners.
https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/#macos-11-deprecation-and-removal
```
In January 2024, GitHub announced the [deprecation of macOS 11](https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/) and the removal of the runner image by June 2024. The macOS 11 runner image will be removed on 6/28/2024. We recommend updating workflows to use macos-14, macos-13, macos-12, or macos-latest. Reminder emails will be sent to those who have used the macOS 11 runner image in the past 30 days. Jobs using macOS 11 will temporarily fail during scheduled time periods to raise awareness of the upcoming removal. The schedule can be found …
```

fix(ci): GH dropped macos-11 at the end of June 24

---

.github/actions/install-dependencies/action.yml
.github/actions/install-playwright/action.yml
.github/workflows/build.yml

This streamlines some caching stuff for CI:
1. Extract dependency installation & cache out into a composite action for reusability
2. Updated the cache key for dependencies to only include package & dev-package `package.json`, not the E2E test ones.

ci: Streamline some caching

---

dev-packages/e2e-tests/test-applications/solidstart/src/routes/back-navigation.tsx
dev-packages/e2e-tests/test-applications/solidstart/src/routes/index.tsx
dev-packages/e2e-tests/test-applications/solidstart/tests/performance.client.test.ts

fix(solidstart): Make back navigation test less flaky

---

dev-packages/size-limit-gh-action/index.mjs

This improves a few things in our size-limit CI action:
1. Show change in bytes, in addition to the change in percentage. 
2. Add a link below the table to the base comparison run.
3. If we detect that the workflow run we used as base is not the latest one, show a warning on top.

ci: Improve size-limit CI action

---

package.json

Reverts getsentry/sentry-javascript#13118
There has been quite a bit of segmentation faults in CI after this PR was merged.
I tried spending time to look into this in more detail, but it didn't get far, so not worrying about this too much for now. Let's revert and re-examine later.

Revert "build: Bump node to 22.5.1"

---

packages/deno/src/client.ts
packages/deno/src/integrations/context.ts
packages/deno/src/integrations/normalizepaths.ts
packages/deno/src/transports/index.ts

This fix isn't perfect but it will at least unblock people on Deno deploy.
Fixes https://github.com/getsentry/sentry-javascript/issues/10521

fix(deno): Don't rely on `Deno.permissions.querySync`

---

dev-packages/e2e-tests/test-applications/default-browser/tests/performance.test.ts

This PR relaxes the pageload transaction assertion. Web vitals are too flaky to hard-assert on them and they are covered in browser integration tests
closes https://github.com/getsentry/sentry-javascript/issues/13377

test(e2e): Fix flake in default browser e2e test

---

docs/changelog/v7.md

Minor changes: I realized that the formatting was broken for `v8` and that the migration guide wasn't linking to the specific section like other changelogs.

docs: Fix v7 changelog format and link

---

dev-packages/browser-integration-tests/utils/fixtures.ts

CI is angery. Crypto is only on global from Node 19 onwards.

ci: Fix crypto not being available

---

packages/feedback/src/core/sendFeedback.ts

If the domain is not in `Allowed Domains` in the Sentry project settings, it would cause a 403 error. The default setting is `*` so this only occurs when the user changes these settings.
Fixes https://github.com/getsentry/sentry-javascript/issues/9856

feat(feedback): Improve error message for 403 errors

---

.github/workflows/build.yml

Oops, we stopped publishing this, just noticed this while working on my hackweek project... 😬

fix(replay): Ensure we publish replay CDN bundles

---

.github/actions/install-dependencies/action.yml
scripts/dependency-hash-key.js

Ensure it only changes if actual dependencies change.
Previously, we would invalidate the dependency cache every time a package.json of the workspace changed in any way. This is defensive, but it also means that we also invalidate if one of these things happen:
1. A script or similar is added/edited for workspace package
2. A release is made, bumping internal dependency versions
This change updates this to calculate the hash with a slightly more sophisticated approach, which should hopefully ensure we only actually bust the cache when a dependency _actually_ changes. This should lead to the dependency cache being re-used much more, because only rarely is an actual dependency changed.

ci: Stabilize CI dependency cache key

---

.github/workflows/build.yml

Noticed this here: https://github.com/getsentry/sentry-javascript/actions/runs/10417249817, when merging a markdown-only PR into develop, CI will not fully run there.

ci: Always run build on develop branch

---

dev-packages/e2e-tests/test-applications/nuxt-3/nuxt.config.ts
dev-packages/e2e-tests/test-applications/nuxt-3/sentry.client.config.ts
packages/nuxt/src/module.ts
packages/nuxt/src/runtime/plugins/sentry.client.ts

To be able to use `useRuntimeConfig()` in the user-defined Sentry config file, it needs to be wrapped in a Nuxt context. Right now, this is only done on the client-side because the server-side is currently still in the `public` folder (this will be changed) and cannot use the virtual `#imports` import (`useRuntimeConfig` is imported from `#imports`)

feat(nuxt): Wrap config in nuxt context

---

.github/workflows/build.yml

There's a bug in Node 22.7.0 with protobuf which we're running into: https://github.com/protobufjs/protobuf.js/issues/2025
Once the bug is fixed, we should revert this PR.
h/t @lforst for figuring this out; I'm just merging it into develop 😅

test(ci): Pin Node 22 unit test Node version

---

.size-limit.js
packages/replay-canvas/package.json
packages/replay-internal/package.json
yarn.lock

* [fix(rrdom): Ignore invalid DOM attributes when diffing](https://github.com/getsentry/rrweb/pull/213)
* [fix: manual snapshot in rAF loop](https://github.com/getsentry/rrweb/pull/210) (thanks @ShinyChang)
* [feat: Fix blocking dynamically added iframes](https://github.com/getsentry/rrweb/pull/212)

feat(replay): Upgrade rrweb packages to 2.26.0

---

dev-packages/rollup-utils/plugins/bundlePlugins.mjs

Noticed that this is mangled on the `options` in the CDN, which it probably shouldn't be...

fix(cdn): Do not mangle _metadata

---

.github/workflows/clear-cache.yml
.github/workflows/external-contributors.yml
dev-packages/clear-cache-gh-action/.eslintrc.cjs
dev-packages/clear-cache-gh-action/action.yml
dev-packages/clear-cache-gh-action/index.mjs
dev-packages/clear-cache-gh-action/package.json
package.json

Previously, we had a CI action to manually clear all caches.
This PR adjusts this so this action can be used in a more granular way:
* By default, the action will now delete caches of any PR runs that are successful, as well as any caches of release branches.
* You can configure to also delete caches on the develop branch, and/or to also delete non-successful PR branches.
Additionally, this action will run every midnight, to automatically clear completed/outdated stuff.
The goal is to keep develop caches as long as possible, and clear out other caches, unless they failed (which indicates you may want to re-run some of the tests) and unless they are currently running (to not break ongoing tests). Ideally, we do not need to manually run this, but can rely on automated cleanup over night.

ci: Update clear cache action to be smarter

---

.github/actions/restore-cache/action.yml
.github/workflows/build.yml

This PR changes it so that the build output is kept as an artifact, not a cache. This way, this should never be lost on us.
We keep the NX cache as before.
I chose a retention period of 7 days, which means that after 7 days you could no longer re-run a workflow partially. IMHO that's a reasonable start, we can adjust this if needed.

ci: Store build output as artifacts instead of cache

---

.github/workflows/build.yml

It keeps complaining that this is deprecated, so bumping this to v4.

ci: Update actions/upload-artifact to v4

---

packages/nuxt/README.md

Config example fix. env.DSN was missing process prefix.

Fix config example in README.md for Nuxt

---

dev-packages/node-integration-tests/suites/tracing/redis-cache/test.ts
dev-packages/node-integration-tests/utils/runner.ts

Noticed e.g. here: https://github.com/getsentry/sentry-javascript/actions/runs/10594383971/job/29358138105 that this was timing out some times, so increasing the timeout a bit...

test: Increase timeout for redis-cache test & docker-compose

---

.github/actions/install-playwright/action.yml

Noticed e.g. here: https://github.com/getsentry/sentry-javascript/actions/runs/10594383971/job/29359100222 that saving of the cache was not working. I guess this only works for the combined restore/save step, but here it expects that the cached data is there immediately (which makes sense!).

ci: Ensure cache save happens after install step

---

packages/browser/src/transports/fetch.ts
packages/cloudflare/src/transport.ts
packages/deno/src/transports/index.ts
packages/node/src/integrations/http.ts
packages/node/src/transports/http.ts
packages/vercel-edge/src/transports/index.ts

https://github.com/getsentry/sentry-javascript/issues/13466#issuecomment-2312856449 correctly points out that we are suppressing tracing for the transport creation instead of the transport execution.
This PR wraps the code that is actually conducting the request with `suppressTracing` instead of the transport creation.
Fixes https://github.com/getsentry/sentry-javascript/issues/13466

fix(node): Suppress tracing for transport request execution rather than transport creation

---

dev-packages/e2e-tests/test-applications/solidstart/tests/performance.client.test.ts

This just skips a flaky E2E solidstart test. It is not a super critical test, so I'd skip this for now until we have time to investigate the flakiness - e.g. see https://github.com/getsentry/sentry-javascript/actions/runs/10596825068/job/29365892465

test(solidstart): Skip flaky test for now

---

packages/vue/src/types.ts
packages/vue/src/vendor/components.ts
packages/vue/test/vendor/components.test.ts

In some cases, Vue components do not have `options.name` defined, but instead have `options.__name`. Such components will be displayed as anonymous in Sentry and currently won't be matched in `trackComponents`.
The same fix was also done in Vue devtools (vuejs/devtools#2020). In my case, the problem were components from my own project, but this change also fixes that.
Also related to component names, the [documentation](https://docs.sentry.io/platforms/javascript/guides/vue/features/component-tracking/#trackcomponents) should probably be fixed. It currently lists components such as `RwvHeader` in the example, but components are actually named like `<RwvHeader>`.

fix(vue): Correctly obtain component name

---

packages/core/test/lib/transports/offline.test.ts
packages/eslint-config-sdk/src/base.js
packages/eslint-plugin-sdk/src/index.js
packages/eslint-plugin-sdk/src/rules/no-focused-tests.js
packages/eslint-plugin-sdk/src/rules/no-skipped-tests.js
packages/profiling-node/test/cpu_profiler.test.ts

I noticed that `it.skip` and `it.only` usage is not correctly flagged in vitest files by our jest eslint plugin. To fix this, I initially wanted to add [eslint-plugin-vitest](https://github.com/vitest-dev/eslint-plugin-vitest) but realized it requires Eslint 9 which we can't use (we're on eslint 7) because it requires Node 18 🙃 
So instead, this PR adds two simple custom rules to ignore `(it|test|describe).(skip|only)`. These rules now also flag vitest-based `skip` and `only` functions but led to duplications with the two rules from `eslint-plugin-jest`. So this PR also disables the jest versions in favour of the custom rules. To be clear, the custom rules are likely a bit less robust than the jest/vitest version but until we can use the actual vitest plugin, I think it's fine to stay …

core(lint): Add custom `no-focused-tests` and `no-skipped-tests` rules

---

.size-limit.js
packages/replay-internal/src/coreHandlers/handleClick.ts

Previously, we only considered `Mutation` style changes of rrweb as "DOM mutations" for dead click detection.
However, after closer inspection, there are also some other types of changes that we may consider as DOM mutations. By including these we can hopefully reduce some false positives.
Not quite sure how to test this 🤔 It's probably also OK to just ship this, as the worst-case scenario is that we have some false-negatives and do not capture certain things, but our general goal here is to be rather on the cautious side, so I think that is acceptable.
Possibly fixes https://github.com/getsentry/sentry-javascript/issues/9755

fix(replay): Consider more things as DOM mutations for dead clicks

---

.github/workflows/build.yml

This takes a lot of resources, and is only very rarely needed.
Now, it only always runs profiling node compilation on release branches, and on dedicated profiling-node changes.

ci: Do not run profiling node jobs on develop

---

packages/nuxt/README.md

Mismatch in env var names in Readme. One was called DSN, the other SENTRY_DSN.

docs(nuxt): Consistently use `SENTRY_DSN` env var in README examples

---

packages/astro/src/index.server.ts
packages/aws-serverless/src/index.ts
packages/bun/src/index.ts
packages/core/src/index.ts
packages/core/src/profiling.ts
packages/google-cloud-serverless/src/index.ts
packages/node/src/index.ts
packages/profiling-node/src/integration.ts
packages/profiling-node/test/spanProfileUtils.test.ts
packages/profiling-node/test/spanProfileUtils.worker.test.ts
packages/types/src/index.ts
packages/types/src/profiling.ts

We are about to enter a public beta for continuous profiling, which means it is time to expose this from under the wraps of the integration and align it with how the profiler is exposed in python and iOS SDKs

feat(profiling): Expose profiler as top level primitive

---

dev-packages/e2e-tests/test-applications/nextjs-13/instrumentation.ts
dev-packages/e2e-tests/test-applications/nextjs-14/instrumentation.ts
dev-packages/e2e-tests/test-applications/nextjs-15/instrumentation.ts
dev-packages/e2e-tests/test-applications/nextjs-app-dir/instrumentation.ts
packages/nextjs/src/common/captureRequestError.ts
packages/nextjs/src/common/index.ts
packages/nextjs/src/index.types.ts

Next.js stabilized the `instrumentation.js` API so we can also stabilize `captureRequestError`: https://github.com/vercel/next.js/pull/68853
Ref https://github.com/getsentry/sentry-javascript/issues/8105#issuecomment-2324415563

feat(nextjs): Stabilize `captureRequestError`

---

.github/workflows/build.yml
dev-packages/e2e-tests/test-applications/nestjs-graphql/.gitignore
dev-packages/e2e-tests/test-applications/nestjs-graphql/.npmrc
dev-packages/e2e-tests/test-applications/nestjs-graphql/nest-cli.json
dev-packages/e2e-tests/test-applications/nestjs-graphql/package.json
dev-packages/e2e-tests/test-applications/nestjs-graphql/playwright.config.mjs
dev-packages/e2e-tests/test-applications/nestjs-graphql/src/app.module.ts
dev-packages/e2e-tests/test-applications/nestjs-graphql/src/app.resolver.ts
dev-packages/e2e-tests/test-applications/nestjs-graphql/src/instrument.ts
dev-packages/e2e-tests/test-applications/nestjs-graphql/src/main.ts
dev-packages/e2e-tests/test-applications/nestjs-graphql/start-event-proxy.mjs
dev-packages/e2e-tests/test-applications/nestjs-graphql/tests/errors.test.ts
dev-packages/e2e-tests/test-applications/nestjs-graphql/tsconfig.build.json
dev-packages/e2e-tests/test-applications/nestjs-graphql/tsconfig.json
packages/nestjs/src/setup.ts

`BaseExceptionFilter` should not be used in GraphQL applications ([ref](https://github.com/nestjs/nest/issues/5958#issuecomment-747483125)). Currently the `SentryGlobalFilter` extends the `BaseExceptionFilter`, which is why GraphQL applications break if an exception is thrown.
By default, NestJS + GraphQL environments use the `ExternalExceptionFilter` ([ref](https://github.com/nestjs/nest/blob/master/packages/core/exceptions/external-exception-filter.ts)), which essentially just rethrows the error. So I added a new `SentryGlobalGraphQLFilter` that captures the exception in Sentry and then simply rethrows the error.
Additionally, added a new e2e test app to test GraphQL applications. Added a test to verify that basic error reporting works correctly now.

feat(nestjs): Add `SentryGlobalGraphQLFilter`

---

dev-packages/e2e-tests/test-applications/nestjs-basic/src/app.controller.ts
dev-packages/e2e-tests/test-applications/nestjs-basic/src/app.service.ts
dev-packages/e2e-tests/test-applications/nestjs-basic/tests/transactions.test.ts
dev-packages/e2e-tests/test-applications/node-nestjs-basic/src/app.controller.ts
dev-packages/e2e-tests/test-applications/node-nestjs-basic/src/app.service.ts
dev-packages/e2e-tests/test-applications/node-nestjs-basic/tests/transactions.test.ts
packages/node/src/integrations/tracing/nest/helpers.ts
packages/node/src/integrations/tracing/nest/sentry-nest-instrumentation.ts
packages/node/src/integrations/tracing/nest/types.ts

Before this fix, calling a `use` method on a service that does not implement the `NestMiddleware` interface resulted in an error. This is because we try to proxy the third argument to the function, which in middleware is an express `NextFunction`, but in other classes can be anything, potentially even undefined. 
This fix introduces a guard to verify that the argument we are trying to proxy is actually a `NextFunction`.
Added a test to verify that services with `use` work fine now. Also added additional tests to verify that this behavior does not occur for `canActivate` (guard), `intercept` (interceptor) and `transform` (pipe) methods.

fix(nestjs): Check arguments before instrumenting with `@Injectable`

---

dev-packages/browser-integration-tests/suites/integrations/httpContext/init.js
dev-packages/browser-integration-tests/suites/integrations/httpContext/subject.js
dev-packages/browser-integration-tests/suites/integrations/httpContext/test.ts

While investigating #13536 I wrote a quick integration test to check that the `httpContextIntegration` works as expected. This PR adds said test to our browser integration tests. We have other tests in which we implicitly check that url and user-agent are set but none for `referer`, so I think this test has value.

test(browser): Add integration test for `httpContextIntegration`

---

packages/vue/src/tracing.ts

UI spans make sense if they are a child of e.g. a pageload root span. This change ensures UI spans are not created as root spans.
ref https://github.com/getsentry/sentry-javascript/issues/13546

feat(vue): Only start UI spans if parent is available

---

packages/replay-internal/src/types/performance.ts
packages/replay-internal/src/util/createPerformanceEntries.ts

Fixes attribution type: when adding an attribution in CLS we add {`value`, `nodeIds`} not {`value`, `sources`}

fix(replay): Fix types in WebVitalData

---

packages/solidstart/src/client/sdk.ts
packages/solidstart/test/client/sdk.test.ts

feat(solidstart): Add `browserTracingIntegration` by default

---

.size-limit.js
dev-packages/browser-integration-tests/package.json
dev-packages/bundle-analyzer-scenarios/package.json
packages/ember/package.json
packages/nextjs/package.json
yarn.lock

I wanted to add a new entry for size limit with sentry browser with max. tree shaking. While doing this, I noticed that bundle size did not shrink as much as I would have expected it. After playing around some, I noticed that it was not actually shaking out the constant changes, for whatever reason. Probably some size-limit internal default config. 
Now, i actually add terser to ensure it fully minimizes & tree shakes stuff for us.

ci: Update size-limit to ensure bundle size optimization

---

packages/node/src/integrations/node-fetch.ts

Uses the stringified value of `origin` to call `.endsWith()`.
closes https://github.com/getsentry/sentry-javascript/issues/13574

fix(node-fetch): Use stringified origin url

---

packages/cloudflare/src/request.ts
packages/cloudflare/test/request.test.ts

This PR guards the call for `context.waitUntil` in the CF request handler wrapper. Our public API requires `context` to be present, however, in certain cases like Astro during build (prerendering), `context` becomes `undefined`. This might [change in the future](https://github.com/getsentry/sentry-javascript/issues/13217#issuecomment-2317092450) with Astro 5 but for now let's guard the invokation of `context.waitUntil` against context being `undefined`.
Note: I opted to leave `context` required in the public options because I don't think we should suggest users that it's optional to pass it in. Happy to change that if reviewers prefer to make it optional.  
ref https://github.com/getsentry/sentry-javascript/issues/13217

fix(cloudflare): Guard `context.waitUntil` call in request handler

---

dev-packages/node-integration-tests/suites/tracing/genericPool/test.ts
packages/node/src/integrations/tracing/genericPool.ts

Ref https://github.com/getsentry/sentry-javascript/pull/13465#issuecomment-2327535609

fix(node): Replace dashes in `generic-pool` span origins with underscores

---

packages/nextjs/src/config/withSentryConfig.ts

The logic in this PR is slightly intense but all it does is check for the Next.js version and if we are on a version that included [this change](https://github.com/vercel/next.js/pull/68853) which stabilized `instrumentation.ts` we no longer inject the `experimental.instrumentationHook` option in `next.config.js`.
This is necessary because otherwise Next.js prints scary warnings and users may be confused why.

feat(nextjs): Future-proof Next.js config options overriding

---

dev-packages/e2e-tests/test-applications/node-express-esm-loader/src/instrument.mjs
dev-packages/node-integration-tests/suites/esm/import-in-the-middle/app.mjs
dev-packages/node-integration-tests/suites/esm/import-in-the-middle/sub-module.mjs
dev-packages/node-integration-tests/suites/esm/import-in-the-middle/test.ts
packages/node/src/sdk/initOtel.ts
packages/node/src/types.ts

Likely closes many issues but I don't want to auto-close anything specific here. We should probably confirm the issues are closed individually. 
`import-in-the-middle` by default wraps every ES module with a wrapping module that later allows it exports to be modified. This has issues though because the wrapping output of `import-in-the-middle` is not compatible with all modules. 
To help work around this I [added a feature](https://github.com/nodejs/import-in-the-middle/pull/146) to `import-in-the-middle` that allows us to only wrap modules that we specifically need to instrument.
```ts
import * as Sentry from '@sentry/node';
Sentry.init({
dsn: '__DSN__',
registerEsmLoaderHooks: { onlyHookedModules: true },
});
```
So far I've only changed the express integration test to use this new …

feat(node): Option to only wrap instrumented modules

---

.github/workflows/build.yml
dev-packages/e2e-tests/test-applications/solidstart/app.config.ts
dev-packages/e2e-tests/test-applications/solidstart/package.json
dev-packages/e2e-tests/test-applications/solidstart/src/routes/client-error.tsx
dev-packages/e2e-tests/test-applications/solidstart/src/routes/error-boundary.tsx
dev-packages/e2e-tests/test-applications/solidstart/src/routes/index.tsx
dev-packages/e2e-tests/test-applications/solidstart/tests/errorboundary.test.ts
dev-packages/e2e-tests/test-applications/solidstart/tests/errors.client.test.ts
packages/solidstart/.eslintrc.js
packages/solidstart/README.md
packages/solidstart/package.json
packages/solidstart/src/index.server.ts
packages/solidstart/src/index.types.ts
packages/solidstart/src/vite/index.ts
packages/solidstart/src/vite/sentrySolidStartVite.ts
packages/solidstart/src/vite/sourceMaps.ts
packages/solidstart/src/vite/types.ts
packages/solidstart/test/server/withServerActionInstrumentation.test.ts
packages/solidstart/test/vite/sentrySolidStartVite.test.ts
packages/solidstart/test/vite/sourceMaps.test.ts

This plugin simplifies source maps upload by using `@sentry/vite-plugin` and enabling source map generation by default.
Usage:
```js
import { defineConfig } from '@solidjs/start/config'
import { sentrySolidStartVite } from '@sentry/solidstart'
export default defineConfig({
vite: {
plugins: [
sentrySolidStartVite({
sourceMapsUploadOptions: {
enabled: true,
org: process.env.SENTRY_ORG,
project: process.env.SENTRY_PROJECT,
authToken: process.env.SENTRY_AUTH_TOKEN,
},
debug: true,
}),
],
}
})
```
Closes: #12553

feat(solidstart): Add `sentrySolidStartVite` plugin to simplify source maps upload

---

dev-packages/size-limit-gh-action/index.mjs

Noticed this was failing on develop e.g. here: https://github.com/getsentry/sentry-javascript/actions/runs/10699493008/job/29661468888

ci: Fix size-limit action on develop branches

---

packages/gatsby/gatsby-node.js

https://github.com/getsentry/sentry-javascript/issues/13582#issuecomment-2331078028 correctly identified that this path is messed up.

fix(gatsby): Fix assets path for sourcemaps upload

---

packages/nextjs/src/config/webpackPluginOptions.ts
packages/nextjs/test/config/webpack/webpackPluginOptions.test.ts

Currently, we use `path.join` to provide sourcemap directories. On Windows, the resulting strings would use `\` which is an escape character for glob patterns and thus no sourcemaps would be found.
This fix ensures we use posix paths which glob then handles correctly on Windows too.
Tested this on a windows machine:
Closes: https://github.com/getsentry/sentry-javascript/issues/13270
Partly fixes: https://github.com/getsentry/sentry-javascript/issues/13288

fix(nextjs): Use posix paths for sourcemap uploads

---

packages/replay-internal/src/types/performance.ts
packages/replay-internal/src/util/createPerformanceEntries.ts

Removes optional types so that type mismatches would be caught by typescript
Follow up to https://github.com/getsentry/sentry-javascript/pull/13573

fix(replays): Improve replay web vital types

---

packages/node/test/integrations/localvariables.test.ts

Changes the rate-limiting tests to use fake timers. This takes the test time from 24s to 4s.

test(node): Use fake timers to speed up unit tests

---

packages/core/src/tracing/measurement.ts

While working on updating [`sentry-javascript-bundler-plugins` to use v8 of the JavaScript SDK](https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/579), I found that I was unable to set measurements as the global client is not used.
If you're not using a global client, there is currently no way to add measurements because `Sentry.setMeasurement()` relies on `getActiveSpan()` which in turn relies on `getCurrentScope()`.
This PR moves the `activeSpan` into the last parameter which defaults to `getActiveSpan()`.

feat(core): Allow adding measurements without global client

---

packages/browser/src/tracing/browserTracingIntegration.ts

`PerformanceObserver` is available on iOS 11 and later, but
the `supportedEntryTypes` method is available on iOS 13 and later.
ref: https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver
Therefore, a runtime error will occur if we use Sentry on iOS 11 or iOS 12.

fix(browser): check supportedEntryTypes before caling the function

---

packages/opentelemetry/package.json
packages/solidstart/package.json

Looks like we overlooked two packages when updating deps previously in #13587.
See: https://github.com/getsentry/sentry-javascript/pull/13587#issuecomment-2339419127
Closes: #13219

fix(node): Update OpenTelemetry instrumentation package for solidstart and opentelemetry

---

CHANGELOG.md

I failed to update the description in my PR when we improved the property name after some discussion in the PR, so the wrong property name was used in the changelog:
https://github.com/getsentry/sentry-javascript/blob/bcf571d9954094be76a99edbb12c23eff7f7b5dc/packages/node/src/types.ts#L20
Thanks to @torickjdavis for reporting this [here](https://github.com/getsentry/sentry-javascript/issues/12414#issuecomment-2339236336)!

fix: incorrect property name in `CHANGELOG.md`

---

dev-packages/e2e-tests/test-applications/nextjs-13/tests/server/404.test.ts
packages/nextjs/src/server/index.ts

On app router, transactions like `GET /404` get created that we don't like.

fix(nextjs): Widen removal of 404 transactions

---

dev-packages/node-integration-tests/package.json
dev-packages/node-integration-tests/suites/tracing/kafkajs/docker-compose.yml
dev-packages/node-integration-tests/suites/tracing/kafkajs/scenario.js
dev-packages/node-integration-tests/suites/tracing/kafkajs/test.ts
packages/astro/src/index.server.ts
packages/aws-serverless/src/index.ts
packages/bun/src/index.ts
packages/google-cloud-serverless/src/index.ts
packages/node/package.json
packages/node/src/index.ts
packages/node/src/integrations/tracing/index.ts
packages/node/src/integrations/tracing/kafka.ts
packages/remix/src/index.server.ts
packages/solidstart/src/server/index.ts
packages/sveltekit/src/server/index.ts
yarn.lock

feat(node): Add `kafkajs` integration

---

.github/workflows/project-automation.yml

Follow up to https://github.com/getsentry/sentry-javascript/pull/13608, after some tweaks and a rebase!
* When a PR is opened in draft mode, move to "In Progress" on the board
* When a PR is opened for review, move to "In Review" on the board
* When a PR is closed but not merged, move it directly to "Done" (instead of "Ready for Release")
Note that for now, this only applies to PRs that are on the board themselves, not to PRs linked to an issue.

ci: Add some additional GH project automation

---

packages/replay-internal/src/replay.ts
packages/replay-internal/test/integration/flush.test.ts

This fixes a potential issue where segments can come in out of order due to our flush "lock" was not being respected in two cases:
1) No current flush in progress, but flush throws an error (this should be rare as the common errors that get thrown should stop the replay completely)
2) Flush is in progress, which skips the code block that releases lock and then calls debouncedFlush. This leaves the lock always set to a resolved (or rejected) promise.
This ultimately should not change too much as the flush calls are debounced anyway, but this cleans up the code a bit and also logs any exceptions that may occur. However this can fix issues where segments can come in out of order depending on how long the send request takes. e.g.
where ideally it looks like

fix(replay): Fixes potential out-of-order segments

---

.github/workflows/build.yml
dev-packages/browser-integration-tests/package.json
dev-packages/browser-integration-tests/playwright.config.ts
dev-packages/e2e-tests/test-applications/ember-classic/playwright.config.ts
dev-packages/e2e-tests/test-applications/ember-embroider/playwright.config.ts
dev-packages/e2e-tests/test-applications/node-express-send-to-sentry/playwright.config.mjs
dev-packages/e2e-tests/test-applications/react-send-to-sentry/playwright.config.mjs
dev-packages/test-utils/src/playwright-config.ts
packages/remix/package.json
packages/remix/playwright.config.ts

https://docs.codecov.com/docs/test-result-ingestion-beta
https://playwright.dev/docs/test-reporters
Adds codecov test analytics to the repo, specifically for our playwright tests.
This works by using the junit reporter with playwright, and then uploading that via the `codecov/test-results-action@v1` GitHub Action.

build: Add codecov test analytics for playwright tests

---

dev-packages/e2e-tests/test-applications/nestjs-basic/src/app.controller.ts
dev-packages/e2e-tests/test-applications/nestjs-basic/src/app.service.ts
dev-packages/e2e-tests/test-applications/nestjs-basic/tests/span-decorator.test.ts
packages/nestjs/src/decorators/sentry-traced.ts

This PR preserves the `name` for functions that are decorated with `@SentryTraced`.
fixes https://github.com/getsentry/sentry-javascript/issues/13683

fix(nestjs): Preserve original function name on `SentryTraced` functions

---

packages/wasm/src/index.ts

Currently we are only setting the `platform` and `instruction_addr` for a wasm frame if we find a matching debug image. This is not always the case and unconditionally parsing the instruction address is almost always desirable.

feat(wasm): Unconditionally parse instruction addresses

---

packages/angular/src/errorhandler.ts
packages/node/src/integrations/local-variables/worker.ts
packages/nuxt/src/module.ts
packages/nuxt/src/vite/addServerConfig.ts
packages/sveltekit/src/server/handleError.ts

To avoid infinite loops etc.
@chargome do you think that fixes the thing you encountered, or was this something else? 🤔

fix: Ensure all logs are wrapped with `consoleSandbox`

---

dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals/test.ts
dev-packages/e2e-tests/test-applications/react-create-hash-router/tests/transactions.test.ts
packages/browser-utils/src/metrics/browserMetrics.ts

In prerendering scenarios, where a page might be prefetched and pre-rendered before the user clicks a link, the performance API starts measuring the navigation earlier than when the user clicks it. Web Vital measurements however are always based on the user-perceived (loading) time, so they are not reported from the actual start of the navigation, but rather from the time where the user actively started the navigation, for example by clicking a link. This user action is called "activation" and the time between navigation start and activation is stored in the [`activationStart` attribute](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceNavigationTiming/activationStart) of the "navigation" PerformanceEntry.
This PR adds this `activationStart` property as it gets reported by the …

feat(browser): Add navigation `activationStart` timestamp to pageload span

---

CHANGELOG.md
README.md

Supercedes https://github.com/getsentry/sentry-javascript/pull/13432
Adds cloudflare sdk to the readme list - thanks @KyGuy2002 for the PR!

chore: Add cloudflare sdk to main README

---

packages/profiling-node/bindings/cpu_profiler.cc

I think what is happening is that by the time our close handler is called, the handler had already been deleted, which causes a use after free error. I also updated the code to check for is_closing which is what that underlying libuv method actually asserts on.
Fixes https://github.com/getsentry/sentry-javascript/pull/13661

ref(profiling) use cleanup instead of destructor

---

packages/profiling-node/src/integration.ts
packages/profiling-node/test/spanProfileUtils.test.ts

Modifies the functionality of profiler start and stop calls to regenerate the profilerId

ref(profiling): reinitialize profilerId on explicit stop calls

---

packages/node/src/types.ts
packages/node/src/utils/ensureIsWrapped.ts
packages/node/test/utils/ensureIsWrapped.test.ts

Closes https://github.com/getsentry/sentry-javascript/issues/13471
This can be used when you know what you're doing to avoid the warning log.

feat(node): Add `disableInstrumentationWarnings` option

---

packages/browser/src/utils/lazyLoadIntegration.ts

This PR makes our `lazyLoadIntegration` a bit more robust when trying to find the parent element to inject the script tag of the integration CDN bundle. It looks like some browsers don't automatically set `document.body` if the html page doesn't contain a `<body>` tag. Unfortunately, I couldn't reproduce this with Chrome, FF or Safari, so my running theory is that this is rather an exotic browser.
Anyway, for now the order of looking up parent elements is:
1. `document.body`
2. `document.head`
3. `document.currentScript.parentElement`
Unfortunately, I couldn't find a way to test these branches since neither chromium (integration tests) nor JSDOM (unit tests) allow unsetting `document.body|head`. I think we _should_ be fine with leaving this specific change untested but I can also spend …

fix(browser): Try multiple options for `lazyLoadIntegration` script parent element lookup

---

packages/node/src/integrations/http.ts

With this change, it is easier to figure out from logs if the correct or incorrect http instrumentation is added.
Now, if you see e.g. this in the logs, if users have enabled logs (`debug: true` if not using `skipOpenTelemetrySetup: true`, else using native OTEL debug logs with e.g. `diag.setLogger(new DiagConsoleLogger(), DiagLogLevel.DEBUG)`):
```js
@opentelemetry/instrumentation-http-sentry Applying instrumentation patch for nodejs core module on require hook { module: 'http' }
@opentelemetry/instrumentation-http Applying instrumentation patch for nodejs core module on require hook { module: 'http' }
```
you can tell that that it has been double instrumenting this incorrectly. You should never see the `@opentelemetry/instrumentation-http` entry anymore, otherwise something is wrong …

ref: Update http instrumentation name for logging

---

.github/workflows/build.yml

Looks like the bug that made us pin to Node 22.6.0 in our Node unit tests was fixed and released in 22.8.0. This PR reverts the pin, meaning we test against the latest Node 22 version again.
draft until CI passes...

test(ci): Use latest node 22 version again for Node unit tests

---

packages/nuxt/src/module.ts
packages/nuxt/src/vite/addServerConfig.ts

Depending on the [nitro preset](https://nitro.unjs.io/deploy), the build output changes. By using the `serverDir` option, the directory can be retrieved dynamically.

fix(nuxt): Use correct server output file path

---

dev-packages/node-integration-tests/package.json
dev-packages/node-integration-tests/suites/tracing/dataloader/scenario.js
dev-packages/node-integration-tests/suites/tracing/dataloader/test.ts
packages/astro/src/index.server.ts
packages/aws-serverless/src/index.ts
packages/bun/src/index.ts
packages/google-cloud-serverless/src/index.ts
packages/node/package.json
packages/node/src/index.ts
packages/node/src/integrations/tracing/dataloader.ts
packages/node/src/integrations/tracing/index.ts
yarn.lock

Resolves: https://github.com/getsentry/sentry-javascript/issues/13313
Adds integration for `dataloader` using [`@opentelemetry/instrumentation-dataloader`](https://www.npmjs.com/package/@opentelemetry/instrumentation-dataloader) on the background.
A few notes:
- We currently don't have access to the lookup / request as there is no hook from `@opentelemetry/instrumentation-dataloader`. So, we don't have `cache.hit`, `cache.key`, `cache.item_size` and so on, in this integration. I can try to implement those upstream, but if you have another way in mind to access those please let me know.
- `@opentelemetry/instrumentation-dataloader` only records spans for `load`, `loadMany` and `batch`, which all are `cache.get` operations. There are also `prime`, `clear`, `clearAll`. We also can implement …

feat(node): Add `dataloader` integration

---

packages/replay-internal/src/replay.ts
packages/replay-internal/src/types/replay.ts
packages/replay-internal/src/util/logger.ts
packages/replay-internal/src/util/sendReplay.ts
packages/replay-internal/test/integration/flush.test.ts
packages/replay-internal/test/unit/util/logger.test.ts

* Adds an `onError` callback for replay SDK exceptions
* Do not log empty messages when calling `logger.exception`
* Send `ratelimit_backoff` client report when necessary (instead of generic `send_error`)

feat(replay): Add `onError` callback + other small improvements to debugging

---

scripts/get-commit-list.ts

Adds the PR link to the changelog for easier access.
An entry would look like this:
> - feat(node): Add `dataloader` integration ([#13664](https://github.com/getsentry/sentry-javascript/pull/13664))
> ```
> - feat(node): Add `dataloader` integration ([#13664](https://github.com/getsentry/sentry-javascript/pull/13664))
> ```

meta(changelog): Add PR link to changelog entry

---

packages/cloudflare/README.md

Removes alpha note from cloudflare sdk readme.

chore: Remove alpha note from cloudflare readme

---

dev-packages/e2e-tests/test-applications/nestjs-graphql/package.json

This fails e.g. here https://github.com/getsentry/sentry-javascript/actions/runs/10964808053/job/30450399966 for prereleases right now, because the prerelease in the verdaccio registry does not match the required range.

test(nestjs): Fix e2e test dependency to allow prereleases

---

dev-packages/browser-integration-tests/suites/tracing/metrics/handlers-lcp/test.ts

Moved assertions inside a conditional where the `lcp.element` is the image, not the button (It's worked around like this in other test suites). I guess this flakiness is behavioural not about the tests.

fix(test): Unflake LCP test

---

.github/workflows/build.yml
.gitignore
dev-packages/e2e-tests/test-applications/node-otel-without-tracing/package.json
dev-packages/e2e-tests/test-applications/node-otel-without-tracing/src/instrument.ts
dev-packages/e2e-tests/test-applications/node-otel-without-tracing/tests/transactions.test.ts
dev-packages/node-integration-tests/suites/tracing/requests/http-breadcrumbs/scenario.ts
dev-packages/node-integration-tests/suites/tracing/requests/http-no-tracing/scenario.ts
dev-packages/node-integration-tests/suites/tracing/requests/http-no-tracing/test.ts
packages/node/src/integrations/node-fetch.ts

Found this while working on https://github.com/getsentry/sentry-javascript/pull/13763.
Oops, the node-otel-without-tracing E2E test was not running on CI, we forgot to add it there - and it was actually failing since we switched to the new undici instrumentation :O
This PR ensures to add it to CI, and also fixes it. The main change for this is to ensure we do not emit any spans when tracing  is disabled, while still ensuring that trace propagation works as expected for this case.
I also pulled some general changes into this, which ensure that we patch both `http.get` and `http.request` properly.

fix(node): Ensure node-fetch does not emit spans without tracing

---

dev-packages/node-integration-tests/suites/tracing/meta-tags-twp-errors/server.js
dev-packages/node-integration-tests/suites/tracing/meta-tags-twp-errors/test.ts
dev-packages/node-integration-tests/suites/tracing/meta-tags-twp/test.ts
packages/core/src/tracing/dynamicSamplingContext.ts
packages/core/test/lib/tracing/dynamicSamplingContext.test.ts

This PR fixes a bug in Core that surfaced in Node apps configured for Tracing without Performance. 
Previously, we'd incorrectly add`sampled: false` flag when creating the DSC from an active span if the application was configured for TwP. This is possible because in TwP, Otel still emits non-recording spans for the incoming requests. Our implementation in Core didn't account for this edge case yet.
This PR also adds a regression test and fixes some previously incorrectly passing tests.

fix(core): Remove `sampled` flag from dynamic sampling context in Tracing without Performance mode

---

dev-packages/node-integration-tests/suites/tracing/requests/http-sampled/scenario.ts
dev-packages/node-integration-tests/suites/tracing/tracePropagationTargets/scenario.ts

This fails sometimes (e.g. https://github.com/getsentry/sentry-javascript/actions/runs/11016486300/job/30592307032), probably due to tiny timing issues.

test: Unflake some node-integration-tests

---

CHANGELOG.md

Follow up to https://github.com/getsentry/sentry-javascript/pull/13772, which kind of messed this up a bit...

docs: Fix changelog

---

.github/workflows/release-size-info.yml

Implements https://github.com/getsentry/size-limit-release/pull/6 
This is now working again: https://github.com/getsentry/sentry-javascript/actions/runs/11031636865

ci: Fix adding bundle sizes to releases

---

.github/ISSUE_TEMPLATE/bug.yml

Update Bug Report template to clarify that the event URL is public

---

packages/nuxt/src/vite/utils.ts
packages/nuxt/test/vite/utils.test.ts

The `buildDir` can be changed in Nuxt and Adding the client config with a relative path worked so far as the `buildDir` in Nuxt v3 is [`/<rootDir>/.nuxt`](https://nuxt.com/docs/api/nuxt-config#builddir) but the `buildDir` can be modified by the user and is also different in Nuxt v4 ([`/<rootDir>/node_modules/.cache/nuxt/.nuxt`](https://github.com/nuxt/nuxt/blob/f56c05d39de5223c5fa8603ed216e91747937d54/packages/kit/src/loader/config.ts#L54)). 
By using the absolute path, the client config can be injected correctly with all `buildDir` variations

fix(nuxt): Use absolute path for client config

---

packages/nuxt/src/vite/sourceMaps.ts

Source maps generated by Vite are only for the Nuxt-part of the application whereas source maps generated by Rollup are only for the Nitro-part of the application. The Nuxt-part of the application has some overlap with the Nitro-part and so it **would** be nice to specify the client/server folder in the `assets` option, but the output is different for every Nitro preset (the files are always located under a different path). 
Should fix https://github.com/getsentry/sentry-javascript/issues/13703

fix(nuxt): Don't restrict source map assets upload

---

.github/workflows/release-comment-issues.yml
dev-packages/release-comment-issues-gh-action/.eslintrc.cjs
dev-packages/release-comment-issues-gh-action/action.yml
dev-packages/release-comment-issues-gh-action/index.mjs
dev-packages/release-comment-issues-gh-action/package.json
package.json
yarn.lock

This ensures that whenever we publish a release, we automatically add a comment to all issues linked to PRs like this:
https://github.com/getsentry/sentry-javascript/issues/13312#issuecomment-2376455183
This way, we do not need to manually go through issues, but users can automatically be notified that a change should be out now.

ci: Automatically notify issues after release

---

packages/types/src/checkin.ts

fix(types): Add jsdocs to cron types

---

packages/replay-internal/src/coreHandlers/handleGlobalEvent.ts
packages/replay-internal/test/integration/coreHandlers/handleGlobalEvent.test.ts

relates to https://github.com/getsentry/sentry-javascript/issues/13778
We're running into issues where we have replay session IDs span over hundreds of hours.
This PR is skips event processing for paused replays, which might be part of the issue.

feat(replay): Stop global event handling for paused replays

---

dev-packages/node-integration-tests/suites/tracing/meta-tags/server-sdk-disabled.js
dev-packages/node-integration-tests/suites/tracing/meta-tags/server-tracesSampleRate-zero.js
dev-packages/node-integration-tests/suites/tracing/meta-tags/test.ts
packages/core/src/utils/traceData.ts
packages/core/test/lib/utils/traceData.test.ts

This came up in a discussion with @s1gr1d: The `getTraceData` and `getTraceMetaTags` functions returned data, even if the SDK was disabled entirely (`enabled: false`). These APIs are publicly exposed and users probably call them without being aware of this limitation (as well as us in our meta framework SDKs). This PR ensures that we don't return data in case the SDK is disabled. 
Added more tests to ensure this is now properly covered, along with a test for behaviour with `tracesSampleRate: 0`.

fix(core): Don't return trace data in `getTraceData` and `getTraceMetaTags` if SDK is disabled

---

dev-packages/e2e-tests/test-applications/solidstart/tests/errorboundary.test.ts

CI is currently blocked because a test in our solidStart e2e test app is failing. It seems like for some reason, when first accessing the `/error-boundary` route, a hydration error is thrown that's caught by the set error boundary. I didn't get to the bottom of why this hydration error is being thrown but at least we can work around it by simply reloading the page before triggering the sample error. This PR does exactly that. We should follow up with a proper fix for this (cc @andreiborza when you get a chance)

test(e2e/solidstart): Skip hydration error to unblock CI

---

packages/nextjs/package.json

The peer dependency introduced in https://github.com/getsentry/sentry-javascript/pull/13571 seems to be too strict.
After installing the latest next version (14.2.13) and @sentry/next version (8.32.0), I get the following:
```sh
└─┬ @sentry/nextjs 8.32.0
└── ✕ unmet peer webpack@5.94.0: found 5.95.0
```

Loosen @sentry/nextjs webpack peer dependency

---

.github/workflows/build.yml

Since we have a bunch of work planned for Next.js and Next.js conf is moving closer it would be good to check for any changes to be compatible with the most recent Next.js canaries.
Note: The tests are optional and non-blocking for any PRs.

test: Run Next.js canary tests on PRs

---

dev-packages/e2e-tests/test-applications/nextjs-14/app/generation-functions/page.tsx
dev-packages/e2e-tests/test-applications/nextjs-14/app/propagation/utils.ts
dev-packages/e2e-tests/test-applications/nextjs-15/app/ppr-error/[param]/page.tsx
dev-packages/e2e-tests/test-applications/nextjs-app-dir/app/client-component/parameter/[...parameters]/page.tsx
dev-packages/e2e-tests/test-applications/nextjs-app-dir/app/client-component/parameter/[parameter]/page.tsx
dev-packages/e2e-tests/test-applications/nextjs-app-dir/app/server-component/parameter/[...parameters]/page.tsx
dev-packages/e2e-tests/test-applications/nextjs-app-dir/app/server-component/parameter/[parameter]/page.tsx
packages/nextjs/src/common/withServerActionInstrumentation.ts

Changes in Next.js https://github.com/vercel/next.js/pull/68812
This PR is mostly just adjusting our E2E tests so they don't fail while building.
Additionally, we had to update the `withServerActionInstrumentation` API in a semver-minor way so you can pass a promise to the `headers` option. The `ReadonlyHeaders` type isn't exposed in all Next.js versions so for now I typed it as `any`.
Resolves https://github.com/getsentry/sentry-javascript/issues/13805
Resolves https://github.com/getsentry/sentry-javascript/issues/13779
Resolves https://github.com/getsentry/sentry-javascript/issues/13780

feat(nextjs): Support new async APIs (`headers()`, `params`, `searchParams`)

---

packages/browser/src/helpers.ts
packages/browser/test/integrations/helpers.test.ts

`__sentry_wrapped__` may be overwritten by libraries, causing subsequent code to crash if the new value is not a function.

fix(browser): Ensure `wrap()` only returns functions

---

dev-packages/e2e-tests/test-applications/react-router-6/tests/sse.test.ts
packages/utils/src/instrument/fetch.ts

This is a quick fix to address a memory overflow issue caused by the recursive approach when handling endless streams (e.g., CCTV).   
However, this is not a perfect solution, as this approach still does not trigger the onFinishedResolving callback for streams that never terminate.
Fixes GH-13806
- [] Ensure your code lints and the test suite passes (`yarn lint`) & (`yarn test`).
The lints didn't pass but they are unrelated to the changes in this commit?

fix(fetch): Fix memory leak when handling endless streaming

---

CHANGELOG.md
packages/browser/src/helpers.ts
packages/browser/test/unit/integrations/helpers.test.ts

Backport of https://github.com/getsentry/sentry-javascript/pull/13838 targeting v7.x.
---

fix(browser/v7): Ensure `wrap()` only returns functions (#13838 backport)

---

dev-packages/node-integration-tests/suites/tracing/amqplib/scenario-message.ts
dev-packages/node-integration-tests/suites/tracing/amqplib/utils.ts

Managed to stop flakes locally with these updates

fix(test): Fix flaky amqplib test

---

dev-packages/node-integration-tests/suites/tracing/dataloader/scenario.js
packages/node/src/integrations/tracing/index.ts

Ref: https://github.com/getsentry/sentry-javascript/issues/13869
Removing `dataloader` instrumentation from default integrations until we patch this upstream.

fix(node): Remove `dataloader` instrumentation from default integrations

---

packages/browser/src/index.bundle.replay.ts
packages/browser/src/index.bundle.tracing.replay.feedback.ts
packages/browser/src/index.bundle.tracing.replay.ts

Closes https://github.com/getsentry/sentry-javascript/issues/13879
I opted to not export a shim for this in non-Replay bundles, as this is already more advanced usage... We can still opt to export shims here later if needed.

feat(cdn): Export `getReplay` in replay CDN bundles

---

packages/nextjs/src/client/index.ts
packages/nextjs/src/common/index.ts
packages/nextjs/src/common/pages-router-instrumentation/_error.ts
packages/nextjs/src/common/pages-router-instrumentation/wrapApiHandlerWithSentry.ts
packages/nextjs/src/common/pages-router-instrumentation/wrapApiHandlerWithSentryVercelCrons.ts
packages/nextjs/src/common/pages-router-instrumentation/wrapAppGetInitialPropsWithSentry.ts
packages/nextjs/src/common/pages-router-instrumentation/wrapDocumentGetInitialPropsWithSentry.ts
packages/nextjs/src/common/pages-router-instrumentation/wrapErrorGetInitialPropsWithSentry.ts
packages/nextjs/src/common/pages-router-instrumentation/wrapGetInitialPropsWithSentry.ts
packages/nextjs/src/common/pages-router-instrumentation/wrapGetServerSidePropsWithSentry.ts
packages/nextjs/src/common/pages-router-instrumentation/wrapGetStaticPropsWithSentry.ts
packages/nextjs/src/common/pages-router-instrumentation/wrapPageComponentWithSentry.ts
packages/nextjs/src/edge/index.ts
packages/nextjs/src/server/index.ts

Simply moves all runtime agnostic instrumentation related to the pages router into its own folder.

ref(nextjs): Move pages router instrumentation into separate folder

---

.github/workflows/external-contributors.yml

I noticed multiple times, e.g. https://github.com/getsentry/sentry-javascript/pull/13883, that the external contributor PRs do not trigger CI automatically. 
I think this is because stuff that is triggered by GITHUB_TOKEN does not trigger CI. So I am updating this to use the repo scoped token instead, let's see if that works.

ci: Use PAT for external contributor PR

---

CHANGELOG.md
MIGRATION.md

Before the v8 release we decided to use `globalThis` to simplify access the global object across all platforms and contexts.
`globalThis` is not ES2018 but we didn't consider this when the minimum supported browser versions were documented.

fix(docs): Correct supported browsers due to `globalThis`

---

packages/nextjs/src/common/_error.ts
packages/nextjs/src/common/utils/edgeWrapperUtils.ts
packages/nextjs/src/common/utils/wrapperUtils.ts
packages/nextjs/src/common/withServerActionInstrumentation.ts
packages/nextjs/src/common/wrapApiHandlerWithSentry.ts
packages/nextjs/src/common/wrapRouteHandlerWithSentry.ts
packages/nextjs/src/common/wrapServerComponentWithSentry.ts
packages/utils/src/index.ts
packages/utils/src/vercelWaitUntil.ts
packages/utils/test/vercelWaitUntil.test.ts

Moving function to be used in other SDKs that can be deployed to Vercel.

ref(utils): Move `vercelWaitUntil` to utils

---

packages/nextjs/src/server/index.ts

I had a situation once that I couldn't reproduce where I encountered Sentry spans being sent with Next.js OTEL tracing. This PR ignores those spans.

ref(nextjs): Ignore sentry spans based on query param attribute

---

packages/nextjs/src/server/index.ts

POST requests and such can also emit `_not-found` transactions. We want to drop those.

fix(nextjs): Drop `_not-found` spans for all HTTP methods

---

packages/node/src/integrations/tracing/graphql.ts
packages/node/src/otel/instrument.ts
packages/node/test/integrations/tracing/graphql.test.ts

Noticed this by chance, due to the way `generateInstrumentOnce` works, we need to pass in the fully formed config.

fix(node): Ensure graphql options are correct when preloading

---

CHANGELOG.md
packages/nextjs/src/common/types.ts
packages/nextjs/src/common/wrapApiHandlerWithSentry.ts

Cleans up the instrumentation for pages router API routes and removes some dead code.

ref(nextjs): Remove dead code

---

.size-limit.js
dev-packages/browser-integration-tests/suites/replay/dsc/subject.js
dev-packages/browser-integration-tests/suites/replay/dsc/test.ts
dev-packages/browser-integration-tests/utils/helpers.ts
packages/replay-internal/src/replay.ts
packages/replay-internal/src/util/resetReplayIdOnDynamicSamplingContext.ts

When a replay is stopped (for whatever reason), we want to ensure to remove the `replay_id` from the DSC.
This can be in two places:
1. Frozen onto the current spans DSC
2. On the current scope propagation context DSC
We just reset it on both.
Closes https://github.com/getsentry/sentry-javascript/issues/13872

fix(replay): Ensure `replay_id` is removed from frozen DSC when stopped

---

dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/route-handlers.test.ts
packages/nextjs/src/common/wrapRouteHandlerWithSentry.ts
packages/nextjs/src/server/index.ts

fixes https://github.com/getsentry/sentry-javascript/issues/13593

feat(nextjs): Use OTEL instrumentation for route handlers

---

packages/nextjs/src/common/pages-router-instrumentation/wrapApiHandlerWithSentry.ts
packages/nextjs/src/common/span-attributes-with-logic-attached.ts
packages/nextjs/src/server/index.ts

Drop all spans/transactions emitted by Next.js for pages router API routes because they are currently super buggy with wrong timestamps. Fix pending: https://github.com/vercel/next.js/pull/70908
This is just a bit of prep-work so we can at some point disable the logic where we turn on all Next.js spans and still have high quality data.

ref(nextjs): Make Pages Router API Routes instrumentation OTEL ready

---

packages/replay-internal/src/coreHandlers/handleAfterSendEvent.ts

It is possible that an error gets thrown outside
of flushing (we should be catching exceptions in
flush and do no re-throw), which our core SDK
error handler would catch due to global rejection
handler and trigger replay SDK to flush again.

fix(replay): Try/catch `sendBufferedReplayOrFlush` to prevent cycles

---

packages/sveltekit/src/server/serverRoute.ts

SvelteKit narrows the type of event.params based on ParamMatchers that are defined in the path, by making the function generic we can respect the narrowed type
Follow up to  #13247

fix(sveltekit): update wrapServerRouteWithSentry to respect ParamMatchers

---

dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/client-app-routing-instrumentation.test.ts
dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/route-handlers.test.ts
dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/server-components.test.ts
packages/nextjs/src/common/span-attributes-with-logic-attached.ts
packages/nextjs/src/common/wrapGenerationFunctionWithSentry.ts
packages/nextjs/src/common/wrapServerComponentWithSentry.ts
packages/nextjs/src/server/index.ts

Disables the instrumentation for incoming HTTP requests to be consistent across Next.js versions for instrumentation.
Next 13 and 15 work with the HTTP instrumentation. 14 doesn't.

ref: Disable incoming HTTP request instrumentation

---

packages/replay-internal/src/eventBuffer/EventBufferProxy.ts

Saw this while debugging, this should not have a big effect since the fallback buffer should be relatively small.

feat(replay): Clear fallback buffer when switching buffers

---

packages/nextjs/src/config/loaders/wrappingLoader.ts

Looks like we missed adding the `build` dir to the template path of `requestAsyncStorageShim` in the NextJS SDK when we changed the package-internal directory structure a while ago (IIRC this was pre-v8 but not sure actually)
I'm a bit surprised that this works at all, given we use `exports` conditions and this is a path to a specific file not covered by any `exports` entry. But I guess webpack can handle this still.
EDIT: Well turns out, this doesn't work. We'll need to add the `exports` entries.
fixes https://github.com/getsentry/sentry-javascript/issues/13925
closes https://github.com/getsentry/sentry-javascript/issues/13926
closes https://github.com/getsentry/sentry-javascript/issues/13927

fix(nextjs): Adjust path to `requestAsynStorageShim.js` template file

---

dev-packages/e2e-tests/test-applications/nextjs-15/package.json
packages/nextjs/src/config/templates/routeHandlerWrapperTemplate.ts
packages/nextjs/src/config/templates/serverComponentWrapperTemplate.ts
packages/nextjs/src/config/webpack.ts

In Next.js v15.0.0-canary.180, requestAsyncStorage was removed and merged into workUnitAsyncStorage (vercel/next.js#70819). workUnitAsyncStorage is used if available. workUnitAsyncStorage is used when workUnitAsyncStorage is present.
----

fix(nextjs): Detect new locations for request async storage to support Next.js v15.0.0-canary.180 and higher

---

.github/workflows/build.yml

Ref: https://github.com/codecov/test-results-action/issues/91
The job randomly fails and causes CI failure.

meta(ci): Don't fail CI run when codecov fails to upload

---

CHANGELOG.md
packages/nextjs/package.json
yarn.lock

Resolves https://github.com/getsentry/sentry-javascript/issues/13934

chore(nextjs/v7): Bump rollup to 2.79.2

---

packages/astro/src/index.types.ts
packages/nextjs/src/index.types.ts
packages/nuxt/src/index.types.ts
packages/remix/src/index.types.ts
packages/solidstart/src/index.types.ts
packages/sveltekit/src/index.types.ts

Fixes https://github.com/getsentry/sentry-javascript/issues/13932
We have defined the type for the shared client/server types in meta-frameworks incorrectly, `init` now returns `Client | undefined` and not `void` anymore.

fix: Ensure type for `init` is correct in meta frameworks

---

.github/workflows/external-contributors.yml

It seems that `github.actor` is not necessarily the PR author, but possibly the user that merged the PR.
You can see e.g. here: https://github.com/getsentry/sentry-javascript/actions/runs/11270299315/job/31340702772 how it still ran for a dependabot PR.

ci: Ensure we check correctly for bot users

---

CHANGELOG.md

This PR adds the external contributor to the CHANGELOG.md file, so that they are credited for their contribution. See #13922

ref: Add external contributor to CHANGELOG.md

---

packages/nextjs/src/server/index.ts

We can assume that `BaseServer.handleRequest` without route is always low-quality data so we can drop it.

feat(nextjs): Drop `BaseServer.handleRequest` without route

---

dev-packages/browser-integration-tests/suites/tracing/dsc-txn-name-update/init.js
dev-packages/browser-integration-tests/suites/tracing/dsc-txn-name-update/subject.js
dev-packages/browser-integration-tests/suites/tracing/dsc-txn-name-update/template.html
dev-packages/browser-integration-tests/suites/tracing/dsc-txn-name-update/test.ts
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/pageload-meta/subject.js
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/pageload/test.ts
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/subject.js
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/template.html
dev-packages/node-integration-tests/suites/tracing/dsc-txn-name-update/scenario-events.ts
dev-packages/node-integration-tests/suites/tracing/dsc-txn-name-update/scenario-headers.ts
dev-packages/node-integration-tests/suites/tracing/dsc-txn-name-update/test.ts

This PR adds a browser integration test that describes the current behaviour of how we update the `transaction` field in the DSC which is propagated via the `baggage` header and added to envelopes as the `trace` header.
Specifically, this test shows a somewhat typical scenario for browser-side routing instrumentation where we initially have a low-quality URL txn name and only after a while update the name with a parameterized route. This test however also shows that we continue to update (i.e. not freeze) the DSC for subsequent transaction name updates. This is something we might want to change in the future, so that we only once set the `transaction` field when we have a high-quality txn name and freeze it afterwards, as discussed with @cleptric.
For more information on the test …

test(browser): Add test for current DSC transaction name updating behavior

---

.size-limit.js
packages/replay-internal/src/util/handleRecordingEmit.ts
packages/replay-internal/test/integration/errorSampleRate.test.ts

This fixes a bug where an older, saved session (that has a `previousSessionId`, i.e. session was recorded and expired) would cause buffered replays to not send when an error happens. This is because the session start timestamp would never update, causing our flush logic to skip sending the replay due to incorrect replay duration calculation.

fix(replay): Fix onError sampling when loading an expired buffered session

---

dev-packages/node-integration-tests/suites/tracing/dsc-txn-name-update/scenario-events.ts
dev-packages/node-integration-tests/suites/tracing/dsc-txn-name-update/scenario-headers.ts
dev-packages/node-integration-tests/suites/tracing/dsc-txn-name-update/test.ts

This PR adds tests for DSC updating behaviour in the Node SDK, analogously to #13953
Currently, also in Node, we mutate the DSC and always include the most up to date transaction name

test(node): Add tests for current DSC transaction name updating behavior

---

dev-packages/e2e-tests/test-applications/nextjs-app-dir/app/layout.tsx
dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/client-app-routing-instrumentation.test.ts
dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/edge-route.test.ts
packages/nextjs/src/server/index.ts

We were dropping a few too many transactions.

fix(nextjs): Don't drop transactions for server components on navigations

---

packages/nuxt/src/vite/utils.ts
packages/nuxt/test/vite/utils.test.ts

While the preset for Netlify exports the serverless handler function as `export { D as default }`, the Vercel preset exports this handler as `export { D as handler };`.
This PR makes some adaptions to the code generation in the plugin to make it possible to re-export `default` functions. The previous snippet did not work as `default` is obviously not allowed as a function name.

fix(nuxt): Re-export 'default' exports with rollup plugin

---

packages/replay-internal/src/coreHandlers/util/fetchUtils.ts
packages/replay-internal/src/types/request.ts
packages/replay-internal/test/unit/coreHandlers/util/fetchUtils.test.ts

Change this to be a warn level log instead of an exception (which gets captured to Sentry). Since this is an error we are throwing ourselves and it is to be expected, no need to treat as an exception.
This also adds a new meta string to differentiate from an error while parsing. This means we can show a more specific error message on the frontend.

feat(replay): Do not log "timeout while trying to read resp body" as exception

---

dev-packages/node-integration-tests/suites/tracing/httpIntegration/server-ignoreOutgoingRequests.js
dev-packages/node-integration-tests/suites/tracing/httpIntegration/test.ts
packages/node/src/integrations/http/SentryHttpInstrumentation.ts
packages/node/src/integrations/http/index.ts

This PR fixes a bug, initially reported in [Discord](https://discord.com/channels/621778831602221064/1293560604816179201/1293560604816179201), which caused the `httpIntegration`'s `ignoreOutgoingRequests` option to not be applied to breadcrumb creation for outgoing requests. The result was that despite spans being correctly filtered by the option, breadcrumbs would still be created which contradicts the function'S JSDoc and [our docs](https://docs.sentry.io/platforms/javascript/guides/node/configuration/integrations/http/#ignoreoutgoingrequests).
It seems like this was already a bug prior to #13763. However, the behaviour seems to have been carried over to #13763. 
This PR fixes the bug by:
- correctly passing in `ignoreOutgoingRequests` to `SentryHttpIntegration` (same signature as …

fix(node): Ensure `ignoreOutgoingRequests` of `httpIntegration` applies to breadcrumbs

---

dev-packages/e2e-tests/test-applications/nuxt-3/package.json
dev-packages/e2e-tests/test-applications/nuxt-4/package.json
packages/nuxt/src/common/types.ts
packages/nuxt/src/module.ts
packages/nuxt/src/vite/addServerConfig.ts
packages/nuxt/src/vite/utils.ts
packages/nuxt/test/vite/utils.test.ts

BREAKING CHANGE: The `--import` flag must not be added anymore. If it is still set, the server-side will be initialized twice and this leads to unexpected errors.
---
First merge this: https://github.com/getsentry/sentry-javascript/pull/13945
Part of this: https://github.com/getsentry/sentry-javascript/issues/13943
This PR makes it the default to include a rollup plugin that wraps the server entry file with a dynamic import (`import()`). This is a replacement for the node `--import` CLI flag.
If you still want to manually add the CLI flag you can use this option in the `nuxt.config.ts` file:
```js
sentry: {
dynamicImportForServerEntry: false,
}
```
(option name is up for discussion)

feat(nuxt): Make dynamic import() wrapping default

---

.github/workflows/release-comment-issues.yml

Noticed here: https://github.com/getsentry/sentry-javascript/issues/13932#issuecomment-2414900079 we should not add comments for prereleases 😅

ci: Ensure release comments are not added for prereleases

---

packages/nuxt/README.md

Removes code snippets with `--import` and adds a "Troubleshooting" section.

docs(nuxt): Add beta readme

---

packages/nuxt/src/vite/sourceMaps.ts
packages/nuxt/test/vite/sourceMaps.test.ts

Nuxt implementation for: https://github.com/getsentry/sentry-javascript/issues/13993
Fixes: https://github.com/getsentry/sentry-javascript/issues/13997
In Nuxt, there are 3 places to set source maps (and all need to be enabled):
- `sourcemap`
- `nitro.rollupConfig.output.sourcemap`
- `vite.build.sourcemap`
As Nuxt sets `sourcemap.client: false` ([docs here](https://nuxt.com/docs/api/nuxt-config#sourcemap)), it's not possible to determine whether this setting was set by the user or the framework. Users have to set this manually like this:
```js
export default defineNuxtConfig({
sourcemap: {
client: true,
},
})
```
With this PR, all source maps are set to `'hidden'` if they were undefined before and keep the setting otherwise. This is done in 3 separate functions (one for vite, rollup and …

feat(nuxt): Respect user-provided source map generation settings

---

packages/nuxt/src/module.ts

Sentry is initialized too late in development mode and tracing does not work. This is a note to inform users about that. Will be fixed in the stable version.

feat(nuxt): Log server instrumentation might not work in dev

---

.size-limit.js
packages/replay-internal/src/eventBuffer/EventBufferCompressionWorker.ts
packages/replay-internal/src/eventBuffer/EventBufferProxy.ts
packages/replay-internal/src/replay.ts
packages/replay-internal/src/util/handleRecordingEmit.ts

This is not intended to be merged to prod, I would like to debug how/why
we keep hitting EventBuffer limits on Sentry SaaS. Aside from debugging
statements, there should be no other behavioral changes.

debug(replay): Add debugging statements around event buffer

---

.eslintrc.js
.github/workflows/build.yml
dev-packages/e2e-tests/test-applications/nextjs-15/.gitignore
dev-packages/e2e-tests/test-applications/nextjs-15/next-env.d.ts
dev-packages/e2e-tests/test-applications/nextjs-15/start-event-proxy.mjs
dev-packages/test-utils/src/event-proxy-server.ts
scripts/normalize-e2e-test-dump-transaction-events.js

- Adds an option to the e2e test proxy to dump all events into a file
- Adds a utility script that transforms an event dump into a deterministic human-readable output

test(e2e): Add event proxy option to allow for event dumps

---

dev-packages/e2e-tests/test-applications/solidstart/package.json
dev-packages/e2e-tests/test-applications/solidstart/post_build.sh
dev-packages/e2e-tests/test-applications/solidstart/tests/errorboundary.test.ts

Adds a small post-build script to copy over deps that are not correctly resolved in our yarn workspace/pnpm e2e test applications (but do work correctly in standalone projects). This allows us to finally use the vinxi production server to run e2e tests and is similar to what the Nuxt SDK has to do.
Also allows us to get rid of the double page loads for the first test to avoid hydration errors that were caused by the dev server previously.

fix(solidstart): Use production server for e2e tests

---

packages/nuxt/README.md

Clarify override for pnpm and fix file name.

fix(nuxt): Server-side setup in readme

---

dev-packages/e2e-tests/test-applications/nuxt-4/app/pages/pinia-cart.vue
dev-packages/e2e-tests/test-applications/nuxt-4/nuxt.config.ts
dev-packages/e2e-tests/test-applications/nuxt-4/package.json
dev-packages/e2e-tests/test-applications/nuxt-4/sentry.client.config.ts
dev-packages/e2e-tests/test-applications/nuxt-4/stores/cart.ts
dev-packages/e2e-tests/test-applications/nuxt-4/tests/pinia.test.ts
packages/nuxt/src/common/types.ts
packages/nuxt/src/runtime/plugins/sentry.client.ts

closes https://github.com/getsentry/sentry-javascript/issues/14039
By adding `trackPinia`, the Pinia store is monitored with Sentry.
```js
Sentry.init({
dsn: useRuntimeConfig().public.sentry.dsn,
trackPinia: true
});
```
or with custom options:
```js
Sentry.init({
dsn: useRuntimeConfig().public.sentry.dsn,
trackPinia: {
actionTransformer: action => `Transformed: ${action}`,
},
});
```

feat(nuxt): Add Sentry Pinia plugin

---

.github/workflows/build.yml
packages/nextjs/src/config/loaders/wrappingLoader.ts
scripts/normalize-e2e-test-dump-transaction-events.js

We had some instances of `unknown page server component` being recorded because we were passing `page.tsx` instead of `/page.tsx` to the matching regex and the regex always matched for a leading slash.

fix(nextjs): Fix matching logic for file convention type for root level components

---

CHANGELOG.md

Re-adds replay SDK debug statements from a prior prelease (and includes 8.35.0 changes).

meta: Prepare prelease of 8.36.0-alphs.0

---

packages/nextjs/src/server/index.ts

It seems like the way we configured this still emitted HTTP spans for incoming reqs.

fix(nextjs): Disable incoming http spans

---

dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/transactions.test.ts
packages/nextjs/src/common/withServerActionInstrumentation.ts

Stop escaping Next.js tracing for server action instrumentation.
When using `withServerActionInstrumentation` the trace will look like this now:

feat(nextjs): Include server action transaction in next tracing

---

dev-packages/e2e-tests/test-applications/nextjs-13/instrumentation.ts
dev-packages/e2e-tests/test-applications/nextjs-13/tests/server/excluded-api-endpoints.test.ts
dev-packages/e2e-tests/test-applications/nextjs-13/tests/server/getServerSideProps.test.ts
dev-packages/e2e-tests/test-applications/nextjs-app-dir/next-env.d.ts
dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/edge-route.test.ts
dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/edge.test.ts
dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/route-handlers.test.ts
dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/server-components.test.ts
packages/nextjs/src/common/wrapRouteHandlerWithSentry.ts

Adds finishing touches to the target branch, unskipping tests ensuring we are not breaking anything.

ref(nextjs): Fix tests

---

packages/nuxt/src/vite/addServerConfig.ts

fixes https://github.com/getsentry/sentry-javascript/issues/14057
`@nuxt/content` adds entry files to rollup. This fix adds a check for `.mjs` to ignore other files in the rollup plugin.

fix(nuxt): Only wrap `.mjs` entry files in rollup

---

packages/replay-internal/src/eventBuffer/EventBufferCompressionWorker.ts
packages/replay-internal/src/replay.ts

Removes a log statement that is output when buffer is already full (which will keep overflowing the buffer). Also noticed a log statement in `stop()` that would trigger when we stop due to event buffer being full, which would compoound the issue. This last fix should be pulled into the SDK.

debug(replay): Remove noisy log that is causing event buffer overflow as well

---

packages/replay-internal/src/integration.ts
packages/replay-internal/test/integration/sendReplayEvent.test.ts

This fixes the `onError` callback added in https://github.com/getsentry/sentry-javascript/pull/13721 -- the option itself was not being propagated to the replay options.

fix(replay): Fix `onError` callback

---

dev-packages/browser-integration-tests/suites/public-api/startSpan/standalone-sdk-disabled/init.js
dev-packages/browser-integration-tests/suites/public-api/startSpan/standalone-sdk-disabled/subject.js
dev-packages/browser-integration-tests/suites/public-api/startSpan/standalone-sdk-disabled/test.ts
packages/core/src/baseclient.ts
packages/core/src/tracing/sentrySpan.ts

Previously, when standalone (most prominently INP) spans would `.end()`, they'd always be sent to Sentry, even if the SDK was disabled (via `Sentry.init({enabled: false})` for example). This was caused by us directly calling `transport.send` and not checking for the enabled option, instead of using the client to send the span envelope. 
This PR now changes the sending logic to use the client's `sendEnvelope` method which we generally use to send envelopes (sessions, client reports, checkins, metrics (RIP), and also events). This has a minor implication: We will now also emit a `beforeEnvelope` client hook event for sending standalone spans. I think this is actually more correct than before but could potentially break someone. IMO this is worth the "risk" as it's easily revertible and …

fix(core): Ensure standalone spans are not sent if SDK is disabled

---

dev-packages/e2e-tests/test-applications/debug-id-sourcemaps/package.json
package.json
packages/nuxt/src/vite/addServerConfig.ts
yarn.lock

This is the rollup version used for building the SDK itself, it is not shipped to users.

chore(dev-deps): Bump rollup from 4.13.0 to 4.24.2

---

packages/opentelemetry/src/spanExporter.ts

resolves https://github.com/getsentry/sentry-javascript/issues/14067
Avoid calling `Date.now()` for each span in the span exporter. This should reduce blocking I/O.

perf(otel): Only calculate current timestamp once

---

packages/profiling-node/src/integration.ts

This seems important enough to warn about each time regardless of debug build
Fixes: https://github.com/getsentry/sentry-javascript/issues/14015

fix(profiling-node): Always warn when running on incompatible major version of Node.js

---

dev-packages/node-integration-tests/package.json
yarn.lock

Only used in tests, but I'm upgrading this because most users will be on these versions anyway considering the amount of security issues in earlier versions.
resolves https://github.com/getsentry/sentry-javascript/security/dependabot/342
resolves https://github.com/getsentry/sentry-javascript/security/dependabot/336
resolves https://github.com/getsentry/sentry-javascript/security/dependabot/334
resolves https://github.com/getsentry/sentry-javascript/security/dependabot/335
resolves https://github.com/getsentry/sentry-javascript/security/dependabot/338

chore(tests): Upgrade mysql2 package to 3.11.3

---

.github/workflows/codeql-analysis.yml

We get failures when running dependabot on CodeQL PRs: https://github.com/getsentry/sentry-javascript/actions/runs/11561736812/job/32181414647
```
Warning: Resource not accessible by integration
Error: Resource not accessible by integration
Warning: Workflows triggered by Dependabot on the "push" event run with read-only access. Uploading Code Scanning results requires write access. To use Code Scanning with Dependabot, please ensure you are using the "pull_request" event for this workflow and avoid triggering on the "push" event for Dependabot branches. See https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning#scanning-on-push for more information on how to configure these events.
```
Given …

chore: Don't run dependabot on CodeQL PRs

---

dev-packages/browser-integration-tests/playwright.config.ts
dev-packages/e2e-tests/test-applications/ember-classic/playwright.config.ts
dev-packages/e2e-tests/test-applications/ember-embroider/playwright.config.ts
dev-packages/e2e-tests/test-applications/node-express-send-to-sentry/playwright.config.mjs
dev-packages/e2e-tests/test-applications/react-send-to-sentry/playwright.config.mjs
packages/remix/playwright.config.ts

This does not work properly anyhow (e.g. it shows all the tests because of how CI logs are rendered, see https://github.com/getsentry/sentry-javascript/actions/runs/11557223813/job/32202778369), so we may as well also have the added detail of per-test runtime etc. in there.

ci: Use `list` reporter for playwright on CI instead of `line`

---

.github/workflows/codeql-analysis.yml

Reverts https://github.com/getsentry/sentry-javascript/pull/14109 and re-implements this differently.
Actually, the problem was dependabot merging to develop (so the fix would not have caught that anyhow), + this was incorrect syntax (oops) as we had ignore-branches _and_ branches, which does not work.
Now, instead we just run this always but check if this is a push from dependabot, which hopefully works better.
See https://github.com/getsentry/sentry-javascript/actions/runs/11570166519

ci: Fix CodeQL workflow config

---

packages/nextjs/package.json
packages/nextjs/src/config/types.ts

Fixes https://github.com/getsentry/sentry-javascript/issues/14066
We're just vendoring the types. The chance that anyone is depending on the specifics is lim x -> 0.

fix(nextjs): Don't leak webpack types into exports

---

dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/route-handlers.test.ts
packages/nextjs/src/common/wrapRouteHandlerWithSentry.ts
packages/nextjs/src/config/templates/routeHandlerWrapperTemplate.ts

Resolves: https://github.com/getsentry/sentry-javascript/issues/13908

feat(nextjs): Add method and url to route handler request data

---

packages/aws-serverless/src/sdk.ts

Fixes [https://github.com/getsentry/sentry-javascript/security/code-scanning/307](https://github.com/getsentry/sentry-javascript/security/code-scanning/307)
To fix the prototype pollution issue, we need to ensure that the `handlerName` does not include any special properties like `__proto__`, `constructor`, or `prototype`. We can achieve this by adding a check to filter out these properties before performing the assignment.
1. Add a check to ensure `handlerName` does not include `__proto__`, `constructor`, or `prototype`.
2. If `handlerName` includes any of these properties, log an error and return without making the assignment.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

fix(aws-serverless): Remove possible prototype pollution source

---

dev-packages/e2e-tests/test-applications/create-remix-app-express-vite-dev/package.json
dev-packages/e2e-tests/test-applications/solid-solidrouter/package.json
dev-packages/e2e-tests/test-applications/solid/package.json
dev-packages/e2e-tests/test-applications/solidstart/package.json
dev-packages/e2e-tests/test-applications/svelte-5/package.json
dev-packages/e2e-tests/test-applications/sveltekit-2-svelte-5/package.json
dev-packages/e2e-tests/test-applications/sveltekit-2-twp/package.json
dev-packages/e2e-tests/test-applications/sveltekit-2/package.json
dev-packages/e2e-tests/test-applications/sveltekit/package.json
dev-packages/e2e-tests/test-applications/tanstack-router/package.json
dev-packages/e2e-tests/test-applications/vue-3/package.json
packages/astro/package.json
packages/remix/package.json
packages/sveltekit/package.json
yarn.lock

resolves all of these warnings: https://github.com/getsentry/sentry-javascript/security/dependabot?q=is%3Aopen+package%3Avite

chore: Upgrade vite dev dep to ^5.4.10

---

dev-packages/browser-integration-tests/suites/public-api/startSpan/attributes/subject.js
dev-packages/browser-integration-tests/suites/public-api/startSpan/attributes/test.ts
packages/browser-utils/src/metrics/browserMetrics.ts
packages/browser-utils/test/browser/browserMetrics.test.ts

This PR adds the `deliveryType` field of a `ResourcePeformanceEntry` to our `resource` spans. This [attribute](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming/deliveryType) can give a definitive answer if a resource was retrieved from the browser cache or if the request was actually made to the resource src. 
Unfortunately, `deliveryType` is not yet supported in all browsers but where it is, it should give us more reliable indicators of browser cache hits/misses. 
The [alternative way](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming/transferSize#checking_if_a_cache_was_hit) of checking for cache hits/misses (which is to check for transfer and decoded body sizes of a response) has a flaw: It only works for requests to 3rd party origins …

feat(browser): Add `http.response_delivery_type` attribute to resource spans

---

package.json
yarn.lock

We are not using them, so no need to include them. If/when we decide to use this again we can re-add them (in a current version).
Also resolves a security warning for outdated marked dependency.

chore(dev-deps): Remove typedoc deps

---

packages/nuxt/src/common/types.ts
packages/nuxt/src/module.ts
packages/nuxt/src/vite/addServerConfig.ts
packages/nuxt/src/vite/utils.ts
packages/nuxt/test/vite/utils.test.ts

Based on this PR: https://github.com/getsentry/sentry-javascript/pull/14086
We get the names of the exports with Rollup's `exportedBindings`, but we cannot know whether this is a function or something else. As we need to re-export serverless functions for Netlify, Vercel and so on, an educated guess is made that `'default', 'handler', 'server'` are potential serverless functions that need to be wrapped by Sentry and re-exported. 
In case users experience issues, this can be changed with `entrypointWrappedFunctions`.
All other exports are exported as they were before.

feat(nuxt): Add `entrypointWrappedFunctions` to define async wrapped server functions

---

dev-packages/node-integration-tests/suites/esm/modules-integration/app.mjs
dev-packages/node-integration-tests/suites/esm/modules-integration/test.ts
packages/node/src/integrations/modules.ts

resolves https://github.com/getsentry/sentry-javascript/issues/12500
resolves https://github.com/getsentry/sentry-javascript/issues/14165
`modulesIntegration` uses top-level require which will crash ESM apps if you explicitly import and use the integration.
```mjs
// index.mjs
Sentry.init({
dsn: '__DSN__',
Sentry.modulesIntegration(),
]
});
```
This fixes that by adding a boolean check for cjs apps, and logging out a warning as a result.

fix(node): Make sure modulesIntegration does not crash esm apps

---

.size-limit.js
packages/astro/src/index.server.ts
packages/astro/src/index.types.ts
packages/aws-serverless/src/index.ts
packages/browser/src/metrics.ts
packages/bun/src/index.ts
packages/cloudflare/src/index.ts
packages/core/src/index.ts
packages/core/src/metrics/aggregator.ts
packages/core/src/metrics/exports-default.ts
packages/core/src/metrics/exports.ts
packages/core/test/lib/metrics/timing.test.ts
packages/deno/src/index.ts
packages/deno/src/sdk.ts
packages/google-cloud-serverless/src/index.ts
packages/nextjs/src/index.types.ts
packages/node/src/index.ts
packages/nuxt/src/index.types.ts
packages/remix/src/index.server.ts
packages/remix/src/index.types.ts
packages/solidstart/src/index.types.ts
packages/solidstart/src/server/index.ts
packages/sveltekit/src/index.types.ts
packages/sveltekit/src/server/index.ts
packages/vercel-edge/src/index.ts

The metrics beta has ended, so we are deprecating the metrics API.
🫡

feat: Deprecate metrics API

---

dev-packages/e2e-tests/test-applications/nestjs-basic/src/app.controller.ts
dev-packages/e2e-tests/test-applications/nestjs-basic/src/app.service.ts
dev-packages/e2e-tests/test-applications/nestjs-basic/tests/cron-decorator.test.ts
packages/core/src/exports.ts
packages/core/test/lib/base.test.ts

https://github.com/getsentry/sentry-javascript/pull/14182/commits/d045ba1b51dd8b889cba60bfdf154b907b725a0a adds tests that fail: 
https://github.com/getsentry/sentry-javascript/actions/runs/11682775381/job/32530893436?pr=14182#step:14:217
https://github.com/getsentry/sentry-javascript/pull/14182/commits/be36a2284923907a2a3d9323526b0196bf0fae8c adds the fix
Closes: https://github.com/getsentry/sentry-javascript/issues/14163

fix(core): Ensure errors thrown in async cron jobs bubble up

---

.size-limit.js
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/long-tasks-before-navigation/init.js
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/long-tasks-before-navigation/subject.js
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/long-tasks-before-navigation/template.html
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/long-tasks-before-navigation/test.ts
packages/browser-utils/src/metrics/browserMetrics.ts
packages/browser/package.json

This PR fixes inconsistent behaviour in our browserTracingIntegration, where we'd previously add `ui.long-task` spans to an ongoing (navigation) transaction, even if the long task started before the navigation transaction started. 
Most other browserTracingIntegration spans (resource, timing, measure/mark spans) are already dropped/not started if their start time stamp is earlier than the navigation start time stamp. This happens in [one central location](https://github.com/getsentry/sentry-javascript/blob/c2bae3ed9cd4a79fc634b1b7f2baa1d2fad246ef/packages/browser-utils/src/metrics/browserMetrics.ts#L312-L314) but it does not apply to long-task spans because they have to be handled separately. 
This PR specifically:
- not checks for the start time stamp and drops long task spans starting …

fix(browser): Avoid recording long task spans starting before their parent span

---

packages/opentelemetry/package.json

Sadly, https://github.com/getsentry/sentry-javascript/pull/14174 didn't bump the dep in `@sentry/opentelemetry`.

feat(deps): Bump @opentelemetry/instrumentation from 0.53.0 to 0.54.0 for @sentry/opentelemetry

---

dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/long-animation-frame-before-navigation/init.js
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/long-animation-frame-before-navigation/subject.js
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/long-animation-frame-before-navigation/template.html
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/long-animation-frame-before-navigation/test.ts
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/long-tasks-before-navigation/subject.js
packages/browser-utils/src/metrics/browserMetrics.ts

Analogously to #14183 for long task spans, this PR ensures we don't create and attach `ui.long-animation-frame` spans to navigation spans/transactions if they were started before the navigation span. 
Changes in this PR: 
- Check for start time of parent navigation span and don't start span long animation frame span if its start timestamp is earlier than the navigation start time stamp
- Refactor span starting logic to use common helper function to compensate the bundle size increase
- Add regression test that failed previously
- Improve regression test from #14183 to avoid flakes and improve the in-test navigation

fix(browser): Avoid recording long animation frame spans starting before their parent span

---

packages/browser-utils/src/metrics/browserMetrics.ts

This PR replaces the manual start and end calls for interaction child spans with our `startAndEndSpan` helper.
Using `startAndEndSpan` also will adjust the root span's start time stamp if the (in this case interaction-) child span starts earlier than the parent span. I think in this particular case, this is fine or even desireable because my testing so far has shown that the performance entry we use for the child spans starts a couple of ms earlier than the surrounding idle interaction transaction. We can add a similar check as in #14183 or #14186 if this becomes a problem.
Further context: If users enable `experiments.enableInteractions`, for every click, we create:
1. A root idle span whose name is the name of the current route (unless there's an ongoing pageload/navigation span)
2. A …

ref(browser): Ensure start time of interaction root and child span is aligned

---

packages/browser/src/profiling/utils.ts
packages/core/src/utils/prepareEvent.ts
packages/profiling-node/src/utils.ts
packages/utils/src/debug-ids.ts
packages/utils/src/index.ts

In the process of fixing https://github.com/getsentry/sentry-electron/issues/1011 I was looking for a way to get a `Map<Filename, DebugId>`.  I found that there was already some code duplication for parsing and caching of debug ids from the polyfilled globals.
This PR moves the common code to `@sentry/utils` which will be useful for fixing the above.

feat(utils): Single implementation to fetch debug ids

---

dev-packages/e2e-tests/test-applications/react-router-6/tests/sse.test.ts

Resolves https://github.com/getsentry/sentry-javascript/issues/14200
RR was emitting an additional log message which caused the matching to fail.

test(e2e): Fix react router 6 canary test

---

dev-packages/e2e-tests/test-applications/react-send-to-sentry/package.json

test(e2e): Pin react-router-dom dep in `react-send-to-sentry` Test

---

dev-packages/browser-integration-tests/suites/integrations/lazyLoad/moduleMetadataIntegration/init.js
dev-packages/browser-integration-tests/suites/integrations/lazyLoad/moduleMetadataIntegration/subject.js
dev-packages/browser-integration-tests/suites/integrations/lazyLoad/moduleMetadataIntegration/test.ts
dev-packages/browser-integration-tests/utils/generatePlugin.ts
packages/browser/rollup.bundle.config.mjs
packages/browser/src/integrations-bundle/index.modulemetadata.ts
packages/browser/src/utils/lazyLoadIntegration.ts

This PR fixes #13803, and adds support for `moduleMetadataIntegration` to be lazy loaded, in [this](https://docs.sentry.io/platforms/javascript/configuration/integrations/#2-load-from-cdn-with-lazyloadintegration) manner.
This integration is crucial for the [micro-frontend recommended solution](https://docs.sentry.io/platforms/javascript/best-practices/micro-frontends/#automatically-route-errors-to-different-projects-depending-on-module). 
**Note**: I'll also try to create a PR for version ^7.0.

feat(browser): Add moduleMetadataIntegration lazy loading support

---

dev-packages/e2e-tests/test-applications/nextjs-t3/tests/trpc-error.test.ts
dev-packages/e2e-tests/test-applications/nextjs-t3/tests/trpc-mutation.test.ts
dev-packages/e2e-tests/test-applications/node-express/tests/trpc.test.ts
packages/core/src/trpc.ts

Resolves https://github.com/getsentry/sentry-javascript/issues/14158

feat(core): Add trpc path to context in trpcMiddleware

---

packages/node/src/integrations/tracing/amqplib.ts
packages/node/src/integrations/tracing/connect.ts
packages/node/src/integrations/tracing/dataloader.ts
packages/node/src/integrations/tracing/express.ts
packages/node/src/integrations/tracing/fastify.ts
packages/node/src/integrations/tracing/genericPool.ts
packages/node/src/integrations/tracing/graphql.ts
packages/node/src/integrations/tracing/hapi/index.ts
packages/node/src/integrations/tracing/kafka.ts
packages/node/src/integrations/tracing/koa.ts
packages/node/src/integrations/tracing/lrumemoizer.ts
packages/node/src/integrations/tracing/mongo.ts
packages/node/src/integrations/tracing/mongoose.ts
packages/node/src/integrations/tracing/mysql.ts
packages/node/src/integrations/tracing/mysql2.ts
packages/node/src/integrations/tracing/postgres.ts
packages/node/src/integrations/tracing/prisma.ts
packages/node/src/integrations/tracing/redis.ts
packages/node/src/integrations/tracing/tedious.ts

Related to https://github.com/getsentry/sentry-javascript/issues/13317
Improve the docstrings and link to documentation pages as appropriate (as they contain information about opentelemetry and supported versions).

docs: Improve docstrings for node otel integrations

---

.github/workflows/external-contributors.yml

We aren't changing any user code, so let's avoid using `ref` in the commit.

build: Update external contributors action to use chore instead of ref

---

dev-packages/node-integration-tests/suites/anr/basic.js
dev-packages/node-integration-tests/suites/anr/basic.mjs
dev-packages/node-integration-tests/suites/anr/test.ts
packages/node/src/integrations/anr/index.ts
packages/node/src/integrations/anr/worker.ts

- Ref: https://github.com/getsentry/sentry-electron/issues/1011
Sends a map of filename -> debug ids to the ANR worker thread and sends an updated list every time more modules are loaded. These are then used and included with events so they can be symbolicated

fix(node): Include `debug_meta` with ANR events

---

CHANGELOG.md

This PR adds the external contributor to the CHANGELOG.md file, so that they are credited for their contribution. See #13526

chore: Add external contributor to CHANGELOG.md

---

packages/nuxt/src/vite/addServerConfig.ts

With nitro 2.10.X the way we imported the server config file and dynamically imported the nitro runtime broke. Instead of landing in the server output entry file, the sdk init and dynamic import landed in the nitro runtime itself.
Based on https://github.com/nitrojs/nitro/commit/8b4a408231bdc222569a32ce109796a41eac4aa6#diff-e58102d2230f95ddeef2662957b48d847a6e891e354cfd0ae6e2e03ce848d1a2R142 we managed to get back to the original solution by using the `\0raw` prefix for the entry file.
__Note for internal__: This does not play well when using symlinks (like `yarn link`) to link the sdk into a project. Haven't tested how yalc behaves, but tarballs work.

fix(nuxt): Fix dynamic import rollup plugin to work with latest nitro

---

dev-packages/node-integration-tests/README.md
dev-packages/node-integration-tests/suites/express/handle-error-scope-data-loss/test.ts
dev-packages/node-integration-tests/suites/express/handle-error-tracesSampleRate-0/test.ts
dev-packages/node-integration-tests/suites/express/handle-error-tracesSampleRate-unset/test.ts
dev-packages/node-integration-tests/suites/express/sentry-trace/baggage-header-assign/test.ts
dev-packages/node-integration-tests/suites/express/sentry-trace/baggage-other-vendors-with-sentry-entries/test.ts
dev-packages/node-integration-tests/suites/express/sentry-trace/baggage-other-vendors/test.ts
dev-packages/node-integration-tests/suites/express/sentry-trace/trace-header-assign/test.ts
dev-packages/node-integration-tests/suites/express/setupExpressErrorHandler/test.ts
dev-packages/node-integration-tests/suites/public-api/startSpan/with-nested-spans/test.ts
dev-packages/node-integration-tests/suites/sessions/crashed-session-aggregate/test.ts
dev-packages/node-integration-tests/suites/sessions/errored-session-aggregate/test.ts
dev-packages/node-integration-tests/suites/sessions/exited-session-aggregate/test.ts
dev-packages/node-integration-tests/suites/sessions/server.ts
dev-packages/node-integration-tests/suites/tracing/connect/test.ts
dev-packages/node-integration-tests/suites/tracing/hapi/test.ts
dev-packages/node-integration-tests/suites/tracing/meta-tags/test.ts
dev-packages/node-integration-tests/utils/assertions.ts
dev-packages/node-integration-tests/utils/defaults/server.ts
dev-packages/node-integration-tests/utils/index.ts
dev-packages/node-integration-tests/utils/runner.ts

Noticed while debugging some test problems, that if axios throws an error (e.g. you get a 500 error), jest cannot serialize the error because it contains recursive data, leading to super hard to debug error messages.
This makes our node integration test runner more resilient by normalizing errors we get there to ensure circular references are resolved.
While working on this, I found some further, actually more serious problems - some tests were simply not running at all. Especially all the session aggregrate tests were simply not being run and just "passed" accidentally. 
The core problem there was that the path to the scenario was incorrect, so nothing was even started, plus some things where we seemed to catch errors and still pass (?? I do not think I fixed all of the issues there, but …

test: Make node integration test runner more resilient

---

packages/nextjs/package.json
yarn.lock

closes https://github.com/getsentry/sentry-javascript/issues/14249

deps(nextjs): Bump @rollup/plugin-commonjs

---

CHANGELOG.md

Small backport release to publish the module metadata integration to the CDN for lazy loading.

meta(changelog): Update changelog for v7.120.0

---

packages/remix/test/integration/test/server/utils/helpers.ts

Oops, https://github.com/getsentry/sentry-javascript/pull/14245 broke our remix integration tests.
Instead of re-exporting this from a path (which is not resolved nicely etc. and not reflected by our dependency graph) we can just inline the two methods we need here, they are not too complicated.

test(remix): Stop relying on node-integration-tests in remix

---

packages/vue/src/tracing.ts

Just a smal bundle size reduction PR for the Vue SDK: I discovered while working on #14251 that we can simplify the check here and just use the `onlyIfParent` flag instead of querying the active span. This should behave identically.

ref(vue): Reduce bundle size for starting application render span

---

.size-limit.js
dev-packages/browser-integration-tests/suites/public-api/startSpan/basic/test.ts
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/pageload-update-txn-name/init.js
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/pageload-update-txn-name/subject.js
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/pageload-update-txn-name/test.ts
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/pageload/test.ts
packages/core/src/tracing/sentrySpan.ts
packages/core/test/lib/tracing/sentrySpan.test.ts
packages/nextjs/src/client/routing/appRouterRoutingInstrumentation.ts
packages/solid/src/solidrouter.ts

This PR fixes a "regression" introduced in v8 where we no longer updated the source of the span when calling `span.updateName`. We had this behaviour in our v7 `Transaction` class (IIRC via `transaction.setName(name, source)` but most likely forgot to port it to the `Span` class as the `event.transaction_info.source` field is only relevant for transactions (i.e. root spans in today's SDK lingo).
The PR also adds and improves some unit and browser integration tests so that we check against the default source as well as that updating the name updates the source. 
Important: While this is a fix in the core package it has **no effect** on spans created in the Node SDK, since these are created from OpenTelemetry. I'll open a second PR for Node, as the changes there are more involved. This fix …

fix(core): Set `sentry.source` attribute to `custom` when calling `span.updateName` on `SentrySpan`

---

docs/migration/draft-v8-migration-guide.md
docs/migration/draft-v9-migration-guide.md
packages/core/src/integrations/requestdata.ts
packages/remix/src/utils/errors.ts
packages/remix/src/utils/instrumentServer.ts
packages/utils/src/requestdata.ts
packages/utils/test/requestdata.test.ts

This is not really necessary anymore - it only sets this on transaction events, and those get the `transaction` in different places already anyhow.
With this, we can also actually remove some other stuff. One method is exported from utils but not otherwise used, we can also drop this in v9.
Finally, this was also the only place that used `route` on the request, so we can also get rid of this in `remix`, which is weird anyhow because we set it for errors there but don't even use it for them.

ref(utils): Stop setting `transaction` in `requestDataIntegration`

---

packages/nestjs/README.md

Ref https://github.com/getsentry/sentry-javascript/issues/14242
The NestJS SDK is stable enough for us to remove this label. All the breaking changes we do to the SDK are gonna end up in v9.

meta: Remove `beta` label from NestJS SDK readme

---

packages/nestjs/src/setup.ts

Ref: https://github.com/getsentry/sentry-javascript/issues/14292
Goal is to make the `SentryGlobalFilter` handle all cases, removing the need for `SentryGlobalGraphQLFilter` and `SentryGlobalGenericFilter`.

feat(nestjs): Handle GraphQL contexts in `SentryGlobalFilter`

---

dev-packages/browser-integration-tests/suites/public-api/captureException/errorEvent/subject.js
dev-packages/browser-integration-tests/suites/public-api/captureException/errorEvent/test.ts
dev-packages/browser-integration-tests/suites/public-api/instrumentation/xhr/onreadystatechange/subject.js
dev-packages/browser-integration-tests/suites/public-api/instrumentation/xhr/onreadystatechange/test.ts
dev-packages/browser-integration-tests/suites/replay/captureReplay/test.ts
dev-packages/browser-integration-tests/suites/replay/captureReplayFromReplayPackage/test.ts
dev-packages/browser-integration-tests/suites/replay/multiple-pages/test.ts
dev-packages/browser-integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-0-snap-full
dev-packages/browser-integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-0-snap-full-chromium
dev-packages/browser-integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-2-snap-full
dev-packages/browser-integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-2-snap-full-chromium
dev-packages/browser-integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-4-snap-full
dev-packages/browser-integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-4-snap-full-chromium
dev-packages/browser-integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-8-snap-full
dev-packages/browser-integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-8-snap-full-chromium
dev-packages/browser-integration-tests/suites/stacktraces/protocol_containing_fn_identifiers/test.ts
dev-packages/browser-integration-tests/suites/stacktraces/protocol_fn_identifiers/test.ts
dev-packages/browser-integration-tests/suites/stacktraces/regular_fn_identifiers/test.ts
dev-packages/browser-integration-tests/suites/tracing/dsc-txn-name-update/test.ts
dev-packages/browser-integration-tests/suites/tracing/metrics/pageload-resource-spans/test.ts
dev-packages/browser-integration-tests/utils/replayEventTemplates.ts

Extracted these out of https://github.com/getsentry/sentry-javascript/pull/11904 - these are all the tests that required changing any (test) code for them to pass with `getLocalTestUrl` vs `getLocalTestPath`.

test(browser): Update tests that need changes for `getLocalTestUrl`

---

docs/migration/draft-v9-migration-guide.md
packages/browser/src/exports.ts
packages/bun/src/index.ts
packages/cloudflare/src/index.ts
packages/deno/src/index.ts
packages/node/src/index.ts
packages/node/src/integrations/http/SentryHttpInstrumentation.ts
packages/types/src/event.ts
packages/types/src/index.ts
packages/types/src/request.ts
packages/utils/src/requestdata.ts
packages/vercel-edge/src/index.ts

The type `Request` is very misleading and overloaded, so let's rename it to something clearer.
I opted with `RequestEventData`, but happy to hear other ideas as well.
Closes https://github.com/getsentry/sentry-javascript/issues/14300

ref(types): Deprecate `Request` type in favor of `RequestEventData`

---

packages/nestjs/src/sdk.ts

Ref: https://github.com/getsentry/sentry-javascript/issues/14292
The `SentryService` is a bit redundant nowadays. This PR duplicates its logic - which is idempotent, therefore not dangerous to be duplicated - into the Sentry.init() call of the nestjs sdk.

feat(nestjs): Duplicate `SentryService` behaviour into `@sentry/nestjs` SDK `init()`

---

dev-packages/size-limit-gh-action/index.mjs
dev-packages/size-limit-gh-action/package.json
yarn.lock

v1 of this is deprecated, which you can see in each CI run on develop as of now. Updating this should fix the deprecation.
This _should_ not break stuff for us: https://www.npmjs.com/package/@actions/artifact#v2---whats-new

ci: Bump `@actions/artifact` from 1x to 2.x

---

packages/utils/src/index.ts
yarn.lock

Resolves https://github.com/getsentry/sentry-javascript/issues/14211

ref(utils): Explicitly export API in `@sentry/utils`

---

dev-packages/rollup-utils/plugins/bundlePlugins.mjs

Creating a corresponding PR to v7 for this fix: https://github.com/getsentry/sentry-javascript/pull/14344
This should solve https://github.com/getsentry/sentry-javascript/issues/14343 in v7.

fix(v7/cdn): Ensure `_sentryModuleMetadata` is not mangled

---

packages/utils/rollup.npm.config.mjs

Using the import assertion broke the release pipeline because we use older node versions for profiling.

meta(utils): Don't use import assertion in rollup config

---

dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/server-components.test.ts
packages/astro/src/server/middleware.ts
packages/astro/test/server/middleware.test.ts
packages/bun/src/integrations/bunserver.ts
packages/cloudflare/src/scope-utils.ts
packages/cloudflare/test/request.test.ts
packages/nextjs/src/common/captureRequestError.ts
packages/nextjs/src/common/withServerActionInstrumentation.ts
packages/nextjs/src/common/wrapGenerationFunctionWithSentry.ts
packages/nextjs/src/common/wrapMiddlewareWithSentry.ts
packages/nextjs/src/common/wrapRouteHandlerWithSentry.ts
packages/nextjs/src/common/wrapServerComponentWithSentry.ts
packages/nextjs/src/edge/wrapApiHandlerWithSentry.ts
packages/node/src/integrations/http/SentryHttpInstrumentation.ts
packages/sveltekit/src/server/handle.ts
packages/utils/src/index.ts
packages/utils/src/requestdata.ts

The request data integration prefers this over `request`, we want to get rid of `request` in v9.
Updates the following:
Part of https://github.com/getsentry/sentry-javascript/issues/14298

ref: Set `normalizedRequest` instead of `request` in various places

---

docs/migration/draft-v9-migration-guide.md
packages/nestjs/src/setup.ts

Resolves https://github.com/getsentry/sentry-javascript/issues/14292

feat(nestjs): Deprecate `SentryTracingInterceptor`, `SentryService`, `SentryGlobalGenericFilter`, `SentryGlobalGraphQLFilter`

---

dev-packages/node-integration-tests/suites/tracing/nestjs-errors-no-express/scenario.ts
dev-packages/node-integration-tests/suites/tracing/nestjs-errors/scenario.ts
dev-packages/node-integration-tests/suites/tracing/nestjs-no-express/scenario.ts
dev-packages/node-integration-tests/suites/tracing/nestjs/scenario.ts
docs/migration/draft-v9-migration-guide.md
packages/astro/src/index.server.ts
packages/aws-serverless/src/index.ts
packages/bun/src/index.ts
packages/google-cloud-serverless/src/index.ts
packages/nestjs/src/index.ts
packages/node/src/index.ts
packages/node/src/integrations/tracing/index.ts
packages/node/src/integrations/tracing/nest/nest.ts
packages/remix/src/index.server.ts
packages/solidstart/src/server/index.ts
packages/sveltekit/src/server/index.ts

Resolves https://github.com/getsentry/sentry-javascript/issues/14242

feat(node): Deprecate `nestIntegration` and `setupNestErrorHandler` in favor of using `@sentry/nestjs`

---

packages/replay-internal/package.json

When running tests for the monorepo locally, replay tests can hang/may not resolve because we run them in watch mode by default. You can still use `yarn test:watch` if you want watch mode anyhow. We use `vitest run` everywhere else we have vitest already.

chore(replay): Use `vitest run` for replay test run

---

packages/core/src/utils-hoist/object.ts
packages/core/test/utils-hoist/object.test.ts

This PR adds a guard to avoid us throwing if we try to fill a readonly property on an object.
Generally speaking this should not work, but it does not hurt us to be defensive here and try-catch this to avoid breaking users apps.
Fixes https://github.com/getsentry/sentry-javascript/issues/14368

fix(core): Do not throw when trying to fill readonly properties

---

dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals-lcp/template.html
dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals-lcp/test.ts
dev-packages/e2e-tests/test-applications/react-create-hash-router/tests/transactions.test.ts
packages/browser-utils/src/metrics/browserMetrics.ts

This PR adds `loadTime` and `renderTime` attributes from the [LCP performance entry](https://developer.mozilla.org/en-US/docs/Web/API/LargestContentfulPaint#instance_properties) to the `pageload` span. Besides being valuable information for users, this also helps us detect if LCP is potentially unreliable:
* if the LCP element was from a 3rd party origin and the `Timing-Allow-Origin` header was not sent in the resource response, the `renderTime` will be `0`.
Background information: The `web-vitals` library takes the `startTime` attribute of the LCP entry as the LCP value. `startTime` is set to:
* `renderTime` if `renderTime > 0`
* `loadTime` otherwise

feat(browser): Send additional LCP timing info

---

packages/feedback/src/modal/components/Dialog.css.ts
packages/feedback/src/modal/components/DialogHeader.tsx

Fixes an issue with long form titles causing the width of the dialog to expand. Instead, apply the css var `--form-width` to the dialog contents so that the title wraps.
After:
Single line:
Closes #14351

fix(feedback): Fix non-wrapping form title

---

.github/workflows/build.yml

Optional tests should not block releases.
There are two groups of optional tests:
1. Canary type tests
2. Tests that send data to sentry
IMHO both of these can be skipped on release branches, as failure in either of them should not affect the release. They will (for now) still run on develop, we can revisit this if we want.

ci: Skip optional E2E tests on release branches

---

docs/migration/draft-v9-migration-guide.md
packages/core/src/api.ts
packages/core/src/utils-hoist/index.ts
packages/core/src/utils-hoist/object.ts
packages/core/test/lib/api.test.ts
packages/core/test/utils-hoist/object.test.ts
packages/utils/src/index.ts

Ref https://github.com/getsentry/sentry-javascript/issues/14267
Deprecates and removes internal usages of `urlEncode`.

feat(core): Deprecate `urlEncode`

---

.github/workflows/canary.yml
dev-packages/e2e-tests/package.json

Oops, we forgot this when moving the stuff from utils to core. The canary test workflow only kept the utils build in cache, which lead to this failing - now, we just keep all build output in cache, to be on the safe side...
see: https://github.com/getsentry/sentry-javascript/actions/runs/11971041974

ci: Fix canary test workflow

---

dev-packages/e2e-tests/test-applications/nextjs-app-dir/app/very-slow-component/page.tsx
dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/transactions.test.ts

This PR hopefully un-flakes this test by marking it as slow and adapting the timeout values.

test(nextjs): Adapt slow test

---

packages/nuxt/src/vite/sourceMaps.ts

As Nuxt generates and keeps server source maps per default, only the source maps in the public folder are deleted after uploading them to Sentry.

feat(nuxt): Only delete public source maps

---

packages/nuxt/src/server/sdk.ts
packages/nuxt/test/server/sdk.test.ts

Dev tools sometimes try to access source maps. This filter makes sure this error is not reported in Sentry as it adds noise to the data.

feat(nuxt): Add filter for not found source maps (devtools)

---

dev-packages/browser-integration-tests/suites/public-api/startSpan/parallel-root-spans-in-scope/subject.js
dev-packages/browser-integration-tests/suites/public-api/startSpan/parallel-root-spans-in-scope/test.ts
dev-packages/browser-integration-tests/suites/public-api/startSpan/parallel-root-spans-with-parentSpanId/subject.js
dev-packages/browser-integration-tests/suites/public-api/startSpan/parallel-root-spans-with-parentSpanId/test.ts
dev-packages/browser-integration-tests/suites/public-api/startSpan/parallel-root-spans/subject.js
dev-packages/browser-integration-tests/suites/public-api/startSpan/parallel-root-spans/test.ts
dev-packages/browser-integration-tests/utils/helpers.ts
dev-packages/node-integration-tests/suites/public-api/startSpan/parallel-root-spans/scenario.ts
dev-packages/node-integration-tests/suites/public-api/startSpan/parallel-root-spans/test.ts
dev-packages/node-integration-tests/suites/public-api/startSpan/parallel-spans-in-scope-with-parentSpanId/scenario.ts
dev-packages/node-integration-tests/suites/public-api/startSpan/parallel-spans-in-scope-with-parentSpanId/test.ts
dev-packages/node-integration-tests/suites/public-api/startSpan/parallel-spans-in-scope/scenario.ts
dev-packages/node-integration-tests/suites/public-api/startSpan/parallel-spans-in-scope/test.ts
packages/opentelemetry/src/trace.ts

This adds node & browser integration tests to demonstrate the current behavior of "trace propagation" based on the current scope.
It shows that the behavior is not really consistent and we should probably adjust it, but for now this PR does no changes.
In browser, the propagation context of the current scope is always picked up. This means that if you call `startSpan` multiple times in the root, both started spans will have the same trace ID, and possibly the same `parentSpanId` if there was an incoming trace.
In node, the propagation context is ignored for the root context. So in the root, started spans will have different traces, and will also ignore parentSpanId (which is only theoretical, there will never really be a parentSpanId on the root scope in node, realistically). 
Outside of …

test: Add tests to demonstrate root trace ID behavior

---

packages/nextjs/src/client/index.ts

Fixes #14436
Reduces error spam by not reporting `NEXT_NOT_FOUND` error which get thrown when use the `redirect()` functions.
From ServerComponents were addressed in #7642 and ServerAction in #10474, but this PR addresses what is reported from the Client (Browser).
- https://github.com/vercel/next.js/blob/2161d8c012dcd98eb8690814bd275d56c45bf00a/packages/next/src/client/components/router-reducer/reducers/server-action-reducer.ts#L384-L397
- https://github.com/vercel/next.js/blob/2161d8c012dcd98eb8690814bd275d56c45bf00a/packages/next/src/client/components/redirect.ts#L10-L18

fix(nextjs): Don't report `NEXT_REDIRECT` from browser

---

docs/migration/draft-v9-migration-guide.md
packages/browser/src/tracing/request.ts
packages/core/src/fetch.ts
packages/core/src/utils-hoist/baggage.ts
packages/core/src/utils-hoist/cache.ts
packages/core/src/utils-hoist/index.ts
packages/core/src/utils-hoist/memo.ts
packages/core/src/utils-hoist/normalize.ts
packages/utils/src/index.ts

Ref https://github.com/getsentry/sentry-javascript/issues/14267
Deprecates a few unused/unnecessary exports from the utils package.

feat(utils): Deprecate `memoBuilder`, `BAGGAGE_HEADER_NAME`, and `makeFifoCache`

---

dev-packages/e2e-tests/test-applications/nextjs-15/app/redirect/destination/page.tsx
dev-packages/e2e-tests/test-applications/nextjs-15/app/redirect/origin/page.tsx
dev-packages/e2e-tests/test-applications/nextjs-15/tests/server-action-redirect.test.ts

tests https://github.com/getsentry/sentry-javascript/pull/14440

test(nextjs): Add test for redirects from server actions

---

packages/core/src/utils-hoist/array.ts
packages/core/src/utils-hoist/index.ts
packages/core/test/utils-hoist/array.test.ts
packages/node/src/utils/redisCache.ts
packages/nuxt/src/vite/utils.ts
packages/utils/src/index.ts

Ref: https://github.com/getsentry/sentry-javascript/issues/14267
From my investigation, redis does not actually support arrays/nested arrays for keys and ioredis is wrapping thinly over redis functions, but otel has `any[]` as one of their possible values for command line arguments so I opted for inlining the implementation and adding a note to use `Array.flat` in v9.

feat(core): Deprecate `flatten`

---

packages/browser-utils/.eslintrc.js
packages/browser-utils/src/metrics/cls.ts
packages/browser-utils/src/metrics/inp.ts
packages/browser-utils/src/metrics/web-vitals/getINP.ts
packages/browser-utils/test/utils/TestClient.ts

We apparently disabled the no-optional-chaining rule in browser-utils, which lead to us including this polyfill. Properly enforcing this rule should (hopefully?) reduce bundle size a bit.

ref(browser): Avoid optional chaining

---

.size-limit.js
docs/migration/draft-v9-migration-guide.md
packages/core/src/baseclient.ts
packages/core/src/utils/prepareEvent.ts
packages/core/test/lib/baseclient.test.ts
packages/core/test/lib/prepareEvent.test.ts
packages/core/test/lib/tracing/sentrySpan.test.ts

This PR updates & streamlines our handling of certain `undefined` options:
First, we do not want to differentiate anymore between options being unset and set to `undefined` - the resulting behavior should be the same. This especially applies to the tracing options `tracesSampleRate`, `tracesSampler` and `enableTracing` - if any of those is set to `undefined`, `hasEnabledTracing()` will be true and certain things will happen.
In v9, we want to change this so that `undefined` will also result in `hasEnabledTracing() === false`. We'll warn if we encounter such a scenario.
Another related thing this PR does is streamline how we handle falsy values for `environment`, `release` and `dist` on an event. Today, we go out of our way to check if the properties are set and only update them …

feat(core): Update & deprecate `undefined` option handling

---

packages/browser-utils/src/metrics/browserMetrics.ts
packages/browser/src/integrations/httpclient.ts
packages/browser/src/tracing/browserTracingIntegration.ts
packages/core/src/tracing/measurement.ts

Streamline some debug logs, esp. also removing some debug logs around browser metrics, in favor of just having a generic log when we add measurements.

ref: Remove & streamline some debug logs

---

docs/migration/draft-v9-migration-guide.md

Backfills items to the draft migration guide for v9 that we missed
- https://github.com/getsentry/sentry-javascript/pull/14433
- https://github.com/getsentry/sentry-javascript/pull/14454

meta: Backfill v9 migration guide items

---

dev-packages/e2e-tests/test-applications/nuxt-3/package.json

Noticed that our e2e tests are not actually using nitro 2.10 despite being on the latest nuxt version: https://github.com/getsentry/sentry-javascript/actions/runs/12028119465/job/33531969920#step:13:196
This fixes it.

chore(nuxt): Remove nft override to ensure we are testing with latest nitro

---

.github/dependency-review-config.yml

Updates dependency review allow list for a vulnerable version that we need to test in an e2e test.

chore: Add GHSA entry for nuxt e2e test

---

dev-packages/e2e-tests/test-applications/nuxt-3-min/package.json
packages/nuxt/package.json
packages/nuxt/src/module.ts

This PR adds a minimum required version for the Nuxt SDK. Version 3.7.0 was selected because this version adds the possibility to set client source maps to `'hidden'` ([PR here](https://github.com/nuxt/nuxt/pull/22787)).
However, as the SDK relies on other versions as well (see below, at the bottom), those packages need to be manually bumped (in case the lock-file is not updated yet). **Nuxt 3.7.0** at least supports the correct version range:
["nitropack": "^2.6.1"](https://github.com/nuxt/nuxt/blob/v3.7.0/packages/nuxt/package.json#L84)
["ofetch": "^1.3.3"](https://github.com/nuxt/nuxt/blob/v3.7.0/packages/nuxt/package.json#L87)
Above **Nuxt v3.14.0**, everything works out of the box, as the versions are already updated:
["nitropack": …

meta(nuxt): Require minimum Nuxt v3.7.0

---

packages/node/src/sdk/client.ts
packages/node/src/types.ts
packages/node/test/sdk/client.test.ts

Ref: https://github.com/getsentry/sentry-javascript/issues/14483
This adds an option `openTelemetryInstrumentations` to the node init and Node client that can be used in the future to migrate away from `addOpenTelemetryInstrumentation` which is a bit foot-gunny timing wise with ESM instrumentation hooks.

feat(node): Add `openTelemetryInstrumentations` option

---

packages/core/src/utils/traceData.ts
packages/core/test/lib/utils/traceData.test.ts

This PR drops the validation for baggage content. We didn't do this for browser previously, only for node, but it adds bundle size and does not appear too important.
I left the trace header validation in for now, we may also drop this but it is smaller and I guess also more important to us...?

ref(core): Do not check baggage validity

---

dev-packages/e2e-tests/test-applications/astro-4/tests/errors.server.test.ts
package.json
packages/astro/src/server/middleware.ts
packages/opentelemetry/src/utils/generateSpanContextForPropagationContext.ts
packages/opentelemetry/test/trace.test.ts

Noticed this while working on https://github.com/getsentry/sentry-javascript/pull/14481.
This PR fixes a bug in our opentelemetry code that lead to invalid empty span IDs being generated in certain cases. 
Instead, we now generate valid (but random) span IDs in this case.
Additionally, I also noticed that the way we try-catched the astro server request code lead to the http.server span not being attached to servers correctly - we had a try-catch block _outside_ of the `startSpan` call, where we sent caught errors to sentry. but any error caught this way would not have an active span (because by the time the `catch` part triggers, `startSpan` is over), and thus the http.server span would not be attached to the error. By moving this try-catch inside of the `startSpan` call, we can correctly …

fix(astro): Fix astro trace propagation issues

---

docs/migration/draft-v9-migration-guide.md
packages/core/src/utils-hoist/index.ts
packages/core/src/utils-hoist/time.ts
packages/utils/src/index.ts

This export is completely internal and should not be exposed.

feat(core/utils): Deprecate `_browserPerformanceTimeOriginMode`

---

docs/migration/draft-v9-migration-guide.md
packages/remix/src/index.server.ts
packages/remix/src/utils/instrumentServer.ts
packages/remix/src/utils/remixOptions.ts

Resolves https://github.com/getsentry/sentry-javascript/issues/14507
`autoInstrumentRemix` will be removed in v9 in favor of a coherent unified instrumentation experience OOTB.

feat(remix): Deprecate `autoInstrumentRemix: false`

---

docs/migration/draft-v9-migration-guide.md
packages/node/src/integrations/node-fetch.ts
packages/opentelemetry/src/index.ts
packages/opentelemetry/src/propagator.ts
packages/opentelemetry/src/utils/generateSpanContextForPropagationContext.ts

Instead, use the new and improved `getTraceData` directly, which avoids URL issues etc. and just gets the trace data.
This also deprecates `generateSpanContextForPropagationContext` and inlines it to the one place we still use this for, I'll probably adapt this in a follow up PR.

ref(node): Avoid using propagator for node-fetch TWP instrumentation

---

packages/nuxt/src/server/sdk.ts
packages/nuxt/test/server/sdk.test.ts

This PR refactors the low quality transaction filter in the Nuxt SDK to filter out all resource requests. Unless I'm missing something, our SDKs should generally not send dedicated transactions for resource requests as they would deplete transaction quota fairly quickly, compared to only tracking page requests. 
The heuristic I chose is pretty simple. Using `path.extname` we get a falsy value if the transaction name does not end in a file extension. Which should be enough but it's almost too good to be true 🤔 
Let's see what our e2e tests have to say... welp turns out they're happy 😅

fix(nuxt): Avoid sending resource request transactions
