getsentry/sentry-javascript

dev-packages/browser-integration-tests/suites/public-api/instrumentation/eventListener/event-target/subject.js, dev-packages/browser-integration-tests/suites/public-api/instrumentation/eventListener/event-target/test.ts, packages/browser/src/helpers.ts, packages/browser/src/integrations/browserapierrors.ts, packages/browser/test/helpers.test.ts, packages/core/src/utils-hoist/object.ts, packages/types/src/wrappedfunction.ts
We use a heavy dose of `any`, that I would like to reduce.
So I started out to look into `wrap()`, which made heave use of this, and tried to rewrite it to avoid `any` as much as possible. This required some changes around it, but should now have much better type inferrence etc. than before, and be more "realistic" in what it tells you.
While at this, I also removed the `before` argument that we were not using anymore - `wrap` is not exported anymore, so this is purely internal.
=> ref(types): Avoid some `any` type casting around `wrap` code

packages/opentelemetry/src/sampler.ts, packages/opentelemetry/test/trace.test.ts
We do not align with how OTEL traces and the default samplers handle invalid span contexts today.
If a span context is invalid, e.g. the span ID or trace ID are invalid, then the span is ignored for new spans as a parent, and the new span will start a new trace. This change aligns our own sampling strategy with this, to ensure that invalid parent span contexts are ignored.
=> fix(opentelemetry): Ignore invalid parent spans

dev-packages/e2e-tests/test-applications/ember-classic/package.json, dev-packages/e2e-tests/test-applications/ember-embroider/package.json
This is failing due to some dependency shenanigans, so skipping this for now until we can figure this out.
=> test(ember): Skip ember-embroider E2E test for now

packages/astro/src/integration/index.ts, packages/nextjs/src/config/types.ts, packages/nextjs/src/config/webpack.ts, packages/solidstart/src/vite/sourceMaps.ts
Resolves https://github.com/getsentry/sentry-javascript/issues/14286
The goal for the future is to a) not stomp user settings if they explicitly disable source maps b) warn users that they should delete their sourcemaps before uploading c) warn users that the SDK will delete by default in the future.
=> feat: Warn about source-map generation

packages/feedback/src/modal/components/Dialog.css.ts
closes https://github.com/getsentry/sentry-javascript/issues/14517
related to https://github.com/getsentry/sentry-javascript/pull/14355
Updated version:
=> fix(feeback): Handle css correctly in screenshot mode

dev-packages/browser-integration-tests/suites/integrations/featureFlags/openfeature/basic/test.ts, dev-packages/browser-integration-tests/suites/integrations/featureFlags/openfeature/errorHook/init.js, dev-packages/browser-integration-tests/suites/integrations/featureFlags/openfeature/errorHook/test.ts, dev-packages/browser-integration-tests/suites/integrations/featureFlags/openfeature/init.js, dev-packages/browser-integration-tests/suites/integrations/featureFlags/openfeature/subject.js, dev-packages/browser-integration-tests/suites/integrations/featureFlags/openfeature/template.html, dev-packages/browser-integration-tests/suites/integrations/featureFlags/openfeature/withScope/test.ts, packages/browser/src/index.ts, packages/browser/src/integrations/featureFlags/launchdarkly/integration.ts, packages/browser/src/integrations/featureFlags/openfeature/index.ts, packages/browser/src/integrations/featureFlags/openfeature/integration.ts, packages/browser/src/integrations/featureFlags/openfeature/types.ts, packages/browser/src/utils/featureFlags.ts, packages/browser/test/utils/featureFlags.test.ts
Moves core logic into re-usable functions so that we can re-use for other integrations.
Depends on https://github.com/getsentry/sentry-javascript/pull/14207
=> ref(flags): Refactor LaunchDarkly integration to reusable functions 

.github/workflows/build.yml, packages/profiling-node/package.json, packages/profiling-node/src/cpu_profiler.ts, yarn.lock
Timeout was being set after dependencies were installed and typescript pkg is not necessary (probably left from migration from the repo)
=> ci(profiling): Fix yarn timeout for Windows

packages/react/src/tanstackrouter.ts, packages/react/src/vendor/tanstackrouter-types.ts
The current sentry implementation was breaking in my application because we use [custom search param serialization](https://tanstack.com/router/latest/docs/framework/react/guide/custom-search-param-serialization).
The default tanstack implementation uses `this.options.parseSearch` to parse the search string into a parsed location
https://github.com/TanStack/router/blob/55891518fcfa7c308e1db4149d357cf38700c882/packages/react-router/src/router.ts#L1015-L1016
The `matchRoutes` signature that sentry was using has been deprecated.
https://github.com/TanStack/router/blob/55891518fcfa7c308e1db4149d357cf38700c882/packages/react-router/src/router.ts#L1063-L1098
The signature only exists to support sentry as far as I can tell
https://github.com/TanStack/router/issues/2164 …
=> fix(react): Match routes with `parseSearch` option in TanStack Router instrumentation

packages/node/src/integrations/http/index.ts
Ref: https://github.com/getsentry/sentry-javascript/issues/14550
This is the option we can migrate to as part of removing `autoSessionTracking.`
=> feat(node): Add `trackIncomingRequestsAsSessions` option to http integration

.github/workflows/build.yml
These runners were deprecated and are causing the release jobs to fail. They have been upgraded in v8, but the change was not backported to v7
=> ci(v7/profiling) upgrade deprecated runners

packages/core/src/utils-hoist/instrument/globalError.ts, packages/core/src/utils-hoist/instrument/globalUnhandledRejection.ts, packages/core/src/utils-hoist/worldwide.ts
This adds a comment explaining why we are using `window.onerror` instead of `window.addEventListener('error')`, for future reference.
It also removes the check for `__SENTRY_LOADER__` check, which we removed quite some time ago in the Loader.
=> ref(core): Streamline global handlers & add comments

dev-packages/node-integration-tests/suites/contextLines/instrument.mjs, dev-packages/node-integration-tests/suites/contextLines/scenario with space.cjs, dev-packages/node-integration-tests/suites/contextLines/scenario with space.mjs, dev-packages/node-integration-tests/suites/contextLines/test.ts, packages/core/src/utils-hoist/node-stack-trace.ts, packages/core/test/utils-hoist/stacktrace.test.ts, packages/node/src/utils/module.ts, packages/node/test/utils/module.test.ts
While working on https://github.com/getsentry/sentry-javascript/issues/14525, I noticed that for some reason, I wasn't getting any context lines for the source JS file but instead a bunch of debug messages about the SDK not being able to read the file. The file path happened to contain spaces which were URL-encoded (`%20`). It turns out that in ESM, the Node stack trace filenames are URL-encoded. I checked and this and it only seems to be the case in ESM, not in CJS. 
Specifically, this PR:
- decodes the `filename` stack frame property
- decodes the `module` property (which is derived from the raw filename)
- adds a bunch of unit tests for the module name extraction logic (general tests as well as for encoded file names)
- adds unit and integration tests (ESM and CJS) for file names with …
=> fix(core): Decode `filename` and `module` stack frame properties in Node stack parser

packages/types/src/index.ts
Removes an export that was added to the deprecated types package in https://github.com/getsentry/sentry-javascript/pull/14207.
Should be fine since we never released that change.
=> meta(types): Remove Feature Flag APIs from deprecated package

packages/core/src/envelope.ts, packages/core/src/types-hoist/csp.ts, packages/core/src/types-hoist/envelope.ts, packages/core/src/types-hoist/index.ts, packages/core/src/utils-hoist/envelope.ts
Adds types for the `raw_security` envelope type. These are displayed in Sentry as CSP violations.
=> feat(core): Add `raw_security` envelope types

packages/angular/src/tracing.ts, packages/browser/src/integrations/globalhandlers.ts, packages/browser/src/sdk.ts, packages/core/src/api.ts, packages/core/src/baseclient.ts, packages/core/src/exports.ts, packages/core/src/fetch.ts, packages/core/src/integrations/functiontostring.ts, packages/core/src/metrics/aggregator.ts, packages/core/src/server-runtime-client.ts, packages/core/src/sessionflusher.ts, packages/core/src/utils-hoist/instrument/globalError.ts, packages/core/src/utils-hoist/instrument/globalUnhandledRejection.ts, packages/core/src/utils-hoist/logger.ts, packages/core/src/utils-hoist/misc.ts, packages/core/src/utils-hoist/object.ts, packages/core/src/utils-hoist/string.ts, packages/core/src/utils-hoist/vendor/supportsHistory.ts, packages/nestjs/src/decorators.ts, packages/node/src/integrations/onunhandledrejection.ts, packages/node/src/utils/errorhandling.ts, packages/replay-internal/src/util/throttle.ts, packages/solid/src/errorboundary.ts
Getting rid of some more `any` types.
=> ref: Refactor some more `any` types

dev-packages/e2e-tests/README.md
Updates readme based on this PR: https://github.com/getsentry/sentry-javascript/pull/14254
=> docs(ci): Add docs for automatic E2E test detection

docs/migration/draft-v9-migration-guide.md, packages/nextjs/src/config/types.ts, packages/nextjs/test/config/webpack/constructWebpackConfig.test.ts, packages/nextjs/test/types/next.config.ts
Ref https://github.com/getsentry/sentry-javascript/issues/13618#issuecomment-2520598510
Seems like I forgot to remove the typedefs for the `hideSourceMaps` option in v8. The option no longer does anything so we should deprecate it and remove it in v9.
I am not just removing it in this PR because I don't want to crash builds.
=> feat(nextjs): Deprecate typedef for `hideSourceMaps`

.github/workflows/build.yml, .github/workflows/enforce-license-compliance.yml
In order for us to have size-limit comparison etc, we need to ensure CI runs on v8 & v9 branches too.
=> ci(v9): Ensure CI runs on v8 & v9 branches

packages/nitro-utils/src/index.ts, packages/nitro-utils/src/nitro/patchEventHandler.ts, packages/nitro-utils/src/util/flush.ts
E2E tests and usage in nuxt in: https://github.com/getsentry/sentry-javascript/pull/14612
=> feat(nitro-utils): Add `patchEventHandler` helper for nitro

dev-packages/e2e-tests/test-applications/nextjs-t3/package.json
Types for react cache are incompatible so we pin it for now.
=> chore(e2e): Pin react types for nextjs-t3 app

packages/core/src/integrations/inboundfilters.ts, packages/core/test/lib/integrations/inboundfilters.test.ts
We have internal [user reports](https://sentry.slack.com/archives/CTZCE4WBZ/p1733360320054299) about an uncaught promise rejection being thrown by a .NET library called CEFSharp. This lib can embed chromium in a .NET app, which I guess means, a web page can be displayed within a .NET app. Apparently there's some problem that spams this error to some of our users.
This error seems to happen quite frequently and it's not the first time we're hearing about it:
- https://github.com/getsentry/sentry-javascript/issues/3440#issuecomment-864140452
- https://github.com/getsentry/sentry-javascript/issues/3796
- Stackoverflow: https://stackoverflow.com/questions/75536442/troubleshooting-non-error-promise-rejection-captured-with-value-object-not-fou
- Issue in  DDog browser SDK repo: …
=> fix(core): Filter out unactionable CEFSharp promise rejection error by default

packages/node/src/sdk/initOtel.ts, packages/node/test/sdk/initOtel.test.ts
Today, if you pass e.g. `Infinity` or another large number to `maxSpanWaitDuration`, the SDK will error out because we try to do `new Array(maxSpanWaitDuration)`, which is impossible.
Ideally, we can properly allow an infinite wait time, but for now this adds checks to ensure only valid values are passed in there, and we do not explode.
See https://github.com/getsentry/sentry-javascript/pull/14154#issuecomment-2527984250
=> fix(node): Guard against invalid `maxSpanWaitDuration` values

docs/migration/draft-v9-migration-guide.md, packages/vue/src/constants.ts
Resolves https://github.com/getsentry/sentry-javascript/issues/12851
=> feat(vue/nuxt)!: No longer create `"update"` spans for component tracking by default

dev-packages/e2e-tests/test-applications/nextjs-t3/package.json, dev-packages/e2e-tests/test-applications/nextjs-t3/src/trpc/server.ts, packages/nextjs/src/common/captureRequestError.ts, packages/nextjs/src/common/index.ts, packages/nextjs/src/index.types.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/14302
=> feat(nextjs)!: Remove `experimental_captureRequestError`

packages/google-cloud-serverless/package.json
The link to the homepage results in a 404.
=> fix(google-cloud-serverless): Update homepage link in package.json

.github/workflows/auto-release.yml, .github/workflows/release.yml
The `getsentry-release` is a GitHub bot account that is used in various automation, and the `${{ secrets.GH_RELEASE_PAT }}` is a personal access token from that bot account. We are using a regular GitHub account as a bot while it should be a non-human account since there are no humans behind it. Hence, we are replacing it with a GitHub App. 
Functionality wise, there will be no difference.
More details: https://www.notion.so/sentry/DACI-Replace-GitHub-bot-accounts-with-GitHub-Apps-getsentry-release-15109965d1204a91b9be71c49e8b66e0?pvs=4
#skip-changelog
=> feat(release): Replace release bot with GH app

packages/browser-utils/src/metrics/browserMetrics.ts, packages/browser-utils/test/browser/browserMetrics.test.ts
Get rid of some type casts around browser timing events/metrics capture.
=> ref(browser): Refactor type casts of browser metrics

dev-packages/e2e-tests/test-applications/nestjs-8/tests/transactions.test.ts, dev-packages/e2e-tests/test-applications/node-express/tests/transactions.test.ts, packages/core/test/lib/tracing/sentrySpan.test.ts, packages/opentelemetry/src/spanExporter.ts, packages/opentelemetry/test/spanExporter.test.ts
This implements the `response` context for http.server spans (https://develop.sentry.dev/sdk/data-model/event-payloads/contexts/#response-context).
I opted to not implement this for the browser, as we do not really expect server spans there. I added a test there anyhow to show the shape of the transaction event, so we can adjust this easier if we want in the future.
Closes https://github.com/getsentry/sentry-javascript/issues/14619
Closes https://github.com/getsentry/sentry-javascript/pull/14634
=> feat(opentelemetry): Set `response` context for http.server spans

docs/migration/draft-v9-migration-guide.md, packages/angular/src/sdk.ts, packages/browser/src/sdk.ts, packages/core/src/server-runtime-client.ts, packages/core/src/types-hoist/options.ts, packages/node/src/integrations/http/SentryHttpInstrumentation.ts, packages/node/src/integrations/http/index.ts, packages/node/src/integrations/tracing/express.ts, packages/node/src/sdk/index.ts, packages/vercel-edge/src/sdk.ts
Ref https://github.com/getsentry/sentry-javascript/issues/14550
Deprecates `autoSessionTracking`. Instead, the `browserSessionIntegration` and `httpIntegration({ trackIncomingRequestsAsSessions: ... })` should be used.
=> feat: Deprecate `autoSessionTracking`

packages/tracing-internal/src/node/integrations/express.ts, packages/tracing-internal/test/node/express.test.ts
This PR fix use case when lrp keys offset is calculate to 0. I discover this case after update express from v4.19.2 to v4.21.2 
For example:
api/v1/users/1/posts
Old behavior
sentry build req._reconstructedRoute as:
api/v1/users/1/posts
New behavior
sentry build req._reconstructedRoute as:
api/v1/users/:param/posts
=> fix(v7/tracing-internal): Fix case when lrp keys offset is 0

.craft.yml
Unfortunately, having the v8 layer already in `.craft.yml` ends up with this layer being the default selection in the docs.
We should add this to the `v8` branch once it exists instead.
=> fix(aws-serverless): Remove v8 layer as it overwrites the current layer for docs

dev-packages/e2e-tests/test-applications/node-exports-test-app/scripts/consistentExports.ts, packages/astro/src/index.server.ts, packages/aws-serverless/src/index.ts, packages/google-cloud-serverless/src/index.ts, packages/node/src/index.ts, packages/node/src/integrations/childProcess.ts
Resolves https://github.com/getsentry/sentry-javascript/issues/14277
=> feat(node)!: Remove `processThreadBreadcrumbIntegration`

dev-packages/browser-integration-tests/suites/integrations/captureConsole/test.ts, packages/core/src/integrations/captureconsole.ts, packages/core/test/lib/integrations/captureconsole.test.ts
This PR adds a `handled` option to the `captureConsoleIntegration`. Right now, for v8, it will default to `false` as previously but it gives users the option to override the handled value. In v9, we will flip the default value to `true` after discussing this offline with the team. In this integration we can never be sure about the `handled` state at all. But flipping it to handled by default seems reasonable. 
closes #14659 
I will add an integration test once #14668 is merged and we can properly assert on exceptions from captureConsole. Might do it as a follow-up, depending on what gets reviewed and merged first.
=> feat(core): Add `handled` option to `captureConsoleIntegration`

packages/nitro-utils/package.json, packages/nuxt/build.config.ts, packages/nuxt/generate-build-stubs.bash, packages/nuxt/package.json, packages/nuxt/rollup.npm.config.mjs, packages/nuxt/src/runtime/plugins/sentry.server.ts
The package `@sentry-internal/nitro-utils` is not inlined in the build process and it's currently not possible to do this with the nuxt module builder, so I inlined the function we import from there to fix the build error people are getting.
follow-up on https://github.com/getsentry/sentry-javascript/issues/14661
=> fix(nuxt): Inline nitro-utils function

packages/profiling-node/src/integration.ts
This PR changes how we store the profile id on the SDK while the the profile is recording. Previously, we'd add the profile id to the current scope. It seems like in some cases, the current scope active at root span start is not applied to the transaction event in an express request transaction. Meaning that when we send the transaction envelope, the transaction event does not contain a profileId. 
This PR puts the profile id onto the isolation scope instead, which at least in server applications (like express) should correspond to the lifetime of a request. 
This doesn't fix all the weird behaviour I discovered in https://github.com/getsentry/sentry-javascript/issues/14655#issuecomment-2538609260 but in my local debugging, profiles were sent after making this change. 
fixes …
=> fix(profiling-node): Ensure profileId is added to transaction event

dev-packages/browser-integration-tests/suites/integrations/httpclient/axios/test.ts, dev-packages/browser-integration-tests/suites/integrations/httpclient/fetch/simple/test.ts, dev-packages/browser-integration-tests/suites/integrations/httpclient/fetch/withRequest/test.ts, dev-packages/browser-integration-tests/suites/integrations/httpclient/fetch/withRequestAndBodyAndOptions/test.ts, dev-packages/browser-integration-tests/suites/integrations/httpclient/fetch/withRequestAndOptions/test.ts, dev-packages/browser-integration-tests/suites/integrations/httpclient/xhr/test.ts, dev-packages/browser-integration-tests/utils/generatePlugin.ts, packages/browser-utils/src/instrument/xhr.ts, packages/browser/src/integrations/httpclient.ts, packages/core/src/types-hoist/instrument.ts, packages/core/src/utils-hoist/instrument/fetch.ts
Resolves: https://github.com/getsentry/sentry-javascript/issues/8353
Updated `fetch` and `xhr` wrappers to pass virtual errors to the `HttpClient` integration so we can group the events with the stack traces. 
It seems we can't create the virtual errors inside the `HttpClient` integration, as we're losing the non-Sentry frames.
Sampled fetch event - [Link](https://sentry-sdks.sentry.io/issues/6094873721/?project=5659328&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&statsPeriod=1m&stream_index=0)
Sampled XHR event - [Link](https://sentry-sdks.sentry.io/issues/6094938511/?project=5659328&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=1m&stream_index=0)
=> feat(browser): Attach virtual stack traces to `HttpClient` events.

packages/profiling-node/src/cpu_profiler.ts, packages/profiling-node/src/types.ts, packages/profiling-node/test/cpu_profiler.test.ts
This PR adds a guard to check that the native `startProfiling` and `stopProfiling` APIs are actually available and functions. This came up in #14561 where it seems like they're not always loaded correctly. For reasons unknown to me. 
However, after looking at the cpp code it seems to me like there is an edge case where `PrivateCpuProfilerBindings` could be loaded but not all of its methods. 
@JonasBa happy to let you make the call if this PR makes sense or not. 
ref #14561
=> fix(profiling-node): Guard invocation of native profiling methods

dev-packages/browser-integration-tests/package.json, packages/replay-canvas/package.json, packages/replay-internal/package.json, yarn.lock
Includes the following fixes:
- fix: remote CSS does not get rebuilt properly ([#226](https://github.com/getsentry/rrweb/pull/226))
- fix(snapshot): Set <link> attributes to null for remote CSS ([#227](https://github.com/getsentry/rrweb/pull/227))
- fix(snapshot): Change to ignore all link[rel="modulepreload"] ([#228](https://github.com/getsentry/rrweb/pull/228))
=> feat(replay): Upgrade rrweb packages to 2.31.0

dev-packages/e2e-tests/test-applications/node-otel-custom-sampler/src/instrument.ts, dev-packages/e2e-tests/test-applications/node-otel-sdk-node/src/instrument.ts, dev-packages/e2e-tests/test-applications/node-otel-without-tracing/src/instrument.ts, docs/migration/draft-v9-migration-guide.md, docs/migration/v8-to-v9.md, packages/node/src/integrations/http/index.ts, packages/node/test/integrations/http.test.ts
With this PR, the default value for the `spans` option in the `httpIntegration` is changed to `false`, if `skipOpenTelemetrySetup: true` is configured. This is what you'd expect as a user, you do not want Sentry to register any OTEL instrumentation and emit any spans in this scenario.
Closes https://github.com/getsentry/sentry-javascript/issues/14675
=> feat(node)!: Avoid http spans by default for custom OTEL setups

.craft.yml
The v9 branch should not push to the v8 layer.
=> chore(craft): Remove aws v8 layer from .craft.yml

.github/dependency-review-config.yml
=> meta: Ignore `GHSA-gp8f-8m3g-qvj9` which is used in E2E tests

.craft.yml
This PR temporarily disables publishing a lambda layer while `develop` is the branch where we cut v9 pre releases from. We shouldn't publish prerelease layer versions since we can't mark these layers as pre-release. They'd appear simply as stable new layer versions (with incremented ARN number)
=> chore(publish): Temporarily stop publishing lambda layer for v9 peview versions

dev-packages/node-integration-tests/suites/anr/basic-multiple.mjs, dev-packages/node-integration-tests/suites/anr/test.ts, packages/node/src/integrations/anr/common.ts, packages/node/src/integrations/anr/index.ts, packages/node/src/integrations/anr/worker.ts
- Closes #11160 
- Ref https://github.com/getsentry/sentry-electron/issues/876
Adds a `maxAnrEvents` option to the ANR integration which allows you to capture more than one event.
=> feat: Allow capture of more than 1 ANR event

packages/node/src/sdk/api.ts, packages/vercel-edge/src/sdk.ts
This change adds release name detection for Railway
Based on https://github.com/getsentry/sentry-javascript/pull/12529
Related: https://github.com/getsentry/sentry-javascript-bundler-plugins/pull/639
=> feat(node): Detect Railway release name

dev-packages/e2e-tests/lib/getTestMatrix.ts, packages/browser/test/sdk.test.ts, packages/core/src/utils-hoist/vercelWaitUntil.ts, packages/core/src/utils/applyScopeDataToEvent.ts, packages/core/src/utils/merge.ts, packages/core/src/utils/prepareEvent.ts, packages/core/src/utils/spanUtils.ts, packages/core/test/lib/envelope.test.ts, packages/core/test/lib/integrations/zoderrrors.test.ts, packages/core/test/lib/tracing/trace.test.ts, packages/core/test/lib/transports/multiplexed.test.ts, packages/core/test/lib/transports/offline.test.ts, packages/core/test/utils-hoist/envelope.test.ts, packages/core/test/utils-hoist/misc.test.ts, packages/feedback/src/core/components/Actor.test.ts, packages/node/src/cron/node-cron.ts, packages/node/src/integrations/context.ts, packages/node/src/integrations/local-variables/local-variables-sync.ts, packages/node/src/integrations/local-variables/worker.ts, packages/node/src/integrations/tracing/hapi/index.ts, packages/node/src/integrations/tracing/koa.ts, packages/node/src/integrations/tracing/nest/sentry-nest-instrumentation.ts, packages/node/src/integrations/tracing/redis.ts, packages/node/src/integrations/tracing/tedious.ts, packages/node/test/integration/transactions.test.ts, packages/opentelemetry/test/integration/transactions.test.ts
I was playing around with finally enabling the [no-unnecessary-condition](https://typescript-eslint.io/rules/no-unnecessary-condition/) eslint rule, and figured to start fixing some of the stuff it found. These should mostly be straightforward things, or in some cases I adjusted tests to ensure we "correctly" check for stuff.
=> ref: Remove some unnecessary conditions

dev-packages/node-integration-tests/suites/public-api/startSpan/with-nested-spans/test.ts, packages/core/src/types-hoist/span.ts, packages/core/src/utils/spanUtils.ts, packages/core/test/lib/baseclient.test.ts, packages/core/test/lib/tracing/sentryNonRecordingSpan.test.ts, packages/core/test/lib/utils/spanUtils.test.ts, packages/node/src/integrations/tracing/graphql.ts, packages/node/src/integrations/tracing/vercelai/index.ts, packages/opentelemetry/src/propagator.ts, packages/opentelemetry/test/trace.test.ts, packages/vue/test/router.test.ts
Previously `spanToJSON` would return `Partial<SpanJSON>`. This meant that you always had to guard all the stuff you picked from it - even though in reality, we know that certain stuff will always be there.
To alleviate this, this PR changes this so that `spanToJSON` actually returns `SpanJSON`. This means that in the fallback case, we return `data: {}`, as well as a random (current) timestamp. Since we know that in reality we will only have the two scenarios that we properly handle, this is fine IMHO and makes usage of this everywhere else a little bit less painful.
In a follow up, we can get rid of a bunch of `const data = spanToJSON(span).data || {}` type code.
While at it, I also updated the type of `data` to `SpanAttributes`, which is correct (it was `Record<string, any>` before). …
=> feat(core): Streamline `SpanJSON` type

.github/workflows/build.yml, .github/workflows/enforce-license-compliance.yml
In order for us to have size-limit comparison etc, we need to ensure CI runs on v8 & v9 branches too.
Picking this from develop so we also have this on v8 branch!
=> ci(v8): Ensure CI runs on v8 & v9 branches (#14604)

CHANGELOG.md
This release also publishes the AWS lambda layer under the current, non-version-suffixed layer since it's lagging behind since `8.42.0` with the introduction of the v8-suffixed layer.
=> meta(changelog): Update changelog for 8.45.1

.size-limit.js, packages/core/src/baseclient.ts, packages/core/src/integrations/inboundfilters.ts, packages/core/src/utils/eventUtils.ts, packages/core/test/lib/baseclient.test.ts
=> ref(core): Log debug message when capturing error events

packages/core/src/carrier.ts, packages/core/src/currentScopes.ts, packages/core/src/defaultScopes.ts, packages/core/src/index.ts, packages/core/src/metrics/exports.ts, packages/core/src/utils-hoist/envelope.ts, packages/core/src/utils-hoist/index.ts, packages/core/src/utils-hoist/logger.ts, packages/core/src/utils-hoist/worldwide.ts, packages/core/test/lib/hint.test.ts, packages/core/test/utils-hoist/envelope.test.ts
I do not really think this is breaking or has any impact on any user code, but to be on the safe side, we can remove this in v9.
The one actual breaking thing is to also move the `encodePolyfill` / `decodePolyfill` code to the versioned carrier - this was before still on the global, making this a bit harder than necessary. In v9, this will have to be set on the versioned carrier the same as other things - cc @krystofwoldrich
=> ref(core)!: Remove backwards compatible SentryCarrier type

.craft.yml
The v8 branch should not publish to the latest layer.
=> chore(craft): Publish only aws v8 layer

packages/deno/package.json
I noticed that after https://github.com/getsentry/sentry-javascript/pull/14729, now tests started failing 😬 
The reason:
* We run `deno check ./build/index.mjs`
* This checks the types, but we now do not inline those anymore into the generated `./build/index.d.ts` file
* Instead, we just import them from `@sentry/core`
* Now `deno check` downloads the latest version of core into a local tmp folder and uses this for checking
* But there are different exports there than locally, leading to test failures 😬 
this PR simple kills the type tests - not sure if we need them/they are needed, but I can't think of a different way to make this work, there isn't really a way (as far as I see?) to tell `deno check` to consider a dependency from a local path instead 😬
=> chore(deno): Stop testing types

packages/core/src/types-hoist/context.ts
This isn't exported in types-hoist/index, but we found users can still import it from a `build/` file. Discussed with @billyvg we don't want users to accidentally import it this way. 
Note we currently use this type in sentry, until https://github.com/getsentry/sentry/pull/81954 is rolled out.
=> ref(flags): don't export FeatureFlagContext in types-hoist/context.ts

packages/browser/src/tracing/request.ts, packages/browser/test/tracing/browserTracingIntegration.test.ts, packages/core/src/tracing/dynamicSamplingContext.ts, packages/core/src/tracing/idleSpan.ts, packages/core/test/lib/tracing/sentrySpan.test.ts, packages/nestjs/src/sdk.ts, packages/nestjs/src/setup.ts, packages/nextjs/src/server/index.ts, packages/node/src/integrations/tracing/connect.ts, packages/node/src/integrations/tracing/express.ts, packages/node/src/integrations/tracing/fastify.ts, packages/node/src/integrations/tracing/graphql.ts, packages/node/src/integrations/tracing/hapi/index.ts, packages/node/src/integrations/tracing/knex.ts, packages/node/src/integrations/tracing/koa.ts, packages/node/src/integrations/tracing/nest/nest.ts, packages/node/src/integrations/tracing/redis.ts, packages/node/src/integrations/tracing/tedious.ts, packages/node/src/integrations/tracing/vercelai/index.ts, packages/opentelemetry/src/propagator.ts, packages/opentelemetry/src/utils/enhanceDscWithOpenTelemetryRootSpanName.ts, packages/remix/src/utils/integrations/opentelemetry.ts, packages/vue/src/router.ts, packages/vue/test/router.test.ts
Since this was reworked in https://github.com/getsentry/sentry-javascript/pull/14693 to always return something, we can safe some checks/fallbacks.
This most likely does not change all the things, but focuses on the places that were easy to find/replace.
=> ref: Remove unnecessary checks for `SpanJSON.data` existence

docs/commit-issue-pr-guidelines.md
Just making this explicit, for the future.
=> docs: Add docs about backported commit guidelines

packages/node/package.json, yarn.lock
Bump [@prisma/instrumentation](https://github.com/prisma/prisma/tree/HEAD/packages/instrumentation) from 5.19.1 to 5.22.0.
See https://github.com/prisma/prisma/releases/tag/5.22.0 for release notes.
This is to take advantage of the following change in 5.22.0:
> In our ongoing effort to stabilize the tracing Preview feature, we’ve made our spans compliant with OpenTelemetry Semantic Conventions for Database Client Calls. **This should lead to better compatibility with tools such as DataDog and Sentry** [emphasis added by me].
There's also this change in [5.21.0](https://github.com/prisma/prisma/releases/tag/5.21.0):
> The `tracing` Preview feature now has full support for MongoDB with previously missing functionality now implemented. This is a part of the ongoing effort to stabilize this …
=> feat(node/deps): Bump @prisma/instrumentation from 5.19.1 to 5.22.0

CHANGELOG.md, packages/node/package.json, yarn.lock
Backport of https://github.com/getsentry/sentry-javascript/pull/14753:
Bump [@prisma/instrumentation](https://github.com/prisma/prisma/tree/HEAD/packages/instrumentation) from 5.19.1 to 5.22.0.
See https://github.com/prisma/prisma/releases/tag/5.22.0 for release notes.
This is to take advantage of the following change in 5.22.0:
> In our ongoing effort to stabilize the tracing Preview feature, we’ve made our spans compliant with OpenTelemetry Semantic Conventions for Database Client Calls. **This should lead to better compatibility with tools such as DataDog and Sentry** [emphasis added by me].
There's also this change in [5.21.0](https://github.com/prisma/prisma/releases/tag/5.21.0):
> The `tracing` Preview feature now has full support for MongoDB with previously missing functionality …
=> feat(v8/node/deps): Bump @prisma/instrumentation from 5.19.1 to 5.22.0

dev-packages/e2e-tests/test-applications/react-create-hash-router/src/index.tsx, dev-packages/e2e-tests/test-applications/react-router-6-use-routes/src/index.tsx, docs/migration/v8-to-v9.md, packages/react/src/index.ts, packages/react/src/reactrouterv6.tsx
Removes code deprecated in https://github.com/getsentry/sentry-javascript/pull/14513 and adds changelog entry as appropriate:
Removed methods:
1. The `wrapUseRoutes` method has been removed. Use `wrapUseRoutesV6` or `wrapUseRoutesV7` instead depending on what version of react router you are using.
2. The `wrapCreateBrowserRouter` method has been removed. Use `wrapCreateBrowserRouterV6` or `wrapCreateBrowserRouterV7` depending on what version of react router you are using.
=> feat(react)!: Remove deprecated react router methods

docs/migration/v8-to-v9.md, packages/core/src/utils-hoist/index.ts, packages/core/src/utils-hoist/url.ts, packages/core/test/utils-hoist/url.test.ts, packages/react/src/reactrouterv6-compat-utils.tsx, packages/react/test/reactrouterv6-compat-utils.test.tsx, packages/utils/src/index.ts
Removes code deprecated in https://github.com/getsentry/sentry-javascript/pull/14458
Removes `getNumberOfUrlSegments` as a public export from `@sentry/core`.
This method is still used, so we extract it into a helper in `@sentry/react` (and port the tests accordingly).
=> feat(react)!: Remove deprecated `getNumberOfUrlSegments` method

docs/migration/v8-to-v9.md, packages/nestjs/src/setup.ts
=> feat(nestjs): Remove `SentryService`

packages/angular/README.md
In this commit, we update the README.md to include examples with `ApplicationConfig` as a first-class citizen, as it is now the recommended approach. Most users are likely using the latest versions, but older examples have also been preserved.
=> docs(angular): update README.md

dev-packages/node-integration-tests/package.json, dev-packages/node-integration-tests/suites/tracing/prisma-orm/package.json, dev-packages/node-integration-tests/suites/tracing/prisma-orm/test.ts, dev-packages/node-integration-tests/suites/tracing/prisma-orm/yarn.lock, packages/node/src/integrations/tracing/prisma.ts
Since v5.22, Prisma properly adds the `db.system` to it's OTEL spans. 
This PR fixes the behavior so we do not overwrite it. For now, I left the fallback behavior in, that would add it if `db.system` is missing - as otherwise this would "break" on older prisma versions. 
This also needs to be backported to v8.
=> feat(node): Do not overwrite prisma `db.system` in newer Prisma versions

packages/replay-internal/src/util/getPrivacyOptions.ts, packages/replay-internal/test/integration/integrationSettings.test.ts, packages/replay-internal/test/integration/rrweb.test.ts, packages/replay-internal/test/unit/util/getPrivacyOptions.test.ts
closes https://github.com/getsentry/sentry-javascript/issues/8241
=> feat(replay): Mask srcdoc iframe contents per default

CHANGELOG.md, packages/nextjs/src/config/webpack.ts
backport of #14766 to v8. Nothing major just figured we might as well get this out with the next v8 release
=> ref(v8/nextjs): Fix typo in source maps deletion warning

packages/replay-internal/src/util/getPrivacyOptions.ts, packages/replay-internal/test/integration/integrationSettings.test.ts, packages/replay-internal/test/integration/rrweb.test.ts, packages/replay-internal/test/unit/util/getPrivacyOptions.test.ts
Backport of https://github.com/getsentry/sentry-javascript/pull/14760
=> feat(v8/replay): Mask srcdoc iframe contents per default

docs/migration/v8-to-v9.md, packages/core/src/utils-hoist/index.ts, packages/core/src/utils-hoist/severity.ts, packages/utils/src/index.ts
ref: https://github.com/getsentry/sentry-javascript/issues/14268
Deprecation PR: https://github.com/getsentry/sentry-javascript/pull/14407
Removes `validSeverityLevels`. This has no replacement.
=> feat(core)!: Remove validSeverityLevels export

docs/migration/v8-to-v9.md, packages/core/src/utils-hoist/index.ts, packages/core/src/utils-hoist/misc.ts, packages/core/test/utils-hoist/misc.test.ts, packages/utils/src/index.ts
ref: https://github.com/getsentry/sentry-javascript/issues/14268
Deprecation PR: https://github.com/getsentry/sentry-javascript/pull/14405
Removes `arrayify`. This has no replacement.
=> feat(core)!: Remove `arrayify` method

dev-packages/e2e-tests/test-applications/nextjs-turbo/package.json, packages/node/package.json, yarn.lock
This version allows for correctly patching absolute paths and unblocks us on https://github.com/getsentry/sentry-javascript/pull/14606.
=> deps(node): Bump `import-in-the-middle` to `1.12.0`

docs/migration/v8-to-v9.md, packages/browser/src/tracing/browserTracingIntegration.ts, packages/core/src/utils-hoist/browser.ts, packages/core/src/utils-hoist/index.ts, packages/core/test/utils-hoist/browser.test.ts, packages/svelte/src/sdk.ts, packages/utils/src/index.ts
I noticed this in https://github.com/getsentry/sentry-javascript/pull/14758, this seems unnecessary and all browsers/envs we support should be able to handle this. We only use this in two places anyhow, so we can just guard there (a bit) for this instead.
I will add a deprecation to v8 for this too, although this is just exported from core and will most likely not affect anybody.
=> feat(core)!: Remove `getDomElement` method

dev-packages/node-integration-tests/suites/tracing/envelope-header/sampleRate-propagation/server.js, dev-packages/node-integration-tests/suites/tracing/envelope-header/sampleRate-propagation/test.ts
While investigating an internally reported SDK issue, I had the suspicion that our Node SDK might handle the sample rate from an incoming `baggage` header incorrectly. Turns out that's not the case and things work correctly. I couldn't find a test though, where we specifically cover a non `1.0` `sentry-sample_rate` baggage value, so I figured there's value in adding this test.
=> test(node): Add integration test to demonstrate sample rate propagation of incoming trace

dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/middleware.test.ts, packages/browser/src/integrations/breadcrumbs.ts, packages/cloudflare/src/integrations/fetch.ts, packages/cloudflare/test/integrations/fetch.test.ts, packages/deno/src/integrations/breadcrumbs.ts, packages/vercel-edge/src/integrations/wintercg-fetch.ts, packages/vercel-edge/test/wintercg-fetch.test.ts
It seems like the fact that fetch breadcrumbs had the `__span` property was an accident since like forever. This PR makes it more explicit what we put in the breadcrumb data.
=> fix(node): Don't leak `__span` property into breadcrumbs

packages/nestjs/package.json
resolves https://github.com/getsentry/sentry-javascript/issues/14789
backport of v9 change: https://github.com/getsentry/sentry-javascript/pull/14790
=> fix(nestjs/v8): Use correct main/module path in package.json

packages/nestjs/package.json
ref https://github.com/getsentry/sentry-javascript/issues/14789
`build/cjs/nestjs/index.js` and `build/esm/nestjs/index.js` doesn't exist, this fixes that.
=> fix(nestjs): Use correct main/module path in package.json

packages/browser/src/tracing/browserTracingIntegration.ts, packages/core/src/utils-hoist/browser.ts, packages/core/src/utils-hoist/index.ts, packages/core/test/utils-hoist/browser.test.ts, packages/svelte/src/sdk.ts, packages/utils/src/index.ts
Backported deprecation of https://github.com/getsentry/sentry-javascript/pull/14797
=> feat(v8/core): Deprecate `getDomElement` method

dev-packages/e2e-tests/test-applications/astro-4/package.json, dev-packages/e2e-tests/test-applications/astro-4/src/env.d.ts
In our Astro-4 E2E test app, Astro's Node adapter was pinned to a bad version that didn'T work correctly with newer Astro versions. We pinned the Astro version a while ago in https://github.com/getsentry/sentry-javascript/pull/14030 to unblock CI but looks like we just didn't follow up with investigating what caused the issue back then. 
This came up again when dependabot tried to bump the Astro version in #14781 and #14807 and as a result #14808 was opened.
This PR now 
- bumps the Node adapter version which makes newer Astro version function properly again
- updates `astro` to the latest v4 version (which is why I closed #14807)
closes #14808
=> test(astro): Fix Astro 4 e2e test

dev-packages/e2e-tests/test-applications/astro-5/package.json, dev-packages/e2e-tests/test-applications/react-router-7-spa/package.json
Adds an override for esbuild for tests that use vite6.
ref https://github.com/evanw/esbuild/issues/4010
=> chore(tests): Add esbuild overrides for vite 6 tests

packages/astro/src/index.types.ts, packages/core/src/asyncContext/types.ts, packages/core/src/tracing/trace.ts, packages/nextjs/src/common/pages-router-instrumentation/wrapApiHandlerWithSentry.ts, packages/nextjs/src/common/withServerActionInstrumentation.ts, packages/nextjs/src/index.types.ts, packages/node/src/index.ts, packages/nuxt/src/index.types.ts, packages/opentelemetry/src/asyncContextStrategy.ts, packages/opentelemetry/src/trace.ts, packages/opentelemetry/test/trace.test.ts, packages/remix/src/index.types.ts, packages/remix/src/utils/instrumentServer.ts, packages/solidstart/src/index.types.ts, packages/sveltekit/src/index.types.ts, packages/sveltekit/src/server/handle.ts
We have a different implementation of `continueTrace` for OTEL/Node. Until now we relied on actually using the import from `@sentry/node` vs `@sentry/core` to ensure this. However, this is a footgun, and actually lead to a problem in NextJS because we used the core variant there. Also, it is simply not isomorphic.
So to fix this, this PR puts `continueTrace` on the ACS so we can consistently use the core variant in all environments.
Fixes https://github.com/getsentry/sentry-javascript/issues/14787
=> fix(core): Use consistent `continueTrace` implementation in core

packages/node/src/integrations/anr/index.ts, packages/node/src/integrations/local-variables/local-variables-async.ts
- Closes #14524
Just like `execArgv` can cause `--import` and `--require` to be preloaded in worker threads and cause infinite loops, `NODE_OPTIONS` can cause this too.
=> fix(node): Ensure `NODE_OPTIONS` is not passed to worker threads

dev-packages/node-integration-tests/suites/anr/app-path.mjs, dev-packages/node-integration-tests/suites/anr/test.ts, packages/node/src/integrations/anr/worker.ts
- Ref https://github.com/getsentry/sentry-electron/issues/1011
In #14709 I didn't add a test. If I had, I would have noticed that it was not working. File paths need normalising before we try and match up debug files.
=> fix: Correctly resolve debug IDs for ANR events with custom appRoot

dev-packages/node-integration-tests/suites/anr/app-path.mjs, dev-packages/node-integration-tests/suites/anr/test.ts, packages/node/src/integrations/anr/worker.ts
=> fix(v8/node): Correctly resolve debug IDs for ANR events with custom appRoot

dev-packages/e2e-tests/test-applications/angular-17/src/app/component-tracking/component-tracking.components.ts, dev-packages/e2e-tests/test-applications/angular-17/tests/performance.test.ts, dev-packages/e2e-tests/test-applications/angular-19/.npmrc, dev-packages/e2e-tests/test-applications/angular-19/src/app/component-tracking/component-tracking.components.ts, dev-packages/e2e-tests/test-applications/angular-19/tests/performance.test.ts, packages/angular/src/tracing.ts
The `trace` directive should typically be declared on components to validly trace the lifecycle (from `ngOnInit` to `ngAfterViewInit`, when child views are also rendered). If `trace` is mistakenly not provided, we fall back to `tagName`.
=> fix(angular): Fall back to element `tagName` when name is not provided to `TraceDirective`

CHANGELOG.md, dev-packages/e2e-tests/test-applications/angular-17/src/app/component-tracking/component-tracking.components.ts, dev-packages/e2e-tests/test-applications/angular-17/tests/performance.test.ts, dev-packages/e2e-tests/test-applications/angular-19/.npmrc, dev-packages/e2e-tests/test-applications/angular-19/src/app/component-tracking/component-tracking.components.ts, dev-packages/e2e-tests/test-applications/angular-19/tests/performance.test.ts, packages/angular/src/tracing.ts
=> fix(v8/angular): Fall back to element `tagName` when name is not provided to `TraceDirective`

packages/react/src/reactrouterv6-compat-utils.tsx, packages/react/test/reactrouterv6.test.tsx
We noticed this in Sentry's `/issues/:groupId/` route, which uses SDK v8.43.0. The full route tree is complex, but the relevant parts are:
```js
<Route path="/" element={<div>root</div>}>
<Route path="/issues/:groupId/" element={<div>issues group</div>}>
<Route index element={<div>index</div>} />
</Route>
</Route>
```
If you navigate to e.g. `/issues/123` (no trailing slash), the recorded transaction name is `//issues/:groupId/` (notice the double slash). This looks messy but doesn't have too much of a consequence.
The worse issue is when you navigate to e.g.  `/issues/123/` (with trailing slash), the transaction name is `/issues/123/` - it is not parameterized. This breaks transaction grouping. On the `master` and `develop` branch of the SDK, the transaction name is recorded as `/`. This …
=> fix(react): improve handling of routes nested under path="/"

.craft.yml
The v8 suffixed layer lands in the release-registry every time we publish a release from the v8 branch which not only breaks https://github.com/getsentry/sentry/blob/c11f4c099257b2388d150f71fb39516e3d3f2328/src/sentry/integrations/aws_lambda/utils.py#L236-L253 but also ends up in the docs as the current version: when using the ARN dropdown https://docs.sentry.io/platforms/javascript/guides/aws-lambda/install/cjs-layer/.
This removes the suffix so we get the current major published under the non-suffixed name.
Follow-up task: https://github.com/getsentry/sentry-javascript/issues/14842
=> fix(aws-lambda): Remove version suffix from lambda layer

packages/astro/src/index.types.ts, packages/core/src/asyncContext/types.ts, packages/core/src/tracing/trace.ts, packages/nextjs/src/common/pages-router-instrumentation/wrapApiHandlerWithSentry.ts, packages/nextjs/src/common/withServerActionInstrumentation.ts, packages/nextjs/src/index.types.ts, packages/node/src/index.ts, packages/nuxt/src/index.types.ts, packages/opentelemetry/src/asyncContextStrategy.ts, packages/opentelemetry/src/trace.ts, packages/opentelemetry/test/trace.test.ts, packages/remix/src/index.types.ts, packages/remix/src/utils/instrumentServer.ts, packages/solidstart/src/index.types.ts, packages/sveltekit/src/index.types.ts, packages/sveltekit/src/server/handle.ts
V8 backport of https://github.com/getsentry/sentry-javascript/pull/14813
We have a different implementation of `continueTrace` for OTEL/Node. Until now we relied on actually using the import from `@sentry/node` vs `@sentry/core` to ensure this. However, this is a footgun, and actually lead to a problem in NextJS because we used the core variant there. Also, it is simply not isomorphic.
So to fix this, this PR puts `continueTrace` on the ACS so we can consistently use the core variant in all environments.
Fixes https://github.com/getsentry/sentry-javascript/issues/14787
=> fix(v8/core): Use consistent `continueTrace` implementation in core

packages/core/src/scope.ts, packages/core/src/types-hoist/event.ts, packages/core/src/types-hoist/request.ts
This ensures we use a consistent and proper type for `setSdkProcessingMetadata()` and related APIs.
Closes https://github.com/getsentry/sentry-javascript/issues/14341
=> feat(core)!: Type sdkProcessingMetadata more strictly

dev-packages/node-integration-tests/suites/express/requestUser/server.js, dev-packages/node-integration-tests/suites/express/requestUser/test.ts, packages/core/src/utils-hoist/requestdata.ts, packages/node/src/integrations/tracing/express.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/14847
After some digging, I figured out that the `req.user` handling on express is not working anymore, because apparently express does not mutate the actual http `request` object, but clones/forkes it (??) somehow. So since we now set the request in the SentryHttpInstrumentation generally, it would not pick up express-specific things anymore.
IMHO this is not great and we do not want this anymore in v9 anyhow, but it was the behavior before. This PR fixes this by setting the express request again on the isolation scope in an express middleware, which is registered by `Sentry.setupExpressErrorHandler(app)`. 
Note that we plan to change this behavior here: https://github.com/getsentry/sentry-javascript/pull/14806 but I figured it …
=> fix(node): Ensure express requests are properly handled

dev-packages/e2e-tests/test-applications/vue-3/src/main.ts, docs/migration/v8-to-v9.md, packages/vue/src/integration.ts, packages/vue/src/sdk.ts, packages/vue/src/tracing.ts, packages/vue/src/types.ts
Deprecation PR: https://github.com/getsentry/sentry-javascript/issues/14265
Closes: #5907
=> feat(vue)!: Remove configuring Vue tracing options anywhere else other than through the `vueIntegration`'s `tracingOptions` option

docs/migration/v8-to-v9.md, packages/browser/src/exports.ts, packages/bun/src/index.ts, packages/cloudflare/src/index.ts, packages/core/src/types-hoist/index.ts, packages/core/src/types-hoist/request.ts, packages/deno/src/index.ts, packages/node/src/index.ts, packages/types/src/index.ts, packages/vercel-edge/src/index.ts
This is named misleadingly, instead use `RequestEventData`.
Closes https://github.com/getsentry/sentry-javascript/issues/14301
=> feat(core)!: Remove deprecated `Request` type

dev-packages/browser-integration-tests/package.json, dev-packages/browser-integration-tests/utils/replayHelpers.ts, packages/replay-internal/package.json, packages/replay-worker/package.json, yarn.lock
Also stop using pako for browser integration tests, to unify this.
v0.8.2 has some small bug fixes, see: https://github.com/101arrowz/fflate/releases/tag/v0.8.2
=> feat(replay): Update fflate to 0.8.2

packages/aws-serverless/src/sdk.ts, packages/core/src/types-hoist/samplingcontext.ts
The `TracingHandler` is deprecated since v8, but some JSDocs still mention the usage of it which can be misleading.
=> docs(node): Remove old occurrences of tracingHandler

docs/migration/v8-to-v9.md, packages/angular/.eslintrc.cjs, packages/core/src/getCurrentHubShim.ts, packages/core/src/types-hoist/hub.ts, packages/core/src/types-hoist/index.ts, packages/core/src/types-hoist/integration.ts, packages/core/src/utils-hoist/syncpromise.ts, packages/eslint-plugin-sdk/src/rules/no-class-field-initializers.js, packages/nestjs/src/integrations/sentry-nest-event-instrumentation.ts, packages/nestjs/src/integrations/sentry-nest-instrumentation.ts, packages/react/src/errorboundary.tsx, packages/react/src/profiler.tsx, packages/replay-internal/src/integration.ts, packages/replay-internal/src/replay.ts, packages/types/src/index.ts
We already have an eslint rule to avoid class fields, but had exceptions for static fields as well as for arrow functions.
This also leads to bundle size increases, so removing the exceptions and handling the (few) exceptions we have there should save some bytes.
Additionally, this has additional challenges if we want to avoid/reduce polyfills, as class fields need to be polyfilled for ES2020, sadly.
Found as part of https://github.com/getsentry/sentry-javascript/pull/14882
=> feat: Avoid class fields all-together

dev-packages/browser-integration-tests/suites/sessions/update-session/test.ts, dev-packages/browser-integration-tests/utils/helpers.ts, docs/migration/v8-to-v9.md, packages/browser/src/client.ts, packages/core/src/baseclient.ts, packages/core/src/exports.ts, packages/core/src/getCurrentHubShim.ts, packages/core/src/server-runtime-client.ts, packages/core/test/lib/server-runtime-client.test.ts, packages/node/src/integrations/anr/index.ts, packages/node/test/sdk/client.test.ts
This PR ensures that we always take the session from the isolation scope, never from the current scope.
This has the implication that we need to be sure to pass the isolation scope to `_processEvent`, as this is where the session may be marked as errored. For this, I updated the internal method `_processEvent` to take the isolation scope as last argument, as well as streamlining this slightly.
I opted to update the signature of the protected `_prepareEvent` method too, and make currentScope/isolationScope required there. We already always pass this in now, so it safes a few bytes to avoid the fallback everywhere. This should not really affect users unless they overwrite the `_processEvent` method, which is internal/private anyhow, so IMHO this should be fine. I added a small note to the …
=> feat(core)!: Always use session from isolation scope

packages/react/src/reactrouterv6-compat-utils.tsx, packages/react/test/reactrouterv6.test.tsx
Backports https://github.com/getsentry/sentry-javascript/pull/14821
=> fix(v8/react): Improve handling of routes nested under path="/"

packages/browser/src/feedbackSync.ts, packages/feedback/src/core/integration.ts
Closes https://github.com/getsentry/sentry-javascript/issues/14891
This PR updates the sync feedback integration to avoid it pulling in the `lazyLoadIntegration` code. This is not really needed and leads to some problems (and also bundle size increase).
For this I updated the type signature of `buildFeedbackIntegration` to ensure that _either_ `lazyLoadIntegration` _or_ the getter functions are provided, so we can type-safely use this.
We probably also want to backport this to v8 then.
=> fix(feedback): Avoid lazy loading code for `syncFeedbackIntegration`

dev-packages/e2e-tests/test-applications/react-router-6-descendant-routes/src/index.tsx, dev-packages/e2e-tests/test-applications/react-router-6-descendant-routes/src/pages/Index.tsx, dev-packages/e2e-tests/test-applications/react-router-6-descendant-routes/tests/transactions.test.ts, packages/react/src/reactrouterv6-compat-utils.tsx, packages/react/test/reactrouter-descendant-routes.test.tsx, packages/react/test/reactrouterv6.test.tsx
backport of https://github.com/getsentry/sentry-javascript/pull/14878
=> fix(v8/react): Use `Set` as the `allRoutes` container. (#14878)

packages/browser/src/feedbackSync.ts, packages/feedback/src/core/integration.ts
Backport of https://github.com/getsentry/sentry-javascript/pull/14895 for v8
=> fix(v8/feedback): Avoid lazy loading code for `syncFeedbackIntegration`

MIGRATION.md
Just a minor fix to the migration guide as raised here: https://github.com/getsentry/sentry-javascript/discussions/13103#discussioncomment-11618821
=> docs: Fix Next.js migration guide for v8

dev-packages/node-integration-tests/suites/express/requestUser/test.ts, docs/migration/v8-to-v9.md, packages/astro/src/index.server.ts, packages/aws-serverless/src/index.ts, packages/bun/src/index.ts, packages/core/src/integrations/requestdata.ts, packages/core/src/utils-hoist/index.ts, packages/core/src/utils-hoist/requestdata.ts, packages/core/test/lib/integrations/requestdata.test.ts, packages/google-cloud-serverless/src/index.ts, packages/node/src/index.ts, packages/remix/src/index.server.ts, packages/solidstart/src/server/index.ts, packages/sveltekit/src/server/index.ts
This was an express-specific, rather undocumented behavior, and also conflicted with our privacy-by-default stance.
Starting in v9, you'll need to manually call `Sentry.setUser()` e.g. in a middleware to set the user on Sentry events.
Docs for this are already pending: https://github.com/getsentry/sentry-docs/pull/12224
Extracted this out of https://github.com/getsentry/sentry-javascript/pull/14806
=> feat(core)!: Stop setting user in `requestDataIntegration`

packages/core/src/utils/prepareEvent.ts, packages/core/test/lib/prepareEvent.test.ts
While investigating https://github.com/getsentry/sentry-javascript/issues/14841, I noticed that we had some brittle non-null assertions in our `applyDebugIds` function which would cause the debug id application logic to terminate early, in case we'd encounter an `event.exception.values` item without a stack trace. The added regression test illustrates the scenario in which debug ids would not have been applied to the second exception prior to this fix.  
The nice thing about this fix is that it should even further decrease bundle size than the try/catch logic we had before because we can now use optional chaining in v9. 
~(I'll probably open another PR for the same problem in `applyDebugMeta`)~ Added to this PR as it really belonged together to get debugIds working in this scenario.
=> fix(core): Ensure debugIds are applied to all exceptions in an event

yarn.lock
I noticed some caching/dependency issues locally (when switching branches, ...), which are probably because the version did not change (but the source did). So I updated the version of sucrase on our fork, so this is clearly different and hopefully busts the cache better.
=> chore(deps): Bump version of forked sucrase from 3.35.0 to 3.36.0

packages/core/src/utils-hoist/worldwide.ts, packages/replay-internal/src/replay.ts, packages/replay-internal/src/util/getRecordingSamplingOptions.ts, packages/replay-internal/test/integration/rrweb.test.ts
This PR updates the rrweb sampling options depending on the userAgent as this tends to block the main thread on iOS browsers.
closes https://github.com/getsentry/sentry-javascript/issues/14534
=> fix(replay): Disable mousemove sampling in rrweb for iOS browsers

docs/migration/v8-to-v9.md, package.json, packages/browser-utils/src/metrics/inp.ts, packages/browser/src/exports.ts, packages/browser/src/sdk.ts, packages/core/src/api.ts, packages/core/src/index.ts, packages/core/src/report-dialog.ts, packages/core/src/types-hoist/wrappedfunction.ts
These are small changes, cleaning up outdated (I believe?) TODOs, and some internal type stuff.
=> ref(core)!: Cleanup internal types, including `ReportDialogOptions`

docs/migration/v8-to-v9.md, packages/nextjs/src/config/webpack.ts, packages/nextjs/src/config/webpackPluginOptions.ts, packages/nextjs/src/config/withSentryConfig.ts, packages/nextjs/test/config/testUtils.ts, packages/nextjs/test/config/webpack/webpackPluginOptions.test.ts
Resolves https://github.com/getsentry/sentry-javascript/issues/14940
=> feat(nextjs)!: Don't rely on Next.js Build ID for release names

dev-packages/node-integration-tests/suites/tracing/requests/http-unsampled/test.ts, packages/core/src/tracing/idleSpan.ts, packages/core/src/tracing/sentrySpan.ts, packages/core/src/tracing/trace.ts, packages/opentelemetry/src/sampler.ts, packages/opentelemetry/test/helpers/TestClient.ts, packages/opentelemetry/test/integration/breadcrumbs.test.ts, packages/opentelemetry/test/integration/scope.test.ts, packages/opentelemetry/test/integration/transactions.test.ts, packages/opentelemetry/test/propagator.test.ts, packages/opentelemetry/test/sampler.test.ts, packages/opentelemetry/test/spanExporter.test.ts, packages/opentelemetry/test/trace.test.ts, packages/opentelemetry/test/utils/getActiveSpan.test.ts, packages/opentelemetry/test/utils/setupEventContextTrace.test.ts
With this PR, the `sample_rate`,`transaction` client report is now consistently emitted at the time when the root span is sampled.
Previously, in Node (OTEL) we did not emit this at all, while in browser we emit it at span end time. This is inconsistent and not ideal. Emitting it in OTEL at span end time is difficult because `span.end()` is a no-op there and you do not get access to it anywhere. So doing it at span start (=sample time) is easier, and also makes more sense as this is also actually the time when the span is dropped.
=> feat(core): Emit client reports for unsampled root spans on span start

packages/sveltekit/src/vite/sourceMaps.ts, packages/sveltekit/test/vite/sentrySvelteKitPlugins.test.ts, packages/sveltekit/test/vite/sourceMaps.test.ts
This PR fixes a source maps deletion bug in the Sentry SvelteKit SDK reported in https://github.com/getsentry/sentry-javascript/issues/14131. 
After debugging this extensively, the root cause turned out to be a timing issue. For SvelteKit, we have to move all invocations of the `writeBundle` hook in the sub-plugins of the original Sentry Vite plugin to the `closeBundle` hook, to ensure that the second build made when the SvelteKit adapter is invoked is also awaited correctly. We did this correctly for the debug id source maps upload plugin but did not do it for the release management and file deletion plugins. 
The changed order of things caused a deadlock situations due to our deletion plugin waiting on upload and release plugins to finish. Since the deletion plugin was started earlier …
=> fix(sveltekit): Ensure source maps deletion is called after source maps upload

packages/angular-ivy/package.json, packages/hub/package.json, packages/serverless/package.json, packages/tracing/package.json
This PR sets the NPM publish tag of discontinued packages from `v7` back to `latest`. As pointed out in https://github.com/getsentry/sentry-javascript/issues/14923, it's a bit misleading for packages that have not received a v8 version but newer v7 versions that their `latest` tag doesn't point to the in fact latest version.
Affected packages:
- `@sentry/angular-ivy` (replaced by `@sentry/angular` in v8)
- `@sentry/hub` (discontinued)
- `@sentry/tracing` (discontinued)
- `@sentry/serverless` (replaced by `@sentry/aws-serverless`, `@sentry/google-cloud` and `@sentry/node` respectively)
fixes https://github.com/getsentry/sentry-javascript/issues/14923
=> fix(v7/publish): Ensure discontinued packages are published with `latest` tag

dev-packages/e2e-tests/test-applications/vue-3/tests/errors.test.ts, packages/vue/src/errorhandler.ts, packages/vue/src/types.ts, packages/vue/test/errorHandler.test.ts
PR for v9: https://github.com/getsentry/sentry-javascript/pull/14958
=> fix(v8/vue): Re-throw error when no errorHandler exists

CHANGELOG.md
Cutting a v7 patch to fix the label assignment of discontinued packages (see https://github.com/getsentry/sentry-javascript/pull/14926)
=> meta: Update Changelog for 7.120.3

docs/changelog/v7.md
=> chore(repo): Add missing v7 changelog entries

docs/changelog/v7.md
Adds a couple of missing changelog entries to the v8 branch, jus to keep things in sync. Will do the same for `develop` in a sec. Already includes #14960
=> chore(v8/repo): Add missing v7 changelog entries

packages/core/src/tracing/idleSpan.ts, packages/core/src/tracing/trace.ts, packages/core/test/lib/tracing/idleSpan.test.ts, packages/core/test/lib/tracing/trace.test.ts
Otherwise, parts of the DSC will be missing - we try to make it as complete as we can.
Since the span cannot be updated anyhow (e.g. the name cannot be changed), we can safely freeze this at this time.
Extracted out of https://github.com/getsentry/sentry-javascript/pull/14955
=> ref(core): Ensure non-recording root spans have frozen DSC

packages/core/src/utils-hoist/time.ts, packages/opentelemetry/src/utils/contextData.ts
Cleaning up some small comments.
=> chore: Cleanup unused comments

packages/browser/src/tracing/browserTracingIntegration.ts
Extracted this out of https://github.com/getsentry/sentry-javascript/pull/14955
We used to rely on implied stuff here quite a bit, which breaks if we start returning non recording spans. Honestly this just surfaces that this is not really ideal as it is 😬 We already pass the client around there everywhere, so this PR updates this so we keep the active idle span as non-enumerable prop on the client, ensuring this is consistent and "pure".
=> ref(browser): Improve active span handling for `browserTracingIntegration`

dev-packages/e2e-tests/test-applications/vue-3/tests/errors.test.ts, docs/migration/v8-to-v9.md, packages/vue/src/errorhandler.ts, packages/vue/src/integration.ts, packages/vue/src/types.ts, packages/vue/test/errorHandler.test.ts
Removes `logError` and always re-throws the error when it's not handled by the user.
PR for v8 (without removing `logError`): https://github.com/getsentry/sentry-javascript/pull/14943
Logging the error has been a problem in the past already (see https://github.com/getsentry/sentry-javascript/pull/7310). By just re-throwing the error we don't mess around with the initial message and stacktrace.
=> fix(vue): Remove `logError` from `vueIntegration`

packages/react/src/errorboundary.tsx, packages/react/test/errorboundary.test.tsx
The previous behaviour was to rely on the presence of the `fallback` prop to decide if the error was considered handled or not. The new property lets the consumer explicitely choose what should the handled status be.
If omitted, the old behaviour is still applied.
-> I'm having some failures locally that seem unrelated to my changes. Waiting for a CI check to confirm
=> feat(react): Add a `handled` prop to ErrorBoundary

CHANGELOG.md, packages/react/src/errorboundary.tsx, packages/react/test/errorboundary.test.tsx
=> feat(v8/react): Add a `handled` prop to ErrorBoundary

dev-packages/browser-integration-tests/suites/tracing/dsc-txn-name-update/test.ts
This pr just removes an unused directive in a test.
=> chore: Remove unused ts directive

packages/solidstart/src/config/wrapServerEntryWithDynamicImport.ts
This a strange one, maybe caused by caching? 
The last few PRs are failing due to these linting issues but I can't reproduce this locally on `develop` and it looks like everything passed in CI 🤷‍♂️
=> chore(nextjs): Fix optional chaining linting issue

.craft.yml
We decided to stop publishing layers under the `SentryNodeServerlessSDK` name and instead use the version suffix even for the next major.
This will not break the docs, but will break the product as explained in https://github.com/getsentry/sentry/issues/82646. I think we can completely remove that check once we are ready to ship v9 but need to investigate further, otherwise we follow the approach outlined in that issue.
=> feat(aws): Rename AWS lambda layer name to `SentryNodeServerlessSDKv9`

packages/core/src/client.ts
From https://github.com/getsentry/sentry-javascript/pull/14800
I noticed I totally forgot to migrate the jsdoc comments from the types to the class, oops!
=> ref(core): Re-add forgotten jsdocs for client

docs/migration/v8-to-v9.md, packages/core/src/tracing/trace.ts, packages/core/src/types-hoist/startSpanOptions.ts, packages/core/test/lib/tracing/trace.test.ts, packages/opentelemetry/test/trace.test.ts
This PR fixes unexpected behaviour that would emerge when starting multiple spans in sequence with `startSpan` when passing on the same scope. Prior to this change, the second span would be started as the child span of the first one, because the span set active on the custom scope was not re-set to the parent span of the first span. The reason is that we didn't clean up or restore the previously active span because the custom scope is not forked in contrast to the current scope. 
In very niche scenarios, this could furthermore lead to only the first span being sent and subsequent spans being discarded because they were being incorrectly considered a child span. Examples for this are the Sentry and CodeCov bundler plugins where we solely rely on `@sentry/core` and a custom client setup. In …
=> fix(core): Fork scope if custom scope is passed to `startSpan`

dev-packages/e2e-tests/test-applications/node-express/package.json, dev-packages/e2e-tests/test-applications/node-express/tsconfig.json
It seems that `@types/qs` v 6.9.18 which was just released breaks this somehow...
Noticed here: https://github.com/getsentry/sentry-javascript/pull/14998
=> test(e2e): Fix node-express test transitive dependency

dev-packages/e2e-tests/test-applications/node-express/package.json, dev-packages/e2e-tests/test-applications/node-express/tsconfig.json
It seems that `@types/qs` v 6.9.18 which was just released breaks this somehow...
Backport of https://github.com/getsentry/sentry-javascript/pull/15001
=> test(v8/e2e): Fix node-express test transitive dependency

dev-packages/node-integration-tests/suites/client-reports/drop-reasons/before-send/test.ts, dev-packages/node-integration-tests/suites/client-reports/drop-reasons/event-processors/test.ts, dev-packages/node-integration-tests/suites/client-reports/periodic-send/test.ts, dev-packages/node-integration-tests/suites/tracing/requests/http-unsampled/test.ts, dev-packages/node-integration-tests/utils/runner.ts
They are now ignored by default, unless we specifically want to test them.
Noticed e.g. here https://github.com/getsentry/sentry-javascript/actions/runs/12767810178/job/35587298600?pr=14999 that this can be flaky now.
=> test(node): Ensure client reports do not make tests flaky

docs/migration/v8-to-v9.md, packages/core/src/client.ts, packages/core/src/transports/base.ts, packages/core/test/lib/client.test.ts, packages/core/test/lib/transports/base.test.ts, packages/replay-internal/src/util/sendReplayRequest.ts
The event was no longer used for some time, instead you can (optionally) pass a count of dropped events as third argument. This has been around since v7, so we can finally clean this up here, which should also save some bytes.
This was not really deprecated before, but is also more an intimate API so I do not expect this to affect users too much. Also, deprecating arguments like this does not really work well with eslint anyhow, so even if we would deprecate it it is unlikely users would find out anyhow.
=> feat(core)!: Stop accepting `event` as argument for `recordDroppedEvent`

packages/solidstart/src/vite/sourceMaps.ts, packages/sveltekit/src/vite/sourceMaps.ts, packages/sveltekit/test/vite/sentrySvelteKitPlugins.test.ts, packages/sveltekit/test/vite/sourceMaps.test.ts
Enables `hidden` source maps if source maps are unset. In case they are explicitly disabled or enabled the setting is kept as is.
Still need to figure out how to set `filesToDeleteAfterUpload` as this setting needs to be passed when "calling" the sentry Vite plugin. However, `filesToDeleteAfterUpload` is dependent on the Vite options and we only have access to the Vite options when creating the custom plugin.
I thought about moving this parts of this logic to the `sentryVitePlugin` in general.
closes https://github.com/getsentry/sentry-javascript/issues/14885
=> feat(sveltekit): Respect user-provided source map generation settings

dev-packages/rollup-utils/npmHelpers.mjs, packages/react/rollup.npm.config.mjs, packages/react/test/sdk.test.ts, packages/remix/test/index.client.test.ts, packages/remix/test/index.server.test.ts
Ref: https://github.com/getsentry/sentry-javascript/issues/3105
By having the `__esModule` property in files where we don't have default exports we may trick tooling into thinking that there would be a default export. The probability of that happening nowadays is pretty low, but since `__esModule` is a non-standard property we should limit it to the minimum.
=> feat: Only emit `__esModule` properties in CJS modules when there is a default export

packages/node/src/sdk/index.ts
Noticed that we had this check which is redundant since we changed the `hasTracingEnabled` behavior.
=> ref(node): Streamline check for adding performance integrations

packages/gatsby/gatsby-node.js, packages/gatsby/test/gatsby-node.test.ts
closes https://github.com/getsentry/sentry-javascript/issues/14993
Generates source maps and deletes them after uploading them to Sentry per default.
Scenarios:
1. users set `config.devtool` to generate source maps -> keep `config.devtool` (a.k.a. source map) setting
2. users set `config.devtool` to something different that "source-map" or "hidden-source-map"
3. `config.devtool` is not defined
--> In case 3 we are automatically setting `filesToDeleteafterUpload`
But `deleteFilesAfterUpload: true` overwrites the behavior and will always delete the source maps. Also in case 1 and 2.
=> feat(gatsby): Preserve user-provided source map settings

dev-packages/e2e-tests/test-applications/tanstack-router/package.json, docs/migration/v8-to-v9.md, packages/react/src/tanstackrouter.ts
Ref https://github.com/getsentry/sentry-javascript/issues/14263
=> feat(react)!: Raise minimum supported TanStack Router version to `1.63.0`

docs/migration/v8-to-v9.md, packages/ember/package.json
Ref https://github.com/getsentry/sentry-javascript/issues/14263
=> feat(ember)!: Officially drop support for ember `<=3.x`

packages/core/src/tracing/trace.ts, packages/core/test/lib/tracing/trace.test.ts
This PR follows up on #14900 and analogously forks an optionally passed custom `scope` to ensure the active span is only active inside the callback.
=> fix(core): Fork scope if custom scope is passed to `startSpanManual`

dev-packages/browser-integration-tests/suites/transport/multiplexed/init.js, dev-packages/browser-integration-tests/suites/transport/multiplexed/subject.js, dev-packages/browser-integration-tests/suites/transport/multiplexed/test.ts, dev-packages/browser-integration-tests/utils/generatePlugin.ts, packages/browser/rollup.bundle.config.mjs, packages/browser/src/pluggable-exports-bundle/index.multiplexedtransport.ts
This PR adds a pluggable CDN bundle for `makeMultiplexedTransport`, an API we export from `@sentry/browser` but not from the browser SDK CDN bundles. After discussing #15041, we settled on avoiding to add the export to the bundle directly, as it would unnecessarily increase bundle size for the majority of our user base. 
However, we'll enable using the multiplexed transport in a CDN bundle setup by publishing a pluggable addon bundle for this API that users can add just like our pluggable integration CDN bundles. 
Will open a PR for docs in a bit
closes #15041 
supersedes #14925
=> feat(browser): Add `multiplexedtransport.js` CDN bundle

packages/aws-serverless/src/sdk.ts, packages/aws-serverless/test/sdk.test.ts, packages/core/src/scope.ts
Came across this by chance: Updating `event.transaction` in an event processor without checking for the type also always overwrites the root span name. To fix this, this PR calls `scope.updateTransactionName` which updates the error location "transaction" name on the scope. This is only applied to error events during event processing, so the intention is clearer than adding an event processor. 
This was mentioned in https://github.com/getsentry/sentry-javascript/issues/13391 but admittedly I must have misread the issue because I'm 99% sure the event processor was unintended behaviour from our end.
=> fix(aws-lambda): Avoid overwriting root span name

dev-packages/browser-integration-tests/suites/tracing/request/fetch/test.ts, dev-packages/browser-integration-tests/suites/tracing/request/init.js
Backport of https://github.com/getsentry/sentry-javascript/pull/15050
=> test(v8/browser): Unflake browser request test

dev-packages/e2e-tests/test-applications/nextjs-13/pages/fetch.tsx, dev-packages/e2e-tests/test-applications/nextjs-13/tests/client/fetch.test.ts, dev-packages/e2e-tests/test-applications/nextjs-14/app/request-instrumentation/page.tsx, dev-packages/e2e-tests/test-applications/nextjs-14/playwright.config.ts, dev-packages/e2e-tests/test-applications/nextjs-14/tests/request-instrumentation.test.ts, dev-packages/e2e-tests/test-applications/nextjs-15/app/pageload-tracing/page.tsx, dev-packages/e2e-tests/test-applications/nextjs-15/app/suspense-error/page.tsx, dev-packages/e2e-tests/test-applications/nextjs-app-dir/app/server-action/page.tsx, dev-packages/e2e-tests/test-applications/nextjs-app-dir/pages/api/request-instrumentation.ts, dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/request-instrumentation.test.ts
=> ci(e2e-test): Switch to `https://example.com` from http equivalent for Next.js e2e tests

packages/aws-serverless/src/sdk.ts, packages/aws-serverless/test/sdk.test.ts, packages/core/src/scope.ts
=> fix(v8/aws-lambda): Avoid overwriting root span name 

dev-packages/browser-integration-tests/suites/transport/multiplexed/init.js, dev-packages/browser-integration-tests/suites/transport/multiplexed/subject.js, dev-packages/browser-integration-tests/suites/transport/multiplexed/test.ts, dev-packages/browser-integration-tests/utils/generatePlugin.ts, packages/browser/rollup.bundle.config.mjs, packages/browser/src/pluggable-exports-bundle/index.multiplexedtransport.ts
v8 backport of #15043 
ref #15041
=> feat(v8/browser): Add `multiplexedtransport.js` CDN bundle (#15043)

dev-packages/node-integration-tests/suites/tracing/httpIntegration/server-ignoreOutgoingRequests.js, dev-packages/node-integration-tests/suites/tracing/httpIntegration/test.ts
Analogously to https://github.com/getsentry/sentry-javascript/pull/15052 this PR switches to the https version of example.com since the http version seems to have become unstable in the last couple of days. These tests failed a lot in CI recently.
=> test(node): Use https version of example.com in Node integration tests

dev-packages/e2e-tests/test-applications/create-remix-app-express-vite-dev/package.json, dev-packages/e2e-tests/test-applications/solid-solidrouter/package.json, dev-packages/e2e-tests/test-applications/solid/package.json, dev-packages/e2e-tests/test-applications/solidstart-spa/package.json, dev-packages/e2e-tests/test-applications/solidstart/package.json, dev-packages/e2e-tests/test-applications/svelte-5/package.json, dev-packages/e2e-tests/test-applications/sveltekit-2-svelte-5/package.json, dev-packages/e2e-tests/test-applications/sveltekit-2-twp/package.json, dev-packages/e2e-tests/test-applications/sveltekit-2/package.json, dev-packages/e2e-tests/test-applications/tanstack-router/package.json, dev-packages/e2e-tests/test-applications/vue-3/package.json, package.json, packages/angular/vitest.config.ts, packages/astro/package.json, packages/remix/package.json, packages/sveltekit/package.json, yarn.lock
Backport of #14971 to v8. This is a prerequisite for an eventual backport of #14968, which will itself will make applying/backporting #14967 much easier.
I ran `yarn build` and `yarn test` locally. Building succeeded, and all but 2 test suites passed. The two that failed also failed for me on `v8` (without any of my changes), so I'm assuming it's something to do with my environment.
=> chore(v8/deps): Upgrade to Vitest 2.1.8 and Vite 5.4.11

dev-packages/browser-integration-tests/suites/integrations/moduleMetadata/appliesMetadata/init.js, dev-packages/browser-integration-tests/suites/integrations/moduleMetadata/appliesMetadata/test.ts, dev-packages/browser-integration-tests/suites/integrations/moduleMetadata/appliesMetadataWithRewriteFrames/init.js, dev-packages/browser-integration-tests/suites/integrations/moduleMetadata/appliesMetadataWithRewriteFrames/test.ts, dev-packages/browser-integration-tests/suites/tracing/request/fetch/test.ts
Just noticed that these tests were skipped for CDN bundles. Since we publish moduleMetadata CDN bundles since #13822, we can also enable these tests.
=> test(browser): Test `moduleMetadataIntegration` in CDN bundle integration tests

docs/migration/v8-to-v9.md, packages/astro/test/client/sdk.test.ts, packages/cloudflare/test/integrations/fetch.test.ts, packages/core/src/tracing/sampling.ts, packages/core/src/types-hoist/options.ts, packages/core/src/utils/hasTracingEnabled.ts, packages/core/test/lib/feedback.test.ts, packages/core/test/lib/tracing/errors.test.ts, packages/core/test/lib/tracing/trace.test.ts, packages/core/test/lib/utils/hasTracingEnabled.test.ts, packages/feedback/src/core/sendFeedback.test.ts, packages/node/test/integration/breadcrumbs.test.ts, packages/node/test/integration/scope.test.ts, packages/node/test/integration/transactions.test.ts, packages/node/test/sdk/api.test.ts, packages/node/test/sdk/init.test.ts, packages/opentelemetry/test/integration/scope.test.ts, packages/svelte/test/performance.test.ts, packages/sveltekit/test/client/fetch.test.ts, packages/sveltekit/test/client/sdk.test.ts, packages/vercel-edge/test/wintercg-fetch.test.ts
Ref: https://github.com/getsentry/sentry-javascript/issues/14366
Ref: https://github.com/getsentry/team-sdks/issues/84
=> feat!: Remove `enableTracing`

.github/workflows/build.yml, packages/remix/src/index.client.tsx, packages/remix/src/index.types.ts
- Updates the label for remix integration tests.
- Updates client types for captureRemixServerException params (forgot to remove these as they serve no real purpose)
Follow up to https://github.com/getsentry/sentry-javascript/pull/14988
=> ci: Update labels for remix integration tests

packages/core/src/client.ts
In the Electron SDK, we have to manually set sessions as crashed when native crashes are encountered:
https://github.com/getsentry/sentry-electron/blob/dabd6daf0c19c2a6f224d1e721eb5d58c3cf61ac/src/main/integrations/sentry-minidump/index.ts#L175
This has the downside that if you return `null` in `beforeSend`, the event still impacts the release health crash rate.
I found that this was required because `_updateSessionFromEvent` in `@sentry/core` does not consider the Electron native events as a crash or an error because there are no exceptions in the event.
This PR ensures that any event with a `fatal` level is considered a crash.
=> fix(core): `fatal` events should set session as crashed

packages/core/src/baseclient.ts
=> fix(v8/core): `fatal` events should set session as crashed 

packages/deno/README.md
=> doc(deno): Remove `deno.land` link

packages/nextjs/src/config/types.ts, packages/nextjs/src/config/webpackPluginOptions.ts, packages/nextjs/test/config/webpack/webpackPluginOptions.test.ts
=> feat(nextjs): Directly forward `sourcemaps.disable` to webpack plugin

packages/core/src/types-hoist/feedback/config.ts, packages/feedback/src/screenshot/components/PenIcon.tsx, packages/feedback/src/screenshot/components/ScreenshotEditor.tsx, packages/feedback/src/screenshot/components/ScreenshotInput.css.ts
Adds a proper pen tool button. The icon for the button is from the hackweek project
Unselected:
Selected:
Relates to https://github.com/getsentry/sentry-javascript/issues/15064
=> feat(user feedback): Create pen tool button for uf annotations

packages/aws-serverless/src/sdk.ts, packages/core/src/index.ts, packages/nextjs/src/config/webpack.ts, packages/nextjs/src/config/withSentryConfig.ts
Ref: https://github.com/getsentry/sentry-javascript/issues/14299
Updates comments to clarify what needs to be done in v9 and what doesn't.
=> meta: Postpone non-breaking TODOs

packages/deno/README.md
Resolves https://github.com/getsentry/sentry-javascript/issues/15088
Deprecates the Deno SDK as it is published on deno.land and instead recommends importing from the npm registry.
=> feat(deno): Deprecate Deno SDK as published on deno.land

packages/core/src/integrations/requestdata.ts
As raised in https://github.com/getsentry/sentry-javascript/issues/5347#issuecomment-2606598918 we should only fall back to using `sendDefaultPii` so that users can do `include.ip: false` and `sendDefaultPii: true`, to have the sendDefaultPii behavior but not collect IPs from the integration.
=> fix(core): Only fall back to `sendDefaultPii` for IP collection in `requestDataIntegration`

packages/browser/src/tracing/browserTracingIntegration.ts
Extracted this out of https://github.com/getsentry/sentry-javascript/pull/14955
Instead of registering a general hook & filtering there, we can just use the `beforeSpanEnd` hook that we already have/use to do this instead.
=> ref(browser): Improve setting of propagation scope for navigation spans

docs/migration/v8-to-v9.md, packages/sveltekit/src/server/handle.ts, packages/sveltekit/test/server/handle.test.ts
This PR removes the `fetchProxyScriptNonce` and in turn simplifies our `transformPageChunk` callback a bit. 
In a follow-up, I'll address https://github.com/getsentry/sentry-javascript/issues/15007
=> feat(sveltekit)!: Remove `fetchProxyScriptNonce` option

packages/sveltekit/src/server/handle.ts
This PR deprecates the `fetchProxyScriptNonce` option which we'll remove in v9 due to security concerns.
The replacements are outlined in the JSDoc.
Note: We cannot completely remove the script injection because it only became completely unnecessary with SvelteKit 2.16.0 which is too new that we could drop support for everything below it in v9. Maybe in v10 :)
For v9, I'll explore if we can dynamically decide to inject the script based on the sveltekit version.
=> feat(v8/sveltekit): Deprecate `fetchProxyScriptNonce` option 

packages/node/src/integrations/tracing/prisma.ts
Ref #14793
Backport of https://github.com/getsentry/sentry-javascript/pull/15127
Adds a compatibility layer to the prismaIntegration via the prismaInstrumentation option that can be used to pass a prisma instrumentation instance of older Prisma versions.
=> feat(node/v8): Add `prismaInstrumentation` option to Prisma integration as escape hatch for all Prisma versions

docs/migration/v8-to-v9.md, packages/node/src/integrations/tracing/prisma.ts
Ref https://github.com/getsentry/sentry-javascript/issues/14793
Adds a compatibility layer to the `prismaIntegration` via the `prismaInstrumentation` option that can be used to pass a prisma instrumentation instance of older Prisma versions.
=> feat(node): Add `prismaInstrumentation` option to Prisma integration as escape hatch for all Prisma versions

CHANGELOG.md, packages/node/src/integrations/tracing/prisma.ts
Ignore the branch name: this is version **8.51.0**
WIP, still waiting on some PRs
- #15011 
- #14967
needs another rebase after the PRs were merged
=> meta: Update Changelog for 8.51.0

packages/replay-internal/src/session/index.ts, packages/vercel-edge/src/transports/types.ts
I think [remove-unused](https://removeunused.com/) found more unused files, this time in `replay-internal` and `vercel-edge`. `lint` and `test` commands run fine. All build tasks seem to be working although I cannot get `@sentry/profiling-node` to ever build locally due to some fun `gyp` stuff
=> chore(repo): Removing unused files

dev-packages/node-integration-tests/suites/anr/basic-session.js, dev-packages/node-integration-tests/suites/anr/test.ts, packages/node/src/integrations/anr/worker.ts
=> fix(node): Missing `release` from ANR sessions

packages/nextjs/src/common/captureRequestError.ts
Ensure that server component errors reliably flush on vercel.
=> fix(nextjs): Flush with `waitUntil` in `captureRequestError`

CHANGELOG.md, docs/migration/v8-to-v9.md, packages/solidstart/src/config/withSentry.ts, packages/solidstart/src/index.server.ts, packages/solidstart/src/index.types.ts, packages/solidstart/src/vite/index.ts
Since the default way of setting up the SDK and passing the Sentry options is by wrapping the SolidStart config with `withSentry`, the previous method of using the `sentrySolidStartVite` plugin is no longer supported.
=> feat(solidstart)!: No longer export `sentrySolidStartVite`

packages/core/package.json, packages/core/src/integrations/zoderrors.ts, packages/core/test/lib/integrations/zoderrrors.test.ts, yarn.lock
- Include full key path rather than the top level key in title
- Improve message for validation issues with no path
- Add option to include extended issue information as an attachment
I tried using this integration, but found the error format in Sentry to be lacking.
I added tests to demonstrate how this will format issues.
---
=> feat(core): Improve error formatting in ZodErrors integration

docs/pr-reviews.md
Link to the Sentry develop docs for explaining the LOGAF scale.
#skip-changelog
=> Reference LOGAF Scale from develop docs

packages/core/src/scope.ts, packages/core/src/types-hoist/clientreport.ts, packages/core/src/types-hoist/datacategory.ts, packages/core/test/lib/baseclient.test.ts
ref https://github.com/getsentry/team-sdks/issues/116
backport of https://github.com/getsentry/sentry-javascript/pull/15082
=> feat(v8/core): Add client outcomes for breadcrumbs buffer

packages/bun/src/integrations/bunserver.ts, packages/bun/test/integrations/bunserver.test.ts, packages/bun/test/sdk.test.ts
If `#reload` is called on an instance of `Bun.serve`, the Sentry intrumentation doesn't surive. This is because the Bun instrumentation works by using `Proxy` on the call to `Bun.serve`, which isn't called for a reload.
We can't wrap the serve created by calling `Bun.serve` with a `Proxy` as Bun seems to do some internal checks using `instanceof` which break if the instance is now reporting itself as a `ProxyObject`.
This fixes #15144.
=> fix(bun): Ensure instrumentation of `Bun.serve` survives a server reload

CHANGELOG.md, packages/core/package.json, packages/core/src/integrations/zoderrors.ts, packages/core/test/lib/integrations/zoderrrors.test.ts, yarn.lock
- Include full key path rather than the top level key in title
- Improve message for validation issues with no path
- Add option to include extended issue information as an attachment
backport of https://github.com/getsentry/sentry-javascript/pull/15111
=> feat(v8/core): Improve error formatting in ZodErrors integration

packages/core/src/utils-hoist/node.ts, packages/nextjs/src/config/webpack.ts, packages/remix/src/utils/instrumentServer.ts
- [-] If you've added code that should be tested, please add tests.
Certainly! Here’s a more elegantly phrased version of your content:
The `loadModule` function currently utilizes `require` to load modules starting from the `@sentry/core` directory. This approach is incompatible with package managers like pnpm, which do not hoist dependencies. Consequently, when another module, such as @sentry/nextjs, invokes `loadModule`, it fails to locate its own dependencies because the search initiates within the @sentry/core tree.
If @sentry/nextjs calls `loadModule('@sentry/webpack-plugin')`, the function attempts to locate @sentry/webpack-plugin within the dependencies of @sentry/core. This results in the module not being found if `@sentry/webpack-plugin` is not a dependency of `@sentry/core`. …
=> fix(core): Pass `module` into `loadModule`

dev-packages/e2e-tests/test-applications/react-send-to-sentry/tests/send-to-sentry.test.ts
Relax the assertion for the replay recording data test so that we allow arbitrary order but still assert on the exact amount and contents of the received recording items.
closes #15167
=> test(e2e): Unflake replay recording data optional e2e test

packages/bun/src/integrations/bunserver.ts, packages/bun/test/integrations/bunserver.test.ts, packages/bun/test/sdk.test.ts
Backport of https://github.com/getsentry/sentry-javascript/pull/15148
=> fix(v8/bun): Ensure instrumentation of `Bun.serve` survives a server reload

dev-packages/e2e-tests/test-applications/nextjs-14/app/request-instrumentation/page.tsx, dev-packages/e2e-tests/test-applications/nextjs-14/tests/request-instrumentation.test.ts
example.com still seems flaky, let's avoid making requests to it
=> test(e2e/nextjs): Avoid making request to example.com 

dev-packages/e2e-tests/test-applications/nextjs-14/app/request-instrumentation/page.tsx, dev-packages/e2e-tests/test-applications/nextjs-14/tests/request-instrumentation.test.ts
=> test(v8/e2e): Avoid making request to example.com in nextjs e2e test

CHANGELOG.md, packages/core/src/utils-hoist/node.ts, packages/nextjs/src/config/webpack.ts, packages/remix/src/utils/instrumentServer.ts
=> fix(v8/core): Pass `module` into `loadModule` (#15139)

packages/nuxt/src/common/types.ts, packages/nuxt/src/vite/sourceMaps.ts, packages/nuxt/test/vite/sourceMaps.test.ts
The build error in question is for self-hosted sentry instances, where a config URL is pointing to sentry.io and the token was generated on our self-hosted instance with a different URL
=> feat(nuxt): Add `url` to `SourcemapsUploadOptions`

.github/workflows/build.yml
It _seems_ we've got way more flakes since 18.20.6 was released, let's see if this fixes this possibly...
=> ci: Pin node-integration-test version to `18.20.5`

packages/core/src/client.ts, packages/core/src/utils-hoist/error.ts
We did some funky stuff in there that does not seem necessary and can even lead to issues.
Fixes https://github.com/getsentry/sentry-javascript/issues/15214.
There was this comment in there:
```
// This sets the prototype to be `Error`, not `SentryError`. It's unclear why we do this, but commenting this line
// out causes various (seemingly totally unrelated) playwright tests consistently time out.
```
but it seems all tests are passing, so should be good I suppose...
=> ref(core): Don't set `this.name` to `new.target.prototype.constructor.name` on `SentryError` class

dev-packages/browser-integration-tests/suites/tracing/metrics/pageload-resource-spans/test.ts, packages/browser-utils/src/index.ts, packages/browser-utils/src/metrics/browserMetrics.ts, packages/browser-utils/src/metrics/utils.ts, packages/browser-utils/test/browser/browserMetrics.test.ts, packages/browser-utils/test/browser/utils.test.ts, packages/browser/src/tracing/request.ts, packages/browser/test/tracing/request.test.ts
Resolves #12395 
- Relocated `extractNetworkProtocol` util and its unit test to `browser-utils`.
- Modified `browserMetrics` test to assert the new metadata.
---
=> ref(browser): Add protocol attributes to resource spans

.github/workflows/auto-release.yml, .github/workflows/build.yml, .github/workflows/canary.yml, .github/workflows/clear-cache.yml, .github/workflows/enforce-license-compliance.yml, .github/workflows/external-contributors.yml, .github/workflows/flaky-test-detector.yml, .github/workflows/gitflow-sync-develop.yml, .github/workflows/release-comment-issues.yml, .github/workflows/release-size-info.yml, .github/workflows/release.yml
Bumping our images to ubuntu-22.04, except for the `ubuntu-20.04-large-js` ones, as I guess those ones are custom - should look into those too then eventually.
In a follow up, we can try to bump to 24.04, possibly, but I figured we can do this piece by piece.
=> ci: Update runners to `ubuntu-22.04`

dev-packages/e2e-tests/test-applications/nextjs-app-dir/assert-build.ts, packages/nextjs/src/config/webpack.ts
This also needs to go into v8, I guess!
=> test(v8): Fix nextjs build warning

packages/core/src/baseclient.ts, packages/core/src/utils-hoist/error.ts
Backport, fixes https://github.com/getsentry/sentry-javascript/issues/15214
=> ref(v8/core): Don't set `this.name` to `new.target.prototype.constructor.name`

CHANGELOG.md, dev-packages/browser-integration-tests/suites/tracing/metrics/pageload-resource-spans/test.ts, packages/browser-utils/src/index.ts, packages/browser-utils/src/metrics/browserMetrics.ts, packages/browser-utils/src/metrics/utils.ts, packages/browser-utils/test/browser/browserMetrics.test.ts, packages/browser-utils/test/browser/utils.test.ts, packages/browser/src/tracing/request.ts, packages/browser/test/tracing/request.test.ts
=> ref(v8/browser): Add protocol attributes to resource spans

packages/react/src/tanstackrouter.ts
fixes #15234
Due to a big bug in TanStack Router getting fixed, this needs an optional chain to not die.
=> fix(react): From location can be undefined in Tanstack Router Instrumentation

packages/nuxt/src/common/types.ts, packages/nuxt/src/vite/sourceMaps.ts, packages/nuxt/test/vite/sourceMaps.test.ts
=> feat(v8/nuxt): Add `url` to `SourcemapsUploadOptions`

packages/react/src/errorboundary.tsx, packages/react/src/hoist-non-react-statics.ts, packages/react/src/profiler.tsx, packages/react/src/reactrouter.tsx, packages/react/src/reactrouterv6-compat-utils.tsx
This came up during upgrading Sentry to our v9 alpha (https://github.com/getsentry/sentry/pull/84258).
Currently our import emits this line in cjs:
`hoistNonReactStatics.default(Wrapped, WrappedComponent);`
Which results in a runtime error (at least in jest runners).
With this change I updated the import to use `import * as hoistNonReactStaticsImport from 'hoist-non-react-statics';` which solves the issue but breaks our ts-check. For this I moved the import into a fallback util function which satisfies ts.
=> fix(react): Import default for hoistNonReactStatics

dev-packages/node-integration-tests/suites/tracing/requests/http-no-tracing-no-spans/scenario.ts, dev-packages/node-integration-tests/suites/tracing/requests/http-no-tracing-no-spans/test.ts, packages/core/src/utils-hoist/baggage.ts, packages/core/src/utils-hoist/index.ts, packages/node/src/integrations/http/SentryHttpInstrumentation.ts
Related to https://github.com/getsentry/sentry-javascript/pull/15231, I noticed that we today would not propagate traces in outgoing http requests if:
1. The user configures `httpIntegration({ spans: false })`
2. ..._or_ the user has a custom OTEL setup
3. _and_ the user does not add their own `HttpInstrumentation`
Admittedly and edge case. More importantly, though, by actually adding distributed tracing information here, we are unblocked from potentially stopping to ship the http-instrumentation to users that do not need spans (and/or have a custom otel setup).
=> fix(node): Ensure `httpIntegration` propagates traces

packages/nuxt/src/common/types.ts, packages/nuxt/src/vite/sourceMaps.ts
This pull request includes changes to enhance the configuration options for managing Sentry source maps in a Nuxt.js project. The most important changes include adding new options to suppress logs, handle errors during release creation, and manage Sentry releases.
Enhancements to Sentry source maps configuration:
* [`packages/nuxt/src/common/types.ts`](diffhunk://#diff-199725da81bbdbb2e85f3dfe2b1a2bf453b4c9755059e5050815d7fcde2f59a5R11-R41): Added `silent`, `errorHandler`, and `release` options to the `SourceMapsOptions` type to provide more control over logging, error handling, and release management.
* [`packages/nuxt/src/vite/sourceMaps.ts`](diffhunk://#diff-d511a0577f152ed6476e519722483c904cd2878586fdcd27f71c5587036bee37R96-R98): Updated the `getPluginOptions` function to include the …
=> feat(nuxt): add `silent`, `errorHandler`, `release` to `SourceMapsOptions`

packages/svelte/src/config.ts, packages/svelte/src/constants.ts, packages/svelte/src/performance.ts, packages/svelte/test/config.test.ts, packages/svelte/test/performance.test.ts
This PR adds a guard the Svelte SDK's component update tracking feature to catch an error thrown by Svelte 5 in Runes mode. In Runes mode, components must not call the old `beforeUpdate` or `afterUpdate` lifecycle hooks. Usually, when users do this in their code, the Svelte compiler would throw a build error. However, since our `withSentryConfig` wrapper adds a preprocessor that sneaks such a function call in, the compiler doesn't notice this (at least not in the webpack loader as reported in #https://github.com/getsentry/sentry-javascript/issues/15259.
This PR also cleans up the preprocessor adding logic which was overcomplicated and a leftover from when we added more than one preprocessor to users' svelte configs. In general, I cleaned up some unnecessary stuff and terminology. 
I'll …
=> fix(v8/svelte): Guard component tracking `beforeUpdate` call

packages/sveltekit/src/server/handle.ts, packages/sveltekit/test/server/handle.test.ts
Removes a no longer necessary fallback check that we only needed in SvelteKit 1.26.0 or older. For Kit 2.x, we can rely on the `event.isSubRequest` flag to identify sub vs. actual requests in our request handler. 
fixes #15244
=> ref(sveltekit): Clean up sub-request check

packages/feedback/src/screenshot/components/CropIcon.tsx, packages/feedback/src/screenshot/components/PenIcon.tsx, packages/feedback/src/screenshot/components/ScreenshotEditor.tsx, packages/feedback/src/screenshot/components/ScreenshotInput.css.ts
- adds a toolbar for cropping and annotations
- changes from inline styles to multiple class names in BEM format
With annotation option:
Without annotation option (to confirm that it looks the same as before):
Closes https://github.com/getsentry/sentry-javascript/issues/15252
=> feat(user feedback): Adds toolbar for cropping and annotating

packages/nuxt/src/runtime/plugins/sentry.server.ts
The debugging ability for Azure Functions when using Azure Static Web Apps is very limited. But as I could see some Sentry-related logs I **think** Sentry is generally initialized.
However, server-related logs don't show up in Sentry. This is **probably** because the Azure Function finishes before the error can be sent to Sentry.
By adding the Azure environment variable to check whether we should flush with a timeout, this should possibly fix the issue.
Logs in Application Insights:
=> fix(nuxt): Detect Azure Function runtime for flushing with timeout

packages/core/src/integration.ts, packages/core/test/lib/integration.test.ts
This integration is removed in v9 so we do not need this code anymore. Noticed this by chance 😅
=> ref(core): Remove unused special handling for `Debug` integration

docs/migration/v8-to-v9.md
Gives the migration guide a pass.
General things I did:
- Remove duplicate information
- Remove deprecations section
- Make language more instructive and less fluffy
- Removed information that was redundant
- Make sure it is more mentally parseable/scannable by putting actual APIs in the first few words of each sentence.
=> docs: Clean up migration guide for v9

packages/aws-serverless/src/sdk.ts, packages/aws-serverless/test/sdk.test.ts, packages/google-cloud-serverless/src/sdk.ts, packages/vue/src/sdk.ts
This was still set differently in a few places. This PR unifies this so we do this consistently.
For aws-serverless, we also still hard-coded the `AWSLambda` integration name, but this is already reflected via the `Aws` and `AwsLambda` integrations anyhow.
=> ref: Use `applySdkMetadata` everywhere

dev-packages/e2e-tests/test-applications/svelte-5/svelte.config.js
Just came across this by chance. `trackUpdates: false` is already default behaviour since #15265. We should rather test against this in the e2e test app than explicitly opting out of update tracking.
=> chore(svelte): Remove redundant component tracking config in e2e test

packages/svelte/src/sdk.ts, packages/svelte/test/sdk.test.ts
When we first created the Svelte SDK, we wanted to gauge how often it is used in a SvelteKit application. Therefore we added some SvelteKit detection logic to annotate events coming from the Svelte SDK. Since we have a SvelteKit SDK now, we don't need to track this anymore. Saves a few bytes, too.
This PR therefore removes the detection and event processing logic
=> ref(svelte): Remove SvelteKit detection

dev-packages/browser-integration-tests/suites/manual-client/skip-init-browser-extension/test.ts, dev-packages/browser-integration-tests/suites/manual-client/skip-init-chrome-extension/test.ts, dev-packages/browser-integration-tests/utils/helpers.ts, packages/browser/src/sdk.ts
I think it is fair to exclude this here, saving a few bytes...?
=> ref(browser): Skip browser extension warning in non-debug builds

packages/node/src/integrations/http/SentryHttpInstrumentation.ts
https://github.com/getsentry/sentry-javascript/pull/15233 introduced a change where we are actually using the return value of the vendored `getRequestInfo()` function to pass along to the original `node:http(s)` API calls.
We missed that OTEL does backfilling of certain fields (protocol and port) for HTTPS requests which we also need to do if we are actually passing along `getRequestInfo()`. It seems like node's default behavior when not providing a protocol/port as options object and using the `https` module is just to assume `https:` and `443`.
=> fix(node): Set the correct fallback URL fields for outgoing https requests if they are not defined

package.json, packages/browser/src/eventbuilder.ts
This PR bumps our volta field to use Node 20, which will be required for building upcoming SDK versions (Nest@11, RR@7)
=> chore: Bump volta to node 20

CHANGELOG.md, packages/nextjs/src/common/devErrorSymbolicationEventProcessor.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/15308
=> fix(nextjs): Use batched devserver symbolication endpoint

dev-packages/node-integration-tests/suites/tracing/httpIntegration/server-ignoreOutgoingRequests.js, dev-packages/node-integration-tests/suites/tracing/httpIntegration/test.ts
Refactors two flaky Node integration tests that made requests to example.com. Now we just spin up our own test server instead.
=> test(node): Remove last example.com requests in node integration tests

packages/nuxt/src/common/types.ts, packages/nuxt/src/module.ts
closes https://github.com/getsentry/sentry-javascript/issues/14935
=> feat(nuxt): Add `enabled` to disable Sentry module

.craft.yml
With the upcoming release of Sentry v9, we will stop publishing the AWS Lambda layer under `SentryNodeServerlessSDK` and instead use a version suffixed naming scheme.
We now have:
- `SentryNodeServerlessSDKv7`
- `SentryNodeServerlessSDKv8`
- `SentryNodeServerlessSDKv9`
If you're expecting to get updates for your v8 layer, please switch over to `SentryNodeServerlessSDKv8` otherwise upgrade to `SentryNodeServerlessSDKv9`.
Closes: #14842
=> chore(ci/v8): Switch lambda layer name to `SentryNodeServerlessSDKv8`

.github/workflows/auto-release.yml, .github/workflows/release.yml
The release action is failing because of an engine field pinned to node 20 and the default installed version of node on our current ubuntu runner version is 18.
=> ci: Setup workspace node version in release actions

packages/astro/src/server/sdk.ts, packages/astro/test/server/sdk.test.ts
Makes sure that `vue` is not wrapped and users don't get the error `$haml has already been declared`
closes https://github.com/getsentry/sentry-javascript/issues/13982
=> fix(astro): Add vue to `registerEsmLoaderHooks`

packages/solidstart/src/config/addInstrumentation.ts, packages/solidstart/test/config/addInstrumentation.test.ts
Backport of https://github.com/getsentry/sentry-javascript/pull/15302
=> fix(v8/solidstart): Do not copy release-injection map file

.github/workflows/build.yml, jest/jest.config.js, package.json, packages/angular/vitest.config.ts, packages/replay-internal/vitest.config.ts, vite/vite.config.ts, yarn.lock
I noticed that not all of our tests were being tracked in codecov. This adds `jest-junit` reporter for our jest tests and configures vitest to use junit reporter (when `CI` env var is set).
This brings [the number of tests tracked](https://app.codecov.io/gh/getsentry/sentry-javascript/tests/feat-ci-jest-junit) from ~700 to 4.5k
=> feat(ci): Add junit reporters to jest/vitest, codecov test results

dev-packages/browser-integration-tests/suites/integrations/featureFlags/constants.ts, dev-packages/browser-integration-tests/suites/integrations/featureFlags/featureFlags/basic/test.ts, dev-packages/browser-integration-tests/suites/integrations/featureFlags/launchdarkly/basic/test.ts, dev-packages/browser-integration-tests/suites/integrations/featureFlags/openfeature/errorHook/test.ts, dev-packages/browser-integration-tests/suites/integrations/featureFlags/statsig/basic/test.ts, dev-packages/browser-integration-tests/suites/integrations/featureFlags/statsig/init.js, dev-packages/browser-integration-tests/suites/integrations/featureFlags/statsig/subject.js, dev-packages/browser-integration-tests/suites/integrations/featureFlags/statsig/template.html, dev-packages/browser-integration-tests/suites/integrations/featureFlags/statsig/withScope/test.ts, dev-packages/browser-integration-tests/suites/integrations/featureFlags/unleash/basic/test.ts, packages/browser/src/index.ts, packages/browser/src/integrations/featureFlags/statsig/index.ts, packages/browser/src/integrations/featureFlags/statsig/integration.ts, packages/browser/src/integrations/featureFlags/statsig/types.ts
New integration for tracking Statsig js-client flag evaluations, specifically the checkGate method which is used for boolean release flags.
Backports https://github.com/getsentry/sentry-javascript/pull/15319 to v8
=> feat(flags/v8): add Statsig browser integration

dev-packages/browser-integration-tests/suites/integrations/featureFlags/unleash/badSignature/init.js, dev-packages/browser-integration-tests/suites/integrations/featureFlags/unleash/init.js, packages/browser/src/integrations/featureFlags/unleash/integration.ts
Renaming this parameter to keep the name consistent with [statsigIntegration](https://github.com/getsentry/sentry-javascript/pull/15319). We can reuse this generic name for future FF integrations.
This integration is not in use for v9 so we're directly changing the options type. Plan for v8: we'll define the same options type but with `featureFlagsClientClass` (new) and `unleashClientClass` (old) both optional, annotating the latter with `@deprecated`.
=> ref(flags): rename unleash integration param

dev-packages/browser-integration-tests/suites/replay/autoFlushOnFeedback/init.js, dev-packages/browser-integration-tests/suites/replay/autoFlushOnFeedback/subject.js, dev-packages/browser-integration-tests/suites/replay/autoFlushOnFeedback/template.html, dev-packages/browser-integration-tests/suites/replay/autoFlushOnFeedback/test.ts, packages/core/src/client.ts, packages/core/src/types-hoist/feedback/sendFeedback.ts, packages/feedback/src/modal/integration.tsx, packages/replay-internal/src/replay.ts, packages/replay-internal/src/types/replay.ts, packages/replay-internal/src/util/addGlobalListeners.ts
This PR adds an experimental flag `autoFlushOnFeedback` to the replay options.
It aims to reduce replays that only contain the user interaction within the feedback modal, whereas the we rather want to inspect what happened prior to this.
Once enabled, replays are automatically flushed when:
- the feedback modal is opened
- feedback is captured manually through an api call
partly related to https://github.com/getsentry/sentry-javascript/issues/6908
=> feat(replay/feedback): Add experimental autoFlushOnFeedback option

.github/workflows/auto-release.yml, .github/workflows/build.yml, .github/workflows/canary.yml, .github/workflows/clear-cache.yml, .github/workflows/enforce-license-compliance.yml, .github/workflows/external-contributors.yml, .github/workflows/flaky-test-detector.yml, .github/workflows/gitflow-sync-develop.yml, .github/workflows/release-comment-issues.yml, .github/workflows/release-size-info.yml, .github/workflows/release.yml
#15219 was a bit eager. We cannot have different runners for normal jobs and our large runners as the browser binaries will be different.
We need to:
- add a large runner image that runs on 22.04
- bump all of the runner images to 22.04
=> ci: Downgrade runners to `ubuntu-20.04`

packages/angular/package.json, packages/astro/package.json, packages/browser/package.json, packages/bun/package.json, packages/core/package.json, packages/deno/package.json, packages/ember/package.json, packages/eslint-config-sdk/package.json, packages/eslint-plugin-sdk/package.json, packages/feedback/package.json, packages/gatsby/package.json, packages/nextjs/package.json, packages/node/package.json, packages/opentelemetry/package.json, packages/profiling-node/package.json, packages/react/package.json, packages/remix/package.json, packages/replay-canvas/package.json, packages/svelte/package.json, packages/sveltekit/package.json, packages/types/package.json, packages/typescript/package.json, packages/utils/package.json, packages/vercel-edge/package.json, packages/vue/package.json, packages/wasm/package.json
Tags all packages on the v8 branch with the `v8` tag on npm, except for utils which was removed in v9 and should therefore still receive the latest tag.
Resolves https://github.com/getsentry/sentry-javascript/issues/14938
=> ci(v8): Tag packages with v8

packages/sveltekit/src/server/handle.ts, packages/sveltekit/test/server/handle.test.ts
This PR attempts to fix an unreproducible bug reported in https://github.com/getsentry/sentry-javascript/issues/14583: It seems like our SDK calling `clone` on the `request` object passed to SvelteKit request handlers causes double read errors when the request body is consumed in user code. 
While I'm not sure about this, my best guess is that it has something to do with SvelteKit [creating a new request object](https://github.com/sveltejs/kit/blob/ca1d09f09ed123f72a98de031a34ec6db68fe915/packages/kit/src/exports/node/index.js#L123-L133) from the actual incoming request in a special way.
This PR removes the `clone()` call (tests would fail if it was still called) from our request handler. This is safe because our SDK does not consume the request body. Cloning here was a precautionary …
=> fix(sveltekit): Avoid request body double read errors

dev-packages/e2e-tests/test-applications/react-create-browser-router/src/index.tsx, dev-packages/e2e-tests/test-applications/react-create-browser-router/src/pages/Index.tsx, dev-packages/e2e-tests/test-applications/react-create-browser-router/src/pages/LazyLoadedInnerRoute.tsx, dev-packages/e2e-tests/test-applications/react-create-browser-router/src/pages/LazyLoadedUser.tsx, dev-packages/e2e-tests/test-applications/react-create-browser-router/tests/transactions.test.ts, packages/react/src/reactrouterv6-compat-utils.tsx, packages/react/src/types.ts
Backports #15039 to v8 branch
Potentially fixes as it also fixes cross-usage of `createBrowserRouter` and `useRoutes`: #15279
=> fix(react/v8): Support lazy-loaded routes and components

dev-packages/e2e-tests/test-applications/node-express/src/app.ts, dev-packages/e2e-tests/test-applications/node-express/tests/trpc.test.ts, packages/core/src/trpc.ts
As reported in https://discord.com/channels/621778831602221064/1339165240482463816/1339165240482463816 we are not capturing trpc input deeply.
=> feat(core): Allow for nested trpc context

dev-packages/e2e-tests/test-applications/vue-3/package.json, packages/vue/package.json
Pinia had a boring major release yesterday: [Migration Guide on their website](https://pinia.vuejs.org/cookbook/migration-v2-v3.html#Migrating-from-v2-to-v3).
As they mainly removed deprecations, I just upgraded the pinia to v3 in the E2E test.
closes https://github.com/getsentry/sentry-javascript/issues/15378
=> feat(vue): Support Pinia v3

dev-packages/e2e-tests/test-applications/vue-3/package.json, dev-packages/e2e-tests/test-applications/vue-3/src/stores/cart.ts, packages/vue/package.json
backport of https://github.com/getsentry/sentry-javascript/pull/15383
=> feat(v8/vue): Support Pinia v3

packages/nuxt/src/common/types.ts, packages/nuxt/src/module.ts
Backport of https://github.com/getsentry/sentry-javascript/pull/15337
=> feat(v8/nuxt): Add `enabled` to disable Sentry module (#15337)

dev-packages/node-integration-tests/package.json, dev-packages/node-integration-tests/suites/tracing/prisma-orm-v5/package.json, dev-packages/node-integration-tests/suites/tracing/prisma-orm-v5/test.ts, dev-packages/node-integration-tests/suites/tracing/prisma-orm-v6/package.json, dev-packages/node-integration-tests/suites/tracing/prisma-orm-v6/test.ts, dev-packages/node-integration-tests/utils/runner.ts
This PR migrates the prisma tests to use the `withDockerCompose` option on the test runner. 
This means:
- Docker is only required if you're running tests that actually use docker
- Containers are automatically cleaned up after tests complete
=> test(node): Run Prisma docker containers via test runner

packages/feedback/src/modal/components/Dialog.css.ts, packages/feedback/src/modal/components/Form.tsx
While submitting feedback the Submit and Cancel buttons previously remained active. So you could smash that submit many times and submit many duplicate feedbacks.
This disabled the buttons while the network request is being fired off.
The disabled buttons are slightly grayed out by the browser. So it depends on what custom color you've picked:
=> feat(feedback): Disable Feedback submit & cancel buttons while submitting

dev-packages/node-integration-tests/suites/tracing/prisma-orm-v5/test.ts, dev-packages/node-integration-tests/suites/tracing/prisma-orm-v6/test.ts
After moving to setup docker via the test runner, the tests became flakey:
https://github.com/getsentry/sentry-javascript/actions/runs/13312637861/job/37179132147?pr=15404#step:6:314
https://github.com/getsentry/sentry-javascript/actions/runs/13327476657/job/37223999432?pr=15404#step:6:347
This PR extends the timeouts.
=> test(node): Extend timeouts for Prisma tests

packages/browser-utils/src/metrics/browserMetrics.ts, packages/browser-utils/test/browser/browserMetrics.test.ts
Third parties may emit measurments with negative durations, causing invalid spans to be emitted, causing relay to drop transactions.
=> fix(browser): Ensure that `performance.measure` spans have a positive duration

packages/core/src/integrations/inboundfilters.ts, packages/core/test/lib/integrations/inboundfilters.test.ts
Filters out an unactionable error thrown by the Facebook Mobile browser web view.
Closes https://github.com/getsentry/sentry-javascript/issues/15065
=> fix(core): Filter out unactionable Facebook Mobile browser error

packages/core/src/integrations/inboundfilters.ts, packages/core/test/lib/integrations/inboundfilters.test.ts
closes https://github.com/getsentry/sentry-javascript/issues/15389
=> fix(core): Add Google `gmo` error to Inbound Filters

packages/profiling-node/src/integration.ts, packages/profiling-node/test/spanProfileUtils.test.ts
Bump profiling chunk interval to 60s as per [spec](https://www.notion.so/sentry/Continuous-UI-Profiling-SDK-API-Spec-17e8b10e4b5d80c59a40c6e114470934)
=> profiling: bump chunk interval to 60s

packages/nuxt/src/common/types.ts, packages/nuxt/src/index.types.ts
We actually have a concrete type for the `init` on the server-side. However, this type was not used so far. Additionally, I removed the `Omit` of `'app'` as there is no `'app'` on the Node types anyway.
=> fix(nuxt): Use `SentryNuxtServerOptions` type for server init

packages/nuxt/src/vite/utils.ts, packages/nuxt/test/vite/utils.test.ts
The Nuxt SDK also uses the preview command to determine where to put the Sentry top-level import. Like this: `node .output/server/index.mjs` (would add Sentry to `index.mjs`)
However, the function to get the file name also used folder names without file extensions which led to Sentry not being included at the top of the index file.
This was a problem in e.g. Azure as the command is the following: `npx @azure/static-web-apps-cli start ./public --api-location ./server`
=> fix(nuxt): Only use filename with file extension from command

packages/browser/test/loader.js, packages/sveltekit/package.json, packages/sveltekit/src/vite/sourceMaps.ts, packages/sveltekit/test/vite/sourceMaps.test.ts, yarn.lock
This PR refactors how we determine the user-provided source map generation settings in our `sentrySvelteKit` vite plugins.
Previously, we'd call Vite's `loadConfigFromFile` function which sounded good but had a couple of drawbacks:
- top-level importing `vite` in a vite config creates a circular import chain (fixed via #15371)
- as reported in #15414, we always loaded the `mode: "production"` version of the config, which was also problematic. 
Since there's no reliably way to read the `mode` for Vite, and parsing `process.argv` also seemed sketchy, I decided to go down the Vite-recommended route and to read the config in the `config` hook. This required a change in our `@sentry/vite-plugin` which was released in 3.2.0, so this PR also bumps the Vite plugin version. 
Concrete changes:
- …
=> fix(sveltekit): Avoid loading vite config to determine source maps setting

packages/bun/src/client.ts, packages/bun/src/index.ts, packages/bun/src/sdk.ts, packages/bun/src/types.ts, packages/bun/test/integrations/bunserver.test.ts, packages/bun/test/sdk.test.ts
- Closes #15458
Extends the basic SDK test to ensure the metadata is correct and that we get the expected exception.
=> fix(bun): Includes correct sdk metadata

.size-limit.js, packages/nextjs/src/client/clientNormalizationIntegration.ts, packages/nextjs/src/client/index.ts, packages/nextjs/src/config/types.ts, packages/nextjs/src/config/webpack.ts, packages/nextjs/src/config/withSentryConfig.ts
**EDIT(cg): Moved this functionality behind `an _experimental.thirdPartyOriginStackFrames` config flag**
This change should drastically improve transparency on stack frames that come from third party origins while keeping existing sourcemapping functionality.
Example: `https://plausible.io/js/script.js` was **always** turned into `app:///js/script.js`, leading the user to believe "wtf is this".
By not stripping scripts on different origins from their origin in the stack trace, it should be way more transparent where errors originate from, potentially even improving sourcemaps via scraping if these scripts have propper source mapping urls/debug IDs.
Additionally, we should no longer strip js-in-html stack frames, also making those more transparent.
Considerations:
- May mess with grouping: …
=> feat(nextjs): Do not strip origin information from different origin stack frames

dev-packages/browser-integration-tests/suites/tracing/linking-addLink/init.js, dev-packages/browser-integration-tests/suites/tracing/linking-addLink/subject.js, dev-packages/browser-integration-tests/suites/tracing/linking-addLink/test.ts, dev-packages/browser-integration-tests/suites/tracing/linking-addLinks/init.js, dev-packages/browser-integration-tests/suites/tracing/linking-addLinks/subject.js, dev-packages/browser-integration-tests/suites/tracing/linking-addLinks/test.ts, packages/core/src/tracing/sentrySpan.ts, packages/core/src/utils/spanUtils.ts, packages/core/test/lib/tracing/trace.test.ts, packages/opentelemetry/test/trace.test.ts
part of https://github.com/getsentry/sentry-javascript/issues/14991
=> feat(core): Add `addLink(s)` to Sentry span

packages/node/package.json, packages/node/test/cron.test.ts, packages/node/test/helpers/conditional.ts, packages/node/test/integration/breadcrumbs.test.ts, packages/node/test/integration/console.test.ts, packages/node/test/integration/scope.test.ts, packages/node/test/integration/transactions.test.ts, packages/node/test/integrations/context.test.ts, packages/node/test/integrations/contextlines.test.ts, packages/node/test/integrations/http.test.ts, packages/node/test/integrations/localvariables.test.ts, packages/node/test/integrations/request-session-tracking.test.ts, packages/node/test/integrations/spotlight.test.ts, packages/node/test/integrations/tracing/graphql.test.ts, packages/node/test/integrations/tracing/mongo.test.ts, packages/node/test/integrations/tracing/redis.test.ts, packages/node/test/sdk/api.test.ts, packages/node/test/sdk/client.test.ts, packages/node/test/sdk/init.test.ts, packages/node/test/sdk/initOtel.test.ts, packages/node/test/sdk/preload.test.ts, packages/node/test/transports/http.test.ts, packages/node/test/transports/https.test.ts, packages/node/test/utils/ensureIsWrapped.test.ts, packages/node/test/utils/entry-point.test.ts, packages/node/test/utils/envToBool.test.ts, packages/node/test/utils/getRequestUrl.test.ts, packages/node/test/utils/module.test.ts, packages/node/tsconfig.test.json, packages/node/vite.config.ts
=> test(node): Migrate to vitest

dev-packages/browser-integration-tests/package.json, packages/replay-canvas/package.json, packages/replay-internal/package.json, yarn.lock
Includes the following:
- https://github.com/getsentry/rrweb/pull/239
- https://github.com/getsentry/rrweb/pull/237
- https://github.com/getsentry/rrweb/pull/238
- https://github.com/getsentry/rrweb/pull/234
- https://github.com/rrweb-io/rrweb/pull/1501
- https://github.com/rrweb-io/rrweb/pull/1500
- https://github.com/rrweb-io/rrweb/pull/1033
- https://github.com/getsentry/rrweb/pull/233
- https://github.com/getsentry/rrweb/pull/229
=> feat(replay): Update rrweb packages to 2.32.0

.github/workflows/release-comment-issues.yml, .github/workflows/release-size-info.yml
Running these workflows is gated pretty well, but this mitigates the potential for a script injection attack by passing the input to an intermediary environment variable first.
See https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#example-of-a-script-injection-attack for more details.
=> security(gha): fix potential for shell injection

packages/aws-serverless/jest.config.js, packages/aws-serverless/package.json, packages/aws-serverless/test/__mocks__/dns.ts, packages/aws-serverless/test/sdk.test.ts, packages/aws-serverless/test/utils.test.ts, packages/aws-serverless/tsconfig.test.json, packages/aws-serverless/vite.config.ts
=> test(aws-serverless): Migrate to Vitest

packages/profiling-node/.eslintrc.js, packages/profiling-node/jest.config.js, packages/profiling-node/package.json, packages/profiling-node/test/integration.test.ts, packages/profiling-node/test/spanProfileUtils.test.ts, packages/profiling-node/test/spanProfileUtils.worker.test.ts, packages/profiling-node/test/utils.test.ts, packages/profiling-node/tsconfig.test.json, packages/profiling-node/vite.config.ts
=> test(profiling-node): Migrate to Vitest

dev-packages/rollup-utils/npmHelpers.mjs, dev-packages/rollup-utils/plugins/npmPlugins.mjs, packages/node/src/sdk/initOtel.ts
Jest didn't like usages of `import.meta.url` but now we're using Vitest, these hacks can be removed. 
Our Rollup config already converts this correctly when building our CommonJs output.
=> test(node): Remove `import.meta.url` hacks

packages/react/jest.config.js, packages/react/package.json, packages/react/test/error.test.ts, packages/react/test/errorboundary.test.tsx, packages/react/test/profiler.test.tsx, packages/react/test/reactrouter-descendant-routes.test.tsx, packages/react/test/reactrouterv3.test.tsx, packages/react/test/reactrouterv4.test.tsx, packages/react/test/reactrouterv5.test.tsx, packages/react/test/reactrouterv6-compat-utils.test.tsx, packages/react/test/reactrouterv6.test.tsx, packages/react/test/redux.test.ts, packages/react/test/sdk.test.ts, packages/react/tsconfig.test.json, packages/react/vite.config.ts
Ref #11084
Before: `7.549 s`
After: `Duration  3.10s (transform 2.32s, setup 0ms, collect 13.39s, tests 599ms, environment 4.11s, prepare 945ms)`
=> test(react): Migrate to vitest

packages/gatsby/.eslintrc.js, packages/gatsby/package.json, packages/gatsby/setup/globalSetup.ts, packages/gatsby/test/gatsby-node.test.ts, packages/gatsby/test/index.test.ts, packages/gatsby/test/sdk.test.ts, packages/gatsby/tsconfig.test.json, packages/gatsby/vite.config.ts
Ref #11084
Before: `6.437 s`
After: `1.23s`
The first thing we did was migrate the `pretest.ts` script to use a vitest global setup instead. This is cleaner, and should ensure it never gets lost in refactors either.
After that we did the conversion. The trickiest thing to change was `packages/gatsby/test/gatsby-node.test.ts`, as `gatsby-node.js` is a CJS file. This is tricky to patch properly with vitest for the spy. To get around this, we monkeypatch `Module._load` temporarily to load a stub which we defined in `vi.hoisted` (which hoists it to the top so it's always available).
=> test(gatsby): Migrate to vitest

packages/feedback/.eslintrc.js, packages/feedback/jest.config.js, packages/feedback/package.json, packages/feedback/src/core/TestClient.ts, packages/feedback/test/core/components/Actor.test.ts, packages/feedback/test/core/getFeedback.test.ts, packages/feedback/test/core/mockSdk.ts, packages/feedback/test/core/sendFeedback.test.ts, packages/feedback/tsconfig.json, packages/feedback/tsconfig.test.json, packages/feedback/vite.config.ts
=> test(feedback): Migrate from jest to vitest

packages/sveltekit/src/server-common/utils.ts
not sure why but apparently `process` is not always available in CloudFlare pages, even with `compatibility_flags = ["nodejs_compat"]` set. This PR adds a guard to the one place where we access `process.env` in the SvelteKit SDK.
closes #15506
=> fix(sveltekit): Guard `process` check when flushing events

dev-packages/browser-integration-tests/suites/manual-client/browser-context/init.js, dev-packages/browser-integration-tests/suites/manual-client/browser-context/test.ts, packages/angular/src/sdk.ts, packages/astro/src/index.server.ts, packages/aws-serverless/src/index.ts, packages/browser/src/exports.ts, packages/browser/src/sdk.ts, packages/browser/test/index.test.ts, packages/bun/src/index.ts, packages/bun/src/sdk.ts, packages/cloudflare/src/index.ts, packages/cloudflare/src/sdk.ts, packages/core/src/index.ts, packages/core/src/integrations/eventFilters.ts, packages/core/test/lib/integrations/eventFilters.test.ts, packages/deno/src/index.ts, packages/deno/src/sdk.ts, packages/google-cloud-serverless/src/index.ts, packages/node/src/index.ts, packages/node/src/sdk/index.ts, packages/remix/src/cloudflare/index.ts, packages/remix/src/server/index.ts, packages/solidstart/src/server/index.ts, packages/sveltekit/src/server/index.ts, packages/sveltekit/src/worker/index.ts, packages/vercel-edge/src/index.ts, packages/vercel-edge/src/sdk.ts
This PR deprecates and renames the `inboundFiltersIntegration` to `eventFiltersIntegration` to improve the integration name and avoid ambiguity with the product. See #15431 for reasons for the renaming.
ref #15431
=> feat(core): Rename `inboundFiltersIntegration` to `eventFiltersIntegration`

dev-packages/browser-integration-tests/package.json, packages/replay-canvas/package.json, packages/replay-internal/package.json, yarn.lock
- fix(snapshot): Do not attempt to load iframe at all if it is blocked
See https://github.com/getsentry/rrweb/releases/tag/2.33.0
=> feat(replay): Bump rrweb to 2.33.0

packages/core/src/trpc.ts, packages/core/test/lib/trpc.test.ts
closes https://github.com/getsentry/sentry-javascript/issues/15505
@chargome 
I didn't have time to properly set up the sentry development environment on my computer. Could you take over from here?
- [] If you've added code that should be tested, please add tests.
- [] Ensure your code lints and the test suite passes (`yarn lint`) & (`yarn test`).
=> feat(core): Add `forceTransaction` to trpc middleware options

.craft.yml, packages/react-router/README.md
Adds a craft entry for publishing `@sentry/react-router` to npm
closes https://github.com/getsentry/sentry-javascript/issues/14725
=> chore(react-router): Add package as npm target in craft 

packages/react-router/README.md
Updates all imports in readme to use `@sentry/react-router`
ref https://github.com/getsentry/sentry-javascript/issues/15191
=> chore(react-router): Update readme to use new package name

.size-limit.js, packages/core/src/integrations/inboundfilters.ts, packages/core/test/lib/integrations/eventFilters.test.ts, packages/core/test/lib/integrations/inboundfilters.test.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/15513
The allowUrls and denyUrls logic up until now only looked at the first entry in the values field of an error event which is complete bogus for aggregate errors and linked errors because the "root" event in the former is one without parent id and in the latter simply the latest entry in the values array.
=> fix(core): Fix `allowUrls` and `denyUrls` for linked and aggregate exceptions

packages/core/src/integrations/eventFilters.ts, packages/core/test/lib/integrations/eventFilters.test.ts
We've been filtering a specific "undefined is not an object" error that referenced "a.L" in our error filters. However, similar errors occured with other uppercase letters (e.g. `a.K`) - they all represent the same class of non-actionable error.
This pr just updates the filter to use a regex for this pattern.
ref https://github.com/getsentry/sentry/issues/85531
=> feat(core): Default filter unactionable error

dev-packages/node-integration-tests/utils/runner.ts
While trying to debug the tedious integration, I figured it would be nice to internals of the envelope item when receiving mismatched envelope items. This PR adds the the serialized envelope item to the error being thrown.
=> test: Log out envelope item for failing node integration tests

packages/opentelemetry/jest.config.js, packages/opentelemetry/package.json, packages/opentelemetry/test/asyncContextStrategy.test.ts, packages/opentelemetry/test/custom/client.test.ts, packages/opentelemetry/test/helpers/mockSdkInit.ts, packages/opentelemetry/test/integration/breadcrumbs.test.ts, packages/opentelemetry/test/integration/scope.test.ts, packages/opentelemetry/test/integration/transactions.test.ts, packages/opentelemetry/test/propagator.test.ts, packages/opentelemetry/test/sampler.test.ts, packages/opentelemetry/test/spanExporter.test.ts, packages/opentelemetry/test/trace.test.ts, packages/opentelemetry/test/utils/getActiveSpan.test.ts, packages/opentelemetry/test/utils/getRequestSpanData.test.ts, packages/opentelemetry/test/utils/getSpanKind.test.ts, packages/opentelemetry/test/utils/getTraceData.test.ts, packages/opentelemetry/test/utils/groupSpansWithParents.test.ts, packages/opentelemetry/test/utils/mapStatus.test.ts, packages/opentelemetry/test/utils/parseSpanDescription.test.ts, packages/opentelemetry/test/utils/setupCheck.test.ts, packages/opentelemetry/test/utils/setupEventContextTrace.test.ts, packages/opentelemetry/test/utils/spanToJSON.test.ts, packages/opentelemetry/test/utils/spanTypes.test.ts, packages/opentelemetry/tsconfig.test.json, packages/opentelemetry/vite.config.ts
=> test(otel): Migrate to Vitest

packages/nextjs/src/config/util.ts, packages/nextjs/src/config/webpack.ts, packages/nextjs/src/config/withSentryConfig.ts
fixes https://github.com/getsentry/sentry-javascript/issues/15551
=> fix(nextjs): Only warn on missing `onRequestError` in version 15

packages/core/src/utils-hoist/normalize.ts, packages/core/test/utils-hoist/normalize.test.ts
Objects that are created from an Object with a null prototype were not correctly handled before. `Object.getPrototypeOf` of such objects does not return `null` directly but also do not have a constructor.
This fix guards against these cases.
Closes: https://github.com/getsentry/sentry-javascript/issues/15538
=> fix(core): Handle normalization of null prototypes correctly

packages/nextjs/src/config/webpack.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/15550#issuecomment-2694085604
=> feat(nextjs): Allow silencing of instrumentation warning

packages/node/src/sdk/index.ts, packages/node/test/sdk/init.test.ts
fixes https://github.com/getsentry/sentry-javascript/issues/15558
The Node SDK init options allow for `transport` to be set as `undefined`, but this breaks because of an error `TypeError: options.transport is not a function`.
You can see a reproduction of this here: https://stackblitz.com/edit/stackblitz-starters-phh3lfmy?file=index.ts
To fix this, we make sure we use `makeNodeTransport` if `options.transport` is set to `undefined`.
=> fix(node): Allow for `undefined` transport to be passed in

packages/cloudflare/package.json
This PR redeclares the `@cloudflare/workers-types` package as an optional peer dependency rather than an optional dependency. With other SDKs now depending on `@sentry/cloudflare`, we'd pull in the type package into non-cloudflare projects. In the particular case reported in https://github.com/getsentry/sentry-javascript/issues/15536, this lead to global type definitions of `fetch` being overridden by the cloudflare types package (more details: https://github.com/getsentry/sentry-javascript/issues/15536#issuecomment-2693832856). 
I'm not sure if I'm missing something but since we only use the `@cloudflare/workers-types` for types, I think it's okay to make this an optional peer dependency. Which should avoid "polluting" non-CF projects with CF types. 
closes #15536
=> fix(cloudflare): Make `@cloudflare/workers-types` an optional peer dependency

.craft.yml
closes https://github.com/getsentry/sentry-javascript/issues/15190
**don't merge before https://github.com/getsentry/sentry-release-registry/pull/183**
=> chore(react-router): Add `@sentry/react-router` as release registry target

.github/CANARY_FAILURE_TEMPLATE.md
Let's set `type: task` on the canary issue so we don't get issues without a type.
=> chore(ci): Add type task to canary issue template

packages/cloudflare/package.json, yarn.lock
In #15554 I forgot to update `yarn.lock` and after doing that manually, I could reproduce a [build error I got in CI](https://github.com/getsentry/sentry-javascript/actions/runs/13649287637). Turns out installing some version of `4.202502...` introduced a type-breaking change (I'm utterly confused by this versioning scheme, ngl). So I hard-pinned to `4.20240725.0`, which was close to the version we installed before (`4.20240722.0`) and still satisfied the same minimum devDep version.
=> fix(build): Pin `@cloudflare/workers-types` and unstale `yarn.lock`

packages/browser/test/tracekit/chromium.test.ts, packages/wasm/package.json, packages/wasm/src/index.ts, packages/wasm/test/stacktrace-parsing.test.ts, packages/wasm/test/tsconfig.json, packages/wasm/tsconfig.test.json, packages/wasm/vite.config.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/9505
=> fix(wasm): Fix wasm integration stacktrace parsing for filename

packages/nextjs/rollup.npm.config.mjs
Fixes https://github.com/getsentry/sentry-javascript/issues/10366
=> feat(nextjs): Add `use client` directive to client SDK entrypoints

packages/node/src/integrations/tracing/express.ts
This should help reduce the memory pressure of the SDK as we don't store
the entire request in memory anymore.
resolves https://github.com/getsentry/sentry-javascript/issues/15528
=> perf(node): Store normalized request for processing

packages/core/src/integrations/eventFilters.ts
https://github.com/getsentry/sentry-javascript/issues/15513#issuecomment-2700229716 noticed a regression I introduced, reversing exceptions in the event, because I fumbled a reverse() call into the wrong location.
Should be fixed asap.
=> fix(core): Don't reverse values in event filters

packages/vue/src/pinia.ts
Each Pinia store will run through the event processor but the Pinia state should only be attached once.
closes https://github.com/getsentry/sentry-javascript/issues/15587
=> fix(vue): Attach Pinia state only once per event

dev-packages/browser-integration-tests/package.json, packages/replay-canvas/package.json, packages/replay-internal/package.json, yarn.lock
- fix(record): Catch exceptions when accessing window.document
See https://github.com/getsentry/rrweb/releases/tag/2.34.0
=> feat(replay): Bump rrweb to 2.34.0

packages/nextjs/package.json, yarn.lock
Fixes https://github.com/getsentry/sentry-javascript/issues/11949
=> deps(nextjs): Bump rollup to `4.34.9`

packages/browser-utils/src/instrument/history.ts
In https://github.com/getsentry/sentry-javascript/pull/14696 an early `return` was introduced that alters the default behavior of the underlying history API that is being patched.
Instead of just returning, the original/underlying function should be called to keep the default behavior.
=> fix(browser): Call original function on early return from patched history API

packages/bun/src/sdk.ts, packages/bun/test/init.test.ts
Automatically adds performance integrations to bun when tracing is enabled.
closes https://github.com/getsentry/sentry-javascript/issues/12705
=> feat(bun): Automatically add performance integrations

packages/remix/package.json
Ref: https://github.com/getsentry/sentry-javascript/issues/5610#issuecomment-2701586784
=> fix(remix): Use correct types export for `@sentry/remix/cloudflare`

packages/sveltekit/src/vite/detectAdapter.ts, packages/sveltekit/src/vite/svelteConfig.ts, packages/sveltekit/test/vite/detectAdapter.test.ts, packages/sveltekit/test/vite/svelteConfig.test.ts
This PR expands upon #14672 by adding detection of the @sveltejs/adapter-cloudflare adapter and defining it's output directory (cloudflare as opposed to output). I've tested it with a Cloudflare Pages project and it was successful in building and uploading sourcemaps, whereas relying on 'other' caused an infinite loop and an OOM when trying to upload sourcemaps.
=> Add cloudflare adapter detection and path generation

packages/sveltekit/src/server-common/utils.ts
`process` was guarded in https://github.com/getsentry/sentry-javascript/pull/15516 already, but it still did not fix the problem as the variable `process` is not even available so the code still broke. This is another attempt to fix "process is undefined" reported in https://github.com/getsentry/sentry-javascript/issues/15506
=> fix(sveltekit): Guard process variable

dev-packages/e2e-tests/test-applications/nuxt-3-dynamic-import/package.json, dev-packages/e2e-tests/test-applications/nuxt-3-dynamic-import/playwright.config.ts, dev-packages/e2e-tests/test-applications/nuxt-3-dynamic-import/tests/errors.client.test.ts, dev-packages/e2e-tests/test-applications/nuxt-3-dynamic-import/tests/tracing.client.test.ts, dev-packages/e2e-tests/test-applications/nuxt-3-min/package.json, dev-packages/e2e-tests/test-applications/nuxt-3-min/playwright.config.ts, dev-packages/e2e-tests/test-applications/nuxt-3-min/tests/errors.client.test.ts, dev-packages/e2e-tests/test-applications/nuxt-3-min/tests/tracing.client.test.ts, dev-packages/e2e-tests/test-applications/nuxt-3-top-level-import/package.json, dev-packages/e2e-tests/test-applications/nuxt-3-top-level-import/playwright.config.ts, dev-packages/e2e-tests/test-applications/nuxt-3-top-level-import/tests/errors.client.test.ts, dev-packages/e2e-tests/test-applications/nuxt-3-top-level-import/tests/tracing.client.test.ts, dev-packages/e2e-tests/test-applications/nuxt-3/package.json, dev-packages/e2e-tests/test-applications/nuxt-3/playwright.config.ts, dev-packages/e2e-tests/test-applications/nuxt-3/tests/errors.client.test.ts, dev-packages/e2e-tests/test-applications/nuxt-3/tests/tracing.client.test.ts, dev-packages/e2e-tests/test-applications/nuxt-4/package.json, dev-packages/e2e-tests/test-applications/nuxt-4/playwright.config.ts
Not sure why this only started happening now but it seems like `import { test, describe } from '@nuxt/test-utils/playwright` instead of from `@playwright/test` builds a nuxt application on every test. This seems in line with what @s1gr1d found out about the purpose of Nuxt E2E which is to create small test apps on every `test` function invocation.
We don't want this functionallity anyway, so let's get rid of this depenency and only import form `@playwright/test`.
=> test(nuxt): Fix failing e2e tests

dev-packages/e2e-tests/test-applications/sveltekit-2/src/routes/type-assertion/+page.svelte, dev-packages/e2e-tests/test-applications/sveltekit-2/src/routes/type-assertion/+page.ts, packages/sveltekit/package.json, packages/sveltekit/src/vite/autoInstrument.ts, packages/sveltekit/src/vite/recastTypescriptParser.ts, packages/sveltekit/test/vite/autoInstrument.test.ts, yarn.lock
This PR
- removes `magicast` as a dependency of the Sveltekit SDK
- replaces it with direct usage of `recast` and `@babel/parser`. Both dependencies were already transitive dependencies beforehand but with this, we just hoist it up a level.
- configures `recast` to use the TypeScript parser, just like it configures it. We can't directly use the recast typscript parser because its export is not compatible with ESM (TODO: open issue in recast repo)
- Makes adjustments to our code (mostly type casts) due to slightly changed types. 
- Given that we have various tests that cover our AST walking logic I think this is a low-risk change overall.
closes https://github.com/getsentry/sentry-javascript/issues/9318
=> fix(sveltekit): Correctly parse angle bracket type assertions for auto instrumentation

packages/browser-utils/src/instrument/history.ts, packages/browser-utils/test/instrument/history.test.ts, packages/core/src/utils-hoist/object.ts, packages/core/src/utils-hoist/supports.ts, packages/core/test/utils-hoist/object.test.ts, packages/core/test/utils-hoist/supports.test.ts
This PR adds a guard to our `fill` utility that we use to instrument/wrap methods defined on an object. However, due to a misleading type cast in `fill` we didn't check if the name of the method to be patched actually corresponded to a function on an object.
This was surfaced via #15552 where we'd call `fill` on `window.history(pushState|replaceState)` without checking if these two methods were actually available or functions.
Note: I initially solved this on the `instrumentHistory` level but then noticed that this is a more general bug in `fill`. Therefore I added some history-specific tests as well but I'd rather keep them than removing them. Fun fact: The more general fix saves ~8 Bytes of bundle size compared to my initial history-based fix 😅 
closes …
=> fix(core): Ensure `fill` only patches functions

MIGRATION.md
I thought about deleting the link as well, but I figured once we start documenting `Deprecation in 9.x` it would be good to have a link.
=> chore: Fix link in migration doc

packages/core/src/profiling.ts, packages/core/src/types-hoist/profiling.ts, packages/profiling-node/src/integration.ts, packages/profiling-node/src/spanProfileUtils.ts, packages/profiling-node/test/integration.test.ts
Implements https://www.notion.so/sentry/Continuous-UI-Profiling-SDK-API-Spec-17e8b10e4b5d80c59a40c6e114470934
=> profiling: implement new profiling API spec

packages/astro/src/integration/index.ts, packages/astro/src/integration/types.ts, packages/astro/test/integration/index.test.ts
Adds support for `unstable_sentryVitePluginOptions` which can be used to pass any valid vite-plugin option.
Fixes #15601
---
Hello 👋 this is my first ever contribution in this repository. I hope I understood and followed all the contribution guides correctly. Please let me know if I need to fix something, add more tests, refactor something. Or feel free to push more commits yourself - whichever working style you prefer!
I tried to base my implementation of this feature for sentry/astro on the existing implementation for sentry/sveltekit, from where I copied for example the type comment.
=> feat(astro): Accept all vite-plugin options

yarn.lock
Splitting this out of #15119 in the hope that gradually deduping things will help identify which dependency is causing the Next E2E tests to fail in that PR.
=> chore(deps): Deduplicate `@babel` dependencies

.github/CANARY_FAILURE_TEMPLATE.md
Apparently `type` is not yet supported by https://github.com/JasonEtco/create-an-issue
ref https://github.com/getsentry/sentry-javascript/pull/15562
=> chore(ci): Remove `type` from canary failure template

packages/nextjs/src/config/webpack.ts
=> fix(nextjs): Consider `pageExtensions` when looking for instrumentation file

packages/core/src/types-hoist/envelope.ts, packages/core/src/types-hoist/index.ts, packages/core/src/types-hoist/log.ts
In https://github.com/getsentry/sentry-javascript/pull/15530 I added types for the log envelope and log item.
This PR comes and explicitly references that these added types were otel logs. For more details, see the logs spec in develop: https://github.com/getsentry/sentry-docs/pull/12920.
Note I used `Otel` everywhere here, but I'm also fine with switching to `OpenTelemetry`.
=> ref(core): Update log types to explicitly reference otel

dev-packages/e2e-tests/test-applications/debug-id-sourcemaps/package.json, package.json, packages/nextjs/package.json, packages/nextjs/src/config/templates/pageWrapperTemplate.ts, yarn.lock
Splitting this fix out of #15119.
The implicit bump to Rollup after deduping caused problems with the `@sentry/nextjs` package. `rollup@4.34.0` implemented tree-shaking of unused properties in object literals in https://github.com/rollup/rollup/pull/5737. Because `@sentry/nextjs` does some interesting things where it replaces strings during bundling, Rollup is unable to determine that the properties in the `getInitialPropsWrappers` are in fact used, so it removes them (see https://github.com/getsentry/sentry-javascript/pull/15119#issuecomment-2725028017). By wrapping the object in `Object.freeze(...)`, we signal to Rollup that it shouldn't perform tree-shaking on that object.
Once merged, this will unblock #15119.
Note that the version of rollup in the top-level `package.json` isn't …
=> chore(deps): Bump rollup to 4.35.0

packages/nuxt/src/module.ts, packages/nuxt/src/vite/addServerConfig.ts
Previously, the Sentry server config was added by adding another entry point in the rollup options of Vite. Since Nuxt changed `preserveModules` to `true`, this did not work anymore. The aim of this change in Nuxt is to avoid duplicating what the Nitro build would do. 
This means, that we now don't change the Rollup options in Vite anymore (affects Nuxt as a whole) but only the Rollup options during the Nitro build.
The added plugin will emit a new file and returns the Sentry config code there.
fixes https://github.com/getsentry/sentry-javascript/issues/15628
=> fix(nuxt): Add Nitro Rollup plugin to inject Sentry server config

packages/browser-utils/test/instrument/history.test.ts
resolves https://github.com/getsentry/sentry-javascript/issues/15594
=> test(browser-utils): Add test to make sure we run `originalHistoryFunction` if urls are the same

packages/nextjs/src/client/routing/appRouterRoutingInstrumentation.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/15700
=> fix(nextjs): Re-patch router if it is overriden by Next.js

packages/remix/src/cloudflare/index.ts
Exposes `sentryHandleError` for `@sentry/remix/cloudflare`.
Closes: #15620
=> feat(remix/cloudflare): Export `sentryHandleError`

packages/node/src/integrations/http/SentryHttpInstrumentation.ts, packages/node/src/integrations/http/index.ts
Part of https://github.com/getsentry/sentry-javascript/pull/15730
Noticed that this is not really happening otherwise, so if we are not adding the `HttpInstrumentation` we now make sure to extract incoming traces ourselves! This will unlock us not adding that instrumentation when tracing is disabled.
Also includes https://github.com/getsentry/sentry-javascript/pull/15731 as a side effect.
=> fix(node): Ensure incoming traces are propagated without HttpInstrumentation

packages/node/src/integrations/http/SentryHttpInstrumentation.ts, packages/node/src/integrations/http/SentryHttpInstrumentationBeforeOtel.ts
Small optimization to avoid unnecessary work.
ref: https://github.com/getsentry/sentry-javascript/issues/15725
=> ref(node): Avoid unnecessary array parsing for incoming requests

dev-packages/node-integration-tests/suites/public-api/onUnhandledRejectionIntegration/mode-none.js, dev-packages/node-integration-tests/suites/public-api/onUnhandledRejectionIntegration/mode-strict.js, dev-packages/node-integration-tests/suites/public-api/onUnhandledRejectionIntegration/mode-warn-error.js, dev-packages/node-integration-tests/suites/public-api/onUnhandledRejectionIntegration/mode-warn-string.js, dev-packages/node-integration-tests/suites/public-api/onUnhandledRejectionIntegration/scenario-strict.ts, dev-packages/node-integration-tests/suites/public-api/onUnhandledRejectionIntegration/scenario-warn.ts, dev-packages/node-integration-tests/suites/public-api/onUnhandledRejectionIntegration/test.ts, packages/node/src/integrations/onunhandledrejection.ts
Closes https://github.com/getsentry/sentry-javascript/issues/13700
This also adds tests for unhandled rejections handling, which we did not really have before.
=> fix(node): Use `fatal` level for unhandled rejections in `strict` mode

docs/publishing-a-release.md
This just makes it a bit more disoverable for poor souls like me searching for "alpha" in this doc
=> chore(docs): Add note on alpha releases to docs

packages/nuxt/src/module.ts
Follow-up for https://github.com/getsentry/sentry-javascript/pull/15710
The server config was still processed by Nuxt (not only Nitro) because the file was imported in a plugin template. This code can be deleted now, as the Sentry server config should only be processed on the Nitro-side.
fixes https://github.com/getsentry/sentry-javascript/issues/15628
=> fix(nuxt): Delete Nuxt server template injection

packages/core/src/integrations/eventFilters.ts
Ref: https://github.com/getsentry/sentry-javascript/issues/15725
- Only does the options merging once
- Adds short circuiting for event types to avoid doing things multiple times/unnecessarily
=> perf(core): Add short-circuits to `eventFilters` integration

packages/react/src/error.ts, packages/react/src/index.ts, packages/react/test/errorboundary.test.tsx
This PR exports the `captureReactException` method from the React package, making it available as a public API. Additionally, it refactors the implementation to use `withScope` instead of directly passing context to `captureException`. This was done so that the arguments to `captureReactException` better align to `captureException`.
This was requested by a user, but I also need it for my conference talk in a couple weeks 😅 
Users can now directly access and use this method in their applications:
```javascript
import * as Sentry from '@sentry/react';
class ErrorBoundary extends React.Component {
componentDidCatch(error, info) {
Sentry.captureReactException(error, info);
}
render() {
return this.props.children;
}
}
```
The reason why `captureReactException` is named as such and not …
=> feat(react): Export captureReactException method

packages/profiling-node/src/integration.ts, packages/profiling-node/src/utils.ts, packages/profiling-node/test/integration.test.ts
We need to send the platform as part of envelope headers as this is the item that relay is checking to manage rate limiting. We only care about backend (node) and in the future frontend.
@AbhiPrasad please correct me here to use the correct convention, would `javascript.node` be more appropriate? The only requirement really is to have all nodejs platform types be of a single platform type, so we dont need to maintain the ever growing list in relay
=> profiling: add platform to chunk envelope

packages/node/src/integrations/http/SentryHttpInstrumentationBeforeOtel.ts
Probabilistic hot fix for https://github.com/getsentry/sentry-javascript/issues/15759
It seems like that sometimes res.end is not available and we should check for it before passing it to a Proxy.
=> fix(node): Check for `res.end` before passing to Proxy

packages/node/src/integrations/http/SentryHttpInstrumentationBeforeOtel.ts, packages/node/src/integrations/http/index.ts
Only adds the HttpInstrumentation that is supposed to flush for Vercel when we are on Vercel. Should reduce some overhead.
Also adds a bit more explanation because of https://github.com/getsentry/sentry-javascript/pull/15602#discussion_r2003184385
=> perf(node): Short circuit flushing on Vercel only for Vercel

packages/browser-utils/src/metrics/cls.ts, packages/core/src/currentScopes.ts, packages/core/src/tracing/sentrySpan.ts, packages/core/src/utils-hoist/envelope.ts, packages/core/src/utils/applyScopeDataToEvent.ts, packages/core/test/lib/utils/applyScopeDataToEvent.test.ts, packages/opentelemetry/src/spanExporter.ts
This gets rid of some unnecessary invocations of `dropUndefinedKeys()` that we have.
=> ref: Avoid some usage of `dropUndefinedKeys()`

dev-packages/e2e-tests/test-applications/nextjs-t3/src/trpc/react.tsx
https://github.com/trpc/trpc/pull/6617 removed an unstable API we used in the app. I just switched it over to use the stable replacement
=> test(e2e): Fix failing nextjs-t3 e2e test app

packages/browser/src/tracing/previousTrace.ts
Small amend to #15569 - we want a duration of 1h and not 60h 🤦‍♂️ 
h/t @s1gr1d for noticing!
=> fix(browser): Fix incorrect previous trace max duration

packages/nestjs/src/integrations/sentry-nest-instrumentation.ts
ref https://github.com/getsentry/sentry-javascript/issues/15725#issuecomment-2741985510
Similar to the work done in https://github.com/getsentry/sentry-javascript/pull/15765 we can avoid usage of `addNonEnumerableProperty` with usage of a `WeakSet`.
=> perf(nestjs): Remove usage of addNonEnumerableProperty

packages/browser/src/client.ts, packages/browser/src/index.ts, packages/browser/src/log.ts, packages/browser/test/index.test.ts, packages/browser/test/log.test.ts, packages/core/src/index.ts, packages/core/src/logs/index.ts, packages/core/test/lib/log/index.test.ts
ref https://github.com/getsentry/sentry-javascript/issues/15526
Continuing off the work from https://github.com/getsentry/sentry-javascript/pull/15717, this PR adds the logging public API to the Browser SDK. It also adds a basic flushing strategy to the SDK that is timeout based. This is done to help save bundle size.
The main file added was `log.ts`. This has three areas to look at:
1. The logger methods for `trace`, `debug`, `info`, `warn`, `error`, `fatal` (the log severity levels) as well as an internal capture log helper all these methods call.
2. `addFlushingListeners` which adds listeners to flush the logs buffer on client flush and document visibility hidden.
3. a flush timeout that flushes logs after X seconds, which gets restarted when new logs are captured.
I also removed any …
=> feat(browser): Add logger.X methods to browser SDK

packages/core/src/fetch.ts, packages/core/src/utils-hoist/url.ts, packages/core/test/utils-hoist/url.test.ts
ref https://github.com/getsentry/sentry-javascript/issues/15767
Now that we support ES2020 (aka not IE11 anymore) and Node.js 18+, we can get rid of `parseUrl` in favor of a method that just uses the built-in URL object. This will save us some bundle size (given we can remove that regex), and we get performance benefits from using native code.
https://github.com/getsentry/sentry-javascript/blob/3d63621714b31c1ea4c2ab2d90d5684a36805a43/packages/core/src/utils-hoist/url.ts#L17
Instead of just blanket replacing `parseUrl`, we'll slowly convert all it's usages to using a new helper, `parseStringToURL`.
Given we are updating the core package, I also went ahead and converted `parseUrl` usage in `packages/core/src/fetch.ts`
=> feat(core): Add `parseStringToURL` method

dev-packages/e2e-tests/test-applications/node-fastify/src/app.ts, dev-packages/e2e-tests/test-applications/node-fastify/tests/errors.test.ts, packages/node/src/integrations/tracing/fastify.ts
Supercedes https://github.com/getsentry/sentry-javascript/pull/13198
resolves https://github.com/getsentry/sentry-javascript/issues/13197
Aligns fastify error handler with the express one.
1. Adds `shouldHandleError` to allow users to configure if errors should be captured
2. Makes sure the default `shouldHandleError` does not capture errors for 4xx and 3xx status codes.
```js
setupFastifyErrorHandler(app, {
shouldHandleError(_error, _request, reply) {
return statusCode >= 500 || statusCode <= 399;
},
});
```
=> feat(node): Add fastify `shouldHandleError`

packages/astro/src/integration/index.ts, packages/browser-utils/src/metrics/inp.ts, packages/core/src/checkin.ts, packages/core/src/feedback.ts, packages/core/src/session.ts, packages/core/src/tracing/dynamicSamplingContext.ts, packages/replay-internal/src/coreHandlers/util/networkUtils.ts, packages/sveltekit/src/client/browserTracingIntegration.ts
In some places this should not really be needed, so we can skip this.
=> ref: Remove some usages of `dropUndefinedKeys()`

packages/nextjs/src/edge/index.ts
Noticed this was "incorrect" here, for all other places it seems correct.
=> ref(nextjs): Fix Next.js vercel-edge runtime package information

packages/nuxt/src/vite/addServerConfig.ts
Due to PR https://github.com/getsentry/sentry-javascript/pull/15710 the Sentry server config is only processed inside the Nitro-part of Nuxt and the server config file is emitted through the Rollup plugin. 
It is not needed anymore to copy-paste the file manually (this has been the case before as the file was added to the `.nuxt` folder - as it was processed by Nuxt, not Nitro-only).
This fixes the "no such file" error [posted in this comment](https://github.com/getsentry/sentry-javascript/issues/13330#issuecomment-2743702460).
closes https://github.com/getsentry/sentry-javascript/issues/13330
=> fix(nuxt): Delete no longer needed Nitro 'close' hook

.size-limit.js, dev-packages/browser-integration-tests/suites/errors/fetch/init.js, dev-packages/browser-integration-tests/suites/errors/fetch/subject.js, dev-packages/browser-integration-tests/suites/errors/fetch/test.ts, packages/core/src/utils-hoist/instrument/fetch.ts
Closes https://github.com/getsentry/sentry-javascript/issues/15709
This also adds tests for the various types of TypeErrors that fetch can produce.
=> feat(browser): Attach host as part of error message to "Failed to fetch" errors

packages/nuxt/src/vite/sourceMaps.ts
Sometimes, the build fails because of this error: ` ERROR  Cannot set property options of #<Object> which has only a getter   `
As `nuxt.options` are always defined anyway (it's also not optional in the `Nuxt` type), we can safely delete the assertion to `{}` which causes the error to dissapear.
=> fix(nuxt): Don't override Nuxt options if undefined

packages/core/src/tracing/sentrySpan.ts, packages/core/src/utils/spanUtils.ts, packages/core/test/lib/tracing/sentrySpan.test.ts
=> ref: Avoid `dropUndefinedKeys` for `spanToJSON` calls

packages/node/src/sdk/index.ts
We can instead of `??` to get the same outcome.
=> ref(node): Avoid `dropUndefinedKeys` in Node SDK init

packages/opentelemetry/src/spanExporter.ts
Another place to get rid of this, this is serialized afterwards and this should not really matter!
=> ref: Stop using `dropUndefinedKeys` in SpanExporter

dev-packages/node-integration-tests/suites/tracing/tedious/test.ts
This test now failed twice in a row for me and I've seen it fail in countless PRs. Skipping it for now but we should prioritize https://github.com/getsentry/sentry-javascript/issues/15579 to eventually unflake and unskip them again.
=> test(node-integration): Skip flaky tedious tests

dev-packages/e2e-tests/test-applications/nuxt-3-min/package.json
Reducing version for E2E test which tests the minimum supported version for Nuxt.
Was bumped here: https://github.com/getsentry/sentry-javascript/pull/15744
=> test(nuxt): Reduce version in Nuxt min test

dev-packages/browser-integration-tests/suites/public-api/captureException/aggregateError/subject.js, dev-packages/browser-integration-tests/suites/public-api/captureException/aggregateError/test.ts
While trying to debug https://github.com/getsentry/sentry-javascript/issues/15707 I added a new integration test. Figured we should merge this in for now.
=> test: Add browser integration test for AggregateErrors

packages/astro/src/index.server.ts, packages/astro/src/index.types.ts, packages/aws-serverless/src/index.ts, packages/bun/src/index.ts, packages/core/src/client.ts, packages/core/src/logs/index.ts, packages/core/src/server-runtime-client.ts, packages/core/src/types-hoist/log.ts, packages/google-cloud-serverless/src/index.ts, packages/nextjs/src/index.types.ts, packages/node/src/index.ts, packages/node/src/log.ts, packages/node/test/log.test.ts, packages/nuxt/src/index.types.ts, packages/react-router/src/index.types.ts, packages/remix/src/index.types.ts, packages/remix/src/server/index.ts, packages/solidstart/src/index.types.ts, packages/solidstart/src/server/index.ts, packages/sveltekit/src/index.types.ts, packages/sveltekit/src/server/index.ts, packages/tanstackstart-react/src/index.types.ts
ref https://github.com/getsentry/sentry-javascript/issues/15526
Continuing off the work from https://github.com/getsentry/sentry-javascript/pull/15763, this PR adds the logging public API to the Node SDK. It also adds a basic weight-based flushing strategy to the SDK that is in the server-runtime client.
The main file added was `log.ts`. In that file I've added  logger methods for `trace`, `debug`, `info`, `warn`, `error`, `fatal` (the log severity levels) as well as an internal capture log helper all these methods call.
Usage:
```js
import * as Sentry from "@sentry/node";
Sentry.init({
dsn: "your-dsn-here",
_experiments: {
enableLogs: true  // This is required to use the logging features
}
});
// Trace level (lowest severity)
Sentry.logger.trace("This is a trace message", { userId: 123 …
```
=> feat(node): Add logging public APIs to Node SDKs

packages/browser/src/diagnose-sdk.ts, packages/browser/src/index.ts
Resolves https://github.com/getsentry/sentry-javascript/issues/15780
Adds a function `diagnoseSdkConnectivity` that will resolve to various "error codes" for possible reasons why events might not land in Sentry.
Originally I wanted to add an API to detect ad blockers so we can show a notification in the example pages that the wizard creates. Then I quickly thought of a different case why the SDK might not send data so I extended the API to also detect if the SDK wasn't initialized yet. We can extend this function at any point if we come up with more cases.
=> feat(browser): Add `diagnoseSdkConnectivity()` function to programmatically detect possible connectivity issues

packages/browser-utils/src/instrument/xhr.ts
While working on https://github.com/getsentry/sentry-javascript/issues/15767 I ran into a `parseUrl` function defined in `packages/browser-utils/src/instrument/xhr.ts`.
This usage is fine, but was a bit confusing, so I renamed the method and expanded the docstring. I also expanded the types a little bit.
=> ref(browser-utils): Give parseUrl a better name

packages/cloudflare/src/transport.ts, packages/cloudflare/test/transport.test.ts, packages/core/src/transports/base.ts, packages/core/src/utils-hoist/index.ts, packages/core/src/utils-hoist/promisebuffer.ts, packages/vercel-edge/src/transports/index.ts, packages/vercel-edge/test/transports/index.test.ts
This replaces usage of `SentryError` for promise buffer control flow.
Instead, we can use a symbol and just check this directly, we do not even care about the message here.
ref https://github.com/getsentry/sentry-javascript/issues/15725#issuecomment-2750892929
=> ref: Avoid using `SentryError` for PromiseBuffer control flow

dev-packages/e2e-tests/test-applications/nuxt-3/server/plugins/customNitroErrorHandler.ts, packages/browser/test/tracing/browserTracingIntegration.test.ts, packages/core/src/tracing/dynamicSamplingContext.ts, packages/core/src/types-hoist/envelope.ts, packages/core/src/utils-hoist/anr.ts, packages/core/src/utils-hoist/envelope.ts, packages/core/src/utils-hoist/index.ts, packages/core/src/utils-hoist/object.ts, packages/core/src/utils/request.ts, packages/core/src/utils/spanUtils.ts, packages/core/src/utils/transactionEvent.ts, packages/core/test/lib/tracing/dynamicSamplingContext.test.ts, packages/core/test/utils-hoist/object.test.ts, packages/nuxt/src/runtime/utils.ts, packages/replay-internal/src/integration.ts, packages/sveltekit/src/vite/sentryVitePlugins.ts
This removes the last remaining usages of `dropUndefinedKeys` in the SDK.
It also deprecates the export from `@sentry/core` for future removal.
=> feat: Stop using `dropUndefinedKeys`

packages/browser/src/log.ts, packages/browser/test/index.test.ts, packages/browser/test/log.test.ts, packages/core/src/types-hoist/log.ts, packages/node/src/log.ts, packages/node/test/log.test.ts
This isn't part of the spec, and will break ingestion if we allow things to be sent.
=> fix: Remove critical log severity level

packages/replay-canvas/package.json, packages/replay-internal/package.json, yarn.lock
closes https://github.com/getsentry/sentry-javascript/issues/15559
(added this so the user gets notified in the ticket once this is released)
=> chore(deps): Bump `rrweb` to `2.35.0`

packages/node/src/integrations/tracing/connect.ts, packages/node/src/integrations/tracing/dataloader.ts, packages/node/src/integrations/tracing/genericPool.ts, packages/node/src/integrations/tracing/knex.ts, packages/node/src/integrations/tracing/prisma.ts, packages/node/src/integrations/tracing/tedious.ts, packages/node/src/integrations/tracing/vercelai/index.ts, packages/node/src/integrations/tracing/vercelai/instrumentation.ts, packages/node/src/otel/instrument.ts, packages/node/test/utils/instrument.test.ts
Related to https://github.com/getsentry/sentry-javascript/issues/15725#issuecomment-2740015011, this PR is an idea to avoid registering `on('spanStart')` hooks for all the node libraries that do not have proper hooks, unless they are used.
Today, for OTEL instrumentation that does not provide span hooks, we fall back to `client.on('spanStart')` to enhance/mutate spans emitted by the instrumentation. This PR improved this by only registering the `spanStart` client hook if we detect that the OTEL instrumentation is actually wrapping something. This avoids us calling a bunch of span callbacks each time a span is started, when it is not even needed.
For this, a new `instrumentWhenWrapped` utility is added which can be passed an instrumentation. This works by monkey-patching `_wrap` on the …
=> feat(node): Only add span listeners for instrumentation when used

packages/core/src/scope.ts, packages/core/test/lib/scope.test.ts, packages/node/src/integrations/console.ts, packages/node/test/integration/console.test.ts
We had this logic in the console instrumentation before but it probably makes sense to truncate all breadcrumbs to some degree for memory consumption reasons.
Acts as prework for https://github.com/getsentry/sentry-javascript/pull/15818 because if we don't truncate error messages they will end up as very big strings in breadcrumbs.
=> feat: Always truncate stored breadcrumb messages to 2kb

packages/opentelemetry/src/sampler.ts
Related to https://github.com/getsentry/sentry-javascript/issues/15725#issuecomment-2742022649
When a span is not a root span, we do not need to do sampling work for it. By reordering stuff in the `shouldSample` function, we should be able to save a bunch of operations for the vast majority of (non-root) spans.
I _think_ this should be just fine!
=> ref(opentelemetry): Avoid sampling work for non-root spans

packages/browser/src/client.ts, packages/browser/src/log.ts, packages/browser/test/client.test.ts, packages/browser/test/log.test.ts, packages/core/src/index.ts, packages/core/src/logs/exports.ts, packages/core/src/server-runtime-client.ts, packages/core/test/lib/logs/exports.test.ts, packages/core/test/lib/server-runtime-client.test.ts
I experimented with a bunch of different approaches to register log flushing implementations, but I found the cleanest and most performant solution was to have log flushing logic live in clients.
This refactors the browser client to do that, and adds tests for all of our flushing logic everywhere.
The bundle size increase is not ideal, but I recognize we have no choice.
After this gets merged in, I'll add the console logging integration to core. I'll also add some quick integrations for pino and winston.
=> ref(browser/core): Move all log flushing logic into clients

packages/aws-serverless/package.json, packages/bun/package.json, packages/cloudflare/package.json, packages/deno/package.json, packages/google-cloud-serverless/package.json, packages/nestjs/package.json, packages/node/package.json, packages/opentelemetry/package.json, packages/profiling-node/package.json
In preparation for OpenTelemetry v2, which targets ES2022, we bump the checks to ES2022 for node-based packages.
=> ref: Bump es-compatibility to ES2022 for node-based packages

packages/node/src/utils/commonjs.ts
As `require` is supported in ESM as well from [Node 20.19.0](https://nodejs.org/en/blog/release/v20.19.0) onwards, the check does not work anymore. However, `module` is not available in ESM.
Also mentioned in this comment: https://github.com/getsentry/sentry-javascript/issues/14202#issuecomment-2761399514
[Node: Compatibility with CommonJS](https://nodejs.org/docs/latest-v15.x/api/esm.html#esm_interoperability_with_commonjs)
[Bun: Using require](https://bun.sh/docs/runtime/modules#using-require)
=> fix(cjs): Use `module` instead of `require` for CJS check

nx.json, packages/profiling-node/.eslintignore, packages/profiling-node/.eslintrc.js, packages/profiling-node/.gitignore, packages/profiling-node/package.json, packages/profiling-node/rollup.npm.config.mjs, packages/profiling-node/tsconfig.json, packages/profiling-node/tsconfig.types.json
This used to build into `/lib` which is not covered by nx (it was changed there but slightly incorrectly, covering `/build/lib` instead of `/lib`). But overall, the way to go here is to just use our standard structure, which is `build/`, then this should all just work :D
=> build(profiling-node): Fix output directory & caching

vite/vite.config.ts
When running some unit tests locally, I noticed that the coverage summary contained files like `vite.config.ts` or `.eslintrc` as well as transpiled code in `build`. These files shouldn't be in the coverage reports and neither have an influence on the overall coverage score.
=> chore(tests): Fix coverage file exclusions

.size-limit.js, packages/browser-utils/src/metrics/browserMetrics.ts, packages/browser-utils/test/browser/browserMetrics.test.ts
This PR adds an `http.redirect_count` attribute to `browser.redirect` spans. The count is taken from the `navigation` performance entry and it describes the number of times a redirect happened. 
Two caveats:
- we can't detect more about redirects (e.g. the location the browser was redirected to)
- this only works for same-origin redirects. [According to MDN](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceNavigationTiming/redirectCount#value), cross-origin redirects are not taken into account.
=> feat(browser): Add `http.redirect_count` attribute to `browser.redirect` span

.size-limit.js, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/previous-trace-links/default/test.ts, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/previous-trace-links/negatively-sampled/test.ts, dev-packages/e2e-tests/test-applications/vue-3/src/main.ts, packages/browser/src/tracing/previousTrace.ts, packages/browser/test/tracing/browserTracingIntegration.test.ts, packages/browser/test/tracing/previousTrace.test.ts
EAP currently doesn't support storing span links. This is on the EAP team's radar but will only be tackled in the future. For now, to unblock our trace linking project, this PR converts the previous trace span link into a span attribute and adds it to the root span (just like the link). We can use this in the product to check for a span link and also query the next trace by this attribute.  
Initially, the idea was to convert the link in Relay to a span attribute but this sparked a bunch of convos around how to handle "internal" attributes and if we should keep such temporary things in Relay. Nothing changes about this with the code living in the SDK but it's more a one-off and easier for us to control so after disussing this with @mydea we settled on doing it in the SDK but also …
=> ref(browser): Temporarily add `sentry.previous_trace` span attribute

dev-packages/e2e-tests/test-applications/nextjs-turbo/next.config.js, dev-packages/e2e-tests/test-applications/nextjs-turbo/tests/pages-router/client-trace-propagation.test.ts, packages/nextjs/src/client/index.ts, packages/nextjs/src/config/withSentryConfig.ts, packages/nextjs/src/edge/index.ts, packages/nextjs/src/server/index.ts
Ref: https://github.com/getsentry/sentry-javascript/issues/8105
Adds release injection for Turbopack.
=> feat(nextjs): Add release injection in Turbopack

.craft.yml
Turns out we never added the release registry entry for nuxt. The corresponding [folder exists in the release registry repo](https://github.com/getsentry/sentry-release-registry/tree/master/packages/npm/%40sentry/nuxt).
=> feat(nuxt): Add nuxt release registry craft entry

packages/remix/test/integration/package.json
Completes #15950 with the rest of the `@remix-run/*` dependencies.
=> test(remix): Bump Remix version of integration tests to `2.16.3`

packages/node/src/sdk/index.ts, packages/node/test/sdk/init.test.ts
Tried debugging the lambda layer today but this is super hard/impossible in a minimal setup without being able to set debug: true via env vars.
This PR:
- sets the `debug` option by reading `options.debug ?? process.env.SENTRY_DEBUG`
- adds unit test for a bunch of supported env variables
=> feat(node): Add support for `SENTRY_DEBUG` env variable

packages/nuxt/test/vite/sourceMaps.test.ts
Improving tests for https://github.com/getsentry/sentry-javascript/pull/15859
- added `it.each` instead of looping with `foreach`
- added tests for console output
=> test(nuxt): Improve tests for source map detection

dev-packages/node-integration-tests/suites/express/tracing/server.js, dev-packages/node-integration-tests/suites/express/tracing/test.ts, packages/node/src/integrations/http/SentryHttpInstrumentation.ts, packages/node/src/integrations/http/index.ts
This allows ignoring the request body for certain requests, which is very useful in situations of long-running requests with large/streaming request bodies which can result in a lot of memory usage
=> feat(node): Add `ignoreIncomingRequestBody` to avoid capturing request bodies

packages/tanstackstart-react/src/config/index.ts
Reported in https://github.com/getsentry/sentry-javascript/issues/14990#issuecomment-2776182271
=> fix(tss-react): Change `authToken` type to `string`

CHANGELOG.md, dev-packages/e2e-tests/test-applications/nextjs-turbo/package.json, packages/nextjs/src/config/types.ts, packages/nextjs/src/config/webpack.ts, packages/nextjs/src/config/withSentryConfig.ts
They actually unexperimentified it https://github.com/vercel/next.js/commit/2737373c3b554cba304a0af03383636bba5086e2
=> feat(nextjs): Un experimentify `clientInstrumentationHook`

packages/astro/src/server/middleware.ts, packages/astro/test/server/middleware.test.ts
Astro components are rendered in a stream, so if a component that is not the page fails during a request, this error is not thrown by the `await next()` call, only when the component is reached in the response stream.
The code was iterating over the response stream assuming it was infallible, so component errors were being ignored by sentry and hidden from the user. This PR wraps the iteration on a `try/catch` pair to report the error and forward it along to the error handling pipeline.
---
=> feat(astro): Add tracking of errors during HTML streaming

packages/core/src/client.ts, packages/core/src/logs/exports.ts, packages/core/src/server-runtime-client.ts, packages/core/test/lib/server-runtime-client.test.ts, packages/node/src/sdk/client.ts
resolves https://linear.app/getsentry/issue/LOGS-18
We got some user feedback that nodejs logging was too inconsistent. This PR improves that.
1. Add a new `flushLogs` client hook that allows us to reset server weight tracking logic more consistently. This also fixes a bug where we didn't reset weight tracking when calling `Sentry.flush`.
2. Add a `process.on('beforeExit'` listener to flush logs. Hooking onto `beforeExit` does not guarantee we flush all logs before exit, but it does increase the chances we do. 
4. Add an idle timeout that will flush logs after 5 seconds if no new logs are recorded. This should not leak memory because it is not an interval, but instead a timeout.
=> fix(node): Make log flushing logic more robust

dev-packages/browser-integration-tests/suites/public-api/logger/integration/test.ts, packages/core/src/logs/console-integration.ts
resolves https://linear.app/getsentry/issue/LOGS-12/
ref https://develop-docs-git-abhi-logs-sdk-developer-documentation.sentry.dev/sdk/telemetry/logs/#default-attributes
=> feat(core): Add sentry origin attribute to console logs integration

packages/core/src/logs/exports.ts, packages/core/test/lib/logs/exports.test.ts
fixes https://linear.app/getsentry/issue/LOGS-5
previously I wasn't matching the spec, this fixes that.
=> fix(core): Prefix release and environment correctly

packages/node/src/sdk/client.ts, packages/node/test/sdk/client.test.ts
`server.address` is the equivalent to `server_name` we attach to errors and transactions. See the spec for the attribute here: https://getsentry.github.io/sentry-conventions/generated/attributes/server.html#serveraddress
resolves https://linear.app/getsentry/issue/LOGS-32
=> feat(node): Add server.address to nodejs logs

packages/core/src/transports/base.ts
https://github.com/getsentry/sentry-javascript/issues/15993 is incredibly annoying to debug because we don't log the actual error
=> feat(core): Emit debug log when transport execution fails

packages/aws-serverless/src/integration/awslambda.ts, packages/node/src/integrations/node-fetch/index.ts, packages/node/src/integrations/tracing/graphql.ts, packages/node/src/otel/instrument.ts, packages/remix/src/server/integrations/opentelemetry.ts
In cases where we tweak the options we pass to the instrumentation, our code did not handle this very well. This could lead to certain options missing when init is called again later, as we updated the config with incomplete/wrong options.
To fix this properly, I added a new variant to `generateInstrumentOnce` which accepts a class and an options transformer, which ensures that the options are always correctly transformed, no matter if called the first or second time.
(The code to make this overloaded `generateInstrumentOnce` function work with TS was pretty tricky, but I think it is good now - type inferral etc. works nicely now!)
Fixes https://github.com/getsentry/sentry-javascript/issues/16004
=> fix(node): Ensure late init works with all integrations

packages/nextjs/src/config/withSentryConfig.ts
closes https://github.com/getsentry/sentry-javascript/issues/16025
=> fix(nextjs): Include patch version 0 for min supported 15.3.0

packages/bun/package.json, packages/bun/src/integrations/bunserver.ts, packages/bun/test/integrations/bunserver.test.ts, yarn.lock
Supercedes https://github.com/getsentry/sentry-javascript/pull/15978
resolves https://github.com/getsentry/sentry-javascript/issues/15941
resolves https://github.com/getsentry/sentry-javascript/issues/15827
resolves https://github.com/getsentry/sentry-javascript/issues/15816
Bun recently updated their `Bun.serve` API with new functionality, which unfortunately broke our existing instrumentation. This is detailed with https://bun.sh/docs/api/http#bun-serve. Specifically, they added a new routing API that looks like so:
```ts
Bun.serve({
// `routes` requires Bun v1.2.3+
routes: {
// Dynamic routes
"/users/:id": req => {
return new Response(`Hello User ${req.params.id}!`);
},
// Per-HTTP method handlers
"/api/posts": {
GET: () => new Response("List posts"),
POST: async req => {
const body = …
```
=> feat(bun): Support new `Bun.serve` APIs

packages/react-router/src/vite/buildEnd/handleOnBuildEnd.ts, packages/react-router/test/vite/buildEnd/handleOnBuildEnd.test.ts
closes https://github.com/getsentry/sentry-javascript/issues/15965
=> fix(react-router): Pass `unstable_sentryVitePluginOptions` to cli instance

packages/core/src/index.ts, packages/core/src/mcp-server.ts, packages/core/test/lib/mcp-server.test.ts
Exposes an API from the core package to wrap MCP servers to have parameterized spans (actually transactions) for the common handlers that MCP servers have.
This is super basic instrumentation for now that has shortcomings:
- no auto instrumentation yet (IITM has a bug outlined here https://github.com/nodejs/import-in-the-middle/issues/187)
- The server is a bit weird. LLMs connect to the server on an SSE endpoint (request number 1) and then they send POST requests to a different endpoint on the server. The problem is that the handlers run in the context of the SSE endpoint. This means that the traces aren't really connected yet because the `http.client` POST requests are not attached to the resource/prompt/tool handler spans in any way. I'll try to tackle this in a follow-up by patching …
=> feat(core): Add `wrapMcpServerWithSentry` to instrument MCP servers from `@modelcontextprotocol/sdk`

packages/nextjs/src/config/withSentryConfig.ts
We don't want to log for `15.3.1-canary.3`
Maybe ref https://github.com/getsentry/sentry-javascript/issues/16060 ???
=> fix(nextjs): Don't show turbopack warning for newer Next.js canaries

dev-packages/node-integration-tests/suites/anr/test.ts
Noticed this flaking sometimes, not 100% sure if this is due to the timeout, but it does not hurt I guess..
=> test(node): Increase timeout of anr tests

dev-packages/e2e-tests/test-applications/nuxt-3-dynamic-import/tests/tracing.test.ts, dev-packages/e2e-tests/test-applications/nuxt-3-min/tests/tracing.test.ts, dev-packages/e2e-tests/test-applications/nuxt-3-top-level-import/tests/tracing.test.ts, dev-packages/e2e-tests/test-applications/nuxt-3/tests/tracing.test.ts, dev-packages/e2e-tests/test-applications/nuxt-4/tests/tracing.test.ts
Check whether the baggage data is propagated correctly in connected traces.
=> test(nuxt): Add tests for trace baggage

packages/nuxt/src/runtime/plugins/sentry.server.ts, packages/nuxt/src/runtime/utils.ts, packages/nuxt/test/runtime/plugins/server.test.ts
Logging the tracing meta tags makes debugging [things like this](https://github.com/getsentry/sentry-javascript/issues/16039) easier.
=> feat(nuxt): Log when adding HTML trace meta tags

packages/node/src/integrations/http/SentryHttpInstrumentation.ts
We used to swallow most things when we try to capture request bodies of incoming requests in node. This can make it hard to debug this.
This PR adds some log messages here:
1. Logs when we successfully patched `request.on`
2. Logs the errors that happen during patching
ref https://github.com/getsentry/sentry-javascript/issues/16090
=> ref(node): Log when incoming request bodies are being captured

dev-packages/e2e-tests/test-applications/node-fastify/src/app.ts, dev-packages/e2e-tests/test-applications/node-fastify/tests/transactions.test.ts
Adding test for https://github.com/getsentry/sentry-javascript/issues/16090
=> test(fastify): Add test for request body parsing in fastify

dev-packages/e2e-tests/test-applications/node-fastify/src/app.ts, dev-packages/e2e-tests/test-applications/node-fastify/tests/transactions.test.ts, packages/node/src/integrations/http/SentryHttpInstrumentation.ts
I have a hunch that not all frameworks call `req.on('end')` but may only do `req.on('close')` or whatever else and this is why we are not reliably capturing bodies.
It should be safe to attach a `req.on('end')` handler, as that doesn't change any semantics AFAIK.
Fixes https://github.com/getsentry/sentry-javascript/issues/16090
=> fix(node): Make body capturing more robust

packages/core/src/types-hoist/options.ts
Built on top of the work of @softwarebyze in https://github.com/getsentry/sentry-javascript/pull/16098
=> chore: Improve docstrings for options and add defaults

packages/react/src/redux.ts, packages/react/test/redux.test.ts
- [ X ] If you've added code that should be tested, please add tests.
- [ X ] Ensure your code lints and the test suite passes (`yarn lint`) & (`yarn test`).
=> fix(react): Fix Redux integration failing with reducer injection

packages/astro/src/index.server.ts, packages/aws-serverless/src/index.ts, packages/bun/src/index.ts, packages/cloudflare/src/index.ts, packages/deno/src/index.ts, packages/google-cloud-serverless/src/index.ts, packages/node/src/index.ts, packages/vercel-edge/src/index.ts
Exports the `wrapMcpServerWithSentry` which is our MCP server instrumentation from all the server packages.
Fixes https://github.com/getsentry/sentry-javascript/issues/16111
=> feat: Export `wrapMcpServerWithSentry` from server packages

packages/node/src/sdk/initOtel.ts
Adding Node 21 to the accepted version range for `module.register` as it is already supported (https://nodejs.org/docs/v21.0.0/api/module.html).
This also causes the customization hook not to call register (maybe a reason why some packages in issue https://github.com/getsentry/sentry-javascript/issues/14202 are not instrumented): https://github.com/getsentry/sentry-javascript/blob/59094afb6ab53ac33b87b83f70eea9d13e4c2291/packages/node/src/sdk/initOtel.ts#L45-L65
--- 
Additionally, the above mentioned issue https://github.com/getsentry/sentry-javascript/issues/14202 shows the following warning although it's using v21:
```
[Sentry] You are using Node.js in ESM mode ("import syntax"). The Sentry Node.js SDK is not compatible with ESM in Node.js versions before 18.19.0 or before 20.6.0. …
```
=> fix(node): Update version range for `module.register`

dev-packages/e2e-tests/test-applications/create-remix-app-v2/package.json, dev-packages/e2e-tests/test-applications/remix-hydrogen/tests/server-transactions.test.ts, packages/remix/src/server/instrumentServer.ts, packages/remix/test/integration/test/server/instrumentation/action.test.ts, packages/remix/test/integration/test/server/instrumentation/loader.test.ts
Resolves: https://github.com/getsentry/sentry-javascript/issues/16075
We used to allow rewrapping of the root loader when we had a separate Express adapter, where we could not determine the instrumentation order. Now that we don't have it anymore, we can remove this. Still, can't reproduce the original issue running e2e test apps under load. But it's clear that's what caused it.
=> fix(remix): Avoid rewrapping root loader.

dev-packages/e2e-tests/test-applications/node-express/package.json, dev-packages/e2e-tests/test-applications/node-express/src/app.ts, dev-packages/e2e-tests/test-applications/node-express/src/mcp.ts, dev-packages/e2e-tests/test-applications/node-express/tests/mcp.test.ts, dev-packages/e2e-tests/test-applications/node-express/tsconfig.json, packages/core/src/mcp-server.ts, packages/core/test/lib/mcp-server.test.ts
This PR adds a best effor mechanism to associate handler spans for `resource`, `tool` and `prompt` with the incoming message requests instead of the outgoing SSE response.
The work is based on the upstream PR which exposes the request id on the handler metadata: https://github.com/modelcontextprotocol/typescript-sdk/pull/358
This PR actually also fixes a bug where we were instrumenting the registering of the handler instead of the actual handler 🤦‍♂️.
One thing to note in this PR is that it has a risk of being slightly memory leaky. We are storing away spans by session and request id and cleaning them up when they are used. In the case of long lived sessions the span will not be garbage collected for a long time. There is unfortunately no way of doing a weak reference because session id …
=> feat(core): Associate resource/tool/prompt invocations with request span instead of response span

dev-packages/e2e-tests/test-applications/remix-hydrogen/package.json, packages/core/src/mcp-server.ts
Seems like `@shopify/mini-oxygen@3.2.1` breaks something. I somewhat suspect that they bumped a vite version but I didn't find a changelog yet
This should unblock the PRs we want to include in Today's release
Update: https://github.com/Shopify/hydrogen/pull/2863 likely caused this
=> test(e2e): Pin `@shopify/mini-oxygen` to 3.2.0 to fix build error

packages/core/src/mcp-server.ts, packages/react-router/src/vite/buildEnd/handleOnBuildEnd.ts, packages/react-router/src/vite/makeCustomSentryVitePlugins.ts, packages/react-router/test/vite/buildEnd/handleOnBuildEnd.test.ts, packages/react-router/test/vite/makeCustomSentryVitePlugins.test.ts, packages/react-router/test/vite/plugin.test.ts
Some of `unstable_sentryVitePluginOptions` were not spread into the final config object correctly. 
closes https://github.com/getsentry/sentry-javascript/issues/16153
=> fix(react-router): Spread `unstable_sentryVitePluginOptions` correctly

dev-packages/node-integration-tests/package.json, dev-packages/node-integration-tests/suites/express-v5/tracing/test.ts, dev-packages/node-integration-tests/suites/express-v5/without-tracing/test.ts, dev-packages/node-integration-tests/suites/express/tracing/test.ts, dev-packages/node-integration-tests/suites/express/without-tracing/test.ts, dev-packages/node-integration-tests/suites/tracing/meta-tags/test.ts, dev-packages/node-integration-tests/utils/runner.ts, yarn.lock
This removes usage of `axios` in our node-integration-test runner, in favor of just using `fetch`.
=> test(node): Remove `axios` in favor of using `fetch`

packages/vercel-edge/src/index.ts, packages/vercel-edge/src/logs/exports.ts
Similar to https://github.com/getsentry/sentry-javascript/pull/16165
Ensures we have logs support for the Next.js Edge Runtime.
resolves https://github.com/getsentry/sentry-javascript/issues/16151
=> feat(vercel-edge): Add logs export

packages/feedback/src/core/components/Actor.ts, packages/feedback/src/modal/integration.tsx, packages/feedback/test/core/components/Actor.test.ts
An internal user reported seeing "NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node." and the replay of their session confirms it: https://sentry.sentry.io/explore/replays/127444034ae84099a84b524458b6dd90/
However, there is no matching JS error to give more clues.
What I think happened is that after interacting with the Feedback SDK the widget got into a state where it was no longer mounted into the page, but we called `removeFromDom()` anyway. 
Looking at the replay i saw the moment when the feedback dom was aded to the page, but it wasn't visible, only this got added at 18:51:
So something prevented it from opening all the way up.
Fixes https://github.com/getsentry/sentry/issues/89424
=> fix(feedback): Prevent `removeFromDom()` from throwing

packages/cloudflare/src/durableobject.ts, packages/cloudflare/src/handler.ts, packages/cloudflare/src/index.ts, packages/cloudflare/src/instrument.ts, packages/cloudflare/src/request.ts
This PR introduces a new `instrumentDurableObjectWithSentry` method to the SDK, which instruments durable objects. We capture both traces and errors automatically.
Usage:
```ts
class MyDurableObjectBase extends DurableObject<Env> {
// impl
}
// Export your named class as defined in your wrangler config
export const MyDurableObject = Sentry.instrumentDurableObjectWithSentry(
// need to define options again because durable objects can be in a separate instance
// to the cloudflare worker 
(env) => ({
dsn: env.SENTRY_DSN,
}),
MyDurableObjectBase,
);
```
This should work with websockets, and thus https://github.com/getsentry/sentry-mcp as well.
This PR also refactors some types in `packages/cloudflare/src/handler.ts` with the `withSentry` method, which should prevent …
=> feat(cloudflare): Add support for durable objects

dev-packages/browser-integration-tests/suites/tracing/request/xhr-merged-baggage-headers/subject.js, dev-packages/browser-integration-tests/suites/tracing/request/xhr-merged-baggage-headers/test.ts, dev-packages/browser-integration-tests/suites/tracing/request/xhr-with-custom-sentry-headers/subject.js, dev-packages/browser-integration-tests/suites/tracing/request/xhr-with-custom-sentry-headers/test.ts, packages/browser/src/tracing/request.ts
Analogously to #16183 for `fetch`, this PR ensures that manually set `sentry-trace` and `baggage` headers in XHR requests are respected by our XHR instrumentation and not overwritten.
This also fixes a bug where we'd append multiple `sentry-trace` or `baggage` values in case the header was somehow set more than once (analogously to https://github.com/getsentry/sentry-javascript/pull/13907 for `fetch`)
Added two integration tests to demonstrate correct behaviour.
Came up in https://linear.app/getsentry/issue/FE-380/debug-trace-context-propagation-issue-from-tanstack-to-go-backend
bundle-size wise, this probably amortizes the savings from #16183 🙃
=> fix(browser): Respect manually set sentry tracing headers in XHR requests

packages/react-router/src/vite/index.ts, packages/react-router/src/vite/makeConfigInjectorPlugin.ts, packages/react-router/src/vite/plugin.ts, packages/react-router/test/vite/plugin.test.ts
Fixes: https://github.com/getsentry/sentry-javascript/issues/15520
Add a new plugin `makeConfigInjectorPlugin` within our existing vite plugin that updates the global vite config with sentry options 
- [ ✅] If you've added code that should be tested, please add tests.
- [ ✅] Ensure your code lints and the test suite passes (`yarn lint`) & (`yarn test`).
=> feat(react-router): Create a Vite plugin that injects sentryConfig into the global vite config

.size-limit.js, dev-packages/node-integration-tests/src/index.ts, dev-packages/node-integration-tests/suites/express-v5/tracing/instrument.mjs, dev-packages/node-integration-tests/suites/express-v5/tracing/scenario.mjs, dev-packages/node-integration-tests/suites/express-v5/tracing/test.ts, dev-packages/node-integration-tests/suites/express-v5/tracing/updateName/test.ts, dev-packages/node-integration-tests/suites/express-v5/tracing/withError/test.ts, dev-packages/node-integration-tests/suites/express-v5/tsconfig.test.json, dev-packages/node-integration-tests/suites/express/tracing/instrument.mjs, dev-packages/node-integration-tests/suites/express/tracing/scenario.mjs, dev-packages/node-integration-tests/suites/express/tracing/test.ts, dev-packages/node-integration-tests/suites/tsconfig.json
This updates naming etc. for express (v5) tests, and makes sure that we test this in esm & cjs in a basic way.
It also adds test for handling of the root route (`/`) as well as 404, where current failures are shown (see https://github.com/getsentry/sentry-javascript/issues/16203).
=> test(node): Update express integration tests

dev-packages/node-integration-tests/suites/vercel/instrument.mjs, dev-packages/node-integration-tests/suites/vercel/scenario.mjs, dev-packages/node-integration-tests/suites/vercel/test.ts, packages/node/src/integrations/http/SentryHttpInstrumentationBeforeOtel.ts
As pre-work for https://github.com/getsentry/sentry-javascript/pull/16178, actually add a test for this (kind of). This showed that there was actually a fundamental flaw here, as we looked as the `req` not the `res`, oops.
=> fix(node): Fix vercel flushing logic & add test for it

dev-packages/node-integration-tests/suites/express-v5/tracing/test.ts, packages/node/src/integrations/tracing/express-v5/instrumentation.ts
Closes https://github.com/getsentry/sentry-javascript/issues/16210
=> fix(node): Fix 404 route handling in express 5

dev-packages/e2e-tests/test-applications/nextjs-14/tests/generation-functions.test.ts, dev-packages/e2e-tests/test-applications/nextjs-app-dir/app/route-handlers/[param]/route.ts, dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/route-handlers.test.ts, dev-packages/e2e-tests/test-applications/node-express/src/app.ts, dev-packages/e2e-tests/test-applications/node-express/tests/trpc.test.ts, dev-packages/e2e-tests/test-applications/node-hapi/src/app.js, dev-packages/e2e-tests/test-applications/node-hapi/tests/errors.test.ts, dev-packages/node-integration-tests/suites/express-v5/tracing/instrument-filterStatusCode.mjs, dev-packages/node-integration-tests/suites/express-v5/tracing/scenario-filterStatusCode.mjs, dev-packages/node-integration-tests/suites/express-v5/tracing/test.ts, dev-packages/node-integration-tests/suites/express/tracing/instrument-filterStatusCode.mjs, dev-packages/node-integration-tests/suites/express/tracing/scenario-filterStatusCode.mjs, dev-packages/node-integration-tests/suites/express/tracing/test.ts, packages/node/src/integrations/http/index.ts
This can be configured like this:
```js
httpIntegration({
dropSpansForIncomingRequestStatusCodes: [404, [300,399]]
})
```
It defaults to `[404]`. 
Closes https://github.com/getsentry/sentry-javascript/issues/16193
=> feat(node): Drop `http.server` spans with 404 status by default

dev-packages/e2e-tests/test-applications/node-express/src/app.ts, dev-packages/e2e-tests/test-applications/node-express/tests/logs.test.ts, packages/core/src/logs/exports.ts, packages/core/src/utils-hoist/worldwide.ts
resolves https://github.com/getsentry/sentry-javascript/issues/16110
Stores the Client to LogBuffer WeakMap onto the global object so logs can be retrieved correctly during flushing. Previously, the WeakMap reference would be different at flush time, causing no logs to be found for any given client.
Adds an express e2e tests to ensure logs are flushed correctly.
=> fix(logs): Ensure logs can be flushed correctly

packages/cloudflare/src/durableobject.ts, packages/cloudflare/src/handler.ts, packages/cloudflare/src/options.ts, packages/cloudflare/test/handler.test.ts, packages/cloudflare/test/options.test.ts, packages/cloudflare/tsconfig.json
This PR enables reading the `SENTRY_RELEASE` variable from the CF `env` that users should pass to their `withSentry` worker wrapper. This is quite similar to how we'd usually access env variables in Node-based SDKs.
We need this for uploading release-based source maps for CF worker functions being bundled and deployed by wrangler.
see https://github.com/getsentry/sentry-wizard/issues/824#issuecomment-2851533722
ref https://linear.app/getsentry/issue/WIZARD-36/improve-sentrywizard-i-sourcemaps-for-cloudflarewrangler
=> feat(cloudflare): Read `SENTRY_RELEASE` from `env`

.github/workflows/build.yml, packages/profiling-node/package.json, packages/profiling-node/src/integration.ts, scripts/ci-unit-tests.ts, yarn.lock
resolves https://github.com/getsentry/sentry-javascript/issues/16058
Profiling binary bump: https://github.com/getsentry/sentry-javascript-profiling-node-binaries/pull/12
=> feat: Support Node 24

.github/workflows/build.yml, packages/remix/test/integration/test/client/capture-exception.test.ts, packages/remix/test/integration/test/client/capture-message.test.ts, packages/remix/test/integration/test/client/click-error.test.ts, packages/remix/test/integration/test/client/errorboundary.test.ts, packages/remix/test/integration/test/client/manualtracing.test.ts, packages/remix/test/integration/test/client/meta-tags.test.ts, packages/remix/test/integration/test/client/pageload.test.ts, packages/remix/test/integration/test/client/root-loader.test.ts, packages/remix/test/integration/test/server/instrumentation/loader.test.ts
Resolves: #16239 
Looks like importing types without `type` fails on Node 24.
=> fix(test): Make Remix integration tests Node 24 compatible

scripts/ci-unit-tests.ts
resolves https://github.com/getsentry/sentry-javascript/issues/16238
The error with the google cloud serverless tests in Node 24 was only happening in Node `24.0.0`, which was fixed in [`24.0.1`](https://github.com/nodejs/node/releases/tag/v24.0.1), so we can safely re-enable everything.
=> chore(ci): re-enable Node 24 tests for google-cloud-serverless

.github/workflows/build.yml
Node [`24.0.1`](https://github.com/nodejs/node/releases/tag/v24.0.1) fixed a bug with our google cloud serverless tests that we were running into in https://github.com/getsentry/sentry-javascript/issues/16238
For some reason CI doesn't want to use it? So pinning to `^24.0.1`.
=> build: Pin node unit tests to ^24.0.1

dev-packages/node-integration-tests/suites/esm/warn-esm/test.ts, packages/bun/scripts/install-bun.js, packages/node/src/sdk/initOtel.ts
I noticed that my bun version locally was old, leading to weird test issues.
Now, our install script will ensure this is the latest version. On CI, we already test against the latest version.
(Noticed this because bun 1.0.2 which I had installed reports itself as Node 18.5.0 which lead to ESM warnings)
=> ref(bun): Ensure bun is latest for local tests

packages/node/package.json, yarn.lock
The `@fastify/otel` instrumentation uses OpenTelemetry v2, but for the time being Sentry only supports OpenTelemetry v1. We forked the library at https://github.com/getsentry/fastify-otel/tree/otel-v1 and downgraded its dependencies to OpenTelemetry v1.
For the downgrade work in the fork see: https://github.com/getsentry/fastify-otel/commit/7893f7044bcdd37acfea10f098571f54740c504b
**Note**: This also bumps the instrumentation from `0.6.0` to `0.8.0`.
Resolves: #16245
=> fix(node): Use sentry forked `@fastify/otel` dependency with pinned Otel v1 deps

dev-packages/e2e-tests/test-applications/nextjs-turbo/package.json, packages/node/package.json, yarn.lock
See https://github.com/nodejs/import-in-the-middle/releases/tag/import-in-the-middle-v1.13.1
* handling of circular dependencies ([#181](https://github.com/nodejs/import-in-the-middle/issues/181)) ([b58092e](https://github.com/nodejs/import-in-the-middle/commit/b58092ec9becf4a14f541da4cf5bfb190f2a9a9b))
* importing JSON files ([#182](https://github.com/nodejs/import-in-the-middle/issues/182)) ([8c52014](https://github.com/nodejs/import-in-the-middle/commit/8c52014658fcf698cc340d032b441d9e7a65be36))
* warning from use of context.importAssertions ([#179](https://github.com/nodejs/import-in-the-middle/issues/179)) ([8e56cf1](https://github.com/nodejs/import-in-the-middle/commit/8e56cf1e89752e6c8768d648c10c12fb3178e2ae))
This version is already allowed by our range, but in order to ensure …
=> deps(node): Bump `import-in-the-middle` to `1.13.1`

packages/cloudflare/src/request.ts, packages/cloudflare/test/request.test.ts, packages/core/src/index.ts, packages/core/src/utils-hoist/url.ts, packages/core/test/utils-hoist/url.test.ts
While helping debug work in https://github.com/getsentry/sentry-mcp, I noticed that we didn't attach `url.path` to the http fetch spans, which made using the trace explorer harder to use.
This PR updates the cloudflare http instrumentation (fetch handlers for regular workers and durable objects) to use a new `getHttpSpanDetailsFromUrlObject` abstraction I built.
`getHttpSpanDetailsFromUrlObject` returns the http span name and it's associated attributes, taking care to handle source, route names, and handling both relative and full URLs.
This is related to all the https://github.com/getsentry/sentry-javascript/issues/15767 work I've been doing.
=> feat(cloudflare): Improve http span data

yarn.lock
Forgot to update the lockfile after updating the minimatch dep on our fastiy/otel fork.
=> chore: Update lockfile for fastify-otel fork

dev-packages/node-integration-tests/suites/tracing/requests/http-no-tracing-no-spans/test.ts, packages/core/src/utils-hoist/baggage.ts, packages/core/src/utils-hoist/debug-build.ts, packages/core/src/utils-hoist/dsn.ts, packages/core/src/utils-hoist/instrument/handlers.ts, packages/core/src/utils-hoist/logger.ts, packages/core/src/utils-hoist/object.ts, packages/core/src/utils-hoist/supports.ts, packages/core/test/utils-hoist/dsn.test.ts
Noticed we still have this twice from the utils-hoist folder.
=> ref(core): Remove duplicate internal `DEBUG_BUILD` constant

.size-limit.js, dev-packages/size-limit-gh-action/package.json, dev-packages/size-limit-gh-action/utils/SizeLimitFormatter.mjs, yarn.lock
By us providing an empty terser plugin we actually get weird results (the browser variant with tree shaking was actually larger then the default one :O). We can just use the defaults here.
I also updated the GH action to use `bytes-iec` instead of `bytes` package for rendering the sizes - this is also what size-limit itself uses, so this should be better aligned now. Values may _look_ larger now because it formats as `kB` now (so factors of 1000) instead of `KiB` (factors of 1024).
=> ci: Improve size limit tree shaking handling

packages/react/src/reactrouterv3.ts, packages/react/test/reactrouterv3.test.tsx
We noticed that routes like `/teams/:teamId/details` were normalized to `/teams:teamIddetails` which is missing `/` and is incorrect.
This PR updates the tests for the React Router v3 integration to ensure correct transaction name normalization for nested parameterized routes.
Specifically, it modifies the `normalizes transaction name` test case to include navigation to a route like `/teams/:teamId/details` and verifies that the resulting transaction name is correctly normalized. This addresses an issue where similar nested route patterns might not be handled correctly.
=> fix(react): Handle nested parameterized routes in reactrouterv3 transaction normalization

packages/remix/package.json, packages/remix/src/server/errors.ts, packages/remix/src/server/integrations/opentelemetry.ts, packages/remix/src/utils/utils.ts, packages/remix/src/vendor/instrumentation.ts, yarn.lock
Resolves: #15739
- Removed Remix v1-related instrumentation code from the original implementation while vendoring in.
- Also, FormData entries for manual instrumentation are aligned with OTEL use.
Resolves: https://github.com/getsentry/sentry-javascript/issues/16140
=> feat(remix): Vendor in `opentelemetry-instrumentation-remix`

.size-limit.js, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/navigation-aborting-pageload/init.js, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/navigation-aborting-pageload/test.ts, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/navigation/test.ts, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/pageload/test.ts, packages/browser/src/tracing/browserTracingIntegration.ts
Noticed that this now has `externalFinish` as reason, which is not really helpful. With this, you should be able to see that the pageload/navigation was ended because a new one started.
=> fix(browser): Ensure spans auto-ended for navigations have `cancelled` reason

packages/node/package.json, yarn.lock
The previous approach of specifying the git repo directly breaks systems that don't have git installed (e.g. slim linux distros). I tested this works on a ubuntu vm without git.
**Important:** When making changes to the fork, the linked commit sha in `packages/node/package.json` has to be updated and the yarn lockfile regenerated.
Resolves: #16281
=> fix(node): Pin `@fastify/otel` fork to direct url to allow installing without git

dev-packages/browser-integration-tests/suites/integrations/Breadcrumbs/history/navigation/test.ts, dev-packages/browser-integration-tests/suites/replay/multiple-pages/test.ts, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/navigation-aborting-pageload/init.js, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/navigation-aborting-pageload/test.ts, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/navigation/test.ts, packages/browser-utils/src/instrument/history.ts, packages/browser/src/helpers.ts, packages/browser/src/integrations/httpcontext.ts, packages/browser/src/tracing/browserTracingIntegration.ts, packages/browser/test/tracing/browserTracingIntegration.test.ts, packages/core/src/tracing/sentrySpan.ts, packages/core/src/types-hoist/instrument.ts
This PR fixes two things about our idle spans emitted from `browserTracingIntegration`:
1. The navigation name was sometimes incorrect. This is because we look at `window.location.pathname` at the time when the `popstate` event is emitted - but at this point, this may not be updated yet. So a `navigation` transaction would possibly have the pathname of the previous page as transaction name.
2. The request data is also possibly incorrect - this is set by `HttpContext` integration at event processing time. However, at this time the `window.location` data is also usually already of the following navigation, so the pageload would often have wrong request data associated to it. Now, we store this on the current scope at span creation time to ensure it is actually correct.
=> fix(browser): Ensure pageload & navigation spans have correct data

dev-packages/e2e-tests/test-applications/react-router-7-framework/app/routes.ts, dev-packages/e2e-tests/test-applications/react-router-7-framework/app/routes/performance/server-action.tsx, dev-packages/e2e-tests/test-applications/react-router-7-framework/tests/performance/performance.server.test.ts, packages/react-router/src/server/sdk.ts
Work for this was basically already done in https://github.com/getsentry/sentry-javascript/pull/16147
This PR just adds a check for POST requests in the event processor + an e2e test
closes https://github.com/getsentry/sentry-javascript/issues/15195
=> feat(react-router): Add server action instrumentation

dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/server-components.test.ts, packages/nextjs/src/server/index.ts
closes https://github.com/getsentry/sentry-javascript/issues/15634
=> fix(nextjs): Preserve `next.route` attribute on root spans

packages/cloudflare/src/durableobject.ts
fixes https://github.com/getsentry/sentry-javascript/issues/16247
By adjusting the generic, we'll make sure that we don't erase static fields with the `instrumentDurableObjectWithSentry` function. See an example below:
```js
class MyDurableObjectBase extends DurableObject {
public static readonly VERSION = '1.0.0';
}
const MyDurableObject = instrumentDurableObjectWithSentry(
() => ({
dsn: 'https://example.com/sentry',
}),
MyDurableObjectBase,
);
console.log(MyDurableObject.VERSION); // This will now work correctly
```
By moving the `DurableObjectClass` into it's own generic (`new (state: DurableObjectState, env: E) => T`), which we named `C`, it helps preserve the exact constructor type of the input class, including all its static properties and methods.
This was …
=> fix(cloudflare): Account for static fields in wrapper type

.size-limit.js, dev-packages/node-integration-tests/suites/tracing/tracePropagationTargets/baggage-org-id/server-no-explicit-org-id.ts, dev-packages/node-integration-tests/suites/tracing/tracePropagationTargets/baggage-org-id/server-no-org-id.ts, dev-packages/node-integration-tests/suites/tracing/tracePropagationTargets/baggage-org-id/server.ts, dev-packages/node-integration-tests/suites/tracing/tracePropagationTargets/baggage-org-id/test.ts, packages/browser/test/tracing/browserTracingIntegration.test.ts, packages/core/src/tracing/dynamicSamplingContext.ts, packages/core/src/types-hoist/envelope.ts, packages/core/src/types-hoist/options.ts, packages/core/src/utils-hoist/dsn.ts, packages/core/test/lib/tracing/dynamicSamplingContext.test.ts, packages/core/test/utils-hoist/dsn.test.ts
Adds the organization ID to the DSC (dynamic sampling context). This will add the org ID as `sentry-org_id` to the baggage.
This org ID is parsed from the DSN. With the `orgId` option it's possible to overwrite the automatically parsed organization ID.
closes https://github.com/getsentry/sentry-javascript/issues/16290
=> feat(core): Add `orgId` option to `init` and DSC (`sentry-org_id` in baggage)

dev-packages/e2e-tests/test-applications/nestjs-distributed-tracing/src/events.controller.ts, dev-packages/e2e-tests/test-applications/nestjs-distributed-tracing/src/events.service.ts, dev-packages/e2e-tests/test-applications/nestjs-distributed-tracing/src/listeners/test-event.listener.ts, dev-packages/e2e-tests/test-applications/nestjs-distributed-tracing/tests/events.test.ts, packages/nestjs/src/integrations/sentry-nest-event-instrumentation.ts, packages/nestjs/test/integrations/nest.test.ts
Problem is that within the execution there is no way of detecting the triggering event.
- Because of this we now emit a merged transaction name of all applied events – but will add a note on docs that we recommend just putting one decorator per function. We do this by reading the metadata applied on the function by nestjs.
- Adds a flag to avoid double wrapping of the descriptor value (this way we get the correct payload per event and make sure the handler is executed for each event) 
closes https://github.com/getsentry/sentry-javascript/issues/15218
=> fix(nestjs): Handle multiple `OnEvent` decorators

dev-packages/node-integration-tests/suites/tracing/requests/fetch-breadcrumbs/scenario.mjs, dev-packages/node-integration-tests/suites/tracing/requests/fetch-breadcrumbs/test.ts, dev-packages/node-integration-tests/suites/tracing/requests/http-breadcrumbs/scenario.mjs, packages/node/src/integrations/http/SentryHttpInstrumentation.ts, packages/node/src/integrations/node-fetch/SentryNodeFetchInstrumentation.ts
It was noticed that we were creating breadcrumbs for sentry-internal requests, which is not desired. This was introduced by us moving breadcrumb generation out of the base http/fetch instrumentation into our own, where we did not look at `suppressTracing`. Now, when tracing is suppressed, no fetch/http breadcrumbs will be created.
=> fix(node): Avoid creating breadcrumbs for suppressed requests

packages/remix/src/cloudflare/index.ts, packages/remix/src/index.server.ts
Resolves: #16298 
Also exported `ErrorBoundary` and `browserTracingIntegration` from `cloudflare` entry.
=> fix(remix): Add missing `client` exports to `server` and `cloudflare` entries

packages/browser/src/exports.ts, packages/browser/src/report-dialog.ts, packages/browser/src/sdk.ts, packages/browser/test/tracing/browserTracingIntegration.test.ts
Just a small refactor, noticed this while working on other browser sdk stuff. Moving this into a dedicated file decouples this from the core SDK functionality, which this IMHO is not (anymore). Also, we can streamline the code slightly for efficiency.
=> ref(browser): Streamline `showReportDialog` code

dev-packages/browser-integration-tests/suites/manual-client/skip-init-browser-extension/test.ts, dev-packages/browser-integration-tests/suites/manual-client/skip-init-chrome-extension/test.ts, packages/browser/src/sdk.ts, packages/browser/test/sdk.test.ts, packages/core/src/index.ts, packages/core/src/utils-hoist/supports.ts
Extracted this out of https://github.com/getsentry/sentry-javascript/pull/15307
This PR:
1. Moves things around in the `sdk.ts` file a bit, moving types & consts to the top of the file
2. Removes an "unecessary" log around fetch not being supported: This log has two problems. First, it is not actually logged, because we do `logger.log()` before running `init()`, which would actually set the logger up. So the log would never show up. Second, the log is superfluous, if the (default) fetch transport fails to send because fetch is not available, you get a warning anyhow for this.
3. Streamlines the browser extension check code slightly.
Closes https://github.com/getsentry/sentry-javascript/issues/16284
=> ref(browser): Streamline browser `init()` checks

packages/remix/src/cloudflare/index.ts, packages/remix/src/server/instrumentServer.ts
Closes: #15615 
Ref: https://github.com/getsentry/sentry-javascript/issues/15615#issuecomment-2887533896
Looks like `createRequestHandler` exported from `@shopify/remix-oxygen` does not accept a function that returns/resolves a `ServerBuild`. [It only accepts a plain `ServerBuild`](https://github.com/Shopify/hydrogen/blob/a7e33c1dd45e3c7c27ab2e1125851468051cee0b/packages/remix-oxygen/src/server.ts#L20).
=> fix(remix): Use generic types for `ServerBuild` argument and return

.size-limit.js, packages/browser-utils/src/metrics/browserMetrics.ts, packages/browser-utils/test/browser/browserMetrics.test.ts
It seems like this change introduced a problem where accessing `event.detail` causes a `DOMException` to be thrown (only on firefox?). This is causing the SDK to crash if someone has tracing enabled. Until we figure out a reproduction and a more formal fix (with some e2e tests) let's revert the problematic PR and move forward.
Reverts getsentry/sentry-javascript#16240
ref https://github.com/getsentry/sentry-javascript/issues/16347
=> Revert "feat(browser): Track measure detail as span attributes"

dev-packages/e2e-tests/test-applications/react-router-7-framework/react-router.config.ts, dev-packages/e2e-tests/test-applications/react-router-7-framework/tests/performance/pageload.client.test.ts, dev-packages/e2e-tests/test-applications/react-router-7-framework/tests/performance/trace-propagation.test.ts
It was confirmed that static pre-renders don't pick up Sentry trace meta tags — this just adds a quick test.
More context: https://linear.app/getsentry/issue/JS-392/rr7-evaluate-static-pre-rendering
P.S. Not a priority, but for some reason, I had to add a trailing / to fetch the correct transactions and pass the tests. I’ll look into why this is happening for transaction route names and whether this behavior is expected in a later PR.
=> test(react-router): Add and fix tests for pre rendered routes

packages/node/src/integrations/http/SentryHttpInstrumentation.ts, packages/node/src/integrations/http/index.ts
This PR just fixes incorrect JSDoc where I missed a mix-up of incoming and outgoing requests for the `ignoreIncomingRequestBody` option while reviewing. Raised in https://github.com/getsentry/sentry-docs/pull/13698/files#r2088760944
=> doc(node): Fix `ignoreIncomingRequestBody` JSDoc

packages/browser/src/client.ts
This was tied together and could theoretically result in logs not being flushed correctly, when users opt-out of client reports.
Noticed this while scanning over the browser client code :)
=> fix(browser): Ensure logs are flushed when sendClientReports=false

packages/core/src/index.ts, packages/core/src/logs/exports.ts
I renamed `defaultCaptureSerializedLog` to `_INTERNAL_captureSerializedLog` and exported it so it can be accessed from other SDKs.
I will use this in the Electron SDK in the root main process to add logs passed by IPC from other processes to the queue.
=> feat(core): Export `_INTERNAL_captureSerializedLog`

dev-packages/browser-integration-tests/suites/integrations/supabase/auth/test.ts, dev-packages/browser-integration-tests/suites/integrations/supabase/db-operations/test.ts, dev-packages/e2e-tests/test-applications/supabase-nextjs/tests/performance.test.ts, packages/core/src/integrations/supabase.ts
DB must be set to populate query/database insights
=> feat(core): Make sure Supabase db query insights are populated

packages/core/src/logs/exports.ts, packages/core/test/lib/logs/exports.test.ts
resolves https://linear.app/getsentry/issue/JS-294
ref https://develop.sentry.dev/sdk/telemetry/logs/#user-attributes
=> feat(core): Add user to logs

.github/workflows/build.yml, .github/workflows/canary.yml, dev-packages/e2e-tests/test-applications/angular-20/package.json
This PR adds canary tests for the `@angular/*@next` packages. The tests are based on our `angular-20` e2e test app just like in our other canary tests, we manually install the preview versions of the packages and the run the app and the tests.
closes #16379 
closes #16365
=> test(angular): Add Angular `next` canary tests

packages/browser/src/exports.ts, packages/browser/src/index.ts
resolves https://github.com/getsentry/sentry-javascript/issues/16418
=> feat(browser): Export getTraceData from the browser sdks

dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/ignoreMeasureSpans/init.js, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/ignoreMeasureSpans/test.ts, packages/browser-utils/src/metrics/browserMetrics.ts, packages/browser-utils/test/browser/browserMetrics.test.ts, packages/browser/src/tracing/browserTracingIntegration.ts
- Adds `ignorePerformanceApiSpans` option that matches span names of `mark` and `measure` spans to a given array or RegExp
- Adds unit tests
- Adds integration test
Usage:
```js
Sentry.init({
dsn: '...',
Sentry.browserTracingIntegration({
ignorePerformanceApiSpans: ['measure-ignore', /mark-to-ignore/],
}),
],
tracesSampleRate: 1,
});
```
closes #16441
=> feat(browser): Add option to ignore `mark` and `measure` spans

packages/node/src/sdk/client.ts, packages/node/src/types.ts, packages/node/test/sdk/client.test.ts
=> feat(node): Add `includeServerName` option

dev-packages/e2e-tests/test-applications/nextjs-orpc/.gitignore, dev-packages/e2e-tests/test-applications/nextjs-orpc/.npmrc, dev-packages/e2e-tests/test-applications/nextjs-orpc/next-env.d.ts, dev-packages/e2e-tests/test-applications/nextjs-orpc/next.config.js, dev-packages/e2e-tests/test-applications/nextjs-orpc/package.json, dev-packages/e2e-tests/test-applications/nextjs-orpc/playwright.config.mjs, dev-packages/e2e-tests/test-applications/nextjs-orpc/sentry.edge.config.ts, dev-packages/e2e-tests/test-applications/nextjs-orpc/sentry.server.config.ts, dev-packages/e2e-tests/test-applications/nextjs-orpc/src/app/client-error/page.tsx, dev-packages/e2e-tests/test-applications/nextjs-orpc/src/app/client/page.tsx, dev-packages/e2e-tests/test-applications/nextjs-orpc/src/app/global-error.tsx, dev-packages/e2e-tests/test-applications/nextjs-orpc/src/app/layout.tsx, dev-packages/e2e-tests/test-applications/nextjs-orpc/src/app/page.tsx, dev-packages/e2e-tests/test-applications/nextjs-orpc/src/app/rpc/[[...rest]]/route.ts, dev-packages/e2e-tests/test-applications/nextjs-orpc/src/components/FindPlanet.tsx, dev-packages/e2e-tests/test-applications/nextjs-orpc/src/instrumentation-client.ts, dev-packages/e2e-tests/test-applications/nextjs-orpc/src/instrumentation.ts, dev-packages/e2e-tests/test-applications/nextjs-orpc/src/orpc/client.ts, dev-packages/e2e-tests/test-applications/nextjs-orpc/src/orpc/router.ts, dev-packages/e2e-tests/test-applications/nextjs-orpc/src/orpc/sentry-middleware.ts, dev-packages/e2e-tests/test-applications/nextjs-orpc/src/orpc/server.ts, dev-packages/e2e-tests/test-applications/nextjs-orpc/start-event-proxy.mjs, dev-packages/e2e-tests/test-applications/nextjs-orpc/tests/orpc-error.test.ts, dev-packages/e2e-tests/test-applications/nextjs-orpc/tests/orpc-tracing.test.ts, dev-packages/e2e-tests/test-applications/nextjs-orpc/tsconfig.json, dev-packages/e2e-tests/test-applications/nextjs-t3/package.json
Basic e2e for making sure tracing looks ok for orpc calls
=> test(nextjs): Add e2e test for orpc

dev-packages/e2e-tests/test-applications/node-exports-test-app/scripts/consistentExports.ts, packages/astro/src/index.server.ts, packages/aws-serverless/src/index.ts, packages/bun/src/index.ts, packages/google-cloud-serverless/src/index.ts, packages/node/src/index.ts, packages/react-router/src/server/sdk.ts, packages/react-router/test/server/sdk.test.ts
This PR conditionally instruments the server runtime of react-router, as there have been [instrumentation issues](https://github.com/getsentry/sentry-javascript/issues/16327). 
- Only instruments RR for node 20 (min version for react router) up to 20.19 (where we started seeing issues).
- Exports the NODE_VERSION helper from `@sentry/node`
=> fix(react-router): Conditionally add `ReactRouterServer` integration

dev-packages/node-integration-tests/suites/express-v5/handle-error-scope-data-loss/server.ts, dev-packages/node-integration-tests/suites/express-v5/handle-error-scope-data-loss/test.ts, dev-packages/node-integration-tests/suites/express/handle-error-scope-data-loss/server.ts, dev-packages/node-integration-tests/suites/express/handle-error-scope-data-loss/test.ts
This PR adds a test demonstrating the unintuitive but expected behaviour reported in https://github.com/getsentry/sentry-javascript/issues/16460
see comment for more details
=> test(node): Add test demonstrating `withIsolationScope` data loss on uncaught errors

packages/react-router/src/vite/makeCustomSentryVitePlugins.ts, packages/react-router/src/vite/types.ts, packages/react-router/test/vite/makeCustomSentryVitePlugins.test.ts
Adds the possibility to add React component annotations in RR.
closes https://github.com/getsentry/sentry-javascript/issues/16471
=> feat(react-router): Add component annotation plugin

packages/sveltekit/src/server/index.ts
Closes #16494 
Was wondering if the order of the exports should be updated since some seem to be grouped logically (the two Supabase ones are next to each other) and others seem to be ordered alphabetically, but just placed this export at the end to be safe 🙂
=> fix(sveltekit): Export `vercelAIIntegration` from `@sentry/node`

packages/nextjs/src/common/devErrorSymbolicationEventProcessor.ts
Noticed that this was missing here, we should not trace this I suppose!
=> fix(nextjs): Avoid tracing calls to symbolication server on dev

.github/actions/install-playwright/action.yml
resolves https://linear.app/getsentry/issue/FE-484
> Using variable interpolation ${{...}} with github context data in a run: step could allow an attacker to inject their own code into the runner. This would allow them to steal secrets and code. github context data can have arbitrary user input and should be treated as untrusted. Instead, use an intermediate environment variable with env: to store the data and use the environment variable in the run: script. Be sure to use double-quotes the environment variable, like this: "$ENVVAR".
=> build: Fix command injection possibility in playwright GHA

packages/core/src/types-hoist/options.ts
reported via https://github.com/getsentry/sentry-javascript/issues/16505#issuecomment-2959594514
closes #16505
=> doc(core): Remove `beforeSendSpan` returning `null` from JSDoc

packages/ember/README.md, packages/ember/addon/index.ts, packages/ember/addon/types.ts, packages/ember/tests/dummy/config/environment.js
This deprecates the `ignoreEmberOnErrorWarning` option, as it is no longer used. Previously, we logged a warnining if we detected that this was used. But the option is now deprecated/will be removed, and since there is no real logic attached to this we can simply remove this (as well as the usage of the global `Ember` namespace) to avoid deprecations.
Closes https://github.com/getsentry/sentry-javascript/issues/16504
=> feat(ember): Stop warning for `onError` usage

packages/cloudflare/src/async.ts, packages/core/src/tracing/trace.ts, packages/core/test/lib/tracing/trace.test.ts, packages/opentelemetry/test/trace.test.ts
This changes the behavior of `suppressTracing` to be less problematic (or, problematic in a different way).
Today, because in the browser we do not have async context isolation, there is only a single shared top scope. Because of this, if you have code like this:
```js
const spanPromise = suppressTracing(async () => {
await new Promise(resolve => setTimeout(resolve, 100));
return startInactiveSpan({ name: 'span' });
});
const span = startInactiveSpan({ name: 'span2' });
```
The span2 will also be suppressed, because `suppressTracing` forks the scope and sets data on it to ensure spans are not recorded. This is problematic as that will result in completely unrelated spans, e.g. pageload/navigation spans, being suppressed while e.g. an ongoing fetch call that is suppressed happens.
This PR …
=> fix(browser): Ensure `suppressTracing` does not leak when async

packages/node/src/integrations/tracing/vercelai/index.ts, packages/node/src/integrations/tracing/vercelai/types.ts
By default, the instrumentation will register span processors only when the ai package is used. This is done to avoid overhead of span processing for users that do not even use this package.
However, it seems that in some environments, esp. in Next.js, the instrumentation is not added correctly, thus never running this, and not converting spans correctly. For now, this PR adds an escape hatch to manually opt-in to this to still get correct spans:
```js
vercelAiIntegration({ force: true })
```
=> feat(node): Allow to force activate `vercelAiIntegration`

packages/vue/src/tracing.ts, packages/vue/test/tracing/tracingMixin.test.ts
This PR fixes a bug discovered in https://github.com/getsentry/sentry-javascript/pull/16486#discussion_r2128214297 where the root component span would not end correctly if `trackComponents` was `false`.
Also added a comment to explain the purpose of the root component `ui.vue.render` span. We might want to look into renaming or removing this span in the future but for now, let's fix the behaviour.
=> fix(vue): Ensure root component render span always ends

dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/server-components.test.ts, dev-packages/node-integration-tests/suites/modules/instrument.mjs, dev-packages/node-integration-tests/suites/modules/server.js, dev-packages/node-integration-tests/suites/modules/server.mjs, dev-packages/node-integration-tests/suites/modules/test.ts, packages/nextjs/src/config/webpack.ts, packages/node/src/integrations/modules.ts, packages/node/src/sdk/index.ts
Extracted out from https://github.com/getsentry/sentry-javascript/pull/16565
I noticed that our `modulesIntegration` is pretty limited:
1. It does nothing on EMS
2. It does not work on Next.js (even though that is CJS)
This PR makes this a bit more robust (not perfect):
1. It generally now also tries to look at `process.cwd() + 'package.json'` and take the dependencies and devDependencies from there. this should generally work in esm apps now as well, at least at a basic level. You do not get all dependencies and versions may be ranges, but better than nothing.
2. For Next.js, we inject a modules list based off the package.json at build time, as we do not have proper access to this at runtime.
=> feat(node): Ensure `modulesIntegration` works in more environments

dev-packages/browser-integration-tests/suites/public-api/captureException/builtInClassInstance/subject.js, dev-packages/browser-integration-tests/suites/public-api/captureException/builtInClassInstance/test.ts
This is not really ideal, but there is no great alternative for this that I can think of to handle this generically 😬 
Now at least we have a test showing the current behavior!
=> test(browser): Add test showing behavior of capturing built-in class instances

packages/nextjs/src/config/types.ts, packages/nextjs/src/config/webpack.ts, packages/nextjs/src/config/withSentryConfig.ts, packages/nextjs/test/utils/tunnelRoute.test.ts
This PR adds support for auto-generated tunnel paths to avoid ad-blocker detection.
- Random paths are less likely to be blocked than `/monitoring`
- Users can just set `tunnelRoute: true` for an auto-generated route
- Existing configs will still work
**Note that every build will now create a different random path which should be quite unpredictable for ad-blockers**
=> feat(nextjs): Add option for auto-generated random tunnel route

packages/google-cloud-serverless/src/gcpfunction/general.ts, packages/google-cloud-serverless/src/index.ts, packages/google-cloud-serverless/test/gcpfunction/cloud_event.test.ts
resolves https://github.com/getsentry/sentry-javascript/issues/16653
As per the google cloud SDK (https://github.com/cloudevents/sdk-javascript/blob/c07afa9b774deefa137a960d2d11adee0bf3674a/src/event/interfaces.ts#L10-L31), `id` and  `specversion` should be mandatory.
=> fix(google-cloud-serverless): Make `CloudEvent` type compatible

packages/browser-utils/src/metrics/web-vitals/lib/LayoutShiftManager.ts
Sentry SDK supported browsers: https://docs.sentry.io/platforms/javascript/troubleshooting/supported-browsers/
`.at` is ES2022: https://blog.saeloun.com/2022/02/24/ecmascript2022-adds-add-method/
The browser SDK supports ES2021 at the current moment, so we need to change this.
Resolves https://github.com/getsentry/sentry-javascript/issues/16646
=> fix(browser): Remove usage of Array.at() method

dev-packages/browser-integration-tests/suites/public-api/logger/integration/subject.js, dev-packages/browser-integration-tests/suites/public-api/logger/integration/test.ts, packages/core/src/logs/console-integration.ts
resolves https://github.com/getsentry/sentry-javascript/issues/16657
In the `consoleLoggingIntegration` (which sends logs to Sentry from console calls), we use a utility called `safeJoin` to join together the console args.
https://github.com/getsentry/sentry-javascript/blob/b94f65279c8341a7176fe68186feef58af57e2cb/packages/core/src/utils/string.ts#L68-L94
This utility calls `String(value)` to convert items to a string, which results in objects and arrays being turned into the dreaded `[Object Object]` or `[Array]`.
https://github.com/getsentry/sentry-javascript/blob/b94f65279c8341a7176fe68186feef58af57e2cb/packages/core/src/utils/string.ts#L86
A user wrote in with feedback that this was annoying, and I agree! 
Instead of using `String(value)` I chose to create a new helper that uses …
=> fix(core): Improve `safeJoin` usage in console logging integration

.cursor/rules/publishing_release.mdc, docs/publishing-a-release.md
We should give this a try next time we want to publish a release (ideally just kick off a background agent that does it).
=> chore: Add cursor rule for publishing a release

.github/ISSUE_TEMPLATE/bug.yml, README.md, dev-packages/e2e-tests/verdaccio-config/config.yaml, package.json, packages/pino-transport/.eslintrc.js, packages/pino-transport/LICENSE, packages/pino-transport/README.md, packages/pino-transport/package.json, packages/pino-transport/rollup.npm.config.mjs, packages/pino-transport/src/index.ts, packages/pino-transport/test/index.test.ts, packages/pino-transport/tsconfig.json, packages/pino-transport/tsconfig.test.json, packages/pino-transport/tsconfig.types.json, packages/pino-transport/vite.config.ts
ref https://github.com/getsentry/sentry-javascript/issues/15952
resolves https://github.com/getsentry/sentry-javascript/issues/16621
We've gotten a lot of feedback about supporting pino. This PR kicks that off by creating a new pino package, specifically for the pino transport.
All pino transports need to use https://github.com/pinojs/pino-abstract-transport, which we don't want to add as a dep to `@sentry/node`. Hopefully keeping the versions in sync shouldn't be too bad, although I'll force a peer dep range.
=> feat(pino): Add initial package for `@sentry/pino-transport`

packages/bun/package.json, packages/nuxt/package.json, packages/remix/package.json, packages/remix/test/integration/package.json, packages/solidstart/package.json, packages/sveltekit/package.json, packages/tanstackstart-react/package.json, yarn.lock
Remove the unused dependency in:
* nuxt
* solidstart
* remix
* bun
* sveltekit
* tanstackstart-react
Closes https://github.com/getsentry/sentry-javascript/issues/16676
=> deps: Remove unused `@sentry/opentelemetry` dependency

dev-packages/node-integration-tests/suites/public-api/LocalVariables/local-variables-name-matching.js, dev-packages/node-integration-tests/suites/public-api/LocalVariables/test.ts, packages/node/src/integrations/local-variables/common.ts
resolves https://github.com/getsentry/sentry-javascript/issues/16701
For function frames that give us function named `X`, the debugger protocol (which is what local variables use) sometimes outputs `Object.X` as the function name. This causes issues when we try to apply local variables to a stacktrace frame.
=> fix(node): account for Object. syntax with local variables matching

packages/node/package.json, yarn.lock
Upgrade to be able to optionally hook internal paths like `require-in-the-middle`.
[Import in the middle v1.14.0 release.](https://github.com/nodejs/import-in-the-middle/releases/tag/import-in-the-middle-v1.14.0)
=> deps(node): Bump import-in-the-middle to 1.14.2 

packages/nextjs/src/config/webpack.ts, packages/nextjs/src/config/withSentryConfig.ts, packages/nextjs/test/config/withSentryConfig.test.ts
closes https://github.com/getsentry/sentry-javascript/issues/16593
=> fix(nextjs): Stop injecting release value when create release options is set to `false`

packages/sveltekit/src/worker/index.ts
The `logger` was missing from SvelteKit's worker environment exports, causing `Sentry.logger` to be `null` when deploying to Cloudflare Pages. Users experienced:
- `Sentry.logger` is `null` in production 
- `logger.info()` throws access violations
- Works fine locally but fails in Cloudflare Pages deployment
Cloudflare Pages uses the **worker runtime environment** (not Node.js) when `@sveltejs/adapter-cloudflare` is configured which is why logger must be exported from there.
[official Cloudflare Pages Functions documentation](https://developers.cloudflare.com/pages/functions/)
https://developers.cloudflare.com/pages/framework-guides/deploy-a-svelte-kit-site/#functions-setup
=> fix: Export logger from sveltekit worker

packages/nextjs/src/config/types.ts, packages/nextjs/src/config/webpackPluginOptions.ts, packages/nextjs/test/config/webpack/webpackPluginOptions.test.ts
Exposes a `errorHandler` option in `withSentryConfig` for handling built-time errors.
closes https://github.com/getsentry/sentry-javascript/issues/16195
=> feat(nextjs): Expose top level buildTime `errorHandler` option

.cursor/rules/publishing_release.mdc, .cursor/rules/sdk_dependency_upgrades.mdc, yarn.lock
I want to unleash an army of background agents to crunch through https://github.com/getsentry/sentry-javascript/security/dependabot?q=is%3Aopen+
To do this, I added some cursor rules for upgrading dependencies within the repo.
I also tested this out with two dependabot security warnings:
resolves https://github.com/getsentry/sentry-javascript/security/dependabot/615
resolves https://github.com/getsentry/sentry-javascript/security/dependabot/613
=> chore: Add cursor rules for dependency upgrades

dev-packages/e2e-tests/test-applications/create-remix-app-express/package.json, dev-packages/e2e-tests/test-applications/create-remix-app-v2/package.json
This will fix the [failing e2e tests](https://github.com/getsentry/sentry-javascript/actions/runs/15852381250) on CI
=> fix(tests): Set `vite` versions in Remix e2e tests.

README.md, packages/pino-transport/README.md, packages/pino-transport/package.json, packages/pino-transport/src/debug-build.ts, packages/pino-transport/src/index.ts, packages/pino-transport/test/index.test.ts, packages/pino-transport/vite.config.ts, yarn.lock
ref https://github.com/getsentry/sentry-javascript/issues/15952
resolves https://github.com/getsentry/sentry-javascript/issues/16622
This PR adds the ability to send logs to sentry via a pino transport.
```js
import pino from 'pino';
const logger = pino({
transport: {
target: '@sentry/pino-transport',
options: {
// Optional: filter which log levels to send to Sentry
logLevels: ['error', 'fatal'], // defaults to all levels
},
},
});
// Now your logs will be sent to Sentry
logger.info('This is an info message');
logger.error('This is an error message');
```
**Type:** `Array<'trace' | 'debug' | 'info' | 'warn' | 'error' | 'fatal'>`
**Default:** `['trace', 'debug', 'info', 'warn', 'error', 'fatal']` (all levels)
Use this option to filter which log levels should be sent to Sentry. …
=> feat(pino-transport): Add functionality to send logs to sentry

dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/startNewTraceSampling/init.js, dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/startNewTraceSampling/subject.js, dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/startNewTraceSampling/template.html, dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/startNewTraceSampling/test.ts
Adding a test for a support case, to ensure that new trace are correctly sampled.
=> test(browser:) Add test about re-sampling new traces

dev-packages/e2e-tests/test-applications/create-next-app/package.json, dev-packages/e2e-tests/test-applications/nextjs-13/package.json, dev-packages/e2e-tests/test-applications/nextjs-app-dir/package.json, packages/nextjs/package.json, yarn.lock
resolves https://github.com/getsentry/sentry-javascript/security/dependabot/538
resolves https://github.com/getsentry/sentry-javascript/security/dependabot/534
resolves https://github.com/getsentry/sentry-javascript/security/dependabot/533
Next.js dependencies were upgraded to address a security vulnerability concerning authorization bypass in middleware.
*   The `next` dependency in `packages/nextjs/package.json` was updated from `13.2.0` to `13.5.9`.
*   Test applications were also patched:
*   `dev-packages/e2e-tests/test-applications/create-next-app/package.json` had `next` upgraded from `14.0.0` to `14.2.25`.
*   `dev-packages/e2e-tests/test-applications/nextjs-13/package.json` had `next` upgraded from `13.5.7` to `13.5.9`.
*   The `yarn.lock` file was subsequently updated by running …
=> chore: Upgrade `next` dev and test dependency for security patch

dev-packages/e2e-tests/test-applications/nuxt-4/app/app.vue, dev-packages/e2e-tests/test-applications/nuxt-4/app/composables/use-sentry-test-tag.ts, dev-packages/e2e-tests/test-applications/nuxt-4/modules/another-module.ts, dev-packages/e2e-tests/test-applications/nuxt-4/nuxt.config.ts, dev-packages/e2e-tests/test-applications/nuxt-4/package.json
This adds a `modules` and `composables` folder to the Nuxt 4 E2E test. The main purpose is to check, that the build runs through without problems.
Additionally, the versions were updated (as this is the Nuxt 4 test and it should use the latest versions for the compatibility mode).
Related to this: https://github.com/getsentry/sentry-javascript/issues/15204#issuecomment-2948908130
=> test(nuxt): Add fake module and composable to E2E test

packages/nuxt/src/vite/utils.ts, packages/nuxt/test/vite/utils.test.ts
Only add alias in dev mode and don't override an existing one so people can still add their own alias.
fixes https://github.com/getsentry/sentry-javascript/issues/16742
reference: https://github.com/getsentry/sentry-javascript/issues/15204
=> fix(nuxt): Only add OTel alias in dev mode

dev-packages/e2e-tests/test-applications/nuxt-4/nuxt.config.ts, dev-packages/e2e-tests/test-applications/nuxt-4/package.json
Nuxt starts releasing official Nuxt 4 versions which we can use for the E2E test.
=> test(nuxt): Use official Nuxt 4 version for E2E test

.size-limit.js, packages/core/src/tracing/trace.ts, packages/core/test/lib/tracing/trace.test.ts
Even if `parentSpanIsAlwaysRootSpan=true` is configured.
Fixes https://github.com/getsentry/sentry-javascript/issues/16769
=> fix(browser): Ensure explicit `parentSpan` is considered

packages/browser/src/exports.ts
closes https://github.com/getsentry/sentry-javascript/issues/16764
=> feat(browser): Export `Context` and `Contexts` types

packages/astro/src/server/middleware.ts
Hopefully fixes https://github.com/getsentry/sentry-javascript/issues/16491
I could not get a reproducing test there for this 🤔 I figure this is "safe" to do, but not quite sure how/when this would happen. I would assume this was "introduced" by https://github.com/getsentry/sentry-javascript/pull/15995, maybe @Fryuni has a clue how/when that could happen and if this is a reasonable change 🤔
=> fix(astro): Handle errors in middlewares better

.craft.yml
In order to be able to publish an alpha release of `@sentry/node-core`, we need a craft target on the default branch (develop). This should not do anything on develop because the package doesn't exist so craft will skip it.
=> chore: Add node-core craft entry

packages/nextjs/src/config/types.ts, packages/nextjs/src/config/withSentryConfig.ts
closes https://github.com/getsentry/sentry-javascript/issues/16815
=> feat(nextjs): Add flag for suppressing router transition warning 

dev-packages/e2e-tests/test-applications/nuxt-3-min/tests/tracing.client.test.ts, packages/vue/src/router.ts, packages/vue/test/router.test.ts
We used to rely on a somewhat complex heuristic to determine if a router change is a pageload or not. This somehow did not work anymore here: https://github.com/getsentry/sentry-javascript/pull/16783 in nuxt-3-min. Likely some vue router difference... However, I think this can be simplified anyhow, by just checking if we have an active pageload span. That seems to work reliably enough.
=> fix(vue): Make pageload span handling more reliable

dev-packages/browser-integration-tests/suites/replay/ignoreMutations/init.js, dev-packages/browser-integration-tests/suites/replay/ignoreMutations/subject.js, dev-packages/browser-integration-tests/suites/replay/ignoreMutations/template.html, dev-packages/browser-integration-tests/suites/replay/ignoreMutations/test.ts, packages/replay-internal/src/integration.ts, packages/replay-internal/src/replay.ts, packages/replay-internal/src/types/replay.ts, packages/replay-internal/src/util/rrweb.ts
This option allows to configure a selector list of elements to not capture mutation for.
This is under `_experiments` for now:
```js
Sentry.replayIntegration({
_experiments: {
ignoreMutations: ['.dragging']
}
});
```
Fixes https://github.com/getsentry/sentry-javascript/issues/16797
=> feat(replay): Add `_experiments.ignoreMutations` option

packages/nextjs/rollup.npm.config.mjs, packages/nextjs/src/common/wrapMiddlewareWithSentry.ts, packages/nextjs/src/config/withSentryConfig.ts, packages/nextjs/test/config/wrappers.test.ts
https://github.com/getsentry/sentry-javascript/pull/16626 added the option to generate a randomly generated tunnel route per build. This PR adds functionality for automatically skipping tunnel route requests in the nextjs middleware, as this had to be set up manually by the user until now.
=> feat(nextjs): Automatically skip middleware requests for tunnel route

packages/astro/src/index.server.ts, packages/aws-serverless/src/index.ts, packages/bun/src/index.ts, packages/google-cloud-serverless/src/index.ts, packages/node/src/index.ts, packages/node/src/integrations/anr/common.ts, packages/node/src/integrations/anr/index.ts, packages/remix/src/server/index.ts, packages/solidstart/src/server/index.ts, packages/sveltekit/src/server/index.ts
resolves https://github.com/getsentry/sentry-javascript/issues/16808
=> feat(node): Deprecate ANR integration

packages/react/src/tanstackrouter.ts, packages/vue/src/router.ts, packages/vue/test/router.test.ts
Rename based on https://getsentry.github.io/sentry-conventions/generated/attributes/url.html#urlpathparameterkey
=> ref(router): Align route params with semantic conventions

packages/browser/src/diagnose-sdk.ts, packages/browser/test/diagnose-sdk.test.ts
Our browser SDKs expose a `diagnoseSdkConnectivity` function, whose primary purpose is to be called by the example pages injected via the wizard. As reported in #16226, even a successful request to Sentry (i.e. no ad blockers or other parties blocked the request) gets logged to the console because the previous URL included an invalid public key (as well as org id). This did not cause a `fetch` error but just a 400 (bad request) response. However, browsers log 4xx fetch requests to the console and users mistook this console log for an incorrectly configured SDK setup. 
This PR now changes the key to a valid but deactivated public key in a new project in the `sentry-sdks` org. All of the information in this URL is public and as safe to share as any DSN. So from this perspective, I don't see …
=> fix(browser): Avoid 4xx response for succesful `diagnoseSdkConnectivity` request

packages/astro/src/integration/index.ts, packages/astro/src/integration/snippets.ts, packages/astro/src/integration/types.ts, packages/astro/test/integration/index.test.ts
Closes https://github.com/getsentry/sentry-javascript/issues/16837
This should not break anything, I actually added a test to verify injecting this works as expected. We now simply console.warn when some runtime config is passed in the astro integration. Also, no more type completion exists for these, but they are still accepted via `Record<string, unknown>`.
=> feat(astro): Deprecate passing runtime config to astro integration

packages/nuxt/package.json, packages/nuxt/src/runtime/hooks/captureErrorHook.ts, packages/nuxt/src/runtime/utils.ts, yarn.lock
This just bumps the underlying transitive dependency on nitropack, which apparently changes some type imports.
Extracted out of https://github.com/getsentry/sentry-javascript/pull/16751
=> deps(nuxt): Add explicit peer dependencies & bump nitropack

packages/sveltekit/src/worker/cloudflare.ts, packages/sveltekit/test/worker/cloudflare.test.ts
This PR builds on top of #16852 to avoid capturing errors too early and too generally via the `initCloudflareSentryHandle` request handler. Internally, this handler used a wrapper from `@sentry/cloudflare` to capture errors but prior to #16852 it captured everything that was thrown. This included thrown `redirect()` objects from SvelteKit which serve as control flow mechanisms but should not be captured as errors.
This PR opts out of capturing errors in the Cloudflare wrapper. Instead, we rely on our already existing error capturing mechanisms in SvelteKit, which already ignore `redirect()` and a few other error classes. 
closes https://github.com/getsentry/sentry-javascript/issues/16847
=> fix(sveltekit): Avoid capturing `redirect()` calls as errors in Cloudflare

dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/linked-traces/negatively-sampled/init.js, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/navigation-redirect/click-early/init.js, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/navigation-redirect/click-early/template.html, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/navigation-redirect/click-early/test.ts, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/navigation-redirect/click/init.js, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/navigation-redirect/click/subject.js, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/navigation-redirect/click/template.html, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/navigation-redirect/click/test.ts, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/navigation-redirect/immediately/init.js, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/navigation-redirect/immediately/test.ts, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/navigation-redirect/keypress-early/init.js, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/navigation-redirect/keypress-early/template.html, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/navigation-redirect/keypress-early/test.ts, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/navigation-redirect/keypress/init.js, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/navigation-redirect/keypress/subject.js, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/navigation-redirect/keypress/template.html, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/navigation-redirect/keypress/test.ts, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/navigation-redirect/late/init.js, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/navigation-redirect/late/test.ts, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/navigation-redirect/opt-out/init.js, dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/navigation-redirect/opt-out/test.ts, packages/browser/src/tracing/browserTracingIntegration.ts, packages/browser/test/tracing/browserTracingIntegration.test.ts, packages/core/src/client.ts, packages/nextjs/test/performance/pagesRouterInstrumentation.test.ts
Closes https://github.com/getsentry/sentry-javascript/issues/15286
This PR adds a new option to `browserTracingIntegration`, `detectRedirects`, which is enabled by default. If this is enabled, the integration will try to detect if a navigation is actually a redirect based on a simple heuristic, and in this case, will not end the ongoing pageload/navigation, but instead let it run and create a `navigation.redirect` zero-duration span instead.
An example trace for this would be: https://sentry-sdks.sentry.io/explore/discover/trace/95280de69dc844448d39de7458eab527/?dataset=transactions&eventId=8a1150fd1dc846e4ac8420ccf03ad0ee&field=title&field=project&field=user.display&field=timestamp&name=All%20Errors&project=4504956726345728&query=&queryDataset=transaction-like&sort=-timestamp&source=disco …
=> feat(browser): Detect redirects when emitting navigation spans

docs/creating-a-new-sdk.md, packages/nuxt/package.json
To not have the need of manually adding another package when wanting to use the Cloudflare SDK, we always add it. This is already the case in the SvelteKit SDK.
=> chore(nuxt): Add `@sentry/cloudflare` as dependency

packages/core/src/carrier.ts, packages/core/src/utils/logger.ts, packages/core/test/lib/utils/logger.test.ts
This has bugged me often already, and I looked into it again nudged by https://github.com/getsentry/sentry-javascript/issues/16846. Today the logger export from core has a side effect and reads from the global. This is a bit weird...
This PR rewrites this to instead only keep the enabled flag on the carrier. The logger itself is a "normal" method that just looks at the carrier to see if logging is enabled or not.
=> ref(core): Rewrite `logger` to avoid side effects

packages/feedback/src/core/sendFeedback.ts, packages/feedback/test/core/sendFeedback.test.ts
This PR increases the feedback widget's submission timeout from 5 seconds to 30 seconds.
**Why?**
The previous 5-second timeout was too aggressive, leading to premature errors and a poor user experience, especially in slow network conditions. Increasing the timeout provides more time for feedback to be sent successfully, improving reliability.
---
[Slack Thread](https://sentry.slack.com/archives/C05J714QPRR/p1752188409093349?thread_ts=1752188409.093349&cid=C05J714QPRR)
=> ref(feedback) set submission timeout to 30 seconds

packages/browser/src/integrations/featureFlags/openfeature/types.ts, packages/core/src/utils/syncpromise.ts, packages/react/src/types.ts
Apart of directly vendored code, we should avoid `enum`, as it has bundle size impact.
Also somehow part of https://github.com/getsentry/sentry-javascript/issues/16846
=> ref: Avoid `enum` usage

packages/svelte/src/debug_build.ts, packages/svelte/src/performance.ts
resolves https://github.com/getsentry/sentry-javascript/issues/16916
=> ref(svelte): use `debug` in svelte sdk

packages/sveltekit/src/server-common/handle.ts, packages/sveltekit/src/server-common/utils.ts
resolves https://github.com/getsentry/sentry-javascript/issues/16913
=> ref(sveltekit): Use `debug` in sveltekit sdk

packages/core/src/index.ts, packages/react/src/errorboundary.tsx, packages/react/src/reactrouterv6-compat-utils.tsx
resolves https://github.com/getsentry/sentry-javascript/issues/16940
Migrates `@sentry/react` to use the `debug` utility instead of `logger` from `@sentry/core`.
This change aligns with the ongoing effort to streamline logging utilities within the SDK, moving towards a more focused `debug` function.
---
=> ref(react): Use `debug` instead of `logger`

packages/core/src/utils/vercel-ai.ts
This is pretty small, but apparently `Object.assign()` also counts as side effect.
Part of https://github.com/getsentry/sentry-javascript/issues/16846
=> ref(core): Avoid side-effect of `vercelAiEventProcessor`

packages/core/src/carrier.ts, packages/core/src/logs/exports.ts, packages/core/src/utils/worldwide.ts
Instead of having a side effect of writing on the GLOBAL_OBJ, we can use a global singleton instead.
Part of https://github.com/getsentry/sentry-javascript/issues/16846
=> ref(core): Keep client-logger map on carrier & avoid side-effect

packages/core/src/tracing/idleSpan.ts, packages/core/test/lib/tracing/idleSpan.test.ts
While working on #16893 I realized that if we reported a web vital standalone span while an idlespan (e.g. pageload) was still running, we'd restart the idle span's child span timeout (i.e. prolong its duration potentially). Is is unintended because by definition the standalone span should not be associated with a potentially ongoing idle span and its tree.
This can happen, for example when users hide the page while the pageload span is still active, causing web vitals to be reported.
=> fix(core): Avoid prolonging idle span when starting standalone span

packages/aws-serverless/package.json
Link "homepage" on https://www.npmjs.com/package/@sentry/aws-serverless links to a 404 page, as it targets the old `serverless` URL.
Is: https://github.com/getsentry/sentry-javascript/tree/master/packages/serverless
Should be: https://github.com/getsentry/sentry-javascript/tree/master/packages/aws-serverless
This is the fix.
Not sure about the commit message, feel free to pick this up and adjust.
This PR is similar to the one for GCP: https://github.com/getsentry/sentry-javascript/pull/14411
=> docs(aws-serverless): Fix package homepage link

packages/vercel-edge/src/sdk.ts, packages/vercel-edge/src/vendored/async-local-storage-context-manager.ts
resolves https://github.com/getsentry/sentry-javascript/issues/16911
=> ref(vercel-edge): Use `debug` in vercel edge sdk

packages/node-native/src/event-loop-block-integration.ts
resolves https://github.com/getsentry/sentry-javascript/issues/16945
=> ref(node-native): Use `debug` instead of `logger`

packages/remix/src/client/index.ts, packages/remix/src/client/performance.tsx, packages/remix/src/server/errors.ts, packages/remix/src/server/instrumentServer.ts, packages/remix/src/server/sdk.ts, packages/remix/src/utils/utils.ts, packages/remix/test/integration/test/server/utils/helpers.ts
resolves https://github.com/getsentry/sentry-javascript/issues/16938
=> ref(remix): Use `debug` instead of `logger`

packages/nuxt/src/runtime/hooks/updateRouteBeforeResponse.ts, packages/nuxt/src/runtime/plugins/route-detector.server.ts, packages/nuxt/src/runtime/plugins/sentry-cloudflare.server.ts, packages/nuxt/src/runtime/plugins/sentry.server.ts, packages/nuxt/src/runtime/utils.ts, packages/nuxt/src/runtime/utils/route-extraction.ts, packages/nuxt/src/server/sdk.ts, packages/nuxt/src/vite/addServerConfig.ts
resolves https://github.com/getsentry/sentry-javascript/issues/16944
=> ref(nuxt): Use `debug` instead of `logger`

packages/browser/src/integrations/spotlight.ts, packages/browser/src/profiling/utils.ts, packages/core/src/fetch.ts, packages/core/src/integrations/dedupe.ts, packages/core/src/integrations/rewriteframes.ts, packages/core/src/utils/vercelWaitUntil.ts, packages/feedback/src/modal/integration.tsx, packages/node-core/src/integrations/spotlight.ts, packages/replay-internal/src/coreHandlers/handleDom.ts, packages/replay-internal/src/util/isRrwebError.ts
A future version of eslint flagged & auto-fixed these, extracting this out for easier review.
=> ref: Use optional chaining wherever possible

packages/node-core/test/integration/transactions.test.ts, packages/node/test/integration/transactions.test.ts, packages/opentelemetry/src/propagator.ts, packages/opentelemetry/src/sampler.ts, packages/opentelemetry/src/spanExporter.ts, packages/opentelemetry/test/helpers/initOtel.ts, packages/opentelemetry/test/integration/transactions.test.ts
resolves https://github.com/getsentry/sentry-javascript/issues/16943
Just give a quick double check to `packages/opentelemetry/test/helpers/initOtel.ts` to make sure it makes sense.
=> ref(opentelemetry): Use `debug` instead of `logger`

packages/angular/src/sdk.ts, packages/angular/src/tracing.ts
resolves https://github.com/getsentry/sentry-javascript/issues/16955
=> ref(angular): Use `debug` instead of `logger`

packages/browser-utils/src/getNativeImplementation.ts, packages/browser-utils/src/metrics/cls.ts, packages/browser-utils/src/metrics/instrument.ts, packages/browser-utils/src/metrics/lcp.ts, packages/browser/src/integrations/breadcrumbs.ts, packages/browser/src/integrations/browsersession.ts, packages/browser/src/integrations/featureFlags/unleash/integration.ts, packages/browser/src/integrations/globalhandlers.ts, packages/browser/src/integrations/httpclient.ts, packages/browser/src/integrations/spotlight.ts, packages/browser/src/profiling/integration.ts, packages/browser/src/profiling/startProfileForSpan.ts, packages/browser/src/profiling/utils.ts, packages/browser/src/report-dialog.ts, packages/browser/src/tracing/backgroundtab.ts, packages/browser/src/tracing/browserTracingIntegration.ts, packages/browser/src/tracing/linkedTraces.ts
resolves https://github.com/getsentry/sentry-javascript/issues/16952
resolves https://github.com/getsentry/sentry-javascript/issues/16951
=> ref(browser): Use debug instead of logger

packages/deno/src/transports/index.ts
resolves https://github.com/getsentry/sentry-javascript/issues/16950
=> ref(deno): Use `debug` instead of `logger`

packages/google-cloud-serverless/src/gcpfunction/cloud_events.ts, packages/google-cloud-serverless/src/gcpfunction/events.ts, packages/google-cloud-serverless/src/gcpfunction/http.ts
resolves https://github.com/getsentry/sentry-javascript/issues/16948
=> ref(google-cloud-serverless): Use `debug` instead of `logger`

.cursor/environment.json, .cursor/rules/sdk_dependency_upgrades.mdc, .cursor/rules/sdk_development.mdc, CLAUDE.md, package.json
trying to un-stupidify cursor in some cases, esp. background tasks.
=> chore: Update cursor rules with more details

dev-packages/browser-integration-tests/suites/integrations/webWorker/assets/worker.js, dev-packages/browser-integration-tests/suites/integrations/webWorker/init.js, dev-packages/browser-integration-tests/suites/integrations/webWorker/template.html, dev-packages/browser-integration-tests/suites/integrations/webWorker/test.ts, dev-packages/e2e-tests/lib/copyToTemp.ts, dev-packages/e2e-tests/test-applications/browser-webworker-vite/.npmrc, dev-packages/e2e-tests/test-applications/browser-webworker-vite/index.html, dev-packages/e2e-tests/test-applications/browser-webworker-vite/package.json, dev-packages/e2e-tests/test-applications/browser-webworker-vite/playwright.config.mjs, dev-packages/e2e-tests/test-applications/browser-webworker-vite/src/main.ts, dev-packages/e2e-tests/test-applications/browser-webworker-vite/src/vite-env.d.ts, dev-packages/e2e-tests/test-applications/browser-webworker-vite/src/worker.ts, dev-packages/e2e-tests/test-applications/browser-webworker-vite/src/worker2.ts, dev-packages/e2e-tests/test-applications/browser-webworker-vite/src/worker3.ts, dev-packages/e2e-tests/test-applications/browser-webworker-vite/start-event-proxy.mjs, dev-packages/e2e-tests/test-applications/browser-webworker-vite/tests/errors.test.ts, dev-packages/e2e-tests/test-applications/browser-webworker-vite/tsconfig.json, dev-packages/e2e-tests/test-applications/browser-webworker-vite/vite.config.ts, packages/browser/src/index.ts, packages/browser/src/integrations/webWorker.ts, packages/browser/test/integrations/webWorker.test.ts
This PR adds two Browser SDK APIs to let the main thread know about debugIds of worker files:
- `webWorkerIntegration({worker})` to be used in the main thread
- `registerWebWorker(self)` to be used in the web worker
The communication between workers and main thread is established between both APIs and they have to be used both for the sync to work correctly. Another limitation around this approach is that users must set up `webWorkerInegration` before they register their own message listeners. This ensures that the message from `registerWebWorker` is not propagated to user-created message listeners. We'll document this thoroughly in docs and I already added a section about this in the JSDoc.
Because of the strict co-dependence of both APIs, I decided to add them in one PR (also makes …
=> feat(browser): Add debugId sync APIs between web worker and main thread

packages/sveltekit/src/server-common/handleError.ts, packages/sveltekit/test/server-common/handleError.test.ts
In SvelteKit, users can return a `Promise` from a `load` function which causes a streamed http respnse to be sent. If the promise rejects after it is returned and the initial response is sent, an error is thrown server-side. This error will not be captured by our request handler wrappers because at this time, they already finished.
However, the error will be caught via our `handleErrorWithSentry` hook. This means we actually still catch the error but because the cloudflare function already terminated directly after the rejection, it is not sent successfully (i.e. the good old flush problem). 
This PR makes sure we use of Cloudflare's `waitUntil` function which fortunately is available within the error handler hook. 
closes https://github.com/getsentry/sentry-javascript/issues/17009
=> fix(sveltekit): Ensure server errors from streamed responses are sent

dev-packages/e2e-tests/test-applications/react-router-7-cross-usage/package.json
This E2E is _probably_ failing due to https://github.com/remix-run/react-router/issues/14020
The PR just pins the react-router version to unblock us
=> test(react): Pin react-router version for e2e test

dev-packages/e2e-tests/registrySetup.ts
The error code 137 is a very common error when running E2E tests. Starting colima only with `colima start` often results in too little memory and it makes sense to add a more descriptive message here. 
To make it work with Colima, it's better to start it with `colima start --cpu 10 --memory 12 --network-address`
=> chore(test-registry): Add more descriptive error code for common error

dev-packages/e2e-tests/test-applications/astro-5/src/pages/api/user/[userId].json.js, dev-packages/e2e-tests/test-applications/astro-5/src/pages/index.astro, dev-packages/e2e-tests/test-applications/astro-5/src/pages/user-page/[userId].astro, dev-packages/e2e-tests/test-applications/astro-5/tests/tracing.dynamic.test.ts
Adds a test case with a client, server and server API request which checks:
- that everything is correctly connected
- that everything has parametrized routes (the current state of it - some are not yet parametrized)
This is a visual representation of the test case (with a different param):
Part of https://github.com/getsentry/sentry-javascript/issues/16686
=> test(astro-5): Add test for current parametrized routes

packages/core/src/profiling.ts, packages/core/src/types-hoist/profiling.ts
This allows us to avoid `any` here, and makes more sense overall IMHO.
=> ref(profiling): Improve generic profiling type

packages/cloudflare/src/opentelemetry/tracer.ts, packages/core/src/tracing/sentryNonRecordingSpan.ts, packages/core/src/utils/handleCallbackErrors.ts, packages/eslint-config-sdk/src/base.js, packages/feedback/src/modal/integration.tsx, packages/feedback/src/screenshot/integration.ts, packages/sveltekit/src/vite/svelteConfig.ts
This is IMHO not super helpful, we constantly disable it or add a noop comment for no gain.
=> ref: Remove `@typescript-eslint/no-empty-function` eslint rule

MIGRATION.md, packages/core/src/client.ts, packages/core/src/index.ts, packages/core/test/lib/client.test.ts
`BaseClient` was deprecated in v9, use `Client` as a direct replacement.
=> feat(core)!: Remove `BaseClient`

MIGRATION.md, packages/core/src/index.ts, packages/core/src/utils/hasSpansEnabled.ts, packages/core/test/lib/utils/hasSpansEnabled.test.ts
`hasTracingEnabled` was deprecated in v9, use `hasSpansEnabled` as a direct replacement.
=> feat(core)!: Remove `hasTracingEnabled`

packages/core/test/lib/tracing/trace.test.ts
This PR adds a couple of unit tests to explicitly test sampling behaviour of the core SDK's sampling logic when users pass in a `tracesSampler` function returning negative sampling values (i.e. `0`, `false`). 
According to coverage, this is tested implicitly already but I couldn't find specific explicit tests that assert on this expected outcome. Decided to add some while investigating https://github.com/getsentry/sentry-javascript/issues/16849.
=> test(core): Add explicit tests for `tracesSampler` returning negative sampling decisions

MIGRATION.md, dev-packages/e2e-tests/test-applications/nuxt-3/server/plugins/customNitroErrorHandler.ts, packages/core/src/carrier.ts, packages/core/src/index.ts, packages/core/src/utils/debug-logger.ts
BREAKING CHANGE
In https://github.com/getsentry/sentry-javascript/issues/16901 we deprecated the `logger` export from `@sentry/core`.
This PR removes it for the v10 release.
=> feat(core)!: Remove deprecated logger

packages/aws-serverless/scripts/buildLambdaLayer.ts
CI for the 10.0.0-alpha.0 release is failing at the build step but it's unclear why. This hopefully reveals more info.
=> chore: Remove `--silent` flag from layer build script and create dir prior

packages/aws-serverless/package.json
The current way of building the AWS Lambda Layer is not working during releases because it tries to install @sentry/aws-serverless from the registry instead of the workspace.
Temporarily disable it until we figure out how to fix it.
=> chore: Avoid building aws layer for now

MIGRATION.md
Migration note for the changes in https://github.com/getsentry/sentry-javascript/pull/17063
=> chore: Add migration note about `enableLogs` option changes

packages/remix/test/integration/app/root.tsx, packages/remix/test/integration/test/client/root-loader.test.ts
Looks like `example.com` has some kind of rate limit or random unavailability. Switching to `docs.sentry.io` resolved the flakes. Maybe we can replace all `example.com` uses in the codebase with a Sentry domain 🤔 Wdyt?
=> test(remix): Fix integration test flakes

dev-packages/e2e-tests/test-applications/astro-5/src/pages/catchAll/[...path].astro, dev-packages/e2e-tests/test-applications/astro-5/tests/tracing.dynamic.test.ts
Extracting a test case in a new PR while working on route parametrization.
Continuation of https://github.com/getsentry/sentry-javascript/pull/17054
Part of https://github.com/getsentry/sentry-javascript/issues/16686
=> test(astro): Add E2E test case for catch-all routes

packages/browser-utils/src/metrics/browserMetrics.ts
Backport of #17090:
Just a minor cleanup from a TODO I left a while ago. We can safely
remove this check because CLS isn't reported before FCP is reported.
=> ref(v9/browser): Remove unnecessary CLS web vital check 

dev-packages/e2e-tests/test-applications/aws-lambda-layer-cjs/package.json, dev-packages/e2e-tests/test-applications/aws-lambda-layer-esm/package.json, packages/aws-serverless/package.json
We removed this in order to release a v10 alpha but the release process still expcets a built layer, thus failing. We'll wait for a proper layer build fix.
=> chore: Revert AWS Lambda Layer build disabling

packages/remix/scripts/createRelease.js
Small cleanup forward-port to `develop` (see  https://github.com/getsentry/sentry-javascript/pull/17095#discussion_r2218413532.)
=> chore(remix): Cleanup unused error args in sourcemaps script

packages/aws-serverless/package.json, packages/aws-serverless/scripts/buildLambdaLayer.ts
This fixes the AWS Layer release build which tried to fetch the new package versions from the NPM registry, which don't exist yet during the build. We now build a new `package.json` that uses `resolutions` to point all Sentry packages to their local version.
=> fix(aws): Resolve all Sentry packages to local versions in layer build

packages/aws-serverless/scripts/buildLambdaLayer.ts
Next try. Use local file link here too to skip registry fetch
=> fix(aws): Use file link in dependency version

dev-packages/e2e-tests/test-applications/node-fastify-3/package.json, dev-packages/e2e-tests/test-applications/node-fastify-3/playwright.override.config.mjs, dev-packages/e2e-tests/test-applications/node-fastify-3/src/app-handle-error-override.ts, dev-packages/e2e-tests/test-applications/node-fastify-3/src/app.ts, dev-packages/e2e-tests/test-applications/node-fastify-3/tests/errors.test.ts, dev-packages/e2e-tests/test-applications/node-fastify-4/package.json, dev-packages/e2e-tests/test-applications/node-fastify-4/playwright.override.config.mjs, dev-packages/e2e-tests/test-applications/node-fastify-4/src/app-handle-error-override.ts, dev-packages/e2e-tests/test-applications/node-fastify-4/tests/errors.test.ts, dev-packages/e2e-tests/test-applications/node-fastify-5/package.json, dev-packages/e2e-tests/test-applications/node-fastify-5/playwright.override.config.mjs, dev-packages/e2e-tests/test-applications/node-fastify-5/src/app-handle-error-override.ts, dev-packages/e2e-tests/test-applications/node-fastify-5/src/app.ts, dev-packages/e2e-tests/test-applications/node-fastify-5/tests/errors.test.ts, packages/node/src/integrations/tracing/fastify/index.ts
Resolves: https://github.com/getsentry/sentry-javascript/issues/16819
This requires the Fastify integration to be manually added while initialising Sentry. 
```typescript
Sentry.init({
Sentry.fastifyIntegration({
shouldHandleError(_error, _request, reply) {
return reply.statusCode >= 500;
},
});
},
});
```
If `shouldHandleError` is provided in `setupFastifyErrorHandler`, it overrides `shouldHandleError` provided from `fastifyIntegration`. So this should not break any existing (pre-DC) usage.
In summary: 
- When `setupFastifyErrorHandler` is not used, `shouldHandleError` at `Sentry.init` will be used.
- When `setupFastifyErrorHandler` is used but without `shouldHandleError`, `shouldHandleError` at `Sentry.init` will be used.
- When in both `setupFastifyErrorHandler` and …
=> feat(node): Add `shouldHandleError` option to `fastifyIntegration`

packages/cloudflare/src/workflows.ts, packages/cloudflare/test/workflow.test.ts
- A backport to v9 of #17121 
- Closes #17074
@StephenHaney unless you're a very early adopter of v10, this PR is probably the one you care about!
=> fix(v9/cloudflare) Allow non UUID workflow instance IDs

.github/workflows/build.yml
This used to be necessary due to polyfills, I believe, but since they are gone this hopefully is not needed anymore.
=> ci: Stop caching utils src files

dev-packages/e2e-tests/test-applications/aws-lambda-layer-cjs/package.json, dev-packages/e2e-tests/test-applications/aws-lambda-layer-cjs/tests/basic.test.ts, dev-packages/e2e-tests/test-applications/aws-lambda-layer-esm/package.json, dev-packages/e2e-tests/test-applications/aws-lambda-layer-esm/tests/basic.test.ts
skip until we figure out why they are failing on CI.
=> chore: Skip Lambda layer tests

dev-packages/e2e-tests/test-applications/aws-lambda-layer-cjs/package.json, dev-packages/node-integration-tests/suites/express/handle-error-tracesSampleRate-0/server.ts, dev-packages/node-integration-tests/suites/express/handle-error/server.ts, dev-packages/node-integration-tests/suites/express/handle-error/test.ts, dev-packages/node-integration-tests/suites/public-api/onUnhandledRejectionIntegration/scenario-with-span-ended.ts, dev-packages/node-integration-tests/suites/public-api/onUnhandledRejectionIntegration/scenario-with-span.ts, dev-packages/node-integration-tests/suites/public-api/onUnhandledRejectionIntegration/test.ts, dev-packages/node-integration-tests/suites/tracing/vercelai/instrument-with-pii.mjs, dev-packages/node-integration-tests/suites/tracing/vercelai/instrument.mjs, dev-packages/node-integration-tests/suites/tracing/vercelai/scenario-error-in-tool-express.mjs, dev-packages/node-integration-tests/suites/tracing/vercelai/scenario-error-in-tool.mjs, dev-packages/node-integration-tests/suites/tracing/vercelai/test.ts, packages/node-core/src/integrations/onunhandledrejection.ts, packages/node/src/integrations/tracing/vercelai/instrumentation.ts
This fixes the problem that for tool errors triggered from vercel-ai integration, traces were not connected.
This seemed to happen because errors bubble up to the global unhandled rejection handler, where the span is no longer active and thus the trace cannot be connected.
This PR fixes this by attaching the active span to the error and using this in the unhandled rejection handler, if it exists. 
Closes https://github.com/getsentry/sentry-javascript/issues/17108
=> fix(node): Ensure tool errors for `vercelAiIntegration` have correct trace connected

dev-packages/e2e-tests/lib/getTestMatrix.ts
This pr changes the detection logic for the e2e tests directory.
Before we always ran every test whenever something changed in this dir.
With this change we check for changed files in the test apps and only run all tests if shared code has been changed.
=> ci(e2e): Only run changed E2E tests

dev-packages/e2e-tests/test-applications/astro-4/src/pages/api/user/[userId].json.js, dev-packages/e2e-tests/test-applications/astro-4/src/pages/catchAll/[...path].astro, dev-packages/e2e-tests/test-applications/astro-4/src/pages/user-page/[userId].astro, dev-packages/e2e-tests/test-applications/astro-4/tests/tracing.dynamic.test.ts, dev-packages/e2e-tests/test-applications/astro-5/src/pages/catchAll/[...path].astro, dev-packages/e2e-tests/test-applications/astro-5/src/pages/user-page/settings.astro, dev-packages/e2e-tests/test-applications/astro-5/tests/tracing.dynamic.test.ts, dev-packages/e2e-tests/test-applications/astro-5/tests/tracing.serverIslands.test.ts, dev-packages/e2e-tests/test-applications/astro-5/tests/tracing.static.test.ts, packages/astro/src/integration/index.ts, packages/astro/src/integration/types.ts, packages/astro/src/server/middleware.ts
Backport of all server-related parametrization in Astro:
- https://github.com/getsentry/sentry-javascript/pull/17054
- https://github.com/getsentry/sentry-javascript/pull/17085
- https://github.com/getsentry/sentry-javascript/pull/17102
- https://github.com/getsentry/sentry-javascript/pull/17105
=> feat(v9/astro): Parametrize dynamic server routes

packages/remix/test/integration/app/root.tsx, packages/remix/test/integration/test/client/root-loader.test.ts
Backport of https://github.com/getsentry/sentry-javascript/pull/17093
=> test(v9/remix): Fix integration test flakes

packages/core/src/utils/vercel-ai.ts
Mapping ai.response.object to gen_ai.response.object
Closes https://linear.app/getsentry/issue/JS-659/map-airesponseobject-to-gen-airesponseobject
=> fix(core): Update ai.response.object to gen_ai.response.object

packages/core/src/utils/openai/index.ts, packages/core/test/utils/openai-integration-functions.test.ts
The OpenAI SDK v5 uses ES private class fields (e.g. #baseURL), which can only be accessed when methods are called with the correct this context. In our instrumentation, methods that are not explicitly instrumented (i.e. skipped by shouldInstrument) were returned unbound, which broke calls to internal OpenAI methods like .parse() by triggering:
TypeError: Cannot read private member from an object whose class did not declare it.
This PR fixes that by explicitly binding all non-instrumented functions to their original instance (value.bind(obj)), ensuring correct this context and avoiding runtime errors when accessing private fields.
=> fix(core): Fix OpenAI SDK private field access by binding non-instrumented fns

packages/core/src/utils/openai/index.ts, packages/core/test/utils/openai-integration-functions.test.ts
=> fix(v9/core): Fix OpenAI SDK private field access by binding non-instrumented fns

dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/devErrorSymbolification.test.ts, packages/nextjs/src/common/devErrorSymbolicationEventProcessor.ts
backport of https://github.com/getsentry/sentry-javascript/pull/17156
=> fix(v9/nextjs): Update stackframe calls for next v15.5 (#17156)

packages/sveltekit/src/client/handleError.ts, packages/sveltekit/src/server-common/handleError.ts, packages/sveltekit/test/client/handleError.test.ts, packages/sveltekit/test/server-common/handleError.test.ts
Our `handleErrorWithSentry` logic was diverging a bit from the rest of the SvelteKit SDK and more general SDK patterns. Specifically, which errors would be ignored and when we set an error mechanism to `handled: true|false`.
This PR now aligns two behaviours:
- Ignore all 4xx errors (previously, we only ignored 404 errors)
- Set `handled: true` if a custom error handler was defined by users and `handled: false` otherwise.
Reported via Support, so no GH issue.
=> fix(sveltekit): Align error status filtering and mechanism in `handleErrorWithSentry`

packages/nuxt/src/runtime/utils.ts, packages/solidstart/src/server/utils.ts, packages/sveltekit/src/server-common/utils.ts
Adds Google Cloud Run environment variable to serverless detection to wait until flushing. 
Documented here: https://cloud.google.com/run/docs/configuring/services/environment-variables#reserved
related to this: https://github.com/getsentry/sentry-javascript/issues/17165
=> feat(meta): Unify detection of serverless environments and add Cloud Run

dev-packages/e2e-tests/test-applications/nextjs-15/.gitignore, dev-packages/e2e-tests/test-applications/nextjs-15/app/page.tsx, dev-packages/e2e-tests/test-applications/nextjs-15/package.json, dev-packages/e2e-tests/test-applications/nextjs-15/playwright.config.mjs, dev-packages/e2e-tests/test-applications/nextjs-15/tests/async-params.test.ts, packages/nextjs/src/common/utils/wrapperUtils.ts, packages/nextjs/src/common/wrapGenerationFunctionWithSentry.ts, packages/nextjs/src/common/wrapServerComponentWithSentry.ts
closes https://linear.app/getsentry/issue/JS-535/error-route-used-searchparams-sentry-skip-normalization-searchparams
closes https://github.com/getsentry/sentry-javascript/issues/16542
Unfortunately we can't resolve the params promise within the template as making this async leads to some nasty RSC errors which we want to stay away from.
=> fix(nextjs): Handle async params in url extraction

packages/cloudflare/src/durableobject.ts, packages/cloudflare/test/durableobject.test.ts
https://github.com/getsentry/sentry-javascript/commit/bb5d3e90f7eaa860f82a400ff7396633ed8cbeec demonstrates the issue with a failing test
https://github.com/getsentry/sentry-javascript/commit/2c9a487a059380206a1d4b6e382324e524a04f91 uses `isThenable` to determine how to wrap methods in `wrapMethodWithSentry`
Fixes: #17094
=> fix(cloudflare): Avoid turning DurableObject sync methods into async

dev-packages/e2e-tests/test-applications/nextjs-turbo/package.json, dev-packages/e2e-tests/test-applications/nextjs-turbo/playwright.config.mjs
Changes the build command for the next.js turbopack e2e test to also run the prod tests with turbopack.
ref https://linear.app/getsentry/project/turbopack-support-nextjs-80713aa82b5a
=> test(nextjs): Run prod e2e tests in turbopack

.craft.yml
We need to skip releasing the v10 AWS Lambda layer, otherwise the current v9 Layer gets overridden
=> chore: Skip releasing v10 AWS layer

dev-packages/e2e-tests/test-applications/nextjs-14/tests/generation-functions.test.ts
closes https://linear.app/getsentry/issue/JS-784/nextjs-14-canary-test-failed
This PR fixes a race condition in what error event is triggering our listener.
=> test(nextjs): Update error listener for generateMetadata test

dev-packages/e2e-tests/test-applications/nextjs-15/app/ai-error-test/page.tsx, dev-packages/e2e-tests/test-applications/nextjs-15/tests/ai-error.test.ts
Add a test to verify that error trace linking works in Next.js and correctly bubbles up to the parent span.
=> test(nextjs): Test error trace linking for Vercel AI in Next.js

dev-packages/node-integration-tests/suites/tracing/openai/test.ts, packages/core/src/utils/gen-ai-attributes.ts, packages/core/src/utils/openai/utils.ts, packages/core/test/lib/utils/openai-utils.test.ts
According to https://opentelemetry.io/docs/specs/semconv/registry/attributes/gen-ai/#gen-ai-operation-name
> “If one of them applies, then the respective value MUST be used; otherwise, a custom value MAY be used.” 
and because the responses api also allows file and image input we can assume it's not really a chat completion
closes: https://github.com/getsentry/sentry-javascript/issues/17192
=> fix(core): Fix operation name for openai responses API 

packages/node-native/package.json, yarn.lock
Although the way we pin this dep allows for patch versions, let's explicitly bump this because https://github.com/getsentry/sentry-javascript-node-native-stacktrace/releases/tag/0.2.2 includes a pretty nice fix for cross-platform timings.
Thanks again to @matthew-nicholson-anrok for the contribution :)
=> feat(node-native): Upgrade `@sentry-internal/node-native-stacktrace` to `0.2.2`

packages/node/src/integrations/tracing/fastify/index.ts
While investigating https://github.com/getsentry/sentry-javascript/issues/17119, I saw that our fastifyIntegration error handler doesn't set a mechanism when calling `captureException`. This leads to the SDK assigning the generic fallback mechanism and marking the error as `handled: true`. This makes it hard to 1. identify that the error was captured by our fastify instrumentation and 2. marks the error as handled, when it's probably not.
=> fix(node): Add mechanism to `fastifyIntegration` error handler

packages/astro/src/integration/index.ts, packages/astro/src/server/middleware.ts
For v9, the changes were already reverted in this PR (https://github.com/getsentry/sentry-javascript/issues/17179) to create a quick fix we can release soon. However, this removed some parametrization.
This PR here not only fixed the problem with continuously writing to `globalThis` to share build-time data with the runtime (we don't do this anymore). The route parametrization now happens only during runtime, as we have access to the route segments at runtime with Astro v5.
This adds a **little** performance overhead when compared with the previous approach (the route segments are now constructed during runtime) - but this is not an expensive operation. The `.find` method was used in the previous approach as well.
Fixes https://github.com/getsentry/sentry-javascript/issues/17179
=> fix(astro): Construct parametrized route during runtime

packages/nextjs/src/common/wrapRouteHandlerWithSentry.ts
closes https://linear.app/getsentry/issue/JS-783/nextjs-no-data-being-sent-from-server-side-functions
closes https://github.com/getsentry/sentry-javascript/issues/17193
This will not fix this issue for prod deployments with turbopack as we do not have any build time instrumentation for route handlers there _yet_. In this case the current suggestion is to use:
```ts
import { after} from 'next/server';
import * as Sentry from '@sentry/nextjs';
export function GET() {
after(() => {
Sentry.flush();
});
// rest of your handler
}
```
=> fix(nextjs): Flush in route handlers

dev-packages/e2e-tests/test-applications/astro-5/tests/tracing.dynamic.test.ts, packages/astro/src/server/middleware.ts
Backport of https://github.com/getsentry/sentry-javascript/pull/17190
=> fix(v9/astro): Construct parametrized route during runtime

packages/react-router/test/client/react-exports.test.ts, packages/react/src/errorboundary.tsx, packages/react/test/errorboundary.test.tsx
Cursor failed me on this one so fixing here.
closes https://github.com/getsentry/sentry-javascript/issues/17183
=> fix(react): Memoize wrapped component to prevent rerenders

packages/react-router/src/server/wrapSentryHandleRequest.ts, packages/react-router/test/server/wrapSentryHandleRequest.test.ts
ref https://github.com/getsentry/sentry-javascript/issues/17228
Splitting this whole flushing topic up into a few PRs.
=> feat(react-router): Automatically flush on Vercel for request handlers

packages/react-router/src/server/wrapServerAction.ts, packages/react-router/src/server/wrapServerLoader.ts, packages/react-router/test/server/wrapSentryHandleRequest.test.ts, packages/react-router/test/server/wrapServerAction.test.ts, packages/react-router/test/server/wrapServerLoader.test.ts
ref https://github.com/getsentry/sentry-javascript/issues/17228
ref https://linear.app/getsentry/issue/JS-793/improve-sentry-react-router-steps
=> feat(react-router): Automatically flush on serverless for loaders/actions

packages/nextjs/src/common/wrapRouteHandlerWithSentry.ts
backports https://github.com/getsentry/sentry-javascript/pull/17223
=> fix(v9/nextjs): Flush in route handlers

dev-packages/browser-integration-tests/suites/replay/autoFlushOnFeedback/init.js, packages/replay-internal/src/replay.ts, packages/replay-internal/src/types/replay.ts, packages/replay-internal/src/util/addGlobalListeners.ts
Flushing on feedback widget opening is better than on submit as you get more relevant replay context, so we are going to make this the default behavior and deprecate the configuration option. The option will be removed in [v10](https://github.com/getsentry/sentry-javascript/pull/17220).
=> feat(replay/v9): Deprecate `_experiments.autoFlushOnFeedback`

MIGRATION.md, dev-packages/browser-integration-tests/suites/replay/autoFlushOnFeedback/init.js, packages/replay-internal/src/replay.ts, packages/replay-internal/src/types/replay.ts, packages/replay-internal/src/util/addGlobalListeners.ts
Flushing on feedback widget opening is better than on submit as you get more relevant replay context, so we are going to make this the default behavior and remove the configuration option. This is deprecated in https://github.com/getsentry/sentry-javascript/pull/17219
=> feat(replay): Promote `_experiments.autoFlushOnFeedback` option as default

packages/aws-serverless/src/sdk.ts, packages/aws-serverless/src/utils.ts, packages/aws-serverless/test/sdk.test.ts
=> ref(aws-serverless): Add `type` to captured event `mechanism`

dev-packages/browser-integration-tests/suites/errors/fetch/test.ts, dev-packages/browser-integration-tests/suites/public-api/instrumentation/onError/non-string-arg/test.ts, dev-packages/browser-integration-tests/suites/public-api/instrumentation/onError/syntax-errors/test.ts, dev-packages/browser-integration-tests/suites/public-api/instrumentation/onError/thrown-errors/test.ts, dev-packages/browser-integration-tests/suites/public-api/instrumentation/onError/thrown-objects/test.ts, dev-packages/browser-integration-tests/suites/public-api/instrumentation/onError/thrown-strings/test.ts, dev-packages/browser-integration-tests/suites/public-api/instrumentation/onUnhandledRejection/custom-event/test.ts, dev-packages/browser-integration-tests/suites/public-api/instrumentation/onUnhandledRejection/event/test.ts, dev-packages/browser-integration-tests/suites/public-api/instrumentation/onUnhandledRejection/thrown-errors/test.ts, dev-packages/browser-integration-tests/suites/public-api/instrumentation/onUnhandledRejection/thrown-null/test.ts, dev-packages/browser-integration-tests/suites/public-api/instrumentation/onUnhandledRejection/thrown-number/test.ts, dev-packages/browser-integration-tests/suites/public-api/instrumentation/onUnhandledRejection/thrown-object-complex/test.ts, dev-packages/browser-integration-tests/suites/public-api/instrumentation/onUnhandledRejection/thrown-objects/test.ts, dev-packages/browser-integration-tests/suites/public-api/instrumentation/onUnhandledRejection/thrown-strings/test.ts, dev-packages/browser-integration-tests/suites/public-api/instrumentation/onUnhandledRejection/thrown-undefined/test.ts, dev-packages/e2e-tests/test-applications/astro-4/tests/errors.client.test.ts, dev-packages/e2e-tests/test-applications/astro-5/tests/errors.client.test.ts, dev-packages/e2e-tests/test-applications/solid-solidrouter/tests/errors.test.ts, dev-packages/e2e-tests/test-applications/solid/tests/errors.test.ts, dev-packages/e2e-tests/test-applications/sveltekit-2.5.0-twp/tests/errors.test.ts, packages/browser/src/integrations/globalhandlers.ts
Adjusts the `mechanism.type` field for errors caught `onerror` or `onunhandledrejection`. Aligns the naming scheme with [trace origin](https://develop.sentry.dev/sdk/telemetry/traces/trace-origin/) naming scheme.
ref #17250 
ref #17212
=> ref(browser): Adjust `mechanism.type` in globalHandlersIntegration

packages/solidstart/src/vite/sourceMaps.ts, packages/solidstart/test/vite/sourceMaps.test.ts
Streamlines solidstart build logs:
1. Only show messages when `debug: true`
2. Show short message when sourcemaps: false and debug: false
=> feat(solidstart): Streamline build logs

packages/react-router/src/vite/buildEnd/handleOnBuildEnd.ts, packages/react-router/src/vite/makeEnableSourceMapsPlugin.ts, packages/react-router/test/vite/sourceMaps.test.ts
Streamlines react router build logs. Those are mostly already gated behind `debug`, so smaller changes here:
1. Streamline with style from other parts of the SDK
2. Log compact message when source maps are disabled without `debug: true`
3. Add some tests for this
=> feat(react-router): Streamline build logs

CHANGELOG.md
The `v9` branch has been added to publish: https://github.com/getsentry/publish/pull/6073
=> meta(changelog): Update changelog for 9.44.2

CHANGELOG.md
Adds an important change entry for #16820 for the next release
=> chore(changelog): Add entry for `ignoreSpans`

packages/nuxt/src/vite/sourceMaps.ts, packages/nuxt/test/vite/sourceMaps.test.ts
This updates nuxt build logs a bit:
1. Make sure everything is gated behind `debug: true`
2. Show short message when sourceMaps: false without `debug: true`
3. Adjust messages to align with other SDKs a bit more.
4. Avoid `consoleSandbox` which we do not need there
=> feat(nuxt): Streamline build logs

dev-packages/e2e-tests/test-applications/nuxt-3-min/nuxt.config.ts, dev-packages/e2e-tests/test-applications/nuxt-3-min/pages/rendering-modes/client-side-only-page.vue, dev-packages/e2e-tests/test-applications/nuxt-3-min/pages/rendering-modes/isr-1h-cached-page.vue, dev-packages/e2e-tests/test-applications/nuxt-3-min/pages/rendering-modes/isr-cached-page.vue, dev-packages/e2e-tests/test-applications/nuxt-3-min/pages/rendering-modes/pre-rendered-page.vue, dev-packages/e2e-tests/test-applications/nuxt-3-min/pages/rendering-modes/swr-1h-cached-page.vue, dev-packages/e2e-tests/test-applications/nuxt-3-min/pages/rendering-modes/swr-cached-page.vue, dev-packages/e2e-tests/test-applications/nuxt-3-min/tests/tracing.cached-html.test.ts, dev-packages/e2e-tests/test-applications/nuxt-4/app/pages/rendering-modes/client-side-only-page.vue, dev-packages/e2e-tests/test-applications/nuxt-4/app/pages/rendering-modes/isr-1h-cached-page.vue, dev-packages/e2e-tests/test-applications/nuxt-4/app/pages/rendering-modes/isr-cached-page.vue, dev-packages/e2e-tests/test-applications/nuxt-4/app/pages/rendering-modes/pre-rendered-page.vue, dev-packages/e2e-tests/test-applications/nuxt-4/app/pages/rendering-modes/swr-1h-cached-page.vue, dev-packages/e2e-tests/test-applications/nuxt-4/app/pages/rendering-modes/swr-cached-page.vue, dev-packages/e2e-tests/test-applications/nuxt-4/nuxt.config.ts, dev-packages/e2e-tests/test-applications/nuxt-4/tests/tracing.cached-html.test.ts, packages/nuxt/src/runtime/plugins/sentry.server.ts, vite/vite.config.ts
> Backport of https://github.com/getsentry/sentry-javascript/pull/17305
Don't inject tracing meta tags on cached HTML pages (SWR and pre-rendered pages). This means won't have connected traces for those pages anymore. But before, multiple pageloads were listed in one trace as they were all connected to one backend request.
Closes https://github.com/getsentry/sentry-javascript/issues/16045
I spent most of the time creating the tests for this PR and verifying it works - the logic is so small 😅
=> feat(v9/nuxt): Do not inject trace meta-tags on cached HTML pages (#17305)

packages/node/src/integrations/tracing/openai/instrumentation.ts
Both of:
- import OpenAI from `openai` 
- import { OpenAI } from`openai`
Should point to the instrumented wrapper function.
=> fix(node): Assign default export of `openai` to the instrumented fn

.cursor/BUGBOT.md
Cursor's bugbot PR review feature accepts [custom rules](https://docs.cursor.com/en/bugbot#rules). Let's use this to enhance Cursor's reviewing capabilities with SDK-specific conventions. This PR adds a couple of them, paired with some more general important concerns. 
As a general rule of thumb: Let's add things that are hard to lint against but should still be flagged (like span origin or exception mechanisms). If this causes cursor to spam us with crap, we can always make things more or less specific of course. But I think this is worth a try.
=> chore(repo): Add Cursor Bugbot PR Review rules

docs/changelog/v8.md
Merged https://github.com/getsentry/sentry-javascript/pull/17327 before I could include these changes
=> chore: Correct title for v8 changelog

scripts/get-commit-list.ts
Commits like `meta: Re-organize changelog to add v8 page` tripped this up. Our changelog entries always follow `meta(changelog)` so we should just check for that.
=> ref: Make `lastReleasePos` checks for yarn changelog stricter

packages/react-router/src/vite/buildEnd/handleOnBuildEnd.ts, packages/react-router/test/vite/buildEnd/handleOnBuildEnd.test.ts, yarn.lock
Sentry CLI's `cli.releases.uploadSourceMaps` method previously never rejected when the actual CLI binary execution exited with an error code. In CLI 2.49.0 and 2.50.0 I added a new execution mode variant (`rejectOnError`) which continues to pipe stdio to the process (the RR SDKs' upload script) but now also rejects on error.
This PR bumps Sentry CLI and configures it to actually reject now. We already catch the rejection and fail silently. Nothing changed here.
=> fix(react-router): Ensure source map upload fails silently if Sentry CLI fails

dev-packages/browser-integration-tests/suites/integrations/globalHandlers/dataUrls/subject.js, dev-packages/browser-integration-tests/suites/integrations/globalHandlers/dataUrls/test.ts, packages/browser/src/integrations/globalhandlers.ts
[#17218](https://github.com/getsentry/sentry-javascript/pull/17218) adjusted data URI stack line parsing for most errors that go through the stack parsers (fully for node, line truncation in general). This PR now applies a similar logic to `globalHandlersIntegration` which in some conditions applies a stack frame that doesn't go through the same stack parser.
=> fix(browser): Handle data urls in errors caught by `globalHandlersIntegration`

packages/bun/src/types.ts
As raised in #16969, the Bun SDK doesn't currently export `skipOpenTelemetrySetup` in the SDK init options type, altghough the option can be correctly passed to the underlying `NodeClient`. This PR exports the option now.
https://github.com/getsentry/sentry-javascript/issues/16969#issuecomment-3163126700
=> feat(bun): Export `skipOpenTelemetrySetup` option

packages/nuxt/src/server/sdk.ts, packages/nuxt/test/server/sdk.test.ts
I just found out Nuxt is dropping spans for catch-all routes.
related to https://github.com/getsentry/sentry-javascript/pull/16843 (as we have parametrized routes since then)
backport of https://github.com/getsentry/sentry-javascript/pull/17357
=> fix(v9/nuxt): Do not drop parametrized routes (#17357)

dev-packages/node-integration-tests/package.json, dev-packages/node-integration-tests/suites/tracing/vercelai/scenario-v5.mjs, dev-packages/node-integration-tests/suites/tracing/vercelai/test.ts, dev-packages/node-integration-tests/utils/runner.ts
This update enhances the Node integration test runner to support per-scenario dependency overrides via a temporary folder that contains package.json.
When additionalDependencies are provided, the runner now:
1. Creates a unique temp directory with a package.json containing the requested dependencies.
2. Copies the ESM and CJS versions of the scenario and instrument files into the temp directory.
3. Installs the specified dependency versions.
4. Runs tests 
ESM and CJS test modes continue to run normally using the files from the temp workspace.
Also adds:
- Minimal test scenario for vercel AI test using ai@^5.0.0. (Adjusted expectations to match the current v5 output format)
=> test(node): Enable additionalDependencies in integration runner

dev-packages/node-integration-tests/utils/runner.ts
Noticed locally that I sometimes got unexpected un-removed `tmp_xxx` dirs in node-integration tests. After some debugging, I figured out the reason: We clean the tmp dir up in `afterAll` of the test. However, if all tests inside are skipped, `afterAll` is not executed. So if you run tests in a filtered way - e.g. `yarn test -t "xxx"` - it would create the tmp dirs, but not delete them.
This PR fixes this by moving the creation of the tmp dir into `beforeAll`, which equally is not executed when all tests are skipped.
=> test(node): Ensure runner does not create unused tmp files

packages/nuxt/README.md, packages/nuxt/src/module.ts
Removes the beta notice from the readme.
I also changed some logs as it's actually possible to enable tracing during dev mode - thankfully, the command prints you the correct path to the Sentry server config 🙌
=> docs(nuxt): Remove beta notice

packages/nuxt/test/server/sdk.test.ts
The test relied on `flush` and if the network functionality of CI does not work 100%, this test produces a timeout and fails.
=> test(nuxt): Don't rely on flushing for lowQualityTransactionFilter

packages/astro/.eslintrc.cjs, packages/astro/src/integration/index.ts, packages/astro/src/integration/types.ts, packages/astro/test/buildOptions.test-d.ts, packages/astro/test/integration/index.test.ts, packages/astro/test/integration/snippets.test.ts, packages/astro/tsconfig.vite.json, packages/astro/vite.config.ts
As Astro currently mixes build-time and runtime options, the `release` option was omitted from the type. It's only possible to set this option with the `unstable_sentryVitePluginOptions` :( 
Closes https://github.com/getsentry/sentry-javascript/issues/17067
=> feat(astro): Align options with shared build time options type

.size-limit.js, dev-packages/e2e-tests/test-applications/nextjs-15/app/ai-error-test/page.tsx, dev-packages/node-integration-tests/suites/tracing/anthropic/instrument-with-options.mjs, dev-packages/node-integration-tests/suites/tracing/anthropic/instrument-with-pii.mjs, dev-packages/node-integration-tests/suites/tracing/anthropic/instrument.mjs, dev-packages/node-integration-tests/suites/tracing/anthropic/scenario.mjs, dev-packages/node-integration-tests/suites/tracing/anthropic/test.ts, packages/astro/src/index.server.ts, packages/aws-serverless/src/index.ts, packages/bun/src/index.ts, packages/core/src/index.ts, packages/core/src/utils/ai/gen-ai-attributes.ts, packages/core/src/utils/ai/utils.ts, packages/core/src/utils/anthropic-ai/constants.ts, packages/core/src/utils/anthropic-ai/index.ts, packages/core/src/utils/anthropic-ai/types.ts, packages/core/src/utils/anthropic-ai/utils.ts, packages/core/src/utils/openai/index.ts, packages/core/src/utils/openai/streaming.ts, packages/core/src/utils/openai/utils.ts, packages/core/src/utils/vercel-ai/utils.ts, packages/google-cloud-serverless/src/index.ts, packages/node/src/index.ts, packages/node/src/integrations/tracing/anthropic-ai/index.ts, packages/node/src/integrations/tracing/anthropic-ai/instrumentation.ts, packages/node/src/integrations/tracing/index.ts
This PR adds official support for instrumenting Anthropic AI SDK calls in Node with Sentry tracing, following OpenTelemetry semantic conventions for Generative AI.
We instrument the following Anthropic AI SDK methods:
-  messages.create
- messages.countTokens
- models.get
- models.retrieve
- completions.create
Supported in:
- Node.js (ESM and CJS) 
- Will be added to cloudflare workers and vercel edge functions exports. 
The anthropicAIIntegration() accepts the following options:
```
// The integration respects your sendDefaultPii client option
interface AnthropicAiOptions {
recordInputs?: boolean;   // Whether to record prompt messages
recordOutputs?: boolean;  // Whether to record response text
}
```
=> feat(node): Add Anthropic AI integration

packages/cloudflare/test/integrations/fetch.test.ts, packages/core/src/utils/isSentryRequestUrl.ts, packages/core/test/lib/utils/isSentryRequestUrl.test.ts, packages/replay-internal/test/integration/shouldFilterRequest.test.ts, packages/vercel-edge/test/wintercg-fetch.test.ts
This PR makes a change to our `isSentryRequestUrl` utility which is used in various parts of the SDKs.
The function checks both, the DSN as well as the `tunnel` option to determine if a request URL is a URL to Sentry. I would argue, we should only return `true` for requests to Sentry's ingest endpoint. For example, if users make regular requests to the Sentry API from within their app that uses a Sentry SDK, we should not special case that request.
Therefore, this PR makes the check for the request URL more specific: 
- If `tunnel` is not provided, return `true` iff the the url includes the host of the DSN AND if it includes the `sentry_key` query param. This param is mandatory to be sent along, as it's equal to the [public key of the DSN …
=> fix(core): Only consider ingest endpoint requests when checking `isSentryRequestUrl`

dev-packages/node-integration-tests/suites/tracing/anthropic/scenario-stream.mjs, dev-packages/node-integration-tests/suites/tracing/anthropic/test.ts, packages/core/src/utils/anthropic-ai/constants.ts, packages/core/src/utils/anthropic-ai/index.ts, packages/core/src/utils/anthropic-ai/streaming.ts, packages/core/src/utils/anthropic-ai/types.ts
This PR adds support for streamed Anthropic Messages API responses in the Core AI instrumentation. It detects streaming via `messages.create({…, stream: true})` and `messages.stream(...),` and marks spans with stream related attributes. It also aggregates token usage from stream events and records streamed text when PII capture is enabled.
=> feat(core): Stream responses Anthropic AI

packages/browser/rollup.bundle.config.mjs, packages/browser/src/index.bundle.replay.feedback.ts
I think we originally decided to only have a error + feedback bundle and a error + tracing + replay + feedback bundle for simplicity. But I suppose it does not really make things easier that there is exactly one (error + replay + feedback) missing, so I'd just add this here now. Esp. if we want to add this in the loader this will be much easier to handle.
=> feat(browser): Add replay.feedback CDN bundle

dev-packages/node-integration-tests/suites/tracing/anthropic/instrument-with-pii.mjs, dev-packages/node-integration-tests/suites/tracing/anthropic/instrument.mjs, dev-packages/node-integration-tests/suites/tracing/anthropic/scenario-stream.mjs, dev-packages/node-integration-tests/suites/tracing/anthropic/scenario.mjs, packages/browser/src/index.bundle.feedback.ts, packages/browser/src/index.bundle.tracing.replay.feedback.ts
This adds the `sendFeedback` method to the CDN bundle exports. This should not really add bundle size as this is used by the feedback integration anyhow I believe.
(Some unrelated prettier fixes somehow also got into this PR, not sure how this got on develop)
=> feat(browser): Export `sendFeedback` from CDN bundles

dev-packages/e2e-tests/test-applications/astro-5/sentry.client.config.js, dev-packages/e2e-tests/test-applications/astro-5/src/pages/blog/[slug].astro, dev-packages/e2e-tests/test-applications/astro-5/src/pages/index.astro, dev-packages/e2e-tests/test-applications/astro-5/tests/tracing.dynamic.test.ts, packages/astro/src/client/browserTracingIntegration.ts
This PR fixes a bug in our Astro SDK's `browserTracingIntegration`. Previously, if users followed our docs how to set a custom span name for the pageload span [via `beforeStartSpan`](https://docs.sentry.io/platforms/javascript/guides/astro/tracing/instrumentation/automatic-instrumentation/#beforeStartSpan), the name would get overwritten by our route parameterization logic. This was because the route parametrization logic ran after the span was already created and it would simply update the span name.
In this case though, we can already start the span with the parameterized name instead of updating after it was started. This has a couple of advantages:
- We get the "right" name from the start, meaning there's no time frame where we could potentially propagate a `source: 'url'` name before …
=> fix(astro): Ensure span name from `beforeStartSpan` isn't overwritten

dev-packages/e2e-tests/test-applications/aws-serverless/pull-sam-image.sh, dev-packages/e2e-tests/test-applications/aws-serverless/tests/lambda-fixtures.ts
- Speed up AWS E2E tests on CI by pulling a smaller Lambda image and not re-pulling it on Lambda startup.
- Write SAM logs to stdout on CI instead of a temp file to help debugging.
=> test(aws): Improve reliability on CI

.github/workflows/build.yml
See https://github.com/getsentry/sentry-javascript/actions/runs/17398257702/job/49385642947, this seems to not trigger the failure, I guess this is `cancelled` not `failure`
I could not really find good documentation on this but I suppose this should work!
=> ci: Ensure we fail on cancelled jobs

package.json
https://github.com/getsentry/sentry-javascript/pull/17497 probably accidentally removed our changelog script.
=> chore: Add `changelog` script back to package.json

dev-packages/cloudflare-integration-tests/suites/tracing/openai/test.ts, dev-packages/node-integration-tests/package.json, dev-packages/node-integration-tests/suites/tracing/openai/openai-tool-calls/test.ts, dev-packages/node-integration-tests/suites/tracing/openai/scenario-root-span.mjs, dev-packages/node-integration-tests/suites/tracing/openai/test.ts, packages/core/src/utils/openai/index.ts, yarn.lock
We used to mock the OpenAI client and manually instrument this. This adds a test for actual auto-instrumentation of OpenAI, and adjusts the origin to be fixed.
=> fix(node): Add `origin` for OpenAI spans & test auto instrumentation

dev-packages/node-integration-tests/suites/tracing/vercelai/v5/test.ts
Something 5.0.31 causes weird errors around `msw` not being found.
Potentially related: https://github.com/vercel/ai/issues/8469
=> test(node-integration-tests): pin ai@5.0.30 to fix test fails

dev-packages/cloudflare-integration-tests/package.json, dev-packages/node-integration-tests/package.json, yarn.lock
We only need to use the `link:...` syntax in E2E tests which are not in the workspace.
Also cleans up some other deps that somehow are not in sync in yarn.lock...?
=> chore: Use proper `test-utils` dependency in workspace

dev-packages/e2e-tests/test-applications/aws-serverless/src/lambda-functions-layer/ExperimentalExtension/index.mjs, dev-packages/e2e-tests/test-applications/aws-serverless/tests/layer.test.ts, dev-packages/rollup-utils/bundleHelpers.mjs, packages/aws-serverless/package.json, packages/aws-serverless/rollup.lambda-extension.config.mjs, packages/aws-serverless/scripts/buildLambdaLayer.ts, packages/aws-serverless/src/init.ts, packages/aws-serverless/src/lambda-extension/aws-lambda-extension.ts, packages/aws-serverless/src/lambda-extension/debug-build.ts, packages/aws-serverless/src/lambda-extension/index.ts, packages/aws-serverless/src/lambda-extension/sentry-extension, packages/aws-serverless/test/init.test.ts
This introduces a new experimental Sentry Lambda extension within the existing Sentry Lambda layer. Sentry events are being tunnelled through the extension, where they are then forwarded to Sentry.
Initial benchmarks using ApacheBench show a reduction in request processing time of around 26% (from 243ms to 180ms on average over 100 requests; function pre-warmed).
To enable it, set `_experiments.enableLambdaExtension` in your Sentry config like this:
```js
Sentry.init({
// ...other config
dsn: "<YOUR_DSN>",
_experiments: {
enableLambdaExtension: true
}
})
```
closes #12856 
relates to #3051
=> feat(aws): Add experimental AWS Lambda extension for tunnelling events

dev-packages/e2e-tests/test-applications/astro-4/package.json, dev-packages/e2e-tests/test-applications/astro-4/playwright.config.mjs, dev-packages/e2e-tests/test-applications/astro-4/tests/errors.client.test.ts, dev-packages/e2e-tests/test-applications/astro-4/tests/tracing.static.test.ts, dev-packages/e2e-tests/test-applications/astro-5/package.json, dev-packages/e2e-tests/test-applications/astro-5/playwright.config.mjs, dev-packages/e2e-tests/test-applications/astro-5/tests/errors.client.test.ts, dev-packages/e2e-tests/test-applications/astro-5/tests/tracing.serverIslands.test.ts, dev-packages/e2e-tests/test-applications/astro-5/tests/tracing.static.test.ts, packages/astro/src/server/middleware.ts, packages/astro/src/server/sdk.ts, packages/astro/test/server/middleware.test.ts
This refactors the astro middleware a bit to be more correct & future proof.
Right now, http.server spans are not emitted by the node http integration because import-in-the-middle does not work with Astro. So we emit our own. This PR makes astro ready to also handle the base http.server spans and enhance them with routing information.
It also handles static routes better: these do not emit spans anymore now, and do not continue traces, but instead only propagate the parametrized route to the client, no trace data.
One fundamental problem remains that is not fixed in this PR: `Sentry.init()` is only injected via `page-ssr` into SSR pages. This means that only once any SSR page is hit, the server-side part of Sentry is initialized. If you hit a prerendered (static) page first, sentry will …
=> fix(astro): Ensure traces are correctly propagated for static routes

packages/core/src/trpc.ts, packages/core/test/lib/trpc.test.ts
=> ref(core): Add `mechanism.type` to `trpcMiddleware` errors

dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/linked-traces/consistent-sampling/meta-precedence/test.ts, dev-packages/browser-integration-tests/suites/tracing/request/fetch-tracing-without-performance-propagateTraceparent/subject.js, dev-packages/browser-integration-tests/suites/tracing/request/fetch-tracing-without-performance-propagateTraceparent/test.ts, dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/tracing-without-performance-propagateTraceparent/init.js, dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/tracing-without-performance-propagateTraceparent/template.html, dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/tracing-without-performance-propagateTraceparent/test.ts, packages/browser/src/tracing/browserTracingIntegration.ts, packages/browser/test/tracing/browserTracingIntegration.test.ts, packages/core/src/utils/spanUtils.ts, packages/core/src/utils/traceData.ts, packages/core/src/utils/tracing.ts, packages/core/test/lib/utils/traceData.test.ts, packages/core/test/lib/utils/tracing.test.ts
This PR adjusts how we set treat the `parentSpanId` when propagating it in an SDK configured for [tracing without performance](https://develop.sentry.dev/sdk/telemetry/traces/tracing-without-performance). Previously, we didn't set the `propagationSpanId` on the `propagationContext` (which is supposed to be serialized to the parent span id in the `sentry-trace` (and `traceparent`) header, if no active span is present.
This had the consequence that every time `getTraceData()` was called, we'd return a new, random (non-existing) parent span id. Meaning, that if we generate both, `sentry-trace` and `traceparent` headers via `getTraceData()` they'd end up with different parent span ids in the respective hedaers.
With this change, we now set a `propagationSpanId` on the PC, which has two …
=> fix(browser): Ensure propagated `parentSpanId` stays consistent during trace in TwP mode

CHANGELOG.md
As suggested in https://github.com/getsentry/sentry-javascript/pull/17613#pullrequestreview-3223271017, this PR adds a note to the changelog about https://github.com/getsentry/sentry-javascript/issues/17212. Decided to put the individual PRs into a `<details>` element because the list is really long and 99% not relevant for users.
=> chore: Add changelog note about mechanism changes

packages/core/src/eventProcessors.ts, packages/core/test/lib/client.test.ts
Avoid re-creating many sync promises where not needed.
We used to wrap every result of an event processor in a sync promise, no matter if needed or not. This is not really necessary, likely having a (very minor) perf impact but also making the stacktraces etc. more complicated then neccessary.
With this PR, we only wrap the overall result in a sync promise once, if needed, and otherwise just run the event processors directly.
Somewhat inspired by looking into this for https://github.com/getsentry/sentry-javascript/issues/17592, but likely does not actually fix this.
=> ref(core): Streamline event processor handling

CHANGELOG.md, packages/deno/src/integrations/globalhandlers.ts
Now follows the same trace origin-esque naming scheme as the [browser version](https://github.com/getsentry/sentry-javascript/blob/4b562bcbf0a81494627ab2c5a153ddbddb2d89ae/packages/browser/src/integrations/globalhandlers.ts#L101) of `globalHandlersIntegration`.
ref https://github.com/getsentry/sentry-javascript/issues/17212
=> ref(deno): Adjust `mechanism` of errors caught by `globalHandlersIntegration`

CHANGELOG.md, dev-packages/node-core-integration-tests/suites/cron/node-schedule/test.ts, dev-packages/node-core-integration-tests/suites/public-api/OnUncaughtException/basic.js, dev-packages/node-core-integration-tests/suites/public-api/OnUncaughtException/test.ts, dev-packages/node-core-integration-tests/suites/public-api/onUnhandledRejectionIntegration/test.ts, dev-packages/node-integration-tests/suites/public-api/OnUncaughtException/basic.js, dev-packages/node-integration-tests/suites/public-api/OnUncaughtException/test.ts, dev-packages/node-integration-tests/suites/public-api/onUnhandledRejectionIntegration/test.ts, packages/core/test/lib/integrations/eventFilters.test.ts, packages/node-core/src/integrations/onuncaughtexception.ts, packages/node-core/src/integrations/onunhandledrejection.ts
mechanism type now follows the trace origin-esque naming, similarly to global handlers [in browser](https://github.com/getsentry/sentry-javascript/blob/4b562bcbf0a81494627ab2c5a153ddbddb2d89ae/packages/browser/src/integrations/globalhandlers.ts#L101)
ref https://github.com/getsentry/sentry-javascript/issues/17212
=> ref(node-core): Adjust `mechanism` of `onUnhandledRejection` and `onUnhandledException` integrations

CHANGELOG.md, dev-packages/cloudflare-integration-tests/suites/basic/test.ts, dev-packages/cloudflare-integration-tests/suites/tracing/durableobject/test.ts, dev-packages/e2e-tests/test-applications/cloudflare-workers/playwright.config.ts, dev-packages/e2e-tests/test-applications/cloudflare-workers/tests/index.test.ts, packages/cloudflare/src/durableobject.ts, packages/cloudflare/src/handler.ts, packages/cloudflare/src/request.ts, packages/cloudflare/src/workflows.ts, packages/cloudflare/test/handler.test.ts, packages/cloudflare/test/request.test.ts, packages/cloudflare/test/workflow.test.ts
- Adjust the event mechanism to use the same value as the surrounding span's origin
- Adjust the durable object span origin because it didn't follow the same patter as the other origins
closes #17617
=> ref(cloudflare): Adjust event `mechanism`s and durable object origin

dev-packages/e2e-tests/test-applications/sveltekit-2-kit-tracing/package.json, dev-packages/e2e-tests/test-applications/sveltekit-2-svelte-5/package.json, dev-packages/e2e-tests/test-applications/sveltekit-2-svelte-5/tests/performance.test.ts, dev-packages/e2e-tests/test-applications/sveltekit-2/package.json
Some of our SvelteKit E2E tests started failing because the SvelteKit version wasn't pinned to a specific version but rather pulled in the latest v2 versions. https://github.com/sveltejs/kit/pull/12896 fixed a bug in Kit's client-side navigation logic that we previously implicitly tested against. 
This PR
- pins all SvelteKit versions used in our e2e tests
- adjusts one of them to use 2.41.0 (the most recent version) and adjust the test to the bugfix
=> test(sveltekit): Pin E2E test app SvelteKit versions and fix failing tests

packages/core/src/client.ts, packages/core/test/lib/client.test.ts, packages/replay-internal/src/coreHandlers/handleAfterSendEvent.ts
I noticed that we actually handled errors in `sendEnvelope` incorrectly - we would resolve this function with the rejection reason, if sending fails. this does not match the type of `TransportMakeRequestResponse`, you could actually get something like this out (and the tests actually incorrectly tested this):
```js
// transport.send() rejects with "fetch does not exist"
const res = await client.sendEnvelope(envelope);
// res --> "fetch does not exist" (string)
```
This PR fixes this to instead resolve with an empty object (which matches the expected return type).
Extracted this out of https://github.com/getsentry/sentry-javascript/pull/17641 because it is actually a bug/fix.
=> fix(core): Fix error handling when sending envelopes

dev-packages/e2e-tests/lib/getTestMatrix.ts
Adds some test for generating the test matrix to be able to easily debug it.
=> ci(test-matrix): Add logs for `getTestMatrix`

packages/remix/src/server/errors.ts, packages/remix/src/server/instrumentServer.ts
Noticed while working on https://github.com/getsentry/sentry-javascript/pull/17679, this was actually incorrect here. `handleCallbackErrors` does not actually do anything, you need to still call the function you want to call in the error case!
Actually we can just drop this as this error is handled by some other handler anyhow, I think, according to the tests!
=> ref(remix): Avoid unnecessary error wrapping `HandleDocumentRequestFunction`

packages/browser/test/profiling/integration.test.ts, packages/bun/src/transports/index.ts, packages/core/src/client.ts, packages/core/src/transports/base.ts, packages/core/test/lib/client.test.ts, packages/deno/src/integrations/deno-cron.ts, packages/deno/src/transports/index.ts, packages/node-core/src/sdk/client.ts, packages/node-core/test/sdk/client.test.ts, packages/replay-internal/src/util/sendReplayRequest.ts
We make quite heavy use of it in event processing, not touching this for now, but in other places it should not be needed IMHO. These are all places that will never be sync generally speaking so it is fine to make them "proper" async.
Somewhat related to https://github.com/getsentry/sentry-javascript/pull/17634
=> ref: Avoid some usage of `SyncPromise` where not needed

packages/node-core/src/integrations/http/index.ts, packages/node/src/integrations/http.ts
Looking at https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status#redirection_messages, it seems that we should not filter out 300, 302 and 304 status codes by default:
> [300 Multiple Choices](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/300)
In [agent-driven content negotiation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Content_negotiation#agent-driven_negotiation), the request has more than one possible response and the user agent or user should choose one of them. There is no standardized way for clients to automatically choose one of the responses, so this is rarely used.
> [304 Not Modified](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/304)
This is used for caching purposes. It tells the client that the response …
=> feat(node): Do not drop 300 and 304 status codes by default

packages/core/src/utils/should-ignore-span.ts, packages/core/src/utils/spanUtils.ts, packages/core/test/lib/client.test.ts, packages/core/test/lib/tracing/sentrySpan.test.ts, packages/core/test/lib/utils/should-ignore-span.test.ts
- Emit a debug log when a span matches `ignoreSpans`
- Adjust the warning when returning `null` in `beforeSendSpan` to suggest `ignoreSpans` instead
closes https://github.com/getsentry/sentry-javascript/issues/17687
=> ref(core): Add debug log when dropping a span via `ignoreSpans`

dev-packages/browser-integration-tests/suites/integrations/thirdPartyErrorsFilter/init.js, dev-packages/browser-integration-tests/suites/integrations/thirdPartyErrorsFilter/subject.js, dev-packages/browser-integration-tests/suites/integrations/thirdPartyErrorsFilter/template.html, dev-packages/browser-integration-tests/suites/integrations/thirdPartyErrorsFilter/test.ts, dev-packages/browser-integration-tests/suites/integrations/thirdPartyErrorsFilter/thirdPartyScript.js, packages/core/src/integrations/third-party-errors-filter.ts, packages/core/test/lib/integrations/third-party-errors-filter.test.ts
As reported in https://github.com/getsentry/sentry-javascript/issues/17674 our previous filter to exclude builtin or native stack frames from `thirdPartyErrorFilterIntegration` filtering logic would incorrectly still let some native frames slip through. This PR expands the check and lets the integration only consider frames with a filename (as previously) AND with at least a `lineno` or `colno`. If neither of these properties are present, we exclude them from being a factor in determining 1st vs. 3rd party. 
Also added integration tests for `thirdPartyErrorsFilterIntegration`.
closes https://github.com/getsentry/sentry-javascript/issues/17674
=> fix(core): Ensure builtin stack frames don't affect `thirdPartyErrorFilterIntegration`

dev-packages/browser-integration-tests/suites/tracing/ignoreSpans/init.js, dev-packages/browser-integration-tests/suites/tracing/ignoreSpans/test.ts, packages/core/src/client.ts, packages/core/src/tracing/idleSpan.ts
This PR fixes a problem reported in https://github.com/getsentry/sentry-javascript/issues/17451 where ignoring spans in idle root spans (pageload and navigations most prominently) caused the root span duration to be perceived much longer than reasonable. This is only a problem for idle spans in browser, so this PR applies a pragmatic fix to adjust the end time stamp: 
We already adjust the time stamp when we end the idle span. So we might as well at this point take any to-be-removed-because-of-`ignoreSpans` spans out of this calculation. This should work well enough without throwing a bunch of idle-span specific logic into the client or completely changing the point in the event lifecycle where `ignoreSpans` is applied.
closes https://github.com/getsentry/sentry-javascript/issues/17451
=> fix(browser): Ensure idle span duration is adjusted when child spans are ignored

packages/core/src/client.ts, packages/core/src/index.ts, packages/core/src/integrations/moduleMetadata.ts, packages/core/src/integrations/third-party-errors-filter.ts, packages/core/src/metadata.ts
Quick PR to streamline the stack frame `module_metadata` property assignment (`addMetadataToStackFrames`) and cleanup (`stripMetadataFromStackFrames`) logic, since we can use optional chaining now without a bundle size hit from polyfilling. 
Originally went with moving the cleanup logic into the client but decided against it due to the bundle size hit (see comment).
=> ref(core): Streamline `module_metadata` assignment and cleanup functions

packages/core/src/tracing/utils.ts, packages/core/test/lib/tracing/utils.test.ts
We often store scopes on spans via `setCapturedScopesOnSpan` and retrieve them via `getCapturedScopesOnSpan`. This change wraps the scopes in `WeakRef` to attempt fixing a potential memory leak when spans hold on to scopes indefinitely.
The downside is spans might end up with undefined scopes on them if the scope was garbage collected, we'll have to see if that's an issue or not.
=> ref(core): Wrap scopes in `WeakRef` when storing scopes on spans

dev-packages/e2e-tests/test-applications/nuxt-3-dynamic-import/package.json, dev-packages/e2e-tests/test-applications/nuxt-3-min/package.json, dev-packages/e2e-tests/test-applications/nuxt-3-top-level-import/package.json, dev-packages/e2e-tests/test-applications/nuxt-3/package.json, dev-packages/e2e-tests/test-applications/nuxt-4/package.json, dev-packages/e2e-tests/test-applications/solidstart-dynamic-import/package.json, dev-packages/e2e-tests/test-applications/solidstart-spa/package.json, dev-packages/e2e-tests/test-applications/solidstart-top-level-import/package.json, dev-packages/e2e-tests/test-applications/solidstart/package.json
This PR unblocks our CI which pas failing because:
- Nuxt and SolidStart rely on nitro which relies on on `@vercel/nft`
- `import-in-the-middle` received a [bug fix ](https://github.com/nodejs/import-in-the-middle/pull/205/files) which mixes `require` and `import` statements in `hooks.mjs`. This was released [in `1.14.3`](https://github.com/nodejs/import-in-the-middle/releases/tag/import-in-the-middle-v1.14.3)
- Apparently, nft can't trace modules that use both, `import` and `require` statements, so the `require`'d `hooks.js` file is not added to the subset of modules nft returns (we're working on a minimal reproduction and bug report for nft)
As a result, we have to pin IITM to the version before the bugfix (`1.14.2`) until either IITM reverts the fix or NFT releases a fix. The terrible …
=> test(e2e): Pin `import-in-the-middle@1.14.2` due to `@vercel/nft` incompatibility

dev-packages/node-integration-tests/suites/tracing/anthropic/scenario.mjs, dev-packages/node-integration-tests/suites/tracing/anthropic/test.ts, packages/core/src/utils/anthropic-ai/index.ts, packages/core/src/utils/anthropic-ai/streaming.ts
Previously, we completely walked over anthropic's SDK and replaced `message.stream` with our own method that returns an async generator. This breaks the SDK as `MessageStream` has further user callable api, such as adding event handlers.
This fix proxies `message.stream` instead of replacing it with our own method. Instead of returning an async generator, we now hook into various events to do our instrumentation.
Streams requested via `stream: true` are expected to return async generators, so the current approach still holds, the only change is that we proxy instead of overwrite.
Fixes: #17734
=> fix(core): Prevent `instrumentAnthropicAiClient` breaking MessageStream api

dev-packages/e2e-tests/test-applications/nuxt-3-dynamic-import/package.json, dev-packages/e2e-tests/test-applications/nuxt-3-min/package.json, dev-packages/e2e-tests/test-applications/nuxt-3-top-level-import/package.json, dev-packages/e2e-tests/test-applications/nuxt-3/package.json, dev-packages/e2e-tests/test-applications/nuxt-4/package.json, dev-packages/e2e-tests/test-applications/solidstart-dynamic-import/package.json, dev-packages/e2e-tests/test-applications/solidstart-spa/package.json, dev-packages/e2e-tests/test-applications/solidstart-top-level-import/package.json, dev-packages/e2e-tests/test-applications/solidstart/package.json
Should be good to revert #17777 since [IITM 1.14.4](https://github.com/nodejs/import-in-the-middle/releases/tag/import-in-the-middle-v1.14.4) was released
=> Revert "test(e2e): Pin `import-in-the-middle@1.14.2` due to `@vercel/nft` incompatibility (#17777)"

packages/aws-serverless/README.md
=> ref(aws-serverless): Improve README with better examples

packages/core/src/logs/internal.ts, packages/core/test/lib/logs/internal.test.ts, packages/replay-internal/src/integration.ts, packages/replay-internal/src/replay.ts, packages/replay-internal/test/integration/getReplayId.test.ts, packages/replay-internal/test/unit/getSessionId.test.ts
Adds an option to `getSessionId` and `getSessionId` to only return a value if the replay is sampled.
ref https://github.com/getsentry/sentry-javascript/issues/17676
=> feat(replay/logs): Only attach sampled replay Ids to logs

dev-packages/e2e-tests/test-applications/react-router-7-framework/app/context.ts, dev-packages/e2e-tests/test-applications/react-router-7-framework/app/routes.ts, dev-packages/e2e-tests/test-applications/react-router-7-framework/app/routes/performance/with-middleware.tsx, dev-packages/e2e-tests/test-applications/react-router-7-framework/package.json, dev-packages/e2e-tests/test-applications/react-router-7-framework/react-router.config.ts, dev-packages/e2e-tests/test-applications/react-router-7-framework/tests/performance/middleware.server.test.ts
Adds a test for v8 middleware + runs all tests on latest version
=> test(react-router): Test v8 middleware

packages/core/src/logs/internal.ts, packages/core/test/lib/logs/internal.test.ts
Adds a flag `replay_is_buffering` for identifying cases where the replayId is attached but the replay itself might never arrive in Sentry.
ref https://github.com/getsentry/sentry-javascript/issues/17676
=> feat(logs): Add internal `replay_is_buffering` flag

packages/core/src/utils/promisebuffer.ts, packages/core/test/lib/utils/promisebuffer.test.ts
Extracted this out of https://github.com/getsentry/sentry-javascript/pull/17782, this improved our promise buffer class a bit:
1. Remove the code path without a `limit`, as we never use this (there is a default limit used). There is also really no reason to use this without a limit, the limit is the whole purpose of this class.
2. Use a `Set` instead of an array for the internal buffer handling, this should slightly streamline stuff.
3. For `drain`, we can simplify the implementation without a timeout drastically. We can use `Promise.race()` to handle this more gracefully, which should be supported everywhere.
4. Some slight refactorings, actually improving timing semantics slightly.
=> ref(core): Improve promise buffer

.cursor/commands/publish_release.md, docs/publishing-a-release.md
This will enable just executing `/publish_release` within a cursor chat for creating a new release.
https://cursor.com/docs/agent/chat/commands 👀
=> chore: Add `publish_release` command

dev-packages/e2e-tests/test-applications/react-router-7-lazy-routes/tests/transactions.test.ts, packages/react/src/reactrouter-compat-utils/instrumentation.tsx
The React Router instrumentation created an additional `navigation` span on `pageload`.
On initial load, the lazy route has the history action `POP` and state `idle`. This leads to the generation of a `navigation` span.
I added a condition to early-return from `handleNavigation` if a page load is going on.
Closes issue (in Linear) https://linear.app/getsentry/issue/FE-551/configure-react-router-for-fully-parameterized-routes-with-sentry
=> fix(react): Do not send additional navigation span on pageload

packages/react-router/src/server/createSentryHandleRequest.tsx, packages/react-router/src/server/wrapSentryHandleRequest.ts
closes https://github.com/getsentry/sentry-javascript/issues/17749
=> fix(react-router): Fix type for `OriginalHandleRequest` with middleware
