bower.json
Ignore files not needed via bower installation.
=> Update ignored files

src/raven.js
This is a major contribution which I stumbled upon trying to get the dataCallback awesomeness working.
=> Fix spelling-error in comment

src/raven.js, test/raven.test.js
=> Preserve original console methods (fixes #373)

src/raven.js, test/raven.test.js
Hopefully fixes GH-377 for good
/cc @benvinegar
=> Handle other cases of unintialized RegExp objects

docs/integrations/index.rst
=> Add note on plugin instalation.

src/raven.js, test/raven.test.js
This makes sure we trim the data packet before being sent since the
dataCallback is freely able to modify the packet
=> Move trimming logic after data callbacks

docs/index.rst
... remove suggestion that Raven out-of-the-box "won't yield the greatest results", and rephrase try/catch as "reporting errors manually"
=> Improve intro docs

src/raven.js, test/integration/test.js
cc @mseeley – would appreciate your input
=> Wrap XMLHttp.prototype.send instead of open (fixes #453)

docs/sourcemaps.rst
cc @mattrobenolt if you could just look over language
=> Add note about needing uploaded artifacts before errors are captured

docs/integrations/angular.rst
I realize these are just docs, but would really love to hear feedback from people using Raven.js w/ Angular: @GeoTob @Sija @thomasjachmann @kukac7
=> Update documentation for Angular plugin

Gruntfile.js, package.json
Saves like 50 bytes after gzip, laugh
=> Use bundle-collapser to minify paths in module requires

plugins/react-native.js
=> Add Content-type: application/json for React Native transport

src/raven.js, test/integration/test.js, test/raven.test.js
=> Change breadcrumb data to match updated api

src/raven.js, src/utils.js, test/integration/test.js, test/utils.test.js
Fixes #573
cc @macqueen @mattrobenolt
=> Include full urls (query, doc fragment) in navigation breadcrumbs

docs/sourcemaps.rst
=> Update docs to use auth tokens

docs/sourcemaps.rst
Feature added in getsentry/sentry#3489
cc @mattrobenolt @mitsuhiko
=> Add docs for naming source files w/ ~ prefix

test/raven.test.js
Just found a comment in the code base and added a test to ensure the behaviour.
=> Add setUserContext test: should not merge with previous value

src/raven.js
=> Remove _newImage helper (not used/deprecated)

docs/integrations/angular2.rst
cc @mattrobenolt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/raven-js/648)
=> Fix bad keyword in ng 2 docs not showing user's DSN string

plugins/angular.js
Mentioned in #477
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/raven-js/658)
=> Updating angular plugin's dataCallback to call original if exists

plugins/react-native.js, test/plugins/react-native.test.js
cc @mattrobenolt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/raven-js/666)
=> Update react-native default pathStrip regex (fixes #665)

src/raven.js, test/raven.test.js
cc @macqueen @mattrobenolt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/raven-js/681)
=> Fix "Error: undefined" breadcrumbs

CHANGELOG.md, CONTRIBUTING.md, README.md, docs/config.rst, docs/index.rst, docs/integrations/react-native.rst, docs/sourcemaps.rst, docs/usage.rst, typescript/raven-tests.ts
cc @getsentry/team
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/raven-js/709)
=> Change getsentry.com => sentry.io

README.md
Fixes #691 (sort of)
cc @mattrobenolt @macqueen – this read okay to you?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/raven-js/715)
=> Update README to reflect on-premise requirements

CONTRIBUTING.md
Again, borrowed heavily from the [Redux project](https://github.com/reactjs/redux/blob/master/CONTRIBUTING.md).
cc @mattrobenolt @LewisJEllis
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/raven-js/726)
=> Update CONTRIBUTING.md w/ detail on opening issues

src/raven.js, test/integration/test.js
cc @maxbittker @lewisjellis @macqueen
=> Fix breadcrumb capture on mousemove events in some cases (fixes #724)

docs/index.rst
Updating this intro for 2016.
cc @maxbittker @macqueen @mattrobenolt
=> Better docs intro text for Raven.js

src/raven.js
=> Check evt exists before accessing properties (fixes #793)

.travis.yml, typescript/raven.d.ts
Making this a PR so I can observe it runs ...
=> Run `npm test` for CI build

vendor/TraceKit/tracekit.js
Fixes https://github.com/getsentry/raven-js/issues/800
=> Check document.location before trying to use it

src/raven.js, test/raven.test.js
Fixes #853 
/cc @zeroX-tj @benvinegar
=> Make _getHttpData still return user-agent when document is absent

docs/index.rst, docs/install.rst
=> Docs: mention webworker support, clarify old browser support

vendor/TraceKit/tracekit.js
=> Remove unused escape functions in tracekit.js

docs/integrations/angularjs.rst
=> Add -- to title line in angularjs doc

src/raven.js, test/raven.test.js
fixes #925
cc @getsentry/javascript
=> Fix TypeError in _trimBreadcrumbs when data undefined

docs/integrations/index.rst, docs/sentry-doc-config.json
=> Fix toctree angular reference in js index

docs/integrations/angularjs.rst
this codeblock syntax needs a newline before the content
=> add newline for rst formatting

typescript/raven-tests.ts, typescript/raven.d.ts
See https://github.com/getsentry/sentry-docs/pull/137
=> Change loglevel option "warn" to "warning".

docs/sourcemaps.rst
This should have been in the troubleshooting guide ages ago.
=> Add note about client config in source map docs

typescript/raven-tests.ts, typescript/raven.d.ts
Update typescript definition file to include `setDNS` function
=> Add setDSN typing definition

src/raven.js
https://github.com/getsentry/raven-js/issues/1023 for more info.
=> Defend against undefined XMLHttpRequest in _makeRequest

plugins/console.js, src/console.js, test/plugins/console.test.js
Fixes https://github.com/getsentry/raven-js/pull/653 and https://github.com/getsentry/raven-js/pull/654
=> feat: Implement `console.assert` wrapping

vendor/TraceKit/tracekit.js, vendor/json-stringify-safe/stringify.js
No other code changes done here.
via: https://github.com/getsentry/raven-js/pull/1038#issuecomment-330280969
=> ref: Run vendor code through Prettier

CONTRIBUTING.md, docs/contributing.rst
=> Fix test command in contribution guides

package.json
Ref: https://github.com/getsentry/raven-js/pull/1069
=> build: Update fetch polyfill for integration tests to v2

docs/integrations/index.rst, docs/integrations/redux.rst
=> docs: Add Redux / Redux Saga examples

Gruntfile.js, test/integration/test.js
Already emailed their support regarding issue from the comment.
Ref: https://github.com/getsentry/raven-js/issues/1032
=> ci: Add iOS 10 and Android 4.4/5.1 SauceLabs configs

docs/integrations/react.rst
sorry 😬. this wouldn't have happened if my local docs were working
=> rst needs newline to parse correctly

CONTRIBUTING.md, karma.sauce.config.js
To reflect those changes: https://github.com/getsentry/raven-js/pull/1087
=> docs: Update CONTRIBUTING.md with correct npm commands

.travis.yml
Is there a nicer way to write that in bash?
=> ci: Run SauceLabs tests only when PRs come from the org

.travis.yml, CONTRIBUTING.md, package-lock.json, package.json, scripts/deploy.js
=> Deployment automation

src/utils.js, test/utils.test.js
=> utils: make isEmptyObject check prototype #940

src/raven.js
=> Extremely helpful contribution

plugins/vue.js, test/plugins/vue.test.js
Ref: https://github.com/getsentry/raven-js/issues/1012#issuecomment-340490132
=> fix: Vue plugin doesnt explode if vm is undefined

typescript/raven.d.ts
=> Add maxBreadcrumbs to Typescript typings

src/raven.js, src/utils.js, test/utils.test.js
Fixes: https://github.com/getsentry/raven-js/issues/1136
=> fix: Add isArray util to prevent undefined stack.stack

.travis.yml
per: https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-348437627
=> ci: Revert headless Chrome workaround

typescript/raven.d.ts
=> docs: fix typo

karma.config.js
Based on https://github.com/getsentry/raven-js/pull/1195
=> ci: Fix ChromeLauncher for Travis integration tests

packages/browser/CHANGELOG.md, packages/browser/package.json, packages/browser/yarn.lock, packages/core/CHANGELOG.md, packages/core/package.json
=> feat: update raven for browser

test/integration/test.js
=> test: Fix fetch tests for fetch-incapable browsers

.npmignore
Resolve: https://github.com/getsentry/raven-js/issues/1247
=> misc: Update npmignore

src/raven.js
I'm just opening this to illustrate a layout for simplifying the logic here by re-using the existing if statements. 
this is problematic because it puts the capture message logical path in the middle of the capture exception path's normal logic, but this might be worthwhile due to the reduced duplication of logic. 
There's probably a better way than this! 
huge caveat - If you agree that this looks better, I'd appreciate if you also validated the logic in your head because I can't guarantee this actually preserves the behavior, I may have made mistakes
=> restructure captureException

src/raven.js, test/raven.test.js
I just realised it never worked as described in config docs...
=> fix: make debug mode actually work

Gruntfile.js
Resolves https://github.com/getsentry/raven-js/issues/1326
=> build: fix missing plugins in dist directory and simplify grunt build

packages/core/src/base.ts, packages/core/src/interfaces.ts, packages/core/src/scope.ts
=> fix: Make scope optional

package.json, packages/core/src/interfaces.ts, packages/core/src/sdk.ts, packages/core/test/lib/sdk.test.ts, packages/core/test/tslint.json, packages/types/src/index.ts, packages/typescript/tslint.json, packages/utils/src/index.ts, packages/utils/src/is.ts, packages/utils/src/object.ts, packages/utils/src/supports.ts, packages/utils/test/is.test.ts, packages/utils/test/object.test.ts, packages/utils/test/tslint.json
- Integrations API
- isSomething utils methods
- supportsSomething utils methods
=> Core integrations and new is/supports utils with tests

docs/config.rst
=> Fix grammar and inconsistency

packages/browser/karma.config.js, packages/browser/package.json, packages/browser/src/backend.ts, packages/browser/src/integrations/breadcrumbs.ts, packages/browser/src/integrations/functiontostring.ts, packages/browser/src/integrations/index.ts, packages/browser/src/integrations/onerror.ts, packages/browser/src/integrations/onunhandledrejection.ts, packages/browser/src/integrations/tracekit.js, packages/browser/src/integrations/trycatch.ts, packages/browser/src/integrations/tslint.json, packages/browser/src/raven.ts, packages/browser/src/sdk.ts
Tested everything locally using quick `index.html` file:
```html
<script src="../raven-js/packages/browser/build/bundle.min.js"></script>
<script>
Sentry.init({
dsn: 'https://asdkasjd@9sdfsena.com/123'
});
Sentry.configureScope(scope => {
scope.setTag('sdk', 'browser');
});
new Promise(function(resolve, reject) {
reject(new Error("promise exception no. 1"));
});
console.log('test')
setTimeout(function() {
new Promise(function(resolve, reject) {
reject(new Error("promise exception no. 2"));
});
}, 50);
function foo(no) {
throw new Error("regular exception no. " + no);
}
setTimeout(function() {
foo(2);
}, 10);
setTimeout(function() {
foo(4);
}, 80);
setTimeout(function() {
foo(3);
}, 3000);
foo(1);
</script>
```
=> Browser integrations

packages/node/package.json, packages/node/src/backend.ts, packages/node/src/integrations/console.ts, packages/node/src/integrations/http.ts, packages/node/src/integrations/index.ts, packages/node/src/integrations/onuncaughtexception.ts, packages/node/src/integrations/onunhandledrejection.ts, packages/node/src/integrations/tslint.json, packages/node/src/raven.ts, packages/node/src/sdk.ts
Quick test code:
```js
const {
init,
captureException,
addBreadcrumb
} = require("../raven-js/packages/node/dist/index");
init({
dsn: "http://asdasdq@aas24d.com/12",
beforeSend: function(data) {
console.log(data); // it'll polute breadcrumbs, but hey, its just a test
return data;
}
});
const { get } = require("http");
get("http://example.com", res => {
console.debug("foo");
captureException(new Error("asd"));
captureException(new Error("asd2"));
setTimeout(function() {
new Promise(function(res, rej) {
rej(new Error("baz"));
});
}, 1000);
setTimeout(function() {
new Promise(function(res, rej) {
rej(new Error("baz"));
});
}, 2000);
});
```
=> Node integrations

packages/browser/src/index.ts, packages/browser/src/sdk.ts, packages/browser/test/index.test.ts, packages/core/src/sdk.ts, packages/hub/src/global.ts, packages/hub/src/hub.ts, packages/hub/src/index.ts, packages/hub/src/interfaces.ts, packages/hub/src/scope.ts, packages/hub/test/lib/global.test.ts, packages/hub/test/lib/hub.test.ts, packages/hub/test/lib/scope.test.ts, packages/minimal/src/index.ts, packages/minimal/test/lib/minimal.test.ts, packages/minimal/test/mocks/client.ts, packages/node/src/hub.ts, packages/node/src/index.ts, packages/node/src/integrations/http.ts, packages/node/src/integrations/onunhandledrejection.ts, packages/node/src/sdk.ts, packages/node/test/domain.test.ts, packages/node/test/index.test.ts
This PR makes the SDK unification paper conform
=> feat: SDK unified API

scripts/browser-upload-cdn.js
=> feat: Increase cache timeout for the new CDN

packages/raven-js/src/raven.js
This enables support for what our docs suggest is the way to customize the feedback dialog.
https://docs.sentry.io/learn/user-feedback/#customizing-the-widget
=> feat: Support dynamic set of options to showReportDialog

docs/install.rst
=> Add information about the CSP to the docs

packages/raven-js/template/_copyright.js
Fixes https://github.com/getsentry/sentry-javascript/issues/1417
=> misc: Update license template for raven-js

packages/browser/src/parsers.ts, packages/browser/src/tracekit/index.js, packages/browser/test/integration/test.js, packages/core/src/basebackend.ts, packages/node/src/parsers.ts, packages/node/test/index.test.ts
=> fix: Fixes stack trace order + es5 tracekit + basebackend impl

packages/browser/src/integrations/index.ts, packages/browser/src/integrations/linkederrors.ts, packages/browser/src/parsers.ts, packages/browser/src/sdk.ts, packages/browser/test/integrations/linkederrors.test.ts
Same as https://github.com/getsentry/sentry-javascript/pull/1511 but for the browser
=> feat: LinkedErrors integration for Browser

packages/browser/src/integrations/pluggable/ember.ts, packages/browser/src/integrations/pluggable/vue.ts
=> feat: Add integrations to sdkinfo

packages/browser/src/backend.ts, packages/browser/src/integrations/index.ts, packages/browser/src/integrations/reportingobserver.ts, packages/browser/src/sdk.ts, packages/browser/src/tracekit/index.js, packages/node/src/backend.ts, packages/utils/src/supports.ts
Resolves https://github.com/getsentry/sentry-javascript/issues/1450
=> feat: Support ReportingObserver API

packages/core/src/sdk.ts, packages/core/test/lib/sdk.test.ts
=> feat: Override default integrations provided through array options

packages/node/package.json
=> misc: Add node typings to packages/node

package.json, typedoc.js, yarn.lock
`typedoc --options ./typedoc.js` -> [docs.zip](https://github.com/getsentry/sentry-javascript/files/2383615/docs.zip)
=> feat: Add typedoc compatibility

packages/browser/src/integrations/helpers.ts, packages/browser/test/integration/test.js, packages/browser/test/integrations/helpers.test.ts
Should fix https://github.com/getsentry/sentry-javascript/issues/1541 and https://github.com/getsentry/sentry-javascript/issues/1539
=> fix: Wrap helper function revisited and tested

packages/browser/src/integrations/trycatch.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/1562
=> fix: Check for anonymous function before getting its name for mechanism

packages/browser/src/integrations/breadcrumbs.ts, packages/browser/src/integrations/globalhandlers.ts, packages/browser/src/integrations/reportingobserver.ts
So that we can do things like: https://github.com/getsentry/sentry-javascript/issues/1307#issuecomment-423620820
=> ref: Unify integrations options and set proper defaults

CHANGELOG.md, packages/browser/src/client.ts, packages/browser/src/index.ts
=> ref: ReportDialogOptions

codecov.yml
=> meta: Disable codecov command

CHANGELOG.md, packages/browser/src/integrations/helpers.ts, packages/utils/src/object.ts
Fix https://github.com/getsentry/sentry-javascript/issues/1568
=> feat: Capture wrapped function arguments as extra

CHANGELOG.md, packages/browser/src/tracekit.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/1586
=> fix: onunhandledrejection handler updates

packages/browser/src/sdk.ts
=> fix: Use ReportDialogOptions

.travis.yml
=> feat: Zeus integration

packages/hub/src/scope.ts, packages/hub/test/lib/scope.test.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/1592
=> fix: Apply scope's level to the event

packages/core/src/baseclient.ts, packages/core/src/interfaces.ts, packages/types/src/index.ts
=> ref: Remove Repo interface and repos attribute from Event

CHANGELOG.md, packages/core/src/baseclient.ts
Fixes https://github.com/getsentry/sentry-javascript/pull/1602
=> misc: Warn user when beforeSend doesnt return an event or null

CHANGELOG.md, packages/node/src/integrations/console.ts, packages/node/src/integrations/http.ts, packages/utils/src/object.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/1599
=> fix: Dont wrap native modules more than once

packages/browser/package.json, packages/browser/rollup.config.js, packages/core/src/integrations/pluggable/rewriteframes.ts, packages/node/src/parsers.ts, packages/node/src/transports/base.ts, packages/utils/src/fs.ts, packages/utils/src/path.ts, packages/utils/src/store.ts, packages/utils/test/store.test.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/1643
=> fix: Add internal path module and correct node http protocol

CHANGELOG.md, packages/browser/test/integration/console-logs.js, packages/browser/test/integration/init.js, packages/browser/test/integration/test.js, packages/browser/test/integration/throw-error.js, packages/browser/test/karma/integration-files.js, packages/core/src/baseclient.ts, packages/core/src/interfaces.ts, packages/core/test/lib/base.test.ts
=> fix: make addBreadcrumb sync

packages/browser/test/integration/init.js, packages/browser/test/integration/test.js, packages/core/src/integrations/inboundfilters.ts, packages/core/test/lib/integrations/inboundfilters.test.ts
Ref https://github.com/getsentry/sentry-javascript/issues/1700
=> [fix] Correct usage of init config in inboundFilters

packages/node/README.md
=> Add es6 import syntax to README 

packages/utils/package.json
=> Replace ; with && in @sentry/types build package script

CHANGELOG.md, packages/browser/examples/README.md, packages/browser/examples/app.js, packages/browser/examples/bundle.js, packages/browser/examples/index.html
=> Added @sentry/browser examples page

packages/browser/package.json, packages/browser/test/manual/npm-build.js, packages/browser/test/manual/test-code.js, scripts/browser-integration.sh
Prevents https://github.com/getsentry/sentry-javascript/issues/1757 from doing ever again.
=> test: Add manual webpack tests with jsdom browser environment

CHANGELOG.md, packages/browser/rollup.config.js, packages/browser/src/integrations/helpers.ts, packages/browser/src/integrations/pluggable/ember.ts, packages/browser/src/integrations/pluggable/vue.ts, packages/browser/src/parsers.ts, packages/browser/test/parsers.test.ts, packages/node/src/handlers.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/1766
=> fix: Correctly detect and remove wrapped function frames

.travis.yml, .vscode/extensions.json, package.json, packages/browser/package.json, packages/browser/src/integrations/trycatch.ts, packages/core/package.json, packages/hub/package.json, packages/minimal/package.json, packages/node/package.json, packages/node/test/index.test.ts, packages/types/package.json, packages/typescript/package.json, packages/typescript/tsconfig.json, packages/utils/package.json, scripts/test.sh, yarn.lock
=> fix: Node 10 tests

CHANGELOG.md, packages/utils/.npmignore
https://github.com/getsentry/sentry-javascript/issues/1552#issuecomment-453141226
=> fix: Don't npm ignore esm for utils

CHANGELOG.md, packages/utils/src/object.ts, packages/utils/test/object.test.ts
Resolves https://github.com/getsentry/sentry-javascript/issues/1865
=> fix: Dont mutate original input in decycle util function

CHANGELOG.md, packages/browser/src/integrations/pluggable/ember.ts, packages/browser/src/integrations/pluggable/vue.ts, packages/utils/test/object.test.ts
Resolves https://github.com/getsentry/sentry-javascript/issues/1869
=> ref: Throw SentryError if Ember/Vue instances are not provided

packages/core/src/integrations/inboundfilters.ts, packages/core/test/lib/integrations/inboundfilters.test.ts
=> fix: Use correct frame for inboundFilter methods

packages/core/src/integrations/extraerrordata.ts, packages/core/test/lib/integrations/extraerrordata.test.ts
The error name alone is not very informative, I think we should add error message here to improve that
=> Serialize error object with message in ExtraErrorData integration

.craft.yml, CHANGELOG.md, packages/browser/package.json, packages/browser/rollup.config.js
=> fix: Fix browser dist build

packages/browser/package.json
=> fix: Spelling mistake

CHANGELOG.md, packages/integrations/package.json, packages/integrations/src/angular.ts, packages/integrations/tsconfig.build.json, packages/integrations/tsconfig.esm.json, packages/integrations/tsconfig.json, tsconfig.json, yarn.lock
Fixes https://github.com/getsentry/sentry-javascript/issues/1985
=> fix: Remove angular types

packages/browser/src/integrations/breadcrumbs.ts, packages/integrations/src/captureconsole.ts, packages/integrations/src/debug.ts, packages/integrations/src/index.ts, packages/utils/src/misc.ts, packages/utils/src/object.ts
ref: https://github.com/getsentry/sentry-docs/pull/870
=> feat: CaptureConsole integration

CHANGELOG.md, packages/core/test/lib/base.test.ts, packages/hub/src/hub.ts, packages/hub/src/scope.ts, packages/hub/test/hub.test.ts, packages/hub/test/scope.test.ts
=> fix: Scope breadcrumb handling

CHANGELOG.md, packages/hub/src/scope.ts, packages/hub/test/scope.test.ts, packages/types/src/scope.ts
Add `setContext` on the Scope.
=> feat: Add setContext on scope

CHANGELOG.md, packages/browser/src/integrations/breadcrumbs.ts, packages/browser/src/integrations/helpers.ts, packages/browser/src/integrations/trycatch.ts, packages/node/src/handlers.ts, packages/utils/src/object.ts, packages/utils/test/object.test.ts
+ fix for breadcrumbs integration
=> feat: multi fill

CHANGELOG.md, packages/browser/src/integrations/breadcrumbs.ts
=> fix: HandleEvent in breadcrumb integration

CHANGELOG.md, packages/browser/src/integrations/globalhandlers.ts
Repro
https://codesandbox.io/embed/yqy8y9r3qv
=> fix: #1949

CHANGELOG.md, packages/browser/src/client.ts
=> feat: Added onLoad callback to showReportDialog

CHANGELOG.md, package.json, yarn.lock
=> fix: Force agent-base to be at version 4.3.0 to fix various issues

packages/browser/tslint.json, packages/integrations/src/angular.ts, packages/integrations/src/ember.ts, packages/integrations/src/extraerrordata.ts, packages/integrations/src/tracing.ts, packages/integrations/src/vue.ts, packages/integrations/tslint.json
Adds [no-console](https://palantir.github.io/tslint/rules/no-console/)
TSLint rule to integrations and browser repos and fixes these warnings.
=> style(lint): Introduce no-console rule to some pkg

CHANGELOG.md, packages/utils/src/supports.ts
=> fix(utils): Better native `fetch` detection via iframes

packages/browser/src/integrations/breadcrumbs.ts, packages/browser/test/integration/test.js
Fixes https://github.com/getsentry/sentry-javascript/issues/2141
=> fix: Correctly handle events that utilize handleEvent object

packages/browser/examples/README.md
fix 404 error in example by resolve symlinks
=> chore: fix 404 error in example

packages/hub/src/hub.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/2229
=> ref: Use domain Hub detection only in Node environment

packages/browser/src/integrations/breadcrumbs.ts
This removes several `any` types and replaces them with the actual type. This also removes a TODO in the XHR related code.
---
=> fix: improve usage of types

packages/core/src/integrations/functiontostring.ts, packages/core/test/lib/integrations/functiontostring.test.ts, packages/utils/src/misc.ts
=> fix: Restore correct functionToString behavior for updated fill method

CHANGELOG.md, packages/integrations/src/rewriteframes.ts, packages/integrations/test/rewriteframes.test.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/2361
=> fix: Make RewriteFrame integration process all exceptions

packages/browser/src/tracekit.ts, packages/browser/test/unit/tracekit/custom.test.ts
=> Allow sentry to work with v8 on react-native

packages/node/src/handlers.ts
=> fix: Improve incorrect ParseRequest typing

packages/browser/src/integrations/breadcrumbs.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/2357
=> fix: Respect breadcrumbs sentry:false option

packages/utils/src/supports.ts, packages/utils/src/syncpromise.ts, packages/utils/test/promisebuffer.test.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/2506
=> fix: Make sure that SyncPromise handler is called only once

packages/node/src/backend.ts
Today I spent a few time to figure out in what time units(seconds or milliseconds) to set the number. I think this explanation can help other developers.
=> ref: update comment for shutdownTimeout type description

CHANGELOG.md, packages/apm/src/hubextensions.ts, packages/apm/src/index.ts, packages/apm/src/integrations/tracing.ts, packages/apm/src/span.ts, packages/apm/src/spanstatus.ts, packages/apm/test/span.test.ts, packages/types/src/hub.ts, packages/types/src/index.ts, packages/types/src/span.ts
before:
```
ES6:  16.2129 kB
ES5:  17.1836 kB
```
after:
```
ES6:  15.8711 kB
ES5:  16.8379 kB
```
=> fix: Improve bundle size by moving span status

CHANGELOG.md, packages/apm/src/integrations/tracing.ts, packages/integrations/src/vue.ts
Also, adding more debug options to the tracing integration
Additional Span Data:
Debug Breadcrumbs:
=> feat: No longer discard transactions instead mark them deadline exceeded

packages/utils/src/dsn.ts, packages/utils/test/dsn.test.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/2591
=> fix: Handle DSN qs and show better error messages

packages/utils/src/dsn.ts, packages/utils/test/dsn.test.ts
Reverts getsentry/sentry-javascript#2635
=> Revert "fix: Handle DSN qs and show better error messages"

packages/browser/src/transports/fetch.ts, packages/browser/test/unit/transports/fetch.test.ts, packages/types/src/transport.ts
=> feat(browser): support fetchParameters

CHANGELOG.md, packages/gatsby/src/gatsby-browser.js
Add SDK identifier so we are able to track it.
=> fix: Add gatsby sdk identifier

packages/apm/src/integrations/tracing.ts
Followup #2711
Tested cases
```js
await fetch('/?1', { headers: {'content-type': 'application/json'} });
await fetch(new Request('/?1.1', { headers: {'content-type': 'application/json'} }));
await fetch('/?2', { headers: new Headers({ 'content-type': 'application/json' }) });
await fetch(new Request('/?2.1', { headers: new Headers({ 'content-type': 'application/json' }) }));
await fetch('/?3', { headers: [['content-type', 'application/json']] });
await fetch(new Request('/?3.1', { headers: [['content-type', 'application/json']] }));
await fetch('/?4');
await fetch(new Request('/?4.1'));
```
cc @Janpot
=> fix: Make it also work if someone passes request obj

packages/gatsby/.npmignore, packages/gatsby/package.json
Fixes https://github.com/getsentry/sentry-javascript/pull/2711#issuecomment-655511616
=> fix: Include correct gatsby files in npm tarball

CHANGELOG.md, packages/react/package.json, yarn.lock
Fix the typing issue on `yarn.lock`, also add changelog update.
=> fix: React Router Typing and CHANGELOG

packages/gatsby/gatsby-node.js
=> feat: support process.env.SENTRY_RELEASE

packages/react/src/errorboundary.tsx, packages/react/src/reactrouter.tsx, packages/react/src/types.ts
=> fix(react): Type more react router types as any

packages/tracing/.npmignore
ref https://github.com/getsentry/sentry-javascript/blob/master/packages/browser/.npmignore
https://unpkg.com/browse/@sentry/browser/build/ is Found
https://unpkg.com/browse/@sentry/tracing/build/ is NotFound
=> feat(tracing): Add build dir in npm package

packages/integrations/src/offline.ts
=> fix: offline integration type as any

packages/serverless/.eslintrc.js, packages/serverless/package.json, packages/serverless/src/awslambda.ts, packages/serverless/test/__mocks__/@sentry/node.ts, packages/serverless/test/awslambda.test.ts, packages/serverless/tsconfig.json
=> test: Add a test suite with 100% [brag] code coverage to AWSLambda handler

MIGRATION.md
=> Typo: attack => attach

packages/react/package.json
Closes https://github.com/getsentry/sentry-javascript/issues/3020
=> ref: Add React 17.x to peerDependencies

packages/tracing/src/integrations/express.ts
=> fix: Express transaction name

packages/node/src/stacktrace.ts
No code changed. Simply a comment changed for TypeDoc
=> style: minor typo in src/stacktrace.ts:25

packages/browser/src/transports/base.ts, packages/browser/src/transports/fetch.ts, packages/node/src/transports/base.ts, packages/node/test/integrations/http.test.ts, packages/tracing/test/span.test.ts
Just a bunch of small stuff I found in my travels.
=> chore(various): Tiny fixes

packages/utils/src/instrument.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/3221
=> fix: Don't break when function call context is undefined

packages/node/src/parsers.ts, packages/node/test/parsers.test.ts
=> fix: Code preview not working with ESM (#3262)

CHANGELOG.md
This PR,
- Added entry in Changelog for release 6.2.1
=> Release: 6.2.1

packages/nextjs/README.md
Updates the README with general description and examples.
=> docs: Update README

README.md
=> We're hiring

packages/gatsby/gatsby-node.js
Vercel updated their environment variable for git commits
=> VERCEL_GITHUB_COMMIT_SHA → VERCEL_GIT_COMMIT_SHA

packages/tracing/src/integrations/mysql.ts
=> fix: MySQL tracing now attaches to createQuery

packages/browser/src/tracekit.ts, packages/browser/test/unit/tracekit/custom.test.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/3313
=> feat: Parse safari-extension and safari-web-extension errors

packages/core/src/baseclient.ts
This PR fixes a typo in comment
=> docs: Fix comment typos

packages/ember/package.json, yarn.lock
Updated and more carefully pinned our ember-source and embroider packages.
=> fix(ember): Fix embroider-safe not working on builds

packages/utils/src/object.ts
=> style(utils): Fix typo

packages/browser/src/loader.js
=> style: simplify finding the first script in document

packages/browser/src/sdk.ts, packages/hub/src/session.ts, packages/hub/test/session.test.ts, packages/nextjs/test/integration/test/client/sessionNavigate.js, packages/nextjs/test/integration/yarn.lock
=> test(hub): Remove duplicate session test

packages/ember/tests/acceptance/sentry-performance-test.js
=> test: Patch ember tests that temporarily blocks the release

packages/core/src/request.ts, packages/core/test/lib/request.test.ts
An oversight that should be fixed.
=> fix: Include DSN in envelope header for sessions

yarn.lock
Use https://github.com/atlassian/yarn-deduplicate to make sure we
dedupe deps properly.
=> chore: Run yarn-deduplicate

packages/hub/src/hub.ts, packages/hub/src/scope.ts
Casually run into one, found more with [eslint-plugin-spellcheck](https://github.com/aotaduy/eslint-plugin-spellcheck) (maybe we can integrate with that later, would require some extra config to remove noise).
---
WIP branch integrating with `eslint-plugin-spellcheck` if someone wants to take it on: https://github.com/getsentry/sentry-javascript/compare/rhcarvalho/eslint-plugin-spellcheck
=> docs: Fix several typos

packages/vue/src/errorhandler.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/3858
=> fix(vue): Attach props only if VM is available

packages/angular/package.json
See Angular 13 release: https://github.com/angular/angular/releases/tag/13.0.0
Fixes https://github.com/getsentry/sentry-javascript/issues/4182
=> feat(angular): Add Angular 13 to peer dep

.github/workflows/build.yml
Trying to not make it rebuild every time
=> ci: Switch to getsentry/size-limit-action

packages/browser/package.json, packages/ember/package.json, packages/node/package.json, packages/react/package.json, packages/serverless/package.json, packages/utils/package.json, packages/wasm/package.json, yarn.lock
Yarn workspaces should take care of everything for us here.
=> build: Remove @sentry-internal/eslint-config-sdk from package.json

packages/nextjs/src/performance/client.ts
Save on bytes by removing object.freeze.
No change is too small!
=> ref(nextjs): Remove object.freeze call

packages/tracing/src/browser/metrics.ts, packages/tracing/src/browser/request.ts, packages/tracing/src/hubextensions.ts, packages/tracing/src/transaction.ts, packages/tracing/src/utils.ts
=> ref(tracing): Remove optional chaining

packages/integration-tests/suites/public-api/setTag/init.js, packages/integration-tests/suites/public-api/setTag/template.hbs, packages/integration-tests/suites/public-api/setTag/with_non_primitives/subject.js, packages/integration-tests/suites/public-api/setTag/with_non_primitives/test.ts, packages/integration-tests/suites/public-api/setTag/with_primitives/subject.js, packages/integration-tests/suites/public-api/setTag/with_primitives/test.ts
=> test(browser): Add integration tests for `setTag`

packages/integration-tests/suites/public-api/setContext/init.js, packages/integration-tests/suites/public-api/setContext/multiple_contexts/subject.js, packages/integration-tests/suites/public-api/setContext/multiple_contexts/test.ts, packages/integration-tests/suites/public-api/setContext/non_serializable_context/subject.js, packages/integration-tests/suites/public-api/setContext/non_serializable_context/test.ts, packages/integration-tests/suites/public-api/setContext/simple_context/subject.js, packages/integration-tests/suites/public-api/setContext/simple_context/test.ts, packages/integration-tests/suites/public-api/setContext/template.hbs
=> test(browser): Add integration tests for `setContext`

packages/integration-tests/suites/public-api/setExtras/consecutive_calls/subject.js, packages/integration-tests/suites/public-api/setExtras/consecutive_calls/test.ts, packages/integration-tests/suites/public-api/setExtras/init.js, packages/integration-tests/suites/public-api/setExtras/multiple_extras/subject.js, packages/integration-tests/suites/public-api/setExtras/multiple_extras/test.ts, packages/integration-tests/suites/public-api/setExtras/template.hbs
=> test(browser): Add integration tests for `setExtras`

packages/integration-tests/suites/tracing/request/fetch/subject.js, packages/integration-tests/suites/tracing/request/fetch/test.ts, packages/integration-tests/suites/tracing/request/init.js, packages/integration-tests/suites/tracing/request/template.hbs, packages/integration-tests/suites/tracing/request/xhr/subject.js, packages/integration-tests/suites/tracing/request/xhr/test.ts
=> test(tracing): Add integration tests for client requests.

.eslintrc.js, .github/workflows/codeql-analysis.yml, packages/nextjs/test/integration/tsconfig.json
Not aiming to be comprehensive, just my autoformatter having its way with a handful of files I've recently touched. No code changes.
=> chore(various): Autoformat various config files

scenarios/browser/package.json, scenarios/browser/webpack.js, scenarios/browser/yarn.lock
Fetches all the directories with scenarios and makes an array of them for easier switching of scenarios.
=> chore(scenarios): improve scenarios DX

packages/integration-tests/suites/tracing/metrics/web-vitals-fid/template.hbs, packages/integration-tests/suites/tracing/metrics/web-vitals-fid/test.ts
=> test(tracing): Add FID tests.

MIGRATION.md
Spotted while migrating myself - so thought I'd fix it.
------------
=> Properly close code section in migration documentation

packages/angular/src/tracing.ts
Related issue: https://github.com/getsentry/sentry-javascript/issues/4157
=> fix(tracing) Browser tracing error with angular universal

CHANGELOG.md
=> chore: Add markdown links to issues in changelog

.size-limit.js, yarn.lock
Also update `yarn.lock` as it seems to have gotten out of date.
=> chore: Remove duplicate @sentry/react entry from size-limit

packages/gatsby/package.json, yarn.lock
Similar in nature to https://github.com/getsentry/sentry-javascript/pull/4635
=> feat(gatsby): Upgrade Sentry Webpack Plugin to 1.18.8

CHANGELOG.md
Should go out on Monday so we can proliferate the webpack plugin/peer deps changes!
=> meta: 6.18.1 CHANGELOG

CHANGELOG.md
Previous attempt at https://github.com/getsentry/sentry-javascript/pull/4673
=> meta: 6.18.2 changelog

packages/integrations/src/debug.ts, packages/integrations/test/debug.test.ts
Adds some unit tests for the `debug` integration.
ref: https://getsentry.atlassian.net/browse/WEB-721
=> test(integrations): Add unit tests for `Debug`

CHANGELOG.md
=> meta: Update changelog for 6.19.1

.github/workflows/build.yml
ref: https://github.com/getsentry/sentry-javascript/issues/4775
=> ci: Update getsentry/size-limit-action to v4

packages/node-integration-tests/suites/public-api/setExtra/multiple-extras/scenario.ts, packages/node-integration-tests/suites/public-api/setExtra/multiple-extras/test.ts, packages/node-integration-tests/suites/public-api/setExtra/non-serializable-extra/scenario.ts, packages/node-integration-tests/suites/public-api/setExtra/non-serializable-extra/test.ts, packages/node-integration-tests/suites/public-api/setExtra/simple-extra/scenario.ts, packages/node-integration-tests/suites/public-api/setExtra/simple-extra/test.ts
=> test(node): Add `setExtra` integration tests.

packages/node-integration-tests/suites/public-api/setExtras/consecutive-calls/scenario.ts, packages/node-integration-tests/suites/public-api/setExtras/consecutive-calls/test.ts, packages/node-integration-tests/suites/public-api/setExtras/multiple-extras/scenario.ts, packages/node-integration-tests/suites/public-api/setExtras/multiple-extras/test.ts
=> test(node): Add `setExtras` integration tests.

packages/node-integration-tests/suites/public-api/setUser/unset_user/scenario.ts, packages/node-integration-tests/suites/public-api/setUser/unset_user/test.ts, packages/node-integration-tests/suites/public-api/setUser/update_user/scenario.ts, packages/node-integration-tests/suites/public-api/setUser/update_user/test.ts
=> test(node): Add `setUser` integration tests.

packages/node-integration-tests/package.json, packages/node-integration-tests/suites/tracing/auto-instrument/mysql/scenario.ts, packages/node-integration-tests/suites/tracing/auto-instrument/mysql/test.ts, yarn.lock
=> test(node): Add integration test for MySQL auto-instrumentation.

packages/nextjs/package.json
More work from https://github.com/getsentry/sentry-javascript/pull/4819
Needed for https://github.com/getsentry/sentry-javascript/pull/4830
=> feat(nextjs): Add React 18 as a peer dep

packages/tracing/package.json
Updated tracing `sideEffects` to reflect new build paths under `build/npm/`
=> fix(tracing): Update `sideEffects` with new build paths.

CHANGELOG.md
=> meta: 6.19.7 CHANGELOG

MIGRATION.md
=> fix(migration-docs): adjust hash-link to propagation-of-baggage-header

packages/ember/README.md
There were quite a few updates especially around how config is preferred to be set, this cleans up the README to clarify and match with sentry-docs to avoid confusion.
Refs https://github.com/getsentry/sentry-javascript/issues/5182
=> fix(ember): Update README docs to match sentry-docs

packages/react/src/reactrouterv3.ts, packages/react/test/reactrouterv3.test.tsx
Ref: https://github.com/getsentry/sentry-javascript/issues/5345
Add support for setting transaction source for react-router-v3, and update the tests to validate this.
=> ref(react): Add source to react-router-v3

package.json, yarn.lock
https://github.com/prettier/prettier/blob/main/CHANGELOG.md
=> build: Upgrade prettier to 2.7.1

CHANGELOG.md
Leaving this as a draft until Lukas's angular PR gets merged.
EDIT: merged
=> meta: Update changelog for version 7.7.0

.craft.yml
Ref: https://github.com/getsentry/sentry-javascript/issues/4894
=> build(craft): Add Remix SDK to release registry

packages/tracing/src/span.ts
Right now, if one of our SDKs is running on a cloud provider and therefore all the user has is logs, there's no real way to debug missing spans. Are they not finishing in time and getting dropped? Are they even starting in the first place? No way to know.
This fixes that by adding logging to the start and end of spans., the same way we have with transactions.
=> feat(tracing): Log start and end of spans

.craft.yml
=> Revert "chore(svelte): Temporarily remove Svelte SDK as a Release Registry target (#5565)"

packages/remix/src/utils/serverAdapters/express.ts
This sets the transaction on the response so it can be finished.
=> fix(remix): Store transaction on express req

CHANGELOG.md
I didn't include the release message in the "Unreleased" section. This PR fixes that.
=> fix: changelog for 7.12.0

packages/utils/src/dsn.ts, packages/utils/test/dsn.test.ts
=> fix(utils): accept DSN URLs with empty password

README.md
Add svelte, remix, serverless and run prettier on the README file.
=> chore: Update README to include our newest packages

packages/node/src/index.ts
=> feat(node): Export Span type from `@sentry/types`

.github/workflows/build.yml
Committed via https://github.com/asottile/all-repos
=> ci: Update actions/upload-artifact to v3.1.1

packages/opentelemetry-node/README.md
Add very basic usage instructions to the (still very much WIP! and unpublished) otel package.
=> chore(otel): Add basic usage instructions to readme

packages/opentelemetry-node/README.md
ref https://github.com/getsentry/sentry-javascript/issues/6107
Adds README instructions for `SentryPropagator`.
Based on https://www.npmjs.com/package/@opentelemetry/propagator-b3
=> chore(otel): Update README to add SentryPropagator info

.github/ISSUE_TEMPLATE/bug.yml
ref #6000 
Get ready for launch 🚀
=> chore: Add otel-node to GH issue template

packages/replay/package.json
Just to make sure this remains aligned.
=> build(replay): Use proper volta config for replay

CHANGELOG.md
Need to release this to unblock profiling users with #6409
=> meta: CHANGELOG for 7.24.0

packages/react/src/profiler.tsx, packages/react/src/reactrouterv6.tsx, yarn.lock
We merged in Replay, so let's run yarn deduplicate to clean up our `yarn.lock` and hopefully improve install times.
=> ref: Run yarn deduplicate

packages/replay/CONTRIBUTING.md
Is this going to help to keep those docs up to date?
=> doc(replay): contributing note rrweb bump

packages/replay/src/constants.ts
=> feat(replay): Change `MAX_SESSION_LIFE` to 1 hour

packages/ember/tests/dummy/app/app.js
Closes https://github.com/getsentry/sentry-javascript/issues/6834
=> test(ember): Ensure tests are not flaky due to long tasks

packages/core/src/baseclient.ts, packages/replay/src/util/sendReplayRequest.ts, packages/types/src/datacategory.ts, packages/utils/src/envelope.ts
Not 100% sure if I'm missing something, but would this work?
ref https://github.com/getsentry/sentry-javascript/pull/6889
=> fix(core): Fix replay client report data category (??)

.github/workflows/build.yml
Fixes https://github.com/getsentry/sentry-javascript/issues/6911
=> ci: Increase E2E test timeout

package.json, packages/replay/demo/package.json
See: https://github.com/getsentry/sentry-javascript/pull/6962
=> chore: Upgrade local Node version to 16.9.0

.github/workflows/gitflow-sync-develop.yml, .github/workflows/gitflow-sync-master.yml
It's failing, hopefully this fixes it...
=> ci: Fix gitflow workflows

.github/workflows/build.yml, .github/workflows/gitflow-sync-master.yml
This merges a fix from develop into master to get the correct build.yml there.
=> [Gitflow] Merge develop>master to get build.yml fix

packages/integration-tests/playwright.config.ts
Should help us better identify flakes.
=> test(integration-tests): Don't retry integration tests

packages/core/test/lib/transports/offline.test.ts
=> test(core): Try and improve flakey offline test

.github/workflows/gitflow-sync-master.yml
Oops, nested the `pull_request` inside of the `push`!
=> ci: Fix yaml

CHANGELOG.md
=> meta(changelog): Update CHANGELOG for 7.37.0

package.json, packages/node-integration-tests/package.json, yarn.lock
Just to get rid of this yarn warning.
=> build: Update `apollo-server` to get rid of yarn resolution

packages/integration-tests/package.json, packages/integration-tests/suites/replay/privacy/template.html, packages/integration-tests/suites/replay/privacy/test.ts-snapshots/privacy-chromium.json, packages/integration-tests/suites/replay/privacy/test.ts-snapshots/privacy-firefox.json, packages/integration-tests/suites/replay/privacy/test.ts-snapshots/privacy-webkit.json
Requires https://github.com/getsentry/sentry-javascript/pull/7145
=> test(replay): Add <video> example to privacy test

packages/replay/README.md
Merge master branch into develop
=> [Gitflow] Merge master into develop

.github/workflows/auto-release.yml
This actually couldn't have worked before - oops!
=> ci: Fix auto-release workflow

packages/replay/package.json, yarn.lock
* https://github.com/getsentry/rrweb/releases/tag/1.104.1
* https://github.com/getsentry/rrweb/releases/tag/1.104.0
=> ref(replay): Update rrweb to 1.104.1

.vscode/settings.json
https://twitter.com/brunoksato/status/1541026637705355264?lang=en
Turned this on so that we no longer get this error:
=> chore(vscode): Add eslint working directories

packages/tracing-internal/package.json
Should fix broken e2e tests on master.
=> chore(tracing): Fix tarball generation path

packages/node/test/requestdata.test.ts
=> test(node): fix cookie test description typo

CHANGELOG.md, packages/browser-integration-tests/suites/replay/customEvents/test.ts, packages/replay/package.json, yarn.lock
See [CHANGELOG](https://github.com/getsentry/rrweb/blob/cd51c854464e803405282a1affc7fc580d2acd94/CHANGELOG.md#11060)
feat(replay): Check for node existance in mirror before appending (#82)
feat: Ensure password inputs are always masked (#78)
fix: Ensure text masking for updated attributes works (#83)
fix: Ensure unmaskTextSelector is used for masked attributes (#81)
fix: Mask <option> values for selects & radio/checkbox value (#75)
=> chore(replay): Upgrade `rrweb` and `rrweb-player`

CHANGELOG.md
Wait for https://github.com/getsentry/sentry-javascript/pull/7544 to be merged.
This will be merged into develop after the release.
=> meta(changelog): Update CHANGELOG for 7.44.2

packages/node/src/declarations.d.ts
This file isn't being used by anything/anyone.
=> chore(node): Remove src/declarations.d.ts

packages/nextjs/rollup.npm.config.js, packages/nextjs/src/config/loaders/wrappingLoader.ts
I accidentally merged an intentional error to ensure the validity of a test causing e2e tests to fail 😬.
(I guess the tests work though, lol)
=> tests(e2e): Undo intentional error

CODEOWNERS
This was previously removed, but we are re-adding for just Replay related items.
Closes https://github.com/getsentry/sentry-javascript/issues/6477
=> meta: Add CODEOWNERS (for replay only)

packages/node/src/handlers.ts
This function shouldn't be async.
=> fix(node): Make `trpcMiddleware` factory synchronous

packages/node/test/async/domain.test.ts, packages/node/test/async/hooks.test.ts
Adds some async tests to the new async context strategies.
=> test(node): Add some async tests to async strategies

packages/core/src/hub.ts
ref https://github.com/getsentry/sentry-javascript/issues/7691
We need this publicly exported so we can document how users can manually instrument hub isolation.
Next up is docs!
=> feat(core): Make `runWithAsyncContext` public API

packages/node/src/handlers.ts
https://twitter.com/coffedevflower/status/1646894562323972097
=> fix(node): Correct typo in trpc integration transaciton name

.github/workflows/gitflow-sync-develop.yml
This was still failing here: https://github.com/getsentry/sentry-javascript/actions/runs/4755882080/jobs/8450653777?pr=7922
I maybe should have read the GH CI docs before 😅 I think now it should really be working, hopefully...
=> ci: Finally fix auto-merge for gitflow

packages/nextjs/src/config/loaders/wrappingLoader.ts
=> fix(nextjs): Import path issue on Windows

packages/tracing/README.md
Title
Resolves https://github.com/getsentry/sentry-javascript/issues/8160
=> meta(tracing): Add deprecation notice to `@sentry/tracing` readme

packages/replay/test/integration/beforeAddRecordingEvent.test.ts
Not sure how this happened and how that didn't fail before, but this is failing on master as of now...
=> test(replay): Fix test

packages/sveltekit/src/server/index.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/8311
=> fix(sveltekit): Export captureCheckIn

packages/e2e-tests/test-applications/nextjs-app-dir/pages/api/edge-endpoint.ts, packages/e2e-tests/test-applications/nextjs-app-dir/pages/api/error-edge-endpoint.ts, packages/e2e-tests/test-applications/nextjs-app-dir/tests/edge-route.test.ts
Ref: https://github.com/getsentry/sentry-javascript/issues/6906
=> test(e2e): Add tests for Next.js edge routes

LICENSE
Discovered under https://github.com/getsentry/rrweb/pull/92.
- Use our [standard🔒](https://www.notion.so/sentry/Open-Source-Legal-Policy-ac4885d265cb4d7898a01c060b061e42) copyright declaration
- Format for 80 char width lines
=> chore: Minor cleanups on LICENSE

packages/tracing/test/hub.test.ts
A validation test for transaction trim end since I noticed this wasn't being tested. Trying to sanity check why trimming is not working for some timestamps.
=> test(tracing): Add test for transaction trimEnd

packages/ember/package.json, yarn.lock
Another part to hopefully fix canary tests.
=> build(ember): Update ember-resolver dev dependency

.craft.yml
This will add the latest develop commit (craft config fix from #8729) to `master` and start the next release attempt
=> Sync develop -> master

packages/browser/src/index.ts, packages/core/src/tracing/index.ts, packages/core/src/tracing/measurement.ts, packages/node/src/index.ts, packages/serverless/src/index.ts, packages/sveltekit/src/server/index.ts
ref https://github.com/getsentry/sentry-javascript/issues/8724
=> feat(core): Add setMeasurement export

.size-limit.js
=> build: Fix typo in size limit config

packages/sveltekit/package.json
Fixes https://github.com/getsentry/sentry-javascript/issues/8262
Fixes https://github.com/getsentry/sentry-javascript/issues/8805
=> deps(sveltekit): Bump `@sentry/vite-plugin`

packages/replay/src/util/prepareReplayEvent.ts
See https://github.com/getsentry/sentry-javascript/pull/9022 for how this otherwise fails. Replay events also go through global event processors, so they should also go through this hook (replay events are not sent via the regular baseclient methods).
@JonasBa not sure if something like this also applies to profiles, but they should also go through this hook before `prepareEvent()` is applied!
=> fix(replay): Ensure replay events go through `preprocessEvent` hook

.craft.yml
ref https://github.com/getsentry/sentry-javascript/issues/8087
need https://github.com/getsentry/sentry-release-registry/pull/120 to merge in first
=> chore: Publish @sentry/vercel-edge to release registry

packages/node-experimental/package.json, packages/node-experimental/src/sdk/initOtel.ts, yarn.lock
This was missing currently, so for correctness adding the resource info here.
=> ref(node-experimental): Add resource information

packages/wasm/src/index.ts
This refactors Wasm integration to use `processEvent`.
=> ref(wasm): Refactor Wasm integration to use `processEvent`

packages/replay/.eslintignore, packages/replay/package.json
Noticed that these are not needed anymore!
=> build(replay): Cleanup unused config

packages/deno/package.json, packages/e2e-tests/verdaccio-config/config.yaml
=> ci: Add configs for deno

README.md
Adds two entries for Bun and Astro to the README in the repo root
=> chore(repo): Add Astro and Bun to main README

.craft.yml, .github/workflows/build.yml, packages/deno/package.json
Prepares Deno SDK for release on npm.
=> build(deno): Prepare Deno SDK for release on npm

packages/feedback/README.md
Fix feedback import in README.
=> fix(feedback): Fixing feedback import

packages/feedback/src/integration.ts
=> ref(feedback): Add treeshaking for logger statements

packages/feedback/README.md
+ tweak some existing descriptions
=> docs(feedback): Add configuration row for `cancelForegroundHover`

packages/deno/package.json, packages/deno/rollup.config.js, packages/deno/test/example.ts, packages/deno/test/mod.test.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/9478
=> fix(deno): Emit .mjs files

packages/replay/src/coreHandlers/handleGlobalEvent.ts, packages/replay/src/coreHandlers/util/addFeedbackBreadcrumb.ts, packages/replay/src/types/replayFrame.ts, packages/replay/src/util/eventUtils.ts
Add feedback breadcrumb to replay when a feedback is sent (and if replays are enabled).
=> feat(replay): Add feedback breadcrumb to replay

packages/browser/package.json, packages/deno/package.json, packages/integrations/package.json, packages/opentelemetry/package.json, packages/replay/package.json, packages/serverless/package.json, packages/tracing/package.json, packages/wasm/package.json
I missed some packages when doing #9269
=> dev: Add missing `--sig` arg to `yalc:publish` task

packages/utils/src/requestdata.ts
fixes https://github.com/getsentry/sentry-javascript/issues/9673
=> fix(utils): Try catch new URL when extracting query params

.craft.yml, .size-limit.js, packages/browser/package.json, packages/browser/rollup.bundle.config.js, packages/browser/src/index.bundle.feedback.ts, packages/browser/src/index.bundle.tracing.replay.feedback.ts, packages/browser/src/index.bundle.tracing.replay.ts, packages/browser/src/index.bundle.ts, packages/browser/src/index.ts, packages/browser/test/unit/index.bundle.feedback.test.ts, packages/browser/test/unit/index.bundle.test.ts, packages/browser/test/unit/index.bundle.tracing.replay.feedback.test.ts, packages/browser/test/unit/index.bundle.tracing.replay.test.ts, packages/browser/test/unit/index.bundle.tracing.test.ts, packages/feedback/package.json, packages/feedback/src/integration.ts, packages/integration-shims/src/Feedback.ts, packages/integration-shims/src/index.ts, packages/tracing-internal/tsconfig.types.json, yarn.lock
Add feedback to craft publish list, and export `Feedback` integration from browser SDK
Depends on
Relates to: https://github.com/getsentry/team-replay/issues/273
=> feat(feedback): Include Feedback package in browser SDK

packages/node/src/sdk.ts
Add Cloudflare pages commit sha
=> feat(node): add cloudflare pages commit sha

codecov.yml
See: https://github.com/codecov/vscode/pull/35/files#diff-084bdbbae104c91c8af1a0b632b46b9e797366d5427a2f11aa0332007866af39R2334-R2359
This is undocumented and in alpha, but I figured we should try testing it out!
=> build: Enable codecov AI PR review

packages/e2e-tests/test-applications/node-hapi-app/event-proxy-server.ts, packages/e2e-tests/test-applications/node-hapi-app/tests/server.test.ts, packages/node/src/integrations/hapi/index.ts
Damn, merged a PR without rebasing it first, it did not have the new biome rules yet 😅 so develop is failing linting right now...
=> build: Fix linting

packages/browser/src/integrations/breadcrumbs.ts, packages/browser/src/integrations/dedupe.ts, packages/browser/src/integrations/globalhandlers.ts, packages/browser/src/integrations/httpcontext.ts, packages/browser/src/integrations/linkederrors.ts, packages/browser/src/integrations/trycatch.ts
Eventually we may think about merging the `LinkedErrors` integration with the core one, but for now this should be OK...
=> ref(browser): Refactor browser integrations to functional style

.vscode/extensions.json, .vscode/settings.json, docs/event-sending.md, docs/gitflow.md, docs/new-sdk-release-checklist.md, docs/publishing-a-release.md, docs/using-yalc.md, package.json, packages/ember/tests/dummy/app/styles/app.css, yarn.lock
Fixes https://github.com/getsentry/sentry-javascript/issues/9934
=> fix: enables prettier for markdown and css

packages/astro/src/integration/index.ts
Hopefully this fixes https://github.com/getsentry/sentry-javascript/issues/9777
=> fix(astro): use correct package name for CF

MIGRATION.md
`yarn fix` caught this error, but somehow this made into the repository.
=> fix: update migration.md due to styling issues

dev-packages/node-integration-tests/suites/express/tracing-experimental/test.ts, packages/core/test/lib/scope.test.ts
Fixes Node.js integration tests
=> test: fix node.js integration tests

packages/core/src/index.ts
=> fix(core): Export `spanToTraceContext` function from span utils

packages/bun/src/index.ts, packages/bun/src/integrations/bunserver.ts, packages/bun/src/integrations/index.ts, packages/bun/src/sdk.ts
And deprecate `new BunServer()`
=> feat(bun): Export `bunServerIntegration()`

CHANGELOG.md
Forward-porting this from the v7 branch.
=> meta(changelog): Update changelog vor v7.101.0

CODEOWNERS
=> chore(codeowners): rename replay team sdk

packages/nextjs/test/config/webpack/sentryWebpackPlugin.test.ts
Forgot to backport this test fix
=> tests: Fix failing Next.js test

packages/core/src/server-runtime-client.ts, packages/deno/src/integrations/globalhandlers.ts, packages/node/test/eventbuilders.test.ts, packages/utils/src/eventbuilder.ts, packages/utils/test/eventbuilder.test.ts
=> feat(v8): Update eventFromUnknownInput to only use client

.github/workflows/build.yml, dev-packages/node-integration-tests/package.json, dev-packages/node-integration-tests/suites/tracing-experimental/nestjs/scenario.ts, dev-packages/node-integration-tests/suites/tracing-experimental/nestjs/test.ts, dev-packages/node-integration-tests/suites/tracing-experimental/nestjs/tsconfig.json, yarn.lock
=> test(node): Add NestJS OpenTelemetry Tests

CHANGELOG.md
=> meta: Update CHANGELOG for 7.102.1 

packages/core/src/tracing/sentrySpan.ts, packages/types/src/span.ts
=> feat(v8/core): Remove deprecated setHttpStatus

packages/core/src/tracing/sentrySpan.ts, packages/core/src/tracing/transaction.ts, packages/types/src/span.ts, packages/types/src/transaction.ts
=> feat(v8/core): Remove deprecated updateWithContext method

dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/http-timings/test.ts, dev-packages/browser-integration-tests/suites/tracing/browsertracing/tracePropagationTargets/customTargetsAndOrigins/init.js, dev-packages/browser-integration-tests/suites/tracing/browsertracing/tracePropagationTargets/customTracingOrigins/init.js, packages/types/src/client.ts
- test we forgot to delete fully
- comments that don't apply anymore
=> chore(v8): Clean up some dead code

packages/profiling-node/package.json, yarn.lock
Fixes https://github.com/getsentry/sentry-javascript/issues/10852
Guess this kind of went out of sync during merging stuff etc 😬
=> fix(profiling-node): [v7] Fix dependencies to point to current versions

MIGRATION.md
=> docs: Fix typo in migration docs

packages/node-experimental/src/proxy/index.ts
There is already a PR to backport this to v7 #11009
=> fix(node): Do not assert in vendored proxy code

MIGRATION.md, dev-packages/e2e-tests/test-applications/angular-17/src/app/component-tracking/component-tracking.components.ts, dev-packages/e2e-tests/test-applications/angular-17/tests/performance.test.ts, packages/angular-ivy/README.md, packages/angular/README.md, packages/angular/src/index.ts, packages/angular/src/tracing.ts
closes https://github.com/getsentry/sentry-javascript/issues/11038
=> feat(angular/v8): Change decorator naming and add `name` parameter

.github/workflows/build.yml, scripts/aws-deploy-local-layer.sh
=> fix(ci): Fix path to aws serverless layer zip

packages/angular/.gitignore
This folder will have changes after generating the package tarballs.
=> build: Gitignore angular output folder

.github/workflows/build.yml, dev-packages/e2e-tests/test-applications/webpack-5/.npmrc, dev-packages/e2e-tests/test-applications/webpack-5/build.mjs, dev-packages/e2e-tests/test-applications/webpack-5/entry.js, dev-packages/e2e-tests/test-applications/webpack-5/package.json, dev-packages/e2e-tests/test-applications/webpack-5/playwright.config.ts, dev-packages/e2e-tests/test-applications/webpack-5/tests/behaviour-test.spec.ts
Tests that an app built with webpack 5 and minified with terser can be built and sends events at runtime
=> test(browser): Test webpack 5 + Terser

MIGRATION.md, packages/ember/addon/types.ts
=> feat(v8/ember): Remove deprecated StartTransactionFunction

dev-packages/e2e-tests/test-applications/sveltekit-2/test/errors.client.test.ts, dev-packages/e2e-tests/test-applications/sveltekit/test/errors.client.test.ts
We're getting a lot of flakes: https://github.com/getsentry/sentry-javascript/actions/runs/8448921832/job/23142093964?pr=11299#step:12:79
=> test(e2e): Attempt to unflake sveltekit e2e tests

packages/tracing-internal/src/browser/metrics/index.ts
Backport of https://github.com/getsentry/sentry-javascript/pull/11311
=> fix(web-vitals): [v7]  Check for undefined navigation entry

dev-packages/node-integration-tests/suites/sessions/crashed-session-aggregate/test.ts, dev-packages/node-integration-tests/suites/sessions/errored-session-aggregate/test.ts, dev-packages/node-integration-tests/suites/sessions/exited-session-aggregate/test.ts, dev-packages/node-integration-tests/utils/runner.ts
Ports these tests to the new test runner - everything still seems to be working as expected 🎉
=> test(node): Fix node session aggregate tests

packages/remix/test/integration/package.json
Tests are failing because mime 4 is Node 16+ only, so pinning this to mime 3...
=> test(remix): Fix test for Node 14

packages/opentelemetry/src/trace.ts
=> feat(opentelemetry): Remove top level startActiveSpan

packages/core/src/scope.ts
Found when examining minified bundle for v8 (to see if treeshaking working properly everywhere).
=> ref(core): Remove duplicate logic in scope.update

packages/types/src/index.ts, packages/types/src/view-hierarchy.ts
https://github.com/getsentry/rfcs/blob/main/text/0033-view-hierarchy.md
=> feat(types): Add View Hierarchy types

packages/feedback/src/modal/components/Dialog.css.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/10202
=> ref(feedback): Add font family to buttons

dev-packages/node-integration-tests/suites/anr/basic-session.js, dev-packages/node-integration-tests/suites/anr/basic.js, dev-packages/node-integration-tests/suites/anr/basic.mjs, dev-packages/node-integration-tests/suites/anr/isolated.mjs, dev-packages/node-integration-tests/suites/anr/test.ts
All of the ANR tests were verified over stdout. This PR ensures some of the basic tests actually send events over http to ensure the transport is fully tested.
=> fix(test): Some ANR tests should test the transport

packages/core/src/integrations/inboundfilters.ts
=> fix(core): Don't log error from Inbound Filters integration

packages/feedback/src/widget/Actor.css.ts, packages/feedback/src/widget/Dialog.css.ts
Backports #11437, #11432, #11414 to v7
=> ref(feedback): [v7] Configure feedback fonts

CHANGELOG.md
ref https://github.com/getsentry/sentry-javascript/issues/11402
=> meta: CHANGELOG for 7.110.0

dev-packages/e2e-tests/test-applications/sveltekit-2/test/errors.client.test.ts, dev-packages/e2e-tests/test-applications/sveltekit/test/errors.client.test.ts
Backporting the unflaking we did on develop
=> test(e2e): Unflake sveltekit e2e tests

packages/nextjs/package.json, yarn.lock
This is not supported since next 12, so we are good to remove this too: https://nextjs.org/docs/messages/webpack5
=> feat(nextjs): Remove webpack 4 support

.github/workflows/build.yml
=> ci: Run CI on merge_group checks requested

nx.json
Just fixes this in v7 to, as it makes development a bit easier.
=> build: Backport nx cache config fixes

CHANGELOG.md
Getting this ember fix out, as it's kind of bad.
=> meta(changelog): Update changelog for 7.112.1

packages/replay-canvas/package.json, packages/replay-internal/package.json, yarn.lock
Pulls in a bunch of commits from rrweb upstream to address some outstanding perf issues
=> feat(replay): Upgrade rrweb packages to 2.15.0

CHANGELOG.md
=> meta(changelog): Update changelog for v7.112.2

packages/node/package.json, yarn.lock
Upgrade prisma instrumentation to take advantage of https://github.com/prisma/prisma/issues/23410#issuecomment-2075762456
=> feat(node): Upgrade @prisma/instrumentation to 5.13.0

packages/astro/src/server/middleware.ts
Ref: https://github.com/getsentry/sentry-javascript/issues/10846
Sets a transaction name on the isolation scope for astro requests.
=> feat(astro): Add `transactionName` to isolation scope for requests

packages/feedback/package.json
This simplifies stuff for our users as well.
=> fix(feedback): Vendor preact into bundle

dev-packages/browser-integration-tests/suites/integrations/captureConsole/init.js, dev-packages/browser-integration-tests/suites/integrations/captureConsole/subject.js, dev-packages/browser-integration-tests/suites/integrations/captureConsole/test.ts
Adding tests for https://github.com/getsentry/sentry-javascript/issues/11829 on v7.
=> test(browser/v7): Add test for captureConsole

packages/node/src/integrations/tracing/nest.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/11877
=> fix(nestjs): Ensure Nest.js interceptor works with non-http context

MIGRATION.md, packages/aws-serverless/src/index.ts, packages/browser/src/exports.ts, packages/bun/src/index.ts, packages/core/src/index.ts, packages/core/src/utils/spanUtils.ts, packages/deno/src/index.ts, packages/google-cloud-serverless/src/index.ts, packages/node/src/index.ts, packages/remix/src/index.server.ts, packages/sveltekit/src/server/index.ts, packages/vercel-edge/src/index.ts
So we have a proper usage path without installing utils & core...
=> feat: Export `spanToBaggageHeader` utility

dev-packages/browser-integration-tests/utils/helpers.ts, packages/nextjs/package.json, packages/node/package.json, yarn.lock
Merging develop into master to unblock the release.
=> meta: Merge develop into master

packages/astro/package.json, packages/aws-serverless/package.json, packages/google-cloud-serverless/package.json, packages/node/package.json, packages/remix/package.json
=> fix(node): Include loader hook files in package.json

packages/node/src/integrations/tracing/express.ts
This prints a warning if we detect that the express `app` passed to `setupExpressErrorHandler` is not instrumented.
This happens if you import express _before_ calling Sentry.init:
=> feat(express): Warn if express is not instrumented

packages/node/src/integrations/tracing/connect.ts
=> feat(connect): Warn if connect is not instrumented

packages/feedback/src/modal/integration.tsx
The user can be set on any scope, we should pick it correctly from wherever it is set.
=> fix(feedback): Pick user from any scope

packages/node/src/integrations/tracing/nest.ts
=> fix(nestjs): Broaden nest.js type

packages/node/src/sdk/init.ts
To make debugging etc. easier for us in the future.
=> ref(node): Add log for running in ESM/CommonJS mode

packages/nextjs/src/config/webpack.ts
Resolves https://github.com/getsentry/sentry-javascript/issues/12077
=> feat(nextjs): Ignore Prisma critical dependency warnings

packages/browser/rollup.bundle.config.mjs, packages/browser/src/integrations/browserprofiling.ts, packages/browser/src/utils/lazyLoadIntegration.ts
Closes https://github.com/getsentry/sentry-javascript/issues/12156
=> feat(browser): Ensure `browserProfilingIntegration` is published to CDN

dev-packages/overhead-metrics/package.json, packages/browser/package.json, yarn.lock
Remove some unneeded deps, and align playwright version everywhere.
=> build: Cleanup dependencies

CHANGELOG.md
Forgot to shoutout @dohooo, @mohd-akram and @ykzts for their help fixing bugs with the SDK this release - will also update the main release notes!
=> docs: Add external contributors to 8.8.0 changelog note

CONTRIBUTING.md
This updates contributing docs to mention that we use volta, + also to set up PNPM support.
=> docs: Update contributing docs to mention volta

.craft.yml
Waiting with merging this until the package is ready.
=> feat(solidjs): Add entry for Solid SDK to .craft.yml

dev-packages/node-integration-tests/suites/tracing/spans/test.ts
Updates the expected status message for 404 span reflecting the updates in #12477
=> fix(tests): Update the expected status on 404.

packages/feedback/src/modal/integration.tsx
Fixes https://github.com/getsentry/sentry-javascript/issues/12496
=> fix(feedback): Fix scrolling after feedback submission

packages/replay-internal/src/coreHandlers/handleBeforeSendEvent.ts, packages/replay-internal/src/types/replayFrame.ts, packages/replay-internal/test/integration/coreHandlers/handleBeforeSendEvent.test.ts
Fixes https://github.com/getsentry/sentry/issues/72152
=> feat(replay): Add url to replay hydration error breadcrumb type

docs/commit-issue-pr-guidelines.md
Noticed that this was missing in the docs!
=> docs: Small tweak to pr docs

packages/core/src/exports.ts
=> docs: Fix JSDoc on captureMessage and captureEvent

README.md
ref https://github.com/getsentry/team-sdks/issues/87
=> chore: Add contributor list to JS SDK repo

packages/astro/package.json, packages/astro/src/integration/index.ts, packages/astro/test/integration/index.test.ts, packages/nextjs/package.json, packages/nextjs/src/config/webpackPluginOptions.ts, packages/nuxt/package.json, packages/sveltekit/package.json, packages/sveltekit/src/vite/sourceMaps.ts, yarn.lock
- Bumps plugins
- Adds meta framework information telemetry
=> deps: Bump bundler plugins to `2.20.1`

docs/triaging.md
Updates the triaging docs based on talks I've had with folks.
=> docs: Update triaging docs

.github/ISSUE_TEMPLATE/bug.yml
ref https://github.com/getsentry/sentry-javascript/pull/12671
=> feat(bug-template): Add `@sentry/nest`

CHANGELOG.md
Based on feedback from https://github.com/getsentry/sentry-javascript/issues/12734
=> docs: Add note to changelog linking migration guide

.github/workflows/build.yml, .github/workflows/canary.yml
Just to align stuff properly everywhere!
=> build: Ensure we use pnpm 9.4.0 everywhere on CI

packages/nuxt/README.md
addition to https://github.com/getsentry/sentry-javascript/pull/12850
=> docs(nuxt): Fix instrument filename in readme

packages/nextjs/tsconfig.test.json
Maybe fixes https://github.com/getsentry/sentry-javascript/issues/12880?
=> ci(nextjs): Fix flakey types?

.craft.yml
Get `@sentry/cloudflare` ready for release.
=> chore: Add @sentry/cloudflare to craft config

dev-packages/e2e-tests/README.md
=> chore: Fix path in e2e test readme

packages/cloudflare/src/pages-plugin.ts
Leftover from auto-generated JSDoc, can be removed
=> ref(cloudflare): Clean up pages plugin docs comment

README.md
=> chore(readme): Add new sentry banner to readme

.craft.yml
following up on https://github.com/getsentry/sentry-release-registry/pull/164
=> chore(cloudflare): Add cloudflare sdk to the release registry

dev-packages/e2e-tests/test-applications/nestjs-basic/tests/cron-decorator.test.ts, dev-packages/e2e-tests/test-applications/node-nestjs-basic/tests/cron-decorator.test.ts
Sometimes ok check-ins arrive before in-progress check-ins and then the test fails. Now filtering directly for in_progress envelopes and separately awaiting and checking ok envelopes.
=> tests(e2e): Unflake nest cron tests

.craft.yml, .github/workflows/build.yml
Closes: https://github.com/getsentry/sentry-javascript/issues/12550
=> chore(solidstart): Add .craft.yml entry for Solid Start SDK

.craft.yml
Waiting on: https://github.com/getsentry/sentry-release-registry/pull/166
Closes: https://github.com/getsentry/sentry-javascript/issues/12555
=> chore(solidstart): Add solidstart sdk to the registry in .craft.yml

packages/nextjs/src/config/index.ts, packages/nextjs/src/index.types.ts
Refs: #13295
I run the linting, it said that there are 16 errors but none are in the file I changed.
=> feat(nextjs): export SentryBuildOptions

.github/actions/install-playwright/action.yml
Should reduce amount of cached data.
=> ci: Only store playwright cache on develop

packages/node/src/timetravel-worker.ts
=> feat: Collect arrays and objects

packages/cloudflare/README.md
Fixes spacing in readme snippet
=> docs(cloudflare): Fix spacing in README snippet

dev-packages/browser-integration-tests/package.json
=> ci: Don't fork bomb on yarn install

dev-packages/e2e-tests/test-applications/create-remix-app-express-legacy/tests/server-transactions.test.ts, dev-packages/e2e-tests/test-applications/create-remix-app-express/tests/server-transactions.test.ts
This flaked e.g. here: https://github.com/getsentry/sentry-javascript/actions/runs/10629179350/job/29465889113
=> test: Unflake remix E2E test

packages/types/src/scope.ts
=> docs: Fix jsdocs param names

packages/nestjs/README.md
=> chore(nestjs): Add note about `SentryGlobalGraphQLFilter` in nestjs README

.github/workflows/build.yml, packages/nestjs/src/decorators/with-sentry.ts
Also adds the `nestjs-with-submodules-decorator` e2e test app to be run on CI.
=> fix(nestjs): Ensure exception and host are correctly passed on when using @WithSentry

packages/feedback/src/core/components/FeedbackIcon.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/13513
=> fix(feedback): Actor color applies to feedback icon

dev-packages/node-integration-tests/suites/tracing/amqplib/test.ts
Fixes test which has been flaking due to timeouts.
=> ref(test): Increase amqplib integration test timeout

packages/replay-canvas/package.json, packages/replay-internal/package.json, yarn.lock
Pulls in upstream rrweb commits, see https://github.com/getsentry/rrweb/pull/220
=> feat(replay): Upgrade rrweb packages to 2.28.0

dev-packages/rollup-utils/plugins/make-esm-plugin.mjs
Module federation needs package version for comparison
fixes https://github.com/getsentry/sentry-javascript/discussions/12433
=> fix(module): keep version for node ESM package

dev-packages/e2e-tests/test-applications/nestjs-basic-with-graphql/package.json
See #13744 for more information
=> dev(e2e): Fix nestjs version constraint

packages/nextjs/src/common/wrapApiHandlerWithSentry.ts
Await flushing the SDK in the case of an error, otherwise the runtime freezes as soon as the error is re-thrown and it will never be captured.
fixes https://github.com/getsentry/sentry-javascript/issues/13977
=> fix(nextjs): Await flush in api handlers

dev-packages/e2e-tests/test-applications/debug-id-sourcemaps/package.json, packages/astro/package.json, packages/gatsby/package.json, packages/nextjs/package.json, packages/nuxt/package.json, packages/remix/package.json, packages/solidstart/package.json, packages/sveltekit/package.json, yarn.lock
=> deps: Bump bundler plugins and CLI to 2.22.6 and 2.37.0 respectively

.github/dependabot.yml
Just streamlining this a bit and adding the remix instrumentation.
=> ci: Update dependabot config

.vscode/settings.json
Removes VS Code workspace settings that imo are more preference than adding anything useful.
=> meta: Remove slightly invasive VS Code workspace settings

CHANGELOG.md
Add @grahamhency to changelog for work in https://github.com/getsentry/sentry-javascript/pull/14205
=> chore: Add external contributor to changelog

dev-packages/browser-integration-tests/package.json, packages/replay-canvas/package.json, packages/replay-internal/package.json, yarn.lock
Change to stop restarting canvas manager web worker when stopping recording.
=> feat(replay): Upgrade rrweb packages to 2.29.0

dev-packages/rollup-utils/plugins/bundlePlugins.mjs
Fixes https://github.com/getsentry/sentry-javascript/issues/14343
=> fix(cdn): Ensure `_sentryModuleMetadata` is not mangled

dev-packages/browser-integration-tests/suites/feedback/attachTo/test.ts, dev-packages/browser-integration-tests/suites/feedback/captureFeedback/test.ts, dev-packages/browser-integration-tests/suites/feedback/captureFeedbackAndReplay/hasSampling/test.ts, dev-packages/browser-integration-tests/suites/feedback/captureFeedbackCsp/test.ts, dev-packages/browser-integration-tests/suites/integrations/lazyLoad/feedbackIntegration/test.ts, dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/navigation/test.ts, dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/pageload-meta/test.ts, dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/pageload/test.ts
We already merged everything for the 8.40.0 release to master but CI is currently failing on master and release branches. #14410 fixes the failing CI runs and was merged to develop. So this PR merges develop into master so that we can restart the 8.40.0 release afterwards.
=> chore: Sync develop -> master

CHANGELOG.md
Change based on this comment: https://github.com/getsentry/sentry-javascript/pull/14502/files#r1860611132
=> meta(changelog): Update versions in changelog

packages/sveltekit/src/vite/sourceMaps.ts
Fixes https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/634
=> fix(sveltekit): Fix git SHA not being picked up for release

CHANGELOG.md
Small bugfix backport release!
=> meta(v7/changelog): Add changelog for 7.120.1

.craft.yml
=> feat(aws): Add v8 lambda layer craft target

.github/workflows/canary.yml
Forgot to update this for canary tests, oops...
=> ci: Fix playwright install on canary tests

packages/nuxt/build.config.ts, packages/nuxt/tsconfig.json
fixes https://github.com/getsentry/sentry-javascript/issues/14661
=> fix(nuxt): Add unbuild config to not fail on warn

CHANGELOG.md
=> meta(v7/changelog): Add changelog for 1.120.2

packages/nuxt/tsconfig.types.json
backport https://github.com/getsentry/sentry-javascript/pull/14735
fixes https://github.com/getsentry/sentry-javascript/issues/14732
=> fix(nuxt): Remove build config from tsconfig

dev-packages/node-integration-tests/package.json, dev-packages/node-integration-tests/suites/tracing/prisma-orm/package.json, dev-packages/node-integration-tests/suites/tracing/prisma-orm/test.ts, dev-packages/node-integration-tests/suites/tracing/prisma-orm/yarn.lock, packages/node/src/integrations/tracing/prisma.ts
Backport of https://github.com/getsentry/sentry-javascript/pull/14771
=> feat(v8/node): Do not overwrite prisma `db.system` in newer Prisma versions

CHANGELOG.md
One more release before holidays to get out some v8-backported changes
=> meta: Update changelog for 8.47.0

dev-packages/node-integration-tests/suites/express/requestUser/server.js, dev-packages/node-integration-tests/suites/express/requestUser/test.ts, packages/core/src/utils-hoist/requestdata.ts, packages/node/src/integrations/tracing/express.ts
Backport of https://github.com/getsentry/sentry-javascript/pull/14850
Fixes https://github.com/getsentry/sentry-javascript/issues/14847
=> fix(v8/node): Ensure express requests are properly handled

dev-packages/node-integration-tests/suites/express/tracing/tracesSampler/scenario-normalizedRequest.js, dev-packages/node-integration-tests/suites/express/tracing/tracesSampler/server.js, dev-packages/node-integration-tests/suites/express/tracing/tracesSampler/test.ts, packages/core/src/tracing/sampling.ts, packages/core/src/types-hoist/samplingcontext.ts
Backport of https://github.com/getsentry/sentry-javascript/pull/14902
=> feat(v8/core): Add `normalizedRequest` to `samplingContext`

docs/migration/v8-to-v9.md
Some changes made based on trying to use the migration doc.
=> chore: Adjust grammer and formatting of migration doc

dev-packages/e2e-tests/test-applications/node-express-app/package.json
Backport of https://github.com/getsentry/sentry-javascript/pull/15001
=> test(v7/e2e): Fix node-express test transitive dependency

dev-packages/browser-integration-tests/suites/tracing/request/fetch/test.ts, dev-packages/browser-integration-tests/suites/tracing/request/init.js
Seems to be failing on CI, can't reproduce it locally but this makes more sense I guess...
=> test(browser): Unflake browser request test

packages/aws-serverless/package.json, yarn.lock
`@opentelemetry/instrumentation-aws-lambda`: Upgrades internal deps and bug fix around semantic conventions
`@opentelemetry/instrumentation-aws-sdk` and `@opentelemetry/instrumentation`: Update internal deps
=> feat(aws-serverless): Upgrade OTEL deps

dev-packages/e2e-tests/test-applications/nestjs-fastify/src/app.controller.ts, dev-packages/e2e-tests/test-applications/nestjs-fastify/tests/transactions.test.ts, packages/nestjs/src/setup.ts, packages/node/src/integrations/tracing/fastify.ts, packages/node/src/integrations/tracing/nest/nest.ts, packages/node/src/integrations/tracing/nest/types.ts
Backports https://github.com/getsentry/sentry-javascript/pull/15066
=> fix(v8/node/nestjs): Use method on current fastify request

dev-packages/e2e-tests/test-applications/react-send-to-sentry/tests/send-to-sentry.test.ts
=> test(v8/e2e): Unflake replay recording data optional e2e test (#15168)

CHANGELOG.md
Cutting a patch to address #15209
=> meta: Update changelog for 8.52.1

packages/react/src/vendor/tanstackrouter-types.ts
We adapted this here but did not adapt the types:
https://github.com/getsentry/sentry-javascript/pull/15235
=> ref(react): Adapt tanstack router type

.github/workflows/flaky-test-detector.yml, dev-packages/browser-integration-tests/scripts/detectFlakyTests.ts
This streamlines this a bit and should be good enough here.
=> test: Only run flaky test detection for chromium

packages/nuxt/src/runtime/plugins/sentry.server.ts
Backport of https://github.com/getsentry/sentry-javascript/pull/15288
=> fix(v8/nuxt): Detect Azure Function runtime for flushing with timeout

.craft.yml
=> ci: Re-enable AWS lambda layer publishing

packages/sveltekit/README.md
=> docs: Fix typo in readme

packages/core/src/integrations/inboundfilters.ts, packages/core/test/lib/integrations/inboundfilters.test.ts
backport of https://github.com/getsentry/sentry-javascript/pull/15432 and https://github.com/getsentry/sentry-javascript/pull/15430
=> fix(v8/core): Filter `gmo` error and Facebook mobile error

packages/remix/README.md
Update remix readme to use the proper integrations reference for Prisma.
=> chore(docs): Update Remix docs to use recent integrations

packages/bun/jest.config.js, packages/bun/tsconfig.test.json
Jest is not being used, we can remove all jest related code from this package
=> chore(bun): Remove all references to jest

README.md
Add a more general version support policy that does not need to be updated on every major release.
=> docs(readme): Update version support policy

packages/remix/src/server/errors.ts
Although I can't reproduce, this should resolve https://github.com/getsentry/sentry-javascript/issues/15612
=> fix(remix): Null-check `options`

CHANGELOG.md
=> meta(changelog): Update changelog for 9.7.0-alpha.0

docs/migration/feedback.md
The actual code is https://github.com/getsentry/sentry-javascript/blob/develop/packages/feedback/src/constants/index.ts#L23-L24
=> fix: Correct @sentry-internal/feedback docs to match the code

.craft.yml
Should wait on https://github.com/getsentry/sentry-release-registry/pull/187 before merging.
=> feat(nestjs): Add nestjs release registry craft entry

.craft.yml
Corresponding entry in sentry-release-registry: https://github.com/getsentry/sentry-release-registry/tree/master/packages/npm/%40sentry/tanstackstart-react
=> feat(tanstackstart-react): Add tanstackstart-react to release registry craft entry

.github/workflows/issue-package-label.yml
OK I looked for the error in the wrong place, it was in the JSON 🤦 I verified that it works now...
=> ci: Finally fix it for real real

packages/vercel-edge/src/index.ts
fixes https://github.com/getsentry/sentry-javascript/issues/16229
ref: https://github.com/getsentry/sentry-javascript/discussions/15916#discussioncomment-13067000
=> feat: Export `consoleLoggingIntegration` from vercel edge sdk

dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/server-components.test.ts, packages/nextjs/src/common/wrapGenerationFunctionWithSentry.ts, packages/nextjs/src/common/wrapServerComponentWithSentry.ts
Necessary for Next.js insights page
=> feat(nextjs): Add more attributes for generation functions

dev-packages/node-integration-tests/suites/tracing/requests/http-no-tracing-no-spans/test.ts
=> test(node): Fix integration test issue due to missing rebase

packages/profiling-node/README.md
=> chore: Add node 24 to profiling node README

packages/react-router/package.json, yarn.lock
ref https://github.com/getsentry/sentry-javascript/security/dependabot/587
ref [linear](https://linear.app/getsentry/issue/FE-493/improper-authentication-in-getsentrysentry-javascript)
=> deps(react-router): Bump react-router version

packages/cloudflare/src/request.ts
resolves https://github.com/getsentry/sentry-javascript/issues/16766
=> feat(cloudflare): Add user agent to cloudflare spans

dev-packages/rollup-utils/npmHelpers.mjs, packages/pino-transport/src/index.ts
resolves https://github.com/getsentry/sentry-javascript/issues/16942
=> ref(pino-transport): Use `debug` instead of `logger`

packages/bun/README.md
https://github.com/oven-sh/bun/issues/5091 has been completed for some time
=> docs(bun): remove advice concerning unhandled exceptions

dev-packages/e2e-tests/test-applications/aws-lambda-layer-cjs/tests/basic.test.ts, dev-packages/e2e-tests/test-applications/aws-lambda-layer-esm/tests/basic.test.ts, dev-packages/e2e-tests/test-applications/aws-serverless-esm/tests/basic.test.ts, packages/aws-serverless/scripts/buildLambdaLayer.ts, packages/aws-serverless/src/sdk.ts, packages/core/src/utils/env.ts
=> feat(aws): Detect SDK source for AWS Lambda layer

CHANGELOG.md
=> meta(changelog): Update changelog for 9.42.0

dev-packages/e2e-tests/test-applications/nextjs-15/.gitignore, dev-packages/e2e-tests/test-applications/nextjs-15/app/page.tsx, dev-packages/e2e-tests/test-applications/nextjs-15/package.json, dev-packages/e2e-tests/test-applications/nextjs-15/playwright.config.mjs, dev-packages/e2e-tests/test-applications/nextjs-15/tests/async-params.test.ts, packages/nextjs/src/common/utils/wrapperUtils.ts, packages/nextjs/src/common/wrapGenerationFunctionWithSentry.ts, packages/nextjs/src/common/wrapServerComponentWithSentry.ts
backports https://github.com/getsentry/sentry-javascript/pull/17162 to v9
=> fix(v9/nextjs): Handle async params in url extraction

packages/cloudflare/src/durableobject.ts, packages/cloudflare/test/durableobject.test.ts
Backport of https://github.com/getsentry/sentry-javascript/pull/17184
=> fix(v9/cloudflare): Avoid turning DurableObject sync methods into async

dev-packages/e2e-tests/test-applications/nuxt-3/server/plugins/customNitroErrorHandler.ts, packages/astro/src/server/middleware.ts, packages/core/src/index.ts, packages/core/src/utils/flushIfServerless.ts, packages/core/test/lib/utils/flushIfServerless.test.ts, packages/nextjs/src/common/withServerActionInstrumentation.ts, packages/nextjs/src/common/wrapMiddlewareWithSentry.ts, packages/nextjs/src/common/wrapServerComponentWithSentry.ts, packages/nuxt/src/runtime/hooks/captureErrorHook.ts, packages/nuxt/src/runtime/plugins/sentry.server.ts, packages/nuxt/src/runtime/utils.ts, packages/nuxt/src/server/sdk.ts, packages/solidstart/src/server/utils.ts, packages/solidstart/src/server/withServerActionInstrumentation.ts, packages/solidstart/test/server/withServerActionInstrumentation.test.ts, packages/sveltekit/src/server-common/handle.ts, packages/sveltekit/src/server-common/handleError.ts, packages/sveltekit/src/server-common/load.ts, packages/sveltekit/src/server-common/serverRoute.ts, packages/sveltekit/src/server-common/utils.ts
backports https://github.com/getsentry/sentry-javascript/pull/17177
=> feat(v9/core): Add shared `flushIfServerless` function (#17177)

dev-packages/e2e-tests/test-applications/nextjs-t3/package.json, dev-packages/e2e-tests/test-applications/nextjs-t3/src/app/layout.tsx, dev-packages/e2e-tests/test-applications/nextjs-t3/tailwind.config.ts
This should fix the `enforce-license-compliance` CI check
=> chore(test): Remove `geist` font

packages/react-router/package.json, packages/remix/package.json, yarn.lock
Accidentally merged this into master instead of develop which would end up with an unreleased PR on master.
=> Revert: [Gitflow] Merge master into develop

README.md
=> chore: Add link to build and test icon in readme
