tsconfig.json
When the tsconfig option`skipLibCheck` is false (as it is by default), TS typechecks not only your code, and not only the code you use from dependencies, but the entire codebase of all of your dependencies. Not only does this seem like overkill, in our case it's actually largely redundant, because our packages have very few dependencies other than each other. Turning this off speeds up the build and prevents us from, for example, typechecking the entire `utils` package 15 times (once for its own sake, and once for every one of the 14 packages which depend on it).
=> fix(build): Prevent redundant typechecking

packages/react/test/reactrouterv3.test.tsx, packages/react/test/reactrouterv4.test.tsx, packages/react/test/reactrouterv5.test.tsx
When running tests, React will throw a warning unless you [surround state changes with `act(() => <state change>)`](https://reactjs.org/docs/test-utils.html#act). This does that everywhere necessary to get rid of the warning.
=> chore(tests): Fix react `act` warning in tests

packages/utils/src/baggage.ts, packages/utils/test/baggage.test.ts
This patch introduced a basic data structure for baggage, as well as controls to create, manipulate and serialize the baggage data structure.
The baggage data structure represents key,value pairs based on the baggage spec: https://www.w3.org/TR/baggage
It is expected that users interact with baggage using the helpers methods: `createBaggage`, `getBaggageValue`, and `setBaggageValue`.
Internally, the baggage data structure is a tuple of length 2, separating baggage values based on if they are related to Sentry or not. If the baggage values are set/used by sentry, they will be stored in an object to be easily accessed. If they are not, they are kept as a string to be only accessed when serialized at baggage propagation time.
As a next step, let's add the baggage values to the envelope …
=> feat(utils): Introduce Baggage API

.github/workflows/build.yml
This moves, without making any changes, the aws lambda build job to live with the other build job in our CI workflow. (I'll admit that it's not totally obvious, but there is in fact a vague organizing principle to that doc.) Extracted from another PR to make it easier to see, in that PR, what actual changes are being made.
=> chore(build): Move aws lambda build step

package.json, packages/browser/package.json, packages/hub/src/session.ts, packages/integrations/package.json, packages/tracing/package.json, packages/types/src/index.ts, packages/vue/package.json, packages/wasm/package.json, scripts/ensure-bundle-deps.ts
In https://github.com/getsentry/sentry-javascript/pull/5094, a change was made to parallelize our repo-level build commands as much as possible. In that PR, it was stated that `build:bundle` could run independent of, and therefore in parallel with, the types and rollup builds, and at the time that was true. When TS (through rollup) builds a bundle, it creates a giant AST out of the bundled package and all of its monorepo dependencies, based on the original source code, then transpiles the whole thing - no prework needed.
But in https://github.com/getsentry/sentry-javascript/pull/5111 we switched our ES6 bundles to use sucrase for transpilation (still through rollup), and that changed things. Sucrase (along with every other non-TS transpilation tool) only considers files one by one, not as …
=> fix(build): Ensure bundle builds have needed dependencies

MIGRATION.md
This mini PR just adds a point to the TL;DR section stating that other Sentry packages like `@sentry/tracing` should be upgraded alongside the used Sentry SDK. Got the idea to add this after I saw that people were just upgrading the SDK to v7 beta but left tracing at v6.
=> docs(migration): Add upgrading information for multiple Sentry packages to TL;DR section

.github/workflows/build.yml, packages/nextjs/test/run-integration-tests.sh, packages/node/test/manual/webpack-domain/npm-build.js, packages/serverless/src/awslambda.ts, packages/utils/src/dsn.ts, packages/utils/src/normalize.ts
https://nodejs.org/en/blog/announcements/v18-release-announce/
From reviewing the CHANGELOG (https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V18.md), there seems to be no changes that will affect us in the code.
See v17 CHANGELOG: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V17.md
Notable things we can maybe pursue:
- Make a Node 18 only fetch transport: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V18.md#fetch-experimental
Resolves https://getsentry.atlassian.net/browse/WEB-870
=> feat(ci): Add Node 18 to test matrix

packages/browser/rollup.bundle.config.js, packages/integrations/rollup.bundle.config.js, packages/tracing/rollup.bundle.config.js, packages/vue/rollup.bundle.config.js, packages/wasm/rollup.bundle.config.js, rollup/bundleHelpers.js, rollup/plugins/bundlePlugins.js, rollup/utils.js
Currently, we have the ability to create rollup configs for two types of bundles, both intended for use in the browser: standalone SDKs (like browser or vue) and SDK add-ons (like integrations). This adds a third option, namely bundles for Node. Though it's clearly a less-common use case, there are Node situations (like serverless functions) where having a single, fully-treeshaken file could be helpful. (Indeed, the reason for this addition is our AWS lambda layer, and a desire for a simpler and more robust way to make sure that it includes all of the necessary dependencies without a lot of unnecessary extras.)
Adding this option required a small amount of refactoring - exchanging a boolean indicator of bundle type for a string option, and switching to a (n admittedly slightly hacky) …
=> feat(build): Add rollup config for Node bundles

packages/browser/rollup.bundle.config.js, packages/integrations/rollup.bundle.config.js, packages/tracing/rollup.bundle.config.js, packages/vue/rollup.bundle.config.js, packages/wasm/rollup.bundle.config.js, rollup/bundleHelpers.js
This adds the ability to create more than one bundle with a single bundle rollup config, by specifying multiple entrypoints. Because multiple files can now be output, the way they're named also needed to be switched, from providing a static string to providing a function to determine the name of each bundle. Finally, the name of the option (`input`) was changed to match the corresponding option used in the building of npm packages (`entryponts`).
=> feat(build): Allow for multiple bundle entrypoints

packages/nextjs/rollup.npm.config.js, rollup/bundleHelpers.js, rollup/npmHelpers.js
Currently, the functions which we use to generate rollup configs accept a small handful of pre-defined options for customizing the output. For greater flexibility, this adds the option of passing arbitrary rollup options, which will get merged into what is currently being generated.
=> feat(build): Add ability to combine package-specific rollup config with standard options

rollup/bundleHelpers.js
There are situations in which we really only need one version of a bundle rather than all versions, but right now there's no way to build one without building all of them. This adds the option to specify which bundles you need, defaulting to the current behavior of building all three types (regular, minified, and minified with logging) if particular ones aren't requested.
=> feat(build): Add option to build only specified bundle variants

.github/workflows/build.yml, packages/core/src/envelope.ts, packages/core/test/lib/envelope.test.ts, packages/integration-tests/suites/tracing/baggage/test.ts, packages/types/src/baggage.ts, packages/types/src/envelope.ts, packages/types/src/index.ts, packages/types/src/user.ts, packages/utils/src/baggage.ts
Matches how this information will be captured and processed in Relay.
See https://github.com/getsentry/sentry-javascript/pull/5104 for init work.
Resolves https://getsentry.atlassian.net/browse/WEB-926
=> ref: Rename baggage env header to trace

MIGRATION.md, packages/core/test/lib/envelope.test.ts, packages/integration-tests/suites/tracing/browsertracing/meta/template.html, packages/integration-tests/suites/tracing/browsertracing/meta/test.ts, packages/nextjs/src/utils/instrumentServer.ts, packages/nextjs/src/utils/withSentry.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-header-assign/test.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-header-out/test.ts, packages/node-integration-tests/suites/express/sentry-trace/server.ts, packages/node/src/handlers.ts, packages/node/src/integrations/http.ts, packages/node/test/handlers.test.ts, packages/node/test/integrations/http.test.ts, packages/serverless/src/awslambda.ts, packages/serverless/src/gcpfunction/http.ts, packages/serverless/test/awslambda.test.ts, packages/serverless/test/gcpfunction.test.ts, packages/tracing/src/browser/browsertracing.ts, packages/tracing/src/browser/request.ts, packages/tracing/src/span.ts, packages/tracing/test/browser/browsertracing.test.ts, packages/types/src/index.ts, packages/types/src/span.ts, packages/types/src/transaction.ts, packages/utils/src/baggage.ts, packages/utils/test/baggage.test.ts
This PR adds the propagation of an "empty" baggage header. The word "empty" is however kind of misleading as the header is not necessarily empty. In order to comply with the baggage spec, as of this PR, we propagate incoming (3rd party) baggage to outgoing requests. The important part of this PR is that we actually add the `baggage` HTTP header to outgoing requests which is a breaking change in terms of CORS rules having to be adjusted.
We don't yet add `sentry-` baggage entries to the propagated baggage. This will come in a follow up PR which does not necessarily have to be part of the initial v7 release as it is no longer a breaking change. 
Overall, the PR is heavily inspired from #3945 (thanks @lobsterkatie for doing the hard work)
More specifically, this PR does the following things: …
=> feat(tracing): Add empty baggage header propagation to outgoing requests

.craft.yml
Deactivated deployment of Lambda Layer until new Lambda Extension is production ready.
With this we make sure, that we do not break existing Lambda Layer users.
=> ref(serverless): Deactivate deployment of Lambda Layer

packages/tracing/src/browser/browsertracing.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/4098
=> fix(tracing): Don't use `querySelector` when not available

.github/workflows/build.yml
Currently, when looking at runs of our `Build & Test` GHA workflow, it's often hard to tell exactly what commit is being used. When the workflow is triggered by a push to a PR, the PR title ends up as the label, which can be pretty uninformative:
Runs triggered manually are no better:
Runs triggered by pushes _are_ better...
...at least from the outisde, but once you're in one, it's not obvious from the logs which commit is being used:
(That SHA listed in the checkout step isn't even that helpful, because by default it's not the branch's `HEAD` commit but rather a made-up merge commit between `HEAD` and the base branch, making it useless for identifying `HEAD`.)
This fixes that problem, by adding a preliminary GHA job to gather and store the SHA of the actual branch head (along with its …
=> ref(dev): Improve labeling of checkout step in GHA

packages/core/src/envelope.ts
This very small PR removes an unnecessary nested call to `dropUndefinedKeys` which we don't need because the function is already recursive (which could be causing a problem).
=> ref(core): Remove unnecessary nested `dropUndefinedKeys` call

packages/core/test/lib/integrations/inboundfilters.test.ts, packages/hub/src/scope.ts, packages/integrations/src/debug.ts, packages/integrations/src/extraerrordata.ts, packages/integrations/test/debug.test.ts, packages/integrations/test/offline.test.ts, packages/node/src/integrations/linkederrors.ts, packages/node/test/integrations/linkederrors.test.ts, packages/types/src/eventprocessor.ts, packages/types/src/options.ts
Now we allow mutating of properties in the hint to pass through things like attachments in `beforeSend` and Event processors, the hint is always defined, even if it's just an empty object. 
This PR removes the optional from the types which means users will no longer need to do unnecessary things like this to work around the incorrect types:
https://github.com/getsentry/sentry-javascript/pull/5140/files#diff-51dd65d366cb1690b4b8b45f0f835ae66f2a20b4d7ee77c0b6c1f2efd28dcb55R48-R54
Because theses are callback parameters and users can just leave off parameters they're not using, this is not a breaking change and means the types more accurately reflect what we're passing to the callback. 
Even if a user has code with an optional parameter type defined:
```ts 
addGlobalEventProcessor(async …
```
=> ref(core): Make hint callback argument non-optional

packages/utils/src/object.ts, packages/utils/test/object.test.ts
Gets rid of infinite recursion in `dropUndefinedKeys` when passing objects/arrays with circular references.
Reported in https://github.com/getsentry/sentry-javascript/issues/2470#issuecomment-1132730854
=> fix(utils): Fix infinite recursion in `dropUndefinedKeys`

MIGRATION.md, packages/ember/addon/instance-initializers/sentry-performance.ts, packages/nextjs/src/index.client.ts, packages/tracing/src/browser/browsertracing.ts, packages/tracing/src/browser/index.ts, packages/tracing/src/index.ts, packages/tracing/test/index.bundle.test.ts, packages/tracing/test/index.test.ts
Makes `@sentry/tracing` treeshakable from `@sentry/nextjs`, by text-replacing `__SENTRY_TRACING__` with `false` in any bundler or pre-processor.
Ref: https://getsentry.atlassian.net/browse/WEB-713
=> feat(nextjs): Make tracing package treeshakable

CHANGELOG.md, MIGRATION.md
ref: https://github.com/getsentry/sentry-javascript/issues/4240
ref: https://github.com/getsentry/sentry-javascript/issues/4882
CHANGELOG for the release of v7
=> meta: 7.0.0 CHANGELOG

CHANGELOG.md
=> misc: Remove new lines from changelog lists to make rendering unified

packages/angular/test/tsconfig.json, packages/browser/test/tsconfig.json, packages/core/test/tsconfig.json, packages/gatsby/test/tsconfig.json, packages/hub/test/tsconfig.json, packages/integrations/test/tsconfig.json, packages/nextjs/test/tsconfig.json, packages/node-integration-tests/suites/tsconfig.json, packages/node/test/tsconfig.json, packages/react/test/tsconfig.json, packages/serverless/test/tsconfig.json, packages/tracing/test/tsconfig.json, packages/utils/test/tsconfig.json, packages/vue/test/tsconfig.json, packages/wasm/test/tsconfig.json, tsconfig-templates/README.md, tsconfig-templates/test/tsconfig.json
It is well-documented ([1](https://github.com/angular/angular-cli/issues/5175), [2](https://github.com/microsoft/TypeScript/issues/49210), [3](https://github.com/microsoft/vscode/issues/107750), [4](https://github.com/Microsoft/vscode/issues/12463), [5](https://github.com/mseag/bible-karaoke/issues/175), [6](https://github.com/microsoft/TypeScript/issues/8435)) that VSCode doesn't support setups like ours, where multiple tsconfig files coexist in a single directory. Strangely, though, it is only recently that this has become a problem, with VSCode at random intervals forgetting that it's ever heard of `expect` or `describe` (because it's not seeing `tsconfig.test.json`, but taking a while to realize it).
There is an [open issue](https://github.com/microsoft/TypeScript/issues/33094) …
=> fix(dev): Add placeholder tsconfigs for tests

.github/workflows/build.yml
This changes our GHA workflow to only zip and upload the lambda layer when the uploaded artifact is needed for a release. (This matches the behavior of other uploaded artifacts.)
=> chore(build): Only upload lambda layer when releasing

packages/tracing/src/browser/metrics/index.ts
Electron renderers can have a combined Chrome and node.js context which can cause it to be detected as node.js when in fact it has full browser features.
This PR simplifies the detection of the browser `performance` API so that it doesn't fail to record page load metrics when running in an Electron renderer with mixed context.
=> fix(tracing): Fix missing page load metrics in Electron renderer

packages/node/src/transports/http-module.ts, packages/node/src/transports/http.ts, packages/node/test/transports/http.test.ts
This is mostly stolen straight from the [Electron transport](https://github.com/getsentry/sentry-electron/blob/master/src/main/transports/electron-net.ts).
This will help with attachments!
=> ref(node): Compression support for node http transport

rollup/bundleHelpers.js
This restores the plugin which includes debug logging in the configuration for our `.debug.min` bundles. (It was accidentally dropped in https://github.com/getsentry/sentry-javascript/pull/5142.)
=> fix(build): Add missing debug logger plugin in `debug.min` bundle variant config

packages/node/src/transports/http.ts, packages/node/test/transports/http.test.ts
#5139 introduced a subtle bug where `options.headers` was modified which causes headers to leak between requests. This means requests after a compressed request will be incorrectly marked with `content-encoding: gzip`.
=> fix(node): Compression headers leak between requests

packages/utils/src/object.ts, packages/utils/test/object.test.ts
For a long time, our helper function `dropUndefinedKeys` (which might more accurately be named `dropKeysWithUndefinedValues`) had a bug: when presented with an object containing a circular reference, it was perfectly happy to follow that cycle and recurse infinitely right along with the object. This was fixed in https://github.com/getsentry/sentry-javascript/pull/5163 using a memoizer - we keep a reference to each value we process, and if we hit one we've seen before, we stop recursing. No more infinite loops, yay!
Unfortunately, that change introduced a new bug. By design, `dropUndefinedKeys` doesn't mutate the object it's given, instead performing a deep copy which just skips over any keys whose value is `undefined`, eventually returning an object wholely separate from the original. If …
=> fix(utils): Fix faulty references in `dropUndefinedKeys`

packages/nextjs/src/utils/instrumentServer.ts, packages/nextjs/src/utils/withSentry.ts, packages/node/src/client.ts, packages/node/src/handlers.ts, packages/node/src/index.ts, packages/node/test/client.test.ts, packages/node/test/handlers.test.ts, packages/node/test/requestdata.test.ts, packages/serverless/src/awslambda.ts, packages/serverless/src/gcpfunction/general.ts, packages/serverless/src/gcpfunction/http.ts, packages/serverless/test/__mocks__/@sentry/node.ts, packages/serverless/test/awslambda.test.ts, packages/serverless/test/gcpfunction.test.ts, packages/utils/package.json, packages/utils/src/index.ts, packages/utils/src/requestdata.ts
Currently, the `handlers` module includes not just our middleware handlers but also a bunch of code for extracting context data and applying it to events. That latter code is indeed used in the handlers, but it's also used in a number of other places in the repo. This pulls that code into its own module in `@sentry/utils`, to make it possible to use in a platform-agnostic context.
Key changes:
-  A new `requestData` module in `@sentry/utils` to hold the data extraction code (and a new test file for its tests).
- Wrapper functions in the `handlers` module for backwards compatibility. (IOW, calling `Handlers.someFunc()` still works, but it's now just a passthrough to `someFunc` from the new module.)
- Deprecation notices in the docstrings of the wrappers, and TODOs so we remember to make …
=> ref(node): Move non-handler code out of `handlers` module

packages/node/src/transports/http-module.ts, packages/node/src/transports/http.ts, packages/node/test/transports/http.test.ts
_Note: This is an exact duplicate of https://github.com/getsentry/sentry-javascript/pull/5139 and https://github.com/getsentry/sentry-javascript/pull/5203, both originally by @timfish, which accidentally got merged into the 7.x branch rather than master._
https://github.com/getsentry/sentry-javascript/pull/5139:
This is mostly stolen straight from the [Electron transport](https://github.com/getsentry/sentry-electron/blob/master/src/main/transports/electron-net.ts).
This will help with attachments!
https://github.com/getsentry/sentry-javascript/pull/5203:
#5139 introduced a subtle bug where `options.headers` was modified which causes headers to leak between requests. This means requests after a compressed request will be incorrectly marked with `content-encoding: gzip`.
=> feat(node): Compression support for `http` transport

packages/node-integration-tests/suites/express/sentry-trace/baggage-header-assign/test.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-header-out/test.ts, packages/node-integration-tests/suites/express/sentry-trace/server.ts, packages/node/test/integrations/http.test.ts, packages/tracing/src/browser/request.ts, packages/tracing/src/span.ts, packages/tracing/src/transaction.ts, packages/tracing/test/browser/browsertracing.test.ts, packages/tracing/test/span.test.ts, packages/types/src/span.ts, packages/utils/src/baggage.ts, packages/utils/test/baggage.test.ts
Following #5133, this PR adds the `sentry-environment` and `sentry-release` values to the `baggage` HTTP headers of outgoing requests. We add these values to baggage as late as possible with the rationale that other baggage values (to be added in the future) will not be available right away, e.g. when intercepting baggage from incoming requests. 
As a result, the flow described below happens, when the first call to `span.getBaggage` is made (e.g. in callbacks of instrumented outgoing requests): 
1. In `span.getBaggage`, check if there is baggage present in the span (in which case it was intercepted from incoming headers/meta tags) and it is empty (or only includes 3rd party data) OR if there is no baggage yet
2. In both of these cases, populate the baggage with Sentry data (and leave 3rd …
=> feat(tracing): Propagate environment and release values in baggage Http headers

packages/serverless/src/awslambda.ts
In AWS Lambda Integration of V7 the DSN of the user is changed to point to `localhost:3000` (that is the URL of the Lambda Extension, that is not yet released)
This breaks the Serverless AWS Lambda Integration, so I disabled "changing the DSN" until the Lambda Extension is released. 
Was reported by a user in this PR: https://github.com/getsentry/sentry-javascript/pull/5126
Fixes https://github.com/getsentry/sentry-javascript/issues/5211
=> fix(serverless) Do not change DSN in Serverless integration

packages/types/src/index.ts, packages/types/src/textencoder.ts, packages/types/src/transport.ts, packages/utils/src/envelope.ts
`TextEncoderCommon` is a type from `lib.dom.d.ts`. We don't want to
require users to set DOM types, so we vendor it in. It's a relatively
simple type, so we don't have to worry about potential conflicts or user
issues.
Fixes https://github.com/getsentry/sentry-javascript/issues/5199
Ref: https://getsentry.atlassian.net/browse/WEB-952
=> fix(types): Vendor in TextEncoderCommon type

CHANGELOG.md
Needs to be merged after https://github.com/getsentry/sentry-javascript/pull/5223 gets merged.
=> meta: CHANGELOG for 7.1.1

packages/nextjs/src/index.server.ts, packages/nextjs/test/integration/pages/reportDialog.tsx, packages/nextjs/test/integration/test/client/reportDialog.js
Resolves: #5240 
Exported from the `server` index, like the other SSR exports of `@sentry/react`.
=> fix(nextjs): Export `showReportDialog` from NextJS SDK

packages/integrations/test/captureconsole.test.ts, packages/utils/src/logger.ts
=> chore: add trace to CONSOLE_LEVELS

packages/angular/package.json
This PR adds Angular 14 peer dependencies to `package.json` to make our SDK compatible with the recently released version 14 of Angular. Tested on an NG14 sample projects - Errors, transaction and component instrumentation work as expected.
Fixes #5215
=> feat(angular): Add Angular 14 support

packages/nextjs/src/utils/instrumentServer.ts, packages/nextjs/src/utils/withSentry.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-header-assign/test.ts, packages/node/src/handlers.ts, packages/node/test/handlers.test.ts, packages/serverless/src/awslambda.ts, packages/serverless/src/gcpfunction/http.ts, packages/serverless/test/awslambda.test.ts, packages/serverless/test/gcpfunction.test.ts, packages/serverless/test/google-cloud-grpc.test.ts, packages/tracing/src/browser/browsertracing.ts, packages/tracing/src/span.ts, packages/tracing/test/browser/browsertracing.test.ts, packages/tracing/test/span.test.ts, packages/types/src/baggage.ts, packages/utils/src/baggage.ts, packages/utils/test/baggage.test.ts
This PR addresses the mutability aspect of baggage. It introduces a third item to our `Baggage` tuple which is a mutability  flag. The reason for adding this flag is to set the mutability of the baggage object when we receive one, either from incoming requests or `<meta>` tags in the browser. It's necessary to decide about mutability at this time because the decision depends on the `sentry-trace` header. Since we're lazily populating baggage when it gets sent (propagated), we have to know at that time, if we are allowed to add `sentry-` entries to it, or if we should just pass it along as is. The only way to cover all cases of when we're allowed to make changes is to set the flag at the incoming time and check it at population time. 
Specifically, we identify and handle mutability in the …
=> ref(tracing): Check and set mutability of baggage

MIGRATION.md
Change the import for `SeverityLevel` from utils -> types to better reflect how it actually works.
=> fix: Update MIGRATION for SeverityLevel

packages/vue/src/components.ts, packages/vue/test/components.test.ts
Fixes #5204 
Returns the `ANONYMOUS_COMPONENT_NAME` early if `vm.$options` is not defined.
---
=> fix(vue): accounts for undefined options when formatting component name

package.json, packages/remix/.eslintrc.js, packages/remix/LICENSE, packages/remix/README.md, packages/remix/jest.config.js, packages/remix/package.json, packages/remix/rollup.npm.config.js, packages/remix/src/index.ts, packages/remix/tsconfig.esm.json, packages/remix/tsconfig.json, packages/remix/tsconfig.test.json, packages/remix/tsconfig.types.json, scripts/test.ts, yarn.lock
Part 1 of #4894
Adds the package boilerplate for Remix SDK.
=> feat: Add Remix SDK package boilerplate.

packages/nextjs/src/utils/instrumentServer.ts, packages/nextjs/src/utils/withSentry.ts, packages/node/src/client.ts, packages/node/src/handlers.ts, packages/node/src/index.ts, packages/node/src/requestDataDeprecated.ts, packages/node/src/sdk.ts, packages/node/test/client.test.ts, packages/node/test/handlers.test.ts, packages/node/test/requestdata.test.ts, packages/serverless/src/awslambda.ts, packages/serverless/src/gcpfunction/cloud_events.ts, packages/serverless/src/gcpfunction/events.ts, packages/serverless/src/gcpfunction/general.ts, packages/serverless/src/gcpfunction/http.ts, packages/serverless/test/__mocks__/@sentry/node.ts, packages/serverless/test/awslambda.test.ts, packages/serverless/test/gcpfunction.test.ts, packages/utils/src/index.ts, packages/utils/src/requestdata.ts
_See https://github.com/getsentry/sentry-javascript/pull/5190 for a detailed description of the motivation for and main substance of this change. TL;DR, isomorphic frameworks like Nextjs need this code to live in a neutral location (rather than in the node package) so it can be used in a browser setting as well._ 
This is a second take on https://github.com/getsentry/sentry-javascript/pull/5190, which had to be reverted because it relied on a peer dependency (`cookie`) which browser-only apps wouldn't have installed. Even if those code didn't _use_ `cookie`, they still failed to compile because without `cookie` installed, `@sentry/utils` didn't typecheck correctly.
This fixes that problem by using `cookie` (and `url`, for node 8 compatibility) only as injected dependencies, not as direct …
=> ref(node): Move request-data-extraction functions to`@sentry/utils`

packages/angular/jest.config.js, packages/angular/package.json, packages/angular/src/errorhandler.ts, packages/angular/src/sdk.ts, packages/angular/test/sdk.test.ts
Query and send the Angular version in events to Sentry to let us know which Angular versions are used by our users. This should help us make data-based Angular version support decisions in the future.
=> chore(angular): Add Angular version to event contexts

.vscode/launch.json, package.json, yarn.lock
This adds a VSCode debugging profile for playwright tests, which works the same way the unit test debugging profile works - whatever file is open in the active editor will be the one tested, and the tests run in watch mode. Because playwright [doesn't have a watch mode of its own](https://github.com/microsoft/playwright/issues/7035), the profile uses the [`nodemon` Node wrapper](https://github.com/remy/nodemon) to do the watching of files and restarting of tests whenever anything changes.
=> feat(dev): Add VSCode playwright debug profile

packages/remix/package.json, packages/remix/src/flags.ts, packages/remix/src/index.client.tsx, packages/remix/src/index.ts, packages/remix/src/performance/client.tsx, packages/remix/src/utils/metadata.ts, packages/remix/src/utils/remixOptions.ts, packages/remix/test/index.client.test.ts
Part 2 of https://github.com/getsentry/sentry-javascript/issues/4894
Adds client side SDK for error tracking / performance tracing of Remix.
- Uses React SDK underneath, and requires `<ErrorBoundary />` to properly catch errors.
- Supports parameterized route paths with `remixRouterInstrumentation` and `withSentryRouteTracing`.
Manually Tested:
Need to add tests for performance / routing.
=> feat(remix): Add Remix client SDK.

packages/core/src/baseclient.ts, packages/core/src/envelope.ts, packages/core/test/lib/base.test.ts, packages/core/test/mocks/client.ts, packages/integration-tests/suites/public-api/configureScope/clear_scope/test.ts, packages/integration-tests/utils/helpers.ts, packages/node-integration-tests/suites/public-api/configureScope/clear_scope/test.ts, packages/node-integration-tests/suites/public-api/withScope/nested-scopes/test.ts
In https://github.com/getsentry/sentry-javascript/pull/4425 and https://github.com/getsentry/sentry-javascript/pull/4574, various hacks were added to the SDK in aid of debugging https://github.com/getsentry/sentry-javascript/issues/2809. Now that that issue is closed, they (and the clean-up code in tests which was there to compensate for them) can come out.
=> chore(core): Remove circular JSON debugging hacks

.craft.yml
Its currently `private`, so we dont want `npm` to pick it up, as it will fail whole build workflow.
=> ci: Ignore sentry-remix for publishing

packages/vue/src/errorhandler.ts, packages/vue/src/types.ts, packages/vue/test/errorHandler.test.ts, packages/vue/tsconfig.test.json
=> fix(vue): property access on undefined in errorHandler

packages/nextjs/src/index.client.ts, packages/nextjs/src/index.server.ts, packages/nextjs/src/utils/_error.ts
In order to have Sentry capture certain kinds of errors in nextjs, users need to add a custom `_error.js` file to their projects. We do this automatically when users go through the wizard setup, but [the file we've been adding](https://github.com/getsentry/sentry-wizard/blob/v1.2.17/scripts/NextJs/configs/_error.js) is just a clone of the one in vercel's `with-sentry` nextjs example app, and is simultaneously quite verbose and pretty bare-bones in terms of what it does. (This is not a knock on the folks who wrote it, who don't have the context we do, but the fact remains that it could stand to be improved.)
This does so, by creating a utility function, `captureUnderscoreErrorException`, for users to use in place of the manual edge-case handling and `captureException` calls in the …
=> feat(nextjs): Add exception handler for `_error.js`

packages/node/src/integrations/http.ts, packages/types/src/index.ts, packages/types/src/misc.ts, packages/utils/src/baggage.ts, packages/utils/test/baggage.test.ts
This PR attempts to fix a bug reported in #5250 where the input parameter for `parseBaggageString` was not a string and hence the `string.split` function call would throw an error. This PR now checks for the type of the input and makes the function
* return an empty baggage object if the input is neither a string, nor an array. In this case we log a warning to get more information on what is actually passed in.
* parse the baggage string if the input is a string
* join and then split the array if the input is an array
Additionally, the parser now ignores empty or blank baggage entries (e.g. `foo=bar,   ,,alice=bob`).
This is far from a proper, complete bugfix because we're missing an actual reproduction of the exact error but we got similar errors when experimenting with a Node/Express …
=> fix(tracing): Baggage parsing fails when input is not of type string

packages/node/src/integrations/http.ts, packages/tracing/src/browser/request.ts, packages/tracing/src/span.ts, packages/tracing/src/transaction.ts, packages/tracing/test/span.test.ts, packages/types/src/span.ts, packages/types/src/transaction.ts, packages/utils/src/baggage.ts
As already discussed in #5292, this PR moves the `getBaggage()` method from the `Span` class, to the `Transaction` class. This change is good for two reasons:
1. It conceptually makes more sense to store DSC on the transaction rather than the span because we're always talking about transactions in DS
2. We can get rid of a sketchy type cast and avoid a circular dependency situation (transaction -> span -> transaction) entirely
=> ref(tracing): Move `getBaggage()` from `Span` to `Transaction` class

packages/tracing/src/browser/metrics/index.ts
* ttfb.requestTime is multiplied times 1000 and is documented in a code comment as ms
* Cumulative Layout Shift does not have a unit. A layout cannot shift by 10 milliseconds
=> fix(tracing): Report the right units for CLS and TTFB [INGEST-1409]

packages/core/src/baseclient.ts
Remove optional chaining usage. This should mean we don't import the optional chaining polyfill into the browser bundle any more.
We really need to lint against this probably.
(proof it was pulling in the polyfill)
=> fix(core): Remove optional chaining usage

packages/hub/src/scope.ts
Move field initializers inside constructor to reduce bundle size.
=> ref(hub): Reduce hub bundle size

packages/tracing/src/browser/metrics/index.ts, packages/tracing/src/transaction.ts, packages/types/src/event.ts, packages/types/src/index.ts, packages/types/src/measurement.ts, packages/types/src/transaction.ts
Folks gave some feedback that we should be explicit about the units we
support. Let's add TypeScript types for these so we don't add any
runtime logic, but it should have helpful autocomplete for users.
cc @k-fish who brought this up with https://github.com/getsentry/sentry/pull/36012
=> feat(types): Add type for measurement unit

.github/workflows/build.yml
We need to run size-limit on master so that we upload size assets that we can do comparisons with.
Some formatting fixes climbed in, but `${{ github.event_name == 'pull_request' }} || ${{ startsWith(github.ref, 'refs/heads/master/') }}` is the line to care about.
=> build: Run size-limit action on master

packages/nextjs/src/utils/withSentry.ts, packages/node-integration-tests/package.json, packages/node-integration-tests/suites/express/sentry-trace/baggage-header-assign/test.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-other-vendors-with-sentry-entries/server.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-other-vendors-with-sentry-entries/test.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-other-vendors/server.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-other-vendors/test.ts, packages/node/src/handlers.ts, packages/node/test/handlers.test.ts, packages/serverless/src/awslambda.ts, packages/serverless/src/gcpfunction/http.ts, packages/serverless/test/awslambda.test.ts, packages/serverless/test/gcpfunction.test.ts, packages/tracing/src/transaction.ts, packages/tracing/test/browser/browsertracing.test.ts, packages/tracing/test/span.test.ts, packages/utils/src/baggage.ts, packages/utils/test/baggage.test.ts
This PR makes changes to how we handle third party content in the `baggage` Http header: On incoming requests we no longer parse and put non-`sentry-` baggage entries into the `Baggage` object but we ignore them and instead store an empty third party string. The reason for this change is that - as we discussed and agreed upon - the Sentry SDK should not be responsible for propagating other vendors' data. If users want to propagate that data as well on the service where the Sentry SDK is installed, they should add the other vendors' propagation mechanisms. In fact, this is the only way we can ensure that baggage content that should _not_ be propagated further is really stopped. 
It's important to note that this only concerns _incoming_ 3rd party baggage items. If other vendors (or the …
=> ref(tracing): Ignore third party baggage entries from incoming requests

packages/utils/src/baggage.ts
Just a simple typo fix, I forgot to commit to #5319
=> chore(doc): Fix typo in JSDoc of parseBaggageHeader

.github/workflows/build.yml
Since we re-enabled the "Size Check" job for GHA runs on `master` in #5314, our CI runs were failing because the "Size Check" job was failing. The reason is that our [size-limit-action](https://github.com/getsentry/size-limit-action) is not passing on the `skip_step` option we set here
https://github.com/getsentry/sentry-javascript/blob/05cb748bdaba970eacf40b62405090688eeac7bc/.github/workflows/build.yml#L210
if it is [executed on the master branch](https://github.com/getsentry/size-limit-action/blob/3f9e584f47175f7f2ac742569ac16b7a8c05ad82/src/main.ts#L68-L74). Instead, `null` is passed to the execution function of the action which makes the action first call `yarn install` followed by `yarn build`. This fails because the Ember SDK cannot be built with Node 16.  
While the best option to …
=> fix(build): Use Node 14 in "Size Check" job to fix CI runs on master

packages/utils/src/normalize.ts, packages/utils/test/normalize.test.ts
This PR handles a case in `normalize()` when a `.toJSON` method on an input value either returns an object with a circular reference or the input value itself, causing problems down the line.
- Normalize the return value from `toJSON`
- Add tests to check for edge cases
To detect circular references we need to do a memoize call before normalizing the return value from `toJSON`. However, at the location we're currently calling the `toJSON` method, `value` could still be a primitive like `string` or `number` and we can't call `memoize` with primitives because the underlying `WeakSet` only takes `object`s.
As a compromise, we're moving the `toJSON` call down to where `value` is certainly an object or array and after the circ-ref-check. I believe it is ok for us to only call `toJSON` on …
=> fix(utils): Handle `toJSON` methods that return circular references

CHANGELOG.md
https://github.com/getsentry/sentry-javascript/issues/4894
=> meta: Add CHANGELOG for 7.4.0

packages/remix/package.json
Publishing failed because we missed a flag in the package.json: https://github.com/getsentry/publish/runs/7147811439?check_suite_focus=true#step:10:1282
=> build(remix): Make remix package public

packages/remix/package.json
Fixes #5351 
Looks like just a typo exporting an esm module under main
=> fix(remix): Use cjs for main entry point

packages/integration-tests/suites/tracing/envelope-header-no-pii/init.js, packages/integration-tests/suites/tracing/envelope-header-no-pii/test.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-header-out/server.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-header-out/test.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-user-id/server.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-user-id/test.ts, packages/node/test/integrations/http.test.ts, packages/tracing/src/hubextensions.ts, packages/tracing/src/transaction.ts, packages/tracing/test/span.test.ts
This PR adds the check if `sendDefaultPii` is set to `true` before adding the `user_id` when populating DSC. 
Additionally, the PR adds some tests to check for the changed behaviour.
resolves #5343
=> ref(tracing): Only add `user_id` to DSC if `sendDefaultPii` is `true`

packages/remix/README.md
There's a typo in the example for `root.tsx`.
=> docs(remix): Add missing comma in README

packages/remix/.eslintrc.js, packages/remix/.npmignore, packages/remix/scripts/prepack.ts
To upload source maps to Sentry, the Remix SDK includes a script that wraps around Sentry CLI to make uploading sourcemaps easier for our users. However, due to the way how we package our NPM tarballs, this script didn't make it into the Remix SDK tarball.
This PR adds the script to the tarball, which required the following changes:
* Added a package-specific `prepack.ts` script which is invoked by the main `prepack.ts` script. This is similar to how we do it with the Gatsby SDK where - just as with Remix - we need to copy over additional files to the `build` directory that are not part of our other packages. The newly added files are:
* `scripts/sentry-upload-sourcemaps.js`
* `scripts/createRelease.js`
* Added a package-specific `.npmignore` which extends the root level `.npmignore` file …
=> fix(remix): Sourcemaps upload script is missing in the tarball

packages/remix/README.md
=> docs(remix): Adjust wording in Remix README

packages/core/test/lib/envelope.test.ts, packages/integration-tests/suites/tracing/envelope-header-no-pii/test.ts, packages/integration-tests/suites/tracing/envelope-header/init.js, packages/integration-tests/suites/tracing/envelope-header/test.ts, packages/node-integration-tests/package.json, packages/node-integration-tests/suites/express/sentry-trace/baggage-header-assign/test.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-header-out/test.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-other-vendors-with-sentry-entries/test.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-user-id/server.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-user-id/test.ts, packages/node/test/integrations/http.test.ts, packages/tracing/src/transaction.ts, packages/tracing/test/browser/browsertracing.test.ts, packages/tracing/test/span.test.ts, packages/types/src/envelope.ts, packages/types/src/options.ts
This patch temporarily removes the `user_id` and `transaction` (name) fields from the dynamic sampling context, meaning they will no longer propagated with outgoing requests via the baggage Http header or sent to sentry via the `trace` envelope header.
We're taking this temporary measure to ensure that for the moment PII is not sent to third parties. Developer spec is update in https://github.com/getsentry/develop/pull/631.
=> ref(tracing): Remove transaction name  and user_id from DSC

packages/remix/src/performance/client.tsx
`withSentryRouteTracing` is called on `root.tsx` which runs before `entry.client.tsx` (where `Sentry.init` for browser is called and `remixRouterInstrumentation` is assigned). 
The check if the provided hooks are available was failing silently, and causing `withSentryRouteTracing` to early return the `App` unwrapped.
This PR ensures that validation runs on the client side, after `entry.client.tsx`.
=> fix(remix): Move hook checks inside the wrapper component.

packages/remix/src/utils/instrumentServer.ts
Remove query params from transaction names to reduce cardinality.
=> fix(remix): Strip query params from transaction names

packages/tracing/src/transaction.ts, packages/tracing/test/span.test.ts, packages/types/src/event.ts, packages/types/src/index.ts, packages/types/src/transaction.ts
Ref: https://github.com/getsentry/sentry-javascript/issues/5345
This patch adds `source` information to `Transaction`, which is typed by
`TransactionSource` in `@sentry/tracing`. This helps track how the name
of a transaction was determined, which will be used by the server for
server-side controls.
For now, we are placing the `source` field under transaction metadata.
In the future, we can move this up into a top level API (an argument to
`startTransaction` or `transaction.setSource`) if needed, but this
should be fine to get us started.
For next steps, after this patch gets merged, we will start going
through various routing instrumentation frameworks and adding
transaction source.
=> feat(tracing): Add transaction source field

.github/workflows/build.yml
Because we keep running into situations where our builds fail out of the blue (https://github.com/getsentry/sentry-javascript/pull/5327#issuecomment-1171603041, https://github.com/getsentry/sentry-javascript/issues/5296#issuecomment-1165625869), I propose we install our dependencies in CI with `--frozen-lockfile` which simply installs packages exactly as described in `yarn.lock`. Additionally, we want to pin as many dependencies in our CI as possible, just so we can have reproducible builds.
This PR:
- adds a `--frozen-lockfile` flag to `yarn install` in our CI
- Pins a `ts-node` dependency version in CI
=> build: Install dependencies in CI with frozen lockfile

packages/remix/package.json
As I was dogfooding remix on https://github.com/getsentry/vanguard, I realized the remix peer deps are pretty restrictive. This opens it up so that we at least support `1.x` of remix - we can re-evaluate when a new major comes out!
=> fix(remix): Make peer deps less restrictive

packages/vue/src/router.ts, packages/vue/src/tracing.ts, packages/vue/test/router.test.ts
Ref: https://github.com/getsentry/sentry-javascript/issues/5345
Set transaction source on the VueRouter instrumentation and update the route types (this more acts like documentation).
=> feat(vue): Add transaction source to VueRouter instrumentation

packages/react/src/reactrouterv6.tsx, packages/react/test/reactrouterv6.test.tsx
ref: https://github.com/getsentry/sentry-javascript/issues/5345
=> ref(react): Add transaction source for react router v6

packages/react/src/reactrouter.tsx, packages/react/test/reactrouterv4.test.tsx, packages/react/test/reactrouterv5.test.tsx
ref: https://github.com/getsentry/sentry-javascript/issues/5345
=> ref(react): Add transaction source for react router v4/v5

packages/react/src/index.ts, packages/remix/README.md, packages/remix/src/index.client.tsx, packages/remix/src/index.server.ts, packages/remix/src/performance/client.tsx
Ref: https://github.com/getsentry/sentry-javascript/issues/4894
Wraps the Remix root with `ErrorBoundary` while wrapping it with the router instrumentation. 
`withSentryRouteTracing` can be renamed to something like `withSentry` from this point, but it is a breaking change, so I left it out.
=> feat(remix): Wrap root with `ErrorBoundary`.

packages/remix/src/utils/instrumentServer.ts
Partly fixes: #5362 
We're currently wrapping `action` and `loader` functions of Remix routes for tracing and error capturing.
When testing the case in #5362, I realized the `render` function of a SSR component in Remix has another handler
[`handleDocumentRequest`](https://github.com/remix-run/remix/blob/b928040061890a6ef0270abdb5b1201638f0dd00/packages/remix-server-runtime/server.ts#L174) which [doesn't re-throw internal errors](https://github.com/remix-run/remix/blob/main/packages/remix-server-runtime/server.ts#L502-L507) so we can't catch them in `wrapRequestHandler`.
Also added a tracing span for `handleDocumentRequest`.
Note: This is also the case with [`resource` requests](https://github.com/remix-run/remix/blob/main/packages/remix-server-runtime/server.ts#L512-L550). Maybe we need …
=> fix(remix): Wrap `handleDocumentRequest` functions.

packages/core/test/lib/envelope.test.ts, packages/integration-tests/suites/tracing/envelope-header-transaction-name/init.js, packages/integration-tests/suites/tracing/envelope-header-transaction-name/test.ts, packages/integration-tests/suites/tracing/envelope-header/init.js, packages/integration-tests/suites/tracing/envelope-header/test.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-header-assign/test.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-header-out/test.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-other-vendors-with-sentry-entries/test.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-transaction-name/server.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-transaction-name/test.ts, packages/node/test/integrations/http.test.ts, packages/tracing/src/transaction.ts, packages/tracing/test/browser/browsertracing.test.ts, packages/tracing/test/span.test.ts, packages/types/src/envelope.ts, packages/types/src/transaction.ts
This PR re-introduces the `transaction` field in the Dynamic Sampling Context (DSC). However, its presence is now determined by the [transaction source](https://develop.sentry.dev/sdk/event-payloads/transaction/#transaction-annotations) which was introduced in #5367.
As of this PR, we add the `transaction` field, if the source indicates that the tranasaction name is not an unparameterized URL. 
While making the changes, I decided to clean up the previously commented out references to user_id (from #5363) in both, source code and tests. Given that user_id was ditched from DS, we probably won't need them going forward.
Additionally, the PR (once again) adjusts our unit and integration tests to reflect this change. Repurposed some DSC<=>`sendDefaultPii` tests that we previously skipped to …
=> ref(tracing): Include transaction in DSC if transaction source is not an unparameterized URL

packages/nextjs/src/performance/client.ts, packages/nextjs/src/utils/instrumentServer.ts, packages/nextjs/src/utils/withSentry.ts, packages/nextjs/test/integration/test/server/tracing200.js, packages/nextjs/test/integration/test/server/tracing500.js, packages/nextjs/test/integration/test/server/tracingHttp.js, packages/nextjs/test/performance/client.test.ts, packages/nextjs/test/utils/withSentry.test.ts
This adds information about the source of the transaction name to all transactions created by the nextjs SDK.
=> feat(nextjs): Record transaction name source when creating transactions

packages/serverless/src/awslambda.ts, packages/serverless/src/gcpfunction/cloud_events.ts, packages/serverless/src/gcpfunction/events.ts, packages/serverless/src/gcpfunction/http.ts, packages/serverless/test/awslambda.test.ts, packages/serverless/test/gcpfunction.test.ts
ref: https://github.com/getsentry/sentry-javascript/issues/5345
Decided to go with `component` for the serverless functions as they are function names as transaction name.
=> ref(serverless): Add transaction source

packages/hub/src/exports.ts, packages/hub/test/exports.test.ts, packages/remix/src/utils/instrumentServer.ts, packages/serverless/src/awslambda.ts, packages/serverless/src/gcpfunction/cloud_events.ts, packages/serverless/src/gcpfunction/events.ts, packages/serverless/src/gcpfunction/http.ts, packages/serverless/test/__mocks__/@sentry/node.ts, packages/serverless/test/awslambda.test.ts, packages/serverless/test/gcpfunction.test.ts, packages/tracing/src/browser/browsertracing.ts, packages/tracing/src/transaction.ts, packages/tracing/test/browser/browsertracing.test.ts, packages/tracing/test/transaction.test.ts
This adds transaction name source to transaction metadata in various situations in which the name is set directly: starting a manual transaction, assigning to the `name` property of a transaction, calling a transaction's `setName` method, and changing the name using `beforeNavigate`.
In order to distinguish manually-created transactions from automatically-created ones, all internal uses of `startTransaction` have been changed so that they are happening directly on the hub, rather than through the top-level `Sentry.startTransaction()` wrapper.
=> feat(tracing): Record transaction name source when name set directly

packages/remix/src/utils/instrumentServer.ts
Fixes: #5401 
I wonder why TS doesn't complain about that.
It's `const name: never` in that scope. Could not find a sign of a global type declaration though.
=> fix(remix): Add `documentRequest` function name.

packages/remix/src/utils/instrumentServer.ts
ref: https://github.com/getsentry/sentry-javascript/issues/5362
[Remix supports throwing responses from `loader` and `action` functions for its internal `CatchBoundary`](https://remix.run/docs/en/v1/api/conventions#throwing-responses-in-loaders).
They are [catched on the caller level](https://github.com/remix-run/remix/blob/7688da5c75190a2e29496c78721456d6e12e3abe/packages/remix-server-runtime/data.ts#L41-L49), but as we wrap the callees, they are registered as exceptions in the SDK. Being http responses, they end up like `{size: 0}`, which is not meaningful.
This PR skips exception capturing for responses that are not `4xx` or `5xx`.
=> fix(remix): Skip capturing `ok` responses as errors.

packages/browser/src/client.ts, packages/core/src/api.ts, packages/core/src/baseclient.ts, packages/core/test/lib/api.test.ts
This adds `sentry_client` to the auth headers* we send with every envelope request, as described [in the develop docs](https://develop.sentry.dev/sdk/overview/#authentication).
In order to have access to the SDK metadata, the full `ClientOptions` object is now passed to `getEnvelopeEndpointWithUrlEncodedAuth`. Despite the fact that this is really an internal function, it's exported, so in order to keep everything backwards-compatible, for the moment it will also accept a string as the second argument, as it has in the past. Finally, all of our internal uses of the function have been switched to passing `options`, and there's a `TODO` in place so that we remember to remove the backwards compatibility in v8.
Note that this change doesn't affect anyone using a tunnel, as no auth headers are …
=> fix(core): Add `sentry_client` to auth headers

packages/angular/src/errorhandler.ts, packages/angular/src/tracing.ts, packages/angular/test/tracing.test.ts
This PR introduces URL Parameterization to our Angular SDK. With this change, the SDK will update transaction names coming from a URL with a paramterized version of the URL (e.g `GET /users/1235/details` will be parameterized to `GET /users/:userId/details/`).
This is done by listening to the `ResolveEnd` routing event in `TraceService`. When this event is fired, the Angular router has finished resolving the new URL and found the correct route. Besides the url, the event contains a snapshot of the resolved and soon-to-be activated route. This `ActivatedRouteSnapshot` instance is the root instance of the activated route. If the resolved route is something other than `''` or `'/'`, it will also points to its first child. This instance might again point to its (a possibly existing) child but …
=> feat(Angular): Add URL Parameterization of Transaction Names

packages/nextjs/src/utils/_error.ts
For a long time, the `_error.js` page we provide `@sentry/nextjs` users contained a workaround for https://github.com/vercel/next.js/issues/8592. When most of the code in `_error.js` was moved into `captureUnderscoreErrorException`, parts of the workaround came along for the ride. Now that that issue has been fixed, the workaround is no longer necessary.
This removes as many of the workaround's vestiges in `captureUnderscoreErrorException` as possible. (We can't remove them all, because the workaround existed in user code rather than ours, and we can't stop people from continuing to use it. This fixes things so that if they do that, it'll just bail gracefully.)
=> ref(nextjs): Remove compensation for workaround in `_error.js`

packages/remix/src/utils/instrumentServer.ts
Fixes: #5423
Ref: #5405 
We were extracting the bodies of 4xx/5xx responses to capture, but Remix also uses them, we should not consume their `body` streams, as they are only available once in response lifespans. 
This PR updates `extractData` to work on a clone response.
=> fix(remix): Clone erroneous responses not to consume their body streams.

packages/remix/src/utils/instrumentServer.ts
Fixes: #5425 
Ref: #5429, #5405 
As per review https://github.com/getsentry/sentry-javascript/pull/5429#issuecomment-1189139234, we need to define how and when we should capture a 4xx error.
We will only capture thrown 5xx responses until then.
=> fix(remix): Do not capture 4xx codes from thrown responses.

packages/angular/src/errorhandler.ts, packages/angular/test/errorhandler.test.ts, packages/browser/src/eventbuilder.ts
Fixes: #3836
Used the approach from node implementation to allow setting custom mechanisms:
https://github.com/getsentry/sentry-javascript/blob/0acf10cf9dcc7f9548c3bcbbf3818f2d7340e05b/packages/node/src/backend.ts#L30-L35
`eventbuilder.ts` does not have tests, so I haven't added a test for this update. I can open a spin-off PR for testing it as whole if you find that useful.
=> feat(browser): Allow mechanism to be provided as a hint. Update `angular` exception mechanism.

packages/utils/src/misc.ts, packages/utils/test/misc.test.ts
Since [modern browsers](https://caniuse.com/mdn-api_crypto_randomuuid) support `crypto.randomUUID()` it's probably a good idea to use that when available. 
Rather than let this impact bundle size, I also took some of the recent updates from the linked stackoverflow question.
- Shaves ~160 bytes off the browser bundle
- I have validated that all code paths do in fact return valid uuidv4 ids with hyphens removed!
- Modern platforms bail out quickly with `crypto.randomUUID()`
- Less modern browsers (including IE11 and Safari < v15.4) use `crypto.getRandomValues()`
- Node.js 
- `< v15` uses `Math.random()`
- `v15 > v16.7 uses` `crypto.getRandomValues()`
- `>= v16.7 uses` `crypto.randomUUID()`
Downsides vs previous code:
- The "code golf" style code is nasty but since this is a utility …
=> ref(utils): Improve uuid generation

packages/nextjs/src/config/webpack.ts
In https://github.com/getsentry/sentry-javascript/pull/4988, we switched to using `eval` in `ensureCLIBinaryExists` (called by our build-time config code in the nextjs SDK), in order to prevent Vercel's dependency-tracing algorithm from thinking the binary was a (n enormous) dependency and including it in people's serverless functions. (It was getting tricked by the `require.resolve()` call; turning that call into a string was the only way we could find to hide it from the algorithm.)
But `eval` is kind of gross. And Rollup, which agrees it's gross, keeps yelling at us for using it. In order to suppress the warnings and generally clean things up, this replaces the `eval` with real code again, and in that real code replaces the `require.resolve()` call with a manual check of all of the …
=> fix(nextjs): Stop using `eval` when checking for `sentry-cli` binary

packages/remix/src/utils/instrumentServer.ts
Ref: #4894
[Remix provides a `meta` function to set `<meta>` tags for route modules.](https://remix.run/docs/en/v1/api/conventions#page-context-in-meta-function)
This PR adds a meta function to each route to set `sentry-trace` using the `http.server` (root) span.
=> feat(remix): Set `sentry-trace` `<meta>` on server-side.

packages/gatsby/package.json, packages/nextjs/package.json, packages/remix/package.json, yarn.lock
This updates our dependency in order to take advantage of https://github.com/getsentry/sentry-webpack-plugin/pull/389.
Fixes https://github.com/getsentry/sentry-javascript/issues/5424
=> chore(nextjs/gatsby/remix): Bump webpack plugin to 1.19.0

packages/nextjs/rollup.npm.config.js, packages/nextjs/src/config/prefixLoader.ts, packages/nextjs/src/config/prefixLoaderTemplate.ts, packages/nextjs/src/config/types.ts, packages/nextjs/src/config/webpack.ts, packages/nextjs/src/index.server.ts, packages/nextjs/test/config.test.ts
In order to work, in the nextjs SDK our server-side `RewriteFrames` integration needs to know the name of the directory into which the app is built. While that information is readily available at build time, it isn't at runtime, so we adjust the webpack config to inject a global variable with the correct value in before the the injected `Sentry.init()` call from `sentry.server.config.js` wherever we inject that `Sentry.init().
Currently, this is done by creating a temporary file with the relevant code and adding it to the relevant pages' `entry` value along with `sentry.server.config.js`. This works, but [has its downsides](https://github.com/getsentry/sentry-javascript/pull/4813), and is a fair amount of machinery just to add a single line of code.
This injects the same line of code …
=> ref(nextjs): Use loader to set `RewriteFrames` helper value

packages/nextjs/src/utils/_error.ts
This removes the index signature in the `ContextOrProps` type in our nextjs `_error` helper function, `captureUnderscoreErrorException`, as it's causing build errors for people writing their `_error` page in TS.
Note: The [problem I anticipated](https://github.com/getsentry/sentry-javascript/issues/5448#issuecomment-1194786778), which led me to add it in the first place, hasn't materialized in my testing. 
Fixes https://github.com/getsentry/sentry-javascript/issues/5448.
=> fix(nextjs): Remove index signaure in `captureUnderscoreErrorException` argument type

packages/nextjs/src/index.server.ts, packages/nextjs/src/utils/isBuild.ts, packages/nextjs/test/utils/isBuild.test.ts
In nextjs hooks which run both during build- and runtime (like `getStaticProps`, which mostly is a build-time function, but [will run at runtime](https://nextjs.org/docs/basic-features/data-fetching/get-static-props#when-does-getstaticprops-run) if revalidation is turned on) it's sometimes helpful to know which you're in, and there's no official way to do that that I've been able to find. In our case, we need to know which phase we're in because by the time pages get loaded in order to be rendered during build, they already have a `Sentry.init()` call baked in, causing the SDK to run. Since certain operations can only happen at runtime, we have logic in `index.server.ts` to detect the current phase.
This pulls that logic into a utility function, so that it can be exported. (Ultimately …
=> ref(nextjs): Extract `isBuild` into an exported function

packages/tracing/src/transaction.ts, packages/types/src/transaction.ts
This adds span metadata to the `TransactionMetadata` type and the default value given to the `metadata` property in the `Transaction` constructor. I chose to add a property to `TransactionMetadata` rather than create a new `SpanMetadata` type/property which would live on the `Span` class because by doing the former, we don't have to worry about looping over the spans and deleting the metadata before the transaction is sent - everything in `transaction.metadata` (which becomes `event.sdkProcessingMetadata`) [is already cleared when the envelope is created](https://github.com/getsentry/sentry-javascript/blob/8a06b16d605ca3a1fa6c9af2a701f332e39799ed/packages/core/src/envelope.ts#L86).
In order to not have to assert on its existence every time it's used, I made `spanMetadata` a required …
=> feat(tracing): Allow storing span metadata

packages/node-integration-tests/suites/express/sentry-trace/baggage-header-assign/test.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-header-out-bad-tx-name/server.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-header-out-bad-tx-name/test.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-header-out/server.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-other-vendors-with-sentry-entries/test.ts, packages/node/src/handlers.ts, packages/node/test/requestdata.test.ts, packages/tracing/src/integrations/node/express.ts, packages/utils/src/requestdata.ts
This PR improves the URL parameterization for transaction names in our Express integration.
Previously, we would only obtain a parameterized version of the incoming request's URL **after** the registered handler(s) finished their job, right before we called `transaction.finish()`. This is definitely too late for DSC propagation, if the handlers made any outgoing request. In that case, the DSC (propagated via the `baggage` header) would not contain a transaction name.
As of this PR, we patch the `Express.Router` prototype, more precisely the `process_params` function. This function contains a reference to the incoming `req` object as well as to the `layer` that matched the route. We hook into the function to extract the matched and parameterized partial route of the layer and we attach it …
=> ref(node): Improve Express URL Parameterization

packages/react/src/redux.ts, packages/react/test/redux.test.ts
Switch to using state context as outlined by
https://develop.sentry.dev/sdk/event-payloads/contexts/#state-context
More context here: https://github.com/getsentry/sentry-javascript/issues/5430#issuecomment-1195882729
cc @thanaen
=> feat(react): Use state context for Redux integration

packages/nextjs/src/config/types.ts, packages/nextjs/src/config/webpack.ts
As of version 7.0, our SDK publishes code which isn't natively compatible with older browsers (ones which can't handle ES6 or certain ES6+ features like object spread). If users control the build process of their apps, they can make sure that our SDK code is included in the transpilation they apply to their own code. In nextjs, however, the build process is controlled by the framework, and while users _can_ make modifications to it, they're modifying a webpack config they didn't create, making it a more challenging task.
Fortunately, our SDK can also modify the build process, and that's what this PR does. Nextjs does its transpiling using a loader (either `next-babel-loader` or `next-swc-loader`, depending on the nextjs version), controlled by entries in the `module.rules` section of the …
=> fix(nextjs): Add `transpileClientSDK` option

packages/nextjs/src/config/index.ts, packages/nextjs/src/config/types.ts, packages/nextjs/src/config/webpack.ts, packages/nextjs/test/config.test.ts
_h/t to @mitchheddles for the research and [initial idea](https://github.com/getsentry/sentry-javascript/pull/5456) - thanks!_
As of https://github.com/vercel/next.js/pull/38498, nextjs now warns (voluminously) if the config exported from `next.config.js` contains properties it doesn't recognize, including the `sentry` property we've been having people use to do things like [disable the webpack plugin](https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/#disable-sentrywebpackplugin). In order to prevent these warnings, the final config returned from `withSentryConfig` must not have such a property, so this deletes the property from the `userNextConfig` object before returning it. 
If we were to stop there, the warning would be gone, but so would the data …
=> fix(nextjs): Move `userNextConfig.sentry` to closure

packages/remix/test/integration/app/routes/capture-exception.tsx, packages/remix/test/integration/app/routes/capture-message.tsx, packages/remix/test/integration/app/routes/error-boundary-capture/$id.tsx, packages/remix/test/integration/app/routes/manual-tracing/$id.tsx, packages/remix/test/integration/test/client/capture-exception.test.ts, packages/remix/test/integration/test/client/capture-message.test.ts, packages/remix/test/integration/test/client/errorboundary.test.ts, packages/remix/test/integration/test/client/manualtracing.test.ts, packages/remix/test/integration/test/client/meta-tags.test.ts
Adds the initial set of client-side integration tests for Remix SDK. 
Ref: #4894
Covers: 
These tests are quite basic, and I haven't checked any edge cases, as they are covered by browser SDK's integration or unit tests.
=> test(remix): Add client-side integration tests.

packages/nextjs/test/integration/package.json
Hard-pins `@types/react` to version `17.0.47` (`@types/react-dom` to version `17.0.17`)  because the latest patch (`@types/react@17.0.48`) caused our NextJs Integration tests to fail. 
Caused by: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61457
=> chore(nextjs): pin @types/react version to fix integration tests

packages/node-integration-tests/suites/express/tracing/server.ts, packages/node-integration-tests/suites/express/tracing/test.ts, packages/tracing/src/integrations/node/express.ts
This PR makes our URL parameterization for Express (introduced in #5450) compatible with RegEx-defined routes.
Previously, as reported in #5481, our parameterization logic would cause a crash because instead of a string, the matched route would be of type `RegExp`. This PR adjusts our logic so that we detect if we get a matched string our regex. 
In the latter case, we also append a `'/'` to the reconstructed partial route name so that the regex is closed.
Generally, with this approach, regex routes' transaction names should be identical to what they were before #5450 (with the exception of child routes that are parameterized now). 
fixes #5481
=> fix(node): Adjust Express URL parameterization for RegEx routes

packages/tracing/src/transaction.ts, packages/tracing/test/span.test.ts
This PR changes our formatting logic of the `sample_rate` value when the dynamic sampling context (DSC) is populated. Instead of using `Number.toLocaleString` with a bunch of options (which theoretically is supported by all browsers; but it turns out that IE11 doesn't support the `fullwide` locale we use), we now simply convert the number `toString` to do the job. Given that Relay now supports parsing the sample_rate from JSON format, we can drop our previous formatting logic. 
Deleted a test that's IMO no longer necessary, covering the conversion of exponential to decimal notation.
Fixes #5466
=> ref(tracing): Simplify sample_rate serialization for DSC

packages/nextjs/src/index.server.ts
In https://github.com/getsentry/sentry-javascript/pull/5445, a change was made to the way the global `RewriteFrames` helper value is handled. Specifically, setting the default value (using the `||` operator) was moved to the place where the value is set rather than where it's retrieved. But if something goes wrong and for whatever reason the value never gets set globally, it now causes errors when the value is later used, because it has nothing to default to.
This fixes that by restoring the default value to the old location, so that when it's used, it will never be undefined.
Fixes https://github.com/getsentry/sentry-javascript/issues/5478.
=> fix(nextjs): Add default `distDir` value back into `index.server.ts`

.github/ISSUE_TEMPLATE/bug.yml
In our bug template, we ask users for their SDK version and, if they're using a framework SDK (react, etc), the version of the framework. Users often misunderstand, however, and just provide the SDK version twice. This aims to clarify the distinction, by making three changes:
- Adding clarifying language to the Framework Version field description.
- Changing the placeholder example for the field to include the name of the framework, and a recent IRL version.
- Changing the placeholder example for the SDK field to be the current version, to further emphasize which one is which.
It also fixes two schema errors highlighted by the linter.
=> fix(dev): Clarify issue template framework field

packages/node/src/module.ts, packages/node/test/module.test.ts
This was causing https://github.com/getsentry/sentry-electron/issues/503
It looks like this was never handled correctly and we don't CI test on Windows so this was never noticed!
=> fix(node): Correctly handle Windows paths when resolving module name

packages/node/src/handlers.ts, packages/node/test/handlers.test.ts
Currently, our `TracingHandler` always starts a transaction, whether or not tracing is enabled. It also traces `OPTIONS` and `HEAD` requests, which it shouldn't. This fixes both of those problems by checking both the current client's options (for tracing enablement) and the incoming request's method before starting a transaction.
=> fix(node): Add conditions to `TracingHanlder.startTransaction`

packages/node/src/integrations/linkederrors.ts
This patch brings back a check for `self._handler` in the global event processor of the LinkedErrors integration for Node. 
The check was removed in #4902 but apparently it is still necessary.
fixes #5493
=> fix(node): Ensure that `self._handler` exists before calling it in LinkedErrors

packages/node-integration-tests/suites/express/tracing/server.ts, packages/node-integration-tests/suites/express/tracing/test.ts, packages/tracing/src/integrations/node/express.ts
This PR fixes an error thrown from our Node SDK that  when our Express router parameterization logic (introduced in #5450) would try to parameterize a route consisting of an array of paths (which could be strings or RegExes). 
Previously, before #5450, the transaction name for a route such as
```js
app.get(['/test/array1', /\/test\/array[2-9]/], (_req, res) => {});
```
would be `GET /test/array1,/\/test\/array[2-9]/`. This is because internally, express does not care about which item in the array matched successfully. Express simply combines all items into one regex and matches the incoming path against this regex. It then stores the whole, concatenated array as the matched route.
While it might be worth revisiting our transaction name strategy for array routes at a later time, this is …
=> fix(node): Adjust Express URL parameterization for array routes

packages/tracing/src/integrations/node/express.ts
This PR hotfixes a problem in our router instrumentation introduced in #5450 which would cause Express 5 Node apps to crash on startup. Because the internals of Express 5 (which is still in beta) have changed quite a bit compared to Express 4, there is unfortunately no quick way of supporting the new version in our current router instrumentation. 
Therefore, this PR simply checks if the router we retrieve from Express 4 apps (which we get from `app._router`) exists. In case it does, we can patch it; in case it doesn't, we know that the integration is either used with Express 3 or 5. In both cases, we early return and do not patch the router.
We can revisit adding proper support for early URL parameterization of Express 5 apps but for now, this PR will unblock Express 5 users by skipping …
=> fix(node): Check if router exists before it is instrumented

CHANGELOG.md
Add a few entries that made it into 7.8.1 after we merged #5488
=> meta: Update 7.8.1 changelog 

packages/browser/src/stack-parsers.ts, packages/browser/test/unit/tracekit/firefox.test.ts, packages/integration-tests/suites/stacktraces/init.js, packages/integration-tests/suites/stacktraces/protocol_containing_fn_identifiers/subject.js, packages/integration-tests/suites/stacktraces/protocol_containing_fn_identifiers/test.ts, packages/integration-tests/suites/stacktraces/protocol_fn_identifiers/subject.js, packages/integration-tests/suites/stacktraces/protocol_fn_identifiers/test.ts, packages/integration-tests/suites/stacktraces/regular_fn_identifiers/subject.js, packages/integration-tests/suites/stacktraces/regular_fn_identifiers/test.ts, packages/integration-tests/suites/stacktraces/template.hbs, packages/integration-tests/utils/fixtures.ts
Fixes: #4138
The original issue about `file` keyword also happens for everything in that group, such as `http`, `blob` and so on. And the problem originates from : `.*` between that group and `:`. It seems that `:` follows those keywords without anything in between, as far as I have seen from the tests.
Removing that from the regex solved the issue without breaking any tests other than `safari-extension` and `safari-web-extension`, which are special-cased [here](https://github.com/getsentry/sentry-javascript/blob/d2e0cc4d683364dc500a681631b5be7df40ffec6/packages/browser/src/stack-parsers.ts#L160), adding those two to the matching group also solved the issue of an extra `:` coming from [there](https://github.com/getsentry/sentry-javascript/blob/d2e0cc4d683364dc500a681631b5be7df40ffec6/packa …
=> fix(browser): Set `:` as a part of gecko protocol regex group.

packages/remix/src/utils/instrumentServer.ts, packages/remix/test/integration/test/server/loader.test.ts
This makes sure server side transactions are parameterized correctly in Remix.
We do this by matching the server routes the same way Remix does under the hood, by reconciling the routes and URL pathname - https://github.com/remix-run/remix/blob/97999d02493e8114c39d48b76944069d58526e8d/packages/remix-server-runtime/server.ts#L36
Copied over a bunch of code from Remix to make this happen (and attributed accordingly).
=> fix(remix): Paramaterize server side transactions

packages/nextjs/src/config/index.ts, packages/nextjs/src/config/types.ts, packages/nextjs/src/config/webpack.ts, packages/nextjs/test/config.test.ts
This simplifies the `NextConfigObject` type in the nextjs SDK, to enable future work. Key changes:
- Removed index signature.
- Added missing `basePath` and `publicRuntimeConfig` properties.
- Made all properties optional. (This allowed for removal of the `Partial` annotation everywhere the type was used.)
- Clarified variable names in `config/index.ts` to better reflect their types.
=> ref(nextjs): Simplify `NextConfigObject` type

packages/remix/src/utils/instrumentServer.ts, packages/remix/test/integration/app/root.tsx, packages/remix/test/integration/test/client/meta-tags.test.ts
Fixes: #5490 
We are currently wrapping [`meta` functions](https://remix.run/docs/en/v1/api/conventions#meta) to create `sentry-trace` and `baggage` `<meta>` tags in the server-side rendered HTML.
It all seems convenient to use that facility (not bothering users to configure anything through the whole process), but turns out it's breaking the hydration. While on React 17, it's just a warning (and `<meta>` tags are still available at the end). On React 18, hydration logic fails and falls back to client-side rendering. 
The problem is that the HTML template for hydration is generated on build time, and uses the `meta` functions before we wrap them. And when we finally wrap it on initial runtime (we are wrapping `createRequestHandler`), the updated template doesn't match.
But we also have …
=> fix(remix): Provide `sentry-trace` and `baggage` via root loader.

packages/react/src/reactrouterv6.tsx, packages/react/test/reactrouterv6.test.tsx, packages/tracing/src/integrations/node/express.ts, packages/utils/src/index.ts, packages/utils/src/misc.ts, packages/utils/src/requestdata.ts, packages/utils/src/url.ts, packages/utils/test/misc.test.ts, packages/utils/test/url.test.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/5513
Make sure paramaterization occurs in scenarios where the full path is not available after all the branches are walked. In those scenarios, we have to construct the paramaterized name based on the previous branches that were analyzed.
This patch also creates a new file in `@sentry/utils` - `url.ts`, where we store some url / string related utils. This was made so that the react package would get access to the `getNumberOfUrlSegments` util.
=> fix(react): Fix React Router v6 paramaterization

packages/browser/src/stack-parsers.ts, packages/browser/test/unit/tracekit/chromium.test.ts
=> fix(browser): Parse Chrome stack frames without full paths

packages/node/test/stacktrace.test.ts, packages/utils/src/stacktrace.ts
Closes #5151
So the regex doesn't just keep growing in complexity, this change drops the ability to parse stack frames that don't have column numbers. It's my understanding that modern versions of v8/node always have column numbers and this was left over for legacy support.
=> fix(node): Handle colons in stack trace paths

packages/nextjs/src/config/index.ts, packages/nextjs/src/config/types.ts, packages/nextjs/src/config/webpack.ts, packages/nextjs/test/config.test.ts
In the process of working simultaneously on both https://github.com/getsentry/sentry-javascript/pull/5472 (which adds the `sentry.transpileClientSDK` option to `next.config.js`) and https://github.com/getsentry/sentry-javascript/pull/5473 (which moves the `sentry` options object from `next.config.js` to a new location halfway through the build process, in order to prevent nextjs from throwing warnings), I missed their overlap. As a result, the `transpileClientSDK` option is still currently being retrieved from the old, pre-move location, even though said retrieval happens in the second half of the build, after the move. (Unsurprisingly, it's therefore always undefined, rendering it useless).
This fixes that by pulling it from the new, correct location instead. It also adjusts our types so …
=> fix(nextjs): Pull `transpileClientSDK` option from correct location

packages/nextjs/test/integration/test/utils/server.js, packages/node-integration-tests/suites/tracing/tracePropagationTargets/scenario.ts, packages/node-integration-tests/suites/tracing/tracePropagationTargets/test.ts, packages/node-integration-tests/utils/index.ts, packages/node/src/integrations/http.ts, packages/node/src/types.ts, packages/node/test/integrations/http.test.ts, packages/types/src/index.ts, packages/types/src/options.ts, packages/types/src/tracing.ts
This PR adds the `tracePropagationTargets` option as outlined in https://github.com/getsentry/sentry-javascript/issues/5403,  https://github.com/getsentry/develop/issues/636, and [DACI](https://www.notion.so/sentry/DACI-Control-Sending-Trace-Data-63fd04ea885443ee99514c15a1e91499) (internal)  to the node SDK init options.
The `tracePropagationTargets` option can be used to control to which request the SDK should attach trace data (at the time of writing via `sentry-trace` and `baggage` headers).
Its behavior (at least for node) is as follows: If not provided, the SDK will attach tracing data to *all* outgoing requests. If provided, the SDK will only attach trace data when the request's URL matches one of the items in the `tracePropagationTargets` array.
Resolves …
=> feat(node): Add `tracePropagationTargets` option

packages/browser/test/unit/tracekit/chromium.test.ts, packages/utils/src/stacktrace.ts
Fixes #5459
I did try and solve this via the Chrome regex but found that the 2nd line (`(error: https://s1.sentry-cdn.com/_static/dist/sentry/chunks/app_bootstrap_initializeLocale_tsx.abcdefg.js)`) was picked up by the gecko parser. This change just strips the `(error: *)` wrapper from all lines before parsing proper. Line 2 is still parsed by the gecko parser but the resulting frame seems sensible even if it doesn't contain much useful info. 
The following stack string:
```
ChunkLoadError: Loading chunk app_bootstrap_initializeLocale_tsx failed.
(error: https://s1.sentry-cdn.com/_static/dist/sentry/chunks/app_bootstrap_initializeLocale_tsx.abcdefg.js)
at (error: (/_static/dist/sentry/chunks/app_bootstrap_initializeLocale_tsx.abcdefg.js))
at key(webpack/runtime/jsonp chunk loading:27:18) …
```
=> fix(browser): Strip webpack wrapping from stack frames

rollup/plugins/bundlePlugins.js
The `localforage` library (used in offline integration) has some internal fields with a leading underscore (e.g. `_initStorage`). In our building process, we allow terser to mangle fields with a leading underscore to reduce bundle size when using classes with private fields. This causes internal breakage within the `localforage` package and throwing a `"Error: Custom driver not compliant"` error.
This PR marks some localforage-internal fields as reserved so they don't get mangled. The fields are taken from the [localforage docs](https://localforage.github.io/localForage/) by searching the page for "_".
Fixes https://github.com/getsentry/sentry-javascript/issues/5527
=> fix(integration): Don't mangle localforage internals

packages/nextjs/package.json, packages/nextjs/rollup.npm.config.js, packages/nextjs/src/config/loaders/ast.ts, packages/nextjs/src/config/loaders/dataFetchersLoader.ts, packages/nextjs/src/config/loaders/index.ts, packages/nextjs/src/config/loaders/parsers.ts, packages/nextjs/src/config/loaders/prefixLoader.ts, packages/nextjs/src/config/loaders/types.ts, packages/nextjs/src/config/templates/dataFetchersLoaderTemplate.ts, packages/nextjs/src/config/types.ts, packages/nextjs/src/config/webpack.ts, packages/nextjs/src/config/wrappers/index.ts, packages/nextjs/src/config/wrappers/types.ts, packages/nextjs/src/config/wrappers/withSentryGSPaths.ts, packages/nextjs/src/config/wrappers/withSentryGSProps.ts, packages/nextjs/src/config/wrappers/withSentryGSSP.ts, packages/nextjs/src/config/wrappers/wrapperUtils.ts, packages/nextjs/src/index.server.ts, packages/nextjs/src/utils/isESM.ts, packages/nextjs/test/utils/isESM.test.ts, packages/nextjs/tsconfig.types.json, yarn.lock
This adds wrapping of the nextjs server-side data-fetching methods (`getStaticPaths`, `getStaticProps`, and `getServerSideProps`) to the webpack config changes we make during app build. Eventually, this will let us create spans for them, use them to improve route parameterization, and trace requests which aren't currently getting traced on Vercel-deployed nextjs apps. For the moment, though, all the wrappers do is call the functions they wrap, in order to separate out the wrapping into its own PR.
Notes:
-  For the moment, in order to allow us to iterate on it without fear of breaking people's apps, this feature is gated behind the `sentry.autoWrapDataFetchers` flag in `next.config.js`.
- To do the wrapping, we scan each page's AST for references to each of the three functions. If a given …
=> ref(nextjs): Wrap server-side data-fetching methods during build

.github/workflows/build.yml, packages/ember/config/ember-try.js
It is running the scenarios in sequence, running them in parallel might speed up the builds a bit.
=> fix(ember): Speed up ember scenarios

packages/nextjs/src/config/types.ts, packages/nextjs/src/config/webpack.ts
This nests the new `autoWrapDataFetchers` option in `next.config.js` in an `experiments` object, to make it clear that it's not necessarily a stable option yet.
=> ref(nextjs): Move `autoWrapDataFetchers` option into `experiments` object

packages/remix/README.md
While working on #5544, I noticed that the badges in our Remix SDK README.md still link to the NextJS NPM package stats. This PR changes the badge links to the Remix SDK NPM badges to get more accurate stats. Tested it locally and it seems to work.
=> chore(remix): Update badge links in Remix README

packages/node-integration-tests/package.json, packages/node-integration-tests/utils/index.ts, packages/remix/test/integration/app/entry.server.tsx, packages/remix/test/integration/app/root.tsx, packages/remix/test/integration/app/routes/action-json-response/$id.tsx, packages/remix/test/integration/app/routes/loader-json-response/$id.tsx, packages/remix/test/integration/test/server/action.test.ts, packages/remix/test/integration/test/server/loader.test.ts, packages/remix/tsconfig.json, yarn.lock
Adds a basic set of tests to ensure `loader`, `action` and `documentRequest` functions are properly instrumented.
Also, switches `node-integration-test` utilities to use `axios` to simulate requests, instead of `http` package, to easily switch between `post` and `get` requests.
=> test(remix): Add server-side instrumentation integration tests.

packages/svelte/package.json, packages/svelte/src/index.ts, packages/svelte/src/sdk.ts, packages/svelte/test/sdk.test.ts
This PR adds basic error and performance monitoring to the new Svelte SDK. For the moment, we only wrap the Browser SDK and overwrite its default config with the Svelte SDK metadata.
Additionally, this PR adds a small unit test to ensure that SDK name and version are set correctly.
ref: #5520
=> feat(svelte): Add Error and Performance Instrumentation from Browser SDK

packages/react/src/redux.ts, packages/react/test/redux.test.ts
Fixes: https://github.com/getsentry/sentry-javascript/issues/5536
ref: https://github.com/getsentry/sentry-javascript/pull/5471
It turns out I misunderstood the state spec for state context. This fixes the state setter to be correct - we do need a nested object for it to render correctly in Sentry. See the Sentry code here: https://github.com/getsentry/sentry/blob/master/static/app/components/events/contexts/state.tsx
@jennmueng do you think this is the correct approach? We can also try to adopt a different schema.
=> fix(react): Set redux state context properly

.vscode/settings.json, packages/react/src/profiler.tsx, packages/react/test/profiler.test.tsx
This PR gives the React SDK the ability to track the duration of `ui.react.update` spans by calling `startChild` within the `shouldComponentUpdate` lifecycle method, and then calling `finish` in `componentDidUpdate`
This will allow Performance users to see in their transactions how long it is taking their components to update
=> feat(react): Track duration of React component updates

packages/remix/test/integration/tsconfig.json
Switch to using `jsx: "react"` - which is what the jsx field expects.
=> chore(remix): Update integration test tsconfig

packages/svelte/package.json
This PR removes the `"private": "true"` field from the Svelte SDK's `package.json` to get it ready for the first public alpha release
ref: #5520
=> chore(svelte): Remove private field from package.json

.craft.yml
This PR adds an entry to `craft.yml` in the release registry section. 
ref: #5520
=> chore(svelte): Add entry for Svelte SDK in craft.yml

CHANGELOG.md
Decided against including https://github.com/getsentry/sentry-javascript/pull/5529 in this release due to test flakyness, can do it in the next release.
=> meta: Update 7.10.0 CHANGELOG

.craft.yml
Let's tmp remove the Svelte SDK as a target to repair RR 7.10.0 entries for the other SDKs and then revert this
=> chore(svelte): Temporarily remove Svelte SDK as a Release Registry target

packages/nextjs/src/config/loaders/ast.ts, packages/nextjs/src/config/loaders/dataFetchersLoader.ts, packages/nextjs/src/config/loaders/parser.ts, packages/nextjs/test/config/ast.test.ts
The changes the experimental data-fetching-function-wrapping loader to always use the tsx parser, as it's capable of parsing jsx as well. This in turn allows us to simplify the `makeAST` function.
=> ref(nextjs): Always use tsx parser in experimental function-wrapping loader

packages/remix/src/utils/instrumentServer.ts, packages/remix/test/integration/test/server/action.test.ts, packages/remix/test/integration/test/server/loader.test.ts
Pass down an ID for better description of remix spans
=> feat(remix): Add route ID to remix routes

packages/eslint-config-sdk/src/index.js
It's debatable whether this should be enabled at all, but at the very least we should relax the conditions that don't affect bundle size, such as blank lines and comments since it leads towards either disabling the rule entirely (as you can see in a lot of sdk files) or people not writing comments (again, not ideal).
=> ref(eslint): Fix max lines eslint rule

packages/core/src/baseclient.ts, packages/core/test/lib/base.test.ts, packages/nextjs/test/index.client.test.ts, packages/nextjs/test/index.server.test.ts, packages/utils/src/error.ts, packages/utils/src/logger.ts
We use `SentryError`s in our event processing and sending pipeline both when something has gone legitimately wrong and when we just want to bail on a promise chain. In all cases, however, we log both the message and the stack, at a warning log level, which both clutters the logs and unnecessarily alarms anyone who has logging on.
This fixes that by adding a `logLevel` property to the `SentryError` class, which can be read before we log to the console. The default behavior remains the same (log the full error, using `logger.warn`), but now we have the option of passing `'log'` as a second constructor parameter, in order to mark a given `SentryError` as something which should only be `logger.log`ged and whose stack should be suppressed.
(To answer the inevitable _Why now?_ question, it's …
=> fix(core): Suppress stack when `SentryError` isn't an error

packages/tracing/src/browser/browsertracing.ts, packages/tracing/test/browser/browsertracing.test.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/5393
Allow for users to set an empty array as `tracingOrigins` option if they do not want to attach outgoing headers to any request. Previously we would just set the default tracing origins if users supplied an empty array.
This is technically a breaking change - but moves us toward the correct behaviour so I don't mind rolling this out in a minor. Thoughts?
=> feat(tracing): Allow empty array as `tracingOrigins`

packages/remix/src/utils/instrumentServer.ts, packages/remix/src/utils/serverAdapters/express.ts, packages/remix/test/integration/test/server/loader.test.ts
https://github.com/getsentry/sentry-javascript/pull/5570 merged, but the tests were being very flaky. I took another look and figured out that we only needed to wrap our instrumentation with a domain once. Wrapping twice (for both express and built-in) was causing problems. In addition, I moved the wrapping down to the request handling phase, which makes the behaviour more correct.
This supercedes https://github.com/getsentry/sentry-javascript/pull/5589
=> fix(remix): Wrap domains properly on instrumentServer

packages/nextjs/src/config/loaders/dataFetchersLoader.ts, packages/nextjs/src/config/templates/dataFetchersLoaderTemplate.ts, packages/nextjs/src/config/webpack.ts, packages/nextjs/src/config/wrappers/withSentryGetServerSideProps.ts, packages/nextjs/src/config/wrappers/withSentryGetStaticProps.ts, packages/nextjs/src/config/wrappers/wrapperUtils.ts
This adds span creation and route parameterization to the experimental `getStaticProps` and `getServerSideProps` wrappers. In order to do the parameterization, we store the parameterized route( which is the same as the filepath of the page file) as a global variable in the code we add using the `dataFetchersLoader` and then pass it to the wrappers, which then replace the name of the active transaction with the parameterized route we've stored. It also adds basic error-capturing to the wrappers.
Open issues/questions (not solved by this PR):
- Because of prefetching, revalidation of static pages, and the like, the data fetching functions can run in the background, during handling of a route different from their own. (For example, if page A has a nextjs `Link` component pointing to page B, …
=> feat(nextjs): Add spans and route parameterization in data fetching wrappers

CHANGELOG.md
Blocked on ~https://github.com/getsentry/sentry-javascript/pull/5564~, ~https://github.com/getsentry/sentry-javascript/pull/5570~, ~https://github.com/getsentry/sentry-javascript/pull/5587~ and ~https://github.com/getsentry/sentry-javascript/pull/5590~
=> meta: CHANGELOG for 7.11.0

CHANGELOG.md
Releases https://github.com/getsentry/sentry-javascript/pull/5595, which fixes server side transactions for remix not working properly.
=> meta: 7.11.1 CHANGELOG

packages/integration-tests/suites/tracing/browsertracing/long-tasks-enabled/test.ts, packages/tracing/src/browser/metrics/index.ts
Update the `ui.long-task` span description to explain what is happening while the span is occuring.
https://developer.mozilla.org/en-US/docs/Web/API/Long_Tasks_API
=> ref(tracing): Update long task description

packages/serverless/src/gcpfunction/events.ts
Fixes: https://github.com/getsentry/sentry-javascript/issues/5607
This PR adds a check if a callback is provided to the GCP Events handler function before calling it. Additionally, it adjusts the types of the function so we would have caught this.
=> fix(serverless): Check for existence of callback in GCP event handler before calling

packages/nextjs/package.json, packages/nextjs/rollup.npm.config.js, packages/nextjs/src/config/loaders/index.ts, packages/nextjs/src/config/loaders/proxyLoader.ts, packages/nextjs/src/config/loaders/rollup.ts, packages/nextjs/src/config/templates/proxyLoaderTemplate.ts, packages/nextjs/src/config/webpack.ts, packages/nextjs/test/run-integration-tests.sh, packages/nextjs/tsconfig.types.json, rollup/plugins/npmPlugins.js, yarn.lock
This changes the experimental auto-wrapping feature to use a templated proxy module for all wrapping. (Previously, the wrapping was done using a different mix of code parsing, AST manipulation, proxying, templating, and string concatenation for each function.) Not only should this be easier to reason about and maintain (because it's one unified method of wrapping), it also solves a number of the disadvantages inherent in various parts of the previous approach. Specifically, using a template for everything rather than storing code as strings lets us take advantage of linting and syntax highlighting, and using a proxy loader rather than dealing with the AST directly puts the onus of handling syntax variations and edge cases on tools which are actually designed for that purpose.
At a high …
=> ref(nextjs): Use proxy loader for wrapping all data-fetching functions

packages/nextjs/src/config/loaders/dataFetchersLoader.ts, packages/nextjs/src/config/templates/proxyLoaderTemplate.ts, packages/nextjs/src/config/wrappers/index.ts, packages/nextjs/src/config/wrappers/withSentryGetServerSideProps.ts, packages/nextjs/src/config/wrappers/withSentryServerSideAppGetInitialProps.ts, packages/nextjs/src/config/wrappers/withSentryServerSideDocumentGetInitialProps.ts, packages/nextjs/src/config/wrappers/withSentryServerSideErrorGetInitialProps.ts, packages/nextjs/src/config/wrappers/withSentryServerSideGetInitialProps.ts, packages/nextjs/src/config/wrappers/wrapperUtils.ts, packages/nextjs/src/index.server.ts
Ref: https://github.com/getsentry/sentry-javascript/issues/5505
This PR adds wrappers for the "special page's" (`_app`, `_document` and `error`) `getInitialProps`. Luckily we have access to the parameterized route in `getInitialProps` so we can reuse the logic introduced in https://github.com/getsentry/sentry-javascript/pull/5593.
Allows for transactions like the following:
And correctly captures exceptions when different errors are thrown in different methods!:
=> feat(nextjs): Instrument server-side `getInitialProps` of `_app`, `_document` and `_error`

CHANGELOG.md, packages/nextjs/src/config/types.ts, packages/nextjs/src/config/webpack.ts, packages/nextjs/test/config/webpack/constructWebpackConfig.test.ts, packages/nextjs/test/config/webpack/sentryWebpackPlugin.test.ts
When someone adds our Vercel integration, it only adds sentry-cli-relevant environment variables to production deployments. This can cause non-production deployments to fail, because when the webpack loader tries to run, it doesn't find the information it needs. That said, there's a reason we only set the env variables for prod - we really shouldn't be creating releases or uploading sourcemaps for dev or preview deployments in any case. 
This adds an environment check for vercel deployments (using [the `VERCEL_ENV` env variable](https://vercel.com/docs/concepts/projects/environment-variables#system-environment-variables)), and only enables the webpack plugin if the environment is `production`. To give users a way to override this, setting `disableClientWebpackPlugin` or …
=> fix(nextjs): Don't run webpack plugin on non-prod Vercel deployments

packages/integration-tests/suites/tracing/metrics/web-vitals-fid/test.ts, packages/integration-tests/suites/tracing/metrics/web-vitals-fp-fcp/test.ts, packages/integration-tests/suites/tracing/metrics/web-vitals-lcp/test.ts, packages/tracing/src/browser/metrics/index.ts
Ref https://github.com/getsentry/sentry/pull/38023
fixes https://getsentry.atlassian.net/browse/PERF-1700
https://www.notion.so/sentry/Stop-sending-mark-X-measurements-from-JavaScript-SDK-66d26d45e860419280ec853377195305
Currently the JS SDK sends extra measurements though, specifically `mark.lcp`, `mark.fid`, `mark.fp`, `mark.fcp`. This is done because these measurements are being used in the Sentry front-end UI to draw these lines:
These measurements should be removed, as they count toward a user’s custom measurement quota - hence we would be reducing the amount of custom measurements they can send and use because the SDK is setting them automatically. In addition, there is no way these measurements are ever going to be indexed, so we can’t move them to be built-in.
To remove these …
=> ref(tracing): Remove mark measurements

packages/nextjs/src/performance/client.ts, packages/utils/src/url.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/5641
Currently we are not starting transactions in Next.js when navigating from one page to another, but within the same route (eg. from `/users/42` to `/users/1337`, both are on the same route `/users/[id]`).
This PR fixes this by starting a transaction for those navigations by looking at the window pathname instead. (See code changes for reason why we're not starting transactions when *just* the query string changes)
=> fix(nextjs): Start navigation transactions on same-route navigations

packages/browser/test/integration/common/utils.js, packages/utils/src/supports.ts
In Deno `@sentry/browser` is almost usable, but the check `new Request('')` fails silently because Deno throws a `TypeError: invalid URL` that goes to a catch block. This changes the Request call to include a valid URL `http://www.example.com` so that `@sentry/browser` can be imported in Deno without this issue.
=> fix(browser): update Request checks to be valid in Deno

packages/node/src/handlers.ts
According to the Node.js docs, domain errors are equivalent to an uncaught exception and therefore should not really be caught except to do some cleanup and then exit the process. Not doing so causes the process to potentially linger without being able to handle any request. Currently, the behavior is also erroneous because `next` can end up be called twice. This issue was discovered via fastify/middie#158.
Fixes #1922.
=> fix(node): Avoid catching domain errors in request handler

CHANGELOG.md, packages/integrations/src/rewriteframes.ts, packages/integrations/test/rewriteframes.test.ts
This PR avoids adding an empty stack trace when a stack trace is not defined.
By doing that, you'll no longer see the following error message at Sentry:
Fixes #5609 and potentially fixes https://github.com/getsentry/sentry-react-native/issues/2429 
=> fix(integrations): Don't add empty stack trace in `RewriteFrames`

packages/utils/src/baggage.ts
Some small adjustments to `parseBaggageSetMutability` docstrings.
=> chore(utils): Update `parseBaggageSetMutability` docstring

.eslintrc.js, .github/workflows/build.yml, .vscode/launch.json, CHANGELOG.md, jest/jest.config.js, packages/core/src/transports/base.ts, packages/gatsby/gatsby-browser.js, packages/gatsby/test/gatsby-browser.test.ts, packages/hub/src/scope.ts, packages/hub/test/exports.test.ts, packages/integrations/rollup.bundle.config.js, packages/nextjs/src/config/types.ts, packages/nextjs/src/config/webpack.ts, packages/nextjs/test/run-integration-tests.sh, packages/node/src/integrations/onuncaughtexception.ts, packages/node/test/client.test.ts, packages/serverless/src/awslambda.ts, packages/tracing/src/index.bundle.ts, packages/types/src/client.ts, packages/utils/README.md, packages/utils/src/is.ts, packages/utils/src/normalize.ts, packages/utils/src/promisebuffer.ts, packages/utils/test/normalize.test.ts, packages/utils/test/syncpromise.test.ts, rollup/plugins/bundlePlugins.js, rollup/plugins/npmPlugins.js, scripts/verify-packages-versions.js
This is just a whole bunch of comment and docstring fixes I've had piled up - typo fixes, grammar fixes, wording clarifications, etc. No behavior changes.
=> chore(various): Fix comments and docstrings

packages/nextjs/package.json, packages/nextjs/src/config/webpack.ts
This adds a warning during nextjs app build (both in prod and dev) letting folks know that by default (for now), the sourcemaps we create can be seen by browser devtools.
In conjunction with https://github.com/getsentry/sentry-wizard/pull/188, https://github.com/getsentry/sentry-docs/pull/5464, and https://github.com/vercel/next.js/pull/40079, this is the first step in addressing the concerns raised in https://github.com/getsentry/sentry-javascript/issues/4489. See [here](https://github.com/getsentry/sentry-javascript/issues/4489#issuecomment-1231137629) for more details.
Notes:
- The function doing the warning includes both the current warning and one for use in v8 and beyond (currently commented out), telling people they no longer need to set `hideSourceMaps` to `true` (because by that …
=> ref(nextjs): Add warning about non-hidden sourcemaps

packages/svelte/package.json, packages/svelte/rollup.npm.config.js, packages/svelte/src/constants.ts, packages/svelte/src/index.ts, packages/svelte/src/performance.ts, packages/svelte/src/preprocessors.ts, packages/svelte/src/types.ts, packages/svelte/test/preprocessors.test.ts, yarn.lock
This PR introduces component tracking to the Sentry Svelte SDK. I'm currently trying to implement an approach for users that is simple and only requires minimal configuration on their end. The idea is to let them specify once if and which  components they actually want to track (like we do it in Vue for example). 
Because Svelte components are compiled into plain JS at build time, we cannot reliably hook into a Svelte runtime or do similar approaches monkey patching approaches. What we can however do, is to hook into the component compilation by using an official Svelte compiler feature: [preprocessors](https://svelte.dev/docs#compile-time-svelte-preprocess). 
With this PR, we add a Svelte preprocessor that injects a function call (+ the necessary import) into the top of the `<script>` …
=> feat(svelte): Add Component Tracking

CHANGELOG.md
One `#` and our prepare release workflow won't pass...
(Or in other words, I should go home, apparently it was a long day...)
=> fix: Adjust changelog 7.12.0 heading level

packages/react/src/index.ts, packages/react/src/reactrouterv6.tsx, packages/react/test/reactrouterv6.test.tsx
Resolves: #5338 
This PR introduces `wrapUseRoutes` function, which can be used to patch [`useRoutes` hook](https://reactrouter.com/en/main/hooks/use-routes) of React Router 6.
Example usage:
```typescript
import {
createRoutesFromChildren,
matchRoutes,
useLocation,
useNavigationType,
useRoutes,
} from "react-router-dom";
import { wrapUseRoutes } from "@sentry/react";
import { useEffect } from "react";
Sentry.init({
dsn: "__DSN__",
new BrowserTracing({
routingInstrumentation: Sentry.reactRouterV6Instrumentation(
useEffect,
useLocation,
useNavigationType,
createRoutesFromChildren,
matchRoutes,
),
}),
],
});
const useSentryRoutes = wrapUseRoutes(useRoutes);
function App() {
return useSentryRoutes([
// ...
]);
}
ReactDOM.render(
<BrowserRouter>
<App /> …
```
=> feat(react): Support `useRoutes` hook of React Router 6.

packages/hub/src/scope.ts, packages/nextjs/src/config/webpack.ts, packages/tracing/src/integrations/node/apollo.ts, packages/utils/src/misc.ts, packages/utils/test/misc.test.ts, packages/vue/src/sdk.ts
In a number of places in our codebase, we have the pattern `const something = Array.isArray(somethingElse) ? somethingElse : [ somethingElse ];`, where we need something (which might already be an array) to be an array. 
This introduces a utility function, `arrayify`, which does that work for us, mostly because I just got tired of typing it. (As a bonus, it's slightly shorter and therefore might save a few bytes on bundle size.)
=> feat(utils): Add function for ensuring input is an array

packages/tracing/src/browser/browsertracing.ts, packages/utils/src/browser.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/5673
Prev similar incident https://github.com/getsentry/sentry-javascript/pull/4451
This PR removes the use of the `Element` DOM type from `@sentry/utils`, introduced with https://github.com/getsentry/sentry-javascript/pull/5594. This breaks `@sentry/node` users that use strict TS configs.
We have to cast the type to `any` to make sure it works in different environments, but we supply a generic argument so that users can specify what type of `Element` will be returned from `querySelector`.
=> fix(utils): Remove Element dom type

packages/node/src/integrations/context.ts
@AbhiPrasad sure was right about #5512 needing some integration tests!
I will do a PR to add integration tests but for now, this PR fixes two issues:
- A missing `typeof` which stops the node culture detection from working entirely
- The contexts are completely overwritten rather than merge any existing keys
=> fix(node): `contexts` cannot be overridden and `culture` never included

README.md, packages/browser/README.md, packages/core/README.md, packages/eslint-config-sdk/README.md, packages/hub/README.md, packages/integrations/README.md, packages/nextjs/README.md, packages/node/README.md, packages/remix/README.md, packages/svelte/README.md, packages/tracing/README.md, packages/types/README.md, packages/typescript/README.md, packages/utils/README.md, packages/wasm/README.md
https://getsentry.github.io/sentry-javascript/ is out of date, let's remove it so it doesn't confuse users.
ref https://github.com/getsentry/sentry-javascript/issues/3871 https://github.com/getsentry/sentry-javascript/issues/3980
=> chore: Remove typedoc from READMEs

packages/nextjs/src/utils/instrumentServer.ts
helps us get prepped for https://github.com/getsentry/sentry-javascript/issues/5679, related to https://github.com/getsentry/sentry-javascript/pull/5681 and https://github.com/getsentry/sentry-javascript/pull/5682
Please merge this in without me if I'm not available!
=> ref(nextjs): Consolidate to use single `setName` call

packages/angular/src/tracing.ts, packages/angular/test/tracing.test.ts
Remove usage `setMetadata` in favour of adding the source to `setName`
helps us get prepped for https://github.com/getsentry/sentry-javascript/issues/5679, related to https://github.com/getsentry/sentry-javascript/pull/5681
Please merge this in without me if I'm not available!
=> ref(angular): Consolidate to use single `setName` call

packages/react/src/reactrouter.tsx, packages/react/src/reactrouterv6.tsx, packages/react/test/reactrouterv4.test.tsx, packages/react/test/reactrouterv5.test.tsx, packages/react/test/reactrouterv6.test.tsx
Remove usage `setMetadata` in favour of adding the source to `setName`
helps us get prepped for https://github.com/getsentry/sentry-javascript/issues/5679
Please merge this in without me if I'm not available!
=> ref(react): Consolidate to use single `setName` call

CHANGELOG.md
We have a couple of key fixes to go out, notably #5675 and #5677, so I figured it's probably appropriate to cut a patch release here. There are some features, which may led to the argument that this should be a minor, but I can walk through them to justify the patch usage.
- feat(nextjs): Connect trace between data-fetching methods and pageload (#5655)
This is gated behind a flag, safe to ship in the patch
- feat(react): Support useRoutes hook of React Router 6 (#5624)
New feature, but just an add-on for existing route parameterization methods, nothing large so we can sneak it on
- feat(remix): Continue transaction from request headers (#5600)
It's remix, so I'm comfortable with including new features here
- feat(utils): Add function for ensuring input is an array (#5668)
utils is …
=> meta: CHANGELOG for 7.12.1

packages/tracing/src/hubextensions.ts, packages/tracing/test/hub.test.ts
Set the `transaction.metadata.transactionSampling.rate` field to 1 or 0 depending on `transaction.sampled` (if it is defined)
Fixes #5690
=> fix(tracing): Set sample rate in transaction metadata and DSC

packages/svelte/jest.config.js, packages/svelte/package.json, packages/svelte/test/components/Dummy.svelte, packages/svelte/test/performance.test.ts, scripts/test.ts, yarn.lock
This PR adds the [Svelte Testing Library](https://testing-library.com/docs/svelte-testing-library/intro) to the Svelte SDK. More specifically, two dev dependencies:
* `@testing-library/svelte` which lets us test Svelte components
* `svelte-jester` which is responsible to transform Svelte components to JS in Jest tests
The nice thing about this is that Svelte Testing Library offers us a way to simulate the rendering and mounting process of Svelte components. This means that we can properly test the `trackComponent` function without having to manually go in and simulate life cycle hooks calls. While in #5612, we added tests for the component tracking preprocessor, we didn't add tests for the actual tracking implementation. 
Therefore, this PR also adds a bunch of test for `trackComponent`. …
=> test(svelte): Add Svelte Testing Library and trackComponent tests

packages/browser/src/transports/fetch.ts, packages/browser/test/unit/transports/fetch.test.ts
While working on https://github.com/getsentry/sentry-javascript/pull/5676 I noticed some navigation transactions don't show up in Sentry. I found out that when navigating between pages, Chrome cancels any outgoing requests - including requests to Sentry.
Events not being sent because of a page navigation probably happens the most with navigation transactions, since we usually finish the transaction right before we navigate (finishing happens implicitly on navigation). To requests being cancelled, we can use `fetch`'s `keepalive` flag to keep outgoing requests alive, even when we're switching pages.
https://github.com/getsentry/sentry-javascript/issues/2547 has an excellent writeup on the pros and cons of this flag. In short:
- `keepalive` isn't supported by Firefox
- As per …
=> feat(browser): Use fetch `keepalive` flag

package.json
Remove the error message that comes with running `yarn`.
=> chore: Upgrade yarn to `1.22.19`

packages/node/src/client.ts, packages/node/src/eventbuilder.ts, packages/node/test/eventbuilders.test.ts
This PR makes use of the `normalizeDepth` init option when creating events from an unknown input. It potentially fixes #5687 where a user reported that calling `Sentry.captureException` with a deep custom object, the `normalizeDepth` isn't respected but the depth defaults to 3. 
Note: I'm not sure if this behaviour was intentional or if we have a bug. Opened this quick PR with an idea how to fix it. Since I'm gone for the next weeks, reviewer(s) please feel free to change, close or merge this PR! Was just a quick idea.
If we decide to go with this, we might want to apply the same fix to the Browser SDKs event builder.
=> fix(node): Use `normalizeDepth` when creating an event from unknown input

packages/browser/src/eventbuilder.ts, packages/browser/test/unit/eventbuilder.test.ts
Analogous change to https://github.com/getsentry/sentry-javascript/pull/5689
Raised by https://github.com/getsentry/sentry-javascript/pull/5689#issuecomment-1238699465
=> fix(browser): Use `normalizeDepth` option when creating an event from a plain object

packages/svelte/README.md
This PR bumps the SDK status to beta and adds a few links to the Svelte docs for source map generation and uploading
ref: https://github.com/getsentry/sentry-javascript/issues/5671
=> ref(svelte): Update README with beta note and improve source maps section

packages/node/src/integrations/modules.ts, packages/node/src/sdk.ts
Start adding module information to NodeJS events. This is important so we can start understanding what kind of packages people use, and better inform strategies around future integration development + opentelemetry.
=> feat(node): Add Modules integration to default integrations

packages/core/src/integration.ts, packages/core/test/lib/integration.test.ts
When the SDK is initialized, we set up a combination of default and user-provided integrations, controlled by two `Sentry.init()` options:
- `defaultIntegrations` - can be set to `false` to disable defaults
- `integrations` - can be an array of integrations (to be merged with the existing array of defaults) or a function `(defaults: Integration[]) => Integration[]` (to replace the entire array of defaults with a new array)
The first option works correctly, but the second has long had two bugs, both relating to how duplicates are handled. Specifically, when two instances of the same integration are present, the following two principles should (but don't) always hold: 1) a user-provided instance should always beat a default instance, and within that, 2) a more recent instance should always …
=> fix(core): Fix integration deduping

packages/nextjs/test/config/mocks.ts, packages/nextjs/test/integration/next.config.js, packages/nextjs/test/integration/next10.config.template, packages/nextjs/test/integration/next11.config.template
The warning added in https://github.com/getsentry/sentry-javascript/pull/5649 isn't relevant to our overall nextjs test suite. This therefore suppresses it in both unit and integration tests.
=> chore(nextjs): Suppress warning message about `hideSourceMaps` option in tests

packages/nextjs/src/index.client.ts, packages/nextjs/src/index.server.ts, packages/nextjs/src/utils/userIntegrations.ts, packages/nextjs/test/index.client.test.ts, packages/nextjs/test/index.server.test.ts, packages/nextjs/test/utils/userIntegrations.test.ts
While working on adding a `RequestData` integration to the nextjs SDK, I found that the functions we use to set default integrations in the SDK were a little hard to parse, primarily because of a docstring that didn't make any sense and vague and/or slightly inaccurate function and variable names. We also have been making things more complicated than necessary, in that
a) The existing functions in `utils/userIntegrations.ts` use the given default integration instance if no user instance is found. Meanwhile, the two index files do the same in the case that no user integrations are provided at all. But those two conditions aren't logically independent, so by simply providing a default (empty) value for the second case, we can rely on the first check to ensure the default instance is used. …
=> ref(nextjs): Simplify adding default integrations when initializing SDK

packages/remix/package.json, packages/remix/test/integration/test/server/action.test.ts, packages/remix/test/integration/test/server/loader.test.ts
Related: https://github.com/getsentry/sentry-javascript/pull/5650
~Updated Remix server-side SDK to use the message of the thrown error instead of the whole object, when the error is not a response.~
Limited maximum stacktrace length for Remix server-side integration tests.
Also updated tests to filter by type and separate consecutive multi-type envelopes, and not to trust the capturing order.
=> fix(tests): Limit Remix server integration test stacktrace length.

packages/node-integration-tests/jest.config.js, packages/node-integration-tests/jest.setup.js, packages/node-integration-tests/package.json, packages/node-integration-tests/utils/index.ts
While working on baggage changes and running the Node.js integration tests, I noticed that integrations were set up N times where N is the number of test suites there were.
I believe we do not want to share global context (i.e. SDK inits) across integration tests since that is not really simulating a real-world scenario.
By removing the `--runInBand` we will not run the tests in a single process anymore but in multiple worker processes. This is a bit slower so I also increased the test timeout. I raised it by quite a lot, hoping to reduce test flakes in the future.
Also, there was some weird race condition/deadlock in the logic where we get a free port on the machine I aim to fix with this PR. TBH I don't quite know why it works but it seems to improve things when running locally.
=> test: Fix node integration tests sharing SDK initializations

packages/nextjs/test/integration/test/server/tracing200.js, packages/nextjs/test/integration/test/server/tracing500.js, packages/nextjs/test/integration/test/server/tracingHttp.js, packages/nextjs/test/integration/test/server/tracingServerGetInitialProps.js, packages/nextjs/test/integration/test/server/tracingServerGetServerSideProps.js, packages/node-integration-tests/suites/express/tracing/test.ts, packages/remix/test/integration/test/server/loader.test.ts, packages/tracing/src/transaction.ts, packages/tracing/test/span.test.ts, packages/types/src/event.ts, packages/types/src/index.ts, packages/types/src/transaction.ts
Part of https://github.com/getsentry/sentry-javascript/issues/5679
This PR adds types for the `TransactionNameChange` interface:
```ts
export interface TransactionInfo {
source: TransactionSource;
changes: TransactionNameChange[];
propagations: number;
};
/**
* Object representing metadata about when a transaction name was changed.
*/
export interface TransactionNameChange {
/**
* Unix timestamp when the name was changed. Same type as the start and
* end timestamps of a transaction and span.
*/
timestamp: number;
/** New source applied for transaction name change */
source: TransactionSource;
/** Number of propagations since start of transaction */
propagations: number;
}
```
`TransactionNameChange` is an object that describes a point in time when a transaction name was changed. It …
=> feat(types): Add `TransactionNameChange` interface

.yarnrc
By default, Node errors [only include the top 10 stackframes](https://nodejs.org/api/errors.html#errorstacktracelimit). Given the number of frames taken up by internal node code (especially when async functions are involved), this very often means that frames which might actually tell us something are cut off.
This solves that problem by removing the 10-frame limit for all errors thrown by node processes run through yarn. Note that this is a change which only affects our dev environment, not the SDK itself.
=> ref(dev): Remove stacktrace limit on node errors in yarn scripts

packages/tracing/src/transaction.ts, packages/tracing/test/transaction.test.ts
This is a quick follow-up to https://github.com/getsentry/sentry-javascript/pull/5723, which makes sure either transaction name or source has actually been changed before recording a name-change entry.
=> fix(tracing): Only record transaction name changes if data is different

packages/node-integration-tests/package.json, packages/node-integration-tests/utils/index.ts, packages/node-integration-tests/utils/run-tests.ts, packages/remix/package.json
Since even after merging https://github.com/getsentry/sentry-javascript/pull/5715 I have trouble with the global context being shared across tests we should definitely isolate the individual node integration tests before something slips though because of it.
This PR adds a quick and dirty script that runs all the test files with an individual `jest` command. It doesn't do anything fancy except for creating a worker sharing work for each CPU core available.
Also removes the `portfinder` package from the integration tests as it was a bit inconsistent - we now let the OS choose a port on its own.
This PR admittedly doesn't contain a lot of effort but was done to unblock https://github.com/getsentry/sentry-javascript/pull/5710
=> test: Run node integration tests in isolation

packages/tracing/src/browser/request.ts, packages/tracing/test/browser/request.test.ts
Part of https://github.com/getsentry/sentry-javascript/issues/5679
Dependent on https://github.com/getsentry/sentry-javascript/pull/5714 merging
This PR updates the propagations metadata field in the tracing SDK for `BrowserTracing`. It does this by adding a propagations incrementor to the fetch and XHR instrumentation.
=> ref(tracing): Add propagations to tracing SDK

packages/nextjs/test/integration/test/server/tracingHttp.js, packages/node/src/integrations/http.ts, packages/node/test/integrations/http.test.ts
Part of https://github.com/getsentry/sentry-javascript/issues/5679
Dependent on https://github.com/getsentry/sentry-javascript/pull/5714 merging
This PR updates the propagations metadata field in the node SDK for the HTTP integration.
=> ref(node): Add propagations to http integration

packages/core/src/baseclient.ts, packages/core/test/lib/base.test.ts
Part of https://github.com/getsentry/sentry-javascript/issues/5679
Dependent on https://github.com/getsentry/sentry-javascript/pull/5714 merging
This PR updates `BaseClient` class to set a custom transaction source if event processors change the transaction name. It also adds metadata around a transaction name change when this is done.
=> feat(core): Set custom transaction source for event processors

packages/core/src/baseclient.ts
ref https://github.com/getsentry/sentry-javascript/issues/5679
Instead of setting a timestamp to a number that is larger than the transaction's end timestamp, set the transaction name change timestamp to be the transaction's end timestamp.
=> ref(core): Use timestamp of processed event in name change

packages/nextjs/src/utils/withSentry.ts
In `withSentry` in the nextjs SDK, we import and use the `NextApiHandler` type provided by Next. In https://github.com/vercel/next.js/pull/35166, which was released in 12.1.6, that type switched to using `uknown` rather than `void` for the function's return type.
For users this isn't a problem. If they import both the type from Nextjs and `withSentry` from our SDK (which in turn imports the type), both imports will be pointed at their local version of Next, and the types will match. For us, though, it's a different story. Our dev version of Next is the lowest one the SDK supports, 10.0.8. If we link our SDK into a test app, the `NextApiHandler` we're importing will be coming from the `node_modules` in our repo, whereas the test app will be pulling the type from its own `node_modules`. And …
=> fix(nextjs): Make `NextApiHandler` type version-agnostic

package.json, yarn.lock
We list `rimraf` as a top-level dev dependency, but have been relying on a hoisted sub-dependency for the types. This adds them as a first-class dev dependency.
=> chore(deps): Add `@types/rimraf`

CHANGELOG.md
`7.13.0` includes all the changes around mutable dynamic sampling context
resolves https://github.com/getsentry/sentry-javascript/issues/5679
resolves https://github.com/getsentry/sentry-javascript/issues/5741
=> meta: CHANGELOG for 7.13.0

packages/node/src/index.ts, packages/node/src/requestDataDeprecated.ts, packages/node/src/sdk.ts, packages/node/test/requestdata.test.ts, packages/tracing/src/integrations/node/express.ts, packages/types/src/index.ts, packages/types/src/polymorphics.ts, packages/utils/src/requestdata.ts
This is a change which comes out of a [code review](https://github.com/getsentry/sentry-javascript/pull/5703#discussion_r970455276) of https://github.com/getsentry/sentry-javascript/pull/5703, moving the `CrossPlatformType` from `@sentry/utils` to `@sentry/types` and renaming it `PolymorphicRequest` (to match the existing `PolymorphicEvent`). Because it affects a number of files, I decided to pull it into its own PR, just to not confuse things in that one.
=> feat(types): Add `PolymorphicRequest` type

package.json, packages/node/package.json, packages/remix/package.json, packages/serverless/package.json, packages/tracing/package.json, yarn.lock
Recently, [this issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/40138) flared up in our remix tests, and it turns out the culprit was that DefinitelyTyped [removed TS 4.0 support from a number of packages](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62240), among them `@types/express-serve-static-core` (upon which `@types/express` depends).
Key changes in this fix:
- Lock `@types/express-serve-static-core` to the last version before this change.
- Add `@types/express` to `@sentry/remix`'s dev dependencies (where it should have been all along).
- Update all usages of `@types/express` to latest. (Not strictly necessary, but done as part of my debugging. Doesn't seem to break anything, and we might as well be up to date.)
=> fix(remix): Fix express `Request` and `Response` types

packages/node/src/handlers.ts, packages/node/src/index.ts, packages/node/src/requestDataDeprecated.ts, packages/node/src/requestdata.ts, packages/node/src/sdk.ts, packages/node/test/requestdata.test.ts, packages/utils/src/index.ts
As part of the work adding a `RequestData` integration, this moves the `requestdata` functions back into the node SDK. (The dependency injection makes things hard to follow, and soon the original reason for the move (so that they could be used in the `_error` helper in the nextjs SDK, which runs in both browser and node) will no longer apply (once https://github.com/getsentry/sentry-javascript/pull/5729 is merged).)
Once these functions are no longer needed, they can be deleted from `@sentry/utils`.
More details and a work plan are in https://github.com/getsentry/sentry-javascript/issues/5756.
=> ref(node): Move request data functions back to`@sentry/node`

packages/typescript/tsconfig.json, tsconfig.json
This removes two `tsconfig` settings which don't have any effect given settings elsewhere in the repo:
- `noEmitHelpers`: The [TS config docs](https://www.typescriptlang.org/tsconfig#noEmitHelpers) aren't super clear in saying this explicitly, but `noEmitHelpers` has no effect in the presence of `importHelpers: true`, because the latter means that no helper implementations will be emitted in any case, instead being imported from `tslib`.
- Node types: We've had Node types in our repo-level `tsconfig` for a long time, but all packages which need Node types already specify it themselves. Removing it in our top-level tsconfig also has the advantage that it means we won't accidentally use Node types where we shouldn't (like in browser-based and cross-platform packages).
=> chore(build): Remove redundant `tsconfig` settings

packages/nextjs/src/config/wrappers/wrapperUtils.ts, packages/nextjs/src/index.server.ts, packages/nextjs/src/utils/instrumentServer.ts, packages/nextjs/src/utils/withSentry.ts, packages/nextjs/test/config/wrappers.test.ts, packages/nextjs/test/index.server.test.ts, packages/nextjs/test/utils/withSentry.test.ts, packages/node/src/index.ts, packages/node/src/integrations/index.ts, packages/node/src/integrations/requestdata.ts, packages/node/src/requestdata.ts, packages/types/src/transaction.ts
In most of our Node-based SDKs, we use domains to prevent scope bleed between requests, running the entire wrapped event-handling process inside a single domain. This works because in those cases, there is only one request-handling entry point for us to wrap, so we can stick the entire thing in a single `domain.run()` call and (more or less) rely on the fact that we've got a single, consistent, unique-to-that-request `Scope` object that we're dealing with. We've followed this pattern in the nextjs SDK as well, both in `instrumentServer` and `withSentry`. The new auto-wrapping of data-fetching functions presents a challenge, though, because a single request may involve a number of our wrapped functions running at different points in the request handling process, with no shared (little S) …
=> ref(nextjs): Use integration to add request data to transaction events

packages/core/src/envelope.ts, packages/tracing/src/hubextensions.ts, packages/tracing/src/transaction.ts, packages/tracing/test/hub.test.ts, packages/tracing/test/span.test.ts, packages/types/src/envelope.ts, packages/types/src/index.ts, packages/types/src/transaction.ts
In our initial work on Dynamic Sampling (https://github.com/getsentry/sentry-javascript/pull/3068), we added the ability to track transaction sampling method.
https://github.com/getsentry/sentry-javascript/pull/3068/files#diff-337facb22f742f05b3326aed66ca6b0d5eb9c782c7c03c88ef0170fd97dc410dR104-R109
```ts
export enum TransactionSamplingMethod {
Explicit = 'explicitly_set',
Sampler = 'client_sampler',
Rate = 'client_rate',
Inheritance = 'inheritance',
}
```
To use this info, we set the transaction sampling method and sample rate on the transaction event header:
```ts
sample_rates: [{ id: samplingMethod, rate: sampleRate }],
```
In Relay this is used here: https://github.com/getsentry/relay/blob/4b16d279ccf21d3c1d975b652ffca01ebd72a500/relay-general/src/protocol/metrics.rs#L7-L16
This is no …
=> ref(tracing): Don't track transaction sampling method

.github/ISSUE_TEMPLATE/bug.yml
Also alpha order it, so remix gets moved down
=> chore: Add Svelte to bug template

packages/node/src/requestdata.ts
This removes a trailing slash which somehow crept into an `@sentry/utils` import when the request-data-adding functions were moved back to node. As a result of the trailing slash, Rollup doesn't recognize the import as external, which leads to the inclusion of files from the utils package in the node build, as well as an incorrect file structure (the root which is used for `build/cjs` and `build/esm` becomes `packages` rather than `packages/node/src`).
(I think that the reason this wasn't caught by our tests is that both our unit and integration tests do their own building of the SDK, using `tsc` and `webpack`, respectively, which must have handled the trailing slash more gracefully than `rollup` does. We've talked before about having tests for our build process, and this is a good …
=> fix(node): Remove trailing slash in `@sentry/utils` import

packages/nextjs/src/config/wrappers/wrapperUtils.ts, packages/nextjs/test/integration/test/server/errorServerSideProps.js, packages/nextjs/test/integration/test/server/tracingServerGetInitialProps.js, packages/nextjs/test/integration/test/server/tracingServerGetServerSideProps.js
Ref https://github.com/getsentry/sentry-javascript/issues/5505
Adds span statuses to spans and transactions of Next.js data fetching methods.
=> feat(nextjs): Add status to data-fetcher spans

packages/nextjs/src/config/wrappers/wrapperUtils.ts, packages/nextjs/test/config/wrappers.test.ts
This adds the request to the sampling context passed to the `startTransaction` call in the data fetchers wrapper in nextjs, to bring it in line with the `startTransaction` calls elsewhere in the SDK.
=> fix(nextjs): Pass request in sampling context of data fetchers wrapper transaction

packages/gatsby/gatsby-node.js
TODO:
- Add references to Gatsby source where this may occur
=> fix(gatsby): Include app-* entrypoints as they may include user source code

packages/nextjs/src/config/wrappers/wrapperUtils.ts, packages/nextjs/src/utils/_error.ts, packages/nextjs/src/utils/instrumentServer.ts, packages/nextjs/src/utils/withSentry.ts, packages/node/src/integrations/requestdata.ts
In https://github.com/getsentry/sentry-javascript/pull/5703, a new integration, `RequestData`, was added to take the place of the request-specific event processors we've been using to add request data to transaction events in the nextjs SDK. This builds on that work by making the same switch for error events.
Notes:
- Because of https://github.com/getsentry/sentry-javascript/issues/5718, it's hard to reason about the potential side effects of making major changes to the logic in `@sentry/utils/requestData`. Therefore, the majority of the new logic in this PR has been added to the integration, and just overwrites the `transaction` value added by the functions in `requestData`. Once we've cleaned up the request data code, we can consolidate the logic.
=> ref(nextjs): Use`RequestData` integration for errors

packages/types/src/envelope.ts
Remove the usage of extend so that we don't eliminate the base envelope types.
=> ref(types): Use intersections instead of extend in envelope types

packages/nextjs/src/utils/instrumentServer.ts
In nextjs version 12.2.6, the signature of `findPageComponents` which we wrap in `instrumentServer` [changed](https://github.com/vercel/next.js/commit/5f95b6b05031201b04d89cee7b6161296bbe7058#diff-2b8e3503c1bebf856610a5551d9c5996435b99f45db389d4eeac1b671518875eR242-R248), from accepting individual parameters to accepting an options object. This changes our wrapping to accommodate that, and fixes transactions started by `instrumentServer` being parameterized as `[ object Object ]`. For backwards compatibility with older versions of next, individual parameters also continue to be accepted.
=> fix(nextjs): Handle `pathname` being passed in object in `instrumentServer`

packages/browser/src/client.ts, packages/browser/src/transports/utils.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/4736
Update the client report sending logic to fallback on whatever transport is initialized on the client. This fallback is also used when a user configures custom transport options.
=> ref(browser): Use any transport as fallback for client reports

packages/remix/src/utils/serverAdapters/express.ts
`loadModule` utility which we use to acquire `react-router-dom` can return `null` when called from Express wrapper.
I suspect the main reason is that we are not monkey-patching Remix core here, like we are doing in the base implementation, the package acquisition is not guaranteed to run when (or where?) `react-router-dom` is available.
Tried using dynamic imports, and it worked well on https://github.com/getsentry/vanguard
[Transaction Before](https://sentry.io/organizations/sentry-sdks/discover/results/?field=transaction&field=project&field=transaction.source&field=epm%28%29&field=p50%28%29&field=p95%28%29&name=Performance+-+Unparameterized+Transactions&project=6407073&query=event.type%3Atransaction+transaction.source%3A%22url%22&sort=-epm&statsPeriod=1h&yAxis=epm%28%29)
[Transaction …
=> fix(remix): Use `require()` to get `react-router-dom` in Express wrapper.

packages/nextjs/src/config/types.ts, packages/nextjs/src/config/webpack.ts, packages/nextjs/test/integration/next.config.js, packages/nextjs/test/integration/next10.config.template, packages/nextjs/test/integration/next11.config.template
Ref: https://github.com/getsentry/sentry-javascript/issues/5505
Promotes `experiments.autoWrapDataFetchers` option in the Sentry Next.js config to a proper option called `autoInstrumentServerFunctions`.
---
Other names I considered naming this option:
- `instrumentServerRequests`
- `autoInstrumentServerMethods`
=> feat(nextjs): Promote option to automatically wrap data fetchers and API routes to non-experimental

packages/remix/src/utils/serverAdapters/express.ts
Reverts getsentry/sentry-javascript#5796
Fixes broken master.
=> Revert "fix(remix): Use `require()` to get `react-router-dom` in Express wrapper."

packages/ember/package.json, yarn.lock
Upgrade `@embroider/macros` as an attempt to fix #5701
=> chore(deps): Upgrade @embroider/macros

rollup/plugins/npmPlugins.js
The existing regex, when presented with code like this:
```js
/* 
* This is
* a multiline
* comment 
*/
const thisIs = "real code"
/* 
* This is
* another multiline
* comment 
*/
const thisIsAlso = "real code"
```
matches everything between the initial `/*` on the first line and the final `*/` on the second-to-last line, and the plugin thus removes all but the last line of the file. This fixes the regex so that only the comments are removed.
=> fix(build): Fix regex in multiline-comment-removal Rollup plugin

packages/remix/src/utils/serverAdapters/express.ts
Details copied from: https://github.com/getsentry/sentry-javascript/pull/5796 which is reverted by  #5802 
> `loadModule` utility which we use to acquire `react-router-dom` can return null when called from Express wrapper.
>
> I suspect the main reason is that we are not monkey-patching Remix core here, like we are doing in the base implementation, the package acquisition is not guaranteed to run when (or where?) react-router-dom is available.
>
> Tried using dynamic imports, and it worked well on https://github.com/getsentry/vanguard
[Parameterized Route Transaction](https://sentry.io/organizations/sentry-sdks/performance/summary/?project=6407073&query=&statsPeriod=1h&transaction=routes%2Fp%2F%24postId%2Fedit&unselectedSeries=p100%28%29)
[Root …
=> fix(remix): Use import() to get `react-router-dom` in Express wrapper.

packages/nextjs/vercel/set-up-branch-for-test-app-use.sh
This is a small refactor to our `set-up-branch-for-test-app-use.sh` vercel script, which prepares the current branch to be tested on vercel by deleting packages unrelated to the nextjs SDK, thereby speeding up the vercel build.
The only consequential change is a switch from specifying which packages should get deleted to specifying which packages shouldn't. (The list of deletion targets kept falling out of date, each time we added a new package. With this change, it should in theory be evergreen.)
=> ref(nextjs): Update vercel testing script

packages/remix/src/utils/instrumentServer.ts
Fixes: #5742
We were early returning wrappers (which are also responsible for most errors to handle) if there isn't an active transaction.
This PR removes it and early returns only if there isn't a scope defined.
=> fix(remix): Do not skip error handling if tracing is not enabled.

packages/utils/src/global.ts
This PR:
- Replaces `getGlobalObject` global object detection with a modern implementation taken from `core-js` which is then modified/simplified a little
- Prioritises `globalThis` which was previously removed due to requiring a TypeScript version which was required in a no longer supported version of Angular (#2978)
- This is a requirement for future support of other js runtimes (#5611)
- No longer uses `isNodeEnv` 🎉
- Caches the global so it doesn't need to be evaluated for every invocation of `getGlobalObject`
=> feat(utils): Modern implementation of `getGlobalObject`

.github/ISSUE_TEMPLATE/config.yml
I noticed when creating an issue in github, the link to the community discussion points to the issues tab again, where it should probably point at the github discussions since I'd imagine that's where the question or post should go if it doesn't fall under a bug or feature request
=> chore: Update discussion link to point to github discussions

packages/nextjs/src/index.server.ts
As it stands right now, when we check whether or not to require `instrumentServer`, our check short-circuits if the code is running on vercel. This is a problem, because the first run of `isBuild()` causes a side effect (it sets an env var) which then enables all future runs, so without that initial runs, future runs fail. This reverses the order of the check, so that `isBuild()` will always run.
=> fix(nextjs): Reverse order of checks for instrumenting server

packages/nextjs/src/config/wrappers/types.ts, packages/nextjs/src/config/wrappers/utils/responseEnd.ts, packages/nextjs/src/config/wrappers/withSentryAPI.ts, packages/nextjs/src/config/wrappers/wrapperUtils.ts, packages/nextjs/test/config/withSentry.test.ts, packages/nextjs/test/config/wrappers.test.ts
When deployed to Vercel, nextjs apps have their route handlers converted to AWS lambdas, which use the vercel node runtime. In this runtime, AWS's [`callbackWaitsForEmptyEventLoop` context option](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-context.html) is [set to `false`](https://github.com/vercel/fun/blob/6329dcbd3f7d99a519cbbd6ac615fec4b46fc28e/src/runtimes/nodejs/bootstrap.ts#L122). As a result, it's possible for a route-handling lambda to be shut down before events have finished sending to Sentry. To ensure that this doesn't happen, in `withSentry` we wrap `res.end`, so that it flushes all of our events before the response marks itself as finished.
This extracts that logic into its own module, so that it can also be used in the other `withSentryX` wrappers …
=> ref(nextjs): Use flush code from `withSentry` in all backend wrappers

packages/nextjs/src/config/wrappers/wrapperUtils.ts, packages/nextjs/test/config/wrappers.test.ts, packages/nextjs/test/integration/test/server/errorServerSideProps.js, packages/nextjs/test/integration/test/server/tracingServerGetInitialProps.js, packages/nextjs/test/integration/test/server/tracingServerGetServerSideProps.js
As per the span operation audit, this transaction is a http request processed on the server, so we should rename the span op.
https://www.notion.so/sentry/Set-up-an-audit-for-SDK-consistency-for-span-operations-to-enable-performance-issues-addf02a8fa234dda8acf48d4ff9b8efb?d=b852bdd1e9914d2ca74c1052296081f3#d04af01302604881999b1bd29c837b1f
ref: https://github.com/getsentry/sentry-javascript/issues/5837
`nextjs.data.server` -> `http.server` for transactions, and `nextjs.data.server` -> `function.nextjs` for spans.
=> fix(nextjs): Rename `nextjs.data.server` ops

packages/e2e-tests/package.json, packages/e2e-tests/validate-test-app-setups.ts
Ref: https://github.com/getsentry/sentry-javascript/issues/5506
Adds a validation script to the E2E test package that does a plausibility check if E2E test apps have a correct setup (i.e. they use the test registry and ignore lockfiles).
=> test(e2e): Validate test app setup

packages/tracing/src/integrations/node/apollo.ts, packages/tracing/src/integrations/node/graphql.ts
ref #5808
This PR actually doesn't solve the source of #5808 (supporting `ApolloServer` instances configured by a pre-constructed `schema`).
But logs a warning instead of breaking the application when `resolvers` array is not defined in the `ApolloServer` configuration.
=> fix(tracing): Warn if `resolvers` is not defined in `ApolloServer` config

packages/utils/src/envelope.ts, packages/utils/test/envelope.test.ts
Since https://github.com/getsentry/sentry-javascript/issues/2809 keeps being necrobumped I decided to look into it once more.
Apparently unnormalized data keeps slipping through up until we serialize envelopes. This causes the `JSON.stringify` call to fail and throw, right before we were about to report an error event. Not ideal.
My proposed fix for now - and I am definitely *not* all for it - is to simply wrap the `JSON.stringify` call in a try-catch and normalize the entire payload with infinite recursion depth once more, in case that call fails.
This has an obvious performance impact, especially since we know that when `JSON.stringify` fails, it has some unnormalized data that might be very big and recursive - potentially even sending payloads that are too big.
=> fix(utils): Normalize when serializing envelope

packages/react/src/reactrouterv6.tsx
Indicate to users what parameters are not defined in debug logs.
=> ref(react): Improve React Router v6 error message

packages/node/src/integrations/context.ts, packages/node/test/integrations/context.test.ts
When[ creating the `DeviceContext` ](https://github.com/getsentry/sentry-javascript/blob/6b82415168f4d4eb33ae955dfef5b082f5adea3d/packages/node/src/integrations/context.ts#L195) in the Node SDK `Context` integration, we calculate the boot time based on `os.uptime`. However, as reported in #5856, `os.uptime` might not always be available or return undefined (I couldn't figure out which of the two cases actually was responsible).
This PR quickly fixes this bug by simply not setting the boot time in case we don't get a valid up time. It also adds two basic tests for this behaviour. I opted to not set the boot time instead of e.g. defaulting to `0` for uptime because IMO this creates a false boot time that probably causes more confusion than not having it. However, as my context on the …
=> fix(node): Only set `DeviceContext.boot_time` if `os.uptime()` is valid

packages/nextjs/src/config/templates/apiProxyLoaderTemplate.ts, packages/nextjs/test/integration/pages/api/withSentryAPI/unwrapped/cjsExport.ts, packages/nextjs/test/integration/pages/api/withSentryAPI/wrapped/cjsExport.ts, packages/nextjs/test/integration/test/server/cjsApiEndpoints.js
Fixes #5863
The PR makes our auto wrapping of Next.js API routes able to handle CJS exports. Previously we only looked at `import.default` which is not defined in case the user exported via CJS export (e.g. `module.exports = myFunction;`)
=> fix(nextjs): Handle CJS API route exports

packages/nextjs/src/config/wrappers/withSentryServerSideAppGetInitialProps.ts, packages/nextjs/src/config/wrappers/withSentryServerSideDocumentGetInitialProps.ts, packages/nextjs/src/config/wrappers/withSentryServerSideErrorGetInitialProps.ts, packages/nextjs/src/config/wrappers/withSentryServerSideGetInitialProps.ts
Fixes #5864
Next.js' `getInitialProps` functions generally are passed request and response objects on the server side. This does not seem to hold in development mode where there are cases that they're undefined.
This PR simply stops tracing `getInitialProps` functions when there are no request or response objects, because we have no clean way of grouping data fetchers under a transaction when there are no `req` and `res` objects.
Disclaimer: I am still not entirely sure if this is the right approach and how the exact behavior for `getInitialProps` and `next dev` is, but this is a forward fix to quickly unblock users.
=> fix(nextjs): Don't assert existence of `req` and `res` in data-fetching wrappers

packages/nextjs/src/index.server.ts, packages/nextjs/src/utils/isBuild.ts
This makes a few changes to the `isBuild` utility function in the nextjs SDK in order to make its operation less brittle. Currently, it relies on being called at the top level of `index.server.ts`, which ensures that it runs early enough in the build process to be executed in the main thread, before operation has been split out into child processes. (This is important because child processes don't conveniently have the word 'build' in their invocations the way the main thread (invoked by `next build`) does, removing one of `isBuild`'s clues about what phase it's in.) It then sets an environment variable as a clue to future calls to itself, so that, child processes or not, it knows the correct phase. This means, however, that if it stops being used at `index.server.ts`'s top level, and …
=> ref(nextjs): Make build-phase check more robust

packages/angular/.eslintrc.js, packages/angular/jest.config.js, packages/angular/package.json, packages/angular/setup-jest.ts, packages/angular/test/errorhandler.test.ts, packages/angular/test/tracing.test.ts, packages/angular/test/utils/index.ts, yarn.lock
Resolves: #4143
This PR increases unit test coverage of Angular SDK by integrating [`TestBed`](https://angular.io/api/core/testing/TestBed).
The main work here is done on [`tracing.ts`](https://github.com/getsentry/sentry-javascript/blob/12c19d051eca4fcef316ba6ee512f1221ae92ef0/packages/angular/src/tracing.ts) which had low test coverage, and the previous tests were [faking the angular router](https://github.com/getsentry/sentry-javascript/blob/12c19d051eca4fcef316ba6ee512f1221ae92ef0/packages/angular/test/tracing.test.ts#L72-L79).
I attempted to use `@testing-library/angular` to be consistent with other SDK tests like `@sentry/react` and `@sentry/svelte`, but it was not possible as [it doesn't support renders without compiled components](https://github.com/testing-library/angular-testing- …
=> test(angular): Increase Angular SDK test coverage.

packages/hub/src/scope.ts, packages/hub/test/scope.test.ts, packages/types/src/options.ts
Fix #4693 
As decission in #4693, this PR remove hard cap from `maxBreadcrumbs`.
=> ref(hub): remove hard cap from maxBreadcrumbs

packages/remix/src/utils/instrumentServer.ts, packages/remix/test/integration/test/server/action.test.ts, packages/remix/test/integration/test/server/loader.test.ts
Ref: #5837
For `packages/remix`, I changed span operations to new operations.
=> fix(remix): align span operations to new operations

packages/serverless/src/awslambda.ts, packages/serverless/src/awsservices.ts, packages/serverless/src/gcpfunction/cloud_events.ts, packages/serverless/src/gcpfunction/events.ts, packages/serverless/src/gcpfunction/http.ts, packages/serverless/src/google-cloud-grpc.ts, packages/serverless/src/google-cloud-http.ts, packages/serverless/test/awslambda.test.ts, packages/serverless/test/awsservices.test.ts, packages/serverless/test/gcpfunction.test.ts, packages/serverless/test/google-cloud-grpc.test.ts, packages/serverless/test/google-cloud-http.test.ts
Ref: #5837
For `packages/serverless`, I changed span operations to new operations.
=> fix(serverless): align span operations to new operations

packages/vue/src/tracing.ts
Ref: #5837
For `packages/vue`, I changed span operations to new operations.
=> fix(vue): align span operations to new operations

packages/integration-tests/suites/tracing/browsertracing/long-tasks-enabled/test.ts, packages/integration-tests/suites/tracing/metrics/web-vitals-fid/test.ts, packages/node-integration-tests/suites/tracing/apollo-graphql/test.ts, packages/node-integration-tests/suites/tracing/prisma-orm/test.ts, packages/tracing/src/browser/metrics/index.ts, packages/tracing/src/integrations/node/apollo.ts, packages/tracing/src/integrations/node/express.ts, packages/tracing/src/integrations/node/graphql.ts, packages/tracing/src/integrations/node/prisma.ts, packages/tracing/test/browser/metrics/index.test.ts, packages/tracing/test/integrations/apollo.test.ts, packages/tracing/test/integrations/graphql.test.ts, packages/tracing/test/integrations/node/prisma.test.ts
Ref: #5837
For `packages/tracing`, I changed span operations to new operations.
=> fix(tracing): align span operations to new operations

CHANGELOG.md
Creating changelog entry because we want to release fixes in #5881 so that we can flip the experimental flag on monday for NextJS.
~Blocked on https://github.com/getsentry/sentry-javascript/pull/5891 and https://github.com/getsentry/sentry-javascript/pull/5892~ Merged!
=> meta: CHANGELOG for 7.14.2

.github/workflows/build.yml
Cancel any pending actions running on a pull request when a new commit is pushed. This should help improve CI times generally.
See: https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
Based on @mattgauntseo-sentry's work in https://vanguard.getsentry.net/p/cl8kjy5ed162880ls6gwjs6a63 - https://github.com/getsentry/sentry/pull/38889
=> build: Cancel in-progress workflows to free up concurrent groups

packages/node/src/requestdata.ts, packages/node/test/requestdata.test.ts
When using the `Sentry.requestMiddleware` in Node (Express), users have the option to define which properties of the incoming requests should be added to the event that is sent to Sentry. Among other options, they can set
* `headers` to add the request's http headers to `event.request.headers`
* `cookies` to add the request's cookies to `event.request.cookies`
However, there is a problem if `cookies` is not specified but `headers` is: The `Cookie` http header of the incoming request is still added to `event.request.headers` as it is treated like a normal http header. Therefore, cookie data (potentially containing sensitive data) is added to the event although users expect it to not be added.
This PR fixes this behaviour by removing the `Cookie` http header from the collected headers, if …
=> fix(node): Remove `Cookie` header from event if cookies should not be sent to Sentry

packages/ember/addon/instance-initializers/sentry-performance.ts
When using engines and the 'ember-engines-router-service' addon, this will allow performance monitoring to work, which was previously causing an error since the ember-engines-router-service router doesn't have a 'recognize' function. This hooks into the main router for the application instead, and only setups up route change listening once for navigation transactions.
=> feat(ember): Add ember-engine-router support

packages/tracing/src/browser/browsertracing.ts, packages/tracing/src/hubextensions.ts, packages/tracing/src/idletransaction.ts, packages/tracing/test/browser/browsertracing.test.ts, packages/tracing/test/idletransaction.test.ts
Close #4925
The heartbeat interval was hard coded. 
This PR makes heartbeat interval configurable via `BrowserTracingOptions`.
=> feat(tracing): Make BrowserTracing heartbeat interval configurable

packages/remix/package.json, packages/remix/rollup.npm.config.js, packages/remix/src/utils/serverAdapters/express.ts
Fixes: #5860
Ref: https://github.com/getsentry/sentry-javascript/pull/5810#discussion_r978866425
---
~~Added `react-router` as a peer dependency to flag it as `external`, so Rollup won't complain in `sentry-javascript`'s build time.~~
**Edit:** 
Defined `react-router` and `react-router-dom` as `external`s in Rollup configuration, without making them peer dependencies.
---
Added import by name as the first priority (which will work in monorepos) and relative imports as the second if the former fails. Logging error at the end if the latter fails too, without breaking the whole application.
This implementation is similar to the `loadModule` implementation below, only the priorities are swapped. (The other way works too)
https://github.com/getsentry/sentry-javascript/blob/69dfc3516896a60245ad6 …
=> fix(remix): Rework dynamic imports of `react-router-dom`.

packages/nextjs/src/config/webpack.ts, packages/nextjs/test/integration/next.config.js, packages/nextjs/test/integration/next10.config.template, packages/nextjs/test/integration/next11.config.template
Ref: https://github.com/getsentry/sentry-javascript/issues/5505
Sets the default value of the `autoInstrumentServerFunctions` option in our Next.js SDK to `true`. This function automatically wraps any Next.js data fetching methods and user-defined API routes with Sentry error and performance monitoring during build-time.
=> feat(nextjs): Enable `autoInstrumentServerFunctions` per default

packages/vue/src/tracing.ts
Attempts to fix https://github.com/getsentry/sentry-javascript/issues/5693
We suspect that Vue does not always call cleanup hooks (e.g. `updated`, `created`, `unmounted`) in mixins. This would currently have the effect that we clobber old spans with new spans on hooks like `beforeUpdated` and never finish the spans.
This PR will simply finish unfinished spans for a particular lifecycle operation when they're not finished/cleaned up yet.
=> fix(vue): Finish spans in component tracking before starting new ones for same operation

packages/remix/package.json, yarn.lock
Fixes https://github.com/getsentry/sentry-javascript/issues/5924
Add `yargs` dep to remix that is used by our upload sourcemaps script: https://github.com/getsentry/sentry-javascript/blob/56868e8bb00a925f2d212048b6c6559d6e1fb2d0/packages/remix/scripts/sentry-upload-sourcemaps.js#L2
=> fix(remix): Add yargs dependency for uploading sourcemaps

packages/svelte/src/config.ts, packages/svelte/src/index.ts, packages/svelte/src/preprocessors.ts, packages/svelte/src/types.ts, packages/svelte/test/config.test.ts, packages/svelte/test/preprocessors.test.ts
This PR adds the `withSentryConfig` wrapper function to our Svelte SDK which can be used to automatically add Sentry-specific svelte configuration options to our users' configuration in `svelte.config.js`. Going forward, this function will allow us to add more sentry-specific config items, such as additional preprocessors to the config without having to ask our users to adjust their config stuff every time we introduce changes.
We already have a concrete use case for adding another preprocessor to fix #5923 which will be addressed in a follow-up PR. 
The change is fully backward-compatible with how we previously instructed users to add the `componentTrackingPreprocessor` explicitly to their set of preprocessors in their config. However, to make it clear that `withSentryConfig` is the way …
=> feat(svelte): Add `withSentryConfig` function to wrap User Svelte Configuration

packages/e2e-tests/test-applications/standard-frontend-react/tests/behaviour-test.spec.ts
Logs out the polled `eventId`s in E2E tests so we can identify why they are potentially flakey.
=> test(e2e): Log polled events in e2e tests

packages/angular/src/tracing.ts, packages/ember/addon/index.ts, packages/ember/addon/instance-initializers/sentry-performance.ts, packages/nextjs/src/performance/client.ts, packages/nextjs/test/index.client.test.ts, packages/nextjs/test/index.server.test.ts, packages/nextjs/test/performance/client.test.ts, packages/react/src/reactrouter.tsx, packages/react/src/reactrouterv3.ts, packages/react/src/reactrouterv6.tsx, packages/remix/src/performance/client.tsx, packages/remix/test/index.client.test.ts, packages/remix/test/index.server.test.ts, packages/vue/src/index.bundle.ts, packages/vue/src/sdk.ts
Builds on top of #5831 and removes usages of `getGlobalObject` from all the framework specific SDKs.
=> ref(utils): Remove `getGlobalObject()` usage from all framework specific SDKs

packages/integrations/src/captureconsole.ts, packages/integrations/src/offline.ts, packages/integrations/src/reportingobserver.ts, packages/integrations/test/offline.test.ts, packages/node/src/sdk.ts
Builds on top of #5831 and removes usages of `getGlobalObject` in node and integrations.
=> ref(utils): Remove `getGlobalObject()` usage from `@sentry/node` and `integrations`

packages/utils/src/global.ts
ref: https://github.com/getsentry/sentry-javascript/issues/5611
This PR wraps up the changes to the global object detection by removing `getGlobalObject` which is no longer used.
=> ref(utils): Deprecate `getGlobalObject` as it's no longer used

packages/nextjs/src/config/wrappers/withSentryServerSideAppGetInitialProps.ts, packages/nextjs/test/integration/pages/_app.tsx, packages/nextjs/test/integration/pages/faultyAppGetInitialProps.tsx, packages/nextjs/test/integration/test/client/faultyAppGetInitialPropsConfiguration.js
Even though the Next.js docs tell users to call `App.getInitialProps(appContext)` in their custom `_app` pages, many of them don't and this will crash our implementation because the user's `getInitialProps` will most likely not contain a `pageProps` property.
This PR adds a simple check if the `pageProps` are there, and inserts them if they aren't. This should not have any negative consequences.
=> ref(nextjs): Don't assert existance of `pageProps` in `_app`

package.json, yarn.lock
This was used here: https://github.com/getsentry/sentry-javascript/pull/1424, but is no longer needed anymore since that uploading happens with craft, so we can `rm -rf`.
=> build: Remove `@google-cloud/storage` dep

package.json, packages/e2e-tests/package.json, packages/gatsby/test/sdk.test.ts, packages/svelte/test/sdk.test.ts, yarn.lock
Retry of https://github.com/getsentry/sentry-javascript/pull/5747
Use https://github.com/atlassian/yarn-deduplicate to make sure we dedupe deps properly. This should help speed up CI times since we don't have to cache as much stuff. 
Had to adjust Svelte tests because was getting the follow error:
```
FAIL  test/sdk.test.ts
● Test suite failed to run
Failed to get mock metadata: /Users/abhijeetprasad/workspace/sentry-javascript/packages/browser/build/npm/cjs/index.js
See: https://jestjs.io/docs/manual-mocks#content
> 1 | import { addGlobalEventProcessor, init as browserInitRaw, SDK_VERSION } from '@sentry/browser';
| ^
2 | import { EventProcessor } from '@sentry/types';
3 |
4 | import { detectAndReportSvelteKit, init as svelteInit, isSvelteKitApp } from '../src/sdk';
at …
```
=> build: Run yarn-deduplicate

packages/svelte/rollup.npm.config.js, packages/svelte/src/preprocessors.ts, packages/svelte/test/preprocessors.test.ts
This PR makes our Svelte component tracking feature track components without `<script>` tags. Previously these components would not be picked up by our preprocessor because its `script` hook is only called for components with script blocks. With this PR, we first leverage the `markup` hook to check if a script block exists. If it doesn't, we add an empty script tag which we later revisit in the `script hook` where we inject the component tracking code.
Note: To determine if a script tag exists in the file, we use a regex check which has drawbacks, as it is not 100% bullet proof. However, we decided that for the lack of better options as explained in [#5923(comment)](https://github.com/getsentry/sentry-javascript/issues/5923#issuecomment-1277738734) we'll go with this approach for now. …
=> fix(svelte): Track components without <script> tags

README.md
ref https://github.com/getsentry/sentry-javascript/issues/5665
`@sentry/hub` is deprecated, so let us remove it from the README.
=> chore: Delete @sentry/hub from the README

packages/node/test/manual/express-scope-separation/start.js, packages/node/test/manual/webpack-domain/index.js
This adds logging of the received and expected values when the tags in the express scope separation test don't match, for easier debugging.
=> fix(node): Improve logging in express scope tag match test

.github/workflows/build.yml, .github/workflows/canary.yml, .github/workflows/codeql-analysis.yml, .github/workflows/release.yml
This updates the `setup-node`, `cache`, and `checkout` actions to each use version 3, in order to deal with the many warnings being thrown by our `Build & Test` workflow:
=> chore(dev): Use `setup-node`, `cache`, and `checkout` v3 in GHA

packages/vue/src/router.ts, packages/vue/src/tracing.ts, packages/vue/test/router.test.ts
This PR makes the `pageload` transaction start a little earlier in the Vue routing instrumentation, allowing our SDK to add the root `ui.vue.render` span and a few missed child component spans to the now available and active transaction.
Previously, in our Vue routing instrumentation, the `pageload` transaction would only be created when the `beforeEach` hook of the Vue router was called for the first time. This worked reasonably well in Vue 2 apps where this hook was called before any components were rendered. However, in Vue 3 (Vue router v3 and v4) it seems like the routing/rendering process was changed so that the root component would be rendered before the initial `beforeEach` router hook call. 
To be clear, this change makes the `pageload` transaction always start with a `url` …
=> fix(vue): Start pageload transaction earlier to capture missing spans

packages/nextjs/src/config/webpack.ts, packages/nextjs/test/integration/src/pages/someNamedComponent.tsx
Fixes https://github.com/getsentry/sentry-javascript/issues/5978
Next.js allows users to have their `pages` directory inside a `src` directory. So far, the regex that tests if we wanna apply our auto instrumentation loader to a file, didn't consider that if a `pages` directory exists we don't want to wrap anything inside `src/pages`, because these files don't count as "pages" anymore.
This PR introduces a check if there is a root-level `pages` directory - if so, we don't wrap anything inside `src/pages`.
https://nextjs.org/docs/advanced-features/src-directory
=> fix(nextjs): Correctly apply auto-instrumentation to pages in `src` folder

.github/workflows/build.yml
The E2E tests need secrets to work (DSN and auth token), however, fork PRs don't have access to the secrets we define in this repository.
To unblock external contributions, this PR simply skips the E2E tests if the PR comes from a different repository. After merging a PR, the tests will run on master anyways.
=> test(e2e): Don't run E2E tests on fork PRs

packages/react/src/reactrouterv6.tsx, packages/react/test/reactrouterv6.test.tsx
Fixes https://github.com/getsentry/sentry-javascript/issues/5965
This PR does two things for the react router v6 instrumentation.
1. Makes sure that routes don't appear with double slashes, like with `//example` or `//my-route`. This is done with a simple check for `pathBuilder[pathBuilder.length - 1] === '/'`.
2. Make sure that wildcard imports will generate proper transaction names. For example with `/tests/123` that loads a wildcard route, render `/tests/:testId/*`. Previously with wildcard routes we would only generate the wildcard portion, so it would render `:testId/*`.
I'm still undecided if we should even keep the wildcards, but I think they are fine for now.
=> fix(react): Support root and wildcard routes in react router v6

.gitignore, packages/nextjs/package.json, packages/nextjs/src/config/types.ts, packages/nextjs/src/config/webpack.ts, packages/nextjs/test/config/fixtures.ts, packages/nextjs/test/types/.gitignore, packages/nextjs/test/types/next.config.ts, packages/nextjs/test/types/package.json, packages/nextjs/test/types/test.ts, packages/nextjs/test/types/tsconfig.json
Closes #4560
This was super nasty to fix!
I managed to fix the reported `null` issue and a couple of other minor differences too, I finally get stuck on this horror: 
```
Argument of type 'NextConfig' is not assignable to parameter of type 'NextConfigObjectWithSentry | NextConfigFunctionWithSentry | undefined'.
Type 'NextConfig' is not assignable to type 'NextConfigObjectWithSentry'.
Type 'NextConfig' is not assignable to type '{ webpack?: WebpackConfigFunction | null | undefined; target?: "server" | "experimental-serverless-trace" | undefined; distDir?: string | undefined; basePath?: string | undefined; publicRuntimeConfig?: { [key: string]: unknown; } | undefined; pageExtensions?: string[] | undefined; }'.
Types of property 'webpack' are incompatible.
Type 'NextJsWebpackConfig | null | …
```
=> fix(nextjs): Fix typing issue with `withSentryConfig` and `NextConfig`

CHANGELOG.md
WIll not include #5973 because it requires more discussion/debugging
=> meta: Update changelog for 7.16.0

packages/node/src/integrations/requestdata.ts, packages/node/src/requestdata.ts, packages/node/test/integrations/requestdata.test.ts
This makes a few small revisions to the new `RequestData` integration:
- Switch to using booleans rather than an array of keys when specifying what user data to include. This makes it match all of the other options, and is something I should have just done from the get-go. Given that the integration is new and thus far entirely undocumented, IMHO it feels safe to make what is technically a breaking change here.
- Rename the integration's internal `RequestDataOptions` type to `RequestDataIntegrationOptions`, to help distinguish it from the many other flavors of request data functions and types floating around.
- Make all properties in `RequestDataIntegrationOptions` optional, rather than using the `Partial` helper type.
- Switch the callback which actually does the data adding from being …
=> ref(node): Small `RequestData` integration tweaks

packages/nextjs/src/index.server.ts, packages/nextjs/test/index.server.test.ts, packages/node/src/sdk.ts
This adds the new `RequestData` integration to the node SDK's default integrations, in order to be able to use it in SDKs besides just nextjs. (It therefore also removes it from the nextjs SDK's specific defaults.) In cases where we haven't yet set up our request handlers to use the integration, the event processor it adds will no-op because it won't find a request object in `sdkProcessingMetadata`.
=> ref(node): Make `RequestData` integration default

CONTRIBUTING.md
Based on https://github.com/getsentry/sentry-cocoa/blob/master/CONTRIBUTING.md#pr-reviews
=> chore: Add logaf guide to CONTRIBUTING docs

packages/react/src/reactrouterv6.tsx
Supersedes https://github.com/getsentry/sentry-javascript/pull/5915'
Fixes https://github.com/getsentry/sentry-javascript/issues/5959
Fixes a type mismatch caused by change https://github.com/remix-run/react-router/pull/9366 in react-router code. Have to use `any` because of typing changes in the above PR, since we can't be backwards compatible with both versions very easily.
=> fix(react): Update types to match react router 6.4 updates

packages/node/src/integrations/requestdata.ts, packages/node/test/integrations/requestdata.test.ts, packages/serverless/src/gcpfunction/http.ts, packages/serverless/test/__mocks__/@sentry/node.ts, packages/serverless/test/gcpfunction.test.ts
This switches the GCP wrapper in the serverless SDK to use the new `RequestData` integration for adding request data to events rather than the current event processor. 
Ref: https://github.com/getsentry/sentry-javascript/issues/5756
=> ref(serverless): Use `RequestData` integration in GCP wrapper

.github/workflows/build.yml
This updates our GHA `Build & Test` workflow to use the newest version of the `codecov` action, in order to get rid of deprecation warnings from GH.
=> chore(dev): Use `codecov` v3 in GHA

packages/node/src/integrations/requestdata.ts
This fixes the casing of the default `transactionNamingScheme` value in the `RequestData` integration so that the default value is one of the accepted values.
=> fix(node): Fix default `transactionNamingScheme` value in `RequestData` integration

packages/nextjs/package.json, packages/nextjs/rollup.npm.config.js, packages/nextjs/src/config/loaders/proxyLoader.ts, packages/nextjs/src/config/loaders/rollup.ts, packages/nextjs/src/config/templates/apiProxyLoaderTemplate.ts, packages/nextjs/src/config/templates/pageProxyLoaderTemplate.ts, yarn.lock
In https://github.com/getsentry/sentry-javascript/pull/5960, we switched from writing temporary files to disk to using virtual files when creating proxy modules in the nextjs SDK's proxy loader. Though it was a good change, it didn't handle certain cases with the potential to crash a user's build process.
Specifically, rollup converts the absolute paths in the template's `import * as wrappedFile from <wrapped file>` and `export * from <wrapped file>` into relative paths, but can break them in the process, by doing things like replacing `[` and `]` with `_`.  Prior to the switch to virtual files, those relative paths only ever had one segment, and so the code compensating for rollup's weirdness only handles basenames. After the switch, the relative paths sometimes have multiple segments, …
=> Revert "ref(nextjs): Use virtual file for proxying in proxy loader (#5960)"

packages/nextjs/src/config/loaders/proxyLoader.ts, packages/nextjs/src/config/loaders/rollup.ts
This makes a few small changes to the `rollupize` function used by the nextjs SDK's proxy loader:
- Consolidate error handling in the proxy loader, rather than handling errors inside of `rollupize` and then handling an undefined `rollupize` return value in the proxy loader.
- Slightly simplify explanation of `makeAbsoluteExternalsRelative`
- Remove type hack in `getRollupInputOptions` which seems no longer to be needed. (It was never clear why it was necessary in the first place, and TS no longer seems mad when it's removed.)
- Rename `resourcePath` to `userModulePath` for clarity
The latter two changes are drawn from https://github.com/getsentry/sentry-javascript/pull/5960, to preserve them even though it is being reverted.
=> ref(nextjs): Simplify `rollupize` in proxy loader

packages/browser/src/integrations/breadcrumbs.ts
Summary of the change (@Lms24):
This PR fixes an infinite loop that would occur in Vue 3 apps with undeclared refs.
Why this happens:
1. Vue3 supports the property `ref` in the second arg of `h` method (see https://cn.vuejs.org/guide/essentials/template-refs.html)
2. When a with an undeclared variable is rendered, Vue3 will call `console.warn` to print the error stack.
3. Sentry instruments `console` (for the `BreadCrumbs` integration), and adds the message to the `Breadcrumb` with `safeJoin`.
4. `safeJoin` converts variables to string. The ref variable is a proxied object via `Proxy` by Vue. so, when `String(value)` …
=> fix(vue): Avoid Render Warning Loop in Vue3 Apps 

CONTRIBUTING.md
Update `CONTRIBUTING.md` to include some guidelines on writing commits, using issues and PRs.
[Rendered](https://github.com/getsentry/sentry-javascript/blob/fn/contribution-docs/CONTRIBUTING.md#commit-issue--pr-guidelines)
=> chore(docs): Add commit, issue & PR guidelines

packages/tracing/src/browser/backgroundtab.ts, packages/tracing/src/browser/browsertracing.ts, packages/tracing/src/browser/index.ts, packages/tracing/src/browser/metrics/index.ts, packages/tracing/src/browser/router.ts, packages/tracing/src/browser/types.ts, packages/tracing/src/browser/web-vitals/lib/getNavigationEntry.ts, packages/tracing/src/browser/web-vitals/lib/getVisibilityWatcher.ts, packages/tracing/src/browser/web-vitals/lib/initMetric.ts, packages/tracing/src/browser/web-vitals/lib/onHidden.ts
Extract `WINDOW` declaration from `index.ts` to remove circular dependency warning when building with rollup.
=> fix(tracing): Remove circular dep warning in build with `GLOBAL`

packages/nextjs/package.json, packages/nextjs/src/config/loaders/proxyLoader.ts, packages/nextjs/src/config/loaders/rollup.ts, yarn.lock
In the proxy loader used by the nextjs SDK to autowrap user code, we currently write a temporary file to disk for each proxy module we create, because by default Rollup's API expects a path to a file, not the file's contents. It's a little bit of an ugly hack, though, and can cause problems because it writes to the user's source directory rather than to their build directory.
This switches to the use of virtual files, using the `@rollup/virtual-plugin` plugin. For unclear reasons, this seems to change (and not in a good way) the base of the relative paths calculated by Rollup when transforming the proxy templates' `import * as wrappedFile from <wrapped file>` and `export * from <wrapped file>` statements. We already have to manually fix those statements, to undo the fact that Rollup …
=> ref(nextjs): Use virtual rather than temporary file for proxy module

packages/e2e-tests/package.json, packages/integration-tests/package.json, packages/node-integration-tests/package.json
Some packages did not have a volta setup, leading to potential issues when running e.g. tests there locally when a different yarn version or similar is installed globally.
=> chore: Ensure volta is setup for all packages

packages/node-integration-tests/suites/express/tracing/test.ts, packages/tracing/src/integrations/node/express.ts
I think this was missed when doing https://github.com/getsentry/sentry-javascript/issues/5837, there have been actually three occurrences of `express.middleware.xx`, only one of which was updated to `middleware.express.xx`.
=> fix(tracing): Align missing express span operation names

packages/nextjs/src/config/webpack.ts
Probably resolves https://github.com/getsentry/sentry-javascript/issues/6012
I couldn't really reproduce https://github.com/getsentry/sentry-javascript/issues/6012 but I noticed that we're applying our proxy loader to JSON files because our loader regex matches on `.js` and `.js` happens to be a substring of `.json`.
In this PR we attempt to fix this by making the loader RegExp an exact match.
=> fix(nextjs): Match loader files exactly

packages/nextjs/src/config/webpack.ts, packages/nextjs/test/config/fixtures.ts, packages/nextjs/test/config/webpack/constructWebpackConfig.test.ts
This removes the `pagesDirectory` variable in the nextjs SDK's `constructWebpackConfigFunction` function, as its computed value matches that of `pagesDir` a few lines above, which we read from nextjs config.
=> ref(nextjs): Remove redundant `pagesDirectory` variable in webpack config

packages/vue/src/router.ts, packages/vue/test/router.test.ts
As brought to our attention in #6048, our pageload transaction start change (which makes the transaction start earlier) introduced in #5983 caused custom transaction names to be overwritten when `beforeNavigate` is used to update the transaction name. 
This patch fixes this problem by checking for the transaction source before (not) updating the current transaction name with the resolved route name once the router's `beforeEach` hook was called. Furthermore, it adds a test to cover this case. 
See https://github.com/getsentry/sentry-javascript/pull/6048#issuecomment-1293083543 for the motivation for creating this PR.
=> fix(vue): Don't overwrite custom transaction names of pageload transactions

packages/node/src/requestdata.ts, packages/remix/src/utils/instrumentServer.ts, packages/remix/src/utils/serverAdapters/express.ts, packages/remix/test/integration/test/server/action.test.ts, packages/types/src/scope.ts
This enables the new `RequestData` integration in the remix SDK in order to add request data to server-side events. The integration itself is already installed automatically when the SDK initializes, because it's one of the underlying node SDK's default integrations, but without access to the request, it currently no-ops. This enables it to function as intended by storing the request object in the scope's `sdkProcessingMetadata`.
=> feat(remix): Enable `RequestData` integration for server-side requests

packages/tracing/src/browser/request.ts
Ap per Katie's summary [here](https://github.com/getsentry/sentry-javascript/issues/5285#issue-1277144511), tracing origins should not be considered when creating spans. 
|   |  `tracingOrigins` match  |  no `tracingOrigins` match |
|---|---|---|
|   `shouldCreateSpanForRequest` returns `true`  |  ✅  |   ❌ * |
|   `shouldCreateSpanForRequest` returns `false`  |  ❌ | ❌  |
|  `shouldCreateSpanForRequest` is undefined  |  ✅  |  ❌ * |
* These are incorrect and should result in span creation. In that case, `tracingOrigins` does not matter.
|   |  Create span?  |
|---|---|
|   `shouldCreateSpanForRequest` returns `true`  |  ✅  |  
|   `shouldCreateSpanForRequest` returns `false`  |  ❌ | 
|  `shouldCreateSpanForRequest` is undefined  |  ✅  |
=> fix(tracing): Don't consider `tracingOrigins` when creating spans

.craft.yml
This should make it so we only publish `@sentry/opentelemetry-node` if it is marked as public.
=> fix: Add otel-node package to craft

.github/workflows/build.yml
Previous attempts to not run E2E tests on PRs didn't work so here we go again. We do this because we cannot run the E2E tests on forks because they require secrets that GitHub doesn't provide in fork actions.
This PR was done via fork so we can actually confirm this is working.
=> ci(e2e): Don't run E2E tests on forked PRs

.craft.yml
As per https://github.com/getsentry/sentry-javascript/pull/6065#discussion_r1006863672
=> fix: Don't publish @sentry/opentelemetry-node on NPM

.craft.yml, CHANGELOG.md
We need to do this to stop the registry release from failing, but waiting till NPM publishes on https://github.com/getsentry/publish/issues/1513
This also updates the changelog to `7.17.1` to prep another release.
=> fix: remove otel from the registry

packages/tracing/src/browser/request.ts, packages/tracing/test/browser/request.test.ts
In the process of working on https://github.com/getsentry/sentry-javascript/issues/5285, we missed the fact that the first two PRs (https://github.com/getsentry/sentry-javascript/pull/6039 and https://github.com/getsentry/sentry-javascript/pull/6041) were interdependent, in that the former accidentally introduced a bug (https://github.com/getsentry/sentry-javascript/issues/6077) which the latter then inadvertently fixed. This would have been fine, except that we published a release after merging the bug-creating PR but before merging the bug-fixing PR. Whoops.
This pulls just the bug-fixing part out of the second PR. It also adds tests to cover the buggy cases, using `it.each` to cover all of the different combinations of outcomes for `shouldCreateSpanForRequest` and …
=> fix(tracing): Fix `tracingOrigins` not applying

packages/nextjs/src/config/wrappers/withSentryAPI.ts
Closes: #3852 
Looks like #3852 is resolved by #5778, which is published with [`7.14.0`](https://github.com/getsentry/sentry-javascript/releases/tag/7.14.0).
We have been logging a warning to point out that Next.JS's warning is a false positive, but it seems not necessary anymore unless the user prefers disabling auto-wrapping and uses `withSentry` wrapper manually.
This PR updates the warning message and ensures it's only logged when the request is not yet finished, before the result is returned.
=> fix(nextjs): Log false positive warning only if request is unfinished.

packages/opentelemetry-node/package.json, packages/opentelemetry-node/src/spanprocessor.ts, packages/opentelemetry-node/src/utils/map-otel-status.ts, packages/opentelemetry-node/test/spanprocessor.test.ts
Enhance sentry transactions/spans/context with data from OpenTelemetry spans, when using otel-integration.
Summary:
* otel `attributes`, `resource` for transaction --> sentry `context`
* otel `attributes`, `kind` for span --> sentry `data`
* otel `status` + data from `attributes` --> sentry `status` (for both transactions & spans)
Part of https://github.com/getsentry/sentry-javascript/issues/6000
=> feat(otel): Map otel span data to Sentry transaction/span/context

packages/ember/index.js
When defining Sentry config in `ENV['@sentry/ember'].sentry`, this goes through @embroider/macros under the hood. This relies on config being serializable, which means that e.g. you cannot use regex in the config.
To make this easier to pin down (as the error message can be a bit cryptic), this now validates the passed config (based on https://github.com/embroider-build/embroider/pull/1083) and shows a helpful warning message.
Produces this now:
```
> ember s
Warning: You passed a non-serializable config to `ENV['@sentry/ember'].sentry`. Non-serializable config (e.g. RegExp, ...) can only be passed directly to `Sentry.init()`.
```
Where the second 
Note that I also moved this around a bit, leading to config being written only once on build, which should be a bit faster.
Eventually, we may …
=> chore(ember): Show warning when using invalid config

packages/tracing/src/browser/web-vitals/getCLS.ts
It's still not immediately clear what causes #6083 since I've been unable to reproduce this locally however it's been reported by numerous users.
Before the upgrade to web vitals v3, there was [an additional check](https://github.com/getsentry/sentry-javascript/blob/5386ce73e4ffa897bfe0ab039552f745066e92ea/packages/tracing/src/browser/web-vitals/getCLS.ts#L54-L59) here so this PR adds that back.
=> fix(tracing): Add an extra conditional check to web vitals `onCLS()`

CHANGELOG.md
cut a release to address web vitals bug in https://github.com/getsentry/sentry-javascript/issues/6083
=> meta: CHANGELOG for 7.17.3

packages/nextjs/src/utils/instrumentServer.ts
Fixes #6059
Attempts to fix a bug where we try to grab the prototype of the Next.js server even though it hasn't been created yet. I couldn't repro this locally - I think this might be due to a race condition.
I believe (emphasis on "believe") it is safe to call `getServer` inside of the `getServerRequestHandler` function because Next.js itself calls it in there: https://github.com/vercel/next.js/blob/0beed3563cdab846fd6b683f1ed5586de3e7d96d/packages/next/server/next.ts#L175
=> fix(nextjs): Await Next.js server in patched `getServerRequestHandler`

packages/nextjs/package.json, packages/nextjs/src/config/webpack.ts, yarn.lock
Fixes #4829
This PR supersedes #6015 which attempted to fix the issue without fixing the underlying issues in the dependencies.
This PR updates `@sentry/webpack-plugin` to the latest version and then uses the new `SentryWebpackPlugin.cliBinaryExists()` function.
This has no issues with `@vercel/nft` since the latest version of `@sentry/cli` now uses code that avoids this issue and is tested against regressions.
=> fix(nextjs): CLI binary not found on Windows

packages/serverless/src/awslambda.ts
fixes #5412 
goes with https://github.com/getsentry/action-build-aws-lambda-extension/pull/6
=> fix(aws): Move relay to port 5333 to avoid collisions

.github/workflows/build.yml
This should address GitHub deprecation warnings
=> ci: Update size-limit-action to v5

packages/nextjs/src/config/loaders/prefixLoader.ts, packages/nextjs/src/config/loaders/proxyLoader.ts
Closes #6085
I suppose it was inevitable that an issue with Windows was an issue with paths!
This PR escapes the backslashes in the paths before they're written to the templates.
=> fix(nextjs): Escape Windows paths when writing wrapper templates

.github/workflows/build.yml
This PR corrects for the fact that E2E tests didn't run on anything other than PRs.
=> ci(e2e): Run E2E tests on non-PR triggers

packages/opentelemetry-node/package.json, yarn.lock
ref: https://github.com/getsentry/sentry-javascript/issues/6107
Not a 100% sure about adding this as a peer dep, since this will by included as a child dep of [`@opentelemetry/sdk-trace-base`](https://www.npmjs.com/package/@opentelemetry/sdk-trace-base)
=> feat(otel): Add `@opentelemetry/core` package

packages/opentelemetry-node/src/spanprocessor.ts, packages/opentelemetry-node/src/utils/parse-otel-span-description.ts, packages/opentelemetry-node/test/spanprocessor.test.ts
This bundles a few otel span processor updates.
ref https://github.com/getsentry/sentry-javascript/issues/6112
=> feat(otel): Updates to otel span processor

packages/opentelemetry-node/src/constants.ts, packages/opentelemetry-node/src/index.ts, packages/opentelemetry-node/src/propagator.ts, packages/opentelemetry-node/test/propagator.test.ts
ref: https://github.com/getsentry/sentry-javascript/issues/6107
Previous implementation: https://github.com/getsentry/sentry-javascript/issues/6107 (yes propagator is spelled wrong everywhere in that PR lol)
Adds base `SentryPropagator` class. In the PRs after this we will add implementations for `inherit` and `extract`
=> feat(otel): Add base SentryPropagator class

packages/opentelemetry-node/src/propagator.ts, packages/opentelemetry-node/src/spanprocessor.ts, packages/opentelemetry-node/test/propagator.test.ts, packages/opentelemetry-node/test/spanprocessor.test.ts
ref https://github.com/getsentry/sentry-javascript/issues/6107
Inject `sentry-trace` and `baggage` headers into context so it's gets propagated on outgoing requests. Very similar to approach taken with https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-propagator-b3/src/B3SinglePropagator.ts
=> feat(otel): Add inject functionality to SentryPropagator

packages/opentelemetry-node/package.json, packages/opentelemetry-node/src/spanprocessor.ts, packages/opentelemetry-node/src/utils/is-sentry-request.ts, packages/opentelemetry-node/test/spanprocessor.test.ts
With the basic setup of the SpanProcessor, you can get into an infinite loop quickly:
* You have some OTEL auto-instrumentation set up
* This auto-instrumentation captures outgoing HTTP requests (e.g. `@opentelemetry/instrumentation-http`)
* You setup the Sentry<>OTEL integration
* For any OTEL span created, we capture this to Sentry
* This is sent to Sentry as an outgoing HTTP request
* Which again is captured by the OTEL auto-instrumentation, ....
The "cleanest" way to avoid this is to setup your auto-instrumentation to skip Sentry requests, e.g.:
```js
const sdk = new opentelemetry.NodeSDK({
traceExporter: new OTLPTraceExporter(),
instrumentations: [ 
getNodeAutoInstrumentations({
// load custom configuration for http instrumentation
'@opentelemetry/instrumentation-http': { …
```
=> feat(otel): Ignore outgoing Sentry HTTP requests from otel integration

packages/opentelemetry-node/src/spanprocessor.ts
Fixes broken master branch: https://github.com/getsentry/sentry-javascript/actions/runs/3379049972
=> fix(otel): Use global map instead of old map var

packages/remix/src/utils/instrumentServer.ts, packages/remix/test/integration/app/routes/action-json-response/$id.tsx, packages/remix/test/integration/test/server/action.test.ts
Closes: #5963
The reason we have been getting exceptions from Remix SDK captured as, `{}` even if the response is not an empty object (see: #5963) was apparently the pending Promises returned from `extractData`.
Implemented the async logic and added another abstraction specifically for error responses, to make sure the errors do not end up misnamed.
Based on Remix examples of [how to throw a `json(...)`](https://github.com/remix-run/remix/blob/471ab259fba5adbdd70de71ee7bc7e874c1f4db9/docs/api/conventions.md), this implementation favours:
1 - `response` (if `response` is a `string`)
2 - `response.statusText`
3 - The extracted `response` object, which will eventually be handled by [Node SDK's `eventbuilder`](https://github.com/getsentry/sentry-javascript/blob/4aff9f14bee54a65105c2ec65170ecef …
=> fix(remix): Prevent capturing pending `Promise`s as exceptions.

packages/nextjs/test/integration/test/client/tracingClientGetInitialProps.js, packages/nextjs/test/integration/test/client/tracingClientGetServerSideProps.js, packages/nextjs/test/integration/test/client/tracingDynamicRoute.js, packages/nextjs/test/integration/test/client/tracingFetch.js, packages/nextjs/test/integration/test/client/tracingNavigate.js, packages/nextjs/test/integration/test/client/tracingPageLoad.js
Partly adresses https://github.com/getsentry/sentry-javascript/issues/6053
I guess there is a possibility that requests go out in between the `page.goto()` calls and the `page.waitForRequest()`, causing us to wait for the latter indefinitely.
If we await the request before we go to the page, there is no way a request is sent before `page.waitForRequest()` is called.
=> test(nextjs): Attempt to make Next.js integration tests less flakey

packages/node/src/sdk.ts, packages/node/src/types.ts, packages/node/test/index.test.ts, packages/types/src/index.ts, packages/types/src/instrumenter.ts, packages/types/src/options.ts
Add a new option `instrumenter` to the the client options, which can be `sentry` or `otel` and defaults to `otel`.
Nothing is done with that option _yet_, this will happen in follow up PRs.
It will only have an effect when being set in the node SDK.
ref https://github.com/getsentry/sentry-javascript/issues/6127
=> feat(core): Add `instrumenter` option to `ClientOptions`

packages/tracing/src/browser/request.ts
As part of the work on https://github.com/getsentry/sentry-javascript/issues/5285, this adds a new option, `tracePropagationTargets`, to our browser-side tracing instrumentation, to live alongside (and eventually take the place of) `tracingOrigins`. Its behavior matches that of `tracingOrigins`, but it has a much clearer name.
Switching from internal use of `tracingOrigins` to `tracePropagationTargets` to come in future PRs.
_Note: This is what remained of https://github.com/getsentry/sentry-javascript/pull/6041 after the fix in https://github.com/getsentry/sentry-javascript/pull/6079 was split off. h/t @timfish for the initial work in that PR._
=> feat(tracing): Add `tracePropagationTargets` option to browser routing instrumentation

packages/nextjs/src/index.server.ts, packages/nextjs/src/utils/userIntegrations.ts, packages/nextjs/test/utils/userIntegrations.test.ts
In the nextjs SDK, the `addOrUpdateIntegration` function exists to force the inclusion of certain integrations with certain options set. If such an integration is included in the underlying SDK's default integrations, however, (in other words, if it's included in the defaults set by `@sentry/browser` or `@sentry/node`), it's possible for the user to have actively chosen to exclude it, which we would then be overriding. This PR adds to the `addOrUpdateIntegration` logic to provide the ability to respect that choice.
The only way for a user to choose to filter out a default integration is by providing a function as their `integrations` option in `Sentry.init()`. Therefore, when handling the function case,  we can check if a given integration is included in the return value, and if it's not, …
=> fix(nextjs): Allow `onUncaughtException` integration to remain excluded

packages/tracing/src/span.ts, packages/tracing/test/span.test.ts, packages/tracing/test/transaction.test.ts, packages/types/src/span.ts, packages/types/src/transaction.ts
A span & transaction now have a field `instrumenter` that can be used to check where a the span/transaction was created.
This defaults to `sentry`.
In later steps, we can use this information to react internally based on SDK config.
ref https://github.com/getsentry/sentry-javascript/issues/6127
=> feat(tracing): Allow to set `instrumenter` on Span & Transaction

packages/node/src/handlers.ts, packages/node/src/integrations/http.ts, packages/node/test/helper/node-client-options.ts, packages/node/test/integrations/http.test.ts, packages/tracing/src/integrations/node/apollo.ts, packages/tracing/src/integrations/node/express.ts, packages/tracing/src/integrations/node/graphql.ts, packages/tracing/src/integrations/node/mongo.ts, packages/tracing/src/integrations/node/mysql.ts, packages/tracing/src/integrations/node/postgres.ts, packages/tracing/src/integrations/node/prisma.ts, packages/tracing/src/integrations/node/utils/node-utils.ts, packages/tracing/test/integrations/apollo.test.ts, packages/tracing/test/integrations/graphql.test.ts, packages/tracing/test/integrations/node/mongo.test.ts, packages/tracing/test/integrations/node/postgres.test.ts, packages/tracing/test/integrations/node/prisma.test.ts, packages/tracing/test/testutils.ts
With this PR, when `instrumenter: 'otel'` is configured in the Node SDK, any auto-instrumentation that generates transactions is skipped.
This is a bit tricky to test, so I created a separate PR for the tests, if we don't like the approach: https://github.com/getsentry/sentry-javascript/pull/6143
ref https://github.com/getsentry/sentry-javascript/issues/6127
=> feat(otel): Disable node tracing auto instrumentation when using otel

packages/core/src/scope.ts
Based on feedback from https://github.com/getsentry/sentry-javascript/pull/6154#discussion_r1016704391
Remove spread operator usage when setting new context so we mutate the current reference instead of creating a new object. Should reduce bundle size and be slightly more performant.
=> perf(core): Prevent creation of new contexts object on scope

packages/opentelemetry-node/test/spanprocessor.test.ts, packages/tracing/src/transaction.ts, packages/tracing/test/transaction.test.ts, packages/types/src/transaction.ts
This is needed for the OpenTelemetry Span Processor. Same behaviour as `scope.setContext` here: https://github.com/getsentry/sentry-javascript/blob/351be067ac7ff280155c128011f79dac9caf6475/packages/core/src/scope.ts#L257-L270
One thing to note, we don't want users to override `trace` context, so we set that here.
=> feat(tracing): Add `transaction.setContext` method

packages/core/test/lib/base.test.ts
Per @Lms24's [suggestion](https://github.com/getsentry/sentry-javascript/pull/6121#discussion_r1013750616), this adds a check to make sure the relevant function is being called in our `beforeSend` and `beforeSendTransaction` tests.
=> fix(core): Check that functions have been called in `beforeSend` and `beforeSendTransaction` tests

packages/opentelemetry-node/src/spanprocessor.ts, packages/opentelemetry-node/test/spanprocessor.test.ts
Previously, due to timing issues with async event processors the context was sometimes not set properly.
As a side effect, that also makes testing this way nicer, yayy!
=> fix(otel): Ensure we properly set the context for transactions

.github/workflows/build.yml
This PR updates the build to only run the "special" CI test jobs when the respective packages have actually changed.
This is done using https://github.com/getsentry/paths-filter with a simple list of directories to watch. We can use the handy `shared` functionality to avoid duplicating the "global" dependencies.
Note that we _do_ need to keep the internal dependencies in sync (e.g. if nextjs starts to depend on another internal package, we need to add it), but IMHO that is acceptable.
This is how that looks:
Replaces https://github.com/getsentry/sentry-javascript/pull/6067
=> chore(ci): Only run CI tests when related files changed

packages/opentelemetry-node/src/propagator.ts, packages/opentelemetry-node/src/spanprocessor.ts
Previously the Sentry Propagator was setting the sample rate on the opentelemetry span context based on the incoming traceparent from `sentry-trace`. This is problematic because it a span is unsampled, it does not enter a span processor. This means that we could create transactions erroneously (for example, unnecessarily promote a child span to a transaction).
To fix this, we move the sampling decision from the propagator to the span processor.
=> fix(otel): Remove sampling decision in propagator

packages/opentelemetry-node/src/spanprocessor.ts, packages/opentelemetry-node/src/utils/parse-otel-span-description.ts, packages/opentelemetry-node/test/spanprocessor.test.ts
Define transaction source on transactions depending on what semantic attributes are being used. See https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#http-server-semantic-conventions.
Related: https://github.com/open-telemetry/opentelemetry-demo/pull/566
=> fix(otel): Add transaction source logic to otel spans

.github/workflows/build.yml
As these jobs are currently required to merge PRs.
We should figure out a better solution for this, but for now this unblocks merging PRs.
=> chore(ci): Always run Next.js & Node SDK tests

packages/opentelemetry-node/src/spanprocessor.ts, packages/tracing/src/hubextensions.ts, packages/tracing/test/hub.test.ts
This is the last piece for the otel integration. It relies on https://github.com/getsentry/sentry-javascript/pull/6144.
Basically, when a transaction is started with an instrumenter that does not match the configured instrumenter of the client, it will ensure it is never sampled, and log an error message.
ref https://github.com/getsentry/sentry-javascript/issues/6127
=> feat(otel): Handle inconsistent `instrumenter` option

packages/ember/tests/acceptance/sentry-performance-test.js
We already had some logic to make test less brittle, but the runloop is a bit unstable, and thus hard to test. So it is easier to just don't test the runloop execution in detail, especially since these are the least interesting spans, and focus on testing the important parts (that are also more stable).
=> chore(ember): Make tests less brittle

packages/remix/README.md
Seems like we forgot to change this here when we merged in https://github.com/getsentry/sentry-docs/pull/5411
=> chore(remix): Remove alpha note from README

packages/opentelemetry-node/README.md
ref https://github.com/getsentry/sentry-javascript/issues/6000
Add an alpha note that indicates that this package is experimental (for now!)
=> chore(otel): Update README to add alpha note

packages/react/src/errorboundary.tsx, packages/react/test/errorboundary.test.tsx
fixes https://github.com/getsentry/sentry-javascript/issues/6167
Although `componentDidCatch` is typed to accept an `Error` object, it can also be invoked with non-error objects. This is why we need to check if the error is an error-like object.
=> fix(react): Guard against non-error obj in ErrorBoundary

.craft.yml
ref: #6000 
Stop excluding the otel package for release stuff.
=> chore: Update craft config in preparation for otel release

packages/nextjs/src/index.client.ts, packages/tracing/src/browser/browsertracing.ts, packages/tracing/src/browser/request.ts, packages/tracing/test/browser/browsertracing.test.ts
Ref #5285 
This PR:
- Deprecates `tracingOrigins` and points out the new properties that replace it
- Removes the warning for no supplied `tracingOrigins`
- Removes the tests for the warning
My best guess is the logged warning about no supplied `tracingOrigins` was due to the fact that it's default limited span creation and the default might not be relaxed enough. Since now span creation in controlled by `shouldCreateSpanForRequest` which defaults to always creating spans, this warning seems redundant.  Users are now only likely to seek out tracing options to reduce the number of spans or stop header attachment if it's causing them CORS issues.
=> ref(tracing): Deprecate `tracingOrigins`

packages/integrations/src/offline.ts, packages/integrations/src/reportingobserver.ts
Fixes #6183
These ended up in the TypeScript definitions because they are exported but they should never have been exported!
=> fix(integrations): Remove erroneous WINDOW exports

packages/opentelemetry-node/package.json
Ah, just noticed, I forgot about this 😬 should be merged before https://github.com/getsentry/sentry-javascript/pull/6186 I guess!
=> chore(otel): Make @sentry/opentelemetry-node public

.github/workflows/build.yml
This adds a new job that doesn't do anything, that runs after all required test matrix jobs.
With this in place, we can remove the requirement of the nextjs, test & node integration matrix tests, and instead only make this one job required. This should then also handle skipped jobs (hopefully).
We can start with making _both_ required (so just add requirement on this new job), then when we see it works remove the requirement on the specific matrix jobs.
After some trial and error, we figured out that we need some further adjustments for this to work as expected.
* A job that is marked as required counts as passed whenever it is not failed
* This means that if the job is skipped, it will pass the required check
* A job that depends on another job will be considered skipped when the …
=> chore(ci): Add new Ci job that runs after required test jobs

.gitignore, CONTRIBUTING.md, docs/new-sdk-release-checklist.md
Following up on a recent incident we had when releasing the Node OTEL package, we decided to port the release checklist for first-time releases of new SDKs from Notion to our SDK repo directly. This PR does exactly that. 
I opted to put it under a `docs` folder as we recently discussed that we might want to split large docs (e.g. migration guide) up in the future. Generally, I think it makes sense to have a docs folder. 
ref: https://getsentry.atlassian.net/browse/WEB-980
=> chore(docs): Add "New SDK Release Checklist" from Notion

packages/core/src/integrations/inboundfilters.ts, packages/node/src/integrations/http.ts, packages/tracing/src/browser/request.ts, packages/utils/src/string.ts, packages/utils/test/string.test.ts
This adds a new utility function, `stringMatchesSomePattern`, which tests a string against an entire array of strings and/or regexes at once (which is something we do in a number of spots in the SDK). It also adds an optional parameter to `isMatchingPattern` to allow the string matching to be exact rather than a substring match.
The primary purpose of adding this is to make code a little easier to read. (I had hoped it would also possibly save us a few bytes, and adding the helper function does, but unfortunately that's canceled out by the new exact-match option, so in the end it's more or less a wash on that score.)
=> feat(util): Add `stringMatchesSomePattern` helper function.

packages/nextjs/src/config/webpack.ts, packages/nextjs/test/config/fixtures.ts, packages/nextjs/test/config/webpack/constructWebpackConfig.test.ts
In nextjs, all non-API pages (other than sometimes `_error`)  include the `_app` component. Up until now, we've leveraged this fact when deciding which webpack entrypoints should have `sentry.server.config.js` injected during serverside build; specifically, we inject into `_app`, `_error`, and all API handlers, but not any other non-API pages.
This works fine, but it means that if we want to be able to pick and choose _which_ non-API pages get the config file injected, we're out of luck. Either we inject into `_app` (and therefore all non-API pages) or we don't (and therefore no non-API pages). In order to allow selective injection (which will be included in an upcoming PR), this inverts the logic: instead of `_app` being the only non-API page into which we inject, it is now one of the …
=> ref(nextjs): Invert serverside injection criteria

packages/nextjs/src/config/loaders/proxyLoader.ts, packages/nextjs/src/config/types.ts, packages/nextjs/src/config/webpack.ts, packages/nextjs/test/config/webpack/constructWebpackConfig.test.ts, packages/nextjs/test/integration/next.config.js, packages/nextjs/test/integration/next10.config.template, packages/nextjs/test/integration/next11.config.template, packages/nextjs/test/integration/pages/api/excludedEndpoints/excludedWithRegExp.tsx, packages/nextjs/test/integration/pages/api/excludedEndpoints/excludedWithString.tsx, packages/nextjs/test/integration/test/server/excludedApiEndpoints.js
Currently, in the nextjs SDK, we inject the user's `Sentry.init()` code (by way of their `sentry.server.config.js` file) into all serverside routes. This adds a new option to the `sentry` object in `next.config.js` which allows users to prevent specific routes from being instrumented in this way. In this option, excluded routes can be specified using either strings (which need to exactly match the route) or regexes.
Note: Heavily inspired by https://github.com/getsentry/sentry-javascript/pull/6125. h/t to @lforst for his work there. Compared to that PR, this one allows non-API routes to be excluded and allows excluded pages to be specified as routes rather than filepaths. (Using routes a) obviates the need for users to add `pages/` to the beginning of every entry, b) abstracts away the …
=> feat(nextjs): Add `excludeServerRoutes` config option

packages/serverless/README.md
This patch fixes an incorrect path for requiring the auto-init script in the `@sentry/serverless` Readme for users who want to set up the layer via the ARN and environment variables. Furthermore, this patch slightly enhances the step to find the correct ARN by linking to our (still kinda broken) ARN dropdown in the docs. 
resolves #6204
=> chore(serverless): Fix incorrect path in Readme

packages/nextjs/src/config/webpack.ts, packages/nextjs/test/config/webpack/sentryWebpackPlugin.test.ts
In nextjs, the output directory (`distDir`) is specified by the user and stored in memory as a relative path. It's then used in two places:
- At build time, it's resolved against the project directory, in order to know where to output built files.
- At runtime, it's resolved against the working directory, in order to know where to find those built files.
In the nextjs SDK, we also use the value in two places:
- At build time, we pass it to `@sentry/cli` via Sentry webpack plugin options. `sentry/cli` then resolves it against its working directory, so that it knows where to find built files to upload.
- At runtime, we grab it from `global.__rewriteFramesDistDir__` (where we've stashed it at build time via our prefix loader), and then resolve it against the working directory, so the …
=> fix(nextjs): Use absolute path for `distDir` in webpack plugin options

packages/remix/src/performance/client.tsx, packages/remix/src/utils/instrumentServer.ts, packages/remix/src/utils/types.ts, packages/remix/src/utils/web-fetch.ts, packages/remix/test/integration/test/server/action.test.ts
Ref: #6139 and https://github.com/getsentry/sentry-javascript/issues/6139#issuecomment-1315799722
This PR is not a complete solution for all issues mentioned in #6139, but it aims to solve the parsing issue, which should fix auto-instrumented usage.
Remix uses [its own implementation of Fetch API](https://github.com/remix-run/web-std-io/tree/main/packages/fetch) on both back-end and front-end, which has different structures storing `headers` and `url`. That has caused `RequestData` integration to not work properly on Remix projects.
I first attempted adding support to the core parser, and `PolymorphicRequest`. But it seemed very complex (if possible), because we have to type Proxy objects and Symbols, which our current TypeScript version doesn't fully support.
So, I vendored / modified a …
=> fix(remix): Resolve Remix Request API compatibility issues.

packages/angular/package.json
This PR adds Angular 15 support by adding `15.x` as a peer dependency version for the Angular packages. A quick test suggests that all previous features seem to work as usual. Still have to do some experiments with new NG15 features but for now we can at least add basic support and unblock anyone who wants to update to v15. 
ref #6219
=> feat(angular): Add Angular 15 Peer Dependencies

packages/angular/src/tracing.ts
This PR fixes a bug in the Angular SDK's `TraceDirective` where previously, the fallback `UNKNOWN_COMPONENT` name wasn't correctly applied to the span description if users didn't specify a manual value for the directive:
```html
<app-my-component trace="standalone1"></app-my-component>
<app-my-component trace></app-my-component>
``` 
Stumbled across this while testing v15 standalone components so... ref #6219 
The reason for this bug is that Angular apparently doesn't entirely respect default values for inputs of directives that have the same name as the directive (but we def want this). 
Note: We do actually [have a test for this](https://github.com/getsentry/sentry-javascript/blob/0ee35f070927b47a37270d6037a3f004f3bce492/packages/angular/test/tracing.test.ts#L263-L265) and according to …
=> fix(angular): Set `unknown` component name default in `TraceDirective`

packages/core/src/scope.ts
When I added the `_sdkProcessingMetadata` field to `Scope`, I missed adding it to the `clone` method. This fixes that.
Addresses the `withScope` problem mentioned in https://github.com/getsentry/sentry-javascript/issues/6139#issuecomment-1310839406. (TL;DR - the stored request upon which the `RequestData` integration relies was getting lost when `withScope` was called, which in turn meant that no request data was coming through.)
=> fix(core): Include `_sdkProcessingMetadata` when cloning scope

.github/dependabot.yml
While it makes sense for us to not run dependabot for general dependencies, we should be able to run it for Github Actions at least. This will create PRs once a month for any GHA that has a newer version available. (e.g. update `@actions/checkout@v3` to `@actions/checkout@v4` or similar stuff).
See: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
=> ci(deps): Setup dependabot for Github Actions

.github/dependabot.yml
Apparently, github only validates the dependabot config _after_ merging it 🤦 
See https://github.com/getsentry/sentry-javascript/pull/6227/checks?check_run_id=9569642709. Apparently there is no real way to check this beforehand.
=> ci: Fix dependabot config

packages/vue/package.json, packages/vue/src/sdk.ts, packages/vue/test/integration/init.test.ts, yarn.lock
This PR adds an error log when trying to mount the vue app BEFORE the sentry SDK is initialized.
I was thinking about if this should be `console.error` or `logger.error`, but since this can lead to silent failures/issues (e.g. sentry may simply not pick up some errors), I'd argue it's fine to actually always log them out - otherwise, chances are users will not notice anyhow.
This uses somewhat internal stuff, but since we can literally check on `=== true` this should degrade very gracefully in that it otherwise simply doesn't log anything.
Closes https://github.com/getsentry/sentry-javascript/issues/6226
If you have code like this:
```vue
// App.vue
<script setup>
// This starter template is using Vue 3 <script setup> SFCs
// Check out …
```
=> feat(vue): Check if SDK is initialized before app is mounted

.github/workflows/build.yml
As they lack access to secrets, we have to skip the E2E tests when running on a dependabot PR.
=> ci: Do not run E2E tests for dependabot PRs

.github/workflows/build.yml, .github/workflows/canary.yml, package.json
This updates the node version we use internally from 14.x to 16.x.
Note that node support policy remains the same (and is tested), so nothing should change externally.
While at it, I also updated CI to actually use volta to setup node. This way, we can use a centralized place to specify the node version for dev & ci.
=> build: Update (internal) node version to 16.x

.github/workflows/build.yml
Currently, because of the logic of the "required jobs passed" meta-CI-job, we only check direct dependends of this job for success. This means that if the `build` job fails, and all the jobs following this are skipped because of this, it pretends to be "OK", which it is not:
The solution is to add the build job to `needs` for the required job.
=> ci: Make `job_build` required to pass

packages/tracing/src/browser/request.ts, packages/tracing/test/browser/request.test.ts
This PR fixes a bug in our `shouldAttachHeaders` function that determines internally if outgoing requests should have headers attached or not. 
Previously, we assigned the default values to `tracingOrigins` as well as `tracePropagationTargets` and overwrote these defaults, if users provided one (or (unlikely) both) options. In `shouldAttachHeaders`, we then first tested `tracingOrigins` for a match and in case there was no match, we'd test `tracePropagationTargets`.  This, however, also meant that if users specified `tracingOrigins` and an URL didn't match them, there was still a chance that headers would be attached - in case the url matched the `tracePropagationTargets`' default values.
With this fix, we don't assign default values to either option but check for definedness of them and …
=> fix(tracing): Make `shouldAttachHeaders` not fall back to default values

.github/workflows/build.yml
As pointed out by @AbhiPrasad, the size check action on CI has not been properly running since we merged https://github.com/getsentry/sentry-javascript/pull/6180.
After some investigation, I think I've pinned the culprit down:
Basically, in that PR I "fixed" an `if` condition for the size limit action job. Previously, because the condition had a wrong syntax, it was _always_ running.
```
if: ${{ github.event_name == 'pull_request' }} || ${{ startsWith(github.ref, 'refs/heads/master/') }}
```
This was incorrect because either we need to wrap the _whole_ expression with `${{ }}`, or none of it (as `if` auto-wraps it). With the original statement, it always evaluated to a truthy expression.
So I "fixed" the syntax, however didn't notice that one part of the check was incorrect:
```
if: …
```
=> ci: Fix size check action to run on master

packages/core/src/baseclient.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/5229#issuecomment-1322748113
We need to check for the existence of `finalScope.getAttachments` because `getAttachments` can be undefined if users are using an older version of `@sentry/core` that does not have the `getAttachments` method.
=> fix(core): Add guard against `scope.getAttachments`

packages/integration-tests/suites/tracing/browsertracing/tracePropagationTargets/customTargets/init.js, packages/integration-tests/suites/tracing/browsertracing/tracePropagationTargets/customTargets/subject.js, packages/integration-tests/suites/tracing/browsertracing/tracePropagationTargets/customTargets/test.ts, packages/integration-tests/suites/tracing/browsertracing/tracePropagationTargets/customTargetsAndOrigins/init.js, packages/integration-tests/suites/tracing/browsertracing/tracePropagationTargets/customTargetsAndOrigins/subject.js, packages/integration-tests/suites/tracing/browsertracing/tracePropagationTargets/customTargetsAndOrigins/test.ts, packages/integration-tests/suites/tracing/browsertracing/tracePropagationTargets/customTracingOrigins/init.js, packages/integration-tests/suites/tracing/browsertracing/tracePropagationTargets/customTracingOrigins/subject.js, packages/integration-tests/suites/tracing/browsertracing/tracePropagationTargets/customTracingOrigins/test.ts, packages/integration-tests/suites/tracing/browsertracing/tracePropagationTargets/defaultTargetsMatch/init.js, packages/integration-tests/suites/tracing/browsertracing/tracePropagationTargets/defaultTargetsMatch/subject.js, packages/integration-tests/suites/tracing/browsertracing/tracePropagationTargets/defaultTargetsMatch/test.ts, packages/integration-tests/suites/tracing/browsertracing/tracePropagationTargets/defaultTargetsNoMatch/init.js, packages/integration-tests/suites/tracing/browsertracing/tracePropagationTargets/defaultTargetsNoMatch/subject.js, packages/integration-tests/suites/tracing/browsertracing/tracePropagationTargets/defaultTargetsNoMatch/test.ts, packages/tracing/src/browser/browsertracing.ts, packages/tracing/src/browser/request.ts, packages/tracing/test/browser/browsertracing.test.ts, packages/tracing/test/browser/request.test.ts
This PR fixes a bug in our `BrowserTracing` integration which caused the new `tracePropagationTargets` option not to be passed to `instrumentOutgoingRequests` where it was needed to decide if our tracing headers should be attached to outgoing requests or not. 
Because we never passed this value to the instrumentation function, custom-defined `tracePropagationTargets` values were not respected by the SDK and headers were attached to requests whose URLs matched the default targets or custom specified `tracingOrigins`. 
With this PR, we also make a change how we internally handle the co-existance between the deprecated `tracingOrigins` and `tracePropagationTargets` options. We now simply overwrite the default `tracePropagationTargets` values with custom `tracingOrigins` (if available and no …
=> fix(tracing): Pass `tracePropagationTargets` to `instrumentOutgoingRequests`

packages/node-integration-tests/.eslintrc.js, packages/node-integration-tests/suites/express/multiple-routers/common-infix-parameterized/server.ts, packages/node-integration-tests/suites/express/multiple-routers/common-infix-parameterized/test.ts, packages/node-integration-tests/suites/express/multiple-routers/common-infix/server.ts, packages/node-integration-tests/suites/express/multiple-routers/common-infix/test.ts, packages/node-integration-tests/suites/express/multiple-routers/common-prefix-parameterized-reverse/server.ts, packages/node-integration-tests/suites/express/multiple-routers/common-prefix-parameterized-reverse/test.ts, packages/node-integration-tests/suites/express/multiple-routers/common-prefix-parameterized/server.ts, packages/node-integration-tests/suites/express/multiple-routers/common-prefix-parameterized/test.ts, packages/node-integration-tests/suites/express/multiple-routers/common-prefix-same-length-parameterized copy/server.ts, packages/node-integration-tests/suites/express/multiple-routers/common-prefix-same-length-parameterized copy/test.ts, packages/node-integration-tests/suites/express/multiple-routers/common-prefix-same-length-parameterized/server.ts, packages/node-integration-tests/suites/express/multiple-routers/common-prefix-same-length-parameterized/test.ts, packages/node-integration-tests/suites/express/multiple-routers/common-prefix/server.ts, packages/node-integration-tests/suites/express/multiple-routers/common-prefix/test.ts, packages/tracing/src/integrations/node/express.ts
Fixes: #6004 
Handles the case when _at the end of reconstruction_ the original URL and the reconstructed URL don't match and there are no parameters.
Added 5 integration tests that cover multiple router usage with / without parameterized routes.
=> fix(express): Support multiple routers with common paths.

packages/core/src/baseclient.ts, packages/core/src/hub.ts, packages/hub/test/hub.test.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/6244
This changes moves all generation of eventId uuids to the client. Since we can't change the signature of `hub.captureException` and similar, we return a event id of zeros, `00000000000000000000000000000000`, if the client method returns undefined.
This should improve the performance of the SDKs!
=> fix(core): Only generate eventIds in client

packages/ember/package.json
This removes `build:extra` from the ember package. It is not really needed at this stage, as far as I can tell. 
For reference: What `ember build` in the context of an addon (=package) does is not really related to the library, but it builds the test app. Ember addons don't need to be built in any way, they are always built by the host app.
=> build(ember): Remove unused `build:extras` for ember package

packages/react/src/types.ts
Fixes: #6264
- Added `errorElement` type to both `NonIndexRouteObject` and `IndexRouteObject`
- Also extended `RouteObject` with `Record<string, any>` to prevent such things breaking users' builds in the future.
=> fix(react): Relax React Router 6 `RouteObject` typing.

packages/remix/src/utils/instrumentServer.ts
Ref: #6139 - https://github.com/getsentry/sentry-javascript/issues/6139#issuecomment-1323023630
Passing transaction names as custom routes to RequestData integration:
Custom routes in RequestData ⬇️ 
https://github.com/getsentry/sentry-javascript/blob/1aa2bc42beba3d27e74a3df3ff17939213f6f0d8/packages/node/src/requestdata.ts#L70-L74
This displays the transaction name prefixed by the method as below:
=> fix(remix): Pass transaction name as route to `RequestData`.

packages/nextjs/test/integration/pages/fetch.tsx, packages/nextjs/test/integration/test/client/tracingFetch.js
Ref: https://github.com/getsentry/sentry-javascript/issues/6281
This PR attempts to fix a flakey Next.js integration test that seems to be flakey because the UI thread was blocking a button-click interaction, causing the page load transaction to terminate before we get the chance to trigger a fetch request via the button click.
We try to fix this by conducting the fetch request on page mount, so we decouple the request from a UI interaction.
=> test(nextjs): Make `tracingFetch` integration test not use UI elements

packages/remix/src/utils/getIpAddress.ts, packages/remix/src/utils/web-fetch.ts
Ref: #6139 - https://github.com/getsentry/sentry-javascript/issues/6139#issuecomment-1323887582
Remix requests don't contain client IP addresses in `req.ip` or `req.socket.*`.
To extract them, we need to iterate over a set of request headers that may contain that info.
I have vendored / modified an implementation of that function from third-party utility set [`remix-utils`](https://github.com/sergiodxa/remix-utils#getclientipaddress). (Using as a dependency is not possible because of incompatible TS syntax.)
It's still the best effort and may also need improvements over header key prioritization.
=> fix(remix): Attempt to extract user IP from request headers.

packages/nextjs/src/config/withSentryConfig.ts, packages/nextjs/src/utils/isBuild.ts, packages/nextjs/src/utils/phases.ts, packages/nextjs/test/config/fixtures.ts, packages/nextjs/test/config/testUtils.ts, packages/nextjs/test/config/withSentryConfig.test.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/6284
This PR fixes that our Webpack configuration didn't get picked up in dev mode.
=> fix(nextjs): Apply Webpack configuration in dev mode

packages/remix/src/utils/instrumentServer.ts
Fixes: #6294 
Wrap `normalizeRemixRequest` calls inside `try` blocks, not to break users' builds / runtimes.
We don't use `normalizeRemixRequest` for our Express adapter, and also core adapter has higher priority to the Express adapter. So, the original source of #6294 needs more investigation.
But this patch should unblock users until then.
=> fix(remix): Prevent crashes from failed `normalizeRemixRequest` calls.

packages/core/src/baseclient.ts, packages/core/src/transports/base.ts, packages/core/test/lib/base.test.ts, packages/core/test/lib/transports/base.test.ts, packages/types/src/client.ts, packages/types/src/transport.ts
For replay, we want to provide an easy (internal) way to strip out dropped events.
Our idea is to monkey patch `recordDroppedEvent` in replay, and use it to get notified of which events have been dropped, and handle that internally. This requires the `recordDroppedEvent` callback to actually receive the event as argument.
This PR changes the signature so that it receives an error/transaction event as optional third argument. For other types of dropped events (e.g. attachments), undefined is passed.
ref https://github.com/getsentry/sentry-javascript/issues/6285
=> feat(core): Pass `event` as third argument to `recordDroppedEvent`

packages/replay/.eslintrc.js, packages/replay/config/tsconfig.base.json, packages/replay/package.json, packages/replay/tsconfig.json, packages/replay/worker/src/handleMessage.ts
This PR reverts a few changes I unintentionally comitted and merged in #6288. It caused build errors which for some reasons did not our CI's "build" step to fail but caused size-check fails in https://github.com/getsentry/sentry-javascript/actions/runs/3546454900
=> fix(build): Revert unintended Replay `tsconfig` changes

.github/workflows/build.yml
In the meanwhile, we've changed our CI setup in regard to which jobs are required or not. So we can revert the change that ensured nextjs & node tests are _always_ running, no matter what.
=> ci: Ensure nextjs & node tests only run when files change

packages/replay/package.json
This PR fixes a build error in Replay process by building it after all other packages (including their type declarations) were built. We have to do this temporarily because `@rollup/plugin-typescript` expects type declarations of the `@sentry/*` dependencies of the replay package. Because we're building types in parallel to transpiling JS, type declarations were not yet (reliably) built before replay's `build:rollup` commands was executed.
To unblock us, we for now build the package via `build:extras` so that it only runs after all other packages were fully built.
We should revert this change as soon as we use our transpilation process (sucrase) where we don't care about type declarations.
This might also fix the size-limit action on the master branch.
=> fix(replay): Temporarily build Replay after other packages

.size-limit.js
This gives us a more "correct" representation of the actual size increase to expect when using replay vs. not using it.
Note that we _do_ want to keep `rrweb` in there.
=> ci(replay): Ensure replay size limit excludes internal dependencies

packages/browser/src/helpers.ts, packages/browser/test/integration/polyfills/promise.js, packages/core/src/baseclient.ts, packages/core/test/mocks/transport.ts, packages/eslint-config-sdk/src/index.js, packages/gatsby/test/integration.test.tsx, packages/integration-tests/utils/helpers.ts, packages/integration-tests/utils/web-vitals/cls.ts, packages/node/src/integrations/http.ts, packages/replay/.eslintrc.js, packages/tracing/src/browser/request.ts, packages/tracing/src/idletransaction.ts, packages/utils/src/browser.ts, packages/utils/src/instrument.ts, packages/utils/src/normalize.ts, packages/utils/src/path.ts, packages/utils/src/promisebuffer.ts, packages/utils/src/stacktrace.ts, packages/vue/src/components.ts, scripts/ensure-bundle-deps.ts
This PR removes the `no-plusplus` eslint rule, as it doesn't really apply to us. By replacing usage of `a += 1` with `a++`, and `a -= 1` with `a--` we should actually be able to shave a few bytes off our bundles.
=> ref: Drop `no-plusplus` rule & refactor to use `++` / `--`

packages/replay/jest.setup.ts, packages/replay/src/index.ts, packages/replay/src/util/isBrowser.ts, packages/replay/src/util/isInternal.ts
Extracted out of https://github.com/getsentry/sentry-javascript/pull/6316, as these are only semi-related. This should allow us to better evaluate bundle size changes due to `WINDOW`
For now, just changed the logic a bit to use `isNodeEnv` under the hood. In a next step we should evaluate if we can remove some of these checks.
=> ref(replay): Improve `isBrowser` check

packages/opentelemetry-node/src/utils/parse-otel-span-description.ts, packages/opentelemetry-node/test/spanprocessor.test.ts
fixes https://github.com/getsentry/sentry-javascript/issues/6301
If a low cardinality `http.route` is not defined, we fall back to `http.target` and set transaction source to be `url`. In that case, we should special case `http.target` === `/` since we know the `/` root transaction has no parameters. Therefore we categorize it as transaction source `route`.
=> fix(otel): Set root transaction name to be route

packages/replay/.eslintrc.js, packages/replay/config/rollup.config.core.ts, packages/replay/package.json, packages/replay/src/createPerformanceEntry.ts, packages/replay/src/eventBuffer.ts, packages/replay/src/index.ts, packages/replay/src/session/deleteSession.ts, packages/replay/src/session/fetchSession.ts, packages/replay/src/session/saveSession.ts, packages/replay/src/util/isBrowser.ts, packages/replay/src/util/isInternal.ts, packages/replay/test/unit/flush.test.ts, packages/replay/test/unit/index-errorSampleRate.test.ts, packages/replay/test/unit/index.test.ts, packages/replay/test/unit/session/Session.test.ts, packages/replay/test/unit/session/createSession.test.ts, packages/replay/test/unit/session/deleteSession.test.ts, packages/replay/test/unit/session/fetchSession.test.ts, packages/replay/test/unit/session/getSession.test.ts, packages/replay/test/unit/session/saveSession.test.ts, packages/replay/test/unit/stop.test.ts
This PR replaces usage of `window` with the global `WINDOW`, to avoid using the window global directly.
=> ref(replay): Use `WINDOW` instead of `window`

packages/browser/src/sdk.ts, packages/gatsby/gatsby-browser.js, packages/gatsby/test/gatsby-browser.test.ts
This adds a magic string in the browser code that can be used by build tooling to inject a release value into the SDK during build time.
This is not used right now but it makes sense to introduce something like it as early as possible because, in the future, we want to move our bundler plugins to use this approach instead of injecting a variable on `global`.
=> feat(browser): Add `__SENTRY_RELEASE__` magic string

packages/node/src/types.ts, packages/types/src/options.ts
Adds profilesSampleRate to the Node SDK init options.
Adding this because we got 3 emails last week about the typescript error by our customers and asking them to @ts-expect-error is not really acceptable.
=> types(node): add profilesSampleRate

packages/browser/src/client.ts, packages/browser/src/integrations/breadcrumbs.ts, packages/browser/test/unit/integrations/breadcrumbs.test.ts
`getIntegrationById` is used to ensure that the `Breadcrumbs` integration is not included in the bundle when it's not used. 
Moving this logic from the `BaseClient` into the integration should save further bundle size when the `Breadcrumbs` integration is not used, especially since `getEventDescription` will no longer be included too.
=> ref(core): Move sentry breadcrumb logic into integration

packages/replay/config/rollup.config.core.ts
This PR fixes a runtime bug with Replay which started happening after the monorepo migration because the `__DEBUG_BUILD__` variable isn't yet replaced correctly at build time. This temporary fix will be replaced once we use the monorepo's rollup configs for building Replay (WIP).
=> fix(replay): Temporarily replace `__DEBUG_BUILD__` with `true`

packages/replay/src/index.ts, packages/replay/src/session/Session.ts, packages/replay/src/session/createSession.ts, packages/replay/src/session/fetchSession.ts, packages/replay/test/mocks/mockSdk.ts, packages/replay/test/unit/index.test.ts, packages/replay/test/unit/session/Session.test.ts, packages/replay/test/unit/session/getSession.test.ts, packages/replay/test/unit/session/saveSession.test.ts, packages/replay/test/unit/util/isSessionExpired.test.ts
Currently, a `Session` in replay receives `stickySession` as argument, and conditionally saves itself in its setters.
IMHO this responsibility is better placed outside of the session class. This also allows us to streamline the Session class quite a lot.
=> ref(replay): Extract sticky session handling

packages/replay/.eslintrc.js, packages/replay/src/eventBuffer.ts, packages/replay/src/index.ts
This one was rather straightforward, basically adding `void` before floating promises.
=> ref(replay): Enable `@typescript-eslint/no-floating-promises` rule

packages/browser/src/client.ts, packages/types/src/options.ts
`InboundFilters` is a default integration, so `allowUrls` and `denyUrls` should be part of the base client options - not just on the browser client only.
=> ref(core): Move `allowUrls` and `denyUrls` options into core

packages/opentelemetry-node/src/utils/map-otel-status.ts, packages/opentelemetry-node/test/spanprocessor.test.ts
http status code is defined in the spec as a number: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#common-attributes
Let's add special casing for both possibilities (status code is either a string or a number).
=> fix(otel): Account for number status code

packages/replay/.eslintrc.js, packages/replay/src/eventBuffer.ts, packages/replay/src/index.ts, packages/replay/test/unit/index.test.ts, packages/replay/worker/src/handleMessage.ts
This enabled `no-console` eslint rule.
I left two cases of actual `console.warn` in, where it is basically a deprecation for old settings (which we can probably eventually delete).
=> ref(replay): Enable `no-console` rule

packages/replay/package.json
This PR cleans up the replay integration's `package.json` by getting rid of a few ToDos, enabling the circular dependency check and using the eslint cache of the monorepo. 
Since the future of the demo app in the replay package is still unclear, I opted to repurpose and rename the `bootstrap` script so that it now only bootstraps the demo app. For the package itself, bootstrapping happens via a monorepo-level `yarn` command or `lerna bootstrap` command.
ref: #6280
=> chore(replay): Cleanup `package.json` scripts

packages/replay/test/tsconfig.json
a) The comment is not allowed in a JSON file
b) The path is not correct (anymore)
=> test(replay): Fix replay test tsconfig

packages/replay/package.json, packages/replay/tsconfig.json
This PR follows up with a small change on top of #6343 to further align the `build` directory. Previously, types were built into `build/npm/types/src/index.d.ts`. The `src` sub-directory shouldn't be in there, so this PR fixes that by removing some leftover properties in the main `tsconfig.json` which caused this sub-directory to appear. 
This PR also removes a few additional unnecessary properties, such as `types` which we only need in `tsconfig.test.json`.
ref: #6280
=> build(replay): Adjust type declaration output directory

packages/tracing/src/browser/browsertracing.ts
The SDK should avoid setting tags when possible. This PR makes sure we remove this tag, which isn't really useful anymore. We were using this to track metadata when we were tracking improvements to `idleTimeout`: https://github.com/getsentry/sentry-javascript/pull/4251, but now that we've shipped that with v7, we can remove this tag.
Related: https://github.com/getsentry/team-mobile/issues/60#issuecomment-1333057921
=> ref(tracing): Remove `sentry_reportAllChanges` tag

packages/replay/.npmignore
This PR removes Replay's empty `.npmignore` file as we can use the monorepo's top-level `.npmignore` file. When running `build:npm`, this top-level ignore file is copied into the `build/npm` directory where it is used to control what's going into the NPM tarball. Because the Replay package now has the same contents and structure as all our other packages, we don't need a package-specific ignore file.
ref #6280
=> chore(replay): Use Monorepo's toplevel `.npmignore`

packages/replay/jest.setup.ts, packages/replay/rollup.npm.config.js, packages/replay/src/index.ts, packages/replay/src/types.ts
This PR removes the magic string replacement of `__SENTRY_REPLAY_VERSION__` at build time in favour of `@sentry/core`'s `SENTRY_VERSION` constant.
This first part of #6366 we can do now as the version will be bumped to 7.x anyway.
ref #6366
=> build(replay): Remove replay version string replacement

packages/opentelemetry-node/src/spanprocessor.ts, packages/opentelemetry-node/test/spanprocessor.test.ts
Follows spec as is outlined here: https://develop.sentry.dev/sdk/performance/opentelemetry/#step-1-implement-the-sentryspanprocessor-on-your-sdk
Uses the logic from the baseclient here: https://github.com/getsentry/sentry-javascript/blob/8139853e416d04772b31e9920bca889ecbee1516/packages/core/src/scope.ts#L473-L482
Attach trace context info from active transaction to errors in an event processor. Couple things to note.
1. This attaches the trace context to all events. Transactions should be setting their own trace context, and that will override this via the spread operator
2. We don't use scope at all here - we are relying on identifying the active span via opentelemetry.
Supercedes approach from https://github.com/getsentry/sentry-javascript/pull/6349 since we don't want to rely on …
=> fix(otel): Add trace info to error events

CHANGELOG.md
Blocked on https://github.com/getsentry/sentry-javascript/pull/6364 merging in.
=> meta: CHANGELOG for 7.23.0

packages/replay/src/index.ts
This removes the (deprecated) options:
* `replaysSamplingRate`
* `captureOnlyOnError`
* `replaysSamplingRate` can be replaced with `sessionSampleRate`
* `captureOnlyOnError` can be replaced with `errorSampleRate`
Closes https://github.com/getsentry/sentry-javascript/issues/6352
=> ref(replay): Remove deprecated replay options

rollup/npmHelpers.js
Currently, our rollup config adds all `dependencies`, `devDependencies` and `peerDependencies` to the `external` array, meaning they will not be inlined into the build.
However, that makes it impossible to _selectively_ inline files. For example, in replay we'd like to inline `rrweb` into the bundle.
What makes this even more tricky is that because of the nature of `deepmerge`, which we use to merge custom config into the default one, it is actually impossible to overwrite this, as a custom `external` array will not overwrite the default one, but be added to it.
This change removes `devDependencies` from the externals. IMHO that is otherwise bound to break anyhow - as if the dependency is neither `dependency` nor `peerDependency`, and you import it (but not bundle it), stuff might break …
=> build: Do not exclude `devDependencies` from rollup build

packages/replay/jest.setup.ts, packages/replay/rollup.npm.config.js, packages/replay/src/index.ts, packages/replay/src/types.ts
This PR reverts #6367 as the Replay team would like to continue injecting the version separately from the SDK to detect version package version mismatches more easily. 
Note: This will not avoid the 7.x bump in the next Replay release, it will just enable a scenario like users use the SDK on e.g. 7.25 and Replay on 7.24 and replay events will have the 7.24 version in their metadata.
Note 2: This makes a very good case for exporting Replay via the SDK to, as it avoids version mismatches all together. Same for Tracing later on...
=> Revert "build(replay): Remove replay version string replacement (#6367)"

packages/replay/src/constants.ts, packages/replay/src/createPerformanceEntry.ts, packages/replay/src/index.ts, packages/replay/src/session/deleteSession.ts, packages/replay/src/session/fetchSession.ts, packages/replay/src/session/saveSession.ts, packages/replay/src/types.ts, packages/replay/src/util/isInternal.ts, packages/replay/src/util/isSessionExpired.ts, packages/replay/test/unit/flush.test.ts, packages/replay/test/unit/index-errorSampleRate.test.ts, packages/replay/test/unit/index-handleGlobalEvent.test.ts, packages/replay/test/unit/index-noSticky.test.ts, packages/replay/test/unit/index.test.ts, packages/replay/test/unit/session/Session.test.ts, packages/replay/test/unit/session/createSession.test.ts, packages/replay/test/unit/session/deleteSession.test.ts, packages/replay/test/unit/session/fetchSession.test.ts, packages/replay/test/unit/session/getSession.test.ts, packages/replay/test/unit/session/saveSession.test.ts, packages/replay/test/unit/stop.test.ts
In preparation of generating CDN bundles, this PR copies the `WINDOW` constant declaration from `@sentry/browser` to the Replay package and updates the imports to use the package-internal version of `WINDOW`. This has two advantages:
* When building CDN bundles, we don't bundle contents from `@sentry/browser` anymore. This previously caused the generated bundles to not work correctly and it unnecessarily increased bundle size
* By not importing anything from `@sentry/browser` we avoid a circular dependency one we export the Replay integration from the Browser SDK.
ref #6362
=> ref(replay): Export `WINDOW` within Replay instead of importing it from Browser

packages/nextjs/src/config/webpack.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/6321
In https://github.com/getsentry/sentry-javascript/pull/6206 we switched up our logic not to always include the SDK on `/app` route. This broke the injection mechanism in dev mode where `_app` is the only entry point that is always hit. In dev mode, pages defined by the user are not considered entry points so they were skipped by our injection logic.
This PR fixes this by always injecting the SDK into `_app` in dev mode. This is probably not optimal because it doesn't really reflect what is happening when a Next.js is built using prod mode but it's as close as we can get with reasonable effort.
=> fix(next): Inject SDK in dev mode

packages/nextjs/src/index.client.ts, packages/nextjs/test/index.client.test.ts
This refactors the code in the nextjs SDK adding client-side integrations to:
- Consolidate the logic, which currently is split between `init` and a helper function, to all live in the helper. Not only is this better practice in general, it also sets up for a future PR which will add a new integration. (Adding more code to the current somewhat-messy setup would just make it worse, and it's easier to fix it before that happens.)
- Align the client-side code with the server-side code, for greater maintainability.
=> ref(nextjs): Clean up client-side integrations code

packages/replay/package.json
This was merged after a release, so the version wasn't bumped 🙈
=> build(replay): Fix peer dependency version

packages/core/src/baseclient.ts, packages/core/src/hub.ts, packages/hub/test/hub.test.ts
Reverts getsentry/sentry-javascript#6247
Fixes https://github.com/getsentry/sentry-javascript/issues/6380
Reverting the PR that moved the event_id generation into the client because this is causing issues if you have async event processors. Although our processing pipeline uses `SyncPromise`, async code can sneak in there, and this means that our event id's can be undefined.
Since there is a workaround for the initial perf problem we are electing to just revert.
=> Revert "fix(core): Only generate eventIds in client"

packages/replay/src/index.ts, packages/replay/test/unit/index-handleGlobalEvent.test.ts
In replay, we attach errors that happened during replay-time via a global event handler.
However, due to various reasons some of these errors _may_ be filtered out later. This leads to a weird user experience when there seem to be more errors that actually exist in sentry.
This PR fixes this (to a decent extend) by making sure we remove any error id that was actually dropped (due to rate limiting or because an integration/callback decided to drop it). For this, we monkey patch `recordDroppedEvent`.
Closes https://github.com/getsentry/sentry-javascript/issues/6285
=> fix(replay): Ensure dropped errors are removed from replay reference

packages/replay/README.md
Related to https://github.com/getsentry/sentry-javascript/issues/6383, this PR improves & updates the docs for replay.
[View rendered](https://github.com/getsentry/sentry-javascript/blob/fn/replay-docs/packages/replay/README.md)
1. Updates the docs for how to define the sample rate(s)
2. Add `maskTextSelector` documentation
3. Add section about how errors are linked to replays
4. Section docs into where configuration has to go, for clarity
5. For now, the rrweb config stuff remains as is. If/when we do https://github.com/getsentry/sentry-javascript/issues/6390, we can update this accordingly.
=> docs(replay): Update replay README

MIGRATION.md, packages/replay/MIGRATION.md, packages/replay/README.md
The second part of https://github.com/getsentry/sentry-javascript/issues/6383, this adds migration instructions for replay (coming from 0.6).
In addition, I also added the header & badges @Lms24 mentioned in the previous PR that I then totally forgot to add 😅 
Not sure if I forgot anything relevant?
[Rendered README.md](https://github.com/getsentry/sentry-javascript/blob/fn/replay-migration-docs/packages/replay/README.md)
[Rendered MIGRATION.md](https://github.com/getsentry/sentry-javascript/blob/fn/replay-migration-docs/packages/replay/MIGRATION.md)
=> docs(replay): Add MIGRATION.md & add badges to README.md

.vscode/settings.json, packages/replay/.eslintrc.js, packages/replay/jest.config.ts, packages/replay/test/mocks/index.ts, packages/replay/test/unit/coreHandlers/handleFetch.test.ts, packages/replay/test/unit/coreHandlers/handleScope-unit.test.ts, packages/replay/test/unit/createPerformanceEntry.test.ts, packages/replay/test/unit/eventBuffer.test.ts, packages/replay/test/unit/flush.test.ts, packages/replay/test/unit/index-errorSampleRate.test.ts, packages/replay/test/unit/index-handleGlobalEvent.test.ts, packages/replay/test/unit/index-integrationSettings.test.ts, packages/replay/test/unit/index-noSticky.test.ts, packages/replay/test/unit/index-sampling.test.ts, packages/replay/test/unit/index.test.ts, packages/replay/test/unit/stop.test.ts, packages/replay/test/unit/util/dedupePerformanceEntries.test.ts, packages/replay/tsconfig.json, packages/replay/tsconfig.test.json
This PR goes some steps towards aligning tsconfig & jest config of replay with the rest of the packages.
* Move some tsconfig stuff we need for tests only to tsconfig.test.json
* Add some more common folders to vscode search.exclude
* Stop using `@test` imports in replay
* Make replay tests non-verbose
IMHO the goal should be to also re-export the jest config from `/jest/jest.config.js`, but I ran into a bunch of issues with that - I think related to typescript, and jest.setup.ts 😬 But this should be OK as a first step.
=> build(replay): Streamline tsconfig & jest config

packages/remix/src/utils/web-fetch.ts
Adds a debug logger to get details about potentially thrown errors from `getClientIpAddress`.
=> ref(remix): Do not fail silently if `getClientIpAddress` throws error.

CHANGELOG.md
This reverts commit 9cc389177a4c78afcd7f26983891a454db4a7f49.
As we have some issues releasing as of now because of Github Action issues, let's revert this for now and try again later.
=> Revert "meta: CHANGELOG for 7.24.0 (#6411)"

packages/browser/src/client.ts, packages/replay/MIGRATION.md, packages/replay/README.md, packages/replay/src/index.ts, packages/replay/test/unit/index-integrationSettings.test.ts
We wanted this config option to be a bit more specific in that it should be the sample rate for "session" replays (vs. on error samples). The previous name could be mistaken as a sample rate that affects both types of replays.
=> ref(replay): Rename `replaysSampleRate` to `replaysSessionSampleRate`

packages/replay/MIGRATION.md, packages/replay/src/eventBuffer.ts, packages/replay/src/index.ts
This ensures public/private annotation is correct for the event buffer implementation. It also refactors a few (internal) things in minor ways, for clarity.
For example, we used a getter which as a side effect incremented itself. It is cleaner to do this explicitly, as getters should generally be side-effect free.
This is technically a breaking change, as the exported name of the interface `IEventBuffer` was changed to `EventBuffer`. It is unlikely that a user relied on that, though.
ref https://github.com/getsentry/sentry-javascript/issues/6323
=> ref(replay): Streamline replay EventBuffer implementation

packages/node-integration-tests/package.json, yarn.lock
v3.13 fixes compatibility with openssl 3, which seems to be used on GHA now. See: https://github.com/prisma/prisma/releases/tag/3.13.0
=> build(dev-deps): bump @prisma/client from 3.12.0 to 3.15.2

.github/workflows/build.yml, package.json, packages/replay/package.json, packages/replay/rollup.npm.config.js, patches/rrweb+1.1.3.patch, yarn.lock
While debugging the replay issue https://github.com/getsentry/sentry-replay/issues/297, we found that most likely the problem is upstream in rrweb. I created an issue there to fix it: https://github.com/rrweb-io/rrweb/issues/1057
Really, the change is minimal, but the PR is not yet merged & even when it is merged it is not clear when this will be released. Even _when_ it will be released, it will probably go into 2.0.0-alpha.X, which will need some time from us to actually update (as there are no upgrade docs yet etc.)
So, with that in mind, this PR does two things:
1. Introduce `patch-package` to fix the exact issue we care about in rrweb
2. Inline rrweb into the replay bundle
This approach has two main benefits:
a) We can fix this issue very quickly
b) We still maintain the ability to …
=> fix(replay): fix rrweb issue & vendor it

packages/browser/src/integrations/breadcrumbs.ts, packages/utils/src/browser.ts, packages/utils/test/browser.test.ts
Implements the configuration feature described in #6175 . This lets sentry users opt in to having longer, potentially more helpful, UI breadcrumbs.
Closes https://github.com/getsentry/sentry-javascript/issues/6175
=> feat(browser): support dom.maxStringLength configuration (#6175)

packages/nextjs/src/config/webpack.ts
This fixes a bug in https://github.com/getsentry/sentry-javascript/pull/6388, wherein `basePath` was ignored when determining `assetPath`. Nextjs copies the former over to the latter if the former is provided and the latter is not. In my original implementation of https://github.com/getsentry/sentry-javascript/pull/6388, the SDK read the values after that had happened, so it was sufficient to look at `asssetPath`. When I moved the reading of the values earlier, I didn't account for the fact that `basePath` wouldn't have yet been copied over into `assetPath`, meaning we have to do it ourselves.
=> fix(nextjs): Use `basePath` for `assetPrefix` if needed

packages/node-integration-tests/suites/tracing/auto-instrument/mongodb/scenario.ts, packages/node-integration-tests/suites/tracing/auto-instrument/mongodb/test.ts, packages/tracing/src/integrations/node/mongo.ts
Checking if the returned value is a `Cursor` using an internal utility instead of matching `EventEmitter` type as done in #6412 and #6337. 
Fixes https://github.com/getsentry/sentry-javascript/issues/4495
Instrumented [Cursor](https://mongodb.github.io/node-mongodb-native/4.12/classes/AbstractCursor.html)s returned from certain MongoDB operations, this also resolves the problem mentioned in https://github.com/getsentry/sentry-javascript/issues/5278.
=> fix(tracing): Instrument cursors returned from MongoDB operations.

packages/angular/src/errorhandler.ts
I believe extracting this into a dedicated function helps to:
- Convey the intent: instead of having a statement and a comment explaining the statement, you directory have a descriptive and explanatory function name.
- This also to further encapsulate additional information, here about a possible refactoring that would make it clearer.
- Bonus: this was the only reason why `let` was being used, so now `const` can be used
=> ref(angular): Extract zonejs error unwrapper into a dedicated function

packages/react/src/types.ts
Fixes: #6421 
`encodeLocation` method is added to `Router` class by: https://github.com/remix-run/react-router/pull/9589
--- 
Note: https://github.com/remix-run/react-router/pull/9589 may also potentially help us with #5997 
I'll investigate it further.
=> fix(react): Add type for React Router's `encodeLocation` method

packages/replay/src/replay.ts
This changes how we overwrite `checkoutEveryNms` config when sampling for errors. This is a bit cleaner and also ensures we do not loose this setting in regular replay sampling if the user specified it. I also extended on the comment for added clarity why this exists.
note: If https://github.com/getsentry/sentry-javascript/pull/6448 is merged first, need to adjust accordingly as that is moved a bit.
=> ref(replay): Avoid overwriting user `checkoutEveryNms` config

packages/tracing/src/integrations/node/apollo.ts, packages/tracing/src/integrations/node/graphql.ts, packages/tracing/src/integrations/node/mongo.ts, packages/tracing/src/integrations/node/mysql.ts, packages/tracing/src/integrations/node/postgres.ts
To make sure we don't override possible OpenTelemetry instrumentation, check for the instrumenter to be configured as `otel` before we dynamically load the database modules to instrument.
=> fix(tracing): Check for otel before loading db module

packages/tracing/src/browser/browsertracing.ts, packages/tracing/src/browser/metrics/index.ts, packages/tracing/src/browser/web-vitals/getCLS.ts, packages/tracing/src/browser/web-vitals/getFID.ts, packages/tracing/src/browser/web-vitals/getLCP.ts
Closes #6078
Removes `reportAllChanges` passed down through all the functions and deprecates `_metricOptions` since it no longer has a use.
=> fix(tracing): Deprecate and remove `reportAllChanges` option

packages/integration-tests/suites/tracing/browsertracing/interactions/assets/script.js, packages/integration-tests/suites/tracing/browsertracing/interactions/init.js, packages/integration-tests/suites/tracing/browsertracing/interactions/template.html, packages/integration-tests/suites/tracing/browsertracing/interactions/test.ts, packages/integration-tests/utils/generatePlugin.ts, packages/tracing/src/browser/browsertracing.ts, packages/tracing/test/browser/browsertracing.test.ts
This adds interactions as an experiment so we can try it out with Sentry SaaS before tuning it for general release. It's behind a rate as an experiment option and only makes idleTransactions on 'click' for now. Future considerations include us likely having differing idleTimeout settings, and being more clever with which data we include, but this should be enough to start experimenting.
For rollout, we can potentially release this as a branch / beta for our SaaS experiment first.
- re: playwright tests I'll need to fix them since they seem to work in debug but not regularly, I think it's a timeout issue.
- refs earlier convos I've had with @AbhiPrasad about interactions, https://github.com/getsentry/sentry-javascript/issues/5750
- We're planning on introducing the INP web vital via …
=> feat(tracing): Add interaction transaction as an experiment

packages/replay/package.json, packages/replay/rollup.npm.config.js, yarn.lock
This PR changes the replay build to inline the lodash.debounce dependency.
There can be potentially build issues with this, as lodash is commonjs. Eventually we may want to replace this with a custom implementation, but for now including it in the bundle should be fine.
Closes https://github.com/getsentry/sentry-javascript/issues/6474
=> ref(replay): Inline lodash dependency into build

packages/types/src/datacategory.ts, packages/types/src/envelope.ts, packages/types/src/event.ts, packages/utils/src/envelope.ts
Adds profile envelope type so we can skip the ts-expect error in the profiling sdk.
=> feat(types): add profile envelope item type

packages/core/src/scope.ts, packages/replay/src/coreHandlers/handleScope.ts, packages/replay/test/unit/coreHandlers/handleScope.test.ts, packages/types/src/scope.ts
This is needed by replay, which can then stop using the private API `_breadcrumbs`.
=> feat(core): Add `scope.getLastBreadcrumb()`

packages/replay/src/constants.ts, packages/replay/src/replay.ts, packages/replay/src/util/createReplayEnvelope.ts, packages/replay/src/util/getReplayEvent.ts, packages/replay/test/unit/util/getReplayEvent.test.ts, packages/replay/test/utils/getDefaultBrowserClientOptions.ts
This is brittle, and can actually be refactored quite easily.
I also used the time to move the event/envelope creation out into dedicated methods, which we'll need to adapt later.
See: https://github.com/getsentry/sentry-javascript/pull/6493
=> ref(replay): Avoid using private `hub._withClient`

rollup/plugins/bundlePlugins.js
In Replay, we access some private methods from the core SDK package from the `Client` class. Because we mangle private fields by default, our SDK CDN bundles wouldn't expose these methods and fields anymore in their clear name to external callers, such as our Replay CDN bundle, producing runtime errors because the methods were not found. 
This PR fixes these errors by explicitly excluding the called private methods from mangling so that they can be accessed externally. This is admittedly not a clean solution but it unblocks minified CDN bundle users. In the long run we can revert this PR once we streamlined Replay event sending into the SDK (#6480) (as well as breadcrumbs via hooks?). 
Note: This unfortunately increases bundle size, not just for the Replay CDN bundle, but also for the …
=> build(core): Do not mangle private methods used by Replay

docs/event-sending.md
This adds a docs page which outlines the flow that events go through when being processed.
I wrote this while trying to reason about the replay event sending - it can be quite hard to have an overview what is added/updated on an event where. This document hopefully helps a bit with that, for future reference.
=> docs: Add docs about internal event sending flow

packages/nextjs/src/config/webpack.ts, packages/nextjs/test/config/webpack/sentryWebpackPlugin.test.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/6504
In we switched from the Sentry Webpack plugin to using a custom loader to inject the release value into the SDK that either reads from options or from environment variables. We didn't consider that the Webpack Plugin (or rather Sentry CLI) has a mechanism to determine a release value apart from options or environment variables.
This PR in essence reverts https://github.com/getsentry/sentry-javascript/pull/6404 which introduced this bug.
=> fix(nextjs): Fix automatic release value discovery

packages/types/src/event.ts
Implements nonbreaking changes from
- https://github.com/getsentry/sentry-javascript/pull/6038
this way RN can patch the behavior in its next major release.
The RN patch
- https://github.com/getsentry/sentry-react-native/pull/2694
=> chore(event): Add threads to Event

packages/replay/src/replay.ts, packages/replay/test/unit/index-errorSampleRate.test.ts
We originally added this delay to flushing to prevent recording short (low value) recordings. However, this causes some issues if the user were to refresh/leave the page before the first recording segment is sent as the backend will consider the replay invalid if it does not have segment id 0 present.
Change to flush immediately to try to reduce the number of replays with missing first segments. Our UI has a default duration filter to hide replays < 5 seconds.
=> feat(replay): Flush immediately on DOM checkouts

packages/replay/src/coreHandlers/handleGlobalEvent.ts, packages/replay/src/util/isRrwebError.ts, packages/replay/test/unit/index-handleGlobalEvent.test.ts
rrweb can throw hard to pinpoint errors in its internals, e.g. when working with iframes or other hard to control environments.
We want to avoid flooding sentry errors with these, so this PR filters them out based on stracktrace.
Unless using `captureExceptions` experiment, we want to ignore these errors.
This is probably not 100% bullet proof, and relies on source maps etc. being correct, but I think it should help in a good amount of cases, at least.
Closes https://github.com/getsentry/sentry-javascript/issues/6418
=> feat(replay): Do not capture errors originating from rrweb

packages/replay/src/constants.ts, packages/replay/src/replay.ts, packages/replay/src/util/createReplayEnvelope.ts, packages/replay/src/util/getReplayEvent.ts, packages/replay/test/unit/util/createReplayEnvelope.test.ts, packages/replay/test/unit/util/getReplayEvent.test.ts
This PR replaces the `sentry.javascript.integration.replay` name in `event.sdk.name` with the actual Sentry SDK name (e.g. `sentry.javascript.browser`), analogously to how we send SDK metadata in other event types.
Going forward, we can can also use this information e.g. for data analysis to filter replay events by SDK
ref #6366
=> ref(replay): Send SDK's name in replay event

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml
In order to cut down CI time when releasing, we can skip build & consecutive steps when we notice that _only_ `.md` files have been changed.
=> ci: Skip build (and consecutive steps) when only changing .md files

packages/core/src/envelope.ts, packages/replay/src/util/createReplayEnvelope.ts, packages/utils/src/envelope.ts
We want to use `getSdkMetadataForEnvelopeHeader` in Replay to not have duplicated minimal SDKInfo extraction logic. I checked that envelope helper functions are usually publicly exposed from the utils package only (which makes sense to me). So, this PR moves the function from core to utils and calls it in the replay envelope creation function.
Note that I changed the input type to accept both, an `Event` as well as `SdkMetadata`, as both have the `sdk: SdkInfo` property. 
Since `getSdkMetadataForEnvelopeHeader` wasn't exported before, I think we don't have to worry about a breaking change here.
ref: #6366
=> ref(core): Move `getSdkMetadataForEnvelopeHeader` to utils

packages/replay/src/constants.ts, packages/replay/src/integration.ts, packages/replay/test/unit/index-integrationSettings.test.ts, packages/replay/test/unit/index.test.ts
Sometimes, we seemed to be masking e.g. content of style tags. This new selector should be more specific to not mask anything that we know is not actually text.
=> fix(replay): Make `maskAllText` selector more specific

package.json, packages/browser/package.json, packages/browser/src/client.ts, packages/browser/src/index.ts, packages/replay/package.json, packages/replay/src/integration.ts, packages/types/src/browseroptions.ts, packages/types/src/index.ts, rollup/bundleHelpers.js, rollup/plugins/bundlePlugins.js, rollup/utils.js, yarn.lock
This PR exports the `Replay` integration from `@sentry/replay` in `@sentry/browser`.  This will eliminate the need for users to separately install the `@sentry/replay` package as they have to do right now. Instead, they can just use Replay like it's part of the core Browser SDK or any FE Framework SDK that builds on top of Browser:
```js
import * as Sentry from '@sentry/browser'; // or @sentry/react, ...
Sentry.init({
// dsn, other options, etc
replaysSessionSampleRate: 0.1,
replaysOnErrorSampleRate: 1.0,
integrations: [new Sentry.Replay()]
});
```
Alternatively, `import { Replay } from '@sentry/browser'` works, too. 
Note: This does not affect users who imported the integration from `@sentry/replay` so it should be fully backwards compatible.  
As far as I tested, for the NPM package, …
=> feat(browser): Export `Replay` integration from Browser SDK

packages/nextjs/test/integration/pages/[id]/withInitialProps.tsx, packages/nextjs/test/integration/pages/[id]/withServerSideProps.tsx, packages/nextjs/test/integration/pages/alsoHealthy.tsx, packages/nextjs/test/integration/pages/healthy.tsx, packages/nextjs/test/integration/pages/users/index.tsx
In Next.js v13.0.7 anchor tags inside Link elements started throwing hydration errors in the browser. This flagged our session integration tests.
We fix this by abiding by the rules Next.js gives us: https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag
I opened an issue to let Vercel folks know that this suddenly started happening: https://github.com/vercel/next.js/issues/44050
=> test(nextjs): Fix integration tests for Next.js 13.0.7

.github/workflows/build.yml
Since @sentry/browser now depends on @sentry/replay, we also need to make sure to run tests on CI accordingly.
=> ci: Ensure replay changes trigger tests in all browser related packages

packages/utils/src/misc.ts
This PR fixes a bug that breaks grouping in Sentry. Currently, when a stack frame doesn't have a line number we attach context lines based on line number 0. This is simply wrong and conflicts with grouping algorithms. We solve this by not attaching context lines at all for frames that do not have line numbers.
Some (ephemeral) context: https://sentry.slack.com/archives/GUCRT2B70/p1671103033977659
=> fix(utils): Don't attach context lines to stack frames without line number

.github/workflows/build.yml, package.json, scripts/test.ts
This PR does two main things:
* Streamline names of CI jobs for better readability (=put the most important stuff up front, as it is often truncated at the end)
* Split unit tests into Browser & Node unit tests - so we only run tests that depend on node stuff in multiple node versions.
=> ci: Split node & browser unit tests

packages/core/src/envelope.ts, packages/replay/src/replay.ts, packages/replay/src/util/createReplayEnvelope.ts, packages/replay/test/unit/util/createReplayEnvelope.test.ts, packages/utils/src/envelope.ts
As outlined in #6539, we're right now not sending the `dsn` key in the replay event [envelope header](https://develop.sentry.dev/sdk/envelopes/#envelope-headers), thereby not including the necessary information to forward the event to Sentry. 
This PR fixes that by extracting the `createEventEnvelopeHeaders` function to utils so that we can use it in Replay (analogously to #6514), as well as using this function to create all headers. 
We tested this PR with NextJS' `tunnelRoute` as well as with the conventional `tunnel` option and everything seems to work now.
Note: While refactoring and adding tests, I discovered that right now, replay event envelopes always contain the identical `replayId` as `event_id` and `replay_id`. Not sure if this is intended but I'm not changing this in this PR …
=> fix(replay): Send `dsn` in envelope header if tunneling is enabled

packages/nextjs/test/integration/package.json, packages/remix/test/integration/package.json
This PR fixes the broken NextJS and Remix integration tests which were unable to look up the local version of `@sentry/replay` before. Replay is now a dependency of these tests because they depend on `@sentry/browser` (which in turn depends on Replay after #6508).
Not sure why we didn't catch this earlier, as afaict, our [test job selection config](https://github.com/getsentry/sentry-javascript/blob/1f7328c27ed9628f88b662f7564b245e26ba4593/.github/workflows/build.yml#L65-L122) already covers this change.   
This should unblock our 7.27.0 release
=> test: Add Replay dependency resolution to Remix and NextJS integration tests

packages/nextjs/src/config/wrappers/withSentryGetServerSideProps.ts, packages/nextjs/src/config/wrappers/withSentryServerSideAppGetInitialProps.ts, packages/nextjs/src/config/wrappers/withSentryServerSideDocumentGetInitialProps.ts, packages/nextjs/src/config/wrappers/withSentryServerSideErrorGetInitialProps.ts, packages/nextjs/src/config/wrappers/withSentryServerSideGetInitialProps.ts, packages/nextjs/src/config/wrappers/wrapperUtils.ts, packages/nextjs/test/integration/pages/_document.tsx
Fixes https://github.com/getsentry/sentry-javascript/issues/6479
Our Next.js wrapping methods didn't take care of correctly passing `this` context. This PR fixes that.
=> fix(nextjs): Pass `this` through wrappers

packages/nextjs/src/index.server.ts
This PR fixes a TypeScript error when using the `Replay` integration exported from the NextJS SDK (>= 7.27.0). Because our SDK tells TS that it should import types from `index.server.ts`, TS doesn't find the Replay integration class although it's correctly exported from `indext.client.ts`. 
Note: even without this change, Replay works in NextJS, it's just a TS error. 
@reviewers: I tested this with a basic NextJS app and for me it works. However, if you have a few minutes and would like to give it a try with more sophisticated test apps, I'd appreciate it. 
fixes #6574
=> fix(nextjs): Export Replay from `index.server.ts` to avoid TS error

packages/core/test/lib/attachments.test.ts, packages/utils/src/envelope.ts, packages/utils/test/clientreport.test.ts, packages/utils/test/envelope.test.ts, packages/utils/test/testutils.ts
An envelope parser has existed in `packages/utils/test/testutils.ts` for a while. It looks like this was originally copied from the Electron e2e test server. I wrote that code and it's pretty awful and was only ever intended to be used for testing. 
To offer the best support for Replay (https://github.com/getsentry/sentry-electron/issues/606), its looking like the Electron main process will need to parse, modify and relay envelopes from the renderer processes. Sending events from renderer to main via a transport rather than an integration also fixes issues with integration ordering and confusing messages logged about events being dropped due to event processors returns null.
The new `parseEnvelope` has moved to `@sentry/utils` where it can be used by downstream SDKs. 
`parseEnvelope` is …
=> feat(utils): Improved envelope parser

packages/nextjs/src/config/templates/apiProxyLoaderTemplate.ts, packages/nextjs/src/index.client.ts, packages/nextjs/src/index.server.ts
Vercel Edge Functions [GA'd](https://vercel.com/blog/edge-functions-generally-available) which means the check for "experimental-edge" doesn't always work anymore. Luckily Next.js provides us with a [magic string we can use instead](https://edge-runtime.vercel.sh/features/available-apis#addressing-the-runtime) (`EdgeRuntime`).
=> feat(nextjs): Check for Vercel Edge Function GA

packages/types/src/event.ts
Fixes #6575 
As described in the issue, setting an `Event`'s property `type: undefined`, like we do in the SDK for `ErrorEvent`s
https://github.com/getsentry/sentry-javascript/blob/aad38ab819de0b7f83f6b188652f9ee8337704b0/packages/types/src/event.ts#L68-L70
causes a TS error, whenever the recommended `exactOptionalPropertyTypes` TS option is enabled. This option was introduced in TS 4.4. Since we're on TS 3.8, we couldn't catch this error. 
This PR changes to `EventType` type declaration to also accept `undefined` as a value, thereby resolving the TS error.
Note:
The initially suggested fix to change the `Event`'s  `type` type to `type: EventType | undefined` causes TS errors all over the place as it would require us to set `type` explicitly to `undefined` whenever we create error events. …
=> ref(types): Add `undefined` as possible value to  `EventType`

packages/replay/src/replay.ts, packages/replay/src/util/getReplayEvent.ts
This PR fixes an issue where an error is thrown if an event processor returns null.
=> fix(replay): Cater for event processor returning null 

README.md
Just noticed that we're not yet linking to the replay package
=> chore(docs): Add Replay link to main README file

rollup/plugins/bundlePlugins.js
When working on #6514 I missed that we access a "private" field in `client.getOptions()._metadata` to retrieve the SDK name. This had the consequence that - once again - we mangled a cross-package field we shouldn't (`_metadata`) in our CDN bundles which caused the SDK name to not be included in the replay event and envelope. 
This caused minified CDN bundles to send incomplete replay event envelopes to Sentry and as a consequence, they were not processed (correctly) and hence users didn't get incoming replays. 
This PR excludes the `_metadata` field from being mangled. Before merging this, I wanna see how much bundle size increase this causes. If it's too much, we can also revert #6514.
h/t @souredoutlook for raising this issue.
=> fix(replay): Do not mangle `_metadata` in client options

packages/react/jest.config.js
Currently, we have a bunch of `console.warn()` outputs there which mess up the test logs a bit.
=> test(react): Make react unit tests silent

packages/replay/src/replay.ts
I was just checking all the places where the Transport `send` is called and noticed this.
If the promise is not awaited within the try, the catch will never be called.
=> fix(replay): Envelope send should be awaited in try/catch

packages/browser/package.json, packages/browser/test/unit/index.test.ts, packages/core/src/baseclient.ts, packages/core/src/index.ts, packages/core/src/utils/prepareEvent.ts
So we can use this in replay, instead of using a private method from the client.
Also added a test to replay to make sure event processors work properly (which they didn't really before).
=> feat(core): Expose `prepareEvent` util function

packages/replay/jest.setup.ts, packages/replay/src/eventBuffer.ts, packages/replay/src/replay.ts, packages/replay/src/types.ts, packages/replay/src/util/createPayload.ts, packages/replay/src/util/createReplayEnvelope.ts, packages/replay/src/util/getReplayEvent.ts, packages/replay/test/unit/util/createReplayEnvelope.test.ts, packages/replay/test/unit/util/getReplayEvent.test.ts, packages/types/src/datacategory.ts, packages/types/src/envelope.ts, packages/types/src/index.ts, packages/types/src/replay.ts, packages/utils/src/envelope.ts
This PR upstreams some types from `@sentry/replay` to `@sentry/types`, in preparation for moving some stuff there.
Especially the `ReplayEvent` may still change a bit, but I think this should be fine.
=> feat(types): Upstream some replay types

packages/replay/src/constants.ts, packages/replay/src/integration.ts, packages/replay/test/unit/index-integrationSettings.test.ts
This PR improves the handling of the replay `maskAllText` option in two ways:
1. Currently, when `maskAllText === true` we overwrite the `maskTextSelector`. However, since we set `maskAllText = true` by default, this means that if you configure replay like this:
```js
new Replay({
maskTextSelector: '[custom]'
})
```
This will actually be overwritten by the maskAllText selector, because internally `maskAllText` is true.
This PR changes this behavior so that we only overwrite it if either we explicitly state `maskAllText: true`, or if we do not set it at all _and_ no `maskTextSelector` is specified.
So the new behavior is:
```js
// Result: all text selector
new Replay({})
// Result: [custom]
new Replay({ maskTextSelector: '[custom]' })
// Result: all text selector
new Replay({ …
```
=> fix(replay): Improve handling of `maskAllText` selector

packages/react/src/reactrouterv6.tsx
Fixes #6470 
This PR fixes a bug where we prematurely finish pageload transactions in our React Router 6 implementation due to some funky logic.
h/t to @onurtemizkan for doing the foundational work on this in https://github.com/getsentry/sentry-javascript/pull/6599
=> fix(tracing): Don't finish React Router 6 `pageload` transactions early

packages/replay/jest.setup.ts, packages/replay/src/replay.ts, packages/replay/src/util/getReplayEvent.ts, packages/replay/src/util/monkeyPatchRecordDroppedEvent.ts, packages/replay/test/unit/index.test.ts, packages/replay/test/utils/getDefaultBrowserClientOptions.ts, rollup/plugins/bundlePlugins.js
**NOTE**: Depends on https://github.com/getsentry/sentry-javascript/pull/6517
This uses the newly exposed `prepareEvent` util from core, and also makes sure that the event processors actually work as expected.
General changes:
* Ensure that replays can be dropped when an event processor returns `null` (previously, this would error)
* Removes some unneeded test stuff
=> feat(replay): Use new `prepareEvent` util & ensure dropping replays works

packages/replay/src/constants.ts, packages/replay/src/integration.ts, packages/replay/test/unit/flush.test.ts, packages/replay/test/unit/index-errorSampleRate.test.ts, packages/replay/test/unit/index-noSticky.test.ts, packages/replay/test/unit/index.test.ts
Following up on the PR review in #6593, this PR extracts the default values of flush min and max delays into constants.
Decided to pull this into its own PR to not clutter the original one with additional changes.
=> ref(replay): Extract flush min and max delay default values to constants

packages/core/src/baseclient.ts, packages/replay/src/util/getReplayEvent.ts, packages/types/src/client.ts, rollup/plugins/bundlePlugins.js
This PR adds a new method to the `Client` interface: `getSdkMetadata`.
We can use this method in the Replay package to avoid accessing `client.getOptions()._metadata`, which previously caused broken CDN bundles which we hot-fixed with #6600. This PR now properly fixes this issue by simply not accessing this "private" field anymore.
Since adding a new method to the `Client` Interface is a breaking change, I made it an optional method, which should avoid breakage. We should consider making this method required in v8. 
I tested the Replay CDN bundles with this change to ensure that we still send events.
~Note: I'm curious about the bundle size impact here, for example, if the added cost is ammortized by mangling `_metadata` now again. Hence leaving this as a draft for now.~
So, turns out, …
=> feat(core): Add `getSdkMetadata` to `Client`

packages/replay/src/replay.ts, packages/replay/src/util/getReplayEvent.ts, packages/replay/test/unit/util/getReplayEvent.test.ts
Instead of using the `replay_id`, we let sentry generate uuids for the `event_id` instead. Otherwise, multiple events will have the same `event_id`, which is not ideal. This still works because right now we do not actually use the `event_id` there, but for consistency it is better to have this be unique.
Closes https://github.com/getsentry/sentry-javascript/issues/6649
=> fix(replay): Generate uuids for replay events

packages/browser/test/unit/tracekit/chromium.test.ts, packages/utils/src/stacktrace.ts
Closes #2286
The CI code scanning previously warned about our stack trace regexes having the potential for DoS due to backtracking and exponential time required for large input strings. We ignored these CI warnings since the JavaScript SDKs have always contained these regexes but since a customer has reported a 90 second hang caused by this it makes sense to add some sensible limits.
=> fix(utils): Don't run stack trace regexes over huge strings

packages/replay/src/integration.ts, packages/replay/src/util/isBrowser.ts
Closes #6630
In Electron renderers with `nodeIntegration` enabled, `process.type === 'renderer'`.
I think this should be ok with bundlers. I think the check below for `isNodeEnv` uses `Object.prototype.toString` because bundlers can shim process with an object:
https://github.com/getsentry/sentry-javascript/blob/371d42d6eb8320ec7d1781e847649fcf06badf30/packages/utils/src/node.ts#L13-L20
=> fix(replay): Allow Replay to be used in Electron renderers with nodeIntegration enabled

packages/gatsby/package.json
At least the [Gatsby v5 release notes](https://www.gatsbyjs.com/docs/reference/release-notes/v5.0/) mention no changes to the plugin interfaces used here (`gatsby-browser#onClientEntry` and `gatsby-node#onCreateWebpackConfig`).
The only instruction for plugin maintainers in the [v4 to v5 migration guide](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/#for-plugin-maintainers) is that ”In most cases, you won’t have to do anything to be v5 compatible.”
Resolves getsentry/sentry-javascript#6261.
----
=> feat(gatsby): Support Gatsby v5

packages/core/src/envelope.ts, packages/core/src/hub.ts, packages/hub/test/hub.test.ts, packages/replay/src/coreHandlers/handleGlobalEvent.ts, packages/types/src/datacategory.ts, packages/types/src/event.ts, packages/types/src/index.ts
As a first step for https://github.com/getsentry/sentry-javascript/issues/6480, this adds the replay event type.
Note that replay is a bit special, in that it has two event types: `replay_event` and `replay_recording`. These are sent in one envelope, where `replay_event` contains the replay metadata etc, and `replay_recording` the actual recording as string. 
IMHO for the `event` type we have here it is sufficient to have `replay_event`, as the `replay_recording` is not really passed around but only need to be considered when we (eventually) build the envelope.
=> feat(core): Add `replay_event` type for events

packages/core/src/baseclient.ts, packages/core/src/integration.ts, packages/types/src/client.ts, packages/types/src/options.ts
This can be used to add an integration at runtime.
This is useful e.g. for replay, where we may want to lazy load this (as the payload is quite large).
=> feat(core): Add `addIntegration` method to client

packages/vue/src/components.ts
I stumbled over this by accident, and was wondering what you thought about making use of the in-built `string.repeat()` method there. This is not supported in IE11, but IMHO it is acceptable to fall back to just use the string once in that case, as it will only result in less-nice-looking nesting, not break. But not sure, maybe it is a bad idea, WDYT?
=> ref(vue): Use `string.repeat()`

packages/replay/src/replay.ts, packages/replay/test/unit/index-errorSampleRate.test.ts, packages/replay/test/unit/index.test.ts, packages/replay/test/unit/util/createReplayEnvelope.test.ts
Moves `replayType` from tags to part of `replay_event`.
Added in backend in https://github.com/getsentry/replay-backend/issues/210
=> feat(replay): Remove `replayType` from tags and into `replay_event`

packages/replay/src/replay.ts, packages/replay/src/util/getReplayEvent.ts, packages/replay/test/unit/util/getReplayEvent.test.ts
While testing Replay with my test app, I noticed that after we merged in #6650, the sent replays are still displayed in the replays list on sentry.io but if I click on one of them, I get a "Page not found" error page. So apparently, I was wrong in #6649 and we do in fact need the `event_id` to be the `replay_id`. 
Fixing this on the back-end will take some time, so let's merge this in for the time being.
=> Revert "fix(replay): Generate uuids for replay events (#6650)"

packages/replay/src/replay.ts, packages/replay/src/types.ts, packages/replay/test/unit/util/getReplayEvent.test.ts, packages/types/src/index.ts, packages/types/src/replay.ts
Fixes type error from https://github.com/getsentry/sentry-javascript/pull/6658 (semantic merge issue).
=> fix(replay): Fix ts errors with `replay_type`

packages/nextjs/src/config/wrappers/types.ts, packages/nextjs/src/config/wrappers/withSentryAPI.ts, packages/nextjs/test/integration/pages/api/doubleEndMethodOnVercel.ts, packages/nextjs/test/integration/test/server/doubleEndMethodOnVercel.js
Fixes https://github.com/getsentry/sentry-javascript/issues/6670
By [inspiration from axiom](https://github.com/axiomhq/next-axiom/blob/main/src/withAxiom.ts#L62-L94) we wrapped all response methods in order to flush in a timely manner on AWS lambdas and Vercel. Turns out this is unnecessary because `res.end` is implicitly called by `res.send` and `res.json` so it is the only one we need to block.
Additionally wrapping `send` and `json` caused race conditions when they're called before `.end` because we turned them into async functions so `end` would sometimes be called before the other methods and prematurely terminatedthe response.
This PR removes the wrapping from `res.json` and `res.end` to fix the issues outlined above.
=> fix(nextjs): Don't wrap `res.json` and `res.send`

docs/event-sending.md, packages/replay/.eslintrc.js, packages/replay/src/coreHandlers/breadcrumbHandler.ts, packages/replay/src/coreHandlers/handleDom.ts, packages/replay/src/coreHandlers/handleFetch.ts, packages/replay/src/coreHandlers/handleHistory.ts, packages/replay/src/coreHandlers/handleScope.ts, packages/replay/src/coreHandlers/handleXhr.ts, packages/replay/src/createPerformanceEntry.ts, packages/replay/src/eventBuffer.ts, packages/replay/src/integration.ts, packages/replay/src/replay.ts, packages/replay/src/session/saveSession.ts, packages/replay/src/types.ts, packages/replay/src/util/addMemoryEntry.ts, packages/replay/src/util/createBreadcrumb.ts, packages/replay/src/util/createPerformanceSpans.ts, packages/replay/src/util/createRecordingData.ts, packages/replay/src/util/createReplayEnvelope.ts, packages/replay/src/util/isBrowser.ts, packages/replay/src/util/isRrwebError.ts, packages/replay/src/util/monkeyPatchRecordDroppedEvent.ts, packages/replay/src/util/prepareReplayEvent.ts, packages/replay/test/unit/util/prepareReplayEvent.test.ts
This is one more step of https://github.com/getsentry/sentry-javascript/issues/6323.
Note that this also renames/moves a few things to make more sense:
* rename `createPayload()` to `createRecordingData()`
* rename `getReplayEvent()` to `prepareReplayEvent()`
* move `ReplayPerformanceEntry` type to `types.ts`
* move `createMemoryEntry` to `addMemoryEntry.ts`, as that was actually the only place where this was used
=> ref(replay): Add jsdoc to all replay modules

packages/nextjs/src/config/loaders/proxyLoader.ts, packages/nextjs/src/config/templates/apiProxyLoaderTemplate.ts, packages/nextjs/src/config/types.ts, packages/nextjs/src/config/webpack.ts, packages/nextjs/src/index.client.ts, packages/nextjs/src/index.server.ts
Ref https://github.com/getsentry/sentry-javascript/issues/6120
Builds currently emit warnings when there is a route using the Vercel edge runtime because we are injecting code into the serverless bundles that is using APIs that are not WinterCG compatible or we are wrapping with code that uses server SDK functions even though we are injecting the client SDK.
Also resolves https://github.com/getsentry/sentry-javascript/issues/5974
=> fix(nextjs): Exclude SDK from Edge runtime bundles

packages/angular/src/errorhandler.ts, packages/angular/test/errorhandler.test.ts
Closes #6332.
As discussed in the linked issue, it is more beneficial to handle error shaped objects instead of just instances of `Error`s.
=> ref(angular) Add error-like objects handling

packages/integration-tests/suites/integrations/httpclient/fetch/test.ts, packages/integration-tests/suites/integrations/httpclient/xhr/test.ts, packages/integration-tests/utils/generatePlugin.ts
This PR adds a configuration to be able to use `@sentry/integrations` package in our browser integration test scenarios.)
Currently, it only supports `@sentry/browser` and `@sentry/tracing` packages / bundles.
This is required to properly integration test #6500 (which is a browser integration from `@sentry/integrations` package)
=> feat(tests): Inject `@sentry/integrations` bundles to Playwright templates

.github/workflows/build.yml
This is to fix CI that is currently failing because we can't download deps from the ubuntu registry.
=> fix(ci): Update package lists before downloading playwright deps

.github/workflows/build.yml, packages/integration-tests/package.json, packages/remix/test/integration/package.json, yarn.lock
CI is failing on the newest remix version due to usage of the hammer operator: https://github.com/getsentry/sentry-javascript/actions/runs/3881841098/jobs/6621446961#step:6:1011
We assume this is a bug within the new remix release so we pin the version to a previous non-faulty one.
Issue in remix repo: https://github.com/remix-run/remix/issues/5043
Updating playwright seems to fix things?
=> ci: Fix CI failing on master

.github/workflows/build.yml
Only some of the playwright jobs seem to fail in the installation step and if one of them fails they cancel the other ones making it very unlikely that we will ever get CI to pass.
This is not a fix but a workaround until we understand why CI fails so often.
=> ci: Add `fail-fast: false` to playwright tests

packages/remix/package.json, packages/remix/src/index.types.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/6705
This PR makes the Remix SDK typings isomorphic by creating a type-only entrypoint that exports everything from the client part of the SDK and everything from the server part of the SDK.
=> fix(remix): Make remix SDK type exports isomorphic

packages/tracing/src/span.ts, packages/types/src/context.ts, packages/types/src/index.ts
ref https://github.com/getsentry/sentry-javascript/issues/6713
Add `TraceContext` type. See https://github.com/getsentry/relay/blob/master/relay-general/src/protocol/contexts/trace.rs
=> feat(types): Add Trace Context type

.github/workflows/build.yml
To reduce possible flakiness, we cache our playwright dependencies. This should help CI times and prevent us from downloading playwright assets over and over (preventing possible timeout issues).
=> test: Cache Playwright deps

packages/opentelemetry-node/src/spanprocessor.ts, packages/opentelemetry-node/test/spanprocessor.test.ts
ref: https://github.com/getsentry/sentry-javascript/issues/6713
Since the `SENTRY_SPAN_PROCESSOR_MAP` can be empty due to the transaction/span already finishing after the event processor was triggered (due to async event processors), we instead rely only on the OpenTelemetry context to determine the active span.
The product uses `trace_id` and `span_id` to associate errors to transactions, so that's what we've kept.
=> fix(otel): Set trace context via Otel Span instead of Sentry span

packages/nextjs/src/server/index.ts
It doesn't make sense that we export any of this functionality so let's just completely deprecate it and remove it in the next major.
=> ref(nextjs): Completely deprecate `isBuild()` and `IS_BUILD`

yarn.lock
https://www.npmjs.com/package/yarn-deduplicate
This is mainly done so that we only have a single version of playwright `1.29.2`, since that is what we are caching in CI: https://github.com/getsentry/sentry-javascript/blob/277264eacaf3053d95eba27405d66e134d535f2f/.github/workflows/build.yml#L584
=> chore: Run yarn deduplicate

packages/opentelemetry-node/src/propagator.ts, packages/opentelemetry-node/test/propagator.test.ts
ref: https://github.com/getsentry/sentry-javascript/issues/6713
We want to make sure that existing baggage is not overwritten when the Sentry Propagator sets the baggage header on the carrier. To do this, we defer to using the `W3CBaggagePropagator` to set the baggage header, and add the Sentry values by setting baggage via [OpenTelemetry's baggage API](https://opentelemetry.io/docs/reference/specification/baggage/api/).
=> fix(otel): Prevent baggage from being overwritten

nx.json
1. `build:tarball` is actually not cacheable
2. Make sure that we do not mark a package as needing to rebuild when tests change
3. Add missing dependencies for serverless build
Note that we are still very defensive and will rebuild quite often. E.g. when you change a file in replay/src, it will not cache replay, browser, and anything that depends on browser. but IMHO it is better to be too defensive, so that's OK.
Reference: https://nx.dev/more-concepts/customizing-inputs
=> build: Improve nx caching strategy

.github/workflows/build.yml
Currently, we do not store any cache for the master branch. When we run a PR, it will try to restore the cache from itself, then from the current branch, then just the newest cache it finds at all.
This means that on a fresh branch, it will restore the cache from the last action that ran - which could be any branch, which means the cache may incorporate changed we don't have, leading to us having to rebuild the cache.
Instead, this makes sure we restore from the master branch first, if possible. This makes it necessary to ensure we actually also _store_ the cache when running on master - we only pass a restore key in that case that will never match anything.
=> ci: Use nx cache from master by default

packages/replay/src/replay.ts
This was inadvertantly changed and was causing replays to have very long durations since it was waiting for 60k events before resetting buffer.
Closes #6720
=> fix(replay): Fix `checkoutEveryNms`

packages/replay/src/replay.ts, packages/replay/src/types.ts
This will be needed when attempting to send a replay request at a different time (e.g. after a reload).
=> ref(replay): Allow `timestamp` to be passed as an argument to `sendReplayRequest`

packages/utils/src/ratelimit.ts
While working on #6733, I noticed that the `ratelimit.ts` JSDocs could use a little rework as e.g. `updateRateLimits`'s doc mentioned an incorrect return value.
=> chore(utils): Adjust JSDoc of rate limit functions

packages/integration-tests/suites/replay/captureReplay/template.html, packages/integration-tests/suites/replay/captureReplay/test.ts, packages/integration-tests/suites/replay/init.js, packages/integration-tests/suites/replay/sampling/init.js, packages/integration-tests/suites/replay/sampling/template.html, packages/integration-tests/suites/replay/sampling/test.ts, packages/integration-tests/utils/helpers.ts
Adds two very basic integration tests for replay.
=> test(replay): Add basic replay integration tests

packages/integration-tests/suites/tracing/browsertracing/long-tasks-enabled/test.ts
Make the check in `should capture long task` integration test check for any number of ui spans instead of just one. In some situations in CI, there can be multiple long tasks instead of one (due to environmental conditions), so assert just to make sure they exist (and they are being recorded).
Should help fight against flakes like: https://github.com/getsentry/sentry-javascript/actions/runs/3901225358/jobs/6662950441
=> test: Adjust long task integration test ui span check

packages/integration-tests/suites/replay/captureReplay/test.ts, packages/replay/src/replay.ts, packages/replay/test/integration/rateLimiting.test.ts
Following up on #6710, this PR addresses option B and adds the following rate-limiting strategy to the Replay integration:
If we receive a rate limit response from the server after sending a replay event, we pause recording and flushing for the received rate limit period. After this period, we resume recording the same session, which triggers a full snapshot and hence should give us working replays. This should reduce segment-loss due to rate limiting, as we previously ignored handling rate limits specifically for replay (other than the transport's internal rate-limiting). 
I added a test to verify this behaviour but couldn't test it easily with a test app. Happy to take suggestions how to test this better. Otherwise, I think this should be good to go. 
ref #6710 
ref #6533
=> ref(replay): Pause recording when replay requests are rate-limited

packages/nextjs/src/config/withSentryConfig.ts
This pr adds a new optional argument for withSentryConfig that allows for easier merging of the next.config.js files in the Sentry Wizard. Now, the Wizard will call withSentryConfig with the 3rd argument which adds in the Sentry options we want to add to the config. This allows for easier merging of the config files, as 2 lines can be added to the existing next.config.js for it to work (https://github.com/getsentry/sentry-wizard/pull/222)
=> feat(nextjs): Add optional options argument to `withSentryConfig` as an alternative to the `sentry` property

packages/replay/jest.setup.ts, packages/replay/src/constants.ts, packages/replay/src/replay.ts, packages/replay/src/types.ts, packages/replay/src/util/prepareRecordingData.ts, packages/replay/src/util/sendReplay.ts, packages/replay/src/util/sendReplayRequest.ts, packages/replay/test/integration/errorSampleRate.test.ts, packages/replay/test/integration/events.test.ts, packages/replay/test/integration/flush.test.ts, packages/replay/test/integration/rateLimiting.test.ts, packages/replay/test/integration/sendReplayEvent.test.ts, packages/replay/test/integration/session.test.ts, packages/replay/test/integration/stop.test.ts
This extracts this out into a more functional style.
In addition, it also changes the `timestamp` we put on the replay to always reflect the time we've added it, no matter if it was retried.
This also renames a few things for clarity (e.g. `events` that was often passed around is actually `recordingData`, so we may as well reflect that in order to be clear about recordingData vs. events).
Note: This depends on https://github.com/getsentry/sentry-javascript/pull/6733, where I'll need to merge the changes once that is merged.
=> ref(replay): Extract `sendReplay` functionality into functions

packages/node/src/module.ts, packages/utils/src/path.ts, packages/utils/src/stacktrace.ts, packages/utils/src/string.ts, packages/wasm/src/registry.ts
`substr` is actually deprecated (see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr). 
For our cases, `slice()` should work just as well - see this very informative answer: https://stackoverflow.com/a/31910656
I noticed this while playing around with typescript update, which complains about this being deprecated.
As far as I see, `slice` and `substr` would only perform differently when `start !== 0`, which we don't have anywhere.
=> ref: Replace `string.substr` with `string.slice`

.github/ISSUE_TEMPLATE/bug.yml
For most incoming bug reports, its important for us to know how people set up their SDK, specifically, which init options they use. This PR adds such an input field to the "Bug" issue template. I decided to keep it optional for the time being as it doesn't apply to 100% of bug reports and some people already add this to the "Steps to Reproduce" section.
=> chore(github): Add "SDK Setup" Input to Bug GH Issue Template

packages/replay/src/replay.ts, packages/replay/test/integration/sendReplayEvent.test.ts
After some investigation, we decided that we actually don't really need a queue for handling replay events, because this is already basically handled by flushing.
For context, the flow in replay is as follows:
* When we try to flush (=send events), we wait debounced 5s
* When the debounce is done, we start flushing the currently recorded events. For this we take the events from the EventBuffer (removing them from there), and create a new flushlock.
* The flushlock resolves when the data has been successfully sent.
* While a flushlock exists, no new flush will happen. Any existing data remains in the eventBuffer.
Because of this, no segment can be sent before the previous segment has finished being sent.
So instead of adding a new queue, the only change of this PR is to ensure we actually …
=> feat(replay): Stop replays when a segment could not be sent

packages/opentelemetry-node/src/propagator.ts, packages/opentelemetry-node/test/propagator.test.ts
When testing with a GRPC example I found that the carrier can return an empty array for some values. This checks for that, and adds a validation test.
=> fix(otel): Make sure we handle when sentry-trace is an empty array

packages/node/src/integrations/localvariables.ts, packages/node/test/integrations/localvariables.test.ts
Closes #6769
I didn't use `process.config.variables.v8_enable_inspector` since it appears undocumented and wrapping the loading in try/catch feels more future proof.
=> fix(node): Handle node build without `inspector` in `LocalVariables` integration

.github/ISSUE_TEMPLATE/flaky.yml
Flaky tests are cancelled.
Add a issue template (mostly copied from https://github.com/getsentry/sentry/blame/master/.github/ISSUE_TEMPLATE/flaky.yml) that allows us to easily create issues when we identify flaky tests.
=> chore: Add flaky test template

packages/nextjs/test/integration/test/server/doubleEndMethodOnVercel.js, packages/nextjs/test/run-integration-tests.sh
Fixes https://github.com/getsentry/sentry-javascript/issues/6784
Since `doubleEndMethodOnVercel` seems only to be flaky on Node 10, and it's very rare that NextJS apps are running on Node 10 (and impossible on Vercel), prevent this test from running in Node 10.
=> test(nextjs): Disable `doubleEndMethodOnVercel` on Node 10

packages/browser/src/client.ts, packages/eslint-config-sdk/src/index.js, packages/eslint-plugin-sdk/src/index.js, packages/eslint-plugin-sdk/src/rules/no-optional-chaining.js, packages/nextjs/.eslintrc.js, packages/node/.eslintrc.js, packages/opentelemetry-node/.eslintrc.js, packages/react/src/reactrouterv6.tsx, packages/remix/.eslintrc.js, packages/replay/src/coreHandlers/handleGlobalEvent.ts, packages/replay/src/coreHandlers/handleXhr.ts, packages/replay/src/eventBuffer.ts, packages/replay/src/replay.ts, packages/replay/src/types.ts, packages/replay/src/util/addEvent.ts, packages/replay/src/util/isRrwebError.ts, packages/replay/src/util/isSessionExpired.ts, packages/replay/src/util/sendReplayRequest.ts, packages/replay/src/util/shouldFilterRequest.ts, packages/serverless/.eslintrc.js, packages/tracing/.eslintrc.js, packages/tracing/src/browser/browsertracing.ts, packages/utils/src/requestdata.ts, packages/utils/src/stacktrace.ts, packages/vue/src/components.ts, packages/vue/src/tracing.ts, packages/wasm/.eslintrc.js
As this is transpiled to a rather verbose form.
This PR now also adds an eslint rule based on https://github.com/facebook/lexical/pull/3233 to enforce avoiding optional chaining. I left it for all node-based stuff, because there we don't care, I guess.
=> ref: Avoid optional chaining & add eslint rule

.git-blame-ignore-revs
Inspired by https://github.com/getsentry/sentry/blob/master/.git-blame-ignore-revs, this patch adds a .git-blame-ignore-revs file to the JS monorepo.
It was mainly motivated by getting rid of #6662 from git blame, and hopefully in the future this will help with bigger refactors.
=> chore: Add .git-blame-ignore-revs

packages/nextjs/src/edge/utils/edgeWrapperUtils.ts
Seems like through some weird behavior passing a scope function to `captureException` disconnects the active span from the error. This PR fixes this for Edge API routes in the Next.js SDK.
=> fix(nextjs): Connect Edge API route errors to span

packages/nextjs/package.json, packages/nextjs/rollup.npm.config.js, packages/nextjs/src/index.client.ts, packages/nextjs/src/index.server.ts, packages/nextjs/src/index.ts, packages/nextjs/test/serverSdk.test.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/6808
Some build pipelines that run outside of Next.js look at the `browser` field in the package.json to import package code that is intended for the browser.
With https://github.com/getsentry/sentry-javascript/pull/6753 we removed the browser field, thinking it wasn't necessary, breaking tooling like Storybook which now imported Node code.
This PR adds back the browser field, but we need to add another multiplexer entry point because Next.js will also look at the `browser` field to import SDK code for the Edge runtime.
=> fix(nextjs): Add back browser field in package.json

packages/replay/README.md
I noticed that the replay readme setup instructions were a bit out of date, so updated stuff there to align with the current state of things.
[Rendered](https://github.com/getsentry/sentry-javascript/blob/fn/replay-docs/packages/replay/README.md)
=> docs(replay): Update setup docs for replay

.github/workflows/build.yml, packages/integration-tests/suites/replay/captureReplay/test.ts, packages/integration-tests/suites/replay/captureReplayViaBrowser/init.js, packages/integration-tests/suites/replay/captureReplayViaBrowser/template.html, packages/integration-tests/suites/replay/captureReplayViaBrowser/test.ts, packages/integration-tests/suites/replay/errorResponse/test.ts, packages/integration-tests/suites/replay/init.js, packages/integration-tests/suites/replay/sampling/init.js, packages/integration-tests/suites/replay/sampling/test.ts, packages/integration-tests/utils/generatePlugin.ts, packages/integration-tests/utils/helpers.ts, rollup/plugins/bundlePlugins.js
Thanks to #6666 we now can inject integration CDN bundles into our Playwright tests. This PR builds on top of #6666 and #6735 to inject the Replay CDN bundle into our integration tests and test against them.
We still can't get rid of the skip condition at the beginning of Replay tests, as we don't have es5 bundles for replay but I think that's fine for the time being. 
Furthermore, for this to work properly, Replay has to be imported from `@sentry/replay`. As a result, tests that run against Replay bundles technically don't check that it is continued to be exported via `@sentry/browser`. Hence, I copied the basic `captureReplay` test and left it once untouched, so we still cover importing Replay via `@sentry/browser`.
In order to test against the minified CDN bundles (which is most …
=> test(replay): Test against CDN bundles in Playwright integration tests

.size-limit.js, packages/replay/README.md, packages/tracing/rollup.bundle.config.js, packages/tracing/src/index.bundle.replay.ts, packages/tracing/src/index.bundle.ts, packages/tracing/test/index.bundle.replay.test.ts, packages/tracing/tsconfig.types.json, rollup/bundleHelpers.js
Adds another CDN bundle `bundle.tracing.replay.js` which includes both tracing and replay.
=> build(replay): Provide full browser+tracing+replay bundle

packages/nextjs/src/config/loaders/wrappingLoader.ts
Potentially/hopefully relates to https://github.com/getsentry/sentry-javascript/issues/6815
s/js/ts/ in a place where js should be ts.
=> fix(nextjs): Correctly handle ts middleware files

packages/opentelemetry-node/src/propagator.ts, packages/opentelemetry-node/src/spanprocessor.ts, packages/opentelemetry-node/test/propagator.test.ts
fixes https://github.com/getsentry/sentry-javascript/issues/6807
Set baggage even when there is no active transaction. We do this because we are responsible for propagating baggage via the `W3CBaggagePropagator` which the `SentryPropagator` inherits from.
=> fix(otel): Always set baggage regardless of active transaction

packages/nextjs/src/server/wrapApiHandlerWithSentry.ts, packages/nextjs/src/server/wrapAppGetInitialPropsWithSentry.ts, packages/nextjs/src/server/wrapDocumentGetInitialPropsWithSentry.ts, packages/nextjs/src/server/wrapErrorGetInitialPropsWithSentry.ts, packages/nextjs/src/server/wrapGetInitialPropsWithSentry.ts, packages/nextjs/src/server/wrapGetServerSidePropsWithSentry.ts, packages/nextjs/src/server/wrapGetStaticPropsWithSentry.ts, packages/nextjs/test/config/withSentry.test.ts, packages/nextjs/test/config/wrappers.test.ts
Blocks release in https://github.com/getsentry/sentry-javascript/pull/6818 as well
Only instrument NextJS data fetchers for performance if the instrumenter is set to sentry (default).
=> fix(nextjs): Disable NextJS perf monitoring when using otel

nx.json
This sneaked through, and is actually not necessary from a dependency perspecitve.
=> build: `build:bundle` does not depend on `build:types`

packages/react/src/profiler.tsx
fixes https://github.com/getsentry/sentry-javascript/issues/6708
=> fix(react): Add children prop for Profiler

packages/replay/README.md
Remove the advanced recording configuration options as we want greater control over how recording should be done. The SDK API will be changed at a later point so that these options will not be passed. Instead we will provide good defaults that shouldn't need to be configured.
Related https://github.com/getsentry/sentry-docs/pull/6094, https://github.com/getsentry/sentry-javascript/issues/6390
=> doc(replay): Remove advanced configuration

packages/integration-tests/suites/tracing/browsertracing/long-tasks-disabled/init.js, packages/tracing/src/browser/browsertracing.ts, packages/tracing/test/browser/browsertracing.test.ts
This experiment was on by default, which showed that this is not actually an experiment anymore, and thus should be promoted to a regular option.
=> feat(tracing): Promote `enableLongTask` to option of `BrowserTracing`

packages/replay/CONTRIBUTING.md
No longer true after:
https://github.com/getsentry/sentry-docs/pull/6094/files
=> chore(replay): contributing.md outdated note

packages/replay/rollup.npm.config.js, rollup/npmHelpers.js
Previously, when transpiling Replay, we preserved modules, just like in every other SDK of ours. In the case of Replay, however, we don't just rely on external dependencies but we want to include a patched version of rrweb in our NPM package. This lead to problems with specific bundler/build tool setups as reported in (#6690). 
With this PR, we don't preserve modules any longer, meaning, everything is bundled into one `index.js` file (similarly to CDN bundles). 
Just so that we're all aware: This is a breaking change for anyone who imports from explicit paths (e.g. `import { something } from '@sentry/replay/utils/test'`). However, we considered this okay in the past (e.g. #6707) as it is not something we instruct people to do in our docs and it is kind of an edge case. Given that Replay …
=> build(replay): Stop preserving modules

packages/replay/jest.setup.ts, packages/replay/rollup.bundle.config.js, packages/replay/rollup.npm.config.js, packages/replay/src/types.ts, packages/replay/src/util/prepareReplayEvent.ts, packages/replay/test/unit/util/prepareReplayEvent.test.ts, packages/tracing/rollup.bundle.config.js
Since we now export Replay via the Browser SDK we can now send the SDK version instead of the Replay package.json version, allowing us to get rid of the custom rollup config to inject said version. 
closes #6366
=> ref(replay): Send SDK version in Replay events

packages/nextjs/src/config/webpack.ts, packages/nextjs/src/config/withSentryConfig.ts, packages/nextjs/test/config/withSentryConfig.test.ts
First, a bit of history: A while back we decided to [exclude our build time dependencies](https://github.com/getsentry/sentry-javascript/pull/6058) from the files that are uploaded to AWS Lambdas through Vercel. This was done by modifying the NFT Plugin Next.js injects. This [caused us to break during runtime](https://github.com/getsentry/sentry-javascript/issues/6265) because the build files could be required when the server starts. The fix for that however [broke `next dev`](https://github.com/getsentry/sentry-javascript/issues/6284) and we had to [convert our `withSentryConfig` function to return a function](https://github.com/getsentry/sentry-javascript/pull/6291) so that we can make an exception for the `dev` phase.
The last change caused an avalanche of issues to appear which we …
=> ref(nextjs): Remove NFT build time exclusions

packages/replay/src/constants.ts
This means that we will only wait 5 seconds before flushing. This should help reduce potential lost segments due to page reloads/closed tabs.
=> feat(replay): Lower the flush max delay from 15 seconds to 5 seconds

packages/replay/metrics/src/results/pr-comment.ts, packages/replay/metrics/src/util/console.ts
as discussed here: https://github.com/getsentry/sentry-javascript/pull/6761#issuecomment-1387106795
=> chore: update metrics PR comment diff/percentage base

.github/workflows/build.yml, .github/workflows/canary.yml, packages/ember/package.json
Now, the ember tests are run "normally" as part of the browser unit tests, plus with the canary tests we run it in all envs (which are the latest versions), potentially spotting breaking changes.
=> ci(ember): Only run pinned tests for ember on build, + add canary tests

packages/integration-tests/suites/replay/captureReplay/test.ts, packages/integration-tests/suites/replay/captureReplayViaBrowser/test.ts, packages/integration-tests/suites/replay/errorResponse/test.ts, packages/integration-tests/suites/replay/sampling/test.ts, packages/integration-tests/utils/helpers.ts, packages/integration-tests/utils/replayHelpers.ts
This PR replaces a bunch of `page.waitForTimeout` calls with `page.waitForRequest` waits which should make Replay integration tests more stable. I couldn't remove all timeout calls, as we're not always actually waiting for a request but the ones that failed mostly in CI are now gone. 
When relying on outgoing http requests during a test, we should try to be as specific as possible in terms of _which_ request we're actually expecting when. Therefore, I added a `waitForReplayRequest`, which ensures we're actually waiting for a replay request. Optionally, this helper takes a `segmentId` to wait for a replay request of a specific replay segment. This might be useful for more involved testing scenarios.
closes #6800
=> fix(ci): Reduce flakiness of Replay integration tests

packages/replay/README.md, packages/replay/src/integration.ts
This exposes a `flush` method on the integration class, which can be used to flush any pending replay recording data immediately.
This has been requested a few times, and while this PR does not really add a first-class solution for this problem, it at least makes it possible to solve it manually. In combination with `replaysOnErrorSampleRate: 1` we can ensure that we _always_ capture up to 60s of replay data. Then, clients may trigger `replay.flush()` at any time (e.g. when the user clicks a "submit error" button or similar), sending the buffered replay data.
note: I went with `flush` vs. `flushImmediate`, as I'd say that is an internal concern of the replay container class - from a users perspective, `flush` makes sense here IMHO?
ref …
=> feat(replay): Add `flush` method to integration

packages/remix/playwright.config.ts, packages/remix/src/utils/instrumentServer.ts
Resolves: #6821 
This problem appears not to be a flaky test, it's a node bug recurring on certain versions, which apparently happens rarely, and our testing environment (high concurrency in a small container maybe) seems to amplify its frequency.
Looks like this can happen when the domain is used right after the creation, which is the case in our Remix implementation. And the [proposed workaround](https://github.com/nodejs/node/issues/40999#issuecomment-1002719169) seems to resolve it with this PR. (8 CI runs without errors here, only failed case is https://github.com/getsentry/sentry-javascript/issues/6848, will be addressed with another PR).
For reference:
https://github.com/getsentry/sentry-javascript/issues/2089
https://github.com/nodejs/node/issues/30122 …
=> fix(remix): Make sure the domain is created before running.

packages/replay/src/util/debounce.ts, packages/replay/test/integration/sendReplayEvent.test.ts
Since we now have a default flush time === max flush time in replay, we can skip the duplicate timer in that case.
=> ref(replay): Avoid duplicate debounce timers

packages/nextjs/src/config/webpack.ts
The SDK multiplexer loader in the Next.js SDK responsible for routing imports to the correct runtime SDK wasn't matching files correctly on Windows. This PR adjusts the loader matching to be able to deal with Windows paths.
Fixes https://github.com/getsentry/sentry-javascript/issues/6858
=> fix(nextjs): Fix SDK multiplexer loader on Windows

.github/workflows/build.yml
This PR fixes (hopefully) the size-limit CI check.
After a lot of digging, I figured out that when the size-limit action runs on CI, it basically doesn't do the same as on the PR. On master, we do not skip the install & build step, but re-run them. Especially, we also just run `yarn install` & `yarn build`, which may have a slightly different outcome. Additionally, this also means that the size check on master takes > 8min, because we re-run all the build stuff etc.
I made a PR to fix our size-limit action: https://github.com/getsentry/size-limit-action/pull/7
For now, we can simply use this branch, until this has been merged.
Note that while debugging this, I also noticed a necessary improvement with the label check. basically, it appeares that the labels that we can fetch from the …
=> ci: Fix size-limit check

packages/opentelemetry-node/src/utils/map-otel-status.ts
Prioritize http/grpc status over span status when we generate a status for a sentry span. This is because they are more thorough then OpenTelemetry's span status values.
=> fix(otel): use http/grpc status over span status

packages/integration-tests/suites/replay/captureReplayViaBrowser/init.js, packages/integration-tests/suites/replay/init.js, packages/integration-tests/suites/replay/sampling/init.js, packages/replay/src/constants.ts, packages/replay/src/integration.ts, packages/replay/src/replay.ts, packages/replay/src/types.ts
This is not in use anymore - we always flush immediately on load. So we can remove this option.
=> ref(replay): Remove unused `initialFlushDelay` option

packages/node-integration-tests/suites/public-api/LocalVariables/local-variables.js, packages/node/src/integrations/localvariables.ts, packages/node/src/types.ts, packages/node/test/integrations/localvariables.test.ts
=> feat(node): Use `includeLocalVariables` option to enable `LocalVariables` integration

packages/replay/README.md
7.31.0 doesn't have the single bundle with errors+perf+replay. Fixing by adding the patch
=> replay: fix CDN version on readme

packages/integration-tests/playwright.config.ts, packages/nextjs/playwright.config.ts, packages/remix/playwright.config.ts
Resolves: #6848
Resolves: #6872 
Updating Playwright configurations to use the [default 30 seconds](https://playwright.dev/docs/test-timeouts), instead of 12 seconds configured. Not sure why we decreased the test timeout in the first place.
The case in #6848 happens randomly in any test in the same file, so I suspect this is just about the shortened timeout, rather than certain implementation / test that trigger flaking.
Testing here to check if there is a hanging test that hits the default 30 seconds.
---
Edit: No flakes for #6848 or #6872 after 9 CI trials on this PR.
=> fix(tests): Use the default Playwright timeouts.

packages/node-integration-tests/suites/sessions/server.ts, packages/remix/test/integration/test/client/manualtracing.test.ts
Resolves: #6868 
Increasing flush interval to 1000ms to 2000ms, with overall timeout from 2000ms to 4000ms.
Looks like the test flakes because of early-flushing (before 'slow' endpoint finishes), so also decreased the slowness of the 'slow' endpoint. 
This branch consistently succeeded on local, will test on CI here.
---
**Update**: None of the 11 CI runs here have failed session tests.
=> fix(tests): Increase flush interval of session tests.

packages/nextjs/src/config/loaders/sdkMultiplexerLoader.ts, packages/nextjs/src/index.client.ts, packages/nextjs/src/index.server.ts
https://github.com/getsentry/sentry-javascript/pull/6817/files#diff-5598248a0f2280565998f93876df482b2040cb761cc510b3bd2c4dfa5824dca8L103 seems to have broken the Next.js SDK multiplexer which is responsible for injecting the right SDK depending on whether the SDK is imported on browser/server/edge. It broke because it started stripping away the comment that told our loader to multiplex.
I suspected the comment was a little fragile from the beginning so let's make it a little bit more resilient by exporting a dummy const which is more or less guaranteed to be in the file to some extent. Maybe still not the optimal solution but better than the current one. The dummy export should not show up in types since the typing file we export doesn't actually point to the multiplexer files.
Oh, and we …
=> fix(nextjs): Make SDK multiplexer more resilient

packages/replay/MIGRATION.md, packages/replay/src/constants.ts, packages/replay/src/integration.ts
Previously, they were:
* `replaysSessionSampleRate: 0.1`
* `replaysOnErrorSampleRate: 1.0`
Now, you have to explicitly set the sample rates, otherwise they default to 0.
Closes https://github.com/getsentry/sentry-javascript/issues/6775
=> feat(replay): Remove default sample rates for replay

packages/replay/src/replay.ts
There were rare instances where stopping rrweb.record would cause an exception to bubble up from rrweb.
=> feat(replay): try/catch around rrweb function calls

packages/replay/src/eventBuffer.ts, packages/replay/src/replay.ts, packages/replay/src/types.ts, packages/replay/test/integration/flush.test.ts
This PR adjusts https://github.com/getsentry/sentry-javascript/pull/6854 to be fully sync.
I tried it in a test app, and it seemed to send the request out - I tried setting up a proxy to properly see logs, and it _appeared_ correct, although not 100% sure if that matches real-world usage.
=> ref(replay): Try to make flush on unload fully sync

packages/nextjs/rollup.npm.config.js
Similar to https://github.com/getsentry/sentry-javascript/pull/6905, https://github.com/getsentry/sentry-javascript/pull/6817/files#diff-5598248a0f2280565998f93876df482b2040cb761cc510b3bd2c4dfa5824dca8L103 started tree shaking away the exports from the files we were targeting with the multiplexer, causing some imports not to be available. This PR fixes this by marking the targets as entrypoints.
Fixes https://github.com/getsentry/sentry-javascript/issues/6915
(I am deeply questioning our test suite at this point)
=> fix(nextjs): Mark multiplexer targets as entrypoints

docs/new-sdk-release-checklist.md
Because _something_ has to go wrong every time we release new packages
=> chore(docs): Add publishConfig to release checklist

.github/workflows/codeql-analysis.yml
CodeQL was not running on pull requests targeting the master branch. 🙂 
Using a `!` in the `paths` directive requires us to list another path without it to work properly in this case.(docs [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-paths:~:text=If%20you%20define%20a%20path%20with%20the%20!%20character%2C%20you%20must%20also%20define%20at%20least%20one%20path%20without%20the%20!%20character.%20If%20you%20only%20want%20to%20exclude%20paths%2C%20use%20paths%2Dignore%20instead.)). Since we are only looking to exclude the path, I've opted to switch us to use `paths-ignore`.
=> codeql(config): fix workflow on ignored .md files

packages/replay/metrics/src/scenarios.ts
Fixes [CodeQL #81](https://github.com/getsentry/sentry-javascript/security/code-scanning/81). The `.replace()` originally here only replaced the first occurrence of double-backslashes. Using a regex with a global flag option ensures all of the `\\`'s are replaced with `/`.
=> fix(replay): fix path separator substitution to replace all `\\`

packages/replay/metrics/src/collector.ts, packages/replay/metrics/src/perf/network.ts, packages/replay/metrics/src/results/analyzer.ts, packages/replay/metrics/src/results/metrics-stats.ts, packages/replay/metrics/src/scenarios.ts, packages/replay/metrics/src/util/console.ts, packages/replay/metrics/src/util/github.ts, packages/replay/metrics/src/util/json.ts
Adds network info to the collected metrics - it shows the amount of data sent (Net Tx) and received (Net Rx) by the browser. It works by intercepting the network requests with a custom handler that logs the transmission stats. Because Sentry SDK is the only application code sending requests, it equals the amount of data sent & received by the SDK. You can see in the example below that because there are no errors triggered, there's no data sent/received with just the plain Sentry SDK; there's network traffic only when Replay is added.
Currently, only HTTP requests are captured, no `file:///` URLs (these are used to load the actual page and scripts from the local filesystem).
https://github.com/vaind/sentry-javascript/pull/2#issuecomment-1398165146
=> chore: collect replay network metrics

packages/replay/src/constants.ts, packages/replay/src/eventBuffer/EventBufferArray.ts, packages/replay/src/eventBuffer/EventBufferCompressionWorker.ts, packages/replay/src/eventBuffer/EventBufferProxy.ts, packages/replay/src/eventBuffer/index.ts, packages/replay/src/replay.ts, packages/replay/test/integration/errorSampleRate.test.ts, packages/replay/test/unit/eventBuffer.test.ts
partially extracted from https://github.com/getsentry/sentry-javascript/pull/6924
This PR improves the event buffer to handle compression worker errors more gracefully.
1. Split up the event buffers into separate files
2. Ensure the initial event is compressed
3. Fall back to using the uncompressed payload when worker compression fails
=> fix(replay): Handle compression worker errors more gracefully

packages/replay/src/replay.ts, packages/replay/src/session/getSession.ts, packages/replay/test/integration/errorSampleRate.test.ts, packages/replay/test/integration/events.test.ts, packages/replay/test/integration/flush.test.ts, packages/replay/test/integration/rateLimiting.test.ts, packages/replay/test/integration/sendReplayEvent.test.ts, packages/replay/test/integration/session.test.ts, packages/replay/test/integration/stop.test.ts
Currently, when you have a replay session running because of an error, and the session expires (after 15min of inactivity or 60min of activity), we just create a new session (again in error mode) and continue recording.
This is confusing because from a users perspective, they see replays in error mode but with (potentially) no error connected to it.
This PR changes this behavior - when in error mode, and the session expires, we stop the replay.
=> fix(replay): Do not renew session in error mode

CHANGELOG.md
=> meta: Update changelog for 7.34.0

packages/utils/src/browser.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/3056
=> feat: Add aria label to breadcrumb attributes

packages/e2e-tests/Dockerfile.publish-packages
Bumps the default Node version for `Dockerfile.publish-packages` to the latest v16.19.0.
This resolves various vulnerabilities patched between 16.15.1 and 16.19.0.
=> chore(deps): bump default node to latest v16 for e2e-tests

packages/utils/src/normalize.ts, packages/utils/test/normalize.test.ts
It's possible for `Object.getPrototypeOf` to return `null` (when the object is created via `Object.create(null)`), in which case `null.constructor.name` will throw.
If there is no prototype, this falls back to `null prototype`.
=> fix: Account for object's prototype possibly being null

packages/replay/src/coreHandlers/handleScope.ts, packages/replay/test/unit/coreHandlers/handleScope.test.ts
`Scope.getLastBreadcrumb` was introduced quite recently for replay and it generally works fine. Just in the few edge cases, where the base SDK version can't be changed or multiple hubs cause conflicts, Replay will crash when the method is not available on the passed scope. This PR lets `handleScope` early-return `null` in case the `getLastBreadcrumb` method does not exist. This will lead to missing breadcrumbs in the replay but at least it will avoid a crash.
closes https://github.com/getsentry/sentry-javascript/issues/6542
=> fix(replay): Only call `scope.getLastBreadcrumb` if available

packages/nextjs/src/edge/transport.ts, packages/nextjs/src/edge/utils/edgeWrapperUtils.ts, packages/nextjs/test/edge/edgeWrapperUtils.test.ts, packages/nextjs/test/edge/transport.test.ts, packages/nextjs/test/edge/withSentryAPI.test.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/6975
Vercel edge routes don't allow shared access to I/O resources (req, res objects etc.) between requests. Our flushing logic inside the default PromiseBuffer was inherently doing that by processing outgoing fetch requests, even after the Edge route terminated.
This PR aims to resolve this issue by making the flushing of Sentry events atomic to a particular request.
=> fix(nextjs): Don't share I/O resources in between requests

packages/nextjs/src/config/loaders/wrappingLoader.ts, packages/nextjs/test/integration/pages/api/requireTest.ts, packages/nextjs/test/integration/test/server/cjsApiEndpoints.test.ts, packages/nextjs/test/integration/test/server/utils/throw.js
The wrapping loader in the Next.js SDK seems to have problems with CJS.
Users reported the following issues:
- https://github.com/getsentry/sentry-javascript/issues/6970 reports that dynamic imports return undefined. This PR fixes that by setting the `ignore` option to ignore all CJS imports.
- https://github.com/getsentry/sentry-javascript/issues/6943 reports that require calls are incorrectly hoisted by our loader. This PR fixes that by setting `strictRequires` to true, which will disable the hoisting that is meant to simulate ESM.
- https://github.com/getsentry/sentry-javascript/issues/6961 reports that Webpack's `require.context` is broken with our SDK. This PR fixes that by setting the `ignoreDynamicRequires` option to `true` which will stop mangling these require calls.
Fixes …
=> fix(nextjs): Don't modify require calls in wrapping loader

packages/utils/src/env.ts, rollup/bundleHelpers.js, rollup/npmHelpers.js, rollup/plugins/bundlePlugins.js
ref: https://github.com/getsentry/sentry-javascript/issues/6903
Add `__SENTRY_SDK_SOURCE__` that tracks the source of the sdk. Right now there are 3 specific values for this: `'npm' | 'cdn' | 'loader'`.
`npm` and `cdn` are filled in at build time, and `loader` will be added via a global flag that the loader itself will set. More details on this soon.
=> build(utils): Add build constant for cdn vs. npm bundles

packages/browser/src/client.ts, packages/browser/test/unit/index.test.ts, packages/utils/src/env.ts, packages/utils/src/worldwide.ts
ref https://github.com/getsentry/sentry-javascript/issues/6903
Based on work in https://github.com/getsentry/sentry-javascript/pull/6904
Adjust the package name source to see if from cdn or npm.
=> feat(browser): Track if cdn or npm bundle

packages/nextjs/package.json, packages/nextjs/src/index.types.ts, packages/nextjs/src/server/index.ts, packages/react/src/errorboundary.tsx
Trying to enable the app-dir server tests on master gave me a failure that we are importing react specifics on the server which is not allowed on in the app dir.
This PR creates react-less pass-throughs for the server SDK to get rid of this error. This error might actually also appear for some users.
=> fix(nextjs): Add isomorphic versions of `ErrorBoundary`, `withErrorBoundary` and `showReportDialog`

packages/integration-tests/suites/replay/captureReplay/test.ts, packages/integration-tests/suites/replay/captureReplayViaBrowser/test.ts, packages/replay/src/util/sendReplayRequest.ts, packages/replay/test/integration/errorSampleRate.test.ts, packages/replay/test/integration/events.test.ts, packages/replay/test/unit/util/createReplayEnvelope.test.ts, packages/replay/test/unit/util/prepareReplayEvent.test.ts, packages/types/src/replay.ts
Move sample rate from tags into context as that is the more appropriate location for this type of data. This data is more for us to collect to debug rather than having as a top level field on the replay event.
=> feat(replay): Move sample rate tags into event context

packages/nextjs/src/config/webpack.ts, packages/nextjs/test/config/webpack/constructWebpackConfig.test.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/7006
Apparently with https://github.com/getsentry/sentry-javascript/pull/6927 we broke some ordering of SDK injection for stuff like [Next.js' `getConfig()`](https://nextjs.org/docs/api-reference/next.config.js/runtime-configuration) to work.
=> fix(nextjs): Inject client config into `_app` instead of `main`

packages/replay/package.json, yarn.lock
This bumps rrweb to 1.100.2, which adds some more error catching/handlung stuff:
https://github.com/getsentry/rrweb/releases/tag/1.100.2
=> fix(replay): Catch style mutation handling & null events in rrweb

packages/browser/src/loader.js
As per https://github.com/getsentry/sentry-javascript/issues/6990 the loader in the JS monorepo and sentry template has drifted apart. This syncs them together (validated by the integration tests in the JS monorepo).
PR in Sentry repo: https://github.com/getsentry/sentry/pull/43880
=> feat(loader): Sync loader with Sentry template

CHANGELOG.md
=> meta: Update CHANGELOG for 7.35.0

docs/publishing-a-release.md, package.json, scripts/get-commit-list.ts
Since I got slightly annoyed about manually sorting the commits, I wrote a small script to automate that for us.
Now, you can just run `yarn changelog` to get all commits since the last release, alphabetized.
E.g. for the current release it output this:
```
- build(deps): bump simple-git in /packages/replay/metrics
- build(utils): Add build constant for cdn vs. npm bundles (#6904)
- chore: Upgrade Node to 16.9.0 (#6971)
- chore(deps): bump default node to latest v16 for e2e-tests (#6962)
- ci: Add labels to gitflow PRs (#6997)
- ci: Fix gitflow workflows (#6995)
- ci: Setup gitflow process (#6890)
- ci(deps): bump actions/upload-artifact from 3.1.1 to 3.1.2 (#6994)
- docs(replay): Add changelog entry and migration log for privacy API (#7008)
- feat: Add aria label to breadcrumb attributes …
```
=> build: Add `yarn changelog` command

.github/workflows/gitflow-sync-develop.yml, .github/workflows/gitflow-sync-master.yml
This supersedes https://github.com/getsentry/sentry-javascript/pull/6999.
With this PR:
* We do not run auto-approval (until we figured this out)
* We only run develop->master sync when merging a PR with a title starting with `meta(changelog):`
* We merge this exact commit into master, not current develop (so if something was merged in the meanwhile, it should not go into this release).
* develop->master sync cannot be triggered via workflow_dispatch anymore (to simplify this. We can still always do this manually)
=> ci: Improve gitflow process

.github/workflows/gitflow-sync-develop.yml, .github/workflows/gitflow-sync-master.yml
Otherwise, workflows will not be triggered due to security issues. See https://github.com/peter-evans/create-pull-request/issues/48 for details.
This should also fix the self-approval issue.
Also fixes a typo in the workflow.
Also fixes a problem where the master->develop workflow is triggered on each PR closed, but then fails because no job is run. Now it will run an empty dummy-job.
=> ci(gitflow): Use personal access token to create PR

packages/replay/src/replay.ts, packages/replay/src/util/sendReplay.ts, packages/replay/src/util/sendReplayRequest.ts, packages/replay/test/integration/rateLimiting.test.ts
As discussed and outlined in #6984, we want to entirely stop recording the replay once we receive a 429 rate limit response. This PR gets rid of all the "pause on rate limit" logic. Because we already stop when we receive other http error responses, we can simply use this logic instead. 
Note: feat() over ref() because it's a behaviour change, not because handling rate limits is entirely new (#6710)
closes #6984
=> feat(replay): Stop recording when hitting a rate limit

packages/replay/src/replay.ts
This was unintentionally find/replaced. Our Network tab basically had no data (although some did, and Im not sure how thats possible).
=> fix(replay): Fix feature detection of PerformanceObserver

packages/replay/src/integration.ts, packages/replay/src/types.ts, packages/replay/src/types/rrweb.ts, packages/replay/src/util/getPrivacyOptions.ts, packages/replay/test/integration/rrweb.test.ts
This was unintentionally removed in #6645 - it is still deprecated and will be removed at a later date.
=> feat(replay): Add back deprecated `maskInputOptions`

.github/workflows/build.yml
With this change, CI should be skipped when merging from master/develop to develop/master (when the `Dev: Gitflow` label is applied to the PR).
I _think_ this should all work, but it's a bit hard to test this 😬
=> ci: Skip CI when syncing develop<>master

rollup/plugins/bundlePlugins.js
Our mangler strikes again! This time in `rrweb` where `attributes._cssText` is accessed ([example](https://github.com/getsentry/rrweb/blob/69205deb8cc1f025af125c1fd6a1ecd623e83d59/packages/rrweb-snapshot/src/snapshot.ts#L502)). This PR adds this property to the list of reserved properties excluded from mangling. 
Note: I went through the rrweb source code and didn't find other private properties, leading me to believe that for now we should be good in terms of bundling. rrweb accesses a bunch of double `__` variables (e.g. `__sn` [here](https://github.com/getsentry/rrweb/blob/69205deb8cc1f025af125c1fd6a1ecd623e83d59/packages/rrweb/src/record/iframe-manager.ts#L25)) but these are not touched by terser and hence fine (+ I double checked that they actually end up in our bundles).  
h/t …
=> fix(replay): Don't mangle private `_cssText` rrweb property

.github/workflows/build.yml, .github/workflows/gitflow-sync-master.yml
It seems to not like double quotes.
See e.g. https://github.com/getsentry/sentry-javascript/actions/runs/4072470708
```
The workflow is not valid. .github/workflows/gitflow-sync-master.yml (Line: 16, Col: 9): Unexpected symbol: '"meta'. Located at position 89 within expression: github.event.pull_request.merged == true
&& startsWith(github.event.pull_request.title, "meta(changelog):")
.github/workflows/gitflow-sync-master.yml (Line: 57, Col: 9): Unexpected symbol: '"meta'. Located at position 90 within expression: github.event.pull_request.merged == false
|| startsWith(github.event.pull_request.title, "meta(changelog):") == false
```
Note: This also fixes an incorrect check which meant we weren't running CI for all prs.
=> ci: Fix invalid yaml

packages/wasm/package.json, yarn.lock
This has been bothering me because `yarn install` on an M1 fails due to puppeteer.
=> chore(wasm): Upgrade puppeteer to v18

packages/node/src/integrations/http.ts
In order to prevent unbounded memory pressure let's make the `createSpanUrlMap` in the `Http` integration an lru cache, and fix it to 100 URLs. 100 should be enough to justify the existence of this, but not enough to use a lot of memory.
fixes https://github.com/getsentry/sentry-javascript/issues/7060
=> fix(node): Add lru cache to http integration span map

packages/integration-tests/suites/replay/customEvents/init.js, packages/integration-tests/suites/replay/customEvents/subject.js, packages/integration-tests/suites/replay/customEvents/template.html, packages/integration-tests/suites/replay/customEvents/test.ts, packages/integration-tests/utils/helpers.ts, packages/integration-tests/utils/replayEventTemplates.ts, packages/integration-tests/utils/replayHelpers.ts
This PR adds a few Playwright integration test helper functions for Replay integration tests. Furthermore, it adds a test for some custom events we add to the rrweb recording (breadcrumbs and performance spans). More tests will follow
ref #7044
=> test(replay): Add Integration tests + setup for custom events

packages/integration-tests/suites/tracing/browsertracing/backgroundtab-pageload/subject.js, packages/integration-tests/suites/tracing/browsertracing/backgroundtab-pageload/test.ts, packages/integration-tests/suites/tracing/metrics/web-vitals-cls/test.ts
Dunno if the changes to the backgroundtab changes actually do something but Id say it is worth a try.
=> test(integration-tests): Unflake some tests

packages/replay/src/coreHandlers/handleGlobalEvent.ts, packages/replay/src/util/isRrwebError.ts, packages/replay/test/integration/coreHandlers/handleGlobalEvent.test.ts
Based on https://github.com/getsentry/rrweb/pull/41, we can now ignore rrweb errors even when the code is minified.
=> feat(replay): Improve rrweb error ignoring

.size-limit.js, packages/browser/rollup.bundle.config.js, packages/tracing/rollup.bundle.config.js
Resolves https://github.com/getsentry/sentry-javascript/issues/7066
Generate CDN bundle (es6 only) for Replay + errors. This gives us all the possible permutations between errors, replays and performance to dynamically load CDN bundle as appropriate for the new loader work.
=> build: Generate errors + replay only CDN bundle

.yarnrc, CONTRIBUTING.md, lerna.json, nx.json, package.json, packages/angular/package.json, packages/browser/package.json, packages/core/package.json, packages/e2e-tests/package.json, packages/eslint-plugin-sdk/package.json, packages/gatsby/package.json, packages/hub/package.json, packages/integration-tests/package.json, packages/integrations/package.json, packages/nextjs/package.json, packages/node-integration-tests/package.json, packages/node/package.json, packages/opentelemetry-node/package.json, packages/react/package.json, packages/remix/package.json, packages/replay/package.json, packages/serverless/package.json, packages/svelte/package.json, packages/tracing/package.json, packages/types/package.json, packages/utils/package.json, packages/vue/package.json, packages/wasm/package.json, yarn.lock
Explainer video below:
https://user-images.githubusercontent.com/900523/217283822-8c952772-ea79-477e-9ac8-70e6461c5611.mp4
=> chore: lerna optimizations

.github/ISSUE_TEMPLATE/bug.yml
Right now, users can't specify that they're using the CDN bundles or the loader when opening a bug report (e.g. #7080) I suggest we add two entries for CDN and loader so that they can set their used SDK correctly.
=> chore(repo): Add CDN bundle and loader entries to bug report template

.github/workflows/build.yml
The previous PR that introduces the Replay SDK metrics job already contained code that collected baseline info from the main branch.   
However, after making a change to only run when a specific label is added, this feature got lost... 
This PR should fix that.
=> chore: metrics collection job should also run on develop

packages/replay/README.md
Following up on a slack discussion with @bruno-garcia, we're going to remove the CDN installation section from the Replay package `README.md`. This section has always been problematic because we can't keep it in sync with the latest SDK version and its integrity checksum. Instead, we now just link to Sentry Docs for the CDN setup, which contains the latest version and checksum.
I put the deprecation notice of the two separate CDN bundles under a spoiler as this is the only place where we still mention this installation method.
=> chore(replay): Link to Docs for CDN bundle installation

.github/workflows/build.yml, .github/workflows/clear-cache.yml, .github/workflows/gitflow-sync-master.yml, package.json, packages/ember/package.json
yaml is a terrible language, I hope this is now actually correct!
=> ci: fix yaml (again)

.github/workflows/build.yml, packages/replay/package.json, yarn.lock
This updates rrweb to https://github.com/getsentry/rrweb/releases/tag/1.101.0, which mainly improves our wrapping of rrweb errors.
=> feat(replay): Improve ignoring of rrweb-internal errors

packages/replay/src/replay.ts, packages/replay/src/util/addEvent.ts, packages/types/src/clientreport.ts
This leverages the new client_report categories.
See https://github.com/getsentry/develop/pull/830
Closes https://github.com/getsentry/sentry-javascript/issues/6774
=> feat(replay): Send client_report when replay sending fails

.github/workflows/build.yml
Something in 18.14.0 causes npm's module resolution to local file paths to fail. Let's pin to 18.13.0 for the time being.
=> chore(nextjs): Pin node 18.13.0 in nextjs integration tests

CHANGELOG.md, packages/tracing/src/index.bundle.replay.ts, packages/tracing/test/index.bundle.replay.test.ts
To be consistent with export namespaces, we want the `Replay` integration to be accesible under `Sentry.Replay` in the full CDN bundles. This is backwards compatible as we still permit `Sentry.Integrations.Replay` as well. We can remove it in v8.
With this change, both CDN bundles containing replay (sdk+tracing+replay and sdk+replay) export from `Sentry.Replay`. Only the addon bundle, which we already deprecated and don't mention in the docs anymore will only be available i n`Sentry.Integrations.Replay`.
=> fix(replay): Export Replay from Sentry namespace in full CDN bundle

.github/workflows/auto-release.yml
Based on e.g. https://github.com/getsentry/sentry-javascript/actions/runs/4135873735/jobs/7148935627 you can see that `head_ref` is actually just the branch name without `refs/heads`
=> ci: Fix auto-release regex

packages/nextjs/src/config/webpack.ts, packages/nextjs/test/config/loaders.test.ts
fixes https://github.com/getsentry/sentry-javascript/issues/7122
=> fix(nextjs): Make api route identifier stricter

packages/node/src/integrations/http.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/7130
=> fix(node): Don't rely on `this` in http integration

packages/browser/src/stack-parsers.ts, packages/browser/test/unit/tracekit/chromium.test.ts
Closes #7128
That regex is becoming a monster!
=> fix(browser): Support `async` in stack frame urls

packages/replay/src/util/shouldFilterRequest.ts, packages/replay/test/integration/shouldFilterRequest.test.ts
Logic was flipped for the filter function so fetch and xhr requests were not being recorded at all.
Closes https://github.com/getsentry/team-replay/issues/9
Closes https://github.com/getsentry/sentry-javascript/issues/7078
=> fix(replay): Fix missing fetch/xhr requests

packages/tracing/src/index.bundle.ts
=> fix(tracing): Export `defaultStackParser` from tracing CDN bundles

CHANGELOG.md, packages/integration-tests/suites/replay/privacy/init.js, packages/integration-tests/suites/replay/privacy/template.html, packages/integration-tests/suites/replay/privacy/test.ts, packages/integration-tests/utils/helpers.ts
=> meta: Update changelog for 7.37.1

MIGRATION.md
As per feedback in https://github.com/getsentry/sentry-javascript/discussions/7112, just forward along all of the options as it reduces user need to understand what they do.
=> chore: Update custom transport migration docs

.github/workflows/build.yml, packages/integration-tests/suites/integrations/httpclient/init.js, packages/integration-tests/suites/replay/captureReplay/test.ts, packages/integration-tests/suites/replay/compression/init.js, packages/integration-tests/suites/replay/compression/test.ts, packages/integration-tests/suites/replay/customEvents/init.js, packages/integration-tests/suites/replay/customEvents/test.ts, packages/integration-tests/suites/replay/errorResponse/test.ts, packages/integration-tests/suites/replay/init.js, packages/integration-tests/suites/replay/sampling/init.js, packages/integration-tests/suites/replay/sampling/test.ts, packages/integration-tests/utils/generatePlugin.ts, packages/integration-tests/utils/replayHelpers.ts
This PR updates our Playwright test setup to test against four new SDK CDN bundles:
* SDK+Tracing+Replay
* SDK+Tracing+Replay minified
* SDK+Replay
* SDK+Replay minified
To make this work and simplify our test case inits, I decided to drop testing against the replay **addon** CDN bundle which we recently decided to deprecate in favour of the full bundles. This has the nice side effect that our PW setup is slightly simplified. 
Overall, this change adds four more PW test jobs to CI but I've checked runtime and the impact seems negligible.    
ref #7044 
Also, cc @billyvg - once this is merged, I think #7055 should work better. You might need to update your init.js file.
=> test(replay): Test against full and errors+replay CDN bundles

packages/integration-tests/package.json, packages/integration-tests/suites/replay/privacy/test.ts
Forgot to rebase #7096 before merging, which causes PW tests to fail after #7055 was merged. This skips the test on non-replay bundles, just like the other replay tests.
=> fix(integration-tests): Skip non-replay bundles in replay test

packages/replay/package.json, yarn.lock
rrweb Changelog: https://github.com/getsentry/rrweb/releases/tag/1.103.0
=> feat(replay): Bump `rrweb` to 1.103.0

packages/replay/test/fixtures/transaction.ts, packages/tracing/src/browser/metrics/index.ts, packages/tracing/test/browser/metrics/index.test.ts
As per https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming/renderBlockingStatus the resource timing has information about whether an asset is blocking render or not, which is useful for determining which assets need to be addressed for fixing critical path.
=> feat(tracing): Track `PerformanceResourceTiming.renderBlockingStatus`

.github/workflows/auto-release.yml, .github/workflows/build.yml, .gitignore, .prettierignore, nx.json, package.json
This PR does some small adjustments to our cache setup:
1. Use `actions/cache/restore` in most places, as actually after the initial runs we only want to _read_ from the cache, never update it.
2. Update the nx cache location to outside of `node_modules`. I guess it can lead to cache conflicts otherwise, as we cache node_modules for the dependencies, and node_modules/.cache/nx for Nx. Now, the Nx cache is in `.nxcache` in the root dir.
=> build: Improve CI cache

packages/browser/src/integrations/dedupe.ts, packages/browser/test/integration/suites/api.js, packages/integrations/src/dedupe.ts, packages/integrations/test/dedupe.test.ts
Currently, the dedupe integration will never _drop_ non-error events, but it will still consider them as `_previousEvent`. Thus, if we have e.g. a sequence of events like this:
* error 1
* transaction
* error 1
It _will_ capture `error 1` twice.
This PR fixes this so we only consider error events for deduping.
This _may_ be related to https://github.com/getsentry/sentry-javascript/issues/7147, although TBH I am not sure if this would really account for that many consecutive errors... 🤔
=> fix(integration): Ensure dedupe integration ignores non-errors

packages/replay-worker/package.json, packages/replay-worker/rollup.worker.config.js, packages/replay-worker/src/_worker.ts, packages/replay-worker/src/index.ts, packages/replay-worker/src/worker.ts, packages/replay-worker/tsconfig.types.json, packages/replay-worker/vendor/index.d.ts, packages/replay-worker/vendor/worker.d.ts, yarn.lock
This changes the build for the replay worker:
* Ensure that `build:transpile` and `build:types` are actually separate things, to avoid conflicts
* Ensure we do not rely on copying `vendor` stuff as-is, but relying on rollup
Basically, we now keep the worker in `_worker.ts`, while `worker.ts` is just a placeholder that is replaced at built time with the string-wrapped & resolved version of `_worker.ts`. This way, the imports etc. work as expected, and we can actually generate the types normally.
I also aligned the build structure with other packages, the output is now:
While `index.js` is:
```js
import r from"./worker";function e(){const e=new Blob([r]);return URL.createObjectURL(e)}export{e as getWorkerURL};
```
and `worker.js` is:
```
export default `/*! pako 2.1.0 …
```
=> build(replay): Improve replay-worker build

packages/replay/src/replay.ts, packages/replay/src/types.ts, packages/replay/src/util/addEvent.ts
This PR should help with debugging stopped replays.
* Add an (optional) reason for stopping replays, to know what triggered the stop
* Ensure that we log to the console when `_experiments.traceInternals === true`, so we get these logs for sentry.io.
Closes https://github.com/getsentry/sentry-javascript/issues/7149
Note that it doesn't actually _fix_ this issue, but will give us more info in the future to debug these things. As of now, it is pretty hard to reason about why this happend.
=> ref(replay): Improve logging for stopped replay

packages/opentelemetry-node/src/spanprocessor.ts, packages/opentelemetry-node/test/spanprocessor.test.ts
ref https://github.com/getsentry/team-webplatform-meta/issues/32
Render a string instead of an integer so it's easier for users to understand.
=> fix(otel): Make otel.kind be a string

packages/react/src/errorboundary.tsx
fixes https://github.com/getsentry/sentry-javascript/issues/4190
We set `error`, `componentStack`, and `eventId` at the same time https://github.com/getsentry/sentry-javascript/blob/2bdda8454ed89355fd9b727c09bb976a2eb88a90/packages/react/src/errorboundary.tsx#L106
This means that there is no way for `componentStack` and `eventId` to be `null` if `error` is defined. Making the TS types more accurate to reflect this.
=> fix(react): Make fallback render types more accurate

packages/core/src/integration.ts, packages/core/test/lib/base.test.ts
In the case when a user adds an empty integration, we want to handle this more gracefully instead of erroring out.
Closes https://github.com/getsentry/sentry-javascript/issues/7200
=> fix(core): Skip empty integrations

.github/workflows/build.yml, .github/workflows/release-size-info.yml
This adds a Github action workflow that runs when a release is published, and updates the release body with the size limit table.
This uses the new action https://github.com/getsentry/size-limit-release, which uses our size-limit-action fork under the hood and re-uses the same markdown table building functionality.
=> build: Add size limit info to releases

packages/replay/src/constants.ts
This is happening due to a bug in the `debounce` function where it does not respect `maxWait` if its value is the same as `wait` (https://github.com/getsentry/sentry-javascript/blob/develop/packages/replay/src/util/debounce.ts#L60) . This is causing poor fidelity in Replays and possibly memory issues if it never flushes after the initial checkout.
This is just a quick fix until we fix `debounce`.
=> fix(replay): Debounced flushes not respecting `maxWait`

packages/integration-tests/utils/replayEventTemplates.ts, packages/replay/src/util/createPerformanceEntries.ts
Fixes up calculating LCP timing based on `web-vitals`. Previously we were using the `duration` field on the PerformanceEntry, but it was always 0.
Decided to change the `data.duration` field to `data.value` so that we do not break the frontend when trying to display this new field.
=> feat(replay): Change LCP calculation

packages/replay/src/util/debounce.ts, packages/replay/test/unit/util/debounce.test.ts
Update and fix tests for debounce when `maxWait` == `wait`.
=> fix(replay): Fix debounce when `maxWait` == `wait`
