.github/workflows/build.yml
Based on https://github.com/getsentry/size-limit-action/pull/8, this ensures we can actually run size-limit on release branches, which currently fails.
=> ci: Ensure we can actually run size-limit for release branches

packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-1-snap-incremental, packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-1-snap-incremental-chromium, packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-3-snap-incremental, packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-3-snap-incremental-chromium, packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-5-snap-incremental, packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-5-snap-incremental-chromium, packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-6-snap-incremental, packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-6-snap-incremental-chromium, packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-7-snap-incremental, packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-7-snap-incremental-chromium, packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-9-snap-incremental, packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-9-snap-incremental-chromium, packages/integration-tests/utils/replayHelpers.ts
I just noticed that the last integration test I added in #7212 is flaky because of time offsets which can change in some CI runs. This PR normalizes the time offset to `[timeOffset]` in DOM snapshots to make sure this doesn't happen.
=> test(replay): Normalize time offset in DOM snapshots

packages/integration-tests/suites/replay/requests/init.js, packages/integration-tests/suites/replay/requests/subject.js, packages/integration-tests/suites/replay/requests/template.html, packages/integration-tests/suites/replay/requests/test.ts, packages/integration-tests/utils/replayEventTemplates.ts
This PR adds two Playwright tests to test fetch/xhr requests being recorded as performance spans
ref #7044
=> test(replay): Add test for fetch and XHR performance spans

.github/workflows/release-size-info.yml
Must actually use the group1 instead of match here, also `github.head_ref` is sadly not available, but apparently `env.GITHUB_REF` is (see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release).
=> ci: Fix adding size info to release

packages/nextjs/src/client/index.ts, packages/nextjs/src/common/getVercelEnv.ts, packages/nextjs/src/edge/index.ts, packages/nextjs/src/server/index.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/6993
This PR is just a quick win that should improve the ootb experience for Vercel on Next.js by setting the environment option to a sensible default provided by the hosting provider.
The `vercel-` prefix is so you can discern the vercel `development` environment from local development because there the `NODE_ENV` var with `development` is likely gonna be picked up.
=> feat(nextjs): Default to `VERCEL_ENV` as environment

packages/core/src/transports/offline.ts, packages/core/test/lib/transports/offline.test.ts, packages/utils/src/envelope.ts
If a user sets any `transportOptions`, the transport is used directly to send client reports rather than beacon which means they can get queued by the offline transport wrapper.
Client reports can be generated every time an event fails to send and these could fill the queue when offline and mean error events get dropped.
This PR modifies `forEachEnvelopeItem` to allow short-cut out of the for loop if the callback returns `true`.
=> fix(core): Exclude client reports from offline queuing

.github/workflows/build.yml
This adds a nightly CI run that runs without cache, to ensure we catch potential caching problems.
=> ci: Run nightly build without cache

packages/integration-tests/suites/replay/customEvents/test.ts, packages/integration-tests/utils/replayHelpers.ts
Based on #7225, draft until merged, otherwise ready
Just adds a check for timestamp equality of LCP perf span start and end times
=> test(replay): Ensure LCP spans have equals start and end timestamps (Playwright)

packages/integration-tests/package.json, packages/integration-tests/suites/replay/flushing/init.js, packages/integration-tests/suites/replay/flushing/subject.js, packages/integration-tests/suites/replay/flushing/template.html, packages/integration-tests/suites/replay/flushing/test.ts, packages/integration-tests/suites/replay/privacyBlock/test.ts-snapshots/privacy.json, packages/integration-tests/suites/replay/privacyDefault/test.ts-snapshots/privacy.json
Adds an integration test that replays are continuously send every {flushDelay} seconds, even if page activity is ongoing.
Note: I also needed to update the non-browser-specific snapshots, and added this to the script as well.
=> test(replay): Add test for continuous flushing

.github/workflows/build.yml
Just noticed that the playwright tests go on forever, so adding a 10min timeout there should help.
Also reducing this from 30m to 10m for some other jobs, which should be sufficient IMHO.
=> ci: Add timeout to integration tests job

packages/integration-tests/suites/replay/unicode/compressed/init.js, packages/integration-tests/suites/replay/unicode/compressed/test.ts, packages/integration-tests/suites/replay/unicode/compressed/test.ts-snapshots/unicode-compressed-chromium.json, packages/integration-tests/suites/replay/unicode/compressed/test.ts-snapshots/unicode-compressed-firefox.json, packages/integration-tests/suites/replay/unicode/compressed/test.ts-snapshots/unicode-compressed-webkit.json, packages/integration-tests/suites/replay/unicode/compressed/test.ts-snapshots/unicode-compressed.json, packages/integration-tests/suites/replay/unicode/subject.js, packages/integration-tests/suites/replay/unicode/template.html, packages/integration-tests/suites/replay/unicode/uncompressed/init.js, packages/integration-tests/suites/replay/unicode/uncompressed/test.ts, packages/integration-tests/suites/replay/unicode/uncompressed/test.ts-snapshots/unicode-uncompressed-chromium.json, packages/integration-tests/suites/replay/unicode/uncompressed/test.ts-snapshots/unicode-uncompressed-firefox.json, packages/integration-tests/suites/replay/unicode/uncompressed/test.ts-snapshots/unicode-uncompressed-webkit.json, packages/integration-tests/suites/replay/unicode/uncompressed/test.ts-snapshots/unicode-uncompressed.json
While working on #7082 we figured it'd be worthwhile to check that we handle unicode characters correctly. Especially when compressing payload we should check that nothing goes wrong.
Note: This test obviously only checks that the payloads _leave_ the SDK correctly. It cannot say anything about the replayer rendering them correctly in the Sentry UI. 
ref #7044
=> test(replay): Ensure that unicode characters are handled correctly

packages/integration-tests/suites/replay/errors/droppedError/init.js, packages/integration-tests/suites/replay/errors/droppedError/test.ts, packages/integration-tests/suites/replay/errors/errorMode/test.ts, packages/integration-tests/suites/replay/errors/errorsInSession/init.js, packages/integration-tests/suites/replay/errors/errorsInSession/test.ts, packages/integration-tests/suites/replay/errors/init.js, packages/integration-tests/suites/replay/errors/subject.js, packages/integration-tests/suites/replay/errors/template.html, packages/integration-tests/utils/replayEventTemplates.ts
This PR adds four integration tests for replays where errors occur:
* error mode:
* error to session transition once the error occurs
* if the error is dropped, it shouldn't be linked in the replay event (see test comment about the problem with this scenario)
* session mode
* if an error occurs, make sure it's linked in the replay event
* unless the error is dropped
ref: #7044
=> test(replay): Add Playwright tests for error-mode and error linking

.craft.yml, package.json, packages/angular-ivy/.eslintrc.js, packages/angular-ivy/LICENSE, packages/angular-ivy/README.md, packages/angular-ivy/angular.json, packages/angular-ivy/ng-package.json, packages/angular-ivy/package.json, packages/angular-ivy/scripts/syncSourceFiles.ts, packages/angular-ivy/src/constants.ts, packages/angular-ivy/src/errorhandler.ts, packages/angular-ivy/src/flags.ts, packages/angular-ivy/src/index.ts, packages/angular-ivy/src/sdk.ts, packages/angular-ivy/src/tracing.ts, packages/angular-ivy/src/zone.ts, packages/angular-ivy/tsconfig.json, packages/angular-ivy/tsconfig.ngc.json, packages/angular/src/constants.ts, packages/angular/src/tracing.ts, packages/angular/test/ivy-synced.test.ts, packages/e2e-tests/verdaccio-config/config.yaml, yarn.lock
This PR adds a new SDK package to our monorepo: `@sentry/angular-ivy`. 
While this is technically a new SDK, its content and functionality is identical to `@sentry/angular`. Only the build configuration differs:
* The Ivy SDK is built with Angular 12, allowing for a compatibility of NG12-15
* The Ivy SDK is built with `compilationMode: partial`, enabeling a build format that is compatible with Angular's Ivy rendering engine. 
* This means that `ngcc` no longer needs to step in at initial build time to up-compile the SDK. Which is good because `ngcc` will be removed in Angular 16 (https://github.com/angular/angular-cli/pull/24720)
* The Ivy SDK's build output follows the Angular Package Format (APF) v12 standard ([spec](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-Ntk …
=> feat(angular): Add Ivy-compatible Angular SDK package

packages/ember/addon/instance-initializers/sentry-performance.ts
We do not want to run the instance initializer in fastboot env, as that relies on Browser stuff.
Note that it would prob. make sense to skip all of sentry in fastboot (SSR), but that probably has to happen in user code. 
This fix at least should lead to the app not failing to be served when fastboot & sentry are installed.
ref https://github.com/getsentry/sentry-javascript/issues/7258
=> fix(ember): Disable performance in FastBoot

packages/integration-tests/suites/replay/flushing/init.js, packages/integration-tests/suites/replay/flushing/template.html, packages/integration-tests/suites/replay/flushing/test.ts
This PR fixes the flakiness of our replay event flushing test by slightly changing the test requirements/expectations:
* Disabled compression to avoid potential timing problems
* Instead of asserting that a flush happens within a certain time frame from the last flush, we ease up this expectation so that we only expect _that_ another flush happens after the previous one, given that click events happened in between. 
* Instead of forcing a flush by triggering a visibility change (like we do a lot in other tests to avoid flakes), this test focuses on the max delay of flushing, thereby ensuring that our flushes are not debounced to eternity.
Note: I tested that flakes were gone by running this test 75x per CI job for multiple times and didn't see this test failing anymore. 
closes #7266
=> test(replay): Fix flaky flush test

packages/serverless/src/gcpfunction/http.ts
As reported in #7222, our GCP function `wrapHttpFunction` handler didn't capture custom tags in error events. We suspect that this was caused by the SDK listening to errors on the wrong domain. This PR changes the way we listen to errors by directly try/catching the function instead of listening to the domain's error callback.  
h/t @lforst for debugging this
fixes #7222
=> fix(serverless): Capture custom tags in error events of GCP functions

packages/serverless/src/gcpfunction/cloud_events.ts, packages/serverless/src/gcpfunction/events.ts
Following up on #7222 and #7298 this PR fixes adding custom tags for GCP Background and CloudEvent function error events. As for Http functions, we also previously captured errors just via `domain.on('error',...)` which used the wrong domain, leading to tags (+other data) not being captured correctly. With this fix, we now also directly capture exceptions during function invocation.
ref #7222
=> fix(serverless): Capture custom tags in GCP Background and CloudEvent function error events

.craft.yml
This adds automatic release registry updates for the new Ivy compatible Angular SDK
still sort of ref #7265
=> chore(angular-ivy): Add release registry config for `@sentry/angular-ivy`

packages/browser/test/unit/transports/offline.test.ts
Unfortunately, these tests are continuously flaky so we're disabling them temporarily until the flakes are resolved.
cc @timfish when you get back :) 
ref #7079
=> test(browser): Temporarily skip offline transport tests

.github/actions/restore-cache/action.yml, .github/workflows/build.yml
This improves our cache restoration to actually fail if we can't restore the dependency/build cache. Without that, tests somewhat "randomly" fail, and it can be hard to figure out why.
We should now error with a more actionable message (=rerun all jobs). I extracted this into a reusable local action so we don't need to splatter this throughout the whole workflow file.
=> ci: Better error handling when caches can't be restored

.github/workflows/build.yml
Not 100% sure if this will work, but it would be nice to avoid having the error logs in all CI runs:
Let's also see if stuff works with Node 18.14.2 again...!
=> ci: Avoid `continue-on-error` for nextjs tests

packages/browser/test/unit/transports/offline.test.ts, packages/core/test/lib/transports/offline.test.ts
This PR
1. reverts #7305 as it seems these tests were in fact not flaky 🙈 
2. skips the actually flaky offline test from core, mentioned in #7079 until we properly fix the flake
=> test(core): Skip flaky offline transport test

packages/integration-tests/suites/replay/captureReplay/test.ts, packages/integration-tests/suites/replay/captureReplayViaBrowser/test.ts, packages/integration-tests/suites/replay/errors/errorsInSession/test.ts, packages/integration-tests/utils/replayHelpers.ts
Hopefully fix https://github.com/getsentry/sentry-javascript/issues/7269
=> test: Fix flaky errorsInSession replay test

packages/overhead-metrics/configs/ci/process.ts, packages/overhead-metrics/package.json, packages/overhead-metrics/src/util/git.ts, packages/overhead-metrics/src/util/github.ts
Currently, it doesn't handle the fact that it runs the measurements on develop very well, and picks random PRs to add comments to 😬
=> ci: Fix overhead measurements runs on default branch

packages/vue/src/sdk.ts
As brought up by @cleptric, right now our Vue SDK doesn't log errors occurring in the Vue renderer to the console by default. Users need to manually set [`logErrors: true`](https://docs.sentry.io/platforms/javascript/guides/vue/#vue-3---manual-initialization) to enable logging of errors. 
After an internal discussion, we decided to log errors by default. Users can continue to use `logErrors` to opt out of that. 
ref: https://github.com/getsentry/sentry-javascript/issues/1416
Docs PR: https://github.com/getsentry/sentry-docs/pull/6392
=> feat(vue): Log errors to the console by default

packages/integration-tests/suites/replay/errors/errorMode/test.ts, packages/integration-tests/suites/replay/errors/errorsInSession/test.ts, packages/integration-tests/suites/replay/errors/init.js, packages/integration-tests/utils/helpers.ts, packages/integration-tests/utils/replayHelpers.ts
Hopefully fixes https://github.com/getsentry/sentry-javascript/issues/7272
=> test: Fix flaky replay error mode test

packages/replay/src/constants.ts, packages/replay/src/replay.ts, packages/replay/test/integration/errorSampleRate.test.ts, packages/replay/test/integration/events.test.ts, packages/replay/test/integration/flush.test.ts, packages/replay/test/integration/rateLimiting.test.ts, packages/replay/test/integration/sendReplayEvent.test.ts, packages/replay/test/integration/session.test.ts, packages/replay/test/integration/stop.test.ts, packages/replay/test/utils/setupReplayContainer.ts
Extracted this out of https://github.com/getsentry/sentry-javascript/pull/7253
This allows us to simplify this code a bit (currently we have code paths that handle these being separate etc).
=> ref(replay): Use `SESSION_IDLE_DURATION` instead of `VISIBILITY_CHANGE_TIMEOUT`

packages/integration-tests/suites/replay/errors/errorMode/test.ts, packages/integration-tests/suites/replay/errors/errorsInSession/test.ts, packages/integration-tests/suites/replay/errors/init.js, packages/integration-tests/utils/helpers.ts, packages/integration-tests/utils/replayHelpers.ts, packages/replay/src/constants.ts, packages/replay/src/replay.ts, packages/replay/test/integration/errorSampleRate.test.ts, packages/replay/test/integration/events.test.ts, packages/replay/test/integration/flush.test.ts, packages/replay/test/integration/rateLimiting.test.ts, packages/replay/test/integration/sendReplayEvent.test.ts, packages/replay/test/integration/session.test.ts, packages/replay/test/integration/stop.test.ts, packages/replay/test/utils/setupReplayContainer.ts
Merge develop into master to fix conflicts here: https://github.com/getsentry/sentry-javascript/pull/7317
I made a branch off `master`, merged `develop` into it and resolved conflicts, now merging this into `master` again to hopefully be able to merge conflict-free into develop from there afterwards!
learning: Avoid merging stuff that touches package.json while a release is ongoing 😬
=> [Gitflow] Merge develop into master

packages/browser/src/profiling/hubextensions.ts, packages/browser/src/profiling/jsSelfProfiling.ts, packages/browser/test/unit/profiling/hubextensions.test.ts
If document-policy header is not set, the profiling API is still present but attempting to initialize the profiler will throw.
This PR guards from that by adding a try/catch block around the profiler constructor.
=> fix(profiling): Guard from throwing if profiler constructor throws

packages/react/src/reactrouterv6.tsx
This is needed for the import to work in a TypeScript project that does not have `allowSyntheticDefaultImports` enabled.
---
=> fix(react): Use namespace import for react router v6

packages/remix/src/utils/getIpAddress.ts, packages/remix/test/utils/getIpAddress.test.ts
Seems like we had a bug in the Remix Server SDK when parsing the `X-Forwarded-For` Http header to obtain the user IP address. This PR attempts to fix this and adds a few unit tests tests.
Fixes #7323 (hopefully)
=> fix(remix): Correctly parse `X-Forwarded-For` Http header

packages/browser/src/profiling/utils.ts, packages/core/src/constants.ts, packages/core/src/hub.ts, packages/core/src/index.ts, packages/core/src/utils/prepareEvent.ts, packages/tracing/src/transaction.ts
This PR adjusts our code to use the same default environment everywhere in the codebase for consistency.
Currently, we use `production` some places and `''` in others.
I _may_ have missed something, but tried to find all places using this.
Closes https://github.com/getsentry/sentry-javascript/issues/6239
=> feat: Ensure we use the same default `environment` everywhere

README.md, packages/angular-ivy/README.md, packages/angular/README.md
This PR just makes a few changes to 3 readmes:
* angular-ivy: 
* remove experimental note
* add badges
* angular:
* add badges
* main readme:
* add entry for` @sentry/angular-ivy  `
still sort of ref #7265
=> chore(angular-ivy): Update Angular `README`s

packages/integration-tests/playwright.config.ts, packages/integration-tests/suites/replay/privacyDefault/test.ts-snapshots/privacy.json, packages/nextjs/playwright.config.ts, packages/remix/playwright.config.ts
This:
* updates the `workers` config for playwright, making sure we use the default on local machines (which depends on available CPU cores), and bump it to 5 on CI to speed this up slightly
* enabled [fullyParallel](https://playwright.dev/docs/api/class-testconfig#test-config-fully-parallel) config to ensure tests inside of a file are also parallelised - IMHO failures due to this show bad test design anyhow, so this should be fine.
=> test: Run playwright tests in parallel

packages/integration-tests/playwright.config.ts, packages/integration-tests/suites/replay/errors/droppedError/test.ts, packages/nextjs/playwright.config.ts, packages/remix/playwright.config.ts
Hopefully fix a flaky test.
I also reverted the workers on CI from 5 parallel workers to 3, as I _think_ I saw a bit more flakes here, _maybe_ due to this. 🤷
=> test: Fix flaky droppedError test

packages/e2e-tests/publish-packages.ts
the opentelemetry node package is no longer private, let's remove this note then.
=> test(e2e): Publish otel-node package tarballs

packages/core/src/integration.ts
This is not downcompiled for ES5 (=it is still present this way in the bundle.es5.js files - see e.g. https://browser.sentry-cdn.com/7.41.0/bundle.es5.js and search for `Object.values()`). So instead we use `Object.keys()` ([which works in IE11](https://caniuse.com/?search=object.keys)) here.
Fixes https://github.com/getsentry/sentry-javascript/issues/7354
=> fix(core): Avoid using `Object.values()`

CHANGELOG.md, packages/replay/package.json, packages/replay/src/replay.ts, packages/replay/src/types.ts, packages/replay/test/integration/rrweb.test.ts, yarn.lock
This updates rrweb to [1.105.0](https://github.com/getsentry/rrweb/releases/tag/1.105.0), which fixes a bug and introduces `onMutation` option.
We use this `onMutation` to create a breadcrumb when we encounter a large mutation. We can later use this to analyse how often this happens.
=> feat(replay): Update rrweb to 1.105.0 & add breadcrumb when encountering large mutation

packages/core/src/baseclient.ts, packages/core/src/hub.ts, packages/node/src/integrations/onunhandledrejection.ts, packages/types/src/event.ts
This used to be typed as `Error | string | null` which is not correct, as technically _anything_ can be thrown. To reflect this existing reality, we have to broaden this type. Note that this _could_ lead to problems for users that currently depend on this type, but any potential issues arising because of this would actually be valid problems that should actually be fixed in the user code (e.g. relying on `error.message` to be present, for example).
This also allows us to update some other types from `any` to `unknown`, which is IMHO more correct as we really just pass this through, whatever it is.
Closes https://github.com/getsentry/sentry-javascript/issues/7344
=> feat(core): Ensure `originalException` has type `unknown`

packages/integration-tests/suites/replay/multiple-pages/test.ts, packages/replay/src/replay.ts, packages/replay/src/types.ts, packages/replay/src/util/addEvent.ts, packages/replay/src/util/handleRecordingEmit.ts, packages/replay/test/integration/autoSaveSession.test.ts, packages/replay/test/unit/util/handleRecordingEmit.test.ts, packages/replay/test/utils/setupReplayContainer.ts
We used to look at `event.type === 2` for replay events to infer if something is a checkout or not.
This is a bit hacky, as type === 2 actually just means it is a full snapshot, which may or may not be due to a checkout.
This makes it hard/impossible to do any future changes where we may want to do a full snapshot in other scenarios than in error mode, e.g. if we want to do a full snapshot to avoid large mutations.
This PR refactors this a bit to really just look at `isCheckout`, _plus_ also handle the very first rrweb event as a checkout (because we rely on this a bit).
This replaces https://github.com/getsentry/sentry-javascript/pull/7237
=> ref(replay): Handle checkouts more explicitly

packages/node/src/integrations/contextlines.ts
I noticed a while back from a customer generated nodejs profile, that the sentry context lines integration was causing a significant slowdown when collecting an error event (iirc in the ballpark of ~200ms). In a long lived process, the cost of this is amortized as we start to hit the file cache more often, however in serverless environments like lambda functions where the cache is short lived, we may still be costing our users some precious execution time.
When I reported this to the SDK team internally and @AbhiPrasad noticed that we actually sequentially read from disk so I wanted to improve this. The changes I made in this PR parallelize i/o read calls and await adding context frames until the source files necessary to do the enrichment have been read.
I ran a quick micro benchmark …
=> ref(node): parallelize disk io when reading source files for context lines

packages/node/src/declarations.d.ts, packages/node/src/integrations/http.ts, packages/node/src/integrations/localvariables.ts, packages/node/src/transports/http.ts, packages/node/test/transports/http.test.ts, packages/node/test/transports/https.test.ts
This PR removes a few dynamic `require` calls from our Node SDK in favour of making them top-level imports.
* `Http` integration: `http` and `https` are now top-level imports.
* Transport: `https-proxy-agent` is now a top-level import as v5 no longer produces side effects when importing.
We need this change for the SvelteKit SDK, as SvelteKit doesn't accept `require` calls in server code by default. 
ref #7348 #6692
=> ref(node): Partially remove dynamic `require` calls

packages/react/src/redux.ts, packages/utils/src/normalize.ts, packages/utils/test/normalize.test.ts
Attempts to fix https://github.com/getsentry/sentry-javascript/issues/7376
Makes the `normalize` function overridable via a non-enumerable property on the normalization target.
=> fix: Make redux integration be configurable via `normalizeDepth`

packages/replay/src/util/sendReplay.ts, packages/replay/src/util/sendReplayRequest.ts, packages/replay/test/integration/sendReplayEvent.test.ts
Attach the original exception as a `cause` when we throw "Unable to send replay" exceptions so that we know what is causing issues with sending replays.
=> feat(replay): Attach an error `cause` to send exceptions

packages/integration-tests/suites/replay/privacyInput/init.js, packages/integration-tests/suites/replay/privacyInput/template.html, packages/integration-tests/suites/replay/privacyInput/test.ts, packages/integration-tests/suites/replay/privacyInputMaskAll/init.js, packages/integration-tests/suites/replay/privacyInputMaskAll/template.html, packages/integration-tests/suites/replay/privacyInputMaskAll/test.ts, packages/integration-tests/suites/replay/sessionExpiry/test.ts, packages/integration-tests/utils/fixtures.ts, packages/integration-tests/utils/replayHelpers.ts
This adds integration tests for input masking specifically when `maskAllInputs = false`.
Requires https://github.com/getsentry/rrweb/pull/61 and https://github.com/getsentry/rrweb/pull/60
Closes https://github.com/getsentry/sentry-javascript/issues/7257
=> test(replay): Add integration tests for input masking on change

packages/core/src/tracing/hubextensions.ts, packages/core/src/tracing/transaction.ts
Builds on top of https://github.com/getsentry/sentry-javascript/pull/7370
For now closes https://github.com/getsentry/sentry-javascript/issues/7262 (but we still need to add replay hooks).
=> feat(core): Emit hooks for transaction start/finish

packages/integration-tests/suites/tracing/browsertracing/interactions/assets/script.js, packages/integration-tests/suites/tracing/browsertracing/interactions/init.js, packages/integration-tests/suites/tracing/browsertracing/interactions/template.html, packages/integration-tests/suites/tracing/browsertracing/interactions/test.ts, packages/tracing/src/browser/browsertracing.ts, packages/tracing/src/browser/metrics/index.ts, packages/tracing/src/browser/web-vitals/types.ts
We hypothesize that there is a 1:1 mapping of `PerformanceObserver` Interactions -> Interaction Transactions. This PR will allow us to confirm whether this hypothesis is true, so we can decide our next steps for refining interaction transactions. To elaborate, we're unsure whether interaction transactions that have no child spans are worth keeping or not, and there are a lot of transactions like this in prod.
Enhances the existing interaction transactions by adding the ability to track interaction events exposed by the `PerformanceObserver` API. Note that this is still hidden under an experimental flag along with interaction transactions.
For now, we are only tracking `click` interactions, but we can expand this functionality later as needed.
=> feat(tracing): Track PerformanceObserver interactions as spans

packages/integration-tests/suites/tracing/metrics/web-vitals-lcp/test.ts, packages/tracing/src/browser/browsertracing.ts, packages/tracing/src/browser/metrics/index.ts, packages/tracing/src/browser/web-vitals/getCLS.ts, packages/tracing/src/browser/web-vitals/getLCP.ts, packages/tracing/src/browser/web-vitals/types/base.ts, packages/tracing/test/browser/browsertracing.test.ts
fixes https://github.com/getsentry/sentry-javascript/issues/7341
To get better LCP and CLS accuracy, let's fire the `stopListening` func on transaction finish.
=> fix(tracing): Record LCP and CLS on transaction finish

packages/sveltekit/package.json, packages/sveltekit/src/client/index.ts, packages/sveltekit/src/config/index.ts, packages/sveltekit/src/config/vitePlugins.ts, packages/sveltekit/src/config/withSentryViteConfig.ts, packages/sveltekit/src/index.server.ts, packages/sveltekit/src/index.types.ts, packages/sveltekit/test/config/vitePlugins.test.ts, packages/sveltekit/test/config/withSentryViteConfig.test.ts, yarn.lock
This PR adds an initial version of `Sentry.init` call injection to our new SvelteKit SDK:
Specifically, we add a `withSentryViteConfig` wrapper function, which users will need to wrap around their Vite config. This will:
* Inject a Vite plugin which takes care of injecting `Sentry.init` calls from `sentry.(client|server).config.(ts|js)` files, providing a DX identical to the NextJS SDK.
* The server-side init is injected into the server `index.js` file
* The client-side init is injected into the `app.js` file 
* The injection works both for production builds (with the Node adapter for now) as well as for a local dev server
* Add the root directory of the project to the allowed directories for the Vite dev server. We need this so that the client config is correctly picked up by the Vite …
=> feat(sveltekit): Inject `Sentry.init` calls into server and client bundles

packages/core/src/integration.ts
Not sure if there is an easy way to polyfill this only for ES5 builds? But other than this, this should be straightforward enough.
Closes https://github.com/getsentry/sentry-javascript/issues/7397
=> fix(core): Avoid using `Array.findIndex()` as it is ES5 incompatible

packages/svelte/src/sdk.ts, packages/svelte/test/sdk.test.ts, packages/sveltekit/src/client/index.ts, packages/sveltekit/src/client/sdk.ts, packages/sveltekit/src/common/metadata.ts, packages/sveltekit/src/server/index.ts, packages/sveltekit/src/server/sdk.ts, packages/sveltekit/test/client/sdk.test.ts, packages/sveltekit/test/server/sdk.test.ts
This PR adds SDK `init` functions for the SvelteKit SDK server- and client-side. Currently these functions 
* set SDK metadata
* call the respective base SDK's init
* set a `runtime` tag ('browser' / 'node' resp.)
Also fixed a bug in the Svelte SDK where passed in `options._metadata.sdk` was previously overwritten with the Svelte SDKs data.
ref #7348
=> feat(sveltekit): Add SvelteKit client and server `init` functions

packages/sveltekit/package.json, packages/sveltekit/src/client/handleError.ts, packages/sveltekit/src/client/index.ts, packages/sveltekit/test/client/handleError.test.ts, yarn.lock
ref https://github.com/getsentry/sentry-javascript/issues/7402
Adds a wrapper for the client-side [`handleError` hook](https://kit.svelte.dev/docs/hooks#shared-hooks-handleerror).
Usage is like the following:
> src/hooks.client.js
```js
import { wrapHandleError } from '@sentry/sveltekit';
/** @type {import('@sveltejs/kit').HandleClientError} */
function myCustomHandleError() {
...
}
export const handleError = wrapHandleError(myCustomHandleError);
```
=> feat(sveltekit): Introduce client-side `handleError` wrapper

packages/sveltekit/src/client/handleError.ts, packages/sveltekit/src/client/index.ts, packages/sveltekit/src/index.types.ts, packages/sveltekit/src/server/handleError.ts, packages/sveltekit/src/server/index.ts, packages/sveltekit/test/client/handleError.test.ts, packages/sveltekit/test/server/handleError.test.ts
ref https://github.com/getsentry/sentry-javascript/issues/7403
Adds a wrapper for the server-side [`handleError` hook](https://kit.svelte.dev/docs/hooks#shared-hooks-handleerror).
Usage is like the following:
> src/hooks.server.js
```js
import { handleErrorWithSentry } from '@sentry/sveltekit';
/** @type {import('@sveltejs/kit').HandleServerError} */
function myCustomHandleError() {
...
}
// myCustomHandleError is optional
export const handleError = handleErrorWithSentry(myCustomHandleError);
```
In https://github.com/getsentry/sentry-javascript/pull/7406 I introduced this functionality on the client side.
=> feat(sveltekit): Add server-side `handleError` wrapper

packages/node/src/types.ts
We need to expose a similar option to tracesSampler but for profiling purposes. I kept the signature identical to tracing (maybe I should just reuse the same type?) as profiling just wraps that same startTransaction call.
We need to wait before merging to add the relevant changes to the profiling repository, I would just like to get some feedback on the type before proceeding
=> feat(types): Add profilesSampler option to node client type

packages/nextjs/src/config/webpack.ts
Prevents Next.js builds from crashing during source maps upload when building and instead prints an error message that gives instructions on how to configure the auth token.
Because the webpack config is invoked 3 times, the message will show up 3 times. I will leave this up for a future fix.
=> fix(nextjs): Don't crash build when auth token is missing

packages/utils/src/stacktrace.ts
If we do not match a webpack error, then dont run replace as it will allocate a new string. This optimizes for non-webpack style errors. For cases where we would actually sanitize the string, calling test + replace makes it slightly slower.
[Browser benchmarks](https://jsbench.me/rolf1s91ki/1) (node benchmarks seem to confirm this)
=> ref(utils): test for webpack error before running replace

packages/nextjs/src/config/webpack.ts, packages/nextjs/test/config/webpack/sentryWebpackPlugin.test.ts
Since with https://github.com/getsentry/sentry-javascript/pull/7427 we don't throw anymore on missing auth tokens it is pretty safe for us to upload source maps for Vercel develop and preview environments now.
=> feat(nextjs): Run source map upload in Vercel develop and preview environments

packages/core/src/tracing/idletransaction.ts
There are several interaction transactions in production that have no spans at all, and we want to find out why this is the case. 
This PR reintroduces `finishReason` from https://github.com/getsentry/sentry-javascript/commit/e0f9ca0c1b59b99314502052d39d9c99c455cc99 but only sets it as a tag for interaction transactions.
This is only temporary, this tag will allow us to diagnose the reason for why interaction transactions appear to be ending early, or without any data. We can remove it from the SDK once we've finished investigating.
[Here's an example of one of these strange transactions](https://sentry.sentry.io/discover/javascript:03b1715e96de4e21995b12e70082c09f/?field=span_ops_breakdown.relative&field=transaction&field=spans.ui&field=transaction.duration&field=spans.http&field=replayId …
=> feat(tracing): Bring back `finishReason` for interaction transactions

packages/e2e-tests/test-applications/nextjs-app-dir/package.json, packages/e2e-tests/test-applications/nextjs-app-dir/yarn.lock, packages/nextjs/src/server/wrapServerComponentWithSentry.ts
Our canary tests for Next.js started failing https://github.com/getsentry/sentry-javascript/issues/7452 - in particular Next.js version `13.2.4`.
This was/is an actual bug that is fixed by that PR. Apparently, from that version onwards, Next.js attaches additional values to the promises returned from server components, and the way we wrapped server components we janked those values off the returned promise causing Next.js to crash.
=> fix(nextjs): Fix broken server component wrapping because of interrupted promise chain

packages/integration-tests/suites/tracing/browsertracing/backgroundtab-pageload/test.ts
Fixes https://github.com/getsentry/sentry-javascript/actions/runs/4406741707/jobs/7719673369
=> test(integration): Fix backgroundtab-pageload flaky test

packages/utils/src/stacktrace.ts
We dont require the actual index + we can match with a single fn call
=> ref(utils): use test instead of indexof in stacktrace

.git-blame-ignore-revs
Add #7455 to git blame ignore since it was a mass rename of files.
=> chore: Add test rename to git blame ignore

packages/core/src/tracing/idletransaction.ts, packages/tracing/test/idletransaction.test.ts
- fixes idle timeout cancel exposed in https://github.com/getsentry/sentry-javascript/pull/7236
- this cancellation only worked when no child was active
=> fix(core): Permanent idle timeout cancel finishes the transaction with the last finished child

packages/tracing-internal/src/index.ts, packages/tracing-internal/src/node/integrations/index.ts, packages/tracing/src/index.ts
This PR:
- Moves the legacy `Integrations` definition from `@sentry-internal/tracing` to `@sentry/tracing`
- Ensures all integrations are exported separately from `@sentry-internal/tracing`
=> feat(tracing): Move `Integrations` from `tracing-internal` to `@sentry/tracing`

packages/serverless/src/index.ts, packages/serverless/test/awslambda.test.ts, packages/serverless/test/awsservices.test.ts, packages/serverless/test/gcpfunction.test.ts, packages/serverless/test/google-cloud-grpc.test.ts, packages/serverless/test/google-cloud-http.test.ts
fixes https://github.com/getsentry/sentry-javascript/issues/7441
A serverless package that is esm only breaks when trying to import our serverless package. This is because in our serverless we combine both wildcard and namespace exports. This confuses our rollup bundler, which causes it to put all of the wildcard exports (from `@sentry/node`) into `default`, which means it is not exposed as a top level export.
When users try to use the esm serverless package, they are unable to access exports like `captureException` or `init`.
The solution here is to just explicitly export everything from the `@sentry/node` package. In v8 we have to re-visit this and get rid of the namespace exports, since they don't serve much use, and mean that tree-shaking does not work.
=> fix(serverless): Explicitly export node package exports

packages/browser-integration-tests/suites/tracing/browsertracing/backgroundtab-pageload/test.ts
This has been flakey... trace.status is sometimes undefined, lets skip for firefox
=> test(browser-integration): Skip "browsertracing/backgroundtab-pageload" test for firefox

packages/sveltekit/package.json
Context:
This was initially added in https://github.com/getsentry/sentry-javascript/pull/7406 to make sure that vite could resolve the server/client entries properly, but this ended up breaking esm resolution for the server-side.
Instead of the exports approach, we are going to try to multiplex the same way the next.js sdk does.
=> fix(sveltekit): Remove package.json exports

.craft.yml
Resolves https://github.com/getsentry/sentry-javascript/issues/5752
https://aws.amazon.com/about-aws/whats-new/2022/05/aws-lambda-adds-support-node-js-16/
https://aws.amazon.com/about-aws/whats-new/2022/11/aws-lambda-support-node-js-18/
=> feat(serverless): Publish lambda layer for Node 16/18

packages/tracing-internal/test/browser/browsertracing.test.ts
Since `custom` is the default and the test above already checks for this, I changed the semantics of the test to make sure we were setting `url` properly.
Did this while validating a customer issue hence why changes here.
=> test(tracing): Check if `beforeNavigate` does not change source

packages/utils/src/stacktrace.ts
Enforce the stacktrace frame limit when we parse frames
=> ref(parser): limit max stack lines we parse

packages/browser/test/integration/polyfills/raf.js, packages/integrations/test/offline.test.ts, packages/replay/src/coreHandlers/handleHistory.ts, packages/replay/src/replay.ts, packages/replay/src/session/Session.ts, packages/replay/src/util/addEvent.ts, packages/replay/src/util/addMemoryEntry.ts, packages/replay/src/util/createBreadcrumb.ts, packages/replay/test/fixtures/error.ts, packages/replay/test/fixtures/transaction.ts, packages/replay/test/mocks/mockRrweb.ts, packages/replay/test/unit/coreHandlers/handleScope.test.ts, packages/replay/test/unit/session/getSession.test.ts, packages/svelte/test/performance.test.ts
This is slightly shorter and should actually be slightly more performant.
=> ref(replay): Use `Date.now()` instead of `new Date().getTime()`

packages/sveltekit/README.md
Add setup instructions for the first alpha release. 
Going forward, let's try to keep the readme up to date as we add more features.
[Rendered Readme](https://github.com/getsentry/sentry-javascript/blob/52274b1527939fb4719e01ce31cec9e39c2abe1c/packages/sveltekit/README.md)
ref #7489
=> chore(sveltekit): Update `README` with setup instructions 

packages/core/src/tracing/errors.ts, packages/core/src/tracing/hubextensions.ts, packages/core/test/lib/tracing/errors.test.ts, packages/tracing-internal/src/extensions.ts
`addTracingExtensions` in `@sentry/core` feels like our better named replacement for `addExtensionMethods` however it didn't end up with the same functionality. 
While working on other tracing PRs I realised that we'd not moved `registerErrorInstrumentation` to core and it makes more sense for it to be there.
This PR moves `registerErrorInstrumentation` to `@sentry/core` and calls it from `addTracingExtensions` since they are called together in `addExtensionMethods`. It also adds a flag so errors are only instrumented once. This means we can safely call `addTracingExtensions` as many times as we like (ie. from integration constructors, etc).
=> feat(tracing): Move `registerErrorInstrumentation` to `@sentry/core`

packages/browser-integration-tests/suites/replay/errors/errorMode/test.ts, packages/browser-integration-tests/suites/replay/errors/errorsInSession/test.ts, packages/browser-integration-tests/suites/replay/requests/test.ts
Skip some more tests for webkit & firefox, as they have been flaky sometimes.
Ran these 100x successfully!
=> test(replay): Skip flaky test in firefox

packages/browser-integration-tests/suites/replay/fileInput/init.js, packages/browser-integration-tests/suites/replay/fileInput/template.html, packages/browser-integration-tests/suites/replay/fileInput/test.ts, packages/replay/src/util/getPrivacyOptions.ts, packages/replay/test/integration/rrweb.test.ts, packages/replay/test/unit/util/getPrivacyOptions.test.ts
IMHO we can just ignore all change events for file inputs, that should be OK I'd say?
Closes https://github.com/getsentry/rrweb/issues/80
=> fix(replay): Never capture file input changes

packages/vue/src/router.ts
When rendering in an SSR environment, `window.location` may not be defined. In this case, we should not error but just not start a transaction.
There may be more graceful ways to handle this, but IMHO this should be fine (and def. better than breaking in SSR).
Closes https://github.com/getsentry/sentry-javascript/issues/7515
=> fix(vue): Do not depend on `window.location` for SSR environments

packages/nextjs/src/server/wrapGetServerSidePropsWithSentry.ts
I don't know enough about next to be able to tell when this would happen, but as we are type-casting this above it seems prudent enough to check for existence here as well, to be on the safe side.
Fixes https://github.com/getsentry/sentry-javascript/issues/7516
=> fix(next): Guard against missing serverSideProps

.github/workflows/flaky-test-detector.yml, packages/browser-integration-tests/.eslintrc.js, packages/browser-integration-tests/package.json, packages/browser-integration-tests/scripts/detectFlakyTests.ts
This adds a new script & workflow that can be run to detect flaky tests.
It runs tests a given amount of times (10 to try it out), and logs errors if they happen, else log the average run time (note this is a bit ~~ as it just takes the duration to run the given test, separated by run count - so parallelization will skew this a bit. Still it should give a decent insight how long a given test takes).
Update:
This now runs automatically on PRs that change any browser integration tests. It will run all changed integration tests 100x, separate from the rest of the integration tests.
note that this is not merge blocking, but will report if it fails.
You can also choose to run this manually via workflow_dispatch, in which case it will run all tests 5x (for now).
=> ci: Add workflow to detect flaky tests

packages/integrations/src/rewriteframes.ts, packages/integrations/test/rewriteframes.test.ts
Our previous regex to rewrite windows file paths in stack frames didn't match lower-case `c:\\` prefixes. This PR fixes that.
closes #7499
=> fix(integrations): Handle lower-case prefix windows paths in `RewriteFrames`

.craft.yml
With this change, the `@sentry/sveltekit` package will be published to npm with the next release.
(Not to the release registry yet)
ref #7489
=> chore(repo): Adjust Craft config to publish SvelteKit SDK to NPM

packages/node/src/module.ts, packages/node/test/module.test.ts
When I initially profiled the code I noticed that the regexp used in splitPath function was dominating the profiles. Both basename and dirname from @sentry/utils were actually calling splitPath which executed the regexp - there were 3 call sites to basename and dirname, 1/3 was conditional. The "optimization" is to call path.parse once and extract each path component - this seems to have contributed to the largest win in terms of performance
=> ref(node): use native path module to infer path

packages/core/src/baseclient.ts, packages/core/src/transports/base.ts
I was wrong in moving beforeEnvelope to transport constructor as no client is bound when transport is created, hence client && client.emit will fail...
=> ref(core): move beforeEnvelope to client

README.md
We already have a hiring message at the top with a link to the careers site
=> chore: Remove duplicate hiring message from README

packages/nextjs/src/client/index.ts, packages/nextjs/src/server/index.ts, packages/nextjs/test/clientSdk.test.ts, packages/sveltekit/package.json, packages/sveltekit/src/client/sdk.ts, packages/sveltekit/test/client/sdk.test.ts, packages/utils/src/index.ts, packages/utils/src/userIntegrations.ts, packages/utils/test/userIntegrations.test.ts
With this PR, the `BrowserTracing` integration is automatically added to the client SvelteKit SDK initialization. As in NextJS, tree-shaking will still work by replacing the `__SENTRY_TRACING__` flag with `false` when bundling. Tested this with the rollup replace plugin.
Since we now use `addOrUpdateIntegration` in two SDKs, I opted to move it to the utils package.
ref #7413
=> feat(sveltekit): Automatically add `BrowserTracing` integration

docs/new-sdk-release-checklist.md, packages/integration-shims/tsconfig.json, rollup/bundleHelpers.js, rollup/plugins/bundlePlugins.js
We need to add packages to the ts plugin config, otherwise they are not correctly ES5 transpiled. I also added this to the checklist.
I will merge this PR into master and cut a release so we can do a bugfix release (there is already a feature on develop). 
Closes https://github.com/getsentry/sentry-javascript/issues/7541
=> fix(cdn): Fix es5 CDN bundles

packages/browser/src/client.ts
Since we use `keepalive` anyway as default in our fetch transport, let's remove all usage for the `sendBeacon` API.
=> ref(browser): Remove `sendBeacon` API usage

packages/browser/src/transports/fetch.ts, packages/browser/test/unit/transports/fetch.test.ts
We noticed that sometimes request would remain in a seemingly pending state.
After some investigation, we found out that the limit of 64kb for keepalive-enabled fetch requests is not _per request_ but for _all parallel requests_ running at the same time.
This PR fixes this by keeping track of how large the pending body sizes are, and setting `keepalive` accordingly.
I tried this in my local reproduction app, where it now worked as expected!
We use keepalive if:
* total currently pending body size < 60k
* total # of pending requests < 15
This should defensively work for relevant cases.
Especially for replays and transactions, having keepalive enabled means we can capture more data when a user leaves the page, which would otherwise be lost. This lead to problems with [Next.js transaction …
=> fix(browser): Ensure keepalive flag is correctly set for parallel requests

packages/core/src/hub.ts, packages/core/src/sdk.ts, packages/core/src/sessionflusher.ts, packages/core/src/tracing/hubextensions.ts, packages/core/src/tracing/idletransaction.ts, packages/core/src/tracing/transaction.ts, packages/core/src/tracing/utils.ts
Let's reduce some bundle size!
Now that https://github.com/getsentry/sentry-javascript/pull/7551 merged in, we can remove guards around using the scope.
It's not a huge deal in node packages, so we don't have to go in and change anything there, but we can have some byte savings in our browser packages, so let's save!
Starting with core, then will do the rest of the packages in other PRs when I get time.
=> ref(core): Remove guards around scope usage

packages/nextjs/src/server/utils/wrapperUtils.ts, packages/nextjs/src/server/wrapApiHandlerWithSentry.ts, packages/opentelemetry-node/src/spanprocessor.ts, packages/opentelemetry-node/src/utils/map-otel-status.ts, packages/remix/src/utils/instrumentServer.ts, packages/serverless/src/awslambda.ts, packages/serverless/src/gcpfunction/http.ts
To deprecate `@sentry/tracing` for v8, we need to remove all the internal imports of the package.
This PR migrates imports of types/functions that have already moved to `@sentry/core` and `@sentry/utils`.
=> feat(tracing): Migrate some imports away from `@sentry/tracing`

packages/browser/src/index.ts, packages/nextjs/package.json, packages/nextjs/src/client/index.ts, packages/nextjs/src/edge/edgeclient.ts, packages/nextjs/src/edge/index.ts, packages/nextjs/src/server/utils/wrapperUtils.ts, packages/nextjs/test/config/wrappers.test.ts, packages/nextjs/test/edge/withSentryAPI.test.ts, packages/node/src/index.ts
This PR removes the `@sentry/tracing` dependency from the nextjs SDK.
This involved:
- Moving some imports around 
- Ensuring `@sentry/browser` and `@sentry/node` were exporting the tracing types required
- Calling `addTracingExtensions` where this was previously taken care of by side-effects
=> feat(nextjs): Remove `@sentry/tracing` dependency from nextjs SDK

packages/core/src/tracing/index.ts, packages/core/src/tracing/trace.ts, packages/core/test/lib/tracing/trace.test.ts
`Sentry.trace` is a wrapper that abstracts away much of the complexities that come with managing spans/transaction. You can wrap a method, and not worry about things being sync/async, all of it will be handled for you.
You can also pass in a `onError` callback, that can process errors (but do not actually suppress the error - users can manually do that themselves).
This was introduced to make adding Sveltekit performance monitoring more simple. As I was adding code for https://github.com/getsentry/sentry-javascript/pull/7536 and https://github.com/getsentry/sentry-javascript/pull/7537, I noticed that we duplicate this span creation/finishing logic all over the code base.
look at something like https://github.com/getsentry/sentry-javascript/blob/72dca3e1bfe4e5756c44ef1e4f7b139c0ec6d2c5/pack …
=> feat(core): Add trace function

packages/core/src/tracing/trace.ts, packages/core/test/lib/tracing/trace.test.ts
if you have not enabled tracing extensions via `addTracingExtensions`, this function will not generate spans, and the `span` returned from the callback may be undefined.
=> fix(tracing): Account for case where startTransaction returns undefined

packages/sveltekit/package.json, packages/sveltekit/rollup.npm.config.js, packages/sveltekit/src/client/router.ts, packages/sveltekit/src/client/sdk.ts, packages/sveltekit/test/client/router.test.ts, packages/sveltekit/test/client/sdk.test.ts, packages/sveltekit/test/vitest.setup.ts, packages/sveltekit/vite.config.ts, yarn.lock
This PR adds a router instrumentation to the client SvelteKit SDK. No need for user configuration, as it will be added automatically on SDK intialization. 
I had to adjust test a bunch because the SvelteKit `$app/stores` import doesn't work in a non-SvelteKit app build (like in our unit tests). The unit tests aren't great but they're at least testing the instrumentation code itself. We'll need to add integration tests later on. 
ref #7413
=> feat(sveltekit): Add SvelteKit routing instrumentation

packages/sveltekit/src/client/load.ts, packages/sveltekit/test/client/load.test.ts
ref https://github.com/getsentry/sentry-javascript/issues/7526
=> feat(sveltekit): Add performance monitoring for client load

packages/browser-integration-tests/suites/replay/extendNetworkBreadcrumbs/fetch/contentLengthHeader/test.ts, packages/browser-integration-tests/suites/replay/extendNetworkBreadcrumbs/fetch/noContentLengthHeader/test.ts, packages/browser-integration-tests/suites/replay/extendNetworkBreadcrumbs/fetch/nonTextBody/test.ts, packages/browser-integration-tests/suites/replay/extendNetworkBreadcrumbs/fetch/requestBody/test.ts, packages/browser-integration-tests/suites/replay/extendNetworkBreadcrumbs/xhr/contentLengthHeader/test.ts, packages/browser-integration-tests/suites/replay/extendNetworkBreadcrumbs/xhr/noContentLengthHeader/test.ts, packages/browser-integration-tests/suites/replay/extendNetworkBreadcrumbs/xhr/nonTextBody/test.ts, packages/browser-integration-tests/suites/replay/extendNetworkBreadcrumbs/xhr/requestBody/test.ts, packages/browser-integration-tests/suites/replay/privacyInput/test.ts, packages/replay/src/coreHandlers/handleNetworkBreadcrumbs.ts, packages/replay/test/unit/coreHandlers/handleNetworkBreadcrumbs.test.ts
This adjusts the replay request body capturing to capture the fetch body size if no Content-Length header is present.
=> feat(replay): Capture fetch body size for replay events

packages/nextjs/test/clientSdk.test.ts, packages/nextjs/test/config/withSentry.test.ts, packages/nextjs/test/edge/edgeWrapperUtils.test.ts, packages/node/package.json, packages/node/src/integrations/onuncaughtexception.ts, packages/node/test/integrations/http.test.ts
This PR cleans up some imports that were missed off the previous node and nextjs PRs.
It removes some more `@sentry/tracing` imports from tests and calls `addTracingExtensions` where tests were relying on the side-effects.
=> feat(tracing): Remove some more `@sentry/tracing` references

packages/opentelemetry-node/package.json, packages/opentelemetry-node/src/index.ts, packages/opentelemetry-node/src/spanprocessor.ts, packages/opentelemetry-node/test/propagator.test.ts, packages/opentelemetry-node/test/spanprocessor.test.ts
This PR removes `@sentry/tracing` as dependency from `opentelemetry-node`
=> feat(otel): Remove `@sentry/tracing` dependency from `opentelemetry-node`

packages/remix/package.json, packages/remix/src/index.client.tsx, packages/remix/src/index.server.ts, packages/remix/test/index.server.test.ts
- In `index.client.tsx`, `BrowserTracing` and `Integrations` are passed through from `@sentry/react`
- In `index.server.ts`:
- `@sentry/node` already exports `Integrations` which includes both node and tracing integrations 
- Previously, node Integrations were hidden due to the tracing Integrations export
- ⚠️ `BrowserTracing` is no longer exported. This is technically a breaking change but I don't think it should have ever been exported from the server.
=> feat(remix): Remove `@sentry/tracing` dependency from Remix SDK

packages/gatsby/package.json, packages/gatsby/src/index.ts, packages/gatsby/src/utils/integrations.ts, packages/gatsby/test/gatsby-browser.test.ts, packages/gatsby/test/sdk.test.ts, packages/node/test/handlers.test.ts
This PR removes `@sentry/tracing` dependency from Gatsby SDK.
- ⚠️ This removes the node tracing integrations from the `Integrations` export which is technically a breaking change but these cannot be used and was likely a mistake
- It's worth noting that `BrowserTracing` is conditionally added via the config options so it will always be included in the output bundle and cannot be tree-shaken away.
=> feat(gatsby): Remove `@sentry/tracing` dependency from Gatsby SDK

packages/serverless/package.json, packages/serverless/scripts/buildLambdaLayer.ts, packages/serverless/src/index.ts
=> feat(serverless): Remove `@sentry/tracing` dependency from serverless SDK

packages/e2e-tests/test-applications/standard-frontend-react/src/globals.d.ts, packages/e2e-tests/test-applications/standard-frontend-react/src/index.tsx, packages/e2e-tests/test-applications/standard-frontend-react/tests/behaviour-test.spec.ts, packages/e2e-tests/test-applications/standard-frontend-react/tests/fixtures/ReplayRecordingData.ts
This adds replay to one of our E2E test apps and also verifies that the replay is correctly sent over.
Closes https://github.com/getsentry/sentry-javascript/issues/7249
=> test(replay): Add replay E2E test

packages/core/src/integrations/inboundfilters.ts, packages/core/test/lib/integrations/inboundfilters.test.ts
Noticed that actually currently we filter _any_ type of event here.
We should handle transactions separately (TBD).
=> fix(core): Ensure `ignoreErrors` only applies to error events

packages/browser-integration-tests/suites/replay/dsc/init.js, packages/browser-integration-tests/suites/replay/dsc/test.ts, packages/browser-integration-tests/utils/replayHelpers.ts, packages/core/src/baseclient.ts, packages/core/src/tracing/transaction.ts, packages/replay/src/util/addGlobalListeners.ts, packages/types/src/client.ts, packages/types/src/envelope.ts
This adds `replay_id` to the DSC of transactions.
Closes https://github.com/getsentry/sentry-javascript/issues/7555
Supersedes https://github.com/getsentry/sentry-javascript/pull/7493
=> feat(replay): Add `replay_id` to transaction DSC

packages/sveltekit/src/client/router.ts, packages/sveltekit/test/client/router.test.ts
Previously our Kit routing instrumentation used the parameterized route id to determine if the origin and destination of the navigation were identical (in which case we don't want to create a navigation transaction). 
This caused navigations from e.g. `/users/123` to `users/456` to not create a transaction because their route id was identical. This PR fixes this bug by using the raw URL which we also get from the `navigating` store emissions. 
Furthermore, this PR fixes the transaction source which previously was always set to `route`, even if no route id was available.  
ref #7413
=> fix(sveltekit): Handle same origin and destination navigations correctly

packages/core/src/tracing/transaction.ts, packages/opentelemetry-node/src/spanprocessor.ts, packages/opentelemetry-node/test/spanprocessor.test.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/7538
This one was tricky to debug...
On transactions we store the hub that called `hub.startTransaction()`. This was because we have the assumption that the hub that calls `startTransaction` will be the one that finishes it.
In OpenTelemetry world this isn't the case, since our hub cloning (via domains) does not map exactly to otel context forking (via async hooks). This means async hooks might fork first, leading to the incorrect hub being used on transaction finish.
I do not want to remove the setting hub in transaction constructor, since that is needed for browser world, but to make due temporarily I added a method to override what hub is on the transaction.
The span processor then sets a new hub on finish.
=> fix(otel): Make sure we use correct hub on finish

.github/workflows/release-size-info.yml
The size adding doesn't seem to be working anymore.
Looking at e.g. https://github.com/getsentry/sentry-javascript/actions/runs/4477866410/jobs/7869927544
it seems that `env.GITHUB_REF` is not set anymore, even though it is documented here: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
So I _think_ this should actually work even better (no regex needed).
=> ci: Get release tag name from event

packages/core/src/tracing/trace.ts, packages/sveltekit/src/server/load.ts, packages/sveltekit/test/server/load.test.ts
Previously, our server `wrapLoadWithSentry` assumed that `load` in `+page.ts` and `+page.server.ts` work identically. Unfortunately, the load `event` arg has different contents for both, namely that the server-only load event contains a `request` object while the shared (client and server) load event doesn't. This PR fixes that by distinguishing between the two load types within the wrapper. Users can still use the same wrapper for both cases.
Furthermore, this PR removes the usage of domains in the load wrapper, as on the server-side, we're already in a domain when `handleSentry` is used. Creating another domain here, caused the creation of a new transaction instead of adding the span to the transaction that was created by `handleSentry`. 
ref #7403
=> fix(sveltekit): Handle server-only and shared load functions

packages/tracing-internal/package.json, packages/tracing-internal/test/browser/backgroundtab.test.ts, packages/tracing-internal/test/browser/browsertracing.test.ts, packages/tracing-internal/test/browser/request.test.ts, packages/tracing-internal/test/utils/TestClient.ts
No need to depend on @sentry/browser as devDependency, which Nx complains about.
I copied the TestClient from Replay, where we had the same issue.
=> build(tracing-internal): Remove circular dependency

packages/sveltekit/src/server/handle.ts, packages/sveltekit/test/server/handle.test.ts
ref https://github.com/getsentry/sentry-javascript/issues/7526
Using the SvelteKit `handle` function, insert in a meta tag to add backend -> frontend tracing.
=> feat(sveltekit): Add meta tag for backend -> frontend

packages/sveltekit/src/server/load.ts, packages/sveltekit/test/server/load.test.ts
This PR adjust the span ops of `load` functions to distinguish between spans of server-only and universal `load` functions (`+page.ts` vs `+page.server.ts`):
* Server-only load span op: `function.sveltekit.server.load`
* Universal load span op: `function.sveltekit.load`
ref #7526
=> ref(sveltekit): Distinguish span ops of server-only and universal load functions

packages/browser-integration-tests/suites/public-api/startTransaction/basic_usage/subject.js, packages/browser-integration-tests/suites/stacktraces/protocol_fn_identifiers/test.ts
Try to fix flaky tests:
Closes https://github.com/getsentry/sentry-javascript/issues/7595
Closes https://github.com/getsentry/sentry-javascript/issues/7596
One of them I actually coulnd't reproduce flaking, so I guess we can close this as well.
=> test: Fix some flaky tests

packages/nextjs/src/client/index.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/7500
In #7167 we put `abs_path` onto the stack frame object in error events. `abs_path` is used by symbolicator to resolve source maps and since we now have it on the stack frame it is not [backfilled](https://github.com/getsentry/relay/blob/014964b2f59f54aca45f1b77f4806f6339e12833/relay-general/src/store/normalize/stacktrace.rs#L26-L48) anymore in Relay.
This change caused source maps to break in the Next.js SDK because we do some frame rewriting to account for asset prefixes and URL decoding issues.
=> fix(nextjs): Rewrite `abs_path` frames

packages/integrations/package.json, packages/integrations/rollup.bundle.config.js, packages/integrations/scripts/buildBundles.ts
I noticed we have a `--parallel` flag for building the integration CDN addons, but don't use it. At least locally that drastically improves build time for me (from ~250s to ~70s).
While at it I also aligned the JS version strings we use there in rollup with the browser config.
=> build(cdn): Make integration CDN bundles build in parallel

packages/sveltekit/src/server/handle.ts, packages/sveltekit/test/server/handle.test.ts
Just noticed in my test app that apparently the `%sveltekit.head%` isn't present in the html that's passed to `transformPageChunk`. Hence our `<meta>` tag injection logic introduced in #7574  didn't find the anchor point where to inject the tags. This PR fixes the injection, by simply appending it to an open `<head>` tag. It's not pretty but it should do the trick 🤞 (we can revisit if this breaks folks).
Tested with one of my kit test apps and now, FE and BE transactions are connected:
ref #7526
=> fix(sveltekit): Fix `<meta>` tag injection

packages/core/src/integrations/inboundfilters.ts, packages/core/test/lib/integrations/inboundfilters.test.ts, packages/types/src/options.ts
This works similar to `ignoreErrors`, but matches transaction names.
ref https://github.com/getsentry/develop/pull/884
=> feat(core): Add `ignoreTransactions` option

packages/browser-integration-tests/suites/tracing/browsertracing/pageload/init.js, packages/browser-integration-tests/suites/tracing/browsertracing/pageload/test.ts, packages/browser-integration-tests/suites/tracing/browsertracing/pageloadDelayed/init.js, packages/browser-integration-tests/suites/tracing/browsertracing/pageloadDelayed/test.ts, packages/tracing-internal/src/browser/router.ts
This adjusts the `pageload` transaction to ensure its start is always the timeOrigin.
This should help with e.g. lazy loading sentry, where we still want this to be accurate.
=> feat(tracing): Ensure `pageload` transaction starts at timeOrigin

packages/vue/src/errorhandler.ts, packages/vue/src/tracing.ts, packages/vue/src/vendor/components.ts, packages/vue/test/errorHandler.test.ts, packages/vue/test/vendor/components.test.ts
ref https://github.com/getsentry/sentry-javascript/issues/7560
Add MIT license to code vendored from vuejs.
=> chore(vue): Add attribution license

packages/utils/src/buildPolyfills/_asyncNullishCoalesce.ts, packages/utils/src/buildPolyfills/_asyncOptionalChain.ts, packages/utils/src/buildPolyfills/_asyncOptionalChainDelete.ts, packages/utils/src/buildPolyfills/_createNamedExportFrom.ts, packages/utils/src/buildPolyfills/_createStarExport.ts, packages/utils/src/buildPolyfills/_interopDefault.ts, packages/utils/src/buildPolyfills/_interopNamespace.ts, packages/utils/src/buildPolyfills/_interopNamespaceDefaultOnly.ts, packages/utils/src/buildPolyfills/_interopRequireDefault.ts, packages/utils/src/buildPolyfills/_interopRequireWildcard.ts, packages/utils/src/buildPolyfills/_nullishCoalesce.ts, packages/utils/src/buildPolyfills/_optionalChain.ts, packages/utils/src/buildPolyfills/_optionalChainDelete.ts, packages/utils/src/path.ts, packages/utils/src/string.ts, packages/utils/src/supports.ts, packages/utils/src/vendor/escapeStringForRegex.ts, packages/utils/src/vendor/supportsHistory.ts
ref https://github.com/getsentry/sentry-javascript/issues/7560
Adds license to top of vendored code. When necessary pulls vendored code into it's own file as per our policies.
=> chore(utils): Add license to vendor attribution

packages/remix/src/utils/instrumentServer.ts, packages/remix/src/utils/types.ts, packages/remix/src/utils/vendor/getIpAddress.ts, packages/remix/src/utils/vendor/response.ts, packages/remix/src/utils/web-fetch.ts, packages/remix/test/utils/getIpAddress.test.ts
ref https://github.com/getsentry/sentry-javascript/issues/7560
Moves stuff into a vendor folder so it's easier to keep track of.
=> chore(remix): Add license text to vendored files

packages/sveltekit/src/server/handle.ts, packages/sveltekit/test/server/handle.test.ts
Previously, we always created a new domain when entering the `sentryHandle` function. This caused "nested" SvelteKit Server calls to create new transaction whenever a new domain was created in the `sentryHandle` function because the active span is bound to the domain. This PR introduces a check if there is an active transaction, in which case we just execute the handler and don't create a new domain, as we are already in this active domain. 
As a result, nested SK server calls become a span of the parent server call instead of a new transaction: 
ref #7526
=> fix(sveltekit): Handle nested server calls in `sentryHandle`

packages/nextjs/src/config/loaders/wrappingLoader.ts
Ref #6726 
We missed the `loading.tsx` component in the server component wrapping logic.
=> fix(nextjs): Add loading component type to server component wrapping

packages/node-integration-tests/suites/public-api/LocalVariables/local-variables-caught.mjs, packages/node/src/integrations/localvariables.ts, packages/node/test/integrations/localvariables.test.ts
Closes #7230 
This PR converts the `LocalVariables` debugger code to callbacks so that we can call `Debugger.resume` synchronously from the `pause` callback which fixes the memory leak.
It's worth noting that now there is no usage of async, it will not be possible to use async import to improve this:
https://github.com/getsentry/sentry-javascript/blob/0743e988d6e160a530b07cb80b9ec4cb17ba9b39/packages/node/src/integrations/localvariables.ts#L32-L35
I created a basic Express server to test these changes and load tested an endpoint with a caught/handled error to see if any memory is leaked. Without the async code, performance is also much improved:
|  | Before | After |
| --- | --- | --- |
| Requests/sec | 40 | 220 |
| Av. Latency | 90ms | 40ms |
| Peak Memory | 570 MB  | 130 MB  |
=> fix(node): Convert debugging code to callbacks to fix memory leak in `LocalVariables` integration

packages/nextjs/src/config/webpack.ts
Fixes showing of certain warning messages 3 times during the build.
=> fix(nextjs): Show errors and warnings only once during build

packages/nextjs/src/config/types.ts, packages/nextjs/src/config/withSentryConfig.ts
fix error:
```
> Build error occurred
TypeError: originalRewritesResult.beforeFiles is not iterable
at userNextConfig.rewrites (/home/bertho/dev/oa/node_modules/@sentry/nextjs/cjs/config/withSentryConfig.js:107:66)
at async loadRewrites (/home/bertho/dev/oa/node_modules/next/dist/lib/load-custom-routes.js:401:23)
at async Promise.all (index 1)
at async Object.loadCustomRoutes [as default] (/home/bertho/dev/oa/node_modules/next/dist/lib/load-custom-routes.js:13:44)
at async Span.traceAsyncFn (/home/bertho/dev/oa/node_modules/next/dist/trace/trace.js:79:20)
at async /home/bertho/dev/oa/node_modules/next/dist/build/index.js:79:34
at async Span.traceAsyncFn (/home/bertho/dev/oa/node_modules/next/dist/trace/trace.js:79:20)
at async Object.build [as default] …
```
=> fix(nextjs): Gracefully handle undefined `beforeFiles` in rewrites

packages/node/src/integrations/undici/index.ts, packages/node/src/types.ts, packages/node/test/integrations/undici.test.ts
closes https://github.com/getsentry/sentry-javascript/issues/7624
This PR does a couple of things.
1. Undeprecates `tracePropagationTargets` as a top level option in Node options.
2. Only generates spans/breadcrumbs on a hub if the Undici integration is active.
3. Moves `shouldCreateSpanForRequest` into an option in the Undici integration.
4. Cleans up patching in the test to make it easier to understand.
After these changes get merged in we can add Undici by default to both next.js and sveltekit. We can then think about adding it by default to the Node SDK.
=> ref(node): Clean up Undici options

packages/sveltekit/src/index.client.ts, packages/sveltekit/src/index.server.ts, packages/sveltekit/src/server/index.ts
This PR fixes Node SDK exports not being available in prod builds. For example, calling `Sentry.withScope(...)` throws an error because `withScope` is not defined on the top-level namespace. This is because for CJS, Vite puts wildcard-exported properties into the `default` property rather than onto the namespace in production builds.
=> fix(sveltekit): Explicitly export Node SDK exports

packages/sveltekit/README.md
Now that we have almost all error/performance monitoring related functionality (once all PRs are merged), it's time to update the readme.
(Yup, currently it's 9 steps. We can simplify this setup, once we move to having everything in the hooks files)
=> doc(sveltekit): Update README Setup Instructions

packages/core/src/tracing/idletransaction.ts, packages/tracing-internal/src/browser/browsertracing.ts
I want to track the frequency of this case, since we currently have no way of seeing it. When you click anywhere while another interaction transaction is still in progress, it gets finished. Therefore, we should add a new `finishReason` for this case.
Reminder that `_finishReason` is for the purpose of experimentation only and I will remove it later, please excuse any sloppiness regarding making `_finishReason` public and setting its value externally 😄
=> feat(tracing): Add custom finishReason for when interaction is interrupted by another

packages/sveltekit/README.md
Restructures SDK setup into client, server and build setup sections. Also moves init call from dedicated files to hooks.
Only ready to go once `withSentryViteConfig` doesn't hard-require the `sentry.client|server.config.js` files.
=> doc(sveltekit): Move SDK initialization to hooks and restructure setup in README

CHANGELOG.md, MIGRATION.md
Merging straight to master as `7.46.0` was already merged with #7666
=> meta(changelog): Add @sentry/tracing notes to 7.46.0 changelog

.github/ISSUE_TEMPLATE/bug.yml, README.md
just noticed that SvelteKit wasn't mentioned yet in the usual places.
Also did some additional rewording in the repo readme
=> chore(repo): Add Sveltekit SDK to repo readme and bug report template

.craft.yml
I just noticed I forgot to add SvelteKit to the release registry target in our craft config after we merged the first [manual entry](https://github.com/getsentry/sentry-release-registry/tree/master/packages/npm/%40sentry/sveltekit). We should be good to add the entry now as missing a version shouldn't be a problem.
=> chore(repo): Update craft config to add SvelteKit SDK release registry entry

packages/sveltekit/src/client/handleError.ts, packages/sveltekit/src/server/handleError.ts, packages/sveltekit/test/client/handleError.test.ts, packages/sveltekit/test/server/handleError.test.ts
Previously, our `handleErrorWithSentry` wrapper did nothing if users didn't provide a custom error handler as an argument. While IMO it's good that the error handler is an optional parameter, this swallowed errors and didn't log them to the console anymore. 
This PR fixes that by adding a default error handler which our wrapper invokes if no custom handler was provided. The client- and server default handlers log the error to the console, exactly like the default handlers by SvelteKit ([client](https://github.com/sveltejs/kit/blob/369e7d6851f543a40c947e033bfc4a9506fdc0a8/packages/kit/src/core/sync/write_client_manifest.js#LL127C2-L127C2), [server](https://github.com/sveltejs/kit/blob/369e7d6851f543a40c947e033bfc4a9506fdc0a8/packages/kit/src/runtime/server/index.js#L43)).
=> fix(sveltekit): Log error to console by default in `handleErrorWithSentry`

MIGRATION.md
If users imported `stripUrlQueryAndFragment` from the tracing package, they now need to import it from the utils package.
This PR adds a note to MIGRATION.md about this.
closes #7684
=> doc(utils): Add migration note for `stripUrlQueryAndFragment` import

packages/core/src/hub.ts
With the changes in https://github.com/getsentry/sentry-javascript/pull/7551, this is no longer required. Let's save some bytes!
=> ref(core): Remove check for scope in `_sendSessionUpdate`

.github/workflows/gitflow-sync-develop.yml
As pointed out here: https://github.com/getsentry/sentry-javascript/pull/7705 we can replace this with core functionality.
=> ci: Use GitHub CLI for automerge

packages/nextjs/package.json
We messed up in #6592 and destroyed tree shaking capabilities for webpack by entirely removing the `sideEffects` field in the package.json. This PR adds it back so tree shaking should be possible again.
Hopefully fixes https://github.com/getsentry/sentry-javascript/issues/7680
=> fix(nextjs): Restore tree shaking capabilities

packages/angular/src/tracing.ts, packages/angular/test/tracing.test.ts
Update function getParameterizedRouteFromSnapshot to handle routes with empty paths.
Fixes GH-7681
- [+] If you've added code that should be tested, please add tests.
- [+] Ensure your code lints and the test suite passes (`yarn lint`) & (`yarn test`).
=> fix(angular): Handle routes with empty path

packages/browser-integration-tests/package.json, packages/browser-integration-tests/suites/integrations/httpclient/axios/subject.js, packages/browser-integration-tests/suites/integrations/httpclient/axios/test.ts, packages/integrations/src/httpclient.ts, packages/replay/test/unit/coreHandlers/handleXhr.test.ts, packages/types/src/instrument.ts, packages/utils/src/instrument.ts, packages/utils/test/instrument.test.ts, yarn.lock
This updates the `HttpClient` integration to use the "regular" instrumentation handling, ensuring this works with Axios.
This also adds `request_headers` to the xhr info (which we'll also need for replay). 
It also ensures that we always correctly get the method/url from fetch options, even when they are other valid objects.
Closes https://github.com/getsentry/sentry-javascript/issues/7615
=> fix(integrations): Ensure HttpClient integration works with Axios

packages/tracing-internal/package.json
Adds `sideEffects: false` to the `tracing-internal` package so that it can be properly tree shaken by Webpack.
=> fix(tracing-internal): Add `sideEffects` field to `package.json`

.github/workflows/gitflow-sync-develop.yml, packages/angular/src/tracing.ts, packages/angular/test/tracing.test.ts, packages/nextjs/package.json, packages/replay/README.md
Update examples for using lazy integrations to avoid typing errors to use `@sentry/replay`.
The example code in the current document was too implicit, and it's hard to predict the errors.
=> docs(replay): Update README.md for lazy integrations

packages/core/src/utils/prepareEvent.ts
In node (and probably other platforms too), the bottom frame of a trace often contains native code/filenames. See "internal/main/run_main_module.js" below:
```json
[
{
"function": "<anonymous>",
"module": "run_main_module",
"filename": "internal/main/run_main_module.js",
"abs_path": "internal/main/run_main_module.js",
"lineno": 17,
"colno": 47,
"in_app": false
},
{
"function": "Function.executeUserEntryPoint [as runMain]",
"module": "run_main",
"filename": "internal/modules/run_main.js",
"abs_path": "internal/modules/run_main.js",
"lineno": 75,
"colno": 12,
"in_app": false
},
{
"function": "Module._load",
"module": "loader",
"filename": "internal/modules/cjs/loader.js",
"abs_path": "internal/modules/cjs/loader.js",
"lineno": 790,
"colno": 12,
"in_app": false
},
{
"function": …
```
=> fix(core): Determine debug ID paths from the top of the stack

packages/ember/addon/instance-initializers/sentry-performance.ts, packages/ember/tests/acceptance/sentry-replay-test.js, packages/ember/tests/dummy/app/app.js, packages/ember/tests/dummy/app/router.js, packages/ember/tests/dummy/app/routes/replay.js, packages/ember/tests/dummy/app/templates/application.hbs, packages/ember/tests/dummy/app/templates/replay.hbs, packages/ember/tests/dummy/config/environment.js
This uses the new `addIntegration` API to add browser tracing, which means we do not need to call `Sentry.init()` twice, which lead to issues as replay relies on the client remaining consistent.
Fixes https://github.com/getsentry/sentry-javascript/issues/7640
=> fix(ember): Ensure only one client is created & Replay works

package.json, packages/remix/package.json
Webpack and intergration are not used in remix app. Webpack even brings older cli version which makes sentry even bigger.
https://packagephobia.com/result?p=@sentry/remix@7.46.0
=> fix(remix): Remove unnecessary dependencies 

packages/core/src/tracing/idletransaction.ts, packages/tracing/test/idletransaction.test.ts
See: https://github.com/getsentry/sentry-javascript/discussions/7660
Make sure that if another transaction is set on the scope while an idle transaction is occuring, don't forcefully remove that transaction from the scope on idle transaction finish.
=> fix(tracing): Make sure idle transaction does not override other transactions

packages/sveltekit/src/client/load.ts, packages/sveltekit/src/common/utils.ts, packages/sveltekit/src/server/load.ts, packages/sveltekit/test/client/load.test.ts, packages/sveltekit/test/common/utils.test.ts, packages/sveltekit/test/server/load.test.ts
As outlined in the [SvelteKit docs](https://kit.svelte.dev/docs/load#redirects), users can `throw redirect(300, 'route/to/redirect')` in `load` functions. We don't want to capture these as errors and send them to Sentry.
closes #7719
=> fix(sveltekit): Don't capture thrown `Redirect`s as exceptions

.github/workflows/flaky-test-detector.yml, packages/browser-integration-tests/suites/replay/sampling/test.ts
Noticed this flake once, adding a guard to make this non-flaky hopefully.
=> test: Fix flaky replay sampling test

packages/node/src/integrations/http.ts, packages/node/src/integrations/undici/index.ts, packages/node/src/integrations/utils/http.ts, packages/node/src/nodeVersion.ts, packages/node/test/integrations/http.test.ts, packages/node/test/utils.ts
Just a quick refactor because I noticed this was duplicated everywhere.
=> chore(node): Extract node version constant

packages/node/src/integrations/utils/http.ts, packages/node/test/integrations/http.test.ts
In #7667 we missed that our `urlToOptions` helper function is actually called to normalize request options that are then passed to the actual http client. Meaning, we shouldn't have redacted the authority in this function but at a later time when we extract the sanitized version (`extractUrl`). This PR changes the redaction location accordingly and hence fixes requests with authority not being sent properly. 
closes #7724
=> fix(node): Redact URL authority only in breadcrumbs and spans

packages/node/src/integrations/http.ts, packages/sveltekit/src/client/load.ts, packages/sveltekit/test/client/load.test.ts, packages/tracing-internal/src/browser/index.ts, packages/tracing-internal/src/browser/request.ts, packages/tracing-internal/src/index.ts, packages/types/src/index.ts, packages/types/src/request.ts, packages/utils/src/instrument.ts, packages/utils/src/url.ts, packages/utils/test/url.test.ts
This PR adds partial instrumentation to the client-side `fetch` passed to the universal `load` functions. It enables distributed traces of fetch calls happening **inside** a `load` function. 
Limitation: `fetch` requests made by SvelteKit (e.g. to call server-only load functions) are **not** touched by this instrumentation because we cannot access the Kit-internal fetch function at this time. Opened an [issue on the SvelteKit repo](https://github.com/sveltejs/kit/issues/9530) to find a solution for this.  
Anyway, here's a fancy screenshot of a successful trace: 
My guess is that https://github.com/sveltejs/kit/issues/9542 and https://github.com/sveltejs/kit/issues/9530 are gonna take a little while longer to be resolved. I'd say, we add this in for the moment so that we at least get …
=> feat(sveltekit): Add partial instrumentation for client-side `fetch`

packages/react/src/errorboundary.tsx, packages/react/test/errorboundary.test.tsx
Based on work in https://github.com/getsentry/sentry-javascript/pull/7750.
Also adds fallback behavior in case the client does not have hooks.
=> fix(react): Only show report dialog if event was sent to Sentry

packages/browser-integration-tests/suites/public-api/captureUserFeedback/init.js, packages/browser-integration-tests/suites/public-api/captureUserFeedback/simple_feedback/subject.js, packages/browser-integration-tests/suites/public-api/captureUserFeedback/simple_feedback/test.ts, packages/browser/src/client.ts, packages/browser/src/exports.ts, packages/browser/src/sdk.ts, packages/browser/src/userfeedback.ts, packages/browser/test/unit/userfeedback.test.ts
- closes: https://github.com/getsentry/sentry-javascript/issues/6252
=> feat(browser): Add `captureUserFeedback`

packages/node-integration-tests/suites/public-api/LocalVariables/test.ts, packages/node/src/integrations/localvariables.ts, packages/node/test/integrations/localvariables.test.ts
It looks like the v8 inspector API has some incompatibilities with domains and async which cause them to not be GC'd in a reasonable timeframe for it to be used in production applications.
This PR causes the `LocalVariables` integration not to be enabled if the Node version is less than v18.
=> fix(node): Disable `LocalVariables` integration on Node < v18

packages/browser/examples/README.md, packages/browser/examples/app.js
From what I know the example is not used/updated much but it's still a super simple way to test some of the SDK functionalities. And at the moment is broken out of the box.
=> chore(browser): Update browser example

packages/browser/src/transports/offline.ts, packages/browser/src/transports/types.ts
As reported in #7766, our `transportOptions` init field currently isn't typed correctly to accept `BrowserOfflineTransportOptions`, causing type errors when trying to configure the offline transport. This PR fixes this bug by making `BrowserTransportOptions` extend `BrowserOfflineTransportOptions`.
closes #7766
=> fix(browser): Adjust `transportOptions` to support offline transport options

packages/node-integration-tests/README.md, packages/tracing-internal/src/node/integrations/prisma.ts, packages/tracing/test/integrations/node/prisma.test.ts
Ran into this while taking a look at https://github.com/getsentry/sentry-javascript/issues/5780
=> ref(tracing): Convert prisma integration to use trace func

packages/core/src/hub.ts, packages/core/src/index.ts, packages/node/src/async/domain.ts, packages/node/test/async/domain.test.ts
This PR extends `runWithAsyncContext` on `AsyncContextStrategy` to allow reuse of existing context rather than creating a new sub-context.
I've also added more jsdocs since the functions are getting more complex.
=> feat(core): Extend `AsyncContextStrategy` to allow reuse of existing context

packages/browser-integration-tests/suites/replay/captureReplay/test.ts, packages/browser-integration-tests/suites/replay/captureReplayFromReplayPackage/test.ts, packages/browser-integration-tests/suites/replay/customEvents/test.ts, packages/browser-integration-tests/suites/replay/errors/errorMode/test.ts, packages/browser-integration-tests/suites/replay/errors/errorsInSession/test.ts, packages/browser-integration-tests/suites/replay/flushing/test.ts, packages/browser-integration-tests/suites/replay/multiple-pages/test.ts, packages/browser-integration-tests/suites/replay/sessionExpiry/test.ts, packages/browser-integration-tests/suites/replay/sessionMaxAge/test.ts, packages/replay/src/replay.ts, packages/replay/src/types.ts, packages/replay/src/util/sendReplayRequest.ts, packages/replay/test/integration/flush.test.ts
This should be sent with each segment now.
=> ref(replay): Always send `replay_start_timestamp`

packages/node/src/checkin.ts, packages/node/test/checkin.test.ts, packages/types/src/checkin.ts, packages/types/src/datacategory.ts, packages/types/src/envelope.ts, packages/types/src/index.ts, packages/utils/src/envelope.ts
ref https://github.com/getsentry/sentry/issues/43661
I had some time on my hands, so added this in. **Does not add any functionality around sending check-ins, only the envelope types needed to construct them**.
https://develop.sentry.dev/sdk/check-ins/
I overengineered envelope types 😭
=> feat(node): Add checkin envelope types

packages/sveltekit/src/config/index.ts, packages/sveltekit/src/index.server.ts, packages/sveltekit/src/index.types.ts, packages/sveltekit/src/vite/index.ts, packages/sveltekit/src/vite/injectInitPlugin.ts, packages/sveltekit/src/vite/sentrySvelteKitPlugin.ts, packages/sveltekit/src/vite/utils.ts, packages/sveltekit/src/vite/withSentryViteConfig.ts, packages/sveltekit/test/vite/injectInitPlugin.test.ts, packages/sveltekit/test/vite/sentrySvelteKitPlugin.test.ts, packages/sveltekit/test/vite/withSentryViteConfig.test.ts
This PR adds the `sentrySvelteKitPlugin` vite plugin to the SvelteKit SDK which will replace the `withSentryViteConfig` wrapper. Currently, this plugin does exactly what the wrapper is doing, namely, adding the injectInitPlugin. In the future, this plugin will also add the source maps plugin. 
Usage:
```js
// vite.config.ts|js
export default defineConfig({
plugins: [sentrySvelteKitPlugin(), sveltekit()],
// rest of config
});
```
I'll remove `withSentryViteConfig` in a follow-up PR, to keep the removal atomic.
ref #7787
=> feat(sveltekit): Add `sentrySvelteKitPlugin`

packages/sveltekit/README.md
following #7788 #7789 and #7791 this final PR now adjust the `README` with the setup instructions for `sentrySvelteKitPlugin`
closes #7787
=> doc(sveltekit): Adjust README Vite setup section

packages/browser/src/index.ts
When reviewing https://github.com/getsentry/sentry-react-native/pull/2958, I noticed that `@sentry-internal/tracing` is only required as a dep of `@sentry/react-native` because of `instrumentOutgoingRequests` and `RequestInstrumentationOptions`.
Let's re-export those from the browser package so that react native can get rid of the `@sentry-internal/tracing` dependency, which should make it easier for them to migrate later on.
=> feat(browser): Export request instrumentation options

packages/browser/test/unit/tracekit/misc.test.ts, packages/utils/src/stacktrace.ts
Closes #7813
It looks like stack lines containing `Error: ` were picked erroneously up by the gecko parser. This PR strips lines that match this pattern.
=> fix(browser): DOMException SecurityError stacktrace parsing bug

packages/replay/README.md, packages/replay/src/integration.ts, packages/replay/test/integration/getReplayId.test.ts, packages/replay/test/integration/getSessionId.test.ts
This adds a public `getReplayId()` method to the replay integration to get the ID of the ongoing session.
Closes https://github.com/getsentry/sentry-javascript/issues/7795
=> feat(replay): Add `getReplayId()` method

packages/browser/src/integrations/breadcrumbs.ts, packages/integrations/src/httpclient.ts, packages/replay/src/coreHandlers/handleXhr.ts, packages/replay/test/unit/coreHandlers/handleXhr.test.ts, packages/tracing-internal/src/browser/request.ts, packages/tracing-internal/test/browser/request.test.ts, packages/types/src/instrument.ts, packages/utils/src/instrument.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/7783
XHR instrumentations of multiple parallel running SDK versions were clashing. We now instead use a field that should be bumped every time we change the layout of the type in a non-backwards compatible way.
=> fix(utils): Make xhr instrumentation independent of parallel running SDK versions

packages/serverless/src/awslambda.ts, packages/serverless/src/gcpfunction/cloud_events.ts, packages/serverless/src/gcpfunction/events.ts, packages/serverless/src/gcpfunction/http.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/7826
If tracing extensions are not added, make sure we identify that `hub.startTransaction` can return undefined.
=> fix(serverless): Account when transaction undefined

packages/sveltekit/src/server/sdk.ts, packages/sveltekit/src/server/utils.ts, packages/sveltekit/test/server/utils.test.ts
This PR adds a custom `RewriteFrames` iteratee to the server SDK which 
* Does exactly the same thing as the default iteratee if simply initializiung `RewriteFrames()` without custom options
* Removes the `module` field from each stack frame
Removing the `module` field improves grouping because for some reason, our stack trace processing pipeline isn't able to resolve the bundled module name to the original file name correctly, leading to a new issue group for the same error, every time the app is built. I suspect this is because of the unique Ids that Vite assigns to modules or due to something that sorcery does when flattening source maps. By removing `module` field the grouping algorithm falls back to the `filename` field, which is correctly resolved and hence grouping works as …
=> fix(sveltekit): Improve server-side grouping by removing stack frame module

packages/sveltekit/src/vite/sourceMaps.ts
Previously, a project build would crash when users didn't specify org, project slugs or auth tokens. This PR fixes that by catching the error and providing additional information to the Sentry CLI error message. 
ref #7669
=> fix(sveltekit): Don't crash build when CLI credentials are missing

packages/core/src/utils/prepareEvent.ts
Cache processed debug ID stack frames so we don't have to recompute them every error event.
=> feat(core): Cache processed stacks for debug IDs

packages/gatsby/gatsby-node.js
Our Gatsby SDK ships with the webpack plugin to automatically upload source maps (TIL).
When building for production, the webpack causes a crash if no auth token is specified. We decided that builds shouldn't crash because of a misconfiguration of our plugin, so this PR fixes that (see #7427 and #7846). Instead, we'll log a warning in this case.
Note: I opted to not log a warning if ORG or PROJECT were not specified because in this case one could argue that users don't want to upload at all. This is identical to the previous behaviour. Happy to change that though, if reviewers think we should notify users anyway.
closes #7852
=> fix(gatsby): Don't crash build when auth token is missing

packages/nextjs/src/config/loaders/types.ts, packages/nextjs/src/config/loaders/valueInjectionLoader.ts, packages/nextjs/src/config/webpack.ts
Attempting to adress https://github.com/getsentry/sentry-javascript/issues/5734
Tested with Vercel CLI. Not sure if it works for auto deploys yet. Let's see.
=> fix(nextjs): Mark value injection loader result as uncacheable

CHANGELOG.md
Without this, errors slip past any app error handling and directly crash the process.
=> chore: Fix bug in changelog about `runWithAsyncContext`

packages/sveltekit/package.json, packages/sveltekit/rollup.npm.config.js, rollup/plugins/bundlePlugins.js, yarn.lock
This PR bumps rollup from 2.6 to 3.2 - for now just in the SvelteKit SDK. We need this to dynamically import users' `svelte.config.js` files at build time. More specifically, rollup 3 introduces [`output.dynamicImportsInCjs`](https://rollupjs.org/configuration-options/#output-dynamicimportincjs) which stops rollup from converting dynamic `import` statements to dynamic (async) `require` calls. 
ESM and CJS... Just gotta love it.
We can think about updating rollup in the other packages as well but the change is ofc riskier and will probably require a lot more changes. 
sort of ref #7669
=> build(sveltekit): Upgrade to Rollup 3

packages/sveltekit/src/vite/sentryVitePlugins.ts, packages/sveltekit/src/vite/sourceMaps.ts, packages/sveltekit/src/vite/svelteConfig.ts, packages/sveltekit/test/vite/sentrySvelteKitPlugins.test.ts, packages/sveltekit/test/vite/sourceMaps.test.ts, packages/sveltekit/test/vite/svelteConfig.test.ts
Needs #7862 
With this PR, our source maps upload plugin is able to read `svelte.config.js`. This is necessary to automatically find the output directory that users can specify when setting up the Node adapter. 
This is a "little" hacky though, because we can't just access the output dir variable. Instead, we actually invoke the adapter (which we can access) and pass a minimal, mostly no-op adapter builder, which will report back the output directory. 
(I'm sure this is gonna backfire some day but let's just do it anyway lol)
the good news:
closes #7669
=> feat(sveltekit): Read adapter output directory from `svelte.config.js`

packages/angular/src/tracing.ts, packages/core/src/tracing/idletransaction.ts, packages/core/src/tracing/span.ts, packages/ember/addon/index.ts, packages/ember/addon/instance-initializers/sentry-performance.ts, packages/react/src/profiler.tsx, packages/tracing-internal/src/browser/router.ts
Fixes a bug introduced in https://github.com/getsentry/sentry-javascript/pull/7632 due to assuming `timestampWithMs` returns a timestamp in ms (which it does not do). 
Also replaces all usage of `timestampWithMs` with `timestampInSeconds`.
Let's deprecate `timestampWithMs` in a follow up PR.
=> fix(tracing): Ensure we use `s` instead of `ms` for startTimestamp

MIGRATION.md, packages/utils/src/time.ts
Depends on https://github.com/getsentry/sentry-javascript/pull/7877 being merged first.
=> ref(deprecate): Deprecate `timestampWithMs`

packages/sveltekit/src/vite/sourceMaps.ts
When setting up the SDK with the wizard (once that's shipped), a `sentry.properties` file will be created with org and project slug information. To pick this up without any additional user config of the Vite plugin, we need to point the plugin to this file. This PR fixes this "missing" behaviour.
(Note: This change can be merged regardless of the wizard state IMO)
sort of ref: https://github.com/getsentry/sentry-wizard/issues/244
=> fix(sveltekit): Use `sentry.properties` file when uploading source maps

.github/workflows/label-last-commenter.yml
We talked about this a bit recently, so I took a quick stab into implementing this. This adds a label `Status: User responded' when a user comments, and removes it when a member responds. In theory, we should be able to use this label to find issues where we forgot to answer.
=> ci: Tag issues if last commenter is user

packages/browser/src/stack-parsers.ts
While working on fixing a stack parser bug I noticed that `[-a-z]+` will match any valid protocol so there is no need to match specific protocols.
This will shave around 120 bytes off the browser bundle.
=> feat(browser): Simplify stack parsers

packages/gatsby/.eslintrc.js, packages/gatsby/gatsby-browser.js, packages/gatsby/jest.config.js, packages/gatsby/package.json, packages/gatsby/test/integration.test.tsx, packages/gatsby/tsconfig.test.json
It seems that due to the `require` usage there, treeshaking is not working as expected. Just replacing this with using esm `import` seems to resolve this. I tried this in sentry-docs and a reproduction app and it seemed good to me.
Fixes https://github.com/getsentry/sentry-javascript/issues/7853
=> fix(gatsby): Use `import` for `gatsby-browser.js` instead of `require`

packages/nextjs/src/config/webpack.ts, packages/nextjs/test/config/webpack/sentryWebpackPlugin.test.ts
Because we're now using Next.js source map resolving server for dev mode we don't need to run the webpack plugin at all in dev mode to get resolved stack traces.
If the plugin isn't silenced in the options it is extremely noisy in dev mode without doing anything. This PR fixes that.
=> ref(nextjs): Don't use Sentry Webpack Plugin in dev mode

.github/workflows/build.yml
https://nodejs.org/en/blog/announcements/v20-release-announce
From reviewing the CHANGELOG (https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V20.md), there seems to be no changes that will affect us in the code.
See v19 CHANGELOG: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V19.md
Notable things we can maybe pursue:
- Tracing Channel in `diagnostic_channel` API https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V19.md#tracing-channel-in-diagnostic_channel
- Add context about permissions: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#permission-model
- ESM loader hooks
PR to add node 18 to SDK Ci: https://github.com/getsentry/sentry-javascript/pull/5049
=> chore(ci): Add Node 20 to the test matrix

packages/browser/src/stack-parsers.ts, packages/browser/test/unit/tracekit/chromium.test.ts
=> fix(nextjs): Handle braces in stack frame URLs

packages/sveltekit/README.md
Just a small PR to be more explicit in terms of files and file locations where users need to configure the SDK.
=> docs(sveltekit): Improve setup instructions

packages/sveltekit/src/vite/sourceMaps.ts
In a SvelteKit production build, an error was thrown if the sentry-cli wasn't able to detect a release (for instance because the project is not in a git repo). This PR fixes this by detecting a release value before creating the plugin. The detection mechanism is identical to the mechanism in the NextJS SDK, with the exception of the fallback:
* Try to detect a git commit hash. If this fails,
* return a generated UUID
In NextJS, we just fall back to Next's internal build id. SvelteKit doesn't have such an Id, which is why ultimately, we just generate a UUID instead. However, I'd argue we want to first attempt detecting a commit hash as it is less random and  the Sentry CLI does it as well.
=> fix(sveltekit): Detect sentry release before creating the Vite plugin

packages/sveltekit/src/server/handleError.ts, packages/sveltekit/test/server/handleError.test.ts
Incoming page load requests on the server side for unknown/invalid routes will throw a `Error: Not found: /unknown/route` error in the server `handleError` hook. In our wrapper, we don't want to catch these errors (similarly to 404 errors in the `wrapLoadWithSentry` wrapper).
=> fix(sveltekit): Avoid capturing "Not Found" errors in server `handleError` wrapper

packages/node/test/checkin.test.ts, packages/types/src/checkin.ts
See: https://develop.sentry.dev/sdk/check-ins/#schedule-configuration
ref: https://github.com/getsentry/sentry/issues/43661, https://github.com/getsentry/sentry-javascript/pull/7777
Add types for monitor upsert, and adjust tests accordingly.
Again we're not exposing these APIs, just having the types around so we can add it whenever.
=> feat(node): Add monitor upsert types

packages/replay/src/coreHandlers/util/addBreadcrumbEvent.ts
After some in-depth debugging, I figured out that the replay may lock up if we do not normalize the scope breadcrumbs to a given depth.
This seems to fix the provided reproduction for me, and seems like a reasonable change overall.
10 is more or less a random value, but seems reasonable for me for this case? 
it gets slower and slower with an increasing value there, becoming basically unusable around ~18-20.
I did some further digging, and the problem is that around a normalization of 20, it becomes crazy large:
```js
console.log(JSON.stringify(normalize(breadcrumb, 20)));
```
results in a 60MB string 🤯 
This is a simple first step to ensure we normalize _all_ breadcrumbs to a max. depth. This applies to scope & dom breadcrumbs from Sentry itself.
This is not really a _fix_ per se, as it …
=> fix(replay): Ensure we normalize scope breadcrumbs to max. depth to avoid circular ref

packages/browser-integration-tests/suites/public-api/setContext/non_serializable_context/test.ts, packages/utils/src/normalize.ts, packages/utils/test/normalize.test.ts
Currently, we do not special-case html elements in normalization. This means they are still normalized as objects, leading to potentially deeply nested stuff, and to problems with e.g. replay. IMHO it is more expected to see a string representation of this element instead.
Ref https://github.com/getsentry/team-replay/issues/67
=> fix(utils): Normalize HTML elements as string

.github/workflows/label-last-commenter.yml
Noticed some improvements for this action:
* Add a proper name
* We do not need to run checkout, I believe, which should make this slightly faster too.
=> ci: Improve last commenter action

packages/replay/src/coreHandlers/util/networkUtils.ts, packages/replay/test/unit/coreHandlers/util/networkUtils.test.ts
This also incorporates feedback from @Lms24 to properly handle the case when we both fail to parse JSON AND still truncate the body.
=> fix(replay): Ensure we still truncate large bodies if they are failed JSON

packages/sveltekit/README.md
After 7.49.0 we can go beta IMO
=> docs(sveltekit): Promote the SDK to beta state

packages/nextjs/src/config/types.ts, packages/nextjs/src/config/webpack.ts, packages/nextjs/test/config/fixtures.ts
This is just adding a very convenient way of treeshaking the logger we can put into docs snippets and the wizard.
=> feat(nextjs): Add `disableLogger` option that automatically tree shakes logger statements

packages/browser-integration-tests/suites/replay/dsc/init.js, packages/browser-integration-tests/suites/replay/dsc/test.ts, packages/replay/src/util/addGlobalListeners.ts
I noticed that we are actually setting the replayId on the DSC even if the replay has stopped. IMHO this doesn't make a lot of sense, so I added this guard.
=> fix(replay): Ensure we do not set replayId on dsc if replay is disabled

packages/browser-integration-tests/suites/replay/bufferMode/test.ts, packages/replay/src/replay.ts, packages/replay/src/session/Session.ts, packages/replay/src/session/getSession.ts, packages/replay/src/types.ts, packages/replay/test/integration/errorSampleRate.test.ts, packages/replay/test/unit/session/fetchSession.test.ts, packages/replay/test/unit/session/getSession.test.ts
This adjusts the PR to handle buffered sessions that expire.
Basically, a buffered session should be sampled normally unless it has been converted from a buffered -> session. Only when an error was captured and the session _then_ expires, we do not want to start a new session.
This fixes https://github.com/getsentry/sentry-javascript/pull/7768
=> fix: Do refresh buffered sessions

packages/replay/src/coreHandlers/handleAfterSendEvent.ts, packages/replay/src/integration.ts, packages/replay/src/replay.ts, packages/replay/src/types.ts, packages/replay/test/integration/errorSampleRate.test.ts
This changes the public API: `flush` to:
* in session-mode, call debounced flush instead of flushing immediately
* in non-session mode, record the current event buffer and by default, convert the replay type to "session" and continue recording.
Essentially, we have extracted the same logic that was used for "onError" capturing and made it a public API.
Closes #7737
=> feat(replay): Change `flush()` API to record current event buffer

.github/workflows/gitflow-sync-develop.yml, packages/core/src/index.ts, packages/core/src/transports/multiplexed.ts, packages/core/test/lib/transports/multiplexed.test.ts
Closes #5185
Adds `makeMultiplexedTransport` which can be used to create a Transport that sends envelopes to different, even multiple DSNs depending on the content of the envelope. 
It takes two parameters:
- A transport creation function that is used to create transports when required
- A match callback with the following type:
```ts
interface MatchParam {
// The envelope to be sent
envelope: Envelope;
// A function that returns an event from the envelope if one exists
getEvent(): Event | undefined;
}
type Matcher = (param: MatchParam) => string[];
```
Currently, the DSN passed to init is used as a fallback if the match callback returns zero DSNs. I'm not 100% happy with this as in the example below, the DSN passed to init will never be used but is required for the client to send events. …
=> feat(core): Add multiplexed transport

.github/workflows/label-last-commenter.yml
Not sure where I got the `closed` stuff from, but this seems to be actually correct based on https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#issues.
Noticed this was incorrectly running for closed issues as well.
=> ci: Fix issue state check

packages/utils/src/normalize.ts
Noticed that one comment was copy-pasted but not changed 😅 So removed it and slightly refactored it to avoid re-assigning the variable. Also renamed the variable as I found it a bit confusing (it is not always overridden!), while at it.
=> ref(utils): Fix comment for normalize

packages/utils/src/normalize.ts, packages/utils/test/normalize.test.ts
This is to avoid infinite recursion that we cannot detect, e.g. when using dynamic proxies.
Fixes https://github.com/getsentry/sentry-javascript/issues/7947 (hopefully).
=> fix(utils): default `normalize()` to a max. of 100 levels deep instead of Inifnity

packages/browser-integration-tests/suites/replay/sessionExpiry/init.js, packages/browser-integration-tests/suites/replay/sessionInactive/init.js, packages/browser-integration-tests/suites/replay/sessionInactive/test.ts, packages/browser-integration-tests/suites/replay/sessionMaxAge/init.js, packages/replay/src/constants.ts, packages/replay/src/replay.ts, packages/replay/src/types.ts, packages/replay/src/util/addEvent.ts, packages/replay/src/util/isSessionExpired.ts, packages/replay/test/integration/errorSampleRate.test.ts, packages/replay/test/integration/session.test.ts, packages/replay/test/unit/session/getSession.test.ts, packages/replay/test/unit/util/isSessionExpired.test.ts
Now, a session will only expire & trigger a new session if no user activity happened for 15min. 
After 5min of inactivity, we will pause recording events. If the user resumes in the next 10 minutes, we'll resume the session, else re-create it if they resume later.
Closes https://github.com/getsentry/sentry-javascript/issues/7942
=> feat(replay): Extend session idle time until expire to 15min

packages/core/src/transports/multiplexed.ts, packages/core/test/lib/transports/multiplexed.test.ts
By default, we only multiplex errors, but allow to opt-in to more envelope types.
After talking about this with @AbhiPrasad , this is actually the default we want to provide (for now).
=> ref(core): Update multiplexed transport to default to errors only

packages/nextjs/src/server/index.ts, packages/nextjs/test/serverSdk.test.ts, packages/node/src/sdk.ts, packages/sveltekit/src/server/sdk.ts, packages/sveltekit/test/server/sdk.test.ts
It's been default in Next.js and Sveltekit for a while now, let's make it a default for Node especially since Node 20 is released.
=> feat(node): Make Undici a default integration.

packages/sveltekit/README.md
We have to revert this unfortunately because of #7951. Once this is in, we can revert the revert 😅
=> Revert "doc(sveltekit): Promote the SDK to beta state (#7874)"

.github/workflows/build.yml, packages/browser-integration-tests/suites/replay/dsc/test.ts
Also one test was actually incorrect.
Also extending browser integration test max. time a bit as I had a few times where we exceeded 15min, sadly.
=> test: Fix flaky replay DSC test

packages/sveltekit/README.md
Now that #7975 is merged, we actually can go beta
=> doc(sveltekit): Promote the SDK to beta state (again)

packages/replay/src/eventBuffer/EventBufferArray.ts, packages/replay/src/eventBuffer/EventBufferCompressionWorker.ts, packages/replay/src/eventBuffer/EventBufferProxy.ts, packages/replay/src/types.ts, packages/replay/src/util/addEvent.ts, packages/replay/test/unit/eventBuffer/EventBufferArray.test.ts, packages/replay/test/unit/eventBuffer/EventBufferCompressionWorker.test.ts
This too is a partial extraction of https://github.com/getsentry/sentry-javascript/pull/7025, to prepare for this & break this up in multiple parts.
This will make it easier in a follow up step to handle clearing a bit different when in buffer mode, to keep more data in store.
=> ref(replay): Explicitly clear eventBuffer for checkout events

packages/tracing-internal/src/browser/request.ts, packages/tracing-internal/test/browser/request.test.ts
Following https://develop.sentry.dev/sdk/performance/span-data-conventions/, set `http.method` instead of `method` for http spans generated by fetch/xhr.
ref https://github.com/getsentry/team-webplatform-meta/issues/60
=> feat(tracing): Use `http.method` for span data

packages/browser/src/index.ts
ref https://github.com/getsentry/sentry-javascript/pull/7926
This is meant to be used in the browser, so let's export this here!
Exporting this from `index.ts` instead of `exports.ts` because we don't want this in the CDN bundles.
=> feat(browser): Export makeMultiplexedTransport from browser SDK

packages/browser-integration-tests/suites/replay/bufferMode/test.ts
This failed on CI, so making this a bit more lenient...
=> test(replay): Unflake test

packages/node/src/integrations/http.ts, packages/node/src/integrations/undici/index.ts, packages/node/test/integrations/http.test.ts, packages/node/test/integrations/undici.test.ts, packages/sveltekit/src/client/load.ts, packages/sveltekit/src/server/load.ts, packages/sveltekit/test/client/load.test.ts, packages/sveltekit/test/server/load.test.ts, packages/types/src/request.ts
See: https://github.com/getsentry/sentry-javascript/pull/7990
Following https://develop.sentry.dev/sdk/performance/span-data-conventions/, set http.method instead of method for http spans generated by http/undici integrations.
ref https://github.com/getsentry/team-webplatform-meta/issues/60
=> feat(node): Add `http.method` to node http spans

packages/browser-integration-tests/suites/replay/dsc/init.js, packages/browser-integration-tests/suites/replay/dsc/test.ts, packages/replay/src/util/addGlobalListeners.ts
We only want to add the replay_id to the DSC when the session is in `session` mode, as while buffering the replay may not even be sent.
Closes https://github.com/getsentry/sentry-javascript/issues/8013
=> fix(replay): Do not add replay_id to DSC while buffering

packages/remix/src/index.types.ts
This PR changes the isomorphic type declarations of `Sentry.Integrations` to a union type rather than an object. This stops `tsc` from resolving the types of the individual integration types which caused errors due to incorrect path resolvings of dependencies of `@sentry/remix`. With this change we now declare `Sentry.Integrations` in Remix identically to how we do it in NextJS and SvelteKit.
<details><summary>Details</summary>
<p>
Here's the incorrect TSC output from 7.45 to 7.50 (after #7575 was merged)
```typescript
export * from './index.client';
export * from './index.server';
import type { Integration, StackParser } from '@sentry/types';
import * as clientSdk from './index.client';
import type { RemixOptions } from './utils/remixOptions';
/** Initializes Sentry Remix SDK */
export …
```
=> fix(remix): Export `Integrations` type declaration as union type

.prettierignore, packages/browser-integration-tests/.eslintrc.js, packages/browser-integration-tests/.gitignore, packages/browser-integration-tests/.prettierignore, packages/browser-integration-tests/loader-suites/loader/noOnLoad/sdkLoadedInMeanwhile/test.ts, packages/browser-integration-tests/package.json, packages/browser-integration-tests/playwright.config.ts, packages/browser-integration-tests/playwright.setup.ts, packages/browser-integration-tests/utils/fixtures.ts, packages/browser-integration-tests/utils/generatePage.ts, packages/browser-integration-tests/utils/generatePlugin.ts, packages/browser-integration-tests/utils/staticAssets.ts
While working on https://github.com/getsentry/sentry-javascript/pull/8024, I noticed that bundle tests were failing, because we couldn't really run the playwright tests in bundle mode when serving the app on a URL instead via `file://`. This is because of the way we reference bundle files, which have been referenced as e.g. `<script src="/Users/francesco/git/sentry-javascript/packages/browser/build/bundle.min.js">`. This doesn't play well with serving from a URL like `https://sentry-test.io/cdn.bundle.js`.
In order to make this work and streamline this, I refactored this to instead keep a `tmp/static` folder for all of the integration tests, where we can cache static files that are the same for all test runs (e.g. cdn.bundle.js, the integrations or loader.js). Where possible, we make …
=> test: Refactor playwright bundle generation

packages/angular-ivy/package.json, packages/angular/package.json
With the official release on Angular 16, and no notable changes to how Sentry should work within this new version we can safely update the peerDependencies to include Angular 16.
=> chore(angular): Upgrade `peerDependencies` to Angular 16

packages/angular-ivy/README.md, packages/angular/README.md
With the release of Angular 16, `ngcc` was finally removed from the framework which means that our `@sentry/angular` package is no longer compatible with this and future versions. Therefore, this PR updates the Readme to point people towards `@sentry/angular-ivy`. 
Peer dep bump is happening in #8035 
IMO there's no docs change necessary, as the [current Angular docs](https://docs.sentry.io/platforms/javascript/guides/angular/) already recommend Ivy for NG12 and newer.
I tested our SDK (Ivy) with Angular 16 and everything seems to be working as expected, including route parameterization and the various component tracking features. Meaning these two PRs should be enough to support Angular 16 🚀
=> chore(angular): Clarify `@sentry/angular` and `@sentry/angular-ivy` version compatibility

packages/sveltekit/package.json, packages/sveltekit/src/server/utils.ts, packages/sveltekit/src/vite/autoInstrument.ts, packages/sveltekit/src/vite/sentryVitePlugins.ts, packages/sveltekit/src/vite/sourceMaps.ts, packages/sveltekit/test/vite/autoInstrument.test.ts, packages/sveltekit/test/vite/sentrySvelteKitPlugins.test.ts, packages/sveltekit/test/vite/sourceMaps.test.ts
Finally something somewhat robust (at least more than modifying the AST):
This PR introduces auto-wrapping of `load` functions in 
* `+(page|layout).(ts|js)` files (universal loads)
* `+(page|layout).server.(ts|js)` files (server-only loads)
API wise, this is not a breaking change for users, as internally, we just add an additional plugin which is returned by the `sentrySvelteKit` plugin factory function. However, users can add new options to the factory functions, to control auto-wrapping:
```js
sentrySvelteKit({
autoInstrument: true, // false to disable entirely
// or
autoInstrument: {
load: true,
serverLoad: false,
},
// other options...
autoUploadSourceMaps: false,
debug: true,
})
```
(Almost) everything auto-wrapping related happens in a new plugin.
The plugin works by returning …
=> feat(sveltekit): Auto-wrap `load` functions with proxy module

packages/node/src/checkin.ts, packages/node/src/client.ts, packages/node/src/index.ts, packages/node/src/sdk.ts, packages/node/test/checkin.test.ts, packages/node/test/client.test.ts, packages/types/src/checkin.ts, packages/types/src/envelope.ts, packages/types/src/index.ts
Closes https://github.com/getsentry/sentry-javascript/issues/8006
Based on the work in https://github.com/getsentry/sentry-javascript/pull/7996, we expose a top level API to send check ins to Sentry. Currently there is no hub level method to do this, that was done intentionally.
To send a check in to Sentry, simply use the `captureCheckIn` method exported from the SDK. First you must send an `in_progress`, checkin, then you can send one with status `ok` or `error` based on what happened with your cron job.
```ts
const Sentry = require('@sentry/node');
// ...
Sentry.captureCheckIn({
// make sure this is the same slug as what you set up your
// Sentry cron monitor with.
monitorSlug: 'dailyEmail',
status: 'in_progress',
});
const startTime = timeInSeconds();
runTask(); …
```
=> feat(node): Add ability to send cron monitor check ins

packages/replay/src/replay.ts
This ensures the session remains active when a user presses a key.
This is a minimal implementation for now. IMHO we should maybe look into capturing key presses for keyboard shortcuts, but we need to make sure to avoid capturing user input into text fields this way etc.
Related to https://github.com/getsentry/sentry-javascript/issues/6532
=> fix(replay): Keep session active on key press

packages/sveltekit/README.md
Update the readme to reflect the changes from #7994
=> doc(sveltekit): Update README with auto instrumentation configuration

packages/sveltekit/src/vite/autoInstrument.ts, packages/sveltekit/test/vite/autoInstrument.test.ts
- When `load` is explicitly typed (using `LayoutLoad`, `PageLoad`, etc.), auto-instrumentation fails.
- The SvelteKit docs suggest using the `satisfies` operator everywhere, but this is not strictly enforced. Prior to support for `satisfies` in TypeScript 4.9, the docs also suggested using explicit types, and were updated once support was more common. ([PR](https://github.com/sveltejs/kit/pull/7861))
- Update the [`hasLoadDeclaration` regex](https://github.com/getsentry/sentry-javascript/blob/2cc7708c0a3ab526716fc4998f59d2104e6f3be3/packages/sveltekit/src/vite/autoInstrument.ts#L101) introduced in #7994 to also check for cases when there is an explicit type.
- Simplified example of a `+layout.ts`file that would be skipped:
```ts
import type { LayoutLoad } from "./$types";
export const …
```
=> fix(sveltekit): Wrap `load` when typed explicitly

packages/replay/jest.setup.ts
Use `printDiffOrStringify()` util function from jest to generate a pretty diff of the received vs expected. Also when searching for *any* calls for `toHaveSentReplay`, stop at the first call where *any* of the keys have a successful match, instead of always falling through to the last call.
=> test(replay): Update jest custom matchers for replay to use differ

packages/replay/package.json, yarn.lock
- fix: Fix some input masking (esp for radio buttons) (getsentry/rrweb#85)
- fix: Unescaped `:` in CSS rule from Safari (getsentry/rrweb#86)
- feat: Define custom elements (web components) (getsentry/rrweb#87)
=> chore(replay): Upgrade `rrweb` to 1.108.0

packages/node/src/client.ts, packages/node/src/sdk.ts, packages/node/test/client.test.ts, packages/node/test/sdk.test.ts, packages/types/src/checkin.ts
Based on work in https://github.com/getsentry/sentry-javascript/pull/8039, this PR fixes a bug where we were adding a unique ID to every check in, which is incorrect behaviour. Instead we now return a `checkInId` every time a check in is captured, which can be used to link check ins together.
Example:
```ts
// 🟡 Notify Sentry your job is running:
const checkInId = Sentry.captureCheckIn({
monitorSlug: '<monitor-slug>',
status: 'in_progress',
});
// Execute your scheduled task here...
// 🟢 Notify Sentry your job has completed successfully:
Sentry.captureCheckIn({
checkInId,
monitorSlug: '<monitor-slug>',
status: 'ok',
});
```
=> fix(node): Make sure we use same ID for checkIns

packages/browser-integration-tests/suites/replay/customEvents/template.html, packages/browser-integration-tests/suites/replay/customEvents/test.ts, packages/replay/src/coreHandlers/handleDom.ts, packages/replay/test/unit/coreHandlers/handleDom.test.ts
This does two things:
1. When capturing clicks, we specifically look for button & a elements as parents, using them as target if applicable.
2. Increase max. text length of selectors, to have better visibility. Note we always cap this at 5 levels deep, still.
This is rather defensive for now, by only checking for button & a. This will not check for general interactivity - there are other cases to look for as well, e.g. `[tabindex]` etc. However, IMHO this has also potential to break, if people have weird HTML. So I think this should be a good enough start with very low potential for false positives.
Fixes https://github.com/getsentry/sentry-javascript/issues/7659
=> feat(replay): Improve click target detection

packages/sveltekit/src/vite/sentryVitePlugins.ts, packages/sveltekit/test/vite/sentrySvelteKitPlugins.test.ts
To upload source maps in SvelteKit, we create a custom plugin building on top of the Sentry Vite plugin, which creates a Sentry hub to collect telemetry. The problem is that in the current version of the Sentry Vite plugin, the hub is set as the current hub (`makeMain`) as soon as the plugin is created, causing tags from the plugin to leak to the user's Sentry projects in errors and transactions. 
This will be fixed in the new major of the vite plugin but we should nevertheless avoid this for now. Hence, this PR fixes this leakage by simply not creating the plugin when we're in dev mode.
=> fix(sveltekit): Avoid creating the Sentry Vite plugin in dev mode

packages/e2e-tests/test-applications/create-react-app/test-recipe.json
See: https://react.dev/community/versioning-policy
React is going to do more stuff in experimental/canary channels. Let's make sure the basics still work and build.
=> test(e2e): Add canary tests for react e2e tests

packages/nextjs/src/server/utils/wrapperUtils.ts, packages/nextjs/src/server/wrapAppGetInitialPropsWithSentry.ts, packages/nextjs/src/server/wrapErrorGetInitialPropsWithSentry.ts, packages/nextjs/src/server/wrapGetInitialPropsWithSentry.ts, packages/nextjs/src/server/wrapGetServerSidePropsWithSentry.ts, packages/nextjs/test/config/wrappers.test.ts
Probably fixes https://github.com/getsentry/sentry-javascript/issues/8025
Continues transactions on the hub in data fetchers instead of always creating a new one when there is none associated with the request object yet.
=> fix(nextjs): Continue traces in data fetchers when there is an already active transaction on the hub

packages/svelte/README.md, packages/sveltekit/README.md
This PR updates the SvelteKit readme:
* Remove beta note
* Add wizard instructions
* Add link to the docs
Also, we can redirect folks from the Svelte readme if they're using SvelteKit
=> chore(sveltekit): Update README (stable, wizard, links)

packages/core/src/integrations/inboundfilters.ts, packages/core/test/lib/integrations/inboundfilters.test.ts
This fixes a helper function used in our implementation of `ignoreErrors` so that in the case of linked errors, it filters on the primary error (the one directly caught by `captureException`) rather than the error in [its `cause` property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause). See https://github.com/getsentry/sentry-javascript/issues/8079 for screenshots and a more detailed explanation.
Fixes https://github.com/getsentry/sentry-javascript/issues/8079.
=> fix(core): Use last error for `ignoreErrors` check

rollup/plugins/bundlePlugins.js
We rely on the `_sentryDebugIds` field for debug ID injection. Unfortunately we mangle away all underscore-prefixed variables in minified bundles unless we disallow mangling for them. This PR fixes that.
=> fix(build): Don't mangle away global debug ID map

packages/browser/test/unit/sdk.test.ts, packages/core/src/exports.ts, packages/core/test/lib/sdk.test.ts
fixes https://github.com/getsentry/sentry-javascript/issues/8100
=> fix(core): Return checkin id from client

packages/tracing-internal/src/browser/request.ts, packages/tracing-internal/test/browser/request.test.ts
Bored at the airport (4h delay) lol 
To fix #8099, we need to adjust our `tracePropagationTargets` default regex to account for protocol-relative URLs. These were previously classified as same-origin, relative URLs, causing tracing headers to be attached which in turn potentially caused CORS errors for users. 
closes #8099
=> fix(tracing-internal): Avoid classifying protocol-relative URLs as same-origin urls

packages/node/src/integrations/http.ts
fixes https://github.com/getsentry/sentry-javascript/issues/8129
Adds an LRU Map so that we don't let the cached items grow infinitely.
Important to note that `shouldAttachTraceData` and `shouldCreateSpan` behaviour is basically identical now other than the map and executor used, but I didn't refactor further because I felt the abstraction is more confusing than just having this simple duplication.
=> fix(node): Add LRU map for tracePropagationTargets calculation

.github/workflows/build.yml, packages/serverless/package.json, packages/serverless/scripts/buildLambdaLayer.ts, packages/serverless/src/awslambda.ts, packages/serverless/tsconfig.json, scripts/aws-delete-local-layers.sh, scripts/aws-deploy-local-layer.sh
we're reverting back to the older setup since the whole 'relay as AWS extension' experiment didn't really work out.
* remove gh action that bundles relay
* remove port override in DSN
* zip in place as part of `buildLambdaLayer`
part of https://github.com/getsentry/team-webplatform-meta/issues/58
see python PR - https://github.com/getsentry/sentry-python/pull/2068
=> ref(serverless): Remove relay extension from AWS layer

packages/core/src/api.ts, packages/core/src/baseclient.ts, packages/core/src/transports/multiplexed.ts, packages/core/test/lib/api.test.ts, packages/core/test/lib/base.test.ts, packages/core/test/lib/transports/multiplexed.test.ts, packages/core/test/lib/transports/offline.test.ts, packages/nextjs/src/client/tunnelRoute.ts, packages/nextjs/test/utils/tunnelRoute.test.ts, packages/node/test/transports/http.test.ts, packages/replay/test/unit/util/createReplayEnvelope.test.ts, packages/utils/src/dsn.ts, packages/utils/test/dsn.test.ts
As discussed, we don't want to hard-throw if the SDK gets an invalid DSN. This PR fixes that by allowing `makeDsn` and `dsnFromString` to return `undefined`, which we do if the Dsn is invalid. This is a breaking change for the utils package but since it's utils we're fine with that. 
(The alternative, try-catching the respective function calls didn't seem much nicer to me, especially considering that we rarely use throwing and try/catching for control flow in the SDK).  
This required changes in more places, since we don't only work with raw DSNs in the BaseClient but also in 
- NextJS for the `tunnelRoute` option
- `makeMultiplexedTransport` where I opted to resort to the fallback URL if an invalid URL is returned by the user matcher 
closes #8110
=> fix(utils): Fail silently if the provided Dsn is invalid

packages/sveltekit/src/client/load.ts, packages/sveltekit/src/common/utils.ts, packages/sveltekit/src/server/load.ts, packages/sveltekit/test/client/load.test.ts, packages/sveltekit/test/server/load.test.ts
As mentioned in the discussion in https://github.com/getsentry/sentry-javascript/pull/8083/files#r1188707540, applying the `wrap(server)?LoadWithSentry` wrappers multiple times shouldn't lead to double wrapping but instead we should detect if we already wrapped a load function and no-op in this case. This PR patches the respective load events with a flag to detect double wrapping. 
Double wrapping can occur, for instance, if users already applied the load wrapper function to their code but also use auto-wrapping. With this change, we'll still apply the wrapper twice but the second wrapper will simply no-op.
Once this is merged, we can adjust the `canWrapLoad` auto-instrumentation check to no longer bail out of auto-wrapping if Sentry code was detected.
=> fix(sveltekit): Avoid double-wrapping load functions

packages/tracing-internal/src/browser/request.ts
Response content length can't be added upon span creation since the response doesn't exist yet, this should add content-length on the subsequent call to the handler after the fetch/xhr has finished.
@narsaynorath this might need test changes, if you can carry it forward 🙏
=> fix(tracing): Change where content-length gets added

CHANGELOG.md, packages/replay/src/integration.ts, packages/replay/src/types.ts, packages/replay/src/util/addEvent.ts, packages/replay/test/integration/beforeAddRecordingEvent.test.ts
Allows you to modify/filter custom recording events for replays. Note this is only a recording event, not the replay event. Custom means that the events do not relate or affect the DOM recording, but rather they are additional events that the Replay integration adds for additional features.
This adds an option for the Replay integration `beforeAddRecordingEvent` to process a recording (rrweb) event before it is added to the event buffer. Example:
```javascript
new Sentry.Replay({
beforeAddRecordingEvent: (event) => {
// Filter out specific events
if (event.data.tag === 'foo') {
return null;
}
// Remember to return an event if you want to keep it!
return event;
}
});
```
Closes https://github.com/getsentry/sentry-javascript/issues/8127
=> feat(replay): Add `beforeAddRecordingEvent` Replay option

packages/nextjs/src/config/loaders/wrappingLoader.ts
=> fix(nextjs): Guard for non-absolute paths when injecting sentry config

packages/nextjs/test/integration/test/server/utils/helpers.ts
Honestly, I don't even know what or how we're fixing a problem with the tests here but we know wehere it came from: https://github.com/vercel/next.js/pull/49805
=> test(nextjs): Unbreak Next.js integration tests

packages/nextjs/src/client/index.ts, packages/nextjs/src/edge/index.ts, packages/nextjs/src/index.types.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/5511
=> fix(nextjs): Make `withSentryConfig` isomorphic

packages/svelte/package.json, yarn.lock
context:  https://github.com/getsentry/sentry-javascript/issues/6692#issuecomment-1557160000
=> chore(svelte): Bump magic-string to 0.30.0

packages/node/src/integrations/context.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/8202
=> fix(node): Catch `os.uptime()` throwing because of EPERM

packages/sveltekit/package.json, packages/sveltekit/src/vite/autoInstrument.ts, packages/sveltekit/test/vite/autoInstrument.test.ts, yarn.lock
This PR improves the `canWrapLoad` check for our `load` auto-instrumentation. Previously, we used a few regexes to strip comments and match certain syntax for auto-wrapping. This proved to be quite brittle and we had to fix some cases (https://github.com/getsentry/sentry-javascript/pull/8049). I just found another case that wasn't handled correctly before so I decided to switch to parsing the module and walking the AST. For this application, IMO AST walking is safer than some brittle regex check, so I vote we go with this approach.
I chose MagicAST despite the fact that we only inspect the AST and don't modify it because:
- we already use it in the wizard and we might want/need to port this functionality over 
- it uses `recast` and babel under the hood which I would have chosen as an …
=> ref(sveltekit): Improve auto-instrumentation applicability check

packages/sveltekit/src/common/utils.ts, packages/sveltekit/src/server/handle.ts, packages/sveltekit/src/server/load.ts, packages/sveltekit/test/common/utils.test.ts, packages/sveltekit/test/server/handle.test.ts
This PR stops sending thrown redirects (which is how you redirect to another route in SvelteKit on the server side) and 4xx Http errors to Sentry. This change is identical to #7731 which introduced these filters to `load` functions. Back then we missed that the same errors can also be thrown in request handlers.
fixes #8214
=> fix(sveltekit): Avoid capturing redirects and 4xx Http errors in request Handlers

packages/replay/src/coreHandlers/handleKeyboardEvent.ts
`key` _should_ always be there, but let's guard against this as it seems it may be undefined.
Fixes https://github.com/getsentry/sentry-javascript/issues/8237
=> fix(replay): Guard against missing key

.github/workflows/canary.yml
1. Do not create an issue when manually running canary tests
2. Update existing issue instead of creating a new one every time
3. Update issue name so we see which canary test is failing
=> ci: Improve canary issue creation

packages/browser-integration-tests/suites/replay/sessionExpiry/test.ts, packages/browser-integration-tests/suites/replay/slowClick/mutation/test.ts
These tests seem to only flake on firefox?
=> test(replay): Skip firefox for flakey tests

packages/tracing-internal/src/node/integrations/express.ts
Fixes #6586 by adding a call to `stripUrlQueryAndFragment()` according to the discussion here https://github.com/getsentry/sentry-javascript/issues/6586#issuecomment-1557485816
=> fix(express): Strip query and fragment from tracing URLs (#6586)

packages/replay/src/replay.ts, packages/replay/src/types.ts, packages/replay/src/util/addGlobalListeners.ts
This is a draft of capturing the current parametrized route for Replay. We'll want to have that for slow click capturing, but maybe also at other places... this is only available when performance is used.
Feel free to adjust/merge/close this when needed.
=> ref(replay): Capture parametrized route

packages/sveltekit/.eslintrc.js, packages/sveltekit/src/server/utils.ts, packages/sveltekit/src/vite/injectGlobalValues.ts, packages/sveltekit/src/vite/sentryVitePlugins.ts, packages/sveltekit/src/vite/sourceMaps.ts, packages/sveltekit/src/vite/svelteConfig.ts, packages/sveltekit/test/server/utils.test.ts, packages/sveltekit/test/vite/injectGlobalValues.test.ts, packages/sveltekit/test/vite/sentrySvelteKitPlugins.test.ts, packages/sveltekit/test/vite/sourceMaps.test.ts, packages/sveltekit/test/vite/svelteConfig.test.ts
This PR adjusts our automatic source maps upload setup in the SvelteKit SDK to support SvelteKit apps deployed to Vercel. This will only work for Lambda functions/Node runtime; not for the Vercel Edge runtime. 
This required a few changes in our custom vite plugin as well as on the server side of the SDK:
* Based on the used adapter (manually set or detected via #8193) and the `svelte.config.js` we determine the output directory where the generated JS emitted to. 
* The determined output directory is injected into the global object on the server side
* When an error occurs on the server side, we strip the absolute filename of each stack frame so that the relative path of the server-side code within the output directory is left.
* We also use the determined output directory to build the …
=> feat(sveltekit): Add source maps support for Vercel (lambda)

packages/core/src/integrations/inboundfilters.ts, packages/core/test/lib/integrations/inboundfilters.test.ts, packages/nextjs/test/integration/test/client/tracingPageLoad.test.ts
Default ignore health check Transactions.
Ref: https://github.com/getsentry/team-webplatform-meta/issues/70
=> feat(core): Add default ignoreTransactions for Healthchecks

packages/replay/src/coreHandlers/handleKeyboardEvent.ts, packages/replay/src/replay.ts, packages/replay/src/types.ts
This is causing some low-value replays. If you search sentry for replays with duration < 5 seconds, you will see that most of them are re-newed sessions from idle that only have a "keydown" breadcrumb. I suspect users are alt-tabbing out of an idle Sentry page. Removing for now until we have a better way to detect when a session is truly resumed via keydown event.
=> feat(replay): Do not restart replays on "keydown"

packages/nextjs/src/client/performance.ts, packages/nextjs/test/performance/client.test.ts
It seems that the NextJS SDK is sometimes sending query parameters in transaction names as discovered by @jjbayer. This PR fixes a possible scenario in which this could happen, namely a navigation to an unknown route. While I can show the regression with a unit test, I'm not sure if this scenario could happen in an actual application. 
Internal conversation: https://sentry.slack.com/archives/C28MX5WAJ/p1685689501514019
=> fix(nextjs): Strip query params from transaction names of navigations to unknown routes

packages/sveltekit/README.md
Update the readme now that we're compatible with more adapters than just the Node adapter.
'+ some additional cleanup
ref #8085
=> chore(sveltekit): Update adapter compatibility in Readme

packages/replay/src/coreHandlers/handleScope.ts, packages/replay/src/coreHandlers/handleSlowClick.ts, packages/replay/src/index.ts, packages/replay/src/replay.ts, packages/replay/src/types/index.ts, packages/replay/src/types/performance.ts, packages/replay/src/types/replay.ts, packages/replay/src/types/replayFrame.ts, packages/replay/src/util/addEvent.ts, packages/replay/src/util/createBreadcrumb.ts, packages/replay/src/util/handleRecordingEmit.ts, packages/replay/test/integration/beforeAddRecordingEvent.test.ts, packages/replay/test/integration/coreHandlers/handleScope.test.ts, packages/replay/test/unit/coreHandlers/handleScope.test.ts, packages/replay/test/unit/util/handleRecordingEmit.test.ts
More specific types for our replay recording events. These are exported so that our UI can use them as well.
=> feat(replay): Improve types for replay recording events

packages/svelte/package.json
Svelte 4 [preview builds](https://www.npmjs.com/package/svelte/v/4.0.0-next.0) are out. I tested `4.0.0-next.0` with a standalone Svelte SPA (without Kit) and the SDK still works, including our component tracking feature. 
I think it's safe to add Svelte 4 as a valid peer dependency for this package.
Note, this doesn't yet address compatibility of Svelte 4 with the SvelteKit SDK. 
(feel free to take over/merge this PR at any time)
=> ref(svelte): Add Svelte 4 as a peer dependency

packages/e2e-tests/lib/runAllTestApps.ts
Due to some concurrency issue in our E2E tests the canary tests are consistently failing. This PR will make the canary tests (hopefully temporarily) non-concurrent so that the canary tests become useful again.
=> test(e2e): Disable concurrent tests for canary tests

packages/replay/src/replay.ts, packages/replay/src/session/getSession.ts, packages/replay/src/util/handleRecordingEmit.ts, packages/replay/test/integration/errorSampleRate-delayFlush.test.ts, packages/replay/test/integration/errorSampleRate.test.ts, packages/replay/test/unit/session/getSession.test.ts
Theres an edge case where a buffered session becomes expired, an error comes in, the link from error to replay is lost because a new session is created due to the session being expired.
We should either ignore the max session life for a buffered session, or possibly check/refresh session when an error comes in.
=> fix(replay): Ignore max session life for buffered sessions

packages/replay/src/index.ts, packages/replay/test/integration/beforeAddRecordingEvent.test.ts
This breaks, as we do not have these packages as dependencies but devDependencies, but the types are not inlined...
This was introduced here: https://github.com/getsentry/sentry-javascript/pull/8284
Fixes https://github.com/getsentry/sentry-javascript/issues/8326
=> fix(replay): Do not export types from `@sentry-internal/rrweb`

packages/serverless/src/index.ts
Export `captureCheckIn` from `@sentry/serverless` so it can be used from there.
=> fix(serverless): Export captureCheckIn

packages/remix/test/integration/package.json, packages/remix/test/integration/test/client/root-loader.test.ts
Updates the version of Remix used in integration tests to the latest 1.17.0, which is needed to test `handleError` and `defer` features.
=> test(remix): Update integration tests to Remix 1.17.0

packages/core/src/utils/prepareEvent.ts, packages/core/test/lib/prepareEvent.test.ts
We are currently facing the problem that the `RewriteFrames` integration, that is existing in many users setups, is breaking debug IDs. This is especially annoying when moving from the old release based source map process to the new debug ID based process.
How is the `RewriteFrames` integration is breaking debug IDs? Stack frames are linked to debug IDs via the `filename` value inside stack frames in the event and the `debug_file` value inside the `debug_meta` field. `filename` and `debug_file` are both generated *at event creation* (before any event processors run) and need to exactly match. When a `RewriteFrames` integration is active, it may register an event processor that modifies the `filename`. This causes the `filename` -> `debug_file` relationship to break, causing the entire …
=> fix(core): Temporarily store debug IDs in stack frame and only put them into `debug_meta` before sending

packages/replay/src/constants.ts, packages/replay/src/eventBuffer/EventBufferArray.ts, packages/replay/src/eventBuffer/EventBufferCompressionWorker.ts, packages/replay/src/eventBuffer/index.ts, packages/replay/src/util/addEvent.ts, packages/replay/test/unit/eventBuffer/EventBufferArray.test.ts, packages/replay/test/unit/eventBuffer/EventBufferCompressionWorker.test.ts, packages/replay/test/unit/util/addEvent.test.ts
When the buffer exceeds ~20MB, stop the replay.
Closes https://github.com/getsentry/sentry-javascript/issues/7657
Closes https://github.com/getsentry/team-replay/issues/94
=> feat(replay): Stop replay when event buffer exceeds max. size

packages/browser-integration-tests/suites/replay/slowClick/template.html, packages/browser-integration-tests/suites/replay/slowClick/windowOpen/test.ts, packages/replay/src/coreHandlers/handleClick.ts, packages/replay/src/coreHandlers/util/onWindowOpen.ts
When a click triggers `window.open()`, do not consider it a slow click.
Closes https://github.com/getsentry/sentry-javascript/issues/8301
=> feat(replay): Consider `window.open` for slow clicks

packages/angular-ivy/src/sdk.ts, packages/angular/src/sdk.ts, packages/angular/test/sdk.test.ts
As explained in https://github.com/getsentry/sentry-javascript/issues/5417#issuecomment-1453407097, the `TryCatch` default integration interferes with the `SentryErrorHander` error handler of the Angular(-Ivy) SDKs by catching certain errors too early, before the Angular SDK-specific error handler can catch them. This caused missing data on the event in some or duplicated errors in other cases.
This PR filters out the `TryCatch` by default, as long as users didn't set `defaultIntegrations` in their SDK init. Therefore, it makes the previously provided [workaround](https://github.com/getsentry/sentry-javascript/issues/5417#issuecomment-1453407097) obsolete.
The fix isn't ideal for two reasons but IMO we should nevertheless do this now to fix a long lasting problem and clean things up in …
=> fix(angular): Filter out `TryCatch` integration by default

packages/e2e-tests/test-applications/sveltekit/package.json
Since @sentry/sveltekit depends on @sentry/vite-plugin, which in turn depens on `@sentry/node@^7.19.0` & `@sentry/tracing@^7.19.0`, this fails to install in E2E tests for pre-release versions (e.g. `7.57.0-beta.0`), as the prerelease does not satisfy the range `^7.19.0`. So we override this to `*` to ensure this works as expected.
(Side note: We should maybe update @sentry/sveltekit to use the latest @sentry/vite-plugin?)
=> test(e2e): Ensure sveltekit E2E test work with prereleases

packages/replay/src/types/replayFrame.ts
This field was added as part of v7.56.0, but `SlowClickFrameData` was created before that. Having `clickCount` be required breaks backwards compatibility, it should be optional.
=> fix(replay): Mark ui.slowClickDetected `clickCount` as optional

packages/sveltekit/src/client/load.ts, packages/sveltekit/test/client/load.test.ts
In the client-side SvelteKit fetch instrumentation, our previous type cast when retrieving the SDK client was wrong, causing us to not guard the fetch instrumentation correctly if the client was undefined. (We did account for the `getClientById` method but missed the more obvious case)
fixes #8290
=> fix(sveltekit): Only instrument SvelteKit `fetch` if the SDK client is valid

packages/serverless/src/index.ts
When refactoring our `@sentry/tracing` package and exporting tracing related integrations from SDK packages, we apparently forgot to export `autoDiscoverNodePerformanceMonitoringIntegrations` from the Serverless SDK. This PR re-adds the export.
ref https://github.com/getsentry/sentry-docs/issues/7221
=> fix(serverless): Export `autoDiscoverNodePerformanceMonitoringIntegrations` from SDK

.github/workflows/build.yml, packages/tracing-internal/src/node/integrations/prisma.ts, packages/tracing/test/integrations/node/prisma.test.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/7216
Adds the Prisma middleware to trace DB calls inside the Sentry Prisma integration constructor instead of inside the `setupOnce` call. Reason being some server-side bundling scenarios (Next.js) where Prisma clients are unintentionally created multiple times. We can only instrument one Prisma client with `setupOnce` hence we move it into the constructor, which is usually called in the same situations as the `PrismaClient` constructor.
For more info view: https://github.com/getsentry/sentry-javascript/issues/7216#issuecomment-1602375012 (This PR implements option 2)
=> fix(tracing): Instrument Prisma client in constructor of integration

packages/replay/src/session/clearSession.ts, packages/replay/src/session/fetchSession.ts, packages/replay/src/session/saveSession.ts, packages/replay/src/util/hasSessionStorage.ts
It seems in some environments `sessionStorage` my be unset to `null` or similar. To be extra careful, we can guard for existence as well there.
Fixes https://github.com/getsentry/sentry-javascript/issues/8392
=> ref(replay): More graceful `sessionStorage` check

packages/browser-integration-tests/utils/helpers.ts, packages/browser-integration-tests/utils/replayHelpers.ts, packages/e2e-tests/test-utils/event-proxy-server.ts, packages/eslint-config-sdk/src/index.js, packages/nextjs/src/client/wrapAppGetInitialPropsWithSentry.ts, packages/nextjs/src/client/wrapDocumentGetInitialPropsWithSentry.ts, packages/nextjs/src/client/wrapErrorGetInitialPropsWithSentry.ts, packages/nextjs/src/client/wrapGetInitialPropsWithSentry.ts, packages/nextjs/src/client/wrapGetServerSidePropsWithSentry.ts, packages/nextjs/src/client/wrapGetStaticPropsWithSentry.ts, packages/nextjs/src/common/devErrorSymbolicationEventProcessor.ts, packages/nextjs/src/edge/wrapApiHandlerWithSentry.ts, packages/nextjs/src/edge/wrapMiddlewareWithSentry.ts, packages/nextjs/src/server/wrapApiHandlerWithSentry.ts, packages/nextjs/src/server/wrapDocumentGetInitialPropsWithSentry.ts, packages/nextjs/src/server/wrapGetStaticPropsWithSentry.ts, packages/replay/src/util/sendReplay.ts, packages/replay/test/integration/flush.test.ts, packages/sveltekit/src/vite/svelteConfig.ts, packages/utils/test/buildPolyfills/originals.js
Add https://eslint.org/docs/latest/rules/no-return-await to eslint config to remove usage of uneeded async/await calls. This helps reduce microtasks being generated, which can help reduce memory pressure caused by the SDK.
The downside of removing `return await` is that stacktraces get slightly worse for async errors that use these methods, as we no longer pause execution on return for the engine to grab context on, but instead just pass through the promise, but I think it's worth it for this to be the default, and for us to opt-in to the better stacktraces if need be.
=> feat(eslint): Add `no-return-await` rule to eslint config

packages/node/src/integrations/http.ts, packages/node/src/types.ts, packages/types/src/options.ts
Move `tracePropagationTargets` to top level options since it's required for tracing without performance support.
Next step here is to refactor `BrowserTracing` to use the top level option and open a docs PR for this change.
=> feat(types): Add tracePropagationTargets to top level options

packages/sveltekit/src/client/load.ts, packages/sveltekit/src/client/vendor/buildSelector.ts, packages/sveltekit/src/client/vendor/hash.ts, packages/sveltekit/src/client/vendor/lookUpCache.ts, packages/sveltekit/test/client/load.test.ts, packages/sveltekit/test/client/vendor/lookUpCache.test.ts, packages/sveltekit/test/vitest.setup.ts
As outlined in https://github.com/getsentry/sentry-javascript/issues/8174#issuecomment-1557042801, our current SvelteKit fetch instrumentation breaks SvelteKit's request caching mechanism. This is problematic as `fetch` requests from universal `load` functions were made again on the client side during hydration although the response was already cached from the initial server-side request. 
The reason for the cache miss is that in the instrumentation we add our tracing headers to the requests, which lead to a different cache key than the one produced on the server side.
This PR vendors in code from [the SvelteKit repo](https://github.com/sveltejs/kit) so that we can perform the same cache lookup in our instrumentation. If the lookup was successful (--> cache hit), we won't attach any …
=> fix(sveltekit): Check for cached requests in client-side fetch instrumentation

packages/e2e-tests/test-applications/nextjs-app-dir/components/transaction-context.tsx, packages/ember/addon/index.ts, packages/nextjs/src/edge/wrapApiHandlerWithSentry.ts, packages/nextjs/test/edge/withSentryAPI.test.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-header-out/server.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-transaction-name/server.ts, packages/node/src/handlers.ts, packages/node/src/integrations/http.ts, packages/node/src/sdk.ts, packages/node/test/handlers.test.ts, packages/node/test/integrations/http.test.ts, packages/node/test/integrations/requestdata.test.ts, packages/opentelemetry-node/test/spanprocessor.test.ts, packages/remix/src/utils/instrumentServer.ts, packages/replay/src/util/sendReplayRequest.ts, packages/replay/test/integration/coreHandlers/handleScope.test.ts, packages/svelte/src/performance.ts, packages/tracing-internal/src/browser/request.ts, packages/tracing/test/hub.test.ts, packages/vue/src/tracing.ts
In https://github.com/getsentry/sentry-javascript/pull/7551 I made it so that scope was always defined when calling `hub.getScope()`. This patch refactors some code (mostly tests) to not check if scope is undefined anymore.
We no longer need to do
```js
const span = hub.getScope()?.getSpan();
```
or
```js
const scope = hub.getScope();
if (scope) {
scope.addBreadcrumb(...)
}
```
=> ref: Remove undefined checks for `hub.getScope()`

packages/browser/src/profiling/cache.ts, packages/browser/src/profiling/hubextensions.ts
Collect span information on how long the async calls to profiler.stop take which will help us evaluate if calling txn.finish after profiler.stop is a viable approach
=> feat: collect timings on profiler stop calls

packages/browser-integration-tests/suites/tracing/browsertracing/http-timings/init.js, packages/browser-integration-tests/suites/tracing/browsertracing/http-timings/subject.js, packages/browser-integration-tests/suites/tracing/browsertracing/http-timings/test.ts, packages/tracing-internal/src/browser/browsertracing.ts, packages/tracing-internal/src/browser/request.ts
This adds an experiment that will allow http timings to be captured. We currently capture timings on Sentry SaaS with some custom code and append them to the spans, which has been helpful to identify some performance problems that were previously hidden (http/1.1 stall time). Following this work we can add these to the waterfall to represent measurements as subtimings and will power an upcoming http/1.1 stall performance issue.
=> feat(tracing): Add experiment to capture http timings

packages/browser/src/sdk.ts
Ref: https://github.com/getsentry/sentry/issues/49535#issuecomment-1612643524
Since we don't need to authenticate users on the report dialog endpoint we should not send any credentials with the request.
Also prevents COEP blockage: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy#avoiding_coep_blockage_with_cors
=> fix(browser): Set anonymous `crossorigin` attribute on report dialog

packages/browser-integration-tests/suites/replay/captureReplay/test.ts, packages/browser-integration-tests/suites/replay/captureReplayFromReplayPackage/test.ts, packages/browser-integration-tests/utils/replayEventTemplates.ts, packages/core/src/baseclient.ts, packages/core/src/scope.ts, packages/core/test/lib/base.test.ts, packages/hub/test/scope.test.ts, packages/node/test/async/domain.test.ts, packages/node/test/async/hooks.test.ts, packages/replay/src/util/sendReplayRequest.ts, packages/replay/test/unit/util/prepareReplayEvent.test.ts, packages/types/src/context.ts, packages/types/src/hub.ts, packages/types/src/index.ts, packages/types/src/scope.ts, packages/types/src/tracing.ts
For more details about PropagationContext, see https://www.notion.so/sentry/Tracing-without-performance-efab307eb7f64e71a04f09dc72722530
Building off of work in both https://github.com/getsentry/sentry-javascript/pull/8403 and https://github.com/getsentry/sentry-javascript/pull/8418, this PR adds `PropagationContext` and uses that to always set a trace context on outgoing error events.
Currently if there is an active span on the scope, we automatically attach that span's trace context to all outgoing events. Now, we want to rely on either the active span or fallback to the propagation context to ensure that there is always a trace being generated and propagated.
Next up we'll work on updating the node/browser SDKs to update …
=> feat(tracing): Add `PropagationContext` to scope 

packages/sveltekit/src/server/handle.ts, packages/sveltekit/src/server/load.ts, packages/sveltekit/src/server/utils.ts
Use the `tracingContextFromHeaders` helper (first used in https://github.com/getsentry/sentry-javascript/pull/8422) to simplify how trace context is generated by the Sveltekit SDK . Then set the propagation context accordingly.
=> ref(sveltekit): Extract propagation context

packages/tracing-internal/src/browser/browsertracing.ts, packages/tracing-internal/src/browser/request.ts, packages/tracing-internal/test/browser/browsertracing.test.ts, packages/tracing-internal/test/browser/metrics/index.test.ts, packages/tracing-internal/test/browser/request.test.ts, packages/tracing-internal/test/browser/router.test.ts
This PR makes sure the `BrowserTracing` integration updates the propagation context based on meta tags. To ensure we don't keep the same propagation context, we continuously update it every time a route change should happen (navigation).
Note that we have a bunch of test changes here. This is because we actually weren't running any of the tracing tests in CI because of a blanket ignore we use (this logic is all in `@sentry-internal/tracing`. I'm fixing this in a follow up PR. https://github.com/getsentry/sentry-javascript/blob/e02c27f4ba8288ff4172a6793c955ae3806714e7/package.json#L28-L29
=> ref(tracing): Extract propagation context from meta tags

packages/node-integration-tests/suites/express/handle-error/test.ts, packages/node/src/handlers.ts
I found it confusing that unhandled errors caught by the express.js middleware were being reported as handled
This change updates the behavior to match Sentry-Python's Django integration: https://github.com/getsentry/sentry-python/blob/81afcea403c0ac148d631164de29ed80d6a64840/sentry_sdk/integrations/asgi.py#L58
I could use help testing this
=> fix(node): report errorMiddleware errors as unhandled

packages/core/src/baseclient.ts, packages/core/src/scope.ts, packages/core/src/tracing/dynamicSamplingContext.ts, packages/core/src/tracing/index.ts, packages/core/src/tracing/span.ts, packages/core/src/tracing/transaction.ts, packages/hub/test/scope.test.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-header-assign/test.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-header-out/test.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-other-vendors-with-sentry-entries/test.ts, packages/node/test/integrations/http.test.ts, packages/node/test/integrations/undici.test.ts, packages/opentelemetry-node/test/propagator.test.ts, packages/tracing/test/utils.test.ts, packages/types/src/scope.ts, packages/utils/src/baggage.ts, packages/utils/src/tracing.ts, packages/utils/test/baggage.test.ts
experiments here: https://github.com/getsentry/sentry-javascript/pull/8433
In preparation for Part 3 of https://github.com/getsentry/sentry-javascript/issues/8352 (which involves creating `sentry-trace`/`baggage` when a span __does not__ exist and attaching them to outgoing requests/meta tags), this PR adds some helpers. Notably it adds:
1. A getter for `PropagationContext` on the scope
2. `generateSentryTraceHeader`, which will be used to dynamically create `sentry-trace` headers, regardless of if there is a span or not
3. `getDynamicSamplingContextFromClient`, which is used to generate dynamic sampling context from a client directly (instead of having to go through a transaction)
This PR also updates `extractTraceparentData` and `dynamicSamplingContextToSentryBaggageHeader` to be more …
=> ref(tracing): Add necessary helpers for using propagation context on outgoing headers

lerna.json, nx.json, package.json, yarn.lock
We've been on an alpha version before, so it makes sense to update to the latest stable version instead. There are some removed things that we are not using, so updating should just fix some bugs and not much else.
I ran `yarn lerna repair` to clean up config.
See: https://github.com/lerna/lerna/releases/tag/7.0.0
=> build: Update lerna to 7.1.1

packages/angular/src/errorhandler.ts
=> chore(angular): remove duplicate condition

.github/workflows/build.yml
Fixes https://github.com/getsentry/sentry-javascript/issues/8445
=> ci: Fix `cache-hit` typo

packages/core/src/index.ts, packages/core/src/metadata.ts, packages/core/test/lib/metadata.test.ts, packages/types/src/stackframe.ts, packages/utils/src/worldwide.ts
Part of the code required to better support Module Federation/Micro Frontends.
The webpack bundler will be able to optionally inject metadata into each bundle chunk (https://github.com/getsentry/sentry-javascript-bundler-plugins/pull/334). 
This PR adds code that:
- Adds `module_metadata` to `StackFrame`
- Adds `getMetadataForUrl` that gets metadata for a path/URL
- Parses the stacks on demand to get the relevant filename for a chunk and associated injected metadata 
- Adds `addMetadataToStackFrames` that populates `module_metadata` in stack frames with metadata when available
- Adds `stripMetadataFromStackFrames` that strips `module_metadata` from stack frames
=> feat(core): Add helpers to get module metadata from injected code

packages/serverless/src/awslambda.ts, packages/serverless/src/gcpfunction/http.ts, packages/serverless/test/__mocks__/@sentry/node.ts
Introduce the `tracingContextFromHeaders` (first used in https://github.com/getsentry/sentry-javascript/pull/8422) to simplify how trace context is generated by serverless tracing handlers. Then set the propagation context accordingly.
=> ref(serverless): Extract propagation context

packages/browser-integration-tests/suites/replay/slowClick/multiClick/test.ts, packages/browser-integration-tests/utils/replayHelpers.ts, packages/replay/src/constants.ts, packages/replay/src/coreHandlers/handleClick.ts, packages/replay/src/replay.ts, packages/replay/src/types/replay.ts, packages/replay/test/unit/coreHandlers/handleClick.test.ts
Implements the changes outlined in https://github.com/getsentry/sentry-javascript/issues/8379
=> fix(replay): Adjust slow/multi click handling

packages/node/src/integrations/linkederrors.ts, packages/node/test/integrations/linkederrors.test.ts
When I looked into the linked errors integration to implement support for Aggregate erros I noticed that in the node linked errors integration we had an `await` that did nothing.
This was a bit curios to me since all of the functions in the node linked errors integration were async just because of that await. Looking into it some more it seems that we used the wrong funciton of the context lines integration to attach source context. We were only attaching source context if the file was in our file cache - this operation is synchronous. We  basically just called the wrong fuction of the context lines integration (`addSourceContextToFrames` instead of `addSourceContext`).
This pr changes the node linked errors integration to add source (cached AND uncached) source context to linked errors …
=> fix(node): Apply source context to linked errors even when it is uncached

packages/nextjs/src/config/webpack.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/8293
Prepends the tunnel route with [Next.js' `basePath` option](https://nextjs.org/docs/app/api-reference/next-config-js/basePath) if it is set.
h/t to @inlet for noting figuring out that the rewrite was already correct. Thought that this was gonna be a bit more involved.
=> fix(nextjs): Use `basePath` option for `tunnelRoute`

packages/react/src/reactrouterv6.tsx, packages/react/src/types.ts, packages/react/test/reactrouterv6.4.test.tsx
Fixes: #8413 
Passes `basename` option to `matchRoutes` we use to generate branches correctly, while updating `pageload` transactions and starting `navigation` transactions.
=> fix(react): Add support for `basename` option of `createBrowserRouter`

packages/angular/tsconfig.json
As `@sentry/angular` uses TS 4.0, but the default behavior of TS is to load _all_ `@types/xxx` packages it can find in node_modules, the build will fail if _any_ other package uses a types package that uses newer TS features. 
In order to avoid this, we opt out of the automatic types resolution - since we are not using any `@types/xxx` package in angular as of now, this doesn't change anything.
See https://www.typescriptlang.org/tsconfig/types.html for details.
=> build(angular): Avoid loading all `@types/` packages

packages/remix/src/utils/instrumentServer.ts, packages/remix/test/integration/app_v1/root.tsx, packages/remix/test/integration/app_v2/root.tsx, packages/remix/test/integration/test/client/root-loader.test.ts
Related: https://github.com/epicweb-dev/epic-stack/issues/256
Skips `trace` and `baggage` injections to `redirect` and `catch` responses.
For `redirect` responses: It was breaking the behaviour of redirection. Internal redirection targets should already have their `trace` and `baggage`, so I assume this should not break the connection between services at the end.
`catch` responses do not have bodies, and they are thrown by Remix, so skipping injection as well not to potentially break the internal catch behaviour of Remix.
=> fix(remix): Don't inject trace/baggage to `redirect` and `catch` responses

packages/types/src/mechanism.ts, packages/utils/src/aggregate-errors.ts, packages/utils/test/aggregate-errors.test.ts
Resolves https://github.com/getsentry/sentry-javascript/issues/5469
Uses the new [exception groups](https://github.com/getsentry/rfcs/blob/main/text/0079-exception-groups.md) in the product to support [`AggregateErrors`](). "Linked errors" aka `Error.cause` will also use these new exception groups.
---
```
new Error("Custom Browser Error!", {
cause: new AggregateError([
new Error('A'),
new Error('B')
], 'Woowee')
});
```
=> feat: Support `AggregateErrors` in `LinkedErrors` integration

packages/nextjs/src/config/types.ts, packages/nextjs/src/config/webpack.ts, packages/nextjs/src/config/withSentryConfig.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/8285
Next.js doesn't allow static exports + rewrites. This PR will stop injecting rewrites on static exports.
=> fix(nextjs): Ignore `tunnelRoute` when doing static exports

packages/node/src/index.ts, packages/node/src/module.ts, packages/node/src/sdk.ts, packages/node/test/module.test.ts
I'm looking to fix [this Electron issue](https://github.com/getsentry/sentry-electron/issues/686) and need access to the `getModule` function but it's not currently exported.
Since we're now exporting this, I've renamed it to `getModuleFromFilename` since that better describes what it does...
=> feat(node): Export `getModule` for Electron SDK

.github/workflows/build.yml, packages/e2e-tests/test-applications/create-remix-app/test-recipe.json
was noticing some timeout issues in my PRs, so adding this change
=> chore: Add 4th e2e test shard and disable remix e2e tests

.github/workflows/build.yml, packages/nextjs/test/integration/sentry.client.config.js, packages/nextjs/test/integration/sentry.edge.config.js, packages/nextjs/test/integration/sentry.server.config.js, packages/node-integration-tests/suites/express/sentry-trace/baggage-header-out/server.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-other-vendors-with-sentry-entries/server.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-other-vendors/server.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-transaction-name/server.ts, packages/node-integration-tests/suites/express/sentry-trace/server.ts, packages/node-integration-tests/suites/express/tracing/server.ts, packages/node-integration-tests/utils/index.ts, packages/node/src/integrations/http.ts, packages/node/test/integrations/http.test.ts, packages/remix/test/integration/app_v1/entry.server.tsx, packages/remix/test/integration/app_v2/entry.server.tsx
Updates the Node HTTP integration to always attach `sentry-trace` headers to outgoing requests.
This can be controlled with the top level `tracePropagationOptions` option.
=> feat(node): Add tracing without performance to Node http integration

packages/node/src/integrations/undici/index.ts, packages/node/src/integrations/undici/types.ts, packages/node/test/integrations/undici.test.ts
Updates the Node Undici integration to always attach `sentry-trace` headers to outgoing requests.
This can be controlled with the top level `tracePropagationOptions` option.
=> feat(node): Add tracing without performance to Node Undici

packages/remix/test/integration/test/client/meta-tags.test.ts
resolves https://github.com/getsentry/sentry-javascript/issues/8398
Since these tests are flaky on firefox skipping them.
=> test(remix): Skip flaky firefox integration tests

packages/remix/src/index.server.ts
Fixes: https://github.com/getsentry/sentry-javascript/issues/8474
Manually tested on latest epic-stack with reproduction at https://github.com/epicweb-dev/epic-stack/issues/289
=> fix(remix): Add explicit `@sentry/node` exports.

packages/browser-integration-tests/suites/replay/dsc/test.ts, packages/browser-integration-tests/suites/tracing/envelope-header-transaction-name/test.ts, packages/browser-integration-tests/suites/tracing/envelope-header/test.ts, packages/core/src/tracing/transaction.ts, packages/node-integration-tests/suites/express/sentry-trace/baggage-header-out/test.ts, packages/node/test/integrations/http.test.ts, packages/node/test/integrations/undici.test.ts, packages/opentelemetry-node/test/propagator.test.ts, packages/tracing-internal/test/browser/browsertracing.test.ts, packages/types/src/envelope.ts
resolves https://github.com/getsentry/sentry-javascript/issues/8482
To save on bundle size, we only add `sampled` to the DSC if there is an active transaction
This matches https://github.com/getsentry/relay/blob/11f1ab455e2d5abc11d05776f8ec4a83cfd8c66e/relay-general/src/protocol/contexts/trace.rs#L109-L112
=> feat(core): Add sampling decision to trace envelope header

packages/node/src/handlers.ts
Only gate transaction creation to the `hasTracingEnabled`, otherwise always make sure that `propagationContext` is being set.
=> fix(node): Set propagation context even when tracingOptions are not defined

packages/core/test/lib/base.test.ts
```
> @sentry/core:lint
$ run-s lint:prettier lint:eslint
$ prettier --check "{src,test,scripts}/**/**.ts"
Checking formatting...
All matched files use Prettier code style!
$ eslint . --format stylish
/home/runner/work/sentry-javascript/sentry-javascript/packages/core/test/lib/base.test.ts
1676:7  warning  Include a description after the "@ts-ignore" directive to explain why the @ts-ignore is necessary. The description must be 3 characters or longer  @typescript-eslint/ban-ts-comment
1704:7  warning  Include a description after the "@ts-ignore" directive to explain why the @ts-ignore is necessary. The description must be 3 characters or longer  @typescript-eslint/ban-ts-comment
1734:7  warning  Include a description after the "@ts-ignore" directive to explain why the @ts-ignore is …
```
=> chore(core): Remove eslint warnings

packages/tracing-internal/src/node/integrations/prisma.ts
```
> @sentry-internal/tracing:lint
$ run-s lint:prettier lint:eslint
$ prettier --check "{src,test,scripts}/**/**.ts"
Checking formatting...
All matched files use Prettier code style!
$ eslint . --format stylish
/home/runner/work/sentry-javascript/sentry-javascript/packages/tracing-internal/src/node/integrations/prisma.ts
68:50  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
```
=> chore(tracing-internal): Fix eslint warning

packages/nextjs/src/config/webpack.ts
As reported in #8541, our NextJS SDK currently breaks dev mode for the newest NextJS 13.4.10 version
I have absolutely no idea which of the changes in [13.4.10](https://github.com/vercel/next.js/releases/tag/v13.4.10) is causing this and the chaotic changelog is no help at all. 
However, I traced the error back and it happens as soon as our NextJS SDK package requires @sentry/webpack-plugin:
* @sentry/nextjs calls `require('@sentry/webpack-plugin')`
* @sentry/webpack-plugin calls `const { RawSource } = require('webpack-sources');`
* For _whatever_ reason, NextJS can't require `webpack-sources` and throws 💥 
Since we don't enable our Webpack plugin [in dev mode](https://github.com/getsentry/sentry-javascript/blob/723f851f358b75cd39da353804c51ff27ebb0c11/packages/nextjs/src/config/webpack.ts …
=> fix(nextjs): Avoid importing SentryWebpackPlugin in dev mode

packages/nextjs/test/integration/next-env.d.ts, packages/nextjs/test/run-integration-tests.sh
As long as our SDK and `next@13.4.10` aren't compatible, we need to hard-pin our NextJS integration tests to `13.4.9` to unblock our CI.  
We need to revert this PR once we figured out 13.4.10! (Set a reminder for myself)
ref #8541
=> test(nextjs): Pin Nextjs 13 integration tests to `next@13.4.9`

packages/replay/src/util/addEvent.ts, packages/replay/test/integration/beforeAddRecordingEvent.test.ts
When an error occurs in `beforeAddRecordingEvent`, we just skip this event and log the error.
Closes https://github.com/getsentry/sentry-javascript/issues/8542
=> fix(replay): Handle errors in `beforeAddRecordingEvent` callback

packages/replay/src/util/hasSessionStorage.ts
Apparently accessing sessionStorage in an iframe with certain permissions can result in a throw, so we try-catch this to ensure we do not produce any errors.
Closes https://github.com/getsentry/sentry-javascript/issues/8392
=> fix(replay): Better session storage check

packages/nextjs/src/config/webpack.ts
This fix was already reviewed, merged and released in the last beta. This PR will now merge it into `develop` to make it available with the next official release. Thanks to the users who tested the beta released and confirmed that it is working.
--- 
As reported in #8541, our NextJS SDK currently breaks dev mode for the newest NextJS 13.4.10 version
I still have absolutely no idea which of the changes in
[13.4.10](https://github.com/vercel/next.js/releases/tag/v13.4.10) is causing this.
However, I traced the error back and it happens as soon as our NextJS SDK package requires @sentry/webpack-plugin:
* @sentry/nextjs calls `require('@sentry/webpack-plugin')`
* @sentry/webpack-plugin calls `const { RawSource } = require('webpack-sources');`
* For _whatever_ reason, NextJS can't require …
=> fix(nextjs): Avoid importing `SentryWebpackPlugin` in dev mode

packages/tracing-internal/src/browser/browsertracing.ts, packages/tracing-internal/src/browser/request.ts, packages/tracing-internal/test/browser/browsertracing.test.ts
This brings HTTP timings out of experiment, with an option to turn them off still. For now we'll be hiding them in the UI until we've figure out which ones we want to display.
=> feat(tracing): Bring http timings out of experiment

CHANGELOG.md
https://github.com/getsentry/publish/issues/2507 publish release failed due to issues with npm publishing. We're remaking the release w/ a new version since that release failed halfway through.
=> meta: Update CHANGELOG for 7.59.1

packages/browser-integration-tests/suites/replay/sessionMaxAge/init.js, packages/browser-integration-tests/suites/replay/sessionMaxAge/test.ts, packages/replay/src/replay.ts
This is a PR to this feature branch: https://github.com/getsentry/sentry-javascript/pull/8407
* Handle edge case where we stop multiple times (honestly no idea how this should happen, but apparently it can 😬 )
* Add some more logging for state changes
We can hopefully eventually remove the `traceInternals` checks, but for now this is an easy solution for debugging in the beta....
=> fix(replay): Handle edge cases & more logging

packages/core/test/lib/transports/offline.test.ts, packages/eslint-config-sdk/package.json, packages/eslint-config-sdk/src/index.js, packages/node/test/integrations/undici.test.ts, yarn.lock
We sometimes forget to remove focused or disabled annotations after debugging tests. This of course isn't ideal and as brought up in #8485 we should add checks against this. Therefore, this PR:
* Adds the [`eslint-plugin-jest` package ](https://github.com/jest-community/eslint-plugin-jest/tree/main)which contains a bunch of jest-syntax-specific rules
* Enables the `no-focused-tests` rule to throw a lint error if a test is focused with `it.only`, `fit` or similar functions. 
* Enables the `no-disabled-tests` rule to throw a lint error if a test (suite) from a suite is disabled/skipped with `it.skip`, `xit` or similar functions. While we sometimes skip tests on purpose, I'd argue that we generally want to avoid this, as it can also happen accidentally. For the few exceptions of this rule, …
=> chore(eslint): Add lint rules for disabled or focused tests

packages/nextjs/src/config/webpack.ts
I guess you can call this a hotfix for the hotfix (#8557). For some reason (lol, I've been saying this a lot lately) dynamic requires of our webpack plugin don't work for some users. We still don't have a better fix for #8541 so let's just get this in to unblock folks. 
closes #8576
=> fix(nextjs): Ensure Webpack plugin is available after dynamic require

.craft.yml, docs/new-sdk-release-checklist.md
Following up on #inc-456, this PR splits the previously universal `npm` target that took care of publishing all packages at once into multiple targets (one for each package).
This will ensure that packages are published in the correct order of their sentry dependency tree (e.g. core -> browser -> react, etc..) Furthermore, this theoretically also lets us disable the release of individual packages (which we might want to do if a package was already released). 
In addition, this PR now moves NPM targets before other targets, so that no GH releases are created if the actual publishing of artifacts failed previously.
The drawback of this solution is that we have to manually add a new target for new packages we added. Therefore, this PR also adjusts our new package release checklist to do this …
=> chore(publish): Publish NPM packages in order of dependency tree

packages/browser/src/client.ts, packages/types/src/browseroptions.ts, packages/types/src/index.ts
Adds the profilesSampleRate type to browser client options. I followed the example of replay and created a new type with profiling related options.
=> types(browser): add browser profiling client options

packages/browser-integration-tests/suites/replay/bufferMode/init.js, packages/browser-integration-tests/suites/replay/compression/init.js, packages/browser-integration-tests/suites/replay/customEvents/init.js, packages/browser-integration-tests/suites/replay/errors/droppedError/init.js, packages/browser-integration-tests/suites/replay/errors/errorModeCustomTransport/init.js, packages/browser-integration-tests/suites/replay/errors/errorNotSent/init.js, packages/browser-integration-tests/suites/replay/errors/errorsInSession/init.js, packages/browser-integration-tests/suites/replay/errors/init.js, packages/browser-integration-tests/suites/replay/flushing/init.js, packages/browser-integration-tests/suites/replay/keyboardEvents/init.js, packages/browser-integration-tests/suites/replay/largeMutations/defaultOptions/init.js, packages/browser-integration-tests/suites/replay/largeMutations/mutationLimit/init.js, packages/browser-integration-tests/suites/replay/multiple-pages/init.js, packages/browser-integration-tests/suites/replay/requests/init.js, packages/browser-integration-tests/suites/replay/sessionExpiry/init.js, packages/browser-integration-tests/suites/replay/sessionInactive/init.js, packages/browser-integration-tests/suites/replay/sessionMaxAge/init.js, packages/browser-integration-tests/suites/replay/slowClick/disable/init.js, packages/browser-integration-tests/suites/replay/slowClick/init.js, packages/browser-integration-tests/suites/replay/unicode/compressed/init.js, packages/browser-integration-tests/suites/replay/unicode/uncompressed/init.js
Just noticed that this is inconsistent, and by using a shorter value we can slightly reduce test times (as we need to wait shorter).
=> test(replay): Reduce flush delay for shorter tests

packages/browser-integration-tests/suites/replay/slowClick/multiClick/test.ts, packages/replay/src/coreHandlers/handleClick.ts, packages/replay/src/eventBuffer/EventBufferArray.ts, packages/replay/src/eventBuffer/EventBufferCompressionWorker.ts, packages/replay/src/util/addEvent.ts, packages/replay/src/util/timestamp.ts
Not sure if this actually fixes the problem with sometimes incorrect click count, but it def. makes sense to have this safeguard, I'd say.
=> fix(replay): Ensure multi click has correct timestamps

packages/e2e-tests/README.md, packages/e2e-tests/test-applications/create-next-app/package.json, packages/e2e-tests/test-applications/create-react-app/package.json, packages/e2e-tests/test-applications/create-remix-app/package.json, packages/e2e-tests/test-applications/nextjs-app-dir/package.json, packages/e2e-tests/test-applications/nextjs-app-dir/test-recipe.json, packages/e2e-tests/test-applications/node-express-app/package.json, packages/e2e-tests/test-applications/react-create-hash-router/package.json, packages/e2e-tests/test-applications/react-create-hash-router/test-recipe.json, packages/e2e-tests/test-applications/standard-frontend-react-tracing-import/package.json, packages/e2e-tests/test-applications/standard-frontend-react/package.json, packages/e2e-tests/test-applications/standard-frontend-react/test-recipe.json, packages/e2e-tests/test-applications/sveltekit/package.json
Due to the [way pnpm handles versions](https://github.com/pnpm/pnpm/issues/6463), the version `*` we use in E2E tests is actually incorrect, because it installs the _lowest_ version it can find, e.g. 0.1.0. This is usually not a problem as when we use verdaccio, there is only a single version in the repository. however, when running things locally/debugging stuff, and you run `pnpm install` without verdaccio, stuff fails. This updates the versions used in E2E tests to `latest || *`, which results in a correct resolution.
=> test(e2e): Use `latest || *` instead of `*` as version

packages/browser-integration-tests/loader-suites/loader/noOnLoad/captureException/test.ts, packages/browser-integration-tests/loader-suites/loader/noOnLoad/customOnErrorHandler/test.ts, packages/browser-integration-tests/loader-suites/loader/noOnLoad/errorHandler/test.ts, packages/browser-integration-tests/loader-suites/loader/noOnLoad/errorHandlerLater/test.ts, packages/browser-integration-tests/loader-suites/loader/noOnLoad/pageloadTransaction/test.ts, packages/browser-integration-tests/loader-suites/loader/noOnLoad/sdkLoadedInMeanwhile/test.ts, packages/browser-integration-tests/loader-suites/loader/onLoad/captureException/test.ts, packages/browser-integration-tests/loader-suites/loader/onLoad/captureExceptionInOnLoad/test.ts, packages/browser-integration-tests/loader-suites/loader/onLoad/customBrowserTracing/test.ts, packages/browser-integration-tests/loader-suites/loader/onLoad/errorHandler/test.ts, packages/browser-integration-tests/loader-suites/loader/onLoad/errorHandlerLater/test.ts, packages/browser-integration-tests/loader-suites/loader/onLoad/pageloadTransaction/test.ts, packages/browser-integration-tests/utils/helpers.ts
Fixes: #8590
Playwright's event listeners and `page.goto` functions can occasionally end up in race condition, even when they are invoked in the correct order.
The workaround is to invoke them in `Promise.all`, unless there's a specific need to separate them.
This PR updates `loader` tests to use that pattern.
=> fix(tests): Update `loader` integration tests to avoid flakes.

packages/browser-integration-tests/suites/public-api/captureException/linkedErrrors/subject.js, packages/browser-integration-tests/suites/public-api/captureException/linkedErrrors/test.ts, packages/browser/src/integrations/linkederrors.ts, packages/node/src/integrations/linkederrors.ts, packages/utils/src/aggregate-errors.ts, packages/utils/test/aggregate-errors.test.ts
As reported in #8580, aggregate exceptions' `exception.value` strings weren't truncated correctly in our event preparation pipeline. The tricky part here is that the `LinkedErrors` integration adds the linked/child exceptions to the event in an event processor which is applied only after we truncate the original event. Hence, we need to also truncate the values in the event processor itself. 
closes #8580
=> fix(utils): Truncate aggregate exception values (LinkedErrors)

packages/browser/src/profiling/utils.ts
This was causing drift between profiling and transaction timelines
=> fix(profiling): align to SDK selected time origin

packages/browser-integration-tests/utils/generatePlugin.ts
Instead of looking up folders in `package`, fetch the packages from the root package.json. This way, if you e.g. have empty folders or similar in your `package/` dir, it will not fail.
I notice this sometimes when working with new packages or similar, and switching branches, you may have leftover empty directories in `packages/`, which leads to integration tests failing unless you make sure to delete the directories.
=> test: Improve workspace dir handling

packages/nextjs/src/config/webpack.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/5978
We were matching for paths that started with `whatever/pages`, however that is bad if people have folders named something like `whatever/pages-components` so with this PR we will match with a trailing (OS-dependent) slash to only match full folders.
=> fix(nextjs): Match folder paths with trailing separator

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/feature.yml, .github/workflows/issue-package-label.yml
We can try to parse the used package from the issue body and auto-add the corresponding label.
This should work for any issue using the bug issue template. For others, it should just do nothing, which should be fine I'd say.
=> meta(ci): Auto-add package label to new issues

packages/browser-integration-tests/suites/replay/maxReplayDuration/init.js, packages/browser-integration-tests/suites/replay/maxReplayDuration/template.html, packages/browser-integration-tests/suites/replay/maxReplayDuration/test.ts, packages/replay/src/replay.ts, packages/replay/src/util/handleRecordingEmit.ts
We've been using `context.initialTimestamp` to check for min/max session duration, but actually this is always updated when a tab is refreshed, for example.
Instead, we now use `session.started`, which should also always be updated for a buffer session.
note that this also means, when an error happens, we flush immediately, but then wait for 5s until we flush again (which is fine, I'd say) - because at the time of conversion of buffer->session, we update the `started` of the session. But that's OK I'd say?
I also updated the logging to be based on this. Overall having a log for the buffer->session change makes sense to me anyhow, plus I also added one for the only other case where `session.started` is updated.
Note: I added a test to kind of cover this, but this test also passed with the …
=> fix(replay): Use `session.started` for min/max duration check

.github/workflows/issue-package-label.yml
Oops, apparently keys are regexes, so need to escape them I think:
https://github.com/getsentry/sentry-javascript/actions/runs/5655218559/job/15319870320
Let's see if that fixes it...
=> meta(ci): Fix label mapper

packages/e2e-tests/test-applications/create-next-app/tests/behaviour-client.test.ts, packages/e2e-tests/test-applications/create-remix-app/package.json, packages/e2e-tests/test-applications/create-remix-app/playwright.config.ts, packages/e2e-tests/test-applications/create-remix-app/tests/behaviour-client.test.ts
Replaces https://github.com/getsentry/sentry-javascript/pull/8611
This adds a super basic remix test scenario that handles booting the server & closing it again properly, ensuring tests don't hang but verify that remix boots up as expected.
=> test(remix): Add basic test for remix E2E app

.github/workflows/issue-package-label.yml
Argh, my previous fix is still not working. I digged some more into it, and the problem seems to be that the input is `JSON.parse()`'d, which wrangles the escape slashes, and then the lookup doesn't match together properly anymore etc.
So instead, we just use `.` as a wildcard instead of `/`, which still matches the regexes correctly and should be handled more gracefully by JSON.parse(). Let's hope that ACTUALLY fixes this now!
=> meta(ci): Actually fix package label mapping finally

.size-limit.js
This updates the size limit config a bit, to be a bit more structured.
* Drop all non-gzipped entries. IMHO it is good enough to have the gzipped values, and it makes it a bit clearer and easier to compare. Not sure if we want to add e.g. a single non-gzipped one, but honestly I don't know when we would really care about that?
* Reorder entries (not 100% sure TBH if the order is actually considered in the UI, though 😅 ). 
* Added webpack scenarios exporting just `{ init }`, or `{ init, BrowserTracing }` or `{ init, BrowserTracing, Replay }` to have a realistic coverage of these scenarios.
* Removed some secondary scenarios (e.g. there is just a single ES5 CDN bundle scenario left to cover this, not for all variations, ...
=> build: Update size limit config

packages/replay/src/coreHandlers/handleDom.ts
Apparently click+shift also opens a link in a new tab (and focuses the tab immediately), so we also need to ignore such clicks for slow click detection.
Closes https://github.com/getsentry/team-replay/issues/128
=> fix(replay): Ignore clicks with `shift` pressed

packages/e2e-tests/package.json, packages/e2e-tests/run.ts, packages/e2e-tests/test-applications/create-next-app/package.json, packages/e2e-tests/test-applications/create-react-app/package.json, packages/e2e-tests/test-applications/create-remix-app/package.json, packages/e2e-tests/test-applications/nextjs-app-dir/package.json, packages/e2e-tests/test-applications/node-express-app/package.json, packages/e2e-tests/test-applications/react-create-hash-router/package.json, packages/e2e-tests/test-applications/standard-frontend-react-tracing-import/package.json, packages/e2e-tests/test-applications/standard-frontend-react/package.json, packages/e2e-tests/test-applications/sveltekit/package.json
Noticed that when running `yarn test:run` it sometimes hang forever. Solved this with two steps:
1. Make sure we actually output the shell stuff, as otherwise it is super hard to debug what's going on.
2. The problem was that sometimes `pnpm` prompts to re-create node_modules (??), and the prompt was obviously forever hanging. I couldn't find any option to disable this from pnpm side, sadly 😬 So I ended up adding a step to clean out all node_modules etc. before running the tests.
=> test(e2e): Show test progress & ensure we clean before running tests

packages/node/src/integrations/http.ts, packages/node/test/integrations/http.test.ts
resolves https://github.com/getsentry/sentry-javascript/issues/8654
if we see that a `sentry-trace` header was already attached on the `requestOptions`, don't attach sentry trace and baggage headers again.
=> fix(node): Don't set extra baggage headers

packages/nextjs/test/run-integration-tests.sh
Set a reminder to revert this now that our SDK is compatible with ^13.4.10. Also need it to test #8666
=> Revert "test(nextjs): Pin Nextjs 13 integration tests to `next@13.4.9` (#8551)"

packages/node-experimental/package.json
Just noticed when rebasing a branch that `@sentry/node-experimental` still registered dependencies for 7.60.0 instead of 7.60.1 which causes yarn to download 7.60.0 instead of using the local packages.
=> chore(node-experimental): Align @sentry/ dependency version

packages/node-experimental/README.md
Just clarify the readme about what is/not supported for node-experimental.
=> docs(node-experimental): Clarify that manual instrumentation is n/a

packages/integrations/src/captureconsole.ts, packages/integrations/test/captureconsole.test.ts
This PR adds support for capturing an exception for the any error in a console method call (only the first error instance), not just if the first argument is an error.
This is a problem for us because timestamps are always the first argument in console calls and we often add a context message before the error.
=> fix(integrations): capture exception if any arg to console method is an error

packages/replay/src/coreHandlers/handleAfterSendEvent.ts, packages/replay/src/coreHandlers/handleGlobalEvent.ts, packages/replay/test/integration/coreHandlers/handleAfterSendEvent.test.ts, packages/replay/test/integration/coreHandlers/handleGlobalEvent.test.ts
We limit to max. 100 IDs being captured per replay, and ensure we do not capture stuff when replay has been disabled in the meanwhile.
Since our handlers are (sadly) all global, I guess it may have been possible for something "bad" to happen when replay has been disabled in the meanwhile 🤔 
ref https://github.com/getsentry/team-replay/issues/131
ref https://github.com/getsentry/sentry-javascript/issues/8672
=> fix(replay): Improve capture of errorIds/traceIds

packages/sveltekit/src/client/load.ts, packages/tracing-internal/src/browser/request.ts, packages/tracing-internal/test/browser/request.test.ts
In slack we reported a bug where there seemed to be the wrong parent span id attached to outgoing `sentry-trace` headers: https://sentry.slack.com/archives/CDXAKMGTU/p1690830621077679
This ends up being because the `addTracingHeadersToFetchRequest` attempts to use the transaction instead of the active request span to generate the outgoing `sentry-trace` header.
This fixes that by adding the span to the `addTracingHeadersToFetchRequest` method.
=> fix(tracing): Set correct parent span id on fetch sentry-trace header

packages/utils/src/stacktrace.ts, packages/utils/test/stacktrace.test.ts
As well as fixes the ordering of operations and removes some redundant code.
The stack should be trimmed _after_ filtering.
Fixes https://github.com/getsentry/sentry-javascript/issues/8396
=> fix(core): Filter internal API frames for synthetic frames

packages/node-integration-tests/package.json, packages/node-integration-tests/utils/run-tests.ts, yarn.lock
This PR adds a few improvements to the node integration tests:
* Re-add support for `-t` arg to filter for specific tests
* Re-add support for `--watch` flag
* Reduce logging for test suites where all tests were skipped. This makes running one specific (e.g. new or modified) test a much better experience locally as you don't have to go through 100s lines of unnecessary console output. Happy to even reduce it further to log nothing at all if reviewers prefer that. 
* Add `yargs` to parse arguments (and provide help)
Came up while modifying a node integration test for #8715 and finding out that running them locally is super annoying 😅
=> chore(node-integration-tests): Improve local testing experience

packages/node-integration-tests/suites/public-api/captureException/catched-error/test.ts, packages/node/src/integrations/contextlines.ts, packages/node/test/index.test.ts
This came up in https://github.com/getsentry/sentry-javascript/pull/8699#discussion_r1280867001, so let's fix it.
=> fix(node): Add availablility check on current hub to Node `ContextLines` integration

packages/nextjs/src/config/types.ts, packages/nextjs/src/config/withSentryConfig.ts, packages/nextjs/test/config/testUtils.ts, packages/nextjs/test/integration/next12.config.template
Modified one template to use the async function instead, as adding an additional variant to an already bloated integration test runner felt meh.
Note that type from https://github.com/getsentry/sentry-javascript/issues/7444 is incorrect.
It should be:
```js
const nextConfig = async () => {
/** @type {import('next').NextConfig} */
return {};
}
```
and not:
```js
/** @type {import('next').NextConfig} */
const nextConfig = async () => {
return {};
}
```
Note #2: async function handling works for `next >= 12.1` only: https://nextjs.org/docs/app/api-reference/next-config-js/pageExtensions
Verified the behavior locally using provided sample config from the original issue.
Fixes https://github.com/getsentry/sentry-javascript/issues/7444
=> ref: Allow withSentryConfig to accept async config function

packages/e2e-tests/README.md, packages/e2e-tests/test-applications/nextjs-app-dir/pages/api/async-context-edge-endpoint.ts, packages/e2e-tests/test-applications/nextjs-app-dir/tests/async-context-edge.test.ts, packages/nextjs/src/edge/asyncLocalStorageAsyncContextStrategy.ts, packages/nextjs/src/edge/index.ts
Adds the `AsyncLocalStorage` async context strategy to the Next.js edge SDK.
`AsyncLocalStorage` is available on the edge runtime.
yields
=> feat(nextjs): Add `AsyncLocalStorage` async context strategy to edge SDK

packages/replay/jest.setup.ts, packages/replay/src/eventBuffer/EventBufferProxy.ts, packages/replay/src/eventBuffer/WorkerHandler.ts, packages/replay/src/eventBuffer/index.ts, packages/replay/src/replay.ts, packages/replay/src/session/createSession.ts, packages/replay/src/session/fetchSession.ts, packages/replay/src/session/getSession.ts, packages/replay/src/types/replayFrame.ts, packages/replay/src/util/handleRecordingEmit.ts, packages/replay/src/util/log.ts, packages/replay/src/util/sendReplayRequest.ts
This streamlines & improves logging for replay status, adding more logs for certain things to be better able to see what's going on, and adapting the `traceInternals` setting to result in console breadcrumbs being added (which should show up both in replay and for e.g. sentry errors etc).
While at it I also fixed some `any` eslint warnings in replay.
ref: https://github.com/getsentry/sentry-javascript/issues/8400
=> ref(replay): Improve status logging

packages/replay/src/session/Session.ts, packages/replay/test/integration/errorSampleRate.test.ts
We haven't been persisting the `shouldRefresh` property of the session. This combined with the fact that we do not update the `sampled` field on the session to `session` when an error occurs, but keep it at `buffer`, means that if a user reloads the page or the session is otherwise re-fetched from sessionStorage, if previously an error occurs, we'll keep buffering forever again (like for a "fresh" buffer session), and if an error happens we convert it again to a `session` session, but since the session ID was never updated this will be "added" to the previous session instead.
I made a reproduction test that failed before and works after this fix.
Fixes https://github.com/getsentry/sentry-javascript/issues/8400
=> fix(replay): Ensure buffer sessions end after capturing an error

packages/replay/src/replay.ts, packages/replay/test/integration/errorSampleRate.test.ts
This does two things:
1. Ensure we switch the `recordingMode` only once, to avoid running this process twice if e.g. multiple errors happen
2. Do not update `session.started` property when switching buffer->session. We just keep started at whatever was the first event sent.
=> fix(replay): Ensure buffer->session switch is reliable

packages/replay/src/replay.ts, packages/replay/test/integration/flush.test.ts
This fix ensures that if we try to flush a replay that is too short, we will debounce flush it again after the min. duration is reached.
=> fix(replay): Ensure we debounce flush if replay too short

packages/browser-integration-tests/suites/integrations/Breadcrumbs/fetch/get/test.ts, packages/browser-integration-tests/suites/integrations/Breadcrumbs/fetch/post/test.ts, packages/browser-integration-tests/suites/integrations/Breadcrumbs/xhr/get/test.ts, packages/browser-integration-tests/suites/integrations/Breadcrumbs/xhr/post/test.ts
Hoping this unflakes some stuff...
Closes https://github.com/getsentry/sentry-javascript/issues/8717
=> test: Use `getLocalTestUrl` instead of `getLocalTestPath` for xhr tests

packages/replay/src/replay.ts, packages/replay/src/util/log.ts
This delays adding the internal replay logging breadcrumbs to the next tick, to avoid race conditions on initial logs where replay may not be initialized yet.
With this, you should get proper log breadcrumbs in a replay for itself:
```
[Replay] Created new session 00:00
[Replay] Starting replay in session mode 00:00
```
=> ref(replay): Improve internal logging

packages/tracing-internal/src/node/integrations/prisma.ts
`JSON.stringify` will throw when called on circular structures. This is an unnecessary risk in the prisma integration so we just log it plainly.
Ref: https://github.com/getsentry/sentry-javascript/issues/8532
=> ref(node): Don't call `JSON.stringify` on prisma client when logging

packages/replay/src/replay.ts
Not sure if this has an impact, but it makes sense to cancel debounce anyhow in the case where we are too long/short.
When we are too short, we schedule a new flush anyhow.
=> fix(replay): Cancel debounce when replay is too short/long

packages/replay/src/util/addEvent.ts
This _shouldn't_ happen, but it makes sense to guard so we only clear the event buffer cache on checkouts when in `buffer` mode. I guess the behavior of rrweb is not 100% defined in that it _cannot_ generate a new checkout in non-buffer mode 🤔 better safe than sorry.
FWIW I don't think that is the cause of our too-long-empty-replays issue right now, but 🤷 it doesn't hurt anyhow to be cautious here.
=> ref(replay): Ensure we only clear for buffer mode

packages/replay/src/eventBuffer/EventBufferArray.ts, packages/replay/src/eventBuffer/EventBufferCompressionWorker.ts, packages/replay/src/eventBuffer/EventBufferProxy.ts, packages/replay/src/replay.ts, packages/replay/src/session/fetchSession.ts, packages/replay/src/session/getSession.ts, packages/replay/src/types/replay.ts, packages/replay/src/util/addEvent.ts, packages/replay/src/util/log.ts, packages/replay/test/integration/flush.test.ts
We keep track of the eventBuffer contains a checkout, and if not, log a warning when trying to flush the initial segment.
If this turns out to be happening, we may think about aborting flushing or similar in this case. But for now, we can gather data.
=> ref(replay): Log warning if trying to flush initial segment without checkout

.craft.yml
Honestly, this is more a guess than anything else. Might be that we need to add `jobs.job_required_jobs_passed`, might be that it doesn't work at all. 
I tried reproducing which contexts are available by directly calling the GH API but it seems like I don't get any statuses for a given commit, regardless of if the commit's CI is currently running or completed. I guess we'll know soon enough once we release...
=> chore(ci): Add `job_required_jobs_passed` as a status provider context

.craft.yml
Our last publish run failed because `job_required_jobs_passed` was not found as a GH context. Let's continue the guessing game with `jobs.job_required_jobs_passed` which contradicts the craft documentation but is more in line with the GH context documentation. 
ref https://github.com/getsentry/craft/issues/482
=> chore(publish): Try different status provider context

.craft.yml
So, as explained in https://github.com/getsentry/craft/issues/482#issuecomment-1669812018 (+ the following messages), I believe that in addition to the default behaviour of Craft's GH status provider, also the [`contexts` feature](https://github.com/getsentry/craft#status-provider) is broken. It seems like the [GitHub API endpoint](https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28#get-the-combined-status-for-a-specific-reference) we use to get the combined statuses of a commit doesn't return statuses (where the contexts would be included) anymore and it always returns state  `pending` (which seems to be a [known issue](https://github.com/orgs/community/discussions/58407)). 
Considering that there is an annoying but proven workaround to this issue (namely to wait …
=> chore(publish): Remove status provider setting from Craft config

packages/node/src/integrations/context.ts, packages/types/src/context.ts, packages/types/src/index.ts
Resolves https://github.com/getsentry/sentry-javascript/issues/8747
Adds a bit of [cloud resource context](https://develop.sentry.dev/sdk/event-payloads/contexts/#cloud-resource-context) based on environment variables that may or may not be available in certain cloud environments.
Note that I didn't manually check all of these environment variables but based them off of stuff I've found on the internet. I tried to put links to the places where I found them but for some of them I lost the link. For these instances GitHub codesearch shows a few results though so I kinda trust them.
=> feat(node): Add basic cloud resource context

packages/replay/src/util/addEvent.ts, packages/replay/test/integration/errorSampleRate.test.ts, packages/replay/test/integration/flush.test.ts
This ensures we ignore any events being added which are after the session max age.
Maybe this helps with cases where we send weird replays with a single event much after initial timestamp.
I added a test to ensure this does not regress in buffer mode, where recording is continuous and _can_ be "forever".
=> ref(replay): Skip events being added too long after initial segment

packages/replay/src/coreHandlers/handleClick.ts, packages/replay/test/unit/coreHandlers/handleClick.test.ts
We assumed that the click debounce should only let one click per second through. however, that does not work if clicking different elements quickly (as it only debounces a single click/element). This adds a guard to ensure we only handle a single click breadcrumb per second.
Fixes https://github.com/getsentry/sentry/issues/54293
=> fix(replay): Handle multiple clicks in a short time

packages/replay/src/eventBuffer/EventBufferProxy.ts, packages/replay/src/util/addEvent.ts
1. Make sure it is correctly kept when doing the compression worker switchover
2. Make sure it is correctly set for `session` recordings
=> fix(replay): Fix `hasCheckout` handling

packages/replay/src/replay.ts, packages/replay/test/integration/flush.test.ts
Add another safeguard to avoid too-long replays, in the case where flushing takes too long.
=> fix(replay): Ensure we do not flush if flush took too long

packages/node-integration-tests/suites/tracing/auto-instrument/mysql/test.ts, packages/tracing-internal/src/node/integrations/mysql.ts
ref https://github.com/getsentry/sentry-javascript/issues/8771
Align mysql spans with https://github.com/open-telemetry/semantic-conventions/blob/main/docs/database/mssql.md
needed for starfish views.
=> feat(tracing): Add db connection attributes for mysql spans

packages/node-integration-tests/suites/tracing/auto-instrument/pg/test.ts, packages/tracing-internal/src/node/integrations/postgres.ts
ref https://github.com/getsentry/sentry-javascript/issues/8771
Align postgres spans with https://github.com/open-telemetry/semantic-conventions/blob/main/docs/database/sql.md
needed for starfish views.
=> feat(tracing): Add db connection attributes for postgres spans

packages/browser-integration-tests/suites/replay/eventBufferError/template.html, packages/browser-integration-tests/suites/replay/eventBufferError/test.ts, packages/browser-integration-tests/utils/replayHelpers.ts, packages/replay/src/integration.ts, packages/replay/src/replay.ts, packages/replay/src/types/replay.ts, packages/replay/src/util/addEvent.ts, packages/replay/test/integration/flush.test.ts
In our `stop()` method, we always tried to force a final flush when in `session` mode. 
However, that may lead to weird behaviour when we internally `stop()` due to a failure - e.g. think a send replay request fails, we do not want to force a flush again in that case.
Note that in tests this seems to be generally passing because `flush()` usually has a running `_flushLock` at this time and thus does not attempt to flush again immediately but only schedules a flush later. I added a test that properly failed for this before and is now fixed.
=> fix(replay): Ensure we do not try to flush when we force stop replay

packages/nextjs/src/config/loaders/wrappingLoader.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/8798
In our logic that injects the Sentry config files to be executed, `path.relative()` may return something like `sentry.server.config.js` which is not allowed. Imports from the current directory need to start with './'. This is why we prepend the path with './', which should always again be a valid relative path.
=> fix(nextjs): Ensure imports are valid relative paths

packages/nextjs/src/config/templates/pageWrapperTemplate.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/8792
In https://github.com/getsentry/sentry-javascript/issues/8792 a user reports that we read `getInitialProps` from `undefined`. The only place where we read `getInitialProps` is in the page wrapper template. As a fix we simply check for its existence before accessing the field. We don't fully know yet how this can happen, but I guess it can't hurt to introduce this check.
=> fix(nextjs): Check for existence of default export when wrapping pages

packages/nextjs/src/config/templates/sentryInitWrapperTemplate.ts
Injecting the Sentry config code failed when there wasn't a default export in a file that is supposed to be wrapped (e.g. a middleware file that only has a `middleware` export).
This PR fixes this by accessing the `.default` property dynamically and either re-exporting the default export or `undefined`.
=> fix(nextjs): Only re-export default export if it exists

packages/core/src/tracing/index.ts, packages/core/src/tracing/trace.ts, packages/core/test/lib/tracing/trace.test.ts, packages/node/src/index.ts, packages/serverless/src/index.ts, packages/sveltekit/src/server/index.ts
ref https://github.com/getsentry/sentry-javascript/issues/8724
```ts
const result = Sentry.startActiveSpan({ name: importantThing }, async () => {
await someWork();
return Sentry.startActiveSpan({ op: 'db', name: 'query-stuff' }, () => expensiveQuery());
});
// result === expensiveQuery() 
```
=> feat(core): Introduce `Sentry.startActiveSpan` and `Sentry.startSpan`

packages/sveltekit/src/server/load.ts, packages/sveltekit/test/server/load.test.ts
As reported in #8610, our SvelteKit SDK caused server load data to be invalidated, resulting in said functions being called on every route change. I initially thought this was related to our Kit-specific client fetch instrumentation which turned out not to be causing this. Instead, the culprit is our `wrapServerLoadWithSentry` wrapper:
In the wrapper, we access `event.route.id` to determine the route of the load function for the span description. Internally, SvelteKit puts a proxy on certain `event` properties, such as `event.route`. In case any property of `event.route` was accessed, [SvelteKit marks this](https://github.com/sveltejs/kit/blob/e133aba479fa9ba0e7f9e71512f5f937f0247e2c/packages/kit/src/runtime/server/page/load_data.js#L111-L124) internally and send along a flag to the …
=> fix(sveltekit): Avoid invalidating data on route changes in `wrapServerLoadWithSentry`

packages/core/src/hub.ts
Closes #8624
For SDKs where it's required to call `addTracingExtensions()`, ie. the browser, is it still important to call it before init?
=> fix(node): More relevant warning message when tracing extensions are missing

.github/workflows/flaky-test-detector.yml
This should cut down on the `yarn install` step.
Take a look at these two runs:
[Uncached](https://github.com/getsentry/sentry-javascript/actions/runs/5822280069/job/15786564103) - 4s setup node + 3m8s to yarn install (2m 31s post setup node to save cache)
[Cached](https://github.com/getsentry/sentry-javascript/actions/runs/5822280069/job/15793082951) - 42s setup node + 1m42s to yarn install
=> feat(ci): Cache `node_modules` in flaky test detector

packages/nextjs/src/edge/asyncLocalStorageAsyncContextStrategy.ts, packages/node/src/async/hooks.ts
Attempts to fix the memory leak reported in https://github.com/getsentry/sentry-javascript/issues/8829 by memoizing the `AsyncLocalStorage` instance we create when setting the async context strategy.
Note for reviewers: Can you think of any problems this may cause?
=> fix: Memoize `AsyncLocalStorage` instance

packages/browser-integration-tests/suites/replay/customEvents/test.ts
Force a flush after each click, otherwise its possible that we have a flush inbtween the 3 clicks.
=> test(replay): Fix flakes from `customEvents`

packages/sveltekit/src/server/handle.ts
(This bug didn't impact anyone as the fetch proxy script wasn't released yet)
=> fix(sveltekit): Remove invalid return in fetch proxy script

packages/angular-ivy/package.json, packages/angular/package.json
Angular `build:transpile` actually depends on types, so we need to reflect that - otherwise, `yarn build:dev` fails if no types are built yet.
Steps to reproduce:
```sh
yarn clean
yarn build:dev
```
Used to fail before this.
Supersedes https://github.com/getsentry/sentry-javascript/pull/8840
=> build(angular): Fix Nx dependency graph for Angular

packages/tracing-internal/src/browser/request.ts
This removes a type cast for the performance observer and actually adds some guards to make sure we do not run into cases where a property we expect to exist does not exist.
It seems we sometimes ran into cases where `nextHopProtocol` would be `undefined`, not a string, leading to https://github.com/getsentry/sentry-javascript/blob/develop/packages/tracing-internal/src/browser/request.ts#L202 failing.
I now specifically check for the existence of this property, as well as also adding a default for all the time based stuff (0) to ensure these also work in the case one of the fields does not exist (instead of checking for existence of all of them).
Closes https://github.com/getsentry/sentry-javascript/issues/8870
Closes https://github.com/getsentry/sentry-javascript/issues/8863
=> fix(tracing): Better guarding for performance observer

packages/nextjs/package.json, packages/nextjs/src/config/loaders/wrappingLoader.ts
Fixes build error reported in https://github.com/getsentry/sentry-javascript/issues/8133#issuecomment-1689040367
=> fix(nextjs): Fix `requestAsyncStorageShim` path resolution on windows

packages/node/src/integrations/http.ts, packages/sveltekit/test/client/sdk.test.ts, packages/tracing-internal/src/browser/browsertracing.ts, packages/tracing-internal/src/browser/request.ts
This PR deprecates `BrowserTracing`'s `tracePropagationTargets` option in favour of the top-level Sentry.init option. 
When introducing Tracing without Performance, we opted to [promote `tracePropagationTargets` to a top-level option](https://github.com/getsentry/sentry-javascript/pull/8395). We deprecated the integration-level option in Node's `Http` integration but not in `BrowserTracing`. This PR fixes that.
I also adjusted #6230 accordingly
(+ some minor JSdoc adjustments)
closes #8851
=> ref(tracing-internal): Deprecate `tracePropagationTargets` in `BrowserTracing`

packages/core/src/scope.ts, packages/hub/test/scope.test.ts, packages/node/test/integrations/http.test.ts, packages/tracing-internal/src/browser/browsertracing.ts, packages/types/src/tracing.ts, packages/utils/src/tracing.ts
Currently, since the introduction of "Tracing without Performance", we always set a negative sampling decision on the tracing context when there is not an active transaction. This could get problematic because we might overrule the sampling decisions for all downstream SDKs when there are no active transactions and when we're the head-SDK.
[Per spec](https://develop.sentry.dev/sdk/performance/#header-sentry-trace), it is allowed to leave away the sampling decision in the `sentry-trace` header. The use-case for this is to defer the sampling decision, which is exactly what we want to do.
=> fix: Defer tracing decision to downstream SDKs when using SDK without performance

packages/integrations/src/captureconsole.ts, packages/integrations/test/captureconsole.test.ts, packages/node/src/integrations/console.ts, packages/utils/src/instrument.ts
While looking into logger issues, I noticed that we fill console.xxx multiple times. This PR changes that so that we use the console instrumentation from utils in all cases.
=> ref: Use consistent console instrumentation

packages/sveltekit/src/vite/autoInstrument.ts, packages/sveltekit/test/vite/autoInstrument.test.ts
In our auto instrumentation Vite plugin for SvelteKit, we read `+(page|layout)(.server).(js|ts)` files' code to determine if we should add our wrapper to the file or not. We previously didn't check for a file id's existence before reading the file if the id matched that certain pattern, wrongly assuming that these ids would always map to actually existing files. 
It seems like Vite plugins such as Houdini's plugin add file ids to the build for files that actually don't exist (#8846, #8854) . When our plugin's `load` hook was called for such an id, it then tried to access and read the file which caused a build error.
This patch now adds a file existence guard to ensure we simply no-op for these files. 
(Wild guess: Houdini adds `load` functions for all (some?) routes so that it can do its …
=> fix(sveltekit): Ensure target file exists before applying auto instrumentation

packages/browser/src/client.ts, packages/browser/src/integrations/breadcrumbs.ts, packages/core/src/baseclient.ts, packages/types/src/client.ts
Noticed that this is a bit tightly coupled in the browser client, and could be simplified by using a hook.
=> ref(browser): Refactor sentry breadcrumb to use hook

packages/nextjs/package.json, packages/nextjs/src/config/loaders/wrappingLoader.ts, packages/nextjs/src/config/templates/requestAsyncStorageShim.ts, packages/nextjs/src/config/templates/serverComponentWrapperTemplate.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/8884
Hot fix for bug caused by https://github.com/getsentry/sentry-javascript/pull/8875
=> fix(nextjs): Fix `package.json` exports

packages/browser-integration-tests/utils/replayHelpers.ts, packages/browser/src/index.ts, packages/replay/.eslintignore, packages/replay/.eslintrc.js, packages/replay/src/coreHandlers/handleClick.ts, packages/replay/src/index.ts, packages/replay/src/replay.ts, packages/replay/src/types/deprecated.ts, packages/replay/src/types/replay.ts, packages/replay/src/types/replayFrame.ts, packages/replay/src/types/rrweb.ts, packages/replay/src/util/createBreadcrumb.ts, packages/replay/src/util/handleRecordingEmit.ts, packages/replay/test/integration/errorSampleRate.test.ts, packages/replay/test/integration/eventProcessors.test.ts, packages/replay/test/integration/events.test.ts, packages/replay/test/integration/flush.test.ts, packages/replay/test/integration/rateLimiting.test.ts, packages/replay/test/integration/sendReplayEvent.test.ts, packages/replay/test/integration/session.test.ts, packages/replay/test/integration/stop.test.ts, packages/replay/test/mocks/mockRrweb.ts, packages/replay/test/unit/eventBuffer/EventBufferArray.test.ts, packages/replay/test/unit/eventBuffer/EventBufferCompressionWorker.test.ts, packages/replay/test/unit/eventBuffer/EventBufferProxy.test.ts, packages/replay/test/unit/util/addEvent.test.ts, packages/replay/test/unit/util/handleRecordingEmit.test.ts, packages/replay/test/utils/getTestEvent.ts
This renames & restructures the type exports from `@sentry/replay`.
We want to deprecate the `@sentry/replay` package eventually - users should import everything they need directly from e.g. `@sentry/browser` or `@sentry/react`.
For this to be possible, we need to re-export everything we need from the replay package in the browser package. However, due to the generic naming of some of the type exports, this may become confusing - so I renamed the type exports to `ReplayXXX` to make it clear what it is for. For now, the old types are still exported as well, but they are deprecated. Ideally you move directly to import from e.g. `@sentry/react` for them.
While at this, I also got rid of the rrweb-specific naming of types (they are not in PascalCase), as IMHO this does not _have_ to be fully …
=> ref(replay): Restructure event type export naming

packages/replay/src/replay.ts
Previously was attempting to take full snapshot when replay recording was not active.
Fixes https://github.com/getsentry/sentry-javascript/issues/8885
=> fix(replay): Resume replay recording if paused when session is expired

packages/browser-integration-tests/suites/public-api/debug/init.js, packages/browser-integration-tests/suites/public-api/debug/test.ts, packages/hub/test/scope.test.ts, packages/integrations/test/captureconsole.test.ts, packages/replay/test/mocks/resetSdkMock.ts, packages/utils/src/instrument.ts, packages/utils/src/logger.ts
Instead of https://github.com/getsentry/sentry-javascript/pull/8873, this tries to simplify the logger to avoid the global lookup.
If you have more than one utils, having multiple loggers would be the least of your problems. So IMHO no need to special case handle this, in the worst case logging should still work somehow 🤔 
Note some test code seems to rely on the global stuff the logger does, which required minor changes there.
This now relies on the `originalConsoleMethods` we keep in the console instrumentation, so no need to look for `__sentry_original__` anymore. If that doesn't exist, nothing to do for us (because we haven't instrumented the console).
Closes https://github.com/getsentry/sentry-javascript/issues/8741
=> ref: Avoid using global singleton for logger

packages/node-experimental/src/integrations/express.ts, packages/node-experimental/src/integrations/fastify.ts, packages/node-experimental/src/integrations/http.ts
Oops, `origin` cannot contain `-`, this was incorrect.
=> fix(node-experimental): Fix trace origins

packages/remix/src/utils/instrumentServer.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/8904
I don't know enough about remix to know if/when this can actually happen, but doesn't hurt to guard anyhow!
=> fix(remix): Guard against missing default export for server instrument

packages/browser/src/client.ts
This PR adds missing replay and profiling options to the `BrowserClientOptions` interface. Previously, we only exposed these types to `BrowserOptions`. This led to type errors for users who directly create a client, without using `Sentry.init` (as reported in #8857).
While one would think that `BrowserClientOptions` is basically a superset of `BrowserOptions` (leaving aside `stackparser`, `integrations` and `transport`) this is in fact not the case, which IMO is the core problem here. `BrowserClientOptions` only inherits the base `Options` (which are shared between browser and node), in addition to transport options. However, changing this so that, `BrowserClientOptions` inherits from `BrowserOptions` is a breaking change, so I opted to just add the missing options to …
=> fix(browser): Add replay and profiling options to `BrowserClientOptions`

packages/browser-integration-tests/suites/replay/errors/errorsInSession/init.js, packages/browser-integration-tests/suites/replay/largeMutations/mutationLimit/init.js, packages/browser-integration-tests/suites/replay/maxReplayDuration/init.js, packages/browser-integration-tests/suites/replay/maxReplayDuration/test.ts, packages/browser-integration-tests/suites/replay/minReplayDuration/init.js, packages/browser-integration-tests/suites/replay/sessionExpiry/init.js, packages/browser-integration-tests/suites/replay/sessionInactive/init.js, packages/browser-integration-tests/suites/replay/sessionMaxAge/init.js, packages/browser-integration-tests/suites/replay/sessionMaxAge/test.ts, packages/replay/src/constants.ts, packages/replay/src/integration.ts, packages/replay/src/replay.ts, packages/replay/src/session/loadOrCreateSession.ts, packages/replay/src/session/maybeRefreshSession.ts, packages/replay/src/types/replay.ts, packages/replay/src/util/addEvent.ts, packages/replay/src/util/isSessionExpired.ts, packages/replay/test/integration/errorSampleRate.test.ts, packages/replay/test/integration/flush.test.ts, packages/replay/test/integration/session.test.ts, packages/replay/test/unit/session/loadOrCreateSession.test.ts, packages/replay/test/unit/session/maybeRefreshSession.test.ts, packages/replay/test/unit/util/isSessionExpired.test.ts, packages/replay/test/utils/setupReplayContainer.ts, yarn.lock
This defaults to 60min, and is capped at max. 60min (=you cannot specify a longer max duration than 60min).
Closes https://github.com/getsentry/sentry-javascript/issues/8758
=> feat(replay): Allow to configure `maxReplayDuration`

packages/remix/scripts/createRelease.js
Added instructions for cases where a version can't be proposed by `sentry-upload-sourcemaps`.
=> chore(remix): Add instructions when a release version can't be proposed.

packages/node-experimental/src/integrations/express.ts, packages/node-experimental/src/integrations/fastify.ts, packages/node-experimental/src/integrations/graphql.ts, packages/node-experimental/src/integrations/http.ts, packages/node-experimental/src/integrations/mongo.ts, packages/node-experimental/src/integrations/mongoose.ts, packages/node-experimental/src/integrations/mysql2.ts, packages/node-experimental/src/integrations/postgres.ts, packages/node-experimental/src/utils/addOriginToSpan.ts, packages/opentelemetry-node/src/index.ts, packages/opentelemetry-node/src/spanprocessor.ts, packages/opentelemetry-node/src/utils/spanData.ts
I noticed that we kind of extended the public API by exporting some things from opentelemetry-node that we need in node-experimental. I am deprecating these internals as I'm refactoring some things to be a bit cleaner IMHO. 
The one export we actually need outside I am exporting as `_INTERNAL_getSentrySpan` to make it clear this is not meant to be used otherwise. The main reason I am not just exporting this is that this _may_ have to change if we change how we internally store/handle spans - e.g. if we move away from the map this is just not possible to have anymore, and I do not want to lock us into having to support this in the future.
=> ref(node-otel): Avoid exporting internals & refactor attribute adding

packages/e2e-tests/test-applications/nextjs-app-dir/.gitignore, packages/e2e-tests/test-applications/nextjs-app-dir/event-proxy-server.ts, packages/e2e-tests/test-applications/nextjs-app-dir/package.json, packages/e2e-tests/test-applications/nextjs-app-dir/tests/edge-route.test.ts, packages/e2e-tests/test-applications/nextjs-app-dir/tests/middleware.test.ts, packages/e2e-tests/test-applications/sveltekit/event-proxy-server.ts
This PR makes our E2E test proxy decode gzipped envelopes.
This change is motivated by Next.js compressing requests in dev mode 🤷‍♂️. It also lets us re-enable a few tests I thought were just broken.
=> test(e2e): Decode gzipped envelopes in E2E tests

packages/node-experimental/src/index.ts, packages/node-experimental/src/sdk/trace.ts, packages/opentelemetry-node/src/spanprocessor.ts
This re-implements the new performance APIs:
* `startActiveSpan`
* `startSpan`
* `getActiveSpan`
In `@sentry/node-experimental`, where these delegate to OTEL under the hood.
I tried to make sure to have _exactly_ the same APIs as we have for these functions without this. There are some caveats with this:
* calling `span.finish()` may behave in unexpected ways - it is not supported to manually finish a span.
* Calling `scope.getSpan()` will not work
* Calling `span.startSpan()` will not work
Basically, only the top level exported methods work, nothing else.
=> feat(node-experimental): Implement new performance APIs

packages/node-experimental/package.json, packages/node-experimental/src/sdk/init.ts, packages/node-experimental/src/sdk/initOtel.ts, packages/node-experimental/src/sdk/otelAsyncContextStrategy.ts, packages/node-experimental/src/sdk/otelContextAsyncContextStrategy.ts, packages/node-experimental/src/sdk/otelContextManager.ts, yarn.lock
This PR implements a strategy to sync the OpenTelemetry Context with our own Hub forking for AsyncContext.
This works by fully relying on OpenTelemetry to handle async context isolation/forking.
1. We implement a custom OTEL ContextManager that wraps the default AsyncHooks manager, but makes sure to also fork the hub for each context change & puts the hub on the OTEL context so we can retrieve it.
2. Then, we also have a custom Sentry AsyncContextStrategy which just refers to OTEL context and picks the hub from there we put there in 1.
This means we do not need to do any context forking ourselves anymore, so no need for e.g. `Sentry.Handlers.requestHandler()` and stuff like this.
It _should_ also mean that Sentry & OTEL should be as in sync as possible.
Some notes:
* Currently only works …
=> feat(node-experimental): Sync OTEL context with Sentry AsyncContext

packages/vue/src/errorhandler.ts, packages/vue/src/router.ts, packages/vue/test/router.test.ts
This PR addresses the mechanisms set in the Vue package, more concretely in
* our Vue error handler 
* our Vue routing instrumentation
ref #6073
=> feat(vue): Mark errors caught in Vue wrappers as unhandled

packages/serverless/src/awslambda.ts, packages/serverless/src/gcpfunction/cloud_events.ts, packages/serverless/src/gcpfunction/events.ts, packages/serverless/src/gcpfunction/http.ts, packages/serverless/src/utils.ts, packages/serverless/test/awslambda.test.ts, packages/serverless/test/gcpfunction.test.ts
This PR addresses the mechanisms set in the Serverless package, more concretely in
* AWS Lambda handler
* GCP http, function, cloudEvent handlers
ref #6073
=> feat(serverless): Mark errors caught in Serverless handlers as unhandled

packages/react/src/errorboundary.tsx
This PR addresses the mechanisms set in the React package, more concretely in our `ErrorBoundary`. 
ref #6073
=> feat(react): Mark errors captured from ErrorBoundary as unhandled

packages/nextjs/src/common/_error.ts, packages/nextjs/src/common/utils/wrapperUtils.ts, packages/nextjs/src/common/wrapApiHandlerWithSentry.ts, packages/nextjs/src/common/wrapServerComponentWithSentry.ts
This PR addresses the mechanisms set in the NextJS package, more concretely in
* `captureUnderscoreException` 
* `wrapApiHandlerWithSentry`
* `callDataFetcherTraced`
* `withErrorInstrumentation`
* `wrapServerComponentWithSentry`
ref #6073
=> feat(nextjs): Mark errors caught from NextJS wrappers as unhandled

packages/remix/src/client/errors.tsx, packages/remix/src/utils/instrumentServer.ts, packages/remix/test/integration/test/client/errorboundary.test.ts, packages/remix/test/integration/test/server/action.test.ts, packages/remix/test/integration/test/server/loader.test.ts
This PR addresses the mechanisms set in the Remix package, more concretely in
* `captureRemixErrorBoundaryError` (TBD)
* `captureRemixServerException`
ref #6073
=> feat(remix): Mark errors caught from Remix instrumentation as unhandled

packages/browser-integration-tests/suites/integrations/httpclient/axios/test.ts, packages/browser-integration-tests/suites/integrations/httpclient/fetch/simple/test.ts, packages/browser-integration-tests/suites/integrations/httpclient/fetch/withRequest/test.ts, packages/browser-integration-tests/suites/integrations/httpclient/fetch/withRequestAndBodyAndOptions/test.ts, packages/browser-integration-tests/suites/integrations/httpclient/fetch/withRequestAndOptions/test.ts, packages/browser-integration-tests/suites/integrations/httpclient/xhr/test.ts, packages/integrations/src/captureconsole.ts, packages/integrations/src/httpclient.ts, packages/integrations/test/captureconsole.test.ts
This PR addresses the mechanisms set in the integrations package, more concretely in the 
* `HttpClient`
* `CaptureConsole`
integrations.
ref #6073
=> feat(integrations): Mark errors caught from `HttpClient` and `CaptureConsole` integrations as unhandled

packages/utils/src/instrument.ts, packages/utils/test/instrument.test.ts
- [ x ] If you've added code that should be tested, please add tests.
- [ x ] Ensure your code lints and the test suite passes (`yarn lint`) & (`yarn test`).
There are cases when global objects such as the window object are shimmed that they define properties such as `document`, but the actual value is undefined. This exact situation has been occurring and is causing the instrumentDOM function to throw an error as `'document' in WINDOW` is technically true though the value is falsey. We should rather attempt an actual check of the value being truthy rather than if the property is defined
=> fix(browser): Check for existence of instrumentation targets

packages/node-experimental/README.md
Update the docs for the current status of the POTEL experiment.
=> docs(node-experimental): Update readme for current status

packages/core/src/eventbuilder.ts, packages/core/src/index.ts, packages/core/src/server-runtime-client.ts, packages/core/test/lib/serverruntimeclient.test.ts, packages/utils/src/eventbuilder.ts, packages/utils/src/index.ts
ref: #8693
The `ServerRuntimeClient` is a near identical copy of the nextjs `EdgeClient`. To make it a direct replacement it has constructor options to override the event `platform`, `runtime`, and `server_name`.
This PR makes yet another copy of the Node `eventbuilder.ts` but after future PRs to remove the `EdgeClient` and make `NodeClient` extend `ServerRuntimeClient`, this will be the only copy. I've put the `eventbuilder` code in utils since some of these functions are used elsewhere outside of the clients and I don't want to export these from core and them become part of our public API. This is especially important since the browser SDK already exports it's own slightly different `exceptionFromError`.
=> feat(core): Add `ServerRuntimeClient`

packages/remix/scripts/prepack.ts
Fixes: #8946
New scripts we added with #8814 were missing in `PACKAGE_ASSETS` for prepacking.
I'll try to find a way to E2E test sourcemap upload scripts.
=> fix(remix): Add new sourcemap-upload script files to prepack assets.

packages/node-experimental/src/sdk/trace.ts, packages/node-experimental/test/helpers/mockSdkInit.ts, packages/node-experimental/test/sdk/init.test.ts, packages/node-experimental/test/sdk/trace.test.ts
For `Sentry.startSpan()` API, we need to ensure that when the Sentry Span is finished, we also finish the OTEL Span.
Also adding some tests for these APIs.
=> fix(node-experimental): Ensure `span.finish()` works as expected

packages/core/src/tracing/span.ts, packages/core/test/lib/tracing/span.test.ts, packages/core/test/lib/tracing/transaction.test.ts, packages/types/src/span.ts
In order to align `Span` & `Transaction` for usage in new performance APIs, this add `name` to the `Span` that also always returns a string.
=> feat(core): Add `name` to `Span`

packages/core/src/scope.ts
This is a micro improvement, but maybe worth it as we can have a lot of breadcrumbs. This ensures we only create a new breadcrumbs array if we exceed the limit.
In contrast, currently we'll always create two copies of the breadcrumbs for each added breadcrumb (first for the array spread, then we copy it through the slice), even if we don't really need to do this.
=> ref(core): Avoid unnecessary breadcrumbs array mutations

packages/nextjs/src/config/withSentryConfig.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/8931
Since the tunnel route usually goes through user's domains and our ingest endpoint has HSTS we were unintentionally promoting user's requests which are unrelated to Sentry to https. This PR fixes that by setting the `hsts=0` query param on the tunnel request to the ingest endpoint which will disable hsts for the responses as implemented in https://github.com/getsentry/ops/pull/7832.
Should wait for https://github.com/getsentry/ops/pull/7832 to land before merging.
=> fix(nextjs): Request for no HSTS in tunnel route endpoint

packages/utils/src/misc.ts, packages/utils/test/misc.test.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/8935
=> fix: uuidv4 fix for cloudflare

packages/core/src/scope.ts, packages/types/src/scope.ts
Making it easier to potentially change this e.g. for POTEL.
=> ref(core): Introduce protected `_getBreadcrumbs()` on scope

.github/workflows/build.yml, packages/e2e-tests/Dockerfile.publish-packages, packages/e2e-tests/package.json, packages/e2e-tests/test-applications/create-next-app/package.json, packages/e2e-tests/test-applications/create-next-app/playwright.config.ts, packages/e2e-tests/test-applications/create-react-app/package.json, packages/e2e-tests/test-applications/create-remix-app/package.json, packages/e2e-tests/test-applications/nextjs-app-dir/package.json, packages/e2e-tests/test-applications/nextjs-app-dir/playwright.config.ts, packages/e2e-tests/test-applications/node-express-app/package.json, packages/e2e-tests/test-applications/react-create-hash-router/package.json, packages/e2e-tests/test-applications/standard-frontend-react-tracing-import/package.json, packages/e2e-tests/test-applications/standard-frontend-react/package.json
Updated Node to v18 (LTS) on E2E tests.
This is needed to properly test Remix v2.
Ref: #8940
=> chore(e2e-tests): Use Node 18 for E2E tests.

packages/e2e-tests/test-applications/create-remix-app/upload-sourcemaps.sh, packages/remix/scripts/createRelease.js, packages/remix/scripts/sentry-upload-sourcemaps.js
=> feat(remix): Accept `org`, `project` and `url` as args to upload script

packages/core/src/integrations/inboundfilters.ts, packages/core/test/lib/integrations/inboundfilters.test.ts
Previously when event had a `message`, the SDK didn't look into the exception value to filter for `ignoreErrors`.
This PR changes the behaviour so that `event.message` and `exception.value` + `exception.` are always both considered for filtering.
Ref: https://github.com/getsentry/sentry-javascript/issues/2520
=> fix(core): Always use event message and exception values for `ignoreErrors`

packages/nextjs/src/common/utils/wrapperUtils.ts, packages/nextjs/src/common/wrapApiHandlerWithSentryVercelCrons.ts, packages/nextjs/src/config/loaders/wrappingLoader.ts, packages/nextjs/src/config/templates/pageWrapperTemplate.ts, packages/nextjs/src/index.types.ts, packages/nextjs/src/server/index.ts, packages/node/test/transports/http.test.ts, packages/node/test/transports/https.test.ts, packages/remix/src/utils/vendor/response.ts
This pollutes the console when running the linter, hopefully also speeds up CI a little bit.
=> ref: Cleanup lint warnings

MIGRATION.md
There was some confusion about this because the migration doc in this repo conflicts with the `highly experimental` tag we put on the README. Also added Node 18+ requirements.
We can change this in migr8 for a future release, but for now let's merge this in to reduce confusion and unblock our users.
=> chore: Update migration docs to indicate sentry-migr8 is experimental.

packages/overhead-metrics/src/perf/sampler.ts
Should fix failing CI on develop rn.
=> fix(overhead-metrics): Remove unneeded @ts-expect-error

packages/node-experimental/src/integrations/http.ts, packages/node-experimental/src/utils/getRequestSpanData.ts
This is a fork of https://github.com/getsentry/sentry-javascript/pull/8937, with only the "uncontroversial" stuff, mainly fixing that we only create HTTP breadcrumbs for _outgoing_ requests.
In addition, this also migrates to using `requestHook` and `responseHook` instead of `applyCustomAttributesOnSpan`. We may have to revisit this later, but these hooks seem to have a better context awareness (=they are called in a more reasonable OTEL context, which gives the callbacks there better access to scope data etc). However that means we cannot (easily) pass both request and response as breadcrumb hints - not sure how important that is to us... For now I'd say that's OK.
Note that also `requestHook` is only called when the request finishes, so we already have all the response OTEL span …
=> fix(node-experimental): Ensure we only create HTTP spans when outgoing

packages/browser/src/integrations/linkederrors.ts, packages/core/src/integration.ts, packages/node/src/integrations/linkederrors.ts, packages/types/src/integration.ts
A change to https://github.com/getsentry/sentry-javascript/pull/8956 based on feedback. 
I figured it makes sense to also pass the client (as in the one concrete example we have we actually need it 😅 ) - not sure if this should be the first or last argument, but IMHO you probably don't need this always and then it is nicer to have (event, hint) as the API...?
=> ref: Replace `setup` with `preprocessEvent` on Integration interface

packages/replay-worker/src/_worker.ts, packages/replay-worker/src/handleMessage.ts
Noticed warnings for this during build.
=> build(lint): Remove unneeded `@ts-expect` comments

packages/node-experimental/src/integrations/http.ts
We do filter these out in the span processor, but we can avoid all this work by not even generating OTEL spans at all for outgoing Sentry requests.
=> fix(node-experimental): Ignore outgoing Sentry requests

packages/browser/src/exports.ts, packages/core/src/tracing/index.ts, packages/core/src/tracing/trace.ts, packages/node/src/index.ts, packages/serverless/src/index.ts, packages/sveltekit/src/server/index.ts
Based on https://github.com/getsentry/sentry-javascript/pull/8911 and convos in slack, it was brought up that we might need to expose a method that works similar to `startSpan`, but that does not automatically finish the span at the end of the callback.
This is necessary when you have event emitters (`res.once`) or similar.
```ts
Sentry.startActiveSpanManual(ctx, (span, finish) => {
// do something with span
// when you're done, call finish()
finish();
});
```
=> feat(core): Introduce startSpanManual

packages/e2e-tests/test-applications/nextjs-app-dir/app/route-handlers/[param]/edge/route.ts, packages/e2e-tests/test-applications/nextjs-app-dir/app/route-handlers/[param]/error/route.ts, packages/nextjs/src/config/loaders/wrappingLoader.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/8977
Next.js moved the internal file we depend on to grab headers of incoming request so we need to check the new location.
=> fix(nextjs): Add new potential location for Next.js request AsyncLocalStorage

packages/node-experimental/src/integrations/postgres.ts
We do not want to create e.g. pool connection transactions etc (for now at least), so let's enable this flag.
=> fix(node-experimental): Require parent span for `pg` spans

.github/workflows/build.yml, packages/e2e-tests/test-applications/react-router-6-use-routes/.gitignore, packages/e2e-tests/test-applications/react-router-6-use-routes/.npmrc, packages/e2e-tests/test-applications/react-router-6-use-routes/package.json, packages/e2e-tests/test-applications/react-router-6-use-routes/playwright.config.ts, packages/e2e-tests/test-applications/react-router-6-use-routes/public/index.html, packages/e2e-tests/test-applications/react-router-6-use-routes/src/globals.d.ts, packages/e2e-tests/test-applications/react-router-6-use-routes/src/index.tsx, packages/e2e-tests/test-applications/react-router-6-use-routes/src/pages/Index.tsx, packages/e2e-tests/test-applications/react-router-6-use-routes/src/pages/User.tsx, packages/e2e-tests/test-applications/react-router-6-use-routes/src/react-app-env.d.ts, packages/e2e-tests/test-applications/react-router-6-use-routes/tests/behaviour-test.spec.ts, packages/e2e-tests/test-applications/react-router-6-use-routes/tests/fixtures/ReplayRecordingData.ts, packages/e2e-tests/test-applications/react-router-6-use-routes/tsconfig.json, packages/react/src/reactrouterv6.tsx
Fixes: https://github.com/getsentry/sentry-javascript/issues/8962
- Moved component creation outside of the wrapper, passing `location` and `routes` as props.
- Added a new test app for this use case.
=> fix(react): Switch to props in `useRoutes`

packages/core/src/tracing/index.ts
Is used in RN. 
I've noticed that it's not exported when using the older ts 3.8 types and I had to fix the path because the auto resolution only uses `index.ts`.
https://github.com/getsentry/sentry-react-native/pull/3277/files#diff-a40e0a9eea538ea7aa19d0dba8ff412404f62087741ecc695f38736adcebda2eL2
=> feat(core): Export `BeforeFinishCallback` type

packages/angular/src/tracing.ts, packages/nextjs/src/common/utils/edgeWrapperUtils.ts, packages/nextjs/src/common/wrapApiHandlerWithSentry.ts, packages/nextjs/src/common/wrapServerComponentWithSentry.ts, packages/node/src/handlers.ts, packages/react/src/profiler.tsx, packages/remix/src/utils/instrumentServer.ts, packages/remix/src/utils/serverAdapters/express.ts, packages/replay/src/util/addGlobalListeners.ts, packages/serverless/src/awsservices.ts, packages/serverless/src/google-cloud-grpc.ts, packages/serverless/src/google-cloud-http.ts, packages/tracing-internal/src/node/integrations/apollo.ts, packages/tracing-internal/src/node/integrations/graphql.ts, packages/tracing-internal/src/node/integrations/mongo.ts, packages/tracing-internal/src/node/integrations/mysql.ts, packages/tracing-internal/src/node/integrations/postgres.ts
We've changed this some time ago so that `hub.getScope()` _always_ returns a scope, so we can actually update our code where we still check for the existence of scope.
Noticed this will looking at some other stuff, may safe some bytes & complexity!
=> ref: Avoid unnecessary `hub.getScope()` checks

packages/node-experimental/src/sdk/initOtel.ts, packages/opentelemetry-node/src/index.ts, packages/opentelemetry-node/src/propagator.ts, packages/opentelemetry-node/src/spanprocessor.ts, packages/opentelemetry-node/src/utils/spanData.ts, packages/opentelemetry-node/src/utils/spanMap.ts, packages/opentelemetry-node/test/propagator.test.ts, packages/opentelemetry-node/test/spanprocessor.test.ts
**Update: This PR was updated with new behaviour.**
This PR updates the span reference cleanup to take into account if a span is/may still be referenced somewhere else.
Previously, whenever a span finished we removed the reference from the map, to clean up and avoid memory leaks.
However, it seems that sometimes spans are ended before a child span is started (at least the hooks may fire in this order). This leads to the potential case where a parent that _should_ exist cannot be found, thus creating a new transaction instead of a span.
With this change, we keep more information in our span map, in order to clear sub-spans (=not transactions) only when the root span (=transaction) is finished.
=> fix(node-otel): Refactor OTEL span reference cleanup

packages/node-experimental/src/integrations/http.ts
Similar to express, we want to ignore (incoming) OPTIONS & HEAD requests.
=> fix(node-experimental): Ignore OPTIONS & HEAD requests

packages/node-experimental/src/index.ts, packages/node-experimental/src/integrations/http.ts, packages/node-experimental/src/sdk/client.ts, packages/node-experimental/src/sdk/hub.ts, packages/node-experimental/src/sdk/initOtel.ts, packages/node-experimental/src/sdk/otelContextManager.ts, packages/node-experimental/src/sdk/scope.ts, packages/node-experimental/src/sdk/trace.ts, packages/node-experimental/src/types.ts
This implements an **experimental** way to handle breadcrumbs for the POTEL world.
This patches stuff so that we get the breadcrumbs from the root transaction, instead of from the scope. This is how it works:
* Patches `Scope.addBreadcrumb()` to fetch the current transaction, and if there is one, add breadcrumbs there
* Patches `Scope.getBreadcrumbs()` to fetch breadcrumbs from current transaction (if there is one)
* Patches hub stuff to ensure we always create a patched OtelScope
* Patches transaction in-place via `Proxy` to allow to store breadcrumbs on them.
* Patches `_prepareEvent` on the experimental node Client to ensure `captureContext` works
This means that for each isolated request (=that creates its own transaction), we'll keep the breadcrumbs in there. So _anything_ that …
=> feat(node-experimental): Keep breadcrumbs on transaction

packages/browser/src/integrations/breadcrumbs.ts, packages/utils/src/is.ts, packages/utils/src/normalize.ts, packages/utils/src/string.ts, packages/utils/test/is.test.ts, packages/utils/test/normalize.test.ts
=> fix(utils): Prevent iterating over VueViewModel

packages/integrations/src/debug.ts, packages/integrations/test/debug.test.ts
Instead we can ensure this is called after all processing finished via a hook. This does not actually process an event, so this is much cleaner.
=> ref(integrations): Do not use event processor for `Debug` integration

packages/node/package.json, yarn.lock
The current version of cookies includes several performance improvements.
https://github.com/jshttp/cookie/releases
And in general, I would like to bring the dependencies to the current versions in order to reduce duplication of the same dependencies, but with different versions.
Before:
```
├─┬ @sentry-internal/node-integration-tests@7.68.0 -> ./packages/node-integration-tests
│ └─┬ express@4.18.2
│   └── cookie@0.5.0
├─┬ @sentry/browser@7.68.0 -> ./packages/browser
│ └─┬ karma@6.3.16 invalid: "1 || 2 || 3 || 4" from node_modules/karma-typescript
│   └─┬ socket.io@4.5.3
│     └─┬ engine.io@6.2.0
│       └── cookie@0.4.2 deduped
├─┬ @sentry/node@7.68.0 -> ./packages/node
│ └── cookie@0.4.2
├─┬ @sentry/remix@7.68.0 -> ./packages/remix
│ └─┬ @remix-run/node@1.5.1
│   └─┬ …
```
=> chore(node): upgrade cookie to ^0.5.0

packages/core/src/baseclient.ts, packages/core/src/eventProcessors.ts, packages/core/src/index.ts, packages/core/src/integration.ts, packages/core/src/scope.ts, packages/core/src/utils/prepareEvent.ts, packages/core/test/lib/integration.test.ts, packages/types/src/client.ts, packages/types/src/integration.ts
This adds a new (optional) `processEvent` hook on the `Integration` interface, which allows to register an event processor **for the current client only**.
This has actually correct semantics in that the processor will only be registered for the client that the integration is added for. This is done by adding a new `addEventProcessor` method on the client, which for now are called after all global & scope event processors.
Previously, all integrations always registered a _global_ event processor, which is not really necessary. With this, we can be much more focused & also skip checking for existence of the integration on the client etc.
Supersedes https://github.com/getsentry/sentry-javascript/pull/9015
=> feat(core): Introduce `processEvent` hook on `Integration`

packages/node-experimental/src/sdk/hubextensions.ts, packages/node-experimental/src/sdk/scope.ts, packages/node-experimental/src/types.ts
This refactors the code for keeping breadcrumbs on transactions in node-experimental to instead patch `startTransaction` on the hub.
=> ref(node-experimental): Patch `startTransaction` for breadcrumbs

packages/node-integration-tests/suites/public-api/captureException/empty-obj/test.ts, packages/remix/test/integration/test/server/action.test.ts, packages/utils/src/eventbuilder.ts, packages/utils/test/eventbuilder.test.ts
Closes #6822
This PR changes the messages reported for captured non-Error exceptions.
For the [browser PR](https://github.com/getsentry/sentry-javascript/pull/8374), it was decided not to use the class name due to these being mangled by bundling. Does this apply to node too?
=> feat(node): Improve non-error messages

.github/workflows/build.yml, package.json, packages/bun/.eslintrc.js, packages/bun/LICENSE, packages/bun/README.md, packages/bun/jest.config.js, packages/bun/package.json, packages/bun/rollup.npm.config.js, packages/bun/scripts/install-bun.js, packages/bun/src/client.ts, packages/bun/src/index.ts, packages/bun/src/sdk.ts, packages/bun/src/transports/index.ts, packages/bun/src/types.ts, packages/bun/test/sdk.test.ts, packages/bun/tsconfig.json, packages/bun/tsconfig.test.json, packages/bun/tsconfig.types.json, packages/e2e-tests/verdaccio-config/config.yaml, packages/node/src/index.ts, scripts/node-unit-tests.ts, yarn.lock
Nice to have:
ref: https://github.com/getsentry/sentry-javascript/discussions/7979
Docs: https://github.com/getsentry/sentry-docs/pull/7858
Platform Icon: https://github.com/getsentry/platformicons/pull/102
=> feat: Add Bun SDK

.craft.yml
ref https://github.com/getsentry/sentry-javascript/issues/9042
Tell craft to publish `@sentry/bun`
=> chore: Add @sentry/bun to craft config

package.json, packages/e2e-tests/verdaccio-config/config.yaml, packages/vercel-edge/.eslintrc.js, packages/vercel-edge/LICENSE, packages/vercel-edge/README.md, packages/vercel-edge/jest.config.js, packages/vercel-edge/package.json, packages/vercel-edge/rollup.npm.config.js, packages/vercel-edge/src/async.ts, packages/vercel-edge/src/client.ts, packages/vercel-edge/src/index.ts, packages/vercel-edge/src/sdk.ts, packages/vercel-edge/src/transports/index.ts, packages/vercel-edge/src/transports/types.ts, packages/vercel-edge/src/types.ts, packages/vercel-edge/src/utils/vercel.ts, packages/vercel-edge/test/transports/index.test.ts, packages/vercel-edge/tsconfig.json, packages/vercel-edge/tsconfig.test.json, packages/vercel-edge/tsconfig.types.json, scripts/node-unit-tests.ts, yarn.lock
ref https://github.com/getsentry/sentry-javascript/issues/8087
This PR adds a `@sentry/vercel-edge` SDK that can be used by our Next.js or Sveltekit SDKs for edge runtime support.
People can also use this standalone 
There is a TODO to figure out how to test this with edge runtime environment, but I'll address this in a follow up PR.
=> feat(vercel-edge): add Vercel Edge Runtime package

packages/e2e-tests/test-applications/nextjs-app-dir/app/route-handlers/[param]/edge/route.ts, packages/e2e-tests/test-applications/nextjs-app-dir/app/route-handlers/[param]/error/route.ts
Next.js introduced type checking for the return values of API routes which failed on the routes where we returned errors. This PR fixes that.
=> test(e2e): Fix typing in error routes in Next.js e2e tests

packages/sveltekit/src/index.types.ts
`handleErrorWithSentry`, which is wrapper function, should be identity function (`f(x) => x`).
Implementation is fine, just the type mismatch from implementation.
https://github.com/getsentry/sentry-javascript/blob/cd0bc3b58d4f4144783997d446eeff960c29b8d2/packages/sveltekit/src/server/handleError.ts#L22-L41
=> fix(sveltekit): Adjust `handleErrorWithSentry` type

packages/vercel-edge/package.json
Seems there was a leftover from `@sentry/core` in the new `@sentry/vercel-edge` package which caused our release preparation script to fail when bumping the package versions. 
I think we should be good to directly merge this into master as master will resync into develop after the release 🤞
=> fix(publish): Remove version command from vercel-edge package

packages/core/src/utils/prepareEvent.ts, packages/node/test/manual/release-health/runner.js, packages/node/test/manual/release-health/session-aggregates/aggregates-disable-single-session.js
Even if no scope is passed.
I guess this is kind of behavior changing, but I'd argue it is just fixing an unexpected behaviour that's not actually intuitive/logical - that global event processors are only applied if a scope is provided.
I extracted this out from https://github.com/getsentry/sentry-javascript/pull/9032, as I figured this is actually a reasonable change on it's own, so it's easier to reason about this in it's own PR.
=> fix(core): Ensure global event processors are always applied to event

packages/core/src/scope.ts, packages/core/src/utils/prepareEvent.ts
I noticed that while from an API POV the current behavior makes kind-of sense IMHO:
1. Run global event processors
2. Run scope event processors
3. Run client event processors
It is potentially breaking, as if we rewrite integrations to use the new client processors, their processing will run after any user global event processors, leading to potentially unexpected outcomes.
So this PR changes this to instead run them in this order:
1. Run client event processors
2. Run global event processors
3. Run scope event processors
Which should be more stable for now. 
In v8, we should update this to run a more sensible order:
1. Global
2. Client
3. Scope
=> fix(core): Run client eventProcessors before global ones

packages/react/src/reactrouterv6.tsx, packages/react/test/reactrouterv6.4.test.tsx
Fixes: #9061
Following up: https://github.com/getsentry/sentry-javascript/pull/8457 which apparently did not cover parameterized paths.
=> fix(react): Compare location against `basename`-prefixed route.

packages/bun/README.md, packages/node-experimental/README.md, packages/node/README.md, packages/vercel-edge/README.md
CJS/ESM has nothing to do with ES5 or ES6
=> docs: Fix comments describing different import styles in readme

.craft.yml
depends on https://github.com/getsentry/sentry-release-registry/pull/119 merging in
ref https://github.com/getsentry/sentry-javascript/issues/9042
=> chore: publish bun to release registry

packages/bun/src/index.ts, packages/bun/src/integrations/bunserver.ts, packages/bun/src/integrations/index.ts, packages/bun/src/sdk.ts, packages/bun/test/helpers.ts, packages/bun/test/integrations/bunserver.test.ts, packages/bun/tsconfig.test.json
ref https://github.com/getsentry/sentry-javascript/issues/9042
Add automatic instrumentation for `Bun.serve`
Simply do something like so:
```ts
import * as Sentry from '@sentry/bun';
Sentry.init({
dsn: Bun.env.SENTRY_DSN,
});
// later
Bun.serve({
async fetch() {
await new Promise((resolve) => setTimeout(resolve, 1000));
throw new Error("An Error from Bun!");
return new Response("Bun!");
},
});
```
and then get:
Link: https://sentry-sdks.sentry.io/discover/abhi-sentry-bun:f2e553067c7f49d58624963ca5e544ae/?field=title&field=event.type&field=project&field=user.display&field=timestamp&field=replayId&homepage=true&name=All+Events&project=4505841905238016&query=&sort=-timestamp&statsPeriod=1h&yAxis=count%28%29
Follow up note. We probably want to export a set of utilities …
=> feat(bun): Instrument Bun.serve

packages/react/src/errorboundary.tsx
Previously, the error name would always be `React ErrorBoundary Error`,  because `errorBoundaryError.name` refers to the name of the Error object that was just created.
=> fix(react): Add actual error name to boundary error name

packages/node-experimental/src/constants.ts, packages/node-experimental/src/opentelemetry/contextManager.ts, packages/node-experimental/src/sdk/initOtel.ts, packages/node-experimental/src/sdk/otelAsyncContextStrategy.ts
To keep things better together, and in preparation for follow up PRs with more OTEL-specific stuff.
Nothing functionally changes here, this is just to keep follow up PRs more readable as there is a lot going on...
=> ref(node-experimental): Reorder files into `opentelemetry` folder

packages/opentelemetry-node/src/spanprocessor.ts, packages/opentelemetry-node/src/utils/captureExceptionForTimedEvent.ts, packages/opentelemetry-node/test/utils/captureExceptionForTimedEvent.test.ts
Also add tests for this. This can then be reused e.g. by node-experimental in a later step.
=> ref(opentelemetry-node): Extract `maybeCaptureExceptionForTimedEvent`

packages/nextjs/src/config/loaders/wrappingLoader.ts, packages/nextjs/src/config/types.ts, packages/nextjs/src/config/webpack.ts
Attempts to fix https://github.com/getsentry/sentry-javascript/issues/9092
I could never reproduce that issue but my suspicion for that error is that somewhere in the node module resolution tree there is a nextjs installation which will make `next/dist/client/components/request-async-storage` resolve.
We probably need to limit the module resolution search by what webpack itself is looking for. We can do this by looking at `webpackConfig.resolve.modules` which contains all the resolution paths.
This is not a 100% probability fix but something that is worth trying.
=> fix(nextjs): Use webpack module paths to attempt to resolve internal request async storage module

packages/node/src/integrations/undici/types.ts, packages/node/src/requestdata.ts, packages/node/test/async/domain.test.ts, packages/node/test/async/hooks.test.ts, packages/node/tsconfig.json
I've been having issues with the `setTimeout` return type in the node SDK, mostly when running tests:
```
Property 'unref' does not exist on type 'number'.
```
It turns out we've got dom lib types in the base tsconfig which means these have ended up in node SDK. 
This PR ensures we only have `es6` and no dom lib types and then fixes all the resulting errors.
=> fix(node): Remove dom lib types

packages/nextjs/src/config/webpack.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/9092
In our previous attempt of fixing we used `require.resolves`' `paths` option which we wanted to limit the locations with to check for the availability of Next.js `RequestAsyncStorage` module.
Unfortunately, `require.resolve` will always check "global" node_modules for when resolving, which means that (old) global installations of Next.js would have still been picked up.
With this PR we additionally check for whether the resolved path would be within the locations webpack would check for resolving the module. This way we shouldn't pick up any global installations of Next.js.
=> fix(nextjs): Filter `RequestAsyncStorage` locations by locations that webpack will resolve

packages/browser-integration-tests/suites/replay/bufferMode/test.ts, packages/browser-integration-tests/suites/replay/captureConsoleLog/test.ts, packages/browser-integration-tests/suites/replay/errors/errorMode/test.ts, packages/browser-integration-tests/suites/replay/largeMutations/defaultOptions/test.ts, packages/browser-integration-tests/suites/replay/largeMutations/mutationLimit/test.ts, packages/browser-integration-tests/suites/replay/maxReplayDuration/test.ts, packages/browser-integration-tests/suites/replay/multiple-pages/test.ts, packages/browser-integration-tests/suites/replay/requests/test.ts, packages/browser-integration-tests/suites/replay/slowClick/clickTargets/test.ts, packages/browser-integration-tests/suites/replay/slowClick/disable/test.ts, packages/browser-integration-tests/suites/replay/slowClick/ignore/test.ts, packages/browser-integration-tests/suites/replay/slowClick/multiClick/test.ts, packages/browser-integration-tests/suites/replay/slowClick/mutation/test.ts, packages/browser-integration-tests/suites/replay/slowClick/scroll/test.ts, packages/browser-integration-tests/suites/replay/slowClick/timeout/test.ts, packages/browser-integration-tests/suites/replay/slowClick/windowOpen/test.ts
Resolves: https://github.com/getsentry/sentry-javascript/issues/8975
Refactored most flaky replay tests to `Promise.all` pattern to reduce flakiness.
=> ref(tests): Update replay integration tests to avoid flakes.

packages/nextjs/src/config/loaders/wrappingLoader.ts
Fixes bug reported in https://github.com/getsentry/sentry-javascript/issues/9092#issuecomment-1736144117
This code path is in theory an invariant but people seem to be hitting it and the _fallback_ started failing because the path was wrong.
=> fix(nextjs): Fix `RequestAsyncStorage` fallback path

packages/node/src/integrations/utils/http.ts, packages/node/test/integrations/http.test.ts
Currently, span data is missing for Node.js requests created with options object as the only argument, such as `http.request(options)`.
=> fix(node): fill in span data from http request options object

packages/core/src/tracing/transaction.ts
This makes it easier to extend the transaction (e.g. for POTEL) and make use of the _finishing_ code without actually sending the transaction to sentry.
This is needed for https://github.com/getsentry/sentry-javascript/pull/9085.
=> ref(core): Split transaction `finish` into underlying `_finishTransaction`

packages/opentelemetry-node/src/spanprocessor.ts
This should ensure that https://github.com/getsentry/sentry-javascript/issues/9127 is fully fixed, and no otel instrumentation picks anything up (hopefully) for closed spans.
A more _complete_ solution would be to wrap the transport with this, to also skip capturing for errors etc 🤔 But that would require more configuration on the users side.
=> fix(node-otel): Suppress tracing for generated sentry spans

packages/sveltekit/src/client/load.ts
This PR fixes a data invalidation issue that appeared on the client side when auto-instrumenting or manually wrapping universal `load` functions. Because our `wrapLoadWithSentry` function accessed `event.route.id`, the data returned from `load` would be invalidated on a route change. As reported in #8818 , this caused prefetched, actually valid data to be invalidated during the navigation to the page, causing another `load` invocation.  
To avoid this invalidation, we change the way how we read the route.id, to first use `Object.getOwnPropertyDescriptor` which doesn't trigger the proxy that listens to accesses. This, however, will only work for `@sveltejs/kit>=1.24.0` which includes a [change](https://github.com/sveltejs/kit/pull/10576) to the Kit-internal proxy. For older versions of …
=> fix(sveltekit): Avoid data invalidation in wrapped client-side `load` functions

packages/node/src/anr/index.ts
Closes #9146
I did try to use `await import('inspector')` but I get:
`Dynamic imports are only supported when the '--module' flag is set to 'es2020', 'es2022', 'esnext', 'commonjs', 'amd', 'system', 'umd', 'node16', or 'nodenext'. ts(1323)`
It looks like we don't have any module target in the tsconfig.
=> fix(node): Only require `inspector` when needed

packages/core/src/tracing/hubextensions.ts, packages/core/src/tracing/index.ts, packages/core/src/tracing/sampling.ts
This extracts the `sampleTransaction` method out and exports this from `core` so we can use it for POTEL (where we build transactions differently).
This is needed for https://github.com/getsentry/sentry-javascript/pull/9085.
=> feat(core): Extract `sampleTransaction` method out

packages/sveltekit/README.md
The previous link resulted in a 404 error: https://github.com/getsentry/sentry-javascript-bundler-plugins/blob/main/packages/vite-plugin/README.md#configuration
I have changed it to the npm link with all options: https://www.npmjs.com/package/@sentry/vite-plugin
Could also use this link: https://github.com/getsentry/sentry-javascript-bundler-plugins/blob/main/packages/vite-plugin/README_TEMPLATE.md but it does not seem well maintained
=> chore: Update vite plugin link

packages/angular-ivy/src/sdk.ts, packages/angular/src/sdk.ts, packages/nextjs/src/client/index.ts, packages/nextjs/src/edge/index.ts, packages/nextjs/src/server/index.ts, packages/react/src/sdk.ts, packages/serverless/src/awslambda.ts, packages/serverless/src/gcpfunction/index.ts, packages/svelte/src/sdk.ts
In various places we mutate the `options` passed to `init()`, which is a) not a great pattern and b) may break if users pass in frozen or similar objects (for whatever reason).
I also normalized this to ensure a passed in `_metadata.sdk` always takes precedent (we had this in most places, but not all).
Closes https://github.com/getsentry/sentry-javascript/issues/9155
=> fix: Ensure we never mutate options passed to `init`

packages/serverless/src/awslambda.ts
This is unused since v6 but we never got around to actually remove this, so let's properly deprecate this for v8.
=> ref(serverless): Properly deprecate `rethrowAfterCapture` option

packages/eslint-config-sdk/package.json, packages/eslint-config-sdk/src/index.js, yarn.lock
There were some bugs in the previous version where deprecated messages would show up as `[object Object]` instead of showing the actual deprecation messages. bumping this to 1.5.0 fixes this. (esp. https://github.com/gund/eslint-plugin-deprecation/releases/tag/v1.3.1 is important for us)
This is what it looks like right now, without bumping this:
=> build(lint): Bump `eslint-plugin-deprecation` to 1.5.0

packages/integrations/src/contextlines.ts, packages/integrations/src/dedupe.ts, packages/integrations/src/extraerrordata.ts, packages/integrations/src/rewriteframes.ts, packages/integrations/src/sessiontiming.ts, packages/integrations/src/transaction.ts, packages/integrations/test/dedupe.test.ts
This refactors pluggable integrations to use `processEvent`.
=> ref(integrations): Refactor pluggable integrations to use `processEvent`

packages/browser/src/exports.ts, packages/bun/src/index.ts, packages/core/src/tracing/index.ts, packages/core/src/tracing/trace.ts, packages/core/test/lib/tracing/trace.test.ts, packages/node/src/index.ts, packages/serverless/src/index.ts, packages/sveltekit/src/server/index.ts, packages/vercel-edge/src/index.ts
This adds a new `continueTrace` method which can be used to continue a trace from headers.
This method has the following signature:
```ts
function continueTrace<V>(
{
sentryTrace,
baggage,
}: {
sentryTrace: Parameters<typeof tracingContextFromHeaders>[0];
baggage: Parameters<typeof tracingContextFromHeaders>[1];
},
callback: (transactionContext: Partial<TransactionContext>) => V,
): V
```
In practice, this can be used like this:
```js
const transaction = continueTrace({ sentryTrace, baggage }, transactionContext => {
return startTransaction({
...transactionContext,
name: 'my transaction',
op: 'my op',
metadata: {
...transactionContext.metadata,
source: 'route',
}
});
});
```
Closes https://github.com/getsentry/sentry-javascript/issues/9011
=> feat(core): Add `continueTrace` method

packages/sveltekit/src/server/handle.ts, packages/sveltekit/src/server/handleError.ts, packages/sveltekit/src/server/load.ts, packages/sveltekit/src/server/utils.ts, packages/sveltekit/test/server/handle.test.ts, packages/sveltekit/test/server/load.test.ts
When deploying to Vercel (non-edge), server code is converted into Lambda functions. These functions have a tendency to freeze/shut down before the SDK is able to flush out events, causing events to be dropped. We already handle this in NextJS by manually calling `flush`. This PR applies the (almost) same logic to SvelteKit's server side instrumentation.
Since I was already at it, I replaced the `trace` calls with `startSpan` which is the newer API.
fixes #8855
=> fix(sveltekit): Flush in server wrappers before exiting

packages/browser/src/exports.ts, packages/bun/src/index.ts, packages/core/src/index.ts, packages/core/src/integration.ts, packages/core/test/lib/base.test.ts, packages/core/test/lib/integration.test.ts, packages/core/test/lib/transports/multiplexed.test.ts, packages/node/src/index.ts, packages/serverless/src/index.ts, packages/sveltekit/src/server/index.ts, packages/vercel-edge/src/index.ts
To make it easier to async add integrations later, which is useful e.g. for replay but also for other cases.
Now instead of:
```js
const client = Sentry.getCurrentHub().getClient();
if (client && client.addIntegration) {
client.addIntegration(new Sentry.Replay());
}
```
You can just do:
```js
Sentry.addIntegration(new Sentry.Replay());
```
Relates to:
* https://github.com/getsentry/sentry-javascript/pull/9138
* https://github.com/getsentry/sentry-javascript/pull/9180
=> feat(core): Add `addIntegration` utility

packages/astro/package.json, packages/astro/src/client/sdk.ts, packages/astro/src/common/metadata.ts, packages/astro/src/index.client.ts, packages/astro/src/index.server.ts, packages/astro/src/index.types.ts, packages/astro/src/server/sdk.ts, packages/astro/test/client/sdk.test.ts, packages/astro/test/server/sdk.test.ts
Adds `init` functions for the server and client side of the Astro SDK with tests.
For now, most of what these functions do is set the SDK metadata. On the client side, we add BrowserTracing, similarly to Next/SvelteKit. 
Contrary to our other SDKs, we'll not hard-require users to call these functions but internally call them in the Sentry Astro integration (not to be mistaken for a Sentry SDK `Integration`) which users will add to their Astro config. For this internal call, we'll apply sensible defaults. Users can manually override the internal SDK init by adding `sentry.(client|server).config.ts` files.  
ref #9182
=> feat(astro): Add server and client SDK `init` functions

packages/e2e-tests/test-applications/node-experimental-fastify-app/tests/transactions.test.ts, packages/node-experimental/package.json, yarn.lock
E2E tests started failing for fastify because of 0.32.3 (https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-fastify/CHANGELOG.md) being released. This includes this change https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1680 (which actually we wrote xD) that changes some span names, which lead to E2E test failing.
=> build(node-experimental): Update fastify instrumentation & E2E test

packages/ember/index.js
It seems some have an issue because of this, and maybe this is overkill anyhow. So I just inline a minimal version of this into the build file here instead, let's see if that fixes it.
Fixes https://github.com/getsentry/sentry-javascript/issues/9215
=> fix(ember): Avoid pulling in utils at build time

packages/e2e-tests/test-applications/node-experimental-fastify-app/src/app.js, packages/e2e-tests/test-applications/node-experimental-fastify-app/tests/propagation.test.ts, packages/node-experimental/src/constants.ts, packages/node-experimental/src/opentelemetry/propagator.ts, packages/node-experimental/src/opentelemetry/sampler.ts, packages/node-experimental/src/sdk/initOtel.ts, packages/node-experimental/test/integration/transactions.test.ts, packages/node-experimental/test/opentelemetry/propagator.test.ts, packages/node-experimental/test/sdk/trace.test.ts, packages/opentelemetry-node/src/index.ts
This fixes the propagator for node-experimental.
The "old" propagator from opentelemetry-node relies on having a transaction for the active span etc, which we don't have anymore. So the propagator never attached the correct stuff etc.
So now there is a new propagator for node-experimental:
* Instead of keeping DSC & TraceparentData on the OTEL Context, we just keep the PropagationContext (which includes the DSC...)
* Add an E2E test to make sure we attach the outgoing header correctly
=> feat(node-experimental): Use new Propagator for OTEL Spans

packages/node-integration-tests/suites/tracing-new/auto-instrument/mysql/withoutCallback/scenario.ts, packages/node-integration-tests/suites/tracing-new/auto-instrument/mysql/withoutCallback/test.ts, packages/tracing-internal/src/node/integrations/mysql.ts
Turns out my "improvement" here actually broke streaming the query response 😬 as in that case you may not provide a callback.
This PR fixes this by using `query.on('end')` instead in that case to finish the span.
Fixes https://github.com/getsentry/sentry-javascript/issues/9207
=> fix(node): Ensure mysql integration works without callback

packages/core/src/tracing/index.ts
This was previously exported so we can use it in node-experimental, but turns out we can't do that anyhow because we need to sample in OTEL. This has not yet been released, so in order to avoid exporting stuff we don't need public let's revert this export. (I'll leave the actual restructuring of moving this into a dedicated file in, though, because I think it still makes sense that way).
=> revert: Expose `sampleTransaction` export from core

packages/utils/src/instrument.ts, packages/utils/src/object.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/9204
=> fix(utils): Dereference DOM events after they have servered their purpose

packages/bun/src/transports/index.ts, packages/vercel-edge/src/transports/index.ts, packages/vercel-edge/test/transports/index.test.ts
I believe it is pointless (if not harmful) to set the `referrerPolicy` field on worker runtime fetch transports.
I think we have this because I copy & pasted it at one point from the browser fetch implemetation.
Fixes https://github.com/getsentry/sentry-javascript/issues/9194
=> fix: Don't set `referrerPolicy` on serverside fetch transports

packages/e2e-tests/test-applications/node-experimental-fastify-app/src/app.js, packages/e2e-tests/test-applications/node-experimental-fastify-app/tests/propagation.test.ts, packages/node-experimental/package.json, packages/node-experimental/src/integrations/index.ts, packages/node-experimental/src/integrations/node-fetch.ts, packages/node-experimental/src/opentelemetry/spanProcessor.ts, packages/node-experimental/src/sdk/init.ts, packages/node-experimental/test/integration/transactions.test.ts, packages/tracing-internal/test/browser/backgroundtab.test.ts, yarn.lock
This adds a new `NodeFetch` integration that is enabled by default.
We use [opentelemetry-instrumentation-node-fetch](https://github.com/gas-buddy/opentelemetry-instrumentation-fetch-node) under the hood, which seems to have the best support/functionality.
I also added an E2E test verifying it actually works and also propagates correctly.
=> feat(node-experimental): Add NodeFetch integration

packages/node/src/module.ts, packages/node/test/module.test.ts
We strip `.js` from the module name but not the newser `.mjs` or `.cjs` extensions.
=> fix(node): Strip .mjs and .cjs extensions from module name

packages/node-integration-tests/suites/anr/basic.js, packages/node-integration-tests/suites/anr/basic.mjs, packages/node-integration-tests/suites/anr/forked.js, packages/node-integration-tests/suites/anr/test.ts, packages/node/src/anr/index.ts, packages/utils/src/logger.ts
A separate `debug` option for `enableAnrDetection` is confusing and is not required if we add an `isEnabled()` function to the logger.
=> fix(node): Remove ANR `debug` option and instead add logger.isEnabled()

packages/tracing-internal/src/node/integrations/postgres.ts, packages/tracing/test/integrations/node/postgres.test.ts
- auto database instrumentation fails out of the box with esbuild - see https://github.com/getsentry/sentry-javascript/issues/3293#issuecomment-1739061872
- Allow consumers to pass resolved module for instrumentation directly
- This mirrors [sequelize dialectModule](https://github.com/sequelize/sequelize/blob/b3f03aed681abe0d5e22a9628b083f59f6772305/packages/core/src/sequelize.js#L166)
- If there's a way to configure esbuild similar to the webpack `commonjsMagicComments`, that should do the trick
- However the proposed solution in this PR seems more robust, especially as more bundlers/minifiers are gaining traction
=> feat(tracing): allow direct pg module to enable esbuild support

packages/serverless/src/awslambda.ts, packages/serverless/test/__mocks__/@sentry/node.ts, packages/serverless/test/awslambda.test.ts
- My team runs Express inside Lambda - we have a monolithic Lambda function with express handling routing, middleware, etc
- We are using `@sentry/node` today, and tried adding `@sentry/serverless` for it's timeout warning, auto-handling of `flush`, and links to cloudwatch logs
- But this caused all of our performance transaction traces to have an incorrect name (and various other tag + context issues)
- A new `startTransaction` boolean flag that turns on/off the transaction tracing feature of `@sentry/serverless`
- This will allow our team to use `@sentry/serverless`, but still rely on express `tracingHandler` for …
=> feat(serverlesss): allow disabling transaction traces

packages/astro/package.json
Adding [specific keywords](https://docs.astro.build/en/reference/publish-to-npm/#integrations-library) to an NPM package makes them show up in [Astro's integration library page](https://astro.build/integrations/). This PR adds them to the Astro package.json. 
While `analytics` isn't the perfect category for Sentry, it still fit better than all others, so I went with it. 
When we're ready we should also file an issue with Astro to add a Sentry logo in the library.
Separate PR because I'd only merge this once we're comfortable with publishing. 
ref #9182
=> chore(astro): Add Astro integration keywords

packages/browser-integration-tests/suites/replay/exceptions/template.html, packages/browser-integration-tests/suites/replay/exceptions/test.ts, packages/replay/src/integration.ts
Fixes an issue where the Replay integration can potentially break applications that use `styled-components`. `styled-components` [relies on an exception being throw](https://github.com/styled-components/styled-components/blob/b7b374bb1ceff1699f7035b15881bc807110199a/packages/styled-components/src/sheet/Tag.ts#L32-L40) for CSS rules that are not supported by the browser engine. However, our SDK suppressed any exceptions thrown from within rrweb, so `styled-components` assumes that an unsupported rule was inserted successfully and increases a rule index, which causes following inserted rules to fail due to an out-of-bounds error.
This was a regression from v1 as [we were always re-throwing the exception](https://github.com/getsentry/rrweb/blob/sentry-v1/packages/rrweb/src/sentry/callbackWrap …
=> fix(replay): Fix potential broken CSS in styled-components

packages/replay/package.json, yarn.lock
* Fix checking for patchTarget in initAdoptedStyleSheetObserver [#110](https://github.com/getsentry/rrweb/pull/110)
https://github.com/getsentry/rrweb/blob/sentry-v2/CHANGELOG.md#201
=> fix(replay): bump rrweb to 2.0.1

.github/ISSUE_TEMPLATE/bug.yml, .github/workflows/issue-package-label.yml
This PR adds @sentry/astro as a selectable option in the bug report template and adjusts the automatic package label assignment action along with it. 
ref #9182
=> chore(repo): Add Astro package in bug report template

packages/node/src/anr/index.ts, packages/utils/src/anr.ts
Closes #9256
Rather than move this all to the Node package, this PR moves only the Node specific code. This means that it might still be possible to use this code for any future browser implementation.
=> fix(utils): Move Node specific ANR impl. out of utils

packages/core/src/integrations/inboundfilters.ts, packages/core/test/lib/integrations/inboundfilters.test.ts
As reported [internally via Slack](https://sentry.slack.com/archives/C28MX5WAJ/p1697448093989649), our filters for health check transactions (which we unfortunately added to the SDK a while ago) were partially far too broad, filtering out transactions like `/delivery` because they matched the `/^.*live.*$/` regex. This PR narrows down the regexes so that they no longer only require a partial but a full match. 
I'd still rather nuke the entire filters array, given that we [filter on the backend](https://docs.sentry.io/product/data-management-settings/filtering/#transactions-coming-from-healthcheck) anyway, but there's a point to be made that the filters in the SDK avoid unnecessary traffic to Relay. 
ref https://github.com/getsentry/team-webplatform-meta/issues/70
=> fix(core): Narrow filters for health check transactions

packages/nextjs/package.json, packages/nextjs/src/config/webpack.ts, yarn.lock
Fixes https://github.com/getsentry/sentry-javascript/issues/9120
Adresses https://github.com/getsentry/sentry-javascript/issues/9092#issuecomment-1754003176
Previously we failed to properly locate Next.js' `request-async-storage` module in monorepo setups because we were limiting our search to a subset of paths in `webpackConfig.resolve.modules`.
Example:
- `webpackConfig.resolve.modules` contained `["<absolute_path_to_monorepo>/packages/<project_with_next_js>/node_modules", "<absolute_path_to_monorepo>/packages/<project_with_next_js>"]`
- `request-async-storage` is located at `/<absolute_path_to_monorepo>/node_modules/next/dist/client/components/request-async-storage.external.js`
- Since since `request-async-storage` was not in `webpackConfig.resolve.modules` or any subpaths, we marked …
=> fix(nextjs): Fix resolution of request async storage module

packages/deno/rollup.config.js
I noticed the deno build output contained some odd pieces of code (the vendored session replay compression) so I figured we are not properly tree shaking.
This PR increases level of tree-shaking we do which will decrease the bundle size to the bare minimum.
=> build(deno): Treeshake deno package

packages/node-integration-tests/suites/public-api/LocalVariables/local-variables-caught.js, packages/node-integration-tests/suites/public-api/LocalVariables/local-variables-caught.mjs
We recently updated the `LocalVariables` integration to capture variables for all exceptions by default so these tests should not need to modify the integration default options for these tests to pass.
=> test(node): Ensure local variables are included for caught exceptions by default

packages/astro/package.json
Turns out, to make our Astro package show up in Astro's integration library, we need to add another keyword that's only [mentioned here](https://docs.astro.build/en/reference/integrations-reference/#allow-installation-with-astro-add) and not in Astro's [NPM publishing guide](https://docs.astro.build/en/reference/publish-to-npm/#keywords).
With this keyword added (and once we cut the next release), our SDK should show up in the library 🤞 
(I'd like to get this out relatively soonish so that we can write docs that actually use `npx astro add` as opposed to installing the package manually).
ref #9093
=> chore(astro): Add `astro-integration` keyword

packages/nextjs/src/config/webpack.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/9067
The order in which we insert the SDK into the webpack entrypoints seems to matter in dev mode. Maybe the dev init script is somehow referenced by index. 🤷‍♂️
There is a slight nuanced consideration here in which the SDK may now be initialized too late to catch any errors generated by Next.js which we insert at the end only in dev mode.
=> fix(nextjs): Fix HMR by inserting new entrypoints at the end

.craft.yml
Adds the RR target for Astro to our craft config. First RR entry was already created manually: https://github.com/getsentry/sentry-release-registry/pull/128 
ref: https://github.com/getsentry/sentry-javascript/issues/9182
=> chore(astro): Add Release Registry Craft target for Astro

packages/node-experimental/src/integrations/node-fetch.ts
It seems that even in Node 18 fetch may not be usable. By using the `NodePerformanceIntegration` base we actually try-catch initializing the instrumentation, which should catch this case.
=> fix(node-experimental): Guard against missing `fetch`

packages/deno/.gitignore, packages/deno/package.json, packages/deno/rollup.types.config.js, packages/deno/tsconfig.types.json
Cleans up the distributed files in the Deno package by putting the intermediary type declarations into a separate folder.
Also disables declaration map generation as we bundle the type definitions so the declaration maps won't work anyhow.
=> build(deno): Clean up build output

packages/ember/.gitignore
This was a bit annoying when running `build:tarball`. I checked, the tarball contents are the same.
=> build(ember): Gitignore prepack artifacts

packages/core/src/session.ts, packages/node-integration-tests/suites/anr/basic-session.js, packages/node-integration-tests/suites/anr/basic.mjs, packages/node-integration-tests/suites/anr/forked.js, packages/node-integration-tests/suites/anr/test-transport.js, packages/node-integration-tests/suites/anr/test.ts, packages/node/src/anr/index.ts, packages/types/src/session.ts
This PR:
- Adds the `abnormal_mechanism` property to session types
- Passes the latest session from main process to ANR process
- If ANR is triggered and there's an active session, send the abnormal session
- Adds a test to check for the session update
~~This PR makes no attempt to suppress further session updates from the main app process.~~ How does Sentry backend treat conflicting session updates?
Ref: https://github.com/getsentry/sentry-electron/issues/774
=> feat(node): Add abnormal session support for ANR

packages/deno/package.json, packages/deno/rollup.config.js, packages/deno/src/integrations/contextlines.ts, packages/node/package.json, packages/node/src/integrations/contextlines.ts, packages/node/src/integrations/http.ts, packages/node/src/integrations/localvariables.ts, packages/node/src/integrations/undici/index.ts, packages/node/test/integrations/localvariables.test.ts, packages/utils/src/index.ts, packages/utils/src/lru.ts, packages/utils/test/lru.test.ts, yarn.lock
Ref #9199
This PR:
- Adds a simple `LRUMap` to utils 
- Considerably smaller and simpler than `lru_map`
- `Map.prototype.keys()` returns an iterator in order of insertion so the oldest entry key is `keys().next().value`
- Replaces all usages of `lru_map`
We could add `LRUMap` to `@sentry/node` but it might be useful elsewhere and it's required in the Electron SDK and it would be better not to add an export to a public API.
=> feat(node): Remove `lru_map` dependency

.vscode/launch.json, package.json, packages/browser/package.json, packages/core/package.json, packages/e2e-tests/test-applications/sveltekit/package.json, packages/feedback/package.json, packages/hub/package.json, packages/integrations/package.json, packages/nextjs/package.json, packages/node/package.json, packages/react/package.json, packages/remix/package.json, packages/replay-worker/package.json, packages/replay/package.json, packages/serverless/package.json, packages/svelte/package.json, packages/tracing-internal/package.json, packages/utils/package.json, packages/vercel-edge/package.json, packages/vue/package.json, packages/wasm/package.json, yarn.lock
Inspired by https://github.com/getsentry/sentry-javascript/issues/9199, let's try removing tslib.
Kept it with the angular package because I wasn't sure if angular build process needs it, but we can remove it if not needed.
=> feat: Remove tslib

packages/deno/test/__snapshots__/mod.test.ts.snap, packages/deno/test/mod.test.ts, packages/deno/test/normalize.ts
We cannot depend on the npm version of files in the deno tests because our typings are gonna drift apart.
This is an ugly "slap any onto everything" to unblock hack.
=> test(deno): Refer to local files in tests

.size-limit.js, package.json, packages/replay/package.json, rollup/bundleHelpers.js, rollup/npmHelpers.js, rollup/plugins/npmPlugins.js, yarn.lock
This depends on https://github.com/getsentry/rrweb/pull/114 to be merged first, but allows to configure build time flags to shake out certain rrweb features that may not be used.
It also adds a size limit entry that shows the total bundle size with everything that can be shaken out removed, incl. debug stuff. Bundle size is about ~11kb gzipped less in this scenario, which is not bad.
=> feat(replay): Allow to treeshake rrweb features

packages/deno/test/__snapshots__/mod.test.ts.snap, packages/deno/test/normalize.ts
We wrongly accessed the context for the event normalization.
And we had normalization logic that didn't do anything (target).
=> test(deno): Fix runtime normalization

packages/e2e-tests/test-applications/debug-id-sourcemaps/package.json
Alpha builds are blocked bc of this: https://github.com/getsentry/sentry-javascript/actions/runs/6575412255/job/17864293589#step:10:76
=> fix(e2e): Resolve `@sentry/node` dependency in bundler plugins to current version

packages/node/src/anr/websocket.ts
fixes https://github.com/getsentry/sentry-javascript/issues/9307
Reading from the buffer requires the buffer to have at least two items, which we now account for. Not sure how exactly this can happen though.
=> fix(node): Check buffer length when attempting to parse ANR frame

packages/types/src/datacategory.ts, packages/types/src/envelope.ts, packages/utils/src/envelope.ts
ref https://github.com/getsentry/sentry-javascript/issues/9262
As per https://github.com/getsentry/sentry-python/pull/2385, add support for statsd envelope.
once https://github.com/getsentry/sentry-javascript/pull/9296 is merged in, we can think about adding this to the web-vital instrumentation.
=> feat(types): Add statsd envelope types

packages/angular-ivy/package.json, packages/angular/package.json, packages/astro/package.json, packages/bun/package.json, packages/core/package.json, packages/gatsby/package.json, packages/hub/package.json, packages/nextjs/package.json, packages/node-experimental/package.json, packages/node/package.json, packages/opentelemetry-node/package.json, packages/react/package.json, packages/remix/package.json, packages/svelte/package.json, packages/sveltekit/package.json, packages/tracing-internal/package.json, packages/types/package.json, packages/utils/package.json, packages/vercel-edge/package.json, packages/vue/package.json
Adds `--sig` option to `yalc:publish` tasks to include a hash of file contents as part of package version. This allows us to cache bust and allows dev servers to hot reload in watch mode.
=> feat(dev): Change `yalc:publish` to publish with a hash

packages/replay/jest.setup.ts, packages/replay/src/integration.ts, packages/utils/src/index.ts, packages/utils/src/isBrowser.ts
We need this in the new feedback integration.
=> ref: Move `isBrowser` util fn from `replay` to `util`

packages/node-experimental/package.json, packages/node-experimental/src/integrations/node-fetch.ts
Installing this on Node <18 produces install time errors, as the package is not compatible, e.g.:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'opentelemetry-instrumentation-fetch-node@1.1.0',
npm WARN EBADENGINE   required: { node: '>18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.18.0', npm: '8.19.2' }
npm WARN EBADENGINE }
```
We already try-catch the `setupInstrumentation` hook anyhow, so no need to check again here - if this fails we'll just skip running this integration.
=> fix(node-experimental): Make node-fetch support optional

.craft.yml
ssh ran into the issue of not having the right known-hosts defined, let's try https.
We're probably gonna run into authentification issues now.
=> meta(deno): Use https git protocol in deno release target

packages/core/src/checkin.ts, packages/types/src/envelope.ts, packages/types/src/index.ts
=> fix(types): Remove typo with CheckInEnvelope

.craft.yml
I think this is more or less just a cosmetic change but it will show "getsentry/deno" in the release issue for the target which I believe is valuable.
=> meta(craft): Add id to Deno target

packages/e2e-tests/test-applications/node-express-app/event-proxy-server.ts, packages/e2e-tests/test-applications/node-express-app/package.json, packages/e2e-tests/test-applications/node-express-app/playwright.config.ts, packages/e2e-tests/test-applications/node-express-app/src/app.ts, packages/e2e-tests/test-applications/node-express-app/start-event-proxy.ts, packages/e2e-tests/test-applications/node-express-app/tests/server.test.ts
Attempt to reproduce https://github.com/getsentry/sentry-javascript/issues/8928
=> test(e2e): Add test for local variables

packages/e2e-tests/README.md, packages/e2e-tests/test-applications/create-next-app/.npmrc, packages/e2e-tests/test-applications/create-react-app/.npmrc, packages/e2e-tests/test-applications/create-remix-app-v2/.npmrc, packages/e2e-tests/test-applications/create-remix-app/.npmrc, packages/e2e-tests/test-applications/debug-id-sourcemaps/.npmrc, packages/e2e-tests/test-applications/generic-ts3.8/.npmrc, packages/e2e-tests/test-applications/nextjs-app-dir/.npmrc, packages/e2e-tests/test-applications/node-experimental-fastify-app/.npmrc, packages/e2e-tests/test-applications/node-express-app/.npmrc, packages/e2e-tests/test-applications/react-create-hash-router/.npmrc, packages/e2e-tests/test-applications/react-router-6-use-routes/.npmrc, packages/e2e-tests/test-applications/standard-frontend-react-tracing-import/.npmrc, packages/e2e-tests/test-applications/standard-frontend-react/.npmrc, packages/e2e-tests/test-applications/sveltekit/.npmrc, packages/e2e-tests/test-registry.npmrc
Locally E2E tests keep hanging due to this, for whatever reason. Probably some DSN issues, but no idea why... Changing this to `127.0.0.1` fixes the problem :O Not sure if this has any downsides...?
=> test(e2e): use `127.0.0.1` instead of `localhost` for E2E `.npmrc`

packages/nextjs/src/config/webpack.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/9285
=> fix(nextjs): Restore `autoInstrumentMiddleware` functionality

packages/node-integration-tests/suites/express/multiple-routers/complex-router/test.ts, packages/tracing-internal/src/node/integrations/express.ts
This PR fix use case when original req url ends with trailing slash and contain query params.
For example:
```
api/v1/users/123/posts/?param=1
```
sentry build req._reconstructedRoute as:
api/v1/users/123/posts
sentry build req._reconstructedRoute as:
api/v1/users/:userID/posts
=> fix(tracing-internal): Fix trailing slash with query paras in url

packages/astro/README.md
This PR updates the Astro readme with up-to-date installation instructions and links to our docs.
[Rendered Version](https://github.com/getsentry/sentry-javascript/blob/78f4f67a8779c6a4076b4ece61df4902273d884c/packages/astro/README.md)
=> doc(astro): Update Readme

packages/astro/src/integration/index.ts, packages/astro/src/integration/snippets.ts
To inject a custom client/server Sentry.init call into the user bundles, we simply import from the file.
However, it seems like Vite can't resolve an absolute windows path in an import statement:
```
import 'C:\path\to\my\sentry.client.config.ts'
```
This PR converts non-posix paths to a POSIX conforming path first which should fix this limitation. This bug was reported on Discord and I asked to user to test the fix in their local setup which they confirmed to be working.  
Note: Omitted tests here because it's quite hard to get `path.sep` to return the actual windows `\\` separator instead of the OS one. Can revisit if reviewers prefer to have this properly covered.
=> fix(astro): Convert init file paths to POSIX paths

packages/astro/src/index.types.ts
This PR adds the @sentry/astro package's default export (i.e. the `sentryAstro` integration) to the types entry point. Previously, the missing default export type declaration caused a type error in `astro.config.ts` files (`astro.config.mjs` is the default).
Thanks @aldy505 for reporting!
=> fix(astro): Add integration default export to types entry point

packages/nextjs/src/common/wrapGetInitialPropsWithSentry.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/9066
Consideration: If users return undefined we will override that with an object, which is arguably fine since when undefined is returned you will likely not depend on it in any way.
=> fix(nextjs): Guard for case where `getInitialProps` may return undefined

packages/nextjs/src/config/webpack.ts
Fixes a bug where we didn't use the release value passed to the webpack plugin to inject release values into the bundle, essentially causing the release values to drift apart causing a plethora of issues:
- no sourcemapping
- countless "phantom" releases
- missassociation of issues
=> fix(nextjs): Use webpack plugin release value to inject release

packages/browser/src/profiling/hubextensions.ts, packages/browser/src/profiling/integration.ts, packages/browser/src/profiling/utils.ts, packages/browser/test/unit/profiling/integration.test.ts
Since there is an unknown elapsed time between document response and profile start, setting profile timestamp = transaction start timestamp can significantly skew our profile and cause alignment issue in the product. This updates the pageload profiles to create independent timestamps.
=> fix(browser): correct timestamp on pageload profiles

packages/replay/src/util/addGlobalListeners.ts
We noticed we still sometimes see "too long sessions", and it seems this is because of errors being tagged with a replay long after the session expired. After some digging, this may be because we do not check session expiration when adding the `replay_id` to the DSC. This PR fixes this.
I thought about adding a test for this, but feels this is _a lot of_ work with all the timing issues etc., so I figure this is OK to do as-is, as this is pretty straightforward... WDYT?
=> fix(replay): ensure `replay_id` is not added to DSC if session expired

packages/serverless/src/awslambda.ts, packages/serverless/src/gcpfunction/index.ts, packages/serverless/src/utils.ts, packages/serverless/test/awslambda.test.ts, packages/serverless/test/gcpfunction.test.ts
Given we merged in https://github.com/getsentry/sentry-javascript/pull/8907, we can now remove the global handlers that indiscriminately tags all events as unhandled.
fixes https://github.com/getsentry/sentry-javascript/issues/5408
=> fix(serverless): Don't mark all errors as unhandled

packages/feedback/package.json, packages/feedback/src/integration.ts, packages/feedback/src/sendFeedback.ts, packages/feedback/src/types/index.ts, packages/feedback/src/util/handleFeedbackSubmit.ts, packages/feedback/src/util/sendFeedbackRequest.ts, packages/feedback/src/widget/Actor.ts, packages/feedback/src/widget/Dialog.ts, packages/feedback/src/widget/Icon.ts, packages/feedback/src/widget/Main.css.ts, packages/feedback/src/widget/SuccessIcon.ts, packages/feedback/src/widget/createShadowHost.ts, packages/feedback/src/widget/createWidget.ts, packages/feedback/src/widget/util/createElement.ts, yarn.lock
- refactor to support multiple widgets
- add `attachTo` and `createWidget` public methods to create respective components. 
Requires https://github.com/getsentry/sentry-javascript/pull/9217
=> ref(feedback): Refactor to better support multiple dialogs

.github/workflows/build.yml
Restores the nx cache in the prepare e2e test action to avoid double building everything.
=> ci(e2e): Restore nxcache in e2e tests

packages/replay-worker/package.json, packages/replay-worker/rollup.worker.config.js, packages/replay-worker/src/Compressor.ts, yarn.lock
See https://github.com/nodeca/pako/issues/268, there is some issue with pako tree shaking ootb.
We don't need all the inflation stuff in our bundle.
=> fix(replay): Remove unused parts of pako from build

packages/e2e-tests/test-applications/nextjs-app-dir/tests/pages-ssr-errors.test.ts, packages/nextjs/src/common/wrapPageComponentWithSentry.ts
This will attach errors happening while serverside rendering page components to the corresponding transaction.
Resolves https://github.com/getsentry/sentry-javascript/issues/9152
Note: Ideally we would have a span for rendering the page and attach the error there but this would be messy to do with our current implementation. The reason is that we cannot directly grab the request transaction from within the render function because it doesn't live in the current async context. We would have to pass references or keys around and clean them up after a response has been sent so the transactions can be GCd. The mess would originate from the fact that we create spans and transactions differently depending on whether we're in a lambda environment.
We will do span creation in a follow-up PR.
=> feat(nextjs): Trace errors in page component SSR

packages/angular-ivy/README.md, packages/angular-ivy/package.json
This PR bumps our peer deps to allow for Angular 12-17 in the `@sentry/angular-ivy` package. 
With the improved SSR capabilities and Vite being used for SSR Angular apps during dev mode in Angular 17, there is still an issue with our SDK's package format ([APF12](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview#heading=h.k0mh3o8u5hx)) not being compatible with the server-side code. There is a [workaround](https://github.com/getsentry/sentry-javascript/issues/9376#issuecomment-1782513570) to fix this by only importing our SDK in the client side config but I [reached out](https://github.com/angular/angular-cli/issues/26135) to the Angular team to find a proper solution. 
Given that this bug only exists in SSR Angular apps, I'd argue we can already go …
=> chore(angular-ivy): Allow Angular 17 in peer dependencies

packages/nextjs/src/common/utils/edgeWrapperUtils.ts, packages/nextjs/src/common/wrapApiHandlerWithSentry.ts, packages/nextjs/src/common/wrapAppGetInitialPropsWithSentry.ts, packages/nextjs/src/common/wrapDocumentGetInitialPropsWithSentry.ts, packages/nextjs/src/common/wrapErrorGetInitialPropsWithSentry.ts, packages/nextjs/src/common/wrapGetInitialPropsWithSentry.ts, packages/nextjs/src/common/wrapGetServerSidePropsWithSentry.ts, packages/nextjs/src/common/wrapGetStaticPropsWithSentry.ts, packages/nextjs/src/server/index.ts, packages/nextjs/test/serverSdk.test.ts
We guarded a lot of tracing functionality in Next.js behind `hasTracingEnabled()` which will prevent events from being traced when performance is disabled. This PR removes these checks, which were a relic of the past we missed when introducing "tracing without performance".
=> fix(nextjs): Trace with performance disabled

packages/astro/src/index.server.ts, packages/bun/src/index.ts, packages/core/src/exports.ts, packages/core/src/index.ts, packages/deno/src/index.ts, packages/node-experimental/src/index.ts, packages/node/src/index.ts, packages/remix/src/index.server.ts, packages/serverless/src/index.ts, packages/sveltekit/src/server/index.ts, packages/types/src/checkin.ts, packages/types/src/index.ts, packages/vercel-edge/src/index.ts
In https://github.com/getsentry/sentry-javascript/pull/8039 we added functionality for `Sentry.captureCheckIn` as part of Sentry's [cron monitoring product](https://docs.sentry.io/product/crons/).
This PR adds `Sentry.withMonitor`, a wrapping function similar to `Sentry.startSpan` that wraps a callback with a cron monitor. Under the hood it uses `Sentry.captureCheckIn`, but having this as a callback means that users don't have to think about passing `checkInId` around.
```ts
import * as Sentry from '@sentry/node';
// with monitor will send checkin when callback is started/finished
// works with async and sync callbacks.
const result = Sentry.withMonitor(
'dailyEmail',
() => {
// withCheckIn return value is same return value here
return sendEmail();
},
{
schedule: {
type: 'crontab',
value: …
```
=> feat(core): Add cron monitor wrapper helper

packages/replay/src/replay.ts
This is not used since we reworked our session refresh flow to just start>stop.
=> ref(replay): Remove unused `_triggerFullSnapshot`

packages/replay/src/coreHandlers/util/xhrUtils.ts, packages/replay/src/replay.ts
Fix one incorrect log message, and remove one we don't actually need.
=> ref(replay): Minor log cleanup

packages/browser-integration-tests/suites/integrations/Breadcrumbs/dom/click/template.html, packages/browser-integration-tests/suites/integrations/Breadcrumbs/dom/click/test.ts, packages/browser-integration-tests/suites/integrations/Breadcrumbs/dom/init.js, packages/browser-integration-tests/suites/integrations/Breadcrumbs/dom/textInput/template.html, packages/browser-integration-tests/suites/integrations/Breadcrumbs/dom/textInput/test.ts, packages/utils/src/instrument.ts, rollup/plugins/bundlePlugins.js
As discussed some time ago, this changes the dom instrumentation to avoid keeping any reference to an event in the module scope.
Instead, we put a `_sentryId` non-enumerable property on the event target (if possible) and check based on this.
I also added some tests to verify the expected behavior, also for future changes here.
Fixes https://github.com/getsentry/sentry-javascript/issues/9204
=> fix(utils): Avoid keeping a reference of last used event

packages/deno/.eslintrc.js, packages/deno/package.json, packages/ember/.eslintignore, packages/ember/package.json
=> build: Clean ember and deno packages properly

packages/replay/src/util/isRrwebError.ts, packages/replay/test/integration/coreHandlers/handleGlobalEvent.test.ts
I think we don't really need this anymore, and this doesn't even work anyhow in any minified scenario, so we can safe these bundle bytes & also the work to check this on each error.
Or @billyvg do you see scenarios where this would catch something that the check above wouldn't? 🤔
=> ref(replay): Streamline rrweb internal error check

packages/angular-ivy/package.json, packages/angular-ivy/scripts/prepack.ts
This PR adjusts the entry points of `@sentry/angular-ivy`'s `package.json` to point directly to FESM2015 bundles (= bundled ESM2015 code) instead of the UMD bundles. This fixes an error when the old (no longer supported) UMD bundles were picked up by Vite in Angular apps with SSR config (#9376).   
This workaround was [suggested](https://github.com/angular/angular-cli/issues/26135#issuecomment-1782904827) by an Angular Team member and after experimenting with it, I found out that in addition to removing the `main` entry point, we also need to add `"type": "module"`.
Tested this with Angular 17 + Node 18 as well as Angular 12 with Node 12. Both seem to work in my test apps. I'm not 100% confident that this always works because we're no longer …
=> fix(angular-ivy): Adjust package entry points to support Angular 17 with SSR config

.size-limit.js, packages/replay/package.json, rollup/bundleHelpers.js, rollup/npmHelpers.js, rollup/plugins/npmPlugins.js, yarn.lock
- feat: Export getCanvasManager & allow passing it to record() [#122](https://github.com/getsentry/rrweb/pull/122)
- feat: Remove hooks related code, which is not used [#126](https://github.com/getsentry/rrweb/pull/126)
- feat: Remove plugins related code, which is not used [#123](https://github.com/getsentry/rrweb/pull/123)
- feat: Refactor module scope vars & export mirror & `takeFullSnapshot` directly [#113](https://github.com/getsentry/rrweb/pull/113)
- fix(rrweb): Fix rule.style being undefined [#121](https://github.com/getsentry/rrweb/pull/121)
- ref: Avoid unnecessary cloning of objects or arrays [#125](https://github.com/getsentry/rrweb/pull/125)
- ref: Avoid cloning events to add timestamp [#124](https://github.com/getsentry/rrweb/pull/124)
Note: With this update, canvas is …
=> feat(replay): Update rrweb to 2.2.0

packages/feedback/README.md
Temp until product docs + dedicated Feedback Alerts UI
=> chore(feedback): Add alerting instructions to readme.md

packages/feedback/README.md
* Adds themeable options for submit/cancel/input
* Make css vars + theme vars consistent
* Fix incorrect defaults
=> docs(feedback): Add more themeables + improve/fix inconsistencies

packages/replay/src/util/sendReplay.ts, packages/replay/src/util/sendReplayRequest.ts, packages/replay/test/integration/rateLimiting.test.ts
We changed this [here](https://github.com/getsentry/sentry-javascript/pull/7018), but apparently it is possible to have responses with a 200 status code but rate limit headers.
This PR updates our handling to stop either for a non-200 status code, _or_ for a rate limit header.
I also streamlined the tests for this a bit, we were testing a bunch of unrelated things, IMHO it's enough to test we stopped/didn't stop.
Resolves: https://github.com/getsentry/sentry/issues/49498
=> fix(replay): Ensure we stop for rate limit headers

packages/browser-integration-tests/suites/replay/slowClick/error/init.js, packages/browser-integration-tests/suites/replay/slowClick/error/template.html, packages/browser-integration-tests/suites/replay/slowClick/error/test.ts, packages/browser-integration-tests/suites/replay/slowClick/mutation/test.ts, packages/replay/src/coreHandlers/handleClick.ts, packages/replay/src/coreHandlers/util/domUtils.ts, packages/replay/src/types/replay.ts, packages/replay/src/util/handleRecordingEmit.ts
This refactors the slow/rage click detection to use rrweb events instead of adding our own event listeners.
* We look for incremental snapshot events, and update the `_lastMutation` and `_lastScroll` properties based on them.
* If a full snapshot happens, we interpret it as a mutation. this is not necessarily correct, but we don't know any different. also this shouldn't matter much because a full snapshot only happens in error mode, in which case things that happened before the full checkout should be discarded anyhow, so 🤷 
Integration tests for this are still passing, so it seems to me to be a good change. Hopefully this:
1. Decreases perf overhead by only using a single instrumentation instead of multiple overlapping ones
2. Increases consistency by ensuring that whatever we see …
=> ref(replay): Use rrweb for slow click detection

packages/nextjs/src/common/devErrorSymbolicationEventProcessor.ts, packages/nextjs/src/config/webpack.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/9057
We inject the base path into the bundles in dev mode and use it for the requests to the resolving server.
=> fix(nextjs): Fix sourcemaps resolving for local dev when basePath is set

packages/bun/src/client.ts, packages/core/test/lib/serverruntimeclient.test.ts, packages/deno/src/client.ts, packages/deno/test/__snapshots__/mod.test.ts.snap, packages/nextjs/src/config/webpack.ts, packages/nextjs/src/edge/index.ts, packages/nextjs/src/server/index.ts, packages/nextjs/test/config/loaders.test.ts, packages/nextjs/test/config/webpack/sentryWebpackPlugin.test.ts, packages/vercel-edge/src/client.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/8646
Fixes https://github.com/getsentry/sentry-javascript/pull/9454
- Fixes bug where we set the platform to something other than `"node"` or `"javascript"`. Doing so will cause symbolicator not to do anything.
- Generally widens the upload scope for Next.js server files for sourcemaps. I believe this should not be harmful. Let's see.
- Adds rewriting logic to the edge part of the SDK to match the paths of stackframes to the uploaded artifacts properly.
=> feat(nextjs): Add automatic sourcemapping for edge part of the SDK

packages/nextjs/src/config/webpack.ts
I forgot to push this change to https://github.com/getsentry/sentry-javascript/pull/9457.
This is not technically required but we should avoid exposing any kind of information if it isn't necessary.
=> fix(nextjs): Only inject basepath in dev mode

packages/ember/ember-cli-build.js, packages/ember/package.json, yarn.lock
broccoli-terser-sourcemap fixed a bug in [v4.1.1](https://github.com/ember-cli/broccoli-terser-sourcemap/releases/tag/v4.1.1) that affected building our SDK.
This adds a test to ensure this continues to work.
Closes https://github.com/getsentry/sentry-javascript/issues/9168
=> test(ember): Test that prod builds & source maps work

packages/feedback/README.md, packages/feedback/src/constants.ts, packages/feedback/src/types/index.ts, packages/feedback/src/widget/Actor.ts, packages/feedback/src/widget/Dialog.css.ts, packages/feedback/src/widget/Main.css.ts
* **BREAKING** `inputBorderFocus` is now `inputOutlineFocus` (I wanted to make this directly tied to the css property being used to avoid confusion)
* added `submitOutlineFocus`, `submitForegroundHover` (as well as the `cancel` versions)
* change to use `:focus-visible` pseudo class (instead of `:focus`)
* do not show `buttonLabel` if empty
Closes #9439
=> feat(feedback): Add "outline focus" and "foreground hover" vars

packages/feedback/src/integration.ts, packages/feedback/src/types/index.ts, packages/feedback/src/widget/createWidget.ts, packages/feedback/test/integration.test.ts, packages/feedback/test/widget/createWidget.test.ts
* Adds `openDialog` and `closeDialog` public methods on the Feedback integration class
* Rename `hideDialog` -> `closeDialog` (for Widget)
* Rename type `Widget` -> `FeedbackWidget`
* Refactor internal logic when creating widgets
=> feat(feedback): Add `openDialog` and `closeDialog` onto integration interface

packages/browser-integration-tests/suites/replay/errors/beforeErrorSampling/init.js, packages/browser-integration-tests/suites/replay/errors/beforeErrorSampling/test.ts, packages/replay/src/coreHandlers/handleAfterSendEvent.ts, packages/replay/src/integration.ts, packages/replay/src/types/replay.ts, packages/replay/test/integration/coreHandlers/handleAfterSendEvent.test.ts
This adds a new option to `new Replay()` which allows to ignore certain errors for error-based sampling:
```js
new Replay({
beforeErrorSampling: (event) => !event.message.includes('ignore me')
});
```
When returning `false` from this callback, the event will not trigger an error-based sampling.
Note that returning `true` there does not mean this will 100% be sampled, but just that it will check the `replaysOnErrorSampleRate`. The purpose of this callback is to be able to ignore certain groups of errors from triggering an error-based replay at all.
Closes https://github.com/getsentry/sentry-javascript/issues/9413
Related to https://github.com/getsentry/sentry-javascript/issues/8462 (not 100% but partially)
=> feat(replay): Allow to configure `beforeErrorSampling`

packages/e2e-tests/test-applications/nextjs-app-dir/app/edge-server-components/error/page.tsx, packages/e2e-tests/test-applications/nextjs-app-dir/tests/edge.test.ts, packages/nextjs/src/common/wrapServerComponentWithSentry.ts
Anything running in the edge runtime requires manual flushing. We forgot to do this for servercomponents.
=> fix(nextjs): Flush servercomponent events for edge

packages/deno/README.md
=> docs: Update Deno SDK readme

packages/core/src/index.ts, packages/feedback/src/index.ts, packages/feedback/src/types/index.ts, packages/feedback/src/util/handleFeedbackSubmit.ts, packages/feedback/src/util/prepareFeedbackEvent.ts, packages/feedback/src/util/sendFeedbackRequest.ts, packages/feedback/src/widget/createWidget.ts, packages/feedback/test/unit/util/prepareFeedbackEvent.test.ts, packages/feedback/test/widget/createWidget.test.ts, packages/types/src/datacategory.ts, packages/types/src/envelope.ts, packages/types/src/event.ts, packages/types/src/feedback.ts, packages/types/src/index.ts, packages/utils/src/envelope.ts
Remove the use of our temporary ingest endpoint, and use our normal ingestion instead.
=> feat(feedback): use custom prepare/send, re-use createEventEnvelope from core

packages/astro/README.md, packages/astro/src/server/middleware.ts
This PR updates the middleware documentation in two places
* be more explicit in pointing out that `trackClientIP` should only be used in SSR/hybrid configs
* replace old name of the middleware factory function with the current (hopefully final) one
=> doc(astro): Update middleware documentation

packages/e2e-tests/test-applications/create-next-app/playwright.config.ts, packages/e2e-tests/test-applications/create-next-app/tests/behaviour-client.test.ts, packages/e2e-tests/test-applications/create-next-app/tests/behaviour-server.test.ts, packages/e2e-tests/test-applications/create-remix-app-v2/playwright.config.ts, packages/e2e-tests/test-applications/create-remix-app-v2/tests/behaviour-client.test.ts, packages/e2e-tests/test-applications/create-remix-app/playwright.config.ts, packages/e2e-tests/test-applications/create-remix-app/tests/behaviour-client.test.ts, packages/e2e-tests/test-applications/debug-id-sourcemaps/tests/server.test.ts, packages/e2e-tests/test-applications/nextjs-app-dir/playwright.config.ts, packages/e2e-tests/test-applications/nextjs-app-dir/tests/exceptions.test.ts, packages/e2e-tests/test-applications/nextjs-app-dir/tests/transactions.test.ts, packages/e2e-tests/test-applications/node-experimental-fastify-app/playwright.config.ts, packages/e2e-tests/test-applications/node-experimental-fastify-app/tests/errors.test.ts, packages/e2e-tests/test-applications/node-experimental-fastify-app/tests/propagation.test.ts, packages/e2e-tests/test-applications/node-experimental-fastify-app/tests/transactions.test.ts, packages/e2e-tests/test-applications/node-express-app/playwright.config.ts, packages/e2e-tests/test-applications/node-express-app/tests/server.test.ts, packages/e2e-tests/test-applications/react-create-hash-router/playwright.config.ts, packages/e2e-tests/test-applications/react-create-hash-router/tests/behaviour-test.spec.ts, packages/e2e-tests/test-applications/react-router-6-use-routes/playwright.config.ts, packages/e2e-tests/test-applications/react-router-6-use-routes/tests/behaviour-test.spec.ts, packages/e2e-tests/test-applications/standard-frontend-react-tracing-import/playwright.config.ts, packages/e2e-tests/test-applications/standard-frontend-react-tracing-import/tests/behaviour-test.spec.ts, packages/e2e-tests/test-applications/standard-frontend-react/playwright.config.ts, packages/e2e-tests/test-applications/standard-frontend-react/tests/behaviour-test.spec.ts, packages/e2e-tests/test-applications/sveltekit/playwright.config.ts, packages/e2e-tests/test-applications/sveltekit/test/transaction.test.ts
We talked about this a few times, maybe increasing the timeout here helps!
=> test(e2e): Increase polling timeout from 30 to 90 seconds

packages/node/src/handlers.ts
We need to be a bit particular in our trpc middleware about error handling because trpc let's you throw errors as control flow.
Any random errors that bubble up, previously didn't get captured. We also don't wanna capture all errors, i.e. trpc 400s, only 500s. We use the `code` property to heuristically say that an error is a trpc error.
=> feat(node): Capture internal server errors in trpc middleware

packages/e2e-tests/test-applications/create-remix-app-v2/app/root.tsx, packages/e2e-tests/test-applications/create-remix-app-v2/tests/behaviour-client.test.ts, packages/e2e-tests/test-applications/create-remix-app/app/root.tsx, packages/e2e-tests/test-applications/create-remix-app/tests/behaviour-client.test.ts, packages/remix/src/index.server.ts, packages/remix/src/utils/types.ts
Fixes: https://github.com/getsentry/sentry-javascript/issues/9358
Exported a type to be used like:
```typescript
export const meta = ({ data }: SentryMetaArgs<MetaFunction<typeof loader>>) => {
return [
{
env: data.ENV,
},
{
name: 'sentry-trace',
content: data.sentryTrace,
},
{
name: 'baggage',
content: data.sentryBaggage,
},
];
};
```
So the types from `loader` function and our injections are both available in type checking.
Also, updated e2e tests to include `meta` injection checks for root and sub-routes.
=> feat(remix): Export a type to use for `MetaFunction` parameters

packages/astro/package.json
Astro's Vite plugin tries to detect if a package is an "astro component package" (i.e. contains `.astro`) files by checking for a bunch of heuristics in the project's `package.json`. These packages will be run through the Astro compiler. 
https://github.com/withastro/astro/blob/7c458514c06c95158245bba4fa3c254abd333f5a/packages/astro/src/core/create-vite.ts#L74-L89
Because our SDK package matches multiple of the used heuristics, it is added to the compiler build which causes errors because some of our packages make the build fail (not sure why/how). Apparently, this is only problematic when the project is managed by `pnpm` which results in a build error. Other package managers don't seem to have a problem.
This PR adds the `astro.external: true` flag to the `package.json` which …
=> fix(astro): Mark SDK package as Astro-external

packages/astro/src/server/meta.ts, packages/astro/src/server/middleware.ts, packages/astro/test/server/meta.test.ts, packages/astro/test/server/middleware.test.ts
This PR adds `<meta>` tag injection in our new `handleRequest` Astro middleware to enable distributed traces between BE and FE transactions. 
This is also the first step towards exporting a `<meta>` tag helper function (tracked in #8438). In a future PR I'll extract the function to the core or utils package and export it in our server-side SDKs.
As with all our connected traces via <meta> tags, the trace ordering is wrong in the sense that the FE transaction is the child of the BE transaction. We should fix this but this is out of scope for this PR
ref #9444 
ref #8438
=> feat(astro): Add distributed tracing via `<meta>` tags

packages/feedback/src/sendFeedback.ts, packages/feedback/src/types/index.ts, packages/feedback/src/util/handleFeedbackSubmit.ts, packages/feedback/src/util/sendFeedbackRequest.ts, packages/feedback/test/sendFeedback.test.ts, packages/feedback/test/utils/mockSdk.ts, packages/feedback/test/widget/createWidget.test.ts
`sendFeedback` now sends a `source` property in the feedback context. `source` will be `api` if you call `sendFeedback` directly, otherwise `widget` when called from widget UI.
=> feat(feedback): Add `source` to feedback payload

packages/browser-integration-tests/suites/integrations/Breadcrumbs/dom/click/test.ts, packages/browser-integration-tests/suites/replay/extendNetworkBreadcrumbs/xhr/captureRequestHeaders/test.ts, packages/browser-integration-tests/suites/replay/privacyInputMaskAll/test.ts
...maybe
Based on what we did in #9025
=> test(browser-integration): Tweak promises a bit to reduce flakes in replay tests

packages/node-integration-tests/suites/tracing-new/prisma-orm/test.ts, packages/node-integration-tests/suites/tracing/prisma-orm/test.ts, packages/tracing-internal/src/node/integrations/prisma.ts, packages/tracing/test/integrations/node/prisma.test.ts
Prisma can be used for NoSQL dbs like mongo, so change the span op from `db.sql.prisma` to `db.prisma`
=> fix(tracing): Update prisma span to be `db.prisma`

CHANGELOG.md
Update our CHANGELOG to include details about the security fixes for CVE-2023-46729 in version 7.77.0.
=> chore: include CVE details for security fixes on 7.77.0

packages/remix/test/integration/package.json
This should fix integration tests for remix.
It seems this version: https://github.com/vanilla-extract-css/vanilla-extract/releases/tag/%40vanilla-extract%2Fcss%401.14.0 switched a dependency which fails on Node 14. so pinning on the previous version here...
=> build(remix): Fix version for remix build on node 14

packages/nextjs/src/config/loaders/types.ts, packages/nextjs/src/config/loaders/wrappingLoader.ts, packages/nextjs/test/config/wrappingLoader.test.ts
I'd assume we thought `path.posix.normalize()` will turn backslashes into forwardslashes. It doesn't so we'll fix that by just replacing them.
Fixes https://github.com/getsentry/sentry-javascript/issues/9525
=> fix(nextjs): Fix serverside transaction names on Windows

packages/replay/src/coreHandlers/util/fetchUtils.ts, packages/replay/src/coreHandlers/util/networkUtils.ts, packages/replay/src/coreHandlers/util/xhrUtils.ts
This adds additional safeguards around fetch/xhr body capturing for replay.
I added additional try-catch in all places that depend on `networkCaptureBodies`.
This also types the fetch/xhr hints as `Partial` to ensure we guard against any of the things not actually being defined, to be on the safe side.
Hopefully fixes https://github.com/getsentry/sentry-javascript/issues/9339
=> fix(replay): Add additional safeguards for capturing network bodies

packages/nextjs/src/config/webpack.ts
Ref https://github.com/getsentry/sentry-javascript/issues/8659#issuecomment-1806942132
=> ref(nextjs): Improve wording in case CLI is missing

packages/astro/src/integration/index.ts, packages/astro/test/integration/index.test.ts
For some reason our automatic assets detection in the Vite plugin doesn't work well in Astro builds. While client files were picked up and uploaded correctly, server-side source and map files were not uploaded.
This PR ensures we search for files to be uploaded in the entire output directory by building an `assets` glob from the output directory stored in the `config` object. Once again Astro's integrations API comes in super handy here as this already gives us a custom output directory if users overwrote the default (`/dist`) one.
=> fix(astro): Adjust Vite plugin config to upload server source maps

packages/node/src/handlers.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/9536
The issue was that the middleware returned a function that returned `Promise<Promise<T>>` instead of `Promise<T>`. To fix this we take care not to modify the return value at all and just return T.
We could have also casted to `any` I think but this is probably cleaner.
=> fix(node): Fix tRPC middleware typing

MIGRATION.md, packages/astro/src/index.server.ts, packages/browser/src/index.ts, packages/bun/src/index.ts, packages/core/src/tracing/index.ts, packages/core/src/tracing/utils.ts, packages/deno/src/index.ts, packages/node-experimental/src/index.ts, packages/node/src/index.ts, packages/remix/src/index.server.ts, packages/sveltekit/src/server/index.ts, packages/tracing-internal/src/exports/index.ts, packages/tracing/src/index.ts, packages/vercel-edge/src/index.ts
Instead, users should import this from `@sentry/utils`.
This was also re-exported from all downstream packages (e.g. `@sentry/browser`, `@sentry/node`). I don't think this is something users need to import from there...? If you need this, installing `@sentry/utils` is probably fine? 
Else if we think we want to keep exporting this, we can also remove the comment, but then we should just properly move this from utils to core and instead remove the utils export, I'd say.
=> ref: Deprecate `extractTraceParentData` from `@sentry/core` & downstream packages

packages/e2e-tests/test-applications/nextjs-app-dir/app/server-action/page.tsx, packages/e2e-tests/test-applications/nextjs-app-dir/next.config.js, packages/e2e-tests/test-applications/nextjs-app-dir/tests/transactions.test.ts, packages/nextjs/src/common/index.ts, packages/nextjs/src/common/withServerActionInstrumentation.ts
Adds a `withServerActionInstrumentation` function that allows for wrapping the contents of server actions with Sentry instrumentation:
```ts
import * as Sentry from "@sentry/nextjs";
import { headers } from 'next/headers';
export default function ServerComponent() {
async function myServerAction(formData: FormData) {
"use server";
return await Sentry.withServerActionInstrumentation(
"myServerAction",
{ formData, headers: headers(), recordResponse: true },
async () => {
await fetch("http://example.com/");
return { city: "Vienna" };
}
);
}
return (
<form action={myServerAction}>
<input
type="text"
defaultValue={"some-default-value"}
name="some-text-value"
/>
<button type="submit">Run Action</button>
</form>
);
}
```
Will look like:
I would have wanted the API to be the following but Next.js …
=> feat(nextjs): Add instrumentation utility for server actions

.github/workflows/codeql-analysis.yml
This expands CodeQL to cover more potentially vulnerable code paths.
In addition to the current detections, this will add detections for:
```
> github/codeql/java/ql/src/Security/CWE/CWE-079/AndroidWebViewSettingsEnabledJavaScript.ql
> github/codeql/java/ql/src/Security/CWE/CWE-079/AndroidWebViewAddJavascriptInterface.ql
> github/codeql/javascript/ql/src/Security/CWE-117/LogInjection.ql
> github/codeql/javascript/ql/src/Security/CWE-384/SessionFixation.ql
> github/codeql/javascript/ql/src/Security/CWE-400/RemotePropertyInjection.ql
> github/codeql/javascript/ql/src/Security/CWE-078/IndirectCommandInjection.ql
> github/codeql/javascript/ql/src/Security/CWE-020/MissingRegExpAnchor.ql
> github/codeql/javascript/ql/src/Security/CWE-020/MissingOriginCheck.ql
> …
```
=> codeql: use extended query pack

packages/browser-integration-tests/suites/manual-client/browser-context/init.js, packages/browser-integration-tests/suites/manual-client/browser-context/test.ts
While debugging something, figured it is good to have a test covering that this works as expected!
See also: https://github.com/getsentry/sentry-docs/pull/8495
=> test: Add test for manual client usage

packages/replay/src/coreHandlers/util/networkUtils.ts, packages/replay/src/coreHandlers/util/xhrUtils.ts
We got somewhat closer to figuring out the problem there. Based on this comment: https://github.com/getsentry/sentry-javascript/issues/9339#issuecomment-1811681894
> The requests are now showing with the request body, but the response body is "undefined"
It seems that the problem is with parsing the response body for a XHR request. I added some more logging there, to be able to debug this further.
=> ref(replay): Add further logging to network body parsing

packages/nextjs/package.json, packages/nextjs/src/config/webpack.ts, yarn.lock
Fixes https://github.com/getsentry/sentry-javascript/issues/8659
With this change we will attempt to download the Sentry CLI binary if we detect that it doesn't exist.
We have to do this in a plugin because we cannot run async code in the config generation code. This generally works well. There is some ugliness involved because our webpack plugin has compat issues with Next.js.
=> fix(nextjs): Download CLI binary if it can't be found

packages/browser-integration-tests/suites/feedback/captureFeedback/init.js, packages/browser-integration-tests/suites/feedback/captureFeedback/template.html, packages/browser-integration-tests/suites/feedback/captureFeedback/test.ts, packages/browser-integration-tests/suites/feedback/captureFeedbackAndReplay/init.js, packages/browser-integration-tests/suites/feedback/captureFeedbackAndReplay/template.html, packages/browser-integration-tests/suites/feedback/captureFeedbackAndReplay/test.ts, packages/feedback/src/constants.ts, packages/feedback/src/sendFeedback.ts, packages/feedback/src/util/handleFeedbackSubmit.ts, packages/feedback/src/util/prepareFeedbackEvent.ts, packages/feedback/src/util/sendFeedbackRequest.ts, packages/feedback/test/sendFeedback.test.ts, packages/replay/src/coreHandlers/handleGlobalEvent.ts
Also adds a browser integration test as well
=> feat(feedback): Add `level` and remove breadcrumbs from feedback event

packages/node/src/anr/index.ts
If communicating via debugger to generate a stack trace fails, then fall back to a regular event, instead of throwing an uncaught exception.
If the parent process exits, exit the ANR child.
Fixes #9546
---
(Tests would be a good idea, but I don't see pre-existing tests for the ANR feature and am not sure the best way to add them.)
=> fix(node): Improve error handling and shutdown handling for ANR

packages/feedback/README.md, packages/feedback/src/integration.ts, packages/feedback/src/types/index.ts, packages/feedback/src/widget/Dialog.ts, packages/feedback/src/widget/Form.ts, packages/feedback/src/widget/createWidget.ts, packages/feedback/test/widget/Dialog.test.ts, packages/feedback/test/widget/Form.test.ts, packages/feedback/test/widget/createWidget.test.ts
Remove isAnonymous option from feedback because it clashes with sentry user
Closes https://github.com/getsentry/sentry-javascript/issues/9585
=> ref(feedback): Remove isAnonymous option from feedback

packages/core/src/baseclient.ts, packages/feedback/src/sendFeedback.ts, packages/feedback/src/util/prepareFeedbackEvent.ts, packages/feedback/src/util/sendFeedbackRequest.ts, packages/feedback/test/widget/createWidget.test.ts, packages/replay/src/util/addGlobalListeners.ts, packages/types/src/client.ts
Add a `beforeSendFeedback` hook that replay listens to, to attach replayId to the feedback event.
=> ref(feedback): Refactor attaching replay id to feedback event to use hooks

packages/feedback/package.json, packages/feedback/src/constants.ts, packages/feedback/src/integration.ts, packages/feedback/src/widget/Icon.ts, packages/feedback/src/widget/Logo.ts, packages/feedback/src/widget/SuccessIcon.ts, packages/feedback/src/widget/createShadowHost.ts, packages/feedback/src/widget/util/createElement.ts
We will be exporting the Feedback package from the `@sentry/browser` package, so to avoid circular imports when we do, we should remove imports from `@sentry/browser`
(this is what we did in Replay)
=> ref(feedback): Do not import window from browser pkg to avoid circular import

packages/deno/package.json
Fixes https://github.com/getsentry/sentry-javascript/issues/9609
Not sure how best to test this, suggestions are welcome! Will add tests in another PR to not unblock this though.
=> fix(deno): Make sure files get published

packages/astro/src/server/middleware.ts, packages/astro/test/server/middleware.test.ts
Although adding method is nice to span op, it duplicates information that is already in span description.
In addition, we want to reduce the total list of span ops as much as possible for cardinality reasons, `http.server` + span data about method is good enough to understand intent here.
=> fix(astro): Remove method from span op

packages/nextjs/src/config/loaders/valueInjectionLoader.ts
> https://github.com/getsentry/sentry-javascript/commit/9f32c618cf91b5e6091deacd8801a7b28660c7d5#diff-55396f0a8f12ba2eb7ce27f3cf886f946c29c2aa93b5d2f993dadbd5a9f3cc75L979
Due to this commit, `sentry.edge.config.js` is added. But `global` doesn't exist in edge runtime, so we should use `globalThis`.
Error Msg:
=> fix(nextjs): Use `globalThis` instead of `global` in edge runtime

packages/node/src/handlers.ts
Carrying on work from https://github.com/getsentry/sentry-javascript/pull/9606
I thought about doing more w/ removing `startTransaction`, but given this is going away soon in v8/otel, not touching it.
=> ref(node): Use Sentry.continueTrace in node

packages/bun/src/integrations/bunserver.ts
Testing out `Sentry.continueTrace`
At this point with `runWithAsyncContext`, `continueTrace`, and `startSpan` feeling like I'm in callback hell a little, but manageable.
=> ref(bun): Use Sentry.continueTrace in Bun

packages/feedback/README.md, packages/feedback/src/integration.ts, packages/feedback/src/types/index.ts, packages/feedback/src/widget/createWidget.ts, packages/feedback/test/integration.test.ts, packages/feedback/test/widget/createWidget.test.ts
Rename the onDialogOpen and onDialogClose callbacks to onFormOpen and onFormClose to match our defined terminology and remove onActorClick as it's not necessary.
Closes https://github.com/getsentry/sentry-javascript/issues/9605
=> ref(feedback): Rename onDialog* to onForm*, remove onActorClick

packages/replay/src/coreHandlers/util/networkUtils.ts
We aren't actually using this anymore anywhere.
=> ref(replay): Remove unused method

packages/replay/src/coreHandlers/util/fetchUtils.ts, packages/replay/src/coreHandlers/util/networkUtils.ts, packages/replay/src/coreHandlers/util/xhrUtils.ts, packages/replay/src/types/request.ts, packages/replay/test/unit/coreHandlers/handleNetworkBreadcrumbs.test.ts, packages/replay/test/unit/coreHandlers/util/fetchUtils.test.ts
This is a tricky one 😬 Basically, it is possible that fetch returns a readable stream that is ongoing. So if we do `await response.text()` this will be pending forever, if a stream is ongoing.
I haven't found a way to really check that is the case and avoid parsing this at all 🤔 So the best I could come up with was to instead add a timeout of 500ms when we stop waiting for the fetch body.
This should at least unblock waiting on this, but it will still mean that the response continues to be parsed client-side - I don't think there is a way to abort this 🤔 
Additionally, this also refactors this a bit so we add a new `BODY_PARSE_ERROR` meta warning if the parsing of the body fails, for whatever reason. we may also use this in the replay UI cc @ryan953 somehow?
"fixes" …
=> fix(replay): Add `BODY_PARSE_ERROR` warning & time out fetch response load

packages/core/src/tracing/trace.ts, packages/core/test/lib/tracing/trace.test.ts
Inspired by recent comments about the continueTrace method, I figured we can actually update this in a backwards-compatible way to _also_ allow to use it without a callback.
=> feat(core): Allow to use `continueTrace` without callback

packages/node/src/integrations/index.ts, packages/node/src/integrations/spotlight.ts, packages/node/src/sdk.ts, packages/node/src/types.ts, packages/node/test/integrations/spotlight.test.ts
This PR adds a new top level option called `spotlight` to Node init options. Under the hood, if this option is true, 
* all integrations will be forcefully initialized . This ensures that without a DSN, we still capture and process events (but simply don't send them to Sentry)
* a new `Spotlight` integration is added. This integration will make a `http` post request to the sidecar URL. Either we take the default sidecar URL or users provide their own URL:
```js
// enable/disable
Sentry.init({
spotlight: process.env.NODE_ENV === "development"
});
// enbale by setting a custom URL
Sentry.init({
spotlight: process.env.NODE_ENV === "development" ? 'http://localhost:7777' : false 
});
```
This option should also work in Node Experimental, given that Node experimental just calls the node init …
=> feat(node): Add Spotlight option to Node SDK

packages/browser/src/helpers.ts, packages/browser/src/sdk.ts, packages/browser/test/unit/index.test.ts, packages/core/src/api.ts, packages/core/test/lib/api.test.ts
Adds an `onClose` callback to `showReportDialog`.
The callback is invoked when a `__sentry_reportdialog_closed__` MessageEvent is received. This is sent from the error page embed via `window.postMessage` and listened to in the sdk.
Please have a look at the accompanying PRs
* for the backend: https://github.com/getsentry/sentry/pull/59885
* for the docs: https://github.com/getsentry/sentry-docs/pull/8484
And here is a sample project that uses `onClose` to color the background green again after closing the widget:
https://github.com/arya-s/sentry-onclose-report-dialog
* Any `__sentry_reportdialog_closed__` message will call `onClose`, so if users use more than one widget per page it could wrongly trigger `onClose`. I figured the widget takes over the entire page and having more than one …
=> feat(feedback): Add onClose callback to showReportDialog (#9433)

packages/tracing-internal/src/browser/metrics/index.ts, packages/tracing-internal/test/browser/metrics/index.test.ts
There's a bug in some browsers that attaches huge resource sizes that are completely unrealistic. Here's an example in chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1324812#c25
To get around this, we add a filter to enforce that resource sizes should only be attached if the size is < 2147483647 bytes (size of maximum value of integer in c/c++).
@mydea should we add this to replay as well? Maybe a good time to unify the resource entry handling logic.
=> fix(tracing): Filter out invalid resource sizes

packages/astro/src/integration/index.ts
Because Vite plugin picks it up correctly from `.env.sentry-build-plugin`
=> fix: Remove Auth Token check here

packages/astro/README.md, packages/astro/package.json, packages/astro/rollup.npm.config.js, packages/astro/src/index.server.ts, packages/astro/src/integration/index.ts, packages/astro/src/integration/middleware/index.ts, packages/astro/src/integration/types.ts, packages/astro/src/server/middleware.ts, packages/astro/test/integration/index.test.ts, packages/astro/test/integration/middleware/index.test.ts, yarn.lock
This PR adds automatic registration of our Astro middleware. This is possible since Astro 3.5.2 by [adding middleware](https://docs.astro.build/en/reference/integrations-reference/#addmiddleware-option) entry points in the astro integration's setup hook.
[Updated Readme](https://github.com/getsentry/sentry-javascript/blob/8e3a32cfa9cee0c0d2a8d596d0e746d0ebe2edb8/packages/astro/README.md#server-instrumentation)
This is backwards compatible with previous Astro versions because we can simply check if the `addMiddleware` function exists and only make use of it if it does. 
ref #9444
=> feat(astro): Automatically add Sentry middleware in Astro integration

packages/core/src/hub.ts, packages/core/src/sdk.ts, packages/deno/src/transports/index.ts, packages/integration-shims/package.json, packages/integration-shims/src/BrowserTracing.ts, packages/integration-shims/src/Replay.ts, packages/nextjs/src/common/wrapApiHandlerWithSentry.ts, packages/nextjs/src/config/webpack.ts, packages/node/src/integrations/utils/errorhandling.ts, packages/node/src/transports/http.ts, packages/opentelemetry/src/custom/hubextensions.ts, packages/remix/src/utils/instrumentServer.ts, packages/replay/src/integration.ts, packages/replay/src/util/getPrivacyOptions.ts, packages/sveltekit/src/client/handleError.ts, packages/utils/src/dsn.ts, packages/vue/src/errorhandler.ts, packages/vue/src/integration.ts
Fixes https://github.com/getsentry/sentry-javascript/issues/9640
=> fix: Wrap all console log instances in console sandbox
