getsentry/sentry-javascript

packages/remix/src/client/errors.tsx
packages/remix/src/utils/instrumentServer.ts

Closes: #9279
Note: The original case mentioned in the issue (capturing 404 responses) is addressed by https://github.com/getsentry/sentry-javascript/pull/9655.

fix(remix): Check the error data before spreading.

---

packages/astro/src/integration/index.ts
packages/astro/test/integration/index.test.ts

This PR adds support for uploading sourcemaps when using the `@astrojs/vercel/*` adapters. 
It seems that the adapter updates the config.outdir value too late for our previous detection logic to 
correctly detect the .vercel output directory. Furthermore, the adapter for some reason first saves server 
files to <root>/dist only to copy it later to <root>/.vercel/functions. This copy command seems to happen too 
late for when our sourcemaps plugin runs.
For these two reasons, we try to detect the used adapter (love that this is much simpler in Astro than 
Sveltekit) and adjust the assets glob to search for files in both, `dist` and `.vercel`. 
Tested this for client side (island) and server-side errors with a test app deployed to vercel (serverless, not 
edge) and it seems to work well. …

fix(astro): Configure sourcemap assets directory for Vercel adapter

---

packages/astro/package.json

Astro 4.0.0 beta is out so let's adjust our peer deps!
I opted for an open max version for now. THere's a risk of this being problematic with future major versions but I'd argue we'd get support requests either way. The important part IMO is the lower bound.

chore(astro): Allow Astro 4.0 in peer dependencies

---

packages/replay/src/coreHandlers/handleDom.ts
packages/replay/src/coreHandlers/util/domUtils.ts
packages/types/src/instrument.ts
packages/utils/src/instrument/dom.ts
packages/utils/src/instrument/history.ts
packages/utils/src/instrument/index.ts
packages/utils/src/instrument/xhr.ts

This is a hotfix for https://github.com/getsentry/sentry-javascript/issues/9679.
We leaked Browser/React types into the generic `@sentry/types` package which should not have any runtime specific types.
cc @mydea if you want to clean this up again at some point

fix: Don't depend on browser types in `types`

---

packages/astro/src/integration/index.ts
packages/astro/src/integration/types.ts
packages/astro/test/integration/index.test.ts

This PR adds the `assets` option to the Astro integration source maps upload options.
It behaves just like the `assets` option of the Vite plugin, taking a (array of) glob(s) and overriding the 
default values. 
This came up in #9591 and I think it makes sense to give users with more advanced/custom setups the ability to 
override our defaults.
Docs PR: https://github.com/getsentry/sentry-docs/pull/8586

feat(astro): Add `assets` option to source maps upload options

---

packages/nextjs/src/config/webpack.ts

Fixes https://github.com/getsentry/sentry-javascript/issues/9681
With https://github.com/getsentry/sentry-javascript/pull/9637 we likely introduced a bug where we started matching any files called `middleware`, also inside node modules.
This PR limits the amount of files we match to a very strict list.

fix(nextjs): Don't match files called `middleware` in node_modules

---

packages/tracing-internal/src/browser/metrics/index.ts
packages/tracing-internal/test/browser/metrics/index.test.ts

Resource size can be null in some browsers, so don't set it if it's null (only set integers).

fix(tracing): Don't attach resource size if null

---

packages/remix/src/client/errors.tsx

Resolves: #9489
Manually tested. Could not figure a way to e2e or integration test this, with our current test setup.
Note: Server-side transactions are still reported regardless they are 404 or not.

fix(remix): Don't capture error responses that are not 5xx on Remix v2.

---

packages/astro/src/integration/index.ts
packages/astro/src/integration/types.ts
packages/astro/test/integration/index.test.ts

This PR adds a guard to avoid adding the Sentry Vite plugin for source maps upload in dev mode. 
Reason: The vite plugin ships with a Sentry SDK. This SDK conflicts with the Astro server-side SDK. For example for some reason, it skews up the line numbers of stack frames. Not exactly sure why that's happening but my best guess is that the plugin SDK somehow changes code (maybe we even inject debugIds or release values or something like this) that mixes up line numbers. 
Anyway, I think it's generally more correct to not use the plugin in dev mode.

fix(astro): Avoid adding the Sentry Vite plugin in dev mode

---

package.json

The LTS release is now Node v20. I propose using v20 on our local machines.

chore: update node.js to v20

---

packages/tracing-internal/src/browser/web-vitals/getINP.ts
packages/tracing-internal/src/browser/web-vitals/lib/polyfills/interactionCountPolyfill.ts
packages/tracing-internal/src/browser/web-vitals/types/inp.ts

Resolves https://github.com/getsentry/sentry-javascript/issues/9660
vendored in from https://github.com/GoogleChrome/web-vitals/tree/7f0ed0bfb03c356e348a558a3eda111b498a2a11
Note that this is on web vitals `v3.0.4`. We need to update to latest web vitals version - will do this in a follow up PR.

feat(web-vitals): Vendor in INP from web-vitals library

---

.github/workflows/build.yml

Let's add Node.js v21 to detect breaking changes faster.

build: add node.js v21 to test matrix

---

packages/nextjs/src/config/types.ts
packages/nextjs/src/config/webpack.ts

Resolves https://github.com/getsentry/sentry-javascript/issues/8701

ref(nextjs): Set `automaticVercelMonitors` to be `false` by default

---

packages/core/src/metrics/index.ts
packages/types/src/envelope.ts
packages/types/src/index.ts
packages/types/src/metrics.ts

ref https://github.com/getsentry/sentry-javascript/issues/9691
Not adding any tests for `createMetricEnvelope` yet because the type for `metricAggregate` is going to change, just added it as boilerplate.
In the next PR I'll be implementing a metrics aggregator class which lives on the client. This is responsible for bucketing metrics and incrementally flushing them out.
https://develop.sentry.dev/delightful-developer-metrics/
https://develop.sentry.dev/delightful-developer-metrics/sending-metrics-sdk/

feat(metrics): Add interfaces for metrics

---

packages/feedback/src/widget/Dialog.css.ts

This makes it consistent with the buttons box shadow, so they both have the same box shadow by default.

ref(feedback): Change form `box-shadow` to use CSS var

---

packages/browser-integration-tests/suites/replay/extendNetworkBreadcrumbs/xhr/captureResponseBody/test.ts
packages/replay/src/coreHandlers/util/networkUtils.ts
packages/replay/src/coreHandlers/util/xhrUtils.ts
packages/replay/src/types/request.ts
packages/replay/test/unit/coreHandlers/util/fetchUtils.test.ts
packages/replay/test/unit/coreHandlers/util/networkUtils.test.ts
packages/replay/test/unit/coreHandlers/util/xhrUtils.test.ts

This is stupid, now that I figured it out. Basically, if you set `xhr.responseType = 'json'`, it will force `xhr.response` to be a POJO - which we can't parse right now.
We now handle this case specifically. 
This also adds a new `UNPARSEABLE_BODY_TYPE` meta warning if we are not getting a body because it is not matching any of the known/parsed types.
Closes https://github.com/getsentry/sentry-javascript/issues/9339

fix(replay): Capture JSON XHR response bodies

---

packages/astro/src/server/middleware.ts
packages/astro/test/server/middleware.test.ts
packages/core/src/tracing/trace.ts

This PR adds isolation to our sever-side request instrumentation, similarly to the request handler in 
Sveltekit.
Note for reviewers: The changes look more drastic than they are. The gist is, we run the previous instrumentation in a new async context if there's no ongoing span. Otherwise we just call the instrumentation.

fix(astro): Isolate request instrumentation middleware on server side

---

docs/new-sdk-release-checklist.md
packages/nextjs/test/integration/package.json
packages/remix/test/integration/package.json

Manually syncing into master to restart the 7.85.0 release

Sync Develop -> Master

---

packages/e2e-tests/test-applications/create-remix-app-v2/app/entry.server.tsx
packages/e2e-tests/test-applications/create-remix-app/app/entry.server.tsx
packages/remix/src/client/errors.tsx
packages/remix/src/index.server.ts
packages/remix/src/utils/instrumentServer.ts
packages/remix/src/utils/vendor/types.ts
packages/remix/test/integration/app_v1/routes/server-side-unexpected-errors/$id.tsx
packages/remix/test/integration/app_v1/routes/ssr-error.tsx
packages/remix/test/integration/app_v2/entry.server.tsx
packages/remix/test/integration/app_v2/routes/server-side-unexpected-errors.$id.tsx
packages/remix/test/integration/app_v2/routes/ssr-error.tsx
packages/remix/test/integration/common/routes/action-json-response.$id.tsx
packages/remix/test/integration/common/routes/server-side-unexpected-errors.$id.tsx
packages/remix/test/integration/common/routes/ssr-error.tsx
packages/remix/test/integration/test/client/ssr-error.test.ts
packages/remix/test/integration/test/server/action.test.ts
packages/remix/test/integration/test/server/loader.test.ts
packages/remix/test/integration/test/server/ssr.test.ts

Resolves: #9695
Should also resolve: #9563
Rewrote the error reporting logic of Remix SDK to handle inconsistencies, missing stack traces and potential duplications.
There are 5 main error types that we are concerned.
- Runtime Browser errors
- SSR Rendering errors
- Errors thrown in `loader`s and `actions`
- Error Responses
- Unexpected server-side errors
And there are different points we can capture such as:
- `handleError`,
- `action / loader / documentRequest` instrumentation
- `ErrorBoundary`
An error is not guaranteed to end up only one of those utilities. Also the objects for the same error are not guaranteed to be the same in different places. That causes duplications.
So, with this patch, the new error handling / filtering logic for the instrumentation will be as below:
| …

ref(remix): Rework Error Handling

---

packages/node/src/integrations/spotlight.ts
packages/node/test/integrations/spotlight.test.ts

Seems like the spotlight integration code is possibly ending up in places it shouldn't. 
While this PR doesn't adress this, it guards accessing `process.env.NODE_ENV` which we should do anyway.
Maybe addresses https://github.com/getsentry/sentry-javascript/issues/8377#issuecomment-1839948743

fix(node): Guard `process.env.NODE_ENV` access in Spotlight integration

---

.github/workflows/build.yml

build: Stop running overhead metrics in develop

---

packages/remix/package.json
yarn.lock

Take advantage of new binary distribution in https://github.com/getsentry/sentry-cli/pull/1836

feat(remix): Bump @sentry/cli to 2.22.3

---

packages/astro/README.md

It's time to set the Astro SDK status to beta

chore(astro): Promote Astro SDK to beta state (Readme)

---

packages/nextjs/src/config/webpack.ts

We should warn users if no `global-error.js` file is present in the app directory because that essentially means there is an instrumentation gap in their setup.
https://nextjs.org/docs/app/building-your-application/routing/error-handling#handling-errors-in-root-layouts

feat(nextjs): Emit warning if your app directory doesn't have a global-error.js file

---

packages/utils/src/instrument/xhr.ts

This was introduced in https://github.com/getsentry/sentry-javascript/pull/9542 😬 
Ideally we could have a lint rule for this, but probably this is rather hard to do - so reminder to self to keep an eye out for this in the future!
Closes https://github.com/getsentry/sentry-javascript/issues/9747
Note to reviewer(s): could you double check the file to make sure I didn't miss anything again? Just being cautious there...

fix(utils): Fix XHR instrumentation early return

---

packages/nextjs/src/client/index.ts

Fixes https://github.com/getsentry/sentry-javascript/issues/8727
When `assetPrefix` is defined the webpack dev server will live on that prefixed domain.
The SDK may attach tracing headers to the HMR server when the asset prefix is something like `http://cdn.localhost:3000` because we match on "localhost". Because this is then a different origin we run into CORS issues with the dev server.
This PR resolves that by special casing the `tracePropagationTargets` when Next.js is in dev mode. This is a bit of a hack for now.
Once we get to https://github.com/getsentry/sentry-javascript/issues/9764 we can remove the hack again.

fix(nextjs): Fix devserver CORS blockage when `assetPrefix` is defined

---

packages/node/src/handlers.ts

Fixes https://github.com/getsentry/sentry-javascript/issues/9780
Looks like I had a tiny bit of a brainfart in the previous implementation. tRPC invokations _shouldn't_ directly throw but instead return an object with `ok: false` and an `error` field. This is the error we should report instead.

fix(node): Capture errors in tRPC middleware

---

packages/replay/package.json
yarn.lock

> * Revert "fix: isCheckout is not included in fullsnapshot event (rrweb-io#1141)"
Fixes an issue where Meta event is being lost in buffered replays.
> revert: feat: Remove plugins related code, which is not used #123
> feat: Export additional canvas-related types and functions (#134)
Changes needed for canvas playback
> feat: Skip addHoverClass when stylesheet is >= 1MB #130
Affects playback only

feat(replay): Bump `rrweb` to 2.5.0

---

packages/core/src/hub.ts
packages/core/src/scope.ts
packages/core/src/utils/prepareEvent.ts
packages/opentelemetry-node/test/spanprocessor.test.ts
packages/opentelemetry/src/contextManager.ts
packages/opentelemetry/src/custom/client.ts
packages/opentelemetry/src/custom/hub.ts
packages/opentelemetry/src/custom/scope.ts
packages/opentelemetry/src/spanExporter.ts
packages/opentelemetry/test/custom/scope.test.ts

To avoid this static method there. It is deprecated to use `Scope.clone()` (but still works), but better to just use `scope.clone()` or `new Scope()` directly.

ref(core): Replace `Scope.clone()` with non-static `scope.clone()`

---

packages/browser/src/profiling/integration.ts
packages/browser/src/profiling/utils.ts
packages/types/src/envelope.ts
packages/types/src/index.ts

As suggested [here](https://github.com/getsentry/sentry-electron/pull/799#discussion_r1423316213) by @AbhiPrasad, this PR adds types for profile envelopes.

feat(types): Add profile envelope types

---

.vscode/settings.json

latest vscode will attempt to correct these values every time you open the project.
**The new options are:**
explicit - Triggers Code Actions when explicitly saved. Same as true. 
always - Triggers Code Actions when explicitly saved and on Auto Saves from window or focus changes. 
never - Never triggers Code Actions on save. Same as false.
https://code.visualstudio.com/updates/v1_85#_code-actions-on-save-and-auto

chore(vscode): Use new code action values `"explicit"`

---

packages/astro/src/index.server.ts
packages/browser/src/exports.ts
packages/bun/src/index.ts
packages/core/src/exports.ts
packages/core/src/index.ts
packages/deno/src/index.ts
packages/node/src/index.ts
packages/serverless/src/index.ts
packages/sveltekit/src/server/index.ts
packages/vercel-edge/src/index.ts

This can be used instead of `getCurrentHub().getScope()`, and is a step towards getting rid of `getCurrentHub()` as a top level API.

feat: Add top level `getCurrentScope()` method

---

packages/nextjs/src/common/_error.ts
packages/nextjs/src/common/utils/edgeWrapperUtils.ts
packages/nextjs/src/common/withServerActionInstrumentation.ts
packages/nextjs/src/common/wrapRouteHandlerWithSentry.ts
packages/nextjs/src/common/wrapServerComponentWithSentry.ts

We missed catching flushes in a few places which could cause problems if there are issues when sending events.

fix(nextjs): Catch rejecting flushes

---

packages/deno/src/integrations/context.ts
packages/deno/src/integrations/contextlines.ts
packages/deno/src/integrations/normalizepaths.ts

Where possible, we should use the new `processEvent` and/or `setup` hooks of the integrations, instead of `setupOnce`. This updates this for the deno integrations.

ref(deno): Update deno integrations to avoid `setupOnce`

---

packages/astro/src/server/middleware.ts
packages/astro/test/server/middleware.test.ts

- iterate over route segments to replace parameter values
- decode raw url to match previously unmatched param values
- prioritize multi-segment [rest parameters](https://docs.astro.build/en/core-concepts/routing/#rest-parameters) before iterating over individual segments

fix(astro): Avoid RegExp creation during route interpolation

---

packages/core/src/integrations/metadata.ts
packages/core/src/integrations/requestdata.ts
packages/core/test/lib/integrations/requestdata.test.ts
packages/node/test/integrations/requestdata.test.ts

Where possible, we should use the new `processEvent` and/or `setup` hooks of the integrations, instead of `setupOnce`. This updates this for the core integrations.

ref(core): Refactor core integrations to avoid `setupOnce`

---

packages/remix/package.json
yarn.lock

CLI v2.23.0 fixes an issue with debug id injection in Remix.
This PR just bumps Sentry CLI from 2.22.3 to 2.23.0.
h/t @brettdh for fixing this bug in the CLI!
resolves https://github.com/getsentry/sentry-javascript/issues/9666

ref(remix): Bump Sentry CLI to ^2.23.0

---

packages/nextjs/src/config/webpack.ts

Pointed out by @samijaber - in dev mode we have the possibility to add files to an entry point multiple times. This feels problematic, so fixing it here.

fix(nextjs): Guard against injecting multiple times

---

packages/replay/package.json
yarn.lock

This should fix an issue where we were unable to record canvas because the canvas manager bundle was split from the main `record` bundle and was unable to emit mutations from the canvas manager.

feat(replay): Bump `rrweb` to 2.6.0

---

packages/utils/src/instrument/globalError.ts
packages/utils/src/worldwide.ts

As that is browser only.
Closes https://github.com/getsentry/sentry-javascript/issues/9860

fix(utils): Do not use `Event` type in worldwide

---

packages/core/src/server-runtime-client.ts
packages/deno/src/integrations/globalhandlers.ts
packages/node/test/eventbuilders.test.ts
packages/utils/src/eventbuilder.ts
packages/utils/test/eventbuilder.test.ts

Instead we can pass a client directly, and I refactored the method to avoid setting extra on the scope, and just set it on the event directly - as this is also kind of leaking right now, because the extra may also be applied to other events using the same scope.

fix(utils): Update `eventFromUnknownInput` to avoid scope pollution & `getCurrentHub`

---

packages/node/src/integrations/context.ts
packages/node/src/integrations/contextlines.ts
packages/node/src/integrations/modules.ts
packages/node/test/index.test.ts

This refactors Node integrations to use `processEvent`.
Missing is the LocalVariables integration, as that is more complicated and may need to be refactored in a different way to properly work.

ref(node): Refactor node integrations to use `processEvent`

---

packages/utils/src/misc.ts
packages/utils/test/misc.test.ts

Fixes https://github.com/getsentry/sentry-javascript/issues/9250
Here is my proposal to fix `getRandomByte` function throwing an error due to `crypto.getRandomValues` returning `undefined` in old browser engines like Chromium 23.
This error could be fixed as well by using a polyfill in every project that imports and uses Sentry but, since the change of this PR only involved keeping the `Uint8Array` reference in a variable, I thought it would be worth it to give it a try.

fix(utils): Support crypto.getRandomValues in old Chromium versions

---

packages/core/src/utils/isSentryRequestUrl.ts
packages/core/test/lib/utils/isSentryRequestUrl.test.ts
packages/integrations/src/httpclient.ts
packages/node-experimental/src/integrations/http.ts
packages/node/src/integrations/http.ts
packages/node/src/integrations/undici/index.ts
packages/opentelemetry-node/src/utils/isSentryRequest.ts
packages/opentelemetry/src/utils/isSentryRequest.ts
packages/replay/src/util/shouldFilterRequest.ts
packages/vercel-edge/src/integrations/wintercg-fetch.ts

Step by step, eradicating the hub...
Note: I haven't found a way to mark an attribute type of a function as deprecated 😬 I think it's OK here, but generally a bit annoying/tricky...

ref: Pass client instead of hub to `isSentryRequestUrl`

---

packages/core/src/exports.ts
packages/core/src/hub.ts
packages/core/test/lib/exports.test.ts
packages/feedback/src/util/sendFeedbackRequest.ts
packages/types/src/hub.ts

To align this with OpenTelemetry and make some things possible that are currently not easily doable without `pushScope` / `popScope`.
Noticed this because currently it's not easily possible to e.g. use `withScope` in places like [this](https://github.com/getsentry/sentry-javascript/pull/9862#discussion_r1427826506).
This should be backwards compatible because any code that previously relied on this returning `void` should still work.

feat(core): Update `withScope` to return callback return value

---

packages/core/src/index.ts
packages/core/src/integration.ts
packages/core/src/integrations/inboundfilters.ts
packages/core/test/lib/integration.test.ts
packages/integrations/src/contextlines.ts
packages/types/src/index.ts
packages/types/src/integration.ts

This PR adds new types for function-based integrations, that eventually (in v8) should fully replace the class-based functions.
This also introduces a small helper function to make writing such integrations easier (as we need to set an id/name etc. on the integration). With this, you can write an integration like this:
```ts
const inboundFiltersIntegration = makeIntegrationFn(
'InboundFilters', 
(options: Partial<InboundFiltersOptions>) => {
return {
processEvent(event, _hint, client) {
const clientOptions = client.getOptions();
const mergedOptions = _mergeOptions(options, clientOptions);
return _shouldDropEvent(event, mergedOptions) ? null : event;
}
}
});
```
And you get a fully typed integration ready to go!
For backwards compatibility, and so that we can actually start converting …

feat(core): Add type & utility for function-based integrations

---

packages/browser/src/integrations/breadcrumbs.ts
packages/browser/test/unit/integrations/breadcrumbs.test.ts
packages/core/src/exports.ts
packages/node-experimental/src/integrations/http.ts
packages/node-experimental/src/integrations/node-fetch.ts
packages/node/src/integrations/console.ts
packages/node/src/integrations/http.ts
packages/node/src/integrations/undici/index.ts
packages/node/test/integrations/http.test.ts
packages/replay/src/util/log.ts
packages/vercel-edge/src/integrations/wintercg-fetch.ts
packages/vercel-edge/test/wintercg-fetch.test.ts

Instead of using `hub.addBreadcrumb()`.

ref: Use `addBreadcrumb` directly & allow to pass hint

---

packages/serverless/src/awslambda.ts
packages/serverless/test/awslambda.test.ts

This is the only place I've found where we use `pushScope`, and since we updated the `withScope` signature we can rewrite this.

ref(serverless): Avoid using `pushScope`

---

MIGRATION.md
packages/browser/test/unit/index.test.ts
packages/core/src/hub.ts
packages/node/test/index.test.ts
packages/opentelemetry/test/custom/hub.test.ts
packages/replay/test/integration/eventProcessors.test.ts
packages/types/src/hub.ts

This deprecates using `pushScope` / `popScope` on the hub.

feat(core): Deprecate `pushScope` & `popScope`

---

packages/replay/src/replay.ts
packages/replay/src/types/replay.ts

Defaults to `webp` instead of `png`. This will also allow `quality` to work.
Closes https://github.com/getsentry/team-replay/issues/326

feat(replay): Add `canvas.type` setting

---

packages/core/src/index.ts
packages/core/src/integration.ts
packages/node-experimental/src/index.ts
packages/node-experimental/src/integrations/http.ts
packages/node-experimental/src/otel/asyncContextStrategy.ts
packages/node-experimental/src/otel/contextManager.ts
packages/node-experimental/src/sdk/api.ts
packages/node-experimental/src/sdk/client.ts
packages/node-experimental/src/sdk/globals.ts
packages/node-experimental/src/sdk/hub.ts
packages/node-experimental/src/sdk/init.ts
packages/node-experimental/src/sdk/initOtel.ts
packages/node-experimental/src/sdk/scope.ts
packages/node-experimental/src/sdk/spanProcessor.ts
packages/node-experimental/src/sdk/types.ts
packages/node-experimental/src/utils/contextData.ts
packages/node-experimental/src/utils/prepareEvent.ts
packages/node-experimental/test/helpers/mockSdkInit.ts
packages/node-experimental/test/integration/breadcrumbs.test.ts
packages/node-experimental/test/integration/scope.test.ts
packages/node-experimental/test/integration/transactions.test.ts
packages/node-experimental/test/sdk/scope.test.ts
packages/node/src/index.ts
packages/opentelemetry/src/custom/scope.ts
packages/opentelemetry/src/index.ts
packages/opentelemetry/src/spanExporter.ts
packages/opentelemetry/src/spanProcessor.ts
packages/opentelemetry/src/utils/spanData.ts

This PR introduces the new scope APIs to node-experimental.
* `getCurrentHub()` is still around, but just a mock hub that uses other methods under the hood.
* Instead, there are the following new APIs:
* `getCurrentScope()`
* `getIsolationScope()`
* `getGlobalScope()`  
* `withIsolationScope()`
Mostly existing tests should cover this OK. The main change here is that for spans, since we use the isolation scope any tags etc. added while the span is running are _also_ added to the resulting event. 
For POTEL, we automatically set an isolation scope whenever a http.server span is generated.
Replaces https://github.com/getsentry/sentry-javascript/pull/9419

feat(node-experimental): Update to new Scope APIs

---

packages/deno/src/integrations/globalhandlers.ts

Slowly getting rid of `getCurrentHub()`...

ref(deno): Refactor deno integration to avoid `setupOnce`

---

packages/browser/src/integrations/globalhandlers.ts
packages/browser/src/profiling/integration.ts
packages/nextjs/src/common/wrapGenerationFunctionWithSentry.ts

ref(browser): Refactor browser integrations to avoid `setupOnce`

---

packages/sveltekit/package.json
scripts/prepack.ts

Looks like Vite 5 module resolution for `@sentry/sveltekit` only works with defining conditional exports. Tested this locally with a Sverdle kit@1, kit@2 and the syntax website. 
It'd be nice to get confirmation that this fixes https://github.com/syntaxfm/website/pull/1458 but based on my tests it should be fine 🤞 
Added an e2e test for Kit 2.0 in #9873 
ref #9851

fix(sveltekit): Add conditional exports

---

packages/remix/src/utils/instrumentServer.ts
packages/remix/test/integration/app_v1/routes/throw-redirect.tsx
packages/remix/test/integration/app_v2/routes/throw-redirect.tsx
packages/remix/test/integration/common/routes/throw-redirect.tsx
packages/remix/test/integration/test/client/throw-redirect.test.ts
packages/remix/test/integration/test/server/loader.test.ts

Fixes: #9906
Skips capturing all responses < 500 that end up in `captureRemixServerException`.

fix(remix): Do not capture thrown redirect responses.

---

packages/sveltekit/package.json
packages/sveltekit/src/client/handleError.ts
packages/sveltekit/src/server/handleError.ts
packages/sveltekit/test/common/utils.test.ts
packages/sveltekit/test/server/handleError.test.ts
yarn.lock

This PR improves our logic to filter out "Not Found" errors in our server-side `handleError` hook wrapper:
- We now use SvelteKit 2.0 - native [error properties](https://kit.svelte.dev/docs/migrating-to-sveltekit-2#improved-error-handling) (`status` ~and `message`~) to check for "Not Found" errors
- Adjusted types for type safety and backwards compatibility with SvelteKit 1.x where the ~two properties~ property don't exist.
- Updated Sveltekit to 2.0 in our dev dependency to work with latest types.
Not really happy with the two `@ts-expect-error` but I didn't find anything that looks nicer and still guarantees type safety when we work with the `input` object. Definitely open to ideas!
ref #9851

ref(sveltekit): Improve SvelteKit 2.0 Not Found server error handling

---

packages/e2e-tests/test-applications/sveltekit-2/package.json
packages/sveltekit/src/client/handleError.ts
packages/sveltekit/test/client/handleError.test.ts

I belive, these errors weren't passed to the client side `handleError` hook in Kit 1.x but in 2.x they're now passed into the hook. This means, we need to filter them out. 
Added the same logic for the client side as in #9901
ref #9851

fix(sveltekit): Avoid capturing 404 errors on client side

---

packages/node/src/integrations/console.ts
packages/node/src/integrations/onuncaughtexception.ts
packages/node/src/integrations/onunhandledrejection.ts
packages/node/test/onuncaughtexception.test.ts
packages/node/test/onunhandledrejection.test.ts

Slowly getting rid of `getCurrentHub()`...

ref(node): Refactor node integrations to avoid `setupOnce`

---

packages/core/src/index.ts
packages/core/src/scope.ts
packages/core/src/utils/applyScopeDataToEvent.ts
packages/core/src/utils/prepareEvent.ts
packages/feedback/test/unit/util/prepareFeedbackEvent.test.ts
packages/node-experimental/src/sdk/scope.ts
packages/node-experimental/test/sdk/scope.test.ts
packages/node/src/integrations/hapi/index.ts
packages/node/test/integrations/requestdata.test.ts
packages/opentelemetry/src/custom/scope.ts
packages/replay/test/unit/util/prepareReplayEvent.test.ts
packages/types/src/index.ts
packages/types/src/scope.ts

This is a try to move the application of scope data to events out of the scope class into a util function.
This changes the flow to be:
1. The scope has a `getScopeData()` method that returns data that should be applied to events.
2. The `prepareEvent` method uses that to actually apply scope data to the event etc.
3. This also makes it much easier to do the experimentation in node-experimental (https://github.com/getsentry/sentry-javascript/pull/9799) because we only need to overwrite this, and can leave the rest of the event processing the same.
I _think_ this makes sense but would appreciate some more eyes on this as well. For me the separation makes also more sense, as e.g. the application of event processors etc. should not really be tied to the scope at all.
This is also is a first …

feat(core): Extract scope application to util

---

packages/integrations/src/captureconsole.ts
packages/integrations/src/debug.ts
packages/integrations/src/httpclient.ts
packages/integrations/src/reportingobserver.ts
packages/integrations/test/captureconsole.test.ts
packages/integrations/test/debug.test.ts
packages/integrations/test/reportingobserver.test.ts

Slowly getting rid of `getCurrentHub()`...

ref(integrations): Refactor pluggable integrations to avoid `setupOnce`

---

packages/replay/src/constants.ts
packages/replay/src/replay.ts
packages/replay/src/types/replay.ts
packages/replay/test/integration/rrweb.test.ts

Instead of using canvas recording quality values direct to rrweb, use presets to control image quality and fps.
Closes https://github.com/getsentry/team-replay/issues/325

feat(replay): Change to use preset quality values

---

packages/replay/src/coreHandlers/handleBeforeSendEvent.ts
packages/replay/test/integration/coreHandlers/handleBeforeSendEvent.test.ts

Refine the regex to match fewer errors, seeing some false positives in replays that are not hydration errors.
fixes https://github.com/getsentry/sentry/issues/61943

fix(replay): Adjust development hydration error messages

---

packages/core/src/integration.ts
packages/core/src/integrations/functiontostring.ts
packages/core/src/integrations/linkederrors.ts
packages/core/src/integrations/metadata.ts
packages/core/src/integrations/requestdata.ts
packages/serverless/test/__mocks__/@sentry/node.ts
packages/serverless/test/gcpfunction.test.ts

Also make a small adjustment to the legacy converter util to ensure `setupOnce()` is callable with or without arguments, to remain stable.

ref(core): Refactor core integrations to functional style

---

package.json

CI keeps flaking on us on what it seems like a node/v8 bug. Let's revert to 18 to fix.

build: Set Volta Node.js version to 18

---

packages/sveltekit/package.json

Looks like we need to add a `types` field to the `"."` subpath in the `exports` object in package.json so that `svelte-check` type checking finds the type declarations of the SDK in Kit 2.0. 
fixes #9923

fix(sveltekit): Add `types` field to package.json `exports`

---

yarn.lock

To ensure we have up-to-date TS support, e.g. `satisfies` cannot be transpiled previously.
See https://github.com/alangpierce/sucrase/blob/main/CHANGELOG.md

build: bump sucrase to 3.34.0

---

.github/workflows/build.yml

If a purely internal package is added, it is not added to the lockfile which will not invalidate the dependency cache and will not include the new internal package (symlink) in the cached deps. This PR fixes that.

ci: Use `package.json`s as additional dependency cache key

---

packages/utils/src/browser.ts
packages/utils/test/browser.test.ts

Adds a utility function to get the frontend component name from a given DOM element. It also adjusts `htmlTreeAsString` to use the component name when applicable, when building out the string.
This is one part of this PR, splitting it up into multiple smaller PRs scoped to specific features:
https://github.com/getsentry/sentry-javascript/pull/9855

feat(utils): Add function to extract relevant component name

---

packages/browser/src/profiling/integration.ts
packages/bun/src/integrations/bunserver.ts
packages/core/src/metrics/integration.ts
packages/integration-shims/src/Feedback.ts

Some small fixes to integrations & rewriting some "forgotten" ones to functional syntax.

ref: Small integration refactors

---

packages/deno/src/integrations/context.ts
packages/deno/src/integrations/contextlines.ts
packages/deno/src/integrations/deno-cron.ts
packages/deno/src/integrations/globalhandlers.ts
packages/deno/src/integrations/normalizepaths.ts

Refactors deno integrations to functional syntax.

ref(deno): Refactor deno integrations to use functional syntax

---

packages/astro/src/index.server.ts
packages/bun/src/index.ts
packages/core/src/baseclient.ts
packages/core/src/hub.ts
packages/core/src/index.ts
packages/core/src/server-runtime-client.ts
packages/core/src/utils/prepareEvent.ts
packages/core/test/lib/prepareEvent.test.ts
packages/deno/src/index.ts
packages/feedback/src/util/prepareFeedbackEvent.ts
packages/hub/test/global.test.ts
packages/node-experimental/src/sdk/client.ts
packages/node-experimental/src/sdk/hub.ts
packages/node-experimental/src/sdk/scope.ts
packages/node-experimental/test/sdk/scope.test.ts
packages/node-integration-tests/suites/public-api/scopes/initialScopes/scenario.ts
packages/node-integration-tests/suites/public-api/scopes/initialScopes/test.ts
packages/node-integration-tests/suites/public-api/scopes/isolationScope/scenario.ts
packages/node-integration-tests/suites/public-api/scopes/isolationScope/test.ts
packages/node/src/index.ts
packages/opentelemetry/src/custom/client.ts
packages/replay/src/util/prepareReplayEvent.ts
packages/serverless/src/index.ts
packages/sveltekit/src/server/index.ts
packages/types/src/hub.ts
packages/vercel-edge/src/index.ts

Also ensure to actually export `getGlobalScope()` everywhere as well.
The isolation scope, currently, lies on the hub, and is applied to all events.

feat(core): Add `getIsolationScope()` method

---

packages/core/src/integration.ts
packages/core/test/lib/integration.test.ts
packages/deno/src/integrations/deno-cron.ts
packages/integrations/src/captureconsole.ts
packages/integrations/src/contextlines.ts
packages/integrations/src/debug.ts
packages/integrations/src/dedupe.ts
packages/integrations/src/extraerrordata.ts
packages/integrations/src/httpclient.ts
packages/integrations/src/reportingobserver.ts
packages/integrations/src/rewriteframes.ts
packages/integrations/src/sessiontiming.ts
packages/integrations/src/transaction.ts
packages/integrations/test/debug.test.ts
packages/integrations/test/dedupe.test.ts
packages/integrations/test/extraerrordata.test.ts
packages/integrations/test/reportingobserver.test.ts
packages/integrations/test/rewriteframes.test.ts
packages/integrations/test/sessiontiming.test.ts
packages/integrations/test/transaction.test.ts
packages/sveltekit/test/server/utils.test.ts

ref(integrations): Rewrite pluggable integrations to use functional style

---

packages/core/src/tracing/trace.ts
packages/core/test/lib/tracing/trace.test.ts

@lforst noticed that currently `startSpan()` and `startSpanManual` do not fork the scope, which is also a slightly different behavior than it is in OTEL.
This adjusts this to better align, so that we always fork a scope. We also always leave the span on the forked scope, even after it was finished.
In a follow up, we can thus also get rid of the `finish` callback arg for `startSpanManual`, as users can/should simply call `span.end()` themselves then.

feat(core): Ensure `startSpan` & `startSpanManual` fork scope

---

packages/react/src/profiler.tsx
packages/react/test/profiler.test.tsx

One of the PRs scoped from https://github.com/getsentry/sentry-javascript/pull/9855
Sends component names on the databag of React UI spans. This will allow us to group spans by component name, and query by component name in the future.

feat(react): Send component name on spans

---

packages/browser-integration-tests/suites/tracing/browsertracing/interactions/assets/script.js
packages/browser-integration-tests/suites/tracing/browsertracing/interactions/template.html
packages/browser-integration-tests/suites/tracing/browsertracing/interactions/test.ts
packages/tracing-internal/src/browser/metrics/index.ts

One of the PRs scoped from https://github.com/getsentry/sentry-javascript/pull/9855
Sends component names on the databag of interaction spans

feat(tracing): Send component name on interaction spans

---

packages/browser-integration-tests/suites/replay/captureComponentName/init.js
packages/browser-integration-tests/suites/replay/captureComponentName/template.html
packages/browser-integration-tests/suites/replay/captureComponentName/test.ts
packages/replay/src/coreHandlers/util/getAttributesToRecord.ts

One of the PRs scoped from https://github.com/getsentry/sentry-javascript/pull/9855
Sends component names on Replay UI breadcrumbs so they can be ingested and indexed. This will allow for searching for Replays by component name in the future.

feat(replay): Send component names in replay breadcrumbs

---

.size-limit.js

I think this was just not updated... I aligned it with the webpack size limit for the "full" bundle.

build: Fix size limit

---

packages/sveltekit/src/server/handle.ts
packages/sveltekit/test/server/handle.test.ts

This PR adds options to the `sentryHandle` request handler that allows control over CSP-relevant aspects for the `<script>` that the request handler injects into the page. Previously, the injected script was blocked by browsers if CSP was enabled, due to inline `<script>`s not being allowed without a nonce or hash. 
Users who configured CSP have now two options to deal with this script:
Users can pass a nonce to `sentryHandle` which will be added to the injected script: `<script nonce="...">`:
```js
// src/hooks.server.js
export const handle = sentryHandle({ fetchProxyScriptNonce: "2726c7f26c" })
```
This requires additional [CSP configuration](https://kit.svelte.dev/docs/configuration). For example:
```js
// svelte.config.js
kit: {
csp: {
directives: {
"script-src": ["nonce-2726c7f26c"], …
```

feat(sveltekit): Add options to configure fetch instrumentation script for CSP

---

packages/node-experimental/src/sdk/init.ts
packages/node/src/async/index.ts
packages/node/src/integrations/anr/index.ts
packages/node/src/integrations/http.ts
packages/node/src/integrations/localvariables.ts
packages/node/src/integrations/undici/index.ts
packages/node/src/integrations/utils/http.ts
packages/node/src/nodeVersion.ts
packages/node/test/integrations/http.test.ts
packages/node/test/integrations/localvariables.test.ts

These types have been annoying me for a while. We can safely assume the node version can be parsed.

fix(node): Make `NODE_VERSION` properties required

---

packages/core/src/hub.ts
packages/core/test/lib/exports.test.ts

Oops, I noticed that our current `withScope` implementation does not actually wait for async callbacks for setting the current scope 😬 Related to https://github.com/getsentry/sentry-javascript/pull/9958, which I copied there now!

fix(core): Ensure `withScope` sets current scope correctly with async callbacks

---

packages/serverless/src/awslambda.ts
packages/serverless/src/gcpfunction/cloud_events.ts
packages/serverless/src/gcpfunction/events.ts
packages/serverless/src/gcpfunction/http.ts
packages/serverless/test/__mocks__/@sentry/node.ts
packages/serverless/test/awslambda.test.ts
packages/serverless/test/gcpfunction.test.ts

Also refactor it to use `continueTrace`.
Note that this already uses the "new" way of `startSpanManual` which ignores the `finish` function.

ref(serverless): Use `startSpanManual()` instead of `startTransaction()`

---

packages/nextjs/src/common/utils/edgeWrapperUtils.ts
packages/nextjs/test/edge/edgeWrapperUtils.test.ts
packages/nextjs/test/edge/withSentryAPI.test.ts
packages/utils/src/requestdata.ts

Continuing work to eliminate `startTransaction` from the codebase.

ref: Remove `startTransaction` call from `withEdgeWrapping`

---

nx.json
package.json

We're doing a few thnings here:
1. Use lerna run for the workspace `build` script instead of run-s for a pretty straightforward scheduling optimization I guess.
2. We have weird CI flakes: [example](https://github.com/getsentry/sentry-javascript/actions/runs/7342967303/job/19992925304#step:7:322) and I hope we are solving this by differently caching the `build:types` ouptut. It seems like doing this solves the issue but I am not 100% sure about this...
3. We cache `build:tarball`

build(nx): Improve Nx setup

---

packages/astro/src/server/middleware.ts

Ref https://github.com/getsentry/sentry-javascript/issues/9985
Some context on the proposed change: https://github.com/whatwg/encoding/issues/184

fix(astro): Handle non-utf8 encoded streams in middleware

---

packages/remix/src/utils/instrumentServer.ts
packages/remix/src/utils/serverAdapters/express.ts
packages/remix/src/utils/vendor/types.ts
packages/remix/test/integration/test/server/loader.test.ts
packages/utils/src/requestdata.ts

Potentially fixes: #9963 
We have been using a boolean flag `isRequestHandlerWrapped` in the scope of `instrumentServer` to avoid instrumenting Remix build multiple times when an Express server adapter is manually instrumented too.
The reason behind that decision was that we could not be sure that the `build` object is the same, so looking for `__sentry_original__` on the wrapped function was not reliable all the time.
While we still can't reproduce locally, #9963 showed that this strategy (hack) may not work all the time, so I tried to find an alternative reliable way to resolve this.
This PR introduces instrumentation for `getLoadContext` which is available in all Remix server adapters, and passes data to `loader`/`action`/`requestHandler`s, to supply information about in which context …

ref(remix): Isolate Express instrumentation from server auto-instrumentation.

---

packages/astro/src/integration/index.ts
packages/astro/src/integration/types.ts
packages/astro/test/integration/index.test.ts

This PR adds a top level `enabled` option to the Astro integration options. This option can be used to globally enable/disable all Sentry features, either for client or server separately or for both sides simultaneously. 
* Disabeling either side will avoid the respective SDK code being injected into the bundles. 
* If both sides are disabled, source maps will not be generated and uploaded.
* If both or just the server side is disabled, the Sentry middleware won't be added.
* Obviously, this options defaults to `true`
```js
// astro.config.mjs
export default defineConfig({
sentry({
// disable entirely
enabled: false,
// or just one side
enabled: {
client: true, // <-- can also be omitted
server: false,
}
}),
],
});
```
closes #9783 
ref #9777

feat(astro): Add `enabled` option to Astro integration options

---

packages/astro/src/server/meta.ts
packages/eslint-config-sdk/src/base.js
packages/eslint-plugin-sdk/src/index.js
packages/eslint-plugin-sdk/src/rules/no-regexp-constructor.js
packages/nextjs/src/client/routing/pagesRouterRoutingInstrumentation.ts
packages/nextjs/src/config/loaders/prefixLoader.ts
packages/nextjs/src/config/loaders/wrappingLoader.ts
packages/nextjs/src/config/webpack.ts
packages/nextjs/src/edge/index.ts
packages/nextjs/src/server/index.ts
packages/sveltekit/src/server/utils.ts
packages/sveltekit/src/vite/sourceMaps.ts
packages/tracing-internal/src/node/integrations/express.ts
packages/utils/src/tracing.ts

This PR adds a new eslint rule that flags the usage of `new RegExp()` constructor calls. The purpose of this rule is to make us aware of the potential danger of creating a regular expression from (end) user input. This has led to security incidents in the past. 
To be clear, it is perfectly okay to ignore this rule in cases where we're sure that there's no danger or where input is already escaped. 
We have other rules (+CodeQL) in place to avoid RegExp usage with static expressions but these didn't cover regular expressions where the expression itself or the flags were constructed from variables. 
closes #9960

chore(eslint): Add eslint rule to flag `new RegExp()` usage

---

package.json

It used to output all the files it processed, which lead to a very verbose console output. By using `--check` we only get files that do not match.

build: Fix prettier lint command

---

packages/node/src/module.ts
packages/node/test/module.test.ts

Closes #10000 
- Caches the `basePath` so `dirname(require.main.filename)` only gets called once
- Now uses full path for module name
- Now correctly handles inside `node_modules`
- Add more tests

fix(node): Correctly resolve module name

---

packages/astro/src/integration/index.ts

- No need to call `process.cwd()` on every iteration.
- No need to create paths on memory

perf(astro): reduce unnecessary path resolutions

---

packages/astro/src/integration/index.ts

We can simply use `AstroIntegrationLogger` instead of console. This might improve DX. https://docs.astro.build/en/reference/integrations-reference/#astrointegrationlogger

Use astro logger instead of console

---

packages/astro/src/integration/index.ts

Fixes https://github.com/getsentry/sentry-javascript/issues/9777

fix(astro): prevent sentry from externalized

---

packages/node-integration-tests/suites/anr/test.ts
packages/node/src/integrations/anr/index.ts

If the inspector is already running, then ANR should be able to (re)use that, instead of opening it itself.
Fixes #10024

fix(node): Handle inspector already open

---

biome.json

Disabled `noDelete` to avoid a huge change log. We can enable it gradually.

build: enable biome performance rules

---

packages/core/src/tracing/trace.ts
packages/node-experimental/src/index.ts
packages/opentelemetry/src/index.ts
packages/opentelemetry/src/trace.ts
packages/opentelemetry/src/types.ts
packages/opentelemetry/test/trace.test.ts

This was brought up in Slack, currently you cannot pass other span properties directly to otel `startSpan()`. This now adds `attributes`, `kind` and `startTime` to better align with OTEL.
Note that I chose to omit `root` and `links` options, not sure if we want to support those in none-OTEL environments, and this API should (~~) be the same for node & non-node in v8.

feat(node-experimental): Allow to pass base span options to trace methods

---

packages/core/src/tracing/span.ts
packages/core/src/tracing/trace.ts
packages/core/test/lib/tracing/span.test.ts
packages/node/src/integrations/undici/types.ts
packages/sveltekit/src/server/handle.ts
packages/tracing/test/span.test.ts
packages/types/src/index.ts
packages/types/src/span.ts
packages/types/src/transaction.ts

Together with `setAttribute()` and `setAttributes()` APIs, mirroring the OpenTelemetry API for their spans.
For now, these are stored as `data` on spans/transactions, until we "directly" support them.

feat(core): Add `attributes` to `Span`

---

packages/core/src/integration.ts
packages/node/src/index.ts
packages/node/src/integrations/anr/index.ts
packages/node/src/integrations/console.ts
packages/node/src/integrations/context.ts
packages/node/src/integrations/contextlines.ts
packages/node/src/integrations/hapi/index.ts
packages/node/src/integrations/modules.ts
packages/node/src/integrations/onuncaughtexception.ts
packages/node/src/integrations/onunhandledrejection.ts
packages/node/src/integrations/spotlight.ts
packages/node/test/integrations/contextlines.test.ts

ref(node): Refactor node integrations to functional syntax

---

MIGRATION.md
packages/core/src/tracing/transaction.ts
packages/tracing/test/span.test.ts
packages/types/src/span.ts
packages/types/src/transaction.ts

These APIs are not really used, and are not compatible with OpenTelemetry. So let's deprecate them for removal in v8.
Unless somebody knows a reason why we still need something like this?

feat(core): Deprecate span `toContext()` and `updateWithContext()`

---

biome.json
packages/serverless/test/google-cloud-http.test.ts

This PR adds the [useRegexLiterals](https://biomejs.dev/linter/rules/use-regex-literals/) rule to our biome config which will  flag unnecessary usage of the `RegExp` constructor where a static regex could be used instead.
The fix codemod seems to be still quite buggy, as it e.g. can't correctly convert slashes `new RegExp('/my/path')` becomes `//my/path/` instead of `/\/my\/path/`. However, an incorrect conversion will trigger other warnings, so I'm okay with that for the moment. 
ref #9960 (in contrast to #10009, this PR doesn't address the RegExp usage problem but it's a nice addition IMO)

chore(biome): Add `useRegexLiterals` rule

---

MIGRATION.md
packages/angular/src/tracing.ts
packages/angular/test/tracing.test.ts
packages/core/src/tracing/span.ts
packages/core/src/tracing/transaction.ts
packages/core/test/lib/tracing/span.test.ts
packages/core/test/lib/tracing/transaction.test.ts
packages/node/src/handlers.ts
packages/opentelemetry-node/src/spanprocessor.ts
packages/react/src/reactrouter.tsx
packages/react/src/reactrouterv6.tsx
packages/react/test/reactrouterv4.test.tsx
packages/react/test/reactrouterv5.test.tsx
packages/react/test/reactrouterv6.4.test.tsx
packages/react/test/reactrouterv6.test.tsx
packages/remix/src/client/performance.tsx
packages/sveltekit/src/client/router.ts
packages/sveltekit/test/client/router.test.ts
packages/tracing-internal/src/node/integrations/express.ts
packages/tracing/test/span.test.ts
packages/tracing/test/transaction.test.ts
packages/types/src/span.ts
packages/utils/src/requestdata.ts
packages/vue/src/router.ts
packages/vue/test/router.test.ts

You can call `span.setMetadata()` if you need to update the source.
This aligns with the OTEL API for spans.

feat(core): Add `span.updateName()` and deprecate `span.setName()`

---

packages/utils/src/requestdata.ts

fix(utils): use correct typeof URL validation

---

MIGRATION.md
packages/astro/src/server/meta.ts
packages/astro/test/server/meta.test.ts
packages/core/src/index.ts
packages/core/src/tracing/hubextensions.ts
packages/core/src/tracing/span.ts
packages/core/src/utils/spanUtils.ts
packages/core/test/lib/utils/spanUtils.test.ts
packages/nextjs/src/common/wrapAppGetInitialPropsWithSentry.ts
packages/nextjs/src/common/wrapErrorGetInitialPropsWithSentry.ts
packages/nextjs/src/common/wrapGetInitialPropsWithSentry.ts
packages/nextjs/src/common/wrapGetServerSidePropsWithSentry.ts
packages/node/src/integrations/hapi/index.ts
packages/node/src/integrations/http.ts
packages/node/src/integrations/undici/index.ts
packages/node/test/integrations/undici.test.ts
packages/opentelemetry-node/src/propagator.ts
packages/remix/src/utils/instrumentServer.ts
packages/sveltekit/src/server/handle.ts
packages/tracing-internal/src/browser/request.ts
packages/tracing-internal/src/common/fetch.ts
packages/types/src/span.ts

Instead, there is a new util `spanToTraceHeader(span)` which can be used. This is done to align the Span schema with OpenTelemetry.
Open question: Do we need to re-export this from all our packages, so users can also use this directly?

feat(core): Deprecate `span.toTraceparent()` in favor of `spanToTraceHeader()` util

---

MIGRATION.md
packages/core/src/server-runtime-client.ts
packages/core/src/tracing/span.ts
packages/core/src/tracing/transaction.ts
packages/core/src/utils/applyScopeDataToEvent.ts
packages/core/src/utils/spanUtils.ts
packages/hub/test/scope.test.ts
packages/types/src/span.ts

Instead, you can use a new `spanToTraceContext(span)` util function.

feat(core): Deprecate `span.getTraceContext()`

---

dev-packages/node-integration-tests/suites/anr/should-exit.js
dev-packages/node-integration-tests/suites/anr/test.ts
packages/node/src/integrations/anr/index.ts

Closes #10022
This could have also been fixed by notifying the worker to disconnect the debugger but this seems simpler.

fix(node): Anr should not block exit

---

packages/astro/src/integration/index.ts

Fixes https://github.com/getsentry/sentry-javascript/issues/10040

fix(astro): handle commonjs related issues

---

packages/astro/src/index.server.ts
packages/browser/src/index.ts
packages/bun/src/index.ts
packages/core/src/index.ts
packages/core/src/tracing/index.ts
packages/core/src/tracing/trace.ts
packages/core/src/utils/handleCallbackErrors.ts
packages/core/test/lib/utils/handleCallbackErrors.test.ts
packages/deno/src/index.ts
packages/nextjs/src/common/utils/edgeWrapperUtils.ts
packages/nextjs/src/common/withServerActionInstrumentation.ts
packages/nextjs/src/common/wrapGenerationFunctionWithSentry.ts
packages/nextjs/src/common/wrapRouteHandlerWithSentry.ts
packages/nextjs/src/common/wrapServerComponentWithSentry.ts
packages/nextjs/test/edge/edgeWrapperUtils.test.ts
packages/nextjs/test/edge/withSentryAPI.test.ts
packages/node-experimental/src/index.ts
packages/node/src/index.ts
packages/opentelemetry/src/trace.ts
packages/remix/src/index.server.ts
packages/serverless/src/gcpfunction/cloud_events.ts
packages/serverless/src/gcpfunction/events.ts
packages/serverless/src/gcpfunction/http.ts
packages/sveltekit/src/client/load.ts
packages/sveltekit/src/server/index.ts
packages/sveltekit/test/client/load.test.ts
packages/tracing-internal/src/node/integrations/prisma.ts
packages/tracing/test/integrations/node/prisma.test.ts
packages/vercel-edge/src/index.ts

Also add a `handleCallbackErrors` utility to replace this.
We've been using this in a few places, and since it has a bit of a different usage than `startSpan` I had to add a new utility to properly make this work. The upside is that we now can ensure to use the same implementation for this "maybe promise" handling everywhere!

feat(core): Deprecate `trace` in favor of `startSpan`

---

dev-packages/browser-integration-tests/package.json
dev-packages/node-integration-tests/package.json
nx.json

I ran into some funky behaviour where I had to run the `lint` script multiple times in order for all lint errors to be printed to me in the terminal.
Then I realized this mistake in our Nx config that we hadn't referenced the `lint` script but the `lint:eslint` script which doesn't exist.
I think this got introduced in https://github.com/getsentry/sentry-javascript/commit/5658aff81776c52c9219d9c02342c8a59d197a4a
Additionally, lint technically depends on `build:types` of the parent package, and in some cases even in the own package (Next.js), so I added that to the nx config.
Also, we were not marking the right outputs of build, so we're fixing that.

build: Fix nx-config for lint

---

.vscode/settings.json

This setting is incredibly buggy. It deletes a bunch of whitespace when I type "// TODO (" for example.

meta: Disable biome quickfix in vscode config

---

.eslintrc.js
dev-packages/browser-integration-tests/suites/public-api/startSpan/error-sync/test.ts
dev-packages/node-integration-tests/suites/anr/test.ts
packages/core/test/lib/exports.test.ts
packages/core/test/lib/utils/applyScopeDataToEvent.test.ts
packages/node/src/cron/node-cron.ts
packages/node/test/cron.test.ts
packages/opentelemetry/src/custom/client.ts
packages/opentelemetry/src/spanProcessor.ts
packages/serverless/test/awslambda.test.ts
packages/types/src/metrics.ts

This effectively undoes changes done in https://github.com/getsentry/sentry-javascript/pull/9692
Our lint job passes even though we clearly have unused variables in our code base. Example: https://github.com/getsentry/sentry-javascript/pull/10012#discussion_r1440651940
This makes me not trust biome so I am adding back the eslint rules.

build: Re-enable eslint `no-unused-vars`, `no-control-regex` and `no-loss-of-precision`

---

packages/core/src/hub.ts
packages/core/src/scope.ts
packages/core/test/lib/scope.test.ts
packages/node-experimental/src/sdk/types.ts
packages/types/src/scope.ts

Adds a getter and setter for client objects to the Scope to align with the new Scope API. We also adjust the logic in the Hub constructor to correctly set the client on newly instantiated scope objects residing on the hub.

feat(core): Add `setClient()` and `getClient()` to `Scope`

---

docs/v8-new-performance-apis.md

This is a WIP document about the new performance APIs. I'm sure I forgot a bunch of things, but it's a start at least...!
[View rendered](https://github.com/getsentry/sentry-javascript/blob/fn/docs-new-performance-apis/docs/v8-new-performance-apis.md)

docs: Add docs for new performance APIs

---

packages/remix/test/integration/package.json

temporarily fixes https://github.com/MattiasBuelens/web-streams-polyfill/issues/137 until the change is reverted.

test(remix): Override `web-streams-polyfill` version to fix integration tests

---

dev-packages/node-integration-tests/suites/anr/should-exit-forced.js
dev-packages/node-integration-tests/suites/anr/test.ts
packages/node/src/integrations/anr/index.ts

Closes #10023
`worker.on` actually calls `worker.ref()` internally so `worker.unref()` needs calling after!

fix(node): Anr doesn't block exit

---

packages/node/src/integrations/anr/worker.ts

I didn't notice this was missing since events still end up in Sentry. 
It was only when I ran it through the Electron e2e tests that I realised it was missing vs the previous incarnation!

fix(node): Anr events should have an `event_id`

---

dev-packages/e2e-tests/test-applications/nextjs-14/app/generation-functions/with-notfound/page.tsx
dev-packages/e2e-tests/test-applications/nextjs-14/app/generation-functions/with-redirect/page.tsx
dev-packages/e2e-tests/test-applications/nextjs-14/app/page.tsx
dev-packages/e2e-tests/test-applications/nextjs-14/tests/generation-functions.test.ts
packages/nextjs/src/common/wrapGenerationFunctionWithSentry.ts

Fixes https://github.com/getsentry/sentry-javascript/issues/10038

fix(nextjs): Don't capture not-found and redirect errors in generation functions

---

packages/core/src/tracing/idletransaction.ts
packages/core/src/tracing/span.ts
packages/core/src/tracing/trace.ts
packages/core/src/tracing/transaction.ts
packages/core/src/tracing/utils.ts
packages/core/src/utils/spanUtils.ts
packages/core/test/lib/tracing/span.test.ts
packages/core/test/lib/tracing/trace.test.ts
packages/core/test/lib/utils/spanUtils.test.ts
packages/types/src/index.ts
packages/types/src/opentelemetry.ts
packages/types/src/span.ts

We allow the same formats as OpenTelemetry:
* `number` (we handle both seconds and milliseconds)
* `Date`
* `[seconds, nanoseconds]`

feat(core): Allow to pass start/end timestamp for spans flexibly

---

MIGRATION.md
packages/astro/test/server/meta.test.ts
packages/browser/src/profiling/utils.ts
packages/browser/test/unit/profiling/hubextensions.test.ts
packages/bun/test/integrations/bunserver.test.ts
packages/core/src/tracing/hubextensions.ts
packages/core/src/tracing/sampling.ts
packages/core/src/tracing/span.ts
packages/core/src/utils/spanUtils.ts
packages/core/test/lib/tracing/span.test.ts
packages/tracing-internal/src/browser/browsertracing.ts
packages/types/src/span.ts

feat(core): Add `span.isRecording()` instead of `span.sampled`

---

dev-packages/browser-integration-tests/suites/public-api/captureException/eventBreadcrumbs/subject.js
dev-packages/browser-integration-tests/suites/public-api/captureException/eventBreadcrumbs/test.ts
dev-packages/browser-integration-tests/suites/public-api/captureException/transactionBreadcrumbs/subject.js
dev-packages/browser-integration-tests/suites/public-api/captureException/transactionBreadcrumbs/test.ts
packages/browser/test/integration/suites/api.js

This test regularly but inconsitently fails so let's try to run it in the newer browser integration tests and hope it is more consistent.
https://github.com/getsentry/sentry-javascript/actions/runs/7420119902/job/20191060365
EDIT: So it's actually 2 flakey tests https://github.com/getsentry/sentry-javascript/actions/runs/7421372038/job/20194632050?pr=10075#step:5:985

test(browser): Replace flakey integration test

---

MIGRATION.md
packages/core/src/hub.ts
packages/types/src/hub.ts

Quick one for a change...
This PR only deprecates the unnecessary `Hub. shouldSendDefaultPii` method which can be easily replaced by accessing client options directly. Replacement of usages was already done in #9899, hence, only the deprecation is left.

feat(core): Deprecate `Hub.shouldSendDefaultPii`

---

dev-packages/browser-integration-tests/suites/integrations/Breadcrumbs/dom/click/test.ts

This test consistently flakes on chrome: 
- https://github.com/getsentry/sentry-javascript/actions/runs/7422426777/job/20197877425
- https://github.com/getsentry/sentry-javascript/actions/runs/7422956761/job/20199398886?pr=10039#step:10:578

test(browser-integration-tests): Skip flakey test on chrome

---

dev-packages/browser-integration-tests/suites/replay/canvas/records/init.js
dev-packages/browser-integration-tests/suites/replay/canvas/records/template.html
dev-packages/browser-integration-tests/suites/replay/canvas/records/test.ts
dev-packages/browser-integration-tests/suites/replay/canvas/template.html
dev-packages/browser-integration-tests/utils/replayHelpers.ts

Adds a test to ensure that Replay canvas recording works.

test(browser-integration): Add test for Replay canvas recording

---

packages/node/src/cron/node-cron.ts
packages/node/test/cron.test.ts

This should enforce via TypeScript that users pass in a name, but we can keep the runtime check just in case.

fix(cron): Make name required for instrumentNodeCron option

---

packages/node/src/integrations/local-variables/local-variables-sync.ts
packages/node/test/integrations/localvariables.test.ts

In #10077, I disabled the async `LocalVariables` integration but forgot to change the name of sync integration to match. Users might be filtering on this!

fix(node): `LocalVariables` integration should have correct name

---

packages/utils/src/time.ts

ref https://github.com/getsentry/sentry-javascript/issues/10046
This PR removes the usage of `dynamicRequire` from `packages/utils/src/time.ts` and cleans up our timestamp code to be simpler and reduce bundle size. Removing `dynamicRequire` means that we no longer rely on `perf_hooks` for the `performance` API, but instead try to grab it from `globalThis.performance`. `performance` was added to the global in Node 16, which means we'll fallback to using `Date.now()` in Node 8, 10, 12, 14 (and in v8 just Node 14). I think that is an acceptable tradeoff, we just reduce accuracy for those versions.
This does not refactor `browserPerformanceTimeOrigin` code at the bottom of the file, I want to come back and touch that in a follow up PR to reduce the amount of changes made here.
I would …

ref(utils): Clean up timestamp calculation code

---

packages/core/package.json
packages/core/src/index.ts
packages/core/src/tracing/span.ts
packages/core/src/tracing/transaction.ts
packages/core/src/utils/spanUtils.ts
packages/core/test/lib/utils/spanUtils.test.ts
packages/node-experimental/test/integration/transactions.test.ts
packages/opentelemetry/test/custom/transaction.test.ts
packages/opentelemetry/test/integration/transactions.test.ts
packages/types/src/index.ts
packages/types/src/span.ts

This is supposed to be an internal API and not necessarily to be used by users.
Naming wise, it's a bit tricky... I went with `JSON` to make it very clear what this is for, but 🤷

feat(core): Add `spanToJSON()` method to get span properties

---

packages/core/src/exports.ts
packages/core/src/tracing/trace.ts
packages/core/test/lib/exports.test.ts
packages/core/test/lib/tracing/trace.test.ts
packages/node-experimental/src/sdk/api.ts
packages/node-experimental/src/utils/contextData.ts
packages/opentelemetry/src/types.ts

Also allow to pass this to `withScope()`, which actually aligns with OTEL as well, where you can also do that. If you pass a scope there, it will use this instead of forking a new one.
This should be the last thing needed to refactor some `span.startChild()` occurrences - you can now store the scope you want to fork off, and pass this into `startSpan` as needed.

feat(core): Allow to pass `scope` to `startSpan` APIs

---

dev-packages/node-integration-tests/suites/public-api/LocalVariables/local-variables-memory-test.js
dev-packages/node-integration-tests/suites/public-api/LocalVariables/test.ts

This PR adds a test for the `LocalVariable` integration that causes 20k caught exceptions and checks that the memory usage does not go over 100MB.

test(node): Add memory leak test for `LocalVariables`

---

MIGRATION.md
packages/core/src/tracing/trace.ts

In v8, there will be a reduced API surface.

feat(core): Deprecate arguments for `startSpan()`

---

packages/node/src/cron/cron.ts
packages/node/src/cron/node-schedule.ts
packages/node/src/index.ts
packages/node/test/cron.test.ts

Closes #9893
This PR adds auto instrumented check-ins for the `node-schedule` library.
It's not shown in the readme, but `scheduleJob` can be passed a job name as the first parameter:
https://github.com/node-schedule/node-schedule/blob/c5a4d9a0dbcd5bda4996e089817e5669b5acd95f/lib/schedule.js#L28
```ts
import * as Sentry from '@sentry/node';
import * as schedule from 'node-schedule';
const scheduleWithCheckIn = Sentry.cron.instrumentNodeSchedule(schedule);
const job = scheduleWithCheckIn.scheduleJob('my-cron-job', '* * * * *', () => {
console.log('You will see this message every minute');
});
```
This PR also adds a check to the `cron` instrumentation that ensures that you can't create multiple schedules with the same monitor slug.

feat(node): Instrumentation for `node-schedule` library

---

packages/node/src/integrations/anr/index.ts

Upon testing the full range of Electron versions for release in CI, I found that starting a worker thread via a data uri requires at least node v16.17.0. 
This wasn't picked up by the tests in this repository because we only test the latest version of each major.

fix(node): Update ANR min node version to v16.17.0

---

packages/core/src/tracing/span.ts

So we do not mutate this if we update data there.
Noticed this here: https://github.com/getsentry/sentry-javascript/pull/10097

fix(core): Ensure we copy passed in span data/tags/attributes

---

MIGRATION.md
dev-packages/browser-integration-tests/suites/replay/dsc/test.ts
dev-packages/browser-integration-tests/suites/tracing/envelope-header-transaction-name/init.js
dev-packages/browser-integration-tests/suites/tracing/envelope-header/init.js
packages/core/src/scope.ts
packages/core/src/utils/applyScopeDataToEvent.ts
packages/serverless/src/awslambda.ts
packages/serverless/test/__mocks__/@sentry/node.ts
packages/serverless/test/awslambda.test.ts
packages/types/src/scope.ts

This can be replaced by an event processor. We only use this in a single place right now.
Closes https://github.com/getsentry/sentry-javascript/issues/5660

feat(core): Deprecate `scope.setTransactionName()`

---

packages/core/src/integration.ts
packages/core/test/lib/integration.test.ts

Currently, if you do:
```js
const myIntegration = new InboundFilters();
const myIntegration2 = new InboundFilters();
const myIntegration3 = new InboundFilters();
client.addIntegration(myIntegration);
client.addIntegration(myIntegration2);
client.addIntegration(myIntegration3);
```
All of these will have their `setup` hooks called, and thus they will be initialized multiple times. However, all but the last will be discarded from the client and not be accessible anymore via e.g. `getIntegration()` or similar.
This used to not matter because everything was guarded through `setupOnce()` anyhow, but i would say this is more of a bug and not really expected.
With this change, an integration can only be added to a client once, if you try to add it again it will noop.

fix(core): Do not run `setup` for integration on client multiple times

---

packages/ember/addon/index.ts
packages/ember/addon/instance-initializers/sentry-performance.ts

ref(ember): Use new span APIs

---

dev-packages/browser-integration-tests/package.json
packages/replay/package.json
yarn.lock

This bump contains the following changes:
- fix(rrweb): Use unpatched requestAnimationFrame when possible [#150](https://github.com/getsentry/rrweb/pull/150)
- ref: Avoid async in canvas [#143](https://github.com/getsentry/rrweb/pull/143)
- feat: Bundle canvas worker manually [#144](https://github.com/getsentry/rrweb/pull/144)
- build: Build for ES2020 [#142](https://github.com/getsentry/rrweb/pull/142)
Extracted out from https://github.com/getsentry/sentry-javascript/pull/9826
Closes https://github.com/getsentry/sentry-javascript/issues/6946

feat(replay): Update rrweb to 2.7.3

---

packages/core/src/tracing/hubextensions.ts
packages/core/src/tracing/idletransaction.ts
packages/core/src/tracing/transaction.ts
packages/node/test/handlers.test.ts
packages/opentelemetry-node/test/propagator.test.ts
packages/opentelemetry/src/custom/transaction.ts
packages/opentelemetry/test/custom/transaction.test.ts
packages/tracing-internal/test/browser/metrics/index.test.ts
packages/tracing-internal/test/browser/metrics/utils.test.ts
packages/tracing/test/idletransaction.test.ts

No more transaction class!
This should not really affect users, as they should only use `startTransaction()` anyhow.

feat(core): Deprecate `new Transaction()`

---

MIGRATION.md
dev-packages/rollup-utils/plugins/bundlePlugins.mjs
packages/astro/src/server/meta.ts
packages/astro/test/server/meta.test.ts
packages/core/src/server-runtime-client.ts
packages/core/src/tracing/dynamicSamplingContext.ts
packages/core/src/tracing/index.ts
packages/core/src/tracing/transaction.ts
packages/core/src/utils/applyScopeDataToEvent.ts
packages/core/test/lib/tracing/dynamicSamplingContext.test.ts
packages/nextjs/src/common/wrapAppGetInitialPropsWithSentry.ts
packages/nextjs/src/common/wrapErrorGetInitialPropsWithSentry.ts
packages/nextjs/src/common/wrapGetInitialPropsWithSentry.ts
packages/nextjs/src/common/wrapGetServerSidePropsWithSentry.ts
packages/node/src/integrations/hapi/index.ts
packages/node/src/integrations/http.ts
packages/node/src/integrations/undici/index.ts
packages/opentelemetry-node/src/propagator.ts
packages/remix/src/utils/instrumentServer.ts
packages/sveltekit/src/server/handle.ts
packages/tracing-internal/src/browser/request.ts
packages/tracing-internal/src/common/fetch.ts
packages/tracing/test/span.test.ts
packages/types/src/transaction.ts

This PR deprecates `Transaction.getDynamicSamplingContext` and introduces its direct replacement, a top-level utility function. Note that IMO this only is an intermediate step we should take to rework how we generate and handle the DSC creation. More details in #10095 
Used various new APIs like `spanToJSON` and `spanIsSampled`. Observed that a slight behavioural change is, that `isSpanSampled` always returns a boolean while `span.sampled` could also be undefined. Considering integration tests still pass, I'd say this is fine.
Added new tests for the top level helper and left the older ones in place to still cover `transaction.getDSC`.

feat(core): Deprecate `Transaction.getDynamicSamplingContext` in favour of `getDynamicSamplingContextFromSpan`

---

MIGRATION.md

Adds documentation on how to migrate off the hub API to the MIGRATION guide. This is still a bit basic - we will expand on this once we have figured out all of our migration paths and are finalizing v8.

chore: Add migration docs for `Hub`

---

packages/core/test/lib/tracing/dynamicSamplingContext.test.ts

meta: Ignore `Transaction` deprecation lint warnings in DSC tests

---

packages/bun/test/integrations/bunserver.test.ts

Not sure why our Bun Unit Tests were still passing but locally as well as in CI somehow 
else (weird) this test failed.
This failed in CI but I see no failed jobs 🤔 
cc @mydea I think the test fix should be correct - in the `finishTransaction` test, the 
span is already finished (hence, isRecording returns `false`) but `spanIsSampled` should 
still be true.

test(bun): Fix failing test after `span.isRecording` change

---

packages/node/src/module.ts
packages/node/test/module.test.ts

The default `basePath` for `createGetModuleFromFilename` is `dirname(process.argv[1])`:
```ts
/** Creates a function that gets the module name from a filename */
export function createGetModuleFromFilename(
basePath: string = dirname(process.argv[1]),
```
But the tests used a trailing slash for the base path:
https://github.com/getsentry/sentry-javascript/blob/84791bf8f83fc637e02a7071bbe70a0d22e20666/packages/node/test/module.test.ts#L3-L4
Which means in some situations the module name can include a leading `.`.
The tests need to pass without a trailing slash on the `basePath`!

fix(node): Module name resolution

---

MIGRATION.md
packages/core/src/tracing/span.ts
packages/types/src/span.ts

This PR deprecates the `instrumenter` field on the `Span` interface and class. The field is not part of the Otel Span API and hence it can't exist publicly on our spans either. After talking with @mydea about the replacement, we can probably replace this with an `instanceof` check when setting `instrumenter` on the event in v8. This is breaking though, so for now, we only deprecate it. Users shouldn't need to worry about this field anyway.

feat(core): Deprecate `Span.instrumenter`

---

packages/node/test/stacktrace.test.ts
packages/utils/src/node-stack-trace.ts

There were no Node stack parser tests for Windows `file://` URLs. 
It turns out we were retaining a leading slash in the filename (ie. `/C:/some/path`).
This was already handled in Electron via path normalisation but it can cause issues with `module` name resolution.

fix(node): Remove leading slash in Windows filenames

---

MIGRATION.md
packages/browser/test/unit/sdk.test.ts
packages/core/src/baseclient.ts
packages/core/src/hub.ts
packages/core/test/lib/base.test.ts
packages/core/test/lib/integrations/inboundfilters.test.ts
packages/node-experimental/src/sdk/init.ts
packages/node/src/sdk.ts
packages/node/test/integrations/localvariables.test.ts
packages/types/src/client.ts

This adds a new `client.init()` method to be called instead of `client.setupIntegrations()`.
Note that this method simply initializes the integrations always, and depends on the check that we don't add integrations multiple times.
This also has a bit of a different semantic, dropping the `force` argument in favor of just calling `addIntegration()` again - this depends on https://github.com/getsentry/sentry-javascript/pull/10116 to really work. cc @HazAT for Spotlight.

feat(core): Add `client.init()` to replace `client.setupIntegrations()`

---

MIGRATION.md
packages/node/src/module.ts

fix(node): Guard against `process.argv[1]` being undefined

---

packages/astro/src/index.server.ts
packages/browser/src/exports.ts
packages/bun/src/index.ts
packages/core/src/exports.ts
packages/core/src/index.ts
packages/core/test/lib/async-context.test.ts
packages/core/test/lib/scope.test.ts
packages/deno/src/index.ts
packages/node/src/index.ts
packages/node/test/async/domain.test.ts
packages/node/test/async/hooks.test.ts
packages/remix/src/index.server.ts
packages/serverless/src/index.ts
packages/sveltekit/src/server/index.ts
packages/vercel-edge/src/index.ts

This adds a global API `withIsolationScope<T>((isolationScope: Scope) => T): T`.
`withIsolationScope()` will fork the current `isolationScope` and the current `scope`. The callback is passed the isolation scope that is active within the callback.
`withIsolationScope()` is mostly intended for developing SDKs and is generally not recommended to be used by SDK consumers directly.
This function makes use of the provided async context strategy in the SDK. In the browser, this means it does effectively nothing as of now.
---
For reviewers:
This PR looks a bit goofy because it is literally wrapping `runWithAsyncContext`, however, this is probably exactly what we want this function to do until we have fully deprecated the hub.
We cannot make assertions in the `core` package that …

feat(core): Add `withIsolationScope`

---

packages/types/src/transaction.ts

I didn't see that `instrumenter` was redeclared on the `Transcation` interface in #10139 - this PR now also deprecates it on `Transaction`.

feat(core): Deprecate `Transaction.instrumenter`

---

MIGRATION.md
packages/core/src/tracing/span.ts
packages/core/src/tracing/transaction.ts
packages/types/src/transaction.ts

Seems like we didn't fully deprecate the `setName` API in #10018  as some deprecation annotations were still missing on 
* `Span` class
* `Transaction` class
* `Transaction` interface

feat(core): Deprecate remaining `setName` declarations on `Transaction` and `Span`

---

dev-packages/browser-integration-tests/suites/tracing/request/fetch-with-request/init.js
dev-packages/browser-integration-tests/suites/tracing/request/fetch-with-request/subject.js
dev-packages/browser-integration-tests/suites/tracing/request/fetch-with-request/test.ts
packages/tracing-internal/src/common/fetch.ts

When a `fetch` call is made with a `Request` object as the input/resource param (i.e. the first) and additionally provided headers in the fetch init options (the second param),
```js
const request = new Request('http://example.com/api/test/', {
headers: { foo: '11' },
});
fetch(request, {
headers: { bar: '22' },
});
```
browsers ignore the headers from the request object but only add the headers from the init options when making the request. 
Our `fetch` instrumentation had it the other way around, preferring headers from the request object over the headers in the options, as reported in #10172 . This PR fixes this behaviour by essentially turning around the logic we previously had.
fixes #10172

fix(tracing-internal): Prefer `fetch` init headers over `fetch` input headers

---

dev-packages/browser-integration-tests/suites/sessions/initial-scope/init.js
dev-packages/browser-integration-tests/suites/sessions/initial-scope/template.html
dev-packages/browser-integration-tests/suites/sessions/initial-scope/test.ts
packages/core/src/exports.ts

When creating a session, we previously only read the user from the isolation scope. This was problematic because the user could be set in `initialScope` which will be applied to the _current_ scope on SDK init. This would happen before the session is started when using auto session tracking.
This PR now takes the user from the current scope if it's set and falls back to the isolation scope should the user be set there. Added an integration test to cover this regression.
fixes #10146
cc @timfish

fix(core): Take user from current scope when starting a session

---

MIGRATION.md
dev-packages/browser-integration-tests/loader-suites/loader/onLoad/customBrowserTracing/test.ts
dev-packages/browser-integration-tests/loader-suites/loader/onLoad/customIntegrations/test.ts
dev-packages/browser-integration-tests/loader-suites/loader/onLoad/customIntegrationsFunction/test.ts
dev-packages/browser-integration-tests/loader-suites/loader/onLoad/customReplay/test.ts
packages/astro/test/client/sdk.test.ts
packages/core/src/baseclient.ts
packages/core/src/hub.ts
packages/core/test/lib/base.test.ts
packages/core/test/mocks/integration.ts
packages/ember/addon/instance-initializers/sentry-performance.ts
packages/ember/tests/acceptance/sentry-replay-test.ts
packages/ember/tests/dummy/app/routes/replay.ts
packages/feedback/README.md
packages/integrations/src/offline.ts
packages/node-experimental/src/sdk/hub.ts
packages/node-experimental/src/sdk/spanProcessor.ts
packages/node-experimental/test/integration/transactions.test.ts
packages/node/src/integrations/undici/index.ts
packages/node/test/integrations/undici.test.ts
packages/sveltekit/test/client/sdk.test.ts
packages/types/src/client.ts
packages/vercel-edge/src/integrations/wintercg-fetch.ts
packages/vercel-edge/test/wintercg-fetch.test.ts
packages/vue/test/integration/init.test.ts

And also deprecate both `getIntegration()` as well as `getIntegrationById()` which is only on the baseclient, but not on the client type, anyhow :grimace:.
Usage:
```ts
const replay = getClient().getIntegrationByName('Replay');
```
Or, if you want to have an easier time with types:
```ts
const replay = getClient().getIntegrationByName<Replay>('Replay');
```
In v8, integrations will not be classes anymore, so you cannot pass a class definition anymore to `getIntegration()`. We also decided to remove the static `id` field, so you cannot find an integration via that way anymore.
`getIntegrationById()` was always just on the baseclient, so not properly types anyhow. It is also an inconsistent/weird naming because we will not have an `id` anymore for integrations at all.

feat(core): Add `client.getIntegrationByName()`

---

dev-packages/e2e-tests/test-applications/node-experimental-fastify-app/tests/propagation.test.ts
dev-packages/e2e-tests/test-applications/node-experimental-fastify-app/tests/transactions.test.ts
packages/opentelemetry/src/spanExporter.ts

Noticed here: https://github.com/getsentry/sentry-javascript/issues/10168, tags should always be strings.

fix(node-experimental): Ensure `http.status_code` is always a string

---

packages/core/src/hub.ts
packages/core/src/scope.ts
packages/core/src/utils/applyScopeDataToEvent.ts
packages/core/test/lib/exports.test.ts
packages/core/test/lib/utils/applyScopeDataToEvent.test.ts

In the new scope model, all the global `Sentry.setX()` APIs should write to the isolation scope. This PR introduces that in the hub as a compatibility and migration layer until we deprecate the hub in v8.
One exception to this rule is the `addBreadcrumb` function, which I opted not to let write to the isolation scope to avoid duplicate breadcrumbs. We can still write breadcrumbs to the isolation scope ourselves by calling `.addBreadcrumb()` on the isolation scope directly. This should therefore be non-blocking to anybody.

feat(core): Write data from `setUser`, `setTags`, `setExtras`, `setTag`, `setExtra`, and `setContext` to isolation scope

---

MIGRATION.md
packages/integrations/src/index.ts
packages/integrations/src/transaction.ts
packages/integrations/test/transaction.test.ts

This was not really documented anywhere anymore, and it's not clear what/when/why you would be using this, so we will remove this in v8.

feat(integrations): Deprecate `Transaction` integration

---

MIGRATION.md
packages/core/src/tracing/measurement.ts
packages/core/src/tracing/transaction.ts
packages/tracing-internal/src/browser/metrics/index.ts
packages/types/src/transaction.ts

This PR deprecates the `setMeasurement` API on the transaction interface and class. It's replaced by an already existing top level `setMeasurement` function. 
The actual replacement behaviour is TBD for v8 but for now we need to deprecate this method as it's not part of the Otel API.

feat(core): Deprecate `Transaction.setMeasurement` in favor of `setMeasurement`

---

packages/core/src/tracing/span.ts

This PR adds some `@deprecated` annotations to already deprecated Span APIs:
* `Span.toTraceParent()`
* `Span.toContext()`
* `Span.updateWithContext()`
* `Span.getTraceContext()`
These fields were already deprecated on the interface, this patch only adds the deprecation annotation to the JSDoc of the class fields.
When testing with eslint, it will correctly infer the deprecation status from the interface. VSCode also shows the fields as deprecated in the JSDoc but doesn't apply the strikethrough. So for extra clarity, let's also deprecate the class fields here.
ref #10184

ref(core): Add missing class field deprecations

---

packages/integration-shims/src/BrowserTracing.ts
packages/integration-shims/src/Feedback.ts
packages/integration-shims/src/Replay.ts

This is a bit less "in your face" which is probably more appropriate here - it is not really an error, we just want to let the user know that the integration is not doing anything.
fixes https://github.com/getsentry/sentry/issues/63085

fix(cdn): Emit console warning instead of error for integration shims

---

packages/node-experimental/src/index.ts
packages/node-experimental/src/sdk/api.ts
packages/node-experimental/test/sdk/api.test.ts

Adds `withActiveSpan` to the node-experimental package that will fork the current scope and set the provided span as active within the provided callback. Any startSpan calls within the callback will have the provided span as a child span.
We need this in situations where we need to pick up and create children for spans from a different execution context.

feat(node-experimental): Add `withActiveSpan`

---

packages/core/src/tracing/span.ts

This small PR just clarifies the API status of the `Span.getSpanJSON` method. This method is purely purposed for internal usage and users should not rely on it but instead on `spanToJSON`.
Why should it stay on the `Span` _class_ anyway?
- The alternative would be to access private properties of `Span` class instances externally, which isn't clean or particularly safe either.
- Given above, we'd need to exclude all private property names from being mangled by Terser when we build our CDN bundles. Which also opens us up to potential errors in the future where we'd add private fields but forget to add the mangling exclusion.
I originally intended to deprecate this method but after discussing this, we decided to just clarify the internal purpose instead. The way we use this function right …

chore(core): Mark `Span.getSpanJSON` method as internal

---

packages/core/src/exports.ts
packages/core/test/lib/scope.test.ts

Similar to https://github.com/getsentry/sentry-javascript/pull/10194
Adds withActiveSpan to the core package that will fork the current scope and set the provided span as active within the provided callback. Any startSpan calls within the callback will have the provided span as a child span.
We need this in situations where we need to pick up and create children for spans from a different execution context.

feat(core): Add `withActiveSpan`

---

MIGRATION.md
packages/core/src/tracing/idletransaction.ts
packages/core/src/tracing/span.ts
packages/core/src/tracing/transaction.ts
packages/node/test/integrations/http.test.ts
packages/node/test/integrations/undici.test.ts
packages/opentelemetry/test/custom/transaction.test.ts

This PR deprecates the `spanRecorder` field on the `Span` class. For now there's no replacement yet. I'm not entirely sure how we're going to keep track of spans within the SDK. #9972 shows an alternative for `IdleSpan` which no longer seems to rely on the `spanRecorder`. Another possibility might be to make the recorder private which might be enough, too. 
Anyhow, we should deprecate the field in any case as it's not meant to be user facing and of course also doesn't exist on the Otel `Span` interface.
ref #10184

feat(core): Deprecate `Span.spanRecorder`

---

dev-packages/e2e-tests/test-applications/nextjs-app-dir/app/very-slow-component/page.tsx
dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/transactions.test.ts
packages/tracing-internal/src/browser/metrics/index.ts

I found that Relay was dropping pageload transactions from my Next.js test app pretty consistently so in my debugging journey I discovered that the reason was that we were sending spans with start timestamps larger than the end timestamps.
Root cause was that we assumed that the `responseEnd` property on the `navigation` performance entry is always present. It is, however, when the response hasn't finished yet, it is `0`.
As a fallback behaviour, this PR changes the logic so we will only collect these performance entry spans when the `responseEnd` logic is available.
We should probably delay finishing of the pageload transaction until domContentLoded fired or the timeout is reached...

fix(tracing-internal): Only collect request/response spans when browser performance timing is available

---

MIGRATION.md
packages/core/src/tracing/span.ts
packages/core/src/tracing/trace.ts
packages/core/test/lib/tracing/errors.test.ts
packages/node/test/handlers.test.ts
packages/opentelemetry-node/test/spanprocessor.test.ts
packages/tracing-internal/src/browser/backgroundtab.ts
packages/tracing-internal/test/browser/backgroundtab.test.ts
packages/types/src/span.ts

This PR deprecates the `status` field on the span interface as well as on the class. The replacements for this field are
* `span.setStatus` to set or update a span status (this API exists on the Otel Span interface but the types don't align yet)
* `spanToJson` to read the status
ref #10184

feat(core): Deprecate `Span.status` 

---

packages/integrations/src/captureconsole.ts
packages/integrations/src/contextlines.ts
packages/integrations/src/debug.ts
packages/integrations/src/dedupe.ts
packages/integrations/src/extraerrordata.ts
packages/integrations/src/httpclient.ts
packages/integrations/src/index.ts
packages/integrations/src/reportingobserver.ts
packages/integrations/src/rewriteframes.ts
packages/integrations/src/sessiontiming.ts
packages/integrations/test/captureconsole.test.ts
packages/integrations/test/debug.test.ts
packages/integrations/test/dedupe.test.ts
packages/integrations/test/extraerrordata.test.ts
packages/integrations/test/reportingobserver.test.ts
packages/integrations/test/rewriteframes.test.ts
packages/integrations/test/sessiontiming.test.ts
packages/nextjs/src/client/index.ts
packages/nextjs/src/edge/index.ts
packages/nextjs/src/server/index.ts
packages/sveltekit/src/server/sdk.ts
packages/sveltekit/test/server/utils.test.ts

Instead, users should import & use the integration functions.

feat(integrations): Deprecate pluggable integration classes

---

packages/remix/src/utils/instrumentServer.ts
packages/remix/src/utils/web-fetch.ts
packages/remix/test/integration/app_v1/routes/loader-throw-response/$id.tsx
packages/remix/test/integration/app_v2/routes/loader-throw-response.$id.tsx
packages/remix/test/integration/common/routes/loader-throw-response.$id.tsx
packages/remix/test/integration/test/server/loader.test.ts

Fixes: #10160
Potentially fixes: https://github.com/getsentry/sentry-javascript/issues/10002
This PR adds support for extracting `header` data from thrown non-Remix responses (fetch responses) inside loaders / actions.

fix(remix): Capture thrown fetch responses.

---

MIGRATION.md
docs/v8-new-performance-apis.md
packages/core/src/tracing/span.ts
packages/tracing/test/span.test.ts
packages/types/src/span.ts

This PR deprecates `Span.isSuccess()` in favor of directly reading the span status via `spanToJSON(span).status === 'ok'` instead. There's no need for this API as it's just syntactic sugar around the status. 
Seemed like we didn't even use this API in our SDKs - maybe some downstream SDKs use it but migrating should be very straightforward.
ref #10184

feat(core): Deprecate `Span.isSuccess()` in favor of reading span status

---

packages/core/src/tracing/dynamicSamplingContext.ts
packages/types/src/envelope.ts
packages/types/src/user.ts

See https://github.com/getsentry/sentry/issues/58767#issuecomment-1808116241
Segment is no longer supported by the product, so we can remove it in v8.

feat: Deprecate user segment field

---

packages/vue/src/index.ts
packages/vue/src/integration.ts
packages/vue/test/integration/VueIntegration.test.ts
packages/vue/test/integration/init.test.ts

Wanted to test out integration changes, so decided try it with Vue integration
I'm not the biggest fan with `vueIntegration` vs. `VueIntegration`. Also I wanted to use `vueIntegration` in `packages/vue/sdk.ts` when setting default integrations but was unable to due to typing, is there a way around that?

ref(vue): Convert Vue integration to use functional approach

---

dev-packages/browser-integration-tests/suites/tracing/browsertracing/pageloadWithHeartbeatTimeout/init.js
dev-packages/browser-integration-tests/suites/tracing/browsertracing/pageloadWithHeartbeatTimeout/test.ts
packages/core/src/tracing/hubextensions.ts
packages/core/src/tracing/idletransaction.ts
packages/tracing-internal/src/browser/browsertracing.ts
packages/tracing-internal/test/browser/browsertracing.test.ts

Before this PR we automatically finished pageload transactions when there were no spans on the transaction for max 1 second, OR when there were no added/removed child spans consecutively in 3x5 seconds.
This caused inaccuracies in some cases, however, with the Next.js app router this causes problems consistently. Reason being that Next.js streams in the document (HTML) meaning the document [`"interactive"` `readyState`](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceNavigationTiming/domInteractive) is delayed by as long as the streaming response hasn't finished yet.
The symptom of this is that, in Next.js applications (and also all other apps that have long document loading times), pageload transactions will be finished prematurely, because while the document is streaming in, …

fix(tracing-internal): Delay pageload transaction finish until document is interactive

---

dev-packages/browser-integration-tests/suites/public-api/startTransaction/basic_usage/test.ts
dev-packages/browser-integration-tests/suites/tracing/browsertracing/http-timings/test.ts
dev-packages/browser-integration-tests/suites/tracing/browsertracing/long-tasks-disabled/test.ts
dev-packages/browser-integration-tests/suites/tracing/browsertracing/long-tasks-enabled/test.ts
dev-packages/browser-integration-tests/suites/tracing/metrics/pageload-browser-spans/test.ts
dev-packages/browser-integration-tests/suites/tracing/metrics/pageload-resource-spans/test.ts
dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals-fid/test.ts
dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals-fp-fcp/test.ts
dev-packages/browser-integration-tests/suites/tracing/request/fetch/test.ts
dev-packages/browser-integration-tests/suites/tracing/request/xhr/test.ts
packages/core/test/lib/tracing/trace.test.ts
packages/ember/tests/helpers/utils.ts
packages/opentelemetry-node/src/spanprocessor.ts
packages/opentelemetry-node/test/spanprocessor.test.ts
packages/tracing-internal/test/browser/metrics/utils.test.ts
packages/types/src/span.ts

As discovered during #10208, the `op` property of the `Span` interface was still missing a deprecation because `Span` inherited it from `SpanContext` which I missed. ~Looks like all usages of `op` were covered already in #10189 so this is more or less only a formality~
EDIT: Nope, definitely not all usages were already covered 😅 Added a bunch of parallel deprecation and replacement adjustments. Primarily in tests though, a couple of rewrites in code.

feat(types): Deprecate `op` on `Span` interface

---

dev-packages/browser-integration-tests/suites/tracing/browsertracing/http-timings/test.ts
packages/types/src/envelope.ts
packages/types/src/event.ts
packages/types/src/index.ts

This PR adds a `SerializedEvent` interface which more accurately represents what an event envelope item contains (i.e. the JSON structure of a serialized `Event` object). Specifically, the `spans` field now correctly only contains the attributes the POJO span will continue to hold, i.e. without the deprecations and methods declared in the `Span` interface.
In v8, we should change the `EventItem` type for the event envelope but doing so now is a breaking change I believe (And arguably, not too important to do now anyway). 
However, we can already use this type in our browser integration tests to remove a lot of the unnecessary deprecation ignores. 
ref #10222 (rest of this has to happen in v8)

feat(types): Add `SerializedEvent` interface (pre v8)

---

packages/serverless/src/awsservices.ts
packages/serverless/src/google-cloud-grpc.ts
packages/serverless/src/google-cloud-http.ts
packages/serverless/test/__mocks__/@sentry/node.ts
packages/serverless/test/awslambda.test.ts
packages/serverless/test/awsservices.test.ts
packages/serverless/test/gcpfunction.test.ts
packages/serverless/test/google-cloud-grpc.test.ts
packages/serverless/test/google-cloud-http.test.ts

Most of the changes here are with tests, otherwise we swap to use `startInactiveSpan` everywhere.
IMO it might be more correct to refactor to use `startSpanManual`, but that can come later, I want to keep same behavior for now.

ref(serverless): Use new span APIs for serverless

---

packages/vue/src/sdk.ts

Following up on stuff that was missed with https://github.com/getsentry/sentry-javascript/pull/10218

ref(vue): use functional vue integration as default

---

dev-packages/browser-integration-tests/suites/public-api/captureUserFeedback/withCaptureException/init.js
dev-packages/browser-integration-tests/suites/public-api/captureUserFeedback/withCaptureException/subject.js
dev-packages/browser-integration-tests/suites/public-api/captureUserFeedback/withCaptureException/test.ts
dev-packages/browser-integration-tests/suites/public-api/captureUserFeedback/withCaptureMessage/init.js
dev-packages/browser-integration-tests/suites/public-api/captureUserFeedback/withCaptureMessage/subject.js
dev-packages/browser-integration-tests/suites/public-api/captureUserFeedback/withCaptureMessage/test.ts

Added two tests to demonstrate correct behavior of `captureUserFeedback` when it's called in `beforeSend` as described in the docs.
Trying to rule out SDK issues for https://github.com/getsentry/sentry-javascript/issues/10229. Given the tests pass, I suspect something isn't working on the Sentry backend when ingesting the feedback.

test(core): Add integration test for `captureUserFeedback` on `captureException` and `captureMessage`

---

.github/workflows/build.yml
dev-packages/e2e-tests/test-applications/create-remix-app-v2/tests/behaviour-client.test.ts
dev-packages/e2e-tests/test-applications/create-remix-app/tests/behaviour-client.test.ts
dev-packages/rollup-utils/plugins/extractPolyfillsPlugin.mjs
packages/remix/test/integration/package.json

fixes https://github.com/getsentry/sentry-javascript/issues/10247
Also remove web-streams-polyfill pin introduced in https://github.com/getsentry/sentry-javascript/pull/10065 because that changed was reverted.

build(remix): Pin @vanilla-extract/integrations to make work on Node 14

---

packages/nextjs/src/client/browserTracingIntegration.ts
packages/nextjs/src/client/index.ts
packages/nextjs/src/client/rewriteFramesIntegration.ts
packages/nextjs/src/edge/index.ts
packages/nextjs/src/edge/rewriteFramesIntegration.ts
packages/nextjs/src/index.types.ts
packages/nextjs/src/server/httpIntegration.ts
packages/nextjs/src/server/index.ts
packages/nextjs/src/server/onUncaughtExceptionIntegration.ts
packages/nextjs/src/server/rewriteFramesIntegration.ts
packages/nextjs/test/clientSdk.test.ts
packages/nextjs/test/serverSdk.test.ts

The usage of this was not really working well to begin with, and even worse with the new functional integrations. Because if the user adds the integration themselves (e.g. `integrations: [new RewriteFrames()]`), it will not actually get the correct iteratee at all.
Overall it is much cleaner anyhow to just fork the integrations properly and use them instead of the default one - then we can rely on the standard behavior of merging integrations etc.
We need to do the same for basically all usages of `addOrUpdateIntegration`, as that actually does not work at all anymore with the functional integrations 😬 (and in many instances never really worked properly if users passed in a custom integration themselves).

fix(next): Fix custom integrations

---

packages/astro/src/client/sdk.ts
packages/astro/src/server/sdk.ts
packages/astro/test/client/sdk.test.ts

We should wait for https://github.com/getsentry/sentry-javascript/pull/10243 to merge this, as otherwise we'll get a deprecation/eslint error there.

ref(astro): Streamline how we add browser tracing

---

MIGRATION.md
dev-packages/browser-integration-tests/suites/public-api/startSpan/basic/test.ts
dev-packages/browser-integration-tests/suites/public-api/startTransaction/basic_usage/test.ts
dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals-fid/test.ts
dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals-fp-fcp/test.ts
docs/v8-new-performance-apis.md
packages/core/src/tracing/span.ts
packages/core/test/lib/scope.test.ts
packages/core/test/lib/tracing/trace.test.ts
packages/opentelemetry-node/test/spanprocessor.test.ts
packages/tracing-internal/src/browser/browsertracing.ts
packages/types/src/span.ts

Deprecate the `Span.parentSpanId` field on the interface and class. 
This required only a couple of code replacements and a bunch of test adjustments. Also went ahead and changed the integration test event type in the tests I was modifying (#10240). 
ref #10184

feat(core): Deprecate `Span.parentSpanId`

---

.github/workflows/build.yml
packages/wasm/package.json

By using functional integrations in #10230, we started importing from `@sentry/core` in the WASM integration. However, we didn't register `@sentry/core` as a dependency, making rollup bundle core into the package output. This changed the `build/npm` directory structure, making our entry points in `package.json` invalid.
This PR fixes things by simply registering core as a dependency of wasm. If we move WASM to core (which I strongly think we should do), we'll be able to get rid of this again.

fix(wasm): Add `@sentry/core` as a dependency

---

packages/replay-canvas/package.json

~- [ ] If you've added code that should be tested, please add tests.~ N/A
Fixes #10266
The built version of `@sentry-internal/replay-canvas` imports from `@sentry/utils`, and should therefore list `@sentry/utils` as one of its dependencies.

fix(replay-canvas): Add missing dependency on @sentry/utils

---

packages/sveltekit/src/client/browserTracingIntegration.ts
packages/sveltekit/src/client/sdk.ts
packages/sveltekit/src/server/rewriteFramesIntegration.ts
packages/sveltekit/src/server/sdk.ts
packages/sveltekit/src/server/utils.ts
packages/sveltekit/test/client/sdk.test.ts
packages/sveltekit/test/server/rewriteFramesIntegration.ts
packages/sveltekit/test/server/sdk.test.ts
packages/sveltekit/test/server/utils.test.ts
packages/utils/src/userIntegrations.ts
packages/utils/test/userIntegrations.test.ts

This updates the last usage of `addOrUpdateIntegration` and deprecates it.

feat(sveltekit): Update default integration handling & deprecate `addOrUpdateIntegration`

---

packages/feedback/src/constants.ts
packages/feedback/src/types/index.ts
packages/feedback/src/widget/Actor.css.ts
packages/feedback/src/widget/Dialog.css.ts
packages/feedback/src/widget/Main.css.ts

Adds ability to configure all border radiuses on feedback widget
Closes https://github.com/getsentry/sentry-javascript/issues/10256

feat(feedback): Configure feedback border radius

---

MIGRATION.md
packages/astro/src/index.server.ts
packages/browser/src/exports.ts
packages/bun/src/index.ts
packages/core/src/exports.ts
packages/core/src/index.ts
packages/core/test/lib/exports.test.ts
packages/deno/src/index.ts
packages/node-experimental/src/index.ts
packages/node-experimental/src/sdk/api.ts
packages/node-experimental/src/sdk/scope.ts
packages/node/src/index.ts
packages/serverless/src/index.ts
packages/sveltekit/src/server/index.ts
packages/vercel-edge/src/index.ts

Currently, you can use `Sentry.getClient() !== undefined` to check if Sentry was initialized. In v8, we want to change this so that this _always_ returns a client (possibly a Noop client), so this check will not work anymore there. Instead, we can provide a new util that does this explicitly, where we can control what it checks under the hood.

feat(core): Expose `isInitialized()` to replace checking via `getClient`

---

packages/tracing-internal/src/browser/metrics/index.ts
packages/tracing-internal/test/browser/metrics/index.test.ts

As per https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming/responseStart, `responseStart` can be 0 if the request is coming straight from the cache. This might lead us to calculate a negative ttfb.
To account for these scenarios, use `Math.max` to make sure we always set to 0 in the case of a negative value.

fix(tracing): Don't send negative ttfb

---

MIGRATION.md
packages/astro/src/index.types.ts
packages/browser/src/exports.ts
packages/browser/src/index.ts
packages/browser/src/integrations/breadcrumbs.ts
packages/browser/src/integrations/dedupe.ts
packages/browser/src/integrations/globalhandlers.ts
packages/browser/src/integrations/httpcontext.ts
packages/browser/src/integrations/index.ts
packages/browser/src/integrations/linkederrors.ts
packages/browser/src/integrations/trycatch.ts
packages/browser/src/sdk.ts
packages/browser/test/unit/integrations/breadcrumbs.test.ts
packages/deno/src/index.ts
packages/deno/src/sdk.ts
packages/nextjs/src/client/index.ts
packages/nextjs/src/index.types.ts
packages/nextjs/test/clientSdk.test.ts
packages/remix/src/index.types.ts
packages/sveltekit/src/index.types.ts

Also deprecate the `Integrations` hash in browser SDKs.
I also forgot to add the integrations from `@sentry/integrations` to the migration.md doc, so adding those as well!

feat(browser): Export functional integrations & deprecate classes

---

MIGRATION.md
packages/core/src/tracing/trace.ts
packages/tracing-internal/src/browser/browsertracing.ts
packages/tracing-internal/test/browser/browsertracing.test.ts
packages/types/src/index.ts
packages/types/src/startSpanOptions.ts

These are mostly naming changes to use `span` instead of `transaction` for options.
Missing is a new handling for `routingInstrumentation`, which I will tackle in a separate PR.

feat(tracing): Deprecate transaction-related options for `BrowserTracing`

---

MIGRATION.md
packages/astro/src/client/sdk.ts
packages/astro/test/client/sdk.test.ts
packages/browser/src/index.bundle.feedback.ts
packages/browser/src/index.bundle.replay.ts
packages/browser/src/index.bundle.tracing.replay.feedback.ts
packages/browser/src/index.bundle.tracing.replay.ts
packages/browser/src/index.bundle.tracing.ts
packages/browser/src/index.bundle.ts
packages/browser/src/index.ts
packages/browser/test/unit/profiling/integration.test.ts
packages/ember/addon/instance-initializers/sentry-performance.ts
packages/ember/addon/types.ts
packages/gatsby/src/utils/integrations.ts
packages/gatsby/test/gatsby-browser.test.ts
packages/gatsby/test/sdk.test.ts
packages/integration-shims/src/BrowserTracing.ts
packages/integration-shims/src/index.ts
packages/nextjs/src/client/browserTracingIntegration.ts
packages/nextjs/src/client/index.ts
packages/nextjs/test/clientSdk.test.ts
packages/sveltekit/src/client/browserTracingIntegration.ts
packages/sveltekit/src/client/sdk.ts
packages/sveltekit/test/client/sdk.test.ts
packages/tracing-internal/src/browser/browsertracing.ts
packages/tracing-internal/src/browser/index.ts
packages/tracing-internal/src/index.ts
packages/tracing/src/index.ts

feat(browser): Deprecate `BrowserTracing` in favor of `browserTracingIntegration`

---

packages/node/package.json

Just noticed that this entry point was broken. `build/npm` doesn't exist because the node package is not a package with CDN bundles. Hence all NPM tarball contents are directly in `build`.

fix(node): Fix downleveled types entry point

---

packages/react/src/reactrouterv6.tsx
packages/react/test/reactrouterv6.4.test.tsx

Resolves: https://github.com/getsentry/sentry-javascript/issues/10196
This PR adds a new option for React Router 6 integration, `stripBasename` for leaving out the `basename` from transaction names. 
TODO: Needs a documentation update.

feat(react): Add `stripBasename` option for React Router 6.

---

dev-packages/node-integration-tests/package.json
dev-packages/node-integration-tests/suites/tracing-experimental/mongoose/scenario.js
dev-packages/node-integration-tests/suites/tracing-experimental/mongoose/test.ts
yarn.lock

This tests v5.13.22 of mongoose because it's the most commonly use version currently supported by the OpenTelemetry plugin:
https://github.com/open-telemetry/opentelemetry-js-contrib/blob/fce7d3b5e478ff7525c9ffe99e59bf35f8c06207/plugins/node/instrumentation-mongoose/src/mongoose.ts#L80
https://www.npmjs.com/package/mongoose?activeTab=versions
It's worth noting that at least versions 5 and 7 of `mongoose` also generate `mongodb` spans because they use the library internally and we auto instrument everything. For some unknown reason, `mongoose@v8` does not appear to generate `mongodb` spans and I haven't tested v6 because very few people are using it.

test(node): Add `mongoose` auto instrumentation test for `@sentry/node-experimental`

---

dev-packages/node-integration-tests/suites/tracing-experimental/apollo-graphql/scenario.js
dev-packages/node-integration-tests/suites/tracing-experimental/apollo-graphql/test.ts

Part of: #9907
Tests only CJS usage.

test(node): Add tests for Apollo / GraphQL OpenTelemetry auto-instrumentation.

---

packages/replay/src/integration.ts

fix(replay): fixed type for options of replayIntegration

---

packages/core/src/index.ts
packages/replay/src/util/prepareReplayEvent.ts

This type wasn't exported from core but used in Replay. This PR just adds the export and fixes the faulty import
(This is part of a couple of fixes we need to get out to fix currently broken type declarations)

feat(core): Export `IntegrationIndex` type

---

packages/nextjs/src/server/httpIntegration.ts
packages/nextjs/src/server/onUncaughtExceptionIntegration.ts

For some reason `const { Http: OriginalHttp } = Integrations` caused weirdness around getting type imports from the local build structure instead of importing the type top-level. This PR removes the object destructuring in favour of directly referencing `Integrations.Http`.
ref https://github.com/getsentry/sentry-javascript/issues/10310#issuecomment-1909462471
(This is part of a couple of fixes we need to get out to fix currently broken type declarations)

fix(nextjs): Fix Http integration type declaration

---

packages/vue/src/types.ts

I was reading the type.ts code and I found the `woth` typo that should be `work`
#skip-changelog

NIT: typo on types.ts

---

biome.json

added ignoring of build output folders because otherwise testing and linting locally is annoying

chore(biome): Ignore SvelteKit and NextJS build output directories

---

packages/types/src/span.ts

(extracted from #10274 to discuss in isolation)
I propose we add known attribute keys to the `SpanAttributes` type because this way we can 
1. enforce a concrete type for some known keys
2. give users (and us) auto suggestions when setting attributes
WDYT, is this an improvement to the pure `Record` type?

ref(types): Add known attribute keys to `SpanAttributes` type

---

packages/core/src/baseclient.ts
packages/core/src/integration.ts
packages/core/test/lib/sdk.test.ts
packages/types/src/integration.ts

This adds a new hook to integrations which runs after all integrations have run their `setup` hooks.
This can be used to handle integrations that depend on each other. 
The only timing guarantee is that `afterAllSetup` will be called after every integration has run `setupOnce` and `setup`.

feat(core): Add `afterAllSetup` hook for integrations

---

packages/deno/src/integrations/deno-cron.ts

I think this conditional needs to still call the deno cron `fn()`, and that we should do an early return if the client is **not** on `SETUP_CLIENTS`

fix(deno): Call function if client is not setup

---

MIGRATION.md
packages/deno/src/index.ts
packages/deno/src/integrations/context.ts
packages/deno/src/integrations/contextlines.ts
packages/deno/src/integrations/deno-cron.ts
packages/deno/src/integrations/globalhandlers.ts
packages/deno/src/integrations/index.ts
packages/deno/src/integrations/normalizepaths.ts
packages/deno/src/sdk.ts

Refactor deno integrations to functional style.

feat(deno): Expose functional integrations to replace classes

---

packages/core/src/integrations/functiontostring.ts
packages/core/test/lib/integrations/functiontostring.test.ts

Auditing our integrations to make sure they work with the new client paradigm, also adding `export type` where appropriate.

fix(core): Make `FunctionToString` integration use SETUP_CLIENTS weakmap

---

dev-packages/e2e-tests/test-applications/nextjs-14/app/request-instrumentation/page.tsx
dev-packages/e2e-tests/test-applications/nextjs-14/tests/request-instrumentation.test.ts

We are running some experiments with Vercel to exlude the SDK from externalized packages and during that I noticed we have a test gap for patching request instrumentation.
In our experiments it broke due to funky compilation.

test(e2e): Add request instrumentation tests for Next.js 14

---

dev-packages/browser-integration-tests/suites/tracing/browsertracing/interactions/test.ts

This PR decreases the lower bound of the interaction span duration. In the script file, we hard block for 70ms but I've seen test fails where we're just ever so slightly below 70ms (69.x). Figured this is because of some timing inaccuracies.
closes #10363

ref(browser-integration-tests): Fix flake in interaction transaction tests

---

packages/node/src/integrations/spotlight.ts

To avoid capturing our own requests.
See https://github.com/getsentry/spotlight/pull/335

fix(spotlight): Use unpatched http.request

---

packages/core/src/baseclient.ts
packages/core/test/lib/integration.test.ts

Noticed that this is not really correct right now!

fix: Ensure `afterAllSetup` is called when using `addIntegration()`

---

CONTRIBUTING.md

As this comes up every now and then (e.g. https://github.com/getsentry/sentry-javascript/issues/5108), I gather it makes sense to document how to build the SDK youself. I added a note to explicitly state that there are no guarantees there.

docs: Add docs on building the SDK

---

CONTRIBUTING.md
packages/remix/src/index.server.ts

Looks like we missed re-exporting a couple of recently added functions in the Remix SDK. This PR adds the missing exports:
* `addIntegration`
* `getClient`
* `getCurrentScope`, `getIsolationScope`, `getGlobalScope`
* `setMeasurement`
* `getActiveSpan`
* `startSpan`, `startSpanManual`, `startInactiveSpan`
* `continueTrace`
* `isInitialized`
closes #10384

feat(remix): Export missing functions

---

CHANGELOG.md
biome.json
packages/astro/src/server/middleware.ts
packages/bun/src/integrations/bunserver.ts
packages/core/src/tracing/errors.ts
packages/core/src/tracing/index.ts
packages/core/src/tracing/span.ts
packages/core/src/tracing/spanstatus.ts
packages/core/test/lib/tracing/spanstatus.test.ts
packages/nextjs/src/common/utils/edgeWrapperUtils.ts
packages/nextjs/src/common/utils/responseEnd.ts
packages/nextjs/src/common/wrapApiHandlerWithSentry.ts
packages/nextjs/src/common/wrapRouteHandlerWithSentry.ts
packages/node/src/handlers.ts
packages/node/src/integrations/hapi/index.ts
packages/node/src/integrations/http.ts
packages/node/src/integrations/undici/index.ts
packages/remix/src/utils/instrumentServer.ts
packages/remix/src/utils/serverAdapters/express.ts
packages/serverless/src/gcpfunction/http.ts
packages/serverless/test/gcpfunction.test.ts
packages/sveltekit/src/server/handle.ts
packages/tracing-internal/src/browser/request.ts
packages/tracing-internal/src/common/fetch.ts
packages/tracing/test/span.test.ts
packages/types/src/span.ts

This PR deprecates the last remaining otel-incompatible API on the `Span` class and interface - `Span.setHttpStatus`. 
We replace this functionality with a `setHttpStatus` wrapper because in addition to setting the data/tag value (more on that below), this function also derives the span status from the status code. Added tests to make sure this is covered properly (I think it wasn't covered well before and we need to remove the old tests anyway). 
I checked with the ingest team and theoretically, from a Relay PoV, we could stop sending the `http.status_code` tag right now. Our min supported Relay version already primarily expectes the `http.response.status_code` _data_ property and only falls back to the tag. **However:** After giving this more thought, I opted to leave the payload …

feat(core): Deprecate `Span.setHttpStatus` in favor of `setHttpStatus`

---

CONTRIBUTING.md
packages/react/src/redux.ts
packages/react/test/redux.test.ts

While working on https://github.com/getsentry/sentry-javascript/issues/9220, I found that `attachReduxState` doesn't work anymore. This PR fixing it.

fix(react): Fix attachReduxState option

---

.vscode/settings.json
packages/astro/src/index.server.ts
packages/browser/src/index.ts
packages/bun/src/index.ts
packages/core/src/tracing/index.ts
packages/core/src/tracing/spanstatus.ts
packages/deno/src/index.ts
packages/node-experimental/src/index.ts
packages/node/src/index.ts
packages/remix/src/index.server.ts
packages/sveltekit/src/server/index.ts
packages/tracing-internal/src/exports/index.ts
packages/tracing/src/index.ts
packages/vercel-edge/src/index.ts

The old export contained a typo/camel-case inconsistency which I fixed in the new export and I opted to prepend the `get` verb. Came across this while working on #10268 and thought since we can, we should fix it in v8.
Also, this finally:
closes #10184

feat(core): Deprecate `spanStatusfromHttpCode` in favour of `getSpanStatusFromHttpCode`

---

CONTRIBUTING.md
dev-packages/node-integration-tests/package.json
dev-packages/node-integration-tests/src/index.ts
dev-packages/node-integration-tests/suites/tracing-experimental/hapi/scenario.js
dev-packages/node-integration-tests/suites/tracing-experimental/hapi/test.ts
yarn.lock

Ref #9907
This actually tests `@hapi/hapi@20.3.0` because the latest v21 is not supported by the otel auto-instrumentation.

test(node): Add `hapi` auto instrumentation test for `@sentry/node-experimental`

---

packages/browser/src/index.ts
packages/tracing-internal/src/browser/browserTracingIntegration.ts
packages/tracing-internal/src/browser/index.ts
packages/tracing-internal/src/index.ts

This implements changes to the new integration, based on feedback from the team.
The main thing this addresses is the way we disable the default span creation. The original idea was to make this work with custom router instrumentations (e.g. for react router) that may be added as separate integrations. This required us to keep track of if another, non-default implementation has been added, to opt out of the defaults.
With this change, we do not do this anymore. Instead, the defaults should be configured by wrapping integrations. Some examples for how this should then work:
1. Angular:
```ts
export function browserTracingIntegration(
options?: Parameters<typeof originalBrowserTracingIntegration>[0],
): Integration {
// do not use default navigation, as we provide our own
// actual code for …
```

ref(tracing): Implement changes to new `browserTracingIntegration`

---

dev-packages/e2e-tests/test-applications/node-exports-test-app/scripts/consistentExports.ts
packages/remix/src/index.server.ts

Missed some exports in my manual pass in #10385. Test in #10389 discovered more missing exports which this PR adds or marks as unnecessary in the re-export test.

feat(remix): Add more missing `@sentry/node` re-exports

---

dev-packages/e2e-tests/test-applications/node-exports-test-app/scripts/consistentExports.ts
packages/sveltekit/src/server/index.ts

Adds missing re-exports from `@sentry/node` in the sveltekit server SDK and enables the re-export test for @sentry/sveltekit
builds on top of https://github.com/getsentry/sentry-javascript/pull/10389

feat(sveltekit): Add more missing `@sentry/node` re-exports

---

.github/workflows/build.yml
dev-packages/e2e-tests/test-applications/node-exports-test-app/package.json
dev-packages/e2e-tests/test-applications/node-exports-test-app/scripts/consistentExports.ts
packages/bun/src/index.ts

This PR adds missing exports from the Node to the Bun SDK. Ignored a couple of exports that I believe aren't compatible with Bun or for which we have dedicated Bun repalcements (e.g. client, transport).
Node would throw ESM/CJS errors when importing from `@sentry/bun`. So let's just use Bun for this test 🙃 
more details in https://github.com/getsentry/sentry-javascript/pull/10389

feat(bun): Add missing `@sentry/node` re-exports

---

dev-packages/browser-integration-tests/suites/tracing/request/fetch-with-no-active-span/init.js
dev-packages/browser-integration-tests/suites/tracing/request/fetch-with-no-active-span/subject.js
dev-packages/browser-integration-tests/suites/tracing/request/fetch-with-no-active-span/test.ts
dev-packages/browser-integration-tests/suites/tracing/request/xhr-with-no-active-span/init.js
dev-packages/browser-integration-tests/suites/tracing/request/xhr-with-no-active-span/subject.js
dev-packages/browser-integration-tests/suites/tracing/request/xhr-with-no-active-span/test.ts
dev-packages/browser-integration-tests/utils/helpers.ts
packages/core/src/tracing/trace.ts
packages/core/test/lib/tracing/trace.test.ts
packages/opentelemetry/src/trace.ts
packages/opentelemetry/src/types.ts
packages/opentelemetry/test/trace.test.ts
packages/react/src/profiler.tsx
packages/react/test/profiler.test.tsx
packages/serverless/src/awsservices.ts
packages/serverless/src/google-cloud-grpc.ts
packages/serverless/src/google-cloud-http.ts
packages/serverless/test/awsservices.test.ts
packages/serverless/test/google-cloud-grpc.test.ts
packages/serverless/test/google-cloud-http.test.ts
packages/tracing-internal/src/browser/request.ts
packages/tracing-internal/src/common/fetch.ts
packages/tracing-internal/src/node/integrations/prisma.ts
packages/tracing/test/integrations/node/prisma.test.ts
packages/types/src/startSpanOptions.ts

This introduces a new `onlyIfParent` option to the start-span APIs, which, if set, will ensure to not create a span if there is no parent. I've added this also for otel to demonstrate this works there as well.
This PR also uses this option in a few places, esp. for http.client spans, to ensure we do not capture these if there is no ongoing transaction.
This replaces https://github.com/getsentry/sentry-javascript/pull/10375/files with a more generic solution, and includes the test from https://github.com/getsentry/sentry-javascript/pull/10376 (which passes here as well).

feat(core): Ensure `startSpan()` can handle spans that require parent

---

packages/tracing-internal/src/browser/browserTracingIntegration.ts

To make it easier to extend this.

feat(tracing): Export proper type for browser tracing

---

packages/tracing-internal/src/browser/browserTracingIntegration.ts

So we can be client-safe when extending the integration.

ref(tracing): Require to pass client to `startBrowserTracing*Span` utils

---

.github/workflows/build.yml

This does not really tell us anything the ESM tests do not already tell us. We can save some CI time there...

test(ci): Do not run browser integration tests for CJS

---

.github/workflows/build.yml

I also opened a PR upstream: https://github.com/joerick/pr-labels-action/pull/17 but merging speed is rather slow there, so I'd rather not wait for this.

build(ci): Bump pr-labels-action to use node20

---

packages/ember/addon/instance-initializers/sentry-performance.ts
packages/ember/addon/types.ts
packages/ember/tests/helpers/setup-sentry.ts
packages/ember/tests/helpers/utils.ts

Refactors the usage of `BrowserTracing()` for Ember.
There it is easy to refactor this because we do not expose this to the user - we automatically add the browsertracing integration based on configuration.
This depends on https://github.com/getsentry/sentry-javascript/pull/10372.

ref(ember): Use new `browserTracingIntegration()` under the hood

---

packages/vue/src/tracing.ts

Cannot get rid of transactions completely because we rely on accessing the root span to mutate.

ref(vue): use startInactiveSpan in tracing mixin

---

.github/workflows/build.yml

This runs a separate, streamlined lint step for prettier only, if only markdown files are changed.

ci: Always run code formatting CI job (even for *.md only PRs)

---

packages/core/src/tracing/trace.ts
packages/nextjs/src/client/routing/pagesRouterRoutingInstrumentation.ts
packages/nextjs/src/common/utils/wrapperUtils.ts
packages/nextjs/src/common/withServerActionInstrumentation.ts
packages/nextjs/src/common/wrapRouteHandlerWithSentry.ts
packages/node-experimental/src/sdk/init.ts
packages/node/src/sdk.ts
packages/opentelemetry/src/propagator.ts
packages/remix/src/utils/instrumentServer.ts
packages/sveltekit/src/server/utils.ts
packages/tracing-internal/src/browser/browserTracingIntegration.ts
packages/tracing-internal/src/browser/browsertracing.ts
packages/utils/src/tracing.ts
packages/utils/test/tracing.test.ts

Adds a simpler alternative to `tracingContextFromHeaders` which is deprecated with this PR. `tracingContextFromHeadrs` is returning duplicate data, and the value it returns is gonna be useless in a world where spans do not take traceparent data and dynamic sampling contexts directly.
I replaced the deprecated instances in places where it was easy and just added an eslint ignore in places where we will need to refactor in any case.

feat(utils): Add `propagationContextFromHeaders`

---

packages/ember/tests/helpers/utils.ts

Saw a flake for this, we should ignore long-task spans as they are unpredictable.

test(ember): Make test more robust

---

.github/workflows/build.yml

This does two things:
1. Only run webkit tests for the full bundle & esm tests (no need to run this for every variation...)
2. Shard the tests for better parallelization

ci: Streamline browser integration tests on CI

---

dev-packages/e2e-tests/test-applications/angular-17/src/main.ts
packages/angular-ivy/README.md
packages/angular/README.md
packages/angular/src/index.ts
packages/angular/src/tracing.ts
packages/angular/test/tracing.test.ts
packages/angular/test/utils/index.ts
packages/tracing-internal/src/browser/browserTracingIntegration.ts

Also deprecate the routing Instrumentation.
This is WIP on top of https://github.com/getsentry/sentry-javascript/pull/10351, to show how that would work.
No idea how to get the tests working for this, though...

feat(angular): Export custom `browserTracingIntegration()`

---

packages/nextjs/src/index.types.ts
packages/vercel-edge/src/index.ts
packages/vercel-edge/src/integrations/wintercg-fetch.ts
packages/vercel-edge/src/sdk.ts
packages/vercel-edge/test/wintercg-fetch.test.ts

This has not been converted yet.

ref(vercel-edge): Replace `WinterCGFetch` with `winterCGFetchIntegration`

---

packages/vue/src/index.ts
packages/vue/src/integration.ts
packages/vue/test/integration/VueIntegration.test.ts
packages/vue/test/integration/init.test.ts

`vueIntegration()` is already exported, but we didn't deprecate the class yet.

feat(vue): Deprecate `new VueIntegration()`

---

packages/browser/src/index.ts
packages/browser/src/profiling/integration.ts
packages/browser/test/unit/profiling/integration.test.ts

And deprecate `new BrowserProfilingIntegration()`

feat(browser): Export `browserProfilingIntegration`

---

MIGRATION.md
packages/core/src/tracing/hubextensions.ts
packages/core/test/lib/tracing/trace.test.ts
packages/opentelemetry-node/src/spanprocessor.ts
packages/opentelemetry/src/sampler.ts
packages/opentelemetry/src/spanExporter.ts
packages/opentelemetry/test/trace.test.ts

Updates `tracesSampler` to receive `name` and `attributes` instead of relying on `transactionContext` being passed.

feat(core): Pass `name` & `attributes` to `tracesSampler`

---

.github/workflows/build.yml

I guess this will make CI much faster since it is a hot path?

ci: Use larger runner for build job

---

dev-packages/browser-integration-tests/package.json
packages/replay-canvas/package.json
packages/replay/package.json
yarn.lock

Fixes an issue where errors from `CanvasManager` were being captured into our clients's Sentry.
Closes #10271

feat(replay): Bump `rrweb` to 2.10.0

---

.github/workflows/build.yml
.github/workflows/flaky-test-detector.yml

Also move off our custom fork as that is no longer needed.
This mainly fixes the node16 deprecation warning for the action: https://github.com/dorny/paths-filter/releases/tag/v3.0.0

build(ci): Update paths-filter action to v3.0.0

---

dev-packages/node-integration-tests/package.json
dev-packages/node-integration-tests/scripts/clean.js
yarn.lock

This PR adds a script to cleanup any docker containers left over from the node integration tests.
- It uses `globby@11` since that is already installed for a couple of our dependencies. 
- It finds all the `docker-compose.yml` files and runs `docker compose down --volumes` in those directories.
- It catches all errors for when docker is not running

fix(test): Clean up docker containers with script

---

packages/feedback/src/widget/Logo.ts

The CSS when colorScheme is "system" was always being overwritten so the logo color ends up being incorrect when OS is in dark mode.

fix(feedback): Fix logo color when colorScheme is "system"

---

packages/feedback/src/constants.ts

Requested by @Jesse-Box: "...fits better with the OS the user uses"

feat(feedback): Add `system-ui` to start of font family

---

dev-packages/browser-integration-tests/suites/integrations/httpclient/httpClientIntegration/init.js
dev-packages/browser-integration-tests/suites/integrations/httpclient/httpClientIntegration/subject.js
dev-packages/browser-integration-tests/suites/integrations/httpclient/httpClientIntegration/test.ts
dev-packages/browser-integration-tests/utils/generatePlugin.ts
dev-packages/rollup-utils/bundleHelpers.mjs

Previously, they were only put on `Sentry.Integrations.XXX`, now you can do e.g. `Sentry.httpClientIntegration()`.
While at it, I also added a browser integration test for this. I also made the way we do this more future proof, as in v8 this will not be imported anymore from `@sentry/integrations` (which we rely on right now), plus the heuristic used to rely on integration name === filename. Now, there is a manual map of imported method names to a CDN bundle file name.

feat(bundles): Add pluggable integrations on CDN to `Sentry` namespace

---

packages/astro/src/index.server.ts
packages/browser/src/index.ts
packages/bun/src/index.ts
packages/deno/src/index.ts
packages/node-experimental/src/index.ts
packages/node/src/index.ts
packages/remix/src/index.server.ts
packages/serverless/src/index.ts
packages/sveltekit/src/server/index.ts
packages/vercel-edge/src/index.ts

This replaces an old API but was not exported anywhere.
We introduced this here: https://github.com/getsentry/sentry-javascript/pull/10268/files

feat: Export `setHttpStatus` from all packages

---

dev-packages/browser-integration-tests/package.json
dev-packages/browser-integration-tests/suites/replay/privacyInput/template.html
dev-packages/browser-integration-tests/suites/replay/privacyInput/test.ts
packages/replay-canvas/package.json
packages/replay/package.json
yarn.lock

This bumps our rrweb-fork to 2.11.0, which mainly includes an improvement to avoid capturing credit card inputs.
See: https://github.com/getsentry/rrweb/releases/tag/2.11.0
Fixes https://github.com/getsentry/sentry-javascript/issues/10258
I also added a test in replay itself to verify that this works as expected!

feat(replay): Enforce masking of credit card fields

---

dev-packages/e2e-tests/test-applications/nextjs-app-dir/app/server-action/page.tsx
dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/transactions.test.ts
packages/nextjs/src/common/withServerActionInstrumentation.ts

Fixes https://github.com/getsentry/sentry-javascript/issues/10466

fix(nextjs): Do not report redirects and notFound calls as errors in server actions

---

.github/workflows/build.yml

One part of https://github.com/getsentry/sentry-javascript/issues/10486, actually our checks for this were not correct 😅 
This is still only a partial fix as if we change anything in core etc. we'll still have the build overhead every time, but it's something!

build(ci): Properly skip node CI steps when not changed

---

.github/workflows/build.yml

This is necessary since v4 of the action.

build(ci): Explicitly add codecov token

---

packages/core/src/baseclient.ts
packages/core/src/tracing/trace.ts
packages/core/src/tracing/transaction.ts
packages/core/test/lib/tracing/trace.test.ts
packages/node/test/performance.test.ts

Makes spans/transactions created with `startSpan`, `startSpanManual` and `startInactiveSpan` use data from the scopes that were active at the time these functions were called instead of using the scopes that are active when the span was `.end()`ed.
We already do this in the otel compatible SDK and we deem this behaviour more intuitive than using the scopes on span finish.

fix: Make `startSpan`, `startSpanManual` and `startInactiveSpan` pick up the scopes at time of creation instead of termination

---

dev-packages/e2e-tests/test-applications/vue-3/src/main.ts
dev-packages/e2e-tests/test-applications/vue-3/tests/performance.test.ts
packages/vue/README.md
packages/vue/src/browserTracingIntegration.ts
packages/vue/src/index.ts
packages/vue/src/router.ts
packages/vue/test/router.test.ts

This replaces the `vueRouterInstrumentation` and allows to deprecate browser tracing in the vue package.
Waiting for https://github.com/getsentry/sentry-javascript/pull/10476, then we should put these changes on top of the E2E test to verify it still works.

feat(vue): Implement vue `browserTracingIntegration()`

---

.github/workflows/build.yml

Mitigates https://github.com/getsentry/sentry-javascript/issues/10486 by skipping compilation unless binaries have changed or we are on release branch

ci(profiling): run compile only if bindings have changed

---

dev-packages/e2e-tests/test-applications/react-create-hash-router/src/index.tsx
dev-packages/e2e-tests/test-applications/react-router-6-use-routes/src/index.tsx
dev-packages/e2e-tests/test-applications/standard-frontend-react/src/index.tsx
packages/react/src/index.ts
packages/react/src/reactrouterv6.tsx
packages/react/test/reactrouterv6.4.test.tsx
packages/react/test/reactrouterv6.test.tsx

feat(react): Add browserTracingIntegrations for router v4 & v5
This adds a new `reactRouterV6BrowserTracingIntegration()` exports deprecating the old routing instrumentation.
I opted to leave as much as possible as-is for now, except for streamlining the attributes/tags we use for the instrumentation.
I also updated the E2E tests to the new format.

feat(react): Add `reactRouterV6BrowserTracingIntegration` for react router v6 & v6.4

---

packages/react/src/index.ts
packages/react/src/reactrouterv3.ts
packages/react/test/reactrouterv3.test.tsx

To replace the routing instrumentation.
There is a _small_ issue here, which is that we do not set the `from` attribute for the first navigation after the pageload (as technically we are calling instrument twice there...) - IMHO that's acceptable, we don't really have a `from` field anyhow in other instrumentations, so we may even think about removing this I'd say...

feat(react): Add `reactRouterV3BrowserTracingIntegration` for react router v3

---

.github/workflows/build.yml

Noticed warnings in GH for these, so bumping all of these to latest.

build(ci): Bump action dependencies for node profiling

---

MIGRATION.md
packages/astro/src/client/sdk.ts
packages/astro/test/client/sdk.test.ts
packages/browser/src/helpers.ts
packages/browser/src/index.bundle.feedback.ts
packages/browser/src/index.bundle.replay.ts
packages/browser/src/index.bundle.tracing.replay.feedback.ts
packages/browser/src/index.bundle.tracing.replay.ts
packages/browser/src/index.bundle.tracing.ts
packages/browser/src/index.bundle.ts
packages/browser/src/index.ts
packages/deno/src/integrations/globalhandlers.ts
packages/ember/addon/instance-initializers/sentry-performance.ts
packages/ember/addon/types.ts
packages/gatsby/src/utils/integrations.ts
packages/gatsby/test/gatsby-browser.test.ts
packages/gatsby/test/sdk.test.ts
packages/integration-shims/src/BrowserTracing.ts
packages/integration-shims/src/Feedback.ts
packages/nextjs/src/client/browserTracingIntegration.ts
packages/sveltekit/src/client/browserTracingIntegration.ts
packages/sveltekit/test/client/sdk.test.ts
packages/tracing-internal/src/browser/browsertracing.ts
packages/tracing-internal/src/browser/index.ts
packages/tracing-internal/src/index.ts
packages/tracing/src/index.ts

There is a proper replacement for all of them now.
Depends on:
* https://github.com/getsentry/sentry-javascript/pull/10491
* https://github.com/getsentry/sentry-javascript/pull/10489
* https://github.com/getsentry/sentry-javascript/pull/10488

feat(browser): Deprecate `BrowserTracing` integration

---

.github/dependabot.yml

Currently, it is only updating the yarn.lock, which is not really what we want, we want the version in the package.json to be raised, which is what this does (I believe).
See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy
See https://github.com/getsentry/sentry-javascript/pull/10496 for how that does not correctly bump right now.

build(ci): Make dependabot actually update the sentry-cli versions

---

dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/transactions.test.ts
packages/nextjs/src/common/withServerActionInstrumentation.ts

We were setting data on the wrong isolation scope for server actions.

fix(nextjs): Apply server action data to correct isolation scope

---

.github/workflows/build.yml
dev-packages/e2e-tests/test-applications/vue-3/tests/performance.test.ts

With the recent change to skip the node profiling compile step when it was not changed, we implicitly also skipped the "Prepare E2E tests" job - as that is by default skipped if the dependent job is skipped.
This PR changes this so that we should be running this even if that was skipped. We have to make sure to check that `build` itself was not skipped though (as then we want to _actually_ skip this).

build(ci): Ensure we run E2E tests when profiling node is skipped

---

.github/workflows/build.yml

I should have read the comments on why we can't update this 😬  - we should still take some time to actually refactor this to work with the new actions, but for now this is fine.
Also fixes some issues with the CI script for tarball handling etc.

build(ci): Use v3 of artifact actions for node-profiling

---

.github/workflows/build.yml
packages/deno/package.json

We don't generate coverage report for these, so we should not try to upload them to codecov, as the action warns about this.

build(test): Skip codecov upload for bun & deno

---

.github/workflows/build.yml

In CI currently on develop, we are stuck in a situation where we don't build bindings which means that the e2e tests always fail.
Let's only run the profiling e2e tests whenever we change bindings, and make it a little more liberal for when we do run CI for changing bindings.

build: Only run profiling e2e test if bindings have changed

---

packages/replay/src/coreHandlers/util/addFeedbackBreadcrumb.ts
packages/replay/src/types/replayFrame.ts

We are creating a replay breadcrumb when user feedback was submitted, however, the it was not typed correctly, which the timestamp not being included in the proper location.

fix(feedback): Replay breadcrumb for feedback events was incorrect

---

packages/browser/src/index.ts
packages/replay/src/index.ts
packages/replay/src/util/getReplay.ts
packages/replay/test/unit/util/getReplay.test.ts
packages/replay/test/utils/TestClient.ts

As pointed out here, and I also did notice that myself, it is not super nice - as you need to provide a generic integration to `getIntegrationByName`, which is annoying to do in a type safe way, esp. if you want to avoid deprecations:
```ts
const client = getClient();
const replay = client && client.getIntegrationByName && client.getIntegrationByName<ReturnType<typeof replayIntegration>>('Replay');
```
So IMHO a small utility `Sentry.getReplay()` is not unreasonable for this 🤔

feat(replay): Add `getReplay` utility function

---

.github/workflows/build.yml
packages/nextjs/test/run-integration-tests.sh

We are dropping Node.js < 14 in v8.

test(nextjs): Don't run Next.js integration tests for Node.js < 14

---

packages/ember/addon/index.ts
packages/ember/addon/instance-initializers/sentry-performance.ts
packages/ember/addon/types.ts
packages/ember/tests/helpers/utils.ts

feat(v8/ember): Remove deprecated exports

---

dev-packages/browser-integration-tests/suites/wasm/init.js
packages/wasm/src/index.ts

feat(v8/wasm): Remove deprecated exports

---

dev-packages/e2e-tests/test-applications/create-next-app/sentry.server.config.ts
dev-packages/node-integration-tests/suites/public-api/LocalVariables/local-variables-memory-test.js
packages/bun/src/sdk.ts
packages/node-experimental/src/integrations/index.ts
packages/node/src/integrations/index.ts
packages/node/src/integrations/local-variables/index.ts

Works toward https://github.com/getsentry/sentry-javascript/issues/8844 in a more incremental way.

feat(v8/node): Remove LocalVariables class integration

---

packages/core/src/hub.ts
packages/opentelemetry/src/contextManager.ts
packages/opentelemetry/src/custom/hub.ts
packages/opentelemetry/src/index.ts
packages/opentelemetry/src/propagator.ts
packages/opentelemetry/src/spanExporter.ts
packages/opentelemetry/src/spanProcessor.ts
packages/opentelemetry/src/trace.ts
packages/opentelemetry/test/asyncContextStrategy.test.ts
packages/opentelemetry/test/custom/hub.test.ts
packages/opentelemetry/test/custom/hubextensions.test.ts
packages/opentelemetry/test/custom/transaction.test.ts
packages/opentelemetry/test/helpers/initOtel.ts
packages/opentelemetry/test/integration/breadcrumbs.test.ts
packages/opentelemetry/test/integration/otelTimedEvents.test.ts
packages/opentelemetry/test/integration/scope.test.ts
packages/opentelemetry/test/integration/transactions.test.ts
packages/opentelemetry/test/trace.test.ts

This is an intermediate step to streamline what we need to customize in OTEL. This should make it easier to slowly remove customizations there.
The main change is that you can set a `createHub` method on the main carrier, which will be used if set. This way, all the code we have to duplicate in node-experimental right now just to create the correct `OpenTelemetryHub` can mostly go away.
We will remove this again during then v8 cycle.

feat(core): Streamline custom hub creation for node-experimental

---

packages/browser/src/exports.ts
packages/browser/src/integrations/globalhandlers.ts
packages/browser/src/integrations/index.ts

closes https://github.com/getsentry/sentry-javascript/issues/5842
Also deletes `GlobalHandlers` integration deprecated export while I'm here.

feat(v8/browser): Remove `_eventFromIncompleteOnError` usage

---

MIGRATION.md
packages/astro/src/index.server.ts
packages/browser/src/index.ts
packages/bun/src/index.ts
packages/core/src/tracing/index.ts
packages/core/src/tracing/spanstatus.ts
packages/deno/src/index.ts
packages/node-experimental/src/index.ts
packages/node/src/index.ts
packages/remix/src/index.server.ts
packages/serverless/src/index.ts
packages/sveltekit/src/server/index.ts
packages/tracing-internal/src/exports/index.ts
packages/tracing/src/index.ts
packages/vercel-edge/src/index.ts

Small removal for `spanStatusfromHttpCode`!

feat(v8): Remove deprecated spanStatusfromHttpCode export

---

packages/nextjs/src/common/wrapApiHandlerWithSentry.ts

Pretty self-explanatory- corrects the function name from the nonexistent `wrapApiWithSentry` (seems like it was intended to be `wrapApiHandlerWithSentry`) in a deprecation warning.

docs(nextjs): Fix function name in deprecation message

---

packages/sveltekit/src/client/load.ts
packages/sveltekit/test/client/load.test.ts

This PR adds the Http 400 avoidance logic from our server-side `load` function instrumentation to the client-side wrapper. Didn't know that these errors were a thing on the client side but now that we know, we definitely don't want to capture them.
Also added tests
closes https://github.com/getsentry/sentry-javascript/issues/10568

fix(sveltekit): Avoid capturing Http 4xx errors on the client

---

packages/angular-ivy/scripts/prepack.ts

This PR adds an `exports` field to the `package.json` for `@sentry/angular-ivy`. While it seems like regular Angular apps didn't need it, tools like `vitest` expect the field as soon as `type: "module"` is specified.
IMO this is just a fix for v7 as we'll bump the APF from Angular 12 to at least Angular 14 in v8. So once this is in, I'll also backport the fix to `v7`.
In addition to the repro provided in #10511, I also tested with Angular 12 and Angular 17 test apps. Seemed to work so far.
closes #10511

fix(angular-ivy): Add `exports` field to `package.json`

---

packages/astro/src/index.server.ts
packages/astro/src/index.types.ts
packages/browser/src/exports.ts
packages/browser/src/sdk.ts
packages/bun/src/index.ts
packages/core/src/exports.ts
packages/core/src/hub.ts
packages/core/src/index.ts
packages/deno/src/index.ts
packages/node-experimental/src/index.ts
packages/node-experimental/src/sdk/api.ts
packages/node-experimental/src/sdk/hub.ts
packages/node-experimental/src/sdk/scope.ts
packages/node-experimental/src/sdk/types.ts
packages/node/src/index.ts
packages/react/src/errorboundary.tsx
packages/remix/src/index.server.ts
packages/remix/src/index.types.ts
packages/serverless/src/index.ts
packages/sveltekit/src/index.types.ts
packages/sveltekit/src/server/index.ts
packages/types/src/hub.ts
packages/vercel-edge/src/index.ts

After the deprecation in v7 we now remove `lastEventId`.

ref: Remove `lastEventId`

---

MIGRATION.md
packages/bun/test/integrations/bunserver.test.ts
packages/core/src/hub.ts
packages/core/test/lib/base.test.ts
packages/core/test/lib/exports.test.ts
packages/core/test/lib/integration.test.ts
packages/core/test/lib/scope.test.ts
packages/core/test/lib/sdk.test.ts
packages/core/test/lib/tracing/dynamicSamplingContext.test.ts
packages/core/test/lib/tracing/errors.test.ts
packages/core/test/lib/tracing/trace.test.ts
packages/deno/test/__snapshots__/mod.test.ts.snap
packages/deno/test/mod.test.ts
packages/node-experimental/src/sdk/hub.ts
packages/node/test/handlers.test.ts
packages/node/test/integrations/http.test.ts
packages/node/test/integrations/undici.test.ts
packages/opentelemetry-node/test/propagator.test.ts
packages/opentelemetry-node/test/spanprocessor.test.ts
packages/opentelemetry/test/propagator.test.ts
packages/sveltekit/test/server/handle.test.ts
packages/tracing-internal/test/browser/backgroundtab.test.ts

This PR is a backport of https://github.com/getsentry/sentry-javascript/pull/10574, deprecating the hub constructor.

feat(core): Deprecate the `Hub` constructor

---

packages/sveltekit/src/vite/sourceMaps.ts

As pointed out in https://github.com/getsentry/sentry-javascript/issues/10589, we didn't properly await sourcemaps flattening via sorcery before proceeding to upload them. The reason is that the async callbacks in `forEach` weren't awaited. A `for` loop is the better approach here. Wondering if we should lint against async `forEach` callbacks.
This behaviour could have caused various inconsistencies. My suspicion is that the timing worked _well enough_ in most cases but we definitely want to properly await this step.
Thanks to @MSDev201 for bringing this up!
Unfortunately this likely won't fix #10589 as a whole :(

fix(sveltekit): Properly await sourcemaps flattening

---

packages/core/src/tracing/span.ts
packages/types/src/span.ts

This was apparently left over from some in-between state, users should actually use `spanToJSON(span)` there to get attributes.

docs: Fix deprecation message for span data/attributes

---

packages/core/src/baseclient.ts
packages/core/src/exports.ts
packages/core/src/index.ts

Instead of to the client.
This was done to ensure this would be "global" without using the fully global event processors (which need to be removed in a separate step). But in the new model, it makes more sense to add them to the isolation scope.

feat(core): Update `addEventProcessor` to add to isolation scope

---

packages/core/src/breadcrumbs.ts
packages/core/src/exports.ts
packages/core/src/index.ts
packages/core/test/lib/base.test.ts
packages/node-experimental/src/index.ts
packages/node-experimental/src/sdk/api.ts
packages/node-experimental/src/sdk/hub.ts
packages/node-experimental/src/sdk/scope.ts
packages/node-experimental/test/integration/breadcrumbs.test.ts
packages/node-experimental/test/integration/scope.test.ts
packages/opentelemetry/src/custom/scope.ts
packages/opentelemetry/src/spanProcessor.ts
packages/opentelemetry/test/custom/scope.test.ts
packages/opentelemetry/test/integration/breadcrumbs.test.ts
packages/opentelemetry/test/integration/scope.test.ts

Build on top of https://github.com/getsentry/sentry-javascript/pull/10600, as that relies on this to ensure replay still works.
This basically goes a step further than https://github.com/getsentry/sentry-javascript/pull/10586/files to actually change the implementation to skip the hub completely.

feat(core): Update `Sentry.addBreadcrumb` to skip hub

---

packages/core/src/tracing/span.ts
packages/types/src/span.ts

This was apparently left over from some in-between state, users should actually use `spanToJSON(span)` there to get attributes.
Backporting this (#10604 ) to v7!

docs: Fix deprecation message for span data/attributes 

---

packages/core/src/exports.ts
packages/core/src/integration.ts
packages/core/src/metrics/aggregator.ts
packages/core/src/metrics/browser-aggregator.ts
packages/core/src/sdk.ts
packages/core/src/utils/prepareEvent.ts
packages/node-experimental/src/sdk/hub.ts
packages/node-experimental/src/sdk/init.ts
packages/node/src/sdk.ts
packages/opentelemetry/src/setupEventContextTrace.ts
packages/replay/src/integration.ts
packages/replay/src/util/addGlobalListeners.ts
packages/replay/src/util/getReplay.ts
packages/replay/src/util/prepareReplayEvent.ts
packages/types/src/client.ts

This makes the following required on the client:
* `captureSession`
* `getSdkMetadata`
* `addEventProcessor`
* `getEventProcessor`
* `getIntegrationByName`
* `addIntegration`
* `init`
* `captureAggregrateMetrics`

ref(core): Make remaining client methods required

---

.github/workflows/build.yml

Always run Node unit tests because unlike the name suggests, they not only execute @sentry/node specific unit tests but all server-side package unit tests, including packages like Astro, NextJS or Serverless.

chore(ci): Always run Node unit tests

---

packages/angular/src/errorhandler.ts
packages/angular/test/errorhandler.test.ts
packages/browser/src/exports.ts
packages/browser/src/helpers.ts
packages/browser/src/sdk.ts
packages/browser/test/unit/index.test.ts
packages/nextjs/test/integration/pages/reportDialog.tsx
packages/react/src/errorboundary.tsx

Removes all deprecated showReportDialog APIs. I noticed we had one deprecation too many in there on the exported options type. I will silently remove this deprecation.

ref: Remove deprecated `showReportDialog` APIs

---

packages/astro/src/index.server.ts
packages/astro/src/index.types.ts

This PR removes all deprecations except for `getCurrentHub` which (unless I missed something last week) stays deprecated for now.

feat(v8/astro): Remove deprecated exports from Astro SDK

---

MIGRATION.md
packages/gatsby/package.json
packages/react/README.md
packages/react/package.json
packages/react/src/errorboundary.tsx
packages/react/test/errorboundary.test.tsx

Resolves: #9828    
Drops official support for React 15.x

feat(react): Drop support for React 15

---

packages/browser/src/index.ts
packages/bun/src/index.ts
packages/core/src/tracing/index.ts
packages/core/src/tracing/utils.ts
packages/deno/src/index.ts
packages/node-experimental/src/index.ts
packages/node/src/index.ts
packages/remix/src/index.server.ts
packages/serverless/src/index.ts
packages/sveltekit/src/server/index.ts
packages/tracing-internal/src/exports/index.ts
packages/tracing/src/index.ts
packages/tracing/test/hub.test.ts
packages/tracing/test/utils.test.ts
packages/utils/test/tracing.test.ts
packages/vercel-edge/src/index.ts

Instead, import this directly from `@sentry/utils`.
Should help when we move `@sentry/utils` into core.

feat(v8): Remove `extractTraceparentData` export

---

packages/core/src/exports.ts
packages/node-experimental/src/index.ts
packages/node-experimental/src/sdk/api.ts
packages/node-experimental/src/sdk/scope.ts

We have this in core now, and align the implementation there to work consistently (and also in a future where a client may not be undefined).

ref(node-experimental): Remove custom `isInitialized`

---

packages/angular/src/tracing.ts
packages/ember/addon/instance-initializers/sentry-performance.ts
packages/tracing-internal/src/browser/browserTracingIntegration.ts
packages/tracing-internal/test/browser/browserTracingIntegration.test.ts

This should make using these much easier:
* add a default `op` to the spans, so users don't need to specify them.
* Return the created span (or undefined), ensuring users don't need to do all the checking for op etc. themselves. 
Also make some small adjustments to ember & angular instrumentation to leverage some of these changes.

feat(core): Make custom tracing methods return spans & set default op

---

packages/core/src/exports.ts
packages/core/src/scope.ts
packages/core/test/lib/tracing/trace.test.ts

One more step to avoid the hub...
Note: This showed a potential footgun (?), where if you pass a client-less scope to `startSpan()`, no span will be created (because no client = no tracing, and the given scope will be made the current scope in the callback). this is correct behavior here, but _could_ be a bit unexpected ("why is no span being created here??"). We could think about warning if a client-less scope is passed in there, but not sure if that's worth it...

feat(core): Lookup client on current scope, not hub

---

packages/astro/src/index.server.ts
packages/browser/src/exports.ts
packages/bun/src/index.ts
packages/deno/src/index.ts
packages/node-experimental/src/index.ts
packages/node/src/index.ts
packages/remix/src/index.server.ts
packages/serverless/src/index.ts
packages/sveltekit/src/server/index.ts
packages/vercel-edge/src/index.ts

Given users should make use of attributes when performing custom instrumentation, this PR adds exports for our semantic attributes keys from the SDK packages so that users don't have to install `@sentry/core` explicitly.

feat: Export semantic attribute keys from SDK packages

---

CHANGELOG.md

Updates the changelog for v7.101.0.
Note, we need to also pick the changelog updates onto develop (also 7.100.x changes) after we published.

meta(changelog): Update changelog for v7.101.0

---

packages/core/src/asyncContext.ts
packages/core/src/exports.ts
packages/core/src/hub.ts
packages/core/src/index.ts
packages/core/src/tracing/trace.ts

Small refactor to ensure we _always_ use a default async context strategy, making the default behavior more explicit.
This will (hopefully) make it easier to encapsulate this going forward.

ref(core): Always use a (default) ACS

---

packages/core/src/asyncContext.ts
packages/core/src/hub.ts
packages/core/src/index.ts
packages/node/src/async/domain.ts
packages/node/src/async/hooks.ts
packages/node/test/async/domain.test.ts
packages/node/test/async/hooks.test.ts
packages/opentelemetry/src/asyncContextStrategy.ts
packages/opentelemetry/test/asyncContextStrategy.test.ts
packages/serverless/src/utils.ts
packages/vercel-edge/src/async.ts

We don't have this anymore in the new model.

ref: Remove `reuseExisting` option for ACS

---

packages/nextjs/src/config/webpack.ts

It seems like newer versions of Next.js do not use the `_N_E` namespace anymore but leave it up to the user. We need to adjust our config for that.
We should in the near future add E2E tests that check for source mapping in Next.js.

fix(nextjs): Remove `webpack://` prefix more broadly from source map `sources` field

---

packages/astro/src/client/sdk.ts
packages/astro/test/client/sdk.test.ts

Spotted one more deprecation ignore in Astro (after #10611) where I initially thought there's more logic to consider but turns out it's just the test that's no longer necessary in a v8 world.

test(astro): Remove old `BrowserTracing` test

---

.github/CANARY_FAILURE_TEMPLATE.md

test: Add SLA label to canary test failure issues

---

dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/devErrorSymbolification.test.ts

Apparently the colno shifted by one https://github.com/getsentry/sentry-javascript/actions/runs/7894509917/job/21545636786
We cannot also just shift it by one because that would then fail the tests on non-canary.
Fixes https://github.com/getsentry/sentry-javascript/issues/10544

test: Adjust Next.js dev error symbolication tests to new behaviour

---

.github/workflows/build.yml
dev-packages/e2e-tests/test-applications/create-remix-app-v2/app/entry.client.tsx
dev-packages/e2e-tests/test-applications/create-remix-app-v2/app/entry.server.tsx
dev-packages/e2e-tests/test-applications/create-remix-app-v2/remix.config.js
dev-packages/e2e-tests/test-applications/create-remix-app-v2/tests/behaviour-client.test.ts
dev-packages/e2e-tests/test-applications/create-remix-app/app/entry.client.tsx
dev-packages/e2e-tests/test-applications/create-remix-app/app/entry.server.tsx
dev-packages/e2e-tests/test-applications/create-remix-app/tests/behaviour-client.test.ts

**Update**: Added `environment: 'qa'` to Remix e2e tests.
~Could not find anything that may cause this to fail, I suppose it was slow ingestion.~
~It's still weird that it only happens in Remix client-side tests. (They take slightly longer to finish, so they may be more prone to timeout when there's slow ingestion)~
~Ran CI many times, and they're not timing out anymore as far as I see.~

test: Re-enable Remix client-side e2e tests

---

packages/svelte/package.json
yarn.lock

To not run in watch mode we need to specifically run `vitest run` instead of `vitest` (missed this when reviewing #10350).
- `yarn test` will run the test suites once
- `yarn test:watch` will continue to run the tests in watch mode
Also unstaled `yarn.lock` which we also seem to have missed in #10350

test(svelte): Avoid running vitest in watch mode

---

dev-packages/e2e-tests/test-applications/angular-17/package.json
dev-packages/e2e-tests/test-applications/angular-17/playwright.config.ts
dev-packages/e2e-tests/test-applications/angular-17/src/app/app.routes.ts
dev-packages/e2e-tests/test-applications/angular-17/src/app/home/home.component.ts
dev-packages/e2e-tests/test-applications/angular-17/tests/performance.test.ts
packages/angular/src/tracing.ts

This PR addresses the problematic check of `getActiveSpan()` in  our Angular SDK's `TraceService` raised in #10634.
In certain situations (e.g. very quick navigations after the initial pageload) the check of `getActiveSpan()` could lead to navigations not getting their own transaction, as the pageload transaction was still active at that time.
I also checked the behaviour of multiple subsequent redirects and here, we only create one navigation transaction for all redirects. The reason for this is that the Angular router doesn't fire individual events for the redirects but only one for the final redirect. IMHO this is fine and should be expected behaviour. 
ref #10634

fix(angular): Ensure navigations always create a transaction

---

packages/browser/src/exports.ts

We forgot to re-export these, apparently.

feat(browser): Export `getIsolationScope` and `getGlobalScope`

---

packages/astro/test/client/sdk.test.ts
packages/astro/test/server/sdk.test.ts
packages/nextjs/src/client/index.ts
packages/nextjs/src/server/index.ts
packages/nextjs/test/clientSdk.test.ts
packages/nextjs/test/serverSdk.test.ts
packages/remix/src/index.client.tsx
packages/remix/src/index.server.ts
packages/remix/test/index.client.test.ts
packages/remix/test/index.server.test.ts
packages/sveltekit/test/client/sdk.test.ts
packages/sveltekit/test/server/sdk.test.ts

This was a bit inconsistent now, we sometimes stored it on the current and sometimes on the isolation scope. Fixing this to always be on the isolation scope, for consistency.

ref: Store runtime on isolation scope

---

.craft.yml
dev-packages/e2e-tests/verdaccio-config/config.yaml
package.json
packages/hub/LICENSE
packages/hub/README.md
packages/hub/package.json

Since we deleted `@sentry/hub` in #10530, we also removed the craft NPM target for the hub package. Given that the craft config is always taken from `develop` (generally, the default branch of the repository), Craft no longer published `@sentry/hub` when we cut a release from our `v7` branch.
Unfortunately, the NPM target does not support an optional `onlyIfPresent` configuration, meaning for now, we have to continue publishing a `@sentry/hub` placeholder package when we cut a release from `develop` (i.e. our v8 branch at the moment).
I'll spend some time trying to adjust our publishing/craft process to finally unblock us here. We shouldn't have to continue publishing a placeholder just to ensure we can publish v7 correctly.

fix(publish): Ensure `@sentry/hub` is published in v7

---

CHANGELOG.md

Cutting a patch to release the missing `@sentry/hub` package from 7.101.0

meta: Update CHANGELOG for 7.101.1

---

packages/tracing-internal/src/browser/browserTracingIntegration.ts

We should also backport this to v7, probably.
Closes https://github.com/getsentry/sentry-javascript/issues/10578

fix(tracing): Guard against missing `window.location`

---

.github/workflows/build.yml

Noticed our "Build & Test" workflow doesn't run on v7 which caused failing tests on the v7 branch, [blocking](https://github.com/getsentry/publish/issues/3412) a release. This PR adds `v7` to one of the branches where the workflow is running. 
Furthermore:
- adjusted the `is_develop` variable to also be `true` for `v7`
- size check to compare against `v7`
I think these additional changes make sense but happy to revert if reviewers have concerns

chore(ci): Ensure "Build & Test" workflow runs on `v7`

---

dev-packages/e2e-tests/test-applications/sveltekit-2/package.json
dev-packages/e2e-tests/test-applications/sveltekit-2/src/routes/+layout.svelte
dev-packages/e2e-tests/test-applications/sveltekit-2/src/routes/+page.svelte
dev-packages/e2e-tests/test-applications/sveltekit-2/src/routes/redirect1/+page.ts
dev-packages/e2e-tests/test-applications/sveltekit-2/src/routes/redirect2/+page.ts
dev-packages/e2e-tests/test-applications/sveltekit-2/test/performance.test.ts
packages/sveltekit/src/client/browserTracingIntegration.ts
packages/sveltekit/test/client/browserTracingIntegration.test.ts

Similarly to #10646, this PR adjusts the root span/transaction creation behaviour of the SvelteKit router instrumentation:
- We no longer check for an active span to create a new navigation span
- This is possible without any `pageloadOngoing` flag because, luckily, pageload and navigation instrumentation is completely decoupled
- Consequently, navigations happening directly after the first pageload will now create their own transaction instead of being attached to the pageload transaction
- Consequently, redirects within a (user perceived) navigation are now treated as separate transactions, where the "current" navigation finishes the transaction of the previous redirect.
Additional changes:
* Removed tag for routing instrumentation (we now have `sentry.origin` for this anyway)
* Added …

fix(sveltekit): Ensure navigations and redirects always create a new transaction

---

packages/core/src/tracing/span.ts
packages/core/src/tracing/transaction.ts
packages/tracing/test/integrations/apollo-nestjs.test.ts
packages/tracing/test/integrations/apollo.test.ts
packages/tracing/test/integrations/graphql.test.ts
packages/tracing/test/integrations/node/mongo.test.ts
packages/tracing/test/integrations/node/postgres.test.ts
packages/tracing/test/span.test.ts
packages/types/src/span.ts
packages/types/src/transaction.ts

With more strict TS settings, these could lead to problems:
1. `startChild()` should return a span interface, to match the interface implementation.
2. All properties that are optional in span/transactions need to also accept `| undefined` to be really correct - otherwise when we extend this and set `undefined` explicitly it complains there. 
Fixes https://github.com/getsentry/sentry-javascript/issues/10654

ref: Make span types more robust

---

dev-packages/node-integration-tests/jest.config.js
dev-packages/node-integration-tests/suites/anr/basic-session.js
dev-packages/node-integration-tests/suites/anr/basic.js
dev-packages/node-integration-tests/suites/anr/basic.mjs
dev-packages/node-integration-tests/suites/anr/forked.js
dev-packages/node-integration-tests/suites/anr/should-exit-forced.js
dev-packages/node-integration-tests/suites/anr/should-exit.js
dev-packages/node-integration-tests/suites/proxy/basic.js
dev-packages/node-integration-tests/suites/tracing-experimental/hapi/scenario.js
dev-packages/node-integration-tests/suites/tracing-experimental/mongoose/scenario.js
dev-packages/node-integration-tests/suites/tracing-new/httpIntegration/spans/scenario.ts
dev-packages/node-integration-tests/utils/run-tests.ts

This improves the output and formatting of the node integration tests, making it a bit easier to work with them:
1. Removed the coverage output, making the general output much clearer
2. Ensure we have color in the jest output, making it easier to scan it
3. Remove logging around started tests & workers, streamlining the output and aligning it more with the usual jest output.
4. Move skipped output to the end of the test, clearing up the output for actually run tests
5. Update summary at the bottom to show success/failed/skipped test numbers
6. Add color to summary output (error/success/skipped) to make it clearer.
7. Show relative path names instead of full path names
Skipped tests:
Failed test:
Successful test:
Failed test summary:
Successful test summary:

test: Improve node integration test running

---

packages/bun/test/integrations/bunserver.test.ts
packages/core/test/lib/integration.test.ts
packages/core/test/lib/scope.test.ts
packages/core/test/lib/sdk.test.ts
packages/core/test/lib/tracing/dynamicSamplingContext.test.ts
packages/core/test/lib/tracing/errors.test.ts
packages/core/test/lib/tracing/trace.test.ts
packages/opentelemetry-node/test/propagator.test.ts
packages/opentelemetry-node/test/spanprocessor.test.ts
packages/opentelemetry/test/propagator.test.ts
packages/sveltekit/test/server/handle.test.ts
packages/tracing-internal/test/browser/backgroundtab.test.ts
packages/tracing-internal/test/browser/browsertracing.test.ts
packages/tracing/test/idletransaction.test.ts
packages/tracing/test/span.test.ts

This removes most (but not all) usage of `makeMain` in our own tests.
Some node tests remain for now, most of these will eventually be removed, so I figured no need to change them right now.

ref: Remove usage of `makeMain` in tests

---

packages/node-experimental/src/index.ts
packages/node-experimental/src/otel/contextManager.ts
packages/node-experimental/src/sdk/hub.ts

Noticed these were not exported yet there.

feat(node-experimental): Add missing re-exports

---

MIGRATION.md
packages/browser/src/index.bundle.tracing.replay.feedback.ts
packages/browser/src/index.bundle.tracing.replay.ts
packages/browser/src/index.bundle.tracing.ts
packages/core/src/tracing/idletransaction.ts
packages/core/src/tracing/index.ts
packages/core/src/tracing/sentrySpan.ts
packages/core/src/tracing/transaction.ts
packages/core/src/utils/spanUtils.ts
packages/core/test/lib/tracing/span.test.ts
packages/core/test/lib/tracing/spanstatus.test.ts
packages/core/test/lib/tracing/trace.test.ts
packages/core/test/lib/utils/getRootSpan.ts
packages/core/test/lib/utils/spanUtils.test.ts
packages/nextjs/src/edge/index.ts
packages/nextjs/src/index.types.ts
packages/node-experimental/test/helpers/createSpan.ts
packages/node/test/integrations/http.test.ts
packages/opentelemetry-node/test/spanprocessor.test.ts
packages/tracing-internal/src/exports/index.ts
packages/tracing-internal/test/browser/metrics/utils.test.ts
packages/tracing/src/index.ts
packages/tracing/test/idletransaction.test.ts
packages/tracing/test/integrations/apollo-nestjs.test.ts
packages/tracing/test/integrations/apollo.test.ts
packages/tracing/test/integrations/graphql.test.ts
packages/tracing/test/integrations/node/mongo.test.ts
packages/tracing/test/integrations/node/postgres.test.ts
packages/tracing/test/span.test.ts

And stop exporting it from packages other than core.

ref(core): Rename `Span` class to `SentrySpan`

---

packages/core/src/exports.ts
packages/node/test/onunhandledrejection.test.ts

Directly call these on `getCurrentScope()` instead.

ref(core): Skip hub in top level `captureXXX` methods

---

packages/browser/src/exports.ts
packages/bun/src/index.ts
packages/deno/src/index.ts
packages/node/src/index.ts
packages/serverless/src/index.ts

We missed exporting the top-level session APIs.

fix: Export session API

---

packages/node/src/integrations/anr/worker.ts

I've removed the `hub` global on the carrier in a recent PR, and noticed this leftover. Guess this is not used/covered by tests...? It should work with using `acs` as that should now always be set too (also for the default case), unless sentry is not initialized. But for type safety, the acs _may_ be undefined.

fx(node): Fix anr worker check

---

packages/node-experimental/src/index.ts
packages/node-experimental/src/sdk/api.ts
packages/node-experimental/src/sdk/init.ts
packages/node-experimental/src/utils/module.ts

These were imported from `@sentry/node` before.
Also moves the `createGetModuleFromFilename` utility over, which is needed for `defaultStackParser`.

feat(node-experimental): Move `defaultStackParser` & `getSentryRelease`

---

packages/core/src/scope.ts
packages/core/test/lib/prepareEvent.test.ts

In https://github.com/getsentry/sentry-javascript/pull/9801, we introduced a regression that if you pass a function as `captureContext` to capture methods, the returned scope is not used.
The cause for this was a confusion on my end, based on the slightly weird way this works in `scope.update(fn)` - we don't actually merge this or update the scope based on the return value of `fn`, but `fn` receives the `scope` as argument, does nothing with the return type of `fn` and just returns it - which we didn't use, because I assumed that `scope.update` would actually return the scope (also, the return type of it is `this` which is not correct there).
This PR changes this so that the returned scope of `fn` is actually merged with the scope, same as if you'd pass a `scope` directly - so this is …

fix(core): Fix scope capturing via `captureContext` function

---

packages/core/src/scope.ts
packages/core/test/lib/prepareEvent.test.ts
packages/core/test/lib/scope.test.ts

Backport to v7.
In https://github.com/getsentry/sentry-javascript/pull/9801, we introduced a regression that if you pass a function as `captureContext` to capture methods, the returned scope is not used.
The cause for this was a confusion on my end, based on the slightly weird way this works in `scope.update(fn)` - we don't actually merge this or update the scope based on the return value of `fn`, but `fn` receives the `scope` as argument, does nothing with the return type of `fn` and just returns it - which we didn't use, because I assumed that `scope.update` would actually return the scope (also, the return type of it is `this` which is not correct there).
This PR changes this so that the returned scope of `fn` is actually merged with the scope, same as if you'd pass a `scope` directly …

fix(core): Fix scope capturing via `captureContext` function (#10735)

---

packages/core/src/scope.ts
packages/core/test/lib/scope.test.ts

Noticed in the backport PR https://github.com/getsentry/sentry-javascript/actions/runs/7971156054/job/21760458423?pr=10737, where this failed, that we apparently lost some scope tests that used to only be in the hub package. This forwards-ports them to v8, and also fixes a case that was failing previously.

fix(core): Add lost scope tests & fix update case

---

dev-packages/node-integration-tests/suites/express/tracing-experimental/server.js
packages/node-experimental/src/index.ts
packages/node-experimental/src/integrations/http.ts
packages/node-experimental/src/sdk/handlers.ts
packages/node-experimental/src/sdk/handlers/errorHandler.ts
packages/node-experimental/src/sdk/init.ts
packages/node-experimental/test/sdk/handlers/errorHandler.test.ts

Also stop exporting `requestHandler`, as that should be handled bu the otel http instrumentation.
I also fixed the otel stuff to properly take care of sessions.

feat(node-experimental): Move `errorHandler`

---

packages/astro/src/index.types.ts
packages/browser/src/exports.ts
packages/browser/src/sdk.ts
packages/bun/src/index.ts
packages/bun/src/sdk.ts
packages/deno/src/index.ts
packages/deno/src/sdk.ts
packages/nextjs/src/index.types.ts
packages/node/src/index.ts
packages/node/src/sdk.ts
packages/remix/src/index.server.ts
packages/remix/src/index.types.ts
packages/serverless/src/awslambda.ts
packages/serverless/src/gcpfunction/index.ts
packages/serverless/src/index.ts
packages/sveltekit/src/index.types.ts
packages/sveltekit/src/server/index.ts
packages/vercel-edge/src/index.ts
packages/vercel-edge/src/sdk.ts

Removes deprecated `defaultIntegrations` export everywhere.

feat(v8): Remove defaultIntegrations deprecated export

---

packages/browser/src/integrations/globalhandlers.ts
packages/browser/src/stack-parsers.ts
packages/browser/test/unit/tracekit/misc.test.ts
packages/deno/test/__snapshots__/mod.test.ts.snap
packages/node/test/stacktrace.test.ts
packages/utils/src/anr.ts
packages/utils/src/index.ts
packages/utils/src/node-stack-trace.ts
packages/utils/src/stacktrace.ts
packages/utils/test/stacktrace.test.ts

This was previously opened as #5664 but closed as it was a breaking change. Now that we're getting ready to ship, v8 this is viable!

fix(stacktrace): Always use `?` for anonymous function name

---

packages/core/src/tracing/sentrySpan.ts
packages/tracing/test/span.test.ts
packages/types/src/span.ts

feat(v8): Remove deprecated `span.isSuccess` method

---

packages/node-experimental/src/cron/common.ts
packages/node-experimental/src/cron/cron.ts
packages/node-experimental/src/cron/index.ts
packages/node-experimental/src/cron/node-cron.ts
packages/node-experimental/src/cron/node-schedule.ts
packages/node-experimental/src/index.ts
packages/node-experimental/test/cron.test.ts

Pending on https://github.com/getsentry/sentry-javascript/pull/10741

feat(node-experimental): Move cron code over

---

dev-packages/browser-integration-tests/suites/integrations/Breadcrumbs/dom/click/test.ts
dev-packages/browser-integration-tests/suites/integrations/httpclient/fetch/simple/test.ts
dev-packages/browser-integration-tests/suites/public-api/startSpan/basic/subject.js
dev-packages/browser-integration-tests/suites/replay/errorResponse/test.ts

This is not a complete fix for all flaky integration tests, but it seems to resolve flakiness of a few tests that fail very frequently.

fix(test): Fix flaky browser integration tests.

---

packages/core/src/tracing/span.ts
packages/core/src/tracing/transaction.ts
packages/tracing-internal/src/browser/browserTracingIntegration.ts
packages/tracing/test/integrations/apollo-nestjs.test.ts
packages/tracing/test/integrations/apollo.test.ts
packages/tracing/test/integrations/graphql.test.ts
packages/tracing/test/integrations/node/mongo.test.ts
packages/tracing/test/integrations/node/postgres.test.ts
packages/tracing/test/span.test.ts
packages/types/src/span.ts
packages/types/src/transaction.ts

This includes two fixes that should be backported:
* ref: Make span types more robust #10660
* fix(tracing): Guard against missing window.location #10659

meta: Backport fixes to v7

---

dev-packages/node-integration-tests/suites/express/multiple-routers/common-infix-parameterized/server.ts
dev-packages/node-integration-tests/suites/express/multiple-routers/common-infix/server.ts
dev-packages/node-integration-tests/suites/express/multiple-routers/common-prefix-parameterized-reverse/server.ts
dev-packages/node-integration-tests/suites/express/multiple-routers/common-prefix-parameterized/server.ts
dev-packages/node-integration-tests/suites/express/multiple-routers/common-prefix-same-length-parameterized copy/server.ts
dev-packages/node-integration-tests/suites/express/multiple-routers/common-prefix-same-length-parameterized/server.ts
dev-packages/node-integration-tests/suites/express/multiple-routers/common-prefix/server.ts
dev-packages/node-integration-tests/suites/express/multiple-routers/complex-router/server.ts
dev-packages/node-integration-tests/suites/express/multiple-routers/middle-layer-parameterized/server.ts
dev-packages/node-integration-tests/suites/express/sentry-trace/baggage-header-out/server.ts
dev-packages/node-integration-tests/suites/express/sentry-trace/baggage-other-vendors-with-sentry-entries/server.ts
dev-packages/node-integration-tests/suites/express/sentry-trace/baggage-other-vendors/server.ts
dev-packages/node-integration-tests/suites/express/sentry-trace/baggage-transaction-name/server.ts
dev-packages/node-integration-tests/suites/express/sentry-trace/server.ts
dev-packages/node-integration-tests/suites/express/tracing/server.ts
dev-packages/node-integration-tests/suites/tracing-new/tracePropagationTargets/scenario.ts
dev-packages/node-integration-tests/suites/tracing/apollo-graphql/scenario.ts
dev-packages/node-integration-tests/suites/tracing/prisma-orm/scenario.ts
dev-packages/node-integration-tests/suites/tracing/tracePropagationTargets/scenario.ts

This PR migrates the Http integration in node-integration-tests (`new Sentry.Integrations.Http` gets `Sentry.httpIntegration`). I also exchanged `Tracing` to `Sentry`.

ref(node-integration-tests): Migrate to new Http integration

---

packages/core/src/tracing/sentrySpan.ts
packages/opentelemetry-node/src/utils/spanData.ts
packages/types/src/span.ts

Removes `span.origin` as a getter.

feat(v8): Remove span.origin

---

.github/workflows/auto-release.yml
.github/workflows/release.yml

This PR updates our prepare release workflows on the `v7` branch to use the craft config from the merge target branch (which for v7 releases should always be `v7`) instead of the config from the default branch (`develop` in our case). 
Once this PR and https://github.com/getsentry/publish/pull/3467 are merged, we can start customizing the craft config on both, `develop` and `v7` to our convenience.
ref https://github.com/getsentry/publish/issues/3441

chore(publish): [v7] Use craft config from merge target branch for release preparation

---

dev-packages/browser-integration-tests/suites/public-api/debug/test.ts
dev-packages/browser-integration-tests/suites/replay/captureReplay/test.ts
dev-packages/browser-integration-tests/suites/replay/captureReplayFromReplayPackage/test.ts
dev-packages/browser-integration-tests/utils/replayEventTemplates.ts
packages/angular-ivy/src/sdk.ts
packages/angular/src/sdk.ts
packages/angular/test/sdk.test.ts
packages/browser/src/exports.ts
packages/browser/src/integrations/browserapierrors.ts
packages/browser/src/integrations/index.ts
packages/browser/src/sdk.ts
packages/replay/test/fixtures/error.ts
packages/replay/test/fixtures/transaction.ts

Resolves https://github.com/getsentry/sentry-javascript/issues/8838
- Removes `TryCatch` integration class export
- Updates angular to refer to browserApiErrorsIntegration by name instead of using `TryCatch`

feat(v8/browser): Rename TryCatch integration to `browserApiErrorsIntegration`

---

packages/core/test/lib/tracing/trace.test.ts
packages/opentelemetry/src/contextManager.ts
packages/opentelemetry/src/trace.ts
packages/opentelemetry/src/types.ts
packages/opentelemetry/src/utils/contextData.ts
packages/opentelemetry/test/trace.test.ts

This aligns the options for `startSpan` in otel with the core ones. Only the `kind` is there in addition for now (we may want to remove this, let's see).
Especially, this also adds the ability to pass a `scope` there and pick up the correct context & span to continue, as well as adding tests for the options.

feat(opentelemetry): Align span options with core span options

---

packages/astro/src/integration/snippets.ts
packages/astro/test/integration/snippets.test.ts

Swaps the class implementation with the new function

ref(astro): Remove deprecated Replay and BrowserTracing

---

dev-packages/e2e-tests/test-applications/debug-id-sourcemaps/package.json
packages/core/src/tracing/sentrySpan.ts
packages/tracing/test/span.test.ts
packages/types/src/span.ts

feat(v8): Remove span.toTraceparent method

---

packages/remix/package.json
packages/remix/src/utils/instrumentServer.ts
packages/remix/src/utils/serverAdapters/express.ts
packages/remix/src/utils/vendor/response.ts
packages/remix/src/utils/vendor/types.ts
yarn.lock

Backports #10479 to v7 branch
Original PR Description:
> Fixes: https://github.com/getsentry/sentry-javascript/issues/10349
> Related: https://github.com/getsentry/sentry-javascript/issues/5860
> Related: https://github.com/getsentry/sentry-javascript/pull/10458
> 
> Removes dynamic loading of `react-router-dom` and makes `@remix-run/router` a peer dependency.
> 
> We don't need to dynamically load `react-router-dom` as our TypeScript version is now up-to-date.

ref(remix): Make `@remix-run/router` a dependency (v7)

---

.github/workflows/build.yml
dev-packages/browser-integration-tests/playwright.config.ts

Collect playwright traces in CI for failures to view in the playwright trace viewer: https://playwright.dev/docs/trace-viewer

ci: Upload playwright traces

---

packages/core/src/hub.ts
packages/core/src/tracing/hubextensions.ts
packages/node-experimental/src/sdk/hub.ts
packages/opentelemetry/src/custom/getCurrentHub.ts
packages/types/src/hub.ts

feat(v8): Remove deprecated `traceHeaders` method

---

packages/bun/src/index.ts
packages/core/src/currentScopes.ts
packages/core/src/index.ts
packages/deno/src/index.ts
packages/node/src/index.ts
packages/opentelemetry/src/asyncContextStrategy.ts
packages/remix/src/index.server.ts
packages/serverless/src/index.ts
packages/sveltekit/src/server/index.ts
packages/vercel-edge/src/index.ts

feat(v8): Remove deprecated runWithAsyncContext API

---

packages/vercel-edge/src/integrations/wintercg-fetch.ts

Right now it's not possible to use it as:
```js
new Sentry.Integrations.WinterCGFetch({
shouldCreateSpanForRequest: (url) => {
return !url.startsWith(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/rest`);
}
})
```
due to `breadcrubs` not being marked as optional. Instead of changing it to such, reuse already existing `Options` interface to keep it in sync with the integration itself.

fix: Make breadcrumbs option optional in WinterCGFetch integration

---

packages/node-experimental/src/integrations/anr/index.ts

Ref #10046
Since v8 increases our minimum supported node version, we no longer need to conditionally `dynamicRequire` the `worker_threads` module.

fix(node): import `worker_threads` and fix node v14 types

---

packages/core/src/tracing/trace.ts
packages/core/src/tracing/transaction.ts
packages/core/test/lib/tracing/trace.test.ts
packages/node/test/integrations/undici.test.ts
packages/types/src/startSpanOptions.ts

This will ensure a span is sent as a transaction to Sentry.
This only implements this option for the core implementation, not yet for OTEL - that is a follow up here: https://github.com/getsentry/sentry-javascript/pull/10807

feat(core): Allow to pass `forceTransaction` to `startSpan()` APIs

---

packages/core/src/tracing/trace.ts
packages/core/src/tracing/transaction.ts
packages/core/test/lib/tracing/trace.test.ts
packages/types/src/startSpanOptions.ts

This will ensure a span is sent as a transaction to Sentry.
This only implements this option for the core implementation, not yet for OTEL - that is a follow up here:
https://github.com/getsentry/sentry-javascript/pull/10807
This is a backport to v7 of https://github.com/getsentry/sentry-javascript/pull/10749

feat(core): Allow to pass `forceTransaction` to `startSpan()` APIs (backport)

---

CHANGELOG.md

meta(changelog): Add changelog for v7.103.0

---

nx.json
packages/angular-ivy/package.json
packages/angular/package.json
packages/deno/package.json

After this annoying me for quite some time, I finally figured out what the problem with our build was - we had our nx cache outputs wrong. This lead to conflicts when caches were restored etc.
Now, this should be more narrow & correct in what it caches per step, leading to caching actually working (hopefully..)

build: Fix nx cache outputs

---

dev-packages/node-integration-tests/suites/public-api/LocalVariables/local-variables-caught.js
dev-packages/node-integration-tests/suites/public-api/LocalVariables/local-variables-caught.mjs
dev-packages/node-integration-tests/suites/public-api/LocalVariables/local-variables-memory-test.js
dev-packages/node-integration-tests/suites/public-api/LocalVariables/local-variables.js
dev-packages/node-integration-tests/suites/public-api/LocalVariables/no-local-variables.js
dev-packages/node-integration-tests/suites/public-api/LocalVariables/test.ts
packages/node-experimental/src/integrations/local-variables/local-variables-async.ts
packages/node-experimental/src/integrations/local-variables/local-variables-sync.ts
packages/node/src/integrations/local-variables/local-variables-async.ts
packages/node/src/integrations/local-variables/local-variables-sync.ts

We previously didn't record local local variables with falsy values because we checked for truthiness instead of definedness when unrolling and serializing the variable values. This PR changes how we check for and extract variable properties to record
- falsy values (`0`, `''`, `false`)
- `null`
- `undefined`
Fixes implementations in `node` and `node-experimental`
fixes https://github.com/getsentry/sentry-javascript/issues/10815

fix(node): Record local variables with falsy values, `null` and `undefined`

---

.github/workflows/build.yml
dev-packages/e2e-tests/test-applications/create-remix-app-v2/app/entry.client.tsx
dev-packages/e2e-tests/test-applications/create-remix-app-v2/app/entry.server.tsx
dev-packages/e2e-tests/test-applications/create-remix-app-v2/remix.config.js
dev-packages/e2e-tests/test-applications/create-remix-app-v2/tests/behaviour-client.test.ts
dev-packages/e2e-tests/test-applications/create-remix-app/app/entry.client.tsx
dev-packages/e2e-tests/test-applications/create-remix-app/app/entry.server.tsx
dev-packages/e2e-tests/test-applications/create-remix-app/tests/behaviour-client.test.ts

Fixes and re-enables flaky Remix E2E tests for v7 branch.
Ref: https://github.com/getsentry/sentry-javascript/pull/10290

test(remix): Re-enable Remix E2E tests on v7

---

dev-packages/browser-integration-tests/suites/replay/extendNetworkBreadcrumbs/xhr/captureRequestSize/test.ts

[maybe] fixes this flakey test

test(integration): Fix flakey test `replay/extendNetworkBreadcrumbs/xhr/captureRequestSize`

---

packages/types/src/attachment.ts

- add docstring and comments for all fields
- make attachmentType type more specific
ref this discord thread https://discord.com/channels/621778831602221064/1212134889651044352

fix(types): Improve attachment type

---

packages/opentelemetry/src/trace.ts
packages/opentelemetry/test/trace.test.ts

This implements `forceTransaction` for otel/node.

feat(opentelemetry): Support `forceTransaction` in OTEL

---

MIGRATION.md
packages/core/src/integrations/inboundfilters.ts
packages/core/test/lib/integrations/inboundfilters.test.ts

This PR removes the `ignoreTransactions` default values which were all patterns trying to identify health check transactions.
We remove these because:
- We now have server-side inbound filters that are configurable in the Sentry UI
- Having two filters (SDK and Sentry backend) is more than unintuitive for users
- The patterns between the SDK and the Sentry backend filters were slightly different
- There's no other SDK that has client-side health check transaction filtering
- There simply is no safe way to filter such transactions without dropping false positives. This ofc also applies to the server-side filter but it's better to have this questionable heuristic only in one place than two.
Implementation note: Decided to remove the entire defaults array b/c there's no point in keeping …

feat(core): Remove health check transaction filters

---

packages/node-experimental/test/integration/transactions.test.ts
packages/opentelemetry/src/semanticAttributes.ts
packages/opentelemetry/src/spanExporter.ts
packages/opentelemetry/src/trace.ts
packages/opentelemetry/src/utils/addOriginToSpan.ts
packages/opentelemetry/test/integration/transactions.test.ts
packages/opentelemetry/test/trace.test.ts

Also stop clearing out sentry attributes, we don't actually want that (except for the parent sampled stuff for now).

ref(node): Align semantic attribute handling

---

.github/workflows/build.yml
nx.json

For whatever reason, builds are weirdly failing now on CI, most probably due to caching issues etc... let's see if this can fix this, possibly...

build(ci): Small fixes to hopefully resolve caching issues

---

.github/workflows/build.yml
nx.json
packages/core/src/metrics/metric-summary.ts
packages/core/src/scope.ts
packages/core/src/tracing/getActiveSpan.ts
packages/core/src/tracing/index.ts
packages/core/src/tracing/sentrySpan.ts
packages/core/src/tracing/trace.ts
packages/core/src/tracing/transaction.ts
packages/core/src/tracing/utils.ts
packages/types/src/scope.ts

This also resolves the circular dependencies we have in core right now by moving utils around a bit.

feat(core): Remove deprecated `scope.applyToEvent()` method

---

nx.json

Turns out you cannout use `{xx,yy}` glob syntax for cache outputs, which broke everything. oops....

build: Fix nx cache for real

---

MIGRATION.md
packages/astro/src/server/middleware.ts
packages/astro/test/server/middleware.test.ts

This removes usage of deprecated options to `startSpan`, and removes the `trackHeaders` option to the astro middleware in favor of using the general request data integration that should pick this up if put on the scope as SDK processing metadata.

ref(astro): Put request as SDK processing metadata instead of span data

---

dev-packages/browser-integration-tests/suites/manual-client/skip-init-browser-extension/init.js
dev-packages/browser-integration-tests/suites/manual-client/skip-init-browser-extension/test.ts
dev-packages/browser-integration-tests/suites/manual-client/skip-init-chrome-extension/init.js
dev-packages/browser-integration-tests/suites/manual-client/skip-init-chrome-extension/test.ts
packages/astro/src/client/sdk.ts
packages/astro/test/client/sdk.test.ts
packages/browser/src/sdk.ts
packages/browser/test/unit/sdk.test.ts

Prevents initialization inside chrome.* and  browser.* extension environments.
Also refactored init() in browser because of eslint warning about too much complexity.
Fixes https://github.com/getsentry/sentry-javascript/issues/10632

feat(browser): Prevent initialization in browser extensions

---

packages/types/src/span.ts

To align this with OTEL types.

ref(core): Allow `number` as span `traceFlag`

---

packages/bun/test/integrations/bunserver.test.ts
packages/core/src/tracing/sentrySpan.ts
packages/core/test/lib/tracing/errors.test.ts
packages/core/test/lib/tracing/idletransaction.test.ts
packages/core/test/lib/tracing/trace.test.ts
packages/core/test/lib/utils/spanUtils.test.ts
packages/node/test/handlers.test.ts
packages/node/test/integrations/undici.test.ts
packages/opentelemetry-node/test/spanprocessor.test.ts
packages/opentelemetry/src/spanExporter.ts
packages/sveltekit/src/client/load.ts
packages/sveltekit/src/server/handle.ts
packages/sveltekit/src/server/load.ts
packages/sveltekit/test/client/load.test.ts
packages/sveltekit/test/server/handle.test.ts
packages/sveltekit/test/server/load.test.ts
packages/types/src/span.ts

This removes the public field to get/set `status` on a span/transaction.

ref(core): Remove `status` field from Span

---

packages/node-experimental/src/integrations/anr/index.ts
packages/node-experimental/src/integrations/spotlight.ts
packages/node-experimental/src/integrations/tracing/hapi/types.ts
packages/node-experimental/src/proxy/helpers.ts
packages/node-experimental/src/proxy/index.ts
packages/node-experimental/src/transports/http-module.ts
packages/node-experimental/src/transports/http.ts

Now we will no longer be supporting Node v8, these imports are no longer required

feat(node): Remove unnecessary URL imports

---

MIGRATION.md
docs/migration/v4-to-v5_v6.md
docs/migration/v6-to-v7.md

This is an attempt to restructure our migration docs in preparation for the first alpha.

docs(v8): Restructure migration docs

---

packages/utils/src/aggregate-errors.ts
packages/utils/test/aggregate-errors.test.ts

When Sentry started supporting the idea of exception groups, two changes happened. In the SDK, we adapted our logic for handling linked errors to also handle `AggregateError`s. And in our ingest pipeline, we began looking for an `is_exception_group` flag on the last entry in `event.exception.values; when we found it, we'd then ignore that entry when grouping and titling events, under the assumption that it was just a container and therefore wasn't meaningful.
When it came to instances of `AggregateError`, this worked great. For linked errors, however, this caused us to focus on the `cause` error rather than the error which was actually caught, with the result that it both threw off grouping and made for some very unhelpful titling of issues. (See the screenshot below, in which the first …

fix(processing): Only mark aggregate errors as exception groups

---

packages/replay-canvas/src/canvas.ts

`errorHandler` for `CanvasManager` was added in the latest rrweb, but was not configured in our integration.

fix(replay): Add `errorHandler` for replayCanvas integration

---

MIGRATION.md
packages/profiling-node/README.md
packages/profiling-node/src/index.ts
packages/profiling-node/src/integration.ts
packages/profiling-node/test/hubextensions.hub.test.ts
packages/profiling-node/test/index.test.ts
packages/profiling-node/test/integration.test.ts

Also noticed that we forgot this integration...! This is a backport to v7, we need to also rewrite this on v8.

feat(profiling-node): [v7] Expose `nodeProfilingIntegration`

---

packages/utils/src/aggregate-errors.ts
packages/utils/test/aggregate-errors.test.ts

This is a backport of https://github.com/getsentry/sentry-javascript/pull/10850
ref: https://github.com/getsentry/sentry-javascript/issues/10865

fix(processing): [v7] Only mark aggregate errors as exception groups

---

packages/core/src/integrations/inboundfilters.ts
packages/core/test/lib/integrations/inboundfilters.test.ts

We want to filter out `ResizeObserver` error since they are not actionable and have no stacktrace and break transaction status. ref https://stackoverflow.com/a/77680580/1139707
Also, I added to filter out undefined errors - here are two events to Sentry to represent this.
undefined: 
https://sentry.sentry.io/issues/3611187513/events/46ed8c398c234ff89baee87c5c341844/
ResizeObserver: 
https://sentry.sentry.io/issues/3611187513/events/48f25ea9dfbf4bd0b84a18982ee73362/

feat: Ignore ResizeObserver and undefined error

---

MIGRATION.md
packages/profiling-node/README.md
packages/profiling-node/src/index.ts
packages/profiling-node/src/integration.ts
packages/profiling-node/test/hubextensions.hub.test.ts
packages/profiling-node/test/index.test.ts
packages/profiling-node/test/integration.test.ts

@JonasBa when you got some time, could you look into actually rewriting this to the new style? Right now a lot of the tests depend on the non-hook based version etc. and I'm not 100% clear on what can/cannot be removed there 😅 
The end result should be just having a single `nodeProfilingIntegration` that receives the client in `setup(client)` and sets up hooks etc in there!

feat(profiling-node): Expose `nodeProfilingIntegration`

---

packages/astro/src/index.server.ts
packages/bun/src/index.ts
packages/node-experimental/src/index.ts
packages/node/src/index.ts
packages/remix/src/index.server.ts
packages/serverless/src/index.ts
packages/sveltekit/src/server/index.ts
packages/vercel-edge/src/index.ts

We forgot to do that, apparently :grimace:

feat: Ensure `withActiveSpan` is exported everywhere

---

packages/astro/src/index.server.ts
packages/browser/src/exports.ts
packages/bun/src/index.ts
packages/node/src/index.ts
packages/remix/src/index.server.ts
packages/serverless/src/index.ts
packages/sveltekit/src/server/index.ts
packages/vercel-edge/src/index.ts

We forgot to re-export this everywhere, oops.

feat: Ensure `withActiveSpan` is exported everywhere [v7]

---

CHANGELOG.md

Includes something we forgot to re-export before...

meta(changelog): Update changelog for v7.105.0

---

packages/deno/package.json
packages/deno/src/index.ts
packages/deno/src/integrations/breadcrumbs.ts
packages/deno/src/sdk.ts

Adds the breadcrumbsIntegration (without xhr, dom, history) to deno without importing that from browser.

ref(deno): Remove `@sentry/browser` dependency from `@sentry/deno`

---

CHANGELOG.md

To avoid conflicts we have right now here: https://github.com/getsentry/sentry-javascript/pull/10881

meta(gitflow): Merge changelog from master into develop

---

packages/ember/addon/instance-initializers/sentry-performance.ts

Let's see if this actually fixes this issue: https://github.com/getsentry/sentry-javascript/issues/10566 🤔 Maybe the internal bundler is thrown off by the fact that we lazy load browser tracing further below, and only includes certain things in `Sentry` on top, not sure...

ref(ember): Avoid namespace import to hopefully resolve minification issue

---

dev-packages/browser-integration-tests/suites/integrations/Breadcrumbs/dom/init.js
dev-packages/browser-integration-tests/suites/integrations/Breadcrumbs/fetch/init.js
dev-packages/browser-integration-tests/suites/integrations/Breadcrumbs/xhr/init.js
dev-packages/browser-integration-tests/suites/manual-client/browser-context/init.js
packages/browser/src/exports.ts
packages/browser/src/index.bundle.base.ts
packages/browser/src/index.ts
packages/browser/src/integrations/breadcrumbs.ts
packages/browser/src/integrations/index.ts
packages/browser/test/unit/index.test.ts
packages/browser/test/unit/integrations/breadcrumbs.test.ts
packages/bun/src/index.ts
packages/core/src/index.ts
packages/core/src/integrations/inboundfilters.ts
packages/core/src/integrations/index.ts
packages/core/src/integrations/linkederrors.ts
packages/core/test/lib/integrations/inboundfilters.test.ts
packages/deno/src/index.ts
packages/node/src/index.ts
packages/node/src/integrations/contextlines.ts
packages/node/src/integrations/index.ts
packages/node/test/index.test.ts
packages/node/test/integrations/contextlines.test.ts
packages/vercel-edge/src/index.ts

Deletes `FunctionToString`, `Breadcrumbs`, `InboundFilters`and `LinkedErrors`
ref https://github.com/getsentry/sentry-javascript/issues/8844

ref(integrations): Delete deprecated class integrations

---

scripts/node-unit-tests.ts

Noticed we seem to have forgotten this, we can skip this there (this runs as browser unit test).

test(replay): Ensure we don't run replay-worker tests as node unit tests

---

packages/browser/src/exports.ts
packages/browser/src/index.bundle.tracing.replay.feedback.ts
packages/browser/src/index.bundle.tracing.replay.ts
packages/browser/src/index.bundle.tracing.ts
packages/browser/src/index.ts

I figured we don't actually need to expor these (e.g. `startSpan`, etc.) in non-performance CDN bundles.
We can think about providing shims for these, but honestly not so sure 🤔

feat(browser): Exclude span exports from non-performance CDN bundles

---

packages/node-experimental/test/integration/transactions.test.ts
packages/opentelemetry/src/constants.ts
packages/opentelemetry/src/index.ts
packages/opentelemetry/src/propagator.ts
packages/opentelemetry/src/sampler.ts
packages/opentelemetry/src/utils/contextData.ts
packages/opentelemetry/test/integration/transactions.test.ts
packages/opentelemetry/test/propagator.test.ts
packages/opentelemetry/test/trace.test.ts

This updates the propagation handling in OTEL to the following:
1. If there is an active (local) span, we always pick up propagation context/DSC data from it.
2. Else, we try to pick it from the current scope
3. If we can't find this (e.g. a detached otel context is used), we try to pick it from the remote span context
4. Finally, if that also fails, we have no DSC
Closes https://github.com/getsentry/sentry-javascript/issues/10899

fix(opentelemetry): Ensure DSC propagation works correctly

---

packages/sveltekit/src/vite/sourceMaps.ts

chore(sveltekit): Fix punctuation in a console.log

---

packages/node-experimental/src/sdk/init.ts
packages/node-experimental/src/types.ts
packages/node-experimental/test/sdk/init.test.ts
packages/opentelemetry/src/contextManager.ts
packages/opentelemetry/src/index.ts
packages/opentelemetry/src/propagator.ts
packages/opentelemetry/src/sampler.ts
packages/opentelemetry/src/spanProcessor.ts
packages/opentelemetry/src/utils/setupCheck.ts
packages/opentelemetry/test/helpers/mockSdkInit.ts
packages/opentelemetry/test/utils/setupCheck.test.ts

Also warn if there is an incomplete setup, to ensure users notice if stuff is breaking.
I do this by just keeping a set of things that were created, which is not perfect but IMHO good enough to notify users if they forgot to setup a specific thing...

feat(node): Allow to configure `skipOpenTelemetrySetup`

---

.github/workflows/build.yml

Let's see if that fixes stuff...

build(profiling-node): Fix profiling-node tarball creation & caching

---

dev-packages/browser-integration-tests/suites/public-api/startSpan/basic/test.ts
dev-packages/browser-integration-tests/suites/public-api/startTransaction/basic_usage/test.ts
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/http-timings/test.ts
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/long-tasks-disabled/test.ts
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/long-tasks-enabled/test.ts
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/pageloadWithHeartbeatTimeout/test.ts
dev-packages/browser-integration-tests/suites/tracing/metrics/pageload-browser-spans/test.ts
dev-packages/browser-integration-tests/suites/tracing/metrics/pageload-resource-spans/test.ts
dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals-fid/test.ts
dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals-fp-fcp/test.ts
dev-packages/browser-integration-tests/suites/tracing/request/fetch/test.ts
dev-packages/browser-integration-tests/suites/tracing/request/xhr/test.ts
dev-packages/e2e-tests/test-applications/angular-17/event-proxy-server.ts
dev-packages/e2e-tests/test-applications/node-experimental-fastify-app/event-proxy-server.ts
dev-packages/e2e-tests/test-applications/sveltekit-2/event-proxy-server.ts
dev-packages/e2e-tests/test-applications/sveltekit/event-proxy-server.ts
dev-packages/e2e-tests/test-applications/vue-3/event-proxy-server.ts
packages/core/src/tracing/transaction.ts
packages/core/src/utils/prepareEvent.ts
packages/core/test/lib/base.test.ts
packages/core/test/lib/tracing/trace.test.ts
packages/ember/tests/helpers/utils.ts
packages/node-experimental/test/integration/transactions.test.ts
packages/node/test/handlers.test.ts
packages/node/test/performance.test.ts
packages/opentelemetry/test/integration/transactions.test.ts
packages/opentelemetry/test/trace.test.ts
packages/svelte/test/performance.test.ts
packages/types/src/event.ts
packages/types/src/index.ts

Previously, we passed the span instance, which is a) tricky because it keeps references etc, and b) doesn't work with the new span schema anyhow (because nothing is readable off the spans).
This also means we can get rid of the `SerializedEvent` again, as this is now just the regular `Event` again.

feat(core): Use serialized spans in transaction event

---

packages/bun/src/integrations/bunserver.ts
packages/react/src/profiler.tsx
packages/react/test/profiler.test.tsx
packages/remix/src/client/performance.tsx
packages/tracing-internal/src/browser/browserTracingIntegration.ts
packages/tracing-internal/src/node/integrations/prisma.ts
packages/vue/src/tracing.ts

Mostly, changes `origin` to be set as an attribute, plus some further small adjustments.
In one case, we replaced `headers` data with a flattened `headers.xxx` object (astro).
In the case of bun, I also changed it to keep the request on the isolation scope (vs. the span).

ref: Refactor some deprecated `startSpan` options

---

packages/nextjs/src/client/index.ts
packages/nextjs/src/client/tunnelRoute.ts

Found while working through ESM issues in #10833.
For whatever reason this passes all the integration tests until ESM is used 🤯

fix(nextjs): Client code should not use Node `global`

---

packages/angular/test/tracing.test.ts
packages/core/src/tracing/sentrySpan.ts
packages/core/src/tracing/transaction.ts
packages/core/src/utils/spanUtils.ts
packages/core/test/lib/utils/spanUtils.test.ts
packages/opentelemetry/test/helpers/createSpan.ts
packages/opentelemetry/test/utils/spanToJSON.test.ts
packages/types/src/event.ts
packages/vue/test/router.test.ts

This is an important step towards aligning OTEL & Sentry Spans 🎉 You can see that the `Span` interface is now aligned enough that it accepts an OTEL span.

feat(core): Update `spanToJSON` to handle OTEL spans

---

packages/node-experimental/src/index.ts

These exports were lost on the migration from the experimental package

fix(node): Add missing core re-exports

---

packages/astro/src/index.server.ts
packages/browser/src/index.bundle.tracing.replay.feedback.ts
packages/browser/src/index.bundle.tracing.replay.ts
packages/browser/src/index.bundle.tracing.ts
packages/browser/src/index.ts
packages/bun/src/index.ts
packages/core/src/tracing/index.ts
packages/core/src/tracing/transaction.ts
packages/core/src/tracing/utils.ts
packages/core/test/lib/tracing/trace.test.ts
packages/node-experimental/src/index.ts
packages/node/src/index.ts
packages/remix/src/index.server.ts
packages/serverless/src/index.ts
packages/vercel-edge/src/index.ts

This can be used instead of `spanRecorder` going forward.

feat: Export `getSpanDescendants()` everywhere

---

packages/core/src/baseclient.ts
packages/core/src/tracing/hubextensions.ts
packages/core/src/tracing/idleSpan.ts
packages/core/src/tracing/index.ts
packages/core/src/tracing/sentrySpan.ts
packages/core/src/tracing/utils.ts
packages/core/test/lib/tracing/idleSpan.test.ts
packages/core/test/lib/tracing/trace.test.ts
packages/opentelemetry/src/custom/transaction.ts
packages/opentelemetry/src/spanProcessor.ts
packages/types/src/client.ts

For now, this does not actually _use_ this anywhere.
The idle span works _mostly_ like the idle transaction, but there are small differences:
1. I replaced the heartbeat with simply waiting for 15s (instead of 3x5s) after the last span was started. IMHO semantically this is good enough, and makes it easier to reason about this? LMK if I am missing something there. 
2. This means that the idle span ends when either:
a. No span was created for 1s
b. The last time a span was created was 15s ago
c. 30s passed (final timeout)
3. Instead of the `delayAutoFinishUntilSignal` we used before for e.g. Next.js streaming pages, we now have `disableAutoFinish`, together with `client.emit('idleSpanEnableAutoFinish', idleSpan)`
4. Idle spans are always on the scope (we never used it without this setting) …

feat(core): Implement `startIdleSpan`

---

packages/core/test/lib/transports/base.test.ts
packages/types/src/attachment.ts
packages/types/src/envelope.ts

`Attachment.attachmentType` was changed to use a string union. The `attachment_type` header property should match so I added an extra type for this.

fix(types): Add `AttachmentType` and use for envelope `attachment_type` property

---

packages/core/src/baseclient.ts
packages/core/src/metrics/aggregator.ts
packages/core/src/metrics/browser-aggregator.ts
packages/core/src/metrics/envelope.ts
packages/core/src/metrics/exports-default.ts
packages/core/src/metrics/exports.ts
packages/types/src/client.ts

This PR adds the ability to override the client used for metrics rather than being tied to using the single client `getClient()` returns.
```ts
Sentry.metrics.increment('counter', 1, { client });
```
It also adds a `getMetricsAggregatorForClient` exported function which is required so the Electron SDK can access the current aggregator.
`sendEnvelope` was added to the `Client` type so that all usages of `BaseClient<ClientOptions>` could be replaced with `Client`.

feat(core): Allow metrics aggregator per client

---

packages/core/src/tracing/sentrySpan.ts
packages/tracing-internal/src/browser/metrics/index.ts
packages/tracing-internal/src/browser/metrics/utils.ts
packages/tracing-internal/test/browser/metrics/index.test.ts
packages/tracing-internal/test/browser/metrics/utils.test.ts

This rewrites browser metrics to:
1. Accept spans instead of transactions
2. Use the new performance APIs instead of the old ones
The only thing I left for now is the tags, which we can get rid of separately: https://github.com/getsentry/sentry-javascript/pull/10823
Part of https://github.com/getsentry/sentry-javascript/issues/10900

ref(browser): Update browser metrics to avoid deprecations

---

packages/node-experimental/src/integrations/http.ts
packages/node/src/integrations/http.ts

- [ ✔️] If you've added code that should be tested, please add tests.
- [✔️ ] Ensure your code lints and the test suite passes (`yarn lint`) & (`yarn test`).
Fixes https://github.com/getsentry/sentry-javascript/issues/9211

feat(node): Rephrase wording in http integration JSDoc

---

packages/svelte/src/performance.ts

ref https://github.com/getsentry/sentry-javascript/issues/10900

ref(svelte): Remove `startChild` deprecations

---

packages/node-experimental/src/sdk/client.ts
packages/node-experimental/src/sdk/hub.ts
packages/node-experimental/src/sdk/initOtel.ts
packages/node-experimental/test/integration/transactions.test.ts
packages/node-experimental/test/sdk/client.test.ts

The SDK is now called `@sentry/node`!

fix(node): Correct SDK name

---

packages/node/src/integrations/undici/index.ts
packages/node/src/integrations/undici/types.ts

fix(node): support undici headers as strings or arrays

---

packages/nextjs/src/client/tunnelRoute.ts
packages/nextjs/src/config/withSentryConfig.ts
packages/nextjs/test/utils/tunnelRoute.test.ts

Fixes https://github.com/getsentry/sentry-javascript/issues/10948
The new Hybrid Cloud DSNs are incompatible with the `tunnelRoute` option. This PR adds some extra matching to support the new DSNs including the region code.
It is paramount that we check for the pattern of the passed query params in the Next.js rewrite matcher to avoid any sort of SSRF.

feat(nextjs/v7): Support Hybrid Cloud DSNs with `tunnelRoute` option

---

packages/nextjs/src/client/tunnelRoute.ts
packages/nextjs/src/config/withSentryConfig.ts
packages/nextjs/test/utils/tunnelRoute.test.ts

The new Hybrid Cloud DSNs are incompatible with the tunnelRoute option. This PR adds some extra matching to support the new DSNs including the region code.
Forward port of https://github.com/getsentry/sentry-javascript/pull/10958

feat(nextjs): Support Hybrid Cloud DSNs with `tunnelRoute` option

---

dev-packages/browser-integration-tests/suites/tracing/metrics/handlers-lcp/test.ts
dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals-cls/test.ts
dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals-lcp/test.ts
packages/tracing-internal/src/browser/metrics/index.ts

Extracted this out from https://github.com/getsentry/sentry-javascript/pull/10808, as this is a bit more impactful, possibly.

ref(browser): Store browser metrics as attributes instead of tags

---

CHANGELOG.md
packages/browser/src/stack-parsers.ts
packages/core/src/scope.ts
packages/core/test/lib/transports/base.test.ts
packages/ember/addon/instance-initializers/sentry-performance.ts
packages/nextjs/src/client/rewriteFramesIntegration.ts
packages/nextjs/src/client/tunnelRoute.ts
packages/nextjs/src/server/rewriteFramesIntegration.ts
packages/node/src/integrations/undici/index.ts
packages/node/src/integrations/undici/types.ts
packages/sveltekit/src/vite/sourceMaps.ts
packages/types/src/attachment.ts
packages/types/src/envelope.ts
packages/types/src/scope.ts
packages/utils/src/vendor/supportsHistory.ts

resolves https://github.com/getsentry/sentry-javascript/issues/10876
also includes change to undeprecate `setTransactionName`.

chore: Backport Release for `7.106.0`

---

packages/core/src/tracing/sentrySpan.ts
packages/core/src/tracing/transaction.ts
packages/core/src/utils/spanUtils.ts
packages/profiling-node/test/hubextensions.test.ts
packages/types/src/span.ts
packages/types/src/transaction.ts

We've refactored all usage away, now we can actually get rid of the tags on the span themselves.

feat: Remove tags from spans & transactions

---

packages/astro/src/index.server.ts
packages/node-experimental/src/index.ts

Unblocks converting more packages to using OpenTelemetry.

fix(node): Export spotlightIntegration from OTEL node

---

MIGRATION.md
packages/sveltekit/src/vite/sentryVitePlugins.ts
packages/sveltekit/test/vite/sentrySvelteKitPlugins.test.ts

As discussed with @lforst last week, we decided to provide an escape hatch to the reduced (but therefore version-agnostic) Vite plugin option API in the SvelteKit version of the plugin (`sentrySvelteKit()`). By specifying options in `unstable_vitePluginOptions`, users can still set and override all options the Vite plugin can take. We explicitly warn that  keys in `unstable_vitePluginOptions` do not follow semver and might be removed or changed at any time. This allows
users to do whatever they need to and us to still bump Vite plugin major versions whenever we need to.
This PR now also adds an MIGRATION entry, which I previously forgot in #10813
builds on #10813 
ref https://github.com/getsentry/sentry-javascript/issues/9835

feat(sveltekit): Export `unstable_sentryVitePluginOptions` for full Vite plugin customization

---

packages/core/src/tracing/hubextensions.ts
packages/core/src/tracing/sentrySpan.ts
packages/core/src/tracing/transaction.ts
packages/node/test/handlers.test.ts
packages/node/test/integrations/http.test.ts
packages/node/test/integrations/undici.test.ts
packages/node/test/performance.test.ts
packages/opentelemetry/src/custom/transaction.ts
packages/opentelemetry/test/custom/transaction.test.ts
packages/sveltekit/test/server/handle.test.ts

This is now not used anymore, we use `getSpanDescendants()` internally now everywhere.

ref: Remove `spanRecorder` and all related code

---

packages/sveltekit/src/server/handle.ts
packages/sveltekit/src/server/load.ts
packages/sveltekit/src/server/utils.ts
packages/sveltekit/test/server/load.test.ts
packages/sveltekit/test/server/utils.test.ts

This WIP updates sveltekit to avoid deprecated options to `startSpan`, which also includes changing how we propagate traces to use `continueTrace`.
I fixed the tests to ensure this still works, but would appreciate a review from @Lms24 if that all seems correct 😅

ref(sveltekit): Update trace propagation & span options

---

packages/remix/src/utils/instrumentServer.ts
packages/remix/src/utils/serverAdapters/express.ts
packages/remix/test/integration/common/routes/manual-tracing.$id.tsx
packages/remix/test/integration/test/client/manualtracing.test.ts

This removes all usage of `startTransaction` and `span.startChild()` in remix.
Instead, we now use `startSpan`, which works reasonably well as we always have callbacks anyhow.
I also updated it to use `continueTrace` for trace propagation.

feat(remix): Refactor to use new performance APIs

---

packages/browser/src/integrations/httpcontext.ts

Removes the old class-based `HttpContext` integration in favor of the `httpContextIntegration`.
(Stumbled upon this while researching something, thought I'd quickly clean it up)

feat(browser): Remove `HttpContext` integration class

---

packages/react/src/errorboundary.tsx
packages/react/test/errorboundary.test.tsx

This PR adjusts when we mark errors caught in our React SDK's `ErrorBoundary` as handled/unhandled.
Previously, we made a change to always mark such errors as unhandled (#8914). However, as pointed out and discussed in #10985, this isn't always the best default value. I propose we set handled/unhandled depending on the presence of the `fallback` component. If users specify a fallback, I think it's safe to mark the error handled, given that users show something else instead of the errored component.
Would appreciate thoughts from our React experts ;)
closes https://github.com/getsentry/sentry-javascript/issues/10985

fix(react): Set `handled` value in ErrorBoundary depending on fallback

---

packages/deno/src/index.ts
packages/deno/src/integrations/breadcrumbs.ts
packages/deno/src/integrations/context.ts
packages/deno/src/integrations/contextlines.ts
packages/deno/src/integrations/deno-cron.ts
packages/deno/src/integrations/globalhandlers.ts
packages/deno/src/integrations/index.ts
packages/deno/src/integrations/normalizepaths.ts
packages/deno/test/__snapshots__/mod.test.ts.snap
packages/deno/test/mod.test.ts
packages/deno/test/normalize.ts

feat(v8/deno): Remove deprecations from deno SDK

---

dev-packages/e2e-tests/test-applications/node-exports-test-app/scripts/consistentExports.ts
packages/bun/src/index.ts
packages/bun/src/integrations/bunserver.ts
packages/bun/test/integrations/bunserver.test.ts

feat(bun/v8): Remove all deprecations from Bun SDK

---

packages/node-experimental/src/sdk/init.ts
packages/opentelemetry/src/constants.ts
packages/opentelemetry/src/contextManager.ts
packages/opentelemetry/src/index.ts
packages/opentelemetry/src/spanProcessor.ts
packages/opentelemetry/src/utils/captureExceptionForTimedEvent.ts
packages/opentelemetry/src/utils/contextData.ts
packages/opentelemetry/src/utils/spanData.ts
packages/opentelemetry/test/utils/captureExceptionForTimedEvent.test.ts

We no longer need it, so we don't need to keep this manually around anymore :tada:
This is WIP on top of https://github.com/getsentry/sentry-javascript/pull/10982

feat(opentelemetry): Remove hub from context

---

.github/workflows/auto-release.yml
.github/workflows/release.yml

Same principle as in #10763 but with config from v8 and releasing from `master`. 
This isn't strictly necessary but I'd say, we also change this to take the config from `master` because technically, our default branch is `develop` and the config _could_ diverge. Unlikely but still something I'd say we should do now that we can.
ref https://github.com/getsentry/publish/issues/3441

chore(publish): [v8] Use craft config from merge target branch for release preparation

---

dev-packages/e2e-tests/test-applications/nextjs-14/package.json
packages/nextjs/src/index.types.ts
packages/nextjs/src/server/index.ts

Backport of https://github.com/getsentry/sentry-javascript/pull/11005
Fixes https://github.com/getsentry/sentry-javascript/issues/10366

fix(nextjs/v7): Use passthrough `createReduxEnhancer` on server

---

packages/core/src/asyncContext.ts
packages/core/src/exports.ts
packages/core/src/index.ts
packages/core/src/metrics/aggregator.ts
packages/core/src/metrics/browser-aggregator.ts
packages/core/src/metrics/metric-summary.ts
packages/core/src/tracing/errors.ts
packages/core/src/tracing/idleSpan.ts
packages/core/src/tracing/index.ts
packages/core/src/tracing/measurement.ts
packages/core/src/tracing/trace.ts
packages/core/src/tracing/utils.ts
packages/core/src/utils/spanUtils.ts
packages/core/test/lib/scope.test.ts
packages/core/test/lib/tracing/dynamicSamplingContext.test.ts
packages/core/test/lib/tracing/trace.test.ts
packages/node-experimental/src/index.ts
packages/node-experimental/src/types.ts
packages/opentelemetry/src/asyncContextStrategy.ts
packages/opentelemetry/src/trace.ts
packages/opentelemetry/src/types.ts
packages/types/src/span.ts

And do this for opentelemetry, instead of relying on extra exports.
Also needed to move things around a bit to avoid circular dependency build issues.
Missing is `getRootSpan` which is still different, I will update this in a follow up to actually use the same non-enumerable property under the hood so we can use the same implementation there!
Until now, we had a core implementation of tracing APIs in `@sentry/core`. In `@sentry/opentelemetry`, we had some alternative implementations, which where instead re-exported in `@sentry/node` - so if you do e.g. this:
```js
import { startSpan } from '@sentry/node';
```
You'll get the correct, OTEL-powered performance API - great!
However, if any code would internally do e.g. this:
```js
import { getActiveSpan } from '@sentry/core'; // import from …
```

feat(core): Allow custom tracing implementations

---

packages/node-experimental/src/integrations/http.ts
packages/node-experimental/test/integration/transactions.test.ts
packages/opentelemetry/src/index.ts
packages/opentelemetry/src/spanExporter.ts
packages/opentelemetry/src/trace.ts
packages/opentelemetry/src/utils/spanData.ts
packages/opentelemetry/test/integration/transactions.test.ts
packages/opentelemetry/test/trace.test.ts

This is not used anymore (and deprecated), so we can remove the custom handling for this.
We put the request on the isolation scope, where it should be picked up anyhow.

ref(opentelemetry): Remove span metadata handling

---

packages/react/src/reactrouter.tsx
packages/react/src/reactrouterv3.ts
packages/react/src/reactrouterv6.tsx
packages/react/src/types.ts

This removes the unused codepaths & fallbacks for the old browser tracing stuff in react.

ref(react): Streamline browser tracing integrations & remove old code

---

packages/bun/test/integrations/bunserver.test.ts
packages/core/src/baseclient.ts
packages/core/src/tracing/trace.ts
packages/core/src/tracing/transaction.ts
packages/core/test/lib/base.test.ts
packages/core/test/lib/tracing/trace.test.ts
packages/replay/src/replay.ts
packages/replay/src/types/replay.ts
packages/replay/src/util/addGlobalListeners.ts
packages/sveltekit/test/server/handle.test.ts
packages/types/src/client.ts

This refactors the remaining usage of `startTransaction` and `finishTransaction` hooks (most of it in tests), and removes these hooks.
This is on top of https://github.com/getsentry/sentry-javascript/pull/11007

ref(core): Remove `startTransaction` & `finishTransaction` hooks

---

packages/ember/addon/instance-initializers/sentry-performance.ts

It seems that this is tree shaken weirdly through the async await import, for some reason. Maybe we can overall refactor this to instead use build time flags (instead of async import) but I'll look into this separately, possibly.
I was able to reproduce this with a small local app, and this seemed to fix it.
Closes https://github.com/getsentry/sentry-javascript/issues/10566

fix(ember): Ensure browser tracing is correctly lazy loaded

---

packages/types/src/envelope.ts
packages/types/src/feedback.ts
packages/types/src/index.ts
packages/types/src/user.ts

Moving the UserFeedback type into the feedback file. It's a better place for it, especially as there will be more related things coming soon (related to the feedback widget)

ref(feedback): Move UserFeedback type into feedback.ts

---

packages/browser/src/stack-parsers.ts
packages/browser/test/unit/tracekit/ie.test.ts

We no longer support IE so we don't need it's parser in the default stack parsers!

feat(browser): Remove IE parser from the default stack parsers

---

packages/nextjs/src/edge/rewriteFramesIntegration.ts
packages/nextjs/src/server/rewriteFramesIntegration.ts
packages/nextjs/test/clientSdk.test.ts

Removes the last internally used deprecated APIs (that are ignored with an eslint comment at least)

ref(nextjs): Remove last internal deprecations

---

dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/route-handlers.test.ts
dev-packages/e2e-tests/test-applications/sveltekit-2/test/errors.server.test.ts
dev-packages/e2e-tests/test-applications/sveltekit/test/errors.server.test.ts
packages/core/src/scope.ts
packages/core/src/utils/applyScopeDataToEvent.ts
packages/core/test/lib/utils/applyScopeDataToEvent.test.ts
packages/remix/test/integration/test/client/capture-exception.test.ts
packages/remix/test/integration/test/client/capture-message.test.ts
packages/types/src/scope.ts

This PR makes some changes to how we apply scope data to events. Previously, we used to apply the transaction name
1. from `scopeData.transactionName`
2. if not already set in 1) the name of the root span
to the `event.transaction` field.
With our efforts to decouple the scope's `transaction` field from a currently active transaction/root span, we now change this behaviour so that:
* only non-transaction events are assigned `event.transaction` from `scopeData.transactionName` (e.g. errors, profiles, replay)
* only transaction events are assigned `event.transaction` from the root span name
Furthermore, this PR also undeprecates `ScopeData.transactionName` as we'll still need it.
ref https://github.com/getsentry/sentry-javascript/issues/10846

feat(core): Decouple `scope.transactionName` from root spans

---

packages/bun/src/integrations/bunserver.ts
packages/core/src/tracing/trace.ts
packages/core/test/lib/tracing/trace.test.ts
packages/node/src/handlers.ts
packages/node/src/integrations/hapi/index.ts
packages/tracing-internal/src/browser/browserTracingIntegration.ts

Also update it to only update the propagation context in the callback. In some places (old node...) we need the legacy behaviour, but for now we can do that in-place.

feat(core): Update `continueTrace` to be callback-only

---

packages/tracing-internal/src/node/integrations/apollo.ts
packages/tracing-internal/src/node/integrations/express.ts
packages/tracing-internal/src/node/integrations/graphql.ts
packages/tracing-internal/src/node/integrations/mongo.ts
packages/tracing-internal/src/node/integrations/mysql.ts
packages/tracing-internal/src/node/integrations/postgres.ts

This refactors the old node integrations to the new syntax, so we can get rid of the public APIs.
This also allows us to get rid of some of the last `getCurrentHub` usage etc.

ref(node-experimental): Refactor usage of `startChild()`

---

packages/google-cloud/package.json

We don't publish bundles from google cloud package, fixing yalc command accordingly.

chore(google-cloud): Fix yalc:publish command

---

packages/replay/src/integration.ts
packages/replay/src/types/replay.ts
packages/replay/test/integration/integrationSettings.test.ts

Options can be configured with `replaysSessionSampleRate` and `replaysOnErrorSampleRate`.
closes https://github.com/getsentry/sentry-javascript/issues/6958

feat(replay/v8): Delete deprecated `replaySession` and `errorSampleRates`

---

dev-packages/rollup-utils/bundleHelpers.mjs
dev-packages/rollup-utils/npmHelpers.mjs

This allows you to configure Sucrase for rollup bundles.
Needed for our work on the Feedback screenshotting feature as we want to use Preact + JSX in the project. (ref: https://github.com/getsentry/sentry-javascript/pull/10590)
Example of how this will be used: https://github.com/getsentry/sentry-javascript/pull/10590/commits/0395331e211cc23f52fd5b4a6e386d38f0edc96d

feat(build): Allow passing Sucrase options for rollup

---

dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/error/subject.js
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/error/test.ts
packages/tracing-internal/src/browser/browserTracingIntegration.ts
packages/tracing-internal/test/browser/browserTracingIntegration.test.ts

_Builds on top of https://github.com/getsentry/sentry-javascript/pull/10991_
This PR updates the transaction name on the scope in the default `browserTracingIntegration` and whenever `startBrowserTracingNavigationSpan` and `startBrowserTracingPageLoadSpan` are called from higher-level SDKs' integrations. 
In a follow-up PR, I'm going to make the same update in our individual `browserTracingIntegration`s whenever we have access to a parameterized transaction name.
ref https://github.com/getsentry/sentry-javascript/issues/10846

ref(browser): Update `scope.transactionName` on pageload and navigation span creation

---

packages/react/src/errorboundary.tsx
packages/react/test/errorboundary.test.tsx

Backport of #10989 (forgot initially; got reminded via #10996)

fix(react): Set `handled` value in ErrorBoundary depending on fallback [v7]

---

dev-packages/e2e-tests/test-applications/angular-17/src/app/user/user.component.ts
dev-packages/e2e-tests/test-applications/angular-17/tests/errors.test.ts
packages/angular/src/tracing.ts

builds on top of https://github.com/getsentry/sentry-javascript/pull/10992
This PR updates our Angular `TraceService` to update the current scope's `transactionName` when we resolve a route and obtain a parameterized route name. This happens:
* during a navigation 
* on first pageload (+ subsequent redirects)
Added/adjusted e2e tests to check for the correct `event.transaction` value.
part of https://github.com/getsentry/sentry-javascript/issues/10846

feat(angular): Update scope `transactionName` when route is resolved

---

packages/angular/src/index.ts
packages/angular/src/tracing.ts

Also remove the deprecated `getActiveTransaction` export.

ref(angular): Refactor usage of `startChild`

---

packages/react/src/reactrouter.tsx
packages/react/src/reactrouterv6.tsx
packages/react/test/reactrouterv3.test.tsx
packages/react/test/reactrouterv4.test.tsx
packages/react/test/reactrouterv5.test.tsx
packages/react/test/reactrouterv6.4.test.tsx
packages/react/test/reactrouterv6.test.tsx

This PR adds  updating of the current scope's `transactionName` value to our React Router instrumentations (i.e. `reactRoutervXbrowserTracingIntegration`s).
Only the v4/5 and v6 integrations needed changes because v3 doesn't retroactively update a transaction name either. We only have to care about transaction name updates here because the `start(Pageload|Navigation)Span` helper functions already set the initial name onto the scope (via https://github.com/getsentry/sentry-javascript/pull/10992).
Added unit tests to all RR versions. 
~Before merging, I'll add an e2e to one of our RR6 e2e test apps~ Actually, this requires some changes to our react e2e test fixture. I'll open a follow-up PR to keep things simpler.
ref: https://github.com/getsentry/sentry-javascript/issues/10846

feat(react): Update scope's `transactionName` in React Router instrumentations

---

packages/core/src/tracing/sentrySpan.ts
packages/core/test/lib/tracing/trace.test.ts
packages/core/test/lib/utils/spanUtils.test.ts
packages/ember/addon/instance-initializers/sentry-performance.ts
packages/node-experimental/src/utils/addOriginToSpan.ts
packages/node-experimental/test/integration/transactions.test.ts
packages/node/src/handlers.ts
packages/opentelemetry/src/index.ts
packages/opentelemetry/src/trace.ts
packages/opentelemetry/test/integration/transactions.test.ts
packages/opentelemetry/test/trace.test.ts
packages/remix/src/utils/instrumentServer.ts
packages/tracing-internal/src/browser/metrics/index.ts
packages/tracing-internal/src/browser/router.ts
packages/tracing-internal/src/node/integrations/express.ts
packages/tracing-internal/test/browser/browserTracingIntegration.test.ts
packages/tracing-internal/test/browser/router.test.ts
packages/types/src/span.ts
packages/types/src/startSpanOptions.ts

This is now always set as attribute.

ref: Remove deprecated `origin` field on span start options

---

MIGRATION.md
dev-packages/browser-integration-tests/suites/replay/customEvents/init.js
dev-packages/browser-integration-tests/suites/replay/privacyBlock/init.js
dev-packages/browser-integration-tests/suites/replay/privacyDefault/template.html
dev-packages/browser-integration-tests/suites/replay/privacyDefault/test.ts-snapshots/privacy-chromium.json
dev-packages/browser-integration-tests/suites/replay/privacyDefault/test.ts-snapshots/privacy-firefox.json
dev-packages/browser-integration-tests/suites/replay/privacyDefault/test.ts-snapshots/privacy-webkit.json
dev-packages/browser-integration-tests/suites/replay/privacyDefault/test.ts-snapshots/privacy.json
dev-packages/browser-integration-tests/suites/replay/privacyInput/init.js
dev-packages/browser-integration-tests/suites/replay/privacyInputMaskAll/init.js
packages/replay/MIGRATION.md
packages/replay/README.md
packages/replay/src/util/getPrivacyOptions.ts
packages/replay/test/integration/rrweb.test.ts
packages/replay/test/unit/util/getPrivacyOptions.test.ts

closes https://github.com/getsentry/sentry-javascript/issues/8887
docs changes: https://github.com/getsentry/sentry-docs/pull/9422

feat(v8/replay): Opt-in options for `unmask` and `unblock`

---

packages/core/src/hub.ts
packages/utils/src/worldwide.ts

This PR moves `defaultCurrentScope` and `defaultIsolationScope` to the `__SENTRY__` global.

feat(core): Move more scope globals to `__SENTRY__`

---

.size-limit.js
packages/core/src/span.ts
packages/tracing-internal/src/browser/browsertracing.ts
packages/tracing-internal/src/browser/metrics/index.ts
packages/tracing-internal/test/browser/browsertracing.test.ts

Adds INP span instrumentation to the old `BrowserTracing` integration.

feat(performance): Port INP span instrumentation to old browser tracing

---

CHANGELOG.md

Backport issue: https://github.com/getsentry/sentry-javascript/issues/10996
This backport previously was going to contain https://github.com/getsentry/sentry-javascript/pull/10970, but given the priority of getting out the INP related change in https://github.com/getsentry/sentry-javascript/pull/11085 we decided to release this now. We can get to the fix in #10970 at a later point, or even move it to v8 entirely.

meta: Update changelog for 7.107.0

---

.github/workflows/build.yml

E.g. see https://github.com/getsentry/sentry-javascript/actions/runs/8283620197/job/22667464126?pr=11106

build(remix): Skip Node 18 & 16 integration tests because they often segfault

---

.craft.yml
CHANGELOG.md

https://github.com/getsentry/publish/issues/3566 failed to fully release because of incorrect google cloud serverless craft config. This fixes that and adjusts our changelog to publish `8.0.0-alpha.4` instead

build: Use correct google cloud serverless craft config

---

.craft.yml

Backport of https://github.com/getsentry/sentry-javascript/pull/11103

feat(serverless/v7): Add Node.js 20 to compatible runtimes

---

packages/node-experimental/test/transports/http.test.ts
packages/node-experimental/test/transports/https.test.ts

Fingers crossed.
Fixes https://github.com/getsentry/sentry-javascript/issues/11111
Node and node-experimental used the same port to set up a test-server. I believe it may have flaked depending on whether the tests were ran at the same time or not.

test(node): Use different test server ports for `node` and `node-experimental` packages

---

.github/workflows/build.yml
.size-limit.js
dev-packages/size-limit-gh-action/.eslintrc.cjs
dev-packages/size-limit-gh-action/action.yml
dev-packages/size-limit-gh-action/index.mjs
dev-packages/size-limit-gh-action/package.json
package.json
yarn.lock

Size seems to be much increased, let's figure this out in follow ups.
Also there is some issue with it reading next.js sizes, also something we can look at in follow ups... I disabled these size checks for now.
The action is now inlined as a package in the monorepo, as our fork has been archived and the upstream package is not really maintained and works pretty different from what we need. Now we at least have full control over this.

ci: Re-add size limit action

---

packages/node-experimental/test/transports/http.test.ts
packages/node-experimental/test/transports/https.test.ts
packages/node/test/transports/http.test.ts
packages/node/test/transports/https.test.ts

Attempt 2
Fixes https://github.com/getsentry/sentry-javascript/issues/11111

test: Wait for test server to close

---

dev-packages/size-limit-gh-action/index.mjs

Noticed this is failing e.g. https://github.com/getsentry/sentry-javascript/actions/runs/8294578489/job/22700116991, it was an incorrect check: if there is no comparison branch, we don't need a PR.

ci: Fix size limit action base upload

---

dev-packages/browser-integration-tests/package.json
dev-packages/rollup-utils/plugins/make-esm-plugin.mjs
packages/browser/package.json
packages/ember/package.json
yarn.lock

Apparently, webpack looks at `sideEffects` in the generated package.json, and based on this does not tree shake correctly 😬 
I also bumped webpack (one of the things I tried while debugging this...).
This now puts the original `sideEffects` value from the original `package.json` and puts it into the esm package.json.

fix(build): Ensure tree shaking works properly for ESM output

---

dev-packages/e2e-tests/test-applications/node-exports-test-app/scripts/consistentExports.ts
packages/opentelemetry/src/index.ts
packages/sveltekit/package.json
packages/sveltekit/src/index.types.ts
packages/sveltekit/src/server/handle.ts
packages/sveltekit/src/server/handleError.ts
packages/sveltekit/src/server/index.ts
packages/sveltekit/src/server/load.ts
packages/sveltekit/src/server/sdk.ts
packages/sveltekit/src/server/utils.ts
packages/sveltekit/src/vite/sourceMaps.ts
packages/sveltekit/test/server/handle.test.ts
packages/sveltekit/test/server/handleError.test.ts
packages/sveltekit/test/server/load.test.ts
packages/sveltekit/test/server/sdk.test.ts

This PR switches the underlying Node SDK from `@sentry/node-experimental` (aka the "legacy" v7 Node SDK) to the new OpenTelemetry-based `@sentry/node` package. 
Had to make a couple of adjustments for tests but overall, the process was rather smooth. 
* Sever-side `fetch` calls are no longer auto-instrumented **in dev mode**. They're still instrumented in prod builds. This is because the SDK/Otel seems to initialize too late in dev mode so the instrumentation of node fetch (undici) doesn't work anymore (?)

feat(sveltekit): Switch to Otel-based `@sentry/node` package

---

packages/node-experimental/src/integrations/local-variables/local-variables-sync.ts

I think we missed this from removing the other class-based exports.

ref(node): Remove class based export for local variable integration

---

dev-packages/browser-integration-tests/suites/replay/extendNetworkBreadcrumbs/fetch/captureRequestHeaders/test.ts
dev-packages/browser-integration-tests/suites/replay/extendNetworkBreadcrumbs/fetch/captureRequestSize/test.ts
dev-packages/browser-integration-tests/suites/replay/extendNetworkBreadcrumbs/fetch/captureResponseHeaders/test.ts
dev-packages/browser-integration-tests/suites/replay/extendNetworkBreadcrumbs/fetch/captureResponseSize/test.ts
dev-packages/browser-integration-tests/suites/tracing/metrics/handlers-lcp/test.ts

closes https://github.com/getsentry/sentry-javascript/issues/11136
closes https://github.com/getsentry/sentry-javascript/issues/11062
closes https://github.com/getsentry/sentry-javascript/issues/11137
closes https://github.com/getsentry/sentry-javascript/issues/11138
closes https://github.com/getsentry/sentry-javascript/issues/11139
In https://github.com/getsentry/sentry-javascript/pull/11134 we changed the playwright tests use a larger GH runner. This should hopefully fix the flaky replay playwright tests. Validating that here.
Note that `Detect flaky tests / Check tests for flakiness` runs on the smaller workers, so it'll experience the same issues we had before.

test: Re-enable flaky replay tests

---

packages/types/src/transaction.ts

`@sentry/types` does not align with `@sentry/core`, and it causes build errors when `exactOptionalPropertyTypes` is `true`.
Example error below:
```
.../Yarn/Berry/cache/@sentry-core-npm-7.107.0-d7aa1d2661-10c0.zip/node_modules/@sentry/core/types/tracing/transaction.d.ts:5:22 - error TS2420: Class 'import(".../Yarn/Berry/cache/@sentry-core-npm-7.107.0-d7aa1d2661-10c0.zip/node_modules/@sentry/core/types/tracing/transaction").Transaction' incorrectly implements interface 'import(".../Yarn/Berry/cache/@sentry-types-npm-7.107.0-a994f84978-10c0.zip/node_modules/@sentry/types/types/transaction").Transaction'.
Types of …
```

fix(types): Fix incorrect `sampled` type on `Transaction`

---

.github/workflows/build.yml
packages/nextjs/test/integration/jest.config.js
packages/nextjs/test/integration/package.json
packages/remix/test/integration/jest.config.js

Ref: https://github.com/getsentry/sentry-javascript/pull/11107/
Removes `--detectOpenHandles` from Jest configurations of Remix and Next.JS which apparently causes segfault.
Re-enables Remix Node 16 and Node 18 integration tests on CI

chore(tests): Remove `--detectOpenHandles` from Jest config.

---

MIGRATION.md
packages/aws-serverless/src/awslambda.ts

The `rethrowAfterCapture` option was deprecated in https://github.com/getsentry/sentry-javascript/pull/4448, which was released in `6.17.2`. This finally removes the option.

feat(aws-serverless): Remove deprecated rethrowAfterCapture option

---

MIGRATION.md
packages/browser/src/exports.ts
packages/browser/src/sdk.ts
packages/browser/test/unit/index.test.ts

In https://github.com/getsentry/sentry-javascript/pull/8927 we deprecated and removed the `wrap` method.
This PR removes the deprecated export from v8.

feat(v8/browser): Remove deprecated wrap export

---

packages/browser/src/integrations/linkederrors.ts

ref https://github.com/getsentry/sentry-javascript/issues/8844

feat(v8/browser): Remove class export for linked errors

---

packages/browser/src/index.ts
packages/core/src/index.ts
packages/core/src/integrations/functiontostring.ts
packages/core/src/integrations/metadata.ts
packages/core/src/integrations/requestdata.ts
packages/core/test/lib/integrations/metadata.test.ts
packages/core/test/lib/integrations/requestdata.test.ts
packages/node/src/integrations/index.ts

Removes exports for `ModuleMetadata` and `RequestData`

feat(v8/core): Remove deprecated integration classes

---

packages/core/src/api.ts
packages/core/src/baseclient.ts
packages/core/test/lib/api.test.ts
packages/node-experimental/src/integrations/anr/common.ts
packages/node-experimental/src/integrations/anr/index.ts
packages/node-experimental/src/integrations/anr/worker.ts

Closes #11159
This PR also modifies `getEnvelopeEndpointWithUrlEncodedAuth` which had a suggested simplification for v8.
I ignored the suggestion because `{ tunnel, _metadata }` feels like a very "internal" API. Sure, this is convenient because it lets you pass the client options directly but it doesn't sit right as a user facing API.

feat(node): Support `tunnel` option for ANR

---

packages/node-experimental/src/integrations/anr/worker.ts
packages/node/src/integrations/anr/worker.ts

fix(node): Use unique variable for ANR context transfer

---

packages/node/src/integrations/anr/worker.ts

fix(node): Use unique variable for ANR context transfer (v7)

---

packages/aws-serverless/src/index.ts
packages/bun/src/index.ts
packages/google-cloud-serverless/src/index.ts
packages/node-experimental/src/index.ts
packages/node-experimental/src/sdk/init.ts
packages/node-experimental/src/sdk/initOtel.ts
packages/node-experimental/test/sdk/client.test.ts

Closes #11118
This PR exports what used to be called `initOtel` so that the `NodeClient` can be used without calling `init`.
If OpenTelemetry is only required for performance feature, we should also only enable it if the sample rate is above zero to save memory.

fix(node):  Export `initOpenTelemetry`

---

dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/interactions/init.js
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/interactions/test.ts
dev-packages/browser-integration-tests/suites/tracing/browsertracing/interactions/init.js
dev-packages/browser-integration-tests/suites/tracing/browsertracing/interactions/test.ts
packages/tracing-internal/src/browser/metrics/index.ts

Adds more interaction event entry names to the INP handler, and distinguish op between click, hover, drag, and press.
Also adds a check to `metric.value` to drop any spans that would have empty exclusive time

feat(webvitals): Adds event entry names for INP handler. Also guard against empty metric value

---

packages/feedback/src/screenshot/components/ScreenshotEditor.tsx

Reduce force layout/reflow by reducing calls mentioned [here](https://gist.github.com/paulirish/5d52fb081b3570c81e3a)

fix(feedback): Reduce force layout in screenshots

---

packages/feedback/src/util/isScreenshotSupported.ts

We use [getDisplayMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia) to take screenshots, which only works in secure contexts, so disable screenshot when not a secure context.

fix(feedback): Only allow screenshots in secure contexts

---

dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/async-spans/init.js
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/async-spans/subject.js
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/async-spans/test.ts

For showing current behavior with using differently timed async spans in browser
ref https://github.com/getsentry/sentry-javascript/pull/10986
ref https://github.com/getsentry/sentry-javascript/issues/10944

test(browser): Add async span example test

---

dev-packages/size-limit-gh-action/index.mjs

Currently, [CI is failing](https://github.com/getsentry/sentry-javascript/actions/runs/8295328564/job/22702264264#step:5:195) on `develop` because we specified the `process.env` object instead of a `rootDir` string as the third argument of the octokit `uploadArtifact` function.  This PR fixes that by setting the directory of the results file as its [root dir](https://github.com/actions/toolkit/tree/%40actions/artifact%401.1.1/packages/artifact#upload-an-artifact). I'm not a 100% convinced that this is correct but we'll see 🤞 
(Also primes example why TypeScript is ❤️ )

fix(ci): Fix root directory for size limit result upload

---

packages/core/src/baseclient.ts
packages/core/src/hub.ts
packages/core/test/lib/base.test.ts
packages/types/src/client.ts

ref https://github.com/getsentry/sentry-javascript/pull/11177

feat(v8/core): Remove deprecated client.setupIntegrations method

---

packages/types/src/datacategory.ts
packages/utils/src/envelope.ts

As per https://github.com/getsentry/relay/blob/2f49cfeb4ed44068e4556ac6ad234f35ee3fde88/relay-server/src/envelope.rs#L166C30-L166C36
Backport for https://github.com/getsentry/sentry-javascript/pull/11184

fix(metrics): use correct statsd data category

---

dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/interactions/assets/script.js
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/interactions/template.html
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/interactions/test.ts
dev-packages/browser-integration-tests/suites/tracing/browsertracing/interactions/assets/script.js
dev-packages/browser-integration-tests/suites/tracing/browsertracing/interactions/template.html
dev-packages/browser-integration-tests/suites/tracing/browsertracing/interactions/test.ts
packages/tracing-internal/src/browser/browserTracingIntegration.ts
packages/tracing-internal/src/browser/browsertracing.ts
packages/tracing-internal/src/browser/instrument.ts
packages/tracing-internal/src/browser/metrics/index.ts
packages/tracing-internal/src/browser/web-vitals/types.ts

Fixes scenarios where interaction tracking wasn't properly recording up to 10 candidate INP interactions.
Fixes `first-input` interaction not always tracked as INP candidates.
Fixes INP candidates not always using the longest latency even in their interaction id grouping.
Also fixes: #11156

fix(webvitals): Fix interactionIdToRouteNameMapping not being maintained properly and sometimes not sending INP spans

---

packages/nextjs/src/server/httpIntegration.ts
packages/nextjs/src/server/index.ts
packages/nextjs/src/server/onUncaughtExceptionIntegration.ts
packages/nextjs/test/serverSdk.test.ts

In order to proceed with removing `Sentry.Integrations.X` as per https://github.com/getsentry/sentry-javascript/issues/8844, there's still some places to clean up.
This does conflict with https://github.com/getsentry/sentry-javascript/pull/11016, but not sure when that merges in, so opening this in the meantime to unblock the integrations cleanup work. if we think the OTEL nextjs work will merge in sooner then the next 1-2 days, I'm happy to leave this alone for now!

feat(v8/nextjs): Remove usage of class integrations

---

packages/core/src/integrations/inboundfilters.ts
packages/core/test/lib/integrations/inboundfilters.test.ts

We received reports about this error
```
TypeError: Cannot redefine property: googletag
```
being thrown and reported to Sentry. It's a noisy error where we strongly suspect that browser extensions interfere with our users' apps. In an effort to quickly reduce noise, this PR adds the error message to our SDK `inboundFilters` integration. 
Side-note: In my opinion we cannot continue adding such filters SDK-side long-term. For the moment we have to because other SDK areas like Replay or spans would incorrectly change their state on an error we first send to Sentry but later on drop in Relay. However, long-term, I strongly think connecting (and sampling) has to happen server side. Otherwise our SDK grows and bundlesize inevitably increases.

feat(core): Filter out noisy GoogleTag error by default

---

MIGRATION.md
packages/ember/addon/index.ts

feat(v8/ember): Remove InitSentryForEmber export

---

packages/node-experimental/src/cron/cron.ts
packages/node-experimental/test/cron.test.ts
packages/node/src/cron/cron.ts
packages/node/test/cron.test.ts

The `cron` package uses `timeZone`, while Sentry internally uses `timezone`. This caused Sentry cron jobs to be incorrectly upserted with no time zone information. Because of the use of the `...(timeZone ? { timeZone } : undefined)` idiom, TypeScript type checking did not catch the mistake.
I kept `cron`'s `timeZone` capitalization within Sentry's instrumentation and changed from the `...(timeZone ? { timeZone } : undefined)` idiom so TypeScript could catch mistakes of this sort. (Passing an undefined `timezone` appears to be okay, because Sentry's `node-cron` instrumentation does it.)

fix(node): Time zone handling for `cron`

---

dev-packages/node-integration-tests/suites/anr/stop-and-start.js
dev-packages/node-integration-tests/suites/anr/test.ts
packages/node-experimental/src/integrations/anr/index.ts

With the Electron SDK, we have an issue (https://github.com/getsentry/sentry-electron/issues/830) where ANR causes the app to freeze when the machine goes through a suspend/resume cycle.
This PR exposes `stopWorker` and `startWorker` methods which can be used in the downstream [ANR integration wrapper](https://github.com/getsentry/sentry-electron/blob/master/src/main/integrations/anr.ts) to stop the ANR feature before device suspend and start it again on device resume.

feat(node): Allow Anr worker to be stopped and restarted

---

dev-packages/node-integration-tests/suites/anr/stop-and-start.js
dev-packages/node-integration-tests/suites/anr/test.ts
packages/node/src/integrations/anr/index.ts

feat(node): Allow Anr worker to be stopped and restarted (v7)

---

packages/node-experimental/src/integrations/anr/index.ts

This was missed from the original PR #11214 but is already included in the backport #11228

fix(node): Clear ANR timer on stop

---

packages/tracing-internal/src/browser/index.ts
packages/tracing-internal/src/browser/instrument.ts
packages/tracing-internal/src/browser/metrics/index.ts
packages/tracing-internal/src/browser/web-vitals/README.md
packages/tracing-internal/src/browser/web-vitals/onTTFB.ts
packages/tracing-internal/src/browser/web-vitals/types/ttfb.ts
packages/tracing-internal/test/browser/metrics/index.test.ts

Backport of https://github.com/getsentry/sentry-javascript/pull/11185

fix(tracing): [v7] use web-vitals ttfb calculation

---

packages/feedback/src/screenshot/components/ScreenshotEditor.tsx
packages/feedback/src/screenshot/components/useTakeScreenshot.tsx

Fixes issue where screenshotting in Safari results in black bars on the right and bottom of the image.
Before:
After:
Relates to https://github.com/getsentry/sentry/issues/63749

fix(feedback): Fix screenshot black bars in Safari

---

CHANGELOG.md
packages/node/src/cron/cron.ts
packages/node/test/cron.test.ts

This is a CHANGELOG for `7.107.0`, and ports https://github.com/getsentry/sentry-javascript/pull/11225 to the v7 branch.

meta: CHANGELOG for 7.108.0

---

dev-packages/node-integration-tests/suites/public-api/LocalVariables/local-variables-caught.mjs
packages/node-experimental/src/integrations/local-variables/local-variables-sync.ts

Closes #11194
The debugger call stack does not include the `new Promise` frames that are parsed from `error.stack`. This means that when we go through the frames to apply the local variables, the frames don't match up and we bail.
This PR ignores those frames when matching functions in the frames.

fix(node): Local variables skipped after Promise

---

dev-packages/browser-integration-tests/suites/replay/bufferMode/test.ts
packages/browser/src/index.bundle.replay.ts
packages/browser/src/index.bundle.tracing.replay.feedback.ts
packages/browser/src/index.bundle.tracing.replay.ts
packages/browser/src/index.ts
packages/replay-canvas/src/canvas.ts
packages/replay/src/index.ts
packages/replay/test/integration/beforeAddRecordingEvent.test.ts
packages/replay/test/integration/stop.test.ts
packages/replay/test/mocks/mockSdk.ts
packages/replay/test/utils/getTestEvent.ts

ref https://github.com/getsentry/sentry-javascript/pull/11200
ref issue https://github.com/getsentry/sentry-javascript/issues/8864

ref(v7/replay): Deprecate `@sentry/replay` exports

---

dev-packages/node-integration-tests/suites/public-api/LocalVariables/local-variables-caught.mjs
packages/node/src/integrations/local-variables/local-variables-sync.ts

fix(node): Local variables skipped after Promise (v7)

---

packages/core/src/integration.ts
packages/core/test/lib/sdk.test.ts
packages/core/test/mocks/integration.ts
packages/feedback/src/core/integration.ts
packages/feedback/src/modal/integration.ts
packages/feedback/src/screenshot/integration.ts
packages/node-experimental/src/integrations/anr/index.ts
packages/node/src/integrations/http.ts
packages/node/src/integrations/undici/index.ts
packages/node/test/integrations/contextlines.test.ts
packages/node/test/integrations/http.test.ts
packages/tracing-internal/src/node/integrations/express.ts
packages/tracing-internal/src/node/integrations/mongo.ts
packages/types/src/index.ts
packages/types/src/integration.ts

Make `integration.setupOnce` accept no arguments. This will allow us to easily remove `addGlobalEventProcessor` which is deprecated API.
This also means we can remove `IntegrationFnResult`, as the type signature of the functional and class based integrations are now the same.
Next up - remove `addGlobalEventProcessor`!

ref(v8): change integration.setupOnce signature

---

CHANGELOG.md

Feedback from Bruno. Also went ahead and updated https://github.com/getsentry/sentry-javascript/releases/tag/8.0.0-alpha.5 accordingly.

chore: Add angular note to 8.0.0-alpha.5 changelog

---

dev-packages/node-integration-tests/suites/tracing-experimental/prisma-orm/scenario.js
packages/astro/src/server/sdk.ts
packages/node-experimental/src/integrations/tracing/index.ts

This seems to have issues in ESM builds (not just in astro, but also saw it in remix), so for now removing this from defaults - users can still add it manually if needed. We may find a better solution for this before v8 is stable.

feat(node): Do not include `prismaIntegration` by default

---

packages/nextjs/src/config/webpack.ts

The warning existed, but was not called

fix(nextjs): Show misconfiguration warning (no `instrumentation.ts`)

---

packages/core/src/utils/spanUtils.ts
packages/opentelemetry/src/spanExporter.ts
packages/opentelemetry/src/trace.ts

This PR fixes span status stomping in the Otel `starSpan` and `startSpanManual` implementations.
When the callbacks threw, we didn't check whether there was already a more useful status on there and just stomped it with an `ERROR` status. Now we only set the status to `ERROR` when it wasn't defined already.

fix(opentelemetry): Do not stomp span status when `startSpan` callback throws

---

MIGRATION.md
packages/browser/src/exports.ts
packages/core/src/eventProcessors.ts
packages/core/src/index.ts
packages/core/src/utils/prepareEvent.ts
packages/node/src/index.ts
packages/replay-internal/test/mocks/resetSdkMock.ts
packages/utils/src/worldwide.ts

Removes `addGlobalEventProcessor` and adds migration guide.

feat(v8): Remove addGlobalEventProcessor

---

dev-packages/node-integration-tests/suites/anr/basic-session.js
dev-packages/node-integration-tests/suites/anr/basic.js
dev-packages/node-integration-tests/suites/anr/basic.mjs
dev-packages/node-integration-tests/suites/anr/forked.js
dev-packages/node-integration-tests/suites/anr/isolated.mjs
dev-packages/node-integration-tests/suites/anr/stop-and-start.js
dev-packages/node-integration-tests/suites/anr/test.ts
packages/node-experimental/src/integrations/anr/index.ts
packages/node-experimental/src/integrations/anr/worker.ts

Closes #10668
Rather than inject large unchecked JavaScript strings to run via `Runtime.evaluate`, when the ANR integration is enabled, we add a function to `global.__SENTRY_GET_SCOPES__` which can then be called via the debugger when the event loop is suspended.

feat(node): Add scope to ANR events

---

dev-packages/node-integration-tests/suites/tracing-experimental/hapi/scenario.js
dev-packages/node-integration-tests/suites/tracing-experimental/hapi/test.ts
dev-packages/node-integration-tests/utils/runner.ts
packages/node/src/integrations/hapi/index.ts

Resolves: https://github.com/getsentry/sentry-javascript/issues/11069
After checking the behaviour, it seems to me that we don't need to capture any Boom responses, as the errors that may cause a `5xx` response are already captured by the core logic. To add an option to control this behaviour, we need to update the usage of `hapiErrorPlugin`, converting it to a function signature, which IMO may not worth doing, as I'm not sure if users in general would need to use it.
This also adds `expectError()` to the `node-integration-tests` runner to allow `5xx` responses to be tested.

fix(node): Skip capturing Hapi Boom error responses.

---

packages/feedback/src/constants/index.ts
packages/feedback/src/core/integration.ts
packages/feedback/src/core/sendFeedback.ts
packages/feedback/src/modal/components/Form.tsx
packages/feedback/src/modal/createDialog.tsx
packages/feedback/src/types/config.ts

Fix #11152
This introduces an option `isRequiredLabel`, and I planned to also add `errorMessageText`.
However, this PR is branched off from a version that is a couple days old. Right now, @c298lee is currently working on getsentry/sentry#63749, which is causing major changes and the current version on master doesn't work yet. Therefore, I didn't yet implement `errorMessageText`.
So consider this PR as a PoC, and either feel free to tag me when the screenshot changes are done – then I'll redo the changes based on the version that supports screenshots – or add the option on your own; however you prefer :slightly_smiling_face: 
One open question:
Until now, there was only the error message:
> There was a problem submitting feedback, please wait and try again.
Now, depending on the status …

feat(feedback): Make "required" text for input elements configurable (#11152)

---

packages/profiling-node/package.json
packages/profiling-node/src/integration.ts
packages/profiling-node/src/spanProfileUtils.ts
packages/profiling-node/src/utils.ts
packages/profiling-node/test/integration.test.ts
packages/profiling-node/test/spanProfileUtils.test.ts

ref https://github.com/getsentry/sentry-javascript/issues/9956
This is another attempt at https://github.com/getsentry/sentry-javascript/pull/11033 now that https://github.com/getsentry/sentry-javascript/pull/11135 has merged in.

feat(profiling): Use OTEL powered node package

---

packages/profiling-node/src/integration.ts
packages/profiling-node/src/utils.ts

Building on top of https://github.com/getsentry/sentry-javascript/pull/11239, this removes usage of `getCurrentHub` in `profiling-node` package by passing in the defined client into the function.
This also removes the `createProfilingEventFromTransaction`, which was totally unused.

ref(profiling-node): Remove usage of getCurrentHub

---

packages/core/src/tracing/sampling.ts
packages/core/src/tracing/sentrySpan.ts
packages/core/src/tracing/trace.ts
packages/core/test/lib/tracing/trace.test.ts
packages/types/src/transaction.ts

Removes `span.sampled`, and rewrites transaction sampling to avoid mutating transaction.

feat(v8/core): Remove deprecated span.sampled

---

dev-packages/e2e-tests/test-applications/node-exports-test-app/scripts/consistentExports.ts
packages/astro/src/index.types.ts
packages/browser/src/exports.ts
packages/core/src/hub.ts
packages/core/src/index.ts
packages/node/src/index.ts
packages/node/test/integrations/http.test.ts
packages/remix/src/index.types.ts

feat(v8): Remove makeMain export

---

MIGRATION.md
packages/svelte/src/config.ts
packages/svelte/src/index.ts
packages/svelte/src/performance.ts
packages/svelte/src/preprocessors.ts
packages/svelte/test/config.test.ts
packages/svelte/test/preprocessors.test.ts

ref ref https://github.com/getsentry/sentry-javascript/issues/10100

feat(v8/svelte): Remove deprecated componentTrackingPreprocessor export

---

MIGRATION.md
packages/browser/src/index.ts
packages/core/src/tracing/index.ts
packages/core/src/tracing/utils.ts
packages/node/src/index.ts
packages/tracing-internal/src/exports/index.ts

more `getCurrentHub` usages bite the dust.

feat(v8/core): Remove getActiveTransaction

---

packages/core/src/tracing/trace.ts
packages/node/src/integrations/http.ts
packages/remix/src/utils/serverAdapters/express.ts
packages/replay-internal/README.md
packages/sveltekit/src/index.types.ts

The remaining usages are shims + stuff we have for tests. Not sure how much test code we should delete.

ref: Remove more usages of getCurrentHub in the codebase

---

packages/utils/src/envelope.ts
packages/utils/src/worldwide.ts
packages/utils/test/envelope.test.ts

The TextEncoder option was removed in https://github.com/getsentry/sentry-javascript/pull/10701 because all of the newly supported platforms support TextEncoder/Decoder.
Sadly that's not true for React Native, yet. TextEncoder will be included in the next release of RN with Hermes. See the PR https://github.com/facebook/hermes/commit/3863a36a53005dd1e6d39ea0d4ef5573bafde910#diff-4bf4a4ab271f254baf2097be87be98333ec69eb2d41e074b81147656c33145eb
We can not drop support of all the previous RN versions in the RN SDK v6 (the next major). 
To avoid passing the encoder option around the SDK, I propose adding polyfill properties to the global __SENTRY__ object which RN can use.

feat(utils): Allow text encoder/decoder polyfill from global __SENTRY__

---

dev-packages/size-limit-gh-action/index.mjs
dev-packages/size-limit-gh-action/package.json
yarn.lock

I inlined https://github.com/billyvg/github-fetch-workflow-artifact, basically, as it struggled to import this in esm, for whatever reason... now all the code is inlined, which is fine I guess 😬

ci: Fix size limit comparison

---

packages/node-experimental/src/transports/http.ts

I leave the other checks (e.g. in http integration) in there, for now (where we check if the url is sentry URL), but this should ensure we are also not picked up by any other OTEL instrumentation etc.

fix(node): Use `suppressTracing` to avoid capturing otel spans

---

packages/node-experimental/src/integrations/node-fetch.ts

Addressing https://github.com/getsentry/sentry-javascript/discussions/11215, this updates the logs for `NodeFetch` to make it clearer what is happening.
Also, we actually do not support Node <18 there, so updating this accordingly too.

fix(node): Add logs when node-fetch cannot be instrumented

---

dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/backgroundtab-custom/init.js
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/backgroundtab-custom/subject.js
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/backgroundtab-custom/test.ts
dev-packages/e2e-tests/test-applications/nextjs-app-dir/components/span-context.tsx
dev-packages/rollup-utils/plugins/bundlePlugins.mjs
packages/browser/src/index.bundle.tracing.replay.feedback.ts
packages/browser/src/index.bundle.tracing.replay.ts
packages/browser/src/index.bundle.tracing.ts
packages/core/src/fetch.ts
packages/core/src/scope.ts
packages/core/src/server-runtime-client.ts
packages/core/src/tracing/idleSpan.ts
packages/core/src/tracing/trace.ts
packages/core/src/utils/spanOnScope.ts
packages/core/src/utils/spanUtils.ts
packages/core/test/lib/scope.test.ts
packages/core/test/lib/tracing/trace.test.ts
packages/node/src/_setSpanForScope.ts
packages/node/src/handlers.ts
packages/node/src/integrations/hapi/index.ts
packages/node/test/integrations/http.test.ts
packages/opentelemetry/src/trace.ts
packages/types/src/scope.ts

Instead, we have an internal utility for this now.

ref(core): Remove `scope.setSpan()` and `scope.getSpan()` methods

---

dev-packages/e2e-tests/test-applications/nextjs-app-dir/assert-build.ts

Fixes https://github.com/getsentry/sentry-javascript/issues/11298

test(nextjs): Adjust build validator for newest Next.js canary

---

packages/replay-internal/package.json

Let's see if that fixes the publishing issue... (Note that this was never there, but maybe this is a problem...)

build(replay): Ensure replay package has `publishConfig`

---

dev-packages/browser-integration-tests/suites/public-api/init/stringSampleRate/init.js
dev-packages/browser-integration-tests/suites/public-api/init/stringSampleRate/subject.js
dev-packages/browser-integration-tests/suites/public-api/init/stringSampleRate/test.ts
dev-packages/browser-integration-tests/suites/tracing/stringSampleRate/init.js
dev-packages/browser-integration-tests/suites/tracing/stringSampleRate/subject.js
dev-packages/browser-integration-tests/suites/tracing/stringSampleRate/test.ts
packages/core/src/baseclient.ts
packages/core/src/index.ts
packages/core/src/tracing/index.ts
packages/core/src/tracing/sampling.ts
packages/core/src/tracing/trace.ts
packages/core/src/utils/parseSampleRate.ts
packages/core/test/lib/utils/parseSampleRate.test.ts
packages/opentelemetry/src/sampler.ts
packages/replay-internal/src/integration.ts
packages/replay-internal/test/integration/integrationSettings.test.ts
packages/utils/src/is.ts
packages/utils/src/normalize.ts
packages/utils/test/is.test.ts

If users pass e.g. `sampleRate: process.env.SAMPLE_RATE`, this will be somewhat silently ignored because we ignore non-number sample rates. This is a bit of a footgun.
So this PR changes this so that we actually accept such sample rates. In the process, I also removed the `isNaN` polyfill as this is not really needed anymore.
I also updated OTEL to use the same sampling function as core (to avoid this drifting apart), and am using this for `sampleRate`, `tracesSampleRate` and the replay sample rates now.
See e.g. https://github.com/getsentry/sentry-javascript/issues/11262

feat(core): Handle string sample rates

---

packages/angular/src/index.ts
packages/angular/src/sdk.ts
packages/angular/test/sdk.test.ts
packages/browser/src/sdk.ts

ref https://github.com/getsentry/sentry-javascript/issues/9508
The `BrowserApiErrors` integration interfers with Angular error handler, so don't include it in the default integrations.

ref(angular): Don't include BrowserApiErrors in bundle

---

packages/tracing-internal/src/browser/metrics/index.ts

resolves https://github.com/getsentry/sentry-javascript/issues/11310

fix(web-vitals): Check for undefined navigation entry

---

.git-blame-ignore-revs

Adding these three PRs to avoid cluttering stuff too much.

ref: Ignore node/node-experimental move PRs from git blame

---

packages/replay-canvas/package.json
packages/replay-internal/package.json
yarn.lock

* fix(canvas): createImageBitmap throws when canvas size is 0
* fix: fixes several cases where we access an undefined value
* fix: Incorrect parsing of functional pseudo class css selector

feat(replay): Bump `rrweb` to 2.12.0

---

packages/replay-canvas/package.json
packages/replay/package.json
yarn.lock

Backport of https://github.com/getsentry/sentry-javascript/pull/11314
* fix(canvas): createImageBitmap throws when canvas size is 0
* fix: fixes several cases where we access an undefined value
* fix: Incorrect parsing of functional pseudo class css selector

 feat(replay/v7): Bump `rrweb` to 2.12.0

---

packages/browser/src/index.bundle.feedback.ts
packages/browser/src/index.bundle.tracing.replay.feedback.ts
packages/browser/src/index.ts
packages/feedback/src/core/getFeedback.test.ts
packages/feedback/src/core/getFeedback.ts
packages/feedback/src/core/integration.ts
packages/feedback/src/index.ts

Also ensure the `feedbackIntegration` returns a properly typed response.
This should make it easier to manually interact with feedbacks.

feat(feedback): Add `getFeedback` utility to get typed feedback instance

---

dev-packages/node-integration-tests/suites/tracing/spans/scenario.ts
dev-packages/node-integration-tests/suites/tracing/spans/test.ts
dev-packages/node-integration-tests/suites/tracing/tracePropagationTargets/scenario.ts
dev-packages/node-integration-tests/suites/tracing/tracePropagationTargets/test.ts
dev-packages/node-integration-tests/utils/runner.ts
dev-packages/node-integration-tests/utils/server.ts

This PR adds some utilities to aid in testing Node HTTP instrumentation and then updates the tests to use the new runner

test(node): Node HTTP instrumentation integration tests

---

CHANGELOG.md

Dependent on https://github.com/getsentry/sentry-javascript/pull/11324
tracking issue: https://github.com/getsentry/sentry-javascript/issues/11247

meta: CHANGELOG for 7.109.0

---

packages/node/src/handlers.ts
packages/utils/src/requestdata.ts

This is not used/needed anymore in v8, and also is coupled to transactions.
Not sure if we need to add this to migration docs, as this is from utils and was more internally used...? (Also, I guess if so we need to add it to migration docs in a separate PR on develop...?)

ref(v7): Deprecate `addRequestDataToTransaction`

---

packages/vercel-edge/src/types.ts

This is not actually used anymore.

ref(v8): Remove `shouldCreateSpanForRequest` from vercel edge options

---

packages/eslint-config-sdk/src/base.js
packages/utils/src/browser.ts
packages/utils/src/supports.ts
packages/utils/src/vendor/supportsHistory.ts
packages/utils/src/worldwide.ts

ref(v8): Remove `getGlobalObject` utility method

---

packages/core/src/scope.ts
packages/core/test/lib/scope.test.ts
packages/types/src/scope.ts

Removing the last deprecated things from the scope!

ref(v8): Remove deprecated methods on scope

---

dev-packages/node-integration-tests/suites/tracing/metric-summaries/test.ts
packages/core/src/metrics/exports.ts
packages/core/src/scope.ts
packages/types/src/scope.ts

This depends on https://github.com/getsentry/sentry-javascript/pull/11363 being merged first...

ref(v8): Remove deprecated `scope.getTransaction()`

---

packages/core/src/index.ts
packages/core/src/integration.ts
packages/core/test/lib/integration.test.ts

ref https://github.com/getsentry/sentry-javascript/issues/9508

ref: Remove convertIntegrationFnToClass

---

packages/utils/src/requestdata.ts

See https://github.com/getsentry/sentry-javascript/pull/11368, where this is deprecated on v7.

ref(v8): Remove `addRequestDataToTransaction` util

---

packages/utils/src/worldwide.ts

Now we've dropped Nove v12 we can simplify to `globalThis`:
https://github.com/getsentry/sentry-javascript/issues/5611#issuecomment-1271712639

feat(utils): Use `globalThis`

---

.eslintrc.js
dev-packages/bundle-analyzer-scenarios/README.md
dev-packages/bundle-analyzer-scenarios/browser-basic/index.js
dev-packages/bundle-analyzer-scenarios/browser-basic/package.json
dev-packages/bundle-analyzer-scenarios/package.json
dev-packages/bundle-analyzer-scenarios/webpack.cjs
dev-packages/rollup-utils/npmHelpers.mjs
package.json
packages/browser/rollup.npm.config.mjs
packages/core/rollup.npm.config.mjs
packages/deno/rollup.test.config.mjs
packages/feedback/rollup.npm.config.mjs
packages/node/rollup.npm.config.mjs
packages/opentelemetry/rollup.npm.config.mjs
packages/replay-canvas/rollup.npm.config.mjs
packages/replay-internal/rollup.npm.config.mjs
packages/tracing-internal/rollup.npm.config.mjs
packages/utils/rollup.npm.config.mjs
yarn.lock

With the v8 beta coming up, we should start examining the bundle to see if there's any opportunity for us to optimize.
This PR adds a package that you can add simple scenarios to that can get tested against.

chore: Add bundle analysis package

---

packages/core/src/tracing/sentrySpan.ts
packages/core/src/tracing/trace.ts
packages/core/test/lib/tracing/transaction.test.ts
packages/tracing-internal/src/browser/metrics/index.ts
packages/types/src/transaction.ts

feat(v8/core): Remove span.attributes top level field

---

dev-packages/node-integration-tests/suites/tracing/prisma-orm/package.json

Seems like GitHub got rid of `docker-compose` on April 2 so we need to use `docker compose` instead now:
- https://github.com/actions/runner-images/issues/9557
- https://github.com/orgs/community/discussions/116610

ci(tests): Use `docker compose` instead of `docker-compose`

---

dev-packages/e2e-tests/test-applications/sveltekit/test/performance.test.ts

We're seeing weird timeouts: https://github.com/getsentry/sentry-javascript/actions/runs/8537463808/job/23388413419?pr=11392#step:12:82

test(e2e): Attempt to fix sveltekit timeouts

---

dev-packages/node-integration-tests/suites/tracing-new/prisma-orm/package.json
dev-packages/node-integration-tests/suites/tracing/prisma-orm/package.json
packages/astro/src/index.server.ts
packages/bun/src/index.ts
packages/node/src/handlers.ts
packages/node/src/index.ts
packages/node/src/trpc.ts
packages/remix/src/index.server.ts
packages/serverless/src/index.ts
packages/sveltekit/src/server/index.ts

The `trpcMiddleware` export will move from `Handlers` to a top level export in v8. This is more or less backporting https://github.com/getsentry/sentry-javascript/pull/11374 to v7.

feat(v7): Deprecate and relocate `trpcMiddleware`

---

packages/core/src/tracing/sentrySpan.ts
packages/core/src/tracing/transaction.ts
packages/types/src/transaction.ts

Removes a bunch of further deprecated properties on span & transaction.

ref(v8): Remove deprecated span & transaction properties

---

packages/tracing-internal/src/browser/browserTracingIntegration.ts
packages/tracing-internal/src/browser/browsertracing.ts
packages/tracing-internal/src/browser/metrics/index.ts
packages/tracing-internal/test/browser/browsertracing.test.ts

Adds a `interactionsSampleRate` option to browser tracing integrations to allow users to apply an additional sample rate filter on interaction spans.
`interactionsSampleRate` is applied on top of the global `tracesSampleRate`.
Therefore if `interactionsSampleRate` is `0.5` and `tracesSampleRate` is `0.1`, then the actual sample rate for interactions is `0.05`

feat(interactions): Add interactions sample rate to browser tracing integrations

---

.vscode/settings.json

Since a couple of days, VSCode no longer auto formats my TS files despite me setting biome as the default formatter in my user `settings.json`. Adding the `typescript` entry to the repo's `settings.json` seems to fix the issue for me. 
cc @lforst I think you experienced something similar
I still think we should get rid of biome but for now, this should solve the auto formatting issue

chore(format): Set biome as default VSCode formatter for typescript

---

dev-packages/rollup-utils/plugins/bundlePlugins.mjs
packages/core/src/tracing/dynamicSamplingContext.ts
packages/core/src/tracing/trace.ts
packages/core/src/tracing/transaction.ts
packages/core/test/lib/tracing/dynamicSamplingContext.test.ts
packages/core/test/lib/tracing/transaction.test.ts
packages/types/src/index.ts
packages/types/src/transaction.ts

Instead, we freeze the DSC explicitly onto the transaction now.

ref(v8): Remove `metadata` on transaction

---

packages/core/src/tracing/span.ts
packages/core/test/lib/tracing/span.test.ts
packages/types/src/span.ts

Allows exclusive time for spans to be 0, including inp spans.

fix(spans): Allow zero exclusive time for INP spans

---

MIGRATION.md
dev-packages/e2e-tests/test-applications/node-exports-test-app/scripts/consistentExports.ts
dev-packages/e2e-tests/test-applications/node-express-app/package.json
dev-packages/e2e-tests/test-applications/node-express-app/src/app.ts
dev-packages/e2e-tests/test-applications/node-express-app/tests/server.test.ts
packages/aws-serverless/src/index.ts
packages/bun/src/index.ts
packages/core/src/index.ts
packages/core/src/trpc.ts
packages/google-cloud-serverless/src/index.ts
packages/node/src/index.ts
packages/remix/src/index.server.ts
packages/sveltekit/src/server/index.ts
packages/vercel-edge/src/index.ts

Adds back the `trpcMiddleware` we accidentally removed when removing the old `@sentry/node` package.

feat: Add `trpcMiddleware` back to serverside SDKs

---

.github/workflows/flaky-test-detector.yml
dev-packages/node-integration-tests/suites/public-api/setMeasurement/scenario.ts
dev-packages/node-integration-tests/suites/public-api/setMeasurement/test.ts
packages/browser/src/index.bundle.tracing.replay.feedback.ts
packages/browser/src/index.bundle.tracing.replay.ts
packages/browser/src/index.bundle.tracing.ts
packages/core/src/semanticAttributes.ts
packages/core/src/tracing/index.ts
packages/core/src/tracing/measurement.ts
packages/core/src/tracing/sentryNonRecordingSpan.ts
packages/core/src/tracing/sentrySpan.ts
packages/core/src/tracing/transaction.ts
packages/opentelemetry/src/spanExporter.ts
packages/types/src/index.ts
packages/types/src/span.ts
packages/types/src/timedEvent.ts
packages/types/src/transaction.ts

Now, we interpret timed events with special attributes as timed events.
For now, we ignore all other timed events.

feat: Implement timed events & remove `transaction.measurements`

---

dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals-ttfb/test.ts
packages/tracing-internal/.eslintrc.js
packages/tracing-internal/src/browser/instrument.ts
packages/tracing-internal/src/browser/metrics/index.ts
packages/tracing-internal/src/browser/web-vitals/README.md
packages/tracing-internal/src/browser/web-vitals/getCLS.ts
packages/tracing-internal/src/browser/web-vitals/getFID.ts
packages/tracing-internal/src/browser/web-vitals/getINP.ts
packages/tracing-internal/src/browser/web-vitals/getLCP.ts
packages/tracing-internal/src/browser/web-vitals/lib/bindReporter.ts
packages/tracing-internal/src/browser/web-vitals/lib/getNavigationEntry.ts
packages/tracing-internal/src/browser/web-vitals/lib/getVisibilityWatcher.ts
packages/tracing-internal/src/browser/web-vitals/lib/initMetric.ts
packages/tracing-internal/src/browser/web-vitals/lib/observe.ts
packages/tracing-internal/src/browser/web-vitals/lib/onHidden.ts
packages/tracing-internal/src/browser/web-vitals/lib/runOnce.ts
packages/tracing-internal/src/browser/web-vitals/lib/whenActivated.ts
packages/tracing-internal/src/browser/web-vitals/onFCP.ts
packages/tracing-internal/src/browser/web-vitals/onTTFB.ts
packages/tracing-internal/src/browser/web-vitals/types.ts
packages/tracing-internal/src/browser/web-vitals/types/base.ts
packages/tracing-internal/src/browser/web-vitals/types/cls.ts
packages/tracing-internal/src/browser/web-vitals/types/fcp.ts
packages/tracing-internal/src/browser/web-vitals/types/fid.ts
packages/tracing-internal/src/browser/web-vitals/types/inp.ts
packages/tracing-internal/src/browser/web-vitals/types/lcp.ts
packages/tracing-internal/src/browser/web-vitals/types/ttfb.ts

There are some bug fixes in the meanwhile.

feat(browser): Bump web-vitals to 3.5.2

---

dev-packages/e2e-tests/test-applications/sveltekit-2/test/errors.client.test.ts
packages/opentelemetry/test/propagator.test.ts
packages/sveltekit/src/client/browserTracingIntegration.ts
packages/sveltekit/test/client/browserTracingIntegration.test.ts

Our SvelteKit routing instrumentation updates the pageload rootspan name once we obtain the parameterized route id. This PR now also updates the scope's `transactionName` at this point.
ref #10846

feat(sveltekit): Update scope `transactionName` when pageload route name is updated

---

yarn.lock

Missed that #11418 didn't update the yarn lock

chore(repo): Unstale `yarn.lock`

---

dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/exceptions.test.ts

Super small PR to check that an error event has a valid `transaction` field in NextJS. 
Besides testing, there was nothing specifically to do for NextJS since as far as I can tell we never update a pageload or navigation span name. 
ref #10846

test(e2e-nextjs): Check NextJS client error `transaction` field

---

dev-packages/e2e-tests/test-applications/vue-3/src/router/index.ts
dev-packages/e2e-tests/test-applications/vue-3/src/views/UserIdErrorView.vue
dev-packages/e2e-tests/test-applications/vue-3/tests/errors.test.ts
packages/vue/src/router.ts
packages/vue/test/router.test.ts

This PR updates the current scope's `transactionName` when our Vue router instrumentation resolves the parameterized route name. 
ref #10846

feat(vue): Update scope's `transactionName` when resolving a route

---

packages/feedback/src/core/components/Actor.css.ts

I forgot to apply the font family style to the actor button too
follow up to https://github.com/getsentry/sentry-javascript/pull/11414
ref: https://github.com/getsentry/sentry-javascript/issues/10202

ref(feedback): Add font family style to actor

---

dev-packages/node-integration-tests/suites/metrics/should-exit-forced.js
dev-packages/node-integration-tests/suites/metrics/should-exit.js
dev-packages/node-integration-tests/suites/metrics/test.ts
dev-packages/node-integration-tests/suites/tracing/metric-summaries/scenario.js
packages/core/src/metrics/aggregator.ts
packages/core/src/sessionflusher.ts

Add `unref` to make sure that the session flusher or metrics aggregator does not block nodejs exit. Especially important for serverless scenarios.

fix(core): unref timer to not block node exit

---

packages/browser-utils/rollup.npm.config.mjs
packages/browser/rollup.npm.config.mjs
packages/core/rollup.npm.config.mjs
packages/utils/rollup.npm.config.mjs

Let's see how much this helps with bundle size.

ref: Set preserveModules to true for browser packages

---

dev-packages/browser-integration-tests/suites/integrations/Breadcrumbs/dom/click/template.html
dev-packages/browser-integration-tests/suites/integrations/Breadcrumbs/dom/click/test.ts
dev-packages/browser-integration-tests/suites/integrations/Breadcrumbs/dom/textInput/template.html
dev-packages/browser-integration-tests/suites/integrations/Breadcrumbs/dom/textInput/test.ts
dev-packages/browser-integration-tests/suites/replay/captureComponentName/template.html
dev-packages/browser-integration-tests/suites/replay/captureComponentName/test.ts
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/interactions/assets/script.js
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/interactions/template.html
dev-packages/browser-integration-tests/suites/tracing/browserTracingIntegration/interactions/test.ts
packages/replay-internal/src/coreHandlers/util/getAttributesToRecord.ts
packages/replay-internal/test/unit/coreHandlers/util/getAttributesToRecord.test.ts
packages/utils/src/browser.ts

Adds element name as fallback. If component name exists, use that, else if element name exists use that, else use selector name. The element name and component name mirrors that of [React components vs elements](https://legacy.reactjs.org/blog/2015/12/18/react-components-elements-and-instances.html)
Example with Replay Play/Pause Button:
| Name Type | HTML Tree|
-------------|------------|
| Component Name | none > none > ReplayControls > ButtonBar > none |
| Element Name | FullViewport > none > ButtonGrid > ButtonGrid > ReplayPlayPauseButton |
| Element + Component fallback | FullViewPort > none > ButtonGrid > ButtonGrid > ReplayPlayPauseButton |
| Component + Element fallback | FullViewPort > none > ReplayControls > ButtonBar > ReplayPlayPauseButton  |
More elements have an …

feat(replay): Use data sentry element as fallback for the component name

---

dev-packages/e2e-tests/test-applications/sveltekit-2/test/errors.client.test.ts
dev-packages/e2e-tests/test-applications/sveltekit-2/test/utils.ts
dev-packages/e2e-tests/test-applications/sveltekit/test/errors.client.test.ts
dev-packages/e2e-tests/test-applications/sveltekit/utils.ts

Both SvelteKit e2e test apps have a flaky test that checks for a client-side error to be caught by the SDK. Looks like Kit hydration takes too long in the Playwright env to kick in, leading to our test clicking the error-triggering button before the onclick handler code is registered. 
The PR attempts to fix the the flakiness by awaiting the initial pageload, meaning we await
- going to the specified route
- a custom hydration flag being set
- the pageload transaction being sent
This will prolong the test for a couple of ms but I think that's acceptable.

test(e2e/sveltekit): Unflake client error test by waiting for hydration

---

packages/opentelemetry/src/utils/contextData.ts
packages/opentelemetry/src/utils/spanData.ts

It may happen that we have different modules, different versions etc. so the weakmaps may not be in sync. Just storing a non-enumerable property should be the safer choice here.
Partially required for next.js 13.4.19 to work....

fix(opentelemetry): Avoid weakmap for storing data

---

dev-packages/browser-integration-tests/suites/integrations/lazyLoad/existingIntegration/init.js
dev-packages/browser-integration-tests/suites/integrations/lazyLoad/existingIntegration/subject.js
dev-packages/browser-integration-tests/suites/integrations/lazyLoad/existingIntegration/test.ts
dev-packages/browser-integration-tests/suites/integrations/lazyLoad/validIntegration/init.js
dev-packages/browser-integration-tests/suites/integrations/lazyLoad/validIntegration/subject.js
dev-packages/browser-integration-tests/suites/integrations/lazyLoad/validIntegration/test.ts
packages/browser/src/client.ts
packages/browser/src/exports.ts
packages/browser/src/utils/lazyLoadIntegration.ts
packages/browser/test/unit/utils/lazyLoadIntegration.test.ts

This can be used to lazy load a pluggable integration.
Usage:
```js
async function getOrLazyLoadFeedback() {
const existing = Sentry.getFeedback(); // check if it has already been installed
if (existing) {
return existing;
}
try {
const feedbackIntegration = await Sentry.lazyLoadIntegration('feedbackIntegration');
client.addIntegration(feedbackIntegration());
} catch(error) {
// this can error, we need to handle this!
}
}
```
Closes https://github.com/getsentry/sentry-javascript/issues/10905

feat(browser): Add `lazyLoadIntegration` utility

---

.craft.yml
CHANGELOG.md

Fixes botched release: https://github.com/getsentry/publish/issues/3661

fix: Remove `@sentry/node-experimental` from craft config

---

packages/aws-serverless/src/index.ts
packages/browser/src/exports.ts
packages/bun/src/index.ts
packages/deno/src/index.ts
packages/google-cloud-serverless/src/index.ts
packages/node/src/index.ts
packages/remix/src/index.server.ts
packages/sveltekit/src/server/index.ts
packages/vercel-edge/src/index.ts

I was looking to bump the [docs to v8](https://github.com/getsentry/sentry-docs/pull/9628), but it seems like `spanToJSON` and `spanToTraceHeader` were missed in a few packages (including Next.js).

feat: Export `spanToJSON` and `spanToTraceHeader` from all relevant packages

---

packages/core/src/currentScopes.ts
packages/core/test/lib/scope.test.ts
packages/opentelemetry/test/asyncContextStrategy.test.ts
packages/vercel-edge/src/async.ts
packages/vercel-edge/test/async.test.ts

Also adds tests for this for core, vercel-edge and opentelemetry.
NOTE: In core, this does not do anything, as we cannot actually update the isolation scope in browser.

feat(core): Allow to pass scope to `withIsolationScope()`

---

dev-packages/node-integration-tests/suites/metrics/should-exit-forced.js
dev-packages/node-integration-tests/suites/metrics/should-exit.js
dev-packages/node-integration-tests/suites/metrics/test.ts
dev-packages/node-integration-tests/suites/tracing/metric-summaries/scenario.js
packages/core/src/metrics/aggregator.ts
packages/core/src/sessionflusher.ts

This backports https://github.com/getsentry/sentry-javascript/pull/11430 to v7

fix(core): [v7] unref timer to not block node exit

---

packages/remix/src/utils/instrumentServer.ts

Fixes: https://github.com/getsentry/sentry-javascript/issues/11105
Skips span creation for `OPTIONS` and `HEAD` requests in `wrapRequestHandler`, which apparently are the unwanted requests mentioned in #11105. We can also implement a more precise filtering but this seems to resolve it on my local test application.

feat(remix): Skip span creation for `OPTIONS` and `HEAD` requests.

---

packages/remix/src/utils/instrumentServer.ts

feat(remix): Skip span creation for `OPTIONS` and `HEAD` requests. [v7]

---

.github/dependabot.yml

These are deps we may want to keep more up to date than we usually do, so generating update PRs for them may be helpful.

build(ci): Run dependabot for opentelemetry dependencies

---

packages/types/src/breadcrumb.ts

When interacting with the Breadcrumd API, I had some trouble finding the correct documentation. I retrieved my changes for the previous [PR](https://github.com/getsentry/sentry-javascript/pull/11119) to make sure the JSDoc is updated with the actual doc.

docs(breadcrumbs): :label: add jsdoc for breadcrumbs

---

dev-packages/e2e-tests/test-applications/nextjs-14/tests/request-instrumentation.test.ts
dev-packages/e2e-tests/test-applications/nextjs-app-dir/package.json
dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/route-handlers.test.ts
packages/nextjs/package.json
packages/nextjs/src/common/wrapRouteHandlerWithSentry.ts
packages/nextjs/src/server/index.ts
packages/nextjs/src/server/requestIsolationScopeIntegration.ts
packages/opentelemetry/src/utils/mapStatus.ts

Next.js provides their own OTel http integration, which conflicts with ours
ref https://github.com/getsentry/sentry-javascript/pull/11016
added commit from this PR: https://github.com/getsentry/sentry-javascript/pull/11319

fix(nextjs): Remove Http integration from Next.js

---

.github/workflows/canary.yml
dev-packages/event-proxy-server/package.json

Fixes the Canary tests by ensuring we cache node modules and files in dev-packages as well.
In the debugging process, I also moved a few things around - e.g. the playwright dependency stuff now happens in CI, not in the build commands everywhere.

ci(canary): Fix canary tests

---

dev-packages/browser-integration-tests/suites/manual-client/skip-init-browser-extension/test.ts
dev-packages/browser-integration-tests/suites/manual-client/skip-init-chrome-extension/test.ts
packages/browser/src/sdk.ts
packages/browser/test/unit/sdk.test.ts

ref https://github.com/getsentry/sentry-docs/pull/9571

fix(browser-extension): Replace browser extension link

---

packages/node/src/integrations/http.ts
packages/node/src/integrations/node-fetch.ts
packages/opentelemetry/src/index.ts

Instead of exporting `_INTERNAL` here, it's OK IMHO to export this. The API is stable enough.

feat(opentelemetry): Export `getRequestSpanData`

---

packages/core/src/transports/base.ts
packages/types/src/datacategory.ts
packages/types/src/envelope.ts
packages/utils/src/envelope.ts
packages/utils/src/ratelimit.ts

`statsd` is the envelope item type and `metric_bucket` is the data category. I also changed some variable names to keep a better distinction.

fix(metrics): Map `statsd` to `metric_bucket`

---

dev-packages/e2e-tests/test-applications/sveltekit-2/test/errors.server.test.ts
dev-packages/e2e-tests/test-applications/sveltekit/test/errors.server.test.ts
packages/sveltekit/src/server/handle.ts

This PR updates the scope's `transactionName` in the `sentryHandle` instrumentation that's always invoked when a request is made to the SvelteKit server. 
For now, I opted to not set the transactionName to unknown route URLs by default (i.e. a request that doesn't match a known server endpoint/route). Users can opt into also handling unknown routes at which point we'll also set the transactionName for such routes. 
ref #10846

feat(sveltekit): Update scope transactionName when handling server-side request

---

dev-packages/e2e-tests/test-applications/node-hapi-app/src/app.js
dev-packages/e2e-tests/test-applications/node-hapi-app/tests/server.test.ts
dev-packages/node-integration-tests/suites/tracing/hapi/scenario.js
dev-packages/node-integration-tests/suites/tracing/hapi/test.ts
packages/node/src/integrations/tracing/hapi/index.ts

This PR updates the scope's `transactionName` in our Hapi error handler. Conveniently, we can access the parameterized route within our Hapi plugin, meaning we're not constrained by reading route info from a potential non-recording span. 
ref #10846

feat(hapi): Update scope `transactionName` when handling request

---

dev-packages/e2e-tests/test-applications/node-nestjs-app/src/app.controller.ts
dev-packages/e2e-tests/test-applications/node-nestjs-app/src/app.service.ts
dev-packages/e2e-tests/test-applications/node-nestjs-app/tests/errors.test.ts
dev-packages/node-integration-tests/suites/tracing/nestjs-errors-no-express/scenario.ts
dev-packages/node-integration-tests/suites/tracing/nestjs-errors-no-express/test.ts
dev-packages/node-integration-tests/suites/tracing/nestjs-errors-no-express/tsconfig.json
dev-packages/node-integration-tests/suites/tracing/nestjs-errors/scenario.ts
dev-packages/node-integration-tests/suites/tracing/nestjs-errors/test.ts
dev-packages/node-integration-tests/suites/tracing/nestjs-errors/tsconfig.json
dev-packages/node-integration-tests/suites/tracing/nestjs-no-express/scenario.ts
dev-packages/node-integration-tests/suites/tracing/nestjs-no-express/test.ts
dev-packages/node-integration-tests/suites/tracing/nestjs-no-express/tsconfig.json
packages/node/src/integrations/tracing/nest.ts

This PR adds scope transactionName updating to our NestJS instrumentation. Similarly to Hapi and Fastify, we can use a framework-native component, an Interceptor, to assign the parameterized route. 
The interesting part is that adding the interceptor _almost_  wouldn't have been necessary: NestJS is built on [top of express](https://github.com/nestjs/nest/tree/master/packages/core#description) and apparently also allows to swap out express with Fastify or other frameworks.  This causes our/Otel's express instrumentation to be initialized on app startup, already giving us a parameterized route via the express layer. 
However, there's the use case of users disabling the express integration in which case I'd argue, the NestJS integration should still set the transactionName. Also, …

feat(nestjs): Update scope transaction name with parameterized route

---

dev-packages/e2e-tests/test-applications/node-fastify-app/src/app.js
dev-packages/e2e-tests/test-applications/node-fastify-app/tests/errors.test.ts
dev-packages/e2e-tests/test-applications/node-fastify-app/tests/transactions.test.ts
packages/node/src/integrations/tracing/fastify.ts

This PR updates the isolation scope's `transactionName` ~whenever the `requestHook` Otel instrumentation hook is invoked and we have a recording span (non-recording spans don't have a attributes :( )~ 
Update: Changed the transactionName updating mechanism to adding another hook callback in our `setupFastifyErrorHandler` fastify plugin. This is better than accessing the otel span for two reasons:
1. We can always update the transactionName, not just when a span is sampled and recording
2. The `onRequest` hook is executed earlier in the lifecycle than the `preHandler` hook that Otel uses to trigger the `requestHook` callback.
Also, we now access the same fields to read the route name [as Otel](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/fe18e2fbb2a6535cb72f314fdb1550a3a4 …

feat(fastify): Update scope `transactionName` when handling request

---

dev-packages/e2e-tests/test-applications/node-koa-app/index.js
dev-packages/e2e-tests/test-applications/node-koa-app/tests/errors.test.ts
packages/node/src/integrations/tracing/koa.ts

This PR updates the current scope's `transactionName` in our Koa integration. Unfortunately, I didn't find a reliable way to get the parameterized route in our error handler/via `app.use` because similarly to Express, koa doesn't seem to expose this information before going through the actual route layers. A couple of stackoverflow posts suggest a way if potentially [obtaining a routename](https://stackoverflow.com/questions/53398808/how-to-get-the-path-of-a-route-inside-middleware-in-koa) via a private `ctx` variable but in my testing this didn't work. Seems like there are multiple versions of `koa-router`/`@koa/router` where some support this and others don't... 
Consequence: In case of a negative sampling decision for the span, we can't update the scope's transaction name which most …

feat(koa): Update scope `transactionName` when creating router span

---

packages/browser-utils/test/browser/metrics/index.test.ts
packages/browser-utils/test/browser/metrics/utils.test.ts
packages/bun/package.json
packages/bun/src/transports/index.ts
packages/core/src/asyncContext.ts
packages/core/src/constants.ts
packages/core/src/tracing/index.ts
packages/core/src/tracing/trace.ts
packages/core/test/lib/tracing/trace.test.ts
packages/nextjs/src/common/devErrorSymbolicationEventProcessor.ts
packages/node/src/transports/http.ts
packages/opentelemetry/src/asyncContextStrategy.ts
packages/opentelemetry/src/index.ts
packages/opentelemetry/src/utils/suppressTracing.ts
packages/opentelemetry/test/trace.test.ts

This implements a new `suppressTracing` method which can be used to ensure we do not send any spans inside of a callback.
Usage:
```js
await suppressTracing(() => {
// do not capture any spans for this fetch!
return fetch(...);
});
```
This also changes the behavior of starting child spans slightly to actually create `NonRecordingSpan` as child spans when not sampled (previously, we'd still create SentrySpans). I choose to continue to create proper spans for unsampled transactions because it makes things like picking name and stuff like this easier for the time being.

feat(core): Implement `suppressTracing`

---

packages/browser/src/client.ts
packages/core/src/tracing/trace.ts
packages/core/test/lib/tracing/trace.test.ts
packages/svelte/src/performance.ts
packages/svelte/test/performance.test.ts
packages/types/src/options.ts

You can opt out of this by setting `parentSpanIsAlwaysRootSpan=false` in your client options.
This means that in browser, any span will always be added to the active root span, not the active span. This way, we should be able to avoid problems with execution contexts etc.
Closes https://github.com/getsentry/sentry-javascript/issues/10944

feat(browser): Create spans as children of root span by default

---

packages/utils/src/ratelimit.ts
packages/utils/test/ratelimit.test.ts

closes https://github.com/getsentry/sentry-javascript/issues/11336

feat(ratelimits): Add metric buckets rate limit

---

MIGRATION.md
dev-packages/node-integration-tests/suites/public-api/OnUncaughtException/test.ts
packages/nextjs/src/server/index.ts
packages/nextjs/src/server/onUncaughtExceptionIntegration.ts
packages/node/src/integrations/onuncaughtexception.ts

Ref: https://github.com/getsentry/sentry-javascript/issues/1661
Ref: https://github.com/getsentry/sentry-javascript/issues/6146
This PR sets the default for the `exitEvenIfOtherHandlersAreRegistered` option of the `onUncaughtExceptionIntegration` to `false`. Effectively this means that going forward, by default, Sentry will not try to exit the process when there are other `onUncaughtException` handlers attached.
In the Next.js SDK we needed to override the option for this integration to `false`, so now it will be in line with the global default.

feat(node): Do not exit process by default when other `onUncaughtException` handlers are registered in `onUncaughtExceptionIntegration`

---

packages/core/src/hub.ts
packages/core/src/utils/isSentryRequestUrl.ts
packages/core/test/lib/utils/isSentryRequestUrl.test.ts
packages/integrations/test/reportingobserver.test.ts
packages/node-experimental/src/integrations/http.ts
packages/node-experimental/src/sdk/globals.ts
packages/node-experimental/src/sdk/hub.ts
packages/node-experimental/src/sdk/types.ts
packages/node/test/eventbuilders.test.ts
packages/opentelemetry-node/src/utils/captureExceptionForTimedEvent.ts
packages/opentelemetry-node/test/utils/captureExceptionForTimedEvent.test.ts
packages/opentelemetry/src/custom/transaction.ts
packages/opentelemetry/src/utils/captureExceptionForTimedEvent.ts
packages/opentelemetry/src/utils/contextData.ts
packages/opentelemetry/src/utils/spanData.ts
packages/opentelemetry/test/utils/captureExceptionForTimedEvent.test.ts
packages/profiling-node/src/hubextensions.ts
packages/profiling-node/src/integration.ts
packages/profiling-node/test/hubextensions.test.ts
packages/profiling-node/test/integration.test.ts
packages/tracing-internal/src/node/integrations/express.ts
packages/tracing-internal/src/node/integrations/utils/node-utils.ts
packages/types/src/hub.ts
packages/types/src/index.ts
packages/types/src/integration.ts
packages/utils/src/eventbuilder.ts
packages/utils/test/eventbuilder.test.ts

This PR deprecates the `Hub` interface as a continuation of #11528 where we deprecated the Hub class.
The difference here is that the interface will stay deprecated throughout v8 so that we can shim the infamous `getCurrentHub` API. Most other usages of the interface should already be removed in v8/`develop` 🤞  
ref #11482

feat(v7/types): Deprecate `Hub` interface

---

packages/core/src/metrics/aggregator.ts
packages/core/src/metrics/browser-aggregator.ts
packages/core/src/metrics/constants.ts
packages/core/src/metrics/utils.ts
packages/core/test/lib/metrics/utils.test.ts

Closes #11433
https://develop.sentry.dev/sdk/metrics/#normalization

feat(core): Update metric normalization

---

dev-packages/browser-integration-tests/suites/sessions/initial-scope/test.ts
dev-packages/browser-integration-tests/suites/sessions/start-session/test.ts
dev-packages/browser-integration-tests/suites/sessions/v7-hub-start-session/test.ts

This hopefully fixes these tests that randomly started failing 😬 
debugging this on CI, I saw that the second session envelope it sent was about discarding session events because sending them failed. So ensuring we don't drop the sessions should fix this, I think.

test(ci): Fix failing tests

---

packages/browser-utils/src/browser/browserTracingIntegration.ts

Forward port of https://github.com/getsentry/sentry-javascript/pull/10702

fix(tracing): Fixes latest route name and source not updating correctly

---

packages/core/src/index.ts
packages/core/src/span.ts
packages/types/src/datacategory.ts
packages/types/src/envelope.ts
packages/types/src/index.ts
packages/utils/src/envelope.ts

Adds span envelopes and datacategory. For use with standalone inp spans
Forward port of https://github.com/getsentry/sentry-javascript/pull/10706

feat(tracing): Adds span envelope and datacategory

---

packages/core/src/integrations/rewriteframes.ts
packages/core/test/lib/integrations/rewriteframes.test.ts

Fixes https://github.com/getsentry/sentry-javascript/issues/6423
Adds functionality on the browser for the `root` option.

feat(core): Add default behaviour for `rewriteFramesIntegration` in browser

---

packages/core/src/transports/base.ts
packages/types/src/datacategory.ts
packages/types/src/envelope.ts
packages/utils/src/envelope.ts
packages/utils/src/ratelimit.ts
packages/utils/test/ratelimit.test.ts

closes https://github.com/getsentry/sentry-javascript/issues/11336
on v7: https://github.com/getsentry/sentry-javascript/pull/11505 https://github.com/getsentry/sentry-javascript/pull/11506

feat(ratelimit): Add metrics rate limit

---

dev-packages/browser-integration-tests/suites/manual-client/browser-context/init.js
packages/astro/src/index.server.ts
packages/aws-serverless/src/index.ts
packages/browser/src/exports.ts
packages/bun/src/index.ts
packages/core/src/asyncContext.ts
packages/core/src/exports.ts
packages/core/src/getCurrentHubShim.ts
packages/core/src/hub.ts
packages/core/src/index.ts
packages/core/src/sdk.ts
packages/deno/src/index.ts
packages/google-cloud-serverless/src/index.ts
packages/node/src/index.ts
packages/opentelemetry/src/asyncContextStrategy.ts
packages/remix/src/index.server.ts
packages/replay-internal/test/unit/session/createSession.test.ts
packages/sveltekit/src/server/index.ts
packages/types/src/hub.ts
packages/types/src/index.ts
packages/vercel-edge/src/async.ts
packages/vercel-edge/src/index.ts

This PR removes top-level exports of the `Hub` class from all SDK packages. The only package that still exports it is core for now because we temporarily still need the class until we shimmed the return value of `getCurrentHub`. Decided to deprecate the class for now as well, to be aware of where we still use it.
Furthermore, this PR also deprecated the `Hub` interface. However, this interface will not be removed in v8 (prob v9) to keep support for `getCurrentHub` during the v8 life cycle. 
ref #11482

feat(core): Remove most Hub class exports

---

packages/core/src/index.ts

Just noticed we export this API from core but it's not used in packages outside of `@sentry/core` (anymore?). Let's remove it while we can.
ref #11482

feat(core): Remove `getGlobalHub` export

---

packages/core/src/index.ts
packages/replay-internal/test/unit/session/createSession.test.ts

This PR removes the last public export of the `Hub` class. Now that it's gone there are no more breaking changes (🤞). The class still remains in the package because it's still used internally for now but we can remove it (and shave off some well needed bytes) throught the v8 beta cycle.
actually thought this would be more work than just removing the export lol
ref #11482

feat(core): Remove `Hub` class export

---

.size-limit.js
dev-packages/browser-integration-tests/suites/tracing/request/fetch-with-no-sample-rate/init.js
dev-packages/browser-integration-tests/suites/tracing/request/fetch-with-no-sample-rate/subject.js
dev-packages/browser-integration-tests/suites/tracing/request/fetch-with-no-sample-rate/test.ts

As a result of our investigation into tracing behaviour for fetch requests without active spans, this PR adjusts/adds tests around checking that a `sentry-trace` header is attached to outgoing requests in v7 of the SDK. As we also discovered today, this unfortunately doesn't work as "advertised in the basic TwP case:
* [correct behaviour] `BrowserTracing` initialized; `tracesSamplerate` set: `sentry-trace` header is attached _without_ a sampled flag.
* [incorrect behaviour] `BrowserTracing` is initialized but no `tracesSampleRate`: We currently don't attach a `sentry-trace` header although we should.

test(V7/browser-integration-tests): Check for `sentry-trace` header in TwP

---

packages/nextjs/src/config/withSentryConfig.ts

Fixes https://github.com/getsentry/sentry-javascript/issues/11559
Multiple issues:
- order of matchers
- escaped regex

fix(nextjs/v7): Fix `tunnelRoute` matching logic for hybrid cloud

---

packages/nextjs/src/config/withSentryConfig.ts

Ref: https://github.com/getsentry/sentry-javascript/issues/11559
I'll add e2e tests in a follow-up

fix(nextjs): Fix `tunnelRoute` matching logic for hybrid cloud

---

dev-packages/node-integration-tests/suites/anr/indefinite.mjs
dev-packages/node-integration-tests/suites/anr/test.ts
packages/node/src/integrations/anr/worker.ts

When experimenting for #11525 I found that `Runtime.evaluate` only returns when the event loop becomes unblocked. This means that we are not sending ANR events if the event loop is blocked indefinitely.
This PR adds a timeout that sends the ANR event if we have not been able to evaluate the scope within 5 seconds.

fix(node): Send ANR events without scope if event loop blocked indefinitely

---

dev-packages/node-integration-tests/suites/express/span-isolationScope/server.ts
dev-packages/node-integration-tests/suites/express/span-isolationScope/test.ts

Adds a test to ensure isolation scope is correctly applied to express spans, and also that console.log is correctly instrumented.
We have related tests in E2E tests and in other places, but it doesn't hurt to have this explicitly here I guess...

test(node): Add test for console.log & isolation scope

---

packages/browser/src/sdk.ts
packages/core/src/asyncContext.ts
packages/core/src/getCurrentHubShim.ts
packages/core/src/hub.ts
packages/core/src/index.ts
packages/core/src/sdk.ts
packages/core/src/trpc.ts
packages/opentelemetry/src/asyncContextStrategy.ts
packages/vercel-edge/src/async.ts

This PR removes the `getCurrentHub` property from the `AsyncContextStrategy` interface and consequently also the property in the interface implementers.
There's still some stuff left to clean up but it is only internal anymore.
Hopefully the last breaking change in connection to #11482

feat(core): Remove `getCurrentHub` from `AsyncContextStrategy`

---

packages/node/test/integration/transactions.test.ts
packages/opentelemetry/src/spanExporter.ts
packages/opentelemetry/test/integration/transactions.test.ts

This is duplicated from the trace data, no need to send this anymore.

feat(opentelemetry): Remove `otel.attributes` in context

---

package.json
yarn.lock

We don't actually need them anymore, as we've updated stuff I guess. This also finally fixes the problem that yarn always seemed to do some work even with the lockfile "up to date".

build: Remove unnecessary yarn resolutions

---

dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/navigation/test.ts

builds on top of #11600 
Adds a test to ensure that errors thrown after a navigation transaction finished are still associated with he trace started from the navigation.

test(browser-integration-tests): Ensure error after navigation has navigation traceId

---

dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/navigation/test.ts
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/pageload/test.ts

Adds two tests to ensure errors thrown during pageload or navigations have the correct traceId.
(Admittedly, this scenario is pretty obvious and we probably test this in some capacity already but it makes a lot of sense to cover this behaviour in this test suite, too). 
ref https://github.com/getsentry/sentry-javascript/issues/11599

test(browser-integration-tests): Test that errors during pageload/navigation have correct trace id

---

dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/README.md
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/pageload-meta/template.html
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/pageload-meta/test.ts

This PR adds a couple of tests to our `trace-lifetime` integration test suite to test `<meta>` tag continued pageload traces. These differ from "normal" pageload traces in the sense that they should pick up and continue the trace from the service that added the meta tags to the HTML response. 
So in our suite:
- `trace-lifetime/pageload` - pageload is head of trace
- `trace-lifetime/pageload-meta` - pageload continues trace from server
ref #11599

test(browser-integration-tests): Add trace lifetime tests for `<meta>` tag pageload transactions

---

packages/tracing-internal/src/browser/backgroundtab.ts
packages/tracing-internal/src/browser/browserTracingIntegration.ts
packages/tracing-internal/src/browser/browsertracing.ts
packages/tracing-internal/src/browser/types.ts
packages/tracing-internal/src/browser/web-vitals/getLCP.ts
packages/tracing-internal/src/browser/web-vitals/lib/getVisibilityWatcher.ts
packages/tracing-internal/src/browser/web-vitals/lib/initMetric.ts
packages/tracing-internal/src/browser/web-vitals/lib/onHidden.ts

Relates to https://github.com/getsentry/sentry-javascript/issues/5289#issuecomment-2056479108
We technically support webworkers so we cannot assume that document API is available.

fix(browser/v7): Don't assume window.document is available

---

packages/browser-utils/src/metrics/types.ts
packages/browser-utils/src/metrics/web-vitals/getLCP.ts
packages/browser-utils/src/metrics/web-vitals/lib/getVisibilityWatcher.ts
packages/browser-utils/src/metrics/web-vitals/lib/initMetric.ts
packages/browser-utils/src/metrics/web-vitals/lib/onHidden.ts
packages/browser-utils/src/metrics/web-vitals/lib/whenActivated.ts
packages/browser-utils/src/metrics/web-vitals/onTTFB.ts
packages/browser/src/tracing/browserTracingIntegration.ts

Ref: https://github.com/getsentry/sentry-javascript/issues/5289#issuecomment-2056479108
We cannot assume window.document is available because we support web workers.

fix(browser): Don't assume window.document is available

---

dev-packages/node-integration-tests/suites/tracing/envelope-header/error-active-span-unsampled/scenario.ts
dev-packages/node-integration-tests/suites/tracing/envelope-header/error-active-span-unsampled/test.ts
dev-packages/node-integration-tests/suites/tracing/envelope-header/error-active-span/scenario.ts
dev-packages/node-integration-tests/suites/tracing/envelope-header/error-active-span/test.ts
dev-packages/node-integration-tests/suites/tracing/envelope-header/error/scenario.ts
dev-packages/node-integration-tests/suites/tracing/envelope-header/error/test.ts
dev-packages/node-integration-tests/suites/tracing/envelope-header/transaction-route/scenario.ts
dev-packages/node-integration-tests/suites/tracing/envelope-header/transaction-route/test.ts
dev-packages/node-integration-tests/suites/tracing/envelope-header/transaction-url/scenario.ts
dev-packages/node-integration-tests/suites/tracing/envelope-header/transaction-url/test.ts
dev-packages/node-integration-tests/suites/tracing/envelope-header/transaction/scenario.ts
dev-packages/node-integration-tests/suites/tracing/envelope-header/transaction/test.ts
dev-packages/node-integration-tests/utils/runner.ts
packages/opentelemetry/src/setupEventContextTrace.ts

This was not correctly set before when we had an active span - the `error-active-span` & `error-active-span-unsampled` scenarios failed before and had no `trace` set on the envelope headers.
The fix was to actually fix our `setupEventContextTrace` utility for OTEL, where we now just set the dsc on the event sdkProcessingMetadata, which is picked up when event processing. I also moved this to `preprocessEvent` to ensure this runs before other stuff.
This should fix https://github.com/getsentry/sentry-javascript-examples/pull/7/files#r1561220216 which @s1gr1d found in her example app. 🚀

fix(node): Ensure DSC is correctly set in envelope headers

---

packages/opentelemetry/src/sampler.ts

We now skip any OTEL spans that Next.js emits, unless we already have a parent span that was created elsewhere (e.g. by our auto instrumentation). This way, we should be able to ensure consistent root spans for all cases.

feat(nextjs): Skip OTEL root spans emitted by Next.js

---

packages/core/src/asyncContext/stackStrategy.ts
packages/core/src/sdk.ts

Added a comment for https://github.com/getsentry/sentry-javascript/pull/11630#discussion_r1567484029!

doc: Add clarifying comment for hub on ACS

---

packages/feedback/src/modal/components/DialogContainer.tsx

The timeout id wasn't getting reset to null after submission which was causing additional clicks on the feedback button to pop up the success message instead. Now, a click on the success message brings back the feedback button, which brings up the dialog when clicked.
Fixes [#418](https://github.com/getsentry/team-replay/issues/418)

fix(feedback): Fix timeout on feedback submission

---

packages/nextjs/src/client/index.ts
packages/nextjs/test/clientSdk.test.ts
packages/sveltekit/src/client/sdk.ts
packages/sveltekit/test/client/sdk.test.ts

Fixes https://github.com/getsentry/sentry-javascript/issues/11627

fix(v7): Ensure  next & sveltekit correctly handle `browserTracingIntegration`

---

dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/navigation/test.ts
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/pageload-meta/template.html
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/pageload-meta/test.ts
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/pageload/test.ts
packages/browser/src/tracing/browserTracingIntegration.ts
packages/browser/test/unit/tracing/browserTracingIntegration.test.ts

As spec'd out in #11599 and agreed upon in internal discussions, a trace should to stay consistent over the entire time span of one route. Therefore, when the initial pageload or navigation span ends, we update the scope's propagation context to keep span-specific attributes like the `sampled` decision and the dynamic sampling context on the scope's propagation context, even after the transaction has ended.
This ensures that the trace data is consistent for the entire duration of the route. Subsequent navigations will reset the propagation context (see #11377).
cc @cleptric 
ref #11599

feat(browser): Update `propagationContext` on `spanEnd` to keep trace consistent

---

dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/README.md
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/subject.js
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/tracing-without-performance/init.js
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/tracing-without-performance/template.html
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/tracing-without-performance/test.ts

Adds a couple of tests to cover the "Tracing Without Performance" use case where no spans will be created but we nevertheless attach tracing headers to outgoing requests and attach a trace id to errors. Also, we expect these traceIds to be different/new for each subsequent navigation
ref #11599

test(browser-integration-tests): Add trace lifetime tests in TwP scenario

---

dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/README.md
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/subject.js
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/tracing-without-performance/init.js
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/tracing-without-performance/template.html
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/tracing-without-performance/test.ts

For some reason, this commit (#11564) caused a conflict in our master->develop sync. Let's fix this by cherry picking it onto master.

test(browser-integration-tests): Add trace lifetime tests in TwP scenario (#11636)

---

.github/ISSUE_TEMPLATE/flaky.yml
.github/workflows/auto-release.yml
.github/workflows/build.yml
.github/workflows/canary.yml
.github/workflows/clear-cache.yml
.github/workflows/codeql-analysis.yml
.github/workflows/enforce-license-compliance.yml
.github/workflows/flaky-test-detector.yml
.github/workflows/gitflow-sync-develop.yml
.github/workflows/issue-package-label.yml
.github/workflows/release-size-info.yml
.github/workflows/release.yml
README.md

The list in https://github.com/getsentry/sentry-javascript/actions is a bit hard to parse, maybe streamlining this makes this easier...

ci: Streamline naming of CI workflows

---

dev-packages/browser-integration-tests/scripts/detectFlakyTests.ts

I checked in the last couple of PRs where added integration tests how long our flaky test detector usually runs. Seems like we average somewhere around 18 minutes. Which is generally fine but our target is 30mins runtime. The reason for the "short" runs is that we assume an average runtime of 3s per test. Which apparently is a bit too long (this actually surprised me). Let's try reduce it to 2s and see if we get closer. We can always revert if we overshoot the time budget in the future. 
More runs => less ❄️ 🤞

test(ci): Reduce flaky test detector assumed average test runtime

---

packages/browser/src/tracing/browserTracingIntegration.ts
packages/browser/test/unit/tracing/browserTracingIntegration.test.ts
packages/utils/src/tracing.ts

As discussed with @lforst yesterday, we can streamline our pageload span creation logic now that we actually want to keep the propagation context on the scope after the transaction finished (see #11599). Previously, we'd fork a new scope for the pageload span but IMHO (and according to all our tests) this is no longer necessary. 
ref #11599

ref(browser): Streamline pageload span creation and scope handling

---

dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/navigation/test.ts
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/pageload-meta/test.ts
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/pageload/test.ts
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/tracing-without-performance/test.ts
dev-packages/browser-integration-tests/utils/helpers.ts

This PR adds checks for the contents of the `trace` envelope headers in our new `trace-lifetime` test suite. The purpose of these checks is to ensure that we not only propagate and send correct trace data in request headers and Sentry events (trace context) but also in the `trace` envelope header. 
Side note: This makes the tests notably longer but IMO its worth to have deep checks here because we can ensure that we always send the right data everywhere. Also, I had to write a "new" request parser to get both, events and the envelope headers. 
ref #11599

test(browser-integration-tests): Check `trace` envelope headers in trace lifetime tests

---

packages/opentelemetry/src/sampler.ts

This hopefully fixes this, not sure how to write a test for this (?) but we can add one later as well...

fix(nextjs): Do not sample next spans if they have remote parent

---

dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/navigation/test.ts
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/pageload-meta/test.ts
dev-packages/browser-integration-tests/suites/tracing/trace-lifetime/pageload/test.ts

More clearly shows the current difference in `event.contexts.trace` for error events, depending on if they were sent during an active span or afterwards.

test(browser-integration-tests): Check for full equality in error event trace context

---

packages/opentelemetry/src/custom/hub.ts
packages/opentelemetry/src/index.ts

Now that https://github.com/getsentry/sentry-javascript/pull/11630 was merged in, we can remove `setupGlobalHub`.

feat(opentelemetry): Remove setupGlobalHub

---

packages/astro/src/index.server.ts
packages/aws-serverless/src/index.ts
packages/bun/src/index.ts
packages/google-cloud-serverless/src/index.ts
packages/node/src/index.ts
packages/node/src/integrations/http.ts
packages/node/src/integrations/node-fetch.ts
packages/node/src/integrations/tracing/connect.ts
packages/node/src/integrations/tracing/express.ts
packages/node/src/integrations/tracing/fastify.ts
packages/node/src/integrations/tracing/graphql.ts
packages/node/src/integrations/tracing/hapi/index.ts
packages/node/src/integrations/tracing/koa.ts
packages/node/src/integrations/tracing/mongo.ts
packages/node/src/integrations/tracing/mongoose.ts
packages/node/src/integrations/tracing/mysql.ts
packages/node/src/integrations/tracing/mysql2.ts
packages/node/src/integrations/tracing/nest.ts
packages/node/src/integrations/tracing/postgres.ts
packages/node/src/integrations/tracing/prisma.ts
packages/opentelemetry/package.json
packages/opentelemetry/src/index.ts
packages/opentelemetry/src/instrumentation.ts
packages/remix/src/index.server.ts
packages/sveltekit/src/server/index.ts

Adds `addOpenTelemetryInstrumentation`, a helper that can be used to dynamically register OpenTelemetry instrumentation. This helps unblock work on https://github.com/getsentry/sentry-javascript/pull/11548
The helper itself is quite small:
```ts
export function addOpenTelemetryInstrumentation(
instrumentation: InstrumentationOption | InstrumentationOption[],
): void {
registerInstrumentations({
instrumentations: Array.isArray(instrumentation) ? instrumentation : [instrumentation],
});
}
```
and is designed to accept either a standalone instrumentation or an array of instrumentations. This gives users a ton of flexibility into usage!

feat(opentelemetry): Add addOpenTelemetryInstrumentation

---

packages/core/src/getCurrentHubShim.ts

Instead of using `this.endSession`, directly use `endSession`.

ref(core): Directly use endSession

---

.size-limit.js
dev-packages/browser-integration-tests/suites/tracing/request/fetch-relative-url/init.js
dev-packages/browser-integration-tests/suites/tracing/request/fetch-relative-url/subject.js
dev-packages/browser-integration-tests/suites/tracing/request/fetch-relative-url/test.ts
dev-packages/browser-integration-tests/suites/tracing/request/fetch/test.ts
dev-packages/browser-integration-tests/suites/tracing/request/xhr-relative-url/init.js
dev-packages/browser-integration-tests/suites/tracing/request/xhr-relative-url/subject.js
dev-packages/browser-integration-tests/suites/tracing/request/xhr-relative-url/test.ts
dev-packages/browser-integration-tests/suites/tracing/request/xhr/test.ts
dev-packages/e2e-tests/test-applications/nextjs-app-dir/tests/middleware.test.ts
packages/nextjs/test/integration/test/client/tracingFetch.test.ts
packages/tracing-internal/src/browser/request.ts
packages/tracing-internal/src/common/fetch.ts

Backport of https://github.com/getsentry/sentry-javascript/pull/11634 to v7

feat(core/v7): Add `server.address` to browser `http.client` spans

---

.size-limit.js
packages/nextjs/package.json
packages/nextjs/src/server/httpIntegration.ts
packages/nextjs/src/server/index.ts
packages/node/src/integrations/http.ts

Until https://github.com/open-telemetry/opentelemetry-js/pull/4643 is merged & released, we try to get around next & http instrumentation limitations.

feat(nextjs): Instrument outgoing http requests

---

packages/nextjs/src/server/index.ts

Since we are filtering removing Next.js spans by default and we have suppressTracing, we do not need to be manually filtering out spans anymore.

ref(nextjs): Remove unnecessary logic to filter symbolification/sentry spans

---

packages/nextjs/package.json
yarn.lock

This dependency is unneeded and clashes with the other ones we have installed.

deps(nextjs): Remove unnecessary and faulty `@opentelemetry/api` dependency from Next.js package
